### PR TITLE
adding fix for aws org feature_set update issue from #15462

### LINKED ISSUE #15462: aws_organizations_organization feature_set change should not force new resource
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform version: 0.13.1
AWS Provider version: 3.9.0

### Affected Resource(s)

* `aws_organizations_organization`

### Terraform Configuration Files

When updating the following resource from the "before" to "after", terraform  the following `org` resource from:

#### Before
```hcl
resource "aws_organizations_organization" "org" {
  feature_set = "CONSOLIDATED_BILLING"
}
```

#### After
```hcl
resource "aws_organizations_organization" "org" {
  aws_service_access_principals = [
    "cloudtrail.amazonaws.com",
  ]

  feature_set = "ALL"
}
```

### Debug Output

```
-/+ aws_organizations_organization.org (new resource required)
      id:                                       "o-example" => <computed> (forces new resource)
      accounts.#:                               "2" => <computed>
      arn:                                      "arn:aws:organizations::123456789012:organization/o-example" => <computed>
      aws_service_access_principals.#:          "0" => "1"
      aws_service_access_principals.123456789: "" => "cloudtrail.amazonaws.com"
      feature_set:                              "CONSOLIDATED_BILLING" => "ALL" (forces new resource)
      master_account_arn:                       "arn:aws:organizations::123456789012:account/o-example/123456789012" => <computed>
      master_account_email:                     "email@foobar.com" => <computed>
      master_account_id:                        "123456789012" => <computed>
      non_master_accounts.#:                    "1" => <computed>
      roots.#:                                  "1" => <computed>
```

### Expected Behavior

The change to [`feature_set`](https://github.com/terraform-providers/terraform-provider-aws/blob/f8ba9a2c291dc809b220033c8050f2cea8d9a016/aws/resource_aws_organizations_organization.go#L157) does not force a new resource, which would generate a new Org ID. The feature set can be changed in Console without creating a new org ID, and I was informed by AWS that this should not need to generate a new org ID.

### Actual Behavior

A new resource if forced when `feature_set` is changed from `CONSOLIDATED_BILLING` to `ALL`. This should only force a new resource if going from `ALL` to `CONSOLIDATED_BILLING`, according to this note on this [page](https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_org_support-all-features.html):

> The migration from consolidated billing features to all features is one-way. You can't switch an organization with all features enabled back to consolidated billing features only.

### Steps to Reproduce

1. `terraform apply` using the config above

### References

N/A

### PR DESCRIPTION
**Pull request by ryandeivert**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #15462

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
NONE
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSOrganizations_serial/Organization/FeatureSet'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSOrganizations_serial/Organization/FeatureSet -timeout 120m
=== RUN   TestAccAWSOrganizations_serial
=== RUN   TestAccAWSOrganizations_serial/OrganizationalUnits
=== RUN   TestAccAWSOrganizations_serial/Organization
=== RUN   TestAccAWSOrganizations_serial/Organization/FeatureSet_Basic
=== RUN   TestAccAWSOrganizations_serial/Organization/FeatureSet_Update
    resource_aws_organizations_organization_test.go:413: [INFO] Got non-empty plan, as expected
    resource_aws_organizations_organization_test.go:413: [INFO] Got non-empty plan, as expected
=== RUN   TestAccAWSOrganizations_serial/Organization/FeatureSet_ForcesNew
=== RUN   TestAccAWSOrganizations_serial/OrganizationalUnit
--- PASS: TestAccAWSOrganizations_serial (141.11s)
    --- PASS: TestAccAWSOrganizations_serial/OrganizationalUnits (0.00s)
    --- PASS: TestAccAWSOrganizations_serial/Organization (141.11s)
        --- PASS: TestAccAWSOrganizations_serial/Organization/FeatureSet_Basic (27.37s)
        --- PASS: TestAccAWSOrganizations_serial/Organization/FeatureSet_Update (52.12s)
        --- PASS: TestAccAWSOrganizations_serial/Organization/FeatureSet_ForcesNew (61.62s)
    --- PASS: TestAccAWSOrganizations_serial/OrganizationalUnit (0.00s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	142.790s
```

### CODE REVIEW

**Review by philnichol — COMMENTED** [review]
@ryandeivert I'm not a maintainer so feel free to ignore, but looks like feature_set changes aren't yet implemented in the Read/Update functions, so this doesn't change the infra in AWS. Might need something like (I'm quite new to TF and Go so apologies if the below examples are garbage):
```hcl
// somewhere within the Read function
if err := d.Set("feature_set", org.Organization.FeatureSet); err != nil {
	return fmt.Errorf("error setting feature_set: %s", err)
}
```

```hcl
// somewhere within the Update function
if d.HasChange("feature_set") {
	o, n := d.GetChange("feature_set")
	input := &organizations.EnableAllFeaturesInput{}
	if _, err := conn.EnableAllFeatures(input); err != nil {
		return fmt.Errorf("error changing feature_set from (%s) to (%s): %s", o, n, err)
	}
}
```
Also may be worth updating docs, since when you enable "All" you still have to manually go into the AWS console and click "Finalize" once all accounts have accepted the change. Until you Finalize it's left in a state where you can still revert things.

**Comment by ryandeivert** [comment]
good catch @philnichol - I added some updates and fixed a different bug in the current tests. docs are also updated now

**Comment by philnichol** [comment]
@ryandeivert great stuff!

**Comment by ryandeivert** [comment]
hi @anGie44 I noticed you updated the issue associated with this. is there any chance you can provide an update here?

File: aws/resource_aws_organizations_organization.go [hunk 1]
```diff
@@ -400,6 +400,12 @@ func resourceAwsOrganizationsOrganizationUpdate(d *schema.ResourceData, meta int
 		}
 	}
 
+	if d.HasChange("feature_set") {
+		if _, err := conn.EnableAllFeatures(&organizations.EnableAllFeaturesInput{}); err != nil {
+			return fmt.Errorf("error changing feature_set to ALL")
```
Comment (anGie44) [inline aws/resource_aws_organizations_organization.go:405]: small change here: we should also return the error received with the organization id e.g.
```suggestion
			return fmt.Errorf("error enabling all features in Organization (%s): %w", d.Id(), err)
```

File: aws/resource_aws_organizations_organization_test.go [hunk 2]
```diff
@@ -354,3 +354,91 @@ func testFlattenOrganizationsRootPolicyTypes(t *testing.T, index int, result []m
...
+func testAccAwsOrganizationsOrganizationRecreated(t *testing.T, before, after *organizations.Organization) resource.TestCheckFunc {
+	return func(s *terraform.State) error {
+		if *before.Id == *after.Id {
+			t.Fatalf("Expected change to Org ID value, but both were %v", *before.Id)
+		}
+		return nil
+	}
+}
+
+func testAccAwsOrganizationsOrganization_FeatureSetForcesNew(t *testing.T) {
```
Comment (anGie44) [inline aws/resource_aws_organizations_organization_test.go:367]: small nitpick here: it would be helpful to keep these new tests (ForcesNew, Update) close to the existing `FeatureSet` test above

File: aws/resource_aws_organizations_organization_test.go [hunk 3]
```diff
@@ -354,3 +354,91 @@ func testFlattenOrganizationsRootPolicyTypes(t *testing.T, index int, result []m
 		}
 	}
 }
+
+func testAccAwsOrganizationsOrganizationRecreated(t *testing.T, before, after *organizations.Organization) resource.TestCheckFunc {
+	return func(s *terraform.State) error {
+		if *before.Id == *after.Id {
```
Comment (anGie44) [inline aws/resource_aws_organizations_organization_test.go:360]: Nit: we should unwrap these with the AWS Go SDK's method `aws.StringValue()` to prevent any unwanted panics

File: aws/resource_aws_organizations_organization_test.go [hunk 4]
```diff
@@ -354,3 +354,91 @@ func testFlattenOrganizationsRootPolicyTypes(t *testing.T, index int, result []m
...
+			t.Fatalf("Expected change to Org ID value, but both were %v", *before.Id)
```
Comment (anGie44) [inline aws/resource_aws_organizations_organization_test.go:361]:
```suggestion
			return fmt.Errorf("Organization (%s) not recreated", aws.StringValue(before.Id))
```

File: aws/resource_aws_organizations_organization_test.go [hunk 5]
```diff
@@ -354,3 +354,91 @@ func testFlattenOrganizationsRootPolicyTypes(t *testing.T, index int, result []m
...
+			},
+		},
+	})
+}
+
+func testAccAwsOrganizationsOrganizationNotRecreated(t *testing.T, before, after *organizations.Organization) resource.TestCheckFunc {
+	return func(s *terraform.State) error {
+		if *before.Id != *after.Id {
+			t.Fatal("Did not expect change to Org ID value")
+		}
```
Comment (anGie44) [inline aws/resource_aws_organizations_organization_test.go:404]: similar nit as above:

```suggestion
		if aws.StringValue(before.Id) != aws.StringValue(after.Id) {
			return fmt.Errorf("Organization (%s) recreated", aws.StringValue(before.Id))
		}
```

**Review by anGie44 — CHANGES_REQUESTED** [review]
Hi @ryandeivert , thank you for this PR and your patience! Overall changes look great just some small changes needed.

**Comment by ryandeivert** [comment]
hi @anGie44 - thank you for the review! I believe I have addressed all of your feedback now

**Review by anGie44 — APPROVED** [review]
Changes LGTM 🚀 Thanks again @ryandeivert @philnichol ! 

Output of acceptance tests:
```
--- PASS: TestFlattenOrganizationsRoots (0.00s)
--- PASS: TestAccAWSOrganizations_serial (1103.64s)
    --- PASS: TestAccAWSOrganizations_serial/Organization (217.24s)
        --- PASS: TestAccAWSOrganizations_serial/Organization/FeatureSet_ForcesNew (26.15s)
        --- PASS: TestAccAWSOrganizations_serial/Organization/DataSource (25.22s)
        --- PASS: TestAccAWSOrganizations_serial/Organization/basic (12.52s)
        --- PASS: TestAccAWSOrganizations_serial/Organization/AwsServiceAccessPrincipals (30.70s)
        --- PASS: TestAccAWSOrganizations_serial/Organization/EnabledPolicyTypes (90.92s)
        --- PASS: TestAccAWSOrganizations_serial/Organization/FeatureSet_Basic (11.43s)
        --- PASS: TestAccAWSOrganizations_serial/Organization/FeatureSet_Update (20.30s)
    --- PASS: TestAccAWSOrganizations_serial/Account (0.00s)
        --- SKIP: TestAccAWSOrganizations_serial/Account/basic (0.00s)
        --- SKIP: TestAccAWSOrganizations_serial/Account/ParentId (0.00s)
        --- SKIP: TestAccAWSOrganizations_serial/Account/Tags (0.00s)
    --- PASS: TestAccAWSOrganizations_serial/OrganizationalUnit (38.24s)
        --- PASS: TestAccAWSOrganizations_serial/OrganizationalUnit/basic (14.78s)
        --- PASS: TestAccAWSOrganizations_serial/OrganizationalUnit/Name (23.45s)
    --- PASS: TestAccAWSOrganizations_serial/OrganizationalUnits (0.00s)
        --- PASS: TestAccAWSOrganizations_serial/OrganizationalUnits/DataSource (13.49s)
    --- PASS: TestAccAWSOrganizations_serial/Policy (764.26s)
        --- PASS: TestAccAWSOrganizations_serial/Policy/Description (24.70s)
        --- PASS: TestAccAWSOrganizations_serial/Policy/Tags (321.10s)
        --- PASS: TestAccAWSOrganizations_serial/Policy/Type_SCP (296.24s)
        --- PASS: TestAccAWSOrganizations_serial/Policy/Type_Tag (13.83s)
        --- PASS: TestAccAWSOrganizations_serial/Policy/basic (25.28s)
        --- PASS: TestAccAWSOrganizations_serial/Policy/concurrent (25.83s)
        --- PASS: TestAccAWSOrganizations_serial/Policy/disappears (13.14s)
        --- PASS: TestAccAWSOrganizations_serial/Policy/Type_AI_OPT_OUT (15.99s)
        --- PASS: TestAccAWSOrganizations_serial/Policy/Type_Backup (13.66s)
        --- PASS: TestAccAWSOrganizations_serial/Policy/ImportAwsManagedPolicy (14.49s)
    --- PASS: TestAccAWSOrganizations_serial/PolicyAttachment (70.41s)
        --- PASS: TestAccAWSOrganizations_serial/PolicyAttachment/OrganizationalUnit (19.30s)
        --- PASS: TestAccAWSOrganizations_serial/PolicyAttachment/Root (18.89s)
        --- PASS: TestAccAWSOrganizations_serial/PolicyAttachment/Account (32.22s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	1106.033s
```
