### PR TITLE
Prevent panic from nil SES active receipt rule set

### LINKED ISSUE #26936: data_source/aws_ses_active_receipt_rule_set: Panic when no SES Active Receipt Rule Set exists
### Terraform Core Version

1.1.6

### AWS Provider Version

4.31.0

### Affected Resource(s)

Error: Plugin did not respond
│ 
│   with data.aws_vpc.vpc,
│   on datasources.tf line 12, in data "aws_vpc" "vpc":
│   12: data "aws_vpc" "vpc" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain
│ more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with data.aws_ses_active_receipt_rule_set.active_receipt_rule_set,
│   on ses.tf line 1, in data "aws_ses_active_receipt_rule_set" "active_receipt_rule_set":
│    1: data "aws_ses_active_receipt_rule_set" "active_receipt_rule_set" {}
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain
│ more details.

### Expected Behavior

Expected Terraform plan to succeed

### Actual Behavior

AWS provider crashed

### Relevant Error/Panic Output Snippet

```shell
Error: Plugin did not respond
│ 
│   with data.aws_vpc.vpc,
│   on datasources.tf line 12, in data "aws_vpc" "vpc":
│   12: data "aws_vpc" "vpc" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain
│ more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with data.aws_ses_active_receipt_rule_set.active_receipt_rule_set,
│   on ses.tf line 1, in data "aws_ses_active_receipt_rule_set" "active_receipt_rule_set":
│    1: data "aws_ses_active_receipt_rule_set" "active_receipt_rule_set" {}
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain
│ more details.
╵
╷
│ Warning: Value for undeclared variable
│ 
│ The root module does not declare a variable named
│ "infrastructure_team_email" but a value was found in file
│ "/build/406320440205/account.tfvars". If you meant to use this value, add a
│ "variable" block to the configuration.
│ 
│ To silence these warnings, use TF_VAR_... environment variables to provide
│ certain "global" settings to all configurations in your organization. To
│ reduce the verbosity of these warnings, use the -compact-warnings option.
╵
╷
│ Warning: Values for undeclared variables
│ 
│ In addition to the other similar warnings shown, 3 other variable(s)
│ defined without being declared.
╵

Stack trace from the terraform-provider-aws_v4.31.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x742add8]

goroutine 356 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/ses.dataSourceActiveReceiptRuleSetRead(0x0?, {0x8de53a0?, 0xc0005e0000})
	github.com/hashicorp/terraform-provider-aws/internal/service/ses/active_receipt_rule_set_data_source.go:39 +0xb8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xaeef8c0?, {0xaeef8c0?, 0xc0020d18f0?}, 0xd?, {0x8de53a0?, 0xc0005e0000?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.22.0/helper/schema/resource.go:712 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc0007fd6c0, {0xaeef8c0, 0xc0020d18f0}, 0xc0032fd100, {0x8de53a0, 0xc0005e0000})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.22.0/helper/schema/resource.go:943 +0x145
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc000121668, {0xaeef8c0?, 0xc0020d17d0?}, 0xc00341e920)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.22.0/helper/schema/grpc_provider.go:1179 +0x38f
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ReadDataSource({0xc001ec14a0, 0xc001ec1500, {0xc001eab8e0, 0x2, 0x2}, 0xc001ec14d0, 0xc0008b7a20, 0xc0018ae090, 0xc001ec1530}, {0xaeef8c0, ...}, ...)
	github.com/hashicorp/terraform-plugin-mux@v0.7.0/tf5muxserver/mux_server_ReadDataSource.go:27 +0x142
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc002d065a0, {0xaeef8c0?, 0xc0020d0fc0?}, 0xc0022c99a0)
	github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:658 +0x3ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0x9e78960?, 0xc002d065a0}, {0xaeef8c0, 0xc0020d0fc0}, 0xc00341d8f0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.****************************************_grpc.pb.go:421 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc002d243c0, {0xaef5160, 0xc002ccd1e0}, 0xc003102c60, 0xc001fafd10, 0x10603dd0, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1295 +0xb0b
google.golang.org/grpc.(*Server).handleStream(0xc002d243c0, {0xaef5160, 0xc002ccd1e0}, 0xc003102c60, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1636 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-aws_v4.31.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

time=2022-09-22T13:52:39Z level=error msg=1 error occurred:
	* exit status 1
```

### Terraform Configuration Files

```terraform
data "aws_ses_active_receipt_rule_set" "active_receipt_rule_set" {}

data "aws_vpc" "vpc" {
  tags = {
    app-id = var.app_id
  }
}
```

var.app_id = 209486 which does exist in the specified region (us-west-2)

There is **no** active_receipt_rule_set, but I would expect the data source to complain, but not crash.

### Steps to Reproduce

Running a `terraform plan` causes the stack trace above.

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

This is occurring in our production AWS account, but does run in our non-production AWS account. I feel like the problem is the missing active_receipt_rule_set and for some reason that's causing a crash instead of a "not found"

### References

_No response_

### Would you like to implement a fix?

_No response_

### PR DESCRIPTION
**Pull request by jar-b**
### Description
Handles cases where there is no SES receipt rule set as active. An empty result error is now returned in this scenario:

```
data.aws_ses_active_receipt_rule_set.active_receipt_rule_set: Reading...
╷
│ Error: empty result
│
│   with data.aws_ses_active_receipt_rule_set.active_receipt_rule_set,
│   on main.tf line 15, in data "aws_ses_active_receipt_rule_set" "active_receipt_rule_set":
│   15: data "aws_ses_active_receipt_rule_set" "active_receipt_rule_set" {}
│
╵
```

### Relations
Closes #26936

### Output from Acceptance Testing

```console
$ make testacc TESTS='TestAccSESActiveReceiptRuleSet_serial' PKG=ses
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ses/... -v -count 1 -parallel 20 -run='TestAccSESActiveReceiptRuleSet_serial'  -timeout 180m
=== RUN   TestAccSESActiveReceiptRuleSet_serial
=== RUN   TestAccSESActiveReceiptRuleSet_serial/Resource
=== RUN   TestAccSESActiveReceiptRuleSet_serial/Resource/disappears
=== RUN   TestAccSESActiveReceiptRuleSet_serial/Resource/basic
=== RUN   TestAccSESActiveReceiptRuleSet_serial/DataSource
=== RUN   TestAccSESActiveReceiptRuleSet_serial/DataSource/basic
=== RUN   TestAccSESActiveReceiptRuleSet_serial/DataSource/noActiveRuleSet
--- PASS: TestAccSESActiveReceiptRuleSet_serial (45.07s)
    --- PASS: TestAccSESActiveReceiptRuleSet_serial/Resource (28.15s)
        --- PASS: TestAccSESActiveReceiptRuleSet_serial/Resource/disappears (14.75s)
        --- PASS: TestAccSESActiveReceiptRuleSet_serial/Resource/basic (13.40s)
    --- PASS: TestAccSESActiveReceiptRuleSet_serial/DataSource (16.92s)
        --- PASS: TestAccSESActiveReceiptRuleSet_serial/DataSource/basic (14.81s)
        --- PASS: TestAccSESActiveReceiptRuleSet_serial/DataSource/noActiveRuleSet (2.11s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ses        47.569s
```

### CODE REVIEW

File: internal/service/ses/active_receipt_rule_set_data_source_test.go [hunk 1]
```diff
@@ -50,3 +77,34 @@ data "aws_ses_active_receipt_rule_set" "test" {
...
+	if output == nil || output.Metadata == nil {
+		return
+	}
+	if err != nil {
+		t.Fatalf("unexpected PreCheck error: %s", err)
+	}
+
+	_, err = conn.SetActiveReceiptRuleSet(&ses.SetActiveReceiptRuleSetInput{
+		RuleSetName: nil,
+	})
```
Comment (jar-b) [inline internal/service/ses/active_receipt_rule_set_data_source_test.go:103]: Passing a null `RuleSetName` is how the AWS docs suggest removing an active receipt rule set:
https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ses#Client.SetActiveReceiptRuleSet

**Comment by johnsonaj** [comment]
```console
$ make testacc TESTS='TestAccSESActiveReceiptRuleSet_serial' PKG=ses

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ses/... -v -count 1 -parallel 20 -run='TestAccSESActiveReceiptRuleSet_serial'  -timeout 180m
=== RUN   TestAccSESActiveReceiptRuleSet_serial
=== RUN   TestAccSESActiveReceiptRuleSet_serial/Resource
=== RUN   TestAccSESActiveReceiptRuleSet_serial/Resource/basic
=== RUN   TestAccSESActiveReceiptRuleSet_serial/Resource/disappears
=== RUN   TestAccSESActiveReceiptRuleSet_serial/DataSource
=== RUN   TestAccSESActiveReceiptRuleSet_serial/DataSource/basic
=== RUN   TestAccSESActiveReceiptRuleSet_serial/DataSource/noActiveRuleSet
--- PASS: TestAccSESActiveReceiptRuleSet_serial (68.47s)
    --- PASS: TestAccSESActiveReceiptRuleSet_serial/Resource (23.33s)
        --- PASS: TestAccSESActiveReceiptRuleSet_serial/Resource/basic (12.35s)
        --- PASS: TestAccSESActiveReceiptRuleSet_serial/Resource/disappears (10.98s)
    --- PASS: TestAccSESActiveReceiptRuleSet_serial/DataSource (45.14s)
        --- PASS: TestAccSESActiveReceiptRuleSet_serial/DataSource/basic (43.28s)
        --- PASS: TestAccSESActiveReceiptRuleSet_serial/DataSource/noActiveRuleSet (1.86s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ses	71.256s
```

**Review by johnsonaj — APPROVED** [review]
LGTM! 🚀
