### PR TITLE
Remove readonly properties from DMS ReplicationTaskSettings

### LINKED ISSUE #1513: aws_dms_replication_task replication_task_settings always reports as needing modification
### Terraform Version
Terraform v0.10.2

### Affected Resource(s)
- aws_dms_replication_task

### Terraform Configuration Files
```hcl
resource "aws_dms_replication_task" "main" {
  migration_type            = "${var.migration_type}"
  replication_instance_arn  = "${var.replication_instance_arn}"
  replication_task_id       = "${var.database_name}"
  replication_task_settings = "${trimspace(file("settings/settings.json"))}"
  source_endpoint_arn       = "${aws_dms_endpoint.source.endpoint_arn}"
  table_mappings            = "${var.table_mappings}"
  target_endpoint_arn       = "${var.endpoint_arn}"
}
```

### Expected Behavior
After running terraform apply, a subsequent run of terraform plan should indicate no changes needed.

### Actual Behavior
The plan continually requires modifications as seen bellow. It appears that the settings from my terraform project are compared against the full set of properties with default values pulled from AWS. Ideally, you should be able to set only the properties that differ from the default.

``` 
~ aws_dms_replication_task.main
      replication_task_settings: "{\"TargetMetadata\":{\"TargetSchema\":\"\",\"SupportLobs\":true,\"FullLobMode\":false,\"LobChunkSize\":64,\"LimitedSizeLobMode\":true,\"LobMaxSize\":32,\"LoadMaxFileSize\":0,\"ParallelLoadThreads\":0,\"ParallelLoadBufferSize\":0,\"BatchApplyEnabled\":true},\"FullLoadSettings\":{\"TargetTablePrepMode\":\"DROP_AND_CREATE\",\"CreatePkAfterFullLoad\":false,\"StopTaskCachedChangesApplied\":false,\"StopTaskCachedChangesNotApplied\":false,\"MaxFullLoadSubTasks\":8,\"TransactionConsistencyTimeout\":600,\"CommitRate\":10000},\"Logging\":{\"EnableLogging\":true,\"LogComponents\":[{\"Id\":\"SOURCE_UNLOAD\",\"Severity\":\"LOGGER_SEVERITY_DEFAULT\"},{\"Id\":\"TARGET_LOAD\",\"Severity\":\"LOGGER_SEVERITY_DEFAULT\"},{\"Id\":\"SOURCE_CAPTURE\",\"Severity\":\"LOGGER_SEVERITY_DEFAULT\"},{\"Id\":\"TARGET_APPLY\",\"Severity\":\"LOGGER_SEVERITY_INFO\"},{\"Id\":\"TASK_MANAGER\",\"Severity\":\"LOGGER_SEVERITY_DEBUG\"}],\"CloudWatchLogGroup\":\"dms-tasks-bi-replication\",\"CloudWatchLogStream\":\"dms-task-5G74HSCGSNESXL47RZBDASB7Y4\"},\"ControlTablesSettings\":{\"historyTimeslotInMinutes\":5,\"ControlSchema\":\"\",\"HistoryTimeslotInMinutes\":5,\"HistoryTableEnabled\":false,\"SuspendedTablesTableEnabled\":false,\"StatusTableEnabled\":false},\"StreamBufferSettings\":{\"StreamBufferCount\":3,\"StreamBufferSizeInMB\":8,\"CtrlStreamBufferSizeInMB\":5},\"ChangeProcessingDdlHandlingPolicy\":{\"HandleSourceTableDropped\":false,\"HandleSourceTableTruncated\":false,\"HandleSourceTableAltered\":true},\"ErrorBehavior\":{\"DataErrorPolicy\":\"LOG_ERROR\",\"DataTruncationErrorPolicy\":\"LOG_ERROR\",\"DataErrorEscalationPolicy\":\"SUSPEND_TABLE\",\"DataErrorEscalationCount\":50,\"TableErrorPolicy\":\"SUSPEND_TABLE\",\"TableErrorEscalationPolicy\":\"STOP_TASK\",\"TableErrorEscalationCount\":50,\"RecoverableErrorCount\":0,\"RecoverableErrorInterval\":5,\"RecoverableErrorThrottling\":true,\"RecoverableErrorThrottlingMax\":1800,\"ApplyErrorDeletePolicy\":\"IGNORE_RECORD\",\"ApplyErrorInsertPolicy\":\"LOG_ERROR\",\"ApplyErrorUpdatePolicy\":\"LOG_ERROR\",\"ApplyErrorEscalationPolicy\":\"LOG_ERROR\",\"ApplyErrorEscalationCount\":0,\"ApplyErrorFailOnTruncationDdl\":false,\"FullLoadIgnoreConflicts\":true,\"FailOnTransactionConsistencyBreached\":false},\"ChangeProcessingTuning\":{\"BatchApplyPreserveTransaction\":true,\"BatchApplyTimeoutMin\":1,\"BatchApplyTimeoutMax\":30,\"BatchApplyMemoryLimit\":500,\"BatchSplitSize\":0,\"MinTransactionSize\":1000,\"CommitTimeout\":1,\"MemoryLimitTotal\":1024,\"MemoryKeepTime\":60,\"StatementCacheSize\":50}}" => "{\n  \"TargetMetadata\": {\n    \"SupportLobs\": true,\n    \"FullLobMode\": false,\n    \"LobChunkSize\": 64,\n    \"LimitedSizeLobMode\": true,\n    \"LobMaxSize\": 32,\n    \"BatchApplyEnabled\": true\n  },\n  \"FullLoadSettings\": {\n    \"TargetTablePrepMode\": \"DROP_AND_CREATE\",\n    \"MaxFullLoadSubTasks\": 8,\n    \"CommitRate\": 10000\n  },\n  \"ChangeProcessingTuning\": {\n    \"BatchApplyPreserveTransaction\": true,\n    \"BatchSplitSize\": 0\n  },\n  \"Logging\": {\n    \"EnableLogging\": true,\n    \"LogComponents\": [{\n        \"Id\": \"SOURCE_UNLOAD\",\n        \"Severity\": \"LOGGER_SEVERITY_DEFAULT\"\n      },\n      {\n        \"Id\": \"SOURCE_CAPTURE\",\n        \"Severity\": \"LOGGER_SEVERITY_DEFAULT\"\n      },\n      {\n        \"Id\": \"TARGET_LOAD\",\n        \"Severity\": \"LOGGER_SEVERITY_DEFAULT\"\n      },\n      {\n        \"Id\": \"TARGET_APPLY\",\n        \"Severity\": \"LOGGER_SEVERITY_INFO\"\n      },\n      {\n        \"Id\": \"TASK_MANAGER\",\n        \"Severity\": \"LOGGER_SEVERITY_DEBUG\"\n      }\n    ]\n  },\n  \"ChangeProcessingDdlHandlingPolicy\": {\n    \"HandleSourceTableDropped\": false,\n    \"HandleSourceTableTruncated\": false,\n    \"HandleSourceTableAltered\": true\n  },\n  \"ErrorBehavior\": {\n    \"DataErrorPolicy\": \"LOG_ERROR\",\n    \"DataTruncationErrorPolicy\": \"LOG_ERROR\",\n    \"DataErrorEscalationPolicy\": \"SUSPEND_TABLE\",\n    \"DataErrorEscalationCount\": 50,\n    \"TableErrorPolicy\": \"SUSPEND_TABLE\",\n    \"TableErrorEscalationPolicy\": \"STOP_TASK\",\n    \"TableErrorEscalationCount\": 50,\n    \"RecoverableErrorCount\": 0,\n    \"RecoverableErrorInterval\": 5,\n    \"RecoverableErrorThrottling\": true,\n    \"RecoverableErrorThrottlingMax\": 1800,\n    \"ApplyErrorDeletePolicy\": \"IGNORE_RECORD\",\n    \"ApplyErrorInsertPolicy\": \"LOG_ERROR\",\n    \"ApplyErrorUpdatePolicy\": \"LOG_ERROR\",\n    \"ApplyErrorEscalationPolicy\": \"LOG_ERROR\",\n    \"ApplyErrorEscalationCount\": 0,\n    \"FullLoadIgnoreConflicts\": true\n  }\n}"
```

### Steps to Reproduce
1. `terraform apply`
1. `terraform plan`

### Important Factoids
N/A

### References
N/A

### PR DESCRIPTION
**Pull request by aburgel**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #1513

The DMS API `DescribeReplicationTasks` includes read only properties in `ReplicationTaskSettings`. This causes `terraform plan` to show that there are changes to apply since your local state will aways be different from remote state. This PR removes these read only properties when setting state so that we only compare properties that are under our control.

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/aws_dms_replication_task Remove read only properties from ReplicationTaskSettings
```

Output from acceptance testing:

```
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSDmsReplicationTaskBasic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws/ -v -count 1 -parallel 1 -run=TestAccAWSDmsReplicationTaskBasic -timeout 120m
=== RUN   TestAccAWSDmsReplicationTaskBasic
=== PAUSE TestAccAWSDmsReplicationTaskBasic
=== CONT  TestAccAWSDmsReplicationTaskBasic
--- PASS: TestAccAWSDmsReplicationTaskBasic (687.25s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	690.785s
```

### CODE REVIEW

File: aws/diff_suppress_funcs.go [hunk 1]
```diff
@@ -8,7 +8,7 @@ import (
 	"strings"
 
 	"github.com/hashicorp/terraform-plugin-sdk/helper/schema"
-	"github.com/jen20/awspolicyequivalence"
+	awspolicy "github.com/jen20/awspolicyequivalence"
```
Comment (aburgel) [inline aws/diff_suppress_funcs.go:11]: Not sure why this appeared here, but the tests pass and it seems like it should be this way... Happy to remove it if it's not needed. (FWIW, I'm relatively new to golang)

File: aws/resource_aws_dms_replication_task.go [hunk 2]
```diff
@@ -328,3 +333,29 @@ func resourceAwsDmsReplicationTaskStateRefreshFunc(
...
+
+	controlTablesSettings, ok := settingsData["ControlTablesSettings"].(map[string]interface{})
+	if ok {
+		delete(controlTablesSettings, "historyTimeslotInMinutes")
+	}
+
+	logging, ok := settingsData["Logging"].(map[string]interface{})
+	if ok {
+		delete(logging, "CloudWatchLogGroup")
+		delete(logging, "CloudWatchLogStream")
```
Comment (aburgel) [inline aws/resource_aws_dms_replication_task.go:351]: If you define these in your task settings, DMS API will return an error that they are read only.

File: aws/resource_aws_dms_replication_task.go [hunk 3]
```diff
@@ -328,3 +333,29 @@ func resourceAwsDmsReplicationTaskStateRefreshFunc(
...
+
+func cleanReadOnlyReplicationTaskSettings(settings string) (*string, error) {
+	var settingsData map[string]interface{}
+	if err := json.Unmarshal([]byte(settings), &settingsData); err != nil {
+		return nil, err
+	}
+
+	controlTablesSettings, ok := settingsData["ControlTablesSettings"].(map[string]interface{})
+	if ok {
+		delete(controlTablesSettings, "historyTimeslotInMinutes")
```
Comment (aburgel) [inline aws/resource_aws_dms_replication_task.go:345]: There is another property `HistoryTimeslotInMinutes ` (with a capital H) that is [the real property](https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Tasks.CustomizingTasks.TaskSettings.ControlTable.html). I don't know why this one exists, but I'm cleaning it out since leaving it in when we set state would cause a difference to show.

File: aws/resource_aws_dms_replication_task_test.go [hunk 4]
```diff
@@ -27,6 +27,11 @@ func TestAccAWSDmsReplicationTaskBasic(t *testing.T) {
 					resource.TestCheckResourceAttrSet(resourceName, "replication_task_arn"),
 				),
 			},
+			{
+				Config:             dmsReplicationTaskConfig(randId),
+				PlanOnly:           true,
+				ExpectNonEmptyPlan: false,
+			},
```
Comment (aburgel) [inline aws/resource_aws_dms_replication_task_test.go:34]: Now we run plan after create to assert that there are no changes. Without the fix, this will fail.

File: aws/resource_aws_dms_replication_task_test.go [hunk 5]
```diff
@@ -104,12 +109,48 @@ func dmsReplicationTaskDestroy(s *terraform.State) error {
...
+
+resource "aws_iam_role_policy_attachment" "dms_vpc_access_policy" {
+  role       = aws_iam_role.dms_vpc_role.name
+  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonDMSVPCManagementRole"
+}
+
+resource "aws_iam_role_policy_attachment" "dms_cloudwatch_logs_access_policy" {
+  role       = aws_iam_role.dms_cloudwatch_logs_role.name
+  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonDMSCloudWatchLogsRole"
+}
```
Comment (aburgel) [inline aws/resource_aws_dms_replication_task_test.go:141]: [Configuring DMS via the API requires two access policies](https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Security.html#CHAP_Security.APIRole), without them you'll get an error:

`Error: AccessDeniedFault: The IAM Role arn:aws:iam::<accountid>:role/dms-vpc-role is not configured properly.`

I'm assuming that people run these tests against an empty AWS account, but if that's not the case, then this may cause failures because the role names are fixed.

File: aws/resource_aws_dms_replication_task_test.go [hunk 6]
```diff
@@ -178,7 +219,7 @@ resource "aws_dms_replication_task" "dms_replication_task" {
...
...AGER\",\"Severity\":\"LOGGER_SEVERITY_DEFAULT\"},{\"Id\":\"TABLES_MANAGER\",\"Severity\":\"LOGGER_SEVERITY_DEFAULT\"},{\"Id\":\"METADATA_MANAGER\",\"Severity\":\"LOGGER_SEVERITY_DEFAULT\"},{\"Id\":\"FILE_FACTORY\",\"Severity\":\"LOGGER_SEVERITY_DEFAULT\"},{\"Id\":\"COMMON\",\"Severity\":\"LOGGER_SEVERITY_DEFAULT\"},{\"Id\":\"ADDONS\",\"Severity\":\"LOGGER_SEVERITY_DEFAULT\"},{\"Id\":\"DATA_STRUCTURE\",\"Severity\":\"LOGGER_SEVERITY_DEFAULT\"},{\"Id\":\"COMMUNICATION\",\"Severity\":\"LOGGER_SEVERITY_DEFAULT\"},{\"Id\":\"FILE_TRANSFER\",\"Severity\":\"LOGGER_SEVERITY_DEFAULT\"}]},\"LoopbackPreventionSettings\":null,\"PostProcessingRules\":null,\"StreamBufferSettings\":{\"CtrlStreamBufferSizeInMB\":5,\"StreamBufferCount\":3,\"StreamBufferSizeInMB\":8},\"TargetMetadata\":{\"BatchApplyEnabled\":false,\"FullLobMode\":false,\"InlineLobMaxSize\":0,\"LimitedSizeLobMode\":true,\"LoadMaxFileSize\":0,\"LobChunkSize\":0,\"LobMaxSize\":32,\"ParallelApplyBufferSize\":0,\"ParallelApplyQueuesPerThread\":0,\"ParallelApplyThreads\":0,\"ParallelLoadBufferSize\":0,\"ParallelLoadQueuesPerThread\":0,\"ParallelLoadThreads\":0,\"SupportLobs\":true,\"TargetSchema\":\"\",\"TaskRecoveryTableEnabled\":false}}"
```
Comment (aburgel) [inline aws/resource_aws_dms_replication_task_test.go:222]: I'm updating the task settings to include all the writeable properties that the `DescribeReplicationTasks` call returns. Even with my changes, this is the only way to get a clean plan since the endpoint returns all properties, even ones that are set to defaults or unused. Perhaps there is some future work in the same vein that would intelligently handle defaults or disabled properties.

As for what actually changed on this line, I added things like `BeforeImageSettings` and more `LogComponent` items, and I removed `CloudWatchLogGroup`, `CloudWatchLogStream`, and `historyTimeslotInMinutes`.

**Comment by atrepca** [comment]
@anGie44 @bflad any chance you could give this PR an eye? It would be great to have these read only DMS tasks settings removed, right now creating a task with logging enabled fails with:
```terraform
Error: InvalidParameterValueException: Task Settings CloudWatchLogGroup or CloudWatchLogStream cannot be modified.
	status code: 400, request id: <REMOVED>
```
As a workaround we're creating tasks with `EnableLogging: false`, then enabling and reflecting the changes in code, but it would be great to have this merged, 🙏 and 🙇‍♂️.

**Comment by burninmedia** [comment]
Since this is an active issue, and has many people reporting they are effected. Can someone please get this committed to master? Just 1 more test to pass it looks like we just need a linting test bug squashed.

**Comment by scottmlikens** [comment]
It's a new year; the tests are passing, and this isn't merged yet? Is there anything I can do to help, or should we wait another 6 months?

**Comment by bobnautic** [comment]
I would appreciate it a lot if this gets finally merged

**Comment by brettcave** [comment]
Would be really great to get this merged, closing in on a year and it looks like the community wants this based on 👍 .

**Comment by robbruce** [comment]
@aburgel - are you able to resolve the merge conflicts on `aws/resource_aws_dms_replication_task.go` ?

**Comment by aburgel** [comment]
just resolved the merge conflicts

**Comment by robbruce** [comment]
@ewbankkit please can be looked at to be in the next release?

**Comment by YakDriver** [comment]
@aburgel Thank you for this PR! I will be looking at it in the near future. I may need to make some minor changes. Coordinate with me if you intend to push to this branch and make sure to pull any changes I've made. Please note that you will still receive all credit for the PR and your code. Thanks again for your interest!

**Review by YakDriver — APPROVED** [review]
Looks good! 🎉 

Acceptance tests in commercial AWS:
```
--- PASS: TestAccAWSDmsReplicationTask_basic (453.75s)
```

Acceptance tests in GovCloud:
```
--- PASS: TestAccAWSDmsReplicationTask_basic (447.48s)
```

**Comment by YakDriver** [comment]
@aburgel Thanks for your work on this! I apologize it took so long to merge. It looks like AWS regularly adds new settings since between opening the PR and now 3 more were added (see below). That means we'll probably need to keep checking this.

```
ControlTablesSettings: FullLoadExceptionTableEnabled
ErrorBehavior: RecoverableErrorStopRetryAfterThrottlingMax
FailTaskWhenCleanTaskResourceFailed
```

**Comment by aburgel** [comment]
> Thanks for your work on this! I apologize it took so long to merge. 

Thank you for getting it merged @YakDriver !

> It looks like AWS regularly adds new settings since between opening the PR and now 3 more were added 

Now that we have this pattern in place, it will be a lot easier to keep on top of new settings.

Any tips for getting a faster turn around on PRs? Or is there some other mechanism we can introduce to make these kind of issues easier to manage?
