### PR TITLE
r/aws_cloudsearch_domain added `source_fields` attribute for index

### LINKED ISSUE #24814: No way to specify "Source Field" in aws_cloudsearch_domain
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.1.9
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.13.0
```

### Affected Resource(s)

* aws_cloudsearch_domain

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_cloudsearch_domain" "people_domain" {
  multi_az = false
  name     = "people"

  endpoint_options {
    enforce_https       = false
    tls_security_policy = "Policy-Min-TLS-1-0-2019-07"
  }

  index_field {
    analysis_scheme = "_mul_default_"
    facet           = false
    highlight       = true
    name            = "email"
    return          = true
    search          = true
    sort            = true
    type            = "text"
  }
  index_field {
    facet     = false
    highlight = false
    name      = "email_literal"
    return    = true
    search    = true
    sort      = true
    type      = "literal"
  }

  scaling_parameters {
    desired_partition_count   = 0
    desired_replication_count = 0
  }

  timeouts {}
}
```

### Expected Behavior

`email_literal` field should have a "Source Field" value which links it to `email`
(See second to last column in screenshot below)
image

### Actual Behavior

"Source Field" is not available as a property when importing or creating `index_field`s with `aws_cloudsearch_domain` provider

### Steps to Reproduce

Configure an index field in AWS CloudSearch which relies on another index field as its "Source Field"

Run terraform import

### References

Index field documentation: https://docs.aws.amazon.com/cloudsearch/latest/developerguide/configuring-index-fields.html

> You can also specify a default value and a source for any field. Specifying a default value can be important if you are using a numeric field in an expression and that field is not present in every document. Specifying a source copies data from one field to another, enabling you to use the same source data in different ways by configuring different options for the fields. You can use a wildcard (*) when specifying the source name to copy data from all fields that match the specified pattern.

Provider documentation: https://registry.terraform.io/providers/hashicorp/aws/3.75.1/docs/resources/cloudsearch_domain

### PR DESCRIPTION
**Pull request by daftkid**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #24814

Output from acceptance testing:

Sorry, I'm not able to run acceptance tests right now, may I ask you to run them, please?

```
$ make testacc TESTS=TestAccCloudSearchDomain_sourceFields PKG=cloudsearch

```

### CODE REVIEW

File: internal/service/cloudsearch/domain.go [hunk 1]
```diff
@@ -969,29 +968,28 @@ func expandIndexField(tfMap map[string]interface{}) (*cloudsearch.IndexField, er
...
 
 		if analysisScheme != "" {
 			options.AnalysisScheme = aws.String(analysisScheme)
 		}
 
-		if v, ok := tfMap["default_value"].(string); ok && v != "" {
-			options.DefaultValue = aws.String(v)
+		if v, ok := tfMap["source_fields"].(string); ok && v != "" {
+			options.SourceFields = aws.String(v)
 		}
```
Comment (daftkid) [inline internal/service/cloudsearch/domain.go:993]: @ewbankkit Hi, could you please briefly explain to me why you changed this piece of code? I'm pretty new to all the stuff and it's not obvious to me...

Comment (ewbankkit) [reply internal/service/cloudsearch/domain.go]: Just alphabetic ordering of setting the fields.

Comment (daftkid) [reply internal/service/cloudsearch/domain.go]: Well, anyway I do not understand why we do not need `default_value` attribute

Comment (daftkid) [reply internal/service/cloudsearch/domain.go]: Don't we just need to have separate `if` statement for `source_fields` instead of replacing `default_value` with it?

Comment (daftkid) [reply internal/service/cloudsearch/domain.go]: Yeah, I did not even think about the ordering, but now I see it might be an issue with a dependency on non-existent resources.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccCloudSearchDomain_' PKG=cloudsearch ACCTEST_PARALLELISM=2  
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/cloudsearch/... -v -count 1 -parallel 2  -run=TestAccCloudSearchDomain_ -timeout 180m
=== RUN   TestAccCloudSearchDomain_basic
=== PAUSE TestAccCloudSearchDomain_basic
=== RUN   TestAccCloudSearchDomain_disappears
=== PAUSE TestAccCloudSearchDomain_disappears
=== RUN   TestAccCloudSearchDomain_indexFields
=== PAUSE TestAccCloudSearchDomain_indexFields
=== RUN   TestAccCloudSearchDomain_sourceFields
=== PAUSE TestAccCloudSearchDomain_sourceFields
=== RUN   TestAccCloudSearchDomain_update
=== PAUSE TestAccCloudSearchDomain_update
=== CONT  TestAccCloudSearchDomain_basic
=== CONT  TestAccCloudSearchDomain_sourceFields
--- PASS: TestAccCloudSearchDomain_basic (606.20s)
=== CONT  TestAccCloudSearchDomain_update
--- PASS: TestAccCloudSearchDomain_sourceFields (1570.78s)
=== CONT  TestAccCloudSearchDomain_indexFields
--- PASS: TestAccCloudSearchDomain_update (2172.68s)
=== CONT  TestAccCloudSearchDomain_disappears
--- PASS: TestAccCloudSearchDomain_indexFields (1769.46s)
--- PASS: TestAccCloudSearchDomain_disappears (815.94s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloudsearch	3605.054s
```

**Comment by ewbankkit** [comment]
@daftkid Thanks for the contribution :tada: :clap:.
