### PR TITLE
[bugfix] aws_elasticache_replication_group : fixed num_node_groups downscaling

### LINKED ISSUE #43884: aws_elasticache_replication_group should remove existing nodes on downscaling, not compute their IDs programamatically
### Terraform and AWS Provider Version

```console
Terraform v1.11.3
on linux_amd64
+ provider registry.terraform.io/datadog/datadog v3.67.0
+ provider registry.terraform.io/hashicorp/archive v2.7.1
+ provider registry.terraform.io/hashicorp/aws v5.100.0
+ provider registry.terraform.io/hashicorp/null v3.2.4
```

### Affected Resource(s) or Data Source(s)

aws_elasticache_replication_group

### Expected Behavior

When decreasing `num_node_groups`, it should attempt to remove node groups that exist and belong to the replication group.

### Actual Behavior

It programmatically generates the ids to remove and then AWS returns an error because they don't exist

### Relevant Error/Panic Output

```console
Error: modifying ElastiCache Replication Group (SNIP) shard configuration: operation error ElastiCache: ModifyReplicationGroupShardConfiguration, https response error StatusCode: 400, RequestID: SNIP, InvalidParameterValue: The following node group ids are invalid: [0010]

```

### Sample Terraform Configuration

<details open>
<summary>Click to expand configuration</summary>

```hcl
resource "aws_elasticache_replication_group" "cluster" {
  replication_group_id = "some_cluster"

  at_rest_encryption_enabled = false
  transit_encryption_enabled = false

  port                       = 6379
  parameter_group_name       = aws_elasticache_parameter_group.cluster.name
  automatic_failover_enabled = true
  engine                     = "valkey"
  engine_version             = "8.0"
  multi_az_enabled           = false

  node_type = "cache.r7g.xlarge"

  subnet_group_name  = aws_elasticache_subnet_group.cluster_subnet.name
  maintenance_window = "mon:08:00-mon:09:00"

  cluster_mode            = "enabled"
  replicas_per_node_group = 0
  num_node_groups         = 10
}
```
</details>

### Steps to Reproduce

As seen [in the code](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/elasticache/replication_group.go#L1166) it programmatically calculates the node ids it should remove. However, because of maintenance (or using terraform import), the nodes that actually belong to a cluster may not be in sequential order.

The concrete example of what I'm facing is:
- my cluster has 10 nodes, with ids `1-7` , `9`, `11` and `12`
- i try to decrease `num_node_groups` from 10 to 9
- it tries to delete node with id `0010` and fails because it doesn't exist

### Debug Logging

<details open>
<summary>Click to expand log output</summary>

```console

```
</details>

### GenAI / LLM Assisted Development

n/a

### Important Facts and References

_No response_

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by sukumaar**
## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the library.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

### Description
Fixed an issue with downscaling `aws_elasticache_replication_group` when `cluster_mode="enabled"` and `num_node_groups` is reduced. Previously, downscaling could fail in certain scenarios; for example, if nodes `0001`, `0002`, `0003`, `0004`, and `0005` exist, and a user manually removes `0003` and `0005`, then sets `num_node_groups = 2`, terraform would attempt to delete `0003`, `0004`, and `0005`. This is now fixed, after this fix terraform will retrieve the current node groups before resizing.

### Relations

Closes #43884

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccElastiCacheReplicationGroup PKG=elasticache ACCTEST_PARALLELISM=2 ACCTEST_TIMEOUT=3880m
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
xargs: gofmt: No such file or directory
make: Running acceptance tests on branch: 🌿 f-elasticache-rg-down-scaling 🌿...
TF_ACC=1 go1.24.10 test ./internal/service/elasticache/... -v -count 1 -parallel 2 -run='TestAccElastiCacheReplicationGroup'  -timeout 3880m -vet=off
2026/01/12 00:03:53 Creating Terraform AWS Provider (SDKv2-style)...
2026/01/12 00:03:53 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccElastiCacheReplicationGroupDataSource_basic
=== PAUSE TestAccElastiCacheReplicationGroupDataSource_basic
=== RUN   TestAccElastiCacheReplicationGroupDataSource_clusterMode
=== PAUSE TestAccElastiCacheReplicationGroupDataSource_clusterMode
=== RUN   TestAccElastiCacheReplicationGroupDataSource_multiAZ
=== PAUSE TestAccElastiCacheReplicationGroupDataSource_multiAZ
=== RUN   TestAccElastiCacheReplicationGroupDataSource_Engine_Redis_LogDeliveryConfigurations
=== PAUSE TestAccElastiCacheReplicationGroupDataSource_Engine_Redis_LogDeliveryConfigurations
=== RUN   TestAccElastiCacheReplicationGroup_Redis_basic
=== PAUSE TestAccElastiCacheReplicationGroup_Redis_basic
=== RUN   TestAccElastiCacheReplicationGroup_Redis_basic_v5
=== PAUSE TestAccElastiCacheReplicationGroup_Redis_basic_v5
=== RUN   TestAccElastiCacheReplicationGroup_Valkey_basic
=== PAUSE TestAccElastiCacheReplicationGroup_Valkey_basic
=== RUN   TestAccElastiCacheReplicationGroup_uppercase
=== PAUSE TestAccElastiCacheReplicationGroup_uppercase
=== RUN   TestAccElastiCacheReplicationGroup_Redis_EngineVersion_v7
=== PAUSE TestAccElastiCacheReplicationGroup_Redis_EngineVersion_v7
=== RUN   TestAccElastiCacheReplicationGroup_OutOfBandUpgrade
=== PAUSE TestAccElastiCacheReplicationGroup_OutOfBandUpgrade
=== RUN   TestAccElastiCacheReplicationGroup_EngineVersion_update
=== PAUSE TestAccElastiCacheReplicationGroup_EngineVersion_update
=== RUN   TestAccElastiCacheReplicationGroup_EngineVersion_6xToRealVersion
=== PAUSE TestAccElastiCacheReplicationGroup_EngineVersion_6xToRealVersion
=== RUN   TestAccElastiCacheReplicationGroup_Engine_RedisToValkey
=== PAUSE TestAccElastiCacheReplicationGroup_Engine_RedisToValkey
=== RUN   TestAccElastiCacheReplicationGroup_disappears
=== PAUSE TestAccElastiCacheReplicationGroup_disappears
=== RUN   TestAccElastiCacheReplicationGroup_updateDescription
=== PAUSE TestAccElastiCacheReplicationGroup_updateDescription
=== RUN   TestAccElastiCacheReplicationGroup_updateMaintenanceWindow
=== PAUSE TestAccElastiCacheReplicationGroup_updateMaintenanceWindow
=== RUN   TestAccElastiCacheReplicationGroup_updateUserGroups
=== PAUSE TestAccElastiCacheReplicationGroup_updateUserGroups
=== RUN   TestAccElastiCacheReplicationGroup_updateNodeSize
=== PAUSE TestAccElastiCacheReplicationGroup_updateNodeSize
=== RUN   TestAccElastiCacheReplicationGroup_updateParameterGroup
=== PAUSE TestAccElastiCacheReplicationGroup_updateParameterGroup
=== RUN   TestAccElastiCacheReplicationGroup_authToken
=== PAUSE TestAccElastiCacheReplicationGroup_authToken
=== RUN   TestAccElastiCacheReplicationGroup_upgrade_6_0_0
=== PAUSE TestAccElastiCacheReplicationGroup_upgrade_6_0_0
=== RUN   TestAccElastiCacheReplicationGroup_upgrade_5_27_0
=== PAUSE TestAccElastiCacheReplicationGroup_upgrade_5_27_0
=== RUN   TestAccElastiCacheReplicationGroup_upgrade_4_68_0
=== PAUSE TestAccElastiCacheReplicationGroup_upgrade_4_68_0
=== RUN   TestAccElastiCacheReplicationGroup_vpc
=== PAUSE TestAccElastiCacheReplicationGroup_vpc
=== RUN   TestAccElastiCacheReplicationGroup_multiAzNotInVPC
=== PAUSE TestAccElastiCacheReplicationGroup_multiAzNotInVPC
=== RUN   TestAccElastiCacheReplicationGroup_multiAzNotInVPC_repeated
=== PAUSE TestAccElastiCacheReplicationGroup_multiAzNotInVPC_repeated
=== RUN   TestAccElastiCacheReplicationGroup_multiAzInVPC
=== PAUSE TestAccElastiCacheReplicationGroup_multiAzInVPC
=== RUN   TestAccElastiCacheReplicationGroup_deprecatedAvailabilityZones_multiAzInVPC
=== PAUSE TestAccElastiCacheReplicationGroup_deprecatedAvailabilityZones_multiAzInVPC
=== RUN   TestAccElastiCacheReplicationGroup_ValidationMultiAz_noAutomaticFailover
=== PAUSE TestAccElastiCacheReplicationGroup_ValidationMultiAz_noAutomaticFailover
=== RUN   TestAccElastiCacheReplicationGroup_ipDiscovery
=== PAUSE TestAccElastiCacheReplicationGroup_ipDiscovery
=== RUN   TestAccElastiCacheReplicationGroup_networkType
=== PAUSE TestAccElastiCacheReplicationGroup_networkType
=== RUN   TestAccElastiCacheReplicationGroup_ClusterMode_basic
=== PAUSE TestAccElastiCacheReplicationGroup_ClusterMode_basic
=== RUN   TestAccElastiCacheReplicationGroup_ClusterMode_nonClusteredParameterGroup
=== PAUSE TestAccElastiCacheReplicationGroup_ClusterMode_nonClusteredParameterGroup
=== RUN   TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroups_scaleUp
=== PAUSE TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroups_scaleUp
=== RUN   TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroups_scaleDown
=== PAUSE TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroups_scaleDown
=== RUN   TestAccElastiCacheReplicationGroup_ClusterMode_updateReplicasPerNodeGroup
=== PAUSE TestAccElastiCacheReplicationGroup_ClusterMode_updateReplicasPerNodeGroup
=== RUN   TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroupsAndReplicasPerNodeGroup_scaleUp
=== PAUSE TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroupsAndReplicasPerNodeGroup_scaleUp
=== RUN   TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroupsAndReplicasPerNodeGroup_scaleDown
=== PAUSE TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroupsAndReplicasPerNodeGroup_scaleDown
=== RUN   TestAccElastiCacheReplicationGroup_ClusterMode_singleNode
=== PAUSE TestAccElastiCacheReplicationGroup_ClusterMode_singleNode
=== RUN   TestAccElastiCacheReplicationGroup_ClusterMode_nodeGroupConfiguration
=== PAUSE TestAccElastiCacheReplicationGroup_ClusterMode_nodeGroupConfiguration
=== RUN   TestAccElastiCacheReplicationGroup_ClusterMode_nodeGroupConfiguration_availabilityZones
=== PAUSE TestAccElastiCacheReplicationGroup_ClusterMode_nodeGroupConfiguration_availabilityZones
=== RUN   TestAccElastiCacheReplicationGroup_ClusterMode_updateFromDisabled_Compatible_Enabled
=== PAUSE TestAccElastiCacheReplicationGroup_ClusterMode_updateFromDisabled_Compatible_Enabled
=== RUN   TestAccElastiCacheReplicationGroup_cacheClustersConflictsWithReplicasPerNodeGroup
=== PAUSE TestAccElastiCacheReplicationGroup_cacheClustersConflictsWithReplicasPerNodeGroup
=== RUN   TestAccElastiCacheReplicationGroup_clusteringAndCacheNodesCausesError
=== PAUSE TestAccElastiCacheReplicationGroup_clusteringAndCacheNodesCausesError
=== RUN   TestAccElastiCacheReplicationGroup_enableSnapshotting
=== PAUSE TestAccElastiCacheReplicationGroup_enableSnapshotting
=== RUN   TestAccElastiCacheReplicationGroup_transitEncryptionWithAuthToken
=== PAUSE TestAccElastiCacheReplicationGroup_transitEncryptionWithAuthToken
=== RUN   TestAccElastiCacheReplicationGroup_transitEncryption5x
=== PAUSE TestAccElastiCacheReplicationGroup_transitEncryption5x
=== RUN   TestAccElastiCacheReplicationGroup_transitEncryption7x_basic
=== PAUSE TestAccElastiCacheReplicationGroup_transitEncryption7x_basic
=== RUN   TestAccElastiCacheReplicationGroup_transitEncryption7x_Enable
=== PAUSE TestAccElastiCacheReplicationGroup_transitEncryption7x_Enable
=== RUN   TestAccElastiCacheReplicationGroup_transitEncryption7x_Disable
=== PAUSE TestAccElastiCacheReplicationGroup_transitEncryption7x_Disable
=== RUN   TestAccElastiCacheReplicationGroup_Redis_enableAtRestEncryption
=== PAUSE TestAccElastiCacheReplicationGroup_Redis_enableAtRestEncryption
=== RUN   TestAccElastiCacheReplicationGroup_Valkey_disableAtRestEncryption
=== PAUSE TestAccElastiCacheReplicationGroup_Valkey_disableAtRestEncryption
=== RUN   TestAccElastiCacheReplicationGroup_useCMKKMSKeyID
=== PAUSE TestAccElastiCacheReplicationGroup_useCMKKMSKeyID
=== RUN   TestAccElastiCacheReplicationGroup_NumberCacheClusters_basic
=== PAUSE TestAccElastiCacheReplicationGroup_NumberCacheClusters_basic
=== RUN   TestAccElastiCacheReplicationGroup_NumberCacheClusters_autoFailoverDisabled
=== PAUSE TestAccElastiCacheReplicationGroup_NumberCacheClusters_autoFailoverDisabled
=== RUN   TestAccElastiCacheReplicationGroup_NumberCacheClusters_autoFailoverEnabled
=== PAUSE TestAccElastiCacheReplicationGroup_NumberCacheClusters_autoFailoverEnabled
=== RUN   TestAccElastiCacheReplicationGroup_autoFailoverEnabled_validateNumberCacheClusters
=== PAUSE TestAccElastiCacheReplicationGroup_autoFailoverEnabled_validateNumberCacheClusters
=== RUN   TestAccElastiCacheReplicationGroup_NumberCacheClusters_multiAZEnabled
=== PAUSE TestAccElastiCacheReplicationGroup_NumberCacheClusters_multiAZEnabled
=== RUN   TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappears_noChange
=== PAUSE TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappears_noChange
=== RUN   TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappears_addMemberCluster
=== PAUSE TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappears_addMemberCluster
=== RUN   TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappearsRemoveMemberCluster_atTargetSize
=== PAUSE TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappearsRemoveMemberCluster_atTargetSize
=== RUN   TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappearsRemoveMemberCluster_scaleDown
=== PAUSE TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappearsRemoveMemberCluster_scaleDown
=== RUN   TestAccElastiCacheReplicationGroup_tags
=== PAUSE TestAccElastiCacheReplicationGroup_tags
=== RUN   TestAccElastiCacheReplicationGroup_TagWithOtherModification_version
=== PAUSE TestAccElastiCacheReplicationGroup_TagWithOtherModification_version
=== RUN   TestAccElastiCacheReplicationGroup_TagWithOtherModification_numCacheClusters
=== PAUSE TestAccElastiCacheReplicationGroup_TagWithOtherModification_numCacheClusters
=== RUN   TestAccElastiCacheReplicationGroup_finalSnapshot
=== PAUSE TestAccElastiCacheReplicationGroup_finalSnapshot
=== RUN   TestAccElastiCacheReplicationGroup_autoMinorVersionUpgrade
=== PAUSE TestAccElastiCacheReplicationGroup_autoMinorVersionUpgrade
=== RUN   TestAccElastiCacheReplicationGroup_Validation_noNodeType
=== PAUSE TestAccElastiCacheReplicationGroup_Validation_noNodeType
=== RUN   TestAccElastiCacheReplicationGroup_Validation_globalReplicationGroupIdAndNodeType
=== PAUSE TestAccElastiCacheReplicationGroup_Validation_globalReplicationGroupIdAndNodeType
=== RUN   TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_basic
=== PAUSE TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_basic
=== RUN   TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_full
=== PAUSE TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_full
=== RUN   TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_disappears
=== PAUSE TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_disappears
=== RUN   TestAccElastiCacheReplicationGroup_GlobalReplicationGroupIDClusterMode_basic
=== PAUSE TestAccElastiCacheReplicationGroup_GlobalReplicationGroupIDClusterMode_basic
=== RUN   TestAccElastiCacheReplicationGroup_GlobalReplicationGroupIDClusterModeValidation_numNodeGroupsOnSecondary
=== PAUSE TestAccElastiCacheReplicationGroup_GlobalReplicationGroupIDClusterModeValidation_numNodeGroupsOnSecondary
=== RUN   TestAccElastiCacheReplicationGroup_dataTiering
=== PAUSE TestAccElastiCacheReplicationGroup_dataTiering
=== RUN   TestAccElastiCacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_ClusterMode_Disabled
=== PAUSE TestAccElastiCacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_ClusterMode_Disabled
=== RUN   TestAccElastiCacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_ClusterMode_Enabled
=== PAUSE TestAccElastiCacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_ClusterMode_Enabled
=== RUN   TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Valkey7
=== PAUSE TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Valkey7
=== RUN   TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Valkey8
=== PAUSE TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Valkey8
=== RUN   TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Redis7
=== PAUSE TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Redis7
=== CONT  TestAccElastiCacheReplicationGroup_autoMinorVersionUpgrade
=== CONT  TestAccElastiCacheReplicationGroupDataSource_basic
--- PASS: TestAccElastiCacheReplicationGroup_autoMinorVersionUpgrade (753.10s)
=== CONT  TestAccElastiCacheReplicationGroup_finalSnapshot
--- PASS: TestAccElastiCacheReplicationGroupDataSource_basic (872.89s)
=== CONT  TestAccElastiCacheReplicationGroup_TagWithOtherModification_numCacheClusters
--- PASS: TestAccElastiCacheReplicationGroup_finalSnapshot (922.42s)
=== CONT  TestAccElastiCacheReplicationGroup_TagWithOtherModification_version
--- PASS: TestAccElastiCacheReplicationGroup_TagWithOtherModification_numCacheClusters (1178.94s)
=== CONT  TestAccElastiCacheReplicationGroup_tags
--- PASS: TestAccElastiCacheReplicationGroup_tags (775.55s)
=== CONT  TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappearsRemoveMemberCluster_scaleDown
--- PASS: TestAccElastiCacheReplicationGroup_TagWithOtherModification_version (2003.60s)
=== CONT  TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappearsRemoveMemberCluster_atTargetSize
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappearsRemoveMemberCluster_scaleDown (1335.52s)
=== CONT  TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappears_addMemberCluster
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappearsRemoveMemberCluster_atTargetSize (1027.04s)
=== CONT  TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappears_noChange
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappears_addMemberCluster (1376.06s)
=== CONT  TestAccElastiCacheReplicationGroup_NumberCacheClusters_multiAZEnabled
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappears_noChange (1345.64s)
=== CONT  TestAccElastiCacheReplicationGroup_autoFailoverEnabled_validateNumberCacheClusters
--- PASS: TestAccElastiCacheReplicationGroup_autoFailoverEnabled_validateNumberCacheClusters (2.25s)
=== CONT  TestAccElastiCacheReplicationGroup_NumberCacheClusters_autoFailoverEnabled
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClusters_multiAZEnabled (1325.52s)
=== CONT  TestAccElastiCacheReplicationGroup_GlobalReplicationGroupIDClusterModeValidation_numNodeGroupsOnSecondary
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClusters_autoFailoverEnabled (1387.45s)
=== CONT  TestAccElastiCacheReplicationGroup_NumberCacheClusters_autoFailoverDisabled
--- PASS: TestAccElastiCacheReplicationGroup_GlobalReplicationGroupIDClusterModeValidation_numNodeGroupsOnSecondary (1213.34s)
=== CONT  TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Redis7
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClusters_autoFailoverDisabled (1260.83s)
=== CONT  TestAccElastiCacheReplicationGroup_NumberCacheClusters_basic
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClusters_basic (1303.91s)
=== CONT  TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Valkey8
--- PASS: TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Redis7 (3084.81s)
=== CONT  TestAccElastiCacheReplicationGroup_useCMKKMSKeyID
--- PASS: TestAccElastiCacheReplicationGroup_useCMKKMSKeyID (617.30s)
=== CONT  TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Valkey7
--- PASS: TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Valkey8 (1804.25s)
=== CONT  TestAccElastiCacheReplicationGroup_Valkey_disableAtRestEncryption
--- PASS: TestAccElastiCacheReplicationGroup_Valkey_disableAtRestEncryption (723.53s)
=== CONT  TestAccElastiCacheReplicationGroup_Redis_enableAtRestEncryption
--- PASS: TestAccElastiCacheReplicationGroup_Redis_enableAtRestEncryption (722.47s)
=== CONT  TestAccElastiCacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_ClusterMode_Enabled
--- PASS: TestAccElastiCacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_ClusterMode_Enabled (891.72s)
=== CONT  TestAccElastiCacheReplicationGroup_transitEncryption7x_Disable
--- PASS: TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Valkey7 (2985.22s)
=== CONT  TestAccElastiCacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_ClusterMode_Disabled
--- PASS: TestAccElastiCacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_ClusterMode_Disabled (860.91s)
=== CONT  TestAccElastiCacheReplicationGroup_dataTiering
--- PASS: TestAccElastiCacheReplicationGroup_transitEncryption7x_Disable (1887.82s)
=== CONT  TestAccElastiCacheReplicationGroup_GlobalReplicationGroupIDClusterMode_basic
--- PASS: TestAccElastiCacheReplicationGroup_dataTiering (596.13s)
=== CONT  TestAccElastiCacheReplicationGroup_transitEncryption7x_Enable
--- PASS: TestAccElastiCacheReplicationGroup_transitEncryption7x_Enable (1879.19s)
=== CONT  TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_full
--- PASS: TestAccElastiCacheReplicationGroup_GlobalReplicationGroupIDClusterMode_basic (3925.17s)
=== CONT  TestAccElastiCacheReplicationGroup_transitEncryption7x_basic
--- PASS: TestAccElastiCacheReplicationGroup_transitEncryption7x_basic (687.20s)
=== CONT  TestAccElastiCacheReplicationGroup_transitEncryption5x
--- PASS: TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_full (3245.59s)
=== CONT  TestAccElastiCacheReplicationGroup_upgrade_4_68_0
--- PASS: TestAccElastiCacheReplicationGroup_transitEncryption5x (1347.00s)
=== CONT  TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_disappears
--- PASS: TestAccElastiCacheReplicationGroup_upgrade_4_68_0 (844.25s)
=== CONT  TestAccElastiCacheReplicationGroup_upgrade_5_27_0
--- PASS: TestAccElastiCacheReplicationGroup_upgrade_5_27_0 (742.85s)
=== CONT  TestAccElastiCacheReplicationGroup_upgrade_6_0_0
--- PASS: TestAccElastiCacheReplicationGroup_upgrade_6_0_0 (741.15s)
=== CONT  TestAccElastiCacheReplicationGroup_vpc
--- PASS: TestAccElastiCacheReplicationGroup_vpc (668.76s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterMode_updateReplicasPerNodeGroup
--- PASS: TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_disappears (2955.22s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroups_scaleDown
--- PASS: TestAccElastiCacheReplicationGroup_ClusterMode_updateReplicasPerNodeGroup (1597.76s)
=== CONT  TestAccElastiCacheReplicationGroup_authToken
--- PASS: TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroups_scaleDown (1768.27s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroups_scaleUp
--- PASS: TestAccElastiCacheReplicationGroup_authToken (1382.16s)
=== CONT  TestAccElastiCacheReplicationGroup_updateParameterGroup
--- PASS: TestAccElastiCacheReplicationGroup_updateParameterGroup (816.09s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterMode_nonClusteredParameterGroup
--- PASS: TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroups_scaleUp (1455.40s)
=== CONT  TestAccElastiCacheReplicationGroup_Validation_globalReplicationGroupIdAndNodeType
--- PASS: TestAccElastiCacheReplicationGroup_ClusterMode_nonClusteredParameterGroup (654.31s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterMode_basic
--- PASS: TestAccElastiCacheReplicationGroup_Validation_globalReplicationGroupIdAndNodeType (1073.93s)
=== CONT  TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_basic
--- PASS: TestAccElastiCacheReplicationGroup_ClusterMode_basic (811.20s)
=== CONT  TestAccElastiCacheReplicationGroup_networkType
--- PASS: TestAccElastiCacheReplicationGroup_networkType (901.08s)
=== CONT  TestAccElastiCacheReplicationGroup_Validation_noNodeType
--- PASS: TestAccElastiCacheReplicationGroup_Validation_noNodeType (8.92s)
=== CONT  TestAccElastiCacheReplicationGroup_ipDiscovery
--- PASS: TestAccElastiCacheReplicationGroup_ipDiscovery (902.17s)
=== CONT  TestAccElastiCacheReplicationGroup_updateNodeSize
--- PASS: TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_basic (2677.95s)
=== CONT  TestAccElastiCacheReplicationGroup_multiAzInVPC
--- PASS: TestAccElastiCacheReplicationGroup_multiAzInVPC (889.87s)
=== CONT  TestAccElastiCacheReplicationGroup_updateUserGroups
--- PASS: TestAccElastiCacheReplicationGroup_updateNodeSize (1610.18s)
=== CONT  TestAccElastiCacheReplicationGroup_multiAzNotInVPC_repeated
--- PASS: TestAccElastiCacheReplicationGroup_updateUserGroups (858.56s)
=== CONT  TestAccElastiCacheReplicationGroup_transitEncryptionWithAuthToken
--- PASS: TestAccElastiCacheReplicationGroup_multiAzNotInVPC_repeated (743.77s)
=== CONT  TestAccElastiCacheReplicationGroup_ValidationMultiAz_noAutomaticFailover
--- PASS: TestAccElastiCacheReplicationGroup_ValidationMultiAz_noAutomaticFailover (2.10s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterMode_nodeGroupConfiguration
--- PASS: TestAccElastiCacheReplicationGroup_transitEncryptionWithAuthToken (606.26s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterMode_singleNode
--- PASS: TestAccElastiCacheReplicationGroup_ClusterMode_nodeGroupConfiguration (873.53s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroupsAndReplicasPerNodeGroup_scaleDown
--- PASS: TestAccElastiCacheReplicationGroup_ClusterMode_singleNode (632.35s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroupsAndReplicasPerNodeGroup_scaleUp
--- PASS: TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroupsAndReplicasPerNodeGroup_scaleUp (1898.62s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterMode_nodeGroupConfiguration_availabilityZones
--- PASS: TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroupsAndReplicasPerNodeGroup_scaleDown (2183.11s)
=== CONT  TestAccElastiCacheReplicationGroup_Redis_EngineVersion_v7
--- PASS: TestAccElastiCacheReplicationGroup_Redis_EngineVersion_v7 (744.56s)
=== CONT  TestAccElastiCacheReplicationGroup_enableSnapshotting
--- PASS: TestAccElastiCacheReplicationGroup_ClusterMode_nodeGroupConfiguration_availabilityZones (876.41s)
=== CONT  TestAccElastiCacheReplicationGroup_updateDescription
--- PASS: TestAccElastiCacheReplicationGroup_enableSnapshotting (693.11s)
=== CONT  TestAccElastiCacheReplicationGroup_clusteringAndCacheNodesCausesError
--- PASS: TestAccElastiCacheReplicationGroup_clusteringAndCacheNodesCausesError (2.01s)
=== CONT  TestAccElastiCacheReplicationGroup_disappears
--- PASS: TestAccElastiCacheReplicationGroup_updateDescription (682.24s)
=== CONT  TestAccElastiCacheReplicationGroup_EngineVersion_update
--- PASS: TestAccElastiCacheReplicationGroup_disappears (660.91s)
=== CONT  TestAccElastiCacheReplicationGroup_deprecatedAvailabilityZones_multiAzInVPC
--- PASS: TestAccElastiCacheReplicationGroup_deprecatedAvailabilityZones_multiAzInVPC (801.25s)
=== CONT  TestAccElastiCacheReplicationGroup_OutOfBandUpgrade
--- PASS: TestAccElastiCacheReplicationGroup_OutOfBandUpgrade (1554.30s)
=== CONT  TestAccElastiCacheReplicationGroup_multiAzNotInVPC
--- PASS: TestAccElastiCacheReplicationGroup_multiAzNotInVPC (834.36s)
=== CONT  TestAccElastiCacheReplicationGroup_cacheClustersConflictsWithReplicasPerNodeGroup
--- PASS: TestAccElastiCacheReplicationGroup_cacheClustersConflictsWithReplicasPerNodeGroup (1.90s)
=== CONT  TestAccElastiCacheReplicationGroup_Engine_RedisToValkey
--- PASS: TestAccElastiCacheReplicationGroup_Engine_RedisToValkey (1540.27s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterMode_updateFromDisabled_Compatible_Enabled
--- PASS: TestAccElastiCacheReplicationGroup_EngineVersion_update (5792.65s)
=== CONT  TestAccElastiCacheReplicationGroup_Redis_basic
--- PASS: TestAccElastiCacheReplicationGroup_Redis_basic (722.68s)
=== CONT  TestAccElastiCacheReplicationGroupDataSource_multiAZ
--- PASS: TestAccElastiCacheReplicationGroupDataSource_multiAZ (741.79s)
=== CONT  TestAccElastiCacheReplicationGroup_uppercase
--- PASS: TestAccElastiCacheReplicationGroup_uppercase (667.51s)
=== CONT  TestAccElastiCacheReplicationGroup_Redis_basic_v5
--- PASS: TestAccElastiCacheReplicationGroup_ClusterMode_updateFromDisabled_Compatible_Enabled (2668.95s)
=== CONT  TestAccElastiCacheReplicationGroupDataSource_Engine_Redis_LogDeliveryConfigurations
--- PASS: TestAccElastiCacheReplicationGroup_Redis_basic_v5 (673.02s)
=== CONT  TestAccElastiCacheReplicationGroupDataSource_clusterMode
--- PASS: TestAccElastiCacheReplicationGroupDataSource_Engine_Redis_LogDeliveryConfigurations (788.04s)
=== CONT  TestAccElastiCacheReplicationGroup_EngineVersion_6xToRealVersion
--- PASS: TestAccElastiCacheReplicationGroup_EngineVersion_6xToRealVersion (729.37s)
=== CONT  TestAccElastiCacheReplicationGroup_updateMaintenanceWindow
--- PASS: TestAccElastiCacheReplicationGroupDataSource_clusterMode (921.48s)
=== CONT  TestAccElastiCacheReplicationGroup_Valkey_basic
--- PASS: TestAccElastiCacheReplicationGroup_updateMaintenanceWindow (742.91s)
--- PASS: TestAccElastiCacheReplicationGroup_Valkey_basic (803.81s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elasticache	48693.587s

...
```

### CODE REVIEW

File: internal/service/elasticache/replication_group.go [hunk 1]
```diff
@@ -1258,19 +1259,37 @@ func modifyReplicationGroupShardConfigurationNumNodeGroups(ctx context.Context,
...
-		input.NodeGroupsToRemove = nodeGroupsToRemove
-	}
 
-	_, err := conn.ModifyReplicationGroupShardConfiguration(ctx, input)
+		for _, ng := range rg.NodeGroups {
+			if ng.NodeGroupId != nil {
+				nodeGroupIDs = append(nodeGroupIDs, *ng.NodeGroupId)
+			}
+		}
+		lenghtOfNodeGroupIDs := len(nodeGroupIDs)
```
Comment (trevorbonas) [inline internal/service/elasticache/replication_group.go]:
```suggestion
		lengthOfNodeGroupIDs := len(nodeGroupIDs)
```

File: internal/service/elasticache/replication_group.go [hunk 2]
```diff
@@ -1258,19 +1259,37 @@ func modifyReplicationGroupShardConfigurationNumNodeGroups(ctx context.Context,
...
 
 	if oldNodeGroupCount > newNodeGroupCount {
-		// Node Group IDs are 1 indexed: 0001 through 0015
-		// Loop from highest old ID until we reach highest new ID
-		nodeGroupsToRemove := []string{}
-		for i := oldNodeGroupCount; i > newNodeGroupCount; i-- {
-			nodeGroupID := fmt.Sprintf("%04d", i)
-			nodeGroupsToRemove = append(nodeGroupsToRemove, nodeGroupID)
+		//scalling down scenario
+
```
Comment (trevorbonas) [inline internal/service/elasticache/replication_group.go]:
```suggestion
		// Scaling down scenario.
```

File: internal/service/elasticache/replication_group.go [hunk 3]
```diff
@@ -1258,19 +1259,37 @@ func modifyReplicationGroupShardConfigurationNumNodeGroups(ctx context.Context,
...
+			nodeGroupsToRemove := []string{}
+			reductionCount := oldNodeGroupCount - newNodeGroupCount
+
+			for i := lenghtOfNodeGroupIDs; i > (lenghtOfNodeGroupIDs - reductionCount); i-- {
+				nodeGroupsToRemove = append(nodeGroupsToRemove, nodeGroupIDs[i-1])
+			}
+
+			input.NodeGroupsToRemove = nodeGroupsToRemove
+		}
```
Comment (trevorbonas) [inline internal/service/elasticache/replication_group.go]: `reductionCount` is based on the old node group count and the new node group count, which is the change in the `num_node_groups` value. This causes problems if, as your summary suggests, we want to support users deleting nodes themselves, without Terraform.

For example, using the scenario you put in your summary:
- A user has a replication group with 5 node groups, `0001` to `0005`. `num_node_groups` is `5`.
- They delete `0003` and `0005` themselves and reduce `num_node_groups` to `2`.
  - This would mean that the user either made a mistake or is now deciding to rely on Terraform to delete more node groups. Either way, the replication group should end up with 2 node groups.
- `lenghtOfNodeGroupIDs` will be `3`, the actual number of node groups in the replication group.
- `newNodeGroupCount` will be `2` (new user-provided value for `num_node_groups`).
- `reductionCount` will be set to `3`.
- Terraform will delete 3 node groups and the replication group will be left with 0 node groups.

Your test cases never run into this problem because `lenghtOfNodeGroupIDs` is never greater than `newNodeGroupCount`. Try adding a test that matches the above scenario.

Comment (sukumaar) [reply internal/service/elasticache/replication_group.go]: Thanks for suggestion, made changes.

File: internal/service/elasticache/replication_group.go [hunk 4]
```diff
@@ -1258,19 +1259,37 @@ func modifyReplicationGroupShardConfigurationNumNodeGroups(ctx context.Context,
 	}
 
 	if oldNodeGroupCount > newNodeGroupCount {
-		// Node Group IDs are 1 indexed: 0001 through 0015
-		// Loop from highest old ID until we reach highest new ID
-		nodeGroupsToRemove := []string{}
-		for i := oldNodeGroupCount; i > newNodeGroupCount; i-- {
-			nodeGroupID := fmt.Sprintf("%04d", i)
-			nodeGroupsToRemove = append(nodeGroupsToRemove, nodeGroupID)
+		//Scalling down scenario.
```
Comment (trevorbonas) [inline internal/service/elasticache/replication_group.go]:
```suggestion
		// Scaling down scenario.
```

**Comment by sukumaar** [comment]
### Acceptance tests after code change:

```console
% make testacc TESTS=TestAccElastiCacheReplicationGroup PKG=elasticache ACCTEST_PARALLELISM=2 ACCTEST_TIMEOUT=3880m
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
xargs: gofmt: No such file or directory
make: Running acceptance tests on branch: 🌿 f-elasticache-rg-down-scaling 🌿...
TF_ACC=1 go1.24.10 test ./internal/service/elasticache/... -v -count 1 -parallel 2 -run='TestAccElastiCacheReplicationGroup'  -timeout 3880m -vet=off
2026/01/16 04:25:05 Creating Terraform AWS Provider (SDKv2-style)...
2026/01/16 04:25:05 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccElastiCacheReplicationGroupDataSource_basic
=== PAUSE TestAccElastiCacheReplicationGroupDataSource_basic
=== RUN   TestAccElastiCacheReplicationGroupDataSource_clusterMode
=== PAUSE TestAccElastiCacheReplicationGroupDataSource_clusterMode
=== RUN   TestAccElastiCacheReplicationGroupDataSource_multiAZ
=== PAUSE TestAccElastiCacheReplicationGroupDataSource_multiAZ
=== RUN   TestAccElastiCacheReplicationGroupDataSource_Engine_Redis_LogDeliveryConfigurations
=== PAUSE TestAccElastiCacheReplicationGroupDataSource_Engine_Redis_LogDeliveryConfigurations
=== RUN   TestAccElastiCacheReplicationGroup_Redis_basic
=== PAUSE TestAccElastiCacheReplicationGroup_Redis_basic
=== RUN   TestAccElastiCacheReplicationGroup_Redis_basic_v5
=== PAUSE TestAccElastiCacheReplicationGroup_Redis_basic_v5
=== RUN   TestAccElastiCacheReplicationGroup_Valkey_basic
=== PAUSE TestAccElastiCacheReplicationGroup_Valkey_basic
=== RUN   TestAccElastiCacheReplicationGroup_uppercase
=== PAUSE TestAccElastiCacheReplicationGroup_uppercase
=== RUN   TestAccElastiCacheReplicationGroup_Redis_EngineVersion_v7
=== PAUSE TestAccElastiCacheReplicationGroup_Redis_EngineVersion_v7
=== RUN   TestAccElastiCacheReplicationGroup_OutOfBandUpgrade
=== PAUSE TestAccElastiCacheReplicationGroup_OutOfBandUpgrade
=== RUN   TestAccElastiCacheReplicationGroup_EngineVersion_update
=== PAUSE TestAccElastiCacheReplicationGroup_EngineVersion_update
=== RUN   TestAccElastiCacheReplicationGroup_EngineVersion_6xToRealVersion
=== PAUSE TestAccElastiCacheReplicationGroup_EngineVersion_6xToRealVersion
=== RUN   TestAccElastiCacheReplicationGroup_Engine_RedisToValkey
=== PAUSE TestAccElastiCacheReplicationGroup_Engine_RedisToValkey
=== RUN   TestAccElastiCacheReplicationGroup_disappears
=== PAUSE TestAccElastiCacheReplicationGroup_disappears
=== RUN   TestAccElastiCacheReplicationGroup_updateDescription
=== PAUSE TestAccElastiCacheReplicationGroup_updateDescription
=== RUN   TestAccElastiCacheReplicationGroup_updateMaintenanceWindow
=== PAUSE TestAccElastiCacheReplicationGroup_updateMaintenanceWindow
=== RUN   TestAccElastiCacheReplicationGroup_updateUserGroups
=== PAUSE TestAccElastiCacheReplicationGroup_updateUserGroups
=== RUN   TestAccElastiCacheReplicationGroup_updateNodeSize
=== PAUSE TestAccElastiCacheReplicationGroup_updateNodeSize
=== RUN   TestAccElastiCacheReplicationGroup_updateParameterGroup
=== PAUSE TestAccElastiCacheReplicationGroup_updateParameterGroup
=== RUN   TestAccElastiCacheReplicationGroup_authToken
=== PAUSE TestAccElastiCacheReplicationGroup_authToken
=== RUN   TestAccElastiCacheReplicationGroup_upgrade_6_0_0
=== PAUSE TestAccElastiCacheReplicationGroup_upgrade_6_0_0
=== RUN   TestAccElastiCacheReplicationGroup_upgrade_5_27_0
=== PAUSE TestAccElastiCacheReplicationGroup_upgrade_5_27_0
=== RUN   TestAccElastiCacheReplicationGroup_upgrade_4_68_0
=== PAUSE TestAccElastiCacheReplicationGroup_upgrade_4_68_0
=== RUN   TestAccElastiCacheReplicationGroup_vpc
=== PAUSE TestAccElastiCacheReplicationGroup_vpc
=== RUN   TestAccElastiCacheReplicationGroup_multiAzNotInVPC
=== PAUSE TestAccElastiCacheReplicationGroup_multiAzNotInVPC
=== RUN   TestAccElastiCacheReplicationGroup_multiAzNotInVPC_repeated
=== PAUSE TestAccElastiCacheReplicationGroup_multiAzNotInVPC_repeated
=== RUN   TestAccElastiCacheReplicationGroup_multiAzInVPC
=== PAUSE TestAccElastiCacheReplicationGroup_multiAzInVPC
=== RUN   TestAccElastiCacheReplicationGroup_deprecatedAvailabilityZones_multiAzInVPC
=== PAUSE TestAccElastiCacheReplicationGroup_deprecatedAvailabilityZones_multiAzInVPC
=== RUN   TestAccElastiCacheReplicationGroup_ValidationMultiAz_noAutomaticFailover
=== PAUSE TestAccElastiCacheReplicationGroup_ValidationMultiAz_noAutomaticFailover
=== RUN   TestAccElastiCacheReplicationGroup_ipDiscovery
=== PAUSE TestAccElastiCacheReplicationGroup_ipDiscovery
=== RUN   TestAccElastiCacheReplicationGroup_networkType
=== PAUSE TestAccElastiCacheReplicationGroup_networkType
=== RUN   TestAccElastiCacheReplicationGroup_ClusterMode_basic
=== PAUSE TestAccElastiCacheReplicationGroup_ClusterMode_basic
=== RUN   TestAccElastiCacheReplicationGroup_ClusterMode_nonClusteredParameterGroup
=== PAUSE TestAccElastiCacheReplicationGroup_ClusterMode_nonClusteredParameterGroup
=== RUN   TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroups_scaleUp
=== PAUSE TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroups_scaleUp
=== RUN   TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroups_scaleDown
=== PAUSE TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroups_scaleDown
=== RUN   TestAccElastiCacheReplicationGroup_ClusterMode_updateReplicasPerNodeGroup
=== PAUSE TestAccElastiCacheReplicationGroup_ClusterMode_updateReplicasPerNodeGroup
=== RUN   TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroupsAndReplicasPerNodeGroup_scaleUp
=== PAUSE TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroupsAndReplicasPerNodeGroup_scaleUp
=== RUN   TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroupsAndReplicasPerNodeGroup_scaleDown
=== PAUSE TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroupsAndReplicasPerNodeGroup_scaleDown
=== RUN   TestAccElastiCacheReplicationGroup_ClusterMode_singleNode
=== PAUSE TestAccElastiCacheReplicationGroup_ClusterMode_singleNode
=== RUN   TestAccElastiCacheReplicationGroup_ClusterMode_nodeGroupConfiguration
=== PAUSE TestAccElastiCacheReplicationGroup_ClusterMode_nodeGroupConfiguration
=== RUN   TestAccElastiCacheReplicationGroup_ClusterMode_nodeGroupConfiguration_availabilityZones
=== PAUSE TestAccElastiCacheReplicationGroup_ClusterMode_nodeGroupConfiguration_availabilityZones
=== RUN   TestAccElastiCacheReplicationGroup_ClusterMode_updateFromDisabled_Compatible_Enabled
=== PAUSE TestAccElastiCacheReplicationGroup_ClusterMode_updateFromDisabled_Compatible_Enabled
=== RUN   TestAccElastiCacheReplicationGroup_cacheClustersConflictsWithReplicasPerNodeGroup
=== PAUSE TestAccElastiCacheReplicationGroup_cacheClustersConflictsWithReplicasPerNodeGroup
=== RUN   TestAccElastiCacheReplicationGroup_clusteringAndCacheNodesCausesError
=== PAUSE TestAccElastiCacheReplicationGroup_clusteringAndCacheNodesCausesError
=== RUN   TestAccElastiCacheReplicationGroup_enableSnapshotting
=== PAUSE TestAccElastiCacheReplicationGroup_enableSnapshotting
=== RUN   TestAccElastiCacheReplicationGroup_transitEncryptionWithAuthToken
=== PAUSE TestAccElastiCacheReplicationGroup_transitEncryptionWithAuthToken
=== RUN   TestAccElastiCacheReplicationGroup_transitEncryption5x
=== PAUSE TestAccElastiCacheReplicationGroup_transitEncryption5x
=== RUN   TestAccElastiCacheReplicationGroup_transitEncryption7x_basic
=== PAUSE TestAccElastiCacheReplicationGroup_transitEncryption7x_basic
=== RUN   TestAccElastiCacheReplicationGroup_transitEncryption7x_Enable
=== PAUSE TestAccElastiCacheReplicationGroup_transitEncryption7x_Enable
=== RUN   TestAccElastiCacheReplicationGroup_transitEncryption7x_Disable
=== PAUSE TestAccElastiCacheReplicationGroup_transitEncryption7x_Disable
=== RUN   TestAccElastiCacheReplicationGroup_Redis_enableAtRestEncryption
=== PAUSE TestAccElastiCacheReplicationGroup_Redis_enableAtRestEncryption
=== RUN   TestAccElastiCacheReplicationGroup_Valkey_disableAtRestEncryption
=== PAUSE TestAccElastiCacheReplicationGroup_Valkey_disableAtRestEncryption
=== RUN   TestAccElastiCacheReplicationGroup_useCMKKMSKeyID
=== PAUSE TestAccElastiCacheReplicationGroup_useCMKKMSKeyID
=== RUN   TestAccElastiCacheReplicationGroup_NumberCacheClusters_basic
=== PAUSE TestAccElastiCacheReplicationGroup_NumberCacheClusters_basic
=== RUN   TestAccElastiCacheReplicationGroup_NumberCacheClusters_autoFailoverDisabled
=== PAUSE TestAccElastiCacheReplicationGroup_NumberCacheClusters_autoFailoverDisabled
=== RUN   TestAccElastiCacheReplicationGroup_NumberCacheClusters_autoFailoverEnabled
=== PAUSE TestAccElastiCacheReplicationGroup_NumberCacheClusters_autoFailoverEnabled
=== RUN   TestAccElastiCacheReplicationGroup_autoFailoverEnabled_validateNumberCacheClusters
=== PAUSE TestAccElastiCacheReplicationGroup_autoFailoverEnabled_validateNumberCacheClusters
=== RUN   TestAccElastiCacheReplicationGroup_NumberCacheClusters_multiAZEnabled
=== PAUSE TestAccElastiCacheReplicationGroup_NumberCacheClusters_multiAZEnabled
=== RUN   TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappears_noChange
=== PAUSE TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappears_noChange
=== RUN   TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappears_addMemberCluster
=== PAUSE TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappears_addMemberCluster
=== RUN   TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappearsRemoveMemberCluster_atTargetSize
=== PAUSE TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappearsRemoveMemberCluster_atTargetSize
=== RUN   TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappearsRemoveMemberCluster_scaleDown
=== PAUSE TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappearsRemoveMemberCluster_scaleDown
=== RUN   TestAccElastiCacheReplicationGroup_tags
=== PAUSE TestAccElastiCacheReplicationGroup_tags
=== RUN   TestAccElastiCacheReplicationGroup_TagWithOtherModification_version
=== PAUSE TestAccElastiCacheReplicationGroup_TagWithOtherModification_version
=== RUN   TestAccElastiCacheReplicationGroup_TagWithOtherModification_numCacheClusters
=== PAUSE TestAccElastiCacheReplicationGroup_TagWithOtherModification_numCacheClusters
=== RUN   TestAccElastiCacheReplicationGroup_finalSnapshot
=== PAUSE TestAccElastiCacheReplicationGroup_finalSnapshot
=== RUN   TestAccElastiCacheReplicationGroup_autoMinorVersionUpgrade
=== PAUSE TestAccElastiCacheReplicationGroup_autoMinorVersionUpgrade
=== RUN   TestAccElastiCacheReplicationGroup_Validation_noNodeType
=== PAUSE TestAccElastiCacheReplicationGroup_Validation_noNodeType
=== RUN   TestAccElastiCacheReplicationGroup_Validation_globalReplicationGroupIdAndNodeType
=== PAUSE TestAccElastiCacheReplicationGroup_Validation_globalReplicationGroupIdAndNodeType
=== RUN   TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_basic
=== PAUSE TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_basic
=== RUN   TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_full
=== PAUSE TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_full
=== RUN   TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_disappears
=== PAUSE TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_disappears
=== RUN   TestAccElastiCacheReplicationGroup_GlobalReplicationGroupIDClusterMode_basic
=== PAUSE TestAccElastiCacheReplicationGroup_GlobalReplicationGroupIDClusterMode_basic
=== RUN   TestAccElastiCacheReplicationGroup_GlobalReplicationGroupIDClusterModeValidation_numNodeGroupsOnSecondary
=== PAUSE TestAccElastiCacheReplicationGroup_GlobalReplicationGroupIDClusterModeValidation_numNodeGroupsOnSecondary
=== RUN   TestAccElastiCacheReplicationGroup_dataTiering
=== PAUSE TestAccElastiCacheReplicationGroup_dataTiering
=== RUN   TestAccElastiCacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_ClusterMode_Disabled
=== PAUSE TestAccElastiCacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_ClusterMode_Disabled
=== RUN   TestAccElastiCacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_ClusterMode_Enabled
=== PAUSE TestAccElastiCacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_ClusterMode_Enabled
=== RUN   TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Valkey7
=== PAUSE TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Valkey7
=== RUN   TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Valkey7_3NodeGroups
=== PAUSE TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Valkey7_3NodeGroups
=== RUN   TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Valkey8
=== PAUSE TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Valkey8
=== RUN   TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Redis7
=== PAUSE TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Redis7
=== RUN   TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Redis7_3NodeGroups
=== PAUSE TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Redis7_3NodeGroups
=== CONT  TestAccElastiCacheReplicationGroupDataSource_basic
=== CONT  TestAccElastiCacheReplicationGroup_Validation_globalReplicationGroupIdAndNodeType
--- PASS: TestAccElastiCacheReplicationGroupDataSource_basic (791.63s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroups_scaleDown
--- PASS: TestAccElastiCacheReplicationGroup_Validation_globalReplicationGroupIdAndNodeType (1173.68s)
=== CONT  TestAccElastiCacheReplicationGroup_Validation_noNodeType
--- PASS: TestAccElastiCacheReplicationGroup_Validation_noNodeType (8.91s)
=== CONT  TestAccElastiCacheReplicationGroup_autoMinorVersionUpgrade
--- PASS: TestAccElastiCacheReplicationGroup_autoMinorVersionUpgrade (754.10s)
=== CONT  TestAccElastiCacheReplicationGroup_finalSnapshot
--- PASS: TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroups_scaleDown (1777.53s)
=== CONT  TestAccElastiCacheReplicationGroup_TagWithOtherModification_numCacheClusters
--- PASS: TestAccElastiCacheReplicationGroup_finalSnapshot (1012.36s)
=== CONT  TestAccElastiCacheReplicationGroup_TagWithOtherModification_version
--- PASS: TestAccElastiCacheReplicationGroup_TagWithOtherModification_numCacheClusters (1089.22s)
=== CONT  TestAccElastiCacheReplicationGroup_tags
--- PASS: TestAccElastiCacheReplicationGroup_tags (888.29s)
=== CONT  TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappearsRemoveMemberCluster_scaleDown
--- PASS: TestAccElastiCacheReplicationGroup_TagWithOtherModification_version (1782.04s)
=== CONT  TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappearsRemoveMemberCluster_atTargetSize
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappearsRemoveMemberCluster_atTargetSize (972.57s)
=== CONT  TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappears_addMemberCluster
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappearsRemoveMemberCluster_scaleDown (1366.37s)
=== CONT  TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappears_noChange
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappears_addMemberCluster (1347.05s)
=== CONT  TestAccElastiCacheReplicationGroup_NumberCacheClusters_multiAZEnabled
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappears_noChange (1307.13s)
=== CONT  TestAccElastiCacheReplicationGroup_updateNodeSize
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClusters_multiAZEnabled (1447.70s)
=== CONT  TestAccElastiCacheReplicationGroup_autoFailoverEnabled_validateNumberCacheClusters
--- PASS: TestAccElastiCacheReplicationGroup_autoFailoverEnabled_validateNumberCacheClusters (2.27s)
=== CONT  TestAccElastiCacheReplicationGroup_NumberCacheClusters_autoFailoverEnabled
--- PASS: TestAccElastiCacheReplicationGroup_updateNodeSize (1528.75s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroups_scaleUp
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClusters_autoFailoverEnabled (1489.05s)
=== CONT  TestAccElastiCacheReplicationGroup_NumberCacheClusters_autoFailoverDisabled
--- PASS: TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroups_scaleUp (1447.84s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterMode_nonClusteredParameterGroup
--- PASS: TestAccElastiCacheReplicationGroup_ClusterMode_nonClusteredParameterGroup (773.07s)
=== CONT  TestAccElastiCacheReplicationGroup_clusteringAndCacheNodesCausesError
--- PASS: TestAccElastiCacheReplicationGroup_clusteringAndCacheNodesCausesError (1.92s)
=== CONT  TestAccElastiCacheReplicationGroup_cacheClustersConflictsWithReplicasPerNodeGroup
--- PASS: TestAccElastiCacheReplicationGroup_cacheClustersConflictsWithReplicasPerNodeGroup (1.79s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterMode_basic
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClusters_autoFailoverDisabled (1370.72s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterMode_updateFromDisabled_Compatible_Enabled
--- PASS: TestAccElastiCacheReplicationGroup_ClusterMode_basic (820.50s)
=== CONT  TestAccElastiCacheReplicationGroup_networkType
--- PASS: TestAccElastiCacheReplicationGroup_networkType (922.77s)
=== CONT  TestAccElastiCacheReplicationGroup_ipDiscovery
--- PASS: TestAccElastiCacheReplicationGroup_ipDiscovery (900.08s)
=== CONT  TestAccElastiCacheReplicationGroup_ValidationMultiAz_noAutomaticFailover
--- PASS: TestAccElastiCacheReplicationGroup_ValidationMultiAz_noAutomaticFailover (2.10s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterMode_nodeGroupConfiguration_availabilityZones
--- PASS: TestAccElastiCacheReplicationGroup_ClusterMode_updateFromDisabled_Compatible_Enabled (2637.57s)
=== CONT  TestAccElastiCacheReplicationGroup_deprecatedAvailabilityZones_multiAzInVPC
--- PASS: TestAccElastiCacheReplicationGroup_ClusterMode_nodeGroupConfiguration_availabilityZones (804.07s)
=== CONT  TestAccElastiCacheReplicationGroup_enableSnapshotting
--- PASS: TestAccElastiCacheReplicationGroup_deprecatedAvailabilityZones_multiAzInVPC (728.27s)
=== CONT  TestAccElastiCacheReplicationGroup_multiAzInVPC
--- PASS: TestAccElastiCacheReplicationGroup_enableSnapshotting (691.46s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterMode_nodeGroupConfiguration
--- PASS: TestAccElastiCacheReplicationGroup_multiAzInVPC (830.33s)
=== CONT  TestAccElastiCacheReplicationGroup_multiAzNotInVPC_repeated
--- PASS: TestAccElastiCacheReplicationGroup_ClusterMode_nodeGroupConfiguration (805.59s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterMode_singleNode
--- PASS: TestAccElastiCacheReplicationGroup_multiAzNotInVPC_repeated (804.67s)
=== CONT  TestAccElastiCacheReplicationGroup_NumberCacheClusters_basic
--- PASS: TestAccElastiCacheReplicationGroup_ClusterMode_singleNode (622.60s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroupsAndReplicasPerNodeGroup_scaleDown
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClusters_basic (1427.55s)
=== CONT  TestAccElastiCacheReplicationGroup_useCMKKMSKeyID
--- PASS: TestAccElastiCacheReplicationGroup_useCMKKMSKeyID (656.79s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroupsAndReplicasPerNodeGroup_scaleUp
--- PASS: TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroupsAndReplicasPerNodeGroup_scaleDown (2165.86s)
=== CONT  TestAccElastiCacheReplicationGroup_Valkey_disableAtRestEncryption
--- PASS: TestAccElastiCacheReplicationGroup_Valkey_disableAtRestEncryption (713.87s)
=== CONT  TestAccElastiCacheReplicationGroup_Redis_enableAtRestEncryption
--- PASS: TestAccElastiCacheReplicationGroup_Redis_enableAtRestEncryption (733.70s)
=== CONT  TestAccElastiCacheReplicationGroup_transitEncryption7x_Disable
--- PASS: TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroupsAndReplicasPerNodeGroup_scaleUp (1913.37s)
=== CONT  TestAccElastiCacheReplicationGroup_transitEncryption7x_Enable
--- PASS: TestAccElastiCacheReplicationGroup_transitEncryption7x_Disable (1910.54s)
=== CONT  TestAccElastiCacheReplicationGroup_transitEncryption7x_basic
--- PASS: TestAccElastiCacheReplicationGroup_transitEncryption7x_Enable (1868.93s)
=== CONT  TestAccElastiCacheReplicationGroup_transitEncryption5x
--- PASS: TestAccElastiCacheReplicationGroup_transitEncryption7x_basic (667.90s)
=== CONT  TestAccElastiCacheReplicationGroup_transitEncryptionWithAuthToken
--- PASS: TestAccElastiCacheReplicationGroup_transitEncryptionWithAuthToken (677.49s)
=== CONT  TestAccElastiCacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_ClusterMode_Disabled
--- PASS: TestAccElastiCacheReplicationGroup_transitEncryption5x (1265.23s)
=== CONT  TestAccElastiCacheReplicationGroup_upgrade_5_27_0
--- PASS: TestAccElastiCacheReplicationGroup_upgrade_5_27_0 (792.45s)
=== CONT  TestAccElastiCacheReplicationGroup_multiAzNotInVPC
--- PASS: TestAccElastiCacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_ClusterMode_Disabled (944.29s)
=== CONT  TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Redis7_3NodeGroups
--- PASS: TestAccElastiCacheReplicationGroup_multiAzNotInVPC (834.68s)
=== CONT  TestAccElastiCacheReplicationGroup_upgrade_6_0_0
--- PASS: TestAccElastiCacheReplicationGroup_upgrade_6_0_0 (729.64s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterMode_updateReplicasPerNodeGroup
--- PASS: TestAccElastiCacheReplicationGroup_ClusterMode_updateReplicasPerNodeGroup (1506.54s)
=== CONT  TestAccElastiCacheReplicationGroup_authToken
--- PASS: TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Redis7_3NodeGroups (3005.67s)
=== CONT  TestAccElastiCacheReplicationGroup_updateParameterGroup
--- PASS: TestAccElastiCacheReplicationGroup_updateParameterGroup (827.46s)
=== CONT  TestAccElastiCacheReplicationGroup_upgrade_4_68_0
--- PASS: TestAccElastiCacheReplicationGroup_authToken (1349.38s)
=== CONT  TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Redis7
--- PASS: TestAccElastiCacheReplicationGroup_upgrade_4_68_0 (783.92s)
=== CONT  TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Valkey7_3NodeGroups
--- PASS: TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Valkey7_3NodeGroups (2977.53s)
=== CONT  TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Valkey7
--- PASS: TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Redis7 (3812.47s)
=== CONT  TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Valkey8
--- PASS: TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Valkey8 (1781.22s)
=== CONT  TestAccElastiCacheReplicationGroup_OutOfBandUpgrade
--- PASS: TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Valkey7 (2681.82s)
=== CONT  TestAccElastiCacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_ClusterMode_Enabled
--- PASS: TestAccElastiCacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_ClusterMode_Enabled (950.37s)
=== CONT  TestAccElastiCacheReplicationGroup_vpc
--- PASS: TestAccElastiCacheReplicationGroup_OutOfBandUpgrade (1605.07s)
=== CONT  TestAccElastiCacheReplicationGroup_updateUserGroups
--- PASS: TestAccElastiCacheReplicationGroup_vpc (781.83s)
=== CONT  TestAccElastiCacheReplicationGroup_disappears
--- PASS: TestAccElastiCacheReplicationGroup_updateUserGroups (866.48s)
=== CONT  TestAccElastiCacheReplicationGroup_updateMaintenanceWindow
--- PASS: TestAccElastiCacheReplicationGroup_disappears (670.63s)
=== CONT  TestAccElastiCacheReplicationGroup_Engine_RedisToValkey
--- PASS: TestAccElastiCacheReplicationGroup_updateMaintenanceWindow (742.52s)
=== CONT  TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_disappears
--- PASS: TestAccElastiCacheReplicationGroup_Engine_RedisToValkey (1611.88s)
=== CONT  TestAccElastiCacheReplicationGroup_EngineVersion_6xToRealVersion
--- PASS: TestAccElastiCacheReplicationGroup_EngineVersion_6xToRealVersion (801.50s)
=== CONT  TestAccElastiCacheReplicationGroup_GlobalReplicationGroupIDClusterMode_basic
--- PASS: TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_disappears (3425.90s)
=== CONT  TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_basic
--- PASS: TestAccElastiCacheReplicationGroup_GlobalReplicationGroupIDClusterMode_basic (3787.42s)
=== CONT  TestAccElastiCacheReplicationGroup_dataTiering
--- PASS: TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_basic (2636.43s)
=== CONT  TestAccElastiCacheReplicationGroup_Redis_basic_v5
--- PASS: TestAccElastiCacheReplicationGroup_dataTiering (608.14s)
=== CONT  TestAccElastiCacheReplicationGroup_GlobalReplicationGroupIDClusterModeValidation_numNodeGroupsOnSecondary
--- PASS: TestAccElastiCacheReplicationGroup_Redis_basic_v5 (664.23s)
=== CONT  TestAccElastiCacheReplicationGroup_updateDescription
--- PASS: TestAccElastiCacheReplicationGroup_updateDescription (683.08s)
=== CONT  TestAccElastiCacheReplicationGroup_Redis_EngineVersion_v7
--- PASS: TestAccElastiCacheReplicationGroup_GlobalReplicationGroupIDClusterModeValidation_numNodeGroupsOnSecondary (1387.67s)
=== CONT  TestAccElastiCacheReplicationGroup_EngineVersion_update
--- PASS: TestAccElastiCacheReplicationGroup_Redis_EngineVersion_v7 (662.70s)
=== CONT  TestAccElastiCacheReplicationGroup_uppercase
--- PASS: TestAccElastiCacheReplicationGroup_uppercase (678.01s)
=== CONT  TestAccElastiCacheReplicationGroupDataSource_Engine_Redis_LogDeliveryConfigurations
--- PASS: TestAccElastiCacheReplicationGroupDataSource_Engine_Redis_LogDeliveryConfigurations (776.61s)
=== CONT  TestAccElastiCacheReplicationGroup_Valkey_basic
--- PASS: TestAccElastiCacheReplicationGroup_Valkey_basic (785.96s)
=== CONT  TestAccElastiCacheReplicationGroup_Redis_basic
--- PASS: TestAccElastiCacheReplicationGroup_Redis_basic (703.56s)
=== CONT  TestAccElastiCacheReplicationGroupDataSource_clusterMode
--- PASS: TestAccElastiCacheReplicationGroupDataSource_clusterMode (962.46s)
=== CONT  TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_full
--- PASS: TestAccElastiCacheReplicationGroup_EngineVersion_update (5552.17s)
=== CONT  TestAccElastiCacheReplicationGroupDataSource_multiAZ
--- PASS: TestAccElastiCacheReplicationGroupDataSource_multiAZ (832.05s)
--- PASS: TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_full (3412.01s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elasticache	52904.768s

```

File: internal/service/elasticache/replication_group.go (hunk 4 above)
Comment (trevorbonas) [inline internal/service/elasticache/replication_group.go]:
```suggestion
		// Scaling down scenario.
```

Comment (sukumaar) [reply internal/service/elasticache/replication_group.go]: Trivial, closing this due to nature of code change.

**Review by YakDriver — APPROVED** [review]
LGTM 🎉 

```console
% make t T='^TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Valkey7$$|^TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Valkey7_3NodeGroups$$|^TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Valkey8$$|^TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Redis7ToValkey8$$|^TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Redis7ToValkey8_3NodeGroups$$' K=elasticache
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 f-elasticache-rg-down-scaling 🌿...
TF_ACC=1 go1.25.6 test ./internal/service/elasticache/... -v -count 1 -parallel 20 -run='^TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Valkey7$|^TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Valkey7_3NodeGroups$|^TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Valkey8$|^TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Redis7ToValkey8$|^TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Redis7ToValkey8_3NodeGroups$'  -timeout 360m -vet=off
2026/01/30 17:02:19 Creating Terraform AWS Provider (SDKv2-style)...
2026/01/30 17:02:19 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Valkey7
=== PAUSE TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Valkey7
=== RUN   TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Valkey7_3NodeGroups
=== PAUSE TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Valkey7_3NodeGroups
=== RUN   TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Valkey8
=== PAUSE TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Valkey8
=== RUN   TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Redis7ToValkey8
=== PAUSE TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Redis7ToValkey8
=== RUN   TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Redis7ToValkey8_3NodeGroups
=== PAUSE TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Redis7ToValkey8_3NodeGroups
=== CONT  TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Valkey7
=== CONT  TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Redis7ToValkey8
=== CONT  TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Valkey8
=== CONT  TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Redis7ToValkey8_3NodeGroups
=== CONT  TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Valkey7_3NodeGroups
--- PASS: TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Valkey8 (1759.35s)
--- PASS: TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Valkey7_3NodeGroups (2967.20s)
--- PASS: TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Redis7ToValkey8_3NodeGroups (3262.45s)
--- PASS: TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Valkey7 (3334.16s)
--- PASS: TestAccElastiCacheReplicationGroup_RemoveNodeGroups_Redis7ToValkey8 (3792.48s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elasticache	3799.197s
```

**Comment by sukumaar** [comment]
Thanks a lot @YakDriver @jar-b

**Comment by YakDriver** [comment]
@sukumaar Thank you for the contribution!
