### PR TITLE
resource/aws_api_gateway_method_settings: Prevent unexpected errors during creation and deletion

### LINKED ISSUE #13985: Unexpected provider exception when creating "aws_api_gateway_method_settings"
_This issue was originally opened by @FlokiOo as hashicorp/terraform#25404. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._
    
<hr>
    
Hey,

we try to enable Logging and Metrics for our API-Gateway and added the following resource:

```
resource "aws_api_gateway_method_settings" "settings" {
  rest_api_id = aws_api_gateway_rest_api.rest_api.id
  stage_name = var.api_gateway_stage
  method_path = "${aws_api_gateway_resource.resource.path_part}/${aws_api_gateway_method.method.http_method}"
  settings {
    metrics_enabled = true
    logging_level = "ERROR"
    data_trace_enabled = true
  }
}
```

Unfortunately this throws the following exception when it gets executed:

```
module.datalake_zendesk.module.apigateway_instances.aws_api_gateway_method_settings.settings,
provider "aws" produced an unexpected new value for was present, but now
absent.

```
Any idea what could cause this issue and how we can fix it?

Greetings Dave

### PR DESCRIPTION
**Pull request by bflad**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #13985
Reference: https://github.com/hashicorp/terraform-provider-aws/issues/16796

Fixing this as part of API Gateway service spike work. As mentioned in the issue this will not help mitigate the cause of the problem, but will at least give a better error message.

Output from acceptance testing:

```
--- PASS: TestAccAWSAPIGatewayMethodSettings_basic (25.35s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_disappears (247.81s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_Settings_CacheDataEncrypted (147.06s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_Settings_CacheTtlInSeconds (340.17s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_Settings_CachingEnabled (448.46s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_Settings_DataTraceEnabled (216.61s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_Settings_LoggingLevel (55.96s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_Settings_MetricsEnabled (397.43s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_Settings_Multiple (692.67s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_Settings_RequireAuthorizationForCacheControl (178.96s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_Settings_ThrottlingBurstLimit (118.97s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_Settings_ThrottlingBurstLimitDisabledByDefault (86.39s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_Settings_ThrottlingRateLimit (515.72s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_Settings_ThrottlingRateLimitDisabledByDefault (484.35s)
--- PASS: TestAccAWSAPIGatewayMethodSettings_Settings_UnauthorizedCacheControlHeaderStrategy (312.16s)
```

### CODE REVIEW

File: aws/resource_aws_api_gateway_method_settings.go [hunk 1]
```diff
@@ -131,26 +136,28 @@ func flattenAwsApiGatewayMethodSettings(settings *apigateway.MethodSetting) []in
...
+		return fmt.Errorf("error getting API Gateway Stage Method Settings (%s): %w", d.Id(), err)
 	}
-	log.Printf("[DEBUG] Received API Gateway Stage: %s", stage)
 
 	methodPath := d.Get("method_path").(string)
 	settings, ok := stage.MethodSettings[methodPath]
-	if !ok {
-		log.Printf("[WARN] API Gateway Method Settings for %q not found, removing", methodPath)
+
+	if !d.IsNewResource() && !ok {
```
Comment (anGie44) [inline aws/resource_aws_api_gateway_method_settings.go:159]: 😎 😎

**Review by anGie44 — APPROVED** [review]
