### PR TITLE
resource/aws_api_gateway_rest_api: Fix disable_execute_api_endpoint and endpoint_configuration vpc_endpoint_ids handling with OpenAPI specification import (body argument)

### LINKED ISSUE #13841: aws_api_gateway_rest_api private API does not set VPC Endpoint association or policy until SECOND apply.
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.14
AWS provider 2.67.0

### Affected Resource(s)

* aws_api_gateway_rest_api

### Terraform Configuration Files

```hcl
resource "aws_api_gateway_rest_api" "service_api_private_vpce" {
  count = "${local.private_vpce ? 1 : 0}"
  name = "${var.api_name}"

  body = "${var.api_openapi_yaml == "" ? data.template_file.openapi_yaml.rendered : var.api_openapi_yaml}"

  policy = "${data.template_file.policy.rendered}"

  endpoint_configuration {
  #
  # This will always be PRIVATE here
  #
    types = ["${local.endpoint_type}"]
    vpc_endpoint_ids = ["${module.environment_vpc_endpoint_id.ssm_parameter_value}"]
  }
  lifecycle {
      #
      # Plans have a permanent difference here!
      #
      ignore_changes = [ "binary_media_types" ]
  }
}
```
### Expected Behavior

API should be created with endpoint type PRIVATE, associated with the passed VPCE ID and with
the provided policy attached

### Actual Behavior

API is created as PRIVATE but without the VPCE association or the policy. Then running `terraform apply` a second time, the policy and the VPCE association are set

### Steps to Reproduce

- create the necessary infrastructure to have a VPCE associated with the API Gateway
- create a terraform config file with the contents as provided by the plan output below, substituting
the VPCE ID in your config for the one currently in the content below
- `terraform apply`
- examine the API in the API Gateway console - no policy, no VPCE
- `terraform apply`
- examine the API in the API Gateway console - policy and VPCE exist

### Important Factoids

While the above resource property settings use a lot of variables, the plan output shows that the values have been correctly resolved

```
  + module.main.module.console_service_api.module.api.aws_api_gateway_rest_api.service_api_private_vpce
      id:                                                    <computed>
      api_key_source:                                        "HEADER"
      arn:                                                   <computed>
      body:                                                  "---\nswagger: \"2.0\"\ninfo:\n  version: \"2019-02-19T16:23:40Z\"\n  title: \"Assure-Platform-Console-Service-private-1\"\nschemes:\n- \"https\"\npaths:\n  /:\n    get:\n      produces:\n      - \"application/json\"\n      responses:\n        200:\n          description: \"200 response\"\n          schema:\n            $ref: \"#/definitions/Empty\"\n      x-amazon-apigateway-integration:\n        uri: \"arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:665158502186:function:${stageVariables.integrationLambda}/invocations\"\n        credentials: \"arn:aws:iam::665158502186:role/${stageVariables.integrationLambdaExecRole}\"\n        responses:\n          default:\n            statusCode: \"200\"\n        passthroughBehavior: \"when_no_match\"\n        httpMethod: \"POST\"\n        contentHandling: \"CONVERT_TO_TEXT\"\n        type: \"aws_proxy\"\n    options:\n      consumes:\n      - \"application/json\"\n      produces:\n      - \"application/json\"\n      responses:\n        200:\n          description: \"200 response\"\n          schema:\n            $ref: \"#/definitions/Empty\"\n          headers:\n            Access-Control-Allow-Origin:\n              type: \"string\"\n            Access-Control-Allow-Methods:\n              type: \"string\"\n            Access-Control-Allow-Headers:\n              type: \"string\"\n      x-amazon-apigateway-integration:\n        responses:\n          default:\n            statusCode: \"200\"\n            responseParameters:\n              method.response.header.Access-Control-Allow-Methods: \"'POST,OPTIONS'\"\n              method.response.header.Access-Control-Allow-Headers: \"'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'\"\n              method.response.header.Access-Control-Allow-Origin: \"'*'\"\n        requestTemplates:\n          application/json: \"{\\\"statusCode\\\": 200}\"\n        passthroughBehavior: \"when_no_match\"\n        type: \"mock\"\ndefinitions:\n  Empty:\n    type: \"object\"\n    title: \"Empty Schema\"\n\n"
      created_date:                                          <computed>
      endpoint_configuration.#:                              "1"
      endpoint_configuration.0.types.#:                      "1"
      endpoint_configuration.0.types.0:                      "PRIVATE"
      endpoint_configuration.0.vpc_endpoint_ids.#:           "1"
      endpoint_configuration.0.vpc_endpoint_ids.1596079509:  "vpce-0efe2662207bd63a0"
      execution_arn:                                         <computed>
      minimum_compression_size:                              "-1"
      name:                                                  "Assure-Platform-Console-Service-private-1"
      policy:                                                "{\n    \"Version\": \"2012-10-17\",\n    \"Statement\": [\n        {\n            \"Effect\": \"Deny\",\n            \"Principal\": \"*\",\n            \"Action\": \"execute-api:Invoke\",\n            \"Resource\": \"execute-api:/*\",\n            \"Condition\": {\n                \"StringNotEquals\": {\n                    \"aws:sourceVpce\": \"vpce-0efe2662207bd63a0\"\n                }\n            }\n        },\n        {\n            \"Effect\": \"Allow\",\n            \"Principal\": \"*\",\n            \"Action\": \"execute-api:Invoke\",\n            \"Resource\": \"execute-api:/*\"\n        }\n    ]\n}"
      root_resource_id:                                      <computed>
```

That VPCE ID has been confirmed to exist and be active at the time of the apply, and, when in the API Gateway console, is available for attachment to the API

On running `terraform apply` the second time (immediately after the first attempt that fails to set the policy and VPCE association), I get a diff for the VPCE and the policy.

```
  ~ module.main.module.console_service_api.module.api.aws_api_gateway_rest_api.service_api_private_vpce
      endpoint_configuration.0.vpc_endpoint_ids.#:           "0" => "1"
      endpoint_configuration.0.vpc_endpoint_ids.1596079509:  "" => "vpce-0efe2662207bd63a0"
      policy:                                                "" => "{\n    \"Version\": \"2012-10-17\",\n    \"Statement\": [\n        {\n            \"Effect\": \"Deny\",\n            \"Principal\": \"*\",\n            \"Action\": \"execute-api:Invoke\",\n            \"Resource\": \"execute-api:/*\",\n            \"Condition\": {\n                \"StringNotEquals\": {\n                    \"aws:sourceVpce\": \"vpce-0efe2662207bd63a0\"\n                }\n            }\n        },\n        {\n            \"Effect\": \"Allow\",\n            \"Principal\": \"*\",\n            \"Action\": \"execute-api:Invoke\",\n            \"Resource\": \"execute-api:/*\"\n        }\n    ]\n}"
```

Letting THAT run through, adds the VPCE association and the policy.

### PR DESCRIPTION
**Pull request by bflad**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #13841

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
* resource/aws_api_gateway_rest_api: Fix `disable_execute_api_endpoint` and `endpoint_configuration` `vpc_endpoint_ids` handling with OpenAPI specification import (`body` argument)
```

Before code updates, these new acceptance tests show how the Terraform configuration value would not be applied if an OpenAPI specification was imported:

```
=== CONT  TestAccAWSAPIGatewayRestApi_DisableExecuteApiEndpoint_OverrideBody
    resource_aws_api_gateway_rest_api_test.go:847: Step 1/4 error: Check failed: 1 error occurred:
        	* Check 2/2 error: aws_api_gateway_rest_api.test: Attribute 'disable_execute_api_endpoint' expected "false", got "true"

--- FAIL: TestAccAWSAPIGatewayRestApi_DisableExecuteApiEndpoint_OverrideBody (10.30s)

=== CONT  TestAccAWSAPIGatewayRestApi_EndpointConfiguration_VpcEndpointIds_OverrideBody
    resource_aws_api_gateway_rest_api_test.go:369: Step 1/2 error: After applying this test step and performing a `terraform refresh`, the plan was not empty.
        stdout

        An execution plan has been generated and is shown below.
        Resource actions are indicated with the following symbols:
          ~ update in-place

        Terraform will perform the following actions:

          # aws_api_gateway_rest_api.test will be updated in-place
          ~ resource "aws_api_gateway_rest_api" "test" {
                id                           = "m9ajz6izjl"
                name                         = "tf-acc-test-6139822644948363723"
                tags                         = {}
                # (9 unchanged attributes hidden)

              ~ endpoint_configuration {
                  ~ vpc_endpoint_ids = [
                      + "vpce-0ba0b61be45886a6f",
                      - "vpce-0ee1a2ccd6af8f011",
                    ]
                    # (1 unchanged attribute hidden)
                }
            }

        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccAWSAPIGatewayRestApi_EndpointConfiguration_VpcEndpointIds_OverrideBody (190.95s)
```

Before code updates, these new acceptance tests show how the Terraform resource would report an unexpected difference for missing configurations that were imported by the OpenAPI specification:

```
=== CONT  TestAccAWSAPIGatewayRestApi_DisableExecuteApiEndpoint_SetByBody
    resource_aws_api_gateway_rest_api_test.go:890: Step 1/2 error: After applying this test step, the plan was not empty.
        stdout:

        An execution plan has been generated and is shown below.
        Resource actions are indicated with the following symbols:
          ~ update in-place

        Terraform will perform the following actions:

          # aws_api_gateway_rest_api.test will be updated in-place
          ~ resource "aws_api_gateway_rest_api" "test" {
              ~ disable_execute_api_endpoint = true -> false
                id                           = "c2t6iky152"
                name                         = "tf-acc-test-8877194198775672292"
                # (8 unchanged attributes hidden)

                # (1 unchanged block hidden)
            }

        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccAWSAPIGatewayRestApi_DisableExecuteApiEndpoint_SetByBody (11.03s)

=== CONT  TestAccAWSAPIGatewayRestApi_EndpointConfiguration_VpcEndpointIds_SetByBody
    resource_aws_api_gateway_rest_api_test.go:415: Step 1/2 error: After applying this test step, the plan was not empty.
        stdout:

        An execution plan has been generated and is shown below.
        Resource actions are indicated with the following symbols:
          ~ update in-place

        Terraform will perform the following actions:

          # aws_api_gateway_rest_api.test will be updated in-place
          ~ resource "aws_api_gateway_rest_api" "test" {
                id                           = "adeg2zcky2"
                name                         = "tf-acc-test-7848512816247428885"
                # (9 unchanged attributes hidden)

              ~ endpoint_configuration {
                  ~ vpc_endpoint_ids = [
                      - "vpce-0653ca468e4c6ba4a",
                    ]
                    # (1 unchanged attribute hidden)
                }
            }

        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccAWSAPIGatewayRestApi_EndpointConfiguration_VpcEndpointIds_SetByBody (150.67s)
```

Output from acceptance testing:

```
--- PASS: TestAccAWSAPIGatewayRestApi_ApiKeySource (30.53s)
--- PASS: TestAccAWSAPIGatewayRestApi_ApiKeySource_OverrideBody (37.78s)
--- PASS: TestAccAWSAPIGatewayRestApi_ApiKeySource_SetByBody (15.25s)
--- PASS: TestAccAWSAPIGatewayRestApi_basic (669.92s)
--- PASS: TestAccAWSAPIGatewayRestApi_BinaryMediaTypes (34.56s)
--- PASS: TestAccAWSAPIGatewayRestApi_BinaryMediaTypes_OverrideBody (34.23s)
--- PASS: TestAccAWSAPIGatewayRestApi_BinaryMediaTypes_SetByBody (514.96s)
--- PASS: TestAccAWSAPIGatewayRestApi_Body (38.01s)
--- PASS: TestAccAWSAPIGatewayRestApi_Description (23.87s)
--- PASS: TestAccAWSAPIGatewayRestApi_Description_OverrideBody (60.58s)
--- PASS: TestAccAWSAPIGatewayRestApi_Description_SetByBody (92.79s)
--- PASS: TestAccAWSAPIGatewayRestApi_DisableExecuteApiEndpoint (3442.94s)
--- PASS: TestAccAWSAPIGatewayRestApi_DisableExecuteApiEndpoint_OverrideBody (2292.47s)
--- PASS: TestAccAWSAPIGatewayRestApi_DisableExecuteApiEndpoint_SetByBody (1083.96s)
--- PASS: TestAccAWSAPIGatewayRestApi_disappears (529.45s)
--- PASS: TestAccAWSAPIGatewayRestApi_EndpointConfiguration (1034.47s)
--- PASS: TestAccAWSAPIGatewayRestApi_EndpointConfiguration_Private (15.42s)
--- PASS: TestAccAWSAPIGatewayRestApi_EndpointConfiguration_VpcEndpointIds (330.11s)
--- PASS: TestAccAWSAPIGatewayRestApi_EndpointConfiguration_VpcEndpointIds_OverrideBody (205.73s)
--- PASS: TestAccAWSAPIGatewayRestApi_EndpointConfiguration_VpcEndpointIds_SetByBody (159.85s)
--- PASS: TestAccAWSAPIGatewayRestApi_MinimumCompressionSize (39.32s)
--- PASS: TestAccAWSAPIGatewayRestApi_MinimumCompressionSize_OverrideBody (1278.64s)
--- PASS: TestAccAWSAPIGatewayRestApi_MinimumCompressionSize_SetByBody (753.00s)
--- PASS: TestAccAWSAPIGatewayRestApi_Name_OverrideBody (2212.45s)
--- PASS: TestAccAWSAPIGatewayRestApi_Parameters (948.67s)
--- PASS: TestAccAWSAPIGatewayRestApi_Policy (28.00s)
--- PASS: TestAccAWSAPIGatewayRestApi_Policy_OverrideBody (80.78s)
--- PASS: TestAccAWSAPIGatewayRestApi_Policy_SetByBody (1967.74s)
--- PASS: TestAccAWSAPIGatewayRestApi_tags (1413.12s)
```

### CODE REVIEW

File: aws/resource_aws_api_gateway_rest_api_test.go [hunk 1]
```diff
@@ -1176,13 +1310,96 @@ resource "aws_api_gateway_rest_api" "test" {
...
+  name                         = %[1]q
+}
+`, rName, disableExecuteApiEndpoint)
+}
+
+func testAccAWSAPIGatewayRestAPIConfigDisableExecuteApiEndpointOverrideBody(rName string, configDisableExecuteApiEndpoint bool, bodyDisableExecuteApiEndpoint bool) string {
+	return fmt.Sprintf(`
+resource "aws_api_gateway_rest_api" "test" {
+  disable_execute_api_endpoint = %[2]t
+  name                         = %[1]q
```
Comment (YakDriver) [inline aws/resource_aws_api_gateway_rest_api_test.go:1326]:
```suggestion
  name                         = %[1]q
  disable_execute_api_endpoint = %[2]t
```
Super nit

**Review by YakDriver — APPROVED** [review]
Commercial:
```
--- PASS: TestAccAWSAPIGatewayRestApi_ApiKeySource_OverrideBody (403.24s)
--- PASS: TestAccAWSAPIGatewayRestApi_ApiKeySource_SetByBody (587.39s)
--- PASS: TestAccAWSAPIGatewayRestApi_basic (17.86s)
--- PASS: TestAccAWSAPIGatewayRestApi_BinaryMediaTypes (205.50s)
--- PASS: TestAccAWSAPIGatewayRestApi_BinaryMediaTypes_OverrideBody (122.93s)
--- PASS: TestAccAWSAPIGatewayRestApi_Description (877.06s)
--- PASS: TestAccAWSAPIGatewayRestApi_Description_OverrideBody (634.31s)
--- PASS: TestAccAWSAPIGatewayRestApi_Description_SetByBody (599.29s)
--- PASS: TestAccAWSAPIGatewayRestApi_DisableExecuteApiEndpoint (877.22s)
--- PASS: TestAccAWSAPIGatewayRestApi_DisableExecuteApiEndpoint_OverrideBody (149.52s)
--- PASS: TestAccAWSAPIGatewayRestApi_DisableExecuteApiEndpoint_SetByBody (483.50s)
--- PASS: TestAccAWSAPIGatewayRestApi_disappears (218.26s)
--- PASS: TestAccAWSAPIGatewayRestApi_EndpointConfiguration (190.63s)
--- PASS: TestAccAWSAPIGatewayRestApi_EndpointConfiguration_Private (49.42s)
--- PASS: TestAccAWSAPIGatewayRestApi_EndpointConfiguration_VpcEndpointIds (366.41s)
--- PASS: TestAccAWSAPIGatewayRestApi_EndpointConfiguration_VpcEndpointIds_OverrideBody (242.17s)
--- PASS: TestAccAWSAPIGatewayRestApi_EndpointConfiguration_VpcEndpointIds_SetByBody (212.34s)
--- PASS: TestAccAWSAPIGatewayRestApi_MinimumCompressionSize (941.24s)
--- PASS: TestAccAWSAPIGatewayRestApi_MinimumCompressionSize_OverrideBody (139.69s)
--- PASS: TestAccAWSAPIGatewayRestApi_MinimumCompressionSize_SetByBody (55.24s)
--- PASS: TestAccAWSAPIGatewayRestApi_Name_OverrideBody (114.05s)
--- PASS: TestAccAWSAPIGatewayRestApi_Parameters (267.21s)
--- PASS: TestAccAWSAPIGatewayRestApi_Policy (379.22s)
--- PASS: TestAccAWSAPIGatewayRestApi_Policy_OverrideBody (83.44s)
--- PASS: TestAccAWSAPIGatewayRestApi_Policy_SetByBody (233.85s)
--- PASS: TestAccAWSAPIGatewayRestApi_tags (472.42s)
--- PASS: TestAccAWSAPIGatewayRestApi_Body (1147.91s)
--- PASS: TestAccAWSAPIGatewayRestApi_BinaryMediaTypes_SetByBody (1148.37s)
--- PASS: TestAccAWSAPIGatewayRestApi_ApiKeySource (1209.28s)
```

GovCloud:
```
--- PASS: TestAccAWSAPIGatewayRestApi_EndpointConfiguration_Private (19.59s)
--- PASS: TestAccAWSAPIGatewayRestApi_EndpointConfiguration_VpcEndpointIds (351.65s)
--- PASS: TestAccAWSAPIGatewayRestApi_EndpointConfiguration_VpcEndpointIds_OverrideBody (203.30s)
--- PASS: TestAccAWSAPIGatewayRestApi_EndpointConfiguration_VpcEndpointIds_SetByBody (163.71s)
--- SKIP: TestAccAWSAPIGatewayRestApi_ApiKeySource (0.01s)
--- SKIP: TestAccAWSAPIGatewayRestApi_ApiKeySource_OverrideBody (0.00s)
--- SKIP: TestAccAWSAPIGatewayRestApi_ApiKeySource_SetByBody (0.00s)
--- SKIP: TestAccAWSAPIGatewayRestApi_basic (1.30s)
--- SKIP: TestAccAWSAPIGatewayRestApi_BinaryMediaTypes (1.30s)
--- SKIP: TestAccAWSAPIGatewayRestApi_BinaryMediaTypes_OverrideBody (1.30s)
--- SKIP: TestAccAWSAPIGatewayRestApi_BinaryMediaTypes_SetByBody (1.30s)
--- SKIP: TestAccAWSAPIGatewayRestApi_Body (1.30s)
--- SKIP: TestAccAWSAPIGatewayRestApi_Description (1.30s)
--- SKIP: TestAccAWSAPIGatewayRestApi_Description_OverrideBody (1.30s)
--- SKIP: TestAccAWSAPIGatewayRestApi_Description_SetByBody (1.30s)
--- SKIP: TestAccAWSAPIGatewayRestApi_DisableExecuteApiEndpoint (1.30s)
--- SKIP: TestAccAWSAPIGatewayRestApi_DisableExecuteApiEndpoint_OverrideBody (1.30s)
--- SKIP: TestAccAWSAPIGatewayRestApi_DisableExecuteApiEndpoint_SetByBody (1.30s)
--- SKIP: TestAccAWSAPIGatewayRestApi_disappears (0.00s)
--- SKIP: TestAccAWSAPIGatewayRestApi_EndpointConfiguration (29.09s)
--- SKIP: TestAccAWSAPIGatewayRestApi_MinimumCompressionSize (1.30s)
--- SKIP: TestAccAWSAPIGatewayRestApi_MinimumCompressionSize_OverrideBody (1.30s)
--- SKIP: TestAccAWSAPIGatewayRestApi_MinimumCompressionSize_SetByBody (1.30s)
--- SKIP: TestAccAWSAPIGatewayRestApi_Name_OverrideBody (0.00s)
--- SKIP: TestAccAWSAPIGatewayRestApi_Parameters (1.30s)
--- SKIP: TestAccAWSAPIGatewayRestApi_Policy (1.30s)
--- SKIP: TestAccAWSAPIGatewayRestApi_Policy_OverrideBody (0.00s)
--- SKIP: TestAccAWSAPIGatewayRestApi_Policy_SetByBody (1.30s)
--- SKIP: TestAccAWSAPIGatewayRestApi_tags (0.00s)
```

File: aws/resource_aws_api_gateway_rest_api_test.go (hunk 1 above)
Comment (bflad) [reply aws/resource_aws_api_gateway_rest_api_test.go:1326]: Most of the newer test resource configurations should be alphabetical for human readability, it just so happens that there is also the potentially competing convention of `rName` always being the first `fmt.Sprintf()` parameter. 🙁  This should go away if/when a newer testing framework is available that works with Terraform variables instead. We could that style of configuration now, but since we don't know the final design of that framework, I would be hesitant to create yet another style of configuration in the meantime.
