### PR TITLE
elasticache: Adds Redis 6.x support

### LINKED ISSUE #15625: Elasticache redis 6.x support
_This issue was originally opened by @kaushik-prasanna as hashicorp/terraform#26570. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._
    
<hr>
    
With the recent release of Redis 6 by AWS Elasticache, AWS has moved to a single version model for its redis engine.

From the docs : 

> Beginning with Redis 6, ElastiCache for Redis will offer a single version for each Redis OSS major release, rather than offering multiple minor versions. Versionless engine support is designed to minimize confusion and ambiguity on having to choose from multiple minor versions. ElastiCache for Redis will also automatically keep your cache cluster up to date on the selected major version (Redis 6 and above). By providing the updated engine version, it ensures improved performance and enhanced security.
> 
> You specify the engine version by using 6.x. ElastiCache for Redis will automatically invoke the preferred minor version of Redis 6 that is available.

What this means is that the version to be specified in such case is `6.x` while creating Elasticache rather than something like `6.0.5`.

Coming to the issue, the creation of elasticache works fine when specified as `6.x`, but the same thing when run again after creation leads to the problem due to terraform not recognising the version and trying to update it as such.

Sample terraform 0.13.4 code :

```
resource "aws_elasticache_replication_group" "redis" {
...
  engine                        = "redis"
  engine_version                = "6.x"
  parameter_group_name          = "default.redis6.x"
  port                          = "6379"
...
}
```

On the first run of terraform apply, the resource gets created. But on second run (with not changes), terraform sees that the redis version created was `6.0.5` and tries to update it to `6.x`.

Output of `terraform plan` :
```
 # aws_elasticache_replication_group.redis will be updated in-place
  ~ resource "aws_elasticache_replication_group" "redis" {
...
        at_rest_encryption_enabled    = false
        auto_minor_version_upgrade    = true
        automatic_failover_enabled    = false
        engine                        = "redis"
      ~ engine_version                = "6.0.5" -> "6.x"
        parameter_group_name          = "default.redis6.x"
...
    }
```

And on apply, we get the error :

> Error: error updating Elasticache Replication Group : InvalidParameterCombination: Upgrading minor engine version for redis '6.x' using modify API is not allowed, please use Service Updates
        status code: 400

From an inital glance, it looks like terraform currently is not aligned with Redis 6.x version from AWS.

Also, we cannot specify specific versions. Hence it's forcing us to downgrade back to Redis 5. Hope this gets solved soon.

> Error: Error creating Elasticache Replication Group: InvalidParameterValue: Specific version selection is not allowed for '6.0.5', please use '6.x'

### LINKED ISSUE #18539: resource/aws_elasticache_cluster: Cannot specify Redis 6.x
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS [documentation for ElastiCache for Redis](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/supported-engine-versions.html#redis-version-6.x) states that

> Beginning with Redis 6, ElastiCache for Redis will offer a single version for each Redis OSS major release, rather than offering multiple minor versions. Versionless engine support is designed to minimize confusion and ambiguity on having to choose from multiple minor versions. ElastiCache for Redis will also automatically keep your cache cluster up to date on the selected major version (Redis 6 and above). By providing the updated engine version, it ensures improved performance and enhanced security.
> 
> You specify the engine version by using `6.x`. ElastiCache for Redis will automatically invoke the preferred minor version of Redis 6 that is available.

When creating an `aws_elasticache_cluster`, `engine_version` can be set to `6.x`, but any subsequent `terraform plan` or `terraform apply` will show a difference. If the `terraform apply` is continued, it fails with the error

```
Error: error updating ElastiCache cluster (<id>): InvalidParameterCombination: Upgrading minor engine version for redis '6.x' using modify API is not allowed, please use Service Updates
```

### Affected Resource

* aws_elasticache_cluster

### References

* The equivalent issue for `aws_elasticache_replication_group`: #15625

### PR DESCRIPTION
**Pull request by gdavison**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Adds support for specifying Redis version 6.x. This was due to a change in how AWS specifies Redis versions: prior to version 6, the full version was specified, e.g. 5.0.6. Staring with version 6, only the major version is specified followed by `.x`. The AWS API, however, returns the full deployed version in the corresponding parameter, leading to perpetual `plan` differences.

This PR adds validation and handling to the `engine_version` parameter to specify it as needed by the API. It also adds the parameter `engine_version_actual` to output the actual in-use version. Additionally, in `aws_elasticache_global_replication_group`, it deprecates `actual_engine_version` in favour of `engine_version_actual`.

Closes #15625
Closes #18539

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSElasticacheCluster\|TestAccAWSElasticacheGlobalReplicationGroup\|TestAccAWSElasticacheReplicationGroup'

--- SKIP: TestAccAWSElasticacheCluster_SecurityGroup_Ec2Classic (2.23s)
--- PASS: TestAccAWSElasticacheCluster_NumCacheNodes_Redis (13.80s)
--- PASS: TestAccAWSElasticacheCluster_Port_Redis_Default (495.39s)
--- PASS: TestAccAWSElasticacheCluster_Memcached_FinalSnapshot (2.79s)
--- PASS: TestAccAWSElasticacheCluster_Port (617.02s)
--- PASS: TestAccAWSElasticacheCluster_AZMode_Redis (617.69s)
--- PASS: TestAccAWSElasticacheCluster_vpc (632.82s)
--- PASS: TestAccAWSElasticacheCluster_AZMode_Memcached (639.96s)
--- PASS: TestAccAWSElasticacheCluster_ParameterGroupName_Default (640.42s)
--- PASS: TestAccAWSElasticacheCluster_Engine_Redis (654.64s)
--- PASS: TestAccAWSElasticacheCluster_snapshotsWithUpdates (673.72s)
--- PASS: TestAccAWSElasticacheCluster_Engine_Memcached (676.60s)
--- PASS: TestAccAWSElasticacheCluster_multiAZInVpc (679.57s)
--- PASS: TestAccAWSElasticacheCluster_NumCacheNodes_Decrease (929.33s)
--- PASS: TestAccAWSElasticacheCluster_NumCacheNodes_IncreaseWithPreferredAvailabilityZones (1029.14s)
--- PASS: TestAccAWSElasticacheCluster_NumCacheNodes_Increase (1087.77s)
--- PASS: TestAccAWSElasticacheCluster_NodeTypeResize_Memcached (1242.96s)
--- PASS: TestAccAWSElasticacheCluster_Redis_FinalSnapshot (826.97s)
--- PASS: TestAccAWSElasticacheCluster_EngineVersion_Memcached (1326.44s)
--- PASS: TestAccAWSElasticacheCluster_NodeTypeResize_Redis (1384.06s)
--- PASS: TestAccAWSElasticacheCluster_ReplicationGroupID_SingleReplica (1381.91s)
--- PASS: TestAccAWSElasticacheReplicationGroup_Validation_multiAz_NoAutomaticFailover (2.50s)
--- PASS: TestAccAWSElasticacheCluster_ReplicationGroupID_AvailabilityZone (1394.91s)
--- PASS: TestAccAWSElasticacheReplicationGroup_basic (801.42s)
--- PASS: TestAccAWSElasticacheCluster_ReplicationGroupID_MultipleReplica (1493.73s)
--- PASS: TestAccAWSElasticacheGlobalReplicationGroup_disappears (960.43s)
--- PASS: TestAccAWSElasticacheGlobalReplicationGroup_basic (1023.89s)
--- PASS: TestAccAWSElasticacheReplicationGroup_Uppercase (967.71s)
--- PASS: TestAccAWSElasticacheGlobalReplicationGroup_Description (1044.01s)
--- PASS: TestAccAWSElasticacheReplicationGroup_disappears (1150.50s)
--- PASS: TestAccAWSElasticacheReplicationGroup_updateMaintenanceWindow (832.55s)
--- PASS: TestAccAWSElasticacheReplicationGroup_clusteringAndCacheNodesCausesError (1.91s)
--- PASS: TestAccAWSElasticacheReplicationGroup_updateDescription (1022.65s)
--- PASS: TestAccAWSElasticacheCluster_EngineVersion_Redis (2106.49s)
--- PASS: TestAccAWSElasticacheReplicationGroup_redisClusterInVpc2 (958.07s)
--- PASS: TestAccAWSElasticacheReplicationGroup_updateParameterGroup (1114.17s)
--- PASS: TestAccAWSElasticacheReplicationGroup_ClusterMode_SingleNode (891.48s)
--- FAIL: TestAccAWSElasticacheGlobalReplicationGroup_ReplaceSecondary_DifferentRegion (2107.14s)
--- PASS: TestAccAWSElasticacheReplicationGroup_ClusterMode_Basic (1562.71s)
--- PASS: TestAccAWSElasticacheReplicationGroup_enableAuthTokenTransitEncryption (1137.91s)
--- PASS: TestAccAWSElasticacheReplicationGroup_enableAtRestEncryption (1106.66s)
--- PASS: TestAccAWSElasticacheReplicationGroup_useCmkKmsKeyId (993.98s)
--- PASS: TestAccAWSElasticacheReplicationGroup_updateNodeSize (2516.41s)
--- PASS: TestAccAWSElasticacheReplicationGroup_multiAzNotInVpc (2279.69s)
--- PASS: TestAccAWSElasticacheReplicationGroup_ClusterMode_UpdateNumNodeGroups_ScaleUp (2176.34s)
--- PASS: TestAccAWSElasticacheReplicationGroup_ClusterMode_UpdateReplicasPerNodeGroup (2068.33s)
--- PASS: TestAccAWSElasticacheReplicationGroup_Validation_NoNodeType (4.62s)
--- PASS: TestAccAWSElasticacheReplicationGroup_multiAzInVpc (2479.59s)
--- PASS: TestAccAWSElasticacheReplicationGroup_enableSnapshotting (2012.62s)
--- PASS: TestAccAWSElasticacheReplicationGroup_ClusterMode_NonClusteredParameterGroup (2445.77s)
--- PASS: TestAccAWSElasticacheReplicationGroup_NumberCacheClusters_Basic (1792.71s)
--- PASS: TestAccAWSElasticacheReplicationGroup_vpc (2943.24s)
--- PASS: TestAccAWSElasticacheReplicationGroup_EngineVersion_Update (3655.68s)
--- PASS: TestAccAWSElasticacheReplicationGroup_NumberCacheClusters_MemberClusterDisappears_NoChange (1305.79s)
--- PASS: TestAccAWSElasticacheReplicationGroup_Validation_GlobalReplicationGroupIdAndNodeType (851.30s)
--- PASS: TestAccAWSElasticacheReplicationGroup_ClusterMode_UpdateNumNodeGroupsAndReplicasPerNodeGroup_ScaleUp (2954.68s)
--- PASS: TestAccAWSElasticacheReplicationGroup_NumberCacheClusters_Failover_AutoFailoverEnabled (1923.84s)
--- PASS: TestAccAWSElasticacheReplicationGroup_NumberCacheClusters_MemberClusterDisappears_AddMemberCluster (1475.98s)
--- PASS: TestAccAWSElasticacheReplicationGroup_NumberCacheClusters_MemberClusterDisappears_RemoveMemberCluster_AtTargetSize (1408.32s)
--- PASS: TestAccAWSElasticacheReplicationGroup_ClusterMode_UpdateNumNodeGroups_ScaleDown (3166.17s)
--- PASS: TestAccAWSElasticacheReplicationGroup_tags (1183.78s)
--- PASS: TestAccAWSElasticacheReplicationGroup_NumberCacheClusters_MemberClusterDisappears_RemoveMemberCluster_ScaleDown (1335.60s)
--- PASS: TestAccAWSElasticacheReplicationGroup_NumberCacheClusters_MultiAZEnabled (2020.69s)
--- PASS: TestAccAWSElasticacheReplicationGroup_FinalSnapshot (1302.19s)
--- PASS: TestAccAWSElasticacheGlobalReplicationGroup_MultipleSecondaries (4419.23s)
--- PASS: TestAccAWSElasticacheReplicationGroup_NumberCacheClusters_Failover_AutoFailoverDisabled (2444.80s)
--- PASS: TestAccAWSElasticacheReplicationGroup_ClusterMode_UpdateNumNodeGroupsAndReplicasPerNodeGroup_ScaleDown (3578.48s)
--- PASS: TestAccAWSElasticacheReplicationGroup_GlobalReplicationGroupId_Basic (2221.57s)
--- PASS: TestAccAWSElasticacheReplicationGroup_GlobalReplicationGroupId_Full (2405.63s)
--- PASS: TestAccAWSElasticacheReplicationGroup_GlobalReplicationGroupId_disappears (2448.18s)
```

`TestAccAWSElasticacheGlobalReplicationGroup_ReplaceSecondary_DifferentRegion` failed with an unrelated error: `Error creating VPC: VpcLimitExceeded: The maximum number of VPCs has been reached.`

### CODE REVIEW

File: aws/resource_aws_elasticache_cluster.go [hunk 1]
```diff
@@ -268,32 +275,37 @@ func resourceAwsElasticacheCluster() *schema.Resource {
 				return errors.New(`az_mode "cross-az" is not supported with num_cache_nodes = 1`)
 			},
 			func(_ context.Context, diff *schema.ResourceDiff, v interface{}) error {
```
Comment (bill-rich) [inline aws/resource_aws_elasticache_cluster.go:277]: It would help with readability here to define all the functions and then list them here by name.

File: aws/resource_aws_elasticache_replication_group.go [hunk 2]
```diff
@@ -301,6 +308,9 @@ func resourceAwsElasticacheReplicationGroup() *schema.Resource {
 				}
 				return nil
 			},
+
+			CustomizeDiffElastiCacheEngineVersion,
```
Comment (bill-rich) [inline aws/resource_aws_elasticache_replication_group.go:312]: Same with this sequence for readability.

File: aws/resource_aws_elasticache_replication_group.go [hunk 3]
```diff
@@ -518,7 +528,18 @@ func resourceAwsElasticacheReplicationGroupRead(d *schema.ResourceData, meta int
 		c := res.CacheClusters[0]
 		d.Set("node_type", c.CacheNodeType)
 		d.Set("engine", c.Engine)
-		d.Set("engine_version", c.EngineVersion)
+
+		engineVersion, err := gversion.NewVersion(aws.StringValue(c.EngineVersion))
```
Comment (bill-rich) [inline aws/resource_aws_elasticache_replication_group.go:532]: This looks the same as in `aws/resource_aws_elasticache_cluster.go`. Can it be pulled out to be a shared function between the two?

**Review by bill-rich — CHANGES_REQUESTED** [review]
Looks good. Just a couple comments on style that may not be applicable.

File: aws/resource_aws_elasticache_cluster.go (hunk 1 above)
Comment (gdavison) [reply aws/resource_aws_elasticache_cluster.go:277]: Yeah, I've been thinking about that. It would also make them testable if needed

Comment (gdavison) [reply aws/resource_aws_elasticache_cluster.go:277]: It's also really easy to miss the one named function among all the inline functions

File: aws/resource_aws_elasticache_replication_group.go (hunk 3 above)
Comment (gdavison) [reply aws/resource_aws_elasticache_replication_group.go:532]: Good thinking

File: aws/resource_aws_elasticache_cluster.go (hunk 1 above)
Comment (bill-rich) [reply aws/resource_aws_elasticache_cluster.go:277]: I actually did that exact thing on my first read-through :-)

**Review by bill-rich — APPROVED** [review]
LGTM
```
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSElasticacheCluster -timeout 180m
=== RUN   TestAccAWSElasticacheCluster_Engine_Memcached
=== PAUSE TestAccAWSElasticacheCluster_Engine_Memcached
=== RUN   TestAccAWSElasticacheCluster_Engine_Redis
=== PAUSE TestAccAWSElasticacheCluster_Engine_Redis
=== RUN   TestAccAWSElasticacheCluster_Port_Redis_Default
=== PAUSE TestAccAWSElasticacheCluster_Port_Redis_Default
=== RUN   TestAccAWSElasticacheCluster_ParameterGroupName_Default
=== PAUSE TestAccAWSElasticacheCluster_ParameterGroupName_Default
=== RUN   TestAccAWSElasticacheCluster_Port
=== PAUSE TestAccAWSElasticacheCluster_Port
=== RUN   TestAccAWSElasticacheCluster_SecurityGroup_Ec2Classic
=== PAUSE TestAccAWSElasticacheCluster_SecurityGroup_Ec2Classic
=== RUN   TestAccAWSElasticacheCluster_snapshotsWithUpdates
=== PAUSE TestAccAWSElasticacheCluster_snapshotsWithUpdates
=== RUN   TestAccAWSElasticacheCluster_NumCacheNodes_Decrease
=== PAUSE TestAccAWSElasticacheCluster_NumCacheNodes_Decrease
=== RUN   TestAccAWSElasticacheCluster_NumCacheNodes_Increase
=== PAUSE TestAccAWSElasticacheCluster_NumCacheNodes_Increase
=== RUN   TestAccAWSElasticacheCluster_NumCacheNodes_IncreaseWithPreferredAvailabilityZones
=== PAUSE TestAccAWSElasticacheCluster_NumCacheNodes_IncreaseWithPreferredAvailabilityZones
=== RUN   TestAccAWSElasticacheCluster_vpc
=== PAUSE TestAccAWSElasticacheCluster_vpc
=== RUN   TestAccAWSElasticacheCluster_multiAZInVpc
=== PAUSE TestAccAWSElasticacheCluster_multiAZInVpc
=== RUN   TestAccAWSElasticacheCluster_AZMode_Memcached
=== PAUSE TestAccAWSElasticacheCluster_AZMode_Memcached
=== RUN   TestAccAWSElasticacheCluster_AZMode_Redis
=== PAUSE TestAccAWSElasticacheCluster_AZMode_Redis
=== RUN   TestAccAWSElasticacheCluster_EngineVersion_Memcached
=== PAUSE TestAccAWSElasticacheCluster_EngineVersion_Memcached
=== RUN   TestAccAWSElasticacheCluster_EngineVersion_Redis
=== PAUSE TestAccAWSElasticacheCluster_EngineVersion_Redis
=== RUN   TestAccAWSElasticacheCluster_NodeTypeResize_Memcached
=== PAUSE TestAccAWSElasticacheCluster_NodeTypeResize_Memcached
=== RUN   TestAccAWSElasticacheCluster_NodeTypeResize_Redis
=== PAUSE TestAccAWSElasticacheCluster_NodeTypeResize_Redis
=== RUN   TestAccAWSElasticacheCluster_NumCacheNodes_Redis
=== PAUSE TestAccAWSElasticacheCluster_NumCacheNodes_Redis
=== RUN   TestAccAWSElasticacheCluster_ReplicationGroupID_AvailabilityZone
=== PAUSE TestAccAWSElasticacheCluster_ReplicationGroupID_AvailabilityZone
=== RUN   TestAccAWSElasticacheCluster_ReplicationGroupID_SingleReplica
=== PAUSE TestAccAWSElasticacheCluster_ReplicationGroupID_SingleReplica
=== RUN   TestAccAWSElasticacheCluster_ReplicationGroupID_MultipleReplica
=== PAUSE TestAccAWSElasticacheCluster_ReplicationGroupID_MultipleReplica
=== RUN   TestAccAWSElasticacheCluster_Memcached_FinalSnapshot
=== PAUSE TestAccAWSElasticacheCluster_Memcached_FinalSnapshot
=== RUN   TestAccAWSElasticacheCluster_Redis_FinalSnapshot
=== PAUSE TestAccAWSElasticacheCluster_Redis_FinalSnapshot
=== CONT  TestAccAWSElasticacheCluster_Engine_Memcached
=== CONT  TestAccAWSElasticacheCluster_Redis_FinalSnapshot
=== CONT  TestAccAWSElasticacheCluster_AZMode_Memcached
=== CONT  TestAccAWSElasticacheCluster_SecurityGroup_Ec2Classic
=== CONT  TestAccAWSElasticacheCluster_multiAZInVpc
=== CONT  TestAccAWSElasticacheCluster_Memcached_FinalSnapshot
=== CONT  TestAccAWSElasticacheCluster_snapshotsWithUpdates
=== CONT  TestAccAWSElasticacheCluster_ReplicationGroupID_MultipleReplica
=== CONT  TestAccAWSElasticacheCluster_ReplicationGroupID_SingleReplica
=== CONT  TestAccAWSElasticacheCluster_ReplicationGroupID_AvailabilityZone
=== CONT  TestAccAWSElasticacheCluster_NumCacheNodes_Redis
=== CONT  TestAccAWSElasticacheCluster_NodeTypeResize_Redis
=== CONT  TestAccAWSElasticacheCluster_NodeTypeResize_Memcached
=== CONT  TestAccAWSElasticacheCluster_EngineVersion_Redis
=== CONT  TestAccAWSElasticacheCluster_EngineVersion_Memcached
=== CONT  TestAccAWSElasticacheCluster_Port_Redis_Default
=== CONT  TestAccAWSElasticacheCluster_ParameterGroupName_Default
=== CONT  TestAccAWSElasticacheCluster_AZMode_Redis
=== CONT  TestAccAWSElasticacheCluster_Engine_Redis
=== CONT  TestAccAWSElasticacheCluster_Port
--- PASS: TestAccAWSElasticacheCluster_NumCacheNodes_Redis (4.63s)
=== CONT  TestAccAWSElasticacheCluster_NumCacheNodes_IncreaseWithPreferredAvailabilityZones
--- PASS: TestAccAWSElasticacheCluster_Memcached_FinalSnapshot (5.01s)
=== CONT  TestAccAWSElasticacheCluster_vpc
--- PASS: TestAccAWSElasticacheCluster_Port_Redis_Default (475.17s)
=== CONT  TestAccAWSElasticacheCluster_NumCacheNodes_Increase
--- PASS: TestAccAWSElasticacheCluster_SecurityGroup_Ec2Classic (561.43s)
=== CONT  TestAccAWSElasticacheCluster_NumCacheNodes_Decrease
--- PASS: TestAccAWSElasticacheCluster_Engine_Redis (598.55s)
--- PASS: TestAccAWSElasticacheCluster_ParameterGroupName_Default (607.56s)
--- PASS: TestAccAWSElasticacheCluster_AZMode_Redis (622.46s)
--- PASS: TestAccAWSElasticacheCluster_Port (624.21s)
--- PASS: TestAccAWSElasticacheCluster_AZMode_Memcached (624.75s)
--- PASS: TestAccAWSElasticacheCluster_Engine_Memcached (628.20s)
--- PASS: TestAccAWSElasticacheCluster_vpc (656.56s)
--- PASS: TestAccAWSElasticacheCluster_multiAZInVpc (706.65s)
--- PASS: TestAccAWSElasticacheCluster_snapshotsWithUpdates (707.94s)
--- PASS: TestAccAWSElasticacheCluster_Redis_FinalSnapshot (809.49s)
--- PASS: TestAccAWSElasticacheCluster_NumCacheNodes_IncreaseWithPreferredAvailabilityZones (1117.90s)
--- PASS: TestAccAWSElasticacheCluster_NodeTypeResize_Memcached (1227.77s)
--- PASS: TestAccAWSElasticacheCluster_ReplicationGroupID_AvailabilityZone (1369.45s)
--- PASS: TestAccAWSElasticacheCluster_NodeTypeResize_Redis (1369.98s)
--- PASS: TestAccAWSElasticacheCluster_EngineVersion_Memcached (1395.04s)
--- PASS: TestAccAWSElasticacheCluster_ReplicationGroupID_MultipleReplica (1434.90s)
--- PASS: TestAccAWSElasticacheCluster_ReplicationGroupID_SingleReplica (1435.60s)
--- PASS: TestAccAWSElasticacheCluster_NumCacheNodes_Decrease (897.34s)
--- PASS: TestAccAWSElasticacheCluster_NumCacheNodes_Increase (1019.81s)
--- PASS: TestAccAWSElasticacheCluster_EngineVersion_Redis (2091.81s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	2091.853s
```
