### PR TITLE
vpc/security_group: Fix complex dependency violations

### LINKED ISSUE #1671: aws_security_group: DependencyViolation: resource sg-XXX has a dependent object
_This issue was originally opened by @brikis98 as hashicorp/terraform#11047. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version

Terraform v0.8.2

### Affected Resource(s)

- aws_security_group

### Terraform Configuration Files

This is part of a larger configuration, but I think the relevant parts are as follows.

Under `modules/webserver-cluster/main.tf`, I define a module with the following code:

```hcl
resource "aws_autoscaling_group" "example" {
  launch_configuration = "${aws_launch_configuration.example.id}"
  availability_zones   = ["${data.aws_availability_zones.all.names}"]
  load_balancers       = ["${aws_elb.example.name}"]
  health_check_type    = "ELB"

  min_size = 2
  max_size = 10
}

resource "aws_launch_configuration" "example" {
  image_id        = "ami-40d28157"
  instance_type   = "t2.micro"
  security_groups = ["${aws_security_group.instance.id}"]

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_security_group" "instance" {
  name = "my-security-group"

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_security_group_rule" "allow_http_inbound" {
  type              = "ingress"
  security_group_id = "${aws_security_group.instance.id}"

  from_port   = 80
  to_port     = 80
  protocol    = "tcp"
  cidr_blocks = ["0.0.0.0/0"]
}

data "aws_availability_zones" "all" {}

resource "aws_elb" "example" {
  name               = "my-example-elb"
  availability_zones = ["${data.aws_availability_zones.all.names}"]
  security_groups    = ["${aws_security_group.elb.id}"]

  listener {
    lb_port           = 80
    lb_protocol       = "http"
    instance_port     = 80
    instance_protocol = "http"
  }

  health_check {
    healthy_threshold   = 2
    unhealthy_threshold = 2
    timeout             = 3
    interval            = 30
    target              = "HTTP:80/"
  }
}

resource "aws_security_group" "elb" {
  name = "elb"
}

resource "aws_security_group_rule" "allow_http_inbound" {
  type              = "ingress"
  security_group_id = "${aws_security_group.elb.id}"

  from_port   = 80
  to_port     = 80
  protocol    = "tcp"
  cidr_blocks = ["0.0.0.0/0"]
}

resource "aws_security_group_rule" "allow_all_outbound" {
  type              = "egress"
  security_group_id = "${aws_security_group.elb.id}"

  from_port   = 0
  to_port     = 0
  protocol    = "-1"
  cidr_blocks = ["0.0.0.0/0"]
}

output "elb_security_group_id" {
  value = "${aws_security_group.elb.id}"
}
```

In a separate folder, I use this module in the usual way, but also add a custom security group rule:

```hcl
module "webserver_cluster" {
  source = "modules/webserver-cluster"

  # ... pass various parameters ...
}

resource "aws_security_group_rule" "allow_testing_inbound" {
  type              = "ingress"
  security_group_id = "${module.webserver_cluster.elb_security_group_id}"

  from_port   = 12345
  to_port     = 12345
  protocol    = "tcp"
  cidr_blocks = ["0.0.0.0/0"]
}
```

### Expected Behavior

I expect to be able to run `terraform apply` and `terraform destroy` without errors.

### Actual Behavior

`terraform apply` works fine. Occasionally, `terraform destroy` fails with the following error:

```
aws_security_group.elb: DependencyViolation: resource sg-344baa48 has a dependent object
```

### Steps to Reproduce

1. `terraform apply`
1. `terraform destroy`

### Important Factoids

It's an intermittent issue, so I can't be sure, but I don't think this error happened with Terraform 0.7.x.

### LINKED ISSUE #8285: Terraform is unable to destroy AWS VPC on of EMR cluster
_This issue was originally opened by @Ohtar10 as hashicorp/terraform#20995. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

Hi!

I'm using terraform with aws, working with EMR clusters, I'm able to create the cluster completely using the docs instructions but when I try to delete it, terraform always fails in destroy de VPC and I'm forced to go to the console and delete it manually.

### Terraform Version
```
Terraform v0.11.13
```

### Expected Behavior:
Terraform should have destroyed everything including the VPC

### Actual Behavior:
The VPC is not deleted even after ~10 min retries, the output of Terraform is:
```
aws_vpc.spark-emr-main: Still destroying... (ID: vpc-0291df56137e9c5b1, 4m50s elapsed)
2019/04/11 15:05:03 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* aws_vpc.spark-emr-main: DependencyViolation: The vpc 'vpc-0291df56137e9c5b1' has dependencies and cannot be deleted.
	status code: 400, request id: 41465664-4873-4c92-b8b2-2e0bda3a5f19
2019/04/11 15:05:03 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* aws_vpc.spark-emr-main: DependencyViolation: The vpc 'vpc-0291df56137e9c5b1' has dependencies and cannot be deleted.
	status code: 400, request id: 41465664-4873-4c92-b8b2-2e0bda3a5f19
2019/04/11 15:05:03 [ERROR] root: eval: *terraform.EvalOpFilter, err: 1 error(s) occurred:

* aws_vpc.spark-emr-main: DependencyViolation: The vpc 'vpc-0291df56137e9c5b1' has dependencies and cannot be deleted.
	status code: 400, request id: 41465664-4873-4c92-b8b2-2e0bda3a5f19

Error: Error applying plan:

1 error(s) occurred:

* aws_vpc.spark-emr-main (destroy): 1 error(s) occurred:

* aws_vpc.spark-emr-main: DependencyViolation: The vpc 'vpc-0291df56137e9c5b1' has dependencies and cannot be deleted.
	status code: 400, request id: 41465664-4873-4c92-b8b2-2e0bda3a5f19

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

Workaround:
Manually go to the aws web console and delete the VPC. If I do this while is destroying the VPC, Terraform finishes successfully.

### Steps to Reproduce
1. Based on *Example bootable config* at: https://www.terraform.io/docs/providers/aws/r/emr_cluster.html, I've created my own scripts then...
2. `terraform init`
3. `terraform apply`
4. `terraform destroy -auto-approve`

### Additional Context
* My setup is almost identical to the sample I mentioned above, except that I don't use `keep_job_flow_alive_when_no_steps`, `instance_group` and `additional_info`.
* I have tried by importing the emr managed security groups into my state, marking them with `revoke_rules_on_delete = true` before deleting; no luck, still unable to delete the VPC.
* I also have additional security groups configured, all of them use `revoke_rules_on_delete = true` Still no luck.
* From the error, it seems from Terraform standpoint, there is some resource depending on the VPC that is not being deleted as part of the destruction plan. I guess aws console is well aware of the dependencies and hence is able to destroy them in proper order.
* I see something interesting though. On creation, I can see three associated with my VPC despite I only have one on my scripts, the one I'm explicitly associating to my VPC. I wonder if this is these are the dependencies that prevent the VPC to be deleted.

### References
Maybe this is related to:

- hashicorp/terraform#9487
- https://github.com/terraform-providers/terraform-provider-aws/issues/3465

### LINKED ISSUE #8769: Terraform sending incorrect parameters to AWS API when revoking security group rules
_This issue was originally opened by @bstrohmeyer as hashicorp/terraform#21437. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version

```
Terraform v0.12.0
* provider.aws: version = "~> 2.12"

```

### Terraform Configuration Files

```hcl
module "sg_common" {
  source      = "./modules/security-group"
  name        = "sg_common"
  description = "Common access security group"
  vpc         = "${data.terraform_remote_state.vpc.outputs.vpc}"

  rules = [
    {
      type        = "ingress"
      from_port   = -1
      to_port     = -1
      protocol    = "icmp"
      description = "Allow ICMP"
      cidr        = ["0.0.0.0/0"]
    },
    {
      type        = "ingress"
      from_port   = 22
      to_port     = 22
      protocol    = "tcp"
      description = "SSH from Bastion"
      source_sg   = module.sg_sc-bastion.id
    },
    {
      type        = "ingress"
      from_port   = 22
      to_port     = 22
      protocol    = "tcp"
      description = "SSH from Gitlab Runners"
      cidr        = ["10.10.10.0/24"]
    },
    {
      type        = "egress"
      from_port   = 0
      to_port     = 0
      protocol    = "-1"
      description = "Outbound Traffic"
      cidr        = ["0.0.0.0/0"]
    },
  ]
}
```
subnets module:
```hcl
resource "aws_subnet" "public" {
  vpc_id            = "${var.vpc["vpc_id"]}"
  cidr_block        = "${var.public.subnet_cidr}"
  availability_zone = "${var.subnet_az}"

  tags = {
    Name = "${var.public.subnet_name}"
  }
}

resource "aws_route_table" "public_route_table" {
  vpc_id = "${var.vpc["vpc_id"]}"

  tags = {
    Name = "public-${var.subnet_az}"
  }
}

resource "aws_route_table" "private_route_table" {
  vpc_id = "${var.vpc["vpc_id"]}"

  tags = {
    Name = "private-${var.subnet_az}"
  }
}

resource "aws_route" "igw_route" {
  route_table_id         = "${aws_route_table.public_route_table.id}"
  destination_cidr_block = "0.0.0.0/0"
  gateway_id             = "${var.vpc["igw_id"]}"
}

resource "aws_route_table_association" "rt_assn" {
  subnet_id      = "${aws_subnet.public.id}"
  route_table_id = "${aws_route_table.public_route_table.id}"
}

resource "aws_eip" "nat" {
  vpc      = true
}

resource "aws_nat_gateway" "natgw" {
  allocation_id = "${aws_eip.nat.id}"
  subnet_id     = "${aws_subnet.public.id}"

  tags = {
    Name = "natgw-${var.subnet_az}"
  }
}

resource "aws_route" "nat_route" {
  route_table_id         = "${aws_route_table.private_route_table.id}"
  destination_cidr_block = "0.0.0.0/0"
  nat_gateway_id             = "${aws_nat_gateway.natgw.id}"
}

resource "aws_subnet" "private" {
  count             = length(var.private)
  vpc_id            = var.vpc["vpc_id"]
  cidr_block        = lookup(var.private[count.index], "subnet_cidr")
  availability_zone = var.subnet_az

  tags = {
    Name = lookup(var.private[count.index], "subnet_name")
  }
}

resource "aws_route_table_association" "rt_assn_private" {
  count          = length(var.private)
  subnet_id      = aws_subnet.private[count.index].id
  route_table_id = aws_route_table.private_route_table.id
}
```

### Expected Behavior

Added new rule to security group:
```hcl
    {
      type        = "ingress"
      from_port   = 22
      to_port     = 22
      protocol    = "tcp"
      description = "SSH from Gitlab Runners"
      cidr        = ["10.10.10.0/24"]
    },
```

Expected Terraform to add this rule to the existing security group.

### Actual Behavior

This rule was added in the middle of the list, which then due to the design of the module would require terraform to delete the Egress rule as the list order was upset. This is expected and is reflected in the terraform plan:

```
 # module.sg_common.aws_security_group_rule.source_cidr[2] must be replaced
-/+ resource "aws_security_group_rule" "source_cidr" {
      ~ cidr_blocks              = [ # forces replacement
          - "0.0.0.0/0",
          + "10.10.10.0/24",
        ]
      ~ description              = "Outbound Traffic" -> "SSH from Gitlab Runners"
      ~ from_port                = 0 -> 22 # forces replacement
      ~ id                       = "sgrule-3520689800" -> (known after apply)
      - ipv6_cidr_blocks         = [] -> null
      - prefix_list_ids          = [] -> null
      ~ protocol                 = "-1" -> "tcp" # forces replacement
        security_group_id        = "sg-09976fde26e3db3ea"
        self                     = false
      + source_security_group_id = (known after apply)
      ~ to_port                  = 0 -> 22 # forces replacement
      ~ type                     = "egress" -> "ingress" # forces replacement
    }

  # module.sg_common.aws_security_group_rule.source_cidr[3] will be created
  + resource "aws_security_group_rule" "source_cidr" {
      + cidr_blocks              = [
          + "0.0.0.0/0",
        ]
      + description              = "Outbound Traffic"
      + from_port                = 0
      + id                       = (known after apply)
      + protocol                 = "-1"
      + security_group_id        = "sg-09976fde26e3db3ea"
      + self                     = false
      + source_security_group_id = (known after apply)
      + to_port                  = 0
      + type                     = "egress"
    }
```

There was an error on apply, however:

```
Error: Error revoking security group sg-09976fde26e3db3ea rules: InvalidPermission.NotFound: The specified rule does not exist in this security group.
	status code: 400, request id: b0bba002-bbd7-4118-b47e-7822328109fa


Error: [WARN] A duplicate Security Group rule was found on (sg-09976fde26e3db3ea). This may be
a side effect of a now-fixed Terraform issue causing two security groups with
identical attributes but different source_security_group_ids to overwrite each
other in the state. See https://github.com/hashicorp/terraform/pull/2376 for more
information and instructions for recovery. Error message: the specified rule "peer: 0.0.0.0/0, ALL, ALLOW" already exists

  on .terraform/modules/sg_common/modules/security-group/main.tf line 12, in resource "aws_security_group_rule" "source_cidr":
  12: resource "aws_security_group_rule" "source_cidr" {
```

Upon investigation, it appears that terraform is sending the wrong parameters in the `RevokeSecurityGroupEgress` API call to AWS which results in the first error. From cloudtrail:

```
"eventSource": "ec2.amazonaws.com",
"eventName": "RevokeSecurityGroupEgress",
"awsRegion": "ap-northeast-1",
"sourceIPAddress": "[removed]",
"userAgent": "aws-sdk-go/1.19.36 (go1.12.5; linux; amd64) APN/1.0 HashiCorp/1.0 Terraform/0.12.0",
"errorCode": "Client.InvalidPermission.NotFound",
"errorMessage": "The specified rule does not exist in this security group.",
 "requestParameters": {
        "groupId": "sg-09976fde26e3db3ea",
        "ipPermissions": {
            "items": [
                {
                    "ipProtocol": "tcp",
                    "fromPort": 0,
                    "toPort": 0,
                    "groups": {},
                    "ipRanges": {
                        "items": [
                            {
                                "cidrIp": "0.0.0.0/0",
                                "description": "Outbound Traffic"
                            }
                        ]
                    },
                    "ipv6Ranges": {},
                    "prefixListIds": {}
                }
            ]
        }
    },
```
`"ipProtocol": "tcp",` is the _new_ value of that security group rule as seen in the plan above, not the existing one. Terraform should be sending `"ipProtocol": "-1",` in this request to revoke the existing rule. This then results in AWS being unable to match this egress rule to the existing one and it cannot delete it, further resulting in a duplicate security group rule error when it tries to recreate the egress rule. 

### Steps to Reproduce

Add a security group rule to an existing security group that causes an egress rule to be deleted.

### Additional Context

Terraform is running via docker via gitlab runner.

### LINKED ISSUE #12394: resource_aws_security_group: DependencyViolation assumes ENI HyperPlane deletion issue
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
When destroying a Security Group the provider assumes a DependencyViolation error is related to the HyperPlane ENI issue and retries.

### New or Affected Resource(s)

* aws_security_group

### Potential Terraform Configuration

* #### First.tf
```hcl
resource "aws_security_group" "SG-1" {
	name = Test
	vpc_id = <VPC_ID>
}
```
* #### Second.tf
```hcl
resource "aws_security_group" "SG-2" {
	name = Test
	vpc_id = <VPC_ID>
	ingress {
		protocol = -1
		from_port = 0
		to_port = 0
		security_groups = [ "<SG-1_SG-ID>" ]
	}
}
```

Process: Apply First.tf followed by Second.tf.  Attempt to destroy First.tf and the system will loop assuming the Hyperplane ENI work-around.

### References

* #10329

### LINKED ISSUE #12420: Security Group /security Group-rule recreation error
Hello.

I have problems recreating securitygrouprules. Seem to be related to multiply old cases, that seem resolved and closed.
would be great to have some feedback or workaround.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.12.20
+ provider.aws v2.27.0   (also tried 2.53.0)
+ provider.dns v2.2.0
+ provider.template v2.1.2

### Affected Resource(s)

aws_security_group

aws_security_group_rule
### Terraform Configuration Files

```hcl
resource "aws_security_group" "security_group" {
  count = var.additional_listener_port == [] ? 0 :1
  name        = "${var.env}-${var.app_name}-securityGroup"
  description = "Securitygroup for ${var.env}-${var.app_name}"
  vpc_id      = module.network.vpc_id
}
resource "aws_security_group_rule" "allow_inbound_rules" {
  for_each = { for v in var.additional_listener_port : v => v }
  type              = "ingress"
  to_port           = tonumber(each.value)
  protocol          = "TCP"
  cidr_blocks       = sort(module.network.app_layer_cidrs)
  from_port         = tonumber(each.value)
  security_group_id = aws_security_group.beanstalk_specific_sg[0].id
}
```

### Debug Output

Error revoking security group sg-087e80ad801d081f2 rules: InvalidPermission.NotFound: The specified rule does not exist in this security group.
        status code: 400, request id: f0d73cde-e0e9-4bd3-8dd7-1fa617edee66

### Expected Behavior

Recreating the security group rule when changing protocol from "-1" to "TCP"
### Actual Behavior

Error revoking security group sg-087e80ad801d081f2 rules: InvalidPermission.NotFound: The specified rule does not exist in this security group.
        status code: 400, request id: f0d73cde-e0e9-4bd3-8dd7-1fa617edee66

### Steps to Reproduce

1. create securitygroup
2. create securitygrouprule
3. change protocol in securitygrouprule and apply

* #0000

### LINKED ISSUE #13228: DependencyViolation on changing aws_alb security group
_This issue was originally opened by @fomichevmi as hashicorp/terraform#24863. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._
    
<hr>
    
### Terraform Version

Terraform v0.12.20

### Terraform AWS Provider Version

v2.57.0

### Terraform Configuration Files

TF 1:
<pre>
resource "aws_alb" "test_aws_alb" {
  drop_invalid_header_fields = false
  enable_deletion_protection = false
  enable_http2               = true
  idle_timeout               = 300
  internal                   = true
  ip_address_type            = "ipv4"
  load_balancer_type         = "application"
  name                       = "test-aws-load-balancer"
  security_groups            = [
    aws_security_group.test_aws_sg.id
  ]
 ...
}
resource "aws_security_group" "test_aws_sg" {
    egress {
       ...
    }
    ingress {
       ...
    }
    name                   = "test-aws-security-group"
    revoke_rules_on_delete = false
    vpc_id                 = "vpc-1"
  }
</pre>
TF 2
<pre>
resource "aws_alb" "test_aws_alb" {
  drop_invalid_header_fields = false
  enable_deletion_protection = false
  enable_http2               = true
  idle_timeout               = 300
  internal                   = true
  ip_address_type            = "ipv4"
  load_balancer_type         = "application"
  name                       = "test-aws-load-balancer"
  security_groups            = [
    aws_security_group.test_aws_sg_2.id
  ]
 ...
}
resource "aws_security_group" "test_aws_sg_2" {
    egress {
       ...
    }
    ingress {
       ...
    }
    name                   = "test-aws-security-group-2"
    revoke_rules_on_delete = false
    vpc_id                 = "vpc-1"
  }
</pre>
### Debug Output

aws_security_group.test_aws_sg: Destroying... [id=sg-1]
aws_security_group.test_aws_sg_2: Creating...
aws_security_group.test_aws_sg_2: Creation complete after 4s [id=sg-2]
[TRACE] Executing graph transform terraform.TransitiveReductionTransformer
[TRACE] Completed graph transform terraform.TransitiveReductionTransformer with new graph:
  aws_alb.test_aws_alb - terraform.NodeApplyableResourceInstance
    aws_alb.test_aws_alb (prepare state) - terraform.NodeApplyableResource
    aws_security_group.test_aws_sg (destroy) - terraform.NodeDestroyResourceInstance
    aws_security_group.test_aws_sg_2 - terraform.NodeApplyableResourceInstance
  aws_alb.test_aws_alb (prepare state) - terraform.NodeApplyableResource
    provider.aws - terraform.NodeApplyableProvider
  aws_security_group.test_aws_sg (clean up state) - terraform.NodeDestroyResource
    aws_security_group.test_aws_sg (destroy) - terraform.NodeDestroyResourceInstance
  aws_security_group.test_aws_sg (destroy) - terraform.NodeDestroyResourceInstance
    provider.aws - terraform.NodeApplyableProvider
  aws_security_group.test_aws_sg_2 - terraform.NodeApplyableResourceInstance
    aws_security_group.test_aws_sg_2 (prepare state) - terraform.NodeApplyableResource
  aws_security_group.test_aws_sg_2 (prepare state) - terraform.NodeApplyableResource
    provider.aws - terraform.NodeApplyableProvider
  meta.count-boundary (EachMode fixup) - terraform.NodeCountBoundary
    aws_alb.test_aws_alb - terraform.NodeApplyableResourceInstance
    aws_security_group.test_aws_sg (clean up state) - *terraform.NodeDestroyResource
  provider.aws - terraform.NodeApplyableProvider
  provider.aws (close) - terraform.graphNodeCloseProvider
    aws_alb.test_aws_alb - terraform.NodeApplyableResourceInstance
  root - terraform.graphNodeRoot
    meta.count-boundary (EachMode fixup) - terraform.NodeCountBoundary
    provider.aws (close) - terraform.graphNodeCloseProvider

aws_security_group.test_aws_sg: Still destroying... [id=sg-1, 19m20s elapsed]
[TRACE] dag/walk: vertex "aws_alb.test_aws_alb" is waiting for "aws_security_group.test_aws_sg (destroy)"
[TRACE] dag/walk: vertex "aws_alb.test_aws_alb" is waiting for "aws_security_group.test_aws_sg (destroy)"
[TRACE] dag/walk: vertex "provider.aws (close)" is waiting for "aws_alb.test_aws_alb"
[TRACE] dag/walk: vertex "aws_security_group.test_aws_sg (clean up state)" is waiting for "aws_security_group.test_aws_sg (destroy)"
[TRACE] dag/walk: vertex "root" is waiting for "meta.count-boundary (EachMode fixup)"
2020/05/05 13:32:51 [TRACE] vertex "aws_security_group.test_aws_sg (destroy)": visit complete
[TRACE] dag/walk: upstream of "aws_alb.test_aws_alb" errored, so skipping
[TRACE] dag/walk: upstream of "aws_security_group.test_aws_sg (clean up state)" errored, so skipping

Error: Error deleting security group: DependencyViolation: resource sg-1 has a dependent object
	status code: 400, request id: aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeffffffff

### Expected Behavior

1. SG-2 is created
2. ALB security groups are refreshed
3. SG-1 is deleted

### Actual Behavior

1. SG-2 is created
2. SG-1 is being deleted... and fails

### Steps to Reproduce

1. Terraform init with TF 1
2. Apply TF 1
3. Apply TF 2

### Description

When I try to change security group related to aws_alb old SG is tried to be deleted before unbind from aws_alb. So instead of refreshing aws_alb I'm receiving DependencyViolation exception

### LINKED ISSUE #16165: DependencyViolation when deleting security group associated to lambda and vpc_endpoint
_This issue was originally opened by @pnandita as hashicorp/terraform#26892. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._
    
<hr>
    
**Description**:
Create 2 lambdas in terraform. Each lambda will have its own security group. Also create a VPC endpoint with a security group of it’s own. Add the lambda security groups as an ingress into vpc_endpoint’s security group. Now, delete one of the lambda it’s associated security group, and also remove the reference from the ingress rules from vpc_endpoint. This results in a dependency violation, and the lambda security group never ends up getting deleted and fails with the error:
aws_security_group.lambda_sg2: Still destroying... [id=sg-xxxxx, 19m41s elapsed]
aws_security_group.lambda_sg2: Still destroying... [id=sg-xxxxx, 19m51s elapsed]

Error: Error deleting security group: DependencyViolation: resource sg-xxxx has a dependent object
	status code: 400, request id: xxxx-xxx-xx-xx-xxxxx

### Terraform Version
```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.14.1
```

### Terraform Configuration Files
```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.0"
    }
  }
}

provider "aws" {
  region = "us-east-1"
}

variable "vpc_id" {}
variable "role" {}
variable "subnet_id" {}
variable "lambda_filename" {}
variable "lambda_runtime" {}
variable "lambda_handler" {}


resource "aws_security_group" "lambda_sg1" {
  name   = "lambda_sg1"
  vpc_id = var.vpc_id
}

resource "aws_lambda_function" "test_lambda1" {
  filename      = var.lambda_filename
  function_name = "test_lambda1"
  role          = var.role
  handler       = var.lambda_handler

  source_code_hash = filebase64sha256(var.lambda_filename)

  runtime = var.lambda_runtime
  vpc_config {
    subnet_ids         = [var.subnet_id]
    security_group_ids = [aws_security_group.lambda_sg1.id]
  }
}

resource "aws_security_group" "lambda_sg2" {
  name   = "lambda_sg2"
  vpc_id = var.vpc_id
}

resource "aws_lambda_function" "test_lambda2" {
  filename      = var.lambda_filename
  function_name = "test_lambda2"
  role          = var.role
  handler       = var.lambda_handler

  source_code_hash = filebase64sha256(var.lambda_filename)

  runtime = var.lambda_runtime
  vpc_config {
    subnet_ids         = [var.subnet_id]
    security_group_ids = [aws_security_group.lambda_sg2.id]
  }
}

resource "aws_security_group" "vpc_endpoint_sg" {
  name   = "vpc_endpoint_sg"
  vpc_id = var.vpc_id

  ingress {
    from_port       = 443
    to_port         = 443
    protocol        = "tcp"
    security_groups = [aws_security_group.lambda_sg1.id, aws_security_group.lambda_sg2.id]
  }
}

resource "aws_vpc_endpoint" "vpc_endpoint" {
  vpc_id              = var.vpc_id
  subnet_ids          = [var.subnet_id]
  service_name        = "com.amazonaws.us-east-1.execute-api"
  vpc_endpoint_type   = "Interface"
  private_dns_enabled = false
  security_group_ids  = [aws_security_group.vpc_endpoint_sg.id]
}

```

### Debug Output
```
aws_security_group.lambda_sg2: Still destroying... [id=sg-xxxxx, 19m41s elapsed]
aws_security_group.lambda_sg2: Still destroying... [id=sg-xxxxx, 19m51s elapsed]

Error: Error deleting security group: DependencyViolation: resource sg-xxxx has a dependent object
	status code: 400, request id: xxxx-xxx-xx-xx-xxxxx

```

### Crash Output
```
2020-11-11T20:16:41.259-0600 [DEBUG] plugin.terraform-provider-aws_v3.14.1_x5: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-11-11T20:16:41.259-0600 [DEBUG] plugin.terraform-provider-aws_v3.14.1_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x204
2020-11-11T20:16:41.269-0600 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2020/11/11 20:16:41 [DEBUG] aws_security_group.lambda_sg2: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2020/11/11 20:16:41 [TRACE] eval: *terraform.EvalWriteState
2020/11/11 20:16:41 [TRACE] EvalWriteState: writing current state object for aws_security_group.lambda_sg2
2020/11/11 20:16:41 [TRACE] eval: *terraform.EvalApplyPost
2020/11/11 20:16:41 [WARN] Early exit triggered by hook: *terraform.stopHook
2020/11/11 20:16:41 [TRACE] eval: *terraform.EvalApplyPost, early exit err: early exit
2020/11/11 20:16:41 [TRACE] eval: *terraform.EvalSequence, early exit err: early exit
2020/11/11 20:16:41 [TRACE] eval: *terraform.EvalOpFilter, early exit err: early exit
2020/11/11 20:16:41 [TRACE] [walkApply] Exiting eval tree: aws_security_group.lambda_sg2 (destroy)
2020/11/11 20:16:41 [TRACE] vertex "aws_security_group.lambda_sg2 (destroy)": visit complete
2020/11/11 20:16:41 [TRACE] dag/walk: visiting "aws_security_group.vpc_endpoint_sg"
2020/11/11 20:16:41 [TRACE] vertex "aws_security_group.vpc_endpoint_sg": starting visit (*terraform.NodeApplyableResourceInstance)
2020/11/11 20:16:41 [TRACE] vertex "aws_security_group.vpc_endpoint_sg": evaluating
2020/11/11 20:16:41 [TRACE] [walkApply] Entering eval tree: aws_security_group.vpc_endpoint_sg
2020/11/11 20:16:41 [TRACE] eval: *terraform.EvalSequence
2020/11/11 20:16:41 [TRACE] eval: *terraform.EvalGetProvider
2020/11/11 20:16:41 [TRACE] eval: *terraform.EvalReadDiff
2020/11/11 20:16:41 [TRACE] EvalReadDiff: Read Update change from plan for aws_security_group.vpc_endpoint_sg
2020/11/11 20:16:41 [TRACE] eval: *terraform.EvalIf
2020/11/11 20:16:41 [TRACE] eval: terraform.EvalNoop
2020/11/11 20:16:41 [TRACE] eval: *terraform.EvalIf
2020/11/11 20:16:41 [TRACE] eval: *terraform.EvalReadState
2020/11/11 20:16:41 [TRACE] EvalReadState: reading state for aws_security_group.vpc_endpoint_sg
2020/11/11 20:16:41 [TRACE] UpgradeResourceState: schema version of aws_security_group.vpc_endpoint_sg is still 1; calling provider "aws" for any other minor fixups
2020/11/11 20:16:41 [TRACE] GRPCProvider: UpgradeResourceState
2020/11/11 20:16:41 [ERROR] eval: *terraform.EvalReadState, err: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: EOF"
2020/11/11 20:16:41 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: EOF"
2020/11/11 20:16:41 [TRACE] [walkApply] Exiting eval tree: aws_security_group.vpc_endpoint_sg
2020/11/11 20:16:41 [TRACE] vertex "aws_security_group.vpc_endpoint_sg": visit complete
2020/11/11 20:16:41 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2020/11/11 20:16:41 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/hashicorp/aws\"] (close)" errored, so skipping
2020/11/11 20:16:41 [TRACE] dag/walk: upstream of "root" errored, so skipping
2020/11/11 20:16:41 [WARN] terraform: stop complete
2020/11/11 20:16:41 [TRACE] backend/local: graceful stop has completed
2020/11/11 20:16:41 [TRACE] statemgr.Filesystem: preparing to manage state snapshots at terraform.tfstate
2020-11-11T20:16:41.270-0600 [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/hashicorp/aws/3.14.1/darwin_amd64/terraform-provider-aws_v3.14.1_x5 pid=47234 error="exit status 2"
2020/11/11 20:16:41 [TRACE] statemgr.Filesystem: existing snapshot has lineage "eab5ade0-ee72-7fb9-35d9-020b0f21eda2" serial 9
2020/11/11 20:16:41 [TRACE] statemgr.Filesystem: not making a backup, because the new snapshot is identical to the old
2020/11/11 20:16:41 [TRACE] statemgr.Filesystem: no state changes since last snapshot
2020/11/11 20:16:41 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
2020-11-11T20:16:41.278-0600 [DEBUG] plugin: plugin exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!


```

### Expected Behavior
Should be able to delete the lambda and security group when removed from terraform.

### Actual Behavior
The security group never gets deleted due to a Dependency violation:
```
aws_security_group.lambda_sg2: Still destroying... [id=sg-xxxxx, 19m41s elapsed]
aws_security_group.lambda_sg2: Still destroying... [id=sg-xxxxx, 19m51s elapsed]

Error: Error deleting security group: DependencyViolation: resource sg-xxxx has a dependent object
	status code: 400, request id: xxxx-xxx-xx-xx-xxxxx
```

### Steps to Reproduce
1. Run terraform init && terraform apply -auto-approve
2. Remove lambda_sg2, test_lambda2, and vpc_endpoint_sg's reference to aws_security_group.lambda_sg2.id
3. Re-run terraform apply -auto-approve

### LINKED ISSUE #19932: Terraform plan or destroy fails when an aws resource that is referenced by another resource is removed outside of terraform.
Problem statement:
When a terraform apply is interrupted or if someone manually deletes an AWS resource in the console, running any subsequent plan or destroy action will fail with an error message that is dependent on the specific resource in question.  Usually along the lines of "resource x cannot be found".  

​More to the point this happens when Resource A exists and references Resource B which does not exist. IE A security group rule that references a security group that no longer exists. Or an ALB Listener rule that references a target group that was deleted. 

Example: `Error: Error deleting Glue Catalog Table: EntityNotFoundException: Database myfancy_database not found.`
Example2: `Error: No security group with ID "sg-myfancysecuritygroup"`

Expected behavior:
Since the goal of a destroy is removing the item in question and previous documentation implied this: a WARN statement should be output indicating there was no action needed on the resource and the destroy should continue to remove the "parent" resource(s)
Planning - should attempt to recreate the resource if it still exists in the tf files. Understood if a refresh=true was needed here but that doesnt work either. 

I would expect both to work under the circumstances with at least executing a refresh to correct the known state of the world but for whatever reason that does not seem to help. 

Current work around isnt super practical. You are required to match the version of terraform the state was previously planned on, ensure the tf files mirror the state that is live as best as possible. Perform Terraform init, terraform workspace select, terraform state list, terraform state rm 'bad resource', terraform destroy. This is a manual, error-prone, painstaking process and when you have over 100 states in an environment .. tedious just isnt really a fitting descriptor anymore.

### LINKED ISSUE #20035: Security Group resource fails to destroy when a rule references another group or entity that does not exist
parent ticket: #19932

Problem statement. When a security resource references a resource that does not exist - more specifically if a rule uses a second security group as a source to allow traffic from and that group no longer exists (has been destroyed outside of terraform), a terraform destroy will fail with one of the following errors:

Error: No security group with ID "sg-0c9450f52f3c5e7dc"
Error: Error deleting security group: DependencyViolation: resource sg-02cd8eca8d630233c has a dependent object status 400

Expected behavior - A warning is displayed and the destroy continues to remove the resource as normal.

### LINKED ISSUE #20405: EKS node group deletion fails due to "Ec2SecurityGroupDeletionFailure: DependencyViolation - resource has a dependent object. Resource IDs: [sg-example]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.29
+ provider.aws v3.37.0
+ provider.http v2.1.0

Your version of Terraform is out of date! The latest version
is 1.0.3. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)

Error: error waiting for EKS Node Group (HRIT:CustA-HR) deletion: Ec2SecurityGroupDeletionFailure: DependencyViolation - resource has a dependent object. Resource IDs: [sg-example]

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
data "http" "workstation-external-ip" {
  url = "http://ipv4.icanhazip.com"
}

# Override with variable or hardcoded value if necessary
locals {
  workstation-external-cidr = "${chomp(data.http.workstation-external-ip.body)}/32"
}


# Provider Configuration
#

provider "aws" {
  region  = var.region
  version = ">= 2.38.0"
}

# Using these data sources allows the configuration to be
# generic for any region.
data "aws_region" "current" {}

data "aws_availability_zones" "available" {}

# Not required: currently used in conjuction with using
# icanhazip.com to determine local workstation external IP
# to open EC2 Security Group access to the Kubernetes cluster.
# See workstation-external-ip.tf for additional information.
provider "http" {}


# VPC Resources
#  * VPC
#  * Subnets
#  * Internet Gateway
#  * Route Table
#


resource "aws_route_table_association" "HR_K8s_1" {
 subnet_id = "${var.hr_k8s_1_id}"
 route_table_id = "${var.route_table_id}"
}


resource "aws_route_table_association" "HR_K8s_2" {
 subnet_id = "${var.hr_k8s_2_id}"
 route_table_id = "${var.route_table_id}"
}

resource "aws_route_table_association" "IT_K8s_1" {
 subnet_id = "${var.it_k8s_1_id}"
 route_table_id = "${var.route_table_id}"
}


resource "aws_route_table_association" "IT_K8s_2" {
 subnet_id = "${var.it_k8s_2_id}"
 route_table_id = "${var.route_table_id}"
}

resource "aws_route_table_association" "Sales_K8s_1" {
 subnet_id = "${var.sales_k8s_1_id}"
 route_table_id = "${var.route_table_id}"
}

resource "aws_route_table_association" "Sales_K8s_2" {
 subnet_id = "${var.sales_k8s_2_id}"
 route_table_id = "${var.route_table_id}"
}

resource "aws_route_table_association" "Marketing_K8s_1" {
 subnet_id = "${var.marketing_k8s_1_id}"
 route_table_id = "${var.route_table_id}"
}

resource "aws_route_table_association" "Marketing_K8s_2" {
 subnet_id = "${var.marketing_k8s_2_id}"
 route_table_id = "${var.route_table_id}"
}


# eks cluster security group configuration

#HRIT Cluster security config

resource "aws_security_group" "HRIT-cluster" {
  name        = "terraform-eks-HRIT-cluster"
  description = "Cluster communication with worker nodes"
  vpc_id      = "${var.vpc_id}"

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name = "terraform-eks-HRIT"
  }
}

resource "aws_security_group_rule" "HRIT-cluster-ingress-workstation-https" {
  cidr_blocks       = [local.workstation-external-cidr]
  description       = "Allow workstation to communicate with the cluster API Server"
  from_port         = 443
  protocol          = "tcp"
  security_group_id = aws_security_group.HRIT-cluster.id
  to_port           = 443
  type              = "ingress"
}

# HRIT Cluster creation

resource "aws_iam_role" "HRIT-cluster" {
  name = "terraform-eks-HRIT-cluster"

  assume_role_policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "eks.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
POLICY
}

resource "aws_iam_role_policy_attachment" "HRIT-cluster-AmazonEKSClusterPolicy" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
  role       = aws_iam_role.HRIT-cluster.name
}

resource "aws_iam_role_policy_attachment" "HRIT-cluster-AmazonEKSServicePolicy" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKSServicePolicy"
  role       = aws_iam_role.HRIT-cluster.name
}

resource "aws_eks_cluster" "HRIT" {
  name     = "HRIT"
  role_arn = aws_iam_role.HRIT-cluster.arn
  version = var.k8s_version

  vpc_config {
    endpoint_private_access = true
    endpoint_public_access = true
    public_access_cidrs = [local.workstation-external-cidr]
    security_group_ids = [aws_security_group.HRIT-cluster.id]
    subnet_ids         = ["${var.hr_k8s_1_id}", "${var.hr_k8s_2_id}", "${var.it_k8s_1_id}", "${var.it_k8s_2_id}"]
  }

  depends_on = [
    aws_iam_role_policy_attachment.HRIT-cluster-AmazonEKSClusterPolicy,
    aws_iam_role_policy_attachment.HRIT-cluster-AmazonEKSServicePolicy,
  ]
}

## HR worker node config

resource "aws_iam_role" "HR-node" {
  name = "terraform-eks-HR-node"

  assume_role_policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
POLICY
}

resource "aws_iam_role_policy_attachment" "HR-node-AmazonEKSWorkerNodePolicy" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy"
  role       = aws_iam_role.HR-node.name
}

resource "aws_iam_role_policy_attachment" "HR-node-AmazonEKS_CNI_Policy" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"
  role       = aws_iam_role.HR-node.name
}

resource "aws_iam_role_policy_attachment" "HR-node-AmazonEC2ContainerRegistryReadOnly" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
  role       = aws_iam_role.HR-node.name
}

resource "aws_eks_node_group" "CustA-HR" {
  disk_size       = var.custa_hr_ng_disk_size
  instance_types  = ["c5.4xlarge"]
  ami_type        = "AL2_x86_64"
  cluster_name    = aws_eks_cluster.HRIT.name
  node_group_name = "CustA-HR"
  node_role_arn   = aws_iam_role.HR-node.arn
  subnet_ids      = ["${var.hr_k8s_1_id}", "${var.hr_k8s_2_id}"]
  labels = {
    "Dept" = "HR"
    }
  remote_access {
    ec2_ssh_key = "XYZ"

  }
  scaling_config {
    desired_size = var.custa_hr_ng_desired_size
    max_size     = var.custa_hr_ng_max_size
    min_size     = var.custa_hr_ng_min_size
  }

  depends_on = [
    aws_iam_role_policy_attachment.HR-node-AmazonEKSWorkerNodePolicy,
    aws_iam_role_policy_attachment.HR-node-AmazonEKS_CNI_Policy,
    aws_iam_role_policy_attachment.HR-node-AmazonEC2ContainerRegistryReadOnly,
    aws_security_group.HRIT-cluster,
  ]
}

## IT worker node config

resource "aws_iam_role" "IT-node" {
  name = "terraform-eks-IT-node"

  assume_role_policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
POLICY
}

resource "aws_iam_role_policy_attachment" "IT-node-AmazonEKSWorkerNodePolicy" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy"
  role       = aws_iam_role.IT-node.name
}

resource "aws_iam_role_policy_attachment" "IT-node-AmazonEKS_CNI_Policy" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"
  role       = aws_iam_role.IT-node.name
}

resource "aws_iam_role_policy_attachment" "IT-node-AmazonEC2ContainerRegistryReadOnly" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
  role       = aws_iam_role.IT-node.name
}

resource "aws_eks_node_group" "CustA-IT" {
  disk_size       = var.custa_it_ng_disk_size
  instance_types  = ["c5.4xlarge"]
  ami_type        = "AL2_x86_64"
  cluster_name    = aws_eks_cluster.HRIT.name
  node_group_name = "CustA-IT"
  node_role_arn   = aws_iam_role.IT-node.arn
  subnet_ids      = ["${var.it_k8s_1_id}", "${var.it_k8s_2_id}"]
  labels = {
    "Dept" = "IT"
    }
  remote_access {
    ec2_ssh_key = "XYZ"

  }
  scaling_config {
    desired_size = var.custa_it_ng_desired_size
    max_size     = var.custa_it_ng_max_size
    min_size     = var.custa_it_ng_min_size
  }

  depends_on = [
    aws_iam_role_policy_attachment.IT-node-AmazonEKSWorkerNodePolicy,
    aws_iam_role_policy_attachment.IT-node-AmazonEKS_CNI_Policy,
    aws_iam_role_policy_attachment.IT-node-AmazonEC2ContainerRegistryReadOnly,
    aws_security_group.HRIT-cluster,
  ]
}

#Sales security group configuration

resource "aws_security_group" "Sales-cluster" {
  name        = "terraform-eks-Sales-cluster"
  description = "Cluster communication with worker nodes"
  vpc_id      = "${var.vpc_id}"

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name = "terraform-eks-Sales"
  }
}

resource "aws_security_group_rule" "Sales-cluster-ingress-workstation-https" {
  cidr_blocks       = [local.workstation-external-cidr]
  description       = "Allow workstation to communicate with the cluster API Server"
  from_port         = 443
  protocol          = "tcp"
  security_group_id = aws_security_group.Sales-cluster.id
  to_port           = 443
  type              = "ingress"
}


# Sales Cluster

resource "aws_iam_role" "Sales-cluster" {
  name = "terraform-eks-Sales-cluster"

  assume_role_policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "eks.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
POLICY
}

resource "aws_iam_role_policy_attachment" "Sales-cluster-AmazonEKSClusterPolicy" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
  role       = aws_iam_role.Sales-cluster.name
}

resource "aws_iam_role_policy_attachment" "Sales-cluster-AmazonEKSServicePolicy" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKSServicePolicy"
  role       = aws_iam_role.Sales-cluster.name
}


resource "aws_eks_cluster" "Sales" {
  name     = "Sales"
  role_arn = aws_iam_role.Sales-cluster.arn
  version = var.k8s_version

  vpc_config {
    endpoint_private_access = true
    endpoint_public_access = true
    public_access_cidrs = [local.workstation-external-cidr]
    security_group_ids = [aws_security_group.Sales-cluster.id]
    subnet_ids         = ["${var.sales_k8s_1_id}", "${var.sales_k8s_2_id}"]
  }

  depends_on = [
    aws_iam_role_policy_attachment.Sales-cluster-AmazonEKSClusterPolicy,
    aws_iam_role_policy_attachment.Sales-cluster-AmazonEKSServicePolicy,
  ]
}

## Sales worker node config

resource "aws_iam_role" "Sales-node" {
  name = "terraform-eks-Sales-node"

  assume_role_policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
POLICY
}

resource "aws_iam_role_policy_attachment" "Sales-node-AmazonEKSWorkerNodePolicy" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy"
  role       = aws_iam_role.Sales-node.name
}

resource "aws_iam_role_policy_attachment" "Sales-node-AmazonEKS_CNI_Policy" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"
  role       = aws_iam_role.Sales-node.name
}

resource "aws_iam_role_policy_attachment" "Sales-node-AmazonEC2ContainerRegistryReadOnly" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
  role       = aws_iam_role.Sales-node.name
}

resource "aws_eks_node_group" "CustA-Sales" {
  disk_size       = var.custa_sales_ng_disk_size
  instance_types  = ["t3.2xlarge"]
  ami_type        = "AL2_x86_64"
  cluster_name    = aws_eks_cluster.Sales.name
  node_group_name = "CustA-Sales"
  node_role_arn   = aws_iam_role.Sales-node.arn
  subnet_ids      = ["${var.sales_k8s_1_id}", "${var.sales_k8s_2_id}"]
  labels = {
    "Dept" = "Sales"
    }
  remote_access {
    ec2_ssh_key = "XYZ"

  }
  scaling_config {
    desired_size = var.custa_sales_ng_desired_size
    max_size     = var.custa_sales_ng_max_size
    min_size     = var.custa_sales_ng_min_size
  }

  depends_on = [
    aws_iam_role_policy_attachment.Sales-node-AmazonEKSWorkerNodePolicy,
    aws_iam_role_policy_attachment.Sales-node-AmazonEKS_CNI_Policy,
    aws_iam_role_policy_attachment.Sales-node-AmazonEC2ContainerRegistryReadOnly,
    aws_security_group.Sales-cluster,
  ]
}



#Marketing security group configuration

resource "aws_security_group" "Marketing-cluster" {
  name        = "terraform-eks-Marketing-cluster"
  description = "Cluster communication with worker nodes"
  vpc_id      = "${var.vpc_id}"

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name = "terraform-eks-Marketing"
  }
}

resource "aws_security_group_rule" "Marketing-cluster-ingress-workstation-https" {
  cidr_blocks       = [local.workstation-external-cidr]
  description       = "Allow workstation to communicate with the cluster API Server"
  from_port         = 443
  protocol          = "tcp"
  security_group_id = aws_security_group.Marketing-cluster.id
  to_port           = 443
  type              = "ingress"
}

# Marketing cluster


resource "aws_iam_role" "Marketing-cluster" {
  name = "terraform-eks-Marketing-cluster"

  assume_role_policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "eks.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
POLICY
}

resource "aws_iam_role_policy_attachment" "Marketing-cluster-AmazonEKSClusterPolicy" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
  role       = aws_iam_role.Marketing-cluster.name
}

resource "aws_iam_role_policy_attachment" "Marketing-cluster-AmazonEKSServicePolicy" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKSServicePolicy"
  role       = aws_iam_role.Marketing-cluster.name
}

resource "aws_eks_cluster" "Marketing" {
  name     = "Marketing"
  role_arn = aws_iam_role.Marketing-cluster.arn
  version = var.k8s_version

  vpc_config {
    endpoint_private_access = true
    endpoint_public_access = true
    public_access_cidrs = [local.workstation-external-cidr]
    security_group_ids = [aws_security_group.Marketing-cluster.id]
    subnet_ids         = ["${var.marketing_k8s_1_id}", "${var.marketing_k8s_2_id}"]
  }

  depends_on = [
    aws_iam_role_policy_attachment.Marketing-cluster-AmazonEKSClusterPolicy,
    aws_iam_role_policy_attachment.Marketing-cluster-AmazonEKSServicePolicy,
  ]
}

## Marketing worker node config

resource "aws_iam_role" "Marketing-node" {
  name = "terraform-eks-Marketing-node"

  assume_role_policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
POLICY
}

resource "aws_iam_role_policy_attachment" "Marketing-node-AmazonEKSWorkerNodePolicy" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy"
  role       = aws_iam_role.Marketing-node.name
}

resource "aws_iam_role_policy_attachment" "Marketing-node-AmazonEKS_CNI_Policy" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"
  role       = aws_iam_role.Marketing-node.name
}

resource "aws_iam_role_policy_attachment" "Marketing-node-AmazonEC2ContainerRegistryReadOnly" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
  role       = aws_iam_role.Marketing-node.name
}

resource "aws_eks_node_group" "CustA-Marketing" {
  disk_size       = var.custa_marketing_ng_disk_size
  instance_types  = ["c5.4xlarge"]
  ami_type        = "AL2_x86_64"
  cluster_name    = aws_eks_cluster.Marketing.name
  node_group_name = "CustA-Marketing"
  node_role_arn   = aws_iam_role.Marketing-node.arn
  subnet_ids      = ["${var.marketing_k8s_1_id}", "${var.marketing_k8s_2_id}"]
  labels = {
    "Dept" = "Marketing"
    }
  remote_access {
    ec2_ssh_key = "XYZ"

  }
  scaling_config {
    desired_size = var.custa_marketing_ng_desired_size
    max_size     = var.custa_marketing_ng_max_size
    min_size     = var.custa_marketing_ng_min_size
  }

  depends_on = [
    aws_iam_role_policy_attachment.Marketing-node-AmazonEKSWorkerNodePolicy,
    aws_iam_role_policy_attachment.Marketing-node-AmazonEKS_CNI_Policy,
    aws_iam_role_policy_attachment.Marketing-node-AmazonEC2ContainerRegistryReadOnly,
    aws_security_group.Marketing-cluster,
  ]
}

```

### Expected Behavior

Security groups should be deleted gracefully(though ENI's are linked to this SG) followed by node group deletion.

### Actual Behavior

1) Security group deletion fails. That results in nodegroup deletion failure since the security group still exists. 
2) When I tried to delete the security group from AWS console, I noticed security group couldn't be deleted as there were some ENI's still linked to this security group. 
3) manually deleting the ENI's and running"terraform destroy" helps.

### Steps to Reproduce

terraform apply
terraform destroy

### References

* #0000

### LINKED ISSUE #20743: Security group name change forces the replacement but it fails if there are linked interfaces
Piece of my configuration:

```
resource "aws_instance" "control" {
  ami = data.aws_ami.control.id
  instance_type = "t2.nano"
  subnet_id = module.vpc.public1_subnet_id
  associate_public_ip_address = true
  vpc_security_group_ids = [
    aws_security_group.control.id
  ]
}

resource "aws_security_group" "control" {
  name = "${local.infra_name_hyphen}-bastion-proxy"
  vpc_id = module.vpc.vpc_id
}
```

When I change the security group name, it is going to be replaced:

```
Terraform will perform the following actions:
  # aws_instance.control will be updated in-place
  ~ resource "aws_instance" "control" {
        id                                   = "id"
      ~ vpc_security_group_ids               = [
          - "sg-0b3b4f192869b74db",
        ] -> (known after apply)
        # (27 unchanged attributes hidden)
        # (5 unchanged blocks hidden)
    }
  # aws_security_group.control must be replaced
-/+ resource "aws_security_group" "control" {
      ~ arn                    = "arn:aws:ec2:" -> (known after apply)
      ~ id                     = "sg-0b3b4f192869b74db" -> (known after apply)
      ~ name                   = "review-dev-control-proxy" -> "review-dev-bastion-proxy" # forces replacement
      + name_prefix            = (known after apply)
        # (3 unchanged attributes hidden)
    }

...

aws_security_group.control: Still destroying... [id=sg-0b3b4f192869b74db, 11m50s elapsed]
aws_security_group.control: Still destroying... [id=sg-0b3b4f192869b74db, 12m0s elapsed]
aws_security_group.control: Still destroying... [id=sg-0b3b4f192869b74db, 12m10s elapsed]
aws_security_group.control: Still destroying... [id=sg-0b3b4f192869b74db, 12m20s elapsed]
Error: Error deleting security group: DependencyViolation: resource sg-0b3b4f192869b74db has a dependent object
	status code: 400, request id: 0fb51d70-0632-44f1-ba62-dafd14459175
```

But changes are failing because the EC2 instance's network interface is linked to the security group.

Such situations should be handled properly.

### LINKED ISSUE #20925: EKS Control Plane Security Group not getting cleaned up
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

TF: v0.13.7
hashicorp/aws v3.58.0 

### Affected Resource(s)

EKS Cluster with Fargate Type and Ec2 NodeGroup

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_eks_cluster" "main" {
  name     = join("-",[local.name_prefix,"eks-cluster"])
  role_arn = aws_iam_role.eks_cluster_role.arn
  version  = local.eks_cluster_version

  enabled_cluster_log_types = ["api", "audit", "authenticator", "controllerManager", "scheduler"]

  vpc_config {
    subnet_ids = concat(local.private_subnet_ids, local.public_subnet_ids)
  }

  depends_on = [
    aws_cloudwatch_log_group.eks_cluster,
    aws_iam_role_policy_attachment.eks_cluster_policy,
    aws_iam_role_policy_attachment.eks_service_policy,
    aws_iam_role_policy_attachment.eks_cluster_nlb_policy,
    aws_iam_role_policy_attachment.eks_controller_policy
  ]
}
```

### Debug Output

```
Error deleting VPC: DependencyViolation: The vpc 'vpc-025bfcbeeeeeeddddf22' has dependencies and cannot be deleted
```

### Panic Output

Error deleting VPC: DependencyViolation: The vpc 'vpc-025bfcbeeeeeeddddf22' has dependencies and cannot be deleted

### Expected Behavior

TF should delete SG associated with EKS 

### Actual Behavior

SG is not getting deleted

### Steps to Reproduce

We are using Terraform to provision EKS Cluster. Creation of cluster is going smooth but deletion of it SG is not happening. 

Below policies are being used in EKS Cluster and I can confirm that these policy attachments are only getting deleted post cluster deletion so here there is no case of policy deletion happening first and then cluster. 

AmazonEKSClusterPolicy
AmazonEKSServicePolicy
AmazonEKSVPCResourceController and

Custom Policy: {
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "elasticloadbalancing:*",
                "ec2:CreateSecurityGroup",
                "ec2:DeleteSecurityGroup",
                "ec2:Describe*"
            ],
            "Resource": "*",
            "Effect": "Allow"
        }
    ]
}

All the above policies are being used in eks cluster role_arn.  While performing terraform delete operations all the resources are getting destroyed successfully but SG ( EKS created security group applied to ENI that is attached to EKS Control Plane master nodes, as well as any managed workloads.) is not getting deleted. 

PS: Consulted AWS Support team for the same and they conclude that SG deletion call was received but at that time SG was attached with ENI of the master plane so call was not successful.  TF didn't even send 2nd call to check its existence. 

Also seen EKS Cluster destroy is happening in 30s-1m and then this error is coming.

### LINKED ISSUE #26090: ENI is not deleted when sagemaker notebook instance is destroyed and a security group is attached to it
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
* Terraform v1.1.9
* provider registry.terraform.io/hashicorp/aws v4.24.0

### Affected Resource(s)

* aws_sagemaker_notebook_instance
* aws_security_group

### Terraform Configuration Files

Actually I'm using a simple configuration with two different modules.
The idea is to create an AWS sagemaker notebook instance in a subnet and then attach a SG to it.

```hcl
module "sagemaker_notebook_instance" {
  source                   = "../../../modules/sagemaker-notebookinstance"
  instance_type            = "ml.t2.medium"
  name                     = "test-sg"
  instance_subnet_id       = "subnet-0751a8c66XXXXXXXX" # hidden
  instance_security_groups = [module.security-group.id]
}

module "security-group" {
  source      = "../../../modules/security-group"
  name        = "sagemaker-test-sg"
  description = "sagemaker-test security group"
  vpc_id      = "vpc-06c413a2eXXXXXXXX" # hidden
}
```

#### Some detail about the two modules
```hcl
resource "aws_sagemaker_notebook_instance" "sagemaker_instance" {
  for_each                = var.instance_ids
  instance_type           = var.instance_type
  name                    = join("-", [module.resource_naming.composed_resource_name, each.value])
  role_arn                = aws_iam_role.default.arn
  lifecycle_config_name   = var.create_lifecycle ? aws_sagemaker_notebook_instance_lifecycle_configuration.sagemaker_lifecycle_conf[0].name : ""
  default_code_repository = var.create_git_config ? aws_sagemaker_code_repository.repo[0].code_repository_name : ""

  subnet_id              = var.instance_subnet_id
  security_groups        = var.instance_security_groups
  kms_key_id             = var.instance_kms_key_id
  direct_internet_access = var.instance_direct_internet_access

  lifecycle {
    create_before_destroy = true
    ignore_changes        = []
  }
}
```

```hcl
resource "aws_security_group" "self_sg" {
  name_prefix = module.resource_naming.composed_resource_name
  description = var.description
  vpc_id      = var.vpc_id

  ingress {
    description = "Allow inbound traffic from network interfaces (and their associated instances) that are assigned to the same security group."
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    self        = true
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  lifecycle {
    create_before_destroy = true
  }
}
```

### Expected Behavior

ENI should be removed when terraform tries to destroy our sagemaker notebook instance, in order to avoid `dependency violations` when security group is deleted. Actually, this creates a deadlock and our security group cannot be deleted.

The basic idea is that we need to delete ENI resource before trying to delete the attached SG. In the following AWS provider doc is described the process to use in order to avoid stucks during SG config changes, but is not mentioned how to overcome a fully deletion problem
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group#change-of-name-or-name-prefix-value

### Actual Behavior
After a bit, terraform destroy fails because ENI still exists and security group cannot be deleted.

```bash
...
module.security-group.aws_security_group.self_sg: Still destroying... [id=sg-08cb8e3c478XXXXXX, 14m30s elapsed]
module.security-group.aws_security_group.self_sg: Still destroying... [id=sg-08cb8e3c478XXXXXX, 14m40s elapsed]
module.security-group.aws_security_group.self_sg: Still destroying... [id=sg-08cb8e3c478XXXXXX, 14m50s elapsed]
╷
│ Error: deleting Security Group (sg-08cb8e3c478XXXXXX): DependencyViolation: resource sg-08cb8e3c478XXXXXX has a dependent object
│       status code: 400, request id: 96f38922-3170-4dec-93c7-92c39XXXXXX
│
│
╵
```

### Steps to Reproduce

1. terraform apply
2. terraform destroy

### References

Probably this issue is similar to:
* https://github.com/hashicorp/terraform-provider-aws/issues/10329
* https://github.com/hashicorp/terraform/issues/10272

### PR DESCRIPTION
**Pull request by YakDriver**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #1671
Closes #8285
Closes #8769
Relates #10329 
Closes #12394
Relates #12396
Closes #12420
Closes #13228
Closes #16165
Relates #18559
Closes #19932
Closes #20035
Closes #20405
Closes #20743
Closes #20925
Relates #23488 
Closes #26090

Output from acceptance testing:

```console
% make testacc TESTS=TestAccVPCSecurityGroup_ PKG=ec2         
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccVPCSecurityGroup_'  -timeout 180m
--- PASS: TestAccVPCSecurityGroup_invalidCIDRBlock (9.79s)
--- PASS: TestAccVPCSecurityGroup_drift (93.59s)
--- PASS: TestAccVPCSecurityGroup_cidrAndGroups (104.10s)
--- PASS: TestAccVPCSecurityGroup_failWithDiffMismatch (105.54s)
--- PASS: TestAccVPCSecurityGroup_basic (111.49s)
--- PASS: TestAccVPCSecurityGroup_vpcNegOneIngress (111.68s)
--- PASS: TestAccVPCSecurityGroup_self (102.55s)
--- PASS: TestAccVPCSecurityGroup_vpc (112.34s)
--- PASS: TestAccVPCSecurityGroup_ipRangesWithSameRules (112.54s)
--- PASS: TestAccVPCSecurityGroup_driftComplex (114.84s)
--- PASS: TestAccVPCSecurityGroup_ingressWithCIDRAndSGsVPC (115.03s)
--- PASS: TestAccVPCSecurityGroup_ipv4AndIPv6Egress (121.28s)
--- PASS: TestAccVPCSecurityGroup_egressWithPrefixList (127.12s)
--- PASS: TestAccVPCSecurityGroup_ingressWithPrefixList (129.94s)
--- PASS: TestAccVPCSecurityGroup_rulesDropOnError (171.17s)
--- PASS: TestAccVPCSecurityGroup_RuleLimit_cidrBlockExceededAppend (187.09s)
--- PASS: TestAccVPCSecurityGroup_ipv6 (103.98s)
--- PASS: TestAccVPCSecurityGroup_defaultEgressVPC (96.23s)
--- PASS: TestAccVPCSecurityGroup_RuleLimit_exceededAppend (244.95s)
--- PASS: TestAccVPCSecurityGroup_namePrefixTerraform (106.25s)
--- PASS: TestAccVPCSecurityGroup_sourceSecurityGroup (115.38s)
--- PASS: TestAccVPCSecurityGroup_allowAll (115.61s)
--- PASS: TestAccVPCSecurityGroup_RuleLimit_exceededAllNew (230.75s)
--- PASS: TestAccVPCSecurityGroup_ipRangeAndSecurityGroupWithSameRules (118.60s)
--- PASS: TestAccVPCSecurityGroup_ruleGathering (125.96s)
--- PASS: TestAccVPCSecurityGroup_multiIngress (110.93s)
--- PASS: TestAccVPCSecurityGroup_RuleLimit_exceededPrepend (240.74s)
--- PASS: TestAccVPCSecurityGroup_vpcProtoNumIngress (87.60s)
--- PASS: TestAccVPCSecurityGroup_change (157.58s)
--- PASS: TestAccVPCSecurityGroup_nameTerraformPrefix (83.18s)
--- PASS: TestAccVPCSecurityGroup_disappears (59.65s)
--- PASS: TestAccVPCSecurityGroup_namePrefix (79.78s)
--- PASS: TestAccVPCSecurityGroup_nameGenerated (75.91s)
--- PASS: TestAccVPCSecurityGroup_ingressMode (186.22s)
--- PASS: TestAccVPCSecurityGroup_egressMode (173.33s)
--- PASS: TestAccVPCSecurityGroup_tags (182.14s)
--- PASS: TestAccVPCSecurityGroup_ruleDescription (128.42s)
--- PASS: TestAccVPCSecurityGroup_forceRevokeRulesTrue (487.29s)
--- PASS: TestAccVPCSecurityGroup_emrDependencyViolation (819.83s)
--- PASS: TestAccVPCSecurityGroup_forceRevokeRulesFalse (1213.36s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	1243.196s
% make testacc TESTS=TestAccVPCDefaultSecurityGroup_ PKG=ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccVPCDefaultSecurityGroup_'  -timeout 180m
--- PASS: TestAccVPCDefaultSecurityGroup_empty (45.12s)
--- PASS: TestAccVPCDefaultSecurityGroup_basic (63.67s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	64.994s
% make testacc TESTS=TestAccVPCSecurityGroupRule_ PKG=ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccVPCSecurityGroupRule_'  -timeout 180m
--- PASS: TestAccVPCSecurityGroupRule_expectInvalidTypeError (8.14s)
--- PASS: TestAccVPCSecurityGroupRule_prefixListEmptyString (8.45s)
--- PASS: TestAccVPCSecurityGroupRule_expectInvalidCIDR (10.47s)
--- PASS: TestAccVPCSecurityGroupRule_Ingress_icmpv6 (113.47s)
--- PASS: TestAccVPCSecurityGroupRule_selfReference (122.56s)
--- PASS: TestAccVPCSecurityGroupRule_egress (123.42s)
--- PASS: TestAccVPCSecurityGroupRule_Ingress_protocol (124.46s)
--- PASS: TestAccVPCSecurityGroupRule_Ingress_vpc (124.96s)
--- PASS: TestAccVPCSecurityGroupRule_issue5310 (124.97s)
--- PASS: TestAccVPCSecurityGroupRule_egressDescription (118.29s)
--- PASS: TestAccVPCSecurityGroupRule_selfSource (130.95s)
--- PASS: TestAccVPCSecurityGroupRule_Ingress_ipv6 (131.29s)
--- PASS: TestAccVPCSecurityGroupRule_Ingress_prefixListAndSource (137.94s)
--- PASS: TestAccVPCSecurityGroupRule_prefixListEgress (139.94s)
--- PASS: TestAccVPCSecurityGroupRule_MultipleRuleSearching_allProtocolCrash (142.10s)
--- PASS: TestAccVPCSecurityGroupRule_PartialMatching_source (143.64s)
--- PASS: TestAccVPCSecurityGroupRule_Ingress_peeredVPC (138.29s)
--- PASS: TestAccVPCSecurityGroupRule_DescriptionAllPorts_nonZeroPorts (173.84s)
--- PASS: TestAccVPCSecurityGroupRule_EgressDescription_updates (177.10s)
--- PASS: TestAccVPCSecurityGroupRule_IngressDescription_updates (176.52s)
--- PASS: TestAccVPCSecurityGroupRule_IngressSourceWithAccount_id (81.66s)
--- PASS: TestAccVPCSecurityGroupRule_ingressDescription (81.45s)
--- PASS: TestAccVPCSecurityGroupRule_Ingress_ipv4AndIPv6 (88.87s)
--- PASS: TestAccVPCSecurityGroupRule_Ingress_prefixListAndSelf (99.13s)
--- PASS: TestAccVPCSecurityGroupRule_Ingress_multipleIPv6 (83.11s)
--- PASS: TestAccVPCSecurityGroupRule_Ingress_multiplePrefixLists (93.01s)
--- PASS: TestAccVPCSecurityGroupRule_PartialMatching_basic (100.79s)
--- PASS: TestAccVPCSecurityGroupRule_protocolChange (232.63s)
--- PASS: TestAccVPCSecurityGroupRule_Description_allPorts (113.62s)
--- PASS: TestAccVPCSecurityGroupRule_multiDescription (245.23s)
--- PASS: TestAccVPCSecurityGroupRule_race (264.08s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	265.527s
% make testacc TESTS=TestAccVPCSecurityGroupDataSource_ PKG=vpc
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccVPCSecurityGroupDataSource_'  -timeout 180m
--- PASS: TestAccVPCSecurityGroupDataSource_basic (41.97s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	43.270s
% make testacc TESTS=TestAccVPCSecurityGroupsDataSource_ PKG=vpc   
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccVPCSecurityGroupsDataSource_'  -timeout 180m
--- PASS: TestAccVPCSecurityGroupsDataSource_empty (27.66s)
--- PASS: TestAccVPCSecurityGroupsDataSource_filter (42.80s)
--- PASS: TestAccVPCSecurityGroupsDataSource_tag (43.87s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	45.272s
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
The `go test` error is a timeout in the `internal/service/ec2` package:

```
panic: test timed out after 10m0s

goroutine 1101 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.18.4/x64/src/testing/testing.go:2029 +0x8e
created by time.goFunc
	/opt/hostedtoolcache/go/1.18.4/x64/src/time/sleep.go:176 +0x32

goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc002034ea0, {0xa56ea82?, 0x516285?}, 0xa6ae3e0)
	/opt/hostedtoolcache/go/1.18.4/x64/src/testing/testing.go:1487 +0x37a
testing.runTests.func1(0xc002034ea0?)
	/opt/hostedtoolcache/go/1.18.4/x64/src/testing/testing.go:1839 +0x6e
testing.tRunner(0xc00[203](https://github.com/hashicorp/terraform-provider-aws/runs/8103733354?check_suite_focus=true#step:7:204)4ea0, 0xc0016bfcd8)
	/opt/hostedtoolcache/go/1.18.4/x64/src/testing/testing.go:1439 +0x102
testing.runTests(0xc00[204](https://github.com/hashicorp/terraform-provider-aws/runs/8103733354?check_suite_focus=true#step:7:205)46e0?, {0x10b6b3c0, 0x46b, 0x46b}, {0x7f263b5c85b8?, 0x40?, 0x10b79da0?})
	/opt/hostedtoolcache/go/1.18.4/x64/src/testing/testing.go:1837 +0x457
testing.(*M).Run(0xc0020446e0)
	/opt/hostedtoolcache/go/1.18.4/x64/src/testing/testing.go:1719 +0x5d9
main.main()
	_testmain.go:2309 +0x1aa

goroutine 50 [chan receive, 10 minutes]:
testing.(*T).Parallel(0xc002072d00)
	/opt/hostedtoolcache/go/1.18.4/x64/src/testing/testing.go:1264 +0x1bf
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.ParallelTest({0xb2dc748, 0xc002072d00}, {0x0, 0xc000947140, 0x0, 0xc00203b560, 0x0, 0x0, 0x0, 0x0, ...})
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.21.0/helper/resource/testing.go:646 +0x55
github.com/hashicorp/terraform-provider-aws/internal/service/ec2_test.TestAccEC2EBSDefaultKMSKeyDataSource_basic(0xc002072d00)
	/home/runner/work/terraform-provider-aws/terraform-provider-aws/internal/service/ec2/ebs_default_kms_key_data_source_test.go:12 +0x207
testing.tRunner(0xc002072d00, 0xa6ac088)
	/opt/hostedtoolcache/go/1.18.4/x64/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.18.4/x64/src/testing/testing.go:1486 +0x35f
...
```

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% ACCTEST_TIMEOUT=360m make testacc TESTARGS='-run=TestAccVPCSecurityGroup\|TestAccVPCDefaultSecurityGroup' PKG=ec2 ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 2  -run=TestAccVPCSecurityGroup\|TestAccVPCDefaultSecurityGroup -timeout 360m
=== RUN   TestAccVPCDefaultSecurityGroup_basic
=== PAUSE TestAccVPCDefaultSecurityGroup_basic
=== RUN   TestAccVPCDefaultSecurityGroup_empty
=== PAUSE TestAccVPCDefaultSecurityGroup_empty
=== RUN   TestAccVPCSecurityGroupDataSource_basic
=== PAUSE TestAccVPCSecurityGroupDataSource_basic
=== RUN   TestAccVPCSecurityGroupRule_Ingress_vpc
=== PAUSE TestAccVPCSecurityGroupRule_Ingress_vpc
=== RUN   TestAccVPCSecurityGroupRule_IngressSourceWithAccount_id
=== PAUSE TestAccVPCSecurityGroupRule_IngressSourceWithAccount_id
=== RUN   TestAccVPCSecurityGroupRule_Ingress_protocol
=== PAUSE TestAccVPCSecurityGroupRule_Ingress_protocol
=== RUN   TestAccVPCSecurityGroupRule_Ingress_icmpv6
=== PAUSE TestAccVPCSecurityGroupRule_Ingress_icmpv6
=== RUN   TestAccVPCSecurityGroupRule_Ingress_ipv6
=== PAUSE TestAccVPCSecurityGroupRule_Ingress_ipv6
=== RUN   TestAccVPCSecurityGroupRule_egress
=== PAUSE TestAccVPCSecurityGroupRule_egress
=== RUN   TestAccVPCSecurityGroupRule_selfReference
=== PAUSE TestAccVPCSecurityGroupRule_selfReference
=== RUN   TestAccVPCSecurityGroupRule_expectInvalidTypeError
=== PAUSE TestAccVPCSecurityGroupRule_expectInvalidTypeError
=== RUN   TestAccVPCSecurityGroupRule_expectInvalidCIDR
=== PAUSE TestAccVPCSecurityGroupRule_expectInvalidCIDR
=== RUN   TestAccVPCSecurityGroupRule_PartialMatching_basic
=== PAUSE TestAccVPCSecurityGroupRule_PartialMatching_basic
=== RUN   TestAccVPCSecurityGroupRule_PartialMatching_source
=== PAUSE TestAccVPCSecurityGroupRule_PartialMatching_source
=== RUN   TestAccVPCSecurityGroupRule_issue5310
=== PAUSE TestAccVPCSecurityGroupRule_issue5310
=== RUN   TestAccVPCSecurityGroupRule_race
=== PAUSE TestAccVPCSecurityGroupRule_race
=== RUN   TestAccVPCSecurityGroupRule_selfSource
=== PAUSE TestAccVPCSecurityGroupRule_selfSource
=== RUN   TestAccVPCSecurityGroupRule_prefixListEgress
=== PAUSE TestAccVPCSecurityGroupRule_prefixListEgress
=== RUN   TestAccVPCSecurityGroupRule_prefixListEmptyString
=== PAUSE TestAccVPCSecurityGroupRule_prefixListEmptyString
=== RUN   TestAccVPCSecurityGroupRule_ingressDescription
=== PAUSE TestAccVPCSecurityGroupRule_ingressDescription
=== RUN   TestAccVPCSecurityGroupRule_egressDescription
=== PAUSE TestAccVPCSecurityGroupRule_egressDescription
=== RUN   TestAccVPCSecurityGroupRule_IngressDescription_updates
=== PAUSE TestAccVPCSecurityGroupRule_IngressDescription_updates
=== RUN   TestAccVPCSecurityGroupRule_EgressDescription_updates
=== PAUSE TestAccVPCSecurityGroupRule_EgressDescription_updates
=== RUN   TestAccVPCSecurityGroupRule_Description_allPorts
=== PAUSE TestAccVPCSecurityGroupRule_Description_allPorts
=== RUN   TestAccVPCSecurityGroupRule_DescriptionAllPorts_nonZeroPorts
=== PAUSE TestAccVPCSecurityGroupRule_DescriptionAllPorts_nonZeroPorts
=== RUN   TestAccVPCSecurityGroupRule_MultipleRuleSearching_allProtocolCrash
=== PAUSE TestAccVPCSecurityGroupRule_MultipleRuleSearching_allProtocolCrash
=== RUN   TestAccVPCSecurityGroupRule_multiDescription
=== PAUSE TestAccVPCSecurityGroupRule_multiDescription
=== RUN   TestAccVPCSecurityGroupRule_Ingress_multipleIPv6
=== PAUSE TestAccVPCSecurityGroupRule_Ingress_multipleIPv6
=== RUN   TestAccVPCSecurityGroupRule_Ingress_multiplePrefixLists
=== PAUSE TestAccVPCSecurityGroupRule_Ingress_multiplePrefixLists
=== RUN   TestAccVPCSecurityGroupRule_Ingress_peeredVPC
=== PAUSE TestAccVPCSecurityGroupRule_Ingress_peeredVPC
=== RUN   TestAccVPCSecurityGroupRule_Ingress_ipv4AndIPv6
=== PAUSE TestAccVPCSecurityGroupRule_Ingress_ipv4AndIPv6
=== RUN   TestAccVPCSecurityGroupRule_Ingress_prefixListAndSelf
=== PAUSE TestAccVPCSecurityGroupRule_Ingress_prefixListAndSelf
=== RUN   TestAccVPCSecurityGroupRule_Ingress_prefixListAndSource
=== PAUSE TestAccVPCSecurityGroupRule_Ingress_prefixListAndSource
=== RUN   TestAccVPCSecurityGroupRule_protocolChange
=== PAUSE TestAccVPCSecurityGroupRule_protocolChange
=== RUN   TestAccVPCSecurityGroup_basic
=== PAUSE TestAccVPCSecurityGroup_basic
=== RUN   TestAccVPCSecurityGroup_disappears
=== PAUSE TestAccVPCSecurityGroup_disappears
=== RUN   TestAccVPCSecurityGroup_nameGenerated
=== PAUSE TestAccVPCSecurityGroup_nameGenerated
=== RUN   TestAccVPCSecurityGroup_nameTerraformPrefix
=== PAUSE TestAccVPCSecurityGroup_nameTerraformPrefix
=== RUN   TestAccVPCSecurityGroup_namePrefix
=== PAUSE TestAccVPCSecurityGroup_namePrefix
=== RUN   TestAccVPCSecurityGroup_namePrefixTerraform
=== PAUSE TestAccVPCSecurityGroup_namePrefixTerraform
=== RUN   TestAccVPCSecurityGroup_tags
=== PAUSE TestAccVPCSecurityGroup_tags
=== RUN   TestAccVPCSecurityGroup_allowAll
=== PAUSE TestAccVPCSecurityGroup_allowAll
=== RUN   TestAccVPCSecurityGroup_sourceSecurityGroup
=== PAUSE TestAccVPCSecurityGroup_sourceSecurityGroup
=== RUN   TestAccVPCSecurityGroup_ipRangeAndSecurityGroupWithSameRules
=== PAUSE TestAccVPCSecurityGroup_ipRangeAndSecurityGroupWithSameRules
=== RUN   TestAccVPCSecurityGroup_ipRangesWithSameRules
=== PAUSE TestAccVPCSecurityGroup_ipRangesWithSameRules
=== RUN   TestAccVPCSecurityGroup_egressMode
=== PAUSE TestAccVPCSecurityGroup_egressMode
=== RUN   TestAccVPCSecurityGroup_ingressMode
=== PAUSE TestAccVPCSecurityGroup_ingressMode
=== RUN   TestAccVPCSecurityGroup_ruleGathering
=== PAUSE TestAccVPCSecurityGroup_ruleGathering
=== RUN   TestAccVPCSecurityGroup_forceRevokeRulesTrue
=== PAUSE TestAccVPCSecurityGroup_forceRevokeRulesTrue
=== RUN   TestAccVPCSecurityGroup_forceRevokeRulesFalse
=== PAUSE TestAccVPCSecurityGroup_forceRevokeRulesFalse
=== RUN   TestAccVPCSecurityGroup_change
=== PAUSE TestAccVPCSecurityGroup_change
=== RUN   TestAccVPCSecurityGroup_ipv6
=== PAUSE TestAccVPCSecurityGroup_ipv6
=== RUN   TestAccVPCSecurityGroup_self
=== PAUSE TestAccVPCSecurityGroup_self
=== RUN   TestAccVPCSecurityGroup_vpc
=== PAUSE TestAccVPCSecurityGroup_vpc
=== RUN   TestAccVPCSecurityGroup_vpcNegOneIngress
=== PAUSE TestAccVPCSecurityGroup_vpcNegOneIngress
=== RUN   TestAccVPCSecurityGroup_vpcProtoNumIngress
=== PAUSE TestAccVPCSecurityGroup_vpcProtoNumIngress
=== RUN   TestAccVPCSecurityGroup_multiIngress
=== PAUSE TestAccVPCSecurityGroup_multiIngress
=== RUN   TestAccVPCSecurityGroup_ruleDescription
=== PAUSE TestAccVPCSecurityGroup_ruleDescription
=== RUN   TestAccVPCSecurityGroup_defaultEgressVPC
=== PAUSE TestAccVPCSecurityGroup_defaultEgressVPC
=== RUN   TestAccVPCSecurityGroup_drift
=== PAUSE TestAccVPCSecurityGroup_drift
=== RUN   TestAccVPCSecurityGroup_driftComplex
=== PAUSE TestAccVPCSecurityGroup_driftComplex
=== RUN   TestAccVPCSecurityGroup_invalidCIDRBlock
=== PAUSE TestAccVPCSecurityGroup_invalidCIDRBlock
=== RUN   TestAccVPCSecurityGroup_cidrAndGroups
=== PAUSE TestAccVPCSecurityGroup_cidrAndGroups
=== RUN   TestAccVPCSecurityGroup_ingressWithCIDRAndSGsVPC
=== PAUSE TestAccVPCSecurityGroup_ingressWithCIDRAndSGsVPC
=== RUN   TestAccVPCSecurityGroup_egressWithPrefixList
=== PAUSE TestAccVPCSecurityGroup_egressWithPrefixList
=== RUN   TestAccVPCSecurityGroup_ingressWithPrefixList
=== PAUSE TestAccVPCSecurityGroup_ingressWithPrefixList
=== RUN   TestAccVPCSecurityGroup_ipv4AndIPv6Egress
=== PAUSE TestAccVPCSecurityGroup_ipv4AndIPv6Egress
=== RUN   TestAccVPCSecurityGroup_failWithDiffMismatch
=== PAUSE TestAccVPCSecurityGroup_failWithDiffMismatch
=== RUN   TestAccVPCSecurityGroup_RuleLimit_exceededAppend
=== PAUSE TestAccVPCSecurityGroup_RuleLimit_exceededAppend
=== RUN   TestAccVPCSecurityGroup_RuleLimit_cidrBlockExceededAppend
=== PAUSE TestAccVPCSecurityGroup_RuleLimit_cidrBlockExceededAppend
=== RUN   TestAccVPCSecurityGroup_RuleLimit_exceededPrepend
=== PAUSE TestAccVPCSecurityGroup_RuleLimit_exceededPrepend
=== RUN   TestAccVPCSecurityGroup_RuleLimit_exceededAllNew
=== PAUSE TestAccVPCSecurityGroup_RuleLimit_exceededAllNew
=== RUN   TestAccVPCSecurityGroup_rulesDropOnError
=== PAUSE TestAccVPCSecurityGroup_rulesDropOnError
=== RUN   TestAccVPCSecurityGroup_emrDependencyViolation
=== PAUSE TestAccVPCSecurityGroup_emrDependencyViolation
=== RUN   TestAccVPCSecurityGroupsDataSource_tag
=== PAUSE TestAccVPCSecurityGroupsDataSource_tag
=== RUN   TestAccVPCSecurityGroupsDataSource_filter
=== PAUSE TestAccVPCSecurityGroupsDataSource_filter
=== RUN   TestAccVPCSecurityGroupsDataSource_empty
=== PAUSE TestAccVPCSecurityGroupsDataSource_empty
=== CONT  TestAccVPCDefaultSecurityGroup_basic
=== CONT  TestAccVPCSecurityGroup_namePrefixTerraform
--- PASS: TestAccVPCSecurityGroup_namePrefixTerraform (27.28s)
=== CONT  TestAccVPCSecurityGroup_defaultEgressVPC
--- PASS: TestAccVPCDefaultSecurityGroup_basic (35.15s)
=== CONT  TestAccVPCSecurityGroupsDataSource_empty
--- PASS: TestAccVPCSecurityGroupsDataSource_empty (12.39s)
=== CONT  TestAccVPCSecurityGroupsDataSource_filter
--- PASS: TestAccVPCSecurityGroup_defaultEgressVPC (26.32s)
=== CONT  TestAccVPCSecurityGroupsDataSource_tag
--- PASS: TestAccVPCSecurityGroupsDataSource_filter (25.13s)
=== CONT  TestAccVPCSecurityGroup_emrDependencyViolation
--- PASS: TestAccVPCSecurityGroupsDataSource_tag (23.79s)
=== CONT  TestAccVPCSecurityGroup_rulesDropOnError
--- PASS: TestAccVPCSecurityGroup_rulesDropOnError (44.80s)
=== CONT  TestAccVPCSecurityGroup_RuleLimit_exceededAllNew
--- PASS: TestAccVPCSecurityGroup_RuleLimit_exceededAllNew (52.68s)
=== CONT  TestAccVPCSecurityGroup_RuleLimit_exceededPrepend
--- PASS: TestAccVPCSecurityGroup_RuleLimit_exceededPrepend (50.88s)
=== CONT  TestAccVPCSecurityGroup_RuleLimit_cidrBlockExceededAppend
--- PASS: TestAccVPCSecurityGroup_RuleLimit_cidrBlockExceededAppend (41.33s)
=== CONT  TestAccVPCSecurityGroup_RuleLimit_exceededAppend
--- PASS: TestAccVPCSecurityGroup_RuleLimit_exceededAppend (65.25s)
=== CONT  TestAccVPCSecurityGroup_failWithDiffMismatch
--- PASS: TestAccVPCSecurityGroup_failWithDiffMismatch (29.13s)
=== CONT  TestAccVPCSecurityGroup_forceRevokeRulesFalse
--- PASS: TestAccVPCSecurityGroup_emrDependencyViolation (831.65s)
=== CONT  TestAccVPCSecurityGroup_ruleDescription
--- PASS: TestAccVPCSecurityGroup_ruleDescription (56.41s)
=== CONT  TestAccVPCSecurityGroup_multiIngress
--- PASS: TestAccVPCSecurityGroup_multiIngress (32.76s)
=== CONT  TestAccVPCSecurityGroup_vpcProtoNumIngress
--- PASS: TestAccVPCSecurityGroup_vpcProtoNumIngress (25.52s)
=== CONT  TestAccVPCSecurityGroup_vpcNegOneIngress
--- PASS: TestAccVPCSecurityGroup_vpcNegOneIngress (23.64s)
=== CONT  TestAccVPCSecurityGroup_ipv4AndIPv6Egress
--- PASS: TestAccVPCSecurityGroup_ipv4AndIPv6Egress (34.17s)
=== CONT  TestAccVPCSecurityGroup_ingressWithPrefixList
--- PASS: TestAccVPCSecurityGroup_ingressWithPrefixList (38.59s)
=== CONT  TestAccVPCSecurityGroup_egressWithPrefixList
--- PASS: TestAccVPCSecurityGroup_egressWithPrefixList (40.30s)
=== CONT  TestAccVPCSecurityGroup_vpc
--- PASS: TestAccVPCSecurityGroup_vpc (27.85s)
=== CONT  TestAccVPCSecurityGroup_ingressWithCIDRAndSGsVPC
--- PASS: TestAccVPCSecurityGroup_ingressWithCIDRAndSGsVPC (31.76s)
=== CONT  TestAccVPCSecurityGroup_self
--- PASS: TestAccVPCSecurityGroup_self (25.03s)
=== CONT  TestAccVPCSecurityGroupRule_egressDescription
--- PASS: TestAccVPCSecurityGroupRule_egressDescription (19.97s)
=== CONT  TestAccVPCSecurityGroup_cidrAndGroups
--- PASS: TestAccVPCSecurityGroup_cidrAndGroups (28.23s)
=== CONT  TestAccVPCSecurityGroup_ipv6
--- PASS: TestAccVPCSecurityGroup_ipv6 (25.25s)
=== CONT  TestAccVPCSecurityGroup_invalidCIDRBlock
--- PASS: TestAccVPCSecurityGroup_invalidCIDRBlock (1.98s)
=== CONT  TestAccVPCSecurityGroup_change
--- PASS: TestAccVPCSecurityGroup_change (37.43s)
=== CONT  TestAccVPCSecurityGroup_namePrefix
--- PASS: TestAccVPCSecurityGroup_namePrefix (24.30s)
=== CONT  TestAccVPCSecurityGroup_driftComplex
--- PASS: TestAccVPCSecurityGroup_driftComplex (30.90s)
=== CONT  TestAccVPCSecurityGroup_nameTerraformPrefix
--- PASS: TestAccVPCSecurityGroup_forceRevokeRulesFalse (1080.95s)
=== CONT  TestAccVPCSecurityGroup_drift
--- PASS: TestAccVPCSecurityGroup_nameTerraformPrefix (26.97s)
=== CONT  TestAccVPCSecurityGroup_ipRangesWithSameRules
--- PASS: TestAccVPCSecurityGroup_drift (19.70s)
=== CONT  TestAccVPCSecurityGroup_ruleGathering
--- PASS: TestAccVPCSecurityGroup_ipRangesWithSameRules (25.78s)
=== CONT  TestAccVPCSecurityGroup_nameGenerated
--- PASS: TestAccVPCSecurityGroup_nameGenerated (24.44s)
=== CONT  TestAccVPCSecurityGroup_forceRevokeRulesTrue
--- PASS: TestAccVPCSecurityGroup_ruleGathering (40.36s)
=== CONT  TestAccVPCSecurityGroup_disappears
--- PASS: TestAccVPCSecurityGroup_disappears (21.36s)
=== CONT  TestAccVPCSecurityGroupRule_Ingress_protocol
--- PASS: TestAccVPCSecurityGroupRule_Ingress_protocol (24.98s)
=== CONT  TestAccVPCSecurityGroup_basic
--- PASS: TestAccVPCSecurityGroup_basic (24.54s)
=== CONT  TestAccVPCSecurityGroupRule_selfReference
--- PASS: TestAccVPCSecurityGroupRule_selfReference (25.55s)
=== CONT  TestAccVPCSecurityGroupRule_protocolChange
--- PASS: TestAccVPCSecurityGroupRule_protocolChange (61.72s)
=== CONT  TestAccVPCSecurityGroupRule_egress
--- PASS: TestAccVPCSecurityGroupRule_egress (21.10s)
=== CONT  TestAccVPCSecurityGroupRule_expectInvalidTypeError
--- PASS: TestAccVPCSecurityGroupRule_expectInvalidTypeError (0.89s)
=== CONT  TestAccVPCSecurityGroup_ingressMode
--- PASS: TestAccVPCSecurityGroup_ingressMode (47.87s)
=== CONT  TestAccVPCSecurityGroupRule_Ingress_ipv6
--- PASS: TestAccVPCSecurityGroupRule_Ingress_ipv6 (26.11s)
=== CONT  TestAccVPCSecurityGroupRule_Ingress_prefixListAndSource
--- PASS: TestAccVPCSecurityGroupRule_Ingress_prefixListAndSource (34.80s)
=== CONT  TestAccVPCSecurityGroupRule_ingressDescription
--- PASS: TestAccVPCSecurityGroupRule_ingressDescription (26.31s)
=== CONT  TestAccVPCSecurityGroupRule_Ingress_icmpv6
--- PASS: TestAccVPCSecurityGroup_forceRevokeRulesTrue (338.71s)
=== CONT  TestAccVPCSecurityGroup_egressMode
--- PASS: TestAccVPCSecurityGroupRule_Ingress_icmpv6 (28.40s)
=== CONT  TestAccVPCSecurityGroupRule_Ingress_prefixListAndSelf
--- PASS: TestAccVPCSecurityGroupRule_Ingress_prefixListAndSelf (33.20s)
=== CONT  TestAccVPCSecurityGroupRule_prefixListEmptyString
--- PASS: TestAccVPCSecurityGroupRule_prefixListEmptyString (0.96s)
=== CONT  TestAccVPCSecurityGroupRule_issue5310
--- PASS: TestAccVPCSecurityGroup_egressMode (53.69s)
=== CONT  TestAccVPCSecurityGroupRule_Ingress_ipv4AndIPv6
--- PASS: TestAccVPCSecurityGroupRule_issue5310 (20.02s)
=== CONT  TestAccVPCSecurityGroupRule_selfSource
--- PASS: TestAccVPCSecurityGroupRule_Ingress_ipv4AndIPv6 (25.24s)
=== CONT  TestAccVPCSecurityGroupRule_race
--- PASS: TestAccVPCSecurityGroupRule_selfSource (26.10s)
=== CONT  TestAccVPCSecurityGroupRule_PartialMatching_source
--- PASS: TestAccVPCSecurityGroupRule_PartialMatching_source (28.67s)
=== CONT  TestAccVPCSecurityGroupRule_Ingress_peeredVPC
    acctest.go:644: skipping test because at least one environment variable of [AWS_ALTERNATE_PROFILE AWS_ALTERNATE_ACCESS_KEY_ID] must be set. Usage: credentials for running acceptance testing in alternate AWS account.
--- SKIP: TestAccVPCSecurityGroupRule_Ingress_peeredVPC (0.00s)
=== CONT  TestAccVPCSecurityGroupRule_prefixListEgress
--- PASS: TestAccVPCSecurityGroupRule_prefixListEgress (35.67s)
=== CONT  TestAccVPCSecurityGroup_sourceSecurityGroup
--- PASS: TestAccVPCSecurityGroup_sourceSecurityGroup (27.59s)
=== CONT  TestAccVPCSecurityGroupRule_PartialMatching_basic
--- PASS: TestAccVPCSecurityGroupRule_PartialMatching_basic (33.56s)
=== CONT  TestAccVPCSecurityGroupRule_Ingress_multiplePrefixLists
--- PASS: TestAccVPCSecurityGroupRule_Ingress_multiplePrefixLists (31.13s)
=== CONT  TestAccVPCSecurityGroupRule_expectInvalidCIDR
--- PASS: TestAccVPCSecurityGroupRule_expectInvalidCIDR (1.35s)
=== CONT  TestAccVPCSecurityGroupRule_DescriptionAllPorts_nonZeroPorts
--- PASS: TestAccVPCSecurityGroupRule_race (177.33s)
=== CONT  TestAccVPCSecurityGroupRule_Description_allPorts
--- PASS: TestAccVPCSecurityGroupRule_DescriptionAllPorts_nonZeroPorts (33.55s)
=== CONT  TestAccVPCSecurityGroup_ipRangeAndSecurityGroupWithSameRules
--- PASS: TestAccVPCSecurityGroupRule_Description_allPorts (32.37s)
=== CONT  TestAccVPCSecurityGroupRule_multiDescription
--- PASS: TestAccVPCSecurityGroup_ipRangeAndSecurityGroupWithSameRules (29.52s)
=== CONT  TestAccVPCSecurityGroupRule_MultipleRuleSearching_allProtocolCrash
--- PASS: TestAccVPCSecurityGroupRule_MultipleRuleSearching_allProtocolCrash (26.82s)
=== CONT  TestAccVPCSecurityGroupRule_EgressDescription_updates
--- PASS: TestAccVPCSecurityGroupRule_multiDescription (70.66s)
=== CONT  TestAccVPCSecurityGroupRule_Ingress_vpc
--- PASS: TestAccVPCSecurityGroupRule_EgressDescription_updates (33.08s)
=== CONT  TestAccVPCSecurityGroupRule_Ingress_multipleIPv6
--- PASS: TestAccVPCSecurityGroupRule_Ingress_vpc (22.07s)
=== CONT  TestAccVPCSecurityGroupRule_IngressDescription_updates
--- PASS: TestAccVPCSecurityGroupRule_Ingress_multipleIPv6 (26.61s)
=== CONT  TestAccVPCSecurityGroup_allowAll
--- PASS: TestAccVPCSecurityGroupRule_IngressDescription_updates (34.84s)
=== CONT  TestAccVPCSecurityGroupRule_IngressSourceWithAccount_id
--- PASS: TestAccVPCSecurityGroup_allowAll (27.86s)
=== CONT  TestAccVPCSecurityGroup_tags
--- PASS: TestAccVPCSecurityGroupRule_IngressSourceWithAccount_id (23.26s)
=== CONT  TestAccVPCSecurityGroupDataSource_basic
--- PASS: TestAccVPCSecurityGroupDataSource_basic (25.46s)
=== CONT  TestAccVPCDefaultSecurityGroup_empty
--- PASS: TestAccVPCSecurityGroup_tags (58.69s)
--- PASS: TestAccVPCDefaultSecurityGroup_empty (22.84s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	2332.892s
```

File: internal/service/ec2/vpc_security_group_test.go [hunk 1]
```diff
@@ -2057,8 +1965,38 @@ func TestAccVPCSecurityGroup_failWithDiffMismatch(t *testing.T) {
...
+		},
+	})
+}
+
+func TestAccVPCSecurityGroup_RuleLimit_exceededAppend(t *testing.T) {
+	quotaMutex.Lock()
+	if ruleLimit == 0 {
+		testAccSecurityGroup_ruleLimit(t)
+	}
+	quotaMutex.Unlock()
```
Comment (ewbankkit) [inline internal/service/ec2/vpc_security_group_test.go:1999]: I think these should be `defer quotaMutex.Unlock()` as in non-acceptance test mode `resource.(Parallel)Test` calls `t.Skip()` which ends up exiting the goroutine via [`runtime.Goexit`](https://pkg.go.dev/runtime#Goexit).
