### PR TITLE
d/aws_iam_session_context: New data source

### LINKED ISSUE #19958: Error: Some AWS operations do not support assumed roles
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS services have operations that require a principal (e.g., an IAM user, role, or group). Sometimes these operations fail if an assumed-role ARN is passed in. Ideally, what you want is to grant/convey/designate the IAM source role so that the STS assumed role will have the benefit of the change, and the operation will succeed.

For example, in the Lake Formation service, you cannot make an assumed role a data lake administrator. If you try to, you receive this error:

```
InvalidInputException: Unsupported principal identifier:arn:aws:sts::123456789012:assumed-role/role_name/session-identifier. Arns identifying principals with temporary credentials are not supported.
```

However, if you pass in the source IAM role (`arn:aws:iam::123456789012:role/role_name`), the operation will succeed. The role will become an administrator and the person using the assumed role will have the benefit of the change as well.

Another example is in Service Catalog. There you may get this type of similar error:

```
InvalidParametersException: Invalid parameter principalArn, assumed-role is not a recognized IAM identity type
```

However, in the same vein, if you pass in the source IAM role, the operation will succeed.

A solution is to create a new data source call `aws_iam_session_context` to find the IAM source role of an STS assumed role. This data source should allow passing through IAM roles and users so that it can be used whether the role is STS or IAM and then everyone can use the same config.

### Affected Data Source

* aws_iam_session_context (new)

### Potential Terraform Configuration

```terraform
data "aws_caller_identity" "current" {}

data "aws_iam_session_context" "example" {
  arn = data.aws_called_identity.current.arn
}
```

### References

* #19572

### PR DESCRIPTION
**Pull request by YakDriver**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #19958

Special thanks to @dpowley for helping storyboard a solution!

Output from acceptance/unit testing (`us-west-2`):

```
--- PASS: TestAssumedRoleRoleSessionName (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/not_an_ARN (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/regular_role_ARN (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/assumed_role_ARN (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/'assumed-role'_part_of_ARN_resource (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/user_ARN (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/assumed_role_from_AWS_example (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/multiple_slashes_in_resource (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/not_an_sts_ARN (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/role_with_path (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/wrong_service (0.00s)
--- PASS: TestAccAWSDataSourceIAMSessionContext_notAssumedRoleUser (13.05s)
--- PASS: TestAccAWSDataSourceIAMSessionContext_notAssumedRoleWithPath (16.37s)
--- PASS: TestAccAWSDataSourceIAMSessionContext_notAssumedRole (16.47s)
--- PASS: TestAccAWSDataSourceIAMSessionContext_basic (16.48s)
--- PASS: TestAccAWSDataSourceIAMSessionContext_withPath (17.07s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	13.257s
```

Output from acceptance/unit testing (GovCloud):

```
--- PASS: TestAssumedRoleRoleSessionName (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/not_an_ARN (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/regular_role_ARN (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/assumed_role_ARN (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/'assumed-role'_part_of_ARN_resource (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/user_ARN (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/assumed_role_from_AWS_example (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/multiple_slashes_in_resource (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/not_an_sts_ARN (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/role_with_path (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/wrong_service (0.00s)
--- PASS: TestAccAWSDataSourceIAMSessionContext_notAssumedRoleUser (13.05s)
--- PASS: TestAccAWSDataSourceIAMSessionContext_notAssumedRole (19.06s)
--- PASS: TestAccAWSDataSourceIAMSessionContext_notAssumedRoleWithPath (19.07s)
--- PASS: TestAccAWSDataSourceIAMSessionContext_withPath (20.06s)
--- PASS: TestAccAWSDataSourceIAMSessionContext_basic (20.07s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	23.041s
```

### CODE REVIEW

File: aws/data_source_aws_caller_identity.go [hunk 1]
```diff
@@ -48,6 +56,38 @@ func dataSourceAwsCallerIdentityRead(d *schema.ResourceData, meta interface{}) e
...
+			return result
+		}
+
+		if parsedARN.Service != "sts" {
+			// not an assumed role
+			return result
+		}
+
+		re := regexp.MustCompile(`^assumed-role/`)
+		parsedARN.Resource = re.ReplaceAllString(parsedARN.Resource, "role/")
```
Comment (dpowley) [inline aws/data_source_aws_caller_identity.go:82]: This will return the incorrect sourceArn for roles with paths. The sts assumed-role ARN doesn't include the path of the role. For instance, if you have IAM role ARN `arn:aws:iam::{accountId}:role/{path}/{roleName}` and you assume that role , the assumed-role ARN will be `arn:aws:sts::{accountId}:assumed-role/{roleName}/{sessionName}`. To derive the sourceARN, you would need to call getRole after parsing the role name from the sts ARN. The problem is then, the caller identity data source will then require the `iam:GetRole` permission, which could theoretically break workflows.

Comment (YakDriver) [reply aws/data_source_aws_caller_identity.go:82]: 😞 absolutely right

File: aws/internal/service/iam/finder/finder.go [hunk 2]
```diff
@@ -109,3 +111,22 @@ func Policies(conn *iam.IAM, arn, name, pathPrefix string) ([]*iam.Policy, error
 
 	return results, err
 }
+
+// RoleARNByName returns a role's ARN given the role name
+func RoleARNByName(conn *iam.IAM, name string) (*iam.Role, error) {
```
Comment (DrFaust92) [inline aws/internal/service/iam/finder/finder.go:116]: Maybe rename to `RoleByName`? can be reused in other places as well.

Comment (YakDriver) [reply aws/internal/service/iam/finder/finder.go]: Cool, i renamed it

Comment (YakDriver) [reply aws/internal/service/iam/finder/finder.go]: I thought about adding retry to the finder. In the end I decided to not since we usually leave that for a waiter.

File: aws/data_source_aws_iam_assumed_role_source.go [hunk 3]
```diff
@@ -0,0 +1,140 @@
...
+
+	roleName := ""
+	sessionName := ""
+	var err error
+
+	if roleName, sessionName = roleNameSessionFromARN(arn); roleName == "" {
+		d.Set("source_arn", arn)
+		d.Set("session_name", "")
+		d.Set("role_name", "")
+		d.Set("role_path", "")
```
Comment (dpowley) [inline aws/data_source_aws_iam_assumed_role_source.go:62]: I don't think returning `role_path` is necessary. Seems like an arbitrary field to choose to return from GetRole output. Maybe we could leave it off and if folks want more role context for this datasource we can always add it later?

File: aws/data_source_aws_iam_assumed_role_source.go [hunk 4]
```diff
@@ -0,0 +1,140 @@
...
+	d.SetId(arn)
+
+	roleName := ""
+	sessionName := ""
+	var err error
+
+	if roleName, sessionName = roleNameSessionFromARN(arn); roleName == "" {
+		d.Set("source_arn", arn)
+		d.Set("session_name", "")
+		d.Set("role_name", "")
```
Comment (dpowley) [inline aws/data_source_aws_iam_assumed_role_source.go:61]: The field name structure for `source_arn` and `role_name` seems inconsistent. Could we name them both with `source`? Or we could even return `arn`, `role_arn`, `role_name` and `session_name`

File: aws/data_source_aws_iam_assumed_role_source.go [hunk 5]
```diff
@@ -0,0 +1,140 @@
...
+)
+
+func dataSourceAwsIAMAssumedRoleSource() *schema.Resource {
+	return &schema.Resource{
+		Read: dataSourceAwsIAMAssumedRoleSourceRead,
+
+		Schema: map[string]*schema.Schema{
+			"arn": {
+				Type:     schema.TypeString,
+				Required: true,
```
Comment (DrFaust92) [inline aws/data_source_aws_iam_assumed_role_source.go:25]: Validate?

File: aws/data_source_aws_iam_assumed_role_source.go [hunk 6]
```diff
@@ -0,0 +1,140 @@
...
+	if err != nil {
+		return "", ""
+	}
+
+	parts := strings.Split(parsedARN.Resource, "/")
+
+	reAssume := regexp.MustCompile(`^assumed-role/.{1,}/.{2,}`)
+	reRole := regexp.MustCompile(`^role/.{1,}`)
+
+	if reAssume.MatchString(parsedARN.Resource) && parsedARN.Service != "sts" {
```
Comment (DrFaust92) [inline aws/data_source_aws_iam_assumed_role_source.go:119]: Nit, IIRC there are enums for the service names? (sts and iam)

**Review by DrFaust92 — APPROVED** [review]
Some minor comments, otherwise LGTM

File: aws/data_source_aws_iam_assumed_role_source.go [hunk 7]
```diff
@@ -0,0 +1,140 @@
...
+		return "", ""
+	}
+
+	if reRole.MatchString(parsedARN.Resource) && parsedARN.Service != "iam" {
```
Comment (dpowley) [inline aws/data_source_aws_iam_assumed_role_source.go:123]: My take on this is we should spit IAM role ARNs out just like we would any non-sts assumed-role ARN. If they want metadata on a role, they should use the `aws_iam_role` data source.

File: aws/data_source_aws_iam_assumed_role_source.go (hunk 6 above)
Comment (YakDriver) [reply aws/data_source_aws_iam_assumed_role_source.go:119]: Can't use the sts enum but can do the iam. Avoiding import of multiple services.

Comment (YakDriver) [reply aws/data_source_aws_iam_assumed_role_source.go:119]: Also, dependency for just an enum is not worth it. Go principle: little copying is better than a little dependency.

File: aws/internal/service/iam/finder/finder.go [hunk 8]
```diff
@@ -109,3 +111,22 @@ func Policies(conn *iam.IAM, arn, name, pathPrefix string) ([]*iam.Policy, error
 
 	return results, err
 }
+
+// RoleByName returns a role's ARN given the role name
+func RoleByName(conn *iam.IAM, name string) (*iam.Role, error) {
```
[the remark this answers is not in the document]
Comment (YakDriver) [reply aws/internal/service/iam/finder/finder.go:116]: Yes, love it

File: aws/data_source_aws_iam_assumed_role_source.go [hunk 9]
```diff
@@ -0,0 +1,140 @@
...
+	d.Set("role_name", roleName)
+	d.Set("source_arn", role.Arn)
+	d.Set("role_path", role.Path)
+
+	return nil
+}
+
+// roleNameSessionFromARN returns the role and session names in an ARN if any.
+// Otherwise, it returns empty strings.
+func roleNameSessionFromARN(rawARN string) (string, string) {
```
[the remark this answers is not in the document]
Comment (YakDriver) [reply aws/data_source_aws_iam_assumed_role_source.go:107]: Yes, the problem is that good Go says we should return an error if we don't plan on dealing with it, which we don't.

File: aws/data_source_aws_iam_assumed_role_source.go (hunk 3 above)
Comment (YakDriver) [reply aws/data_source_aws_iam_assumed_role_source.go:62]: Removed.

File: aws/data_source_aws_iam_assumed_role_source.go (hunk 4 above)
Comment (YakDriver) [reply aws/data_source_aws_iam_assumed_role_source.go:61]: the challenge here is if you're using an IAM user, you should still be able to get out a passed through user ARN from `source_arn`.

File: aws/data_source_aws_iam_assumed_role_source.go (hunk 7 above)
Comment (YakDriver) [reply aws/data_source_aws_iam_assumed_role_source.go]: Since we have the role name, I figure I'd also verify IAM role - no cost.

File: aws/data_source_aws_iam_assumed_role_source.go (hunk 4 above)
Comment (dpowley) [reply aws/data_source_aws_iam_assumed_role_source.go]: Yeah I see what you are saying. Don't love it, but can't think of a better way to do it.

File: aws/data_source_aws_iam_assumed_role_source.go (hunk 7 above)
Comment (dpowley) [reply aws/data_source_aws_iam_assumed_role_source.go]: Its not costly, but I think it muddies the water a little on what this data source does. Its easiest to say if you pass in an assumed-role arn we'll give you back all of the metadata and if not you only get sourceArn. Once you add in a case for IAM role, I think the use case isn't quite as clear.

Comment (YakDriver) [reply aws/data_source_aws_iam_assumed_role_source.go]: Yeah, I can see that.

File: .changelog/19957.txt [hunk 10]
```diff
@@ -0,0 +1,3 @@
+```release-note:new-data-source
+aws_iam_assumed_role_source
```
Comment (ewbankkit) [inline .changelog/19957.txt:2]:
```suggestion
aws_iam_session_context
```

File: aws/data_source_aws_iam_assumed_role_source.go (hunk 4 above)
Comment (YakDriver) [reply aws/data_source_aws_iam_assumed_role_source.go]: `issuer_arn`?

File: aws/data_source_aws_iam_assumed_role_source.go (hunk 5 above)
Comment (YakDriver) [reply aws/data_source_aws_iam_assumed_role_source.go]: Added

File: aws/data_source_aws_iam_session_context.go [hunk 11]
```diff
@@ -0,0 +1,135 @@
...
+			"arn": {
+				Type:         schema.TypeString,
+				Required:     true,
+				ValidateFunc: validateArn,
+			},
+			"role_name": {
+				Type:     schema.TypeString,
+				Computed: true,
+			},
+			"source_arn": {
```
Comment (ewbankkit) [inline aws/data_source_aws_iam_session_context.go:32]: Swap with `session_name` for alphabetic ordering?

Comment (YakDriver) [reply aws/data_source_aws_iam_session_context.go]: it's now called `issuer_name` and should be in the correct order

**Comment by YakDriver** [comment]
Tests after many refactors:

GovCloud:
```
--- PASS: TestAccAWSDataSourceIAMSessionContext_notAssumedRoleUser (13.07s)
--- PASS: TestAccAWSDataSourceIAMSessionContext_notAssumedRole (17.41s)
--- PASS: TestAccAWSDataSourceIAMSessionContext_notAssumedRoleWithPath (17.42s)
--- PASS: TestAccAWSDataSourceIAMSessionContext_basic (19.85s)
--- PASS: TestAccAWSDataSourceIAMSessionContext_withPath (19.85s)
--- PASS: TestAssumedRoleRoleSessionName (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/not_an_ARN (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/regular_role_ARN (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/assumed_role_ARN (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/'assumed-role'_part_of_ARN_resource (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/user_ARN (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/assumed_role_from_AWS_example (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/multiple_slashes_in_resource (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/not_an_sts_ARN (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/role_with_path (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/wrong_service (0.00s)
```

`us-west-2`:
```
--- PASS: TestAccAWSDataSourceIAMSessionContext_notAssumedRoleUser (8.84s)
--- PASS: TestAccAWSDataSourceIAMSessionContext_notAssumedRole (11.30s)
--- PASS: TestAccAWSDataSourceIAMSessionContext_notAssumedRoleWithPath (11.30s)
--- PASS: TestAccAWSDataSourceIAMSessionContext_basic (11.50s)
--- PASS: TestAccAWSDataSourceIAMSessionContext_withPath (11.65s)
--- PASS: TestAssumedRoleRoleSessionName (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/not_an_ARN (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/regular_role_ARN (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/assumed_role_ARN (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/'assumed-role'_part_of_ARN_resource (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/user_ARN (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/assumed_role_from_AWS_example (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/multiple_slashes_in_resource (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/not_an_sts_ARN (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/role_with_path (0.00s)
    --- PASS: TestAssumedRoleRoleSessionName/wrong_service (0.00s)
```

File: aws/data_source_aws_iam_assumed_role_source.go (hunk 7 above)
Comment (YakDriver) [reply aws/data_source_aws_iam_assumed_role_source.go]: Water un muddied

File: website/docs/d/iam_session_context.markdown [hunk 12]
```diff
@@ -0,0 +1,50 @@
...
+
+### Find the Terraform Runner's Source Role
+
+Combined with `aws_caller_identity`, you can get the current user's source IAM role ARN (`issuer_arn`) if you're using an assumed role. If you're not using an assumed role, the caller's (e.g., an IAM user's) ARN will simply be passed through. In environments where both IAM users and individuals using assumed roles need to apply the same configurations, this data source enables seamless use.
+
+```terraform
+data "aws_caller_identity" "current" {}
+
+data "aws_iam_session_context" "example" {
+  arn = data.aws_called_identity.current.arn
```
Comment (ewbankkit) [inline website/docs/d/iam_session_context.markdown:33]: Typo.

```suggestion
  arn = data.aws_caller_identity.current.arn
```

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

##### Commercial

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSDataSourceIAMSessionContext_'        
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSDataSourceIAMSessionContext_ -timeout 180m
=== RUN   TestAccAWSDataSourceIAMSessionContext_basic
=== PAUSE TestAccAWSDataSourceIAMSessionContext_basic
=== RUN   TestAccAWSDataSourceIAMSessionContext_withPath
=== PAUSE TestAccAWSDataSourceIAMSessionContext_withPath
=== RUN   TestAccAWSDataSourceIAMSessionContext_notAssumedRole
=== PAUSE TestAccAWSDataSourceIAMSessionContext_notAssumedRole
=== RUN   TestAccAWSDataSourceIAMSessionContext_notAssumedRoleWithPath
=== PAUSE TestAccAWSDataSourceIAMSessionContext_notAssumedRoleWithPath
=== RUN   TestAccAWSDataSourceIAMSessionContext_notAssumedRoleUser
=== PAUSE TestAccAWSDataSourceIAMSessionContext_notAssumedRoleUser
=== CONT  TestAccAWSDataSourceIAMSessionContext_basic
=== CONT  TestAccAWSDataSourceIAMSessionContext_notAssumedRoleWithPath
=== CONT  TestAccAWSDataSourceIAMSessionContext_notAssumedRole
=== CONT  TestAccAWSDataSourceIAMSessionContext_withPath
=== CONT  TestAccAWSDataSourceIAMSessionContext_notAssumedRoleUser
--- PASS: TestAccAWSDataSourceIAMSessionContext_notAssumedRoleUser (14.35s)
--- PASS: TestAccAWSDataSourceIAMSessionContext_notAssumedRoleWithPath (16.05s)
--- PASS: TestAccAWSDataSourceIAMSessionContext_notAssumedRole (17.17s)
--- PASS: TestAccAWSDataSourceIAMSessionContext_basic (17.21s)
--- PASS: TestAccAWSDataSourceIAMSessionContext_withPath (17.32s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	21.124s
```

##### GovCloud

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSDataSourceIAMSessionContext_'  
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSDataSourceIAMSessionContext_ -timeout 180m
=== RUN   TestAccAWSDataSourceIAMSessionContext_basic
=== PAUSE TestAccAWSDataSourceIAMSessionContext_basic
=== RUN   TestAccAWSDataSourceIAMSessionContext_withPath
=== PAUSE TestAccAWSDataSourceIAMSessionContext_withPath
=== RUN   TestAccAWSDataSourceIAMSessionContext_notAssumedRole
=== PAUSE TestAccAWSDataSourceIAMSessionContext_notAssumedRole
=== RUN   TestAccAWSDataSourceIAMSessionContext_notAssumedRoleWithPath
=== PAUSE TestAccAWSDataSourceIAMSessionContext_notAssumedRoleWithPath
=== RUN   TestAccAWSDataSourceIAMSessionContext_notAssumedRoleUser
=== PAUSE TestAccAWSDataSourceIAMSessionContext_notAssumedRoleUser
=== CONT  TestAccAWSDataSourceIAMSessionContext_basic
=== CONT  TestAccAWSDataSourceIAMSessionContext_notAssumedRoleWithPath
=== CONT  TestAccAWSDataSourceIAMSessionContext_notAssumedRoleUser
=== CONT  TestAccAWSDataSourceIAMSessionContext_notAssumedRole
=== CONT  TestAccAWSDataSourceIAMSessionContext_withPath
--- PASS: TestAccAWSDataSourceIAMSessionContext_notAssumedRoleUser (18.53s)
--- PASS: TestAccAWSDataSourceIAMSessionContext_notAssumedRole (23.04s)
--- PASS: TestAccAWSDataSourceIAMSessionContext_notAssumedRoleWithPath (23.36s)
--- PASS: TestAccAWSDataSourceIAMSessionContext_basic (23.51s)
--- PASS: TestAccAWSDataSourceIAMSessionContext_withPath (23.69s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	28.284s
```

**Comment by ewbankkit** [comment]
Verified that one of our nightly CI tests that fails with an assumed role passes using

```hcl
data "aws_caller_identity" "current" {}

data "aws_iam_session_context" "current" {
  arn = data.aws_caller_identity.current.arn
}
```


```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSVpcEndpointServiceAllowedPrincipal_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSVpcEndpointServiceAllowedPrincipal_ -timeout 180m
=== RUN   TestAccAWSVpcEndpointServiceAllowedPrincipal_basic
=== PAUSE TestAccAWSVpcEndpointServiceAllowedPrincipal_basic
=== CONT  TestAccAWSVpcEndpointServiceAllowedPrincipal_basic
    resource_aws_vpc_endpoint_service_allowed_principal_test.go:19: Step 1/1 error: Error running apply: exit status 1
        2021/06/28 14:59:22 [DEBUG] Using modified User-Agent: Terraform/0.12.31 HashiCorp-terraform-exec/0.13.3
        
        Error: Error creating VPC Endpoint Service allowed principal: InvalidPrincipal: Invalid Principal: 'arn:aws:sts::123456789012:assumed-role/terraform_team1_dev-developer/abc@example.com'
        	status code: 400, request id: e1a5d963-8952-41dd-a2dd-aa120a0ee9d2
        
          on terraform_plugin_test.tf line 63, in resource "aws_vpc_endpoint_service_allowed_principal" "test":
          63: resource "aws_vpc_endpoint_service_allowed_principal" "test" {
        
        
--- FAIL: TestAccAWSVpcEndpointServiceAllowedPrincipal_basic (258.09s)
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	261.617s
FAIL
make: *** [testacc] Error 1
```

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSVpcEndpointServiceAllowedPrincipal_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSVpcEndpointServiceAllowedPrincipal_ -timeout 180m
=== RUN   TestAccAWSVpcEndpointServiceAllowedPrincipal_basic
=== PAUSE TestAccAWSVpcEndpointServiceAllowedPrincipal_basic
=== CONT  TestAccAWSVpcEndpointServiceAllowedPrincipal_basic
--- PASS: TestAccAWSVpcEndpointServiceAllowedPrincipal_basic (227.45s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	230.947s
```
