### PR TITLE
resource/aws_instance: Add `tags` parameter to `root_block_device`, `ebs_block_device` blocks (#12225)

### LINKED ISSUE #729: aws_instance.volume_tags gets confused when > 1 volume attached
_This issue was originally opened by @FransUrbo as hashicorp/terraform#14107. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

It seems the new `volume_tags` (thanx btw!) gets confused when there's more than one volume attached to an instance.

### Terraform Version
0.9.4

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_instance

### Terraform Configuration Files
```hcl
resource "aws_instance" "instance" {
  root_block_device {
    volume_type               = "standard"
    volume_size               = 8
  }

  volume_tags {
    Name                      = "my-instance-root"
  }
}

resource "aws_ebs_volume" "instance" {
  tags {
    Name                      = "my-instance-db"
  }
}

resource "aws_volume_attachment" "instance" {
  instance_id                 = "${aws_instance.instance.id}"
  volume_id                   = "${aws_ebs_volume.instance.id}"
  device_name                 = "/dev/sdb"
}
```

### Expected Behavior
Nothing.

### Actual Behavior
Every other time it modified the `aws_ebs_volume` tags and every other on the `aws_instance`.

### Steps to Reproduce
1. `terraform apply`

### LINKED ISSUE #770: aws_instance volume_tags conflict with aws_ebs_volume tags for attached volumes in a module
_This issue was originally opened by @kojiromike as hashicorp/terraform#14462. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version
0.9.5

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_instance
- aws_ebs_volume
- aws_volume_attachment

### Terraform Configuration Files
1. A file in a non-root module:

```hcl
resource "aws_instance" "test" {
  ami               = "ami-20328b40"
  availability_zone = "us-west-2a"
  instance_type     = "t2.micro"
  subnet_id         = "subnet-850585e2"
  key_name          = "michaels_id_rsa"

  tags {
    Name = "test-instance"
  }

  volume_tags {
    Name = "test-instance"
  }
}

variable "vol_id" {}

resource "aws_volume_attachment" "test" {
  device_name = "/dev/xvdf"
  instance_id = "${aws_instance.test.id}"
  volume_id   = "${var.vol_id}"
}
```

2. A root module referencing that file:
```
provider aws {
  region = "us-west-2"
}

resource "aws_ebs_volume" "test" {
  availability_zone = "us-west-2a"
  size              = "1"
  type              = "gp2"

  tags {
    Name = "test-vol"
  }
}

module "test" {
  source = "../../modules/bug"
  vol_id = "${aws_ebs_volume.test.id}"
}
```

### Expected Behavior
The tag for `aws_ebs_volume.test` should consistently be "Name=>vol" according to the `tags` specified in that resource.

### Actual Behavior
The "Name" tag switches back and forth between the value supplied by the `aws_ebs_volume` and the `aws_instance.volume_tags`.

### Steps to Reproduce
After each subsequent `terraform plan/apply`, then I do `aws --region us-west-2 ec2 describe-volumes --volume-ids "$volid" | jq -c '.Volumes[].Tags'` using the volume id grabbed from the first run:

Run 1: `[{"Value":"test-vol","Key":"Name"}]`
Run 2: `[{"Value":"test-instance","Key":"Name"}]`

### Important Factoids
This is so similar to terraform-providers/terraform-provider-aws#729 I almost requested that be reopened, but when I tried to reproduce it in a very simple case without a non-root module, I couldn't. But when I put some components in a module, the problem was evident.

### LINKED ISSUE #884: volume_tags on instance (sometimes) clobbers attached EBS volume tags
_This issue was originally opened by @gavD as hashicorp/terraform#15302. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version

`0.9.8`

### Description

I use `volume_tags` on an EC2 instance to set my boot volume's tags. However, for my mounted volumes, I want slightly different tags (I use `MakeSnapshot: True` so a custom tool makes a snapshots ONLY of the mounted volume)

### Expected Behavior

MakeSnapshot: True is set on the mounted volume

### Actual Behavior

Terraform SOMETIMES does what I want and SOMETIMES stripes the MakeSnapshot tag. Here's the plan output:

```
~ module.basic2.aws_instance.database.0
    volume_tags.%:            "10" => "9"
    volume_tags.MakeSnapshot: "True" => ""
```

### Steps to Reproduce

Here's an example terraform config with the irrelevant parts stripped out.

```
resource "aws_instance" "database" {

   # ...various config here...

  root_block_device {
    volume_type = "gp2"
  }

  tags {
    Name           =  "myinstance"
  }

  # I only want these on the boot volume
  volume_tags {
    Name           = "myinstance-bootVolume"
  }
}

resource "aws_ebs_volume" "database" {

  # ... various config here...

  type              = "gp2"

  tags {
    Name           = "myinstance-dataVolume"
    MakeSnapshot   = "True"
  }
}

resource "aws_volume_attachment" "database" {
  # ... various config here ...
}
```

then run `terraform plan`

### Important Factoids
- Running in EC2 VPCs
- Sometimes it will strip the tag from the data, sometimes it will not

### References
- GH-14019

### LINKED ISSUE #5080: Alternating tags in volume
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.11.7
+ provider.aws v1.23.0
+ provider.template v1.0.0
```

### Affected Resource(s)

* aws_instance
* aws_ebs_volume
* aws_volume_attachment

### Debug Output
- First apply we get:
```volume_tags.Name: "suse12 volume tags" => "suse12-data-ndj"```
- Second apply we get:
```volume_tags.Name: "suse12-data-ndj" => "suse12 volume tags"```

Here is a longer output
```
PS C:\Users\helde\Documents\GitHub\hs-scripts\TerraForm\suse> terraform apply
aws_ebs_volume.data-ndj: Refreshing state... (ID: vol-0e4ee5ad2c9a3629e)
data.aws_ami.suse12: Refreshing state...
aws_instance.suse12: Refreshing state... (ID: i-0140a00017d5c96dc)
aws_volume_attachment.data-ndj: Refreshing state... (ID: vai-2788403704)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ aws_ebs_volume.data-ndj
      tags.Name: "suse12 volume tags" => "suse12-data-ndj"


Plan: 0 to add, 1 to change, 0 to destroy.
...

PS C:\Users\helde\Documents\GitHub\hs-scripts\TerraForm\suse> terraform apply
aws_ebs_volume.data-ndj: Refreshing state... (ID: vol-0e4ee5ad2c9a3629e)
data.aws_ami.suse12: Refreshing state...
aws_instance.suse12: Refreshing state... (ID: i-0140a00017d5c96dc)
aws_volume_attachment.data-ndj: Refreshing state... (ID: vai-2788403704)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ aws_instance.suse12
      volume_tags.Name: "suse12-data-ndj" => "suse12 volume tags"


Plan: 0 to add, 1 to change, 0 to destroy.
...
```

### Expected Behavior
The Volume tag set at `aws_ebs_volume` should not be overwritten by those on `volume_tags`

### Actual Behavior
On every apply Tags are alternating 

### Steps to Reproduce

terraform apply this:
https://github.com/heldersepu/hs-scripts/blob/master/TerraForm/suse/ec2.tf

### LINKED ISSUE #5609: Terraform volume tags changes on alternate run if defined in both aws_instance and aws_ebs_volume resources
_This issue was originally opened by @saveshnshetty as hashicorp/terraform#18713. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

Hi team,
I've defined volume tags in aws_instance resource and  aws_ebs_volume resource since I need to add tags to root volume also. But when I ran "terraform apply" second time. Ebs volumes tags got replaced with aws instance volume tags. On third run it got replaced with original ebs volume tags .
This tags changes alternatively . Can you please look into it .

syntax : 
resource "aws_instance" "app" {
	count                       = "1"
	ami                         = "${lookup(var.ami,var.region)}"
	ebs_optimized               = "${var.ebs_optimized}"
	instance_type               = "${var.instance_type_app}"
	monitoring                  = "${var.monitoring}"
	key_name                    = "${var.key_name}"
	user_data                   = "${data.template_file.userdata-app.*.rendered[count.index]}"
    network_interface {
       network_interface_id = "${element(aws_network_interface.network-interface-app.*.id, count.index)}"
       device_index = 0
    }
		tags {
			Name                  = "$app-${count.index + 1}"
			Type                  = "app"
			Env                   = "${var.env}"
            Customer_id           = "${var.customer_id}"
		}

		root_block_device {
			volume_type           = "${var.root_volume_type}"
			volume_size           = "${var.root_volume_size}"
			delete_on_termination = "${var.root_delete_on_termination}"
		}

		volume_tags {
			Name                  = "${var.env}-s4hana-app-${count.index + 1}"
			Type                  = "root-volume"
			Env                   = "${var.env}"
            Customer_id           = "${var.customer_id}"
		}
}

resource "aws_ebs_volume" "ebs-app" {
    count                   = "${var.app_count}"
    availability_zone       = "****"
    size                    = "${var.ebs_volume_size[0]}"
    type                    = "${var.ebs_volume_type[0]}"
    tags {
      Name                  = "app-tmp"
      Type                  = "ebs-volume"
      Env                   = "${var.env}"
      Customer_id           = "${var.customer_id}"
    }
}

### LINKED ISSUE #5878: Overwrite tags to an EBS attached to an EC2 instance when volume_tags is specified
_This issue was originally opened by @notuscloud as hashicorp/terraform#18860. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version
```
Terraform v0.11.7
+ provider.aws v1.30.0
```

### Terraform Configuration Files

I use `https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/blob/v1.9.0/main.tf` which rely on the `volume_tags` directive.

### Debug Output
 
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ module.db.aws_instance.this_t2
      volume_tags.%:         "5" => "4"
      volume_tags.Env:       "MyEnv" => "MyEnv"
      volume_tags.Name:      "company-stack-db-ec2" => "company-stack-db-ec2"
      volume_tags.Selector:  "company-stack-db-data" => ""
      volume_tags.Stack:     "stack" => "stack"
      volume_tags.Terraform: "true" => "true"
```

### Expected Behavior

The tag `volume_tags.Selector` belongs to an EBS provisioned by terraform beforehand, by an another team with its own separate set of files. The volume is then attached to an EC2 instance thanks to an `aws_volume_attachment`. 

When applying modifications to the instance, it should not update the tags of the attached EBS, only the tags of the volumes created directly by the `aws_instance` resource.

### Actual Behavior

Terraform changes the tags of every attached disk, even those not created when you spawned the instance.

### Steps to Reproduce

1. Create an EBS with terraform
2. Create an EC2 instance with the `volume_tags` directive.
3. Attach the previously created EBS to the EC2 instance
4. Update the volume_tags value then `terraform apply`

### LINKED ISSUE #12225: r/aws_instance: volume_tags works incorrectly with aws_volume_attachment resources
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
$ terraform -v
Terraform v0.12.20
+ provider.aws v2.51.0
```

### Affected Resource(s)

* aws_instance

### Terraform Configuration Files

```hcl
variable az {
  default = "us-east-1a"
}

variable region {
  default = "us-east-1"
}

variable subnet {
  default = "subnet-XXXXXXXX"
}

variable ami {
  default = "ami-046842448f9e74e7d"
}

provider "aws" {
  region = var.region
}

resource "aws_instance" "tst" {
  ami                         = var.ami
  instance_type               = "t2.micro"
  associate_public_ip_address = false
  subnet_id                   = var.subnet

  tags = {
    "Name"        = "tfbug-instance"
    "Environment" = "dev"
    "instance"    = "yes"
  }

  volume_tags = {
    "Name"        = "tfbug-root"
    "Environment" = "dev"
    "root"        = "yes"
  }
}

resource "aws_volume_attachment" "tst" {
  device_name = "/dev/sdf"
  volume_id   = aws_ebs_volume.tst.id
  instance_id = aws_instance.tst.id
}

resource "aws_ebs_volume" "tst" {
  availability_zone = var.az
  size              = 1
  type              = "gp2"

  tags = {
    "Name"        = "tfbug-data"
    "Environment" = "dev"
    "data"        = "yes"
  }
}
```

### Expected Behavior
After first `terraform apply`: 
root EBS device should have tags:
```
  volume_tags = {
    "Name"        = "tfbug-root"
    "Environment" = "dev"
    "root"        = "yes"
  }
```

attached EBS device tags:
```
  tags = {
    "Name"        = "tfbug-data"
    "Environment" = "dev"
    "data"        = "yes"
  }
```
Subsequent `terraform plan` shouldn't show any changes. 

### Actual Behavior
After first apply volume tags are correct, but subsequent `terraform apply/plan` shows changes:
```
# aws_instance.tst will be updated in-place
~ resource "aws_instance" "tst" {
      ami                          = "ami-046842448f9e74e7d"
....
      tags                         = {
          "Environment" = "dev"
          "Name"        = "tfbug-instance"
          "instance"    = "yes"
      }
      tenancy                      = "default"
    ~ volume_tags                  = {
          "Environment" = "dev"
          "Name"        = "tfbug-root"
        - "data"        = "yes" -> null
          "root"        = "yes"
      }

....

      ebs_block_device {
          delete_on_termination = false
          device_name           = "/dev/sdf"
          encrypted             = false
          iops                  = 100
          volume_id             = "vol-XXXXXXXXXXXXX"
          volume_size           = 1
          volume_type           = "gp2"
      }

      root_block_device {
          delete_on_termination = true
          encrypted             = false
          iops                  = 100
          volume_id             = "vol-YYYYYYYYYYYYYY"
          volume_size           = 8
          volume_type           = "gp2"
      }
  }

Plan: 0 to add, 1 to change, 0 to destroy.
```
Note that attached EBS Volume comes up in `aws_instance` resource state.

### Steps to Reproduce
1. `terraform apply`
2. `terraform plan`

### LINKED ISSUE #17074: Tags are removed from EBS volumes
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.4
+ provider registry.terraform.io/hashicorp/aws v3.23.0

### Affected Resource(s)

* aws_ebs_volume
* aws_volume_attachment
* aws_instance

### Terraform Configuration Files

```hcl
resource "aws_instance" "web" {
  ami               = "ami-089668cd321f3cf82"
  instance_type     = "t3.micro"
  availability_zone = "us-west-2a"

  lifecycle {
    ignore_changes = [
      root_block_device,
    ]
  }
}

resource "aws_ebs_volume" "example1" {
  availability_zone = "us-west-2a"

  tags = {
    Name = "example1"
  }
}

resource "aws_volume_attachment" "example1" {
  device_name = "/dev/sdh"
  volume_id   = aws_ebs_volume.example1.id
  instance_id = aws_instance.web.id
}
```

### Expected Behavior

The first apply and subsequent applies result in an EBS volume with a "Name" tag set to "example1".

### Actual Behavior

The first apply creates the volume with the correct tag, but subsequent applies alternatively remove and recreate the tag.

### Steps to Reproduce

1.  `terraform apply`.  The volume will be created correctly with the "Name" tag set to "example1".
2. `terraform apply` again.  The "Name" tag will be removed from the volume.
3. `terraform apply` again.  The "Name" tag will be added to the volume.
4. `terraform apply` again.  The "Name" tag will be removed from the volume.
5. `terraform apply` again.  The "Name" tag will be added to the volume.

### Important Factoids

Applies that remove the tag from the volume have the following plan.  This is unexpected, because the instance resource does not specify `volume_tags`:

```
Terraform will perform the following actions:

  # aws_instance.web will be updated in-place
  ~ resource "aws_instance" "web" {
        id                           = "i-06ccbb7893d13d8cf"
        tags                         = {}
      ~ volume_tags                  = {
          - "Name" = "example1" -> null
        }
        # (26 unchanged attributes hidden)

        # (5 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

Removing `root_block_device` from the ignored changes on `aws_instance` will prevent volume tags from being removed.  However, I'm seeing other examples in my Terraform environment of tags being removed from volumes which do not ignore changes to `root_block_device`.  This was just the first example that I could reproduce simply.

### PR DESCRIPTION
**Pull request by klebediev**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #12225, closes #17074, closes #5878, closes #5609, closes #5080, closes #770, closes #729, closes #884, closes #12225, closes #9156, closes #12226
Similar PR #12226 #9156

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
 - resource/aws_instance: Add `tags` parameter to `root_block_device`, `ebs_block_device` blocks. 
```

Output from acceptance testing:
```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSInstance_.*olumeTags'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSInstance_.*olumeTags -timeout 120m
=== RUN   TestAccAWSInstance_volumeTags
=== PAUSE TestAccAWSInstance_volumeTags
=== RUN   TestAccAWSInstance_rootVolumeTags
=== PAUSE TestAccAWSInstance_rootVolumeTags
=== RUN   TestAccAWSInstance_volumeTagsComputed
=== PAUSE TestAccAWSInstance_volumeTagsComputed
=== RUN   TestAccAWSInstance_rootVolumeTagsEbsAttached
=== PAUSE TestAccAWSInstance_rootVolumeTagsEbsAttached
=== CONT  TestAccAWSInstance_volumeTags
=== CONT  TestAccAWSInstance_volumeTagsComputed
=== CONT  TestAccAWSInstance_rootVolumeTagsEbsAttached
=== CONT  TestAccAWSInstance_rootVolumeTags
--- PASS: TestAccAWSInstance_volumeTagsComputed (173.91s)
--- PASS: TestAccAWSInstance_rootVolumeTagsEbsAttached (219.93s)
--- PASS: TestAccAWSInstance_rootVolumeTags (279.90s)
--- PASS: TestAccAWSInstance_volumeTags (289.16s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	291.061s
```

### CODE REVIEW

**Comment by klebediev** [comment]
```
./aws/resource_aws_instance_test.go:3959
time="2020-10-04 09:55:05" level=error msg="block 35 @ ./aws/resource_aws_instance_test.go:4052 failed to process with: failed to parse hcl: ./aws/resource_aws_instance_test.go:34,3-4: Invalid argument name; Argument names must not be quoted."
time="2020-10-04 09:55:05" level=error msg="block 36 @ ./aws/resource_aws_instance_test.go:4094 failed to process with: failed to parse hcl: ./aws/resource_aws_instance_test.go:34,3-4: Invalid argument name; Argument names must not be quoted."
```
an issue with `terrafmt` fork/branch used in CI/CD pipeline.
It doesn't properly processes `%s` in parameter names despite of `-fmtcompat` option specified.

"main" version of `terrafmt` works fine:
```bash
$ go get github.com/katbyte/terrafmt
....
$ terrafmt diff --check --fmtcompat aws/resource_aws_instance_test.go
$
```

File: aws/resource_aws_instance.go [hunk 1]
```diff
@@ -717,6 +719,14 @@ func resourceAwsInstanceCreate(d *schema.ResourceData, meta interface{}) error {
 		})
 	}
 
+	if _, ok := d.GetOk("root_volume_tags"); ok {
+		if rootVolumeId := getRootVolumeId(instance); rootVolumeId != "" {
+			if err := keyvaluetags.Ec2CreateTags(conn, rootVolumeId, d.Get("root_volume_tags").(map[string]interface{})); err != nil {
+				log.Printf("[ERR] Error creating root_volume_tags (%s): %s", rootVolumeId, err)
```
Comment (klebediev) [inline aws/resource_aws_instance.go:725]: not sure how to handle this error

**Comment by YakDriver** [comment]
@klebediev I apologize if I was unclear. Please review https://github.com/terraform-providers/terraform-provider-aws/issues/12225#issuecomment-702939295.

Rather than `root_volume_tags`, the `ebs_block_device` and `root_block_device` blocks should have tags. The schema would look something like this:

```go
			"ebs_block_device": {
				Type:     schema.TypeSet,
				Optional: true,
				Computed: true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						// other existing code...

						"snapshot_id": {
							Type:     schema.TypeString,
							Optional: true,
							Computed: true,
							ForceNew: true,
						},

						"tags": tagsSchema(),

						"volume_size": {
							Type:     schema.TypeInt,
							Optional: true,
							Computed: true,
							ForceNew: true,
						},

						// other existing code...
					},
				},
				Set: func(v interface{}) int {
					var buf bytes.Buffer
					m := v.(map[string]interface{})
					buf.WriteString(fmt.Sprintf("%s-", m["device_name"].(string)))
					buf.WriteString(fmt.Sprintf("%s-", m["snapshot_id"].(string)))
					return hashcode.String(buf.String())
				},
			},

			// "ephemeral_block_device"... can these be tagged? may need tags here too

			"root_block_device": {
				Type:     schema.TypeList,
				Optional: true,
				Computed: true,
				MaxItems: 1,
				Elem: &schema.Resource{
					// "You can only modify the volume size, volume type, and Delete on
					// Termination flag on the block device mapping entry for the root
					// device volume." - bit.ly/ec2bdmap
					Schema: map[string]*schema.Schema{
						// other existing code...
						"iops": {
							Type:             schema.TypeInt,
							Optional:         true,
							Computed:         true,
							DiffSuppressFunc: iopsDiffSuppressFunc,
						},

						"tags": tagsSchema(),

						"volume_size": {
							Type:     schema.TypeInt,
							Optional: true,
							Computed: true,
						},
					},
				},
			},
```

Hopefully, this example makes it more clear! Let me know if you have questions.

**Review by YakDriver — CHANGES_REQUESTED** [review]
Instead of `root_volume_tags`, please add `tags` within the `ebs_block_device` and `root_block_device` blocks.

**Comment by klebediev** [comment]
ohh.. my fault, you were clear, but for some reason I was reading wrong comment (right above that you referred to)
okay, I'll be able to start working on this in several days

**Comment by YakDriver** [comment]
@klebediev Thanks for your work on this! We look forward to your update. If anything changes on your end with your schedule, let us know!

**Comment by klebediev** [comment]
```
$ TF_ACC=1 go test ./aws -v -count 1 -parallel 8 -run="TestAccAWSInstance_.*olumeTags" -timeout 120m
=== RUN   TestAccAWSInstance_volumeTags
=== PAUSE TestAccAWSInstance_volumeTags
=== RUN   TestAccAWSInstance_volumeTagsWithAttachedVolume
=== PAUSE TestAccAWSInstance_volumeTagsWithAttachedVolume
=== RUN   TestAccAWSInstance_blockDeviceVolumeTags
=== PAUSE TestAccAWSInstance_blockDeviceVolumeTags
=== CONT  TestAccAWSInstance_volumeTags
=== CONT  TestAccAWSInstance_blockDeviceVolumeTags
=== CONT  TestAccAWSInstance_volumeTagsWithAttachedVolume
--- PASS: TestAccAWSInstance_volumeTagsWithAttachedVolume (195.39s)
--- PASS: TestAccAWSInstance_blockDeviceVolumeTags (219.62s)
--- PASS: TestAccAWSInstance_volumeTags (296.43s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	299.135s
```

**Comment by klebediev** [comment]
Can't say I like how it's implemented (it's a bit tricky to deal with 2 or more parameters controlling the same functionality), but at least it works in all cases except importing when `volume_tags` set: in this case `terraform apply` is required after `terraform import`.
So far it's the best behavior I was able to achieve. 
Kind of micro-breaking change I had to introduce: `volume_tags` switched to `Computed: false`

@YakDriver might you take a quick look at this and advise if this could be implemented better

**Comment by klebediev** [comment]
@YakDriver any feedback?

**Comment by YakDriver** [comment]
@klebediev Thanks for these fixes! My first impression is that I like this. I'll dive in deeper and see if I can see any places to improve.

File: aws/resource_aws_instance_test.go [hunk 2]
```diff
@@ -3943,6 +3990,112 @@ resource "aws_instance" "test" {
...
+  instance_type = "t2.medium"
+
+  root_block_device {
+    volume_type = "gp2"
+  }
+
+  ebs_block_device {
+    device_name = "/dev/sdb"
+    volume_size = 1
+    tags = {
```
Comment (YakDriver) [inline aws/resource_aws_instance_test.go:4007]: Nit:
```suggestion

    tags = {
```

File: aws/resource_aws_instance_test.go [hunk 3]
```diff
@@ -3943,6 +3990,112 @@ resource "aws_instance" "test" {
...
+func testAccCheckInstanceConfigBlockDeviceCreateVolumeTags() string {
+	return composeConfig(testAccLatestAmazonLinuxHvmEbsAmiConfig(), fmt.Sprintf(`
+resource "aws_instance" "test" {
+  ami = data.aws_ami.amzn-ami-minimal-hvm-ebs.id
+
+  instance_type = "t2.medium"
+
+  root_block_device {
+    volume_type = "gp2"
+    tags = {
```
Comment (YakDriver) [inline aws/resource_aws_instance_test.go:4035]:
```suggestion

    tags = {
```

File: aws/resource_aws_instance_test.go [hunk 4]
```diff
@@ -3943,6 +3990,112 @@ resource "aws_instance" "test" {
...
+      Name    = "terraform-test-root"
+      Purpose = "test"
+    }
+  }
+
+  ebs_block_device {
+    device_name = "/dev/sdb"
+    volume_size = 1
+    tags = {
```
Comment (YakDriver) [inline aws/resource_aws_instance_test.go:4044]:
```suggestion

    tags = {
```

File: aws/resource_aws_instance_test.go [hunk 5]
```diff
@@ -3943,6 +3990,112 @@ resource "aws_instance" "test" {
...
+func testAccCheckInstanceConfigBlockDeviceUpdateVolumeTags() string {
+	return composeConfig(testAccLatestAmazonLinuxHvmEbsAmiConfig(), fmt.Sprintf(`
+resource "aws_instance" "test" {
+  ami = data.aws_ami.amzn-ami-minimal-hvm-ebs.id
+
+  instance_type = "t2.medium"
+
+  root_block_device {
+    volume_type = "gp2"
+    tags = {
```
Comment (YakDriver) [inline aws/resource_aws_instance_test.go:4071]:
```suggestion

    tags = {
```

File: aws/resource_aws_instance_test.go [hunk 6]
```diff
@@ -3943,6 +3990,112 @@ resource "aws_instance" "test" {
...
+      Name = "terraform-test-root-new"
+      Env  = "dev"
+    }
+  }
+
+  ebs_block_device {
+    device_name = "/dev/sdb"
+    volume_size = 1
+    tags = {
```
Comment (YakDriver) [inline aws/resource_aws_instance_test.go:4080]:
```suggestion

    tags = {
```

File: website/docs/r/instance.html.markdown [hunk 7]
```diff
@@ -97,7 +97,7 @@ instances. See [Shutdown Behavior](https://docs.aws.amazon.com/AWSEC2/latest/Use
 * `ipv6_address_count`- (Optional) A number of IPv6 addresses to associate with the primary network interface. Amazon EC2 chooses the IPv6 addresses from the range of your subnet.
 * `ipv6_addresses` - (Optional) Specify one or more IPv6 addresses from the range of the subnet to associate with the primary network interface
 * `tags` - (Optional) A map of tags to assign to the resource.
-* `volume_tags` - (Optional) A map of tags to assign to the devices created by the instance at launch time.
+* `volume_tags` - (Optional) A map of tags to assign to the devices created by the instance at launch time. Not recommended to use in configurations with EBS volumes attached via `aws_volume_attachment` resource. Use `tags` in `root_block_device` parameter in such cases.
```
Comment (YakDriver) [inline website/docs/r/instance.html.markdown:100]:
```suggestion
* `volume_tags` - (Optional) A map of tags to assign to the devices created by the instance at launch time.

~> **NOTE:** Use `volume_tags` to apply the same tags to an instance's root and EBS devices. Using `volume_tags` is incompatible with other ways of tagging an instance's volumes such as using `tags` in `root_block_device` or `ebs_block_device` blocks, or using `tags` in an `aws_ebs_volume` resource attached via `aws_volume_attachment`. Using `volume_tags` together with other ways of tagging volumes will cause inconsistent behavior and resource cycling.
```

File: aws/resource_aws_instance_test.go [hunk 8]
```diff
@@ -1123,6 +1123,53 @@ func TestAccAWSInstance_volumeTagsComputed(t *testing.T) {
 	})
 }
 
+func TestAccAWSInstance_blockDeviceVolumeTags(t *testing.T) {
```
Comment (YakDriver) [inline aws/resource_aws_instance_test.go:1126]: I think we need another test for this sort of config:

```hcl
resource "aws_instance" "tst" {
  ami                         = var.ami
  instance_type               = "t2.micro"

  root_block_device {
    delete_on_termination = true
    volume_size           = "10"
    volume_type           = "standard"

    tags = {
      Name = %q
    }
  }
}

resource "aws_volume_attachment" "tst" {
  device_name = "/dev/sdf"
  volume_id   = aws_ebs_volume.tst.id
  instance_id = aws_instance.tst.id
}

resource "aws_ebs_volume" "tst" {
  availability_zone = var.az
  size              = 1
  type              = "gp2"

  tags = {
    Name = %q
  }
}
```

**Review by YakDriver — CHANGES_REQUESTED** [review]
@klebediev Thanks for all your work! I like the way this is going. We're getting close to being able to merge.

**Comment by YakDriver** [comment]
@ewbankkit I'd love to get your feedback on the direction we're going with this. The goal is to avoid breaking changes but provide a way forward with tagging.

**Comment by ewbankkit** [comment]
In `resourceAwsInstanceUpdate` the case of an update to `ebs_block_device` tags is not being checked.
Previously all of `ebs_block_device`'s attributes were `ForceNew: true` so any change led to an instance Delete followed by an instance Create but now we can have just a change to the device's `tags` which won't force an instance recreation.
You handled the case of just a change to `root_block_device`'s `tags`.

File: aws/resource_aws_instance_test.go (hunk 8 above)
Comment (klebediev) [reply aws/resource_aws_instance_test.go:1126]: So, we have `TestAccAWSInstance_volumeTagsWithAttachedVolume` for this. 
Should I modify it somehow?

File: aws/resource_aws_instance.go [hunk 9]
```diff
@@ -385,6 +385,8 @@ func resourceAwsInstance() *schema.Resource {
 							ForceNew: true,
 						},
 
+						"tags": tagsSchemaConflictsWith([]string{"volume_tags"}),
```
[the remark this answers is not in the document]
Comment (klebediev) [reply aws/resource_aws_instance.go:388]: done
https://github.com/hashicorp/terraform-provider-aws/blob/f0e973b9084d973b6a2301824349d19936b60707/aws/resource_aws_instance_test.go#L1135-L1142

File: aws/resource_aws_instance.go [hunk 10]
```diff
@@ -1442,6 +1481,14 @@ func resourceAwsInstanceUpdate(d *schema.ResourceData, meta interface{}) error {
 				}
 			}
 		}
+
+		if d.HasChange("root_block_device.0.tags") {
```
[the remark this answers is not in the document]
Comment (klebediev) [reply aws/resource_aws_instance.go:1485]: if I remember correctly changes to tags are be suppressed by
https://github.com/hashicorp/terraform-provider-aws/blob/f0e973b9084d973b6a2301824349d19936b60707/aws/resource_aws_instance.go#L411-L417

**Comment by klebediev** [comment]
> In `resourceAwsInstanceUpdate` the case of an update to `ebs_block_device` tags is not being checked.
> Previously all of `ebs_block_device`'s attributes were `ForceNew: true` so any change led to an instance Delete followed by an instance Create but now we can have just a change to the device's `tags` which won't force an instance recreation.
> You handled the case of just a change to `root_block_device`'s `tags`, so need something similar.

as stated in [docs](https://github.com/hashicorp/terraform-provider-aws/blame/f0e973b9084d973b6a2301824349d19936b60707/website/docs/r/instance.html.markdown#L165) 
> changes to the `ebs_block_device` configuration of _existing_ resources cannot be automatically detected by Terraform

Changing this just for tags might be confusing for users. And recommended way of managing changes for ebs block devices is via `aws_volume_attachment`+`aws_ebs_volume` resources. 
So, are we sure we need this functionality?

**Comment by klebediev** [comment]
expect the question about handling updates for `ebs_block_device` tags PR is ready for review

**Comment by YakDriver** [comment]
@klebediev I will look over your changes and get back to you soon. As for the question of tags on `ebs_block_device`, I need to look into that history more. Ideally, a practitioner could manage both ebs/root tags entirely with `aws_instance` by itself. Is there a technical reason that could not work?

**Comment by klebediev** [comment]
> Is there a technical reason that could not work?
my idea is: "if we handle updates of tags for ebs_block_devices, then we need to handle updates properly for the rest of parameters". 
Talking about technical reasons, as far as I understand this is gonna be a fragile construct taking into account we can use `aws_instance` with `aws_volume_attachment` + `aws_ebs_volume`; my guess that's the reason why updates aren't handled for ebs_block_devices now

**Comment by YakDriver** [comment]
@klebediev You've done a great job on this. Thank you for your help. I'm going to do some work on this and hopefully get this merged. Make sure the "allow edits by maintainers" box is checked. Don't worry as you will still get credit for all your work and commits. Also, let me know before you commit to this branch. Thanks again!

**Review by YakDriver — APPROVED** [review]
```
--- PASS: TestAccAWSInstance_addSecondaryInterface (181.43s)
--- PASS: TestAccAWSInstance_addSecurityGroupNetworkInterface (190.56s)
--- PASS: TestAccAWSInstance_associatePublic_defaultPrivate (89.09s)
--- PASS: TestAccAWSInstance_associatePublic_defaultPublic (224.23s)
--- PASS: TestAccAWSInstance_associatePublic_explicitPrivate (100.27s)
--- PASS: TestAccAWSInstance_associatePublic_explicitPublic (214.61s)
--- PASS: TestAccAWSInstance_associatePublic_overridePrivate (99.56s)
--- PASS: TestAccAWSInstance_associatePublic_overridePublic (109.78s)
--- PASS: TestAccAWSInstance_associatePublicIPAndPrivateIP (114.88s)
--- PASS: TestAccAWSInstance_atLeastOneOtherEbsVolume (164.65s)
--- PASS: TestAccAWSInstance_basic (91.43s)
--- PASS: TestAccAWSInstance_blockDevices (93.37s)
--- PASS: TestAccAWSInstance_blockDeviceTags_ebsAndRoot (127.19s)
--- PASS: TestAccAWSInstance_blockDeviceTags_volumeTags (179.42s)
--- PASS: TestAccAWSInstance_blockDeviceTags_withAttachedVolume (173.43s)
--- PASS: TestAccAWSInstance_changeInstanceType (170.63s)
--- PASS: TestAccAWSInstance_CreditSpecification_Empty_NonBurstable (315.86s)
--- PASS: TestAccAWSInstance_creditSpecification_isNotAppliedToNonBurstable (114.38s)
--- PASS: TestAccAWSInstance_creditSpecification_standardCpuCredits (144.36s)
--- PASS: TestAccAWSInstance_creditSpecification_standardCpuCredits_t2Tot3Taint (454.12s)
--- PASS: TestAccAWSInstance_creditSpecification_unknownCpuCredits_t2 (110.36s)
--- PASS: TestAccAWSInstance_creditSpecification_unknownCpuCredits_t3 (338.63s)
--- PASS: TestAccAWSInstance_creditSpecification_unlimitedCpuCredits (138.75s)
--- PASS: TestAccAWSInstance_creditSpecification_unlimitedCpuCredits_t2Tot3Taint (225.89s)
--- PASS: TestAccAWSInstance_creditSpecification_unspecifiedDefaultsToStandard (122.18s)
--- PASS: TestAccAWSInstance_CreditSpecification_UnspecifiedToEmpty_NonBurstable (136.87s)
--- PASS: TestAccAWSInstance_creditSpecification_updateCpuCredits (176.97s)
--- PASS: TestAccAWSInstance_creditSpecificationT3_standardCpuCredits (122.82s)
--- PASS: TestAccAWSInstance_creditSpecificationT3_unlimitedCpuCredits (144.93s)
--- PASS: TestAccAWSInstance_creditSpecificationT3_unspecifiedDefaultsToUnlimited (324.56s)
--- PASS: TestAccAWSInstance_creditSpecificationT3_updateCpuCredits (136.49s)
--- PASS: TestAccAWSInstance_dedicatedInstance (111.88s)
--- PASS: TestAccAWSInstance_disableApiTermination (147.33s)
--- PASS: TestAccAWSInstance_disappears (68.70s)
--- PASS: TestAccAWSInstance_EbsBlockDevice_InvalidIopsForVolumeType (8.29s)
--- PASS: TestAccAWSInstance_EbsBlockDevice_InvalidThroughputForVolumeType (7.43s)
--- PASS: TestAccAWSInstance_EbsBlockDevice_KmsKeyArn (109.12s)
--- PASS: TestAccAWSInstance_EbsRootDevice_basic (138.20s)
--- PASS: TestAccAWSInstance_EbsRootDevice_ModifyAll (143.95s)
--- PASS: TestAccAWSInstance_EbsRootDevice_ModifyDeleteOnTermination (120.57s)
--- PASS: TestAccAWSInstance_EbsRootDevice_ModifyIOPS_Io1 (172.28s)
--- PASS: TestAccAWSInstance_EbsRootDevice_ModifyIOPS_Io2 (130.38s)
--- PASS: TestAccAWSInstance_EbsRootDevice_ModifySize (132.30s)
--- PASS: TestAccAWSInstance_EbsRootDevice_ModifyThroughput_Gp3 (152.25s)
--- PASS: TestAccAWSInstance_EbsRootDevice_ModifyType (141.72s)
--- PASS: TestAccAWSInstance_EbsRootDevice_MultipleBlockDevices_ModifyDeleteOnTermination (108.78s)
--- PASS: TestAccAWSInstance_EbsRootDevice_MultipleBlockDevices_ModifySize (172.46s)
--- PASS: TestAccAWSInstance_EbsRootDevice_MultipleDynamicEBSBlockDevices (213.17s)
--- PASS: TestAccAWSInstance_Empty_PrivateIP (104.27s)
--- PASS: TestAccAWSInstance_enclaveOptions (216.43s)
--- PASS: TestAccAWSInstance_forceNewAndTagsDrift (162.62s)
--- PASS: TestAccAWSInstance_getPasswordData_falseToTrue (153.69s)
--- PASS: TestAccAWSInstance_getPasswordData_trueToFalse (186.56s)
--- PASS: TestAccAWSInstance_GP2IopsDevice (156.85s)
--- PASS: TestAccAWSInstance_GP2WithIopsValue (7.61s)
--- PASS: TestAccAWSInstance_hibernation (199.64s)
--- PASS: TestAccAWSInstance_inDefaultVpcBySgId (92.83s)
--- PASS: TestAccAWSInstance_inDefaultVpcBySgName (103.11s)
--- PASS: TestAccAWSInstance_inEc2Classic (78.07s)
--- PASS: TestAccAWSInstance_instanceProfileChange (223.90s)
--- PASS: TestAccAWSInstance_ipv6_supportAddressCount (99.40s)
--- PASS: TestAccAWSInstance_ipv6_supportAddressCountWithIpv4 (100.63s)
--- PASS: TestAccAWSInstance_ipv6AddressCountAndSingleAddressCausesError (15.70s)
--- PASS: TestAccAWSInstance_keyPairCheck (101.77s)
--- PASS: TestAccAWSInstance_metadataOptions (178.23s)
--- PASS: TestAccAWSInstance_NetworkInstanceRemovingAllSecurityGroups (142.18s)
--- PASS: TestAccAWSInstance_NetworkInstanceSecurityGroups (119.27s)
--- PASS: TestAccAWSInstance_NetworkInstanceVPCSecurityGroupIDs (119.96s)
--- PASS: TestAccAWSInstance_NewNetworkInterface_EmptyPrivateIPAndSecondaryPrivateIPs (100.96s)
--- PASS: TestAccAWSInstance_NewNetworkInterface_EmptyPrivateIPAndSecondaryPrivateIPsUpdate (165.49s)
--- PASS: TestAccAWSInstance_NewNetworkInterface_PrivateIPAndSecondaryPrivateIPs (319.49s)
--- PASS: TestAccAWSInstance_NewNetworkInterface_PrivateIPAndSecondaryPrivateIPsUpdate (166.89s)
--- PASS: TestAccAWSInstance_NewNetworkInterface_PublicIPAndSecondaryPrivateIPs (423.94s)
--- PASS: TestAccAWSInstance_noAMIEphemeralDevices (62.00s)
--- PASS: TestAccAWSInstance_placementGroup (323.68s)
--- PASS: TestAccAWSInstance_primaryNetworkInterface (154.91s)
--- PASS: TestAccAWSInstance_primaryNetworkInterfaceSourceDestCheck (156.34s)
--- PASS: TestAccAWSInstance_privateIP (209.27s)
--- PASS: TestAccAWSInstance_RootBlockDevice_KmsKeyArn (82.50s)
--- PASS: TestAccAWSInstance_rootBlockDeviceMismatch (83.04s)
--- PASS: TestAccAWSInstance_rootInstanceStore (100.11s)
--- PASS: TestAccAWSInstance_sourceDestCheck (169.24s)
--- PASS: TestAccAWSInstance_tags (111.91s)
--- PASS: TestAccAWSInstance_UserData_EmptyStringToUnspecified (130.54s)
--- PASS: TestAccAWSInstance_UserData_UnspecifiedToEmptyString (133.43s)
--- PASS: TestAccAWSInstance_userDataBase64 (113.53s)
--- PASS: TestAccAWSInstance_withIamInstanceProfile (114.62s)
--- SKIP: TestAccAWSInstance_outpost (1.13s)
```

**Comment by klebediev** [comment]
@YakDriver thank you very much for all the work you've done!

**Comment by YakDriver** [comment]
@klebediev Thank you for your work on this!! 🎉  There were no real changes with the functionality of your fixes - some minor variable name tweaks and test tweaks. I did some gardening with all the attributes/arguments but that was really secondary. Also, I saw what you were discussing with EBS volumes since the instance really isn't handling those. At some point, I think we should either add support to manage EBS volumes properly from `aws_instance` or deprecate it and point people to `aws_ebs_volume`.

**Comment by tdmalone** [comment]
Causes: https://github.com/hashicorp/terraform-provider-aws/issues/17125

**Comment by yermulnik** [comment]
Did this PR cause the removal of `volume_tags` block from `aws_instance` for me with the latest AWS provider version or did I hit something else?
```
  # module.mssql-2.aws_instance.mssql-ec2 will be updated in-place
  ~ resource "aws_instance" "mssql-ec2" {
[…]
      ~ volume_tags                  = {
          - "Application"          = "MSSQL" -> null
 […]
        }
        ebs_block_device {
            delete_on_termination = false
[…]
            tags                  = {}
[…]
        }
[…]
        root_block_device {
[…]
            tags                  = {}
[…]
        }
[…]
}
```
If it was indeed this PR what caused the change why wouldn't it worth to communicate this via CHANGELOG entry?
