### PR TITLE
Avoid recreating aws_ec2_transit_gateway_route_table_association when unnecessary

### LINKED ISSUE #30085: [Bug]: expanding allowed prefixes aws_dx_gateway_association causes downtime
### Terraform Core Version

1.4.1

### AWS Provider Version

4.58

### Affected Resource(s)

* aws_dx_gateway_association
* aws_ec2_transit_gateway_route_table_association

### Expected Behavior

When updaing `aws_dx_gateway_association` with an additional `allowed_prefix`. Gateway association should be update in place with zero impact on other prefixes.

### Actual Behavior

Update to `aws_dx_gateway_association` resource causes `aws_ec2_transit_gateway_route_table_association` replacement which is disabling all the traffix through dx gateway. 

### Relevant Error/Panic Output Snippet

_No response_

### Terraform Configuration Files

  ~ resource "aws_dx_gateway_association" "lnd_eng_1" {
      ~ allowed_prefixes                    = [
          + "10.10.10.0/23",
            # (4 unchanged elements hidden)
        ]
        id                                  = "ga-46208b72-12345"
        # (6 unchanged attributes hidden)
    }

    # aws_ec2_transit_gateway_route_table_association.dx_gateway_lnd_eng_1 must be replaced
-/+ resource "aws_ec2_transit_gateway_route_table_association" "dx_gateway_lnd_eng_1" {
      ~ id                             = "tgw-rtb-3445_tgw-attach-1234" -> (known after apply)
      ~ resource_id                    = "46208b72-f184-12345" -> (known after apply)
      ~ resource_type                  = "direct-connect-gateway" -> (known after apply)
      ~ transit_gateway_attachment_id  = "tgw-attach-123434" # forces replacement -> (known after apply)
        # (1 unchanged attribute hidden)
    }

### Steps to Reproduce

Implement `aws_dx_gateway_association` which is associated with transit gateway `aws_ec2_transit_gateway_route_table_association.dx_gateway`

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by YakDriver**
### Description

Previously, we would ForceNew always on changes to `transit_gateway_attachment_id` regardless. However, there are times when the `transit_gateway_attachment_id` is not known because a dependency changes, such as described in #30085, but the `transit_gateway_attachment_id` won't change. In these cases, the resource should not be ForceNew based on the `transit_gateway_attachment_id` change.

### Relations

Closes #30085

### Output from Acceptance Testing

```console
% make t T='TestAccTransitGateway_serial/RouteTableAssociation_' K=ec2            
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.5 test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccTransitGateway_serial/RouteTableAssociation_'  -timeout 360m -vet=off
2025/02/10 17:03:47 Initializing Terraform AWS Provider...
=== RUN   TestAccTransitGateway_serial
=== PAUSE TestAccTransitGateway_serial
=== CONT  TestAccTransitGateway_serial
=== RUN   TestAccTransitGateway_serial/RouteTableAssociation_basic
=== PAUSE TestAccTransitGateway_serial/RouteTableAssociation_basic
=== RUN   TestAccTransitGateway_serial/RouteTableAssociation_disappears
=== PAUSE TestAccTransitGateway_serial/RouteTableAssociation_disappears
=== RUN   TestAccTransitGateway_serial/RouteTableAssociation_replaceExistingAssociation
=== PAUSE TestAccTransitGateway_serial/RouteTableAssociation_replaceExistingAssociation
=== RUN   TestAccTransitGateway_serial/RouteTableAssociation_notRecreatedDXGateway
=== PAUSE TestAccTransitGateway_serial/RouteTableAssociation_notRecreatedDXGateway
=== RUN   TestAccTransitGateway_serial/DefaultRouteTableAssociation_disappears
=== PAUSE TestAccTransitGateway_serial/DefaultRouteTableAssociation_disappears
=== RUN   TestAccTransitGateway_serial/DefaultRouteTableAssociation_disappearsTransitGateway
=== PAUSE TestAccTransitGateway_serial/DefaultRouteTableAssociation_disappearsTransitGateway
=== RUN   TestAccTransitGateway_serial/DefaultRouteTableAssociation_basic
=== PAUSE TestAccTransitGateway_serial/DefaultRouteTableAssociation_basic
=== CONT  TestAccTransitGateway_serial/RouteTableAssociation_basic
=== CONT  TestAccTransitGateway_serial/DefaultRouteTableAssociation_disappears
=== CONT  TestAccTransitGateway_serial/RouteTableAssociation_replaceExistingAssociation
=== CONT  TestAccTransitGateway_serial/DefaultRouteTableAssociation_disappearsTransitGateway
=== CONT  TestAccTransitGateway_serial/DefaultRouteTableAssociation_basic
=== CONT  TestAccTransitGateway_serial/RouteTableAssociation_notRecreatedDXGateway
=== CONT  TestAccTransitGateway_serial/RouteTableAssociation_disappears
--- PASS: TestAccTransitGateway_serial (0.00s)
    --- PASS: TestAccTransitGateway_serial/DefaultRouteTableAssociation_disappearsTransitGateway (166.90s)
    --- PASS: TestAccTransitGateway_serial/DefaultRouteTableAssociation_basic (375.42s)
    --- PASS: TestAccTransitGateway_serial/RouteTableAssociation_replaceExistingAssociation (377.53s)
    --- PASS: TestAccTransitGateway_serial/RouteTableAssociation_basic (418.27s)
    --- PASS: TestAccTransitGateway_serial/RouteTableAssociation_disappears (447.17s)
    --- PASS: TestAccTransitGateway_serial/DefaultRouteTableAssociation_disappears (554.61s)
    --- PASS: TestAccTransitGateway_serial/RouteTableAssociation_notRecreatedDXGateway (1886.13s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	1890.621s
```

### CODE REVIEW

File: internal/service/ec2/transitgateway_route_table_association_test.go [hunk 1]
```diff
@@ -175,6 +231,9 @@ func testAccCheckTransitGatewayRouteTableAssociationDestroy(ctx context.Context)
 	}
 }
 
+// testAccCheckRouteTableAssociationNotRecreated function, as is typical, cannot work here because
+// the resource ID will be the same, even if the association is recreated.
```
Comment (jar-b) [inline internal/service/ec2/transitgateway_route_table_association_test.go:235]: Could this comment move up into the "not recreated" test case? I wonder if it'd get lost down here for a future reviewer wondering why this typical check is missing.

**Review by jar-b — DISMISSED** [review]
LGTM 🎉 

```console
% make testacc PKG=ec2 TESTS=TestAccTransitGateway_serial/RouteTableAssociation_
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.5 test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccTransitGateway_serial/RouteTableAssociation_'  -timeout 360m -vet=off
2025/02/11 09:52:15 Initializing Terraform AWS Provider...

--- PASS: TestAccTransitGateway_serial (0.00s)
    --- PASS: TestAccTransitGateway_serial/DefaultRouteTableAssociation_basic (199.07s)
    --- PASS: TestAccTransitGateway_serial/DefaultRouteTableAssociation_disappears (200.03s)
    --- PASS: TestAccTransitGateway_serial/DefaultRouteTableAssociation_disappearsTransitGateway (217.32s)
    --- PASS: TestAccTransitGateway_serial/RouteTableAssociation_disappears (435.10s)
    --- PASS: TestAccTransitGateway_serial/RouteTableAssociation_replaceExistingAssociation (616.40s)
    --- PASS: TestAccTransitGateway_serial/RouteTableAssociation_basic (616.44s)
    --- PASS: TestAccTransitGateway_serial/RouteTableAssociation_notRecreatedDXGateway (2321.00s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        2327.872s
```

File: internal/service/ec2/transitgateway_route_table_association_test.go (hunk 1 above)
Comment (YakDriver) [reply internal/service/ec2/transitgateway_route_table_association_test.go]: Good call
