### PR TITLE
Amazon MSK multiple authentication modes and updates to TLS encryption settings

### LINKED ISSUE #20956: Amazon MSK multiple authentication modes and updates to TLS encryption settings
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> Amazon Managed Streaming for Apache Kafka (Amazon MSK) now supports the simultaneous use of multiple authentication modes and updates to encryption-in-transit settings for Amazon MSK clusters.

### New or Affected Resource(s)

* [`aws_msk_cluster`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/msk_cluster)

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2021/09/amazon-msk-multiple-authentication-modes-tls-encryption-settings/)
* [Developer Guide](https://docs.aws.amazon.com/msk/latest/developerguide/msk-update-security.html)

Requires [AWS SDK v1.40.39](https://github.com/aws/aws-sdk-go/releases/tag/v1.40.39):

* #20848

### LINKED ISSUE #22839: SASL client_authentication conflicts with TLS client_authentication
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.1.4
provider registry.terraform.io/hashicorp/aws v3.74.0

### Affected Resource(s)

* aws_msk_cluster

### Terraform Configuration Files

msk.tf

```hcl
resource "aws_vpc" "vpc" {
  cidr_block = "192.168.0.0/22"
}

data "aws_availability_zones" "azs" {
  state = "available"
}

resource "aws_subnet" "subnet_az1" {
  availability_zone = data.aws_availability_zones.azs.names[0]
  cidr_block        = "192.168.0.0/24"
  vpc_id            = aws_vpc.vpc.id
}

resource "aws_subnet" "subnet_az2" {
  availability_zone = data.aws_availability_zones.azs.names[1]
  cidr_block        = "192.168.1.0/24"
  vpc_id            = aws_vpc.vpc.id
}

resource "aws_subnet" "subnet_az3" {
  availability_zone = data.aws_availability_zones.azs.names[2]
  cidr_block        = "192.168.2.0/24"
  vpc_id            = aws_vpc.vpc.id
}

resource "aws_security_group" "sg" {
  vpc_id = aws_vpc.vpc.id
}

resource "aws_kms_key" "kms" {
  description = "example"
}

resource "aws_msk_cluster" "example" {
  cluster_name           = "example"
  kafka_version          = "2.8.1"
  number_of_broker_nodes = 3

  broker_node_group_info {
    instance_type   = "kafka.m5.large"
    ebs_volume_size = 100
    client_subnets = [
      aws_subnet.subnet_az1.id,
      aws_subnet.subnet_az2.id,
      aws_subnet.subnet_az3.id,
    ]
    security_groups = [aws_security_group.sg.id]
  }

  client_authentication {
    sasl {
      iam = true
      scram = true
    }
    tls {
      certificate_authority_arns = [aws_acmpca_certificate_authority.root_ca.arn]
    }
  }

}
```

root-ca.tf

```hcl
resource "aws_acmpca_certificate_authority" "root_ca" {
  certificate_authority_configuration {
    key_algorithm     = "RSA_4096"
    signing_algorithm = "SHA512WITHRSA"

    subject {
      common_name = "Root CA"
      organization = "example"
    }
  }
  type = "ROOT"
}

resource "aws_acmpca_certificate_authority_certificate" "root_ca_cert" {
  certificate_authority_arn = aws_acmpca_certificate_authority.root_ca.arn

  certificate       = aws_acmpca_certificate.root_ca_cert.certificate
  certificate_chain = aws_acmpca_certificate.root_ca_cert.certificate_chain
}

resource "aws_acmpca_certificate" "root_ca_cert" {
  certificate_authority_arn   = aws_acmpca_certificate_authority.root_ca.arn
  certificate_signing_request = aws_acmpca_certificate_authority.root_ca.certificate_signing_request
  signing_algorithm           = "SHA512WITHRSA"

  template_arn = "arn:aws:acm-pca:::template/RootCACertificate/V1"

  validity {
    type  = "YEARS"
    value = 20
  }
}

```

### Debug Output

https://gist.github.com/dassaf1/e2c5a9f542383c66c2839284c772d154

### Expected Behavior

The MSK cluster should be created with both SASL (SCRAM and/or IAM) and TLS authentication enabled (it is supported by AWS MSK).

### Actual Behavior

Error message is presented indicating that there is a conflict between SASL and TLS authentication (see below):
```
"client_authentication.0.sasl": conflicts with client_authentication.0.tls
```

### Steps to Reproduce

1. `terraform apply`

### LINKED ISSUE #23727: Adding SASL and IAM based client_authenticatin to a cluster replaces the cluster instead of updating it
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

 
### Terraform CLI and Terraform AWS Provider Version

hashicorp/aws: version = "~> 4.6.0"

### Affected Resource(s)

- aws_msk_cluster

### Terraform Configuration Files

```hcl
resource "aws_msk_cluster" "msk" {
  cluster_name           = var.cluster_name
  kafka_version          = var.kafka_version
  number_of_broker_nodes = var.number_of_brokers
  enhanced_monitoring    = var.enhanced_monitoring
  configuration_info {
    arn      = aws_msk_configuration.msk_config.arn
    revision = aws_msk_configuration.msk_config.latest_revision
  }

  broker_node_group_info {
    instance_type   = var.instance_size
    ebs_volume_size = var.ebs_size
    client_subnets  = var.az_list
    security_groups = var.sg_list
  }


  dynamic "encryption_info" {
    for_each = var.client_authentication_sasl == false  && var.client_authentication_iam == false ? [1] : []
    content {
      # encryption_at_rest_kms_key_arn = "" # Accept default key
      encryption_in_transit {
        client_broker = "TLS_PLAINTEXT"
        in_cluster    = true
      }
    }
  }
  

  dynamic "encryption_info" {
    for_each = var.client_authentication_sasl == true  ||  var.client_authentication_iam == true ?  [1] : []
    content {
      # encryption_at_rest_kms_key_arn = "" # Accept default key
      encryption_in_transit {
        client_broker = "TLS"
        in_cluster    = true
      }
    }
  }


  logging_info {
    broker_logs {
      cloudwatch_logs {
        enabled   = true
        log_group = aws_cloudwatch_log_group.msk_logs.name
      }
      firehose {
        enabled         = var.enable_firehose_delivery
        delivery_stream = var.firehose_delivery_stream_name
      }
    }
  }

  dynamic "client_authentication" {
    for_each = (var.client_authentication_sasl == true || var.client_authentication_iam == true ) ? [1] : []
    content {
      sasl {
        iam =  var.client_authentication_iam 

        scram = var.client_authentication_sasl
      }
    }
  }

  open_monitoring {
    prometheus {
      jmx_exporter {
        enabled_in_broker = var.enable_jmx_exporter
      }
      node_exporter {
        enabled_in_broker = var.enable_node_exporter
      }
    }
  }



  tags = {
    terraform   = "true"
    environment = var.env
  }

  
}
```

### Expected Behavior

Existing cluster should be modified , with IAM based client authentication

### Actual Behavior

Existing cluster is replaced and destroyed . 

### Steps to reproduce

Created a MSK Cluster without any authentication. 
Tried adding support for SASL and IAM authentication by adding this 

```hcl
  client_authentication {
           sasl {
               iam   = true
               scram = true
            }
        }
```

an attempt to appy the plan says it will replace the MSK cluster. However  using the AWS management console, its does allow enabling SASL , IAM based authentication  on an pre existing unautheticated cluster
  Is there a way to prevent replacement of the cluster while allowing addition of SAL, IAM authntication. Blocked on it and any help is appreciated.
  
  .

### PR DESCRIPTION
**Pull request by james-bjss**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #20956.
Closes #22839.
Closes #23727.

Output from acceptance testing:

```
 make testacc TESTS=TestAccKafkaCluster_basic PKG=kafka
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/kafka/... -v -count 1 -parallel 20 -run='TestAccKafkaCluster_basic' -timeout 180m
=== RUN   TestAccKafkaCluster_basic
=== PAUSE TestAccKafkaCluster_basic
=== CONT  TestAccKafkaCluster_basic
--- PASS: TestAccKafkaCluster_basic (1993.81s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/kafka      1993.866s


make testacc TESTS=TestAccKafkaCluster_ClientAuthenticationSASL_scram PKG=kafka
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/kafka/... -v -count 1 -parallel 20 -run='TestAccKafkaCluster_ClientAuthenticationSASL_scram' -timeout 180m
=== RUN   TestAccKafkaCluster_ClientAuthenticationSASL_scram
=== PAUSE TestAccKafkaCluster_ClientAuthenticationSASL_scram
=== CONT  TestAccKafkaCluster_ClientAuthenticationSASL_scram
--- PASS: TestAccKafkaCluster_ClientAuthenticationSASL_scram (3611.11s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/kafka      3611.202s
```

### CODE REVIEW

File: aws/resource_aws_msk_cluster.go [hunk 1]
```diff
@@ -643,6 +634,40 @@ func resourceAwsMskClusterUpdate(d *schema.ResourceData, meta interface{}) error
...
 	}
 
+	if d.HasChanges("encryption_info", "client_authentication") {
+
+		input := &kafka.UpdateSecurityInput{
+			ClusterArn:     aws.String(d.Id()),
+			CurrentVersion: aws.String(d.Get("current_version").(string)),
+		}
+
+		if d.HasChange("client_authentication") {
```
Comment (james-bjss) [inline aws/resource_aws_msk_cluster.go:644]: These checks are probably not necessary. I attempted to send only the changes applied as whilst the API is idempotent it still takes ~25 for an operation to complete even if not changes are made.

For example if the cluster is provisioned without a `client_authentication` block sasl is implicilty disabled, if we later add the configuration and explicitly set it disabled this will result still result in a cluster update

```hcl
  client_authentication {
    sasl {
      sasl= false
    }
  }
```

File: aws/resource_aws_msk_cluster.go [hunk 2]
```diff
@@ -107,42 +107,35 @@ func resourceAwsMskCluster() *schema.Resource {
...
-				MaxItems: 1,
+				MaxItems: 2,
 				Elem: &schema.Resource{
 					Schema: map[string]*schema.Schema{
 						"sasl": {
 							Type:     schema.TypeList,
 							Optional: true,
-							ForceNew: true,
-							MaxItems: 1,
+							MaxItems: 2,
```
Comment (james-bjss) [inline aws/resource_aws_msk_cluster.go:116]: Should we add a new `unauthenticated` config?

File: aws/resource_aws_msk_cluster.go [hunk 3]
```diff
@@ -105,52 +107,54 @@ func resourceAwsMskCluster() *schema.Resource {
 				},
 			},
 			"client_authentication": {
-				Type:     schema.TypeList,
-				Optional: true,
-				ForceNew: true,
-				MaxItems: 1,
+				Type:             schema.TypeList,
+				Required:         true,
```
Comment (james-bjss) [inline aws/resource_aws_msk_cluster.go:111]: My logic behind making both the `client_authentication` and `unauthenticated` attributes mandatory is to force users to explicitly set the authentication options.

Whilst this field is optional in the API the behaviour when creating a cluster without this set is undefined. 
eg. If we create a cluster without this set the AWS Console UI shows the cluster has all authentication modes disabled and the `describeCluster` endpoint omits the `client_authentication` key completely in its response, despite this the behaviour observed is that it is possible to connect unauthenticated.

If the user were to make an update and include this block without setting any authentication options then the `updateSecurity` call fails saying at least one auth method should be set.

If were to default the `Unauthenticated` option to true there is a danger that a user could inadvertently disable unauthenticated access, likewise the inverse if they have configuration already for `tls` then defaulting this to true could unknowingly enable Unauthenticated access when they re-apply.

If there is a better way or idea I am open to it, we could potentially only send the fields if they are explicitly set, perhaps detecting changes on the individual attributes instead of the whole block?

**Comment by james-bjss** [comment]
` make testacc TESTS=TestAccKafkaCluster_basic PKG=kafka
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/kafka/... -v -count 1 -parallel 20 -run='TestAccKafkaCluster_basic' -timeout 180m
=== RUN   TestAccKafkaCluster_basic
=== PAUSE TestAccKafkaCluster_basic
=== CONT  TestAccKafkaCluster_basic
--- PASS: TestAccKafkaCluster_basic (1993.81s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/kafka      1993.866s


make testacc TESTS=TestAccKafkaCluster_ClientAuthenticationSASL_scram PKG=kafka
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/kafka/... -v -count 1 -parallel 20 -run='TestAccKafkaCluster_ClientAuthenticationSASL_scram' -timeout 180m
=== RUN   TestAccKafkaCluster_ClientAuthenticationSASL_scram
=== PAUSE TestAccKafkaCluster_ClientAuthenticationSASL_scram
=== CONT  TestAccKafkaCluster_ClientAuthenticationSASL_scram
--- PASS: TestAccKafkaCluster_ClientAuthenticationSASL_scram (3611.11s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/kafka      3611.202s`

Screenshot for second test to show the update occuring:
image

**Comment by jplock** [comment]
Is there any update on when this change might be merged?

**Comment by LuisDeHaro** [comment]
+1 - Is there any new info about this change?

File: aws/resource_aws_msk_cluster.go (hunk 3 above)
Comment (ewbankkit) [reply aws/resource_aws_msk_cluster.go]: For backwards compatibility we will have to keep everything as `Optional`.

File: website/docs/r/msk_cluster.html.markdown [hunk 4]
```diff
@@ -187,11 +187,21 @@ The following arguments are supported:
...
+
+### connectivity_info public_access Argument Reference
+
+* `type` - (Optional) Public access type. Valida values: `DISABLED`, `SERVICE_PROVIDED_EIPS`.
 
 ### client_authentication Argument Reference
 
 * `sasl` - (Optional) Configuration block for specifying SASL client authentication. See below.
 * `tls` - (Optional) Configuration block for specifying TLS client authentication. See below.
+* `unauthenticated` - (Optional) Enables unauthenticated access.
```
Comment (james-bjss) [inline website/docs/r/msk_cluster.html.markdown:204]: @ewbankkit Does this default to false? Just a heads up, but prior to this option being introduced clusters would default to it enabled when plaintext options were specified.

The AWS API call in this case does not return the key at all but its implicitly enabled.
I think in later revisions of the API it forces it to be specified if those options are enabled else it reports and error. SOo probably OK?

I was just worried about the cases where it was implicitly enabled but the provider then defaults it to false if the property is absent, which is why i added a validate method. But can see the reasons for removing this as it replcaes logic in the AWS API.

I's been a while, but see this comment:
https://github.com/hashicorp/terraform-provider-aws/issues/20956#issuecomment-929116934

Comment (ewbankkit) [reply website/docs/r/msk_cluster.html.markdown:204]: Actually, we are testing that scenario in the new `TestAccKafkaCluster_ClientAuthenticationTLS_initiallyNoAuthentication` acceptance test where we start with no `client_authentication` and `encryption_in_transit.client_broker = "PLAINTEXT"` and then ensure that we can update in-place to multiple `client_authentication` methods and `encryption_in_transit.client_broker = "TLS"`.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% ACCTEST_TIMEOUT=720m make testacc TESTS=TestAccKafkaCluster PKG=kafka ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/kafka/... -v -count 1 -parallel 3 -run='TestAccKafkaCluster'  -timeout 720m
=== RUN   TestAccKafkaClusterDataSource_basic
=== PAUSE TestAccKafkaClusterDataSource_basic
=== RUN   TestAccKafkaCluster_basic
=== PAUSE TestAccKafkaCluster_basic
=== RUN   TestAccKafkaCluster_BrokerNodeGroupInfo_ebsVolumeSize
=== PAUSE TestAccKafkaCluster_BrokerNodeGroupInfo_ebsVolumeSize
=== RUN   TestAccKafkaCluster_BrokerNodeGroupInfo_instanceType
=== PAUSE TestAccKafkaCluster_BrokerNodeGroupInfo_instanceType
=== RUN   TestAccKafkaCluster_BrokerNodeGroupInfo_publicAccessSaslIam
=== PAUSE TestAccKafkaCluster_BrokerNodeGroupInfo_publicAccessSaslIam
=== RUN   TestAccKafkaCluster_ClientAuthenticationSASL_scram
=== PAUSE TestAccKafkaCluster_ClientAuthenticationSASL_scram
=== RUN   TestAccKafkaCluster_ClientAuthenticationSASL_iam
=== PAUSE TestAccKafkaCluster_ClientAuthenticationSASL_iam
=== RUN   TestAccKafkaCluster_ClientAuthenticationTLS_certificateAuthorityARNs
=== PAUSE TestAccKafkaCluster_ClientAuthenticationTLS_certificateAuthorityARNs
=== RUN   TestAccKafkaCluster_ClientAuthenticationTLS_initiallyNoAuthentication
=== PAUSE TestAccKafkaCluster_ClientAuthenticationTLS_initiallyNoAuthentication
=== RUN   TestAccKafkaCluster_Info_revision
=== PAUSE TestAccKafkaCluster_Info_revision
=== RUN   TestAccKafkaCluster_EncryptionInfo_encryptionAtRestKMSKeyARN
=== PAUSE TestAccKafkaCluster_EncryptionInfo_encryptionAtRestKMSKeyARN
=== RUN   TestAccKafkaCluster_EncryptionInfoEncryptionInTransit_clientBroker
=== PAUSE TestAccKafkaCluster_EncryptionInfoEncryptionInTransit_clientBroker
=== RUN   TestAccKafkaCluster_EncryptionInfoEncryptionInTransit_inCluster
=== PAUSE TestAccKafkaCluster_EncryptionInfoEncryptionInTransit_inCluster
=== RUN   TestAccKafkaCluster_enhancedMonitoring
=== PAUSE TestAccKafkaCluster_enhancedMonitoring
=== RUN   TestAccKafkaCluster_numberOfBrokerNodes
=== PAUSE TestAccKafkaCluster_numberOfBrokerNodes
=== RUN   TestAccKafkaCluster_openMonitoring
=== PAUSE TestAccKafkaCluster_openMonitoring
=== RUN   TestAccKafkaCluster_loggingInfo
=== PAUSE TestAccKafkaCluster_loggingInfo
=== RUN   TestAccKafkaCluster_kafkaVersionUpgrade
=== PAUSE TestAccKafkaCluster_kafkaVersionUpgrade
=== RUN   TestAccKafkaCluster_kafkaVersionDowngrade
=== PAUSE TestAccKafkaCluster_kafkaVersionDowngrade
=== RUN   TestAccKafkaCluster_kafkaVersionUpgradeWithInfo
=== PAUSE TestAccKafkaCluster_kafkaVersionUpgradeWithInfo
=== RUN   TestAccKafkaCluster_tags
=== PAUSE TestAccKafkaCluster_tags
=== CONT  TestAccKafkaClusterDataSource_basic
=== CONT  TestAccKafkaCluster_EncryptionInfoEncryptionInTransit_clientBroker
=== CONT  TestAccKafkaCluster_ClientAuthenticationSASL_iam
--- PASS: TestAccKafkaCluster_EncryptionInfoEncryptionInTransit_clientBroker (1941.08s)
=== CONT  TestAccKafkaCluster_EncryptionInfo_encryptionAtRestKMSKeyARN
--- PASS: TestAccKafkaClusterDataSource_basic (1949.57s)
=== CONT  TestAccKafkaCluster_Info_revision
--- PASS: TestAccKafkaCluster_EncryptionInfo_encryptionAtRestKMSKeyARN (1955.82s)
=== CONT  TestAccKafkaCluster_ClientAuthenticationTLS_initiallyNoAuthentication
--- PASS: TestAccKafkaCluster_ClientAuthenticationSASL_iam (3909.38s)
=== CONT  TestAccKafkaCluster_ClientAuthenticationTLS_certificateAuthorityARNs
--- PASS: TestAccKafkaCluster_Info_revision (2688.38s)
=== CONT  TestAccKafkaCluster_loggingInfo
--- PASS: TestAccKafkaCluster_ClientAuthenticationTLS_certificateAuthorityARNs (2288.52s)
=== CONT  TestAccKafkaCluster_tags
--- PASS: TestAccKafkaCluster_loggingInfo (2266.44s)
=== CONT  TestAccKafkaCluster_kafkaVersionUpgradeWithInfo
--- PASS: TestAccKafkaCluster_ClientAuthenticationTLS_initiallyNoAuthentication (4265.93s)
=== CONT  TestAccKafkaCluster_kafkaVersionDowngrade
--- PASS: TestAccKafkaCluster_tags (2148.92s)
=== CONT  TestAccKafkaCluster_kafkaVersionUpgrade
--- PASS: TestAccKafkaCluster_kafkaVersionDowngrade (4154.47s)
=== CONT  TestAccKafkaCluster_BrokerNodeGroupInfo_instanceType
--- PASS: TestAccKafkaCluster_kafkaVersionUpgradeWithInfo (5748.13s)
=== CONT  TestAccKafkaCluster_ClientAuthenticationSASL_scram
--- PASS: TestAccKafkaCluster_kafkaVersionUpgrade (5813.05s)
=== CONT  TestAccKafkaCluster_BrokerNodeGroupInfo_publicAccessSaslIam
--- PASS: TestAccKafkaCluster_ClientAuthenticationSASL_scram (3384.64s)
=== CONT  TestAccKafkaCluster_BrokerNodeGroupInfo_ebsVolumeSize
--- PASS: TestAccKafkaCluster_BrokerNodeGroupInfo_ebsVolumeSize (2466.04s)
=== CONT  TestAccKafkaCluster_numberOfBrokerNodes
--- PASS: TestAccKafkaCluster_BrokerNodeGroupInfo_instanceType (6307.75s)
=== CONT  TestAccKafkaCluster_openMonitoring
--- PASS: TestAccKafkaCluster_BrokerNodeGroupInfo_publicAccessSaslIam (6018.91s)
=== CONT  TestAccKafkaCluster_basic
--- PASS: TestAccKafkaCluster_openMonitoring (1677.99s)
=== CONT  TestAccKafkaCluster_enhancedMonitoring
--- PASS: TestAccKafkaCluster_numberOfBrokerNodes (2644.50s)
=== CONT  TestAccKafkaCluster_EncryptionInfoEncryptionInTransit_inCluster
--- PASS: TestAccKafkaCluster_basic (1729.06s)
--- PASS: TestAccKafkaCluster_enhancedMonitoring (1727.91s)
--- PASS: TestAccKafkaCluster_EncryptionInfoEncryptionInTransit_inCluster (2028.77s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/kafka	22884.818s
```

**Comment by ewbankkit** [comment]
@james-bjss @nuttmeister Thanks for the contribution :tada: :clap:.
