### PR TITLE
r/aws_codepipeline: support removal of `trigger` arguments

### LINKED ISSUE #39347: [Bug]: No changes detected when adding/removing aws_codepipeline trigger
### Terraform Core Version

1.8.1

### AWS Provider Version

5.66.0

### Affected Resource(s)

aws_codepipeline

### Expected Behavior

Adding or removing the trigger block of an aws_codepipeline resource should result in that trigger being created or removed.

### Actual Behavior

Terraform doesn't detect adding or removing the trigger block of a pipeline, regardless of the state of the DetectChanges property on the source stage.

Changes to options within the trigger are detected, e.g. branch includes list.

It seems like it's not possible to remove the trigger, but this is an option in the AWS console:

image
image

### Terraform Configuration Files

```
resource "aws_codepipeline" "pipeline" {
  name          = "test-pipeline"
  pipeline_type = "V2"


  dynamic "trigger" {
    for_each = var.trigger_on_push ? [1] : []
    content {
      provider_type = "CodeStarSourceConnection"
      git_configuration {
        source_action_name = "GitCheckout"
        push {
          branches {
            includes = [
              var.branch
            ]
          }
        }
      }
    }
  }

  stage {
    name = "Source"

    action {
      name             = "GitCheckout"
      category         = "Source"
      owner            = "AWS"
      provider         = "CodeStarSourceConnection"
      version          = "1"

      configuration = {
        ConnectionArn    = data.aws_codestarconnections_connection.github_codestar_connection.arn
        FullRepositoryId = var.repository
        BranchName       = var.branch
        DetectChanges    = var.trigger_on_push
      }
    }
  }
}
```

### Steps to Reproduce

1. Setup an AWS CodePipeline
2. Add a trigger block with a branch in the push branch includes list
3. Deploy the pipeline
4. Remove the trigger block

### Debug Output

```
No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by jar-b**
### Description

Previously the `trigger` argument was optional and computed, meaning that removal of a configured trigger definition would not result in planned changes as the value would be interpreted as computed only. This change switches the `trigger` argument back to optional only, and adds a computed `trigger_all` block which is used to track both custom trigger configurations provided by the user and default configurations added by AWS for `V2` pipelines. The downside of this approach is that drift between the remote and configured `trigger` definition can no longer be detected. This was deemed an acceptable trade-off in order to ensure trigger removals operate as intended without manual intervention.

### Relations

Closes #39347 

### References

- https://docs.aws.amazon.com/codepipeline/latest/APIReference/API_CreatePipeline.html
- https://docs.aws.amazon.com/codepipeline/latest/APIReference/API_UpdatePipeline.html

### Output from Acceptance Testing

```console
% make testacc PKG=codepipeline TESTS="TestAccCodePipeline_"
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.7 test ./internal/service/codepipeline/... -v -count 1 -parallel 20 -run='TestAccCodePipeline_'  -timeout 360m -vet=off
2025/03/27 11:28:59 Initializing Terraform AWS Provider...

--- PASS: TestAccCodePipeline_disappears (36.97s)
--- PASS: TestAccCodePipeline_withNamespace (37.27s)
--- PASS: TestAccCodePipeline_deployWithServiceRole (42.22s)
--- PASS: TestAccCodePipeline_emptyStageArtifacts (42.87s)
--- PASS: TestAccCodePipeline_MultiRegion_basic (46.63s)
--- PASS: TestAccCodePipeline_trigger (50.36s)
--- PASS: TestAccCodePipeline_manualApprovalTimeoutInMinutes (59.18s)
--- PASS: TestAccCodePipeline_conditions (59.98s)
--- PASS: TestAccCodePipeline_basic (60.17s)
--- PASS: TestAccCodePipeline_MultiRegion_update (64.77s)
--- PASS: TestAccCodePipeline_ecr (71.32s)
--- PASS: TestAccCodePipeline_tags (77.72s)
--- PASS: TestAccCodePipeline_MultiRegion_convertSingleRegion (79.22s)
--- PASS: TestAccCodePipeline_pipelineType (100.41s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/codepipeline       107.207s
```

### CODE REVIEW

File: internal/service/codepipeline/codepipeline.go [hunk 1]
```diff
@@ -400,213 +610,8 @@ func resourcePipeline() *schema.Resource {
...
-							"provider_type": {
-								Type:             schema.TypeString,
-								Required:         true,
-								ValidateDiagFunc: enum.Validate[types.PipelineTriggerProviderType](),
-							},
-						},
-					},
-				},
+				"trigger":         triggerSchema(),
+				"trigger_all":     sdkv2.DataSourcePropertyFromResourceProperty(triggerSchema()),
```
Comment (ewbankkit) [inline internal/service/codepipeline/codepipeline.go:614]: We should probably rename `DataSourcePropertyFromResourceProperty` to capture the fact that it can be used outside of data sources to make al;l attributes _Computed_ only.

Comment (jar-b) [reply internal/service/codepipeline/codepipeline.go:614]: Agreed. I'll open a tech debt issue for follow up.
