### PR TITLE
B account region enable

### LINKED ISSUE #41430: [Bug]: `aws_account_region` errors when attempting to enable a region that it already enabled
### Terraform Core Version

1.10.0

### AWS Provider Version

5.84.0

### Affected Resource(s)

* aws_account_region

### Expected Behavior

When the Terraform configuration wishes to set a region to be enabled, if that region was already enabled, then silently import the enablement and continue.

### Actual Behavior

Got an error: `Unable to switch region status because of its current opt-in status.`

### Relevant Error/Panic Output Snippet

```shell
Error: enabling Account Region (123456789012,eu-south-1): operation error Account: EnableRegion, https response error StatusCode: 400, RequestID: abcdef01-2345-6789-0abc-def012345678, ValidationException: Unable to switch region status because of its current opt-in status.
  with module.bootstrap.aws_account_region.enabled["eu-south-1"],
  on resources-regions.tf line 1, in resource "aws_account_region" "enabled":
   1: resource "aws_account_region" "enabled" {
```

### Terraform Configuration Files

N/A

### Steps to Reproduce

1. (optional) override the resource create timeout to `10s` to force a timeout error and show the problem
2. Terraform provider calls `EnableRegion`: https://github.com/hashicorp/terraform-provider-aws/blob/ddc7bceb2a7ac23982507fe4a6315d7f1d933127/internal/service/account/region.go#L102
3. AWS accepts the API call, and puts the region into the "Enabling..." status
4. Terraform waits for enablement to finish before proceeding: https://github.com/hashicorp/terraform-provider-aws/blob/ddc7bceb2a7ac23982507fe4a6315d7f1d933127/internal/service/account/region.go#L108
5. Something happens and the Terraform process stops before the region enters "Enabled" status
6. Attempt to re-run Terraform
7. `terraform plan` will attempt to create `aws_account_region` again, since it didn't think that the region was successfully "created" in the last run
8. Terraform provider calls `EnableRegion` on a region that has since entered into `Enabled` status
9. get the error. Error persists on subsequent retries without manual intervention.

### Debug Output

N/A

### Panic Output

N/A

### Important Factoids

_No response_

### References

https://docs.aws.amazon.com/accounts/latest/reference/API_EnableRegion.html#API_EnableRegion_RequestBody

The documentation warns:

> This process takes a few minutes for most accounts, but it can take several hours.

Particularly since the default timeout is 60 minutes, if for some reason the region is not enabled/created successfully on the first attempt, then the error will trigger.

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by nam054**
### Description

Currently, when attempting to enable a region that is already in the enabling  or  enabled status, an error occurs. This change will prevent this error by allowing the process to skip the EnableRegion API call. Instead, it would go directly to the waitRegionEnabled status if the region is already enabling or enabled. Essentially, this change modifies the behavior by letting the process continue without error/failing.

### Relations

Closes #41430

### Output from Acceptance Testing

```console
> make testacc TESTARGS="-run=TestAccAccount_serial/Region" PKG=account
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.5 test ./internal/service/account/... -v -count 1 -parallel 20  -run=TestAccAccount_serial/Region -timeout 360m -vet=off
2025/03/06 10:23:09 Initializing Terraform AWS Provider...
=== RUN   TestAccAccount_serial
=== PAUSE TestAccAccount_serial
=== CONT  TestAccAccount_serial
=== RUN   TestAccAccount_serial/Region
=== RUN   TestAccAccount_serial/Region/basic
=== RUN   TestAccAccount_serial/Region/AccountID
    region_test.go:70: skipping test because at least one environment variable of [AWS_ALTERNATE_PROFILE AWS_ALTERNATE_ACCESS_KEY_ID] must be set. Usage: credentials for running acceptance testing in alternate AWS account.
--- PASS: TestAccAccount_serial (413.81s)
    --- PASS: TestAccAccount_serial/Region (413.81s)
        --- PASS: TestAccAccount_serial/Region/basic (413.81s)
        --- SKIP: TestAccAccount_serial/Region/AccountID (0.00s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/account    420.625s

...
```

### CODE REVIEW

File: internal/service/account/region.go [hunk 1]
```diff
@@ -239,3 +244,10 @@ func waitRegionDisabled(ctx context.Context, conn *account.Client, accountID, re
 
 	return nil, err
 }
+
+func requiresStatusChange(status types.RegionOptStatus, enable bool) bool {
+	if enable {
+		return status != types.RegionOptStatusEnabled
```
Comment (jar-b) [inline internal/service/account/region.go:250]: To ensure we also skip when the region is actively being enabled.

```suggestion
		return status != types.RegionOptStatusEnabled && status != types.RegionOptStatusEnabling
```

File: .changelog/41678.txt [hunk 2]
```diff
@@ -0,0 +1,3 @@
+```release-note:note
+resource/aws_account_region: Change the way to handle region enable/disable when already enabled/disabled in state
```
Comment (jar-b) [inline .changelog/41678.txt:2]: We might want to split this into two distinct enhancement items.

1. Prevent errors when the region is an `ENABLING` or `DISABLING` state during creation.
2. Allow adoption of regions in an `ENABLED` or `DISABLED` state without an explicit import operation.

**Review by jar-b — APPROVED** [review]
LGTM 🚀
