### PR TITLE
SuppressEquivalentJsonDiffs on redrive_allow_policy for aws_sqs_queue_redrive_allow_policy

### LINKED ISSUE #40119: [Bug]: Permadiff in `redrive_allow_policy` attribute of `aws_sqs_queue_redrive_allow_policy`
### Terraform Core Version

1.5.7

### AWS Provider Version

5.75.1

### Affected Resource(s)

* `aws_sqs_queue_redrive_allow_policy`

### Expected Behavior

The `aws_sqs_queue_redrive_allow_policy` resource shows no diffs when running `terraform plan` after a successful `terraform apply`

### Actual Behavior

The `redrive_allow_policy` attribute of `aws_sqs_queue_redrive_allow_policy` shows a diff when running `terraform plan` after a successful `terraform apply` if it contains any whitespaces in the json string.

A normalized version of `redrive_allow_policy` is saved to state and compared against the un-normalized one when diff'ing.

### Relevant Error/Panic Output Snippet

_No response_

### Terraform Configuration Files

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
    }
  }
}

provider "aws" {
  region = "eu-central-1"
}

resource "aws_sqs_queue" "demo_dlq" {
  name_prefix = "sqs-redrive-policy-diff-"
}

resource "aws_sqs_queue" "demo_queue" {
  name_prefix = "sqs-redrive-policy-diff-"

  redrive_policy = jsonencode({
    deadLetterTargetArn = aws_sqs_queue.demo_dlq.arn
    maxReceiveCount     = 2
  })
}

resource "aws_sqs_queue_redrive_allow_policy" "example" {
  queue_url = aws_sqs_queue.demo_dlq.id

  redrive_allow_policy = "{\"redrivePermission\": \"byQueue\", \"sourceQueueArns\": [\"${aws_sqs_queue.demo_queue.arn}\"]}"
}

```

### Steps to Reproduce

- `terraform apply`
- `terraform plan` <- observe diff

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by t0yv0**
### Description

redrive_allow_policy field on aws_sqs_queue_redrive_allow_policy is made more robust to ignore non-semantic JSON whitespace changes for purposes of planning. 

### Relations

Closes #40119

### Output from Acceptance Testing

```console
> TF_ACC=1 go test -run TestAccSQSQueueRedriveAllowPolicy_by_queue -test.v
2024/12/17 16:22:20 Initializing Terraform AWS Provider...
=== RUN   TestAccSQSQueueRedriveAllowPolicy_by_queue
=== PAUSE TestAccSQSQueueRedriveAllowPolicy_by_queue
=== CONT  TestAccSQSQueueRedriveAllowPolicy_by_queue
--- PASS: TestAccSQSQueueRedriveAllowPolicy_by_queue (124.55s)
PASS
```

### CODE REVIEW

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccSQSQueueRedriveAllowPolicy_\|TestAccSQSQueueDataSource_' PKG=sqs ACCTEST_PARALLELISM=3
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.3 test ./internal/service/sqs/... -v -count 1 -parallel 3  -run=TestAccSQSQueueRedriveAllowPolicy_\|TestAccSQSQueueDataSource_ -timeout 360m
2024/12/18 14:34:30 Initializing Terraform AWS Provider...
=== RUN   TestAccSQSQueueDataSource_tags
=== PAUSE TestAccSQSQueueDataSource_tags
=== RUN   TestAccSQSQueueDataSource_tags_NullMap
=== PAUSE TestAccSQSQueueDataSource_tags_NullMap
=== RUN   TestAccSQSQueueDataSource_tags_EmptyMap
=== PAUSE TestAccSQSQueueDataSource_tags_EmptyMap
=== RUN   TestAccSQSQueueDataSource_tags_DefaultTags_nonOverlapping
=== PAUSE TestAccSQSQueueDataSource_tags_DefaultTags_nonOverlapping
=== RUN   TestAccSQSQueueDataSource_tags_IgnoreTags_Overlap_DefaultTag
=== PAUSE TestAccSQSQueueDataSource_tags_IgnoreTags_Overlap_DefaultTag
=== RUN   TestAccSQSQueueDataSource_tags_IgnoreTags_Overlap_ResourceTag
=== PAUSE TestAccSQSQueueDataSource_tags_IgnoreTags_Overlap_ResourceTag
=== RUN   TestAccSQSQueueDataSource_basic
=== PAUSE TestAccSQSQueueDataSource_basic
=== RUN   TestAccSQSQueueRedriveAllowPolicy_basic
=== PAUSE TestAccSQSQueueRedriveAllowPolicy_basic
=== RUN   TestAccSQSQueueRedriveAllowPolicy_disappears
=== PAUSE TestAccSQSQueueRedriveAllowPolicy_disappears
=== RUN   TestAccSQSQueueRedriveAllowPolicy_Disappears_queue
=== PAUSE TestAccSQSQueueRedriveAllowPolicy_Disappears_queue
=== RUN   TestAccSQSQueueRedriveAllowPolicy_update
=== PAUSE TestAccSQSQueueRedriveAllowPolicy_update
=== RUN   TestAccSQSQueueRedriveAllowPolicy_byQueue
=== PAUSE TestAccSQSQueueRedriveAllowPolicy_byQueue
=== CONT  TestAccSQSQueueDataSource_tags
=== CONT  TestAccSQSQueueDataSource_basic
=== CONT  TestAccSQSQueueDataSource_tags_DefaultTags_nonOverlapping
--- PASS: TestAccSQSQueueDataSource_tags (41.01s)
=== CONT  TestAccSQSQueueDataSource_tags_IgnoreTags_Overlap_ResourceTag
--- PASS: TestAccSQSQueueDataSource_tags_DefaultTags_nonOverlapping (41.02s)
=== CONT  TestAccSQSQueueDataSource_tags_IgnoreTags_Overlap_DefaultTag
--- PASS: TestAccSQSQueueDataSource_basic (41.42s)
=== CONT  TestAccSQSQueueRedriveAllowPolicy_Disappears_queue
--- PASS: TestAccSQSQueueDataSource_tags_IgnoreTags_Overlap_DefaultTag (39.47s)
=== CONT  TestAccSQSQueueRedriveAllowPolicy_byQueue
--- PASS: TestAccSQSQueueDataSource_tags_IgnoreTags_Overlap_ResourceTag (39.66s)
=== CONT  TestAccSQSQueueRedriveAllowPolicy_update
--- PASS: TestAccSQSQueueRedriveAllowPolicy_Disappears_queue (133.18s)
=== CONT  TestAccSQSQueueRedriveAllowPolicy_disappears
--- PASS: TestAccSQSQueueRedriveAllowPolicy_byQueue (118.37s)
=== CONT  TestAccSQSQueueRedriveAllowPolicy_basic
--- PASS: TestAccSQSQueueRedriveAllowPolicy_update (151.87s)
=== CONT  TestAccSQSQueueDataSource_tags_NullMap
--- PASS: TestAccSQSQueueDataSource_tags_NullMap (39.20s)
=== CONT  TestAccSQSQueueDataSource_tags_EmptyMap
--- PASS: TestAccSQSQueueDataSource_tags_EmptyMap (39.32s)
--- PASS: TestAccSQSQueueRedriveAllowPolicy_basic (125.54s)
--- PASS: TestAccSQSQueueRedriveAllowPolicy_disappears (164.93s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/sqs	344.877s
```

File: internal/service/sqs/queue_data_source.go [hunk 1]
```diff
@@ -68,16 +66,6 @@ func dataSourceQueueRead(ctx context.Context, d *schema.ResourceData, meta inter
 	d.Set(names.AttrARN, attributesOutput)
 	d.Set(names.AttrURL, queueURL)
 
-	if errs.IsUnsupportedOperationInPartitionError(meta.(*conns.AWSClient).Partition(ctx), err) {
```
Comment (t0yv0) [inline internal/service/sqs/queue_data_source.go:71]: Is this needed as part of the change? Thanks.

**Review by jar-b — APPROVED** [review]
LGTM 🚀
