### PR TITLE
r/aws_route53_vpc_association_authorization: retry `InvalidPaginationToken` errors on read

### LINKED ISSUE #40585: [Bug]: aws_route53_vpc_association_authorization InvalidPaginationToken during terraform plan
### Terraform Core Version

1.6.6

### AWS Provider Version

5.66.0,5.67.0,5.68.0,5.69.0,5.70.0,5.71.0,5.72.0,5.73.0,5.74.0,5.75.0,5.76.0,5.77.0,5.78.0,5.79.0,5.80.0,5.81.0

### Affected Resource(s)

* aws_route53_vpc_association_authorization

### Expected Behavior

Terraform plan should succeed and determine whether or not to make changes.

### Actual Behavior

Terraform plan fails with an `InvalidPaginationToken` error on `ListVPCAssociationAuthorizations` when running multiple terraform workspaces concurrently. Using a central network account in a micro account architecture which is why we have multiple workspaces running concurrently with a provider to the central network account.

I believe what is happening, the resource isn't properly retrying and handling a 400 Bad Request, Throttling error.

https://github.com/hashicorp/terraform-provider-aws/blob/c45a7d8e90ea23fdf52fab8a9a692d2754c37d18/internal/service/route53/vpc_association_authorization.go#L189

> All Amazon Route 53 API requests
For the [Amazon Route 53 APIs](https://docs.aws.amazon.com/Route53/latest/APIReference/API_Operations_Amazon_Route_53.html) five requests per second per AWS account. If you submit more than five requests per second, Amazon Route 53 returns an HTTP 400 error (Bad request). The response header also includes a Code element with a value of Throttling and a Message element with a value of Rate exceeded.

### Relevant Error/Panic Output Snippet

```shell
> Error: reading Route53 VPC Association Authorization (<zone_id>:<vpc_id>): operation error Route 53: ListVPCAssociationAuthorizations, https response error StatusCode: 400, RequestID: <request_id>, InvalidPaginationToken: <long_string_here>
```

### Terraform Configuration Files

```hcl
resource "aws_route53_vpc_association_authorization" "this" {
  provider = aws.network-hub

  for_each = local.zone_ids_json
  zone_id  = each.key
  vpc_id    = aws_vpc.this.id
}
```

### Steps to Reproduce

1. Cause a r53 throttling error. simple bash + curl command
2. Run terraform 

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

Using AFT in a micro account architecture. Running many customization workspaces when communicating to a single central network aws account.

Route53 API has a limit of five requests per second.

### References

https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DNSLimitations.html

https://github.com/hashicorp/terraform-provider-aws/blob/c45a7d8e90ea23fdf52fab8a9a692d2754c37d18/internal/service/route53/vpc_association_authorization.go#L189

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by jar-b**
## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the library.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

### Description

Practitioners have reported instances of `InvalidPaginationToken` errors being returned in workspaces where many VPC association authorizations are managed concurrently. This change adds a basic retry to the `ListVPCAssociationAuthoriziations` API call, as this error type may be masking what is truly some other underlying issue. We ask for community help in evaluating this fix as maintainers are limited to a small number of test accounts in which to test concurrent authorizations, from which we have yet to observe the reported errors.

In addition to the retry handling, this change also introduces configurable timeouts for the create, read, and delete operations. Create and delete will have a default timeout of 20 minutes, while read will have a default of 5 minutes.

### Relations

Closes #40585

### Output from Acceptance Testing

```console
% AWS_ALTERNATE_PROFILE=<redacted> AWS_THIRD_PROFILE=<redacted> make testacc PKG=route53 TESTS=TestAccRoute53VPCAssociationAuthorization_
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.10 test ./internal/service/route53/... -v -count 1 -parallel 20 -run='TestAccRoute53VPCAssociationAuthorization_'  -timeout 360m -vet=off
2025/06/10 13:44:42 Initializing Terraform AWS Provider...

--- PASS: TestAccRoute53VPCAssociationAuthorization_disappears (326.72s)
--- PASS: TestAccRoute53VPCAssociationAuthorization_basic (329.87s)
--- PASS: TestAccRoute53VPCAssociationAuthorization_crossRegion (329.92s)
--- PASS: TestAccRoute53VPCAssociationAuthorization_concurrent (329.97s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/route53    335.659s
```

### CODE REVIEW

File: internal/service/route53/vpc_association_authorization.go [hunk 1]
```diff
@@ -97,7 +104,7 @@ func resourceVPCAssociationAuthorizationRead(ctx context.Context, d *schema.Reso
 		return sdkdiag.AppendFromErr(diags, err)
 	}
 
-	vpc, err := findVPCAssociationAuthorizationByTwoPartKey(ctx, conn, zoneID, vpcID)
+	vpc, err := findVPCAssociationAuthorizationByTwoPartKey(ctx, conn, zoneID, vpcID, d.Timeout(schema.TimeoutRead))
```
Comment (ewbankkit) [inline internal/service/route53/vpc_association_authorization.go]: Did you consider putting the retry loop out here rather than deeper in the implementation?

Comment (jar-b) [reply internal/service/route53/vpc_association_authorization.go]: Fair point. My original thinking was to capture the `InvalidPaginationToken` as close to the original API call as possible. 

However, retrying in the read method avoids having to pass timeouts all the way down the finder call stack and makes the retry logic easier to see. I'll make the change.

**Comment by jar-b** [comment]
Acceptance test results after refactoring the placement of the retry logic.

```console
% AWS_ALTERNATE_PROFILE=<redacted> AWS_THIRD_PROFILE=<redacted> make testacc PKG=route53 TESTS=TestAccRoute53VPCAssociationAuthorization_
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.10 test ./internal/service/route53/... -v -count 1 -parallel 20 -run='TestAccRoute53VPCAssociationAuthorization_'  -timeout 360m -vet=off
2025/06/11 13:47:54 Initializing Terraform AWS Provider...

--- PASS: TestAccRoute53VPCAssociationAuthorization_disappears (280.43s)
--- PASS: TestAccRoute53VPCAssociationAuthorization_concurrent (282.60s)
--- PASS: TestAccRoute53VPCAssociationAuthorization_crossRegion (283.22s)
--- PASS: TestAccRoute53VPCAssociationAuthorization_basic (283.64s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/route53    289.427s
```
