### PR TITLE
aws_elasticache_user_group: Skip deleted users during user group update

### LINKED ISSUE #43281: [Bug]: `elasticache_user_group` returns an error when user is deleted
### Terraform and AWS Provider Version

```console
Terraform Version
1.12.2

AWS Provider Version
6.0.0
```

### Affected Resource(s) or Data Source(s)

* `aws_elasticache_user_group`
* `aws_elasticache_user`

### Expected Behavior

User group should be updated with the new user ids without returning an error. This slows down infrastructure deployments where user rotations are frequent and requires retries.

### Actual Behavior

Plan: `-` are removed users and `+` are users to be created and added to group
```
  # aws_elasticache_user_group.default will be updated in-place
  ~ resource "aws_elasticache_user_group" "default" {
        id            = "ug-37ec29e4a63f"
        tags          = {}
      ~ user_ids      = [
          - "user-ug-37ec29e4a63f-1-id",
          - "user-ug-37ec29e4a63f-10-id",
          - "user-ug-37ec29e4a63f-11-id",
          - "user-ug-37ec29e4a63f-12-id",
          - "user-ug-37ec29e4a63f-13-id",
          - "user-ug-37ec29e4a63f-14-id",
          - "user-ug-37ec29e4a63f-15-id",
          - "user-ug-37ec29e4a63f-16-id",
          - "user-ug-37ec29e4a63f-17-id",
          - "user-ug-37ec29e4a63f-18-id",
          - "user-ug-37ec29e4a63f-19-id",
          - "user-ug-37ec29e4a63f-2-id",
          - "user-ug-37ec29e4a63f-20-id",
          - "user-ug-37ec29e4a63f-21-id",
          - "user-ug-37ec29e4a63f-22-id",
          - "user-ug-37ec29e4a63f-23-id",
          - "user-ug-37ec29e4a63f-24-id",
          - "user-ug-37ec29e4a63f-25-id",
          - "user-ug-37ec29e4a63f-26-id",
          - "user-ug-37ec29e4a63f-27-id",
          - "user-ug-37ec29e4a63f-28-id",
          - "user-ug-37ec29e4a63f-29-id",
          - "user-ug-37ec29e4a63f-3-id",
          - "user-ug-37ec29e4a63f-4-id",
          - "user-ug-37ec29e4a63f-5-id",
          - "user-ug-37ec29e4a63f-6-id",
          - "user-ug-37ec29e4a63f-7-id",
          - "user-ug-37ec29e4a63f-8-id",
          - "user-ug-37ec29e4a63f-9-id",
          + "user-ug-37ec29e4a63f-1-id-2",
          + "user-ug-37ec29e4a63f-10-id-2",
          + "user-ug-37ec29e4a63f-11-id-2",
          + "user-ug-37ec29e4a63f-12-id-2",
          + "user-ug-37ec29e4a63f-13-id-2",
          + "user-ug-37ec29e4a63f-14-id-2",
          + "user-ug-37ec29e4a63f-15-id-2",
          + "user-ug-37ec29e4a63f-16-id-2",
          + "user-ug-37ec29e4a63f-17-id-2",
          + "user-ug-37ec29e4a63f-18-id-2",
          + "user-ug-37ec29e4a63f-19-id-2",
          + "user-ug-37ec29e4a63f-2-id-2",
          + "user-ug-37ec29e4a63f-20-id-2",
          + "user-ug-37ec29e4a63f-21-id-2",
          + "user-ug-37ec29e4a63f-22-id-2",
          + "user-ug-37ec29e4a63f-23-id-2",
          + "user-ug-37ec29e4a63f-24-id-2",
          + "user-ug-37ec29e4a63f-25-id-2",
          + "user-ug-37ec29e4a63f-26-id-2",
          + "user-ug-37ec29e4a63f-27-id-2",
          + "user-ug-37ec29e4a63f-28-id-2",
          + "user-ug-37ec29e4a63f-29-id-2",
          + "user-ug-37ec29e4a63f-3-id-2",
          + "user-ug-37ec29e4a63f-4-id-2",
          + "user-ug-37ec29e4a63f-5-id-2",
          + "user-ug-37ec29e4a63f-6-id-2",
          + "user-ug-37ec29e4a63f-7-id-2",
          + "user-ug-37ec29e4a63f-8-id-2",
          + "user-ug-37ec29e4a63f-9-id-2",
            # (1 unchanged element hidden)
        ]
        # (5 unchanged attributes hidden)
    }
```
Apply:
```
╷
│ Error: updating ElastiCache User Group ("ug-37ec29e4a63f"): operation error ElastiCache: ModifyUserGroup, https response error StatusCode: 400, RequestID: 60169049-9fd1-461b-a8a8-ab000e022ddc, InvalidParameterValue: User user-ug-37ec29e4a63f-8-id is not a member of user group ug-37ec29e4a63f.
│ 
│   with aws_elasticache_user_group.default,
│   on main.tf line 64, in resource "aws_elasticache_user_group" "default":
│   64: resource "aws_elasticache_user_group" "default" {
│ 
╵
```

### Relevant Error/Panic Output

```console
╷
│ Error: updating ElastiCache User Group ("ug-37ec29e4a63f"): operation error ElastiCache: ModifyUserGroup, https response error StatusCode: 400, RequestID: 60169049-9fd1-461b-a8a8-ab000e022ddc, InvalidParameterValue: User user-ug-37ec29e4a63f-8-id is not a member of user group ug-37ec29e4a63f.
│ 
│   with aws_elasticache_user_group.default,
│   on main.tf line 64, in resource "aws_elasticache_user_group" "default":
│   64: resource "aws_elasticache_user_group" "default" {
│ 
╵

```
Since the user is already deleted, TF should acknowledge instead of returning error.

### Sample Terraform Configuration

<details>
<summary>Click to expand configuration</summary>

```hcl

```
</details>

### Steps to Reproduce

1. Create large number of users and add it to a user group
2. Rotate users (to replicate, simply change id and name)
3. Apply changes

### Debug Logging

<details>
<summary>Click to expand log output</summary>

```console

```
</details>

### GenAI / LLM Assisted Development

n/a

### Important Facts and References

_No response_

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by asungur**
## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the library.

### Description

When resource updates/deletes are running in parallel, sometimes `aws_elasticache_user`s to be deleted get deleted before they are removed from the associated `aws_elasticache_user_group` which causes `terraform apply` to fail.

This PR proposes to skip these errors since these `aws_elasticache_user`s are not relevant to the user group anymore.

### Relations

Closes #43281 

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccElastiCacheUserGroup_update PKG=elasticache 

make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.24.5 test ./internal/service/elasticache/... -v -count 1 -parallel 20 -run='TestAccElastiCacheUserGroup_update'  -timeout 360m -vet=off
2025/07/23 21:03:10 Creating Terraform AWS Provider (SDKv2-style)...
2025/07/23 21:03:10 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccElastiCacheUserGroup_update
=== PAUSE TestAccElastiCacheUserGroup_update
=== CONT  TestAccElastiCacheUserGroup_update
--- PASS: TestAccElastiCacheUserGroup_update (652.67s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/elasticache        657.096s

...
```

_**Replicating the issue, without the code change:**_
```
make testacc TESTS=TestAccElastiCacheUserGroup_update PKG=elasticache
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.24.5 test ./internal/service/elasticache/... -v -count 1 -parallel 20 -run='TestAccElastiCacheUserGroup_update'  -timeout 360m -vet=off
2025/07/23 20:49:31 Creating Terraform AWS Provider (SDKv2-style)...
2025/07/23 20:49:31 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccElastiCacheUserGroup_update
=== PAUSE TestAccElastiCacheUserGroup_update
=== CONT  TestAccElastiCacheUserGroup_update
    user_group_test.go:56: Step 3/7 error: Error running apply: exit status 1
        
        Error: updating ElastiCache User Group ("tf-acc-2261574475646944262"): operation error ElastiCache: ModifyUserGroup, https response error StatusCode: 400, RequestID: 9f7fee43-3346-49b4-a539-86e6c38db5d6, InvalidParameterValue: User tf-acc-2261574475646944262-3 is not a member of user group tf-acc-2261574475646944262.
        
          with aws_elasticache_user_group.test,
          on terraform_plugin_test.tf line 37, in resource "aws_elasticache_user_group" "test":
          37: resource "aws_elasticache_user_group" "test" {
        
--- FAIL: TestAccElastiCacheUserGroup_update (443.57s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/elasticache        447.967s
FAIL
make: *** [testacc] Error 1
```

### CODE REVIEW

File: internal/service/elasticache/user_group_test.go [hunk 1]
```diff
@@ -246,6 +264,32 @@ resource "aws_elasticache_user_group" "test" {
...
+	return acctest.ConfigCompose(acctest.ConfigAvailableAZsNoOptIn(), fmt.Sprintf(`
+resource "aws_elasticache_user" "test1" {
+  user_id       = "%[1]s-1"
+  user_name     = "default"
+  access_string = "on ~app::* -@all +@read +@hash +@bitmap +@geo -setbit -bitfield -hset -hsetnx -hmset -hincrby -hincrbyfloat -hdel -bitop -geoadd -georadius -georadiusbymember"
+  engine        = "REDIS"
+  passwords     = ["password123456789"]
+}
+
+resource "aws_elasticache_user" "test2" {
```
Comment (asungur) [inline internal/service/elasticache/user_group_test.go:277]: Change user id which will create/delete the `test2` user and trigger the existing bug

**Review by jar-b — DISMISSED** [review]
LGTM 🎉 

```console
% make testacc PKG=elasticache TESTS=TestAccElastiCacheUserGroup_
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 b-aws_ec_user_group-skip-removed-user 🌿...
TF_ACC=1 go1.24.6 test ./internal/service/elasticache/... -v -count 1 -parallel 20 -run='TestAccElastiCacheUserGroup_'  -timeout 360m -vet=off
2025/09/16 14:38:28 Creating Terraform AWS Provider (SDKv2-style)...
2025/09/16 14:38:28 Initializing Terraform AWS Provider (SDKv2-style)...

--- PASS: TestAccElastiCacheUserGroup_disappears (140.26s)
--- PASS: TestAccElastiCacheUserGroup_tags (140.39s)
--- PASS: TestAccElastiCacheUserGroup_basic (143.97s)
--- PASS: TestAccElastiCacheUserGroup_engineValkey (200.12s)
--- PASS: TestAccElastiCacheUserGroup_update (262.93s)
--- PASS: TestAccElastiCacheUserGroup_rotate (453.03s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/elasticache        459.658s
```

File: .changelog/43383.txt [hunk 2]
```diff
@@ -0,0 +1,3 @@
+```release-note:bug
```
Comment (johnsonaj) [inline .changelog/43383.txt]: please update changelog filename to match PR

**Review by johnsonaj — APPROVED** [review]
LGTM 🚀

**Comment by jar-b** [comment]
Thanks for your contribution, @asungur ! 👍
