### PR TITLE
resource/aws_verifiedpermissions_identity_source: Multiple fixes

### LINKED ISSUE #45248: Missing field when updating AWS Verified Permissions Identity Store configuration
### Terraform and AWS Provider Version

```console
OpenTofu v1.10.2
on darwin_arm64
+ provider registry.opentofu.org/hashicorp/aws v6.22.1

Issue was found using registry.opentofu.org/hashicorp/aws v6.18.0 initially.
```

### Affected Resource(s) or Data Source(s)

aws_verifiedpermissions_identity_source

### Expected Behavior

`apply` should update the identity-store configuration as planned.

### Actual Behavior

`apply` errors with missing field:
operation error VerifiedPermissions: UpdateIdentitySource, 1 validation
│ error(s) found.
│ - missing required field, UpdateIdentitySourceInput.UpdateConfiguration.

### Relevant Error/Panic Output

```
Error: 
updating AWS Verified Permissions Identity Source (): operation error VerifiedPermissions: UpdateIdentitySource, 1 validation error(s) found.
│ - missing required field, UpdateIdentitySourceInput.UpdateConfiguration.
│ 
│ 
│   with module.this.module.verified_permissions.aws_verifiedpermissions_identity_source.this[0],
│   on .terraform/modules/this.verified_permissions/identity-source.tf line 2, in resource "aws_verifiedpermissions_identity_source" "this":
│    2: resource "aws_verifiedpermissions_identity_source" "this" {
│ 
│ operation error VerifiedPermissions: UpdateIdentitySource, 1 validation
│ error(s) found.
│ - missing required field, UpdateIdentitySourceInput.UpdateConfiguration.
│ 
╵
Error: Failed to perform terraform apply. Unexpected exit code: 1
```

### Sample Terraform Configuration

<details open>
<summary>Click to expand configuration</summary>

```hcl
resource "aws_verifiedpermissions_identity_source" "this" {

  policy_store_id = aws_verifiedpermissions_policy_store.this.policy_store_id

  configuration {

    open_id_connect_configuration {
      issuer = "https://auth.example.com"

      token_selection {
        access_token_only {
          principal_id_claim = "Id"
        }
      }
      group_configuration {
        group_claim       = "groups"
        group_entity_type = "MyCorp::UserGroup"
      }
    }

  }
  principal_entity_type = "MyCorp::User"
}
```
</details>
There seems to be an issue with the AWS API call made when attempting to update an AWS Verified Permissions Identity Store configuration.
When creating an identity store we have configured the resource with an OpenID configuration, using access tokens & providing the principal entity type claim mapping.
This is created without any errors.

However, when we want to update the configuration with a group mapping we consistently get the above error message when running Tofu Apply.

The Tofu plan for the same run shows the configuration being updated as expected;

```
 # module.this.module.verified_permissions.aws_verifiedpermissions_identity_source.this[0] will be updated in-place
  ~ resource "aws_verifiedpermissions_identity_source" "this" {
        id                    = "id" 
        # (3 unchanged attributes hidden)
      ~ configuration {
          ~ open_id_connect_configuration {
                # (1 unchanged attribute hidden)
              + group_configuration {
                  + group_claim       = "group"
                  + group_entity_type = ""MyCorp::User"
                }
                # (1 unchanged block hidden)
            }
        }
    }
```
I've replaced the values for id, claim & namespace from the above just FYI.

One workaround we currently have is to delete the identity store entirely in the AWS console, then re-run the tofu apply, the identity-store resource is then re-created with the expected configuration, including the new group mapping.

### Steps to Reproduce

1. create an aws_verifiedpermissions_identity_source resource with principal_entity_type mapping to principal_id_claim.
2. change the configuration by updating either principal_entity_type, principal_id_claim or adding a group configuration block.
3. tofu apply will error

### Debug Logging

<details open>
<summary>Click to expand log output</summary>

```console

```
</details>

### GenAI / LLM Assisted Development

n/a

### Important Facts and References

https://search.opentofu.org/provider/opentofu/aws/latest/docs/resources/verifiedpermissions_identity_source
https://registry.terraform.io/providers/hashicorp/aws/6.0.0/docs/resources/verifiedpermissions_identity_source

### Would you like to implement a fix?

No

### LINKED ISSUE #45454: Spurious "AutoFlex Flatten; incompatible types" error when reading `aws_verifiedpermissions_identity_source` with `cognito_user_pool_configuration`
### Terraform and AWS Provider Version

```console
Terraform v1.14.1
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v6.25.0
```

### Affected Resource(s) or Data Source(s)

* `aws_verifiedpermissions_identity_source`

### Expected Behavior

When running terraform plan or apply on an existing `aws_verifiedpermissions_identity_source` configured with `cognito_user_pool_configuration`, the provider should refresh the state silently and successfully without logging errors to stderr.

### Actual Behavior

When running terraform plan or apply on an existing `aws_verifiedpermissions_identity_source` configured with `cognito_user_pool_configuration`, the plan / apply operation succeeds, however, the provider logs a severe ERROR to stderr indicating a type mismatch in the AutoFlex engine. This creates significant log noise and false alarms in CI/CD pipelines.

### Relevant Error/Panic Output

```console
aws_verifiedpermissions_policy_store.test_policy_store: Refreshing state... [id=FHbC7b2yC37DqL7UR8nkE1]
aws_cognito_user_pool.test_pool: Refreshing state... [id=eu-central-1_OVnAsmn2W]
aws_cognito_user_pool_client.test_client: Refreshing state... [id=4ukuf281541mj203vln8bqf5me]
aws_verifiedpermissions_identity_source.test_identity_source: Refreshing state... [id=97zb1Ebi6q9BK7Y5pi1UZN]
2025-12-05T15:38:46.571+0100 [ERROR] provider.terraform-provider-aws_v6.25.0_x5: AutoFlex Flatten; incompatible types: autoflex.target.path=Configuration to="map[ElemType:map[AttrTypes:map[cognito_user_pool_configuration:map[ElemType:map[AttrTypes:map[client_ids:map[ElemType:map[]] group_configuration:map[ElemType:map[AttrTypes:map[group_entity_type:map[]]]] user_pool_arn:map[]]]] open_id_connect_configuration:map[ElemType:map[AttrTypes:map[entity_id_prefix:map[] group_configuration:map[ElemType:map[AttrTypes:map[group_claim:map[] group_entity_type:map[]]]] issuer:map[] token_selection:map[ElemType:map[AttrTypes:map[access_token_only:map[ElemType:map[AttrTypes:map[audiences:map[ElemType:map[]] principal_id_claim:map[]]]] identity_token_only:map[ElemType:map[AttrTypes:map[client_ids:map[ElemType:map[]] principal_id_claim:map[]]]]]]]]]]]]]" @module=aws.autoflex tf_provider_addr=registry.terraform.io/hashicorp/aws tf_req_id=0ddadf7a-ffcb-ca45-c7d5-9a6e73a1663b @caller=github.com/hashicorp/terraform-provider-aws/internal/framework/flex/autoflex_flatten.go:1248 autoflex.source.path=Configuration autoflex.source.type=github.com/aws/aws-sdk-go-v2/service/verifiedpermissions/types.ConfigurationDetail tf_rpc=ReadResource tf_resource_type=aws_verifiedpermissions_identity_source autoflex.target.type=github.com/hashicorp/terraform-provider-aws/internal/framework/types.ListNestedObjectValueOf[github.com/hashicorp/terraform-provider-aws/internal/service/verifiedpermissions.configuration] from=20 tf_mux_provider="*proto5server.Server" timestamp="2025-12-05T15:38:46.571+0100"

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
```

### Sample Terraform Configuration

<details open>
<summary>Click to expand configuration</summary>

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "6.25.0"
    }
  }
}

provider "aws" {
  region = "eu-central-1"
}

resource "aws_cognito_user_pool" "test_pool" {
  name = "avp-repro-pool"
}

resource "aws_cognito_user_pool_client" "test_client" {
  name         = "avp-repro-client"
  user_pool_id = aws_cognito_user_pool.test_pool.id
}

resource "aws_verifiedpermissions_policy_store" "test_policy_store" {
  validation_settings {
    mode = "OFF"
  }
}

resource "aws_verifiedpermissions_identity_source" "test_identity_source" {
  policy_store_id       = aws_verifiedpermissions_policy_store.test_policy_store.id
  principal_entity_type = "Test::User"

  configuration {
    cognito_user_pool_configuration {
      user_pool_arn = aws_cognito_user_pool.test_pool.arn
      client_ids    = [aws_cognito_user_pool_client.test_client.id]
    }
  }
}

```
</details>

### Steps to Reproduce

1. Apply the configuration.
2. Run `TF_LOG=ERROR terraform plan`.
3. Observe the AutoFlex error logged to stderr, despite the run succeeding.

### Debug Logging

<details open>
<summary>Click to expand log output</summary>

```console

```
</details>

### GenAI / LLM Assisted Development

n/a

### Important Facts and References

Based on the AWS CLI output for the resource (provided below) and the [AWS docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-properties-verifiedpermissions-identitysource-identitysourceconfiguration.html), it looks like AWS returns OIDC-specific fields alongside Cognito-specific fields in the details block.

```
aws verifiedpermissions get-identity-source --policy-store-id FHbC7b2yC37DqL7UR8nkE1 --identity-source-id 97zb1Ebi6q9BK7Y5pi1UZN
{
    "createdDate": "2025-12-05T13:45:05.630356+00:00",
    "details": {
        "clientIds": [
            "4ukuf281541mj203vln8bqf5me"
        ],
        "userPoolArn": "arn:aws:cognito-idp:eu-central-1:REDACTED:userpool/eu-central-1_OVnAsmn2W",
        "discoveryUrl": "https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_OVnAsmn2W",
        "openIdIssuer": "COGNITO"
    },
    "identitySourceId": "97zb1Ebi6q9BK7Y5pi1UZN",
    "lastUpdatedDate": "2025-12-05T13:45:05.630356+00:00",
    "policyStoreId": "FHbC7b2yC37DqL7UR8nkE1",
    "principalEntityType": "Test::User"
}
```

The formatted schema from AutoFlex error log:

```
map[
    ElemType:map[
        AttrTypes:map[
            cognito_user_pool_configuration:map[
                ElemType:map[
                    AttrTypes:map[
                        client_ids:map[ElemType:map[]]
                        group_configuration:map[ElemType:map[AttrTypes:map[group_entity_type:map[]]]]
                        user_pool_arn:map[]
                    ]
                ]
            ]
            open_id_connect_configuration:map[
                ElemType:map[
                    AttrTypes:map[
                        entity_id_prefix:map[]
                        group_configuration:map[ElemType:map[AttrTypes:map[group_claim:map[] group_entity_type:map[]]]] issuer:map[]
                        token_selection:map[
                            ElemType:map[
                                AttrTypes:map[
                                    access_token_only:map[ElemType:map[AttrTypes:map[audiences:map[ElemType:map[]]
                                    principal_id_claim:map[]]]]
                                    identity_token_only:map[ElemType:map[AttrTypes:map[client_ids:map[ElemType:map[]] principal_id_claim:map[]]]]
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ]
    ]
]

```

**Hypothesis** 

I have a very limited understanding of what is going on here, but from the observed behavior and logs it appears that AutoFlex reads the API response and attempts to match it to the `open_id_connect_configuration` schema block, which fails and produces the error log. It does not crash the run, likely because it subsequently attempts to match the `cognito_user_pool_configuration schema`, which succeeds.

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by gdavison**
## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the library.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

### Description

Multiple fixes for `aws_verifiedpermissions_identity_source`:

* Now allows modifying `aws_verifiedpermissions_identity_source` resources
* Prevents eventual consistency error for associated Policy Store
* Removes AutoFlex error messages

### Relations

Closes #45454
Closes #45248

### Output from Acceptance Testing

```console
% make testacc PKG=verifiedpermissions TESTS=TestAccVerifiedPermissionsIdentitySource_

--- PASS: TestAccVerifiedPermissionsIdentitySource_disappears (22.89s)
--- PASS: TestAccVerifiedPermissionsIdentitySource_Cognito_basic (25.51s)
--- PASS: TestAccVerifiedPermissionsIdentitySource_OpenID_basic (25.53s)
--- PASS: TestAccVerifiedPermissionsIdentitySource_OpenID_convertToCognito (36.46s)
--- PASS: TestAccVerifiedPermissionsIdentitySource_Cognito_update (37.59s)
--- PASS: TestAccVerifiedPermissionsIdentitySource_Cognito_convertToOpenID (39.72s)
--- PASS: TestAccVerifiedPermissionsIdentitySource_OpenID_update (53.35s)
```

### CODE REVIEW

File: internal/framework/flex/autoflex_flatten.go [hunk 1]
```diff
@@ -2025,6 +2023,16 @@ func diagFlatteningTargetDoesNotImplementAttrValue(targetType reflect.Type) diag
...
 
+// func diagFlatteningTargetDoesNotImplementFlexFlattener(targetType reflect.Type) diag.ErrorDiagnostic {
+// 	return diag.NewErrorDiagnostic(
+// 		"Incompatible Types",
+// 		"An unexpected error occurred while flattening configuration. "+
+// 			"This is always an error in the provider. "+
+// 			"Please report the following to the provider developer:\n\n"+
+// 			fmt.Sprintf("Target type %q does not implement flex.Flattener", fullTypeName(targetType)),
+// 	)
+// }
```
Comment (jar-b) [inline internal/framework/flex/autoflex_flatten.go:2037]: Can this be deleted?

File: internal/framework/flex/autoflex_flatten.go [hunk 2]
```diff
@@ -1245,10 +1245,8 @@ func (flattener autoFlattener) interfaceToNestedObject(ctx context.Context, vFro
 
 		vTo.Set(reflect.ValueOf(val))
 
-		tflog.SubsystemError(ctx, subsystemName, "AutoFlex Flatten; incompatible types", map[string]any{
-			"from": vFrom.Kind(),
-			"to":   tTo,
-		})
+		tflog.SubsystemError(ctx, subsystemName, "Source does not implement flex.Flattener")
+		// diags.Append(diagFlatteningTargetDoesNotImplementFlexFlattener(reflect.TypeOf(vTo.Interface())))
```
Comment (jar-b) [inline internal/framework/flex/autoflex_flatten.go:1249]: Potentially also deleted.

**Review by jar-b — DISMISSED** [review]
LGTM 🚀
