### PR TITLE
r/pinpoint_event_stream - retry on eventual consistency error

### LINKED ISSUE #15899: Race condition between pinpoint event stream and dependencies not handled
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

* terragrunt version v0.25.5
* Terraform version: 0.13.5
* hashicorp/aws version = "~> 3.12.0"

### Affected Resource(s)

* aws_pinpoint_event_stream
* aws_kinesis_firehose_delivery_stream

### Terraform Configuration Files

Settup is identical to https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/pinpoint_event_stream#example-usage except we're using a `aws_kinesis_firehose_delivery_stream` instead of the `aws_kinesis_stream` in the example.  Please note that adding explicit `depends_on` did not resolve the issue.

```hcl
resource "aws_pinpoint_event_stream" "transaction_app_event_stream" {
  application_id         = aws_pinpoint_app.transaction_app.application_id
  destination_stream_arn = aws_kinesis_firehose_delivery_stream.pinpoint_event_delivery_stream.arn
  role_arn               = aws_iam_role.pinpoint_kinesis_delivery_stream_role.arn
  depends_on = [
    aws_iam_role.pinpoint_kinesis_delivery_stream_role,
    # make sure the role's policy is present
    aws_iam_role_policy.pinpoint_kinesis_delivery_stream_policy,
    aws_kinesis_firehose_delivery_stream.pinpoint_event_delivery_stream
  ]
}
```

### Expected Behavior

We have a module that creates a pinpoint event stream along with the kinesis delivery stream and iam role needed to access the delivery stream.  This is pretty much identical to the https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/pinpoint_event_stream#example-usage.  The only difference is we're using a delivery stream instead of a data stream.

Pinpoint Event stream should've been created with the configured `destination_stream_arn` and `role_arn` which are also defined in the same module.

### Actual Behavior

All resources in the module except the `aws_pinpoint_event_stream` are created successfully.  The event streams error with the following message.  Simply re-running apply immediately after the failure successfully creates the event streams.

module.pinpoint.aws_iam_role_policy.pinpoint_kinesis_delivery_stream_policy: Creating...
module.pinpoint.aws_iam_role_policy.pinpoint_kinesis_delivery_stream_policy: Creation complete after 1s [id=role-dev-navigating-care-pinpoint-event-delivery-stream:delivery_stream_policy]
module.pinpoint.aws_pinpoint_event_stream.info_app_event_stream: Creating...
module.pinpoint.aws_pinpoint_event_stream.transaction_app_event_stream: Creating...

Error: error putting Pinpoint Event Stream for application ***masked***: BadRequestException: Destination stream validation failed. Check Destination and Role ARN values and make sure the IAM Role is configured correctly.
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "248a4927-ddab-4cc8-9444-b65379e795ae"
  },
  Message_: "Destination stream validation failed. Check Destination and Role ARN values and make sure the IAM Role is configured correctly.",
  RequestID_: "248a4927-ddab-4cc8-9444-b65379e795ae"
}

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

### PR DESCRIPTION
**Pull request by DrFaust92**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #15899

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSPinpointEventStream_'
--- PASS: TestAccAWSPinpointEventStream_disappears (92.02s)
--- PASS: TestAccAWSPinpointEventStream_basic (204.16s)
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
Verified acceptance tests:

```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSPinpointEventStream_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSPinpointEventStream_ -timeout 180m
=== RUN   TestAccAWSPinpointEventStream_basic
=== PAUSE TestAccAWSPinpointEventStream_basic
=== RUN   TestAccAWSPinpointEventStream_disappears
=== PAUSE TestAccAWSPinpointEventStream_disappears
=== CONT  TestAccAWSPinpointEventStream_basic
=== CONT  TestAccAWSPinpointEventStream_disappears
--- PASS: TestAccAWSPinpointEventStream_disappears (66.57s)
--- PASS: TestAccAWSPinpointEventStream_basic (136.22s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	136.319s
```

File: aws/resource_aws_pinpoint_event_stream.go [hunk 1]
```diff
@@ -42,19 +44,22 @@ func resourceAwsPinpointEventStreamUpsert(d *schema.ResourceData, meta interface
...
 	req := pinpoint.PutEventStreamInput{
 		ApplicationId:    aws.String(applicationId),
 		WriteEventStream: params,
 	}
 
-	_, err := conn.PutEventStream(&req)
+	// Retry for IAM eventual consistency
+	_, err := retryOnAwsCode("BadRequestException", func() (interface{}, error) {
+		return conn.PutEventStream(&req)
+	})
```
Comment (bflad) [inline aws/resource_aws_pinpoint_event_stream.go:60]: IAM eventual consistency retry logic should follow this Contributing Guide section: https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/retries-and-waiters.md#iam-error-retries

I would also recommend conditionalizing this based on the error message as well, since `BadRequestException` by itself could retry on actually malformed requests.

**Review by bflad — APPROVED** [review]
Will adjust retry logic on merge, but otherwise looks good. Thank you, @DrFaust92 🚀 

Output from acceptance testing in AWS Commercial:

```
--- PASS: TestAccAWSPinpointEventStream_disappears (71.12s)
--- PASS: TestAccAWSPinpointEventStream_basic (143.79s)
```

Output from acceptance testing in AWS GovCloud (US):

```
--- PASS: TestAccAWSPinpointEventStream_disappears (69.10s)
--- PASS: TestAccAWSPinpointEventStream_basic (148.10s)
```
