### PR TITLE
r/ssm_maintainance_window_target - remove from state if deleted

### LINKED ISSUE #16451: AWS SSM DoesNotExistException for missing Maintenance Window Target
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.16.0
```

### Affected Resource(s)

* aws_ssm_maintenance_window_target

### Terraform Configuration Files

```hcl
resource "aws_ssm_maintenance_window" "default" {
  cutoff   = 1
  duration = 3
  name     = "default"
  schedule = "cron(0 0 2 ? * * *)"
}

resource "aws_ssm_maintenance_window_target" "default" {
  window_id     = aws_ssm_maintenance_window.default.id
  name          = "default-target"
  description   = "Default maintenance window target"
  resource_type = "INSTANCE"

  targets {
    key    = "tag:SystemManagement"
    values = ["default"]
  }
}
```

### Panic Output

`Error: DoesNotExistException: Maintenance window mw-XXXX does not exist`

### Expected Behavior

After deleting all resources in our AWS Account via aws-nuke, I'd like to refresh the Terraform state to remove the deleted resources from the state as well. I expect that after running `terraform refresh` my state should be updated.

### Actual Behavior

`terraform refresh` errors with `Error: DoesNotExistException: Maintenance window mw-XXXX does not exist`. This seems to be caused by the `aws_ssm_maintenance_window_target` resource. When I manually remove it from the state via `terraform state rm aws_ssm_maintenance_window.default` and then run the refresh again, everything works fine.

### Steps to Reproduce

1. `terraform apply`
2. Delete the resource via AWS cli, aws-nuke or via the Developer Console.
3. `terraform refresh`

### Important Factoids

Nothing I know of.

### References

Looks similar to the following issues:
* https://github.com/hashicorp/terraform-provider-aws/issues/5412

### PR DESCRIPTION
**Pull request by DrFaust92**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #16451

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource_aws_ssm_maintainance_window_target - remove from state if deleted
resource_aws_ssm_maintainance_window_target - add plan time validation to `targets.key`, `targets.values`, `owner_information`.
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSSSMMaintenanceWindowTarget_'
--- PASS: TestAccAWSSSMMaintenanceWindowTarget_validation (9.44s)
--- PASS: TestAccAWSSSMMaintenanceWindowTarget_disappears_window (35.48s)
--- PASS: TestAccAWSSSMMaintenanceWindowTarget_disappears (39.88s)
--- PASS: TestAccAWSSSMMaintenanceWindowTarget_basic (47.08s)
--- PASS: TestAccAWSSSMMaintenanceWindowTarget_noNameOrDescription (47.48s)
--- PASS: TestAccAWSSSMMaintenanceWindowTarget_resourceGroup (47.54s)
--- PASS: TestAccAWSSSMMaintenanceWindowTarget_update (89.70s)
```

### CODE REVIEW

File: aws/resource_aws_ssm_maintenance_window_target.go [hunk 1]
```diff
@@ -151,7 +160,7 @@ func resourceAwsSsmMaintenanceWindowTargetRead(d *schema.ResourceData, meta inte
 			d.Set("description", t.Description)
 
 			if err := d.Set("targets", flattenAwsSsmTargets(t.Targets)); err != nil {
-				return fmt.Errorf("Error setting targets error: %#v", err)
+				return fmt.Errorf("Error setting targets error: %w", err)
```
Comment (ewbankkit) [inline aws/resource_aws_ssm_maintenance_window_target.go:163]:
```suggestion
				return fmt.Errorf("Error setting targets: %w", err)
```

**Comment by ewbankkit** [comment]
Verified acceptance tests:

```console
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSSSMMaintenanceWindowTarget_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSSSMMaintenanceWindowTarget_ -timeout 120m
=== RUN   TestAccAWSSSMMaintenanceWindowTarget_basic
=== PAUSE TestAccAWSSSMMaintenanceWindowTarget_basic
=== RUN   TestAccAWSSSMMaintenanceWindowTarget_noNameOrDescription
=== PAUSE TestAccAWSSSMMaintenanceWindowTarget_noNameOrDescription
=== RUN   TestAccAWSSSMMaintenanceWindowTarget_validation
=== PAUSE TestAccAWSSSMMaintenanceWindowTarget_validation
=== RUN   TestAccAWSSSMMaintenanceWindowTarget_update
=== PAUSE TestAccAWSSSMMaintenanceWindowTarget_update
=== RUN   TestAccAWSSSMMaintenanceWindowTarget_resourceGroup
=== PAUSE TestAccAWSSSMMaintenanceWindowTarget_resourceGroup
=== RUN   TestAccAWSSSMMaintenanceWindowTarget_disappears
=== PAUSE TestAccAWSSSMMaintenanceWindowTarget_disappears
=== RUN   TestAccAWSSSMMaintenanceWindowTarget_disappears_window
=== PAUSE TestAccAWSSSMMaintenanceWindowTarget_disappears_window
=== CONT  TestAccAWSSSMMaintenanceWindowTarget_basic
=== CONT  TestAccAWSSSMMaintenanceWindowTarget_resourceGroup
=== CONT  TestAccAWSSSMMaintenanceWindowTarget_disappears_window
=== CONT  TestAccAWSSSMMaintenanceWindowTarget_disappears
=== CONT  TestAccAWSSSMMaintenanceWindowTarget_validation
=== CONT  TestAccAWSSSMMaintenanceWindowTarget_update
=== CONT  TestAccAWSSSMMaintenanceWindowTarget_noNameOrDescription
2020/11/29 17:54:10 [WARN] Got error running Terraform: 2020/11/29 17:54:08 [DEBUG] Using modified User-Agent: Terraform/0.12.26 HashiCorp-terraform-exec/0.10.0

Error: invalid value for name (Only alphanumeric characters, hyphens, dots & underscores allowed)

  on config828337723/terraform_plugin_test.tf line 10, in resource "aws_ssm_maintenance_window_target" "test":
  10:   name              = "Bäd Name!@#$%^"


--- PASS: TestAccAWSSSMMaintenanceWindowTarget_validation (5.97s)
--- PASS: TestAccAWSSSMMaintenanceWindowTarget_disappears_window (18.60s)
--- PASS: TestAccAWSSSMMaintenanceWindowTarget_disappears (22.74s)
--- PASS: TestAccAWSSSMMaintenanceWindowTarget_basic (23.73s)
--- PASS: TestAccAWSSSMMaintenanceWindowTarget_resourceGroup (25.95s)
--- PASS: TestAccAWSSSMMaintenanceWindowTarget_noNameOrDescription (26.05s)
--- PASS: TestAccAWSSSMMaintenanceWindowTarget_update (38.57s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	38.641s
```

**Review by bflad — APPROVED** [review]
Looks good, thank you, @DrFaust92 🚀 

Output from acceptance testing:

```
--- PASS: TestAccAWSSSMMaintenanceWindowTarget_validation (5.21s)
--- PASS: TestAccAWSSSMMaintenanceWindowTarget_disappears_window (14.93s)
--- PASS: TestAccAWSSSMMaintenanceWindowTarget_disappears (17.64s)
--- PASS: TestAccAWSSSMMaintenanceWindowTarget_basic (17.72s)
--- PASS: TestAccAWSSSMMaintenanceWindowTarget_resourceGroup (18.33s)
--- PASS: TestAccAWSSSMMaintenanceWindowTarget_noNameOrDescription (18.74s)
--- PASS: TestAccAWSSSMMaintenanceWindowTarget_update (27.98s)
```
