### PR TITLE
r/backup_plan - retry on delete + validations

### LINKED ISSUE #10414: Backup Plan deletion fails randomly
Hi!

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.14
provider.aws v2.19.0
provider.random v2.2.1

### Affected Resource(s)

* aws_backup_selection
* aws_backup_plan

### Terraform Configuration Files

Code can be found here: https://scm.dazzlingwrench.fxinnovation.com/fxinnovation-public/terraform-module-aws-backup/pulls/2/files

### Expected Behavior

I expect all resources to be destroyed without issue.

### Actual Behavior

**Randomly**, Terraform fails to delete Backup Plan, saying Backup Selections should be deleted before:

```
Error: Error applying plan:

1 error occurred:
	* module.default.aws_backup_plan.this (destroy): 1 error occurred:
	* aws_backup_plan.this: error deleting Backup Plan: InvalidRequestException: Related backup plan selections must be deleted prior to backup plan deletion
	status code: 400, request id: 170f2b1c-156e-4e77-97e3-9aacbd9b6d02
```

Even if the actual order of deletion is correct:
```
module.default.aws_backup_selection.by_resources: Destruction complete after 1s
module.default.aws_backup_selection.by_tags: Destruction complete after 1s
aws_ebs_volume.example: Destroying... (ID: vol-0f6fecced036d1281)
module.default.aws_iam_role.this: Destroying... (ID: tftestbtsaul9fRole)
module.default.aws_backup_plan.this: Destroying... (ID: 170f2b1c-156e-4e77-97e3-9aacbd9b6d02)
```

My bet is that AWS API returns an OK status for Backup Selection deletion before it’s actually true…

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`

### PR DESCRIPTION
**Pull request by DrFaust92**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #10414

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource_aws_backup_plan - retry delete if selections are still attached
resource_aws_backup_plan - add plan time validations for `rule.rule_name`, `rule.target_vault_name` , `rule.lifecycle.delete_after`, `rule.copy_action.lifecycle.delete_after`, `advanced_backup_setting.resource_type 
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAwsBackupPlan_'
--- PASS: TestAccAwsBackupPlan_basic (51.36s)
--- PASS: TestAccAwsBackupPlan_Rule_CopyAction_NoLifecycle (130.37s)
--- PASS: TestAccAwsBackupPlan_Rule_CopyAction_SameRegion (139.68s)
--- PASS: TestAccAwsBackupPlan_withLifecycle (209.53s)
--- PASS: TestAccAwsBackupPlan_withRecoveryPointTags (176.58s)
--- PASS: TestAccAwsBackupPlan_AdvancedBackupSetting (94.81s)
--- PASS: TestAccAwsBackupPlan_disappears (37.81s)
--- PASS: TestAccAwsBackupPlan_Rule_CopyAction_CrossRegion (47.25s)
--- PASS: TestAccAwsBackupPlan_Rule_CopyAction_Multiple (47.56s)
--- PASS: TestAccAwsBackupPlan_withRules (169.26s)
--- PASS: TestAccAwsBackupPlan_withTags (123.17s)
```

### CODE REVIEW

**Review by ewbankkit — APPROVED** [review]
LGTM.

```console
$ make testacc TEST=./aws TESTARGS='-run=TestAccAwsBackupPlan_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsBackupPlan_ -timeout 120m
=== RUN   TestAccAwsBackupPlan_basic
=== PAUSE TestAccAwsBackupPlan_basic
=== RUN   TestAccAwsBackupPlan_withTags
=== PAUSE TestAccAwsBackupPlan_withTags
=== RUN   TestAccAwsBackupPlan_withRules
=== PAUSE TestAccAwsBackupPlan_withRules
=== RUN   TestAccAwsBackupPlan_withLifecycle
=== PAUSE TestAccAwsBackupPlan_withLifecycle
=== RUN   TestAccAwsBackupPlan_withRecoveryPointTags
=== PAUSE TestAccAwsBackupPlan_withRecoveryPointTags
=== RUN   TestAccAwsBackupPlan_Rule_CopyAction_SameRegion
=== PAUSE TestAccAwsBackupPlan_Rule_CopyAction_SameRegion
=== RUN   TestAccAwsBackupPlan_Rule_CopyAction_NoLifecycle
=== PAUSE TestAccAwsBackupPlan_Rule_CopyAction_NoLifecycle
=== RUN   TestAccAwsBackupPlan_Rule_CopyAction_Multiple
=== PAUSE TestAccAwsBackupPlan_Rule_CopyAction_Multiple
=== RUN   TestAccAwsBackupPlan_Rule_CopyAction_CrossRegion
=== PAUSE TestAccAwsBackupPlan_Rule_CopyAction_CrossRegion
=== RUN   TestAccAwsBackupPlan_AdvancedBackupSetting
=== PAUSE TestAccAwsBackupPlan_AdvancedBackupSetting
=== RUN   TestAccAwsBackupPlan_disappears
=== PAUSE TestAccAwsBackupPlan_disappears
=== CONT  TestAccAwsBackupPlan_basic
=== CONT  TestAccAwsBackupPlan_Rule_CopyAction_NoLifecycle
=== CONT  TestAccAwsBackupPlan_disappears
=== CONT  TestAccAwsBackupPlan_AdvancedBackupSetting
=== CONT  TestAccAwsBackupPlan_Rule_CopyAction_CrossRegion
=== CONT  TestAccAwsBackupPlan_Rule_CopyAction_Multiple
=== CONT  TestAccAwsBackupPlan_withLifecycle
=== CONT  TestAccAwsBackupPlan_Rule_CopyAction_SameRegion
=== CONT  TestAccAwsBackupPlan_withRecoveryPointTags
=== CONT  TestAccAwsBackupPlan_withRules
=== CONT  TestAccAwsBackupPlan_withTags
--- PASS: TestAccAwsBackupPlan_disappears (35.91s)
--- PASS: TestAccAwsBackupPlan_basic (42.04s)
--- PASS: TestAccAwsBackupPlan_AdvancedBackupSetting (42.70s)
--- PASS: TestAccAwsBackupPlan_Rule_CopyAction_Multiple (42.82s)
--- PASS: TestAccAwsBackupPlan_Rule_CopyAction_CrossRegion (44.20s)
--- PASS: TestAccAwsBackupPlan_withRecoveryPointTags (72.50s)
--- PASS: TestAccAwsBackupPlan_withRules (73.04s)
--- PASS: TestAccAwsBackupPlan_withTags (76.57s)
--- PASS: TestAccAwsBackupPlan_Rule_CopyAction_NoLifecycle (77.55s)
--- PASS: TestAccAwsBackupPlan_Rule_CopyAction_SameRegion (78.34s)
--- PASS: TestAccAwsBackupPlan_withLifecycle (88.29s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	88.418s
```

File: aws/resource_aws_backup_plan.go [hunk 1]
```diff
@@ -36,10 +40,18 @@ func resourceAwsBackupPlan() *schema.Resource {
 						"rule_name": {
 							Type:     schema.TypeString,
 							Required: true,
+							ValidateFunc: validation.All(
+								validation.StringLenBetween(1, 50),
+								validation.StringDoesNotMatch(regexp.MustCompile(`^[a-zA-Z0-9\-\_\.]$`), ""),
```
Comment (bflad) [inline aws/resource_aws_backup_plan.go:45]: Shouldn't this validation be checking for all characters to match? This is currently checking that the string does not match a single character of these types.

Also its generally good to provide practitioners with a helpful validation error message rather than the raw regular expression. See also some future linting: https://github.com/bflad/tfproviderlint/issues/214

```suggestion
								validation.StringMatch(regexp.MustCompile(`^[a-zA-Z0-9\-\_\.]+$`), "must contain only alphanumeric characters, hyphens, underscores, and periods"),
```

File: aws/resource_aws_backup_plan.go [hunk 2]
```diff
@@ -36,10 +40,18 @@ func resourceAwsBackupPlan() *schema.Resource {
...
+							),
 						},
 						"target_vault_name": {
 							Type:     schema.TypeString,
 							Required: true,
+							ValidateFunc: validation.All(
+								validation.StringLenBetween(2, 50),
+								validation.StringDoesNotMatch(regexp.MustCompile(`^[a-zA-Z0-9\-\_]$`), ""),
```
Comment (bflad) [inline aws/resource_aws_backup_plan.go:53]: Similarly:

```suggestion
								validation.StringMatch(regexp.MustCompile(`^[a-zA-Z0-9\-\_]+$`), "must contain only alphanumeric characters, hyphens, and underscores"),
```

**Review by bflad — CHANGES_REQUESTED** [review]
Otherwise looking good

**Review by bflad — APPROVED** [review]
Looks good, thank you @DrFaust92 🚀 

Output from acceptance testing:

```
--- PASS: TestAccAwsBackupPlan_disappears (28.69s)
--- PASS: TestAccAwsBackupPlan_basic (32.26s)
--- PASS: TestAccAwsBackupPlan_AdvancedBackupSetting (32.54s)
--- PASS: TestAccAwsBackupPlan_Rule_CopyAction_Multiple (32.98s)
--- PASS: TestAccAwsBackupPlan_Rule_CopyAction_CrossRegion (41.01s)
--- PASS: TestAccAwsBackupPlan_withTags (58.71s)
--- PASS: TestAccAwsBackupPlan_withRecoveryPointTags (58.79s)
--- PASS: TestAccAwsBackupPlan_Rule_CopyAction_SameRegion (58.91s)
--- PASS: TestAccAwsBackupPlan_withRules (59.84s)
--- PASS: TestAccAwsBackupPlan_Rule_CopyAction_NoLifecycle (60.10s)
--- PASS: TestAccAwsBackupPlan_withLifecycle (65.80s)
```
