### PR TITLE
Use engine_version and engine_version_actual for aws_db_instance

### LINKED ISSUE #14277: Add supressAwsEngineVersionDiffs to RDS Aurora aws_rds_cluster
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When doing automatic minor updates to Aurora, there's not a way in the resource aws_rds_cluster to suppress the incremental engine_version updates like in aws_db_instance.

### New or Affected Resource(s)

aws_rds_cluster

### Potential Terraform Configuration

engine_version = 5.7  //mysql should equate to 5.7.mysql_aurora.2.x.x
engine_version = 11  //postgresql should equate to 11.x

```hcl
resource "aws_rds_cluster" "default" {

  cluster_identifier = "${lower(var.db_cluster_identifier)}"
  db_subnet_group_name                = aws_db_subnet_group.rds_subnet_group.name
  database_name                       = var.db_name
  deletion_protection                 = var.deletion_protection
  master_username                     = var.username
  master_password                     = var.password
  apply_immediately                   = var.apply_immediately
  engine                              = "aurora-postgresql"
  engine_version                      = "11"
  source_region                       = data.aws_region.current.name
}
```

### References

compare sections

https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_db_instance.go#L86

with

https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_rds_cluster.go#L159

DiffSuppressFunc: suppressAwsDbEngineVersionDiffs not defined for aws_rds_cluster

* #0000

### LINKED ISSUE #19240: aws_db_instance engine_version gets updated in-place with every run
Hello,

Whenever `auto_minor_version_upgrade` is disabled with every `terraform apply` it wants to do `engine_version` update in-place.

When `auto_minor_version_upgrade` is enabled it works as expected.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.37.0
```

### Affected Resource(s)

* aws_db_instance

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_db_instance" "default" {
  instance_class             = "db.t3.small"
  license_model              = "license-included"
  maintenance_window         = "sun:03:05-sun:05:00"
  engine                     = "oracle-se2"
  engine_version             = "12.1"
  name                       = "EMXPL"
  auto_minor_version_upgrade = false
  allocated_storage          = 10
  username                   = "foo"
  password                   = "foobarbaz"
  skip_final_snapshot        = true
}
```

### Expected Behavior

Configuration has not changed therefore there should be no update in-place. As long as major version is in order (12.1 matches 12.1.x.y.z) there should not be an update.

### Actual Behavior

With every run Terraform wants to update engine_version as you can see below. In reality it does nothing as anyway it stays pinned to the newest minor version that's actually available in AWS RDS.

Below there's a plan from second run (after it was first created without any problems).

```terraform
aws_db_instance.default: Refreshing state... [id=terraform-20210504214948210400000001]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # aws_db_instance.default will be updated in-place
  ~ resource "aws_db_instance" "default" {
        address                               = "terraform-20210504214948210400000001.ck27w5szo6th.us-east-1.rds.amazonaws.com"
        allocated_storage                     = 10
        arn                                   = "arn:aws:rds:us-east-1:237839530861:db:terraform-20210504214948210400000001"
        auto_minor_version_upgrade            = false
        availability_zone                     = "us-east-1c"
        backup_retention_period               = 0
        backup_window                         = "05:57-06:27"
        ca_cert_identifier                    = "rds-ca-2019"
        character_set_name                    = "AL32UTF8"
        copy_tags_to_snapshot                 = false
        db_subnet_group_name                  = "default"
        delete_automated_backups              = true
        deletion_protection                   = false
        enabled_cloudwatch_logs_exports       = []
        endpoint                              = "terraform-20210504214948210400000001.ck27w5szo6th.us-east-1.rds.amazonaws.com:1521"
        engine                                = "oracle-se2"
      ~ engine_version                        = "12.1.0.2.v23" -> "12.1"
      	# redacted rest of the lines
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to Reproduce

1. `terraform apply`

* #0000

### PR DESCRIPTION
**Pull request by bill-rich**
Instead of suppressing diffs to allow for using less specific `engine_version`s, allow `engine_version` to be less specific, and keep the actual engine version in `engine_version_actual`.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #20211.
Closes #19240.
Closes #14277.

Output from acceptance testing:

```
=== RUN   TestAccAWSDBInstance_basic
=== PAUSE TestAccAWSDBInstance_basic
=== RUN   TestAccAWSDBInstance_OnlyMajorVersion
=== PAUSE TestAccAWSDBInstance_OnlyMajorVersion
=== RUN   TestAccAWSDBInstance_namePrefix
=== PAUSE TestAccAWSDBInstance_namePrefix
=== RUN   TestAccAWSDBInstance_generatedName
=== PAUSE TestAccAWSDBInstance_generatedName
=== RUN   TestAccAWSDBInstance_kmsKey
=== PAUSE TestAccAWSDBInstance_kmsKey
=== RUN   TestAccAWSDBInstance_subnetGroup
=== PAUSE TestAccAWSDBInstance_subnetGroup
=== RUN   TestAccAWSDBInstance_optionGroup
=== PAUSE TestAccAWSDBInstance_optionGroup
=== RUN   TestAccAWSDBInstance_iamAuth
=== PAUSE TestAccAWSDBInstance_iamAuth
=== RUN   TestAccAWSDBInstance_AllowMajorVersionUpgrade
=== PAUSE TestAccAWSDBInstance_AllowMajorVersionUpgrade
=== RUN   TestAccAWSDBInstance_DbSubnetGroupName
=== PAUSE TestAccAWSDBInstance_DbSubnetGroupName
=== RUN   TestAccAWSDBInstance_DbSubnetGroupName_RamShared
=== PAUSE TestAccAWSDBInstance_DbSubnetGroupName_RamShared
=== RUN   TestAccAWSDBInstance_DbSubnetGroupName_VpcSecurityGroupIds
=== PAUSE TestAccAWSDBInstance_DbSubnetGroupName_VpcSecurityGroupIds
=== RUN   TestAccAWSDBInstance_DeletionProtection
=== PAUSE TestAccAWSDBInstance_DeletionProtection
=== RUN   TestAccAWSDBInstance_FinalSnapshotIdentifier
=== PAUSE TestAccAWSDBInstance_FinalSnapshotIdentifier
=== RUN   TestAccAWSDBInstance_FinalSnapshotIdentifier_SkipFinalSnapshot
=== PAUSE TestAccAWSDBInstance_FinalSnapshotIdentifier_SkipFinalSnapshot
=== RUN   TestAccAWSDBInstance_IsAlreadyBeingDeleted
=== PAUSE TestAccAWSDBInstance_IsAlreadyBeingDeleted
=== RUN   TestAccAWSDBInstance_MaxAllocatedStorage
=== PAUSE TestAccAWSDBInstance_MaxAllocatedStorage
=== RUN   TestAccAWSDBInstance_Password
=== PAUSE TestAccAWSDBInstance_Password
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_AllocatedStorage
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_AllocatedStorage
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_AllowMajorVersionUpgrade
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_AllowMajorVersionUpgrade
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_AutoMinorVersionUpgrade
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_AutoMinorVersionUpgrade
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_AvailabilityZone
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_AvailabilityZone
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_BackupRetentionPeriod
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_BackupRetentionPeriod
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_BackupWindow
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_BackupWindow
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_DbSubnetGroupName
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_DbSubnetGroupName
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_DbSubnetGroupName_RamShared
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_DbSubnetGroupName_RamShared
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_DbSubnetGroupName_VpcSecurityGroupIds
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_DbSubnetGroupName_VpcSecurityGroupIds
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_DeletionProtection
    provider_test.go:57: CreateDBInstanceReadReplica API currently ignores DeletionProtection=true with SourceDBInstanceIdentifier set
--- SKIP: TestAccAWSDBInstance_ReplicateSourceDb_DeletionProtection (0.00s)
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_IamDatabaseAuthenticationEnabled
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_IamDatabaseAuthenticationEnabled
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_MaintenanceWindow
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_MaintenanceWindow
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_MaxAllocatedStorage
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_MaxAllocatedStorage
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_Monitoring
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_Monitoring
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_MultiAZ
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_MultiAZ
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_ParameterGroupName
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_ParameterGroupName
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_Port
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_Port
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_VpcSecurityGroupIds
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_VpcSecurityGroupIds
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_CACertificateIdentifier
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_CACertificateIdentifier
=== RUN   TestAccAWSDBInstance_S3Import
=== PAUSE TestAccAWSDBInstance_S3Import
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier
=== RUN   TestAccAWSDBInstance_SnapshotIdentifierRemoved
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifierRemoved
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_AllocatedStorage
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_AllocatedStorage
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_Io1Storage
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_Io1Storage
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_AllowMajorVersionUpgrade
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_AllowMajorVersionUpgrade
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_AutoMinorVersionUpgrade
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_AutoMinorVersionUpgrade
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_AvailabilityZone
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_AvailabilityZone
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_BackupRetentionPeriod
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_BackupRetentionPeriod
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_BackupRetentionPeriod_Unset
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_BackupRetentionPeriod_Unset
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_BackupWindow
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_BackupWindow
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_DbSubnetGroupName
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_DbSubnetGroupName
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_DbSubnetGroupName_RamShared
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_DbSubnetGroupName_RamShared
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_DbSubnetGroupName_VpcSecurityGroupIds
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_DbSubnetGroupName_VpcSecurityGroupIds
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_DeletionProtection
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_DeletionProtection
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_IamDatabaseAuthenticationEnabled
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_IamDatabaseAuthenticationEnabled
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_MaintenanceWindow
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_MaintenanceWindow
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_MaxAllocatedStorage
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_MaxAllocatedStorage
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_Monitoring
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_Monitoring
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_MultiAZ
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_MultiAZ
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_MultiAZ_SQLServer
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_MultiAZ_SQLServer
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_ParameterGroupName
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_ParameterGroupName
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_Port
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_Port
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_Tags
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_Tags
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_Tags_Unset
    provider_test.go:57: To be fixed: https://github.com/hashicorp/terraform-provider-aws/issues/5959
--- SKIP: TestAccAWSDBInstance_SnapshotIdentifier_Tags_Unset (0.00s)
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_VpcSecurityGroupIds
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_VpcSecurityGroupIds
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_VpcSecurityGroupIds_Tags
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_VpcSecurityGroupIds_Tags
=== RUN   TestAccAWSDBInstance_MonitoringInterval
=== PAUSE TestAccAWSDBInstance_MonitoringInterval
=== RUN   TestAccAWSDBInstance_MonitoringRoleArn_EnabledToDisabled
=== PAUSE TestAccAWSDBInstance_MonitoringRoleArn_EnabledToDisabled
=== RUN   TestAccAWSDBInstance_MonitoringRoleArn_EnabledToRemoved
=== PAUSE TestAccAWSDBInstance_MonitoringRoleArn_EnabledToRemoved
=== RUN   TestAccAWSDBInstance_MonitoringRoleArn_RemovedToEnabled
=== PAUSE TestAccAWSDBInstance_MonitoringRoleArn_RemovedToEnabled
=== RUN   TestAccAWSDBInstance_separateIopsUpdate
=== PAUSE TestAccAWSDBInstance_separateIopsUpdate
=== RUN   TestAccAWSDBInstance_portUpdate
=== PAUSE TestAccAWSDBInstance_portUpdate
=== RUN   TestAccAWSDBInstance_MSSQL_TZ
=== PAUSE TestAccAWSDBInstance_MSSQL_TZ
=== RUN   TestAccAWSDBInstance_MSSQL_Domain
=== PAUSE TestAccAWSDBInstance_MSSQL_Domain
=== RUN   TestAccAWSDBInstance_MSSQL_DomainSnapshotRestore
=== PAUSE TestAccAWSDBInstance_MSSQL_DomainSnapshotRestore
=== RUN   TestAccAWSDBInstance_MySQL_SnapshotRestoreWithEngineVersion
=== PAUSE TestAccAWSDBInstance_MySQL_SnapshotRestoreWithEngineVersion
=== RUN   TestAccAWSDBInstance_MinorVersion
=== PAUSE TestAccAWSDBInstance_MinorVersion
=== RUN   TestAccAWSDBInstance_ec2Classic
=== PAUSE TestAccAWSDBInstance_ec2Classic
=== RUN   TestAccAWSDBInstance_cloudwatchLogsExportConfiguration
=== PAUSE TestAccAWSDBInstance_cloudwatchLogsExportConfiguration
=== RUN   TestAccAWSDBInstance_EnabledCloudwatchLogsExports_MySQL
=== PAUSE TestAccAWSDBInstance_EnabledCloudwatchLogsExports_MySQL
=== RUN   TestAccAWSDBInstance_EnabledCloudwatchLogsExports_MSSQL
=== PAUSE TestAccAWSDBInstance_EnabledCloudwatchLogsExports_MSSQL
=== RUN   TestAccAWSDBInstance_EnabledCloudwatchLogsExports_Oracle
=== PAUSE TestAccAWSDBInstance_EnabledCloudwatchLogsExports_Oracle
=== RUN   TestAccAWSDBInstance_EnabledCloudwatchLogsExports_Postgresql
=== PAUSE TestAccAWSDBInstance_EnabledCloudwatchLogsExports_Postgresql
=== RUN   TestAccAWSDBInstance_NoDeleteAutomatedBackups
=== PAUSE TestAccAWSDBInstance_NoDeleteAutomatedBackups
=== RUN   TestAccAWSDBInstance_PerformanceInsightsEnabled_DisabledToEnabled
=== PAUSE TestAccAWSDBInstance_PerformanceInsightsEnabled_DisabledToEnabled
=== RUN   TestAccAWSDBInstance_PerformanceInsightsEnabled_EnabledToDisabled
=== PAUSE TestAccAWSDBInstance_PerformanceInsightsEnabled_EnabledToDisabled
=== RUN   TestAccAWSDBInstance_PerformanceInsightsKmsKeyId
=== PAUSE TestAccAWSDBInstance_PerformanceInsightsKmsKeyId
=== RUN   TestAccAWSDBInstance_PerformanceInsightsRetentionPeriod
=== PAUSE TestAccAWSDBInstance_PerformanceInsightsRetentionPeriod
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_PerformanceInsightsEnabled
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_PerformanceInsightsEnabled
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_PerformanceInsightsEnabled
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_PerformanceInsightsEnabled
=== RUN   TestAccAWSDBInstance_CACertificateIdentifier
=== PAUSE TestAccAWSDBInstance_CACertificateIdentifier
=== RUN   TestAccAWSDBInstance_RestoreToPointInTime_SourceIdentifier
=== PAUSE TestAccAWSDBInstance_RestoreToPointInTime_SourceIdentifier
=== RUN   TestAccAWSDBInstance_RestoreToPointInTime_SourceResourceID
=== PAUSE TestAccAWSDBInstance_RestoreToPointInTime_SourceResourceID
=== CONT  TestAccAWSDBInstance_basic
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_BackupRetentionPeriod_Unset
=== CONT  TestAccAWSDBInstance_MSSQL_TZ
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_BackupRetentionPeriod
=== CONT  TestAccAWSDBInstance_portUpdate
=== CONT  TestAccAWSDBInstance_separateIopsUpdate
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_BackupRetentionPeriod
=== CONT  TestAccAWSDBInstance_MonitoringRoleArn_RemovedToEnabled
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_AvailabilityZone
=== CONT  TestAccAWSDBInstance_MonitoringRoleArn_EnabledToRemoved
=== CONT  TestAccAWSDBInstance_MonitoringRoleArn_EnabledToDisabled
=== CONT  TestAccAWSDBInstance_MonitoringInterval
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_AutoMinorVersionUpgrade
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_VpcSecurityGroupIds_Tags
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_AllowMajorVersionUpgrade
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_VpcSecurityGroupIds
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_Io1Storage
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_MaintenanceWindow
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_AllocatedStorage
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_IamDatabaseAuthenticationEnabled
--- PASS: TestAccAWSDBInstance_portUpdate (519.28s)
=== CONT  TestAccAWSDBInstance_SnapshotIdentifierRemoved
--- PASS: TestAccAWSDBInstance_basic (570.76s)
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_DeletionProtection
--- PASS: TestAccAWSDBInstance_separateIopsUpdate (765.17s)
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_DbSubnetGroupName_VpcSecurityGroupIds
--- PASS: TestAccAWSDBInstance_MonitoringRoleArn_RemovedToEnabled (789.29s)
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier
--- PASS: TestAccAWSDBInstance_MonitoringRoleArn_EnabledToRemoved (846.10s)
=== CONT  TestAccAWSDBInstance_S3Import
--- PASS: TestAccAWSDBInstance_MonitoringRoleArn_EnabledToDisabled (915.78s)
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_MaxAllocatedStorage
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_VpcSecurityGroupIds (1006.38s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_CACertificateIdentifier
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_AvailabilityZone (1149.08s)
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_DbSubnetGroupName
--- PASS: TestAccAWSDBInstance_MonitoringInterval (1155.88s)
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_BackupWindow
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_MaintenanceWindow (1189.88s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_VpcSecurityGroupIds
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_AutoMinorVersionUpgrade (1190.10s)
=== CONT  TestAccAWSDBInstance_NoDeleteAutomatedBackups
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_VpcSecurityGroupIds_Tags (1200.16s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_Port
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_IamDatabaseAuthenticationEnabled (1343.55s)
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_Tags
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_BackupRetentionPeriod (1384.57s)
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_Port
--- PASS: TestAccAWSDBInstance_MSSQL_TZ (1531.05s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_ParameterGroupName
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_Io1Storage (1548.31s)
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_ParameterGroupName
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_BackupRetentionPeriod_Unset (1568.69s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_MultiAZ
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_AllocatedStorage (1630.31s)
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_MultiAZ_SQLServer
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_DeletionProtection (1088.35s)
=== CONT  TestAccAWSDBInstance_RestoreToPointInTime_SourceResourceID
--- FAIL: TestAccAWSDBInstance_S3Import (834.80s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_Monitoring
--- PASS: TestAccAWSDBInstance_SnapshotIdentifierRemoved (1242.46s)
=== CONT  TestAccAWSDBInstance_RestoreToPointInTime_SourceIdentifier
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier (978.38s)
=== CONT  TestAccAWSDBInstance_CACertificateIdentifier
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_BackupRetentionPeriod (1814.42s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_MaxAllocatedStorage
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_DbSubnetGroupName_VpcSecurityGroupIds (1063.19s)
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_MultiAZ
--- PASS: TestAccAWSDBInstance_NoDeleteAutomatedBackups (726.90s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_MaintenanceWindow
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_MaxAllocatedStorage (1169.81s)
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_Monitoring
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_DbSubnetGroupName (979.08s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_IamDatabaseAuthenticationEnabled
--- PASS: TestAccAWSDBInstance_CACertificateIdentifier (400.90s)
=== CONT  TestAccAWSDBInstance_PerformanceInsightsKmsKeyId
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_BackupWindow (1036.49s)
=== CONT  TestAccAWSDBInstance_cloudwatchLogsExportConfiguration
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_Port (1099.66s)
=== CONT  TestAccAWSDBInstance_EnabledCloudwatchLogsExports_Postgresql
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_Tags (1150.87s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_DbSubnetGroupName_VpcSecurityGroupIds
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_VpcSecurityGroupIds (1314.83s)
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_PerformanceInsightsEnabled
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_Port (1365.81s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_PerformanceInsightsEnabled
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_CACertificateIdentifier (1582.43s)
=== CONT  TestAccAWSDBInstance_PerformanceInsightsRetentionPeriod
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_AllowMajorVersionUpgrade (2609.36s)
=== CONT  TestAccAWSDBInstance_EnabledCloudwatchLogsExports_MSSQL
--- PASS: TestAccAWSDBInstance_cloudwatchLogsExportConfiguration (439.70s)
=== CONT  TestAccAWSDBInstance_PerformanceInsightsEnabled_EnabledToDisabled
--- PASS: TestAccAWSDBInstance_RestoreToPointInTime_SourceResourceID (1280.13s)
=== CONT  TestAccAWSDBInstance_PerformanceInsightsEnabled_DisabledToEnabled
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_ParameterGroupName (1440.51s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_DbSubnetGroupName
--- PASS: TestAccAWSDBInstance_EnabledCloudwatchLogsExports_Postgresql (535.76s)
=== CONT  TestAccAWSDBInstance_DeletionProtection
--- PASS: TestAccAWSDBInstance_RestoreToPointInTime_SourceIdentifier (1302.52s)
=== CONT  TestAccAWSDBInstance_EnabledCloudwatchLogsExports_MySQL
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_ParameterGroupName (1541.07s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_Monitoring (1138.60s)
=== CONT  TestAccAWSDBInstance_Password
--- PASS: TestAccAWSDBInstance_PerformanceInsightsKmsKeyId (1117.29s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_AllowMajorVersionUpgrade
--- PASS: TestAccAWSDBInstance_EnabledCloudwatchLogsExports_MSSQL (728.02s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_BackupWindow
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_MaxAllocatedStorage (1583.12s)
=== CONT  TestAccAWSDBInstance_MaxAllocatedStorage
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_MaintenanceWindow (1481.85s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_AllocatedStorage
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_Monitoring (1767.81s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_AvailabilityZone
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_IamDatabaseAuthenticationEnabled (1351.34s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_AutoMinorVersionUpgrade
--- PASS: TestAccAWSDBInstance_DeletionProtection (522.48s)
=== CONT  TestAccAWSDBInstance_FinalSnapshotIdentifier_SkipFinalSnapshot
--- PASS: TestAccAWSDBInstance_PerformanceInsightsEnabled_EnabledToDisabled (913.95s)
=== CONT  TestAccAWSDBInstance_optionGroup
--- PASS: TestAccAWSDBInstance_PerformanceInsightsRetentionPeriod (955.23s)
=== CONT  TestAccAWSDBInstance_IsAlreadyBeingDeleted
--- PASS: TestAccAWSDBInstance_Password (454.93s)
=== CONT  TestAccAWSDBInstance_generatedName
--- PASS: TestAccAWSDBInstance_PerformanceInsightsEnabled_DisabledToEnabled (740.13s)
=== CONT  TestAccAWSDBInstance_FinalSnapshotIdentifier
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_MultiAZ (2261.68s)
=== CONT  TestAccAWSDBInstance_DbSubnetGroupName_VpcSecurityGroupIds
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_MultiAZ (2073.34s)
=== CONT  TestAccAWSDBInstance_subnetGroup
--- PASS: TestAccAWSDBInstance_MaxAllocatedStorage (605.38s)
=== CONT  TestAccAWSDBInstance_DbSubnetGroupName
--- PASS: TestAccAWSDBInstance_EnabledCloudwatchLogsExports_MySQL (941.53s)
=== CONT  TestAccAWSDBInstance_kmsKey
--- PASS: TestAccAWSDBInstance_generatedName (353.89s)
=== CONT  TestAccAWSDBInstance_DbSubnetGroupName_RamShared
    provider_test.go:714: skipping test because at least one environment variable of [AWS_ALTERNATE_PROFILE AWS_ALTERNATE_ACCESS_KEY_ID] must be set. Usage: credentials for running acceptance testing in alternate AWS account.
--- SKIP: TestAccAWSDBInstance_DbSubnetGroupName_RamShared (0.03s)
=== CONT  TestAccAWSDBInstance_iamAuth
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_PerformanceInsightsEnabled (1540.24s)
=== CONT  TestAccAWSDBInstance_MySQL_SnapshotRestoreWithEngineVersion
--- PASS: TestAccAWSDBInstance_IsAlreadyBeingDeleted (506.65s)
=== CONT  TestAccAWSDBInstance_ec2Classic
--- PASS: TestAccAWSDBInstance_FinalSnapshotIdentifier_SkipFinalSnapshot (542.99s)
=== CONT  TestAccAWSDBInstance_MinorVersion
--- PASS: TestAccAWSDBInstance_optionGroup (580.45s)
=== CONT  TestAccAWSDBInstance_AllowMajorVersionUpgrade
--- PASS: TestAccAWSDBInstance_DbSubnetGroupName_VpcSecurityGroupIds (433.43s)
=== CONT  TestAccAWSDBInstance_OnlyMajorVersion
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb (1279.71s)
=== CONT  TestAccAWSDBInstance_MSSQL_DomainSnapshotRestore
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_PerformanceInsightsEnabled (1797.03s)
=== CONT  TestAccAWSDBInstance_MSSQL_Domain
--- PASS: TestAccAWSDBInstance_kmsKey (449.81s)
=== CONT  TestAccAWSDBInstance_namePrefix
--- PASS: TestAccAWSDBInstance_DbSubnetGroupName (475.30s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_DbSubnetGroupName_VpcSecurityGroupIds (2007.06s)
--- PASS: TestAccAWSDBInstance_iamAuth (477.58s)
--- PASS: TestAccAWSDBInstance_ec2Classic (472.63s)
--- PASS: TestAccAWSDBInstance_FinalSnapshotIdentifier (857.17s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_AllowMajorVersionUpgrade (1292.43s)
--- PASS: TestAccAWSDBInstance_AllowMajorVersionUpgrade (503.83s)
--- PASS: TestAccAWSDBInstance_MinorVersion (558.44s)
--- PASS: TestAccAWSDBInstance_OnlyMajorVersion (437.40s)
--- PASS: TestAccAWSDBInstance_subnetGroup (947.41s)
--- PASS: TestAccAWSDBInstance_namePrefix (448.26s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_AutoMinorVersionUpgrade (1440.46s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_DbSubnetGroupName (1947.30s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_AvailabilityZone (1499.04s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_BackupWindow (1649.98s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_AllocatedStorage (1846.34s)
--- PASS: TestAccAWSDBInstance_MySQL_SnapshotRestoreWithEngineVersion (2018.54s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_MultiAZ_SQLServer (4779.57s)
<Removed skips and known failures>
```

### CODE REVIEW

File: aws/resource_aws_db_instance_test.go [hunk 1]
```diff
@@ -3337,6 +3370,28 @@ resource "aws_db_instance" "bar" {
 `)
 }
 
+func testAccAWSDBInstanceConfig_MajorVersionOnly(engine, engineVersion string) string {
+	return composeConfig(testAccAWSDBInstanceConfig_orderableClassMysql(), fmt.Sprintf(`
+resource "aws_db_instance" "test" {
+  allocated_storage       = 10
+  backup_retention_period = 0
+  engine                  = %[1]q
```
Comment (ewbankkit) [inline aws/resource_aws_db_instance_test.go:3378]: This (and the equivalent in `aws_rds_cluster`) is causing **tflint** to complain: https://github.com/terraform-linters/tflint-ruleset-aws/blob/v0.4.0/docs/rules/aws_db_instance_invalid_engine.md.
Maybe try using an intermediate HCL local?

```hcl
locals {
  engine = %[1]q
}

resource "aws_db_instance" "test" {
  engine = local.engine
}
```

Comment (bill-rich) [reply aws/resource_aws_db_instance_test.go]: Good call. Thank you.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% ACCTEST_TIMEOUT=600m ACCTEST_PARALLELISM=10 make testacc TESTARGS='-run=TestAccAWSDBInstance_' 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 10 -run=TestAccAWSDBInstance_ -timeout 600m
=== RUN   TestAccAWSDBInstance_basic
=== PAUSE TestAccAWSDBInstance_basic
=== RUN   TestAccAWSDBInstance_OnlyMajorVersion
=== PAUSE TestAccAWSDBInstance_OnlyMajorVersion
=== RUN   TestAccAWSDBInstance_namePrefix
=== PAUSE TestAccAWSDBInstance_namePrefix
=== RUN   TestAccAWSDBInstance_generatedName
=== PAUSE TestAccAWSDBInstance_generatedName
=== RUN   TestAccAWSDBInstance_kmsKey
=== PAUSE TestAccAWSDBInstance_kmsKey
=== RUN   TestAccAWSDBInstance_subnetGroup
=== PAUSE TestAccAWSDBInstance_subnetGroup
=== RUN   TestAccAWSDBInstance_optionGroup
=== PAUSE TestAccAWSDBInstance_optionGroup
=== RUN   TestAccAWSDBInstance_iamAuth
=== PAUSE TestAccAWSDBInstance_iamAuth
=== RUN   TestAccAWSDBInstance_AllowMajorVersionUpgrade
=== PAUSE TestAccAWSDBInstance_AllowMajorVersionUpgrade
=== RUN   TestAccAWSDBInstance_DbSubnetGroupName
=== PAUSE TestAccAWSDBInstance_DbSubnetGroupName
=== RUN   TestAccAWSDBInstance_DbSubnetGroupName_RamShared
=== PAUSE TestAccAWSDBInstance_DbSubnetGroupName_RamShared
=== RUN   TestAccAWSDBInstance_DbSubnetGroupName_VpcSecurityGroupIds
=== PAUSE TestAccAWSDBInstance_DbSubnetGroupName_VpcSecurityGroupIds
=== RUN   TestAccAWSDBInstance_DeletionProtection
=== PAUSE TestAccAWSDBInstance_DeletionProtection
=== RUN   TestAccAWSDBInstance_FinalSnapshotIdentifier
=== PAUSE TestAccAWSDBInstance_FinalSnapshotIdentifier
=== RUN   TestAccAWSDBInstance_FinalSnapshotIdentifier_SkipFinalSnapshot
=== PAUSE TestAccAWSDBInstance_FinalSnapshotIdentifier_SkipFinalSnapshot
=== RUN   TestAccAWSDBInstance_IsAlreadyBeingDeleted
=== PAUSE TestAccAWSDBInstance_IsAlreadyBeingDeleted
=== RUN   TestAccAWSDBInstance_MaxAllocatedStorage
=== PAUSE TestAccAWSDBInstance_MaxAllocatedStorage
=== RUN   TestAccAWSDBInstance_Password
=== PAUSE TestAccAWSDBInstance_Password
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_AllocatedStorage
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_AllocatedStorage
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_Iops
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_Iops
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_AllocatedStorageAndIops
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_AllocatedStorageAndIops
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_AllowMajorVersionUpgrade
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_AllowMajorVersionUpgrade
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_AutoMinorVersionUpgrade
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_AutoMinorVersionUpgrade
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_AvailabilityZone
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_AvailabilityZone
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_BackupRetentionPeriod
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_BackupRetentionPeriod
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_BackupWindow
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_BackupWindow
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_DbSubnetGroupName
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_DbSubnetGroupName
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_DbSubnetGroupName_RamShared
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_DbSubnetGroupName_RamShared
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_DbSubnetGroupName_VpcSecurityGroupIds
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_DbSubnetGroupName_VpcSecurityGroupIds
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_DeletionProtection
    provider_test.go:58: CreateDBInstanceReadReplica API currently ignores DeletionProtection=true with SourceDBInstanceIdentifier set
--- SKIP: TestAccAWSDBInstance_ReplicateSourceDb_DeletionProtection (0.00s)
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_IamDatabaseAuthenticationEnabled
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_IamDatabaseAuthenticationEnabled
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_MaintenanceWindow
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_MaintenanceWindow
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_MaxAllocatedStorage
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_MaxAllocatedStorage
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_Monitoring
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_Monitoring
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_MultiAZ
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_MultiAZ
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_ParameterGroupName
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_ParameterGroupName
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_Port
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_Port
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_VpcSecurityGroupIds
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_VpcSecurityGroupIds
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_CACertificateIdentifier
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_CACertificateIdentifier
=== RUN   TestAccAWSDBInstance_S3Import
=== PAUSE TestAccAWSDBInstance_S3Import
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier
=== RUN   TestAccAWSDBInstance_SnapshotIdentifierRemoved
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifierRemoved
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_AllocatedStorage
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_AllocatedStorage
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_Io1Storage
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_Io1Storage
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_AllowMajorVersionUpgrade
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_AllowMajorVersionUpgrade
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_AutoMinorVersionUpgrade
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_AutoMinorVersionUpgrade
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_AvailabilityZone
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_AvailabilityZone
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_BackupRetentionPeriod
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_BackupRetentionPeriod
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_BackupRetentionPeriod_Unset
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_BackupRetentionPeriod_Unset
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_BackupWindow
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_BackupWindow
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_DbSubnetGroupName
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_DbSubnetGroupName
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_DbSubnetGroupName_RamShared
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_DbSubnetGroupName_RamShared
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_DbSubnetGroupName_VpcSecurityGroupIds
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_DbSubnetGroupName_VpcSecurityGroupIds
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_DeletionProtection
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_DeletionProtection
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_IamDatabaseAuthenticationEnabled
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_IamDatabaseAuthenticationEnabled
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_MaintenanceWindow
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_MaintenanceWindow
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_MaxAllocatedStorage
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_MaxAllocatedStorage
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_Monitoring
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_Monitoring
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_MultiAZ
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_MultiAZ
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_MultiAZ_SQLServer
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_MultiAZ_SQLServer
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_ParameterGroupName
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_ParameterGroupName
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_Port
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_Port
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_Tags
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_Tags
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_Tags_Unset
    provider_test.go:58: To be fixed: https://github.com/hashicorp/terraform-provider-aws/issues/5959
--- SKIP: TestAccAWSDBInstance_SnapshotIdentifier_Tags_Unset (0.00s)
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_VpcSecurityGroupIds
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_VpcSecurityGroupIds
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_VpcSecurityGroupIds_Tags
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_VpcSecurityGroupIds_Tags
=== RUN   TestAccAWSDBInstance_MonitoringInterval
=== PAUSE TestAccAWSDBInstance_MonitoringInterval
=== RUN   TestAccAWSDBInstance_MonitoringRoleArn_EnabledToDisabled
=== PAUSE TestAccAWSDBInstance_MonitoringRoleArn_EnabledToDisabled
=== RUN   TestAccAWSDBInstance_MonitoringRoleArn_EnabledToRemoved
=== PAUSE TestAccAWSDBInstance_MonitoringRoleArn_EnabledToRemoved
=== RUN   TestAccAWSDBInstance_MonitoringRoleArn_RemovedToEnabled
=== PAUSE TestAccAWSDBInstance_MonitoringRoleArn_RemovedToEnabled
=== RUN   TestAccAWSDBInstance_separateIopsUpdate
=== PAUSE TestAccAWSDBInstance_separateIopsUpdate
=== RUN   TestAccAWSDBInstance_portUpdate
=== PAUSE TestAccAWSDBInstance_portUpdate
=== RUN   TestAccAWSDBInstance_MSSQL_TZ
=== PAUSE TestAccAWSDBInstance_MSSQL_TZ
=== RUN   TestAccAWSDBInstance_MSSQL_Domain
=== PAUSE TestAccAWSDBInstance_MSSQL_Domain
=== RUN   TestAccAWSDBInstance_MSSQL_DomainSnapshotRestore
=== PAUSE TestAccAWSDBInstance_MSSQL_DomainSnapshotRestore
=== RUN   TestAccAWSDBInstance_MySQL_SnapshotRestoreWithEngineVersion
=== PAUSE TestAccAWSDBInstance_MySQL_SnapshotRestoreWithEngineVersion
=== RUN   TestAccAWSDBInstance_MinorVersion
=== PAUSE TestAccAWSDBInstance_MinorVersion
=== RUN   TestAccAWSDBInstance_ec2Classic
=== PAUSE TestAccAWSDBInstance_ec2Classic
=== RUN   TestAccAWSDBInstance_cloudwatchLogsExportConfiguration
=== PAUSE TestAccAWSDBInstance_cloudwatchLogsExportConfiguration
=== RUN   TestAccAWSDBInstance_EnabledCloudwatchLogsExports_MySQL
=== PAUSE TestAccAWSDBInstance_EnabledCloudwatchLogsExports_MySQL
=== RUN   TestAccAWSDBInstance_EnabledCloudwatchLogsExports_MSSQL
=== PAUSE TestAccAWSDBInstance_EnabledCloudwatchLogsExports_MSSQL
=== RUN   TestAccAWSDBInstance_EnabledCloudwatchLogsExports_Oracle
=== PAUSE TestAccAWSDBInstance_EnabledCloudwatchLogsExports_Oracle
=== RUN   TestAccAWSDBInstance_EnabledCloudwatchLogsExports_Postgresql
=== PAUSE TestAccAWSDBInstance_EnabledCloudwatchLogsExports_Postgresql
=== RUN   TestAccAWSDBInstance_NoDeleteAutomatedBackups
=== PAUSE TestAccAWSDBInstance_NoDeleteAutomatedBackups
=== RUN   TestAccAWSDBInstance_PerformanceInsightsEnabled_DisabledToEnabled
=== PAUSE TestAccAWSDBInstance_PerformanceInsightsEnabled_DisabledToEnabled
=== RUN   TestAccAWSDBInstance_PerformanceInsightsEnabled_EnabledToDisabled
=== PAUSE TestAccAWSDBInstance_PerformanceInsightsEnabled_EnabledToDisabled
=== RUN   TestAccAWSDBInstance_PerformanceInsightsKmsKeyId
=== PAUSE TestAccAWSDBInstance_PerformanceInsightsKmsKeyId
=== RUN   TestAccAWSDBInstance_PerformanceInsightsRetentionPeriod
=== PAUSE TestAccAWSDBInstance_PerformanceInsightsRetentionPeriod
=== RUN   TestAccAWSDBInstance_ReplicateSourceDb_PerformanceInsightsEnabled
=== PAUSE TestAccAWSDBInstance_ReplicateSourceDb_PerformanceInsightsEnabled
=== RUN   TestAccAWSDBInstance_SnapshotIdentifier_PerformanceInsightsEnabled
=== PAUSE TestAccAWSDBInstance_SnapshotIdentifier_PerformanceInsightsEnabled
=== RUN   TestAccAWSDBInstance_CACertificateIdentifier
=== PAUSE TestAccAWSDBInstance_CACertificateIdentifier
=== RUN   TestAccAWSDBInstance_RestoreToPointInTime_SourceIdentifier
=== PAUSE TestAccAWSDBInstance_RestoreToPointInTime_SourceIdentifier
=== RUN   TestAccAWSDBInstance_RestoreToPointInTime_SourceResourceID
=== PAUSE TestAccAWSDBInstance_RestoreToPointInTime_SourceResourceID
=== CONT  TestAccAWSDBInstance_basic
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_BackupRetentionPeriod
=== CONT  TestAccAWSDBInstance_separateIopsUpdate
=== CONT  TestAccAWSDBInstance_RestoreToPointInTime_SourceResourceID
=== CONT  TestAccAWSDBInstance_portUpdate
=== CONT  TestAccAWSDBInstance_MonitoringRoleArn_RemovedToEnabled
=== CONT  TestAccAWSDBInstance_MonitoringRoleArn_EnabledToRemoved
=== CONT  TestAccAWSDBInstance_MonitoringRoleArn_EnabledToDisabled
=== CONT  TestAccAWSDBInstance_MonitoringInterval
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_VpcSecurityGroupIds_Tags
--- PASS: TestAccAWSDBInstance_basic (548.38s)
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_VpcSecurityGroupIds
--- PASS: TestAccAWSDBInstance_portUpdate (603.38s)
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_Tags
--- PASS: TestAccAWSDBInstance_MonitoringRoleArn_RemovedToEnabled (665.87s)
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_Port
--- PASS: TestAccAWSDBInstance_MonitoringRoleArn_EnabledToDisabled (698.28s)
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_ParameterGroupName
--- PASS: TestAccAWSDBInstance_separateIopsUpdate (777.21s)
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_MultiAZ_SQLServer
--- PASS: TestAccAWSDBInstance_MonitoringRoleArn_EnabledToRemoved (815.52s)
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_MultiAZ
--- PASS: TestAccAWSDBInstance_MonitoringInterval (1064.22s)
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_Monitoring
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_VpcSecurityGroupIds_Tags (1240.68s)
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_MaxAllocatedStorage
--- PASS: TestAccAWSDBInstance_RestoreToPointInTime_SourceResourceID (1307.12s)
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_MaintenanceWindow
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_BackupRetentionPeriod (1394.90s)
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_IamDatabaseAuthenticationEnabled
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_Tags (1153.54s)
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_DeletionProtection
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_Port (1191.81s)
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_DbSubnetGroupName_VpcSecurityGroupIds
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_VpcSecurityGroupIds (1309.47s)
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_DbSubnetGroupName_RamShared
    provider_test.go:715: skipping test because at least one environment variable of [AWS_ALTERNATE_PROFILE AWS_ALTERNATE_ACCESS_KEY_ID] must be set. Usage: credentials for running acceptance testing in alternate AWS account.
--- SKIP: TestAccAWSDBInstance_SnapshotIdentifier_DbSubnetGroupName_RamShared (0.04s)
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_DbSubnetGroupName
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_ParameterGroupName (1307.20s)
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_BackupWindow
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_Monitoring (1328.12s)
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_BackupRetentionPeriod_Unset
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_MaxAllocatedStorage (1152.62s)
=== CONT  TestAccAWSDBInstance_EnabledCloudwatchLogsExports_Postgresql
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_MaintenanceWindow (1197.25s)
=== CONT  TestAccAWSDBInstance_RestoreToPointInTime_SourceIdentifier
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_IamDatabaseAuthenticationEnabled (1130.06s)
=== CONT  TestAccAWSDBInstance_CACertificateIdentifier
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_MultiAZ_SQLServer
    resource_aws_db_instance_test.go:1830: Step 1/1 error: Check failed: Check 4/4 error: aws_db_instance.test: Attribute 'multi_az' expected "true", got "false"
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_MultiAZ (1997.02s)
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_PerformanceInsightsEnabled
--- PASS: TestAccAWSDBInstance_EnabledCloudwatchLogsExports_Postgresql (428.24s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_PerformanceInsightsEnabled
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_DbSubnetGroupName (1008.62s)
=== CONT  TestAccAWSDBInstance_PerformanceInsightsRetentionPeriod
--- PASS: TestAccAWSDBInstance_CACertificateIdentifier (446.00s)
=== CONT  TestAccAWSDBInstance_PerformanceInsightsKmsKeyId
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_DbSubnetGroupName_VpcSecurityGroupIds (1124.33s)
=== CONT  TestAccAWSDBInstance_PerformanceInsightsEnabled_EnabledToDisabled
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_DeletionProtection (1236.30s)
=== CONT  TestAccAWSDBInstance_PerformanceInsightsEnabled_DisabledToEnabled
--- FAIL: TestAccAWSDBInstance_SnapshotIdentifier_MultiAZ_SQLServer (2263.25s)
=== CONT  TestAccAWSDBInstance_NoDeleteAutomatedBackups
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_BackupWindow (1047.68s)
=== CONT  TestAccAWSDBInstance_ec2Classic
--- PASS: TestAccAWSDBInstance_ec2Classic (424.21s)
=== CONT  TestAccAWSDBInstance_EnabledCloudwatchLogsExports_Oracle
    resource_aws_db_instance_test.go:2556: Step 1/2 error: Error running pre-apply refresh: exit status 1
        
        Error: error reading RDS orderable DB instance options: InvalidParameterCombination: Cannot find version 11.2.0.4.v25 for oracle-se
        	status code: 400, request id: 0c6d7a28-dd60-4a11-9d6a-201f08790955
        
          with data.aws_rds_orderable_db_instance.test,
          on terraform_plugin_test.tf line 2, in data "aws_rds_orderable_db_instance" "test":
           2: data "aws_rds_orderable_db_instance" "test" {
        
--- FAIL: TestAccAWSDBInstance_EnabledCloudwatchLogsExports_Oracle (2.45s)
=== CONT  TestAccAWSDBInstance_EnabledCloudwatchLogsExports_MSSQL
--- PASS: TestAccAWSDBInstance_RestoreToPointInTime_SourceIdentifier (1282.52s)
=== CONT  TestAccAWSDBInstance_EnabledCloudwatchLogsExports_MySQL
--- PASS: TestAccAWSDBInstance_NoDeleteAutomatedBackups (761.06s)
=== CONT  TestAccAWSDBInstance_cloudwatchLogsExportConfiguration
--- PASS: TestAccAWSDBInstance_PerformanceInsightsEnabled_DisabledToEnabled (825.64s)
=== CONT  TestAccAWSDBInstance_MSSQL_DomainSnapshotRestore
--- PASS: TestAccAWSDBInstance_PerformanceInsightsRetentionPeriod (991.95s)
=== CONT  TestAccAWSDBInstance_MinorVersion
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_BackupRetentionPeriod_Unset (1620.37s)
=== CONT  TestAccAWSDBInstance_MySQL_SnapshotRestoreWithEngineVersion
--- PASS: TestAccAWSDBInstance_PerformanceInsightsKmsKeyId (1072.01s)
=== CONT  TestAccAWSDBInstance_MSSQL_Domain
--- PASS: TestAccAWSDBInstance_PerformanceInsightsEnabled_EnabledToDisabled (1074.65s)
=== CONT  TestAccAWSDBInstance_MSSQL_TZ
=== CONT  TestAccAWSDBInstance_EnabledCloudwatchLogsExports_MySQL
    resource_aws_db_instance_test.go:2470: Step 2/4 error: After applying this test step and performing a `terraform refresh`, the plan was not empty.
        stdout
        
        
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        
        Terraform will perform the following actions:
        
          # aws_db_instance.bar will be updated in-place
          ~ resource "aws_db_instance" "bar" {
              ~ enabled_cloudwatch_logs_exports       = [
                  + "general",
                    # (2 unchanged elements hidden)
                ]
                id                                    = "foobarbaz-test-terraform-2521903670497593162"
                name                                  = "baz"
                tags                                  = {}
                # (45 unchanged attributes hidden)
            }
        
        Plan: 0 to add, 1 to change, 0 to destroy.
--- PASS: TestAccAWSDBInstance_cloudwatchLogsExportConfiguration (462.98s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_AvailabilityZone
--- PASS: TestAccAWSDBInstance_MinorVersion (477.51s)
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_AvailabilityZone
--- FAIL: TestAccAWSDBInstance_EnabledCloudwatchLogsExports_MySQL (614.50s)
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_AutoMinorVersionUpgrade
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_PerformanceInsightsEnabled (1689.55s)
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_AllowMajorVersionUpgrade
--- PASS: TestAccAWSDBInstance_EnabledCloudwatchLogsExports_MSSQL (1047.89s)
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_Io1Storage
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_PerformanceInsightsEnabled (1707.44s)
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier_AllocatedStorage
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_AvailabilityZone (1033.73s)
=== CONT  TestAccAWSDBInstance_SnapshotIdentifierRemoved
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_AutoMinorVersionUpgrade (1188.44s)
=== CONT  TestAccAWSDBInstance_SnapshotIdentifier
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_AvailabilityZone (1462.41s)
=== CONT  TestAccAWSDBInstance_S3Import
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_AllocatedStorage (1484.40s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_CACertificateIdentifier
--- PASS: TestAccAWSDBInstance_MySQL_SnapshotRestoreWithEngineVersion (2128.17s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_VpcSecurityGroupIds
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_Io1Storage (1630.06s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_Port
=== CONT  TestAccAWSDBInstance_S3Import
    resource_aws_db_instance_test.go:1250: Step 1/1 error: Error running apply: exit status 1
        
        Error: unexpected state 'incompatible-restore', wanted target 'available, storage-optimization'. last error: %!s(<nil>)
        
          with aws_db_instance.s3,
          on terraform_plugin_test.tf line 124, in resource "aws_db_instance" "s3":
         124: resource "aws_db_instance" "s3" {
        
--- FAIL: TestAccAWSDBInstance_S3Import (895.50s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_ParameterGroupName
--- PASS: TestAccAWSDBInstance_MSSQL_TZ (2583.52s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_MultiAZ
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_AllowMajorVersionUpgrade (2141.63s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_Monitoring
--- PASS: TestAccAWSDBInstance_SnapshotIdentifierRemoved (1290.23s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_MaxAllocatedStorage
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier (1139.42s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_MaintenanceWindow
--- PASS: TestAccAWSDBInstance_MSSQL_DomainSnapshotRestore (3578.95s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_IamDatabaseAuthenticationEnabled
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_CACertificateIdentifier (1463.74s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_DbSubnetGroupName_VpcSecurityGroupIds
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_VpcSecurityGroupIds (1448.50s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_DbSubnetGroupName_RamShared
    provider_test.go:715: skipping test because at least one environment variable of [AWS_ALTERNATE_PROFILE AWS_ALTERNATE_ACCESS_KEY_ID] must be set. Usage: credentials for running acceptance testing in alternate AWS account.
--- SKIP: TestAccAWSDBInstance_ReplicateSourceDb_DbSubnetGroupName_RamShared (0.09s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_DbSubnetGroupName
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_Port (1558.98s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_BackupWindow
--- PASS: TestAccAWSDBInstance_MSSQL_Domain (3971.87s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_BackupRetentionPeriod
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_MaxAllocatedStorage (1433.63s)
=== CONT  TestAccAWSDBInstance_DeletionProtection
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_MaintenanceWindow (1385.06s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_AutoMinorVersionUpgrade
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_ParameterGroupName (1665.60s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_AllowMajorVersionUpgrade
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_Monitoring (1653.02s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_AllocatedStorageAndIops
--- PASS: TestAccAWSDBInstance_DeletionProtection (508.07s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_Iops
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_IamDatabaseAuthenticationEnabled (1392.03s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_AllocatedStorage
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_MultiAZ (2348.64s)
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_BackupWindow (1429.29s)
=== CONT  TestAccAWSDBInstance_Password
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_BackupRetentionPeriod (1426.16s)
=== CONT  TestAccAWSDBInstance_MaxAllocatedStorage
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_DbSubnetGroupName_VpcSecurityGroupIds (2047.75s)
=== CONT  TestAccAWSDBInstance_IsAlreadyBeingDeleted
=== CONT  TestAccAWSDBInstance_ReplicateSourceDb_AllocatedStorage
    resource_aws_db_instance_test.go:666: Step 1/1 error: Check failed: Check 4/4 error: aws_db_instance.test: Attribute 'allocated_storage' expected "10", got "5"
--- PASS: TestAccAWSDBInstance_Password (540.51s)
=== CONT  TestAccAWSDBInstance_FinalSnapshotIdentifier_SkipFinalSnapshot
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_AllowMajorVersionUpgrade (1404.29s)
=== CONT  TestAccAWSDBInstance_FinalSnapshotIdentifier
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_AutoMinorVersionUpgrade (1580.71s)
=== CONT  TestAccAWSDBInstance_optionGroup
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_DbSubnetGroupName (2154.57s)
=== CONT  TestAccAWSDBInstance_DbSubnetGroupName_VpcSecurityGroupIds
--- PASS: TestAccAWSDBInstance_IsAlreadyBeingDeleted (499.05s)
=== CONT  TestAccAWSDBInstance_DbSubnetGroupName_RamShared
    provider_test.go:715: skipping test because at least one environment variable of [AWS_ALTERNATE_PROFILE AWS_ALTERNATE_ACCESS_KEY_ID] must be set. Usage: credentials for running acceptance testing in alternate AWS account.
--- SKIP: TestAccAWSDBInstance_DbSubnetGroupName_RamShared (0.04s)
=== CONT  TestAccAWSDBInstance_DbSubnetGroupName
--- FAIL: TestAccAWSDBInstance_ReplicateSourceDb_AllocatedStorage (1251.79s)
=== CONT  TestAccAWSDBInstance_AllowMajorVersionUpgrade
--- PASS: TestAccAWSDBInstance_MaxAllocatedStorage (607.16s)
=== CONT  TestAccAWSDBInstance_iamAuth
--- PASS: TestAccAWSDBInstance_DbSubnetGroupName_VpcSecurityGroupIds (473.49s)
=== CONT  TestAccAWSDBInstance_namePrefix
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_AllocatedStorageAndIops (1925.76s)
=== CONT  TestAccAWSDBInstance_subnetGroup
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb (1268.04s)
=== CONT  TestAccAWSDBInstance_OnlyMajorVersion
--- PASS: TestAccAWSDBInstance_optionGroup (578.18s)
=== CONT  TestAccAWSDBInstance_kmsKey
--- PASS: TestAccAWSDBInstance_FinalSnapshotIdentifier_SkipFinalSnapshot (762.05s)
=== CONT  TestAccAWSDBInstance_generatedName
--- PASS: TestAccAWSDBInstance_DbSubnetGroupName (453.06s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_Iops (1897.27s)
--- PASS: TestAccAWSDBInstance_AllowMajorVersionUpgrade (466.72s)
--- PASS: TestAccAWSDBInstance_iamAuth (473.16s)
--- PASS: TestAccAWSDBInstance_FinalSnapshotIdentifier (848.90s)
--- PASS: TestAccAWSDBInstance_OnlyMajorVersion (320.89s)
--- PASS: TestAccAWSDBInstance_namePrefix (435.41s)
--- PASS: TestAccAWSDBInstance_kmsKey (464.54s)
--- PASS: TestAccAWSDBInstance_generatedName (466.91s)
--- PASS: TestAccAWSDBInstance_subnetGroup (971.20s)
```

**Comment by tdmalone** [comment]
Hi @bill-rich,

We're seeing new diffs on plans since the latest release which might be caused by this PR. Was this an expected result? (These instances have not had recent upgrades or other changes).

Should we now be `ignoring_changes` for `engine_version`?

```
build	13-Aug-2021 00:47:26	  # module.co_db.aws_db_instance.main[0] will be updated in-place
build	13-Aug-2021 00:47:26	  ~ resource "aws_db_instance" "main"
build	13-Aug-2021 00:47:26	      + allow_major_version_upgrade           = false
build	13-Aug-2021 00:47:26	      ~ engine_version                        = "5.7.33" -> "5.7"
build	13-Aug-2021 00:47:26	
build	13-Aug-2021 00:47:26	  # module.jc_db.aws_db_instance.main[0] will be updated in-place
build	13-Aug-2021 00:47:26	  ~ resource "aws_db_instance" "main"
build	13-Aug-2021 00:47:26	      ~ engine_version                        = "5.6.51" -> "5.6"
build	13-Aug-2021 00:47:26	
build	13-Aug-2021 00:47:26	  # module.web_db.aws_db_instance.main[0] will be updated in-place
build	13-Aug-2021 00:47:26	  ~ resource "aws_db_instance" "main"
build	13-Aug-2021 00:47:26	      + allow_major_version_upgrade           = false
build	13-Aug-2021 00:47:26	      ~ engine_version                        = "8.0.23" -> "8.0"
build	13-Aug-2021 00:47:26	
build	13-Aug-2021 00:47:26	Plan: 0 to add, 3 to change, 0 to destroy.
```

**Comment by jamiepedwards** [comment]
We are also seeing the same behaviour as @tdmalone - we have had to pin our provider version to hold it back from using v3.54.0 as we don't know what's going to happen if we apply and don't want our RDS instances to be destroyed and recreated accidentally.

**Comment by pmason56** [comment]
We are also experiencing the same issue, if this is expected please can a suitable alternative be provided for this please?
