### PR TITLE
lb_target_group: Allow invalid stickiness config, avoid breaking change

### LINKED ISSUE #15603: Stickiness support for source_ip broke valid configurations for NLB
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

0.13.1
3.10

### Affected Resource(s)

* aws_lb_target_group

### Terraform Configuration Files

Before this was merged, I used blocks like 

```
  stickiness {
    type    = "lb_cookie"
    enabled = false
  }
```

because due to a previous bug in order to disable stickiness you had to set `lb_cookie` as your type, even though it wasn't appropriate for the NLB (was the only available one), because the config otherwise complained that `type` was not set, even though the only desired effect was to disable stickiness.

These configurations worked fine up to 3.10 where they fail with `InvalidConfigurationRequest: Stickiness type 'lb_cookie' is not supported for target groups with the TCP protocol`, even though enabled is (still) set to `false`. I think it shouldn't complain about the stickiness type when enabled is set to `false`. 

### Expected Behavior

When stickiness block is configured as `enabled = false` it doesn't complain about the type of stickiness.

### Actual Behavior

Terraform fails with `Stickiness type 'lb_cookie' is not supported for target groups with the TCP protocol`

### Steps to Reproduce

Add this block

```
  stickiness {
    type    = "lb_cookie"
    enabled = false
  }
```

to a NLB target group.

### References

* https://github.com/terraform-providers/terraform-provider-aws/pull/15295

### PR DESCRIPTION
**Pull request by YakDriver**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #15603

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
Allow invalid configurations that were allowed prior to 3.10.
```

The output from acceptance testing (GovCloud):

```
--- PASS: TestAccAWSLBTargetGroup_generatedName (40.86s)
--- PASS: TestAccAWSLBTargetGroup_namePrefix (40.99s)
--- PASS: TestAccAWSLBTargetGroup_stickinessDefaultALB (41.03s)
--- PASS: TestAccAWSLBTargetGroup_enableHealthCheck (48.48s)
--- PASS: TestAccAWSLBTargetGroup_BackwardsCompatibility (49.34s)
--- PASS: TestAccAWSLBTargetGroup_defaults_network (50.62s)
--- PASS: TestAccAWSLBTargetGroup_defaults_application (59.21s)
--- PASS: TestAccAWSLBTargetGroup_withoutHealthcheck (23.52s)
--- PASS: TestAccAWSLBTargetGroup_Protocol_Tls (32.28s)
--- PASS: TestAccAWSLBTargetGroup_stickinessValidALB (77.30s)
--- PASS: TestAccAWSLBTargetGroup_networkLB_TargetGroupWithProxy (82.51s)
--- PASS: TestAccAWSLBTargetGroup_TCP_HTTPHealthCheck (83.38s)
--- PASS: TestAccAWSLBTargetGroup_changePortForceNew (84.64s)
--- PASS: TestAccAWSLBTargetGroupAttachment_lambda (44.47s)
--- PASS: TestAccAWSLBTargetGroup_changeVpcForceNew (87.52s)
--- PASS: TestAccAWSLBTargetGroup_basicUdp (38.22s)
--- PASS: TestAccAWSLBTargetGroup_changeProtocolForceNew (88.25s)
--- PASS: TestAccAWSLBTargetGroup_basic (39.35s)
--- PASS: TestAccAWSLBTargetGroup_changeNameForceNew (92.62s)
--- PASS: TestAccAWSLBTargetGroup_updateHealthCheck (96.76s)
--- PASS: TestAccAWSLBTargetGroupAttachment_basic (98.01s)
--- PASS: TestAccAWSLBTargetGroup_Protocol_Tcp_HealthCheck_Protocol (74.99s)
--- PASS: TestAccAWSLBTargetGroup_updateSticknessEnabled (118.41s)
--- PASS: TestAccAWSLBTargetGroup_tags (121.59s)
--- PASS: TestAccAWSLBTargetGroup_stickinessInvalidNLB (40.67s)
--- PASS: TestAccAWSLBTargetGroup_networkLB_TargetGroup (133.30s)
--- PASS: TestAccAWSLBTargetGroup_stickinessInvalidALB (59.85s)
--- PASS: TestAccAWSLBTargetGroupAttachment_Port (93.30s)
--- PASS: TestAccAWSLBTargetGroupAttachment_ipAddress (94.36s)
--- PASS: TestAccAWSLBTargetGroupAttachment_BackwardsCompatibility (93.26s)
--- PASS: TestAccAWSLBTargetGroup_stickinessValidNLB (168.99s)
--- PASS: TestAccAWSLBTargetGroupAttachment_disappears (93.33s)
--- PASS: TestAccAWSLBTargetGroup_stickinessDefaultNLB (97.18s)
```

The output from acceptance testing (commercial):

```
--- PASS: TestAccAWSLBTargetGroup_generatedName (36.09s)
--- PASS: TestAccAWSLBTargetGroup_stickinessDefaultALB (36.13s)
--- PASS: TestAccAWSLBTargetGroup_enableHealthCheck (37.18s)
--- PASS: TestAccAWSLBTargetGroup_defaults_application (37.36s)
--- PASS: TestAccAWSLBTargetGroup_stickinessInvalidNLB (41.56s)
--- PASS: TestAccAWSLBTargetGroup_defaults_network (47.30s)
--- PASS: TestAccAWSLBTargetGroup_stickinessInvalidALB (60.50s)
--- PASS: TestAccAWSLBTargetGroup_Protocol_Tls (27.15s)
--- PASS: TestAccAWSLBTargetGroup_stickinessValidALB (64.99s)
--- PASS: TestAccAWSLBTargetGroup_BackwardsCompatibility (32.51s)
--- PASS: TestAccAWSLBTargetGroup_namePrefix (32.99s)
--- PASS: TestAccAWSLBTargetGroup_updateHealthCheck (71.33s)
--- PASS: TestAccAWSLBTargetGroup_changeVpcForceNew (71.82s)
--- PASS: TestAccAWSLBTargetGroup_changePortForceNew (73.20s)
--- PASS: TestAccAWSLBTargetGroup_TCP_HTTPHealthCheck (74.78s)
--- PASS: TestAccAWSLBTargetGroup_withoutHealthcheck (19.19s)
--- PASS: TestAccAWSLBTargetGroup_changeNameForceNew (81.91s)
--- PASS: TestAccAWSLBTargetGroupAttachment_lambda (36.98s)
--- PASS: TestAccAWSLBTargetGroup_changeProtocolForceNew (86.84s)
--- PASS: TestAccAWSLBTargetGroup_updateSticknessEnabled (93.53s)
--- PASS: TestAccAWSLBTargetGroup_stickinessDefaultNLB (95.29s)
--- PASS: TestAccAWSLBTargetGroup_basic (31.70s)
--- PASS: TestAccAWSLBTargetGroup_basicUdp (33.60s)
--- PASS: TestAccAWSLBTargetGroup_networkLB_TargetGroupWithProxy (62.11s)
--- PASS: TestAccAWSLBTargetGroup_tags (99.93s)
--- PASS: TestAccAWSLBTargetGroup_Protocol_Tcp_HealthCheck_Protocol (66.00s)
--- PASS: TestAccAWSLBTargetGroup_networkLB_TargetGroup (126.24s)
--- PASS: TestAccAWSLBTargetGroup_stickinessValidNLB (145.36s)
--- PASS: TestAccAWSLBTargetGroupAttachment_Port (89.55s)
--- PASS: TestAccAWSLBTargetGroupAttachment_BackwardsCompatibility (89.05s)
--- PASS: TestAccAWSLBTargetGroupAttachment_disappears (98.74s)
--- PASS: TestAccAWSLBTargetGroupAttachment_ipAddress (110.10s)
--- PASS: TestAccAWSLBTargetGroupAttachment_basic (219.84s)
```

### CODE REVIEW

**Comment by YakDriver** [comment]
Potentially helpful notes for this resource that I'll leave here:

```
ALB = HTTP, HTTPS
deregistration_delay.timeout_seconds
stickiness.enabled
stickiness.type = lb_cookie
load_balancing.algorithm.type
slow_start.duration_seconds
stickiness.lb_cookie.duration_seconds

NLB = TCP, UDP, TCP_UDP
deregistration_delay.timeout_seconds
stickiness.enabled
stickiness.type = source_ip
proxy_protocol_v2.enabled

NLB = TLS
deregistration_delay.timeout_seconds
stickiness.enabled = false
stickiness.type = source_ip
proxy_protocol_v2.enabled
```

File: aws/resource_aws_lb_target_group.go [hunk 1]
```diff
@@ -152,6 +152,16 @@ func resourceAwsLbTargetGroup() *schema.Resource {
...
+							DiffSuppressFunc: func(k, old, new string, d *schema.ResourceData) bool {
+								switch d.Get("protocol").(string) {
+								case elbv2.ProtocolEnumTcp, elbv2.ProtocolEnumUdp, elbv2.ProtocolEnumTcpUdp, elbv2.ProtocolEnumTls:
+									if new == "lb_cookie" && !d.Get("stickiness.0.enabled").(bool) {
+										log.Printf("[WARN] invalid configuration, this will fail in a future version: stickiness enabled %v, protocol %s, type %s", d.Get("stickiness.0.enabled").(bool), d.Get("protocol").(string), new)
+										return true
+									}
+								}
+								return false
+							},
```
Comment (gdavison) [inline aws/resource_aws_lb_target_group.go:164]: This would be a great place to use `ValidateDiagFunc` instead of combining `ValidateFunc` and `DiffSuppressFunc`, since it can also return warnings. It also doesn't require the practitioner to enable logging in Terraform

File: aws/resource_aws_lb_target_group.go [hunk 2]
```diff
@@ -447,23 +457,27 @@ func resourceAwsLbTargetGroupUpdate(d *schema.ResourceData, meta interface{}) er
...
+							Key:   aws.String("stickiness.enabled"),
+							Value: aws.String(strconv.FormatBool(stickiness["enabled"].(bool))),
+						},
+						&elbv2.TargetGroupAttribute{
+							Key:   aws.String("stickiness.type"),
+							Value: aws.String(stickiness["type"].(string)),
 						})
+
+					switch d.Get("protocol").(string) {
+					case elbv2.ProtocolEnumHttp, elbv2.ProtocolEnumHttps:
```
Comment (gdavison) [inline aws/resource_aws_lb_target_group.go:474]: Since we only have one option, would it make sense to use an `if` statement instead of `switch`?

**Review by gdavison — APPROVED** [review]
A couple comments, but otherwise LGTM 🚀 

--- PASS: TestLBTargetGroupCloudwatchSuffixFromARN (0.00s)
--- PASS: TestAccAWSLBTargetGroup_Protocol_Tls (33.32s)
--- PASS: TestAccAWSLBTargetGroup_basicUdp (34.15s)
--- PASS: TestAccAWSLBTargetGroup_withoutHealthcheck (34.48s)
--- PASS: TestAccAWSLBTargetGroup_BackwardsCompatibility (49.61s)
--- PASS: TestAccAWSLBTargetGroup_namePrefix (51.07s)
--- PASS: TestAccAWSLBTargetGroup_basic (61.68s)
--- PASS: TestAccAWSLBTargetGroup_generatedName (66.13s)
--- PASS: TestAccAWSLBTargetGroupAttachment_lambda (69.68s)
--- PASS: TestAccAWSLBTargetGroup_changeNameForceNew (90.34s)
--- PASS: TestAccAWSLBTargetGroup_TCP_HTTPHealthCheck (92.43s)
--- PASS: TestAccAWSLBTargetGroup_changePortForceNew (91.74s)
--- PASS: TestAccAWSLBTargetGroup_networkLB_TargetGroupWithProxy (93.66s)
--- PASS: TestAccAWSLBTargetGroup_Protocol_Tcp_HealthCheck_Protocol (94.47s)
--- PASS: TestAccAWSLBTargetGroupAttachment_basic (102.49s)
--- PASS: TestAccAWSLBTargetGroupAttachment_disappears (104.87s)
--- PASS: TestAccAWSLBTargetGroup_changeProtocolForceNew (109.08s)
--- PASS: TestAccAWSLBTargetGroup_defaults_application (47.71s)
--- PASS: TestAccAWSLBTargetGroupAttachment_BackwardsCompatibility (114.94s)
--- PASS: TestAccAWSLBTargetGroupAttachment_ipAddress (115.22s)
--- PASS: TestAccAWSLBTargetGroup_enableHealthCheck (85.20s)
--- PASS: TestAccAWSLBTargetGroup_changeVpcForceNew (87.87s)
--- PASS: TestAccAWSLBTargetGroupAttachment_Port (125.06s)
--- PASS: TestAccAWSLBTargetGroup_stickinessDefaultALB (39.41s)
--- PASS: TestAccAWSLBTargetGroup_defaults_network (64.09s)
--- PASS: TestAccAWSLBTargetGroup_stickinessInvalidNLB (39.84s)
--- PASS: TestAccAWSLBTargetGroup_updateHealthCheck (84.09s)
--- PASS: TestAccAWSLBTargetGroup_networkLB_TargetGroup (134.51s)
--- PASS: TestAccAWSLBTargetGroup_tags (107.53s)
--- PASS: TestAccAWSLBTargetGroup_stickinessInvalidALB (48.70s)
--- PASS: TestAccAWSLBTargetGroup_updateSticknessEnabled (95.99s)
--- PASS: TestAccAWSLBTargetGroup_stickinessValidALB (54.76s)
--- PASS: TestAccAWSLBTargetGroup_stickinessDefaultNLB (80.87s)
--- PASS: TestAccAWSLBTargetGroup_stickinessValidNLB (85.28s)

File: aws/resource_aws_lb_target_group.go (hunk 1 above)
Comment (YakDriver) [reply aws/resource_aws_lb_target_group.go:164]: The one deal killer is the need to access the `protocol`. I don't see a way to do that from the `ValidateDiagFunc`.

Comment (YakDriver) [reply aws/resource_aws_lb_target_group.go:164]: Also, the `DiffSuppressFunc` should go away soon.

File: aws/resource_aws_lb_target_group.go (hunk 2 above)
Comment (YakDriver) [reply aws/resource_aws_lb_target_group.go:474]: I just don't like the `d.Get("protocol").(string)` proliferation...
