### PR TITLE
[Enhancement] aws_networkmanager_vpc_attachment: Enable in-place update of `routing_policy_label` argument 

### LINKED ISSUE #45703: Adding routing_policy_label to an existing aws_networkmanager_vpc_attachment force replacement
### Terraform and AWS Provider Version

```console
Terraform v1.14.2
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v6.27.0
+ provider registry.terraform.io/hashicorp/local v2.6.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

### Affected Resource(s) or Data Source(s)

* `aws_networkmanager_vpc_attachment`

### Expected Behavior

Update in place the routing policy of the `aws_networkmanager_vpc_attachment` as the cli does with the commands:
* `aws networkmanager put-attachment-routing-policy-label`
* `aws networkmanager remove-attachment-routing-policy-label`

### Actual Behavior

When adding or removing the param `routing_policy_label` the replacement is forced for the `aws_networkmanager_vpc_attachment`.

### Relevant Error/Panic Output

```console
  # module.vpc.aws_networkmanager_vpc_attachment.this[0] must be replaced
+/- resource "aws_networkmanager_vpc_attachment" "this" {
      ~ arn                           = "arn:aws:networkmanager::xxxxxxx:attachment/attachment-xxxxxxx" -> (known after apply)
      ~ attachment_policy_rule_number = 200 -> (known after apply)
      ~ attachment_type               = "VPC" -> (known after apply)
      ~ core_network_arn              = "arn:aws:networkmanager::xxxxxxx:core-network/core-network-xxxxxxx" -> (known after apply)
      ~ edge_location                 = "xxxxxxx" -> (known after apply)
      ~ id                            = "attachment-xxxxxxx" -> (known after apply)
      ~ owner_account_id              = "xxxxxxx" -> (known after apply)
      ~ resource_arn                  = "arn:aws:ec2:xxxxxxx:xxxxxxx:vpc/vpc-xxxxxxx" -> (known after apply)
      + routing_policy_label          = "vpcAttachments" # forces replacement
      ~ segment_name                  = "xxxxxxx" -> (known after apply)
      ~ state                         = "AVAILABLE" -> (known after apply)
        tags                          = {
            "Name"       = "xxxxxxx"
            "tec:cwnsgm" = "xxxxxxx"
        }
        # (4 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

### Sample Terraform Configuration

<details open>
<summary>Click to expand configuration</summary>

```hcl
resource "aws_networkmanager_vpc_attachment" "this" {
  count = var.core_network_attach != null ? 1 : 0

  subnet_arns          = [for k, v in aws_subnet.netatt : v.arn]
  core_network_id      = var.core_network_attach.id
  vpc_arn              = aws_vpc.this.arn
  routing_policy_label = var.core_network_attach.routing_policy_label
  options {
    appliance_mode_support             = var.core_network_attach.appliance_mode_support
    dns_support                        = var.core_network_attach.dns_support
    security_group_referencing_support = var.core_network_attach.security_group_referencing_support
    ipv6_support                       = false
  }

  tags = merge(
    var.core_network_attach.tags,
    {
      Name = format("%s-cna", var.name_prefix)
    }
  )
}
```
</details>

### Steps to Reproduce

1. Deploy a TF with a `aws_networkmanager_vpc_attachment` without `routing_policy_label` without errors
2. Update the TF adding to `aws_networkmanager_vpc_attachment`  the param `routing_policy_label`

### Debug Logging

<details open>
<summary>Click to expand log output</summary>

```console

```
</details>

### GenAI / LLM Assisted Development

n/a

### Important Facts and References

_No response_

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by tabito-hara**
## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the library.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

### Description
This PR enables in-place updates of the `routing_policy_label` argument for the `aws_networkmanager_vpc_attachment` resource.

#### AWS API Behavior and Provider Implementation
* The `UpdateVPCAttachment` API does not accept the `routing_policy_label` field.
  * For this reason, `routing_policy_label` was previously marked as `ForceNew`.
* Recently, AWS introduced a new API, `PutAttachmentRoutingPolicyLabel`, which allows this argument to be updated without recreating the resource.
* In addition, the `RemoveAttachmentRoutingPolicyLabel` API allows the routing policy label to be removed without requiring resource recreation.
* With these APIs:
  * When `routing_policy_label` is specified during an update, it is applied using the `PutAttachmentRoutingPolicyLabel` API.
  * When `routing_policy_label` is not specified, the existing label is removed using the `RemoveAttachmentRoutingPolicyLabel` API.

### Relations

Closes #45703

### References
https://docs.aws.amazon.com/cli/latest/reference/networkmanager/put-attachment-routing-policy-label.html
https://docs.aws.amazon.com/cli/latest/reference/networkmanager/remove-attachment-routing-policy-label.html
(AWS CLI documents cover new APIs, but the API references for them have not been published yet)

### Output from Acceptance Testing
```console
$ ACCTEST_PARALLELISM=5 make testacc TESTS='TestAccNetworkManagerVPCAttachment_' PKG=networkmanager
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 f-aws_iam_saml_provider-add_saml_provider_uuid 🌿...
TF_ACC=1 go1.25.5 test ./internal/service/networkmanager/... -v -count 1 -parallel 5 -run='TestAccNetworkManagerVPCAttachment_'  -timeout 360m -vet=off
2025/12/24 01:57:51 Creating Terraform AWS Provider (SDKv2-style)...
2025/12/24 01:57:51 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccNetworkManagerVPCAttachment_tags
=== PAUSE TestAccNetworkManagerVPCAttachment_tags
=== RUN   TestAccNetworkManagerVPCAttachment_tags_null
=== PAUSE TestAccNetworkManagerVPCAttachment_tags_null
=== RUN   TestAccNetworkManagerVPCAttachment_tags_EmptyMap
=== PAUSE TestAccNetworkManagerVPCAttachment_tags_EmptyMap
=== RUN   TestAccNetworkManagerVPCAttachment_tags_AddOnUpdate
=== PAUSE TestAccNetworkManagerVPCAttachment_tags_AddOnUpdate
=== RUN   TestAccNetworkManagerVPCAttachment_tags_EmptyTag_OnCreate
    vpc_attachment_tags_gen_test.go:399: Resource VPCAttachment does not support empty tags
--- SKIP: TestAccNetworkManagerVPCAttachment_tags_EmptyTag_OnCreate (0.00s)
=== RUN   TestAccNetworkManagerVPCAttachment_tags_EmptyTag_OnUpdate_Add
    vpc_attachment_tags_gen_test.go:486: Resource VPCAttachment does not support empty tags
--- SKIP: TestAccNetworkManagerVPCAttachment_tags_EmptyTag_OnUpdate_Add (0.00s)
=== RUN   TestAccNetworkManagerVPCAttachment_tags_EmptyTag_OnUpdate_Replace
    vpc_attachment_tags_gen_test.go:620: Resource VPCAttachment does not support empty tags
--- SKIP: TestAccNetworkManagerVPCAttachment_tags_EmptyTag_OnUpdate_Replace (0.00s)
=== RUN   TestAccNetworkManagerVPCAttachment_tags_DefaultTags_providerOnly
=== PAUSE TestAccNetworkManagerVPCAttachment_tags_DefaultTags_providerOnly
=== RUN   TestAccNetworkManagerVPCAttachment_tags_DefaultTags_nonOverlapping
=== PAUSE TestAccNetworkManagerVPCAttachment_tags_DefaultTags_nonOverlapping
=== RUN   TestAccNetworkManagerVPCAttachment_tags_DefaultTags_overlapping
=== PAUSE TestAccNetworkManagerVPCAttachment_tags_DefaultTags_overlapping
=== RUN   TestAccNetworkManagerVPCAttachment_tags_DefaultTags_updateToProviderOnly
=== PAUSE TestAccNetworkManagerVPCAttachment_tags_DefaultTags_updateToProviderOnly
=== RUN   TestAccNetworkManagerVPCAttachment_tags_DefaultTags_updateToResourceOnly
=== PAUSE TestAccNetworkManagerVPCAttachment_tags_DefaultTags_updateToResourceOnly
=== RUN   TestAccNetworkManagerVPCAttachment_tags_DefaultTags_emptyResourceTag
    vpc_attachment_tags_gen_test.go:1378: Resource VPCAttachment does not support empty tags
--- SKIP: TestAccNetworkManagerVPCAttachment_tags_DefaultTags_emptyResourceTag (0.00s)
=== RUN   TestAccNetworkManagerVPCAttachment_tags_DefaultTags_emptyProviderOnlyTag
    vpc_attachment_tags_gen_test.go:1443: Resource VPCAttachment does not support empty tags
--- SKIP: TestAccNetworkManagerVPCAttachment_tags_DefaultTags_emptyProviderOnlyTag (0.00s)
=== RUN   TestAccNetworkManagerVPCAttachment_tags_DefaultTags_nullOverlappingResourceTag
=== PAUSE TestAccNetworkManagerVPCAttachment_tags_DefaultTags_nullOverlappingResourceTag
=== RUN   TestAccNetworkManagerVPCAttachment_tags_DefaultTags_nullNonOverlappingResourceTag
=== PAUSE TestAccNetworkManagerVPCAttachment_tags_DefaultTags_nullNonOverlappingResourceTag
=== RUN   TestAccNetworkManagerVPCAttachment_tags_ComputedTag_OnCreate
=== PAUSE TestAccNetworkManagerVPCAttachment_tags_ComputedTag_OnCreate
=== RUN   TestAccNetworkManagerVPCAttachment_tags_ComputedTag_OnUpdate_Add
=== PAUSE TestAccNetworkManagerVPCAttachment_tags_ComputedTag_OnUpdate_Add
=== RUN   TestAccNetworkManagerVPCAttachment_tags_ComputedTag_OnUpdate_Replace
=== PAUSE TestAccNetworkManagerVPCAttachment_tags_ComputedTag_OnUpdate_Replace
=== RUN   TestAccNetworkManagerVPCAttachment_tags_IgnoreTags_Overlap_DefaultTag
=== PAUSE TestAccNetworkManagerVPCAttachment_tags_IgnoreTags_Overlap_DefaultTag
=== RUN   TestAccNetworkManagerVPCAttachment_tags_IgnoreTags_Overlap_ResourceTag
=== PAUSE TestAccNetworkManagerVPCAttachment_tags_IgnoreTags_Overlap_ResourceTag
=== RUN   TestAccNetworkManagerVPCAttachment_basic
=== PAUSE TestAccNetworkManagerVPCAttachment_basic
=== RUN   TestAccNetworkManagerVPCAttachment_Attached_basic
=== PAUSE TestAccNetworkManagerVPCAttachment_Attached_basic
=== RUN   TestAccNetworkManagerVPCAttachment_disappears
=== PAUSE TestAccNetworkManagerVPCAttachment_disappears
=== RUN   TestAccNetworkManagerVPCAttachment_Attached_disappears
=== PAUSE TestAccNetworkManagerVPCAttachment_Attached_disappears
=== RUN   TestAccNetworkManagerVPCAttachment_Attached_disappearsAccepter
=== PAUSE TestAccNetworkManagerVPCAttachment_Attached_disappearsAccepter
=== RUN   TestAccNetworkManagerVPCAttachment_update
=== PAUSE TestAccNetworkManagerVPCAttachment_update
=== RUN   TestAccNetworkManagerVPCAttachment_Attached_update
=== PAUSE TestAccNetworkManagerVPCAttachment_Attached_update
=== RUN   TestAccNetworkManagerVPCAttachment_attachmentOptions
=== PAUSE TestAccNetworkManagerVPCAttachment_attachmentOptions
=== RUN   TestAccNetworkManagerVPCAttachment_routingPolicyLabel
=== PAUSE TestAccNetworkManagerVPCAttachment_routingPolicyLabel
=== RUN   TestAccNetworkManagerVPCAttachment_routingPolicyLabelUpdate
=== PAUSE TestAccNetworkManagerVPCAttachment_routingPolicyLabelUpdate
=== CONT  TestAccNetworkManagerVPCAttachment_tags
=== CONT  TestAccNetworkManagerVPCAttachment_tags_ComputedTag_OnUpdate_Replace
=== CONT  TestAccNetworkManagerVPCAttachment_Attached_disappearsAccepter
=== CONT  TestAccNetworkManagerVPCAttachment_Attached_basic
=== CONT  TestAccNetworkManagerVPCAttachment_Attached_disappears
=== RUN   TestAccNetworkManagerVPCAttachment_Attached_basic/acceptance_required
=== RUN   TestAccNetworkManagerVPCAttachment_Attached_disappears/acceptance_required
=== PAUSE TestAccNetworkManagerVPCAttachment_Attached_basic/acceptance_required
=== RUN   TestAccNetworkManagerVPCAttachment_Attached_basic/acceptance_not_required
=== PAUSE TestAccNetworkManagerVPCAttachment_Attached_basic/acceptance_not_required
=== CONT  TestAccNetworkManagerVPCAttachment_disappears
=== RUN   TestAccNetworkManagerVPCAttachment_disappears/acceptance_required
=== PAUSE TestAccNetworkManagerVPCAttachment_disappears/acceptance_required
=== RUN   TestAccNetworkManagerVPCAttachment_disappears/acceptance_not_required
=== PAUSE TestAccNetworkManagerVPCAttachment_disappears/acceptance_not_required
=== CONT  TestAccNetworkManagerVPCAttachment_tags_IgnoreTags_Overlap_ResourceTag
=== PAUSE TestAccNetworkManagerVPCAttachment_Attached_disappears/acceptance_required
=== RUN   TestAccNetworkManagerVPCAttachment_Attached_disappears/acceptance_not_required
=== PAUSE TestAccNetworkManagerVPCAttachment_Attached_disappears/acceptance_not_required
=== CONT  TestAccNetworkManagerVPCAttachment_basic
=== RUN   TestAccNetworkManagerVPCAttachment_basic/acceptance_required
=== PAUSE TestAccNetworkManagerVPCAttachment_basic/acceptance_required
=== RUN   TestAccNetworkManagerVPCAttachment_basic/acceptance_not_required
=== PAUSE TestAccNetworkManagerVPCAttachment_basic/acceptance_not_required
=== CONT  TestAccNetworkManagerVPCAttachment_tags_DefaultTags_updateToProviderOnly
--- PASS: TestAccNetworkManagerVPCAttachment_Attached_disappearsAccepter (898.66s)
=== CONT  TestAccNetworkManagerVPCAttachment_tags_ComputedTag_OnUpdate_Add
--- PASS: TestAccNetworkManagerVPCAttachment_tags_ComputedTag_OnUpdate_Replace (936.34s)
=== CONT  TestAccNetworkManagerVPCAttachment_tags_ComputedTag_OnCreate
--- PASS: TestAccNetworkManagerVPCAttachment_tags_IgnoreTags_Overlap_ResourceTag (970.65s)
=== CONT  TestAccNetworkManagerVPCAttachment_tags_DefaultTags_nullNonOverlappingResourceTag
--- PASS: TestAccNetworkManagerVPCAttachment_tags_DefaultTags_updateToProviderOnly (975.94s)
=== CONT  TestAccNetworkManagerVPCAttachment_tags_DefaultTags_nullOverlappingResourceTag
--- PASS: TestAccNetworkManagerVPCAttachment_tags (1074.11s)
=== CONT  TestAccNetworkManagerVPCAttachment_tags_DefaultTags_updateToResourceOnly
--- PASS: TestAccNetworkManagerVPCAttachment_tags_ComputedTag_OnCreate (929.15s)
=== CONT  TestAccNetworkManagerVPCAttachment_routingPolicyLabelUpdate
--- PASS: TestAccNetworkManagerVPCAttachment_tags_ComputedTag_OnUpdate_Add (1061.70s)
=== CONT  TestAccNetworkManagerVPCAttachment_Attached_update
=== RUN   TestAccNetworkManagerVPCAttachment_Attached_update/acceptance_required
=== PAUSE TestAccNetworkManagerVPCAttachment_Attached_update/acceptance_required
=== RUN   TestAccNetworkManagerVPCAttachment_Attached_update/acceptance_not_required
=== PAUSE TestAccNetworkManagerVPCAttachment_Attached_update/acceptance_not_required
=== CONT  TestAccNetworkManagerVPCAttachment_tags_IgnoreTags_Overlap_DefaultTag
--- PASS: TestAccNetworkManagerVPCAttachment_tags_DefaultTags_nullNonOverlappingResourceTag (1018.62s)
=== CONT  TestAccNetworkManagerVPCAttachment_update
=== RUN   TestAccNetworkManagerVPCAttachment_update/acceptance_required
=== PAUSE TestAccNetworkManagerVPCAttachment_update/acceptance_required
=== RUN   TestAccNetworkManagerVPCAttachment_update/acceptance_not_required
=== PAUSE TestAccNetworkManagerVPCAttachment_update/acceptance_not_required
=== CONT  TestAccNetworkManagerVPCAttachment_routingPolicyLabel
--- PASS: TestAccNetworkManagerVPCAttachment_tags_DefaultTags_nullOverlappingResourceTag (1164.74s)
=== CONT  TestAccNetworkManagerVPCAttachment_attachmentOptions
--- PASS: TestAccNetworkManagerVPCAttachment_tags_DefaultTags_updateToResourceOnly (1103.64s)
=== CONT  TestAccNetworkManagerVPCAttachment_tags_DefaultTags_providerOnly
--- PASS: TestAccNetworkManagerVPCAttachment_tags_IgnoreTags_Overlap_DefaultTag (1142.81s)
=== CONT  TestAccNetworkManagerVPCAttachment_tags_DefaultTags_overlapping
--- PASS: TestAccNetworkManagerVPCAttachment_tags_DefaultTags_providerOnly (1011.71s)
=== CONT  TestAccNetworkManagerVPCAttachment_tags_EmptyMap
--- PASS: TestAccNetworkManagerVPCAttachment_attachmentOptions (1099.91s)
=== CONT  TestAccNetworkManagerVPCAttachment_tags_DefaultTags_nonOverlapping
--- PASS: TestAccNetworkManagerVPCAttachment_routingPolicyLabelUpdate (1399.25s)
=== CONT  TestAccNetworkManagerVPCAttachment_tags_AddOnUpdate
--- PASS: TestAccNetworkManagerVPCAttachment_routingPolicyLabel (1345.31s)
=== CONT  TestAccNetworkManagerVPCAttachment_tags_null
--- PASS: TestAccNetworkManagerVPCAttachment_tags_EmptyMap (945.59s)
=== CONT  TestAccNetworkManagerVPCAttachment_Attached_basic/acceptance_required
--- PASS: TestAccNetworkManagerVPCAttachment_tags_DefaultTags_overlapping (1039.06s)
=== CONT  TestAccNetworkManagerVPCAttachment_Attached_basic/acceptance_not_required
--- PASS: TestAccNetworkManagerVPCAttachment_tags_DefaultTags_nonOverlapping (918.57s)
=== CONT  TestAccNetworkManagerVPCAttachment_disappears/acceptance_required
--- PASS: TestAccNetworkManagerVPCAttachment_tags_AddOnUpdate (952.68s)
=== CONT  TestAccNetworkManagerVPCAttachment_disappears/acceptance_not_required
--- PASS: TestAccNetworkManagerVPCAttachment_tags_null (888.08s)
=== CONT  TestAccNetworkManagerVPCAttachment_Attached_disappears/acceptance_required
=== CONT  TestAccNetworkManagerVPCAttachment_Attached_disappears/acceptance_not_required
=== CONT  TestAccNetworkManagerVPCAttachment_basic/acceptance_required
=== CONT  TestAccNetworkManagerVPCAttachment_basic/acceptance_not_required
--- PASS: TestAccNetworkManagerVPCAttachment_Attached_basic (0.00s)
    --- PASS: TestAccNetworkManagerVPCAttachment_Attached_basic/acceptance_not_required (961.35s)
    --- PASS: TestAccNetworkManagerVPCAttachment_Attached_basic/acceptance_required (985.58s)
=== CONT  TestAccNetworkManagerVPCAttachment_Attached_update/acceptance_required
--- PASS: TestAccNetworkManagerVPCAttachment_disappears (0.00s)
    --- PASS: TestAccNetworkManagerVPCAttachment_disappears/acceptance_required (667.28s)
    --- PASS: TestAccNetworkManagerVPCAttachment_disappears/acceptance_not_required (968.06s)
=== CONT  TestAccNetworkManagerVPCAttachment_Attached_update/acceptance_not_required
=== CONT  TestAccNetworkManagerVPCAttachment_update/acceptance_required
=== CONT  TestAccNetworkManagerVPCAttachment_update/acceptance_not_required
--- PASS: TestAccNetworkManagerVPCAttachment_Attached_disappears (0.00s)
    --- PASS: TestAccNetworkManagerVPCAttachment_Attached_disappears/acceptance_required (982.51s)
    --- PASS: TestAccNetworkManagerVPCAttachment_Attached_disappears/acceptance_not_required (983.39s)
--- PASS: TestAccNetworkManagerVPCAttachment_basic (0.00s)
    --- PASS: TestAccNetworkManagerVPCAttachment_basic/acceptance_required (581.41s)
    --- PASS: TestAccNetworkManagerVPCAttachment_basic/acceptance_not_required (929.00s)
--- PASS: TestAccNetworkManagerVPCAttachment_Attached_update (0.00s)
    --- PASS: TestAccNetworkManagerVPCAttachment_Attached_update/acceptance_not_required (1266.67s)
    --- PASS: TestAccNetworkManagerVPCAttachment_Attached_update/acceptance_required (1319.03s)
--- PASS: TestAccNetworkManagerVPCAttachment_update (0.00s)
    --- PASS: TestAccNetworkManagerVPCAttachment_update/acceptance_required (1105.00s)
    --- PASS: TestAccNetworkManagerVPCAttachment_update/acceptance_not_required (1325.09s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/networkmanager     7138.921s

```

### CODE REVIEW

File: internal/service/networkmanager/vpc_attachment.go [hunk 1]
```diff
@@ -331,6 +330,21 @@ func resourceVPCAttachmentUpdate(ctx context.Context, d *schema.ResourceData, me
 		return sdkdiag.AppendErrorf(diags, "waiting for Network Manager VPC Attachment (%s) update: %s", d.Id(), err)
 	}
 
+	if d.HasChange("routing_policy_label") {
+		input := networkmanager.PutAttachmentRoutingPolicyLabelInput{
+			AttachmentId:       aws.String(d.Id()),
+			CoreNetworkId:      aws.String(d.Get("core_network_id").(string)),
+			RoutingPolicyLabel: aws.String(d.Get("routing_policy_label").(string)),
+		}
+		_, err := conn.PutAttachmentRoutingPolicyLabel(ctx, &input)
```
Comment (rarandab) [inline internal/service/networkmanager/vpc_attachment.go]: Yesterday I was looking into the go SDK for this issue also and there is another method for remove the routing policy label, maybe it should check if has change to empty or null and use remove?

RemoveAttachmentRoutingPolicyLabel

Comment (tabito-hara) [reply internal/service/networkmanager/vpc_attachment.go]: Thank you for your information!

I was just verifying removal of `routing_policy_label` and found that an empty string did not work.
As you pointed out, another API is required to remove it.

I fixed my PR to use `RemoveAttachmentRoutingPolicyLabel` when `routing_policy_label` is not specified,  and am now running tests to verify this.

I will update the PR shortly.

File: .changelog/45728.txt [hunk 2]
```diff
@@ -0,0 +1,3 @@
+```release-note:enhancement
+resource/aws_networkmanager_vpc_attachment: Enable in-place updates of `routing_policy_label` argument
```
Comment (ewbankkit) [inline .changelog/45728.txt]:
```suggestion
resource/aws_networkmanager_vpc_attachment: Enable in-place updates of `routing_policy_label` argument. This functionality requires the `networkmanager: PutAttachmentRoutingPolicyLabel` and `networkmanager: RemoveAttachmentRoutingPolicyLabel` IAM permissions
```

**Comment by ewbankkit** [comment]
@tabito-hara Thanks for the contribution :tada: :clap:.
