### PR TITLE
tests: Add Common (semgrepable) ErrorCheck functionality

### LINKED ISSUE #16390: tests/resource/route53_record: Hosted zone does not exist (GovCloud)
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This tests fails in GovCloud:

```
TestAccAWSRoute53Record_Alias_VpcEndpoint
```

Not sure if the `.com` ending is causing this problem.

### New or Affected Resource(s)

* aws_route53_record

### Potential Terraform Configuration

```hcl
resource "aws_vpc" "test" {
  cidr_block = "10.0.0.0/16"

  tags = {
    Name = "yaktest"
  }
}

resource "aws_subnet" "test" {
  cidr_block = "10.0.0.0/24"
  vpc_id     = aws_vpc.test.id

  tags = {
    Name = "yaktest"
  }
}

resource "aws_lb" "test" {
  internal           = true
  load_balancer_type = "network"
  name               = "yaktest"
  subnets            = [aws_subnet.test.id]
}

resource "aws_security_group" "test" {
  name   = "yaktest"
  vpc_id = aws_vpc.test.id

  tags = {
    Name = "yaktest"
  }
}

resource "aws_vpc_endpoint_service" "test" {
  acceptance_required        = false
  network_load_balancer_arns = [aws_lb.test.id]
}

resource "aws_vpc_endpoint" "test" {
  private_dns_enabled = false
  security_group_ids  = [aws_security_group.test.id]
  service_name        = aws_vpc_endpoint_service.test.service_name
  subnet_ids          = [aws_subnet.test.id]
  vpc_endpoint_type   = "Interface"
  vpc_id              = aws_vpc.test.id
}

resource "aws_route53_zone" "test" {
  name = "notexample.com"

  vpc {
    vpc_id = aws_vpc.test.id
  }
}

resource "aws_route53_record" "test" {
  name    = "test"
  type    = "A"
  zone_id = aws_route53_zone.test.zone_id

  alias {
    evaluate_target_health = false
    name                   = lookup(aws_vpc_endpoint.test.dns_entry[0], "hosted_zone_id")
    zone_id                = lookup(aws_vpc_endpoint.test.dns_entry[0], "dns_name")
  }
}
```

### Debug

```
resource_aws_route53_record_test.go:576: Step 2/3 error: Error running apply: 2020/11/23 15:50:02 [DEBUG] Using modified User-Agent: Terraform/0.12.29 HashiCorp-terraform-exec/0.10.0
        
        Error: [ERR]: Error building changeset: NoSuchHostedZone: The specified hosted zone does not exist.
        	status code: 404, request id: 77cc81a3-7260-499d-be40-3aa9386a4233
```

### References

* #16380

### PR DESCRIPTION
**Pull request by YakDriver**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #17566
Fixes #16390

Output from acceptance testing (GovCloud):

```
--- SKIP: TestAccAWSRoute53Record_Alias_VpcEndpoint (423.10s)
--- SKIP: TestAccAWSRoute53Record_Alias_Elb (20.22s)
--- SKIP: TestAccAWSRoute53Record_Alias_S3 (19.21s)
--- SKIP: TestAccAWSRoute53Record_Alias_Uppercase (22.64s)
--- SKIP: TestAccAWSRoute53Record_AliasChange (19.60s)
--- SKIP: TestAccAWSRoute53Record_allowOverwrite (10.72s)
--- SKIP: TestAccAWSRoute53Record_basic (11.17s)
--- SKIP: TestAccAWSRoute53Record_basic_fqdn (13.62s)
--- SKIP: TestAccAWSRoute53Record_basic_trailingPeriodAndZoneID (33.44s)
--- SKIP: TestAccAWSRoute53Record_caaSupport (20.31s)
--- SKIP: TestAccAWSRoute53Record_disappears (36.86s)
--- SKIP: TestAccAWSRoute53Record_disappears_MultipleRecords (33.15s)
--- SKIP: TestAccAWSRoute53Record_doNotAllowOverwrite (11.80s)
--- SKIP: TestAccAWSRoute53Record_dsSupport (11.24s)
--- SKIP: TestAccAWSRoute53Record_empty (11.20s)
--- SKIP: TestAccAWSRoute53Record_failover (15.42s)
--- SKIP: TestAccAWSRoute53Record_generatesSuffix (11.53s)
--- SKIP: TestAccAWSRoute53Record_geolocation_basic (10.19s)
--- SKIP: TestAccAWSRoute53Record_HealthCheckId_SetIdentifierChange (21.36s)
--- SKIP: TestAccAWSRoute53Record_HealthCheckId_TypeChange (15.29s)
--- SKIP: TestAccAWSRoute53Record_latency_basic (62.97s)
--- SKIP: TestAccAWSRoute53Record_longTXTrecord (11.53s)
--- SKIP: TestAccAWSRoute53Record_multivalue_answer_basic (10.03s)
--- SKIP: TestAccAWSRoute53Record_NameChange (33.84s)
--- SKIP: TestAccAWSRoute53Record_SetIdentifierChange (11.58s)
--- SKIP: TestAccAWSRoute53Record_spfSupport (20.75s)
--- SKIP: TestAccAWSRoute53Record_txtSupport (14.06s)
--- SKIP: TestAccAWSRoute53Record_TypeChange (34.83s)
--- SKIP: TestAccAWSRoute53Record_underscored (30.38s)
--- SKIP: TestAccAWSRoute53Record_weighted_alias (42.74s)
--- SKIP: TestAccAWSRoute53Record_weighted_basic (11.65s)
--- SKIP: TestAccAWSRoute53Record_weighted_to_simple_basic (11.53s)
--- SKIP: TestAccAWSRoute53Record_wildcard (11.62s)
```

On commercial (`us-west-2`):
```
--- PASS: TestAccAWSRoute53Record_doNotAllowOverwrite (135.39s)
--- PASS: TestAccAWSRoute53Record_Alias_S3 (152.89s)
--- PASS: TestAccAWSRoute53Record_dsSupport (174.82s)
--- PASS: TestAccAWSRoute53Record_caaSupport (175.10s)
--- PASS: TestAccAWSRoute53Record_multivalue_answer_basic (175.78s)
--- PASS: TestAccAWSRoute53Record_failover (178.10s)
--- PASS: TestAccAWSRoute53Record_generatesSuffix (179.49s)
--- PASS: TestAccAWSRoute53Record_geolocation_basic (182.96s)
--- PASS: TestAccAWSRoute53Record_latency_basic (183.92s)
--- PASS: TestAccAWSRoute53Record_empty (190.77s)
--- PASS: TestAccAWSRoute53Record_longTXTrecord (197.37s)
--- PASS: TestAccAWSRoute53Record_TypeChange (198.71s)
--- PASS: TestAccAWSRoute53Record_basic (207.94s)
--- PASS: TestAccAWSRoute53Record_SetIdentifierChange (221.32s)
--- PASS: TestAccAWSRoute53Record_allowOverwrite (221.76s)
--- PASS: TestAccAWSRoute53Record_wildcard (245.64s)
--- PASS: TestAccAWSRoute53Record_HealthCheckId_SetIdentifierChange (250.42s)
--- PASS: TestAccAWSRoute53Record_AliasChange (256.13s)
--- PASS: TestAccAWSRoute53Record_NameChange (282.15s)
--- PASS: TestAccAWSRoute53Record_Alias_Uppercase (162.23s)
--- PASS: TestAccAWSRoute53Record_HealthCheckId_TypeChange (305.46s)
--- PASS: TestAccAWSRoute53Record_spfSupport (131.32s)
--- PASS: TestAccAWSRoute53Record_Alias_Elb (125.85s)
--- PASS: TestAccAWSRoute53Record_basic_trailingPeriodAndZoneID (146.32s)
--- PASS: TestAccAWSRoute53Record_disappears (135.23s)
--- PASS: TestAccAWSRoute53Record_txtSupport (156.31s)
--- PASS: TestAccAWSRoute53Record_basic_fqdn (161.19s)
--- PASS: TestAccAWSRoute53Record_underscored (147.12s)
--- PASS: TestAccAWSRoute53Record_weighted_to_simple_basic (179.77s)
--- PASS: TestAccAWSRoute53Record_weighted_basic (182.45s)
--- PASS: TestAccAWSRoute53Record_disappears_MultipleRecords (191.86s)
--- PASS: TestAccAWSRoute53Record_weighted_alias (317.13s)
--- PASS: TestAccAWSRoute53Record_Alias_VpcEndpoint (461.22s)
```

### CODE REVIEW

File: aws/provider_test.go [hunk 1]
```diff
@@ -1036,6 +1036,66 @@ func testAccErrorCheckSkipMessagesContaining(t *testing.T, messages ...string) r
...
 
+type ServiceErrorCheckFunc func(*testing.T) resource.ErrorCheckFunc
+
+var serviceErrorCheckFuncs map[string]ServiceErrorCheckFunc
+
+func RegisterServiceErrorCheckFunc(endpointID string, f ServiceErrorCheckFunc) {
+	if serviceErrorCheckFuncs == nil {
+		serviceErrorCheckFuncs = make(map[string]ServiceErrorCheckFunc)
+	}
+	serviceErrorCheckFuncs[endpointID] = f
```
Comment (bflad) [inline aws/provider_test.go:1047]: We may want to consider `panic()` for cases if a duplicate service is being registered to prevent that type of coding issue instead of potentially confusing behavior. I believe `init()` functions run in file naming alphabetical order.

File: aws/provider_test.go [hunk 2]
```diff
@@ -1036,6 +1036,66 @@ func testAccErrorCheckSkipMessagesContaining(t *testing.T, messages ...string) r
...
+		for _, endpointID := range endpointIDs {
+			if f, ok := serviceErrorCheckFuncs[endpointID]; ok {
+				ef := f(t)
+				err = ef(err)
+			}
+		}
+
+		if testAccErrorCheckCommon(err) {
+			t.Skipf("skipping test for %s/%s: %s", testAccGetPartition(), testAccGetRegion(), err.Error())
+		}
```
Comment (bflad) [inline aws/provider_test.go:1065]: In the case of looping through multiple services, error checking should occur at each service or break to save unnecessarily looping through additional services:

```suggestion
		for _, endpointID := range endpointIDs {
			if f, ok := serviceErrorCheckFuncs[endpointID]; ok {
				ef := f(t)
				err = ef(err)
			}

			if err == nil {
				break
			}
		}

		if testAccErrorCheckCommon(err) {
			t.Skipf("skipping test for %s/%s: %s", testAccGetPartition(), testAccGetRegion(), err.Error())
		}
```

**Review by bflad — APPROVED** [review]
I think this is a good starting implementation. 👍 

In the future, we will likely want to consider implementing this where it can read a Terraform configuration to determine all of its resource types, then use those resource types to determine the appropriate error checking functions. This will prevent the multiple AWS SDK Go service import issue and remove the manual coding work.

Output from acceptance testing in AWS Commercial:

```
--- PASS: TestAccAWSRoute53Record_basic (113.20s)
```

Output from acceptance testing in AWS GovCloud (US):

```
--- SKIP: TestAccAWSRoute53Record_basic (9.52s)
```

File: aws/provider_test.go (hunk 1 above)
Comment (YakDriver) [reply aws/provider_test.go:1047]: Good idea! That would be very confusing to figure out why a registered-over func wasn't running.
