### PR TITLE
sns/topic: ISO-friendly tagging

### LINKED ISSUE #21209: SNS State Refreshes and Subscriptions Fail in us-iso-b due to Tagging Not Existing
Relates #18593

Because tagging doesn't currently exist for SNS in us-iso-b, and because when trying to refresh the state or do other operations against an SNS topic after creation tries pulling the tags, the operation fails.  The AWS platform returns a 400 with the following when trying to update the resource:

> InvalidAction: Unsupported Action

And a 403 with the following when trying to list tags:

> AuthorizationError: You are not authorized to perform tagging operations

As a result, further resources cannot be created as the provider gives no method to skip updating or listing tags, even when there are no tags specified in the terraform code.

### PR DESCRIPTION
**Pull request by YakDriver**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #21209
Relates #22532

Output from acceptance testing (`us-west-2`):

```console
% make testacc TESTS=TestAccSNSTopic_ PKG=sns
--- PASS: TestAccSNSTopic_fifoExpectContentBasedDeduplicationError (4.25s)
--- PASS: TestAccSNSTopic_disappears (17.49s)
--- PASS: TestAccSNSTopic_name (24.78s)
--- PASS: TestAccSNSTopic_NamePrefix_fifoTopic (24.97s)
--- PASS: TestAccSNSTopic_namePrefix (25.12s)
--- PASS: TestAccSNSTopic_Name_fifoTopic (25.13s)
--- PASS: TestAccSNSTopic_policy (25.14s)
--- PASS: TestAccSNSTopic_NameGenerated_fifoTopic (25.14s)
--- PASS: TestAccSNSTopic_withDeliveryPolicy (25.14s)
--- PASS: TestAccSNSTopic_basic (25.18s)
--- PASS: TestAccSNSTopic_withIAMRole (32.51s)
--- PASS: TestAccSNSTopic_fifoWithContentBasedDeduplication (34.85s)
--- PASS: TestAccSNSTopic_encryption (35.21s)
--- PASS: TestAccSNSTopic_deliveryStatus (36.25s)
--- PASS: TestAccSNSTopic_tags (44.99s)
--- PASS: TestAccSNSTopic_withFakeIAMRole (130.83s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/sns	132.191s
```

Output from acceptance testing (GovCloud):

```console
% make testacc TESTS=TestAccSNSTopic_ PKG=sns
--- PASS: TestAccSNSTopic_fifoExpectContentBasedDeduplicationError (5.28s)
--- SKIP: TestAccSNSTopic_Name_fifoTopic (10.68s)
--- SKIP: TestAccSNSTopic_fifoWithContentBasedDeduplication (10.69s)
--- SKIP: TestAccSNSTopic_NameGenerated_fifoTopic (10.69s)
--- SKIP: TestAccSNSTopic_NamePrefix_fifoTopic (10.70s)
--- PASS: TestAccSNSTopic_disappears (20.55s)
--- PASS: TestAccSNSTopic_withDeliveryPolicy (27.36s)
--- PASS: TestAccSNSTopic_basic (27.42s)
--- PASS: TestAccSNSTopic_name (27.49s)
--- PASS: TestAccSNSTopic_namePrefix (27.54s)
--- PASS: TestAccSNSTopic_policy (27.57s)
--- PASS: TestAccSNSTopic_withIAMRole (33.66s)
--- PASS: TestAccSNSTopic_deliveryStatus (40.43s)
--- PASS: TestAccSNSTopic_encryption (40.64s)
--- PASS: TestAccSNSTopic_tags (53.25s)
--- PASS: TestAccSNSTopic_withFakeIAMRole (133.58s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/sns	134.787s
```

### CODE REVIEW

File: internal/service/sns/topic.go [hunk 1]
```diff
@@ -250,6 +250,13 @@ func resourceTopicCreate(d *schema.ResourceData, meta interface{}) error {
 	log.Printf("[DEBUG] Creating SNS Topic: %s", input)
 	output, err := conn.CreateTopic(input)
 
+	// Some partitions may not support tag-on-create
+	if input.Tags != nil && (tfawserr.ErrCodeContains(err, "AccessDenied") || tfawserr.ErrCodeContains(err, "InvalidAction") || tfawserr.ErrCodeContains(err, "AuthorizationError")) {
```
Comment (ewbankkit) [inline internal/service/sns/topic.go:254]: Do you want to add constants for these string values (as they are used in multiple locations) or is that too much?

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTS=TestAccSNSTopic_ PKG=sns
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/sns/... -v -count 1 -parallel 20 -run='TestAccSNSTopic_'  -timeout 180m
=== RUN   TestAccSNSTopic_basic
=== PAUSE TestAccSNSTopic_basic
=== RUN   TestAccSNSTopic_name
=== PAUSE TestAccSNSTopic_name
=== RUN   TestAccSNSTopic_namePrefix
=== PAUSE TestAccSNSTopic_namePrefix
=== RUN   TestAccSNSTopic_policy
=== PAUSE TestAccSNSTopic_policy
=== RUN   TestAccSNSTopic_withIAMRole
=== PAUSE TestAccSNSTopic_withIAMRole
=== RUN   TestAccSNSTopic_withFakeIAMRole
=== PAUSE TestAccSNSTopic_withFakeIAMRole
=== RUN   TestAccSNSTopic_withDeliveryPolicy
=== PAUSE TestAccSNSTopic_withDeliveryPolicy
=== RUN   TestAccSNSTopic_deliveryStatus
=== PAUSE TestAccSNSTopic_deliveryStatus
=== RUN   TestAccSNSTopic_NameGenerated_fifoTopic
=== PAUSE TestAccSNSTopic_NameGenerated_fifoTopic
=== RUN   TestAccSNSTopic_Name_fifoTopic
=== PAUSE TestAccSNSTopic_Name_fifoTopic
=== RUN   TestAccSNSTopic_NamePrefix_fifoTopic
=== PAUSE TestAccSNSTopic_NamePrefix_fifoTopic
=== RUN   TestAccSNSTopic_fifoWithContentBasedDeduplication
=== PAUSE TestAccSNSTopic_fifoWithContentBasedDeduplication
=== RUN   TestAccSNSTopic_fifoExpectContentBasedDeduplicationError
=== PAUSE TestAccSNSTopic_fifoExpectContentBasedDeduplicationError
=== RUN   TestAccSNSTopic_encryption
=== PAUSE TestAccSNSTopic_encryption
=== RUN   TestAccSNSTopic_tags
=== PAUSE TestAccSNSTopic_tags
=== RUN   TestAccSNSTopic_disappears
=== PAUSE TestAccSNSTopic_disappears
=== CONT  TestAccSNSTopic_basic
=== CONT  TestAccSNSTopic_encryption
=== CONT  TestAccSNSTopic_fifoWithContentBasedDeduplication
=== CONT  TestAccSNSTopic_tags
=== CONT  TestAccSNSTopic_Name_fifoTopic
=== CONT  TestAccSNSTopic_withFakeIAMRole
=== CONT  TestAccSNSTopic_NameGenerated_fifoTopic
=== CONT  TestAccSNSTopic_deliveryStatus
=== CONT  TestAccSNSTopic_disappears
=== CONT  TestAccSNSTopic_policy
=== CONT  TestAccSNSTopic_withIAMRole
=== CONT  TestAccSNSTopic_withDeliveryPolicy
=== CONT  TestAccSNSTopic_NamePrefix_fifoTopic
=== CONT  TestAccSNSTopic_namePrefix
=== CONT  TestAccSNSTopic_name
=== CONT  TestAccSNSTopic_fifoExpectContentBasedDeduplicationError
--- PASS: TestAccSNSTopic_fifoExpectContentBasedDeduplicationError (9.48s)
--- PASS: TestAccSNSTopic_disappears (37.62s)
--- PASS: TestAccSNSTopic_namePrefix (44.06s)
--- PASS: TestAccSNSTopic_Name_fifoTopic (49.58s)
--- PASS: TestAccSNSTopic_NamePrefix_fifoTopic (49.63s)
--- PASS: TestAccSNSTopic_NameGenerated_fifoTopic (49.68s)
--- PASS: TestAccSNSTopic_name (49.75s)
--- PASS: TestAccSNSTopic_withDeliveryPolicy (49.83s)
--- PASS: TestAccSNSTopic_policy (49.92s)
--- PASS: TestAccSNSTopic_basic (50.03s)
--- PASS: TestAccSNSTopic_deliveryStatus (59.14s)
--- PASS: TestAccSNSTopic_encryption (64.13s)
--- PASS: TestAccSNSTopic_fifoWithContentBasedDeduplication (64.14s)
--- PASS: TestAccSNSTopic_withIAMRole (69.69s)
--- PASS: TestAccSNSTopic_tags (74.61s)
--- PASS: TestAccSNSTopic_withFakeIAMRole (142.25s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/sns	148.659s
```
