### PR TITLE
r/db_instance: update plan-time validation for snapshot_identifier/name/username

### LINKED ISSUE #17712: Bug introduced v3.29.0 with RDS Validation and Snapshots
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

v3.29.0 for AWS Provider
v0.14.5 for Terraform

### Affected Resource(s)

* aws_db_instance

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_db_instance" "main" {
  engine                                = "postgres"
  engine_version                        = var.engine_version
  apply_immediately                     = true
  identifier                            = "db-${var.name}-pg-instance"
  name                                  = var.database_name
  username                              = var.database_name
  password                              = random_password.password.result
  storage_encrypted                     = true
  allocated_storage                     = var.allocated_storage
  max_allocated_storage                 = var.max_allocated_storage
  instance_class                        = var.instance_class
  snapshot_identifier                   = var.snapshot_identifier
  storage_type                          = var.storage_type
  backup_retention_period               = var.backup_retention_period
  backup_window                         = var.backup_window
  maintenance_window                    = var.maintenance_window
  auto_minor_version_upgrade            = true
  final_snapshot_identifier             = "${var.name}-rds-pg-final-snapshot"
  multi_az                              = true
  vpc_security_group_ids                = [aws_security_group.main.id]
  db_subnet_group_name                  = aws_db_subnet_group.main.name
  parameter_group_name                  = length(var.db_parameters) > 0 ? aws_db_parameter_group.main[0].name : null

  monitoring_interval                   = 30
  monitoring_role_arn                   = aws_iam_role.monitor_role.arn

  performance_insights_enabled          = true
  performance_insights_retention_period = 7

  enabled_cloudwatch_logs_exports       = [
    "postgresql",
    "upgrade"
  ]

  deletion_protection                   = var.deletion_protection
  tags                                  = local.common_data_tags

  lifecycle {
    ignore_changes = [
      username
    ]
  }

  #depends_on = [aws_iam_policy_attachment.monitor_role]
}
```

### Expected Behavior

Because we're passing null in for the snapshot we'd expect validation to succeed. 

### Actual Behavior

Validation fails because it does not take the null case into account.

### Steps to Reproduce

1. Create a `aws_db_instance` resource that includes a username and passes in null for the snapshot id.
1. `terraform apply`

### Important Factoids

This is a bug introduced in #17156

### References

* #17156

### LINKED ISSUE #17722: The RDS instances created from Snapshots cannot be updated anymore
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/aws v3.29.0
```

### Affected Resource(s)

* aws_db_instance

### Terraform Configuration Files

```hcl
resource "aws_db_instance" "db" {
  allocated_storage       = 100
  storage_type            = "gp2"
  engine                  = "postgres"
  engine_version          = "11.5"
  instance_class          = "db.t3.micro"
  vpc_security_group_ids  = ["sg-EXISTING_SG"]
  db_subnet_group_name    = aws_db_subnet_group.db_sg.name
  parameter_group_name    = "default.postgres11"
  deletion_protection     = false
  skip_final_snapshot     = true
  snapshot_identifier     = "EXISTING_SNAPSHOT"
  tags                    = {
    "foo" = "bar"
  }
  identifier              = "bugcatcher"
  maintenance_window      = "Sun:00:00-Sun:08:00"
}
resource "aws_db_subnet_group" "db_sg" {
  name                    = "bugcatcher"
  subnet_ids              = ["EXISTING_SUBNETS"]
  tags                    = {
    "foo" = "bar"
  }
}

```

### Debug Output

https://gist.github.com/konstl000/3261f63f77c4c3587b6872282ede667b
### Expected Behavior

On the first run, terraform successfully creates a DB instance from the snapshot provided. After this, terraform plan should return the "Infrastructure is up to date" message.

### Actual Behavior
On the first run, terraform successfully creates a DB instance from the snapshot provided. After this, terraform plan exits with a following error message:
```
Error: 1 error occurred:
        * name attribute is not supported with snapshot_identifier when engine is postgres



  on bug.tf line 1, in resource "aws_db_instance" "db":
   1: resource "aws_db_instance" "db" {
```

### Steps to Reproduce

1. `terraform apply`

2. `terraform plan -out plan`

### References

* Seems to be related to https://github.com/hashicorp/terraform-provider-aws/pull/17156
* Also seems that these changes were reverted by the [last commit](https://github.com/hashicorp/terraform-provider-aws/commit/609f858240c60ab8ab9f9c78c7269bf7016bf451) in the repo.

### PR DESCRIPTION
**Pull request by anGie44**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #17712, closes #17722
Relates #17037, #17156

Output from acceptance testing:

```
--- PASS: TestAccAWSDBInstance_MySQL_SnapshotRestoreWithEngineVersion (1192.86s)
```

### Notes
* changes here revert those originally introduced (https://github.com/hashicorp/terraform-provider-aws/pull/17156) to address #17037

### CODE REVIEW

**Comment by YakDriver** [comment]
Here is a sum up of what we've learned going through this.

Original issue #17037 resulted in fix #17156. However, #17037 did not include any configuration detailing how the problem occurred and merely that a problem had occurred. Unfortunatley, the speculative fix in #17156 could not have fixed the issue. The #17037 op was concerned about a diff (`ForceNew`) and all that the #17156 fix did was throw new errors. Throwing errors cannot resolve erroneous diffs.

#17156 resulted in many kinds of problems noted in #17712 and #17722. For example, the `ConflictsWith` addition instantly errored configs with empty `snapshot_identifier`s but `name`. Next, when restoring from an instance with a `name` to an instance without `name` but with `snapshot_identifier`, you'd receive an error on the second apply because of the computed `name`. For example, the config below should be valid but #17156 checks caused the error:

```hcl
resource "aws_db_instance" "db" {
  allocated_storage    = 5
  engine               = "mysql"
  engine_version       = "5.7"
  instance_class       = "db.t3.micro"
  deletion_protection  = false
  skip_final_snapshot  = true
  snapshot_identifier  = aws_db_snapshot.test.db_snapshot_identifier
  tags = {
    "foo" = "bar"
  }
  identifier         = "yakdriver-tf-acc-target"
  maintenance_window = "Sun:00:00-Sun:08:00"
}

resource "aws_db_instance" "source" {
  allocated_storage    = 5
  engine               = "mysql"
  engine_version       = "5.7"
  identifier           = "yakdriver-tf-acc-source"
  instance_class       = "db.t3.micro"
  name                 = "yakdrivertfaccdbtesst"
  password             = "avoid-plaintext-passwords"
  username             = "tfacctest"
  skip_final_snapshot  = true
}

resource "aws_db_snapshot" "test" {
  db_instance_identifier = aws_db_instance.source.id
  db_snapshot_identifier = "yakdriver-tf-acc-snap"
}
```

File: aws/resource_aws_db_instance.go [hunk 1]
```diff
@@ -911,7 +894,14 @@ func resourceAwsDbInstanceCreate(d *schema.ResourceData, meta interface{}) error
 		}
 
 		if attr, ok := d.GetOk("name"); ok {
-			opts.DBName = aws.String(attr.(string))
+			// "Note: This parameter [DBName] doesn't apply to the MySQL, PostgreSQL, or MariaDB engines."
```
Comment (YakDriver) [inline aws/resource_aws_db_instance.go:897]: This section is going to create problems. On _restore_, the `DBName` doesn't apply but will be ignored. However, on _create_, MySQL, Postgres, and MariaDB need to the `DBName`.
https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBInstance.html

**Review by YakDriver — CHANGES_REQUESTED** [review]

**Review by YakDriver — APPROVED** [review]
Looking good! 🎉 

This is reverting a previous change that didn't include new acceptances tests so I'm using a random set of acceptance tests to ensure nothing went awry. (Daily tests will ensure the rest work as well.)

GovCloud:
```
--- PASS: TestAccAWSDBInstance_MinorVersion (330.86s)
--- PASS: TestAccAWSDBInstance_namePrefix (362.36s)
--- PASS: TestAccAWSDBInstance_DeletionProtection (399.23s)
--- PASS: TestAccAWSDBInstance_basic (448.55s)
--- PASS: TestAccAWSDBInstance_kmsKey (452.26s)
--- PASS: TestAccAWSDBInstance_EnabledCloudwatchLogsExports_Postgresql (470.55s)
--- PASS: TestAccAWSDBInstance_Password (474.81s)
--- PASS: TestAccAWSDBInstance_iamAuth (498.87s)
--- PASS: TestAccAWSDBInstance_IsAlreadyBeingDeleted (525.67s)
--- PASS: TestAccAWSDBInstance_DbSubnetGroupName (531.73s)
--- PASS: TestAccAWSDBInstance_DbSubnetGroupName_VpcSecurityGroupIds (531.89s)
```

`us-west-2`:
```
--- PASS: TestAccAWSDBInstance_CACertificateIdentifier (330.23s)
--- PASS: TestAccAWSDBInstance_generatedName (382.24s)
--- PASS: TestAccAWSDBInstance_DbSubnetGroupName_VpcSecurityGroupIds (489.53s)
--- PASS: TestAccAWSDBInstance_MaxAllocatedStorage (505.53s)
--- PASS: TestAccAWSDBInstance_optionGroup (530.20s)
--- PASS: TestAccAWSDBInstance_cloudwatchLogsExportConfiguration (564.96s)
--- PASS: TestAccAWSDBInstance_portUpdate (645.56s)
--- PASS: TestAccAWSDBInstance_EnabledCloudwatchLogsExports_MSSQL (677.47s)
--- PASS: TestAccAWSDBInstance_MonitoringRoleArn_RemovedToEnabled (724.28s)
--- PASS: TestAccAWSDBInstance_NoDeleteAutomatedBackups (737.83s)
--- PASS: TestAccAWSDBInstance_FinalSnapshotIdentifier_SkipFinalSnapshot (789.48s)
--- PASS: TestAccAWSDBInstance_FinalSnapshotIdentifier (832.39s)
--- PASS: TestAccAWSDBInstance_EnabledCloudwatchLogsExports_Oracle (832.94s)
```
