### PR TITLE
dynamodb/table: Fix ability to disable dynamodb table ttl

### LINKED ISSUE #39195: [Bug]: Unable to disable Dynamodb table TTL
### Terraform Core Version

1.6.5

### AWS Provider Version

5.66.0

### Affected Resource(s)

aws_dynamodb_table

### Expected Behavior

I should be able to disable TTLs on my dynamo table in Terraform:

```hcl
  ttl {
    enabled = false
    attribute_name = "ttlK"
  }
```

### Actual Behavior

I get a provider validation error that i cannot have a name while ttl.enabled is false.  If I try to remove the name, I get an error from the Dynamo API itself.

### Relevant Error/Panic Output Snippet

```console
│ Error: updating AWS DynamoDB Table (ttl_test): updating Time To Live: operation error DynamoDB: UpdateTimeToLive, https response error StatusCode: 400, RequestID: 4QV78T54MGHV732LBM9N0SUOIVVV4KQNSO5AEMVJF66Q9ASUAAJG, api error ValidationException: 1 validation error detected: Value '' at 'timeToLiveSpecification.attributeName' failed to satisfy constraint: Member must have length greater than or equal to 1
│ 
│   with aws_dynamodb_table.ttl_test,
│   on ttl_test.tf line 1, in resource "aws_dynamodb_table" "ttl_test":
│    1: resource "aws_dynamodb_table" "ttl_test" {
│ 
╵
```

and

```console
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Invalid Attribute Combination
│ 
│ Attribute "ttl[0].attribute_name" cannot be specified when "ttl[0].enabled" is "false".
│ ttl[0].attribute_name
│ 
│   with aws_dynamodb_table.ttl_test,
│   on ttl_test.tf line 1, in resource "aws_dynamodb_table" "ttl_test":
│    1: resource "aws_dynamodb_table" "ttl_test" {
│
```

### Terraform Configuration Files

```hcl
resource "aws_dynamodb_table" "ttl_test" {
  name = "ttl_test"

  billing_mode = "PAY_PER_REQUEST"

  hash_key  = "PK"
  range_key = "SK"

  attribute {
    name = "PK"
    type = "S"
  }

  attribute {
    name = "SK"
    type = "S"
  }

  ttl {
    enabled = true
    attribute_name = "ttlK"
  }
}
```

### Steps to Reproduce

1. Create the table described in the TF config files above
2. Try to set `enabled=false` on line 20, produces first error listed in "Relevant error" section
3. Additionally try to comment out attribute name: `#attribute_name = "ttlK"` to get the second error

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

I'm pretty sure this validation check is the issue: 
https://github.com/hashicorp/terraform-provider-aws/blame/main/internal/service/dynamodb/table.go#L2471-L2475

With it, there is seemingly no way to disable TTLs via Terraform

### References

_No response_

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by YakDriver**
### Description

Brief history:
* #10304 describes a diff bug caused by `ttl.0.attribute_name` going out to AWS but not coming back
* #37991 attempted to fix the diff by applying validation preventing `ttl.0.attribute_name` from being set if `ttl.0.enabled` is `false`. That fixed the diff but caused another problem.
* In order to disable TTL on a table, you *_must_* pass in `ttl.0.attribute_name`, even though AWS will not return it. #37991 made it impossible to disable TTL.
* This PR removes the validation preventing `ttl.0.attribute_name` from being set if `ttl.0.enabled` is `false` and addresses the diff issue with a `DiffSuppressFunc`.
* Unfortunately, testing this fix is complicated because AWS will not allow you to disable TTL in the first hour it's enabled. I've added a test that sleeps an hour so it can verify that disabling works.

### Relations

Closes #39195
Relates #37991 

### References

* #37991
* #10304

### Output from Acceptance Testing

```console
% make t T=TestAccDynamoDBTable_TTL_updateDisable K=dynamodb
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.2 test ./internal/service/dynamodb/... -v -count 1 -parallel 20 -run='TestAccDynamoDBTable_TTL_updateDisable'  -timeout 360m
2024/11/07 13:57:43 Initializing Terraform AWS Provider...
=== RUN   TestAccDynamoDBTable_TTL_updateDisable
=== PAUSE TestAccDynamoDBTable_TTL_updateDisable
=== CONT  TestAccDynamoDBTable_TTL_updateDisable
--- PASS: TestAccDynamoDBTable_TTL_updateDisable (3639.96s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/dynamodb	3643.912s
```

### CODE REVIEW

File: internal/service/dynamodb/table_test.go [hunk 1]
```diff
@@ -1606,6 +1607,83 @@ func TestAccDynamoDBTable_TTL_update(t *testing.T) {
...
+				ImportState:       true,
+				ImportStateVerify: true,
+			},
+			{
+				PreConfig: func() {
+					// AWS does not allow disabling TTL for an hour after it was enabled. Otherwise, it
+					// will return the following error: ValidationException: Time to live has been
+					// modified multiple times within a fixed interval
+					time.Sleep(60 * time.Minute)
+				},
```
Comment (jar-b) [inline internal/service/dynamodb/table_test.go:1655]: Should we consider gating this behind an environment variable (`ENABLE_DYNAMODB_TTL_DISABLE` or similar) in addition to the standard `-short` directive? 

The other table tests aren't quite on the order of hours, so I could see this causing friction when running acceptance tests to validate changes to other arguments.

**Review by jar-b — APPROVED** [review]
LGTM 🚀

Looks good! Just one suggestion on gating the new test.

File: internal/service/dynamodb/table_test.go (hunk 1 above)
Comment (YakDriver) [reply internal/service/dynamodb/table_test.go:1655]: My concern there is that the test wouldn't be run ever then.... I definitely see your point and maybe we circle back and add it but would like to see it run sometimes to make sure we don't break it again for a little bit.
