### PR TITLE
aws_sagemaker_image_version: fix ResourceInUse errors

### LINKED ISSUE #44693: `aws_sagemaker_image_version`:  ResourceInUse when multiple image versions are created / deleted for the same image (image_name)
### Terraform and AWS Provider Version

```console
Terraform v1.13.4
on darwin_arm64
```

### Affected Resource(s) or Data Source(s)

* `aws_sagemaker_image_version`

### Expected Behavior

All resources are created / deleted correctly

### Actual Behavior

400 Error from AWS API : ResourceInUse

### Relevant Error/Panic Output

```console
Error: creating SageMaker AI Image Version (...): operation error SageMaker: CreateImageVersion, https response error StatusCode: 400, RequestID: 83aac55f-307d-4a13-ae52-799d1b053236, ResourceInUse: Resource was modified concurrently

Error: deleting SageMaker AI Image Version (...): operation error SageMaker: DeleteImageVersion, https response error StatusCode: 400, RequestID: 2c25eee7-fb21-49ee-b81e-4e48348e0672, ResourceInUse: ImageVersion (...) is being deleted

```

### Sample Terraform Configuration

<details open>
<summary>Click to expand configuration</summary>

```hcl
resource aws_sagemaker_image_version versions {
   count = 100

   image_name = "my-image" #same for all
   base_image  = "different ECR sha256 for each"
   job_type        = "NOTEBOOK_KERNEL"
   processor      = "GPU"
   aliases           =  ["HERE : list of tags based on ECR tags"]
}
```
</details>

### Steps to Reproduce

1. Apply
or 
1. Destroy

### Debug Logging

<details open>
<summary>Click to expand log output</summary>

```console

```
</details>

### GenAI / LLM Assisted Development

n/a

### Important Facts and References

_No response_

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by psantus**
### Description
See #44693 for bug description

Solution: we apply Mutex on Create and Delete operations. Slows down a bit but makes it reliable.

### Relations
Closes #44693

### References
https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateImageVersion.html

### Output from Acceptance Testing

** With Mutex ** 

```console
% TF_ACC=1 SAGEMAKER_IMAGE_VERSION_BASE_IMAGE="MASKED.PUT_EXISTING_ECR_URI_HERE" go test -v ./internal/service/sagemaker -run TestAccSageMakerImageVersion_concurrentCreation -timeout 30m
2025/10/17 15:11:09 Creating Terraform AWS Provider (SDKv2-style)...
2025/10/17 15:11:09 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccSageMakerImageVersion_concurrentCreation
=== PAUSE TestAccSageMakerImageVersion_concurrentCreation
=== CONT  TestAccSageMakerImageVersion_concurrentCreation
--- PASS: TestAccSageMakerImageVersion_concurrentCreation (441.94s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker  446.801s

...
```

** Without Mutex ** 

```console
% TF_ACC=1 SAGEMAKER_IMAGE_VERSION_BASE_IMAGE="MASKED.PUT_EXISTING_ECR_URI_HERE" go test -v ./internal/service/sagemaker -run TestAccSageMakerImageVersion_concurrentCreation -timeout 30m
2025/10/17 15:03:11 Creating Terraform AWS Provider (SDKv2-style)...
2025/10/17 15:03:11 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccSageMakerImageVersion_concurrentCreation
=== PAUSE TestAccSageMakerImageVersion_concurrentCreation
=== CONT  TestAccSageMakerImageVersion_concurrentCreation
    image_version_test.go:488: Step 1/1 error: Error running apply: exit status 1
        
        Error: creating SageMaker AI Image Version tf-acc-test-1054052909525976931: operation error SageMaker: CreateImageVersion, https response error StatusCode: 400, RequestID: 0f4e652d-d0c2-407e-94fc-72b1ebeccdd7, ResourceInUse: Resource was modified concurrently
        
          with aws_sagemaker_image_version.test4,
          on terraform_plugin_test.tf line 56, in resource "aws_sagemaker_image_version" "test4":
          56: resource "aws_sagemaker_image_version" "test4" {
        
        
        Error: creating SageMaker AI Image Version tf-acc-test-1054052909525976931: operation error SageMaker: CreateImageVersion, https response error StatusCode: 400, RequestID: 83aac55f-307d-4a13-ae52-799d1b053236, ResourceInUse: Resource was modified concurrently
        
          with aws_sagemaker_image_version.test26,
          on terraform_plugin_test.tf line 166, in resource "aws_sagemaker_image_version" "test26":
         166: resource "aws_sagemaker_image_version" "test26" {
        
        
        Error: creating SageMaker AI Image Version tf-acc-test-1054052909525976931: operation error SageMaker: CreateImageVersion, https response error StatusCode: 400, RequestID: 0d07b9d6-86d3-4877-a931-9cf141f968e5, ResourceInUse: Resource was modified concurrently
        
          with aws_sagemaker_image_version.test69,
          on terraform_plugin_test.tf line 381, in resource "aws_sagemaker_image_version" "test69":
         381: resource "aws_sagemaker_image_version" "test69" {
        
--- FAIL: TestAccSageMakerImageVersion_concurrentCreation (334.01s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker  339.090s
FAIL

...
```

### CODE REVIEW

**Comment by psantus** [comment]
* All SDK v2 has been removed in favor of Terraform Plugin Framework, 
* PR has been rebased
* Tests pass

File: internal/service/sagemaker/image_version_test.go [hunk 1]
```diff
@@ -479,3 +480,74 @@ resource "aws_sagemaker_image_version" "test" {
...
+					resource.TestCheckResourceAttr("aws_sagemaker_image_version.test70", "image_name", rName),
+				),
+			},
+		},
+	})
+}
+
+func testAccImageVersionConfig_concurrent(rName, baseImage string) string {
+	var versions strings.Builder
+	for i := 1; i <= 80; i++ {
```
Comment (jar-b) [inline internal/service/sagemaker/image_version_test.go]: Given the number of resources this will create, we might want to consider making this count configurable, or set via an environment variable to gate it from running during normal test execution. It might also be worth switching to the built-in `count` Terraform argument rather than concatenating literal strings for each version.

File: internal/service/sagemaker/image_version.go [hunk 2]
```diff
@@ -128,6 +128,9 @@ func resourceImageVersionCreate(ctx context.Context, d *schema.ResourceData, met
 	conn := meta.(*conns.AWSClient).SageMakerClient(ctx)
 
 	name := d.Get("image_name").(string)
+
+	conns.GlobalMutexKV.Lock(name)
+	defer conns.GlobalMutexKV.Unlock(name)
```
Comment (jar-b) [inline internal/service/sagemaker/image_version.go]: Could this wrap just the `CreateImageVersion` call rather than the entirety of the Terraform Create op?

Comment (psantus) [reply internal/service/sagemaker/image_version.go]: done

File: internal/service/sagemaker/image_version_test.go (hunk 1 above)
Comment (psantus) [reply internal/service/sagemaker/image_version_test.go]: Done

**Comment by psantus** [comment]
review comments adresseed, PR rebased.

**Comment by jar-b** [comment]
Thanks for your contribution, @psantus! 👍
