### PR TITLE
`aws_opensearch_domain`: Omit IOPS/Throughput when not supported

### LINKED ISSUE #27467: aws_opensearch_domain ebs_options throughput attribute populated for non-gp3 volume types? [Bug]:
### Terraform Core Version

1.3.3

### AWS Provider Version

4.36.1

### Affected Resource(s)

* aws_opensearch_domain

### Expected Behavior

* When I add the `volume_type` attribute to `aws_opensearch_domain.ebs_options`, and set it to `standard`, no errors related to `throughput` arise, since the `throughput` attribute is only applicable to the gp3 volume type. 

### Actual Behavior

 When I add the `volume_type` attribute to `aws_opensearch_domain.ebs_options.volume_type`, and set it to `standard`(or `gp2`), I get the error: 
 
` Error: ValidationException: Throughput is only valid when volume type is GP3.`

I get the same error if I explicitly set `throughput` to `null`. I searched existing issues, and google for anything useful but came up dry & this issue did not seem to exist in this system. 

### Relevant Error/Panic Output Snippet

_No response_

### Terraform Configuration Files

Here's the relevant config. Note that this started because I changed the value of the incoming instance_type variable from a t3-class instance to an m4.xlarge.search instance type. At that time, ebs_options only had `ebs_enabled` and `volume_size` attributes, and I got the error ` Error: ValidationException: EBS volume-types :[standard, io1, gp2] must be selected for m4.xlarge.search`. So I added a `volume_type` attribute and that's when I got the error I'm reporting about here: ` Error: ValidationException: Throughput is only valid when volume type is GP3.`. 

This config will generate the error ` Error: ValidationException: Throughput is only valid when volume type is GP3.` if the instance_type is set to `m4.xlarge.search`. 

```
resource "aws_opensearch_domain" "opensearch" {
  domain_name    = "opensearch-${var.environment}"
  engine_version = "OpenSearch_1.3"

  cluster_config {
    instance_type            = var.opensearch_instance_type
    instance_count           = var.opensearch_instance_count
    dedicated_master_enabled = var.opensearch_dedicated_master_enabled
    warm_enabled             = var.opensearch_warm_enabled
    zone_awareness_enabled = false
  }

  ebs_options {
    ebs_enabled = true
    volume_size = 10
    volume_type = "standard"
  }

  log_publishing_options {
    cloudwatch_log_group_arn = aws_cloudwatch_log_group.opensearch_logs.arn
    log_type                 = "INDEX_SLOW_LOGS"
  }

  vpc_options {
    subnet_ids = toset(var.opensearch_vpc_options_subnet_ids)
    security_group_ids = [
      aws_security_group.opensearch.id,
      var.sg_1,
      var.sg_2
    ]
  }
}
```

### Steps to Reproduce

* Configure aws_opensearch_domain.cluster_config.instance_type to m4.xlarge.search
* Configure ebs_options.volume_type = "standard" 
* Run terraform apply

### Debug Output

If I don't add the volume_type attribute, but my instance type is m4.xlarge.search, I get the error `Error: ValidationException: EBS volume-types :[standard, io1, gp2] must be selected for m4.xlarge.search`, and the debug log shows the following: 

```
22759             "ebs_options": [
22760               {
22761                 "ebs_enabled": true,
22762                 "iops": 3000,
22763                 "throughput": 125,
22764                 "volume_size": 10,
22765                 "volume_type": "standard"
22766               }
22767             ],
```

When I add `volume_type` and set it to `standard` and don't add a `throughput` attribute, or explicitly set `throughput` to `null`, the debug log shows this: 

```
22775             "ebs_options": [
22776               {
22777                 "ebs_enabled": true,
22778                 "iops": 3000,
22779                 "throughput": 125,
22780                 "volume_size": 10,
22781                 "volume_type": "standard"
22782               }
```

It appears that `throughput` is set to `125` as a default and cannot be overridden by a null, and is applied to volume_types for which that option is not appropriate. 

### Panic Output

_No response_

### Important Factoids

I'm new to tf, but I don't think I'm doing anything exotic here. 

### References

Both the tf provider docs & the AWS docs say that `throughput` is only applicable to gp3 volume type. It is not an option for any other volume_type. 
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opensearch_domain#throughput
https://docs.aws.amazon.com/opensearch-service/latest/developerguide/configuration-api.html

### Would you like to implement a fix?

_No response_

### PR DESCRIPTION
**Pull request by jar-b**
### Description
This fix prevents the `Throughput` and `Iops` EBS options from being included in the input struct when the specified volume type does not support them. 

Specifically, this can happen when a configuration uses a `gp3` volume type without specifying `iops` or `throughput`, then the volume type changes to a type that doesn't support these arguments. On the first apply, the default values set by AWS are written to state. On the subsequent apply these should be omitted from the UpdateDomain request input to avoid a `ValidationException`.

### Relations
Closes #27467

### References
https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/opensearch@v1.12.0/types#EBSOptions

### Output from Acceptance Testing

```console
$ make testacc PKG=opensearch TESTS=TestAccOpenSearchDomain_VolumeType
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/opensearch/... -v -count 1 -parallel 20 -run='TestAccOpenSearchDomain_VolumeType'  -timeout 180m
=== RUN   TestAccOpenSearchDomain_VolumeType_update
=== PAUSE TestAccOpenSearchDomain_VolumeType_update
=== RUN   TestAccOpenSearchDomain_VolumeType_GP3ToGP2
=== PAUSE TestAccOpenSearchDomain_VolumeType_GP3ToGP2
=== RUN   TestAccOpenSearchDomain_VolumeType_missing
=== PAUSE TestAccOpenSearchDomain_VolumeType_missing
=== CONT  TestAccOpenSearchDomain_VolumeType_update
=== CONT  TestAccOpenSearchDomain_VolumeType_missing
=== CONT  TestAccOpenSearchDomain_VolumeType_GP3ToGP2
--- PASS: TestAccOpenSearchDomain_VolumeType_missing (1195.95s)
--- PASS: TestAccOpenSearchDomain_VolumeType_GP3ToGP2 (3440.65s)
--- PASS: TestAccOpenSearchDomain_VolumeType_update (4052.78s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/opensearch 4055.888s
```

```console
$ go test -v ./internal/service/opensearch/... -run ^TestEBS
=== RUN   TestEBSVolumeTypePermitsIopsInput
=== PAUSE TestEBSVolumeTypePermitsIopsInput
=== RUN   TestEBSVolumeTypePermitsThroughputInput
=== PAUSE TestEBSVolumeTypePermitsThroughputInput
=== CONT  TestEBSVolumeTypePermitsIopsInput
=== RUN   TestEBSVolumeTypePermitsIopsInput/empty
=== PAUSE TestEBSVolumeTypePermitsIopsInput/empty
=== RUN   TestEBSVolumeTypePermitsIopsInput/gp2
=== PAUSE TestEBSVolumeTypePermitsIopsInput/gp2
=== RUN   TestEBSVolumeTypePermitsIopsInput/gp3
=== PAUSE TestEBSVolumeTypePermitsIopsInput/gp3
=== RUN   TestEBSVolumeTypePermitsIopsInput/io1
=== PAUSE TestEBSVolumeTypePermitsIopsInput/io1
=== CONT  TestEBSVolumeTypePermitsThroughputInput
=== RUN   TestEBSVolumeTypePermitsIopsInput/standard
=== PAUSE TestEBSVolumeTypePermitsIopsInput/standard
=== RUN   TestEBSVolumeTypePermitsThroughputInput/empty
=== CONT  TestEBSVolumeTypePermitsIopsInput/empty
=== PAUSE TestEBSVolumeTypePermitsThroughputInput/empty
=== CONT  TestEBSVolumeTypePermitsIopsInput/gp3
=== CONT  TestEBSVolumeTypePermitsIopsInput/gp2
=== CONT  TestEBSVolumeTypePermitsIopsInput/io1
=== CONT  TestEBSVolumeTypePermitsIopsInput/standard
--- PASS: TestEBSVolumeTypePermitsIopsInput (0.00s)
    --- PASS: TestEBSVolumeTypePermitsIopsInput/empty (0.00s)
    --- PASS: TestEBSVolumeTypePermitsIopsInput/gp3 (0.00s)
    --- PASS: TestEBSVolumeTypePermitsIopsInput/gp2 (0.00s)
    --- PASS: TestEBSVolumeTypePermitsIopsInput/io1 (0.00s)
    --- PASS: TestEBSVolumeTypePermitsIopsInput/standard (0.00s)
=== RUN   TestEBSVolumeTypePermitsThroughputInput/gp2
=== PAUSE TestEBSVolumeTypePermitsThroughputInput/gp2
=== RUN   TestEBSVolumeTypePermitsThroughputInput/gp3
=== PAUSE TestEBSVolumeTypePermitsThroughputInput/gp3
=== RUN   TestEBSVolumeTypePermitsThroughputInput/io1
=== PAUSE TestEBSVolumeTypePermitsThroughputInput/io1
=== RUN   TestEBSVolumeTypePermitsThroughputInput/standard
=== PAUSE TestEBSVolumeTypePermitsThroughputInput/standard
=== CONT  TestEBSVolumeTypePermitsThroughputInput/empty
=== CONT  TestEBSVolumeTypePermitsThroughputInput/standard
=== CONT  TestEBSVolumeTypePermitsThroughputInput/io1
=== CONT  TestEBSVolumeTypePermitsThroughputInput/gp2
=== CONT  TestEBSVolumeTypePermitsThroughputInput/gp3
--- PASS: TestEBSVolumeTypePermitsThroughputInput (0.00s)
    --- PASS: TestEBSVolumeTypePermitsThroughputInput/empty (0.00s)
    --- PASS: TestEBSVolumeTypePermitsThroughputInput/standard (0.00s)
    --- PASS: TestEBSVolumeTypePermitsThroughputInput/io1 (0.00s)
    --- PASS: TestEBSVolumeTypePermitsThroughputInput/gp2 (0.00s)
    --- PASS: TestEBSVolumeTypePermitsThroughputInput/gp3 (0.00s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/opensearch 2.908s
```

---

Output of the new acceptance test prior to the expander changes that confirms the behavior:

```console
$ make testacc PKG=opensearch TESTS=TestAccOpenSearchDomain_VolumeType_gp3ToStandard
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/opensearch/... -v -count 1 -parallel 20 -run='TestAccOpenSearchDomain_VolumeType_gp3ToStandard'  -timeout 180m
=== RUN   TestAccOpenSearchDomain_VolumeType_gp3ToStandard
=== PAUSE TestAccOpenSearchDomain_VolumeType_gp3ToStandard
=== CONT  TestAccOpenSearchDomain_VolumeType_gp3ToStandard
    domain_test.go:1509: Step 3/3 error: Error running apply: exit status 1

        Error: ValidationException: Throughput is only valid when volume type is GP3.

          with aws_opensearch_domain.test,
          on terraform_plugin_test.tf line 2, in resource "aws_opensearch_domain" "test":
           2: resource "aws_opensearch_domain" "test" {

--- FAIL: TestAccOpenSearchDomain_VolumeType_gp3ToStandard (1387.59s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/opensearch 1390.825s
FAIL
make: *** [testacc] Error 1
```

### CODE REVIEW

File: internal/service/opensearch/domain_test.go [hunk 1]
```diff
@@ -1493,6 +1545,54 @@ func TestAccOpenSearchDomain_VolumeType_update(t *testing.T) {
 		}})
 }
 
+// Verifies that EBS volume_type can be changed from gp3 to a type which does not
+// support the throughput and iops input values (ex. gp2)
+//
+// Reference: https://github.com/hashicorp/terraform-provider-aws/issues/27467
+func TestAccOpenSearchDomain_VolumeType_GP3ToGP2(t *testing.T) {
```
Comment (YakDriver) [inline internal/service/opensearch/domain_test.go:1552]:
```suggestion
func TestAccOpenSearchDomain_VolumeType_gp3ToGP2(t *testing.T) {
```
Nit: The final tuple/clause/thing should be lowercase in Go.

File: internal/service/opensearch/domain_test.go [hunk 2]
```diff
@@ -2241,6 +2341,42 @@ resource "aws_opensearch_domain" "test" {
...
 }
 
+func testAccDomainConfig_clusterEBSVolumeGP3DefaultIopsThroughput(rName string, volumeSize int) string {
+	return fmt.Sprintf(`
+resource "aws_opensearch_domain" "test" {
+  domain_name = %[1]q
+
+  ebs_options {
+    ebs_enabled = true
+    volume_size = %d
```
Comment (YakDriver) [inline internal/service/opensearch/domain_test.go:2351]:
```suggestion
    volume_size = %[2]d
```

File: internal/service/opensearch/domain_test.go [hunk 3]
```diff
@@ -2241,6 +2341,42 @@ resource "aws_opensearch_domain" "test" {
...
+}
+
+func testAccDomainConfig_clusterEBSVolumeGP2(rName string, volumeSize int) string {
+	return fmt.Sprintf(`
+resource "aws_opensearch_domain" "test" {
+  domain_name = %[1]q
+
+  ebs_options {
+    ebs_enabled = true
+    volume_size = %d
```
Comment (YakDriver) [inline internal/service/opensearch/domain_test.go:2369]:
```suggestion
    volume_size = %[2]d
```

**Review by YakDriver — APPROVED** [review]
Looks good, couple small things. 🎉 

```console
% go test -v ./internal/service/opensearch/... -run ^TestEBS
=== RUN   TestEBSVolumeTypePermitsIopsInput
=== PAUSE TestEBSVolumeTypePermitsIopsInput
=== RUN   TestEBSVolumeTypePermitsThroughputInput
=== PAUSE TestEBSVolumeTypePermitsThroughputInput
=== CONT  TestEBSVolumeTypePermitsIopsInput
=== RUN   TestEBSVolumeTypePermitsIopsInput/empty
=== PAUSE TestEBSVolumeTypePermitsIopsInput/empty
=== RUN   TestEBSVolumeTypePermitsIopsInput/gp2
=== PAUSE TestEBSVolumeTypePermitsIopsInput/gp2
=== CONT  TestEBSVolumeTypePermitsThroughputInput
=== RUN   TestEBSVolumeTypePermitsIopsInput/gp3
=== PAUSE TestEBSVolumeTypePermitsIopsInput/gp3
=== RUN   TestEBSVolumeTypePermitsThroughputInput/empty
=== RUN   TestEBSVolumeTypePermitsIopsInput/io1
=== PAUSE TestEBSVolumeTypePermitsIopsInput/io1
=== RUN   TestEBSVolumeTypePermitsIopsInput/standard
=== PAUSE TestEBSVolumeTypePermitsIopsInput/standard
=== PAUSE TestEBSVolumeTypePermitsThroughputInput/empty
=== CONT  TestEBSVolumeTypePermitsIopsInput/empty
=== RUN   TestEBSVolumeTypePermitsThroughputInput/gp2
=== PAUSE TestEBSVolumeTypePermitsThroughputInput/gp2
=== CONT  TestEBSVolumeTypePermitsIopsInput/standard
=== RUN   TestEBSVolumeTypePermitsThroughputInput/gp3
=== PAUSE TestEBSVolumeTypePermitsThroughputInput/gp3
=== CONT  TestEBSVolumeTypePermitsIopsInput/io1
=== CONT  TestEBSVolumeTypePermitsIopsInput/gp3
=== RUN   TestEBSVolumeTypePermitsThroughputInput/io1
=== CONT  TestEBSVolumeTypePermitsIopsInput/gp2
=== PAUSE TestEBSVolumeTypePermitsThroughputInput/io1
--- PASS: TestEBSVolumeTypePermitsIopsInput (0.00s)
    --- PASS: TestEBSVolumeTypePermitsIopsInput/empty (0.00s)
    --- PASS: TestEBSVolumeTypePermitsIopsInput/standard (0.00s)
    --- PASS: TestEBSVolumeTypePermitsIopsInput/io1 (0.00s)
    --- PASS: TestEBSVolumeTypePermitsIopsInput/gp3 (0.00s)
    --- PASS: TestEBSVolumeTypePermitsIopsInput/gp2 (0.00s)
=== RUN   TestEBSVolumeTypePermitsThroughputInput/standard
=== PAUSE TestEBSVolumeTypePermitsThroughputInput/standard
=== CONT  TestEBSVolumeTypePermitsThroughputInput/empty
=== CONT  TestEBSVolumeTypePermitsThroughputInput/standard
=== CONT  TestEBSVolumeTypePermitsThroughputInput/gp2
=== CONT  TestEBSVolumeTypePermitsThroughputInput/io1
=== CONT  TestEBSVolumeTypePermitsThroughputInput/gp3
--- PASS: TestEBSVolumeTypePermitsThroughputInput (0.00s)
    --- PASS: TestEBSVolumeTypePermitsThroughputInput/empty (0.00s)
    --- PASS: TestEBSVolumeTypePermitsThroughputInput/standard (0.00s)
    --- PASS: TestEBSVolumeTypePermitsThroughputInput/gp2 (0.00s)
    --- PASS: TestEBSVolumeTypePermitsThroughputInput/io1 (0.00s)
    --- PASS: TestEBSVolumeTypePermitsThroughputInput/gp3 (0.00s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/opensearch	1.639s
```
