### PR TITLE
[bugfix] aws_cloudwatch_log_metric_filter: Fix validation to count `pattern` length in UTF-8 characters

### LINKED ISSUE #47274: aws_cloudwatch_log_metric_filter: pattern length validation incorrectly counts bytes instead of characters for multibyte (UTF-8) strings
### Terraform and AWS Provider Version

```console
Terraform v1.4.4 on darwin_arm64
AWS Provider v4.14.0 (also reproduced with v6.37.0)
```

### Affected Resource(s)

- `aws_cloudwatch_log_metric_filter`

### Expected Behavior

The `pattern` attribute validation should count characters (Unicode code points), not bytes. The AWS API accepts patterns up to 1024 characters, regardless of byte length. A pattern containing multibyte characters (e.g., Japanese) that is 803 characters long should pass validation.

### Actual Behavior

The validation uses Go's `len()` which returns the byte length of a UTF-8 string. A pattern that is 803 characters but 1419 bytes is rejected with:
```
expected length of pattern to be in the range (0 - 1024)
```
The same pattern can be successfully created via the AWS CLI (`aws logs put-metric-filter`), confirming that the AWS API accepts it.

### Relevant Error/Panic Output

```console
│ Error: expected length of pattern to be in the range (0 - 1024), got [(msg = "*ERROR*") && (msg != "*テスト除外パターン０１*") && (msg != "*テスト除外パターン０２*") && (msg != "*テスト除外パターン０３*") && ... && (msg != "*テスト除外パターン２８*")]
```

### Sample Terraform Configuration

<details open>
<summary>Click to expand configuration</summary>

```hcl
resource "aws_cloudwatch_log_metric_filter" "example" {
  name           = "MultibyteLengthTest"
  # This pattern is 803 characters but 1419 bytes due to Japanese (multibyte) characters.
  # AWS API accepts this pattern via CLI, but Terraform rejects it.
  pattern        = "[(msg = \"*ERROR*\") && (msg != \"*テスト除外パターン０１*\") && (msg != \"*テスト除外パターン０２*\") && (msg != \"*テスト除外パターン０３*\") && (msg != \"*テスト除外パターン０４*\") && (msg != \"*テスト除外パターン０５*\") && (msg != \"*テスト除外パターン０６*\") && (msg != \"*テスト除外パターン０７*\") && (msg != \"*テスト除外パターン０８*\") && (msg != \"*テスト除外パターン０９*\") && (msg != \"*テスト除外パターン１０*\") && (msg != \"*テスト除外パターン１１*\") && (msg != \"*テスト除外パターン１２*\") && (msg != \"*テスト除外パターン１３*\") && (msg != \"*テスト除外パターン１４*\") && (msg != \"*テスト除外パターン１５*\") && (msg != \"*テスト除外パターン１６*\") && (msg != \"*テスト除外パターン１７*\") && (msg != \"*テスト除外パターン１８*\") && (msg != \"*テスト除外パターン１９*\") && (msg != \"*テスト除外パターン２０*\") && (msg != \"*テスト除外パターン２１*\") && (msg != \"*テスト除外パターン２２*\") && (msg != \"*テスト除外パターン２３*\") && (msg != \"*テスト除外パターン２４*\") && (msg != \"*テスト除外パターン２５*\") && (msg != \"*テスト除外パターン２６*\") && (msg != \"*テスト除外パターン２７*\") && (msg != \"*テスト除外パターン２８*\")]"
  log_group_name = aws_cloudwatch_log_group.example.name

  metric_transformation {
    name          = "ErrorCount"
    namespace     = "Custom/Test"
    value         = "1"
    default_value = 0
  }
}

resource "aws_cloudwatch_log_group" "example" {
  name = "/test/multibyte-pattern"
}
```
</details>

### Steps to Reproduce

1. Create a configuration with `aws_cloudwatch_log_metric_filter` using a `pattern` that contains multibyte (e.g., Japanese) characters exceeding 1024 bytes but under 1024 characters
2. Run `terraform validate` or `terraform plan`
3. Observe the validation error
4. Run the equivalent `aws logs put-metric-filter` via AWS CLI — it succeeds

### Debug Logging

_No response_

### GenAI / LLM Assisted Development

n/a

### Important Facts and References

- The root cause appears to be in the validation function `validation.StringLenBetween(0, 1024)`, which uses Go's `len()` (byte count) rather than `utf8.RuneCountInString()` (character count)
- The AWS API documentation states the maximum length is 1024, which appears to refer to characters, not bytes
- Related historical issue: #1810 (pattern limit was corrected from 512 to 1024, but byte vs character distinction was not addressed)

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by tabito-hara**
## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the library.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

### Description

This PR fixes the validation for the `pattern` length to count UTF-8 characters instead of bytes.

* Although the AWS documentation does not explicitly state this, the "1024 character limit" appears to be based on the number of UTF-8 characters rather than bytes.

* A custom validator is implemented to count the length in UTF-8 characters.

* Without this fix, the newly added acceptance test fails when `pattern2` (which exceeds 1024 bytes but is fewer than 1024 UTF-8 characters) is used, reproducing the reported issue.

* When `pattern1` (which exceeds 1024 UTF-8 characters) is used and the validation is removed, the AWS API raises an error due to the string being too long. This indicates that the validation is consistent with the AWS API behavior.

### Relations
Closes #47274 

### References
https://docs.aws.amazon.com/ja_jp/AmazonCloudWatchLogs/latest/APIReference/API_PutMetricFilter.html#CWL-PutMetricFilter-request-filterPattern

### Output from Acceptance Testing

```console
$ make testacc TESTS='TestAccLogsMetricFilter_' PKG=logs 
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 b-aws_cloudwatch_log_metric_filter_validate_char_length_in_utf8 🌿...
TF_ACC=1 go1.25.8 test ./internal/service/logs/... -v -count 1 -parallel 20 -run='TestAccLogsMetricFilter_'  -timeout 360m -vet=off
2026/04/04 09:32:13 Creating Terraform AWS Provider (SDKv2-style)...
2026/04/04 09:32:13 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccLogsMetricFilter_basic
=== PAUSE TestAccLogsMetricFilter_basic
=== RUN   TestAccLogsMetricFilter_disappears
=== PAUSE TestAccLogsMetricFilter_disappears
=== RUN   TestAccLogsMetricFilter_Disappears_logGroup
=== PAUSE TestAccLogsMetricFilter_Disappears_logGroup
=== RUN   TestAccLogsMetricFilter_many
=== PAUSE TestAccLogsMetricFilter_many
=== RUN   TestAccLogsMetricFilter_update
=== PAUSE TestAccLogsMetricFilter_update
=== RUN   TestAccLogsMetricFilter_longPatternInUTF8
=== PAUSE TestAccLogsMetricFilter_longPatternInUTF8
=== CONT  TestAccLogsMetricFilter_basic
=== CONT  TestAccLogsMetricFilter_many
=== CONT  TestAccLogsMetricFilter_Disappears_logGroup
=== CONT  TestAccLogsMetricFilter_longPatternInUTF8
=== CONT  TestAccLogsMetricFilter_disappears
=== CONT  TestAccLogsMetricFilter_update
--- PASS: TestAccLogsMetricFilter_Disappears_logGroup (34.78s)
--- PASS: TestAccLogsMetricFilter_disappears (35.58s)
--- PASS: TestAccLogsMetricFilter_basic (38.09s)
--- PASS: TestAccLogsMetricFilter_longPatternInUTF8 (39.64s)
--- PASS: TestAccLogsMetricFilter_update (57.35s)
--- PASS: TestAccLogsMetricFilter_many (60.84s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/logs       66.813s
```

### CODE REVIEW

File: internal/service/logs/metric_filter.go [hunk 1]
```diff
@@ -115,6 +117,25 @@ func resourceMetricFilter() *schema.Resource {
 	}
 }
 
+func validatePatternLength() schema.SchemaValidateDiagFunc {
```
Comment (ewbankkit) [inline internal/service/logs/metric_filter.go]: @tabito-hara As this function is more widely useful could you please move it to the `internal/verify` package and name it something like `StringUTF8LenBetween(minVal, maxVal int)` to match the Terraform Plugin Framework equivalent: https://github.com/hashicorp/terraform-plugin-framework-validators/blob/main/stringvalidator/utf8_length_between.go? Thanks.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

**Comment by ewbankkit** [comment]
@tabito-hara Thanks for the contribution :tada: :clap:.
