### PR TITLE
resource/aws_detective_member: Fix "unexpected state" error when adding Organization member account

### LINKED ISSUE #35317: [Bug]: `aws_detective_member`with organization accounts - unexpected state 'ENABLED', wanted target 'INVITED'
### Terraform Core Version

1.6.6

### AWS Provider Version

5.32.1

### Affected Resource(s)

* aws_detective_member

### Expected Behavior

Resource creation is expected without output errors in Terraform.

### Actual Behavior

The resource is created correctly, but there is an output error in Terraform:
```bash
Error: waiting for Detective Member () invited: unexpected state 'ENABLED', wanted target 'INVITED'. last error: %!s(<nil>)
```

### Relevant Error/Panic Output Snippet

```shell
│ Error: waiting for Detective Member () invited: unexpected state 'ENABLED', wanted target 'INVITED'. last error: %!s(<nil>)
│ 
│   with aws_detective_member.this,
│   on main.tf line 1, in resource "aws_detective_member" "this":
│    1: resource "aws_detective_member" "this" {
```

### Terraform Configuration Files

```terraform
resource "aws_detective_organization_admin_account" "this" {
  account_id = "012345678901"
}

resource "aws_detective_member" "this" {
  account_id                 = "123456789012"
  disable_email_notification = true
  email_address              = "email@example.org"
  graph_arn                  = "arn:aws:detective:us-east-1:012345678901:graph:231684d34gh74g4bae1dbc7bd807d02d/123456789012"

  depends_on = [aws_detective_organization_admin_account.this]
}
```

### Steps to Reproduce

```bash
terraform apply
```

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

The bug was originally requested and corrected here: [Enhance aws_detective_member to be compatible with organization accounts](https://github.com/hashicorp/terraform-provider-aws/issues/23459)

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by gdavison**
### Description

When adding an Organization member account to Detective, the provider would return an unexpected state error

> waiting for Detective Member () invited: unexpected state 'ENABLED', wanted target 'INVITED'.

This is because Organization member accounts do not need to be verified.

Also enables testing Detective Organization configurations in existing Organizations.

Adds Detective tests to Org Account CI tests

### Relations

Closes #35317

### Output from Acceptance Testing

```console
% make testacc PKG=detective

--- PASS: TestAccDetective_serial (365.20s)
    --- PASS: TestAccDetective_serial/Member (137.20s)
        --- SKIP: TestAccDetective_serial/Member/message (0.00s)
        --- PASS: TestAccDetective_serial/Member/organization_basic (64.16s)
        --- PASS: TestAccDetective_serial/Member/organization_AutoEnable (73.04s)
        --- SKIP: TestAccDetective_serial/Member/basic (0.00s)
        --- SKIP: TestAccDetective_serial/Member/disappear (0.00s)
    --- PASS: TestAccDetective_serial/OrganizationAdminAccount (87.76s)
        --- PASS: TestAccDetective_serial/OrganizationAdminAccount/MultiRegion (40.92s)
        --- PASS: TestAccDetective_serial/OrganizationAdminAccount/basic (24.64s)
        --- PASS: TestAccDetective_serial/OrganizationAdminAccount/disappears (22.19s)
    --- PASS: TestAccDetective_serial/OrganizationConfiguration (53.73s)
        --- PASS: TestAccDetective_serial/OrganizationConfiguration/basic (53.73s)
    --- PASS: TestAccDetective_serial/Graph (86.51s)
        --- PASS: TestAccDetective_serial/Graph/basic (26.73s)
        --- PASS: TestAccDetective_serial/Graph/disappears (18.87s)
        --- PASS: TestAccDetective_serial/Graph/tags (40.92s)
    --- PASS: TestAccDetective_serial/InvitationAccepter (0.00s)
        --- SKIP: TestAccDetective_serial/InvitationAccepter/basic (0.00s)
```

### CODE REVIEW

File: internal/service/detective/organization_admin_account.go [hunk 1]
```diff
@@ -102,17 +102,20 @@ func resourceOrganizationAdminAccountDelete(ctx context.Context, d *schema.Resou
 	conn := meta.(*conns.AWSClient).DetectiveClient(ctx)
 
 	_, err := conn.DisableOrganizationAdminAccount(ctx, &detective.DisableOrganizationAdminAccountInput{})
-
 	if errs.IsA[*awstypes.ResourceNotFoundException](err) {
 		return diags
 	}
+	// For some reason, the API is returning this instead of `ResourceNotFoundException`
```
Comment (jar-b) [inline internal/service/detective/organization_admin_account.go:108]: 😢

**Review by jar-b — APPROVED** [review]
LGTM 🚀

**Review by jar-b — APPROVED** [review]
