### PR TITLE
fix resourceDashboardUpdate

### LINKED ISSUE #33463: [Bug]: Typo in quicskightschema flattenTableFieldOption
### Terraform Core Version

1.3.4

### AWS Provider Version

5.16.0

### Affected Resource(s)

aws_quicksight_template

### Expected Behavior

The template should be created

### Actual Behavior

The following error gets thrown:

setting definition: Invalid address to set: []string{"definition", "0", "sheets", "0", "visuals", "0", "table_visual", "0", "chart_configuration", "0", "field_options", "0", "selected_field_options", "2", "visbility"}

### Relevant Error/Panic Output Snippet

```shell
Error: setting definition: Invalid address to set: []string{"definition", "0", "sheets", "0", "visuals", "0", "table_visual", "0", "chart_configuration", "0", "field_options", "0", "selected_field_options", "2", "visbility"}
│ 
│   with aws_quicksight_template.enviso_pay,
│   on quicksight.tf line 34, in resource "aws_quicksight_template" "enviso_pay":
│   34: resource "aws_quicksight_template" "template" {
```

### Terraform Configuration Files

Create any template with a table visual and set the visibility.

Fix ->
To fix, change "visbility" to "visibility" in this file:
./internal/service/quicksight/schema/visual_table.go

In this function -> flattenTableFieldOption

### Steps to Reproduce

terraform init
terraform apply

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

Yes

### LINKED ISSUE #35109: [Bug]: Incorrect mapping  in canvas_size_options quicksight analysis
### Terraform Core Version

1.6.6

### AWS Provider Version

5.31.0

### Affected Resource(s)

aws_quicksight_analysis

### Expected Behavior

correct mapping should be 'screen_canvas_size_options' in 

https://github.com/hashicorp/terraform-provider-aws/blob/42bfa9ceb806e63cd08caee579d611f519dbea93/internal/service/quicksight/schema/template_sheet.go#L1740C22-L1740C22

### Actual Behavior

```shell
Error: setting definition: Invalid address to set: []string{"definition", "0", "sheets", "0", "layouts", "0", "configuration", "0", "free_form_layout", "0", "canvas_size_options", "0", "canvas_size_options"}
```

### Relevant Error/Panic Output Snippet

_No response_

### Terraform Configuration Files

```terraform
canvas_size_options {
              screen_canvas_size_options {
                optimized_view_port_width = "1600px"
              }
            }
```

### Steps to Reproduce

N/A

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by dsbibby**
### Description

This PR addresses a bug in the aws_quicksight_dashboard resource.

When terraform updates a dashboard resource, two AWS API calls are made. The first updates the dashboard which results in a new dashboard version. The second call should update the published version of the dashboard to the new version.

The bug manifests when the first call takes a little time, which results in the second call returning an error about the dashboard creation still being in progress.

This is because the provider waits for the dashboard status to change to creation successful, however the API call used is checking the current published version, not the new version just made. As such it returns early and doesn’t actually wait.

This PR fixes this by explicitly waiting for the new version of the dashboard to be created before trying to update the published version.

Additionally this PR fixes two minor typo issues, and an issue caused when the state file for a template contains an empty string, resulting in "Error: a number is required" errors.

### Relations

Closes #33463
Closes #35109

### References

Redacted screenshot showing the failure:
image-20230824-081431

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccQuickSightDashboard PKG=quicksight
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/quicksight/... -v -count 1 -parallel 20 -run='TestAccQuickSightDashboard'  -timeout 360m
?       github.com/hashicorp/terraform-provider-aws/internal/service/quicksight/schema  [no test files]
=== RUN   TestAccQuickSightDashboard_basic
=== PAUSE TestAccQuickSightDashboard_basic
=== RUN   TestAccQuickSightDashboard_disappears
=== PAUSE TestAccQuickSightDashboard_disappears
=== RUN   TestAccQuickSightDashboard_sourceEntity
=== PAUSE TestAccQuickSightDashboard_sourceEntity
=== RUN   TestAccQuickSightDashboard_updateVersionNumber
=== PAUSE TestAccQuickSightDashboard_updateVersionNumber
=== RUN   TestAccQuickSightDashboard_dashboardSpecificConfig
=== PAUSE TestAccQuickSightDashboard_dashboardSpecificConfig
=== CONT  TestAccQuickSightDashboard_basic
=== CONT  TestAccQuickSightDashboard_updateVersionNumber
=== CONT  TestAccQuickSightDashboard_sourceEntity
=== CONT  TestAccQuickSightDashboard_dashboardSpecificConfig
=== CONT  TestAccQuickSightDashboard_disappears
--- PASS: TestAccQuickSightDashboard_disappears (40.98s)
--- PASS: TestAccQuickSightDashboard_dashboardSpecificConfig (45.02s)
--- PASS: TestAccQuickSightDashboard_basic (45.43s)
--- PASS: TestAccQuickSightDashboard_sourceEntity (48.19s)
--- PASS: TestAccQuickSightDashboard_updateVersionNumber (95.68s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/quicksight 99.768s
```

### CODE REVIEW

**Comment by dsbibby** [comment]
Hi, how do I encourage a review of this PR please? It's a pretty minor change to address a nasty bug that is stopping us (and surely others) from using this.

File: internal/service/quicksight/dashboard.go [hunk 1]
```diff
@@ -203,7 +203,7 @@ func resourceDashboardRead(ctx context.Context, d *schema.ResourceData, meta int
 		return diag.FromErr(err)
 	}
 
-	out, err := FindDashboardByID(ctx, conn, d.Id())
+	out, err := FindDashboardByID(ctx, conn, d.Id(), -1)
```
Comment (dev-slatto) [inline internal/service/quicksight/dashboard.go:206]: Do we always want the latest version as this is hardcoded?

Comment (DavidB19456) [reply internal/service/quicksight/dashboard.go:206]: That is the current (as in before this PR) behaviour, so no change to the current behaviour.

That said, we could easily add a version parameter to this `resourceDashboardRead()` function if that would be beneficial for the future?

Comment (atlesp) [reply internal/service/quicksight/dashboard.go:206]: The issue this MR tries to fix is urgent since the current provider version makes it impossible to update a dashboard. 

To update a dashboard we currently use the workaround to rename the dashboard, hence deleting the old and creating a new dashboard. This has the impact of making the user data, such as bookmarks, customisation, etc, vanish for the user and therefore not making it very user-friendly.

@dev-slatto I struggle to understand the concern you are raising. The old version of the code also tries to update to the latest version and it does not even allow you to update the dashboard at all since it now throws the error referred to in this MR.

When deploying a new version it would be (in my opinion) natural to deploy the latest version in most of the use cases. I struggle to see a good use case for not enabling the latest version except for maybe testing the new version before it is published to everyone. We have separate dev/test/prod env, so for us, it makes sense to always publish the latest.

Comment (dsbibby) [reply internal/service/quicksight/dashboard.go:206]: > Do we always want the latest version as this is hardcoded?

That is the current (as in before this PR) behaviour, so no change to the current behaviour.

That said, we could easily add a version parameter to this `resourceDashboardRead()` function if that would be beneficial for the future?

File: internal/service/quicksight/dashboard_test.go [hunk 2]
```diff
@@ -156,6 +156,8 @@ func TestAccQuickSightDashboard_updateVersionNumber(t *testing.T) {
 					resource.TestCheckResourceAttr(resourceName, "name", rNameUpdated),
 					resource.TestCheckResourceAttr(resourceName, "status", quicksight.ResourceStatusCreationSuccessful),
 					resource.TestCheckResourceAttr(resourceName, "version_number", "2"),
+					testAccCheckDashboardVersionExists(ctx, resourceName, 1, &dashboard),
+					testAccCheckDashboardName(&dashboard, rName),
```
Comment (gdavison) [inline internal/service/quicksight/dashboard_test.go:160]: For clarity, these should indicate that they're referencing version 1, e.g.

```suggestion
					testAccCheckDashboardVersionExists(ctx, resourceName, 1, &dashboardV1),
					testAccCheckDashboardName(&dashboardV1, rName),
```

**Review by gdavison — CHANGES_REQUESTED** [review]
Thanks for the PR, @dsbibby. It looks good, though I have a few suggestions

File: internal/service/quicksight/dashboard.go (hunk 1 above)
Comment (dev-slatto) [reply internal/service/quicksight/dashboard.go:206]: Had a chat with Graham and we concluded that it makes sence for a hardcoded version for the resource, and that a data source of dashboard should be able to include the version paramater. However, see the comment later down in the PR about defining the version as a constant instead of hardcoding it 😄

File: internal/service/quicksight/dashboard.go [hunk 3]
```diff
@@ -297,14 +297,15 @@ func resourceDashboardUpdate(ctx context.Context, d *schema.ResourceData, meta i
 			return create.DiagError(names.QuickSight, create.ErrActionUpdating, ResNameDashboard, d.Id(), err)
 		}
 
-		if _, err := waitDashboardUpdated(ctx, conn, d.Id(), d.Timeout(schema.TimeoutUpdate)); err != nil {
+		updatedVersionNumber := extractVersionFromARN(aws.StringValue(out.VersionArn))
```
[the remark this answers is not in the document]
Comment (DavidB19456) [reply internal/service/quicksight/dashboard.go:301]: Have addressed this 👍

File: internal/service/quicksight/dashboard.go (hunk 1 above)
Comment (dsbibby) [reply internal/service/quicksight/dashboard.go]: Great, I have updated to use a constant 👍

File: internal/service/quicksight/dashboard.go [hunk 4]
```diff
@@ -367,15 +368,26 @@ func resourceDashboardDelete(ctx context.Context, d *schema.ResourceData, meta i
 	return nil
 }
 
-func FindDashboardByID(ctx context.Context, conn *quicksight.QuickSight, id string) (*quicksight.Dashboard, error) {
+// Pass version as -1 for latest published version, or specify a specific version if required
```
[the remark this answers is not in the document]
Comment (dsbibby) [reply internal/service/quicksight/dashboard.go]: Done!

File: internal/service/quicksight/dashboard.go [hunk 5]
```diff
@@ -367,15 +368,26 @@ func resourceDashboardDelete(ctx context.Context, d *schema.ResourceData, meta i
...
+			AwsAccountId: aws.String(awsAccountId),
+			DashboardId:  aws.String(dashboardId),
+		}
+	} else {
+		descOpts = &quicksight.DescribeDashboardInput{
+			AwsAccountId:  aws.String(awsAccountId),
+			DashboardId:   aws.String(dashboardId),
+			VersionNumber: &version,
+		}
 	}
```
[the remark this answers is not in the document]
Comment (dsbibby) [reply internal/service/quicksight/dashboard.go]: Yes, that's neater, done 👍

File: internal/service/quicksight/dashboard_test.go (hunk 2 above)
Comment (dsbibby) [reply internal/service/quicksight/dashboard_test.go]: Updated to `dashboardV1`

**Comment by dsbibby** [comment]
I have addressed the comments so far. In testing this with a massive config I have access to, I got blocked by a couple of minor typos for which there are existing issues and a regression introduced by #33931 - I added fixes for these also so that I could complete my tests. Hope that is OK.

File: internal/service/quicksight/dashboard.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (dsbibby) [reply internal/service/quicksight/dashboard.go:301]: Have addressed this 👍

**Review by gdavison — APPROVED** [review]
Looks good! 🚀 

--- PASS: TestAccQuickSightDashboard_disappears (31.92s)
--- PASS: TestAccQuickSightDashboard_dashboardSpecificConfig (32.84s)
--- PASS: TestAccQuickSightDashboard_sourceEntity (35.41s)
--- PASS: TestAccQuickSightDashboard_basic (35.93s)
--- PASS: TestAccQuickSightDashboard_updateVersionNumber (57.83s)
