### PR TITLE
tests/provider: Fix partition issues (DS AMI)

### LINKED ISSUE #15913: tests/provider: AMI Data Source tests failing (GovCloud)
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

These tests fail on GovCloud:

```
TestAccAWSAmiDataSource_instanceStore
TestAccAWSAmiDataSource_localNameFilter
TestAccAWSAmiDataSource_natInstance
TestAccAWSAmiDataSource_windowsInstance
```

With related errors: `Your query returned no results. Please change your search criteria and try again.` or `Attribute 'owner_id' expected "801119661308", got "077303321853"`.

### New or Affected Resource(s)

* data.aws_ami

### Terraform Configuration Files

Example config:

```hcl
data "aws_ami" "nat_ami" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["amzn-ami-vpc-nat*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }

  filter {
    name   = "root-device-type"
    values = ["ebs"]
  }

  filter {
    name   = "block-device-mapping.volume-type"
    values = ["standard"]
  }
}
```

### Debug Output

```
TestAccAWSAmiDataSource_localNameFilter: data_source_aws_ami_test.go:135: Step 1/1 error: Error running pre-apply refresh: 2020/10/28 05:31:35 [DEBUG] Using modified User-Agent: Terraform/0.12.29 HashiCorp-terraform-exec/0.10.0
        
        Error: Your query returned no results. Please change your search criteria and try again.

--- FAIL: TestAccAWSAmiDataSource_localNameFilter (9.83s)
```

Or

```
TestAccAWSAmiDataSource_natInstance: data_source_aws_ami_test.go:14: Step 1/1 error: Check failed: Check 14/25 error: data.aws_ami.nat_ami: Attribute 'owner_id' expected "137112412989", got "045324592363"
--- FAIL: TestAccAWSAmiDataSource_natInstance (28.12s)
```

### References

* #0000

### PR DESCRIPTION
**Pull request by YakDriver**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #15913

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
NONE
```

Output from acceptance testing (GovCloud):

```
--- PASS: TestAccAWSAmiDataSource_instanceStore (17.90s)
--- PASS: TestAccAWSAmiDataSource_natInstance (17.95s)
--- PASS: TestAccAWSAmiDataSource_windowsInstance (18.01s)
--- PASS: TestAccAWSAmiDataSource_localNameFilter (18.70s)
```

Output from acceptance testing (commercial):

```
--- PASS: TestAccAWSAmiDataSource_natInstance (13.19s)
--- PASS: TestAccAWSAmiDataSource_instanceStore (14.00s)
--- PASS: TestAccAWSAmiDataSource_localNameFilter (14.70s)
--- PASS: TestAccAWSAmiDataSource_windowsInstance (15.01s)
```

### CODE REVIEW

File: aws/data_source_aws_ami_test.go [hunk 1]
```diff
@@ -76,7 +75,6 @@ func TestAccAWSAmiDataSource_windowsInstance(t *testing.T) {
 					resource.TestCheckResourceAttr(resourceName, "image_type", "machine"),
 					resource.TestCheckResourceAttr(resourceName, "most_recent", "true"),
 					resource.TestMatchResourceAttr(resourceName, "name", regexp.MustCompile("^Windows_Server-2012-R2")),
-					resource.TestCheckResourceAttr(resourceName, "owner_id", "801119661308"),
```
Comment (YakDriver) [inline aws/data_source_aws_ami_test.go:79]: Unnecessary since `image_owner_alias` is checked to be `amazon`. Also, not consistent across partitions and potentially over time.

File: aws/data_source_aws_ami_test.go [hunk 2]
```diff
@@ -38,7 +38,6 @@ func TestAccAWSAmiDataSource_natInstance(t *testing.T) {
 					resource.TestCheckResourceAttr(resourceName, "image_type", "machine"),
 					resource.TestCheckResourceAttr(resourceName, "most_recent", "true"),
 					resource.TestMatchResourceAttr(resourceName, "name", regexp.MustCompile("^amzn-ami-vpc-nat")),
-					resource.TestCheckResourceAttr(resourceName, "owner_id", "137112412989"),
```
Comment (YakDriver) [inline aws/data_source_aws_ami_test.go:41]: Unnecessary since `image_owner_alias` is checked to be `amazon`. Also, not consistent across partitions and potentially over time.

Comment (bflad) [reply aws/data_source_aws_ami_test.go:41]: Rather than removing these, we should verify that something was set for the attribute to prevent future regressions should a `d.Set()` be errantly removed, e.g.

```
// preferably
// maybe could be its own "testAccTestMatchResourceAttrAccountID(resourceName, attribute) helper
// and lintable!
resource.TestMatchResourceAttr(resourceName, "owner_id", regexp.MustCompile(`\d{12}`)),

// otherwise
resource.TestCheckResourceAttrSet(resourceName, "owner_id")
```

**Comment by YakDriver** [comment]
@bflad Changes made!

GovCloud:
```
--- PASS: TestAccAWSAmiDataSource_instanceStore (18.31s)
--- PASS: TestAccAWSAmiDataSource_natInstance (18.36s)
--- PASS: TestAccAWSAmiDataSource_windowsInstance (18.44s)
--- PASS: TestAccAWSAmiDataSource_localNameFilter (19.11s)
```

Commercial:
```
--- PASS: TestAccAWSAmiDataSource_instanceStore (14.12s)
--- PASS: TestAccAWSAmiDataSource_natInstance (14.27s)
--- PASS: TestAccAWSAmiDataSource_windowsInstance (14.63s)
--- PASS: TestAccAWSAmiDataSource_localNameFilter (16.21s)
```

File: aws/provider_test.go [hunk 3]
```diff
@@ -292,6 +292,18 @@ func testAccCheckResourceAttrHostnameWithPort(resourceName, attributeName, servi
 	}
 }
 
+// testAccMatchResourceAttrAccountID ensures the Terraform state regexp matches an account ID
+func testAccMatchResourceAttrAccountID(resourceName, attributeName string) resource.TestCheckFunc {
+	return func(s *terraform.State) error {
+		attributeMatch, err := regexp.Compile(`\d{12}`)
```
Comment (bflad) [inline aws/provider_test.go:298]: Nit: We'll want to check the whole string so things like `oops123456789012` doesn't match

```suggestion
		attributeMatch, err := regexp.Compile(`^\d{12}$`)
```

Further we can also use `regexp.MustCompile()` instead since its not accepting "user input" for the regular expression to compile:

```go
func testAccMatchResourceAttrAccountID(resourceName, attributeName string) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		return resource.TestMatchResourceAttr(resourceName, attributeName, regexp.MustCompile(`^\d{12}$`))(s)
	}
}
```

**Review by bflad — APPROVED** [review]
Minor things, otherwise looks good 🚀
