### PR TITLE
Honor region during import: Fix custom + API call importers

### LINKED ISSUE #45253: Region not honored for import when using `region` at the resource level
### Terraform and AWS Provider Version

```console
terraform version 1.33.5
terraform-provider-aws version 6.20.0
```

### Affected Resource(s) or Data Source(s)

I've tested at least these three:

* aws_dx_hosted_transit_virtual_interface
* aws_dx_hosted_transit_virtual_interface_accepter
* aws_dx_transit_virtual_interface

### Expected Behavior

Using the new `region` attribute at the resource level, along with the appended `@<region>` in the import block, Terraform should plan to import the resource.

```
import {
  to = aws_dx_hosted_transit_virtual_interface.denver
  id = "dxvif-........@us-west-2"
}
```

### Actual Behavior

Terraform instead fails with `  │ Error: empty result`.

From the debug log, it appears to be using `us-east-1`, which is the provider-configured region, rather than `us-west-2`, which is the resource-configured and import-configured region:

```
  2025-11-25T18:12:18.529Z [DEBUG] provider.terraform-provider-aws_v6.20.0_x5: HTTP Request Sent: http.request.header.x_amz_date=20251125T181218Z http.request.header.x_amz_target=OvertureService.DescribeVirtualInterfaces rpc.method=DescribeVirtualInterfaces tf_rpc=ImportResourceState @caller=github.com/hashicorp/aws-sdk-go-base/v2@v2.0.0-beta.68/logging/tf_logger.go:45 http.request.header.authorization="AWS4-HMAC-SHA256 Credential=ASIA************UX2T/20251125/us-east-1/directconnect/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-date;x-amz-security-token;x-amz-target, Signature=*****" http.request.header.x_amz_security_token="*****" tf_mux_provider="*schema.GRPCProviderServer" http.request.header.amz_sdk_invocation_id=403f6556-195d-4115-81ae-7205eb5a6185 tf_aws.sdk=aws-sdk-go-v2 tf_req_id=c38aa096-ec04-598b-c301-a705a1e41579 http.method=POST http.url=https://directconnect.us-east-1.amazonaws.com/ tf_resource_type=aws_dx_hosted_transit_virtual_interface_accepter aws.region=us-east-1
    http.request.body=
    | {"virtualInterfaceId":"dxvif-......"}
     http.request_content_length=39 http.user_agent="APN/1.0 HashiCorp/1.0 Terraform/1.13.5 (+https://www.terraform.io) terraform-provider-aws/6.20.0 (+https://registry.terraform.io/providers/hashicorp/aws) aws-sdk-go-v2/1.39.6 ua/2.1 os/linux lang/go#1.24.8 md/GOOS#linux md/GOARCH#amd64 exec-env/AWS_ECS_EC2 api/directconnect#1.38.3 m/i" net.peer.name=directconnect.us-east-1.amazonaws.com http.request.header.amz_sdk_request="attempt=1; max=25" tf_aws.signing_region="" tf_provider_addr=registry.terraform.io/hashicorp/aws @module=aws rpc.service="Direct Connect" rpc.system=aws-api http.request.header.content_type=application/x-amz-json-1.1 timestamp=2025-11-25T18:12:18.529Z
```

### Relevant Error/Panic Output

```console
 │ Error: empty result
```

### Sample Terraform Configuration

<details open>
<summary>Click to expand configuration</summary>

```hcl
import {
  to = aws_dx_hosted_transit_virtual_interface.denver
  id = "dxvif-....@us-west-2"
}

import {
  to = aws_dx_hosted_transit_virtual_interface_accepter.denver
  id = "dxvif-....@us-west-2"
}

import {
  to = aws_dx_transit_virtual_interface.denver
  id = "dxvif-....@us-west-2"
}

resource "aws_dx_hosted_transit_virtual_interface" "denver" {
  # provider = aws.us-west-2
  region = "us-west-2"

  owner_account_id = var.account_id
  connection_id    = "dxcon-..."
  name             = "..."
  vlan             = ...
  address_family   = "ipv6"
  bgp_asn          = ...
  amazon_address   = "..."
  customer_address = "..."
  bgp_auth_key     = "..."
  mtu              = ...
}

resource "aws_dx_hosted_transit_virtual_interface_accepter" "denver" {
  # provider = aws.us-west-2
  region = "us-west-2"

  dx_gateway_id        = "..."
  virtual_interface_id = "..."
}

resource "aws_dx_transit_virtual_interface" "denver" {
  # provider = aws.us-west-2
  region = "us-west-2"

  connection_id = "..."
  dx_gateway_id = "..."

  name             = "..."
  vlan             = ...
  address_family   = "..."
  bgp_asn          = ...
  amazon_address   = "..."
  customer_address = "..."
  bgp_auth_key     = "..."
  mtu              = ...
  sitelink_enabled = ...
}


```
</details>

### Steps to Reproduce

1. Attempt to run `terraform plan`

### Debug Logging

<details open>
<summary>Click to expand log output</summary>

```console

```
</details>

### GenAI / LLM Assisted Development

n/a

### Important Facts and References

If I switch back to provider-configured region, using the aliased provider in the config above, then the import does find the resources and plan correctly.

I confirmed with the [Enhance Region Support Guide](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/enhanced-region-support) that the service and resources were not being treated as global.

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by YakDriver**
## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the library.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

### Description

The provider lets you set `region` directly on resources. When importing with a region override, you append `@region` to the ID (like `dxvif-123@us-west-2`).

Most resources handle this automatically through an interceptor that strips the `@region` suffix before the import function runs. But 32 resources have custom import functions that make API calls using the resource ID. The bug was that these functions were using the wrong region's API client - they were getting the client before the interceptor set the region attribute, so API calls went to the default region instead of the overridden region.

This would result in:

```
Error: empty result
```

Or:

```
Error: couldn't find resource
```

The fix ensures these custom import functions get the API client after the region attribute is set, so API calls go to the correct region.

Impacted resources (API call in custom import functions going to the wrong region when `@region`):

- [x] aws_api_gateway_method
- [x] aws_apigatewayv2_integration
- [x] aws_apigatewayv2_route
- [x] aws_apigatewayv2_stage
- [x] aws_appmesh_gateway_route
- [x] aws_appmesh_route
- [x] aws_appmesh_virtual_gateway
- [x] aws_appmesh_virtual_node
- [x] aws_appmesh_virtual_router
- [x] aws_appmesh_virtual_service
- [x] aws_controltower_control
- [x] aws_default_route_table
- [x] aws_dx_gateway_association
- [x] aws_dx_hosted_private_virtual_interface_accepter
- [x] aws_dx_hosted_private_virtual_interface
- [x] aws_dx_hosted_public_virtual_interface_accepter
- [x] aws_dx_hosted_public_virtual_interface
- [x] aws_dx_hosted_transit_virtual_interface_accepter
- [x] aws_dx_hosted_transit_virtual_interface
- [x] aws_dx_private_virtual_interface
- [x] aws_dx_public_virtual_interface
- [x] aws_dx_transit_virtual_interface
- [x] aws_kinesis_stream
- [x] aws_network_acl
- [x] aws_network_interface_sg_attachment
- [x] aws_opensearch_domain
- [x] aws_route_table_association
- [x] aws_serverlessapplicationrepository_cloudformation_stack
- [x] aws_servicecatalog_product
- [x] aws_ses_active_receipt_rule_set
- [x] aws_ssm_default_patch_baseline
- [x] aws_vpc_dhcp_options_association

### Relations

Closes #45253.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/45120.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/43733.

### References

* [Comment](https://github.com/hashicorp/terraform-provider-aws/issues/45253#issuecomment-4101109027) on #45253

#### Without fix

```console
% make t T=TestAccServiceCatalogProduct_regionOverride K=servicecatalog
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 b-dx-rt-honor-region-import 🌿...
TF_ACC=1 go1.25.8 test ./internal/service/servicecatalog/... -v -count 1 -parallel 20 -run='TestAccServiceCatalogProduct_regionOverride'  -timeout 360m -vet=off
2026/03/23 17:10:41 Creating Terraform AWS Provider (SDKv2-style)...
2026/03/23 17:10:41 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccServiceCatalogProduct_regionOverride
=== PAUSE TestAccServiceCatalogProduct_regionOverride
=== CONT  TestAccServiceCatalogProduct_regionOverride
    product_test.go:197: Step 2/2 error running import: exit status 1
        
        Error: couldn't find resource
        
        
--- FAIL: TestAccServiceCatalogProduct_regionOverride (56.29s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/servicecatalog	63.281s
FAIL
make: *** [t] Error 1
% make t T=TestAccVPCRouteTableAssociation_regionOverride K=vpc
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 b-dx-rt-honor-region-import 🌿...
TF_ACC=1 go1.25.8 test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccVPCRouteTableAssociation_regionOverride'  -timeout 360m -vet=off
2026/03/23 13:49:50 Creating Terraform AWS Provider (SDKv2-style)...
2026/03/23 13:49:50 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccVPCRouteTableAssociation_regionOverride
=== PAUSE TestAccVPCRouteTableAssociation_regionOverride
=== CONT  TestAccVPCRouteTableAssociation_regionOverride
    vpc_route_table_association_test.go:183: Step 2/2 error running import: exit status 1
        
        Error: couldn't find resource
        
        
--- FAIL: TestAccVPCRouteTableAssociation_regionOverride (24.09s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	31.029s
FAIL
make: *** [t] Error 1
% make t T=TestAccAPIGatewayV2Route_regionOverride K=apigatewayv2
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 b-dx-rt-honor-region-import 🌿...
TF_ACC=1 go1.25.8 test ./internal/service/apigatewayv2/... -v -count 1 -parallel 20 -run='TestAccAPIGatewayV2Route_regionOverride'  -timeout 360m -vet=off
2026/03/23 17:17:30 Creating Terraform AWS Provider (SDKv2-style)...
2026/03/23 17:17:30 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccAPIGatewayV2Route_regionOverride
=== PAUSE TestAccAPIGatewayV2Route_regionOverride
=== CONT  TestAccAPIGatewayV2Route_regionOverride
    route_test.go:66: Step 2/2 error running import: exit status 1
        
        Error: couldn't find resource
        
        
--- FAIL: TestAccAPIGatewayV2Route_regionOverride (19.96s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/apigatewayv2	26.802s
FAIL
make: *** [t] Error 1
```

#### With fix

```console
% make t T=TestAccServiceCatalogProduct_regionOverride K=servicecatalog
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 b-dx-rt-honor-region-import 🌿...
TF_ACC=1 go1.25.8 test ./internal/service/servicecatalog/... -v -count 1 -parallel 20 -run='TestAccServiceCatalogProduct_regionOverride'  -timeout 360m -vet=off
2026/03/23 17:08:53 Creating Terraform AWS Provider (SDKv2-style)...
2026/03/23 17:08:53 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccServiceCatalogProduct_regionOverride
=== PAUSE TestAccServiceCatalogProduct_regionOverride
=== CONT  TestAccServiceCatalogProduct_regionOverride
--- PASS: TestAccServiceCatalogProduct_regionOverride (57.08s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/servicecatalog	63.619s
% make t T=TestAccVPCRouteTableAssociation_regionOverride K=vpc
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 b-dx-rt-honor-region-import 🌿...
TF_ACC=1 go1.25.8 test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccVPCRouteTableAssociation_regionOverride'  -timeout 360m -vet=off
2026/03/23 13:47:51 Creating Terraform AWS Provider (SDKv2-style)...
2026/03/23 13:47:51 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccVPCRouteTableAssociation_regionOverride
=== PAUSE TestAccVPCRouteTableAssociation_regionOverride
=== CONT  TestAccVPCRouteTableAssociation_regionOverride
--- PASS: TestAccVPCRouteTableAssociation_regionOverride (25.51s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	32.555s
% make t T=TestAccAPIGatewayV2Route_regionOverride K=apigatewayv2
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 b-dx-rt-honor-region-import 🌿...
TF_ACC=1 go1.25.8 test ./internal/service/apigatewayv2/... -v -count 1 -parallel 20 -run='TestAccAPIGatewayV2Route_regionOverride'  -timeout 360m -vet=off
2026/03/23 17:16:02 Creating Terraform AWS Provider (SDKv2-style)...
2026/03/23 17:16:02 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccAPIGatewayV2Route_regionOverride
=== PAUSE TestAccAPIGatewayV2Route_regionOverride
=== CONT  TestAccAPIGatewayV2Route_regionOverride
--- PASS: TestAccAPIGatewayV2Route_regionOverride (24.96s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/apigatewayv2	32.334s
```

### CODE REVIEW

**Comment by lorengordon** [comment]
Linking the issue to close: https://github.com/hashicorp/terraform-provider-aws/issues/45253

**Comment by YakDriver** [comment]
This might need some more cipherin'. By my count, there's 87+ resources with custom importings. Some will be global but probably not the majority. That leaves a lot of fixes and probably a more generalized solution.

```console
% rg -l 'StateContext:.*resource.*Import' internal/service --type go        
internal/service/lightsail/database.go
internal/service/organizations/account.go
internal/service/organizations/organization.go
internal/service/organizations/policy.go
internal/service/ec2/vpc_dhcp_options_association.go
internal/service/ec2/vpc_default_vpc.go
internal/service/cloudfront/monitoring_subscription.go
internal/service/serverlessrepo/cloudformation_stack.go
internal/service/appmesh/virtual_router.go
internal/service/appmesh/route.go
internal/service/appmesh/virtual_gateway.go
internal/service/lexmodels/bot_alias.go
internal/service/appmesh/virtual_service.go
internal/service/appmesh/gateway_route.go
internal/service/appmesh/virtual_node.go
internal/service/s3control/access_point_policy.go
internal/service/kinesis/stream.go
internal/service/ec2/vpc_default_route_table.go
internal/service/servicecatalog/product.go
internal/service/kinesisanalyticsv2/application.go
internal/service/ec2/vpc_managed_prefix_list_entry.go
internal/service/signer/signing_profile_permission.go
internal/service/ecs/cluster.go
internal/service/ssmincidents/replication_set.go
internal/service/ec2/vpc_endpoint_route_table_association.go
internal/service/ecs/account_setting_default.go
internal/service/ecs/service.go
internal/service/kinesisanalytics/application.go
internal/service/logs/subscription_filter.go
internal/service/logs/query_definition.go
internal/service/ec2/ec2_ami_launch_permission.go
internal/service/ec2/vpc_endpoint_security_group_association.go
internal/service/s3outposts/endpoint.go
internal/service/redshift/cluster.go
internal/service/directconnect/hosted_public_virtual_interface_accepter.go
internal/service/directconnect/hosted_private_virtual_interface.go
internal/service/iam/user_group_membership.go
internal/service/directconnect/private_virtual_interface.go
internal/service/iam/user_ssh_key.go
internal/service/appautoscaling/target.go
internal/service/directconnect/hosted_transit_virtual_interface.go
internal/service/iam/server_certificate.go
internal/service/iam/user_policy_attachment.go
internal/service/directconnect/transit_virtual_interface.go
internal/service/iam/group_policy_attachment.go
internal/service/directconnect/hosted_public_virtual_interface.go
internal/service/directconnect/gateway_association_proposal.go
internal/service/appautoscaling/policy.go
internal/service/directconnect/gateway_association.go
internal/service/directconnect/public_virtual_interface.go
internal/service/directconnect/hosted_private_virtual_interface_accepter.go
internal/service/directconnect/hosted_transit_virtual_interface_accepter.go
internal/service/ec2/vpc_.go
internal/service/autoscaling/schedule.go
internal/service/autoscaling/lifecycle_hook.go
internal/service/ec2/vpc_endpoint_subnet_association.go
internal/service/autoscaling/policy.go
internal/service/ec2/vpc_security_group_rule.go
internal/service/backup/selection.go
internal/service/ec2/vpnclient_network_association.go
internal/service/ec2/vpc_traffic_mirror_filter_rule.go
internal/service/servicediscovery/instance.go
internal/service/ec2/vpc_network_acl_rule.go
internal/service/apigatewayv2/stage.go
internal/service/apigatewayv2/api_mapping.go
internal/service/ses/event_destination.go
internal/service/apigatewayv2/integration.go
internal/service/apigatewayv2/model.go
internal/service/apigatewayv2/route_response.go
internal/service/ses/active_receipt_rule_set.go
internal/service/ses/receipt_rule.go
internal/service/apigatewayv2/integration_response.go
internal/service/apigatewayv2/route.go
internal/service/apigatewayv2/authorizer.go
internal/service/lambda/alias.go
internal/service/apigatewayv2/deployment.go
internal/service/cloudformation/stack_instances.go
internal/service/cloudformation/stack_set.go
internal/service/ec2/vpc_route_table_association.go
internal/service/cloudformation/stack_set_instance.go
internal/service/ec2/vpc_network_interface_sg_attachment.go
internal/service/rds/instance.go
internal/service/rds/cluster.go
internal/service/autoscalingplans/scaling_plan.go
internal/service/customerprofiles/profile.go
internal/service/apigateway/method_settings.go
internal/service/apigateway/deployment.go
```

**Comment by ewbankkit** [comment]
The fundamental problem here is that the import interceptor (which always runs) https://github.com/hashicorp/terraform-provider-aws/blob/016eed39342ccd062a2c76d523945e67263fcfe9/internal/provider/sdkv2/region.go#L121-L141 is setting the `region` argument correctly but the Region held in `Context` (which is used when determining the Region for AWS API clients)  is set via the `bootstrapContext` function https://github.com/hashicorp/terraform-provider-aws/blob/016eed39342ccd062a2c76d523945e67263fcfe9/internal/provider/sdkv2/provider.go#L803-L834 which is run _before_ the interceptor https://github.com/hashicorp/terraform-provider-aws/blob/016eed39342ccd062a2c76d523945e67263fcfe9/internal/provider/sdkv2/intercept.go#L276-L348 and hence contains the default (provider-configured value).

It's likely that not all of the 87 custom importers listed above make AWS API calls (and hence hit this problem) but it's also likely than more than the few addressed here do.
My reading of https://github.com/hashicorp/terraform/blob/main/docs/resource-instance-change-lifecycle.md is that if we move any checks that use AWS API calls into the resource's `Read` handler then the Read interceptor will run and since the `region` argument is set correctly _before_ the Read interceptor bootstraps its `Context`, the correct Region is set in `Context` and used for AWS API calls. As an aside, I think that's what may have happened e.g. with the various FSx file system imports where a single API returns filesystems of every type and we have a _finder_ wrapper that checks for the correct type, returning `NotFound` if the type is not correct, which would trigger an error during the `Read` phase of the import.
Anyway, the more general solution would be to "reboot" the `Context` in the import interceptor once the `region` argument is set correctly.

The generated Resource Identity acceptance test cases verify the appending of `@<region>` so implementing RI everywhere would have found this 😄.

**Comment by YakDriver** [comment]
Quick note on why framework resources aren't affected by this bug:

In the SDK interceptor, the context needs to be re-bootstrapped after the `Before` interceptors run (lines 320-323 in `sdkv2/intercept.go`) because custom import functions receive a context parameter that was created before the region attribute was set. Without re-bootstrapping, API client calls inside the import function use the wrong region.

Framework resources don't have this issue because the region interceptor directly modifies `response.State` during the `Before` phase (see `framework/region.go:346`). The import function doesn't receive a context with region info - instead, the region is already in the state by the time any code runs. When the subsequent Read function executes, it can access the region attribute correctly from state.

So this bug only affects SDK resources with 1) custom import functions that 2) make API calls.

File: internal/provider/sdkv2/intercept.go [hunk 1]
```diff
@@ -315,6 +315,13 @@ func interceptedImportHandler(bootstrapContext contextFunc, interceptorInvocatio
 			}
 		}
 
+		// Re-bootstrap context after Before interceptors to pick up any region changes.
```
Comment (ewbankkit) [inline internal/provider/sdkv2/intercept.go]: For completeness shall we move this logic inside the `for` loop above so that a (theoretical) earlier interceptor can affect the `Context` for a later one?

Comment (YakDriver) [reply internal/provider/sdkv2/intercept.go]: I like it. We can do interceptor chaining

**Comment by YakDriver** [comment]
With interceptor chaining:

```console
% make t T=TestAccServiceCatalogProduct_regionOverride K=servicecatalog
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 b-dx-rt-honor-region-import 🌿...
TF_ACC=1 go1.25.8 test ./internal/service/servicecatalog/... -v -count 1 -parallel 20 -run='TestAccServiceCatalogProduct_regionOverride'  -timeout 360m -vet=off
2026/03/24 10:55:15 Creating Terraform AWS Provider (SDKv2-style)...
2026/03/24 10:55:15 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccServiceCatalogProduct_regionOverride
=== PAUSE TestAccServiceCatalogProduct_regionOverride
=== CONT  TestAccServiceCatalogProduct_regionOverride
--- PASS: TestAccServiceCatalogProduct_regionOverride (57.76s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/servicecatalog	70.101s
% make t T=TestAccVPCRouteTableAssociation_regionOverride K=vpc
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 b-dx-rt-honor-region-import 🌿...
TF_ACC=1 go1.25.8 test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccVPCRouteTableAssociation_regionOverride'  -timeout 360m -vet=off
2026/03/24 10:55:10 Creating Terraform AWS Provider (SDKv2-style)...
2026/03/24 10:55:10 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccVPCRouteTableAssociation_regionOverride
=== PAUSE TestAccVPCRouteTableAssociation_regionOverride
=== CONT  TestAccVPCRouteTableAssociation_regionOverride
--- PASS: TestAccVPCRouteTableAssociation_regionOverride (27.92s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	35.246s
% make t T=TestAccAPIGatewayV2Route_regionOverride K=apigatewayv2
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 b-dx-rt-honor-region-import 🌿...
TF_ACC=1 go1.25.8 test ./internal/service/apigatewayv2/... -v -count 1 -parallel 20 -run='TestAccAPIGatewayV2Route_regionOverride'  -timeout 360m -vet=off
2026/03/24 10:56:23 Creating Terraform AWS Provider (SDKv2-style)...
2026/03/24 10:56:23 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccAPIGatewayV2Route_regionOverride
=== PAUSE TestAccAPIGatewayV2Route_regionOverride
=== CONT  TestAccAPIGatewayV2Route_regionOverride
--- PASS: TestAccAPIGatewayV2Route_regionOverride (19.84s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/apigatewayv2	26.699s
```

**Comment by YakDriver** [comment]
I didn't add tests to all 32 affected resources. Adding these 3 should prevent provider-level regressions though it might be a good idea to add more.

**Comment by ewbankkit** [comment]
As we add RI to all resources then we will pick up auto-generated `@<region>` tests.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

**Comment by YakDriver** [comment]
@ewbankkit Thanks Kit
