### PR TITLE
f/Add check to ignore case for secret regions/govcloud

### LINKED ISSUE #41177: [Bug]: EIP Addresses Attribute not supported in all AWS regions
### Terraform Core Version

all

### AWS Provider Version

5.46.0 or higher

### Affected Resource(s)

* aws_eip

### Expected Behavior

Provider should be able to plan EIP resources in all AWS regions

### Actual Behavior

In regions where the EIP Address Attributes are unsupported any attempt to plan an EIP fails with

```shell
Error: reading EC2 EIP (eipalloc-xxxxxxxxxxxx) domain name attribute: operation error EC2: DescribeAddressesAttribute, https response error StatusCode: 400, RequestID: xxxxx-xxxxx-xxxxx-xxxx-xxxxx, api error InvalidAction: The action DescribeAddressesAttribute is not valid for this web service
```

### Relevant Error/Panic Output Snippet

```shell

```

### Terraform Configuration Files

```hcl
resource "aws_eip" "this" {
  domain = "vpc"
  tags = {
     Name = "test-eip"
  }
}
```

### Steps to Reproduce

in a region where the EC2 DescribeAddressesAtribute API is unsupported, plan with 

```
terraform {
  required_providers {
     aws = ">= 5.46.0"
  }
}
```

If you pin the version to <= 5.45.0, planning succeeds.

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

I believe this was introduced when resolving #20876 with #36963

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by nam054**
### Description

Prevents application from failing when hitting the "InvalidAction" error for specific regions where the `DescribeAddressesAttribute` is not supported such as govCloud or secret regions.

### Relations

Closes #41177

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccXXX PKG=ec2

...
```

### CODE REVIEW

File: internal/service/ec2/ec2_eip.go [hunk 1]
```diff
@@ -278,6 +278,8 @@ func resourceEIPRead(ctx context.Context, d *schema.ResourceData, meta any) diag
 		d.Set("ptr_record", strings.TrimSuffix(aws.ToString(addressAttr.PtrRecord), "."))
 	case tfresource.NotFound(err):
 		d.Set("ptr_record", nil)
+	case tfawserr.ErrMessageContains(err, "InvalidAction", "not valid for this web service"):
+		// Effectively ignoring the error as we handle errors from GovCloud/Secret Regions
```
Comment (johnsonaj) [inline internal/service/ec2/ec2_eip.go:282]: we should set `ptr_record` to `nil`, similar to when `NotFound(err)` is checked.

File: .changelog/41920.txt [hunk 2]
```diff
@@ -0,0 +1,3 @@
+```release-note:note
```
Comment (johnsonaj) [inline .changelog/41920.txt:1]: release-note would be better as a bug

**Review by johnsonaj — APPROVED** [review]
LGTM 🚀 

```console
% make testacc TESTARGS='-run=TestAccEC2EIP_basic\|TestAccEC2EIP_disappears' PKG=ec2

make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.7 test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccEC2EIP_basic\|TestAccEC2EIP_disappears -timeout 360m -vet=off
2025/03/24 10:24:15 Initializing Terraform AWS Provider...
=== RUN   TestAccEC2EIP_basic
=== PAUSE TestAccEC2EIP_basic
=== RUN   TestAccEC2EIP_disappears
=== PAUSE TestAccEC2EIP_disappears
=== CONT  TestAccEC2EIP_basic
=== CONT  TestAccEC2EIP_disappears
--- PASS: TestAccEC2EIP_disappears (14.78s)
--- PASS: TestAccEC2EIP_basic (17.10s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	24.124s
```
