### PR TITLE
[bugfix]: aws_elasticache_serverless_cache user group removal fix

### LINKED ISSUE #42766: resource/aws_elasticache_serverless_cache: user_group_id is not set to null after engine is updated to Valkey
### Terraform and AWS Provider Version

```console
Terraform v1.11.3
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.98.0

Your version of Terraform is out of date! The latest version
is 1.12.1. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s) or Data Source(s)

* `aws_elasticache_serverless_cache`

### Expected Behavior

It should update the state with attribute `user_group_id` set to `null` as deduced from the [resource documentation](https://registry.terraform.io/providers/-/aws/5.98.0/docs/resources/elasticache_serverless_cache#user_group_id-3).

### Actual Behavior

AWS API errors out.

### Relevant Error/Panic Output

```console
│ Error: updating ElastiCache Serverless Cache (cache1-serverless)
│
│   with module.elasticache_serverless["cache1"].aws_elasticache_serverless_cache.elasticache,
│   on .terraform/modules/elasticache_serverless/aws-elasticache-serverless/main.tf line 17, in resource "aws_elasticache_serverless_cache" "elasticache":
│   17: resource "aws_elasticache_serverless_cache" "elasticache" {
│
│ operation error ElastiCache: ModifyServerlessCache, https response error StatusCode: 400, RequestID: 9c9c8b2c-d71b-4717-b62a-68cfa4b18aa9, InvalidParameterCombination: No
│ modifications were requested
```

### Sample Terraform Configuration

<details>
<summary>Click to expand configuration</summary>

```hcl
# module.elasticache_serverless["cache1"].aws_elasticache_serverless_cache.elasticache will be updated in-place
~ resource "aws_elasticache_serverless_cache" "elasticache" {
    ~ full_engine_version      = "7.2" -> (known after apply)
      id                       = "cache1-serverless"
      name                     = "cache1-serverless"
      tags                     = {
          "Name"        = "cache1-serverless"
      }
    - user_group_id            = "cache1-serverless" -> null
      # (13 unchanged attributes hidden)

      # (1 unchanged block hidden)
  }
```
</details>

### Steps to Reproduce

1. Have serverless cache running Redis 7 associated to its own user group having engine Redis
2. Modify serverless cache in the AWS Console to use Valkey 7 as engine
3. Modify user group to use engine Valkey
4. Run Terraform apply

### Debug Logging

<details>
<summary>Click to expand log output</summary>

```console

```
</details>

### GenAI / LLM Assisted Development

n/a

### Important Facts and References

_No response_

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by sukumaar**
## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the library.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

### Description

This fix enables `user_group_id` removal from `aws_elasticache_serverless_cache` while modification/update.

### Relations

Closes #42766

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccElastiCacheServerlessCache PKG=elasticache ACCTEST_PARALLELISM=2 ACCTEST_TIMEOUT=3880m
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
xargs: gofmt: No such file or directory
make: Running acceptance tests on branch: 🌿 f-elasticache-serverless-ug-removal-fix 🌿...
TF_ACC=1 go1.24.10 test ./internal/service/elasticache/... -v -count 1 -parallel 2 -run='TestAccElastiCacheServerlessCache'  -timeout 3880m -vet=off
2025/12/12 20:34:11 Creating Terraform AWS Provider (SDKv2-style)...
2025/12/12 20:34:11 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccElastiCacheServerlessCacheDataSource_Redis_basic
=== PAUSE TestAccElastiCacheServerlessCacheDataSource_Redis_basic
=== RUN   TestAccElastiCacheServerlessCacheDataSource_Valkey_basic
=== PAUSE TestAccElastiCacheServerlessCacheDataSource_Valkey_basic
=== RUN   TestAccElastiCacheServerlessCache_basicRedis
=== PAUSE TestAccElastiCacheServerlessCache_basicRedis
=== RUN   TestAccElastiCacheServerlessCache_basicValkey
=== PAUSE TestAccElastiCacheServerlessCache_basicValkey
=== RUN   TestAccElastiCacheServerlessCache_full
=== PAUSE TestAccElastiCacheServerlessCache_full
=== RUN   TestAccElastiCacheServerlessCache_fullRedis
=== PAUSE TestAccElastiCacheServerlessCache_fullRedis
=== RUN   TestAccElastiCacheServerlessCache_redisUpdateWithUserGroup
=== PAUSE TestAccElastiCacheServerlessCache_redisUpdateWithUserGroup
=== RUN   TestAccElastiCacheServerlessCache_redisUpdateWithUserGroupRemoval
=== PAUSE TestAccElastiCacheServerlessCache_redisUpdateWithUserGroupRemoval
=== RUN   TestAccElastiCacheServerlessCache_fullValkey
=== PAUSE TestAccElastiCacheServerlessCache_fullValkey
=== RUN   TestAccElastiCacheServerlessCache_description
=== PAUSE TestAccElastiCacheServerlessCache_description
=== RUN   TestAccElastiCacheServerlessCache_cacheUsageLimits
=== PAUSE TestAccElastiCacheServerlessCache_cacheUsageLimits
=== RUN   TestAccElastiCacheServerlessCache_engine
=== PAUSE TestAccElastiCacheServerlessCache_engine
=== RUN   TestAccElastiCacheServerlessCache_disappears
=== PAUSE TestAccElastiCacheServerlessCache_disappears
=== RUN   TestAccElastiCacheServerlessCache_tags
=== PAUSE TestAccElastiCacheServerlessCache_tags
=== CONT  TestAccElastiCacheServerlessCacheDataSource_Redis_basic
=== CONT  TestAccElastiCacheServerlessCache_redisUpdateWithUserGroupRemoval
--- PASS: TestAccElastiCacheServerlessCacheDataSource_Redis_basic (374.93s)
=== CONT  TestAccElastiCacheServerlessCache_full
--- PASS: TestAccElastiCacheServerlessCache_full (314.08s)
=== CONT  TestAccElastiCacheServerlessCache_redisUpdateWithUserGroup
--- PASS: TestAccElastiCacheServerlessCache_redisUpdateWithUserGroupRemoval (1143.29s)
=== CONT  TestAccElastiCacheServerlessCache_fullRedis
--- PASS: TestAccElastiCacheServerlessCache_redisUpdateWithUserGroup (529.18s)
=== CONT  TestAccElastiCacheServerlessCache_basicRedis
--- PASS: TestAccElastiCacheServerlessCache_fullRedis (324.88s)
=== CONT  TestAccElastiCacheServerlessCache_engine
--- PASS: TestAccElastiCacheServerlessCache_basicRedis (367.53s)
=== CONT  TestAccElastiCacheServerlessCache_tags
--- PASS: TestAccElastiCacheServerlessCache_tags (381.88s)
=== CONT  TestAccElastiCacheServerlessCache_disappears
--- PASS: TestAccElastiCacheServerlessCache_disappears (305.22s)
=== CONT  TestAccElastiCacheServerlessCacheDataSource_Valkey_basic
--- PASS: TestAccElastiCacheServerlessCacheDataSource_Valkey_basic (304.21s)
=== CONT  TestAccElastiCacheServerlessCache_description
--- PASS: TestAccElastiCacheServerlessCache_engine (1251.20s)
=== CONT  TestAccElastiCacheServerlessCache_cacheUsageLimits
--- PASS: TestAccElastiCacheServerlessCache_description (407.64s)
=== CONT  TestAccElastiCacheServerlessCache_basicValkey
--- PASS: TestAccElastiCacheServerlessCache_basicValkey (307.41s)
=== CONT  TestAccElastiCacheServerlessCache_fullValkey
--- PASS: TestAccElastiCacheServerlessCache_cacheUsageLimits (629.00s)
--- PASS: TestAccElastiCacheServerlessCache_fullValkey (385.12s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elasticache	3677.354s
...
```

### CODE REVIEW

File: internal/service/elasticache/serverless_cache_test.go [hunk 1]
```diff
@@ -841,6 +909,101 @@ resource "aws_elasticache_serverless_cache" "test" {
...
+  access_string = "on ~* +@all"
+  engine        = "redis"
+  passwords     = ["password123456789"]
+}
+
+resource "aws_elasticache_user_group" "test" {
+  engine        = "redis"
+  user_group_id = %[4]q
+  user_ids      = [aws_elasticache_user.test.user_id]
+}
```
Comment (trevorbonas) [inline internal/service/elasticache/serverless_cache_test.go:996]: The [issue](https://github.com/hashicorp/terraform-provider-aws/issues/42766) has these reproduction steps:
> 1. Have serverless cache running Redis 7 associated to its own user group having engine Redis
> 2. Modify serverless cache in the AWS Console to use Valkey 7 as engine
> 3. Modify user group to use engine Valkey
> 4. Run Terraform apply

Were you able to reproduce the error or verify the error is fixed when the user group's engine type is changed to Valkey? These tests keep the user group's engine type as Redis.

Comment (sukumaar) [reply internal/service/elasticache/serverless_cache_test.go:996]: Thanks, modified test. Somehow, expected behaviour and steps to reproduce does not match in original issue.

**Comment by sukumaar** [comment]
### Output from Acceptance Testing
```console
% make testacc TESTS=TestAccElastiCacheServerlessCache PKG=elasticache ACCTEST_PARALLELISM=2 ACCTEST_TIMEOUT=3880m
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
xargs: gofmt: No such file or directory
make: Running acceptance tests on branch: 🌿 f-elasticache-serverless-ug-removal-fix 🌿...
TF_ACC=1 go1.24.10 test ./internal/service/elasticache/... -v -count 1 -parallel 2 -run='TestAccElastiCacheServerlessCache'  -timeout 3880m -vet=off
2025/12/19 16:24:59 Creating Terraform AWS Provider (SDKv2-style)...
2025/12/19 16:24:59 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccElastiCacheServerlessCacheDataSource_Redis_basic
=== PAUSE TestAccElastiCacheServerlessCacheDataSource_Redis_basic
=== RUN   TestAccElastiCacheServerlessCacheDataSource_Valkey_basic
=== PAUSE TestAccElastiCacheServerlessCacheDataSource_Valkey_basic
=== RUN   TestAccElastiCacheServerlessCache_basicRedis
=== PAUSE TestAccElastiCacheServerlessCache_basicRedis
=== RUN   TestAccElastiCacheServerlessCache_basicValkey
=== PAUSE TestAccElastiCacheServerlessCache_basicValkey
=== RUN   TestAccElastiCacheServerlessCache_full
=== PAUSE TestAccElastiCacheServerlessCache_full
=== RUN   TestAccElastiCacheServerlessCache_fullRedis
=== PAUSE TestAccElastiCacheServerlessCache_fullRedis
=== RUN   TestAccElastiCacheServerlessCache_redisUpdateWithUserGroup
=== PAUSE TestAccElastiCacheServerlessCache_redisUpdateWithUserGroup
=== RUN   TestAccElastiCacheServerlessCache_updateWithUserGroupRemoval
=== PAUSE TestAccElastiCacheServerlessCache_updateWithUserGroupRemoval
=== RUN   TestAccElastiCacheServerlessCache_fullValkey
=== PAUSE TestAccElastiCacheServerlessCache_fullValkey
=== RUN   TestAccElastiCacheServerlessCache_description
=== PAUSE TestAccElastiCacheServerlessCache_description
=== RUN   TestAccElastiCacheServerlessCache_cacheUsageLimits
=== PAUSE TestAccElastiCacheServerlessCache_cacheUsageLimits
=== RUN   TestAccElastiCacheServerlessCache_engine
=== PAUSE TestAccElastiCacheServerlessCache_engine
=== RUN   TestAccElastiCacheServerlessCache_disappears
=== PAUSE TestAccElastiCacheServerlessCache_disappears
=== RUN   TestAccElastiCacheServerlessCache_tags
=== PAUSE TestAccElastiCacheServerlessCache_tags
=== CONT  TestAccElastiCacheServerlessCacheDataSource_Redis_basic
=== CONT  TestAccElastiCacheServerlessCache_updateWithUserGroupRemoval
--- PASS: TestAccElastiCacheServerlessCacheDataSource_Redis_basic (304.99s)
=== CONT  TestAccElastiCacheServerlessCache_engine
--- PASS: TestAccElastiCacheServerlessCache_updateWithUserGroupRemoval (1313.13s)
=== CONT  TestAccElastiCacheServerlessCache_tags
--- PASS: TestAccElastiCacheServerlessCache_engine (1281.52s)
=== CONT  TestAccElastiCacheServerlessCache_disappears
--- PASS: TestAccElastiCacheServerlessCache_tags (391.92s)
=== CONT  TestAccElastiCacheServerlessCache_description
--- PASS: TestAccElastiCacheServerlessCache_disappears (304.93s)
=== CONT  TestAccElastiCacheServerlessCache_cacheUsageLimits
--- PASS: TestAccElastiCacheServerlessCache_description (407.10s)
=== CONT  TestAccElastiCacheServerlessCache_basicRedis
--- PASS: TestAccElastiCacheServerlessCache_cacheUsageLimits (568.62s)
=== CONT  TestAccElastiCacheServerlessCache_basicValkey
--- PASS: TestAccElastiCacheServerlessCache_basicRedis (468.44s)
=== CONT  TestAccElastiCacheServerlessCache_fullValkey
--- PASS: TestAccElastiCacheServerlessCache_basicValkey (317.91s)
=== CONT  TestAccElastiCacheServerlessCache_full
--- PASS: TestAccElastiCacheServerlessCache_fullValkey (385.31s)
=== CONT  TestAccElastiCacheServerlessCacheDataSource_Valkey_basic
--- PASS: TestAccElastiCacheServerlessCache_full (334.72s)
=== CONT  TestAccElastiCacheServerlessCache_redisUpdateWithUserGroup
--- PASS: TestAccElastiCacheServerlessCacheDataSource_Valkey_basic (314.00s)
=== CONT  TestAccElastiCacheServerlessCache_fullRedis
--- PASS: TestAccElastiCacheServerlessCache_fullRedis (345.50s)
--- PASS: TestAccElastiCacheServerlessCache_redisUpdateWithUserGroup (529.95s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elasticache	3642.799s

```

**Review by jar-b — APPROVED** [review]
LGTM 🚀

**Comment by sukumaar** [comment]
Thanks a lot @YakDriver @jar-b

**Comment by YakDriver** [comment]
@sukumaar Thanks for the contribution!
