### PR TITLE
resource/networkfirewall_rule_group: check configuration changes in rules when determining update input

### LINKED ISSUE #19414: aws_networkfirewall_rule_group: cannot update suricata rules
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.15.3
+ provider registry.terraform.io/hashicorp/aws v3.40.0

### Affected Resource(s)

* aws_networkfirewall_rule_group

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_networkfirewall_rule_group" "main" {
  name     = "set1"
  type     = "STATEFUL"
  rules    = file("set1.rules")
  capacity = 100
}
```
Suricata rules `set1.rules` pre-update:
```
pass tls $HOME_NET any -> $EXTERNAL_NET 443 (tls.sni; content:"OLD.example.com"; msg:"FQDN test"; sid:1;)
```

Suricate rules `set1.rules` post-update:
```
pass tls $HOME_NET any -> $EXTERNAL_NET 443 (tls.sni; content:"NEW.example.com"; msg:"FQDN test"; sid:1;)
```

### Debug Output

Running `terraform apply`:
```
Terraform will perform the following actions:

  # aws_networkfirewall_rule_group.main will be updated in-place
  ~ resource "aws_networkfirewall_rule_group" "main" {
        id           = "arn:aws:network-firewall:us-east-1:000000000000:stateful-rulegroup/set1"
        name         = "set1"
      ~ rules        = <<-EOT
          - pass tls $HOME_NET any -> $EXTERNAL_NET 443 (tls.sni; content:"OLD.example.com"; msg:"FQDN test"; sid:1;)
          + pass tls $HOME_NET any -> $EXTERNAL_NET 443 (tls.sni; content:"NEW.example.com"; msg:"FQDN test"; sid:1;)
        EOT
        tags         = {}
        # (5 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

When applied the following occurs:
```
aws_networkfirewall_rule_group.main: Modifying... [id=arn:aws:network-firewall:us-east-1:000000000000:stateful-rulegroup/set1]
╷
│ Error: error updating NetworkFirewall Rule Group (arn:aws:network-firewall:us-east-1:000000000000:stateful-rulegroup/set1): InvalidRequestException: Exactly one of Rules or RuleGroup must be set
│
│   with aws_networkfirewall_rule_group.main,
│   on firewall_rules.tf line 1, in resource "aws_networkfirewall_rule_group" "main":
│    1: resource "aws_networkfirewall_rule_group" "main" {
│
```

### Expected Behavior

Applying this change should update the firewall rule group.

### Actual Behavior

An error was generated, and the rules were not updated in AWS.

Even though an error ocurred, Terraform updated its state. A subsequent plan/apply shows no changes.

### Steps to Reproduce

1. `terraform apply`
2. Update `set1.rules`
3. `terraform apply`
4. Run `terraform apply` again and see that Terraform's state has been updated.

### PR DESCRIPTION
**Pull request by anGie44**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #19414 

Output from acceptance testing:

```
--- PASS: TestAccAwsNetworkFirewallRuleGroup_updateRules (163.26s)

--- PASS: TestAccAwsNetworkFirewallRuleGroup_basic_rules (166.65s)
--- PASS: TestAccAwsNetworkFirewallRuleGroup_basic_rulesSourceList (166.88s)
--- PASS: TestAccAwsNetworkFirewallRuleGroup_statelessRuleWithCustomAction (178.55s)
--- PASS: TestAccAwsNetworkFirewallRuleGroup_basic_statefulRule (178.77s)
--- PASS: TestAccAwsNetworkFirewallRuleGroup_basic_statelessRule (178.78s)
--- PASS: TestAccAwsNetworkFirewallRuleGroup_disappears (193.26s)
--- PASS: TestAccAwsNetworkFirewallRuleGroup_updateRulesSourceList (266.68s)
--- PASS: TestAccAwsNetworkFirewallRuleGroup_updateStatelessRule (312.36s)
--- PASS: TestAccAwsNetworkFirewallRuleGroup_statefulRule_header (312.82s)
--- PASS: TestAccAwsNetworkFirewallRuleGroup_updateStatefulRule (329.79s)
--- PASS: TestAccAwsNetworkFirewallRuleGroup_tags (339.96s)
--- PASS: TestAccAwsNetworkFirewallRuleGroup_updateMultipleStatefulRules (386.25s)
--- PASS: TestAccAwsNetworkFirewallRuleGroup_statefulRule_action (393.60s)
--- PASS: TestAccAwsNetworkFirewallRuleGroup_rulesSourceAndRuleVariables (405.81s)
```

### CODE REVIEW

File: aws/resource_aws_networkfirewall_rule_group.go [hunk 1]
```diff
@@ -511,7 +511,7 @@ func resourceAwsNetworkFirewallRuleGroupUpdate(ctx context.Context, d *schema.Re
 		if v, ok := d.GetOk("description"); ok {
 			input.Description = aws.String(v.(string))
 		}
-		if v, ok := d.GetOk("rule_group"); ok {
+		if v, ok := d.GetOk("rule_group"); ok && !d.HasChange("rules") {
```
Comment (anGie44) [inline aws/resource_aws_networkfirewall_rule_group.go:514]: so i though i would be able to do something like 
```suggestion
		if d.HasChange("rule_group") {
		  ...
		  input.RuleGroup = ...
	        }
	        
	        if d.HasChange("rules") {
	         ...
	         input.Rules = ...
	        }
```
but the Computed nature of `rule_group` returns true for `d.HasChange()`

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

##### Commercial

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAwsNetworkFirewallRuleGroup_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsNetworkFirewallRuleGroup_ -timeout 180m
=== RUN   TestAccAwsNetworkFirewallRuleGroup_basic_rulesSourceList
=== PAUSE TestAccAwsNetworkFirewallRuleGroup_basic_rulesSourceList
=== RUN   TestAccAwsNetworkFirewallRuleGroup_basic_statefulRule
=== PAUSE TestAccAwsNetworkFirewallRuleGroup_basic_statefulRule
=== RUN   TestAccAwsNetworkFirewallRuleGroup_basic_statelessRule
=== PAUSE TestAccAwsNetworkFirewallRuleGroup_basic_statelessRule
=== RUN   TestAccAwsNetworkFirewallRuleGroup_basic_rules
=== PAUSE TestAccAwsNetworkFirewallRuleGroup_basic_rules
=== RUN   TestAccAwsNetworkFirewallRuleGroup_statelessRuleWithCustomAction
=== PAUSE TestAccAwsNetworkFirewallRuleGroup_statelessRuleWithCustomAction
=== RUN   TestAccAwsNetworkFirewallRuleGroup_updateRules
=== PAUSE TestAccAwsNetworkFirewallRuleGroup_updateRules
=== RUN   TestAccAwsNetworkFirewallRuleGroup_updateRulesSourceList
=== PAUSE TestAccAwsNetworkFirewallRuleGroup_updateRulesSourceList
=== RUN   TestAccAwsNetworkFirewallRuleGroup_rulesSourceAndRuleVariables
=== PAUSE TestAccAwsNetworkFirewallRuleGroup_rulesSourceAndRuleVariables
=== RUN   TestAccAwsNetworkFirewallRuleGroup_updateStatefulRule
=== PAUSE TestAccAwsNetworkFirewallRuleGroup_updateStatefulRule
=== RUN   TestAccAwsNetworkFirewallRuleGroup_updateMultipleStatefulRules
=== PAUSE TestAccAwsNetworkFirewallRuleGroup_updateMultipleStatefulRules
=== RUN   TestAccAwsNetworkFirewallRuleGroup_statefulRule_action
=== PAUSE TestAccAwsNetworkFirewallRuleGroup_statefulRule_action
=== RUN   TestAccAwsNetworkFirewallRuleGroup_statefulRule_header
=== PAUSE TestAccAwsNetworkFirewallRuleGroup_statefulRule_header
=== RUN   TestAccAwsNetworkFirewallRuleGroup_updateStatelessRule
=== PAUSE TestAccAwsNetworkFirewallRuleGroup_updateStatelessRule
=== RUN   TestAccAwsNetworkFirewallRuleGroup_tags
=== PAUSE TestAccAwsNetworkFirewallRuleGroup_tags
=== RUN   TestAccAwsNetworkFirewallRuleGroup_disappears
=== PAUSE TestAccAwsNetworkFirewallRuleGroup_disappears
=== CONT  TestAccAwsNetworkFirewallRuleGroup_basic_rulesSourceList
=== CONT  TestAccAwsNetworkFirewallRuleGroup_updateStatefulRule
=== CONT  TestAccAwsNetworkFirewallRuleGroup_statefulRule_header
=== CONT  TestAccAwsNetworkFirewallRuleGroup_statefulRule_action
=== CONT  TestAccAwsNetworkFirewallRuleGroup_updateStatelessRule
=== CONT  TestAccAwsNetworkFirewallRuleGroup_basic_rules
=== CONT  TestAccAwsNetworkFirewallRuleGroup_basic_statefulRule
=== CONT  TestAccAwsNetworkFirewallRuleGroup_updateMultipleStatefulRules
=== CONT  TestAccAwsNetworkFirewallRuleGroup_updateRulesSourceList
=== CONT  TestAccAwsNetworkFirewallRuleGroup_statelessRuleWithCustomAction
=== CONT  TestAccAwsNetworkFirewallRuleGroup_rulesSourceAndRuleVariables
=== CONT  TestAccAwsNetworkFirewallRuleGroup_updateRules
=== CONT  TestAccAwsNetworkFirewallRuleGroup_basic_statelessRule
=== CONT  TestAccAwsNetworkFirewallRuleGroup_disappears
=== CONT  TestAccAwsNetworkFirewallRuleGroup_tags
--- PASS: TestAccAwsNetworkFirewallRuleGroup_basic_rulesSourceList (147.83s)
--- PASS: TestAccAwsNetworkFirewallRuleGroup_basic_rules (148.18s)
--- PASS: TestAccAwsNetworkFirewallRuleGroup_disappears (151.46s)
--- PASS: TestAccAwsNetworkFirewallRuleGroup_updateStatefulRule (164.07s)
--- PASS: TestAccAwsNetworkFirewallRuleGroup_statelessRuleWithCustomAction (168.88s)
--- PASS: TestAccAwsNetworkFirewallRuleGroup_basic_statefulRule (169.17s)
--- PASS: TestAccAwsNetworkFirewallRuleGroup_basic_statelessRule (169.49s)
--- PASS: TestAccAwsNetworkFirewallRuleGroup_statefulRule_header (172.77s)
--- PASS: TestAccAwsNetworkFirewallRuleGroup_updateRulesSourceList (175.44s)
--- PASS: TestAccAwsNetworkFirewallRuleGroup_updateRules (175.62s)
--- PASS: TestAccAwsNetworkFirewallRuleGroup_tags (193.65s)
--- PASS: TestAccAwsNetworkFirewallRuleGroup_updateStatelessRule (196.56s)
--- PASS: TestAccAwsNetworkFirewallRuleGroup_updateMultipleStatefulRules (198.88s)
--- PASS: TestAccAwsNetworkFirewallRuleGroup_rulesSourceAndRuleVariables (207.17s)
--- PASS: TestAccAwsNetworkFirewallRuleGroup_statefulRule_action (209.45s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	212.792s
```
