### PR TITLE
service/s3control: Add d.IsNewResource() checks, public access block update waiters, and standardize read handling

### LINKED ISSUE #18530: resource/aws_s3_account_public_access_block: Add attribute waiters on updates
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The S3 control plane has places that still remain eventually consistent, e.g. as evidenced by some our acceptance testing for attribute updates to the `aws_s3_account_public_access_block` resource:

```
=== RUN   TestAccAWSS3Account_serial/PublicAccessBlock/BlockPublicPolicy
    resource_aws_s3_account_public_access_block_test.go:166: Step 3/4 error: After applying this test step and performing a `terraform refresh`, the plan was not empty.
        stdout


        An execution plan has been generated and is shown below.
        Resource actions are indicated with the following symbols:
          ~ update in-place

        Terraform will perform the following actions:

          # aws_s3_account_public_access_block.test will be updated in-place
          ~ resource "aws_s3_account_public_access_block" "test" {
              ~ block_public_policy     = true -> false
                id                      = "--OMITTED--"
                # (4 unchanged attributes hidden)
            }

        Plan: 0 to add, 1 to change, 0 to destroy.

=== RUN   TestAccAWSS3Account_serial/PublicAccessBlock/IgnorePublicAcls
    resource_aws_s3_account_public_access_block_test.go:206: Step 4/4 error: After applying this test step and performing a `terraform refresh`, the plan was not empty.
        stdout


        An execution plan has been generated and is shown below.
        Resource actions are indicated with the following symbols:
          ~ update in-place

        Terraform will perform the following actions:

          # aws_s3_account_public_access_block.test will be updated in-place
          ~ resource "aws_s3_account_public_access_block" "test" {
                id                      = "--OMITTED--"
              ~ ignore_public_acls      = false -> true
                # (4 unchanged attributes hidden)
            }

        Plan: 0 to add, 1 to change, 0 to destroy.

=== RUN   TestAccAWSS3Account_serial/PublicAccessBlock/BlockPublicPolicy
    resource_aws_s3_account_public_access_block_test.go:166: Step 3/4 error: After applying this test step and performing a `terraform refresh`, the plan was not empty.
        stdout


        An execution plan has been generated and is shown below.
        Resource actions are indicated with the following symbols:
          ~ update in-place

        Terraform will perform the following actions:

          # aws_s3_account_public_access_block.test will be updated in-place
          ~ resource "aws_s3_account_public_access_block" "test" {
              ~ block_public_policy     = true -> false
                id                      = "--OMITTED--"
                # (4 unchanged attributes hidden)
            }

        Plan: 0 to add, 1 to change, 0 to destroy.
```

Adding attribute waiters for this eventual consistency should help the testing pass more consistently (and reduce oddities should practitioner configurations be referencing values and updating them).

### Affected Resource(s)

* aws_s3_account_public_access_block

### PR DESCRIPTION
**Pull request by bflad**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Reference: https://github.com/hashicorp/terraform-provider-aws/issues/16796
Closes #18530

Other s3control resources already implement `d.IsNewResource()` checking.

Output from acceptance testing:

```
--- PASS: TestAccAWSS3AccessPoint_basic (28.97s)
--- PASS: TestAccAWSS3AccessPoint_disappears (24.96s)
--- PASS: TestAccAWSS3AccessPoint_disappears_Bucket (20.92s)
--- PASS: TestAccAWSS3AccessPoint_Policy (72.29s)
--- PASS: TestAccAWSS3AccessPoint_PublicAccessBlockConfiguration (28.96s)
--- PASS: TestAccAWSS3AccessPoint_VpcConfiguration (29.37s)
--- SKIP: TestAccAWSS3AccessPoint_Bucket_Arn (1.78s)

--- PASS: TestAccAWSS3Account_serial (253.40s)
    --- PASS: TestAccAWSS3Account_serial/PublicAccessBlock (253.40s)
        --- PASS: TestAccAWSS3Account_serial/PublicAccessBlock/BlockPublicPolicy (47.72s)
        --- PASS: TestAccAWSS3Account_serial/PublicAccessBlock/IgnorePublicAcls (52.10s)
        --- PASS: TestAccAWSS3Account_serial/PublicAccessBlock/RestrictPublicBuckets (51.18s)
        --- PASS: TestAccAWSS3Account_serial/PublicAccessBlock/basic (18.16s)
        --- PASS: TestAccAWSS3Account_serial/PublicAccessBlock/disappears (14.86s)
        --- PASS: TestAccAWSS3Account_serial/PublicAccessBlock/AccountId (18.18s)
        --- PASS: TestAccAWSS3Account_serial/PublicAccessBlock/BlockPublicAcls (51.19s)
```

### CODE REVIEW

File: aws/resource_aws_s3_account_public_access_block.go [hunk 1]
```diff
@@ -152,17 +154,31 @@ func resourceAwsS3AccountPublicAccessBlockUpdate(d *schema.ResourceData, meta in
...
+	}
+
+	if d.HasChange("restrict_public_buckets") {
+		if _, err := waiter.PublicAccessBlockConfigurationRestrictPublicBucketsUpdated(conn, d.Id(), d.Get("restrict_public_buckets").(bool)); err != nil {
+			return fmt.Errorf("error waiting for S3 Account Public Access Block (%s) restrict_public_buckets update: %w", d.Id(), err)
+		}
+	}
+
+	return resourceAwsS3AccountPublicAccessBlockRead(d, meta)
 }
```
Comment (anGie44) [inline aws/resource_aws_s3_account_public_access_block.go:182]: 🙌

**Review by anGie44 — APPROVED** [review]
Looks great!
