### PR TITLE
Handle pending RDS engine version updates

### LINKED ISSUE #22022: Failing to upgrade Aurora Cluster for Postgres database from version 11.9 to 11.12 using Terraform
Terraform Version = v0.14.6
Provider = AWS
Using TFE
There error is during Apply:

Plan Result

```shell
Terraform will perform the following actions:

module.aurora_01_cluster.aws_rds_cluster.this will be updated in-place
~ resource "aws_rds_cluster" "this" {
~ engine_version = "11.9" -> "11.12"
id = "snaurorapsgcluster"
tags = {

        "Core"            = "true"
        "Description"     = "Aurora Cluster"

    }
    # (34 unchanged attributes hidden)

    # (1 unchanged block hidden)
}
module.aurora_01_cluster_instance_reader.aws_rds_cluster_instance.default will be updated in-place
~ resource "aws_rds_cluster_instance" "default" {
~ engine_version = "11.9" -> "11.12"
id = "snaurorapsginstance"
~ tags = {
+ "Environment" = "Test"
# (10 unchanged elements hidden)
}
~ tags_all = {
+ "Environment" = "Test"
# (10 unchanged elements hidden)
}
# (28 unchanged attributes hidden)
}

module.aurora_01_cluster_instance_writer.aws_rds_cluster_instance.default will be updated in-place
~ resource "aws_rds_cluster_instance" "default" {
~ engine_version = "11.9" -> "11.12"
id = "snaurorapsginstance"
~ tags = {
+ "Environment" = "Test"
# (10 unchanged elements hidden)
}
~ tags_all = {
+ "Environment" = "Test"
# (10 unchanged elements hidden)
}
# (28 unchanged attributes hidden)
}

Plan: 0 to add, 3 to change, 0 to destroy.
```

Apply result:

```shell
�Terraform v0.14.6
Initializing plugins and modules...
�[0m�[1mmodule.aurora_01_cluster.aws_rds_cluster.this: Modifying... [id=snaurorapsgcluster]�[0m�[0m
�[0m�[1mmodule.aurora_01_cluster.aws_rds_cluster.this: Still modifying... [id=snaurorapsgcluster, 10s elapsed]�[0m�[0m
�[0m�[1mmodule.aurora_01_cluster.aws_rds_cluster.this: Still modifying... [id=snaurorapsgcluster, 20s elapsed]�[0m�[0m
�[0m�[1mmodule.aurora_01_cluster.aws_rds_cluster.this: Still modifying... [id=snaurorapsgcluster, 30s elapsed]�[0m�[0m
�[0m�[1mmodule.aurora_01_cluster.aws_rds_cluster.this: Modifications complete after 31s [id=snaurorapsgcluster]�[0m�[0m
�[31m
�[1m�[31mError: �[0m�[0m�[1mProvider produced inconsistent final plan�[0m

�[0mWhen expanding the plan for
module.aurora_01_cluster_instance_writer.aws_rds_cluster_instance.default to
include new values learned so far during apply, provider
"registry.terraform.io/hashicorp/aws" produced an invalid new value for
.engine_version: was cty.StringVal("11.12"), but now cty.StringVal("11.9").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
�[0m�[0m
�[31m
�[1m�[31mError: �[0m�[0m�[1mProvider produced inconsistent final plan�[0m

�[0mWhen expanding the plan for
module.aurora_01_cluster_instance_reader.aws_rds_cluster_instance.default to
include new values learned so far during apply, provider
"registry.terraform.io/hashicorp/aws" produced an invalid new value for
.engine_version: was cty.StringVal("11.12"), but now cty.StringVal("11.9").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
�[0m�[0m
```

### LINKED ISSUE #28219: [Bug]: aws_rds_cluster major version upgrade throws InvalidParameterCombination in second apply attempt
### Terraform Core Version

1.0.8, 0.14.11

### AWS Provider Version

4.30.0

### Affected Resource(s)

aws_rds_cluster
db_instance_parameter_group_name

### Expected Behavior

Trying to upgrade RDS Aurora cluster with one instance from Postgres engine version 13.7 to 14.3
apply_immediately set to true at cluster level. Also db_instance_parameter_group_name is passed to the cluster.
Expect cluster and instance to be upgraded.

### Actual Behavior

On first plan and apply there are no parameter group related error. However if the first run fails for any given reason on second attempt upgrade fails with error:
Error: updating RDS Cluster: InvalidParameterCombination: The current DB instance parameter group is custom. You must explicitly specify a new DB instance parameter group, either default or custom, for the engine version upgrade
If the db_instance_parameter_group_name is changed then apply works again.

### Relevant Error/Panic Output Snippet

```shell
Error: updating RDS Cluster: InvalidParameterCombination: The current DB instance parameter group is custom. You must explicitly specify a new DB instance parameter group, either default or custom, for the engine version upgrade
```

### Terraform Configuration Files

resource "aws_rds_cluster" "aurora_postgres" {
  depends_on = [
    aws_rds_cluster_parameter_group.aurora_postgres_db,
    aws_db_parameter_group.aurora_instance_parameter_group
  ]
  cluster_identifier              = "test-aurora-upgrade-cluster"
  engine                          = "aurora-postgresql"
  engine_version                  = 14.3
  port                            = 6160
  database_name                   = "test"
  allow_major_version_upgrade     = true
  db_cluster_parameter_group_name = aws_rds_cluster_parameter_group.aurora_postgres_db.id
  db_instance_parameter_group_name =aws_db_parameter_group.aurora_instance_parameter_group.id
  apply_immediately          = true
}

### Steps to Reproduce

- Create an rds aurora postgres cluster with one writer instance - engine version 13.7 and custom cluster and instance parameter groups. Set apply_immediately to true
- Once cluster and instance is created change the engine version to 14.3 also change the parameter groups for cluster and instance to family 14
- Make a deliberate mistake so plan completes but apply fails (i had set apply_immediately to false). Plan succeeds but apply will fail
- Revert apply_immediately to true and run apply again. Will get the below error:
Error: updating RDS Cluster: InvalidParameterCombination: The current DB instance parameter group is custom. You must explicitly specify a new DB instance parameter group, either default or custom, for the engine version upgrade

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

No

### LINKED ISSUE #29861: [Bug]: Upgrading Aurora DB engine version produces an error
### Terraform Core Version

1.3.8

### AWS Provider Version

4.57.0

### Affected Resource(s)

* aws_rds_cluster
* aws_rds_instance

### Expected Behavior

I've created a Aurora MySQL DB cluster with no problems, with engine version `2.07.8`, and then changed the version in the Terraform configuration to 2.11.1, and received an error

### Actual Behavior

An error is produced, see the below snippet

### Relevant Error/Panic Output Snippet

```shell
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.mysql_cluster.aws_rds_cluster_instance.this[0] to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced
│ an invalid new value for .engine_version: was cty.StringVal("5.7.mysql_aurora.2.11.1"), but now cty.StringVal("5.7.mysql_aurora.2.07.8").
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

### Terraform Configuration Files

Please browse to my GitHub repo:
https://github.com/yoav-klein/terraform/tree/695797c77868c1ed85fe069289f7ea59843e7b06

In there, we have the `aws/modules/aurora-mysql` which is a module that creates a Aurora MySQL cluster.
We also have the `aws/configurations/aurora-mysql`, which is a configuration which uses the above module, along with
some other modules, to create a VPC, a cluster, an EC2 instance.

### Steps to Reproduce

* Run the configuration with `terraform apply` with the `2.07.8` version. this should work fine
* Change the version to `2.11.1`, and apply the configuration again.

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by jar-b**
### Description
This change fixes "inconsistent final plan" errors caused by deferred engine version updates (`apply_immediately = false`) in the RDS cluster, cluster instance, and instance resources. Specifically, read operations will now check the `PendingModifiedValues` for a non-nil `EngineVersion`. If present, and equal to the existing configured value, this will be stored in state to ensure a consistent final plan and avoid persistent diffs until the update takes place during the next maintenance window.

Additionally, this change improves the cluster update workflow when there are pending updates by:
- Setting the `EngineVersion` field if the configured and "actual" engine versions differ.
  - This can occur when multiple applies happen prior to a maintenance window. In this situation the desired engine version is sent again, rather than omitting the field entirely (the current behavior).
- Setting the `DBInstanceParameterGroupName` field any time the value is set.
  - This attribute is not returned from the `DescribeDBClusters` API, so once set there is no way to detect drift and determine when state does not match the remote value. Sending the value whenever configured avoids errors where the desired value _should_ be sent, but isn't because no drift could be detected. Sending a value that matches the existing remote should have no negative impact.

### Relations

Closes #29861
Closes #22022
Closes #28219
Relates #30245

### References
- [ModifyDBCluster](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ModifyDBCluster.html)
- [CreateDBCluster](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBCluster.html)
- [DescribeDBClusters](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribeDBClusters.html)

### Output from Acceptance Testing

```console
$ make testacc PKG=rds TESTS=TestAccRDSCluster_allowMajorVersionUpgrade
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccRDSCluster_allowMajorVersionUpgrade'  -timeout 180m
=== RUN   TestAccRDSCluster_allowMajorVersionUpgrade
=== PAUSE TestAccRDSCluster_allowMajorVersionUpgrade
=== RUN   TestAccRDSCluster_allowMajorVersionUpgradeNoApplyImmediately
=== PAUSE TestAccRDSCluster_allowMajorVersionUpgradeNoApplyImmediately
=== RUN   TestAccRDSCluster_allowMajorVersionUpgradeWithCustomParametersApplyImm
=== PAUSE TestAccRDSCluster_allowMajorVersionUpgradeWithCustomParametersApplyImm
=== RUN   TestAccRDSCluster_allowMajorVersionUpgradeWithCustomParameters
=== PAUSE TestAccRDSCluster_allowMajorVersionUpgradeWithCustomParameters
=== CONT  TestAccRDSCluster_allowMajorVersionUpgrade
=== CONT  TestAccRDSCluster_allowMajorVersionUpgradeWithCustomParameters
=== CONT  TestAccRDSCluster_allowMajorVersionUpgradeWithCustomParametersApplyImm
=== CONT  TestAccRDSCluster_allowMajorVersionUpgradeNoApplyImmediately
--- PASS: TestAccRDSCluster_allowMajorVersionUpgradeNoApplyImmediately (950.64s)
--- PASS: TestAccRDSCluster_allowMajorVersionUpgrade (2141.41s)
--- PASS: TestAccRDSCluster_allowMajorVersionUpgradeWithCustomParameters (2259.32s)
--- PASS: TestAccRDSCluster_allowMajorVersionUpgradeWithCustomParametersApplyImm (2409.43s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/rds        2412.582s
```

```console
$ make testacc PKG=rds TESTS=TestAccRDSCluster_
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccRDSCluster_'  -timeout 180m
<snip>
--- PASS: TestAccRDSCluster_EngineMode_global (152.24s)
=== CONT  TestAccRDSCluster_SnapshotIdentifier_encryptedRestore
--- PASS: TestAccRDSCluster_iamAuth (161.20s)
=== CONT  TestAccRDSCluster_SnapshotIdentifierVPCSecurityGroupIDs_tags
--- PASS: TestAccRDSCluster_identifierGenerated (162.58s)
=== CONT  TestAccRDSCluster_SnapshotIdentifier_vpcSecurityGroupIDs
--- PASS: TestAccRDSCluster_identifierPrefix (162.75s)
=== CONT  TestAccRDSCluster_SnapshotIdentifier_tags
--- PASS: TestAccRDSCluster_basic (166.60s)
=== CONT  TestAccRDSCluster_SnapshotIdentifier_preferredMaintenanceWindow
--- PASS: TestAccRDSCluster_backupsUpdate (191.74s)
=== CONT  TestAccRDSCluster_SnapshotIdentifier_preferredBackupWindow
--- PASS: TestAccRDSCluster_deletionProtection (204.22s)
=== CONT  TestAccRDSCluster_SnapshotIdentifier_masterUsername
--- PASS: TestAccRDSCluster_copyTagsToSnapshot (302.90s)
=== CONT  TestAccRDSCluster_SnapshotIdentifier_masterPassword
--- PASS: TestAccRDSCluster_Scaling_defaultMinCapacity (306.86s)
=== CONT  TestAccRDSCluster_SnapshotIdentifier_kmsKeyID
--- PASS: TestAccRDSCluster_enableHTTPEndpoint (324.78s)
=== CONT  TestAccRDSCluster_SnapshotIdentifierEngineVersion_equal
--- PASS: TestAccRDSCluster_pointInTimeRestore (467.58s)
=== CONT  TestAccRDSCluster_SnapshotIdentifierEngineVersion_different
--- PASS: TestAccRDSCluster_engineMode (498.77s)
=== CONT  TestAccRDSCluster_SnapshotIdentifierEngineMode_provisioned
--- PASS: TestAccRDSCluster_SnapshotIdentifier_preferredMaintenanceWindow (415.64s)
=== CONT  TestAccRDSCluster_SnapshotIdentifierEngineMode_parallelQuery
    cluster_test.go:1756: Step 1/1 error: Error running apply: exit status 1

        Error: creating RDS Cluster (tf-acc-test-2442697265199590370-source): InvalidParameterCombination: Cannot find version null for aurora
                status code: 400, request id: b8fb3c84-4ec4-4b61-8a45-eda467758d15

          with aws_rds_cluster.source,
          on terraform_plugin_test.tf line 2, in resource "aws_rds_cluster" "source":
           2: resource "aws_rds_cluster" "source" {

=== CONT  TestAccRDSCluster_SnapshotIdentifier_deletionProtection
--- FAIL: TestAccRDSCluster_SnapshotIdentifierEngineMode_parallelQuery (4.26s)
--- PASS: TestAccRDSCluster_SnapshotIdentifier_vpcSecurityGroupIDs (450.67s)
=== CONT  TestAccRDSCluster_snapshotIdentifier
--- PASS: TestAccRDSCluster_SnapshotIdentifier_encryptedRestore (476.70s)
=== CONT  TestAccRDSCluster_availabilityZones
--- PASS: TestAccRDSCluster_SnapshotIdentifierVPCSecurityGroupIDs_tags (470.27s)
=== CONT  TestAccRDSCluster_allowMajorVersionUpgradeWithCustomParameters
--- PASS: TestAccRDSCluster_SnapshotIdentifier_preferredBackupWindow (456.09s)
=== CONT  TestAccRDSCluster_GlobalClusterIdentifierEngineModeGlobal_update
--- PASS: TestAccRDSCluster_SnapshotIdentifier_masterUsername (445.91s)
=== CONT  TestAccRDSCluster_tags
--- PASS: TestAccRDSCluster_SnapshotIdentifier_masterPassword (385.53s)
=== CONT  TestAccRDSCluster_serverlessV2ScalingConfiguration
--- PASS: TestAccRDSCluster_SnapshotIdentifierEngineVersion_equal (415.03s)
=== CONT  TestAccRDSCluster_scaling
--- PASS: TestAccRDSCluster_SnapshotIdentifier_kmsKeyID (446.47s)
=== CONT  TestAccRDSCluster_port
    cluster_test.go:1529: Step 1/2 error: Error running apply: exit status 1

        Error: creating RDS Cluster (tf-acc-test-4181258938337893371): InvalidParameterCombination: The Parameter Group default.aurora-postgresql13 with DBParameterGroupFamily aurora-postgresql13 cannot be used for this instance. Please use a Parameter Group with DBParameterGroupFamily aurora-postgresql14
                status code: 400, request id: 9ccc5fdd-7e47-4045-80c4-b90d3c3e3fca

          with aws_rds_cluster.test,
          on terraform_plugin_test.tf line 2, in resource "aws_rds_cluster" "test":
           2: resource "aws_rds_cluster" "test" {

--- FAIL: TestAccRDSCluster_port (5.41s)
=== CONT  TestAccRDSCluster_EnabledCloudWatchLogsExports_postgresql
--- PASS: TestAccRDSCluster_availabilityZones (176.39s)
=== CONT  TestAccRDSCluster_GlobalClusterIdentifier_secondaryClustersWriteForwarding
    cluster_test.go:1501: Step 1/1 error: Error running apply: exit status 1

        Error: creating RDS Global Cluster: InvalidParameterValue: The requested engine version was not found or does not support global functionality
                status code: 400, request id: 8841bd8c-c280-4607-bcc8-70909151616b

          with aws_rds_global_cluster.test,
          on terraform_plugin_test.tf line 18, in resource "aws_rds_global_cluster" "test":
          18: resource "aws_rds_global_cluster" "test" {

--- FAIL: TestAccRDSCluster_GlobalClusterIdentifier_secondaryClustersWriteForwarding (9.44s)
=== CONT  TestAccRDSCluster_encrypted
--- PASS: TestAccRDSCluster_onlyMajorVersion (860.77s)
=== CONT  TestAccRDSCluster_networkType
--- PASS: TestAccRDSCluster_GlobalClusterIdentifierEngineModeGlobal_update (214.30s)
=== CONT  TestAccRDSCluster_kmsKey
--- PASS: TestAccRDSCluster_tags (213.28s)
=== CONT  TestAccRDSCluster_updateIAMRoles
--- PASS: TestAccRDSCluster_SnapshotIdentifierEngineVersion_different (437.60s)
=== CONT  TestAccRDSCluster_engineVersionWithPrimaryInstance
--- PASS: TestAccRDSCluster_serverlessV2ScalingConfiguration (219.72s)
=== CONT  TestAccRDSCluster_GlobalClusterIdentifierEngineModeGlobal_remove
--- PASS: TestAccRDSCluster_SnapshotIdentifier_tags (780.79s)
=== CONT  TestAccRDSCluster_GlobalClusterIdentifierEngineModeGlobal_add
--- PASS: TestAccRDSCluster_allowMajorVersionUpgradeNoApplyImmediately (969.24s)
=== CONT  TestAccRDSCluster_GlobalClusterIdentifierEngineMode_global
--- PASS: TestAccRDSCluster_SnapshotIdentifierEngineMode_provisioned (486.24s)
=== CONT  TestAccRDSCluster_EnabledCloudWatchLogsExports_mySQL
--- PASS: TestAccRDSCluster_encrypted (184.34s)
=== CONT  TestAccRDSCluster_missingUserNameCausesError
--- PASS: TestAccRDSCluster_missingUserNameCausesError (5.16s)
=== CONT  TestAccRDSCluster_takeFinalSnapshot
--- PASS: TestAccRDSCluster_snapshotIdentifier (405.58s)
=== CONT  TestAccRDSCluster_PointInTimeRestore_enabledCloudWatchLogsExports
--- PASS: TestAccRDSCluster_updateIAMRoles (175.31s)
=== CONT  TestAccRDSCluster_backtrackWindow
--- PASS: TestAccRDSCluster_kmsKey (180.37s)
=== CONT  TestAccRDSCluster_dbSubnetGroupName
--- PASS: TestAccRDSCluster_networkType (208.95s)
=== CONT  TestAccRDSCluster_EngineMode_parallelQuery
    cluster_test.go:1183: Step 1/1 error: Error running apply: exit status 1

        Error: creating RDS Cluster (tf-acc-test-6924192451476223119): InvalidParameterCombination: Cannot find version null for aurora
                status code: 400, request id: 745c2f17-093d-4fa1-822a-2e2b32766a5f

          with aws_rds_cluster.test,
          on terraform_plugin_test.tf line 2, in resource "aws_rds_cluster" "test":
           2: resource "aws_rds_cluster" "test" {

--- FAIL: TestAccRDSCluster_EngineMode_parallelQuery (4.37s)
=== CONT  TestAccRDSCluster_engineVersion
--- PASS: TestAccRDSCluster_scaling (336.55s)
=== CONT  TestAccRDSCluster_dbClusterInstanceClass
--- PASS: TestAccRDSCluster_GlobalClusterIdentifierEngineModeGlobal_add (162.41s)
=== CONT  TestAccRDSCluster_EngineMode_multiMaster
--- PASS: TestAccRDSCluster_GlobalClusterIdentifierEngineModeGlobal_remove (198.33s)
=== CONT  TestAccRDSCluster_GlobalClusterIdentifier_primarySecondaryClusters
--- PASS: TestAccRDSCluster_GlobalClusterIdentifierEngineMode_global (137.64s)
=== CONT  TestAccRDSCluster_GlobalClusterIdentifierEngineMode_provisioned
--- PASS: TestAccRDSCluster_SnapshotIdentifier_deletionProtection (567.98s)
=== CONT  TestAccRDSCluster_disappears
--- PASS: TestAccRDSCluster_dbSubnetGroupName (173.48s)
=== CONT  TestAccRDSCluster_GlobalClusterIdentifier_replicationSourceIdentifier
--- PASS: TestAccRDSCluster_EnabledCloudWatchLogsExports_mySQL (243.87s)
--- PASS: TestAccRDSCluster_backtrackWindow (194.27s)
--- PASS: TestAccRDSCluster_GlobalClusterIdentifierEngineMode_provisioned (148.39s)
--- PASS: TestAccRDSCluster_EngineMode_multiMaster (163.55s)
--- PASS: TestAccRDSCluster_takeFinalSnapshot (276.77s)
--- PASS: TestAccRDSCluster_disappears (142.09s)
--- PASS: TestAccRDSCluster_PointInTimeRestore_enabledCloudWatchLogsExports (398.87s)
--- PASS: TestAccRDSCluster_engineVersion (465.10s)
--- PASS: TestAccRDSCluster_iops (1904.38s)
--- PASS: TestAccRDSCluster_allocatedStorage (1944.34s)
--- PASS: TestAccRDSCluster_storageType (1964.65s)
--- PASS: TestAccRDSCluster_ReplicationSourceIdentifier_kmsKeyID (2151.53s)
--- PASS: TestAccRDSCluster_allowMajorVersionUpgradeWithCustomParametersApplyImm (2190.92s)
=== NAME  TestAccRDSCluster_EnabledCloudWatchLogsExports_postgresql
    cluster_test.go:775: Step 2/2 error: Error running post-apply refresh: exit status 1

        Error: reading RDS Global Cluster for RDS Cluster (tf-acc-test-6347732204348353326): RequestError: send request failed
        caused by: Post "https://rds.us-west-2.amazonaws.com/": read tcp 192.168.0.170:61584->54.240.253.127:443: read: connection reset by peer

          with aws_rds_cluster.test,
          on terraform_plugin_test.tf line 2, in resource "aws_rds_cluster" "test":
           2: resource "aws_rds_cluster" "test" {

--- PASS: TestAccRDSCluster_allowMajorVersionUpgrade (2251.78s)
--- PASS: TestAccRDSCluster_dbClusterInstanceClass (1175.51s)
--- PASS: TestAccRDSCluster_engineVersionWithPrimaryInstance (1349.47s)
--- PASS: TestAccRDSCluster_allowMajorVersionUpgradeWithCustomParameters (1667.27s)
--- FAIL: TestAccRDSCluster_EnabledCloudWatchLogsExports_postgresql (1540.10s)
--- PASS: TestAccRDSCluster_GlobalClusterIdentifier_primarySecondaryClusters (1782.34s)
--- PASS: TestAccRDSCluster_GlobalClusterIdentifier_replicationSourceIdentifier (1895.94s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/rds        3115.569s
FAIL
make: *** [testacc] Error 1
```

Failures are unrelated to this change.

### CODE REVIEW

File: internal/service/rds/cluster.go [hunk 1]
```diff
@@ -1149,8 +1149,11 @@ func resourceClusterUpdate(ctx context.Context, d *schema.ResourceData, meta int
 			input.DBClusterParameterGroupName = aws.String(d.Get("db_cluster_parameter_group_name").(string))
 		}
 
-		if d.HasChange("db_instance_parameter_group_name") {
-			input.DBInstanceParameterGroupName = aws.String(d.Get("db_instance_parameter_group_name").(string))
+		// DB instance parameter group name is not currently returned from the
+		// DescribeDBClusters API. This means there is no drift detection, so when
+		// set, the configured attribute should always be sent on modify.
+		if v, ok := d.GetOk("db_instance_parameter_group_name"); ok || d.HasChange("db_instance_parameter_group_name") {
```
Comment (johnsonaj) [inline internal/service/rds/cluster.go:1155]: I believe `d.GetOk("db_instance_parameter_group_name")` would always get the configured value whether there is a change or not. `d.HasChange()` might not be needed here.

This should work similar to how `d.Get("apply_immediately)` works in an update. It is always passed into input

File: internal/service/rds/cluster.go [hunk 2]
```diff
@@ -1180,6 +1183,13 @@ func resourceClusterUpdate(ctx context.Context, d *schema.ResourceData, meta int
 			input.EngineVersion = aws.String(d.Get("engine_version").(string))
 		}
 
+		// This can happen when updates are deferred (apply_immediately = false), and
+		// multiple applies occur before the maintenance window. In this case,
+		// continue sending the desired engine_version as part of the modify request.
+		if d.Get("engine_version").(string) != d.Get("engine_version_actual").(string) {
```
Comment (ewbankkit) [inline internal/service/rds/cluster.go:1189]: Is there anything to be gained from checking whether `apply_immediately` _is_ `false` here?

File: internal/service/rds/cluster.go (hunk 1 above)
Comment (jar-b) [reply internal/service/rds/cluster.go:1155]: Yeah, I wasn't positive here - I kept `d.HasChange()` to preserve backward compatibility with the previous behavior.

Based on the old implementation, I assumed an empty input was required to remove an existing parameter group if the configuration removes it (while omitting the input would leave it unchanged). If omitting the value causes the same behavior as an empty input I think we can safely remove though.

File: internal/service/rds/cluster.go (hunk 2 above)
Comment (jar-b) [reply internal/service/rds/cluster.go:1189]: Good question, edge cases are tough to reason about here. One potential case could be an out of band deferred engine_version upgrade.

- Config has `apply_immediately = true`, `engine_version = 1.0.0`
- Major `engine_version` upgrade (2.0.0) is done in the console, but deferred
- On the next read, `engine_version = 2.0.0` (from pending updates), `engine_version_actual = 1.0.0`

If the user then updates their config `engine_version = "2.0.0"` (now matches refreshed state) and runs an `apply`, the current implementation would hit this conditional and set the `EngineVersion` input to `2.0.0`. If we added an `if !d.Get("apply_immediately")` condition, neither the `d.HasChange("engine_version")` or this condition would return true, leaving `EngineVersion` unset in the ModifyDBCluster request.
