### PR TITLE
resource/aws_mq_broker: Adds nullable bool for `audit`

### LINKED ISSUE #18067: aws_mq_broker RabbitMQ general logs cannot be enabled
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/aws v3.32.0

### Affected Resource(s)
* aws_mq_broker

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_mq_broker" "rabbitmq" {
  broker_name = "my-broker"
  engine_type = "RabbitMQ"
  engine_version = "3.8.6"
  // enabling cloudwatch logging
  logs {
    general = true
  }

```

### Debug Output

```
Terraform will perform the following actions:

  # aws_mq_broker.rabbitmq will be created
  + resource "aws_mq_broker" "rabbitmq" {
      + apply_immediately          = false
      + authentication_strategy    = "SIMPLE"
      + broker_name                = "my-broker"
      + deployment_mode            = "SINGLE_INSTANCE"
      + engine_type                = "RabbitMQ"
      + engine_version             = "3.8.6"

      + logs {
          + general = true
        }
```

### Panic Output

```
Error: BadRequestException: Audit logging is not supported for RabbitMQ brokers.
```

### Expected Behavior

General logging via CloudWatch should be enabled, given that `logs` configuration only specify `general` and omitted `audit`

### Actual Behavior

```
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "..."
  },
  ErrorAttribute: "logs.audit",
  Message_: "Audit logging is not supported for RabbitMQ brokers."
}
Audit logging is not supported for RabbitMQ brokers
```

### Steps to Reproduce

Create aws_mq_broker RabbitMQ resource enabling just logs `general`.

1. `terraform apply`

### Important Factoids

Specifying `audit = null` also yields same outcome.

### References

* #0000 https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/mq_broker#logs

### LINKED ISSUE #18350: Unable to create Amazon MQ RabbitMQ broker with logging enabled.
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/aws v3.33.0

### Affected Resource(s)

* aws_mq_broker

### Terraform Configuration Files

```hcl

resource "aws_mq_broker" "this" {
  broker_name = var.name

  subnet_ids = var.subnet_ids
  security_groups = var.security_group_ids

  deployment_mode = length(var.subnet_ids) == 1 ? "SINGLE_INSTANCE" : "CLUSTER_MULTI_AZ"

  publicly_accessible =  false

  engine_type = "RabbitMQ"
  engine_version           = "3.8.6"

  host_instance_type = var.instance_type


  # RabbitMQ only supports general logs, no audit logs 
  logs {
    general = true
    audit = false
  }

  user {
    username = var.username
    password = var.password
  }

  auto_minor_version_upgrade  = false

  maintenance_window_start_time {
    day_of_week = "SUNDAY"
    time_of_day = "03:00"
    time_zone = "UTC"
  }
}



```

### Expected Behavior

The broker should be created with general logs enabled.

### Actual Behavior

AWS throws an error:

```
module.rabbitmq.aws_mq_broker.this: Creating...

Error: BadRequestException: Audit logging is not supported for RabbitMQ brokers.
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "35ad4197-8cd0-4a6a-a547-4700c568681c"
  },
  ErrorAttribute: "logs.audit",
  Message_: "Audit logging is not supported for RabbitMQ brokers."
}

```

### Steps to Reproduce

1. Create `variables.tf` with the following variables:
  - subnet_ids
  - security_group_ids
  - name
  - username
  - password

2.  then `main.tf` with above manifest.
3. `terraform apply`

### PR DESCRIPTION
**Pull request by gdavison**
When the `engine_type` is `RABBITMQ`, no value for `logs.audit` is allowed, not even `false`.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #18067
Closes #18350

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSMqBroker_'

--- PASS: TestAccAWSMqBroker_rabbitmq_Logs (626.20s)
--- PASS: TestAccAWSMqBroker_throughputOptimized (664.12s)
--- PASS: TestAccAWSMqBroker_rabbitmq_Validation_AuditLog (756.43s)
--- PASS: TestAccAWSMqBroker_clusterRabbitMQ (768.65s)
--- PASS: TestAccAWSMqBroker_rabbitmq (771.58s)
--- PASS: TestAccAWSMqBroker_disappears (1105.31s)
--- PASS: TestAccAWSMqBroker_ldap (1122.57s)
--- PASS: TestAccAWSMqBroker_basic (1141.67s)
--- PASS: TestAccAWSMqBroker_EncryptionOptions_KmsKeyId (1153.39s)
--- PASS: TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Enabled (1156.94s)
--- PASS: TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Disabled (1176.22s)
--- PASS: TestAccAWSMqBroker_tags (1195.02s)
--- PASS: TestAccAWSMqBroker_updateEngineVersion (1373.76s)
--- PASS: TestAccAWSMqBroker_updateSecurityGroup (1409.84s)
--- PASS: TestAccAWSMqBroker_updateUsers (1595.92s)
--- PASS: TestAccAWSMqBroker_allFieldsDefaultVpc (1771.77s)
--- PASS: TestAccAWSMqBroker_allFieldsCustomVpc (1850.80s)
```

### CODE REVIEW

File: aws/resource_aws_mq_broker.go [hunk 1]
```diff
@@ -217,8 +222,17 @@ func resourceAwsMqBroker() *schema.Resource {
 							Optional: true,
 						},
 						"audit": {
-							Type:     schema.TypeBool,
-							Optional: true,
+							Type:         nullable.TypeNullableBool,
+							Optional:     true,
+							ValidateFunc: nullable.ValidateTypeStringNullableBool,
+							DiffSuppressFunc: func(k, o, n string, d *schema.ResourceData) bool {
```
Comment (ewbankkit) [inline aws/resource_aws_mq_broker.go:228]: This seems like something that could be useful in other places where we would be using nullable bools - Do you want to extract it to `diff_suppress_funcs.go` or somewhere similar?

**Review by ewbankkit — APPROVED** [review]
LGTM 🚀.

##### Commercial

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSMqBroker_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSMqBroker_ -timeout 180m
=== RUN   TestAccAWSMqBroker_basic
=== PAUSE TestAccAWSMqBroker_basic
=== RUN   TestAccAWSMqBroker_throughputOptimized
=== PAUSE TestAccAWSMqBroker_throughputOptimized
=== RUN   TestAccAWSMqBroker_allFieldsDefaultVpc
=== PAUSE TestAccAWSMqBroker_allFieldsDefaultVpc
=== RUN   TestAccAWSMqBroker_allFieldsCustomVpc
=== PAUSE TestAccAWSMqBroker_allFieldsCustomVpc
=== RUN   TestAccAWSMqBroker_EncryptionOptions_KmsKeyId
=== PAUSE TestAccAWSMqBroker_EncryptionOptions_KmsKeyId
=== RUN   TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Disabled
=== PAUSE TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Disabled
=== RUN   TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Enabled
=== PAUSE TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Enabled
=== RUN   TestAccAWSMqBroker_updateUsers
=== PAUSE TestAccAWSMqBroker_updateUsers
=== RUN   TestAccAWSMqBroker_tags
=== PAUSE TestAccAWSMqBroker_tags
=== RUN   TestAccAWSMqBroker_updateSecurityGroup
=== PAUSE TestAccAWSMqBroker_updateSecurityGroup
=== RUN   TestAccAWSMqBroker_updateEngineVersion
=== PAUSE TestAccAWSMqBroker_updateEngineVersion
=== RUN   TestAccAWSMqBroker_disappears
=== PAUSE TestAccAWSMqBroker_disappears
=== RUN   TestAccAWSMqBroker_rabbitmq
=== PAUSE TestAccAWSMqBroker_rabbitmq
=== RUN   TestAccAWSMqBroker_rabbitmq_Logs
=== PAUSE TestAccAWSMqBroker_rabbitmq_Logs
=== RUN   TestAccAWSMqBroker_rabbitmq_Validation_AuditLog
=== PAUSE TestAccAWSMqBroker_rabbitmq_Validation_AuditLog
=== RUN   TestAccAWSMqBroker_clusterRabbitMQ
=== PAUSE TestAccAWSMqBroker_clusterRabbitMQ
=== RUN   TestAccAWSMqBroker_ldap
=== PAUSE TestAccAWSMqBroker_ldap
=== CONT  TestAccAWSMqBroker_basic
=== CONT  TestAccAWSMqBroker_updateSecurityGroup
=== CONT  TestAccAWSMqBroker_rabbitmq_Logs
=== CONT  TestAccAWSMqBroker_rabbitmq_Validation_AuditLog
=== CONT  TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Enabled
=== CONT  TestAccAWSMqBroker_clusterRabbitMQ
=== CONT  TestAccAWSMqBroker_allFieldsCustomVpc
=== CONT  TestAccAWSMqBroker_EncryptionOptions_KmsKeyId
=== CONT  TestAccAWSMqBroker_updateEngineVersion
=== CONT  TestAccAWSMqBroker_ldap
=== CONT  TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Disabled
=== CONT  TestAccAWSMqBroker_tags
=== CONT  TestAccAWSMqBroker_updateUsers
=== CONT  TestAccAWSMqBroker_disappears
=== CONT  TestAccAWSMqBroker_rabbitmq
=== CONT  TestAccAWSMqBroker_allFieldsDefaultVpc
=== CONT  TestAccAWSMqBroker_throughputOptimized
--- PASS: TestAccAWSMqBroker_rabbitmq_Logs (519.05s)
--- PASS: TestAccAWSMqBroker_rabbitmq (520.36s)
--- PASS: TestAccAWSMqBroker_rabbitmq_Validation_AuditLog (580.80s)
--- PASS: TestAccAWSMqBroker_throughputOptimized (834.85s)
--- PASS: TestAccAWSMqBroker_clusterRabbitMQ (874.28s)
--- PASS: TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Enabled (1131.64s)
--- PASS: TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Disabled (1166.04s)
--- PASS: TestAccAWSMqBroker_tags (1174.10s)
--- PASS: TestAccAWSMqBroker_basic (1174.19s)
--- PASS: TestAccAWSMqBroker_ldap (1175.03s)
--- PASS: TestAccAWSMqBroker_disappears (1193.60s)
--- PASS: TestAccAWSMqBroker_EncryptionOptions_KmsKeyId (1209.42s)
--- PASS: TestAccAWSMqBroker_updateSecurityGroup (1367.61s)
--- PASS: TestAccAWSMqBroker_updateEngineVersion (1402.56s)
--- PASS: TestAccAWSMqBroker_updateUsers (1554.07s)
--- PASS: TestAccAWSMqBroker_allFieldsDefaultVpc (1755.23s)
--- PASS: TestAccAWSMqBroker_allFieldsCustomVpc (1782.56s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	1785.456s
```

Amazon MQ not supported in GovCloud.
