### PR TITLE
[bugfix] aws_vpc_endpoint:  Fix persistent diffs caused by case differences in `ip_address_type`

### LINKED ISSUE #45946: aws_vpc_endpoint non-idempotency for ip_address_type
### Terraform and AWS Provider Version

```console
Terraform v1.14.3
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v6.28.0
```

### Affected Resource(s) or Data Source(s)

* `aws_vpc_endpoint`

### Expected Behavior

No changes during each terraform execution

### Actual Behavior

According to the provider documentation https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_endpoint.html#ip_address_type-1 
```
[ip_address_type]
(Optional) The IP address type for the endpoint. Valid values are ipv4, dualstack, and ipv6.
``` 

but terraform updates endpoint each run to uppercase:
```
Terraform will perform the following actions:
  # aws_vpc_endpoint.services["shared"] will be updated in-place
  ~ resource "aws_vpc_endpoint" "services" {
        id                         = "vpce-XXX"
      ~ ip_address_type            = "IPV4" -> "ipv4"
        # (20 unchanged attributes hidden)
        # (4 unchanged blocks hidden)
    }
```

### Relevant Error/Panic Output

```console

```

### Sample Terraform Configuration

<details open>
<summary>Click to expand configuration</summary>

```hcl
resource "aws_vpc_endpoint" "services" {
  vpc_endpoint_type = "ServiceNetwork"
  vpc_id            = module.vpc-info.vpc_id
  ip_address_type   = "ipv4"
```
</details>

### Steps to Reproduce

- run terraform apply
- run terraform appy again, observe changes applied

### Debug Logging

<details open>
<summary>Click to expand log output</summary>

```console

```
</details>

### GenAI / LLM Assisted Development

n/a

### Important Facts and References

_No response_

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by tabito-hara**
## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the library.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

### Description

Issue #45946 reported a persistent diff caused by uppercase/lowercase differences in `ip_address_type`.

Although the AWS API documentation states that `ip_address_type` is returned in lowercase, the AWS API returns it in uppercase in some cases. This inconsistency is the root cause of the reported issue.

Without the fix in this PR, the newly added acceptance test reproduces the reported behavior.

It can also be confirmed that some of the existing acceptance tests expect `IPV4` rather than `ipv4`, which does not follow the API specification described in the AWS documentation.

To address this issue, diffs caused by case differences are suppressed by implementing `DiffSuppressFunc`.

### Relations

Closes #45946

### References
https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateVpcEndpoint.html
https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_VpcEndpoint.html

### Output from Acceptance Testing

```console
$ make testacc TESTS='TestAccVPCEndpoint_' PKG=ec2
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 b-aws_vpc_endpoint-suppress_diff_ip_address_type 🌿...
TF_ACC=1 go1.25.5 test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccVPCEndpoint_'  -timeout 360m -vet=off
2026/01/14 07:53:30 Creating Terraform AWS Provider (SDKv2-style)...
2026/01/14 07:53:30 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccVPCEndpoint_gatewayBasic
=== PAUSE TestAccVPCEndpoint_gatewayBasic
=== RUN   TestAccVPCEndpoint_interfaceBasic
=== PAUSE TestAccVPCEndpoint_interfaceBasic
=== RUN   TestAccVPCEndpoint_interfaceNoPrivateDNS
=== PAUSE TestAccVPCEndpoint_interfaceNoPrivateDNS
=== RUN   TestAccVPCEndpoint_interfacePrivateDNS
=== PAUSE TestAccVPCEndpoint_interfacePrivateDNS
=== RUN   TestAccVPCEndpoint_interfacePrivateDNS_updateWithDefaults
=== PAUSE TestAccVPCEndpoint_interfacePrivateDNS_updateWithDefaults
=== RUN   TestAccVPCEndpoint_interfacePrivateDNSNoGateway
=== PAUSE TestAccVPCEndpoint_interfacePrivateDNSNoGateway
=== RUN   TestAccVPCEndpoint_disappears
=== PAUSE TestAccVPCEndpoint_disappears
=== RUN   TestAccVPCEndpoint_tags
=== PAUSE TestAccVPCEndpoint_tags
=== RUN   TestAccVPCEndpoint_gatewayWithRouteTableAndPolicy
=== PAUSE TestAccVPCEndpoint_gatewayWithRouteTableAndPolicy
=== RUN   TestAccVPCEndpoint_gatewayPolicy
=== PAUSE TestAccVPCEndpoint_gatewayPolicy
=== RUN   TestAccVPCEndpoint_ignoreEquivalent
=== PAUSE TestAccVPCEndpoint_ignoreEquivalent
=== RUN   TestAccVPCEndpoint_ipAddressType
=== PAUSE TestAccVPCEndpoint_ipAddressType
=== RUN   TestAccVPCEndpoint_interfaceWithSubnetAndSecurityGroup
=== PAUSE TestAccVPCEndpoint_interfaceWithSubnetAndSecurityGroup
=== RUN   TestAccVPCEndpoint_interfaceNonAWSServiceAcceptOnCreate
=== PAUSE TestAccVPCEndpoint_interfaceNonAWSServiceAcceptOnCreate
=== RUN   TestAccVPCEndpoint_interfaceNonAWSServiceAcceptOnUpdate
=== PAUSE TestAccVPCEndpoint_interfaceNonAWSServiceAcceptOnUpdate
=== RUN   TestAccVPCEndpoint_interfaceUserDefinedIPv4
=== PAUSE TestAccVPCEndpoint_interfaceUserDefinedIPv4
=== RUN   TestAccVPCEndpoint_interfaceUserDefinedIPv6
=== PAUSE TestAccVPCEndpoint_interfaceUserDefinedIPv6
=== RUN   TestAccVPCEndpoint_interfaceUserDefinedDualstack
=== PAUSE TestAccVPCEndpoint_interfaceUserDefinedDualstack
=== RUN   TestAccVPCEndpoint_VPCEndpointType_gatewayLoadBalancer
=== PAUSE TestAccVPCEndpoint_VPCEndpointType_gatewayLoadBalancer
=== RUN   TestAccVPCEndpoint_crossRegionService
=== PAUSE TestAccVPCEndpoint_crossRegionService
=== RUN   TestAccVPCEndpoint_invalidCrossRegionService
=== PAUSE TestAccVPCEndpoint_invalidCrossRegionService
=== RUN   TestAccVPCEndpoint_resourceConfiguration
=== PAUSE TestAccVPCEndpoint_resourceConfiguration
=== RUN   TestAccVPCEndpoint_resourceConfigurationPrivateDNSOptions
=== PAUSE TestAccVPCEndpoint_resourceConfigurationPrivateDNSOptions
=== RUN   TestAccVPCEndpoint_serviceNetwork
=== PAUSE TestAccVPCEndpoint_serviceNetwork
=== RUN   TestAccVPCEndpoint_serviceNetworkWithExplicitIPAddressType
=== PAUSE TestAccVPCEndpoint_serviceNetworkWithExplicitIPAddressType
=== RUN   TestAccVPCEndpoint_serviceNetworkPrivateDNSOptions
=== PAUSE TestAccVPCEndpoint_serviceNetworkPrivateDNSOptions
=== RUN   TestAccVPCEndpoint_crossRegionInterfaceAlternateRegion
=== PAUSE TestAccVPCEndpoint_crossRegionInterfaceAlternateRegion
=== RUN   TestAccVPCEndpoint_crossRegionInterfaceGlobalService
=== PAUSE TestAccVPCEndpoint_crossRegionInterfaceGlobalService
=== RUN   TestAccVPCEndpoint_gatewayIPv6
=== PAUSE TestAccVPCEndpoint_gatewayIPv6
=== RUN   TestAccVPCEndpoint_interfaceWithPrivateDNSOnlyForInboundResolverEndpoint
=== PAUSE TestAccVPCEndpoint_interfaceWithPrivateDNSOnlyForInboundResolverEndpoint
=== CONT  TestAccVPCEndpoint_gatewayBasic
=== CONT  TestAccVPCEndpoint_interfaceUserDefinedIPv4
=== CONT  TestAccVPCEndpoint_interfaceBasic
=== CONT  TestAccVPCEndpoint_serviceNetwork
=== CONT  TestAccVPCEndpoint_crossRegionService
=== CONT  TestAccVPCEndpoint_resourceConfiguration
=== CONT  TestAccVPCEndpoint_crossRegionInterfaceGlobalService
=== CONT  TestAccVPCEndpoint_gatewayWithRouteTableAndPolicy
=== CONT  TestAccVPCEndpoint_interfaceNonAWSServiceAcceptOnUpdate
=== CONT  TestAccVPCEndpoint_interfaceNonAWSServiceAcceptOnCreate
=== CONT  TestAccVPCEndpoint_interfaceWithSubnetAndSecurityGroup
=== CONT  TestAccVPCEndpoint_ipAddressType
=== CONT  TestAccVPCEndpoint_ignoreEquivalent
=== CONT  TestAccVPCEndpoint_gatewayPolicy
=== CONT  TestAccVPCEndpoint_interfacePrivateDNS_updateWithDefaults
=== CONT  TestAccVPCEndpoint_tags
=== CONT  TestAccVPCEndpoint_disappears
=== CONT  TestAccVPCEndpoint_interfacePrivateDNSNoGateway
=== CONT  TestAccVPCEndpoint_interfaceNoPrivateDNS
=== CONT  TestAccVPCEndpoint_interfacePrivateDNS
--- PASS: TestAccVPCEndpoint_disappears (50.74s)
=== CONT  TestAccVPCEndpoint_crossRegionInterfaceAlternateRegion
--- PASS: TestAccVPCEndpoint_interfaceNoPrivateDNS (60.19s)
=== CONT  TestAccVPCEndpoint_resourceConfigurationPrivateDNSOptions
--- PASS: TestAccVPCEndpoint_ignoreEquivalent (69.81s)
=== CONT  TestAccVPCEndpoint_serviceNetworkPrivateDNSOptions
--- PASS: TestAccVPCEndpoint_interfaceBasic (72.33s)
=== CONT  TestAccVPCEndpoint_serviceNetworkWithExplicitIPAddressType
--- PASS: TestAccVPCEndpoint_serviceNetwork (92.16s)
=== CONT  TestAccVPCEndpoint_interfaceWithPrivateDNSOnlyForInboundResolverEndpoint
--- PASS: TestAccVPCEndpoint_tags (93.18s)
=== CONT  TestAccVPCEndpoint_invalidCrossRegionService
--- PASS: TestAccVPCEndpoint_gatewayPolicy (115.39s)
=== CONT  TestAccVPCEndpoint_interfaceUserDefinedDualstack
--- PASS: TestAccVPCEndpoint_gatewayBasic (116.43s)
=== CONT  TestAccVPCEndpoint_gatewayIPv6
--- PASS: TestAccVPCEndpoint_gatewayWithRouteTableAndPolicy (146.11s)
=== CONT  TestAccVPCEndpoint_VPCEndpointType_gatewayLoadBalancer
--- PASS: TestAccVPCEndpoint_serviceNetworkWithExplicitIPAddressType (75.41s)
=== CONT  TestAccVPCEndpoint_interfaceUserDefinedIPv6
--- PASS: TestAccVPCEndpoint_resourceConfiguration (151.21s)
--- PASS: TestAccVPCEndpoint_gatewayIPv6 (91.47s)
--- PASS: TestAccVPCEndpoint_interfaceUserDefinedIPv4 (208.69s)
--- PASS: TestAccVPCEndpoint_interfaceNonAWSServiceAcceptOnCreate (296.71s)
--- PASS: TestAccVPCEndpoint_invalidCrossRegionService (210.70s)
--- PASS: TestAccVPCEndpoint_interfaceNonAWSServiceAcceptOnUpdate (309.93s)
--- PASS: TestAccVPCEndpoint_ipAddressType (324.39s)
--- PASS: TestAccVPCEndpoint_serviceNetworkPrivateDNSOptions (266.25s)
--- PASS: TestAccVPCEndpoint_interfaceUserDefinedDualstack (237.69s)
--- PASS: TestAccVPCEndpoint_interfaceWithSubnetAndSecurityGroup (361.03s)
--- PASS: TestAccVPCEndpoint_interfaceUserDefinedIPv6 (225.29s)
--- PASS: TestAccVPCEndpoint_resourceConfigurationPrivateDNSOptions (334.34s)
--- PASS: TestAccVPCEndpoint_VPCEndpointType_gatewayLoadBalancer (373.34s)
--- PASS: TestAccVPCEndpoint_interfacePrivateDNSNoGateway (527.96s)
--- PASS: TestAccVPCEndpoint_crossRegionInterfaceGlobalService (534.09s)
--- PASS: TestAccVPCEndpoint_crossRegionService (578.90s)
--- PASS: TestAccVPCEndpoint_interfacePrivateDNS (580.21s)
--- PASS: TestAccVPCEndpoint_interfaceWithPrivateDNSOnlyForInboundResolverEndpoint (520.93s)
--- PASS: TestAccVPCEndpoint_crossRegionInterfaceAlternateRegion (638.67s)
--- PASS: TestAccVPCEndpoint_interfacePrivateDNS_updateWithDefaults (927.19s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        931.882s


```

### CODE REVIEW

File: internal/service/ec2/vpc_endpoint.go [hunk 1]
```diff
@@ -121,9 +121,12 @@ func resourceVPCEndpoint() *schema.Resource {
 				},
 			},
 			names.AttrIPAddressType: {
-				Type:             schema.TypeString,
-				Optional:         true,
-				Computed:         true,
+				Type:     schema.TypeString,
+				Optional: true,
+				Computed: true,
+				DiffSuppressFunc: func(k, oldValue, newValue string, d *schema.ResourceData) bool {
```
Comment (ewbankkit) [inline internal/service/ec2/vpc_endpoint.go]: Can use `internal/sdkv2/suppress.go`, `SuppressEquivalentStringCaseInsensitive()`.

Comment (tabito-hara) [reply internal/service/ec2/vpc_endpoint.go]: Thank you for your comment.
I updated the implementation to use `sdkv2.SuppressEquivalentStringCaseInsensitive` and reran the acceptance tests.

**Comment by ewbankkit** [comment]
@tabito-hara Thanks for the contribution :tada: :clap:.
