### PR TITLE
r/aws_dms_replication_config: Add missing task settings

### LINKED ISSUE #35573: [Bug]: aws_dms_replication_config has persistent changes
### Terraform Core Version

1.3.1

### AWS Provider Version

5.34.0

### Affected Resource(s)

aws_dms_replication_config

### Expected Behavior

Apply config parameters consistently

### Actual Behavior

It wants to remove the replication_settings and it is not configured by terraform. In my replication_settings, I just configure the "Logging" settings. However, the terraform plan show many changes of replication_settings.

I have reported issue https://github.com/hashicorp/terraform-provider-aws/issues/35493 and it said this bug is fixed in 5.32.0. However, this issue still exists in 5.34.0.

### Relevant Error/Panic Output Snippet

```shell
# On plan:
# module.dms_replication_instance.aws_dms_replication_config.dms_cdc_serverless_replication will be updated in-place
  ~ resource "aws_dms_replication_config" "dms_cdc_serverless_replication" {
        id                            = "arn:aws:dms:us-east-1:192609132212:replication-config:devint-common-domain-cdc"
      ~ replication_settings          = jsonencode(
          ~ {
              - BeforeImageSettings                 = null -> null
              - ChangeProcessingDdlHandlingPolicy   = {
                  - HandleSourceTableAltered   = true
                  - HandleSourceTableDropped   = true
                  - HandleSourceTableTruncated = true
                } -> null
              - ChangeProcessingTuning              = {
                  - BatchApplyMemoryLimit         = 500
                  - BatchApplyPreserveTransaction = true
                  - BatchApplyTimeoutMax          = 30
                  - BatchApplyTimeoutMin          = 1
                  - BatchSplitSize                = 0
                  - CommitTimeout                 = 1
                  - MemoryKeepTime                = 60
                  - MemoryLimitTotal              = 1024
                  - MinTransactionSize            = 1000
                  - StatementCacheSize            = 50
                } -> null
              - CharacterSetSettings                = null -> null
              - ControlTablesSettings               = {
                  - CommitPositionTableEnabled    = false
                  - ControlSchema                 = ""
                  - FullLoadExceptionTableEnabled = false
                  - HistoryTableEnabled           = false
                  - HistoryTimeslotInMinutes      = 5
                  - StatusTableEnabled            = false
                  - SuspendedTablesTableEnabled   = false
                  - historyTimeslotInMinutes      = 5
                } -> null
              - ErrorBehavior                       = {
                  - ApplyErrorDeletePolicy                      = "IGNORE_RECORD"
                  - ApplyErrorEscalationCount                   = 0
                  - ApplyErrorEscalationPolicy                  = "LOG_ERROR"
                  - ApplyErrorFailOnTruncationDdl               = false
                  - ApplyErrorInsertPolicy                      = "LOG_ERROR"
                  - ApplyErrorUpdatePolicy                      = "LOG_ERROR"
                  - DataErrorEscalationCount                    = 0
                  - DataErrorEscalationPolicy                   = "SUSPEND_TABLE"
                  - DataErrorPolicy                             = "LOG_ERROR"
                  - DataTruncationErrorPolicy                   = "LOG_ERROR"
                  - EventErrorPolicy                            = "IGNORE"
                  - FailOnNoTablesCaptured                      = true
                  - FailOnTransactionConsistencyBreached        = false
                  - FullLoadIgnoreConflicts                     = true
                  - RecoverableErrorCount                       = -1
                  - RecoverableErrorInterval                    = 5
                  - RecoverableErrorStopRetryAfterThrottlingMax = true
                  - RecoverableErrorThrottling                  = true
                  - RecoverableErrorThrottlingMax               = 1800
                  - TableErrorEscalationCount                   = 0
                  - TableErrorEscalationPolicy                  = "STOP_TASK"
                  - TableErrorPolicy                            = "SUSPEND_TABLE"
                } -> null
              - FailTaskWhenCleanTaskResourceFailed = false -> null
              - FullLoadSettings                    = {
                  - CommitRate                      = 10000
                  - CreatePkAfterFullLoad           = false
                  - MaxFullLoadSubTasks             = 8
                  - StopTaskCachedChangesApplied    = false
                  - StopTaskCachedChangesNotApplied = false
                  - TargetTablePrepMode             = "DO_NOTHING"
                  - TransactionConsistencyTimeout   = 600
                } -> null
              ~ Logging                             = {
                  - CloudWatchLogGroup  = "dms-serverless-replication-devint-common-domain-cdc" -> null
                  - CloudWatchLogStream = "dms-serverless-serv-res-id-1706673342400-mt2" -> null
                  - EnableLogContext    = false -> null
                    # (2 unchanged elements hidden)
                }
              - LoopbackPreventionSettings          = null -> null
              - PostProcessingRules                 = null -> null
              - StreamBufferSettings                = {
                  - CtrlStreamBufferSizeInMB = 5
                  - StreamBufferCount        = 3
                  - StreamBufferSizeInMB     = 8
                } -> null
              - TTSettings                          = {
                  - EnableTT            = false
                  - FailTaskOnTTFailure = false
                  - TTRecordSettings    = null
                  - TTS3Settings        = null
                } -> null
              - TargetMetadata                      = {
                  - BatchApplyEnabled            = false
                  - FullLobMode                  = false
                  - InlineLobMaxSize             = 0
                  - LimitedSizeLobMode           = true
                  - LoadMaxFileSize              = 0
                  - LobChunkSize                 = 64
                  - LobMaxSize                   = 32
                  - ParallelApplyBufferSize      = 0
                  - ParallelApplyQueuesPerThread = 0
                  - ParallelApplyThreads         = 0
                  - ParallelLoadBufferSize       = 0
                  - ParallelLoadQueuesPerThread  = 0
                  - ParallelLoadThreads          = 0
                  - SupportLobs                  = true
                  - TargetSchema                 = ""
                  - TaskRecoveryTableEnabled     = false
                } -> null
            }
        )
        tags                          = {
            "Client"   = "ksc"
            "Domain"   = "common-domain"
            "Solution" = "indy"
            "Type"     = "cdc"
            "Use"      = "devint"
        }
        # (9 unchanged attributes hidden)
        # (1 unchanged block hidden)
    }

# On apply:
│ Error: modifying DMS Replication Config (arn:aws:dms:us-east-1:192609132212:replication-config:devint-holding-domain): InvalidParameterCombinationException: No modifications requested for replication config with arn, 'arn:aws:dms:us-east-1:192609132212:replication-config:devint-holding-domain'
│ 	status code: 400, request id: aa3f06d9-33a3-4237-93e3-2b7b046f49db
│ 
│   with module.dms_replication_instance.aws_dms_replication_config.dms_full_load_serverless_replication[5],
│   on ../../../modules/dms/replication/dms_serverless_replication.tf line 136, in resource "aws_dms_replication_config" "dms_full_load_serverless_replication":
│  136: resource "aws_dms_replication_config" "dms_full_load_serverless_replication" {
```

### Terraform Configuration Files

```
# Create the DMS full load serverless replication
resource "aws_dms_replication_config" "dms_full_load_serverless_replication" {
  count = length(var.full_load_domain_list)

  # The maximum length of the replication name is 31. Use substr to make sure the name length is compliant.
  replication_config_identifier = replace(substr("${local.usage}-${var.full_load_domain_list[count.index].domain_name}",0,31), "/-$/", "")
  resource_identifier           = replace(substr("${local.usage}-${var.full_load_domain_list[count.index].domain_name}",0,31), "/-$/", "")
  replication_type              = "full-load"
  source_endpoint_arn           = var.source_endpoint_arn
  target_endpoint_arn           = aws_dms_s3_endpoint.full_load_target_endpoint[count.index].endpoint_arn
  table_mappings                = data.template_file.full_load_table_mapping[count.index].rendered
  replication_settings          = var.replication_settings

  compute_config {
    max_capacity_units           = var.full_load_max_capacity_units
    min_capacity_units           = var.full_load_min_capacity_units
    multi_az                     = var.multi_az
    availability_zone            = var.availability_zone
    preferred_maintenance_window = var.preferred_maintenance_window
    replication_subnet_group_id  = aws_dms_replication_subnet_group.dms_subnet_group.id
    vpc_security_group_ids       = [aws_security_group.replication_instance_sg.id]
  }

  tags = {
    Solution = var.context["solution"]
    Client   = var.context["client"]
    Use      = var.context["usage"]
    Domain   = var.full_load_domain_list[count.index].domain_name
    Type     = "full-load"
  }

  depends_on = [
    aws_iam_role_policy_attachment.dms-access-for-endpoint-AmazonDMSRedshiftS3Role,
    aws_iam_role_policy_attachment.dms-cloudwatch-logs-role-AmazonDMSCloudWatchLogsRole,
    aws_iam_role_policy_attachment.dms-vpc-role-AmazonDMSVPCManagementRole
  ]
}

#replication setting
{
    "Logging": {
        "EnableLogging": true,
        "LogComponents": [
            {
                "Id": "TRANSFORMATION",
                "Severity": "LOGGER_SEVERITY_DEFAULT"
            },
            {
                "Id": "SOURCE_UNLOAD",
                "Severity": "LOGGER_SEVERITY_DEFAULT"
            },
            {
                "Id": "IO",
                "Severity": "LOGGER_SEVERITY_DEFAULT"
            },
            {
                "Id": "TARGET_LOAD",
                "Severity": "LOGGER_SEVERITY_DEFAULT"
            },
            {
                "Id": "PERFORMANCE",
                "Severity": "LOGGER_SEVERITY_DEFAULT"
            },
            {
                "Id": "SOURCE_CAPTURE",
                "Severity": "LOGGER_SEVERITY_DEFAULT"
            },
            {
                "Id": "SORTER",
                "Severity": "LOGGER_SEVERITY_DEFAULT"
            },
            {
                "Id": "REST_SERVER",
                "Severity": "LOGGER_SEVERITY_DEFAULT"
            },
            {
                "Id": "VALIDATOR_EXT",
                "Severity": "LOGGER_SEVERITY_DEFAULT"
            },
            {
                "Id": "TARGET_APPLY",
                "Severity": "LOGGER_SEVERITY_DEFAULT"
            },
            {
                "Id": "TASK_MANAGER",
                "Severity": "LOGGER_SEVERITY_DEFAULT"
            },
            {
                "Id": "TABLES_MANAGER",
                "Severity": "LOGGER_SEVERITY_DEFAULT"
            },
            {
                "Id": "METADATA_MANAGER",
                "Severity": "LOGGER_SEVERITY_DEFAULT"
            },
            {
                "Id": "FILE_FACTORY",
                "Severity": "LOGGER_SEVERITY_DEFAULT"
            },
            {
                "Id": "COMMON",
                "Severity": "LOGGER_SEVERITY_DEFAULT"
            },
            {
                "Id": "ADDONS",
                "Severity": "LOGGER_SEVERITY_DEFAULT"
            },
            {
                "Id": "DATA_STRUCTURE",
                "Severity": "LOGGER_SEVERITY_DEFAULT"
            },
            {
                "Id": "COMMUNICATION",
                "Severity": "LOGGER_SEVERITY_DEFAULT"
            },
            {
                "Id": "FILE_TRANSFER",
                "Severity": "LOGGER_SEVERITY_DEFAULT"
            }
        ]
    }
}
```

### Steps to Reproduce

apply the configuration to create a dms serverless application
try to apply again and receive the error above

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by nam054**
### Description

DMS replication config would show non-zero value defaults were being removed from the plan. This PR creates a defaults map in `task_settings_json` to compare with what's being configured to make sure that if the settings are set to default, the diffs would be suppressed.

### Relations

Closes #35573

### Output from Acceptance Testing

```console
> make testacc TESTARGS='-run=TestAccDMSReplicationConfig_' PKG=dms
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/dms/... -v -count 1 -parallel 20  -run=TestAccDMSReplicationConfig_ -timeout 360m
=== RUN   TestAccDMSReplicationConfig_basic
=== PAUSE TestAccDMSReplicationConfig_basic
=== RUN   TestAccDMSReplicationConfig_noChangeOnDefault
=== PAUSE TestAccDMSReplicationConfig_noChangeOnDefault
=== RUN   TestAccDMSReplicationConfig_disappears
=== PAUSE TestAccDMSReplicationConfig_disappears
=== RUN   TestAccDMSReplicationConfig_tags
=== PAUSE TestAccDMSReplicationConfig_tags
=== RUN   TestAccDMSReplicationConfig_update
=== PAUSE TestAccDMSReplicationConfig_update
=== RUN   TestAccDMSReplicationConfig_startReplication
=== PAUSE TestAccDMSReplicationConfig_startReplication
=== CONT  TestAccDMSReplicationConfig_basic
=== CONT  TestAccDMSReplicationConfig_tags
=== CONT  TestAccDMSReplicationConfig_update
=== CONT  TestAccDMSReplicationConfig_disappears
=== CONT  TestAccDMSReplicationConfig_noChangeOnDefault
=== CONT  TestAccDMSReplicationConfig_startReplication
--- PASS: TestAccDMSReplicationConfig_basic (1500.92s)
--- PASS: TestAccDMSReplicationConfig_noChangeOnDefault (1503.27s)
--- PASS: TestAccDMSReplicationConfig_disappears (1529.48s)
--- PASS: TestAccDMSReplicationConfig_update (1563.68s)
--- PASS: TestAccDMSReplicationConfig_tags (1628.00s)
--- PASS: TestAccDMSReplicationConfig_startReplication (3272.23s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/dms        3276.416s

> make testacc TESTARGS='-run=TestAccDMSReplicationTask_' PKG=dms
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.21.8 test ./internal/service/dms/... -v -count 1 -parallel 20  -run=TestAccDMSReplicationTask_ -timeout 360m
=== RUN   TestAccDMSReplicationTask_basic
=== PAUSE TestAccDMSReplicationTask_basic
=== RUN   TestAccDMSReplicationTask_update
=== PAUSE TestAccDMSReplicationTask_update
=== RUN   TestAccDMSReplicationTask_cdcStartPosition
=== PAUSE TestAccDMSReplicationTask_cdcStartPosition
=== RUN   TestAccDMSReplicationTask_startReplicationTask
=== PAUSE TestAccDMSReplicationTask_startReplicationTask
=== RUN   TestAccDMSReplicationTask_s3ToRDS
=== PAUSE TestAccDMSReplicationTask_s3ToRDS
=== RUN   TestAccDMSReplicationTask_disappears
=== PAUSE TestAccDMSReplicationTask_disappears
=== RUN   TestAccDMSReplicationTask_cdcStartTime_rfc3339_date
=== PAUSE TestAccDMSReplicationTask_cdcStartTime_rfc3339_date
=== RUN   TestAccDMSReplicationTask_cdcStartTime_unix_timestamp
=== PAUSE TestAccDMSReplicationTask_cdcStartTime_unix_timestamp
=== RUN   TestAccDMSReplicationTask_move
=== PAUSE TestAccDMSReplicationTask_move
=== CONT  TestAccDMSReplicationTask_basic
=== CONT  TestAccDMSReplicationTask_disappears
=== CONT  TestAccDMSReplicationTask_startReplicationTask
=== CONT  TestAccDMSReplicationTask_cdcStartPosition
=== CONT  TestAccDMSReplicationTask_update
=== CONT  TestAccDMSReplicationTask_s3ToRDS
=== CONT  TestAccDMSReplicationTask_cdcStartTime_unix_timestamp
=== CONT  TestAccDMSReplicationTask_cdcStartTime_rfc3339_date
=== CONT  TestAccDMSReplicationTask_move
--- PASS: TestAccDMSReplicationTask_cdcStartPosition (928.24s)
--- PASS: TestAccDMSReplicationTask_cdcStartTime_unix_timestamp (928.53s)
--- PASS: TestAccDMSReplicationTask_disappears (947.10s)
--- PASS: TestAccDMSReplicationTask_basic (987.13s)
--- PASS: TestAccDMSReplicationTask_move (1235.57s)
--- PASS: TestAccDMSReplicationTask_cdcStartTime_rfc3339_date (1339.97s)
--- PASS: TestAccDMSReplicationTask_s3ToRDS (1566.27s)
--- PASS: TestAccDMSReplicationTask_update (1596.19s)
--- PASS: TestAccDMSReplicationTask_startReplicationTask (2057.24s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/dms        2061.873s
...
```

### CODE REVIEW

File: internal/service/dms/task_settings_json.go [hunk 1]
```diff
@@ -14,150 +18,198 @@ import (
...
+			"HandleSourceTableTruncated": true,
+			"HandleSourceTableAltered":   true,
+		},
+	}
 
-	if err := json.Unmarshal([]byte(apiObject), &taskSettings); err != nil {
+	var jsonMap map[string]interface{}
+
+	if err := json.Unmarshal([]byte(apiObject), &jsonMap); err != nil {
+		log.Printf("[WARN] failed to unmarshal task settings JSON: %v", err)
```
Comment (johnsonaj) [inline internal/service/dms/task_settings_json.go:206]: remove logging

File: internal/service/dms/task_settings_json.go [hunk 2]
```diff
@@ -14,150 +18,198 @@ import (
...
 		return apiObject
 	}
 
-	if b, err := json.Marshal(&taskSettings); err != nil {
+	jsonMap = checkdefaultvalues(defaultValues, jsonMap)
+	if b, err := json.Marshal(&jsonMap); err != nil {
+		log.Printf("[WARN] failed to marshal task settings JSON: %v", err)
```
Comment (johnsonaj) [inline internal/service/dms/task_settings_json.go:212]: remove logging

File: internal/service/dms/task_settings_json.go (hunk 1 above)
Comment (johnsonaj) [reply internal/service/dms/task_settings_json.go:206]: or change to DEBUG

**Review by johnsonaj — APPROVED** [review]
LGTM 🚀 

```console
make testacc TESTARGS='-run=TestAccDMSReplicationTask_\|TestAccDMSReplicationConfig_' PKG=dms | filter-test                                                                                               141 ↵
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.21.8 test ./internal/service/dms/... -v -count 1 -parallel 20  -run=TestAccDMSReplicationTask_\|TestAccDMSReplicationConfig_ -timeout 360m
--- PASS: TestAccDMSReplicationTask_cdcStartTime_rfc3339_date (952.98s)
--- PASS: TestAccDMSReplicationTask_disappears (961.52s)
--- PASS: TestAccDMSReplicationTask_cdcStartTime_unix_timestamp (973.39s)
--- PASS: TestAccDMSReplicationTask_cdcStartPosition (996.06s)
--- PASS: TestAccDMSReplicationTask_basic (1020.76s)
--- PASS: TestAccDMSReplicationConfig_tags (1364.17s)
--- PASS: TestAccDMSReplicationConfig_update (1404.11s)
--- PASS: TestAccDMSReplicationConfig_basic (1505.28s)
--- PASS: TestAccDMSReplicationConfig_noChangeOnDefault (1525.73s)
--- PASS: TestAccDMSReplicationConfig_disappears (1584.93s)
--- PASS: TestAccDMSReplicationTask_update (1596.88s)
--- PASS: TestAccDMSReplicationTask_s3ToRDS (1713.89s)
--- PASS: TestAccDMSReplicationTask_move (1787.15s)
--- PASS: TestAccDMSReplicationTask_startReplicationTask (1854.96s)
--- PASS: TestAccDMSReplicationConfig_startReplication (3131.88s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/dms	3136.463s
```

**Comment by johnsonaj** [comment]
@nam054 needs CHANGELOG entry
