### PR TITLE
internal/verify: handle policy parsing errors of state content 

### LINKED ISSUE #28609: [Bug]: aws_secretsmanager_secret saves bad resource policy into state
### Terraform Core Version

1.3.4

### AWS Provider Version

4.48.0

### Affected Resource(s)

aws_secretsmanager_secret

### Expected Behavior

When the apply fails with `MalformedPolicyDocumentException: This resource policy contains a syntax error`, the state should not be saved

### Actual Behavior

The state is saved even after `MalformedPolicyDocumentException: This resource policy contains a syntax error`

### Relevant Error/Panic Output Snippet

```shell
encountered: parsing policy 1: parsing statement 1: 1 error(s) decoding:

* '[3]' expected a map, got 'slice'
```

### Terraform Configuration Files

``` hcl
locals {
  policy = {
    Version = "2012-10-17"
    Statement = concat([
        {
          Effect = "Allow"
          Action = [
            "secretsmanager:Delete*",
            "secretsmanager:PutResourcePolicy",
            "secretsmanager:ReplicateSecretToRegions",
            "secretsmanager:RemoveRegionsFromReplication",
            "secretsmanager:StopReplicationToReplica",
            "secretsmanager:TagResource",
            "secretsmanager:UntagResource",
          ]
          Principal = "arn:aws:iam::<AWS_ACCOUNT_ID>:root"
          Resource  = "*"
          }
        },
        {
          Effect = "Allow"
          Action = [
            "secretsmanager:DescribeSecret",
            "secretsmanager:GetResourcePolicy",
            "secretsmanager:RestoreSecret"
          ]
          Principal = {
            AWS = "arn:aws:iam::<AWS_ACCOUNT_ID>:root"
          }
          Resource = "*"
        },
        [
          {
            Effect = "Allow"
            Action = "secretsmanager:GetSecretValue"
            Principal = {
              AWS = "arn:aws:iam::<AWS_ACCOUNT_ID>:root"
            }
            Resource = "*"
          }
        ]
    ])
  }
}

resource "aws_secretsmanager_secret" "secret" {
  name        = "foo"
  description = "bar"
  policy      = jsonencode(local.policy)
}
```

### Steps to Reproduce

1. replace `<AWS_ACCOUNT_ID>` with an actual account id
2. run the code to create the secret
3. you may need to first create a valid secret then apply a wonky resource policy to it

Please note that the example config file is a stripped down and modified version of the actual policy and so the `relevent error` may not look exactly like what you see there.

### Debug Output

none

### Panic Output

none

### Important Factoids

_No response_

### References

https://github.com/hashicorp/terraform-provider-aws/issues/22895

That closed issue i think is very closely related to this

### Would you like to implement a fix?

None

### LINKED ISSUE #29185: [Bug]: Terraform saves invalid boundary policy in its state
### Terraform Core Version

0.37.0

### AWS Provider Version

4.48

### Affected Resource(s)

arn:aws:iam:::policy/platform/pipeline_boundary

### Expected Behavior

The permissions boundary should not have been updated if the policy was invalid. 

 

### Actual Behavior

Tf saved an invalid boundary policy in its state, then couldn't change it, because it did a validation. This was fixed by removing it from the state, and from AWS, which fixed this. However TF does not do a proper state refresh and didn't reattach the boundary policies. 
Changing the state to have an empty boundary policy fixed this

### Relevant Error/Panic Output Snippet

```shell
Error: while setting policy (), encountered: while checking equivalency of existing policy , encountered: parsing policy 1: parsing statement 1: 1 error(s) decoding:
│ 
│ * '[5].Condition' expected a map, got 'slice'
```

### Terraform Configuration Files

```terraform
arn"arn:aws:iam::286059767448:policy/platform/pipeline_boundary"
description""
id"dvb-dvb-testing-sbx""arn:aws:iam::286059767448:policy/platform/pipeline_boundary"
name"pipeline_boundary"
name_prefixnull
path"/platform/"
policy"{\"Statement\":[{\"Action\":\"*\",\"Effect\":\"Allow\",\"Resource\":\"*\",\"Sid\":\"AllowAdminAccess\"},{\"Action\":[\"account:*\",\"savingsplans:*\",\"tax:*\",\"invoicing:*\"],\"Effect\":\"Deny\",\"Resource\":\"*\",\"Sid\":\"DenyAccessToCostAndBilling\"},{\"Action\":[\"iam:DeletePolicy\",\"iam:DeletePolicyVersion\",\"iam:CreatePolicyVersion\",\"iam:SetDefaultPolicyVersion\"],\"Effect\":\"Deny\",\"Resource\":[\"arn:aws:iam::286059767448:policy/platform/workload_boundary\",\"arn:aws:iam::286059767448:policy/platform/pipeline_boundary\"],\"Sid\":\"DenyPermBoundaryIAMPolicyAlteration\"},{\"Action\":[\"iam:DeleteUserPermissionsBoundary\",\"iam:DeleteRolePermissionsBoundary\"],\"Condition\":{\"StringEquals\":{\"iam:PermissionsBoundary\":\"arn:aws:iam::286059767448:policy/platform/workload_boundary\"}},\"Effect\":\"Deny\",\"Resource\":[\"arn:aws:iam::286059767448:user/*\",\"arn:aws:iam::286059767448:role/*\"],\"Sid\":\"DenyRemovalOfPermBoundaryFromAnyUserOrRole\"},{\"Action\":[\"iam:PutUserPermissionsBoundary\",\"iam:PutRolePermissionsBoundary\"],\"Condition\":{\"StringNotEquals\":{\"iam:PermissionsBoundary\":\"arn:aws:iam::286059767448:policy/platform/workload_boundary\"}},\"Effect\":\"Deny\",\"Resource\":[\"arn:aws:iam::286059767448:user/*\",\"arn:aws:iam::286059767448:role/*\"],\"Sid\":\"DenyAccessIfRequiredPermBoundaryIsNotBeingApplied\"},{\"Action\":[\"iam:CreateUser\",\"iam:CreateRole\",\"iam:UpdateUser\",\"iam:UpdateRole\",\"iam:DeleteUserPolicy\",\"iam:AttachUserPolicy\",\"iam:DetachUserPolicy\"],\"Condition\":[{\"ArnNotLike\":{\"aws:PrincipalArn\":\"arn:aws:iam::867002137709:role/platform/TFEPipelineDomainmanagementDefaultPrdRole\"},\"StringNotEquals\":{\"iam:PermissionsBoundary\":\"arn:aws:iam::286059767448:policy/platform/workload_boundary\"}}],\"Effect\":\"Deny\",\"Resource\":[\"arn:aws:iam::286059767448:user/*\",\"arn:aws:iam::286059767448:role/*\"],\"Sid\":\"DenyUserAndRoleCreationWithOutPermBoundary\"},{\"Action\":[\"secretsmanager:*\"],\"Effect\":\"Deny\",\"Resource\":[\"arn:aws:secretsmanager:*:286059767448:secret/platform/*\"],\"Sid\":\"DenyUseOfEnablementPlatformSecretManagerNamespace\"},{\"Action\":[\"kms:*\"],\"Condition\":{\"ForAnyValue:StringLike\":{\"kms:ResourceAliases\":\"alias/platform/*\"}},\"Effect\":\"Deny\",\"Resource\":\"*\",\"Sid\":\"DenyUseOfEnablementPlatformKMSNamespace\"}],\"Version\":\"2012-10-17\"}"
policy_id"ANPAUFGT5U2MJI6NDKHPA"
tags{}
tags_all{}
```

### Steps to Reproduce

1. Create valid JSON permissions boundary but invalid policy
2. Update the permissions boundary attached to the IAM role
3. On running tf apply

 "Error: updating IAM policy arn:aws:iam::286059767448:policy/platform/pipeline_boundary: MalformedPolicyDocument: Syntax errors in policy."

On running again : 
 Error: while setting policy (), encountered: while checking equivalency of existing policy 
│ * '[5].Condition' expected a map, got 'slice'

4. Applied Terraform refresh , did not work. Reattaching the boundaries did not work.
5. Finally fixed it by changing the state to have an empty boundary policy. 

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

None

### LINKED ISSUE #39202: [Bug]: Creating a duplicate ECR repository policy causes irrecoverable validation error
### Terraform Core Version

1.3.3, 1.7.5

### AWS Provider Version

5.66.0

### Affected Resource(s)

* `aws_ecr_repository_policy`

### Expected Behavior

If you create two `aws_ecr_repository_policy` objects for the same policy this is user error, but the expected result is that the only thing that should get broken is your repository policy getting set to the wrong value and/or your terraform plan failing until you fix the code.

### Actual Behavior

If you do things in a certain order, it's possible to get the terraform state into a broken place where absolutely no terraform operations can be run without manually running `terraform state rm` commands.

### Relevant Error/Panic Output Snippet

```shell
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: parsing policy 1: parsing statement 1: 1 error(s) decoding:
│
│ * '[0].Condition' expected a map, got 'slice'
│
│   with aws_ecr_repository_policy.conflicting_b,
│   on infra.tf line 32, in resource "aws_ecr_repository_policy" "conflicting_b":
│   32: resource "aws_ecr_repository_policy" "conflicting_b" {
```

### Terraform Configuration Files

Start by applying this:

```terraform
resource "aws_ecr_repository" "example" {
  name = "rrosborough-cursed-test"
  tags = {
    team           = "infra"
    safe-to-delete = "true"
    who-to-blame   = "rrosborough"
  }
}

data "aws_iam_policy_document" "example" {
  statement {
    sid    = "allow-pull"
    effect = "Allow"

    principals {
      type        = "AWS"
      identifiers = ["763104351884"]
    }

    actions = [
      "ecr:BatchGetImage",
      "ecr:GetDownloadUrlForLayer",
    ]
  }
}

resource "aws_ecr_repository_policy" "conflicting_a" {
  repository = aws_ecr_repository.example.name
  policy     = data.aws_iam_policy_document.example.json
}
```

Now add the following resource and apply:

```terraform
resource "aws_ecr_repository_policy" "conflicting_b" {
  repository = aws_ecr_repository.example.name

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "LambdaECRImageRetrievalPolicy"
        Effect = "Allow"
        Principal = {
          Service = "lambda.amazonaws.com"
        }
        Action = [
          "ecr:BatchGetImage",
          "ecr:GetDownloadUrlForLayer",
          "ecr:BatchGetImage",
          "ecr:DeleteRepositoryPolicy",
          "ecr:GetDownloadUrlForLayer",
          "ecr:GetRepositoryPolicy",
          "ecr:SetRepositoryPolicy"
        ]
        Condition = {
          StringLike = {
            "aws:sourceArn" = "arn:aws:lambda:us-east-1:763104351884:function:*"
          }
        }
      }
    ]
  })
}
```

Finally edit the added resource like so and try applying:

```terraform
resource "aws_ecr_repository_policy" "conflicting_b" {
  repository = aws_ecr_repository.example.name

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = concat(
      data.aws_iam_policy_document.example.statement,
      [
        {
          Sid    = "LambdaECRImageRetrievalPolicy"
          Effect = "Allow"
          Principal = {
            Service = "lambda.amazonaws.com"
          }
          Action = [
            "ecr:BatchGetImage",
            "ecr:DeleteRepositoryPolicy",
            "ecr:GetDownloadUrlForLayer",
            "ecr:GetRepositoryPolicy",
            "ecr:SetRepositoryPolicy"
          ]
          Condition = {
            StringLike = {
              "aws:sourceArn" = "arn:aws:lambda:us-east-1:763104351884:function:*"
            }
          }
        }
      ]
    )
  })
}
```

### Steps to Reproduce

Do the steps above. Applying the first code block should succeed. Applying the second code block should also succeed although now there will be a permanent diff because there are two different TF references to the same repository policy, so the one that applied from the second code block will have overwritten the one from the first code block. Applying the third code block hangs for 2 minutes and then aborts with:

```
│ Error: putting ECR Repository Policy (rrosborough-cursed-test): operation error ECR: SetRepositoryPolicy, https response error StatusCode: 400, RequestID: e0d3042f-0892-4e1e-924b-802de641f01c, InvalidParameterException: Invalid parameter at 'PolicyText' failed to satisfy constraint: 'Invalid repository policy provided'
│
│   with aws_ecr_repository_policy.conflicting_b,
│   on infra.tf line 32, in resource "aws_ecr_repository_policy" "conflicting_b":
│   32: resource "aws_ecr_repository_policy" "conflicting_b" {
```

That is expected because the new repository policy is invalid (it's constructed in a way that gives an invalid value for the `Condition` key). But, what's not expected is that now ALL future Terraform commands fail with this:

```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: parsing policy 1: parsing statement 1: 1 error(s) decoding:
│
│ * '[0].Condition' expected a map, got 'slice'
│
│   with aws_ecr_repository_policy.conflicting_b,
│   on infra.tf line 32, in resource "aws_ecr_repository_policy" "conflicting_b":
│   32: resource "aws_ecr_repository_policy" "conflicting_b" {
```

You can remove the broken resources from Terraform source code but it does not help, since somehow Terraform has put an object into the Terraform state that was not applied to AWS and does not pass the provider's own validation checks. The only way to get out of this state is `terraform state rm`.

(It might _look_ like removing the resource on line 32 would resolve the error, since the error message points to it explicitly... humorously enough, removing the resource just make Terraform print the same error except now with no line of code or resource pointer.)

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

The code in this issue is obviously incorrect and should be rejected, everyone on our end is on the same page about that, the issue though is that the provider gets into a permanently broken state where administrative intervention is needed, instead of just failing the apply like it should (or producing an incorrect result).

### References

_No response_

### Would you like to implement a fix?

None

### LINKED ISSUE #39833: [Bug]: `r/aws_iam_policy`: Malformed `Condition` prevents subsequent modifications
### Terraform Core Version

1.9.5

### AWS Provider Version

5.72.1

### Affected Resource(s)

- `aws_iam_policy`

### Expected Behavior

When malformed policy content is configured, the first apply should fail. Reverting of fixing the content should result in a successful apply.

### Actual Behavior

When malformed policy content is configured, the first apply fails (expected). 

```
│ Error: updating IAM Policy (arn:aws:iam::727561393803:policy/policy_zd163007): operation error IAM: CreatePolicyVersion, https response error StatusCode: 400, RequestID: 273b745a-e51
c-49b7-bd12-1f08ee676a58, MalformedPolicyDocument: Syntax errors in policy
```

Then, all subsequent attempts to resolve the syntax error fail because the invalid JSON has been stored in state and cannot be parsed when checking equivalence with the remote policy content.

```
│ Error: while setting policy (), encountered: while checking equivalency of existing policy ({"Statement":[{"Action":["ec2:Describe*"],"Condition":{"ForAnyValue:StringLike":["aws:Mult
iFactorAuthAge"]},"Effect":"Allow","Resource":"*"}],"Version":"2012-10-17"}) and new policy ({"Statement":[{"Action":["ec2:Describe*"],"Effect":"Allow","Resource":"*"}],"Version":"2012
-10-17"}), encountered: parsing policy 1: parsing statement 1: 1 error(s) decoding:
│
│ * '[0].Condition[ForAnyValue:StringLike]' expected a map, got 'slice'
```

### Relevant Error/Panic Output Snippet

_No response_

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

# Configure the AWS Provider
provider "aws" {}

resource "aws_iam_policy" "policy" {
  name        = "policy_zd163007"
  path        = "/"
  description = "My test policy"

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = [
          "ec2:Describe*",
        ]
        # After successfully creating the policy, uncomment this malformed
        # condition and apply again, causing the unrecoverable state.
        # "Condition" : {
        #   "ForAnyValue:StringLike" : ["aws:MultiFactorAuthAge"]
        # }

        Effect   = "Allow"
        Resource = "*"
      },
    ]
  })
}
```

### Steps to Reproduce

1. Apply the configuration above.
2. Uncomment the malformed `Condition`, apply. This should fail as expected.
3. Comment out the problematic `Condition` and run `plan` or `apply`. Observe failure while setting the `policy` argument.

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

Relates #39202

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by jar-b**
### Description

Plugin SDK V2 based resources can set malformed policy content in state despite a failed update. In these cases, parsing the old content will fail (it is still malformed). Surfacing parsing errors during read operations causes a persistent plan-time validation error, so this changes the behavior to return the "new" content read directly from the remote resource instead.

This fix is applied as far down in the provider codebase as possible, directly after calling the `PoliciesAreEquivalent` function from `github.com/hashicorp/awspolicyequivalence`. The `SecondJSONUnlessEquivalent` function is called across a variety of services which have arguments that expect IAM policy JSON, as well by other upstream functions within `internal/verify` which apply additional normalization on top of the output. As such, this fix may apply to more resources than are explicitly included in the CHANGELOG entry. For now I've limited entries only to those with open bug reports (that I could easily find).

This change also includes a test case reproducing this previously broken workflow for an IAM policy resource. Before the changes to `internal/verify`:

```console
make testacc PKG=iam TESTS=TestAccIAMPolicy_malformedCondition
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.2 test ./internal/service/iam/... -v -count 1 -parallel 20 -run='TestAccIAMPolicy_malformedCondition'  -timeout 360m
2024/10/22 14:34:52 Initializing Terraform AWS Provider...

    policy_test.go:366: Step 3/3 error: Error running pre-apply plan: exit status 1

        Error: while setting policy (), encountered: while checking equivalency of existing policy ({"Statement":[{"Action":["s3:ListBucket"],"Condition":{"StringLike":["demo-prefix/"]},"Effect":"Allow","Resource":"*"}],"Version":"2012-10-17"}) and new policy ({"Statement":[{"Action":["s3:ListBucket"],"Effect":"Allow","Resource":"*"}],"Version":"2012-10-17"}), encountered: parsing policy 1: parsing statement 1: 1 error(s) decoding:

        * '[0].Condition[StringLike]' expected a map, got 'slice'

          with aws_iam_policy.test,
          on terraform_plugin_test.tf line 12, in resource "aws_iam_policy" "test":
          12: resource "aws_iam_policy" "test" {

--- FAIL: TestAccIAMPolicy_malformedCondition (14.38s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/iam        20.852s
```

After:

```console
% make testacc PKG=iam TESTS=TestAccIAMPolicy_malformedCondition
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.2 test ./internal/service/iam/... -v -count 1 -parallel 20 -run='TestAccIAMPolicy_malformedCondition'  -timeout 360m
2024/10/22 14:33:06 Initializing Terraform AWS Provider...

--- PASS: TestAccIAMPolicy_malformedCondition (21.43s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/iam        27.884s
```

### Relations

Closes #39833
Closes #39202
Closes #29185
Closes #28609

### References

- https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition.html

### Output from Acceptance Testing

```console
% make testacc PKG=iam TESTS=TestAccIAMPolicy_
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.2 test ./internal/service/iam/... -v -count 1 -parallel 20 -run='TestAccIAMPolicy_'  -timeout 360m
2024/10/22 14:47:49 Initializing Terraform AWS Provider...

--- PASS: TestAccIAMPolicy_policyDuplicateKeys (3.93s)
=== CONT  TestAccIAMPolicy_whitespace
--- PASS: TestAccIAMPolicy_disappears (33.95s)
=== CONT  TestAccIAMPolicy_description
--- PASS: TestAccIAMPolicy_path (39.26s)
=== CONT  TestAccIAMPolicy_basic
--- PASS: TestAccIAMPolicy_namePrefix (40.36s)
=== CONT  TestAccIAMPolicy_tags_DefaultTags_emptyProviderOnlyTag
--- PASS: TestAccIAMPolicy_tags_DefaultTags_nullOverlappingResourceTag (47.05s)
=== CONT  TestAccIAMPolicy_tags_ComputedTag_OnUpdate_Replace
--- PASS: TestAccIAMPolicy_tags_DefaultTags_nullNonOverlappingResourceTag (47.31s)
=== CONT  TestAccIAMPolicy_tags_IgnoreTags_Overlap_DefaultTag
--- PASS: TestAccIAMPolicy_tags_DefaultTags_emptyResourceTag (48.16s)
=== CONT  TestAccIAMPolicy_tags_DefaultTags_updateToProviderOnly
--- PASS: TestAccIAMPolicy_tags_ComputedTag_OnCreate (48.91s)
=== CONT  TestAccIAMPolicy_tags_DefaultTags_updateToResourceOnly
--- PASS: TestAccIAMPolicy_tags_EmptyMap (60.04s)
=== CONT  TestAccIAMPolicy_tags_null
--- PASS: TestAccIAMPolicy_malformedCondition (66.86s)
=== CONT  TestAccIAMPolicy_tags_ComputedTag_OnUpdate_Add
--- PASS: TestAccIAMPolicy_policy (69.03s)
=== CONT  TestAccIAMPolicy_tags_DefaultTags_overlapping
--- PASS: TestAccIAMPolicy_tags_EmptyTag_OnUpdate_Replace (71.84s)
--- PASS: TestAccIAMPolicy_description (40.11s)
--- PASS: TestAccIAMPolicy_tags_AddOnUpdate (76.91s)
--- PASS: TestAccIAMPolicy_basic (37.69s)
--- PASS: TestAccIAMPolicy_whitespace (76.92s)
--- PASS: TestAccIAMPolicy_tags_DefaultTags_emptyProviderOnlyTag (45.17s)
--- PASS: TestAccIAMPolicy_tags_EmptyTag_OnCreate (85.62s)
--- PASS: TestAccIAMPolicy_tags_IgnoreTags_Overlap_ResourceTag (100.60s)
--- PASS: TestAccIAMPolicy_tags_null (42.53s)
--- PASS: TestAccIAMPolicy_tags_EmptyTag_OnUpdate_Add (103.00s)
--- PASS: TestAccIAMPolicy_tags_DefaultTags_updateToProviderOnly (56.55s)
--- PASS: TestAccIAMPolicy_tags_DefaultTags_updateToResourceOnly (56.36s)
--- PASS: TestAccIAMPolicy_tags_ComputedTag_OnUpdate_Replace (58.95s)
--- PASS: TestAccIAMPolicy_tags_DefaultTags_nonOverlapping (107.66s)
--- PASS: TestAccIAMPolicy_tags_IgnoreTags_Overlap_DefaultTag (64.80s)
--- PASS: TestAccIAMPolicy_tags_ComputedTag_OnUpdate_Add (48.12s)
--- PASS: TestAccIAMPolicy_tags (119.83s)
--- PASS: TestAccIAMPolicy_tags_DefaultTags_providerOnly (120.47s)
--- PASS: TestAccIAMPolicy_tags_DefaultTags_overlapping (59.19s)
--- PASS: TestAccIAMPolicy_diffs (133.46s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/iam        139.894s
```

### CODE REVIEW

File: internal/verify/json.go [hunk 1]
```diff
@@ -144,6 +149,17 @@ func SecondJSONUnlessEquivalent(old, new string) (string, error) {
...
 
 	if err != nil {
+		// Plugin SDK V2 based resources can set malformed policy content in state
+		// despite a failed update. In these cases, parsing the "old" content
+		// will fail. Surfacing this error during read operations causes a
+		// persistent plan-time validation error, so return the "new" content
+		// read directly from the remote resource instead.
+		//
+		// Ref: https://github.com/hashicorp/terraform-provider-aws/issues/39833
+		if strings.Contains(err.Error(), "parsing policy 1") {
```
Comment (ewbankkit) [inline internal/verify/json.go:159]: or use `errs.Contains`

Comment (jar-b) [reply internal/verify/json.go]: Updated.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccIAMPolicy_' PKG=iam ACCTEST_PARALLELISM=4
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.2 test ./internal/service/iam/... -v -count 1 -parallel 4  -run=TestAccIAMPolicy_ -timeout 360m
2024/10/23 08:57:44 Initializing Terraform AWS Provider...
=== RUN   TestAccIAMPolicy_tags
=== PAUSE TestAccIAMPolicy_tags
=== RUN   TestAccIAMPolicy_tags_null
=== PAUSE TestAccIAMPolicy_tags_null
=== RUN   TestAccIAMPolicy_tags_EmptyMap
=== PAUSE TestAccIAMPolicy_tags_EmptyMap
=== RUN   TestAccIAMPolicy_tags_AddOnUpdate
=== PAUSE TestAccIAMPolicy_tags_AddOnUpdate
=== RUN   TestAccIAMPolicy_tags_EmptyTag_OnCreate
=== PAUSE TestAccIAMPolicy_tags_EmptyTag_OnCreate
=== RUN   TestAccIAMPolicy_tags_EmptyTag_OnUpdate_Add
=== PAUSE TestAccIAMPolicy_tags_EmptyTag_OnUpdate_Add
=== RUN   TestAccIAMPolicy_tags_EmptyTag_OnUpdate_Replace
=== PAUSE TestAccIAMPolicy_tags_EmptyTag_OnUpdate_Replace
=== RUN   TestAccIAMPolicy_tags_DefaultTags_providerOnly
=== PAUSE TestAccIAMPolicy_tags_DefaultTags_providerOnly
=== RUN   TestAccIAMPolicy_tags_DefaultTags_nonOverlapping
=== PAUSE TestAccIAMPolicy_tags_DefaultTags_nonOverlapping
=== RUN   TestAccIAMPolicy_tags_DefaultTags_overlapping
=== PAUSE TestAccIAMPolicy_tags_DefaultTags_overlapping
=== RUN   TestAccIAMPolicy_tags_DefaultTags_updateToProviderOnly
=== PAUSE TestAccIAMPolicy_tags_DefaultTags_updateToProviderOnly
=== RUN   TestAccIAMPolicy_tags_DefaultTags_updateToResourceOnly
=== PAUSE TestAccIAMPolicy_tags_DefaultTags_updateToResourceOnly
=== RUN   TestAccIAMPolicy_tags_DefaultTags_emptyResourceTag
=== PAUSE TestAccIAMPolicy_tags_DefaultTags_emptyResourceTag
=== RUN   TestAccIAMPolicy_tags_DefaultTags_emptyProviderOnlyTag
=== PAUSE TestAccIAMPolicy_tags_DefaultTags_emptyProviderOnlyTag
=== RUN   TestAccIAMPolicy_tags_DefaultTags_nullOverlappingResourceTag
=== PAUSE TestAccIAMPolicy_tags_DefaultTags_nullOverlappingResourceTag
=== RUN   TestAccIAMPolicy_tags_DefaultTags_nullNonOverlappingResourceTag
=== PAUSE TestAccIAMPolicy_tags_DefaultTags_nullNonOverlappingResourceTag
=== RUN   TestAccIAMPolicy_tags_ComputedTag_OnCreate
=== PAUSE TestAccIAMPolicy_tags_ComputedTag_OnCreate
=== RUN   TestAccIAMPolicy_tags_ComputedTag_OnUpdate_Add
=== PAUSE TestAccIAMPolicy_tags_ComputedTag_OnUpdate_Add
=== RUN   TestAccIAMPolicy_tags_ComputedTag_OnUpdate_Replace
=== PAUSE TestAccIAMPolicy_tags_ComputedTag_OnUpdate_Replace
=== RUN   TestAccIAMPolicy_tags_IgnoreTags_Overlap_DefaultTag
=== PAUSE TestAccIAMPolicy_tags_IgnoreTags_Overlap_DefaultTag
=== RUN   TestAccIAMPolicy_tags_IgnoreTags_Overlap_ResourceTag
=== PAUSE TestAccIAMPolicy_tags_IgnoreTags_Overlap_ResourceTag
=== RUN   TestAccIAMPolicy_basic
=== PAUSE TestAccIAMPolicy_basic
=== RUN   TestAccIAMPolicy_description
=== PAUSE TestAccIAMPolicy_description
=== RUN   TestAccIAMPolicy_whitespace
=== PAUSE TestAccIAMPolicy_whitespace
=== RUN   TestAccIAMPolicy_disappears
=== PAUSE TestAccIAMPolicy_disappears
=== RUN   TestAccIAMPolicy_namePrefix
=== PAUSE TestAccIAMPolicy_namePrefix
=== RUN   TestAccIAMPolicy_path
=== PAUSE TestAccIAMPolicy_path
=== RUN   TestAccIAMPolicy_policy
=== PAUSE TestAccIAMPolicy_policy
=== RUN   TestAccIAMPolicy_diffs
=== PAUSE TestAccIAMPolicy_diffs
=== RUN   TestAccIAMPolicy_policyDuplicateKeys
=== PAUSE TestAccIAMPolicy_policyDuplicateKeys
=== RUN   TestAccIAMPolicy_malformedCondition
=== PAUSE TestAccIAMPolicy_malformedCondition
=== CONT  TestAccIAMPolicy_tags
=== CONT  TestAccIAMPolicy_tags_ComputedTag_OnCreate
=== CONT  TestAccIAMPolicy_tags_DefaultTags_nonOverlapping
=== CONT  TestAccIAMPolicy_tags_DefaultTags_nullNonOverlappingResourceTag
--- PASS: TestAccIAMPolicy_tags_DefaultTags_nullNonOverlappingResourceTag (13.91s)
=== CONT  TestAccIAMPolicy_tags_DefaultTags_nullOverlappingResourceTag
--- PASS: TestAccIAMPolicy_tags_ComputedTag_OnCreate (17.23s)
=== CONT  TestAccIAMPolicy_tags_DefaultTags_updateToProviderOnly
--- PASS: TestAccIAMPolicy_tags_DefaultTags_nullOverlappingResourceTag (13.66s)
=== CONT  TestAccIAMPolicy_tags_DefaultTags_overlapping
--- PASS: TestAccIAMPolicy_tags_DefaultTags_nonOverlapping (36.11s)
=== CONT  TestAccIAMPolicy_disappears
--- PASS: TestAccIAMPolicy_tags_DefaultTags_updateToProviderOnly (23.13s)
=== CONT  TestAccIAMPolicy_malformedCondition
--- PASS: TestAccIAMPolicy_disappears (10.48s)
=== CONT  TestAccIAMPolicy_policyDuplicateKeys
--- PASS: TestAccIAMPolicy_policyDuplicateKeys (0.79s)
=== CONT  TestAccIAMPolicy_diffs
--- PASS: TestAccIAMPolicy_tags (47.51s)
=== CONT  TestAccIAMPolicy_policy
--- PASS: TestAccIAMPolicy_malformedCondition (18.85s)
=== CONT  TestAccIAMPolicy_path
--- PASS: TestAccIAMPolicy_tags_DefaultTags_overlapping (36.51s)
=== CONT  TestAccIAMPolicy_namePrefix
--- PASS: TestAccIAMPolicy_policy (18.83s)
=== CONT  TestAccIAMPolicy_tags_IgnoreTags_Overlap_ResourceTag
--- PASS: TestAccIAMPolicy_path (11.48s)
=== CONT  TestAccIAMPolicy_whitespace
--- PASS: TestAccIAMPolicy_namePrefix (11.41s)
=== CONT  TestAccIAMPolicy_description
--- PASS: TestAccIAMPolicy_description (11.36s)
=== CONT  TestAccIAMPolicy_basic
--- PASS: TestAccIAMPolicy_whitespace (21.98s)
=== CONT  TestAccIAMPolicy_tags_EmptyTag_OnCreate
--- PASS: TestAccIAMPolicy_tags_IgnoreTags_Overlap_ResourceTag (30.68s)
=== CONT  TestAccIAMPolicy_tags_DefaultTags_providerOnly
--- PASS: TestAccIAMPolicy_basic (11.26s)
=== CONT  TestAccIAMPolicy_tags_EmptyTag_OnUpdate_Replace
--- PASS: TestAccIAMPolicy_diffs (59.54s)
=== CONT  TestAccIAMPolicy_tags_EmptyTag_OnUpdate_Add
--- PASS: TestAccIAMPolicy_tags_EmptyTag_OnCreate (23.62s)
=== CONT  TestAccIAMPolicy_tags_DefaultTags_emptyProviderOnlyTag
--- PASS: TestAccIAMPolicy_tags_EmptyTag_OnUpdate_Replace (21.38s)
=== CONT  TestAccIAMPolicy_tags_EmptyMap
--- PASS: TestAccIAMPolicy_tags_DefaultTags_emptyProviderOnlyTag (13.14s)
=== CONT  TestAccIAMPolicy_tags_AddOnUpdate
--- PASS: TestAccIAMPolicy_tags_EmptyMap (16.32s)
=== CONT  TestAccIAMPolicy_tags_DefaultTags_emptyResourceTag
--- PASS: TestAccIAMPolicy_tags_EmptyTag_OnUpdate_Add (31.50s)
=== CONT  TestAccIAMPolicy_tags_ComputedTag_OnUpdate_Replace
--- PASS: TestAccIAMPolicy_tags_DefaultTags_providerOnly (45.31s)
=== CONT  TestAccIAMPolicy_tags_IgnoreTags_Overlap_DefaultTag
--- PASS: TestAccIAMPolicy_tags_DefaultTags_emptyResourceTag (13.24s)
=== CONT  TestAccIAMPolicy_tags_ComputedTag_OnUpdate_Add
--- PASS: TestAccIAMPolicy_tags_AddOnUpdate (21.46s)
=== CONT  TestAccIAMPolicy_tags_null
--- PASS: TestAccIAMPolicy_tags_ComputedTag_OnUpdate_Replace (25.16s)
=== CONT  TestAccIAMPolicy_tags_DefaultTags_updateToResourceOnly
--- PASS: TestAccIAMPolicy_tags_null (16.57s)
--- PASS: TestAccIAMPolicy_tags_IgnoreTags_Overlap_DefaultTag (26.54s)
--- PASS: TestAccIAMPolicy_tags_ComputedTag_OnUpdate_Add (24.67s)
--- PASS: TestAccIAMPolicy_tags_DefaultTags_updateToResourceOnly (20.00s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/iam	188.909s
```
