### PR TITLE
tests/apprunner_custom_domain_association: use ENV var for domain and use a valid ECR public image to ensure service creation succeeds 

### LINKED ISSUE #20349: resource/aws_apprunner_custom_domain_association: Acceptance tests fail
The acceptance tests for `aws_apprunner_custom_domain_association` fail with the error

> Error: error waiting for App Runner Custom Domain Association (7lewf1kx.test,arn:aws:apprunner:us-west-2:*******:service/tf-acc-test-8028814703980260801/bfce4c361aa94b90ae8b659b3b2bc4bb) creation: unexpected state 'create_failed', wanted target 'pending_certificate_dns_validation'. last error: %!s(<nil>)

When creating an association manually in the AWS Console, the association appears to enter the `create_failed` state after waiting several minutes.

### Affected Resource

* aws_apprunner_custom_domain_association

### PR DESCRIPTION
**Pull request by anGie44**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #19869 
Closes #20349 

Output from acceptance testing:

```
--- SKIP: TestAccAwsAppRunnerCustomDomainAssociation_basic (0.00s)
--- SKIP: TestAccAwsAppRunnerCustomDomainAssociation_disappears (0.00s)
```

### CODE REVIEW

File: aws/resource_aws_apprunner_custom_domain_association_test.go [hunk 1]
```diff
@@ -16,6 +17,11 @@ import (
 )
 
 func TestAccAwsAppRunnerCustomDomainAssociation_basic(t *testing.T) {
+	domain := os.Getenv("APPRUNNER_CUSTOM_DOMAIN")
```
Comment (anGie44) [inline aws/resource_aws_apprunner_custom_domain_association_test.go:20]: i think we had a dictionary for these env vars but I can't remember where to look 😅

Comment (ewbankkit) [reply aws/resource_aws_apprunner_custom_domain_association_test.go:20]: https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/MAINTAINING.md#environment-variable-dictionary

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAwsAppRunnerCustomDomainAssociation_'     
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsAppRunnerCustomDomainAssociation_ -timeout 180m
=== RUN   TestAccAwsAppRunnerCustomDomainAssociation_basic
    resource_aws_apprunner_custom_domain_association_test.go:22: Environment variable APPRUNNER_CUSTOM_DOMAIN is not set
--- SKIP: TestAccAwsAppRunnerCustomDomainAssociation_basic (0.00s)
=== RUN   TestAccAwsAppRunnerCustomDomainAssociation_disappears
    resource_aws_apprunner_custom_domain_association_test.go:60: Environment variable APPRUNNER_CUSTOM_DOMAIN is not set
--- SKIP: TestAccAwsAppRunnerCustomDomainAssociation_disappears (0.00s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	5.670s
```
