### PR TITLE
resource/aws_dynamodb_table: Prevents error when `global_secondary_index[*].range_key` is explicitly set to empty string

### LINKED ISSUE #46322: terraform 6.30 failed with aws_dynamodb_table Error: all indexes must match a defined attribute. Unmatched indexes: [""]
### Terraform and AWS Provider Version

```console
Terraform v1.12.2
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v6.30.0
+ provider registry.terraform.io/hashicorp/random v3.8.1
```

### Affected Resource(s) or Data Source(s)

aws_dynamodb_table

### Expected Behavior

it is an existing resource for a few years, no change on it, I expect to the plan to do nothing.

### Actual Behavior

the plan report an error :
│ Error: all indexes must match a defined attribute. Unmatched indexes: [""]
but on differents tables, and it change at each run (maybe timing on aws query during the plan ?)

with 6.29, the provider crash,

with 6.28 plan report nothing.

This is on a sandbox stack, on a dev stack with the same set of dynamodb tables but more of other resources,
6.30 report the same error, but on differents tables, and it change at each run (maybe timing on aws query ?)
on 6.29 no error, and no crash.

### Relevant Error/Panic Output

```console

```

### Sample Terraform Configuration

<details open>
<summary>Click to expand configuration</summary>

```hcl

  var.dynamodb_attributes = [
    {
      name : "name",
      type : "S"
    },
    {
      name : "tenantId",
      type : "S"
    }
  ]

  var.global_secondary_index_map = [
    {
      name               = "idx_tenant_id"
      hash_key           = "tenantId"
      range_key          = ""
      projection_type    = "ALL"
      non_key_attributes = []
      read_capacity      = 0
      write_capacity     = 0
    }
]

resource "aws_dynamodb_table" "default" {
  name                        = local.name
  billing_mode                = var.billing_mode
  hash_key                    = var.hash_key
  range_key                   = var.range_key
  deletion_protection_enabled = true
  point_in_time_recovery {
    enabled = var.point_in_time_recovery
  }

  read_capacity  = var.billing_mode == "PROVISIONED" ? var.read_capacity : null
  write_capacity = var.billing_mode == "PROVISIONED" ? var.write_capacity : null

  server_side_encryption {
    enabled     = true
    kms_key_arn = var.kms_key_arn
  }

  dynamic "attribute" {
    for_each = local.attributes_final
    content {
      name = attribute.value.name
      type = attribute.value.type
    }
  }

  dynamic "global_secondary_index" {
    for_each = var.global_secondary_index_map
    content {
      hash_key           = global_secondary_index.value.hash_key
      name               = global_secondary_index.value.name
      non_key_attributes = lookup(global_secondary_index.value, "non_key_attributes", null)
      projection_type    = global_secondary_index.value.projection_type
      range_key          = lookup(global_secondary_index.value, "range_key", null)
      read_capacity      = global_secondary_index.value.read_capacity
      write_capacity     = global_secondary_index.value.write_capacity
    }
  }

  dynamic "ttl" {
    for_each = var.ttl_enabled ? [1] : []
    content {
      attribute_name = var.ttl_attribute
      enabled        = var.ttl_enabled
    }
  }

  tags = merge(var.tags, local.role)
}
```
</details>

terraform state show :
resource "aws_dynamodb_table" "default" {
    arn                         = "..."
    billing_mode                = "PAY_PER_REQUEST"
    deletion_protection_enabled = true
    hash_key                    = "name"
    id                          = "..."
    name                        = "..."
    range_key                   = null
    read_capacity               = 0
    region                      = "us-west-2"
    stream_arn                  = null
    stream_enabled              = false
    stream_label                = null
    stream_view_type            = null
    table_class                 = "STANDARD"
    tags                        = {
...
    }
    tags_all                    = {
...
    }
    write_capacity              = 0

    attribute {
        name = "name"
        type = "S"
    }
    attribute {
        name = "tenantId"
        type = "S"
    }

    global_secondary_index {
        hash_key           = "tenantId"
        name               = "idx_tenant_id"
        non_key_attributes = []
        projection_type    = "ALL"
        range_key          = null
        read_capacity      = 0
        write_capacity     = 0
    }

    point_in_time_recovery {
        enabled                 = false
        recovery_period_in_days = 0
    }

    server_side_encryption {
        enabled     = true
        kms_key_arn = "..."
    }

    ttl {
        attribute_name = null
        enabled        = false
    }
}

### Steps to Reproduce

just a terraform plan, it should report no change on our dynamodb resources.

### Debug Logging

<details open>
<summary>Click to expand log output</summary>

```console

```
</details>

### GenAI / LLM Assisted Development

n/a

### Important Facts and References

those tables exist in our system (terraform/aws) for more than 2 years and are live and running well in multiple accounts and region.
No change are planned on them, I was working on terraform for another change on something else in our infra.

with 6.30 I have the error,
with 6.29, sometime it pass, sometime it crash,
with 6.28 it pass.

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by gdavison**
## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the library.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

### Description

Before the introduction of multi-attribute keys in DynamoDB Global Secondary Indexes, the `range_key` was ignored if it was explicitly set to an empty string. This was missed when adding multi-attribute key support.

Also adds validation for `hash_key`, `range_key`, and `key_schema[*].attribute_name`.

### Relations

Closes #46322

### Output from Acceptance Testing

```console
% make testacc PKG=dynamodb TESTS=TestAccDynamoDBTable_

--- PASS: TestAccDynamoDBTable_GSI_unknown (265.28s)
--- PASS: TestAccDynamoDBTable_nameKnownAfterApply_attribute_notIndexed_onUpdate (265.63s)
--- PASS: TestAccDynamoDBTable_GSI_keySchema_unknown (273.25s)
--- PASS: TestAccDynamoDBTable_nameKnownAfterApply_attribute_notIndexed (24.15s)
--- PASS: TestAccDynamoDBTable_Replica_MRSC_MixedConsistencyModes (345.64s)
--- FAIL: TestAccDynamoDBTable_Replica_MRSC_TooManyReplicas (383.98s)
--- PASS: TestAccDynamoDBTable_Replica_MRSC_NotEnoughReplicas (392.50s)
--- PASS: TestAccDynamoDBTable_tableClassInfrequentAccess (421.74s)
--- PASS: TestAccDynamoDBTable_Tags_ComputedTag_OnUpdate_add (421.74s)
--- PASS: TestAccDynamoDBTable_TTL_updateEnable (422.14s)
--- PASS: TestAccDynamoDBTable_nameKnownAfterApply (148.97s)
--- PASS: TestAccDynamoDBTable_Replica_upgradeV6_2_0 (536.29s)
--- PASS: TestAccDynamoDBTable_Tags_ComputedTag_onCreate (132.26s)
--- PASS: TestAccDynamoDBTable_warmThroughputDefault (132.45s)
--- PASS: TestAccDynamoDBTable_GSI_keySchema_removeHashKey (636.18s)
--- PASS: TestAccDynamoDBTable_tags (674.46s)
--- PASS: TestAccDynamoDBTable_Tags_DefaultTags_nullNonOverlappingResourceTag (151.05s)
--- PASS: TestAccDynamoDBTable_gsiWarmThroughput_switchBilling (400.67s)
--- PASS: TestAccDynamoDBTable_importTable (197.70s)
--- PASS: TestAccDynamoDBTable_Tags_DefaultTags_overlapping (353.11s)
--- PASS: TestAccDynamoDBTable_Replica_MRSC_witness_tags_nonPropagatedTagsAreUnmanaged (776.79s)
--- PASS: TestAccDynamoDBTable_Tags_DefaultTags_nullOverlappingResourceTag (113.40s)
--- PASS: TestAccDynamoDBTable_Tags_DefaultTags_emptyProviderOnlyTag (79.05s)
--- PASS: TestAccDynamoDBTable_tableClass_migrate (77.42s)
--- PASS: TestAccDynamoDBTable_Replica_MRSC_tags_updateIsPropagated_twoOfTwo (831.28s)
--- PASS: TestAccDynamoDBTable_Replica_MRSC_witness_tags_notPropagatedToAddedReplica (676.94s)
--- PASS: TestAccDynamoDBTable_Replica_MRSC_tags_nonPropagatedTagsAreUnmanaged (832.93s)
--- PASS: TestAccDynamoDBTable_Tags_DefaultTags_emptyResourceTag (77.63s)
--- PASS: TestAccDynamoDBTable_warmThroughput (316.38s)
--- PASS: TestAccDynamoDBTable_Replica_MRSC_witness_tags_propagateToAddedReplica (601.90s)
--- PASS: TestAccDynamoDBTable_Replica_MRSC_tags_propagateToAddedReplica (598.82s)
--- PASS: TestAccDynamoDBTable_tableClass_ConcurrentModification (116.98s)
--- PASS: TestAccDynamoDBTable_Replica_MRSC_CreateEventuallyConsistent (904.24s)
--- PASS: TestAccDynamoDBTable_Tags_DefaultTags_updateToResourceOnly (126.23s)
--- PASS: TestAccDynamoDBTable_Replica_MRSC_witness_tags_updateIsPropagated_twoOfTwo (535.77s)
--- PASS: TestAccDynamoDBTable_GSI_keySchema_OnCreate_multipleHashKeys (107.64s)
--- PASS: TestAccDynamoDBTable_tableClassExplicitDefault (113.64s)
--- PASS: TestAccDynamoDBTable_Tags_DefaultTags_updateToProviderOnly (114.88s)
--- PASS: TestAccDynamoDBTable_gsiWarmThroughput_billingPayPerRequest (605.52s)
--- PASS: TestAccDynamoDBTable_gsiWarmThroughput_billingProvisioned (627.74s)
--- PASS: TestAccDynamoDBTable_GSI_transitionKeySchemaToHashKey_noChange (153.80s)
--- PASS: TestAccDynamoDBTable_backupEncryption (374.92s)
--- PASS: TestAccDynamoDBTable_GSI_transitionHashKeyToKeySchema_noChange (156.36s)
--- PASS: TestAccDynamoDBTable_Replica_MRSC_tagsUpdate (1106.11s)
--- PASS: TestAccDynamoDBTable_Replica_MRSC_witness_tagsUpdate (1122.83s)
--- PASS: TestAccDynamoDBTable_Replica_MRSC_Create_witness_too_many_replicas (120.92s)
--- PASS: TestAccDynamoDBTable_GSI_keySchema_OnCreate_singleHashKey (158.71s)
--- PASS: TestAccDynamoDBTable_GSI_keySchema_OnCreate_singleRangeKey (198.14s)
--- PASS: TestAccDynamoDBTable_GSI_transitionKeySchemaToHashKey_removeKey (446.00s)
--- PASS: TestAccDynamoDBTable_GSI_keySchema_addHashKey (452.91s)
--- PASS: TestAccDynamoDBTable_Replica_MRSC_witness_tags_updateIsPropagated_oneOfTwo (510.87s)
--- PASS: TestAccDynamoDBTable_GSI_transitionHashKeyToKeySchema_addHashKey (445.65s)
--- PASS: TestAccDynamoDBTable_Replica_MRSC_witness_pitr (533.21s)
--- PASS: TestAccDynamoDBTable_Replica_MRSC_tags_updateIsPropagated_oneOfTwo (599.52s)
--- PASS: TestAccDynamoDBTable_Replica_MRSC_pitr (539.24s)
--- PASS: TestAccDynamoDBTable_Replica_MRSC_Create_witness (395.49s)
--- PASS: TestAccDynamoDBTable_backup_overrideEncryption (906.03s)
--- PASS: TestAccDynamoDBTable_Replica_MRSC_Create (382.17s)
--- PASS: TestAccDynamoDBTable_deletion_protection (142.51s)
--- PASS: TestAccDynamoDBTable_disappears (100.91s)
--- PASS: TestAccDynamoDBTable_Replica_tags_updateIsPropagated_oneOfTwo (924.97s)
--- PASS: TestAccDynamoDBTable_Disappears_payPerRequestWithGSI (288.54s)
--- PASS: TestAccDynamoDBTable_Replica_singleCMK (505.35s)
--- PASS: TestAccDynamoDBTable_Replica_MRSC_witness_pitrKMS (1029.92s)
--- PASS: TestAccDynamoDBTable_basic (141.13s)
--- PASS: TestAccDynamoDBTable_attributeUpdateValidation (10.78s)
--- PASS: TestAccDynamoDBTable_Tags_IgnoreTags_Overlap_resourceTag (266.30s)
--- PASS: TestAccDynamoDBTable_Replica_singleDefaultKeyEncrypted (622.34s)
--- PASS: TestAccDynamoDBTable_Replica_tags_nonPropagatedTagsAreUnmanaged (860.47s)
--- PASS: TestAccDynamoDBTable_Replica_MRSC_pitrKMS (1079.18s)
--- PASS: TestAccDynamoDBTable_Replica_deletionProtection (1981.91s)
--- PASS: TestAccDynamoDBTable_Replica_tags_notPropagatedToAddedReplica (866.81s)
--- PASS: TestAccDynamoDBTable_Tags_IgnoreTags_Overlap_defaultTag (168.23s)
--- PASS: TestAccDynamoDBTable_Replica_MRSC_doubleAddCMK (1146.10s)
--- PASS: TestAccDynamoDBTable_Replica_tags_propagateToAddedReplica (862.41s)
--- PASS: TestAccDynamoDBTable_TTL_validate (30.50s)
--- PASS: TestAccDynamoDBTable_extended (522.36s)
--- PASS: TestAccDynamoDBTable_Tags_EmptyTag_OnUpdate_add (268.37s)
--- PASS: TestAccDynamoDBTable_Replica_tags_updateIsPropagated_twoOfTwo (876.52s)
--- PASS: TestAccDynamoDBTable_Replica_pitr (761.03s)
--- PASS: TestAccDynamoDBTable_Tags_EmptyTag_OnUpdate_replace (246.87s)
--- PASS: TestAccDynamoDBTable_Tags_DefaultTags_nonOverlapping (326.43s)
--- PASS: TestAccDynamoDBTable_Tags_ComputedTag_OnUpdate_replace (250.51s)
--- PASS: TestAccDynamoDBTable_encryption (336.40s)
--- PASS: TestAccDynamoDBTable_Replica_MRSC_witness_doubleAddCMK (1333.85s)
--- PASS: TestAccDynamoDBTable_lsiUpdate (203.10s)
--- PASS: TestAccDynamoDBTable_Replica_singleStreamSpecification (514.22s)
--- PASS: TestAccDynamoDBTable_streamSpecificationValidation (12.50s)
--- PASS: TestAccDynamoDBTable_Tags_emptyMap (179.49s)
--- PASS: TestAccDynamoDBTable_Replica_singleDefaultKeyEncryptedAmazonOwned (907.35s)
--- PASS: TestAccDynamoDBTable_TTL_disabled (146.72s)
--- PASS: TestAccDynamoDBTable_Tags_addOnUpdate (205.01s)
--- PASS: TestAccDynamoDBTable_TTL_enabled (153.60s)
--- PASS: TestAccDynamoDBTable_Tags_DefaultTags_providerOnly (431.34s)
--- PASS: TestAccDynamoDBTable_Tags_EmptyTag_onCreate (189.25s)
--- PASS: TestAccDynamoDBTable_lsiNonKeyAttributes (318.48s)
--- PASS: TestAccDynamoDBTable_Tags_null (375.35s)
--- PASS: TestAccDynamoDBTable_GSI_validate_keySchema_tooManyHashKeys (44.21s)
--- PASS: TestAccDynamoDBTable_GsiUpdateNonKeyAttributes_emptyPlan (479.83s)
--- PASS: TestAccDynamoDBTable_GSI_validate_exactlyOneOfKeySchemaHashKey (5.12s)
--- PASS: TestAccDynamoDBTable_BillingModeGSI_payPerRequestToProvisioned (666.26s)
--- PASS: TestAccDynamoDBTable_streamSpecification (466.93s)
--- PASS: TestAccDynamoDBTable_GSI_validate_rangeKeyConflictsWithKeySchema (9.01s)
--- PASS: TestAccDynamoDBTable_gsiOnDemandThroughput (512.65s)
--- PASS: TestAccDynamoDBTable_onDemandThroughput (560.56s)
--- PASS: TestAccDynamoDBTable_GSI_keySchema_removeGSI (256.85s)
--- PASS: TestAccDynamoDBTable_restoreCrossRegion (973.06s)
--- PASS: TestAccDynamoDBTable_provisioned_gsiUpdateCapacity_DifferentFromTable (206.79s)
--- PASS: TestAccDynamoDBTable_GSI_rangeKeyExplicitEmptyString (120.00s)
--- PASS: TestAccDynamoDBTable_provisioned_gsiUpdateCapacity_SameAsTable (159.64s)
--- PASS: TestAccDynamoDBTable_gsiUpdateNonKeyAttributes (640.03s)
--- PASS: TestAccDynamoDBTable_GSIvalidate_keySchema_tooManyRangeKeys (3.49s)
--- PASS: TestAccDynamoDBTable_Replica_tagsUpdate (1805.35s)
--- PASS: TestAccDynamoDBTable_BillingMode_provisionedToPayPerRequestIgnoreChanges (237.24s)
--- PASS: TestAccDynamoDBTable_streamSpecificationDiffs (702.83s)
--- PASS: TestAccDynamoDBTable_BillingMode_payPerRequestBasic (668.41s)
--- PASS: TestAccDynamoDBTable_enablePITR (122.37s)
--- PASS: TestAccDynamoDBTable_GSI_keySchema_OnCreate_multipleRangeKeys (82.18s)
--- PASS: TestAccDynamoDBTable_BillingModeGSI_provisionedToPayPerRequest (665.98s)
--- PASS: TestAccDynamoDBTable_attributeUpdate (1062.47s)
--- PASS: TestAccDynamoDBTable_enablePITRWithCustomRecoveryPeriod (144.60s)
--- PASS: TestAccDynamoDBTable_BillingMode_payPerRequestToProvisionedIgnoreChanges (195.78s)
--- PASS: TestAccDynamoDBTable_GSI_keySchema_maxSet (63.08s)
--- PASS: TestAccDynamoDBTable_Replica_pitrKMS (1770.78s)
--- PASS: TestAccDynamoDBTable_BillingMode_payPerRequestToProvisioned (138.59s)
--- PASS: TestAccDynamoDBTable_BillingMode_provisionedToPayPerRequest (291.01s)
--- PASS: TestAccDynamoDBTable_GSI_keySchema_addRangeKey (362.16s)
--- PASS: TestAccDynamoDBTable_GSI_keySchema_removeRangeKey (337.37s)
--- PASS: TestAccDynamoDBTable_gsiUpdateOtherAttributes (934.18s)
--- PASS: TestAccDynamoDBTable_Replica_single (1398.50s)
--- PASS: TestAccDynamoDBTable_Replica_multiple (1546.53s)
--- FAIL: TestAccDynamoDBTable_Replica_doubleAddCMK (2570.76s)
--- PASS: TestAccDynamoDBTable_TTL_updateDisable (3736.20s)
```

`TestAccDynamoDBTable_Replica_MRSC_TooManyReplicas` and `TestAccDynamoDBTable_Replica_doubleAddCMK` are pre-existing failures

### CODE REVIEW

File: internal/verify/validate.go [hunk 1]
```diff
@@ -569,3 +569,19 @@ func CaseInsensitiveMatchDeprecation(valid []string) schema.SchemaValidateDiagFu
 		return diags
 	}
 }
+
+func WarnStringIsNotEmpty(v any, path cty.Path) diag.Diagnostics {
+	var diags diag.Diagnostics
+	s := v.(string)
```
Comment (YakDriver) [inline internal/verify/validate.go]: If we're accepting `v any`, might be worth type switching instead to avoid remote chance of a panic.

File: internal/verify/validate.go [hunk 2]
```diff
@@ -569,3 +569,19 @@ func CaseInsensitiveMatchDeprecation(valid []string) schema.SchemaValidateDiagFu
...
+		diags = append(diags, diag.Diagnostic{
+			Severity:      diag.Warning,
+			Summary:       "Empty String",
+			Detail:        "Value must not be an empty string.\n\nThis will be an error in a future release of the provider.",
+			AttributePath: path,
+		})
+	}
+
+	return diags
+}
```
Comment (YakDriver) [inline internal/verify/validate.go:586]: Simple unit test for `WarnStringIsNotEmpty` would be good.

**Review by YakDriver — DISMISSED** [review]
Couple comments but LGTM

**Review by YakDriver — APPROVED** [review]
LGTM 🎉
