### PR TITLE
resource/aws_ram: Fix eventual consistency problems

### LINKED ISSUE #13494: TGW multi-provider aws_ram_resource_share_accepter cannot find invitation
_This issue was originally opened by @mitucsaki as hashicorp/terraform#25023. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._
    
<hr>
    
Creating a TGW across 4 accounts. I am using the provider mark to switch accounts. organization RAM sharing is off and TGW auto-accept is also turned off for security. RAM external principals = true:

Account 1 creates the TGW and RAM association. Associates the TGW and creates the ram principals with account 2 and account 3
Account 2 uses aws_ram_resource_share_accepter to accept the ram invitation
Account 3 uses aws_ram_resource_share_accepter to accept the ram invitation
```
resource "aws_ram_resource_association" "ram_tgw_associate" {
  provider = aws.account_1

  depends_on = [aws_ec2_transit_gateway.tgw]

  resource_arn       = aws_ec2_transit_gateway.tgw.arn
  resource_share_arn = aws_ram_resource_share.ram.id
}

resource "aws_ram_principal_association" "tgw_ram_principal_account_2" {
  provider = aws.account_1

  depends_on = [aws_ram_resource_association.ram_tgw_associate]

  principal          = data.aws_caller_identity.aws.account_2.account_id
  resource_share_arn = aws_ram_resource_share.ram.id
}
resource "aws_ram_principal_association" "tgw_ram_principal_account_3" {
  provider = aws.account_1

  depends_on = [aws_ram_resource_association.ram_tgw_associate]

  principal          = data.aws_caller_identity.aws.account_3.account_id
  resource_share_arn = aws_ram_resource_share.ram.id
}

resource "aws_ram_resource_share_accepter" "tgw_ram_accept_account_2" {
  provider = aws.account_2

  share_arn = aws_ram_principal_association.tgw_ram_principal_account_2.resource_share_arn
}

resource "aws_ram_resource_share_accepter" "tgw_ram_accept_account_3" {
  provider = aws.account_3

  share_arn = aws_ram_principal_association.tgw_ram_principal_account_3.resource_share_arn
}
```
### Expected Behaviour 
Both Accounts successfully accept the invitation and TF continues

### Actual behavior:
Account 2 successfully accepts and has the invitation approved:
`aws_ram_resource_share_accepter. tgw_ram_accept_account_2: Creation complete after 1s [id=arn:aws:ram:ca-central-1:OMITTED:resource-share/resource-id-here-omitted`

Account 3 gives an error saying it cannot find the resource share id: **however** in the AWS Console the invitation is accepted and valid and I can see it being shared from terraform. Looks like TF fails to acknowledge that the creation is completed.

`Error retrieving resource shares: UnknownResourceException: ResourceShare arn:aws:ram:ca-central-1:OMITTED:resource-share/resource-id-here-omitted could not be found`

### Other Notes
I've gone through the TGW Example of sharing, however here I am using more providers and my organization does not allow RAM sharing directly, therefore I have to include this extra step + the external principals

### LINKED ISSUE #15187: aws_ram_share_accepter fails to refresh state
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.13.1
+ provider registry.terraform.io/hashicorp/aws v3.6.0
+ provider registry.terraform.io/hashicorp/time v0.5.0

Your version of Terraform is out of date! The latest version
is 0.13.2. You can update by downloading from https://www.terraform.io/downloads.html
```
### Affected Resource(s)

* aws_ram_resource_share_accepter

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.3"
    }
    time = {
      source  = "hashicorp/time"
      version = "~> 0.5.0"
    }
  }
  required_version = ">= 0.13"
}

provider "aws" {
  alias   = "dev_nsoc"
  region  = "us-east-2"
  profile = "dev-nsoc"
}

provider "aws" {
  alias   = "dev_multi"
  region  = "us-east-2"
  profile = "dev-multi"
}

data "aws_caller_identity" "dev_multi" {
  provider = aws.dev_multi
}

resource "aws_ec2_transit_gateway" "tgw" {
  provider                        = aws.dev_nsoc
  amazon_side_asn                 = 65000
  auto_accept_shared_attachments  = "enable"
  default_route_table_association = "disable"
  default_route_table_propagation = "disable"
  description                     = "TGW for VPNs to on-prem sites"
  dns_support                     = "enable"
  vpn_ecmp_support                = "enable"
  tags = {
    Name        = "dhagan-testing"
  }
}

resource "aws_ram_resource_share" "tgw" {
  provider                  = aws.dev_nsoc
  name                      = "dhagan-test"
  allow_external_principals = true
  tags = {
    Name        = "dhagan-test"
  }
}

resource "aws_ram_resource_association" "tgw" {
  provider           = aws.dev_nsoc
  resource_share_arn = aws_ram_resource_share.tgw.arn
  resource_arn       = aws_ec2_transit_gateway.tgw.arn
}

resource "aws_ram_principal_association" "tgw" {
  provider           = aws.dev_nsoc
  principal          = data.aws_caller_identity.dev_multi.account_id
  resource_share_arn = aws_ram_resource_share.tgw.arn
  depends_on = [
    aws_ram_resource_association.tgw
  ]
}

resource "aws_ram_resource_share_accepter" "tgw" {
  provider  = aws.dev_multi
  share_arn = aws_ram_principal_association.tgw.resource_share_arn
}

```

### Debug Output

https://gist.github.com/dthvt/2071c4ac7efadf383ea9907a448c046e

### Expected Behavior

Expect the RAM share to be accepted.

### Actual Behavior

Seems to be a very common but not 100% occurring error.  The RAM share accepter fails with the error:
```
Error: error retrieving resource shares: UnknownResourceException: ResourceShare arn:aws:ram:us-east-2:024660257967:resource-share/e3eeada4-b908-4a0a-8c01-045441086956 could not be found.
```

In the debug output, the call to /getresourceshares (which at first glance appears correct to me) returns a 400 code from AWS.  Not sure if this is a timing issue that needs to be retried.

Sometimes the accepter resource is not in the state file (even though it's been accepted).  Sometimes (as in the example I've attached here) the accepter is added to the state file but marked as tainted.  Example plan debug is here https://gist.github.com/dthvt/fab84469caaf7fe8b4a275a15ddc67fd

I've tried adding a time_sleep resource between the share and accepter, but that seems irrelevant since it's actually the API calls within the accepter itself that end up erroring out.

As a work around, you can use terraform import to add the accepter to the state file (if it's already there and marked as tainted, a terraform state rm first, then an import seems to work).

### Steps to Reproduce

1. `terraform apply`

May take more than one attempt unfortunately.  However, it happens VERY commonly for me and should be reproducible.

### Important Factoids

Two accounts in the same AWS org w/ RAM sharing turned off (so accepter is required).

### References

* #0000

### LINKED ISSUE #16578: TestAccAwsRamResourceShareAccepter_basic fails
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.13.5
```

And terraform-provider-aws is the latest master.

### Affected Resource(s)

* aws_ram_resource_share_accepter

### Terraform Configuration Files

See [testAccAwsRamResourceShareAccepterBasic](https://github.com/hashicorp/terraform-provider-aws/blob/81da040d9fd06811b7e007533c829ec72f299543/aws/resource_aws_ram_resource_share_accepter_test.go#L108).

### Expected Behavior

The test passes

### Actual Behavior

The test fails with the following message:

```
$ make testacc TESTARGS='-run=TestAccAwsRamResourceShareAccepter_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsRamResourceShareAccepter_basic -timeout 120m
=== RUN   TestAccAwsRamResourceShareAccepter_basic
=== PAUSE TestAccAwsRamResourceShareAccepter_basic
=== CONT  TestAccAwsRamResourceShareAccepter_basic
    TestAccAwsRamResourceShareAccepter_basic: resource_aws_ram_resource_share_accepter_test.go:23: Step 1/2 error: Error running apply:
        Error: No RAM Resource Share (arn:aws:ram:ap-northeast-1:732481906906:resource-share/f65079e2-e952-4014-8a54-500b19ea767a) invitation found

        NOTE: If both AWS accounts are in the same AWS Organization and RAM Sharing with AWS Organizations is enabled, this resource is not necessary


--- FAIL: TestAccAwsRamResourceShareAccepter_basic (24.27s)
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	26.148s
FAIL
make: *** [testacc] Error 1
```

```
make testacc TESTARGS='-run=TestAccAwsRamResourceShareAccepter_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsRamResourceShareAccepter_basic -timeout 120m
=== RUN   TestAccAwsRamResourceShareAccepter_basic
=== PAUSE TestAccAwsRamResourceShareAccepter_basic
=== CONT  TestAccAwsRamResourceShareAccepter_basic
    resource_aws_ram_resource_share_accepter_test.go:23: Step 1/2 error: Error running apply:
        Error: error retrieving resource shares: UnknownResourceException: ResourceShare arn:aws:ram:ap-northeast-1:732481906906:resource-share/b57bc5aa-7736-4cae-babe-c69e9c2592ed could not be found.


--- FAIL: TestAccAwsRamResourceShareAccepter_basic (28.01s)
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	29.992s
FAIL
make: *** [testacc] Error 1
```
### References

* https://github.com/hashicorp/terraform-provider-aws/issues/13494

When I implementing https://github.com/hashicorp/terraform-provider-aws/pull/16576, I noticed `aws_ram_resource_share_accepter` kept failing, so I ran its ACC test and the test failed too with the same error. I'm going to look into the problem later but if someone has any ideas about what is wrong with it, I'd like to know.

### LINKED ISSUE #17658: aws_ram_resource_share_accepter sometimes fails while accept actually succeeded at AWS
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

* hashicorp/aws: version = "~> 3.28.0"
* Terraform v0.13.5
* 
### Affected Resource(s)

* aws_ram_resource_share_accepter

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
provider "aws" {
  region = "eu-central-1"
  alias  = "eu-central-1"
}
provider "aws" {
  region = "eu-west-1"
  alias  = "eu-west-1"
}
provider "aws" {
  region = "eu-west-3"
  alias  = "eu-west-3"
}

resource "aws_ram_resource_share_accepter" "accept_eu-central-1" {
  share_arn = "arn:aws:ram:eu-central-1:xxxxxxxxx:resource-share/f10..."
  provider  = aws.eu-central-1
}

resource "aws_ram_resource_share_accepter" "accept_eu-west-1" {
  share_arn = "arn:aws:ram:eu-west-1:xxxxxxxxx:resource-share/202..."
  provider  = aws.eu-west-1
}

resource "aws_ram_resource_share_accepter" "accept_eu-west-3" {
  share_arn = "arn:aws:ram:eu-west-3:xxxxxxxxx:resource-share/b49..."
  provider  = aws.eu-west-3
}

```

### Debug Output

```
terraform apply -auto-approve tfplan
aws_ram_resource_share_accepter.accept_eu-west-1: Creating...
aws_ram_resource_share_accepter.accept_eu-central-1: Creating...
aws_ram_resource_share_accepter.accept_eu-west-3: Creating...
aws_ram_resource_share_accepter.accept_eu-west-3: Creation complete after 2s [id=arn:aws:ram:eu-west-3:xxxxxxx:resource-share/b49...]
aws_ram_resource_share_accepter.accept_eu-central-1: Creation complete after 2s [id=arn:aws:ram:eu-central-1:xxxxxxx:resource-share/f10...]

Error: error retrieving resource shares: UnknownResourceException: ResourceShare arn:aws:ram:eu-west-1:xxxxxxx:resource-share/202... could not be found.
```
### Expected Behavior

Since the share-ids are correct: all 3 shares accepted and terraform-state reflects this.

### Actual Behavior

Acceptance at AWS was successful for all 3 resources which was verified on the console
Yet Terraform sees 2 successes and 1 failure, resulting in a tainted resource.

A 2nd apply will try to delete and recreate that tainted resource, resulting in a deletion of the actual share in that region.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

### LINKED ISSUE #18332: Race condition in RAM Share Accepter on Create
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
$ terraform version
Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/aws v3.33.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/time v0.7.0
```

### Affected Resource(s)

* `aws_ram_resource_share_accepter`

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
provider "aws" {
  profile = "resource-member"
}

provider "aws" {
  alias   = "owner"
  profile = "resource-owner"
}

resource "aws_ram_resource_share_accepter" "receiver_accept" {
  share_arn = time_sleep.principal_association_invite.triggers.resource_share_arn

  # This depends_on is present to demonstrate the race condition. When the share
  # has resources, *sometimes* the cross-account invite/accept workflow will fail
  # when the accepter attempts to read the resource after accepting the invite.
  depends_on = [
    aws_ram_resource_share.owner,
    aws_ram_resource_association.owner,
  ]
}

# Sometimes the invite takes a bit to show up in the account, and at the moment
# the accepter does not retry the command to lookup the invite
resource "time_sleep" "principal_association_invite" {
  create_duration = "10s"

  triggers = {
    resource_share_arn = aws_ram_principal_association.invite.resource_share_arn
  }
}

resource "aws_ram_principal_association" "invite" {
  provider = aws.owner

  principal          = data.aws_caller_identity.member.account_id
  resource_share_arn = aws_ram_resource_share.owner.arn

  # This depends_on is present to demonstrate the race condition. When the share
  # has resources, *sometimes* the cross-account invite/accept workflow will fail
  # when the accepter attempts to read the resource after accepting the invite.
  depends_on = [
    aws_ram_resource_share.owner,
    aws_ram_resource_association.owner,
  ]
}

resource "aws_ram_resource_association" "owner" {
  provider = aws.owner

  resource_arn       = aws_route53_resolver_rule.this.arn
  resource_share_arn = aws_ram_resource_share.owner.arn
}

resource "aws_ram_resource_share" "owner" {
  provider = aws.owner

  name                      = local.name
  allow_external_principals = true

  tags = {
    Name = local.name
  }

  # This depends_on is present to demonstrate the race condition. When the share
  # has resources, *sometimes* the cross-account invite/accept workflow will fail
  # when the accepter attempts to read the resource after accepting the invite.
  depends_on = [
    aws_route53_resolver_rule.this,
  ]
}

resource "aws_route53_resolver_rule" "this" {
  provider = aws.owner

  domain_name          = "${random_string.this.result}.com"
  name                 = local.name
  rule_type            = "FORWARD"
  resolver_endpoint_id = aws_route53_resolver_endpoint.this.id

  target_ip {
    ip = "123.45.67.89"
  }
}

resource "aws_route53_resolver_endpoint" "this" {
  provider = aws.owner

  name      = local.name
  direction = "OUTBOUND"

  security_group_ids = [
    aws_security_group.this.id,
  ]

  ip_address {
    subnet_id = aws_subnet.one.id
    ip        = "10.0.0.43"
  }

  ip_address {
    subnet_id = aws_subnet.two.id
    ip        = "10.0.1.43"
  }
}

resource "aws_security_group" "this" {
  provider = aws.owner

  name        = local.name
  description = "test for ${local.name}"
  vpc_id      = aws_vpc.this.id

  tags = {
    Name = local.name
  }
}

resource "aws_subnet" "one" {
  provider = aws.owner

  vpc_id     = aws_vpc.this.id
  cidr_block = "10.0.0.0/24"

  tags = {
    Name = local.name
  }
}

resource "aws_subnet" "two" {
  provider = aws.owner

  vpc_id     = aws_vpc.this.id
  cidr_block = "10.0.1.0/24"

  tags = {
    Name = local.name
  }
}

resource "aws_vpc" "this" {
  provider = aws.owner

  cidr_block = "10.0.0.0/16"
}

resource "random_string" "this" {
  length  = 6
  upper   = false
  special = false
  number  = false
}

locals {
  name = "tf-test-resource-share-${random_string.this.result}"
}

data "aws_caller_identity" "member" {}

output "ram_share_arn" {
  value = aws_ram_resource_share.owner.arn
}
```

### Expected Behavior

Running `terraform apply` should "accept" the invite for the RAM Share Accepter, without erroring that it cannot find the share.

### Actual Behavior

Receive the error, `Error: error retrieving resource shares: UnknownResourceException: ResourceShare arn:aws:ram:us-east-1:aaaaaaaaaa:resource-share/xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx could not be found.`

When the error occurs, it appears the invite is actually accepted, but on the subsequent Read the share is not found and generates the error. I'm jumping to this conclusion based on the text of the error message, and because the resource ends up in the state, just tainted. If I untaint it, all is well.

### Steps to Reproduce

This is a race condition, and appears to depend on the state of the RAM Share and the resource/principal associations of the share. I.e. the error doesn't occur *every* time, but it occurs more frequently in some scenarios. It helps to use a loop to detect the problem.

1. `for i in {1..100}; do echo "Loop = $i"; terraform apply -auto-approve || break; terraform destroy -auto-approve; done`

```
Loop = 12
...
aws_ram_resource_share_accepter.receiver_accept: Creating...

Error: error retrieving resource shares: UnknownResourceException: ResourceShare arn:aws:ram:us-east-1:aaaaaaaaaa:resource-share/xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx could not be found.

  on main.tf line 10, in resource "aws_ram_resource_share_accepter" "receiver_accept":
  10: resource "aws_ram_resource_share_accepter" "receiver_accept" {
```

```
$ terraform state list | grep aws_ram_resource_share_accepter.receiver_accept
aws_ram_resource_share_accepter.receiver_accept
```

```
$ terraform plan
...
  # aws_ram_resource_share_accepter.receiver_accept is tainted, so must be replaced
-/+ resource "aws_ram_resource_share_accepter" "receiver_accept" {
...
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

### PR DESCRIPTION
**Pull request by shuheiktgw**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #13494
Closes #15187
Closes #16578
Closes #17658
Closes #18332

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
* resource/aws_ram_resource_share_accepter: Fix eventual consistency problems
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAwsRamResourceShareAccepter_*'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsRamResourceShareAccepter_* -timeout 120m
=== RUN   TestAccAwsRamResourceShareAccepter_basic
=== PAUSE TestAccAwsRamResourceShareAccepter_basic
=== CONT  TestAccAwsRamResourceShareAccepter_basic
--- PASS: TestAccAwsRamResourceShareAccepter_basic (79.33s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	81.162s

$ make testacc TESTARGS='-run=TestAccAwsRamResourceShare_*'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsRamResourceShare_* -timeout 120m
=== RUN   TestAccAwsRamResourceShareAccepter_basic
=== PAUSE TestAccAwsRamResourceShareAccepter_basic
=== RUN   TestAccAwsRamResourceShare_basic
=== PAUSE TestAccAwsRamResourceShare_basic
=== RUN   TestAccAwsRamResourceShare_AllowExternalPrincipals
=== PAUSE TestAccAwsRamResourceShare_AllowExternalPrincipals
=== RUN   TestAccAwsRamResourceShare_Name
=== PAUSE TestAccAwsRamResourceShare_Name
=== RUN   TestAccAwsRamResourceShare_Tags
=== PAUSE TestAccAwsRamResourceShare_Tags
=== CONT  TestAccAwsRamResourceShareAccepter_basic
=== CONT  TestAccAwsRamResourceShare_Name
=== CONT  TestAccAwsRamResourceShare_AllowExternalPrincipals
=== CONT  TestAccAwsRamResourceShare_Tags
=== CONT  TestAccAwsRamResourceShare_basic
--- PASS: TestAccAwsRamResourceShare_basic (42.74s)
--- PASS: TestAccAwsRamResourceShare_Name (69.01s)
--- PASS: TestAccAwsRamResourceShare_AllowExternalPrincipals (69.10s)
--- PASS: TestAccAwsRamResourceShareAccepter_basic (90.10s)
--- PASS: TestAccAwsRamResourceShare_Tags (92.77s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	94.688s
```

Thank you for your review! 👍

### CODE REVIEW

File: aws/resource_aws_ram_resource_share_accepter.go [hunk 1]
```diff
@@ -233,12 +228,47 @@ func resourceAwsRamResourceShareAccepterDelete(d *schema.ResourceData, meta inte
...
 }
 
-func resourceAwsRamResourceShareGetInvitation(conn *ram.RAM, resourceShareARN, status string) (*ram.ResourceShareInvitation, error) {
+func resourceAwsRamResourceShareAccepterGetInvitation(conn *ram.RAM, resourceShareARN, status string) (*ram.ResourceShareInvitation, error) {
+	var invitation *ram.ResourceShareInvitation
+
+	// Retry for Ram resource share invitation eventual consistency
+	err := resource.Retry(1*time.Minute, func() *resource.RetryError {
+		i, err := findResourceShareInvitation(conn, resourceShareARN, status)
+		invitation = i
```
Comment (dthvt) [inline aws/resource_aws_ram_resource_share_accepter.go:237]: Not a golang expert, but is there a reason `i` is used here and then immediately assigned to `invitation` instead of just using `invitation, err :=` ?

Comment (shuheiktgw) [reply aws/resource_aws_ram_resource_share_accepter.go]: No, actually you cannot substitute the returned output for the outer `invitation` using `:=`...

Comment (dthvt) [reply aws/resource_aws_ram_resource_share_accepter.go]: Ah, TIL.  Thanks!

**Comment by pkleanthous** [comment]
Hey guys,

Can you please merge this PR?

**Comment by datacenter-dylan** [comment]
Any estimate on when we can expect this to be merged?

**Comment by lorengordon** [comment]
This PR _might_ also fix the race condition I reported here: https://github.com/hashicorp/terraform-provider-aws/pull/17032

**Comment by lorengordon** [comment]
@YakDriver I [built the aws provider using this branch](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/DEVELOPMENT.md#using-the-provider) and can confirm it does appear to also address the race condition I reported in #18332 (and probably #17658 and #15187, as well as the two linked in the PR description  #13494 and #16578). At least, I looped over 100 builds without encountering the failure...

**Comment by YakDriver** [comment]
@shuheiktgw My friend, thank you for this excellent PR. Unfortunately, I believe due to account settings changes on our side, I cannot currently test this properly. Rather than wait for us to straighten out our account problems, if you (and @lorengordon) can help test/fix my new changes, that would be very helpful! Please let me know if you have any questions.

**Comment by lorengordon** [comment]
@YakDriver running my test now, the loop takes a long time, so probably will report back tomorrow.

**Comment by lorengordon** [comment]
fwiw, closing the loop, finally made it through my looped tests for the race condition. didn't encounter it even once in 100 executions of the test config, so 🤞 i'm pretty sure this is solid!
