### PR TITLE
`aws_elasticache_replication_group`: Add `node_group_configuration`

### LINKED ISSUE #5118: resource/aws_elasticache_replication_group: support setting primary/replica AZ atrributes inside NodeGroupConfiguration for RedisClusterModelEnabled
Currently I do not have a way to express in an `aws_elasticache_replication_group` resource block which availability zone my primary node gets deployed in and which AZ its read replicas are deployed in. The AWS ElastiCache SDK supports the following attributes:

**PrimaryAvailabilityZone**

    The Availability Zone where ElastiCache launches the node group's primary node.

    Required: No

    Type: String

**ReplicaAvailabilityZones**

    A list of Availability Zones where ElastiCache launches the read replicas. The number of Availability Zones must match the value of the ReplicaCount property or, if you don't specify the ReplicaCount property, the replication group's ReplicasPerNodeGroup property.

    Required: No

    Type: List of String values

(see: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticache-replicationgroup-nodegroupconfiguration.html)

It would be useful for `aws_elasticache_replication_group` resource to provide the same level of control.

### LINKED ISSUE #5510: aws_elasticache_replication_group error when restoring redis cluster from snapshot - Slots must be provided when restoring from snapshot ARNs with cluster mode enabled
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7
+ provider.aws v1.31.0
+ provider.chef v0.1.0
+ provider.external v1.0.0
+ provider.null v1.0.0
+ provider.template v1.0.

### Affected Resource(s)

aws_elasticache_replication_group

### Terraform Configuration Files

```hcl
resource "aws_elasticache_replication_group" "redis-ap-southeast-2" {
  provider = "aws.stage-ap-southeast-2"
  engine                        = "redis"
  engine_version                = "4.0.10"
  replication_group_id          = "reds"
  replication_group_description = "redis"
  node_type                     = "cache.t2.medium"
  port                          = 6379
  parameter_group_name          = "default.redis4.0.cluster.on"
  automatic_failover_enabled    = true
  auto_minor_version_upgrade    = true
  at_rest_encryption_enabled    = true
  transit_encryption_enabled    = false

  subnet_group_name = "${aws_elasticache_subnet_group.redis-ap-southeast-2.name}"

  security_group_ids = [
      "${aws_security_group.redis-ap-southeast-2.id}"
  ]

  snapshot_arns = [
    "arn:aws:s3:::temp-redis-ap-southeast-2/0.rdb",
    "arn:aws:s3:::temp-redis-ap-southeast-2/1.rdb",
    "arn:aws:s3:::temp-redis-ap-southeast-2/2.rdb"
  ]

  maintenance_window = "sun:05:00-sun:09:00"
  snapshot_window = "05:00-09:00"

  cluster_mode {
    replicas_per_node_group     = 1
    num_node_groups             = 3
  }
}
```

### Expected Behavior

Created redis cluster from snapshot

### Actual Behavior

```
Error: Error applying plan:

1 error(s) occurred:

* aws_elasticache_replication_group.redis-ap-southeast-2: 1 error(s) occurred:
* aws_elasticache_replication_group.redis-ap-southeast-2: Error creating Elasticache Replication Group: InvalidParameterCombination: Slots must be provided when restoring from snapshot ARNs with cluster mode enabled
	status code: 400, request id: 1177d4c9-9d15-11e8-b12c-6347cdd5feee
```

### Steps to Reproduce

1. `terraform apply`

### LINKED ISSUE #31816: [Bug]: Blocks of type "node_group_configuration" are not expected here
### Terraform Core Version

0.14.11

### AWS Provider Version

4.18.0

### Affected Resource(s)

aws_elasticache_replication_group

### Expected Behavior

Should create a Redis cluster with cluster mode enabled using snapshot ARN

### Actual Behavior

```
Blocks of type "node_group_configuration" are not expected here
```

### Relevant Error/Panic Output Snippet

_No response_

### Terraform Configuration Files
Earlier was getting error:

```shell
Error: error creating ElastiCache Replication Group (abc-app-redis): InvalidParameterCombination: Slots must be provided when restoring from snapshot ARNs with cluster mode enabled
```

TO fix this added `node_group_configuration` but then getting `Blocks of type "node_group_configuration" are not expected here`

`main.tf:`

```terraform
resource "aws_elasticache_replication_group" "app_redis_cluster_yes" {
  count                      = local.cluster_mode_yes ? 1 : 0
  replication_group_id       = "${local.prefix}-app-redis"
  description                = "${local.prefix}_app_redis"
  engine                     = "redis"
  node_type                  = local.app_node_type
  parameter_group_name       = aws_elasticache_parameter_group.app_redis_pg_on[0].name
  automatic_failover_enabled = true
  security_group_ids         = [aws_security_group.app_redis_sg.id]
  subnet_group_name          = aws_elasticache_subnet_group.app_redis_subnet.name
  engine_version             = local.app_redis_version
  port                       = 6379
  snapshot_window            = local.app_snapshot_window
  snapshot_retention_limit   = local.app_snapshot_retention
  snapshot_arns              = [local.snapshot_restore]
  transit_encryption_enabled = true
  kms_key_id                 = local.app_kms_key
  at_rest_encryption_enabled = true
  tags = merge(local.default_tags,
    { Name = "${local.prefix}_app_redis" }
  )
  node_group_configuration {
    slots = [ "0-5461", "5462-10922", "10923-16383" ]
  }
  cluster_mode {
    replicas_per_node_group = local.app_replicas_per_node_group
    num_node_groups            = local.app_node_group_num
  }
}
```

### Steps to Reproduce

run the terraform to reproduce

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

Taking reference from :

[https://registry.terraform.io/providers/tfproviders/aws/latest/docs/resources/elasticache_replication_group?pollNotifications=true#creating-replication-group-from-previous-snapshots](url)

### Would you like to implement a fix?

None

### LINKED ISSUE #32962: [Bug]: aws_elasticache_replication_group: unable to launch from snapshot due to slots error
### Terraform Core Version

1.5.4

### AWS Provider Version

4.67.0

### Affected Resource(s)

aws_elasticache_replication_group

### Expected Behavior

Launching redis cluster from snapshot_arns requires slots but there is no parameter which we can fill for the slots

### Actual Behavior

I was not able to launch cluster from the snapshot for cluster mode enabled as it is asking for slots . not able to add slots(of shard) as a parameter even in the terraform

### Relevant Error/Panic Output Snippet

```shell
│ Error: creating ElastiCache Replication Group (***_******): InvalidParameterCombination: Slots must be provided when restoring from snapshot ARNs with cluster mode enabled
```

### Terraform Configuration Files

```terraform
resource "aws_elasticache_replication_group" "redis_replication_group" {
  description                = var.replication_group_id
  replication_group_id       = var.replication_group_id
  node_type                  = var.instance_type
  num_cache_clusters         = var.cluster_mode_enabled ? null : var.cluster_size
  engine                     = "redis"
  parameter_group_name       = var.use_existing_parameter_group ? var.parameter_group_name : module.aws_elasticache_parameter_group.redis_parameter_group_name[0]
  subnet_group_name          = var.subnet_group_name
  port                       = 6379
  automatic_failover_enabled = var.cluster_mode_enabled ? true : var.automatic_failover_enabled
  multi_az_enabled           = var.multi_az_enabled
  security_group_ids         = var.use_existing_security_group ? var.security_group_ids : module.redis_security_group.security_group_id
  num_node_groups            = var.cluster_mode_enabled ? var.cluster_mode_num_node_groups : null
  replicas_per_node_group    = var.cluster_mode_enabled ? var.cluster_mode_replicas_per_node_group : null
  at_rest_encryption_enabled = var.at_rest_encryption_enabled
  engine_version             = var.engine_version
  notification_topic_arn     = var.sns_arn
  snapshot_name              = var.snapshot_name
  snapshot_arns              = var.snapshot_arns
  snapshot_window            = var.snapshot_window
  snapshot_retention_limit   = var.snapshot_retention_limit
  final_snapshot_identifier  = "${var.replication_group_id}${var.final_snapshot_identifier}"
  apply_immediately          = var.apply_immediately
  data_tiering_enabled       = var.data_tiering_enabled
  auto_minor_version_upgrade = var.auto_minor_version_upgrade
  maintenance_window         = var.maintenance_window
  


  dynamic "log_delivery_configuration" {
    for_each = var.slow_log_enabled ? [1] : []
    content {
      log_type         = "slow-log"
      destination      = module.redis_log_groups.slow_log_group_name
      destination_type = "cloudwatch-logs"
      log_format       = "json"
    }
  }

  dynamic "log_delivery_configuration" {
    for_each = var.engine_log_enabled ? [1] : []
    content {
      log_type         = "engine-log"
      destination      = module.redis_log_groups.engine_log_group_name
      destination_type = "cloudwatch-logs"
      log_format       = "json"
    }
  }
  tags       = local.tags
}


snapshot_arns                        = ["arn:aws:s3:::xxxxxxxxxx.rdb"]
```

### Steps to Reproduce

Get the backup of any cluster mode enabled redis of any shard and copy that snapshot to S3 .so you will get the rdb file then try to launch the cluster using the same rdb file

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

https://github.com/hashicorp/terraform-provider-aws/issues/5577
https://github.com/hashicorp/terraform-provider-aws/issues/5510

### Would you like to implement a fix?

None

### LINKED ISSUE #37497: [Enhancement]: Allow to set preferred_cache_cluster_azs for ElastiCache Redis Сluster
### Description

For now, on the AWS web interface, users can choose which available zones they prefer for primary and replica Redis Cluster nodes.
But you can't choose preferred available zones when you create an ElastiCache Redis Cluster as code using Terraform.
As a result, one of the shards is always created in a different zone than your main available zone. This leads to additional traffic transfers and a bad connection time.
Please add the ability to choose `preferred_cache_cluster_azs` for the Redis Сluster.

### Affected Resource(s) and/or Data Source(s)

_No response_

### Potential Terraform Configuration

_No response_

### References

_No response_

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by YakDriver**
## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the library.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

### Description

**Add `node_group_configuration` Support to ElastiCache Replication Groups.** This PR addresses multiple long-standing user complaints by adding comprehensive `node_group_configuration` block support to both the `aws_elasticache_replication_group` resource and data source.

### Key Issues Resolved:

#5118 & #37497 - Availability Zone Control: Users can now specify exact placement of primary and replica nodes across availability zones for cluster mode enabled Redis, eliminating random AZ assignment and reducing cross-AZ traffic costs.

#31816 & #5510 & #32962 - Snapshot Restoration: Enables restoration from snapshots with cluster mode enabled by allowing users to specify required slot ranges and node group configurations that AWS API demands.

### Changes Made:

Resource Enhancement (`internal/service/elasticache/replication_group.go`):

* Added complete `node_group_configuration` schema block with 7 configurable fields
* Implemented intelligent `CustomizeDiff` logic to only force recreation when truly necessary
* Added expand/flatten functions for proper AWS API integration
* Made block computed to handle AWS-populated values without causing diffs

Data Source Addition (`internal/service/elasticache/replication_group_data_source.go`):

* Added read-only `node_group_configuration` attribute for infrastructure discovery
* Enables users to reference existing cluster configurations

Comprehensive Testing (`internal/service/elasticache/replication_group_test.go`):

* Added tests for basic node group configuration
* Added tests for availability zone specification
* Includes import state verification

Documentation Updates:

* Resource documentation with usage examples and field descriptions
* Data source documentation with attribute details

### Technical Highlights:

* **Smart ForceNew Logic**: Only recreates resources when AWS API requires it, not for computed-only changes
* **TypeSet Implementation**: Handles AWS API ordering inconsistencies automatically
* **Import Support**: Full state import/export compatibility
* **Backward Compatibility**: Existing configurations continue working unchanged

This implementation finally provides the granular control over Redis cluster topology that users have requested for years, while maintaining full backward compatibility.

### Relations

Closes #5118
Closes #31816
Closes #5510
Closes #32985
Closes #32962
Closes #37497 

### Output from Acceptance Testing

```console
% make t T=TestAccElastiCacheReplicationGroup K=elasticache P=10               
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 f-elasticache-prefer-cache-cluster 🌿...
TF_ACC=1 go1.24.8 test ./internal/service/elasticache/... -v -count 1 -parallel 10 -run='TestAccElastiCacheReplicationGroup'  -timeout 360m -vet=off
2025/10/30 14:58:11 Creating Terraform AWS Provider (SDKv2-style)...
2025/10/30 14:58:11 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccElastiCacheReplicationGroupDataSource_basic
=== PAUSE TestAccElastiCacheReplicationGroupDataSource_basic
=== RUN   TestAccElastiCacheReplicationGroupDataSource_clusterMode
=== PAUSE TestAccElastiCacheReplicationGroupDataSource_clusterMode
=== RUN   TestAccElastiCacheReplicationGroupDataSource_multiAZ
=== PAUSE TestAccElastiCacheReplicationGroupDataSource_multiAZ
=== RUN   TestAccElastiCacheReplicationGroupDataSource_Engine_Redis_LogDeliveryConfigurations
=== PAUSE TestAccElastiCacheReplicationGroupDataSource_Engine_Redis_LogDeliveryConfigurations
=== RUN   TestAccElastiCacheReplicationGroup_Redis_basic
=== PAUSE TestAccElastiCacheReplicationGroup_Redis_basic
=== RUN   TestAccElastiCacheReplicationGroup_Redis_basic_v5
=== PAUSE TestAccElastiCacheReplicationGroup_Redis_basic_v5
=== RUN   TestAccElastiCacheReplicationGroup_Valkey_basic
=== PAUSE TestAccElastiCacheReplicationGroup_Valkey_basic
=== RUN   TestAccElastiCacheReplicationGroup_uppercase
=== PAUSE TestAccElastiCacheReplicationGroup_uppercase
=== RUN   TestAccElastiCacheReplicationGroup_Redis_EngineVersion_v7
=== PAUSE TestAccElastiCacheReplicationGroup_Redis_EngineVersion_v7
=== RUN   TestAccElastiCacheReplicationGroup_OutOfBandUpgrade
=== PAUSE TestAccElastiCacheReplicationGroup_OutOfBandUpgrade
=== RUN   TestAccElastiCacheReplicationGroup_EngineVersion_update
=== PAUSE TestAccElastiCacheReplicationGroup_EngineVersion_update
=== RUN   TestAccElastiCacheReplicationGroup_EngineVersion_6xToRealVersion
=== PAUSE TestAccElastiCacheReplicationGroup_EngineVersion_6xToRealVersion
=== RUN   TestAccElastiCacheReplicationGroup_Engine_RedisToValkey
=== PAUSE TestAccElastiCacheReplicationGroup_Engine_RedisToValkey
=== RUN   TestAccElastiCacheReplicationGroup_disappears
=== PAUSE TestAccElastiCacheReplicationGroup_disappears
=== RUN   TestAccElastiCacheReplicationGroup_updateDescription
=== PAUSE TestAccElastiCacheReplicationGroup_updateDescription
=== RUN   TestAccElastiCacheReplicationGroup_updateMaintenanceWindow
=== PAUSE TestAccElastiCacheReplicationGroup_updateMaintenanceWindow
=== RUN   TestAccElastiCacheReplicationGroup_updateUserGroups
=== PAUSE TestAccElastiCacheReplicationGroup_updateUserGroups
=== RUN   TestAccElastiCacheReplicationGroup_updateNodeSize
=== PAUSE TestAccElastiCacheReplicationGroup_updateNodeSize
=== RUN   TestAccElastiCacheReplicationGroup_updateParameterGroup
=== PAUSE TestAccElastiCacheReplicationGroup_updateParameterGroup
=== RUN   TestAccElastiCacheReplicationGroup_authToken
=== PAUSE TestAccElastiCacheReplicationGroup_authToken
=== RUN   TestAccElastiCacheReplicationGroup_upgrade_6_0_0
=== PAUSE TestAccElastiCacheReplicationGroup_upgrade_6_0_0
=== RUN   TestAccElastiCacheReplicationGroup_upgrade_5_27_0
=== PAUSE TestAccElastiCacheReplicationGroup_upgrade_5_27_0
=== RUN   TestAccElastiCacheReplicationGroup_upgrade_4_68_0
=== PAUSE TestAccElastiCacheReplicationGroup_upgrade_4_68_0
=== RUN   TestAccElastiCacheReplicationGroup_vpc
=== PAUSE TestAccElastiCacheReplicationGroup_vpc
=== RUN   TestAccElastiCacheReplicationGroup_multiAzNotInVPC
=== PAUSE TestAccElastiCacheReplicationGroup_multiAzNotInVPC
=== RUN   TestAccElastiCacheReplicationGroup_multiAzNotInVPC_repeated
=== PAUSE TestAccElastiCacheReplicationGroup_multiAzNotInVPC_repeated
=== RUN   TestAccElastiCacheReplicationGroup_multiAzInVPC
=== PAUSE TestAccElastiCacheReplicationGroup_multiAzInVPC
=== RUN   TestAccElastiCacheReplicationGroup_deprecatedAvailabilityZones_multiAzInVPC
=== PAUSE TestAccElastiCacheReplicationGroup_deprecatedAvailabilityZones_multiAzInVPC
=== RUN   TestAccElastiCacheReplicationGroup_ValidationMultiAz_noAutomaticFailover
=== PAUSE TestAccElastiCacheReplicationGroup_ValidationMultiAz_noAutomaticFailover
=== RUN   TestAccElastiCacheReplicationGroup_ipDiscovery
=== PAUSE TestAccElastiCacheReplicationGroup_ipDiscovery
=== RUN   TestAccElastiCacheReplicationGroup_networkType
=== PAUSE TestAccElastiCacheReplicationGroup_networkType
=== RUN   TestAccElastiCacheReplicationGroup_ClusterMode_basic
=== PAUSE TestAccElastiCacheReplicationGroup_ClusterMode_basic
=== RUN   TestAccElastiCacheReplicationGroup_ClusterMode_nonClusteredParameterGroup
=== PAUSE TestAccElastiCacheReplicationGroup_ClusterMode_nonClusteredParameterGroup
=== RUN   TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroups_scaleUp
=== PAUSE TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroups_scaleUp
=== RUN   TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroups_scaleDown
=== PAUSE TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroups_scaleDown
=== RUN   TestAccElastiCacheReplicationGroup_ClusterMode_updateReplicasPerNodeGroup
=== PAUSE TestAccElastiCacheReplicationGroup_ClusterMode_updateReplicasPerNodeGroup
=== RUN   TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroupsAndReplicasPerNodeGroup_scaleUp
=== PAUSE TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroupsAndReplicasPerNodeGroup_scaleUp
=== RUN   TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroupsAndReplicasPerNodeGroup_scaleDown
=== PAUSE TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroupsAndReplicasPerNodeGroup_scaleDown
=== RUN   TestAccElastiCacheReplicationGroup_ClusterMode_singleNode
=== PAUSE TestAccElastiCacheReplicationGroup_ClusterMode_singleNode
=== RUN   TestAccElastiCacheReplicationGroup_ClusterMode_nodeGroupConfiguration
=== PAUSE TestAccElastiCacheReplicationGroup_ClusterMode_nodeGroupConfiguration
=== RUN   TestAccElastiCacheReplicationGroup_ClusterMode_nodeGroupConfiguration_availabilityZones
=== PAUSE TestAccElastiCacheReplicationGroup_ClusterMode_nodeGroupConfiguration_availabilityZones
=== RUN   TestAccElastiCacheReplicationGroup_ClusterMode_updateFromDisabled_Compatible_Enabled
=== PAUSE TestAccElastiCacheReplicationGroup_ClusterMode_updateFromDisabled_Compatible_Enabled
=== RUN   TestAccElastiCacheReplicationGroup_cacheClustersConflictsWithReplicasPerNodeGroup
=== PAUSE TestAccElastiCacheReplicationGroup_cacheClustersConflictsWithReplicasPerNodeGroup
=== RUN   TestAccElastiCacheReplicationGroup_clusteringAndCacheNodesCausesError
=== PAUSE TestAccElastiCacheReplicationGroup_clusteringAndCacheNodesCausesError
=== RUN   TestAccElastiCacheReplicationGroup_enableSnapshotting
=== PAUSE TestAccElastiCacheReplicationGroup_enableSnapshotting
=== RUN   TestAccElastiCacheReplicationGroup_transitEncryptionWithAuthToken
=== PAUSE TestAccElastiCacheReplicationGroup_transitEncryptionWithAuthToken
=== RUN   TestAccElastiCacheReplicationGroup_transitEncryption5x
=== PAUSE TestAccElastiCacheReplicationGroup_transitEncryption5x
=== RUN   TestAccElastiCacheReplicationGroup_transitEncryption7x_basic
=== PAUSE TestAccElastiCacheReplicationGroup_transitEncryption7x_basic
=== RUN   TestAccElastiCacheReplicationGroup_transitEncryption7x_Enable
=== PAUSE TestAccElastiCacheReplicationGroup_transitEncryption7x_Enable
=== RUN   TestAccElastiCacheReplicationGroup_transitEncryption7x_Disable
=== PAUSE TestAccElastiCacheReplicationGroup_transitEncryption7x_Disable
=== RUN   TestAccElastiCacheReplicationGroup_Redis_enableAtRestEncryption
=== PAUSE TestAccElastiCacheReplicationGroup_Redis_enableAtRestEncryption
=== RUN   TestAccElastiCacheReplicationGroup_Valkey_disableAtRestEncryption
=== PAUSE TestAccElastiCacheReplicationGroup_Valkey_disableAtRestEncryption
=== RUN   TestAccElastiCacheReplicationGroup_useCMKKMSKeyID
=== PAUSE TestAccElastiCacheReplicationGroup_useCMKKMSKeyID
=== RUN   TestAccElastiCacheReplicationGroup_NumberCacheClusters_basic
=== PAUSE TestAccElastiCacheReplicationGroup_NumberCacheClusters_basic
=== RUN   TestAccElastiCacheReplicationGroup_NumberCacheClusters_autoFailoverDisabled
=== PAUSE TestAccElastiCacheReplicationGroup_NumberCacheClusters_autoFailoverDisabled
=== RUN   TestAccElastiCacheReplicationGroup_NumberCacheClusters_autoFailoverEnabled
=== PAUSE TestAccElastiCacheReplicationGroup_NumberCacheClusters_autoFailoverEnabled
=== RUN   TestAccElastiCacheReplicationGroup_autoFailoverEnabled_validateNumberCacheClusters
=== PAUSE TestAccElastiCacheReplicationGroup_autoFailoverEnabled_validateNumberCacheClusters
=== RUN   TestAccElastiCacheReplicationGroup_NumberCacheClusters_multiAZEnabled
=== PAUSE TestAccElastiCacheReplicationGroup_NumberCacheClusters_multiAZEnabled
=== RUN   TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappears_noChange
=== PAUSE TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappears_noChange
=== RUN   TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappears_addMemberCluster
=== PAUSE TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappears_addMemberCluster
=== RUN   TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappearsRemoveMemberCluster_atTargetSize
=== PAUSE TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappearsRemoveMemberCluster_atTargetSize
=== RUN   TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappearsRemoveMemberCluster_scaleDown
=== PAUSE TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappearsRemoveMemberCluster_scaleDown
=== RUN   TestAccElastiCacheReplicationGroup_tags
=== PAUSE TestAccElastiCacheReplicationGroup_tags
=== RUN   TestAccElastiCacheReplicationGroup_TagWithOtherModification_version
=== PAUSE TestAccElastiCacheReplicationGroup_TagWithOtherModification_version
=== RUN   TestAccElastiCacheReplicationGroup_TagWithOtherModification_numCacheClusters
=== PAUSE TestAccElastiCacheReplicationGroup_TagWithOtherModification_numCacheClusters
=== RUN   TestAccElastiCacheReplicationGroup_finalSnapshot
=== PAUSE TestAccElastiCacheReplicationGroup_finalSnapshot
=== RUN   TestAccElastiCacheReplicationGroup_autoMinorVersionUpgrade
=== PAUSE TestAccElastiCacheReplicationGroup_autoMinorVersionUpgrade
=== RUN   TestAccElastiCacheReplicationGroup_Validation_noNodeType
=== PAUSE TestAccElastiCacheReplicationGroup_Validation_noNodeType
=== RUN   TestAccElastiCacheReplicationGroup_Validation_globalReplicationGroupIdAndNodeType
=== PAUSE TestAccElastiCacheReplicationGroup_Validation_globalReplicationGroupIdAndNodeType
=== RUN   TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_basic
=== PAUSE TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_basic
=== RUN   TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_full
=== PAUSE TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_full
=== RUN   TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_disappears
=== PAUSE TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_disappears
=== RUN   TestAccElastiCacheReplicationGroup_GlobalReplicationGroupIDClusterMode_basic
=== PAUSE TestAccElastiCacheReplicationGroup_GlobalReplicationGroupIDClusterMode_basic
=== RUN   TestAccElastiCacheReplicationGroup_GlobalReplicationGroupIDClusterModeValidation_numNodeGroupsOnSecondary
=== PAUSE TestAccElastiCacheReplicationGroup_GlobalReplicationGroupIDClusterModeValidation_numNodeGroupsOnSecondary
=== RUN   TestAccElastiCacheReplicationGroup_dataTiering
=== PAUSE TestAccElastiCacheReplicationGroup_dataTiering
=== RUN   TestAccElastiCacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_ClusterMode_Disabled
=== PAUSE TestAccElastiCacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_ClusterMode_Disabled
=== RUN   TestAccElastiCacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_ClusterMode_Enabled
=== PAUSE TestAccElastiCacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_ClusterMode_Enabled
=== CONT  TestAccElastiCacheReplicationGroupDataSource_basic
=== CONT  TestAccElastiCacheReplicationGroup_enableSnapshotting
=== CONT  TestAccElastiCacheReplicationGroup_vpc
=== CONT  TestAccElastiCacheReplicationGroup_transitEncryptionWithAuthToken
=== CONT  TestAccElastiCacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_ClusterMode_Disabled
=== CONT  TestAccElastiCacheReplicationGroup_dataTiering
=== CONT  TestAccElastiCacheReplicationGroup_GlobalReplicationGroupIDClusterModeValidation_numNodeGroupsOnSecondary
=== CONT  TestAccElastiCacheReplicationGroup_GlobalReplicationGroupIDClusterMode_basic
=== CONT  TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_disappears
=== CONT  TestAccElastiCacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_ClusterMode_Enabled
--- PASS: TestAccElastiCacheReplicationGroup_dataTiering (618.81s)
=== CONT  TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_full
--- PASS: TestAccElastiCacheReplicationGroup_transitEncryptionWithAuthToken (689.44s)
=== CONT  TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_basic
--- PASS: TestAccElastiCacheReplicationGroup_enableSnapshotting (729.18s)
=== CONT  TestAccElastiCacheReplicationGroup_Validation_globalReplicationGroupIdAndNodeType
--- PASS: TestAccElastiCacheReplicationGroup_vpc (750.38s)
=== CONT  TestAccElastiCacheReplicationGroup_Validation_noNodeType
--- PASS: TestAccElastiCacheReplicationGroup_Validation_noNodeType (5.32s)
=== CONT  TestAccElastiCacheReplicationGroup_autoMinorVersionUpgrade
--- PASS: TestAccElastiCacheReplicationGroupDataSource_basic (810.51s)
=== CONT  TestAccElastiCacheReplicationGroup_finalSnapshot
--- PASS: TestAccElastiCacheReplicationGroup_GlobalReplicationGroupIDClusterModeValidation_numNodeGroupsOnSecondary (1118.65s)
=== CONT  TestAccElastiCacheReplicationGroup_TagWithOtherModification_numCacheClusters
--- PASS: TestAccElastiCacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_ClusterMode_Enabled (1124.63s)
=== CONT  TestAccElastiCacheReplicationGroup_TagWithOtherModification_version
--- PASS: TestAccElastiCacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_ClusterMode_Disabled (1236.82s)
=== CONT  TestAccElastiCacheReplicationGroup_tags
--- PASS: TestAccElastiCacheReplicationGroup_autoMinorVersionUpgrade (737.61s)
=== CONT  TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappearsRemoveMemberCluster_scaleDown
--- PASS: TestAccElastiCacheReplicationGroup_finalSnapshot (939.40s)
=== CONT  TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappearsRemoveMemberCluster_atTargetSize
--- PASS: TestAccElastiCacheReplicationGroup_Validation_globalReplicationGroupIdAndNodeType (1062.72s)
=== CONT  TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappears_addMemberCluster
--- PASS: TestAccElastiCacheReplicationGroup_tags (825.09s)
=== CONT  TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappears_noChange
--- PASS: TestAccElastiCacheReplicationGroup_TagWithOtherModification_numCacheClusters (1169.44s)
=== CONT  TestAccElastiCacheReplicationGroup_NumberCacheClusters_multiAZEnabled
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappearsRemoveMemberCluster_atTargetSize (1024.44s)
=== CONT  TestAccElastiCacheReplicationGroup_autoFailoverEnabled_validateNumberCacheClusters
--- PASS: TestAccElastiCacheReplicationGroup_autoFailoverEnabled_validateNumberCacheClusters (1.88s)
=== CONT  TestAccElastiCacheReplicationGroup_Redis_enableAtRestEncryption
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappearsRemoveMemberCluster_scaleDown (1418.82s)
=== CONT  TestAccElastiCacheReplicationGroup_transitEncryption7x_Disable
--- PASS: TestAccElastiCacheReplicationGroup_TagWithOtherModification_version (1851.51s)
=== CONT  TestAccElastiCacheReplicationGroup_transitEncryption7x_Enable
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappears_addMemberCluster (1271.84s)
=== CONT  TestAccElastiCacheReplicationGroup_transitEncryption7x_basic
--- PASS: TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_disappears (3252.46s)
=== CONT  TestAccElastiCacheReplicationGroup_transitEncryption5x
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappears_noChange (1253.39s)
=== CONT  TestAccElastiCacheReplicationGroup_Engine_RedisToValkey
--- PASS: TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_basic (2697.17s)
=== CONT  TestAccElastiCacheReplicationGroup_upgrade_4_68_0
--- PASS: TestAccElastiCacheReplicationGroup_Redis_enableAtRestEncryption (656.03s)
=== CONT  TestAccElastiCacheReplicationGroup_upgrade_5_27_0
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClusters_multiAZEnabled (1351.99s)
=== CONT  TestAccElastiCacheReplicationGroup_upgrade_6_0_0
--- PASS: TestAccElastiCacheReplicationGroup_transitEncryption7x_basic (636.71s)
=== CONT  TestAccElastiCacheReplicationGroup_authToken
--- PASS: TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_full (3233.83s)
=== CONT  TestAccElastiCacheReplicationGroup_updateParameterGroup
--- PASS: TestAccElastiCacheReplicationGroup_upgrade_4_68_0 (812.98s)
=== CONT  TestAccElastiCacheReplicationGroup_updateNodeSize
--- PASS: TestAccElastiCacheReplicationGroup_upgrade_5_27_0 (810.75s)
=== CONT  TestAccElastiCacheReplicationGroup_updateUserGroups
--- PASS: TestAccElastiCacheReplicationGroup_GlobalReplicationGroupIDClusterMode_basic (4347.30s)
=== CONT  TestAccElastiCacheReplicationGroup_updateMaintenanceWindow
--- PASS: TestAccElastiCacheReplicationGroup_upgrade_6_0_0 (727.24s)
=== CONT  TestAccElastiCacheReplicationGroup_updateDescription
--- PASS: TestAccElastiCacheReplicationGroup_transitEncryption5x (1203.86s)
=== CONT  TestAccElastiCacheReplicationGroup_disappears
--- PASS: TestAccElastiCacheReplicationGroup_updateParameterGroup (814.60s)
=== CONT  TestAccElastiCacheReplicationGroup_NumberCacheClusters_autoFailoverDisabled
--- PASS: TestAccElastiCacheReplicationGroup_transitEncryption7x_Disable (1888.58s)
=== CONT  TestAccElastiCacheReplicationGroup_NumberCacheClusters_autoFailoverEnabled
--- PASS: TestAccElastiCacheReplicationGroup_Engine_RedisToValkey (1544.03s)
=== CONT  TestAccElastiCacheReplicationGroup_NumberCacheClusters_basic
--- PASS: TestAccElastiCacheReplicationGroup_transitEncryption7x_Enable (1887.77s)
=== CONT  TestAccElastiCacheReplicationGroup_useCMKKMSKeyID
--- PASS: TestAccElastiCacheReplicationGroup_authToken (1353.08s)
=== CONT  TestAccElastiCacheReplicationGroup_Valkey_basic
--- PASS: TestAccElastiCacheReplicationGroup_updateMaintenanceWindow (737.95s)
=== CONT  TestAccElastiCacheReplicationGroup_EngineVersion_6xToRealVersion
--- PASS: TestAccElastiCacheReplicationGroup_updateDescription (738.67s)
=== CONT  TestAccElastiCacheReplicationGroup_Valkey_disableAtRestEncryption
--- PASS: TestAccElastiCacheReplicationGroup_updateUserGroups (866.85s)
=== CONT  TestAccElastiCacheReplicationGroup_EngineVersion_update
--- PASS: TestAccElastiCacheReplicationGroup_disappears (888.71s)
=== CONT  TestAccElastiCacheReplicationGroup_OutOfBandUpgrade
--- PASS: TestAccElastiCacheReplicationGroup_useCMKKMSKeyID (664.26s)
=== CONT  TestAccElastiCacheReplicationGroup_Redis_EngineVersion_v7
--- PASS: TestAccElastiCacheReplicationGroup_Valkey_basic (779.98s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroups_scaleDown
--- PASS: TestAccElastiCacheReplicationGroup_updateNodeSize (1737.59s)
=== CONT  TestAccElastiCacheReplicationGroup_uppercase
--- PASS: TestAccElastiCacheReplicationGroup_Valkey_disableAtRestEncryption (850.26s)
=== CONT  TestAccElastiCacheReplicationGroup_clusteringAndCacheNodesCausesError
--- PASS: TestAccElastiCacheReplicationGroup_clusteringAndCacheNodesCausesError (0.73s)
=== CONT  TestAccElastiCacheReplicationGroup_ipDiscovery
--- PASS: TestAccElastiCacheReplicationGroup_EngineVersion_6xToRealVersion (961.80s)
=== CONT  TestAccElastiCacheReplicationGroup_cacheClustersConflictsWithReplicasPerNodeGroup
--- PASS: TestAccElastiCacheReplicationGroup_cacheClustersConflictsWithReplicasPerNodeGroup (0.70s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroups_scaleUp
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClusters_autoFailoverEnabled (1352.77s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterMode_updateFromDisabled_Compatible_Enabled
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClusters_basic (1329.84s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterMode_nonClusteredParameterGroup
--- PASS: TestAccElastiCacheReplicationGroup_Redis_EngineVersion_v7 (728.42s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterMode_nodeGroupConfiguration_availabilityZones
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClusters_autoFailoverDisabled (1627.45s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterMode_basic
--- PASS: TestAccElastiCacheReplicationGroup_uppercase (604.79s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterMode_nodeGroupConfiguration
--- PASS: TestAccElastiCacheReplicationGroup_ClusterMode_nonClusteredParameterGroup (679.02s)
=== CONT  TestAccElastiCacheReplicationGroup_networkType
--- PASS: TestAccElastiCacheReplicationGroup_ipDiscovery (912.87s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterMode_singleNode
--- PASS: TestAccElastiCacheReplicationGroup_OutOfBandUpgrade (1723.18s)
=== CONT  TestAccElastiCacheReplicationGroupDataSource_Engine_Redis_LogDeliveryConfigurations
--- PASS: TestAccElastiCacheReplicationGroup_ClusterMode_nodeGroupConfiguration_availabilityZones (894.34s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroupsAndReplicasPerNodeGroup_scaleDown
--- PASS: TestAccElastiCacheReplicationGroup_ClusterMode_nodeGroupConfiguration (860.50s)
=== CONT  TestAccElastiCacheReplicationGroup_Redis_basic_v5
--- PASS: TestAccElastiCacheReplicationGroup_ClusterMode_basic (1109.20s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroupsAndReplicasPerNodeGroup_scaleUp
--- PASS: TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroups_scaleDown (1693.89s)
=== CONT  TestAccElastiCacheReplicationGroup_Redis_basic
--- PASS: TestAccElastiCacheReplicationGroup_ClusterMode_singleNode (657.82s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterMode_updateReplicasPerNodeGroup
--- PASS: TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroups_scaleUp (1563.24s)
=== CONT  TestAccElastiCacheReplicationGroupDataSource_clusterMode
--- PASS: TestAccElastiCacheReplicationGroup_networkType (912.25s)
=== CONT  TestAccElastiCacheReplicationGroupDataSource_multiAZ
--- PASS: TestAccElastiCacheReplicationGroupDataSource_Engine_Redis_LogDeliveryConfigurations (763.60s)
=== CONT  TestAccElastiCacheReplicationGroup_ValidationMultiAz_noAutomaticFailover
--- PASS: TestAccElastiCacheReplicationGroup_ValidationMultiAz_noAutomaticFailover (1.23s)
=== CONT  TestAccElastiCacheReplicationGroup_multiAzNotInVPC
--- PASS: TestAccElastiCacheReplicationGroup_Redis_basic_v5 (656.65s)
=== CONT  TestAccElastiCacheReplicationGroup_multiAzInVPC
--- PASS: TestAccElastiCacheReplicationGroup_Redis_basic (728.53s)
=== CONT  TestAccElastiCacheReplicationGroup_deprecatedAvailabilityZones_multiAzInVPC
--- PASS: TestAccElastiCacheReplicationGroupDataSource_clusterMode (950.19s)
=== CONT  TestAccElastiCacheReplicationGroup_multiAzNotInVPC_repeated
--- PASS: TestAccElastiCacheReplicationGroupDataSource_multiAZ (796.69s)
--- PASS: TestAccElastiCacheReplicationGroup_ClusterMode_updateFromDisabled_Compatible_Enabled (2428.07s)
--- PASS: TestAccElastiCacheReplicationGroup_multiAzNotInVPC (821.04s)
--- PASS: TestAccElastiCacheReplicationGroup_multiAzInVPC (799.53s)
--- PASS: TestAccElastiCacheReplicationGroup_ClusterMode_updateReplicasPerNodeGroup (1518.01s)
--- PASS: TestAccElastiCacheReplicationGroup_deprecatedAvailabilityZones_multiAzInVPC (822.02s)
--- PASS: TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroupsAndReplicasPerNodeGroup_scaleUp (1793.42s)
--- PASS: TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroupsAndReplicasPerNodeGroup_scaleDown (2110.40s)
--- PASS: TestAccElastiCacheReplicationGroup_multiAzNotInVPC_repeated (803.02s)
--- PASS: TestAccElastiCacheReplicationGroup_EngineVersion_update (5510.10s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elasticache	10625.414s
```

### CODE REVIEW

File: internal/service/elasticache/replication_group_test.go [hunk 1]
```diff
@@ -3579,6 +3673,60 @@ func testAccCheckResourceTags(resourceName string, kvs []kvp) []resource.TestChe
 	return checks
 }
 
+func resourceReplicationGroupDisableAutomaticFailover(ctx context.Context, conn *elasticache.Client, replicationGroupID string, timeout time.Duration) error {
```
Comment (YakDriver) [inline internal/service/elasticache/replication_group_test.go:3676]: All these helper functions were moved without change from the bottom of the test file to the proper helper location, before configs.

**Comment by YakDriver** [comment]
Only 2.95 hours to run the whole replication group suite of tests (including the data source), and there wasn't even a flaky test!
