### PR TITLE
Fix AccessDeniedError listing tags in aws_vpclattice_service_network, aws_vpclattice_service data sources

### LINKED ISSUE #41270: [Bug]: error listing tags in aws_vpclattice_service_network data source
### Terraform Core Version

1.10.3, 1.8.2, 1.8.0

### AWS Provider Version

5.85.0

### Affected Resource(s)

- aws_vpclattice_service_network data source

### Expected Behavior

The `aws_vpclattice_service_network` data source should successfully look up the service network, even when shared across accounts with RAM.

### Actual Behavior

There is an error listing the tags on the service network.

### Relevant Error/Panic Output Snippet

```shell
Error: listing tags for VPC Lattice Service Network (arn:aws:vpc-lattice:us-east-1:************:servicenetwork/sn-*****************): operation error VPC Lattice: ListTagsForResource, https response error StatusCode: 403, RequestID: ************************************, AccessDeniedException: User: arn:aws:sts::************:assumed-role/*** is not authorized to perform: vpc-lattice:ListTagsForResource on resource: arn:aws:vpc-lattice:us-east-1:************:servicenetwork/sn-*****************
```

### Terraform Configuration Files

```tf
data "aws_vpclattice_service_network" "service_network" {
  service_network_identifier = var.service_network_id
}
```

### Steps to Reproduce

- Create a VPC Lattice Service network in AWS Account 1
- Share Service Network with AWS Account 2
- Using credentials in AWS Account 2, run a terraform plan with a `aws_vpclattice_service_network` data source pointed at the Service Network

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

- Pinning to version `5.84.0` of the AWS provider resolves this issue for us.
- We are using the `AWSRAMPermissionVpcLatticeServiceNetworkReadWrite` managed permissions when sharing the service network with other accounts. My understanding is that this is a complete list of actions able to be taken on shared Service Networks.

### References

This issue seems similar https://github.com/hashicorp/terraform-provider-aws/issues/32938 along with it's corresponding pull-request #32939

Screenshot of `AWSRAMPermissionVpcLatticeServiceNetworkReadWrite` 
Image

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by YakDriver**
### Description

Using tags interceptor does not work for these shareable resources since tags cannot be listed for another account. This skips tags when the account is not the same or Access is denied.

### Relations

Closes #41270 

### References

* Fixes regression in #41019
* Relates #32938 
* Relates #32939 

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccXXX PKG=ec2

...
```

### CODE REVIEW

File: internal/service/vpclattice/service_network_data_source.go [hunk 1]
```diff
@@ -83,19 +92,27 @@ func dataSourceServiceNetworkRead(ctx context.Context, d *schema.ResourceData, m
...
 	if err != nil {
 		return sdkdiag.AppendFromErr(diags, err)
 	}
 
-	if parsedARN.AccountID == meta.(*conns.AWSClient).AccountID(ctx) {
-		tags, err := listTags(ctx, conn, serviceNetworkARN)
+	if parsedARN.AccountID == accountID {
+		tags, err := listTags(ctx, conn, resARN)
+
+		if err != nil && errs.Contains(err, ErrCodeAccessDeniedException) {
```
Comment (jar-b) [inline internal/service/vpclattice/service_network_data_source.go:110]: Can be simplified slightly.

```suggestion
		if errs.Contains(err, ErrCodeAccessDeniedException) {
```

**Review by jar-b — APPROVED** [review]
LGTM 🎉 

```console
% make testacc PKG=vpclattice TESTS="TestAccVPCLatticeServiceDataSource_|TestAccVPCLatticeServiceNetworkDataSource_"
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.5 test ./internal/service/vpclattice/... -v -count 1 -parallel 20 -run='TestAccVPCLatticeServiceDataSource_|TestAccVPCLatticeServiceNetworkDataSource_'  -timeout 360m -vet=off
2025/02/10 09:18:34 Initializing Terraform AWS Provider...
=== RUN   TestAccVPCLatticeServiceDataSource_basic
=== PAUSE TestAccVPCLatticeServiceDataSource_basic
=== RUN   TestAccVPCLatticeServiceDataSource_byName
=== PAUSE TestAccVPCLatticeServiceDataSource_byName
=== RUN   TestAccVPCLatticeServiceDataSource_shared
=== PAUSE TestAccVPCLatticeServiceDataSource_shared
=== RUN   TestAccVPCLatticeServiceNetworkDataSource_basic
=== PAUSE TestAccVPCLatticeServiceNetworkDataSource_basic
=== RUN   TestAccVPCLatticeServiceNetworkDataSource_shared
=== PAUSE TestAccVPCLatticeServiceNetworkDataSource_shared
=== CONT  TestAccVPCLatticeServiceDataSource_basic
=== CONT  TestAccVPCLatticeServiceNetworkDataSource_basic
=== CONT  TestAccVPCLatticeServiceDataSource_shared
=== CONT  TestAccVPCLatticeServiceDataSource_byName
=== CONT  TestAccVPCLatticeServiceNetworkDataSource_shared
=== NAME  TestAccVPCLatticeServiceDataSource_shared
    service_data_source_test.go:90: skipping test because at least one environment variable of [AWS_ALTERNATE_PROFILE AWS_ALTERNATE_ACCESS_KEY_ID] must be set. Usage: credentials for running acceptance testing in alternate AWS account.
--- SKIP: TestAccVPCLatticeServiceDataSource_shared (0.38s)
=== NAME  TestAccVPCLatticeServiceNetworkDataSource_shared
    service_network_data_source_test.go:57: skipping test because at least one environment variable of [AWS_ALTERNATE_PROFILE AWS_ALTERNATE_ACCESS_KEY_ID] must be set. Usage: credentials for running acceptance testing in alternate AWS account.
--- SKIP: TestAccVPCLatticeServiceNetworkDataSource_shared (0.38s)
--- PASS: TestAccVPCLatticeServiceNetworkDataSource_basic (13.26s)
--- PASS: TestAccVPCLatticeServiceDataSource_basic (16.65s)
--- PASS: TestAccVPCLatticeServiceDataSource_byName (17.80s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/vpclattice 24.429s
```

**Review by jar-b — APPROVED** [review]
LGTM 🚀
