### PR TITLE
changed aws_guardduty_feature additional_configuration from list to set

### LINKED ISSUE #36400: [Bug]: `aws_guardduty_detector_feature` `additional_configuration` blocks must be in a particular order, else they force replacement on every run
### Terraform Core Version

1.7.5

### AWS Provider Version

5.41.0

### Affected Resource(s)

* aws_guardduty_detector_feature

### Expected Behavior

"No changes. Your infrastructure matches the configuration."

### Actual Behavior

Terraform wants to do the following state changes every time:

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # aws_guardduty_detector_feature.runtime_monitoring must be replaced
-/+ resource "aws_guardduty_detector_feature" "runtime_monitoring" {
      ~ id          = "<redacted>/RUNTIME_MONITORING" -> (known after apply)
        name        = "RUNTIME_MONITORING"
        # (2 unchanged attributes hidden)

      ~ additional_configuration {
          ~ name   = "EKS_ADDON_MANAGEMENT" -> "ECS_FARGATE_AGENT_MANAGEMENT" # forces replacement
            # (1 unchanged attribute hidden)
        }
      ~ additional_configuration {
          ~ name   = "ECS_FARGATE_AGENT_MANAGEMENT" -> "EKS_ADDON_MANAGEMENT" # forces replacement
            # (1 unchanged attribute hidden)
        }
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

### Relevant Error/Panic Output Snippet

_No response_

### Terraform Configuration Files

```terraform
resource "aws_guardduty_detector" "this" {
  enable = true
}

resource "aws_guardduty_detector_feature" "this" {
  for_each = toset([
    "S3_DATA_EVENTS",
    "EKS_AUDIT_LOGS",
    "EBS_MALWARE_PROTECTION",
    "RDS_LOGIN_EVENTS",
    "LAMBDA_NETWORK_LOGS"
  ])

  detector_id = aws_guardduty_detector.this.id
  name        = each.value
  status      = "ENABLED"
}

resource "aws_guardduty_detector_feature" "runtime_monitoring" {
  detector_id = aws_guardduty_detector.this.id
  name        = "RUNTIME_MONITORING"
  status      = "ENABLED"

  additional_configuration {
    name   = "ECS_FARGATE_AGENT_MANAGEMENT"
    status = "ENABLED"
  }

  additional_configuration {
    name   = "EKS_ADDON_MANAGEMENT"
    status = "ENABLED"
  }
}
```

### Steps to Reproduce

In a AWS account with GuardDuty disabled, run `terraform apply` to apply the changes. Then re-run `terraform apply`. Every invocation will see state changes.

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

Re-ordering the `additional_configuration` blocks makes the state happy:

```terraform
resource "aws_guardduty_detector_feature" "runtime_monitoring" {
  detector_id = aws_guardduty_detector.this.id
  name        = "RUNTIME_MONITORING"
  status      = "ENABLED"

  additional_configuration {
    name   = "EKS_ADDON_MANAGEMENT"
    status = "ENABLED"
  }

  additional_configuration {
    name   = "ECS_FARGATE_AGENT_MANAGEMENT"
    status = "ENABLED"
  }
}
```

This configuration, ordered "EKS_ADDON_MANAGEMENT" first and then "ECS_FARGATE_AGENT_MANAGEMENT", will be stable and say "No changes. Your infrastructure matches the configuration." on subsequent runs of `terraform apply`

### References

_No response_

### Would you like to implement a fix?

No

### LINKED ISSUE #36695: [Bug]: Plan generates changes to aws_guardduty_detector_feature when no changes were made to the terraform code
### Terraform Core Version

1.7.4

### AWS Provider Version

5.43.0

### Affected Resource(s)

* aws_guardduty_detector_feature

### Expected Behavior

When I generate terraform plan on workspace with no changes it should show that no changes are to be made.

### Actual Behavior

Terraform produces following plan to remove `EC2_AGENT_MANAGEMENT` feature:
```
# aws_guardduty_detector_feature.runtime_monitoring must be replaced
-/+ resource "aws_guardduty_detector_feature" "runtime_monitoring" {
      ~ id          = "3ac6e6760edfc732d67f0bd15c0f040c/RUNTIME_MONITORING" -> (known after apply)
        name        = "RUNTIME_MONITORING"
        # (2 unchanged attributes hidden)

      - additional_configuration { # forces replacement
          - name   = "EC2_AGENT_MANAGEMENT" -> null # forces replacement
          - status = "DISABLED" -> null
        }

        # (2 unchanged blocks hidden)
    }
```

This is current configuration I use:
```
resource "aws_guardduty_detector_feature" "runtime_monitoring" {
  detector_id = aws_guardduty_detector.main.id
  name        = "RUNTIME_MONITORING"
  status      = "ENABLED"

  additional_configuration {
    name   = "EKS_ADDON_MANAGEMENT"
    status = "DISABLED"
  }

  additional_configuration {
    name   = "ECS_FARGATE_AGENT_MANAGEMENT"
    status = "ENABLED"
  }
}
```
Adding following block to the resource causes an `EC2_AGENT_MANAGEMENT` value not supported error.
```
        additional_configuration {
          name   = "EC2_AGENT_MANAGEMENT"
          status = "DISABLED"
        }
```

### Relevant Error/Panic Output Snippet

_No response_

### Terraform Configuration Files

resource "aws_guardduty_detector" "main" {
  enable = true
}

resource "aws_guardduty_detector_feature" "runtime_monitoring" {
  detector_id = aws_guardduty_detector.main.id
  name        = "RUNTIME_MONITORING"
  status      = "ENABLED"

  additional_configuration {
    name   = "EKS_ADDON_MANAGEMENT"
    status = "DISABLED"
  }

  additional_configuration {
    name   = "ECS_FARGATE_AGENT_MANAGEMENT"
    status = "ENABLED"
  }
}

### Steps to Reproduce

Run `terraform plan`

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by icco**
## Rollback Plan

Not needed.

## Changes to Security Controls

No

### Description

This is a rebase of https://github.com/hashicorp/terraform-provider-aws/pull/36985.

Description
This changes the aws_guardduty_detector_feature additional_configuration type from a list to a set. This is so that the order of the additional configurations does not matter. Before pushing this fix, if you didn't provide the additional_configurations in the order the AWS API returns them, there would be a force replace on every terraform apply.

I added an additional acceptance test to confirm that the ordering of the additional_configurations doesn't matter and that an empty plan is returned no matter the order.

### Relations

Closes #36400
Closes #36695
Closes #36985

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccXXX PKG=ec2

...
```

### CODE REVIEW

**Review by YakDriver — DISMISSED** [review]
LGTM 🎉 

```console
--- PASS: TestAccGuardDuty_serial (102.90s)
    --- PASS: TestAccGuardDuty_serial/DetectorFeature (102.90s)
        --- PASS: TestAccGuardDuty_serial/DetectorFeature/basic (14.67s)
        --- PASS: TestAccGuardDuty_serial/DetectorFeature/additional_configuration (32.79s)
        --- PASS: TestAccGuardDuty_serial/DetectorFeature/additional_configuration_order (19.76s)
        --- PASS: TestAccGuardDuty_serial/DetectorFeature/multiple (35.67s)
```

**Comment by YakDriver** [comment]
@icco Thanks for the rebase!

@joelmccoy Thanks for your contribution!

File: internal/service/guardduty/detector_feature.go [hunk 1]
```diff
@@ -33,14 +33,12 @@ func resourceDetectorFeature() *schema.Resource {
 		Schema: map[string]*schema.Schema{
 			"additional_configuration": {
 				Optional: true,
-				ForceNew: true,
```
Comment (YakDriver) [inline internal/service/guardduty/detector_feature.go:36]: It may show in the plan, but ForceNew has no effect since Delete is NoOp.

**Comment by YakDriver** [comment]
Findings for future travelers:

1. `ForceNew` is irrelevant except it shows in plan. For `aws_guardduty_feature`, it does nothing since Delete is a no-op.
2. Updates to `additional_configuration` are not possible with or without `ForceNew` (since Delete's a no-op). Based on my testing, for example, if you start with `additional_configuration` of `EC2_AGENT_MANAGEMENT`, you can’t remove it and you can’t add `ECS_FARGATE_AGENT_MANAGEMENT` or `EKS_ADDON_MANAGEMENT` .  All you can do is change the `status` to `ENABLED` or  `DISABLED` of those `additional_configuration`s you added initially. You don't get update errors but they don't take effect and cause perpetual diffs.
3. Best practice would be to add all the `additional_configuration` blocks, setting those you don't need to `DISABLED`. Then they can be updated. 
4. Recreating the detector seems to be the only way to reset so that updates to `additional_configuration` take effect.

**Review by johnsonaj — APPROVED** [review]
LGTM 🚀
