### PR TITLE
provider: add additional logic to SetTagsDiff to prevent `tags_all` perpetual diff when no `tags` configured

### LINKED ISSUE #19005: provider: Tests failing with ` After applying this test step, the plan was not empty` for `tags_all`
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Merge of #18958 accounts for `tags` values not known until apply, however, in the event no tags are set on the resource, we end with perpetual diff, such that terraform suggests the value for `tags_all` must be updated 

### Affected Resource(s)

* aws_* (those that now support default tags)

### Test Output

```
------- Stdout: -------
=== RUN   TestAccAWSALBTargetGroup_generatedName
=== PAUSE TestAccAWSALBTargetGroup_generatedName
=== CONT  TestAccAWSALBTargetGroup_generatedName
    resource_aws_alb_target_group_test.go:120: Step 1/1 error: After applying this test step, the plan was not empty.
        stdout:
        
        
        An execution plan has been generated and is shown below.
        Resource actions are indicated with the following symbols:
          ~ update in-place
        
        Terraform will perform the following actions:
        
          # aws_alb_target_group.test will be updated in-place
          ~ resource "aws_alb_target_group" "test" {
                id                                 = "arn:aws:elasticloadbalancing:us-west-2:*******:targetgroup/tf-20210420043346757400000001/98413905f615c1e8"
                name                               = "tf-20210420043346757400000001"
              ~ tags_all                           = {} -> (known after apply)
                # (12 unchanged attributes hidden)
        
        
                # (2 unchanged blocks hidden)
            }
        
        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccAWSALBTargetGroup_generatedName (33.92s)
```

### References

* #18958

### PR DESCRIPTION
**Pull request by anGie44**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #19005 

Output from acceptance testing before change:

```
=== CONT  TestAccAWSSubnet_basic
    resource_aws_subnet_test.go:117: Step 1/2 error: After applying this test step, the plan was not empty.
        stdout:


        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place

        Terraform will perform the following actions:

          # aws_subnet.test will be updated in-place
          ~ resource "aws_subnet" "test" {
                id                              = "subnet-0fe05d105c277af1e"
              ~ tags_all                        = {} -> (known after apply)
                # (9 unchanged attributes hidden)
            }

        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccAWSSubnet_basic (16.08s)
--- PASS: TestAccAWSSubnet_updateTagsKnownAtApply (54.32s)
```
```
------- Stdout: -------
=== RUN   TestAccAWSALBTargetGroup_generatedName
=== PAUSE TestAccAWSALBTargetGroup_generatedName
=== CONT  TestAccAWSALBTargetGroup_generatedName
    resource_aws_alb_target_group_test.go:120: Step 1/1 error: After applying this test step, the plan was not empty.
        stdout:
        
        
        An execution plan has been generated and is shown below.
        Resource actions are indicated with the following symbols:
          ~ update in-place
        
        Terraform will perform the following actions:
        
          # aws_alb_target_group.test will be updated in-place
          ~ resource "aws_alb_target_group" "test" {
                id                                 = "arn:aws:elasticloadbalancing:us-west-2:*******:targetgroup/tf-20210420043346757400000001/98413905f615c1e8"
                name                               = "tf-20210420043346757400000001"
              ~ tags_all                           = {} -> (known after apply)
                # (12 unchanged attributes hidden)
        
        
                # (2 unchanged blocks hidden)
            }
        
        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccAWSALBTargetGroup_generatedName (33.92s)
```

Output from acceptance testing after change:

```
--- PASS: TestAccAWSALBTargetGroup_generatedName (25.91s)
--- PASS: TestAccAWSSubnet_basic (27.10s)
--- PASS: TestAccAWSSubnet_tags (67.01s)
--- PASS: TestAccAWSSubnet_updateTagsKnownAtApply (54.32s)
--- PASS: TestAccAWSSubnet_defaultTags_providerAndResource_duplicateTag (2.25s)
--- PASS: TestAccAWSSubnet_defaultTags_updateToProviderOnly (37.14s)
--- PASS: TestAccAWSSubnet_defaultTags_updateToResourceOnly (40.15s)
--- PASS: TestAccAWSSubnet_defaultTags_providerAndResource_nonOverlappingTag (49.27s)
--- PASS: TestAccAWSSubnet_defaultTags_providerAndResource_overlappingTag (53.70s)
--- PASS: TestAccAWSSubnet_defaultTags_providerOnly (53.71s)
```

### CODE REVIEW

File: aws/tags.go [hunk 1]
```diff
@@ -111,15 +111,16 @@ func SetTagsDiff(_ context.Context, diff *schema.ResourceDiff, meta interface{})
 
 	allTags := defaultTagsConfig.MergeTags(resourceTags).IgnoreConfig(ignoreTagsConfig)
```
Comment (ewbankkit) [inline aws/tags.go:112]: Unrelated to this issue I'm sure, but does this line also require `.IgnoreAws()`?

Comment (bflad) [reply aws/tags.go:112]: I'm guessing there might be strange behavior if the `CustomizeDiff` function is removing `aws:` keys, but they are actually configured. Might be best to create a tracking issue for what happens in such a scenario. My guess would be that it will already trigger a perpetual difference, which is likely the desirable behavior.

Comment (ewbankkit) [reply aws/tags.go:112]: OK, `TestAccAWSS3Bucket_tagsWithSystemTags` is already testing `aws:` tag functionality.
I'll create a variant of that with `default_tags` and see what happens...

Comment (anGie44) [reply aws/tags.go:112]: tracking issue created here : https://github.com/hashicorp/terraform-provider-aws/issues/19019 (feel free to add more context :) , close if it doesn't prove applicable )
