### PR TITLE
r/aws_ecs_service: include volume_configuration, service_connect_configurations in resourceServiceRead

### LINKED ISSUE #40402: [New]: Missing in Importing "aws_ecs_service" ( Service Connect Configuration)
### Description

when i imported aws_ecs_service the Service Connect Configuration did was not importeted

### Requested Resource(s) and/or Data Source(s)

 Service Connect Configuration 

### Potential Terraform Configuration

```terraform
service Connect Configuration
service_connect_configuration {
enabled = true
# Define the namespace (usually, this should match the AWS Cloud Map namespace)
namespace = aws_service_discovery_http_namespace.ns--preprod-cluster.name
# List of services to register
service {
client_alias {
port = 8007
dns_name = "preprod.x"
}
port_name = "x-service-preprod-8007-tcp" # Reference the port from task definition
discovery_name = "x-preprod" # The name for service discovery
}
```

### References

_No response_

### Would you like to implement a fix?

None

### LINKED ISSUE #40715: [Bug]: aws_ecs_service - changes to service connect configuration are not detected.
### Terraform Core Version

1.10.0

### AWS Provider Version

5.82.2

### Affected Resource(s)

* aws_ecs_service

### Expected Behavior

if service connect is disabled or changed outside of terraform, it should show a diff when terraform runs

### Actual Behavior

terraform shows no changes

### Relevant Error/Panic Output Snippet

_No response_

### Terraform Configuration Files

I don't have readily available config to provide.

### Steps to Reproduce

1. Create an ECS service with service connect configuration defined
2. verify in the console that it is present, or in some cases like mine terraform will successfully apply but the console shows service connect is turned off. if it is turned on, just manually disable it in the console
3. run terraform plan, you'll see no changes

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

I can confirm via the aws cli that the configuration is indeed no longer present once it has been removed, so the issue seems to be in how terraform is determining the diff.

### References

_No response_

### Would you like to implement a fix?

No

### LINKED ISSUE #41997: [Bug]: `aws_ecs_service` does not read `volume_configuration` when syncing & importing
### Terraform Core Version

1.11.3

### AWS Provider Version

5.92.0

### Affected Resource(s)

* `aws_ecs_service`

### Expected Behavior

* importing an ECS service with configured volumes should yield `volume_configuration` blocks
* remote changes to a service's volume configuration should be reflected in changes to its `volume_configuration` in Terraform state on refresh
* discrepancies between a service's (primary deployment's) volume configuration and its corresponding `volume_configuration` in Terraform should register as a change & trigger an update

### Actual Behavior

* importing a service with configured volumes does _not_ yield `volume_configuration` blocks
* drift between a service's volume configurations and its `volume_configuration` in Terraform are not detected on refresh or planning

### References

a comparable problem also exists for [`service_connect_configuration` for the same resource](https://github.com/hashicorp/terraform-provider-aws/issues/40715)

add.l references:
* [`volume_configuration`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_service#volume_configuration-1) attribute
* [`volumeConfigurations`](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_Deployment.html#ECS-Type-Deployment-volumeConfigurations) field nested in `DescribeServices` response (via `deployments`)

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by obataku**
### Description
include `volume_configuration`, `service_connect_configurations` in `resourceServiceRead`

### Relations
Closes #41997.
Closes #40715.
Closes #40402.

### References
https://github.com/hashicorp/terraform-provider-aws/issues/40715#issuecomment-2571413422
> I could be wrong, but it seems that the resource code is not reading the config from AWS back into the state. The code that handles service_connect_configuration is commented out and there's no flattenServiceConnectConfiguration function defined

https://github.com/hashicorp/terraform-provider-aws/issues/40715#issuecomment-2755958396
>it appears this also affects changes to volume_configuration, which is missing entirely from resourceServiceRead 

### Output from Acceptance Testing
```console
% make testacc TESTS='TestAccECSService_(VolumeConfiguration_update|ServiceConnect_basic)' PKG=ecs              
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.7 test ./internal/service/ecs/... -v -count 1 -parallel 20 -run='TestAccECSService_(VolumeConfiguration_update|ServiceConnect_basic)'  -timeout 360m -vet=off
2025/03/27 21:23:33 Initializing Terraform AWS Provider...
=== RUN   TestAccECSService_VolumeConfiguration_update
=== PAUSE TestAccECSService_VolumeConfiguration_update
=== RUN   TestAccECSService_ServiceConnect_basic
=== PAUSE TestAccECSService_ServiceConnect_basic
=== CONT  TestAccECSService_VolumeConfiguration_update
=== CONT  TestAccECSService_ServiceConnect_basic
--- PASS: TestAccECSService_VolumeConfiguration_update (91.73s)
--- PASS: TestAccECSService_ServiceConnect_basic (158.01s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ecs        161.844s
```

### CODE REVIEW

File: internal/service/ecs/service.go [hunk 1]
```diff
@@ -2281,195 +2291,347 @@ func expandPlacementStrategy(s []any) ([]awstypes.PlacementStrategy, error) {
...
+	}
+	if v := apiObject.Iops; v != nil {
+		tfMap[names.AttrIOPS] = aws.ToInt32(v)
+	}
+	if v := apiObject.KmsKeyId; v != nil {
+		tfMap[names.AttrKMSKeyID] = aws.ToString(v)
+	}
+	if v := apiObject.RoleArn; v != nil {
+		tfMap[names.AttrRoleARN] = aws.ToString(v)
+	}
```
Comment (obataku) [inline internal/service/ecs/service.go:2595]: @ewbankkit this is already assigned when initializing `tfMap` as it's a required field in [`ServiceManagedEBSVolumeConfiguration`](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ServiceManagedEBSVolumeConfiguration.html#API_ServiceManagedEBSVolumeConfiguration_Contents); we should only keep one of these assignments

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccECSService_' PKG=ecs ACCTEST_PARALLELISM=4
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.7 test ./internal/service/ecs/... -v -count 1 -parallel 4  -run=TestAccECSService_ -timeout 360m -vet=off
2025/03/31 16:56:15 Initializing Terraform AWS Provider...
=== RUN   TestAccECSService_basic
=== PAUSE TestAccECSService_basic
=== RUN   TestAccECSService_basicImport
=== PAUSE TestAccECSService_basicImport
=== RUN   TestAccECSService_disappears
=== PAUSE TestAccECSService_disappears
=== RUN   TestAccECSService_LatticeConfigurations
=== PAUSE TestAccECSService_LatticeConfigurations
=== RUN   TestAccECSService_PlacementStrategy_unnormalized
=== PAUSE TestAccECSService_PlacementStrategy_unnormalized
=== RUN   TestAccECSService_CapacityProviderStrategy_basic
=== PAUSE TestAccECSService_CapacityProviderStrategy_basic
=== RUN   TestAccECSService_CapacityProviderStrategy_forceNewDeployment
=== PAUSE TestAccECSService_CapacityProviderStrategy_forceNewDeployment
=== RUN   TestAccECSService_CapacityProviderStrategy_update
=== PAUSE TestAccECSService_CapacityProviderStrategy_update
=== RUN   TestAccECSService_VolumeConfiguration_basic
=== PAUSE TestAccECSService_VolumeConfiguration_basic
=== RUN   TestAccECSService_VolumeConfiguration_tagSpecifications
=== PAUSE TestAccECSService_VolumeConfiguration_tagSpecifications
=== RUN   TestAccECSService_VolumeConfiguration_update
=== PAUSE TestAccECSService_VolumeConfiguration_update
=== RUN   TestAccECSService_VolumeConfiguration_throughputTypeChange
=== PAUSE TestAccECSService_VolumeConfiguration_throughputTypeChange
=== RUN   TestAccECSService_familyAndRevision
=== PAUSE TestAccECSService_familyAndRevision
=== RUN   TestAccECSService_healthCheckGracePeriodSeconds
=== PAUSE TestAccECSService_healthCheckGracePeriodSeconds
=== RUN   TestAccECSService_iamRole
=== PAUSE TestAccECSService_iamRole
=== RUN   TestAccECSService_DeploymentControllerType_codeDeploy
=== PAUSE TestAccECSService_DeploymentControllerType_codeDeploy
=== RUN   TestAccECSService_DeploymentControllerType_codeDeployUpdateDesiredCountAndHealthCheckGracePeriod
=== PAUSE TestAccECSService_DeploymentControllerType_codeDeployUpdateDesiredCountAndHealthCheckGracePeriod
=== RUN   TestAccECSService_DeploymentControllerType_external
=== PAUSE TestAccECSService_DeploymentControllerType_external
=== RUN   TestAccECSService_alarmsAdd
=== PAUSE TestAccECSService_alarmsAdd
=== RUN   TestAccECSService_alarmsUpdate
=== PAUSE TestAccECSService_alarmsUpdate
=== RUN   TestAccECSService_DeploymentValues_basic
=== PAUSE TestAccECSService_DeploymentValues_basic
=== RUN   TestAccECSService_DeploymentValues_minZeroMaxOneHundred
=== PAUSE TestAccECSService_DeploymentValues_minZeroMaxOneHundred
=== RUN   TestAccECSService_deploymentCircuitBreaker
=== PAUSE TestAccECSService_deploymentCircuitBreaker
=== RUN   TestAccECSService_loadBalancerChanges
=== PAUSE TestAccECSService_loadBalancerChanges
=== RUN   TestAccECSService_clusterName
=== PAUSE TestAccECSService_clusterName
=== RUN   TestAccECSService_alb
=== PAUSE TestAccECSService_alb
=== RUN   TestAccECSService_multipleTargetGroups
=== PAUSE TestAccECSService_multipleTargetGroups
=== RUN   TestAccECSService_forceNewDeployment
=== PAUSE TestAccECSService_forceNewDeployment
=== RUN   TestAccECSService_forceNewDeploymentTriggers
=== PAUSE TestAccECSService_forceNewDeploymentTriggers
=== RUN   TestAccECSService_PlacementStrategy_basic
=== PAUSE TestAccECSService_PlacementStrategy_basic
=== RUN   TestAccECSService_PlacementStrategy_missing
=== PAUSE TestAccECSService_PlacementStrategy_missing
=== RUN   TestAccECSService_PlacementConstraints_basic
=== PAUSE TestAccECSService_PlacementConstraints_basic
=== RUN   TestAccECSService_PlacementConstraints_emptyExpression
=== PAUSE TestAccECSService_PlacementConstraints_emptyExpression
=== RUN   TestAccECSService_LaunchTypeFargate_basic
=== PAUSE TestAccECSService_LaunchTypeFargate_basic
=== RUN   TestAccECSService_LaunchTypeFargate_platformVersion
=== PAUSE TestAccECSService_LaunchTypeFargate_platformVersion
=== RUN   TestAccECSService_LaunchTypeFargate_waitForSteadyState
=== PAUSE TestAccECSService_LaunchTypeFargate_waitForSteadyState
=== RUN   TestAccECSService_LaunchTypeFargate_updateWaitForSteadyState
=== PAUSE TestAccECSService_LaunchTypeFargate_updateWaitForSteadyState
=== RUN   TestAccECSService_LaunchTypeEC2_network
=== PAUSE TestAccECSService_LaunchTypeEC2_network
=== RUN   TestAccECSService_DaemonSchedulingStrategy_basic
=== PAUSE TestAccECSService_DaemonSchedulingStrategy_basic
=== RUN   TestAccECSService_DaemonSchedulingStrategy_setDeploymentMinimum
=== PAUSE TestAccECSService_DaemonSchedulingStrategy_setDeploymentMinimum
=== RUN   TestAccECSService_replicaSchedulingStrategy
=== PAUSE TestAccECSService_replicaSchedulingStrategy
=== RUN   TestAccECSService_ServiceRegistries_basic
=== PAUSE TestAccECSService_ServiceRegistries_basic
=== RUN   TestAccECSService_ServiceRegistries_container
=== PAUSE TestAccECSService_ServiceRegistries_container
=== RUN   TestAccECSService_ServiceRegistries_changes
=== PAUSE TestAccECSService_ServiceRegistries_changes
=== RUN   TestAccECSService_ServiceRegistries_removal
=== PAUSE TestAccECSService_ServiceRegistries_removal
=== RUN   TestAccECSService_ServiceConnect_basic
=== PAUSE TestAccECSService_ServiceConnect_basic
=== RUN   TestAccECSService_ServiceConnect_full
=== PAUSE TestAccECSService_ServiceConnect_full
=== RUN   TestAccECSService_ServiceConnect_tls_with_empty_timeout
=== PAUSE TestAccECSService_ServiceConnect_tls_with_empty_timeout
=== RUN   TestAccECSService_ServiceConnect_ingressPortOverride
=== PAUSE TestAccECSService_ServiceConnect_ingressPortOverride
=== RUN   TestAccECSService_ServiceConnect_remove
=== PAUSE TestAccECSService_ServiceConnect_remove
=== RUN   TestAccECSService_Tags_basic
=== PAUSE TestAccECSService_Tags_basic
=== RUN   TestAccECSService_Tags_managed
=== PAUSE TestAccECSService_Tags_managed
=== RUN   TestAccECSService_Tags_propagate
=== PAUSE TestAccECSService_Tags_propagate
=== RUN   TestAccECSService_executeCommand
=== PAUSE TestAccECSService_executeCommand
=== RUN   TestAccECSService_AvailabilityZoneRebalancing
=== PAUSE TestAccECSService_AvailabilityZoneRebalancing
=== CONT  TestAccECSService_basic
=== CONT  TestAccECSService_forceNewDeploymentTriggers
=== CONT  TestAccECSService_iamRole
=== CONT  TestAccECSService_CapacityProviderStrategy_update
--- PASS: TestAccECSService_iamRole (31.38s)
=== CONT  TestAccECSService_DeploymentValues_minZeroMaxOneHundred
--- PASS: TestAccECSService_forceNewDeploymentTriggers (69.10s)
=== CONT  TestAccECSService_forceNewDeployment
--- PASS: TestAccECSService_basic (79.69s)
=== CONT  TestAccECSService_multipleTargetGroups
--- PASS: TestAccECSService_DeploymentValues_minZeroMaxOneHundred (69.99s)
=== CONT  TestAccECSService_alb
--- PASS: TestAccECSService_forceNewDeployment (57.42s)
=== CONT  TestAccECSService_clusterName
--- PASS: TestAccECSService_clusterName (69.63s)
=== CONT  TestAccECSService_loadBalancerChanges
--- PASS: TestAccECSService_multipleTargetGroups (283.74s)
=== CONT  TestAccECSService_deploymentCircuitBreaker
--- PASS: TestAccECSService_alb (272.19s)
=== CONT  TestAccECSService_alarmsAdd
--- PASS: TestAccECSService_deploymentCircuitBreaker (69.89s)
=== CONT  TestAccECSService_DeploymentValues_basic
--- PASS: TestAccECSService_alarmsAdd (68.35s)
=== CONT  TestAccECSService_alarmsUpdate
--- PASS: TestAccECSService_CapacityProviderStrategy_update (447.77s)
=== CONT  TestAccECSService_PlacementStrategy_unnormalized
--- PASS: TestAccECSService_loadBalancerChanges (253.65s)
=== CONT  TestAccECSService_CapacityProviderStrategy_forceNewDeployment
--- PASS: TestAccECSService_DeploymentValues_basic (69.24s)
=== CONT  TestAccECSService_CapacityProviderStrategy_basic
--- PASS: TestAccECSService_PlacementStrategy_unnormalized (58.68s)
=== CONT  TestAccECSService_DeploymentControllerType_codeDeployUpdateDesiredCountAndHealthCheckGracePeriod
--- PASS: TestAccECSService_alarmsUpdate (68.14s)
=== CONT  TestAccECSService_DeploymentControllerType_external
--- PASS: TestAccECSService_DeploymentControllerType_external (31.91s)
=== CONT  TestAccECSService_DeploymentControllerType_codeDeploy
--- PASS: TestAccECSService_CapacityProviderStrategy_forceNewDeployment (249.04s)
=== CONT  TestAccECSService_VolumeConfiguration_throughputTypeChange
--- PASS: TestAccECSService_CapacityProviderStrategy_basic (236.42s)
=== CONT  TestAccECSService_healthCheckGracePeriodSeconds
--- PASS: TestAccECSService_DeploymentControllerType_codeDeployUpdateDesiredCountAndHealthCheckGracePeriod (251.77s)
=== CONT  TestAccECSService_familyAndRevision
--- PASS: TestAccECSService_DeploymentControllerType_codeDeploy (243.66s)
=== CONT  TestAccECSService_disappears
--- PASS: TestAccECSService_VolumeConfiguration_throughputTypeChange (90.34s)
=== CONT  TestAccECSService_LatticeConfigurations
--- PASS: TestAccECSService_familyAndRevision (78.15s)
=== CONT  TestAccECSService_basicImport
--- PASS: TestAccECSService_healthCheckGracePeriodSeconds (197.97s)
=== CONT  TestAccECSService_ServiceRegistries_container
--- PASS: TestAccECSService_disappears (189.46s)
=== CONT  TestAccECSService_AvailabilityZoneRebalancing
--- PASS: TestAccECSService_basicImport (184.94s)
=== CONT  TestAccECSService_executeCommand
--- PASS: TestAccECSService_LatticeConfigurations (256.43s)
=== CONT  TestAccECSService_Tags_propagate
--- PASS: TestAccECSService_AvailabilityZoneRebalancing (73.02s)
=== CONT  TestAccECSService_Tags_managed
--- PASS: TestAccECSService_executeCommand (69.27s)
=== CONT  TestAccECSService_Tags_basic
--- PASS: TestAccECSService_Tags_managed (58.63s)
=== CONT  TestAccECSService_ServiceConnect_remove
--- PASS: TestAccECSService_ServiceRegistries_container (173.70s)
=== CONT  TestAccECSService_ServiceConnect_ingressPortOverride
--- PASS: TestAccECSService_Tags_propagate (66.18s)
=== CONT  TestAccECSService_ServiceConnect_tls_with_empty_timeout
--- PASS: TestAccECSService_Tags_basic (78.20s)
=== CONT  TestAccECSService_ServiceConnect_full
--- PASS: TestAccECSService_ServiceConnect_remove (117.11s)
=== CONT  TestAccECSService_ServiceConnect_basic
--- PASS: TestAccECSService_ServiceConnect_ingressPortOverride (119.29s)
=== CONT  TestAccECSService_ServiceRegistries_removal
--- PASS: TestAccECSService_ServiceConnect_tls_with_empty_timeout (119.76s)
=== CONT  TestAccECSService_ServiceRegistries_changes
--- PASS: TestAccECSService_ServiceConnect_full (136.20s)
=== CONT  TestAccECSService_VolumeConfiguration_update
    acctest.go:1552: skipping test for aws/us-west-2: Error running apply: exit status 1
        
        Error: updating ECS Service (arn:aws:ecs:us-west-2:187416307283:service/tf-acc-test-6297247269009236498/tf-acc-test-6297247269009236498): operation error ECS: UpdateService, https response error StatusCode: 400, RequestID: 0cc261c8-c1bd-46b2-a5b0-a7169b98666a, InvalidParameterException: ECS managed EBS volume configuration was invalid for volume 'vol1'. Encountered 'VolumeTypeNotAvailableInZone' error from AmazonEC2: "The specified zone does not support gp3 volume type."
        
          with aws_ecs_service.test,
          on terraform_plugin_test.tf line 85, in resource "aws_ecs_service" "test":
          85: resource "aws_ecs_service" "test" {
        
--- SKIP: TestAccECSService_VolumeConfiguration_update (66.66s)
=== CONT  TestAccECSService_LaunchTypeFargate_waitForSteadyState
--- PASS: TestAccECSService_ServiceRegistries_removal (142.92s)
=== CONT  TestAccECSService_ServiceRegistries_basic
--- PASS: TestAccECSService_ServiceConnect_basic (150.42s)
=== CONT  TestAccECSService_replicaSchedulingStrategy
--- PASS: TestAccECSService_replicaSchedulingStrategy (69.39s)
=== CONT  TestAccECSService_DaemonSchedulingStrategy_setDeploymentMinimum
--- PASS: TestAccECSService_ServiceRegistries_changes (231.74s)
=== CONT  TestAccECSService_DaemonSchedulingStrategy_basic
--- PASS: TestAccECSService_DaemonSchedulingStrategy_setDeploymentMinimum (38.33s)
=== CONT  TestAccECSService_LaunchTypeEC2_network
--- PASS: TestAccECSService_DaemonSchedulingStrategy_basic (29.78s)
=== CONT  TestAccECSService_LaunchTypeFargate_updateWaitForSteadyState
--- PASS: TestAccECSService_LaunchTypeFargate_waitForSteadyState (153.22s)
=== CONT  TestAccECSService_VolumeConfiguration_basic
--- PASS: TestAccECSService_ServiceRegistries_basic (153.39s)
=== CONT  TestAccECSService_PlacementConstraints_emptyExpression
--- PASS: TestAccECSService_VolumeConfiguration_basic (60.04s)
=== CONT  TestAccECSService_LaunchTypeFargate_platformVersion
--- PASS: TestAccECSService_PlacementConstraints_emptyExpression (58.98s)
=== CONT  TestAccECSService_LaunchTypeFargate_basic
--- PASS: TestAccECSService_LaunchTypeEC2_network (106.00s)
=== CONT  TestAccECSService_PlacementStrategy_missing
--- PASS: TestAccECSService_PlacementStrategy_missing (0.76s)
=== CONT  TestAccECSService_PlacementConstraints_basic
--- PASS: TestAccECSService_PlacementConstraints_basic (68.01s)
=== CONT  TestAccECSService_PlacementStrategy_basic
--- PASS: TestAccECSService_LaunchTypeFargate_basic (75.69s)
=== CONT  TestAccECSService_VolumeConfiguration_tagSpecifications
--- PASS: TestAccECSService_LaunchTypeFargate_platformVersion (86.73s)
--- PASS: TestAccECSService_LaunchTypeFargate_updateWaitForSteadyState (206.20s)
--- PASS: TestAccECSService_VolumeConfiguration_tagSpecifications (70.52s)
--- PASS: TestAccECSService_PlacementStrategy_basic (95.63s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ecs	1757.937s
```

File: internal/service/ecs/service_test.go [hunk 2]
```diff
@@ -409,19 +409,36 @@ func TestAccECSService_VolumeConfiguration_update(t *testing.T) {
...
+				// Resource currently defaults to importing task_definition as family:revision
+				// and wait_for_steady_state is not read from API
+				ImportStateVerifyIgnore: []string{"task_definition", "wait_for_steady_state"},
+			},
 			{
 				Config: testAccServiceConfig_volumeConfiguration_update(rName, "gp3", 8),
 				Check: resource.ComposeTestCheckFunc(
-					testAccCheckServiceExists(ctx, resourceName, &service),
+					testAccCheckServiceExists(ctx, resourceName, &service2),
+					testAccCheckServiceNotRecreated(&service1, &service2),
```
Comment (jar-b) [inline internal/service/ecs/service_test.go:431]: Can we use a `ConfigPlanCheck` here instead?

Comment (ewbankkit) [reply internal/service/ecs/service_test.go]: Done:

```console
% make testacc TESTARGS='-run=TestAccECSService_' PKG=ecs ACCTEST_PARALLELISM=4
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.7 test ./internal/service/ecs/... -v -count 1 -parallel 4  -run=TestAccECSService_ -timeout 360m -vet=off
2025/04/01 10:08:56 Initializing Terraform AWS Provider...
=== RUN   TestAccECSService_basic
=== PAUSE TestAccECSService_basic
=== RUN   TestAccECSService_basicImport
=== PAUSE TestAccECSService_basicImport
=== RUN   TestAccECSService_disappears
=== PAUSE TestAccECSService_disappears
=== RUN   TestAccECSService_LatticeConfigurations
=== PAUSE TestAccECSService_LatticeConfigurations
=== RUN   TestAccECSService_PlacementStrategy_unnormalized
=== PAUSE TestAccECSService_PlacementStrategy_unnormalized
=== RUN   TestAccECSService_CapacityProviderStrategy_basic
=== PAUSE TestAccECSService_CapacityProviderStrategy_basic
=== RUN   TestAccECSService_CapacityProviderStrategy_forceNewDeployment
=== PAUSE TestAccECSService_CapacityProviderStrategy_forceNewDeployment
=== RUN   TestAccECSService_CapacityProviderStrategy_update
=== PAUSE TestAccECSService_CapacityProviderStrategy_update
=== RUN   TestAccECSService_VolumeConfiguration_basic
=== PAUSE TestAccECSService_VolumeConfiguration_basic
=== RUN   TestAccECSService_VolumeConfiguration_tagSpecifications
=== PAUSE TestAccECSService_VolumeConfiguration_tagSpecifications
=== RUN   TestAccECSService_VolumeConfiguration_update
=== PAUSE TestAccECSService_VolumeConfiguration_update
=== RUN   TestAccECSService_VolumeConfiguration_throughputTypeChange
=== PAUSE TestAccECSService_VolumeConfiguration_throughputTypeChange
=== RUN   TestAccECSService_familyAndRevision
=== PAUSE TestAccECSService_familyAndRevision
=== RUN   TestAccECSService_healthCheckGracePeriodSeconds
=== PAUSE TestAccECSService_healthCheckGracePeriodSeconds
=== RUN   TestAccECSService_iamRole
=== PAUSE TestAccECSService_iamRole
=== RUN   TestAccECSService_DeploymentControllerType_codeDeploy
=== PAUSE TestAccECSService_DeploymentControllerType_codeDeploy
=== RUN   TestAccECSService_DeploymentControllerType_codeDeployUpdateDesiredCountAndHealthCheckGracePeriod
=== PAUSE TestAccECSService_DeploymentControllerType_codeDeployUpdateDesiredCountAndHealthCheckGracePeriod
=== RUN   TestAccECSService_DeploymentControllerType_external
=== PAUSE TestAccECSService_DeploymentControllerType_external
=== RUN   TestAccECSService_alarmsAdd
=== PAUSE TestAccECSService_alarmsAdd
=== RUN   TestAccECSService_alarmsUpdate
=== PAUSE TestAccECSService_alarmsUpdate
=== RUN   TestAccECSService_DeploymentValues_basic
=== PAUSE TestAccECSService_DeploymentValues_basic
=== RUN   TestAccECSService_DeploymentValues_minZeroMaxOneHundred
=== PAUSE TestAccECSService_DeploymentValues_minZeroMaxOneHundred
=== RUN   TestAccECSService_deploymentCircuitBreaker
=== PAUSE TestAccECSService_deploymentCircuitBreaker
=== RUN   TestAccECSService_loadBalancerChanges
=== PAUSE TestAccECSService_loadBalancerChanges
=== RUN   TestAccECSService_clusterName
=== PAUSE TestAccECSService_clusterName
=== RUN   TestAccECSService_alb
=== PAUSE TestAccECSService_alb
=== RUN   TestAccECSService_multipleTargetGroups
=== PAUSE TestAccECSService_multipleTargetGroups
=== RUN   TestAccECSService_forceNewDeployment
=== PAUSE TestAccECSService_forceNewDeployment
=== RUN   TestAccECSService_forceNewDeploymentTriggers
=== PAUSE TestAccECSService_forceNewDeploymentTriggers
=== RUN   TestAccECSService_PlacementStrategy_basic
=== PAUSE TestAccECSService_PlacementStrategy_basic
=== RUN   TestAccECSService_PlacementStrategy_missing
=== PAUSE TestAccECSService_PlacementStrategy_missing
=== RUN   TestAccECSService_PlacementConstraints_basic
=== PAUSE TestAccECSService_PlacementConstraints_basic
=== RUN   TestAccECSService_PlacementConstraints_emptyExpression
=== PAUSE TestAccECSService_PlacementConstraints_emptyExpression
=== RUN   TestAccECSService_LaunchTypeFargate_basic
=== PAUSE TestAccECSService_LaunchTypeFargate_basic
=== RUN   TestAccECSService_LaunchTypeFargate_platformVersion
=== PAUSE TestAccECSService_LaunchTypeFargate_platformVersion
=== RUN   TestAccECSService_LaunchTypeFargate_waitForSteadyState
=== PAUSE TestAccECSService_LaunchTypeFargate_waitForSteadyState
=== RUN   TestAccECSService_LaunchTypeFargate_updateWaitForSteadyState
=== PAUSE TestAccECSService_LaunchTypeFargate_updateWaitForSteadyState
=== RUN   TestAccECSService_LaunchTypeEC2_network
=== PAUSE TestAccECSService_LaunchTypeEC2_network
=== RUN   TestAccECSService_DaemonSchedulingStrategy_basic
=== PAUSE TestAccECSService_DaemonSchedulingStrategy_basic
=== RUN   TestAccECSService_DaemonSchedulingStrategy_setDeploymentMinimum
=== PAUSE TestAccECSService_DaemonSchedulingStrategy_setDeploymentMinimum
=== RUN   TestAccECSService_replicaSchedulingStrategy
=== PAUSE TestAccECSService_replicaSchedulingStrategy
=== RUN   TestAccECSService_ServiceRegistries_basic
=== PAUSE TestAccECSService_ServiceRegistries_basic
=== RUN   TestAccECSService_ServiceRegistries_container
=== PAUSE TestAccECSService_ServiceRegistries_container
=== RUN   TestAccECSService_ServiceRegistries_changes
=== PAUSE TestAccECSService_ServiceRegistries_changes
=== RUN   TestAccECSService_ServiceRegistries_removal
=== PAUSE TestAccECSService_ServiceRegistries_removal
=== RUN   TestAccECSService_ServiceConnect_basic
=== PAUSE TestAccECSService_ServiceConnect_basic
=== RUN   TestAccECSService_ServiceConnect_full
=== PAUSE TestAccECSService_ServiceConnect_full
=== RUN   TestAccECSService_ServiceConnect_tls_with_empty_timeout
=== PAUSE TestAccECSService_ServiceConnect_tls_with_empty_timeout
=== RUN   TestAccECSService_ServiceConnect_ingressPortOverride
=== PAUSE TestAccECSService_ServiceConnect_ingressPortOverride
=== RUN   TestAccECSService_ServiceConnect_remove
=== PAUSE TestAccECSService_ServiceConnect_remove
=== RUN   TestAccECSService_Tags_basic
=== PAUSE TestAccECSService_Tags_basic
=== RUN   TestAccECSService_Tags_managed
=== PAUSE TestAccECSService_Tags_managed
=== RUN   TestAccECSService_Tags_propagate
=== PAUSE TestAccECSService_Tags_propagate
=== RUN   TestAccECSService_executeCommand
=== PAUSE TestAccECSService_executeCommand
=== RUN   TestAccECSService_AvailabilityZoneRebalancing
=== PAUSE TestAccECSService_AvailabilityZoneRebalancing
=== CONT  TestAccECSService_basic
=== CONT  TestAccECSService_forceNewDeploymentTriggers
=== CONT  TestAccECSService_iamRole
=== CONT  TestAccECSService_forceNewDeployment
--- PASS: TestAccECSService_iamRole (37.43s)
=== CONT  TestAccECSService_multipleTargetGroups
--- PASS: TestAccECSService_forceNewDeployment (61.08s)
=== CONT  TestAccECSService_alb
--- PASS: TestAccECSService_forceNewDeploymentTriggers (61.21s)
=== CONT  TestAccECSService_clusterName
--- PASS: TestAccECSService_basic (81.61s)
=== CONT  TestAccECSService_loadBalancerChanges
--- PASS: TestAccECSService_clusterName (70.02s)
=== CONT  TestAccECSService_deploymentCircuitBreaker
--- PASS: TestAccECSService_deploymentCircuitBreaker (72.46s)
=== CONT  TestAccECSService_DeploymentValues_minZeroMaxOneHundred
--- PASS: TestAccECSService_DeploymentValues_minZeroMaxOneHundred (70.30s)
=== CONT  TestAccECSService_DeploymentValues_basic
--- PASS: TestAccECSService_multipleTargetGroups (283.52s)
=== CONT  TestAccECSService_alarmsUpdate
--- PASS: TestAccECSService_alb (266.97s)
=== CONT  TestAccECSService_alarmsAdd
--- PASS: TestAccECSService_DeploymentValues_basic (59.47s)
=== CONT  TestAccECSService_DeploymentControllerType_external
--- PASS: TestAccECSService_loadBalancerChanges (258.02s)
=== CONT  TestAccECSService_DeploymentControllerType_codeDeployUpdateDesiredCountAndHealthCheckGracePeriod
--- PASS: TestAccECSService_DeploymentControllerType_external (28.21s)
=== CONT  TestAccECSService_DeploymentControllerType_codeDeploy
--- PASS: TestAccECSService_alarmsAdd (68.35s)
=== CONT  TestAccECSService_ServiceRegistries_container
--- PASS: TestAccECSService_alarmsUpdate (79.03s)
=== CONT  TestAccECSService_CapacityProviderStrategy_update
--- PASS: TestAccECSService_CapacityProviderStrategy_update (407.98s)
=== CONT  TestAccECSService_healthCheckGracePeriodSeconds
--- PASS: TestAccECSService_ServiceRegistries_container (154.14s)
=== CONT  TestAccECSService_familyAndRevision
--- PASS: TestAccECSService_DeploymentControllerType_codeDeploy (231.94s)
=== CONT  TestAccECSService_VolumeConfiguration_throughputTypeChange
=== CONT  TestAccECSService_VolumeConfiguration_throughputTypeChange
    acctest.go:1552: skipping test for aws/us-west-2: Error running apply: exit status 1
        
        Error: creating ECS Service (tf-acc-test-1251836749557687720): InvalidParameterException: ECS managed EBS volume configuration was invalid for volume 'vol1'. Encountered 'VolumeTypeNotAvailableInZone' error from AmazonEC2: "The specified zone does not support gp3 volume type."
        
          with aws_ecs_service.test,
          on terraform_plugin_test.tf line 87, in resource "aws_ecs_service" "test":
          87: resource "aws_ecs_service" "test" {
        
--- SKIP: TestAccECSService_VolumeConfiguration_throughputTypeChange (38.39s)
=== CONT  TestAccECSService_VolumeConfiguration_update
--- PASS: TestAccECSService_familyAndRevision (77.06s)
=== CONT  TestAccECSService_VolumeConfiguration_tagSpecifications
=== NAME  TestAccECSService_VolumeConfiguration_update
    acctest.go:1552: skipping test for aws/us-west-2: Error running apply: exit status 1
        
        Error: updating ECS Service (arn:aws:ecs:us-west-2:187416307283:service/tf-acc-test-5643404474085742429/tf-acc-test-5643404474085742429): operation error ECS: UpdateService, https response error StatusCode: 400, RequestID: 04915943-7324-4279-a95d-60f599b677a3, InvalidParameterException: ECS managed EBS volume configuration was invalid for volume 'vol1'. Encountered 'VolumeTypeNotAvailableInZone' error from AmazonEC2: "The specified zone does not support gp3 volume type."
        
          with aws_ecs_service.test,
          on terraform_plugin_test.tf line 85, in resource "aws_ecs_service" "test":
          85: resource "aws_ecs_service" "test" {
        
--- SKIP: TestAccECSService_VolumeConfiguration_update (67.85s)
=== CONT  TestAccECSService_VolumeConfiguration_basic
--- PASS: TestAccECSService_VolumeConfiguration_tagSpecifications (60.96s)
=== CONT  TestAccECSService_LaunchTypeFargate_waitForSteadyState
--- PASS: TestAccECSService_VolumeConfiguration_basic (60.90s)
=== CONT  TestAccECSService_ServiceRegistries_basic
--- PASS: TestAccECSService_DeploymentControllerType_codeDeployUpdateDesiredCountAndHealthCheckGracePeriod (480.12s)
=== CONT  TestAccECSService_replicaSchedulingStrategy
--- PASS: TestAccECSService_LaunchTypeFargate_waitForSteadyState (164.36s)
=== CONT  TestAccECSService_DaemonSchedulingStrategy_setDeploymentMinimum
--- PASS: TestAccECSService_healthCheckGracePeriodSeconds (316.42s)
=== CONT  TestAccECSService_DaemonSchedulingStrategy_basic
--- PASS: TestAccECSService_ServiceRegistries_basic (142.99s)
=== CONT  TestAccECSService_LaunchTypeEC2_network
--- PASS: TestAccECSService_replicaSchedulingStrategy (59.19s)
=== CONT  TestAccECSService_LaunchTypeFargate_updateWaitForSteadyState
--- PASS: TestAccECSService_DaemonSchedulingStrategy_setDeploymentMinimum (29.43s)
=== CONT  TestAccECSService_ServiceConnect_ingressPortOverride
--- PASS: TestAccECSService_DaemonSchedulingStrategy_basic (37.69s)
=== CONT  TestAccECSService_executeCommand
--- PASS: TestAccECSService_LaunchTypeEC2_network (76.26s)
=== CONT  TestAccECSService_Tags_propagate
--- PASS: TestAccECSService_executeCommand (47.72s)
=== CONT  TestAccECSService_Tags_managed
--- PASS: TestAccECSService_Tags_propagate (55.86s)
=== CONT  TestAccECSService_Tags_basic
--- PASS: TestAccECSService_Tags_managed (69.26s)
=== CONT  TestAccECSService_ServiceConnect_remove
--- PASS: TestAccECSService_ServiceConnect_ingressPortOverride (166.32s)
=== CONT  TestAccECSService_disappears
--- PASS: TestAccECSService_Tags_basic (68.76s)
=== CONT  TestAccECSService_LatticeConfigurations
--- PASS: TestAccECSService_LaunchTypeFargate_updateWaitForSteadyState (193.95s)
=== CONT  TestAccECSService_CapacityProviderStrategy_forceNewDeployment
--- PASS: TestAccECSService_ServiceConnect_remove (146.94s)
=== CONT  TestAccECSService_PlacementStrategy_unnormalized
--- PASS: TestAccECSService_PlacementStrategy_unnormalized (59.66s)
=== CONT  TestAccECSService_CapacityProviderStrategy_basic
--- PASS: TestAccECSService_disappears (179.59s)
=== CONT  TestAccECSService_ServiceConnect_basic
--- PASS: TestAccECSService_CapacityProviderStrategy_forceNewDeployment (183.91s)
=== CONT  TestAccECSService_ServiceConnect_tls_with_empty_timeout
--- PASS: TestAccECSService_LatticeConfigurations (270.56s)
=== CONT  TestAccECSService_ServiceConnect_full
--- PASS: TestAccECSService_ServiceConnect_basic (123.83s)
=== CONT  TestAccECSService_ServiceRegistries_removal
--- PASS: TestAccECSService_ServiceConnect_tls_with_empty_timeout (195.51s)
=== CONT  TestAccECSService_PlacementConstraints_emptyExpression
--- PASS: TestAccECSService_ServiceRegistries_removal (116.76s)
=== CONT  TestAccECSService_basicImport
--- PASS: TestAccECSService_ServiceConnect_full (167.25s)
=== CONT  TestAccECSService_LaunchTypeFargate_platformVersion
--- PASS: TestAccECSService_PlacementConstraints_emptyExpression (59.83s)
=== CONT  TestAccECSService_ServiceRegistries_changes
--- PASS: TestAccECSService_CapacityProviderStrategy_basic (308.27s)
=== CONT  TestAccECSService_LaunchTypeFargate_basic
--- PASS: TestAccECSService_LaunchTypeFargate_platformVersion (77.03s)
=== CONT  TestAccECSService_PlacementStrategy_missing
--- PASS: TestAccECSService_PlacementStrategy_missing (0.82s)
=== CONT  TestAccECSService_PlacementStrategy_basic
--- PASS: TestAccECSService_LaunchTypeFargate_basic (60.25s)
=== CONT  TestAccECSService_PlacementConstraints_basic
--- PASS: TestAccECSService_basicImport (164.51s)
=== CONT  TestAccECSService_AvailabilityZoneRebalancing
--- PASS: TestAccECSService_PlacementConstraints_basic (49.19s)
--- PASS: TestAccECSService_PlacementStrategy_basic (89.56s)
--- PASS: TestAccECSService_AvailabilityZoneRebalancing (63.25s)
--- PASS: TestAccECSService_ServiceRegistries_changes (245.43s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ecs	1763.158s
```

**Review by jar-b — APPROVED** [review]
LGTM 🚀

File: internal/service/ecs/service.go (hunk 1 above)
Comment (obataku) [reply internal/service/ecs/service.go:2592]: @ewbankkit for clarification, right now the `role_arn` attribute is being redundantly assigned twice:
```go
	tfMap := map[string]any{
		names.AttrRoleARN: aws.ToString(apiObject.RoleArn),
	}
...
	if v := apiObject.RoleArn; v != nil {
		tfMap[names.AttrRoleARN] = aws.ToString(v)
	}
```

**Review by obataku — COMMENTED** [review]
thanks for the assist @ewbankkit & @jar-b, just following up on my previous comment
