### PR TITLE
aws_batch_job_queue add `compute_environment_order` and deprecate `compute_environments`

### LINKED ISSUE #19247: Missing ComputeEnvironmentOrder Data Type in AWS Batch
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The Data Type in question is https://docs.aws.amazon.com/batch/latest/APIReference/API_ComputeEnvironmentOrder.html

Currently Terraform does not allow assignment of an order to an AWS Batch Queue's Compute Environments. It will assign a number depending on the ordinal position in which it is listed, for example in the following code:
```
resource "aws_batch_job_queue" "job_queue" {
  ...
  compute_environments = [
    aws_batch_compute_environment.job_compute_environment1.arn,
    aws_batch_compute_environment.job_compute_environment2.arn
  ]
}
```
`aws_batch_compute_environment.job_compute_environment1` will be assigned order 0 and `aws_batch_compute_environment.job_compute_environment2` will be assigned order 1.

However, this feature of being able to assign an order is available in [AWS CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-batch-jobqueue-computeenvironmentorder.html), the [AWS CLI](https://docs.aws.amazon.com/cli/latest/reference/batch/create-job-queue.html), [boto3](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/batch.html#Batch.Client.create_job_queue) and possibly other SDKs.

### New or Affected Resource(s)

* aws_batch_queue

### Potential Terraform Configuration

```hcl
resource "aws_batch_job_queue" "batch_queue" {
  name = "batch_queue"
  state = "ENABLED"
  priority = 0

  compute_environments = [
    {
       compute_environment = aws_batch_compute_environment.job_compute_environment1.arn,
       order = 1
    },
    {
       compute_environment = aws_batch_compute_environment.job_compute_environment1.arn,
       order = 2
    }
  ]
}
```

### References

* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/batch_job_queue
* https://docs.aws.amazon.com/batch/latest/APIReference/API_ComputeEnvironmentOrder.html
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-batch-jobqueue-computeenvironmentorder.html
* https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/batch.html#Batch.Client.create_job_queue

### LINKED ISSUE #20764: AWS Batch Enhancements
We have a requirement to build a high performance compute environment for an enterprise.

AWS developers discovered a number of limitations related to some limits and scale of the project.

1. Ability to attach more than 3 compute environments to one job queue. (Our limit was raised to 6 in this case while aws standard limit is 3)

parameter - 
compute_environments - (Required) Specifies the set of compute environments mapped to a job queue and their order. The position of the compute environments in the list will dictate the order. You can associate up to 3 compute environments with a job queue.

2. Ability to assign 'Compute environment order' in the queue. As far as we understand the module assign order 0-1-2. We need to be able to assign 1-1-1 for example to make sure we can boost the process.

Thanks.

### LINKED ISSUE #34760: [Bug]: `aws_batch_queue` _disappears test fails
### Terraform Core Version

x

### AWS Provider Version

latest

### Affected Resource(s)

* aws_batch_job_queue

### Expected Behavior

resource should be gracefully removed from state if missing and asked to be deleted

### Actual Behavior

```shell
    testing_new.go:91: Error running post-test destroy, there may be dangling resources: exit status 1
        
        Error: deleting AWS Batch Job Queue (tf-acc-test-1550725352243262377)
        
        ClientException:
        arn:aws:batch:us-east-2:<>:job-queue/tf-acc-test-1550725352243262377
        does not exist.
--- FAIL: TestAccBatchJobQueue_disappears (331.72s)
```

### Relevant Error/Panic Output Snippet

_No response_

### Terraform Configuration Files

n/a

### Steps to Reproduce

`make testacc TESTS=TestAccBatchJobQueue_disappears PKG=batch`

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

Issue is caused by not catching ResourceNotFound here: https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/batch/job_queue.go#L418

### References

_No response_

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by drewmullen**
### Description

- `compute_environments` (CEs) and `compute_environment_order` (CEOs) are mutually exclusive
- In order to preserve schema migration, `compute_environments` must stay as the "default" or it will cause breaking changes when a users schema is migrated from CEs in state without requiring them to update their HCL to use CEOs.
- Because import requires `CEs` it is impossible to migrate to CEOs parameter :/  You must have done the initial `Create` with it

### Relations

Closes #34760
Closes #19247
Closes #20764

**Does not close or resolve** #34794 however, migration does appear to work as expected

### Output from Acceptance Testing

```console
$ make testacc TESTS=TestAccBatchJobQueue_ PKG=batch
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/batch/... -v -count 1 -parallel 20 -run='TestAccBatchJobQueue_'  -timeout 360m
=== RUN   TestAccBatchJobQueue_basic
=== PAUSE TestAccBatchJobQueue_basic
=== RUN   TestAccBatchJobQueue_basicCEO
=== PAUSE TestAccBatchJobQueue_basicCEO
=== RUN   TestAccBatchJobQueue_disappears
=== PAUSE TestAccBatchJobQueue_disappears
=== RUN   TestAccBatchJobQueue_disappearsCEO
=== PAUSE TestAccBatchJobQueue_disappearsCEO
=== RUN   TestAccBatchJobQueue_MigrateFromPluginSDK
=== PAUSE TestAccBatchJobQueue_MigrateFromPluginSDK
=== RUN   TestAccBatchJobQueue_ComputeEnvironments_multiple
=== PAUSE TestAccBatchJobQueue_ComputeEnvironments_multiple
=== RUN   TestAccBatchJobQueue_ComputeEnvironmentOrder_multiple
=== PAUSE TestAccBatchJobQueue_ComputeEnvironmentOrder_multiple
=== RUN   TestAccBatchJobQueue_ComputeEnvironments_externalOrderUpdate
=== PAUSE TestAccBatchJobQueue_ComputeEnvironments_externalOrderUpdate
=== RUN   TestAccBatchJobQueue_priority
=== PAUSE TestAccBatchJobQueue_priority
=== RUN   TestAccBatchJobQueue_schedulingPolicy
=== PAUSE TestAccBatchJobQueue_schedulingPolicy
=== RUN   TestAccBatchJobQueue_state
=== PAUSE TestAccBatchJobQueue_state
=== RUN   TestAccBatchJobQueue_tags
=== PAUSE TestAccBatchJobQueue_tags
=== CONT  TestAccBatchJobQueue_basic
=== CONT  TestAccBatchJobQueue_ComputeEnvironmentOrder_multiple
=== CONT  TestAccBatchJobQueue_disappearsCEO
=== CONT  TestAccBatchJobQueue_disappears
=== CONT  TestAccBatchJobQueue_tags
=== CONT  TestAccBatchJobQueue_priority
=== CONT  TestAccBatchJobQueue_MigrateFromPluginSDK
=== CONT  TestAccBatchJobQueue_schedulingPolicy
=== CONT  TestAccBatchJobQueue_ComputeEnvironments_multiple
=== CONT  TestAccBatchJobQueue_state
=== CONT  TestAccBatchJobQueue_ComputeEnvironments_externalOrderUpdate
=== CONT  TestAccBatchJobQueue_basicCEO
=== NAME  TestAccBatchJobQueue_MigrateFromPluginSDK
    testing_new.go:80: Error retrieving state, there may be dangling resources: exit status 1
        Failed to marshal state to json: schema version 0 for aws_batch_job_queue.test in state does not match version 1 from the provider
--- FAIL: TestAccBatchJobQueue_MigrateFromPluginSDK (225.20s)
--- PASS: TestAccBatchJobQueue_disappearsCEO (533.22s)
--- PASS: TestAccBatchJobQueue_disappears (533.37s)
--- PASS: TestAccBatchJobQueue_basic (542.01s)
--- PASS: TestAccBatchJobQueue_ComputeEnvironments_externalOrderUpdate (543.04s)
--- PASS: TestAccBatchJobQueue_basicCEO (547.48s)
--- PASS: TestAccBatchJobQueue_priority (705.88s)
--- PASS: TestAccBatchJobQueue_state (716.18s)
--- PASS: TestAccBatchJobQueue_ComputeEnvironmentOrder_multiple (767.04s)
--- PASS: TestAccBatchJobQueue_schedulingPolicy (770.29s)
--- PASS: TestAccBatchJobQueue_ComputeEnvironments_multiple (778.00s)
--- PASS: TestAccBatchJobQueue_tags (801.21s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/batch      803.366s
FAIL
make: *** [testacc] Error 1
```

### CODE REVIEW

File: internal/service/batch/job_queue.go [hunk 1]
```diff
@@ -366,7 +422,7 @@ func (r *resourceJobQueueData) refreshFromOutput(ctx context.Context, out *batch
 	return diags
 }
 
-func expandComputeEnvironmentOrder(order []string) (envs []*batch.ComputeEnvironmentOrder) {
+func expandComputeEnvironments(order []string) (envs []*batch.ComputeEnvironmentOrder) {
```
Comment (drewmullen) [inline internal/service/batch/job_queue.go:425]: renamed only for clarity with the conflicting parameter

File: internal/service/batch/job_queue_schema.go [hunk 2]
```diff
@@ -29,7 +29,7 @@ func jobQueueSchema0(ctx context.Context) schema.Schema {
 			"arn": framework.ARNAttributeComputedOnly(),
 			"compute_environments": schema.ListAttribute{
 				ElementType: types.StringType,
-				Required:    true,
+				// Required:    true,
```
Comment (danquack) [inline internal/service/batch/job_queue_schema.go:32]: Can we remove this instead of commenting?
```suggestion
```

File: internal/service/batch/job_queue.go [hunk 3]
```diff
@@ -206,14 +244,22 @@ func (r *resourceJobQueue) Update(ctx context.Context, request resource.UpdateRe
...
-		JobQueue: flex.StringFromFramework(ctx, plan.Name),
+		JobQueue: flex.StringFromFramework(ctx, plan.JobQueueName),
 	}
 
-	if !plan.ComputeEnvironments.Equal(state.ComputeEnvironments) {
-		ceo := flex.ExpandFrameworkStringValueList(ctx, plan.ComputeEnvironments)
-		input.ComputeEnvironmentOrder = expandComputeEnvironmentOrder(ceo)
+	if !plan.ComputeEnvironmentOrder.IsNull() {
+		if !plan.ComputeEnvironmentOrder.Equal(state.ComputeEnvironmentOrder) {
+			flex.Expand(ctx, plan.ComputeEnvironmentOrder, &input.ComputeEnvironmentOrder)
```
Comment (danquack) [inline internal/service/batch/job_queue.go:252]: Can we combine this to make the check a single vs a nested if? No additional checks are done inside the first if.

If you take this suggestion, you'll have a dangling `}`. Suggestions wouldn't let me review it.
```suggestion
	if !plan.ComputeEnvironmentOrder.IsNull() && !plan.ComputeEnvironmentOrder.Equal(state.ComputeEnvironmentOrder) {
			flex.Expand(ctx, plan.ComputeEnvironmentOrder, &input.ComputeEnvironmentOrder)
```

File: internal/service/batch/job_queue_schema.go (hunk 2 above)
Comment (drewmullen) [reply internal/service/batch/job_queue_schema.go:32]: good catch. this should still be included - adding back now!

File: internal/service/batch/job_queue.go (hunk 3 above)
Comment (drewmullen) [reply internal/service/batch/job_queue.go:252]: good suggestion. retrying tests now

Comment (drewmullen) [reply internal/service/batch/job_queue.go:252]: cant take the suggestion directly due to the `}`. sorry! tests passed so taking the suggestion

**Review by AdamTylerLynch — APPROVED** [review]
LGTM 🚀

**Comment by nithinvenugopal** [comment]
@danquack @drewmullen any update on this?

**Comment by drewmullen** [comment]
@nithinvenugopal just waiting for it to be merged and released. Not up to me /shrug
