### PR TITLE
sweeper/aws_elasticache_global_replication_group: Reduce run time during failures

### LINKED ISSUE #18625: resource/aws_elasticache_replication_group: Acceptance test failure reading tags on global rep group primary
### Description

Acceptance tests for `aws_elasticache_replication_group` fail when reading tags on the primary replication group on a global replication group with the following error

```
Error: error listing tags for resource (arn:aws:elasticache:us-west-2:*******:cluster:tf-acc-test-5114468746919192496-s-001): InvalidReplicationGroupState: Replication Group of tf-acc-test-5114468746919192496-s-001 is not available.
```

To solve this, tag reading code should handle this error by retrying and the global replication group code should also wait for the primary replication group to be `available`

### Affected Resource

* aws_elasticache_replication_group

### LINKED ISSUE #19438: sweeper/aws_elasticache_global_replication_group: hangs too long if there are problems disassociating members
When sweeping `aws_elasticache_global_replication_group` resources and member `aws_elasticache_replication_group` resources, if there is a problem, the sweeper can hang for a long time across both sweepers. Due to configured timeouts, a single stuck `aws_elasticache_global_replication_group` can cause the 4 hour overall sweeper timeout to be hit. This means that other sweepers, such as `aws_vpc`, may not run.

When the sweeper for `aws_elasticache_global_replication_group` is run, it serially tries to disassociate secondary members before deleting the global replication group. To do the disassociation, it uses the `disassociateElasticacheReplicationGroup` function, which is also used by the `aws_elasticache_replication_group` resource during deletion. This function has a hardcoded timeout of 45 minutes, which makes sense during normal Terraform operation, but should be shorter in a sweeper to allow best-effort without timing out. If the global replication group has two secondary members, the 45 minute timeout may be reached for both.

Regardless of whether the disassociation succeeds, the Delete operation of the `aws_elasticache_global_replication_group` is called. This has a timeout of 20 minutes. If the disassociation has failed, the global replication group deletion will also fail. However, this particular type of failure will retry up to the timeout, since it makes sense during normal Terraform operation.

Once the `aws_elasticache_global_replication_group` sweepers complete, the `aws_elasticache_replication_group` sweeper will run. This sweeper also uses the Delete operation of the resource, which has a default timeout of 40 minutes, though it can be configured through the Terraform `timeouts` block. This will reach the timeout for the primary member. For secondary members, it first tries to disassociate itself from the global replication group, taking 45 minutes, then waits 40 minutes to try to delete itself.

Steps to resolve:

* Make disassociation from global replication group concurrent in sweeper
* Do not attempt to sweep global replication group if disassociation fails
* Make global replication group sweeper concurrent
* Allow sweeper to use lower timeout values for
  * disassociating member from global replication group in `aws_elasticache_global_replication_group` sweeper
  * deleting global replication group
  * deleting member replication group
  * disassociating member replication group in `aws_elasticache_replication_group` sweeper

### Affected Resources

* aws_elasticache_global_replication_group
* aws_elasticache_replication_group

### PR DESCRIPTION
**Pull request by gdavison**
When problems occur during global replication group member disassociation, a single ElastiCache global replication group can cause the sweeper to run for hours.

This PR reduces the wait time for sweepers and adds concurrency to global replication group sweeper steps. It also addresses an issue with reading tags on the global replication group.

Adds `us-east-2` to default sweeper regions, since it's the default "third" acceptance testing region.

Closes #19438
Closes #18625

Output from acceptance testing:

```console
$ make testacc TESTARGS='-run=TestAccAWSElasticacheGlobalReplicationGroup_'

--- PASS: TestAccAWSElasticacheGlobalReplicationGroup_basic (954.30s)
--- PASS: TestAccAWSElasticacheGlobalReplicationGroup_disappears (1008.32s)
--- PASS: TestAccAWSElasticacheGlobalReplicationGroup_Description (1206.08s)
--- PASS: TestAccAWSElasticacheGlobalReplicationGroup_MultipleSecondaries (2957.05s)
--- PASS: TestAccAWSElasticacheGlobalReplicationGroup_ReplaceSecondary_DifferentRegion (3048.89s)
```

```console
$ make sweep SWEEPARGS="-sweep-run=aws_elasticache_replication_group"
2021/06/01 16:52:59 [DEBUG] Running Sweepers for region (us-east-1):
2021/06/01 16:52:59 [DEBUG] Sweeper (aws_elasticache_replication_group) has dependency (aws_elasticache_global_replication_group), running..
2021/06/01 16:52:59 [DEBUG] Running Sweeper (aws_elasticache_global_replication_group) in region (us-east-1)
2021/06/01 16:52:59 [INFO] Attempting to use session-derived credentials
2021/06/01 16:53:00 [INFO] Successfully derived credentials from session
2021/06/01 16:53:00 [INFO] AWS Auth provider used: "CredentialsEndpointProvider"
2021/06/01 16:53:00 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/06/01 16:53:00 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/06/01 16:53:02 [INFO] Deleting ElastiCache Global Replication Group: sgaui-gmdtest4
2021/06/01 16:53:02 [INFO] Deleting ElastiCache Global Replication Group: sgaui-gmdtest3
2021/06/01 16:53:02 [DEBUG] Waiting for state to become: [success]
2021/06/01 16:53:02 [DEBUG] Waiting for state to become: [success]
2021/06/01 16:53:03 [DEBUG] Waiting for state to become: []
2021/06/01 16:53:03 [DEBUG] Waiting for state to become: []
2021/06/01 16:53:33 [TRACE] Waiting 10s before next try
2021/06/01 16:53:33 [TRACE] Waiting 10s before next try
2021/06/01 16:53:44 [DEBUG] Running Sweeper (aws_elasticache_replication_group) in region (us-east-1)
2021/06/01 16:53:44 [DEBUG] Waiting for state to become: [success]
2021/06/01 16:53:44 [DEBUG] Waiting for state to become: [success]
2021/06/01 16:53:45 [DEBUG] Waiting for state to become: []
2021/06/01 16:53:45 [DEBUG] Waiting for state to become: []
2021/06/01 16:54:15 [TRACE] Waiting 10s before next try
2021/06/01 16:54:15 [TRACE] Waiting 10s before next try
...
2021/06/01 16:59:00 [TRACE] Waiting 10s before next try
2021/06/01 16:59:00 [TRACE] Waiting 10s before next try
2021/06/01 16:59:11 [DEBUG] Sweeper (aws_elasticache_global_replication_group) already ran in region (us-east-1)
2021/06/01 16:59:11 Sweeper Tests ran successfully:
	- aws_elasticache_global_replication_group
	- aws_elasticache_replication_group
2021/06/01 16:59:11 [DEBUG] Running Sweepers for region (us-east-2):
2021/06/01 16:59:11 [DEBUG] Sweeper (aws_elasticache_replication_group) has dependency (aws_elasticache_global_replication_group), running..
2021/06/01 16:59:11 [DEBUG] Running Sweeper (aws_elasticache_global_replication_group) in region (us-east-2)
2021/06/01 16:59:11 [INFO] Attempting to use session-derived credentials
2021/06/01 16:59:11 [INFO] Successfully derived credentials from session
2021/06/01 16:59:11 [INFO] AWS Auth provider used: "CredentialsEndpointProvider"
2021/06/01 16:59:11 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/06/01 16:59:11 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/06/01 16:59:13 [DEBUG] Running Sweeper (aws_elasticache_replication_group) in region (us-east-2)
2021/06/01 16:59:14 [DEBUG] Waiting for state to become: [success]
2021/06/01 16:59:14 [DEBUG] Waiting for state to become: []
2021/06/01 16:59:45 [TRACE] Waiting 10s before next try
...
2021/06/01 17:04:20 [TRACE] Waiting 10s before next try
2021/06/01 17:04:31 [DEBUG] Sweeper (aws_elasticache_global_replication_group) already ran in region (us-east-2)
2021/06/01 17:04:31 Sweeper Tests ran successfully:
	- aws_elasticache_global_replication_group
	- aws_elasticache_replication_group
2021/06/01 17:04:31 [DEBUG] Running Sweepers for region (us-west-2):
2021/06/01 17:04:31 [DEBUG] Sweeper (aws_elasticache_replication_group) has dependency (aws_elasticache_global_replication_group), running..
2021/06/01 17:04:31 [DEBUG] Running Sweeper (aws_elasticache_global_replication_group) in region (us-west-2)
2021/06/01 17:04:31 [INFO] Attempting to use session-derived credentials
2021/06/01 17:04:31 [INFO] Successfully derived credentials from session
2021/06/01 17:04:31 [INFO] AWS Auth provider used: "CredentialsEndpointProvider"
2021/06/01 17:04:31 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/06/01 17:04:31 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/06/01 17:04:33 [DEBUG] Running Sweeper (aws_elasticache_replication_group) in region (us-west-2)
2021/06/01 17:04:33 [DEBUG] Waiting for state to become: [success]
2021/06/01 17:04:33 [DEBUG] Waiting for state to become: [success]
2021/06/01 17:04:33 [DEBUG] Waiting for state to become: [success]
2021/06/01 17:04:33 [DEBUG] Waiting for state to become: [success]
2021/06/01 17:04:33 [DEBUG] Waiting for state to become: []
2021/06/01 17:04:33 [DEBUG] Waiting for state to become: []
2021/06/01 17:04:33 [DEBUG] Waiting for state to become: []
2021/06/01 17:04:33 [DEBUG] Waiting for state to become: []
2021/06/01 17:05:04 [TRACE] Waiting 10s before next try
2021/06/01 17:05:04 [TRACE] Waiting 10s before next try
2021/06/01 17:05:04 [TRACE] Waiting 10s before next try
2021/06/01 17:05:04 [TRACE] Waiting 10s before next try
...
2021/06/01 17:10:45 [TRACE] Waiting 10s before next try
2021/06/01 17:10:46 [TRACE] Waiting 10s before next try
2021/06/01 17:10:56 [TRACE] Waiting 10s before next try
2021/06/01 17:10:57 [TRACE] Waiting 10s before next try
2021/06/01 17:11:07 [DEBUG] Sweeper (aws_elasticache_global_replication_group) already ran in region (us-west-2)
2021/06/01 17:11:07 Sweeper Tests ran successfully:
	- aws_elasticache_global_replication_group
	- aws_elasticache_replication_group
ok  	github.com/terraform-providers/terraform-provider-aws/aws	1091.045s
```

### CODE REVIEW

File: aws/resource_aws_elasticache_replication_group.go [hunk 1]
```diff
@@ -436,6 +436,16 @@ func resourceAwsElasticacheReplicationGroupCreate(d *schema.ResourceData, meta i
 		return fmt.Errorf("error creating ElastiCache Replication Group (%s): waiting for completion: %w", d.Id(), err)
 	}
 
+	if v, ok := d.GetOk("global_replication_group_id"); ok {
```
Comment (ewbankkit) [inline aws/resource_aws_elasticache_replication_group.go:439]: Does this address the tags issue you mention in the PR's initial comment?

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

##### Commercial

```console
% ACCTEST_TIMEOUT=600m make testacc TEST=./aws TESTARGS='-run=TestAccAWSElasticacheGlobalReplicationGroup_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSElasticacheGlobalReplicationGroup_ -timeout 600m
=== RUN   TestAccAWSElasticacheGlobalReplicationGroup_basic
=== PAUSE TestAccAWSElasticacheGlobalReplicationGroup_basic
=== RUN   TestAccAWSElasticacheGlobalReplicationGroup_Description
=== PAUSE TestAccAWSElasticacheGlobalReplicationGroup_Description
=== RUN   TestAccAWSElasticacheGlobalReplicationGroup_disappears
=== PAUSE TestAccAWSElasticacheGlobalReplicationGroup_disappears
=== RUN   TestAccAWSElasticacheGlobalReplicationGroup_MultipleSecondaries
=== PAUSE TestAccAWSElasticacheGlobalReplicationGroup_MultipleSecondaries
=== RUN   TestAccAWSElasticacheGlobalReplicationGroup_ReplaceSecondary_DifferentRegion
=== PAUSE TestAccAWSElasticacheGlobalReplicationGroup_ReplaceSecondary_DifferentRegion
=== CONT  TestAccAWSElasticacheGlobalReplicationGroup_basic
=== CONT  TestAccAWSElasticacheGlobalReplicationGroup_MultipleSecondaries
=== CONT  TestAccAWSElasticacheGlobalReplicationGroup_Description
=== CONT  TestAccAWSElasticacheGlobalReplicationGroup_disappears
=== CONT  TestAccAWSElasticacheGlobalReplicationGroup_ReplaceSecondary_DifferentRegion
--- PASS: TestAccAWSElasticacheGlobalReplicationGroup_disappears (848.98s)
--- PASS: TestAccAWSElasticacheGlobalReplicationGroup_basic (850.74s)
--- PASS: TestAccAWSElasticacheGlobalReplicationGroup_Description (871.29s)
--- PASS: TestAccAWSElasticacheGlobalReplicationGroup_MultipleSecondaries (2436.46s)
--- PASS: TestAccAWSElasticacheGlobalReplicationGroup_ReplaceSecondary_DifferentRegion (2842.76s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	2846.281s
% TEST=./aws SWEEP=eu-west-1,us-west-1 SWEEPARGS=-sweep-run=aws_elasticache_replication_group make sweep   
WARNING: This will destroy infrastructure. Use only in development accounts.
go test ./aws -v -sweep=eu-west-1,us-west-1 -sweep-run=aws_elasticache_replication_group -timeout 60m
2021/06/10 09:17:13 [DEBUG] Running Sweepers for region (eu-west-1):
2021/06/10 09:17:13 [DEBUG] Sweeper (aws_elasticache_replication_group) has dependency (aws_elasticache_global_replication_group), running..
2021/06/10 09:17:13 [DEBUG] Running Sweeper (aws_elasticache_global_replication_group) in region (eu-west-1)
2021/06/10 09:17:13 [INFO] AWS Auth provider used: "EnvProvider"
2021/06/10 09:17:13 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/06/10 09:17:13 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/06/10 09:17:15 [DEBUG] Running Sweeper (aws_elasticache_replication_group) in region (eu-west-1)
2021/06/10 09:17:15 [DEBUG] No ElastiCache Replicaton Groups to sweep
2021/06/10 09:17:15 [DEBUG] Sweeper (aws_elasticache_global_replication_group) already ran in region (eu-west-1)
2021/06/10 09:17:15 Sweeper Tests ran successfully:
	- aws_elasticache_global_replication_group
	- aws_elasticache_replication_group
2021/06/10 09:17:15 [DEBUG] Running Sweepers for region (us-west-1):
2021/06/10 09:17:15 [DEBUG] Running Sweeper (aws_elasticache_global_replication_group) in region (us-west-1)
2021/06/10 09:17:15 [INFO] AWS Auth provider used: "EnvProvider"
2021/06/10 09:17:15 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/06/10 09:17:15 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/06/10 09:17:17 [DEBUG] Sweeper (aws_elasticache_replication_group) has dependency (aws_elasticache_global_replication_group), running..
2021/06/10 09:17:17 [DEBUG] Sweeper (aws_elasticache_global_replication_group) already ran in region (us-west-1)
2021/06/10 09:17:17 [DEBUG] Running Sweeper (aws_elasticache_replication_group) in region (us-west-1)
2021/06/10 09:17:18 [DEBUG] No ElastiCache Replicaton Groups to sweep
2021/06/10 09:17:18 Sweeper Tests ran successfully:
	- aws_elasticache_replication_group
	- aws_elasticache_global_replication_group
ok  	github.com/terraform-providers/terraform-provider-aws/aws	7.631s
```

##### GovCloud

```
--- PASS: TestAccAWSElasticacheGlobalReplicationGroup_disappears (880.36s)
--- PASS: TestAccAWSElasticacheGlobalReplicationGroup_basic (915.24s)
--- PASS: TestAccAWSElasticacheGlobalReplicationGroup_Description (939.57s)
```
