### PR TITLE
Sweeper: exclude replication group member clusters from aws_elasticache_cluster sweeper

### LINKED ISSUE #17647: Sweeper: aws_elasticache_cluster does not correctly handle Cluster that is last member of Replication Group
The `aws_elasticache_cluster` sweeper depends on the `aws_elasticache_replication_group` sweeper. If the `aws_elasticache_replication_group` fails for some reason, the member clusters still exists and will be picked up by the `aws_elasticache_cluster` sweeper.

If the Cluster sweeper tries to delete the last member Cluster in a Replication Group, it receives the following error:

```
InvalidCacheClusterState: Cannot delete the cache cluster since it is the only member of a replication group. Delete the replication group instead.
```

Aside from one particular case, the `InvalidCacheClusterState` error is retried for 5 minutes.

### Affected Resource

* aws_elasticache_cluster

### PR DESCRIPTION
**Pull request by gdavison**
Prevents retry when trying to delete the last member cluster from a replication group.

Excludes replication group member clusters from sweeper.

Closes #17647

### CODE REVIEW

File: aws/resource_aws_elasticache_cluster_test.go [hunk 1]
```diff
@@ -47,24 +54,31 @@ func testSweepElasticacheClusters(region string) error {
 
 			log.Printf("[INFO] Deleting ElastiCache Cluster: %s", id)
 			err := deleteElasticacheCacheCluster(conn, id, "")
+			if tfawserr.ErrMessageContains(err, elasticache.ErrCodeInvalidCacheClusterStateFault, "only member of a replication group") {
+				log.Printf("[WARN] ElastiCache Cache Cluster (%s) is member of a Replication Group. Ignoring. %s", id, err)
+				continue
+			}
```
Comment (anGie44) [inline aws/resource_aws_elasticache_cluster_test.go:60]: qq: if we're filtering these specific clusters out in the `DescribeCacheClustersInput` , is it still possible to hit this type of error? doesn't hurt to catch the error tho 👍

**Review by anGie44 — APPROVED** [review]
Looks great! just one small q more for my own curiosity

File: aws/resource_aws_elasticache_cluster_test.go (hunk 1 above)
Comment (gdavison) [reply aws/resource_aws_elasticache_cluster_test.go:60]: Good catch, it's redundant since they're filtered out from the results

Comment (anGie44) [reply aws/resource_aws_elasticache_cluster_test.go]: gotchu, sounds good! tho i'm always cautious with AWS APIs 😅
