### PR TITLE
tests/sweeper/route53_resolver_dnssec_confg: update sweeper and waiter func

### LINKED ISSUE #17502: tests/sweeper/route53_resolver_dnssec_config: failing with ValidationException
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Sweeper(s)

* aws_route53_resolver_dnssec_config

### Sweeper Output
```
* error deleting Route53 Resolver Resolver Dnssec config (vpc-03ccceacde53941f9): 
 ValidationException: 1 validation error detected: Value 'DISABLED' at 'validation' failed to satisfy constraint: Member must satisfy enum value set: [ENABLE, DISABLE]
```

### Expected Behavior

* sweeper to run successfully

### Actual Behavior

* sweeper failing with multiple validation exceptions

### PR DESCRIPTION
**Pull request by anGie44**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #17502

Output from acceptance testing:

```
--- PASS: TestAccAWSRoute53ResolverDnssecConfig_basic (392.59s)
--- PASS: TestAccAWSRoute53ResolverDnssecConfig_disappear (400.41s)
```

Output from sweeper:
```
$ make sweep SWEEPARGS='-sweep-run=aws_route53_resolver_dnssec_config'
WARNING: This will destroy infrastructure. Use only in development accounts.
go test ./aws -v -sweep=us-east-1,us-west-2 -sweep-run=aws_route53_resolver_dnssec_config -timeout 60m
2021/02/08 00:27:03 [DEBUG] Running Sweepers for region (us-east-1):
2021/02/08 00:27:03 [DEBUG] Running Sweeper (aws_route53_resolver_dnssec_config) in region (us-east-1)
2021/02/08 00:27:03 [INFO] AWS Auth provider used: "EnvProvider"
2021/02/08 00:27:03 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/02/08 00:27:03 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/02/08 00:27:03 Sweeper Tests ran successfully:
	- aws_route53_resolver_dnssec_config
2021/02/08 00:27:03 [DEBUG] Running Sweepers for region (us-west-2):
2021/02/08 00:27:03 [DEBUG] Running Sweeper (aws_route53_resolver_dnssec_config) in region (us-west-2)
2021/02/08 00:27:03 [INFO] AWS Auth provider used: "EnvProvider"
2021/02/08 00:27:03 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/02/08 00:27:03 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/02/08 00:27:04 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-44665e87ddf630a4
2021/02/08 00:27:04 [DEBUG] Deleting Route53 Resolver DNSSEC config: rdsc-44665e87ddf630a4
2021/02/08 00:27:05 [DEBUG] Waiting for state to become: []
2021/02/08 00:27:05 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-4579d595f3433114
2021/02/08 00:27:05 [DEBUG] Deleting Route53 Resolver DNSSEC config: rdsc-4579d595f3433114
2021/02/08 00:27:05 [DEBUG] Waiting for state to become: []
2021/02/08 00:27:06 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-47897780bb63316
2021/02/08 00:27:06 [DEBUG] Deleting Route53 Resolver DNSSEC config: rdsc-47897780bb63316
2021/02/08 00:27:06 [DEBUG] Waiting for state to become: []
2021/02/08 00:27:06 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-55fcaceabe353ea1
2021/02/08 00:27:06 [DEBUG] Deleting Route53 Resolver DNSSEC config: rdsc-55fcaceabe353ea1
2021/02/08 00:27:07 [DEBUG] Waiting for state to become: []
2021/02/08 00:27:07 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-5610e6442a993705
2021/02/08 00:27:07 [DEBUG] Deleting Route53 Resolver DNSSEC config: rdsc-5610e6442a993705
2021/02/08 00:27:08 [DEBUG] Waiting for state to become: []
2021/02/08 00:27:08 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-5983758fc2da3dc7
2021/02/08 00:27:08 [DEBUG] Deleting Route53 Resolver DNSSEC config: rdsc-5983758fc2da3dc7
2021/02/08 00:27:08 [DEBUG] Waiting for state to become: []
2021/02/08 00:27:09 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-5c3b43f4a863344b
2021/02/08 00:27:09 [DEBUG] Deleting Route53 Resolver DNSSEC config: rdsc-5c3b43f4a863344b
2021/02/08 00:27:09 [DEBUG] Waiting for state to become: []
2021/02/08 00:27:09 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-61a2a098b0fa34a2
2021/02/08 00:27:09 [DEBUG] Deleting Route53 Resolver DNSSEC config: rdsc-61a2a098b0fa34a2
2021/02/08 00:27:10 [DEBUG] Waiting for state to become: []
2021/02/08 00:27:10 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-6809ce740db53254
2021/02/08 00:27:10 [DEBUG] Deleting Route53 Resolver DNSSEC config: rdsc-6809ce740db53254
2021/02/08 00:27:10 [DEBUG] Waiting for state to become: []
2021/02/08 00:27:11 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-6e4da6e72ffc3d4d
2021/02/08 00:27:11 [DEBUG] Deleting Route53 Resolver DNSSEC config: rdsc-6e4da6e72ffc3d4d
2021/02/08 00:27:11 [DEBUG] Waiting for state to become: []
2021/02/08 00:27:11 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-6fb036d9edea3885
2021/02/08 00:27:11 [DEBUG] Deleting Route53 Resolver DNSSEC config: rdsc-6fb036d9edea3885
2021/02/08 00:27:12 [DEBUG] Waiting for state to become: []
2021/02/08 00:27:12 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-74d592e94f593826
2021/02/08 00:27:12 [DEBUG] Deleting Route53 Resolver DNSSEC config: rdsc-74d592e94f593826
2021/02/08 00:27:12 [DEBUG] Waiting for state to become: []
2021/02/08 00:27:13 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-81735941ac2e3692
2021/02/08 00:27:13 [DEBUG] Deleting Route53 Resolver DNSSEC config: rdsc-81735941ac2e3692
2021/02/08 00:27:13 [DEBUG] Waiting for state to become: []
2021/02/08 00:27:14 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-8d60d79360763ca8
2021/02/08 00:27:14 [DEBUG] Deleting Route53 Resolver DNSSEC config: rdsc-8d60d79360763ca8
2021/02/08 00:27:14 [DEBUG] Waiting for state to become: []
2021/02/08 00:27:14 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-8ebd95515dc43a06
2021/02/08 00:27:14 [DEBUG] Deleting Route53 Resolver DNSSEC config: rdsc-8ebd95515dc43a06
2021/02/08 00:27:15 [DEBUG] Waiting for state to become: []
2021/02/08 00:27:15 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-8ec0eda94c0f3ba9
2021/02/08 00:27:15 [DEBUG] Deleting Route53 Resolver DNSSEC config: rdsc-8ec0eda94c0f3ba9
2021/02/08 00:27:15 [DEBUG] Waiting for state to become: []
2021/02/08 00:27:16 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-976bf7d274173cc5
2021/02/08 00:27:16 [DEBUG] Deleting Route53 Resolver DNSSEC config: rdsc-976bf7d274173cc5
2021/02/08 00:27:16 [DEBUG] Waiting for state to become: []
2021/02/08 00:27:16 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-9a6eeca8c78138dc
2021/02/08 00:27:16 [DEBUG] Deleting Route53 Resolver DNSSEC config: rdsc-9a6eeca8c78138dc
2021/02/08 00:27:17 [DEBUG] Waiting for state to become: []
2021/02/08 00:27:17 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-9cca9a70eaee33ab
2021/02/08 00:27:17 [DEBUG] Deleting Route53 Resolver DNSSEC config: rdsc-9cca9a70eaee33ab
2021/02/08 00:27:17 [DEBUG] Waiting for state to become: []
2021/02/08 00:27:18 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-a37d02db49713d61
2021/02/08 00:27:18 [DEBUG] Deleting Route53 Resolver DNSSEC config: rdsc-a37d02db49713d61
2021/02/08 00:27:19 [DEBUG] Waiting for state to become: []
2021/02/08 00:27:19 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-a83283394de33deb
2021/02/08 00:27:19 [DEBUG] Deleting Route53 Resolver DNSSEC config: rdsc-a83283394de33deb
2021/02/08 00:27:20 [DEBUG] Waiting for state to become: []
2021/02/08 00:27:21 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-b1624c3550133ed2
2021/02/08 00:27:21 [DEBUG] Deleting Route53 Resolver DNSSEC config: rdsc-b1624c3550133ed2
2021/02/08 00:27:21 [DEBUG] Waiting for state to become: []
2021/02/08 00:27:22 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-b571d25b54a534ab
2021/02/08 00:27:22 [DEBUG] Deleting Route53 Resolver DNSSEC config: rdsc-b571d25b54a534ab
2021/02/08 00:27:22 [DEBUG] Waiting for state to become: []
2021/02/08 00:27:23 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-cbeb8e156db435d3
2021/02/08 00:27:23 [DEBUG] Deleting Route53 Resolver DNSSEC config: rdsc-cbeb8e156db435d3
2021/02/08 00:27:23 [DEBUG] Waiting for state to become: []
2021/02/08 00:27:23 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-cc63a23ee5503471
2021/02/08 00:27:23 [DEBUG] Deleting Route53 Resolver DNSSEC config: rdsc-cc63a23ee5503471
2021/02/08 00:27:24 [DEBUG] Waiting for state to become: []
2021/02/08 00:27:24 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-d22988f9bfc730e3
2021/02/08 00:27:24 [DEBUG] Deleting Route53 Resolver DNSSEC config: rdsc-d22988f9bfc730e3
2021/02/08 00:27:24 [DEBUG] Waiting for state to become: []
2021/02/08 00:27:25 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-d469ac7ff2df3cdc
2021/02/08 00:27:25 [DEBUG] Deleting Route53 Resolver DNSSEC config: rdsc-d469ac7ff2df3cdc
2021/02/08 00:27:25 [DEBUG] Waiting for state to become: []
2021/02/08 00:27:25 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-d64d397c8d903521
2021/02/08 00:27:25 [DEBUG] Deleting Route53 Resolver DNSSEC config: rdsc-d64d397c8d903521
2021/02/08 00:27:26 [DEBUG] Waiting for state to become: []
2021/02/08 00:27:26 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-dc5013564a6f3140
2021/02/08 00:27:26 [DEBUG] Deleting Route53 Resolver DNSSEC config: rdsc-dc5013564a6f3140
2021/02/08 00:27:27 [DEBUG] Waiting for state to become: []
2021/02/08 00:27:27 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-e50310188c3f3594
2021/02/08 00:27:27 [DEBUG] Deleting Route53 Resolver DNSSEC config: rdsc-e50310188c3f3594
2021/02/08 00:27:27 [DEBUG] Waiting for state to become: []
2021/02/08 00:27:28 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-e7a2163479cf369d
2021/02/08 00:27:28 [DEBUG] Deleting Route53 Resolver DNSSEC config: rdsc-e7a2163479cf369d
2021/02/08 00:27:28 [DEBUG] Waiting for state to become: []
2021/02/08 00:27:28 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-e836144711563104
2021/02/08 00:27:28 [DEBUG] Deleting Route53 Resolver DNSSEC config: rdsc-e836144711563104
2021/02/08 00:27:29 [DEBUG] Waiting for state to become: []
2021/02/08 00:27:29 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-ea8188ddb68c3613
2021/02/08 00:27:29 [DEBUG] Deleting Route53 Resolver DNSSEC config: rdsc-ea8188ddb68c3613
2021/02/08 00:27:29 [DEBUG] Waiting for state to become: []
2021/02/08 00:27:30 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-ee93af43e5d3ca8
2021/02/08 00:27:30 [DEBUG] Deleting Route53 Resolver DNSSEC config: rdsc-ee93af43e5d3ca8
2021/02/08 00:27:30 [DEBUG] Waiting for state to become: []
2021/02/08 00:27:30 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-f29607922f723719
2021/02/08 00:27:30 [DEBUG] Deleting Route53 Resolver DNSSEC config: rdsc-f29607922f723719
2021/02/08 00:27:31 [DEBUG] Waiting for state to become: []
2021/02/08 00:27:31 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-f4a201d428733058
2021/02/08 00:27:31 [DEBUG] Deleting Route53 Resolver DNSSEC config: rdsc-f4a201d428733058
2021/02/08 00:27:31 [DEBUG] Waiting for state to become: []
2021/02/08 00:27:32 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-f85d2722829530d7
2021/02/08 00:27:32 [DEBUG] Deleting Route53 Resolver DNSSEC config: rdsc-f85d2722829530d7
2021/02/08 00:27:32 [DEBUG] Waiting for state to become: []
2021/02/08 00:27:32 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-fb4581c1fdfc3b5b
2021/02/08 00:27:32 [DEBUG] Deleting Route53 Resolver DNSSEC config: rdsc-fb4581c1fdfc3b5b
2021/02/08 00:27:33 [DEBUG] Waiting for state to become: []
2021/02/08 00:27:33 Sweeper Tests ran successfully:
	- aws_route53_resolver_dnssec_config
ok  	github.com/terraform-providers/terraform-provider-aws/aws	36.423s
```

```sh
 $ aws route53resolver list-resolver-dnssec-configs

{
    "ResolverDnssecConfigs": []
}
```

### CODE REVIEW

File: aws/resource_aws_route53_resolver_dnssec_config.go [hunk 1]
```diff
@@ -110,22 +111,80 @@ func resourceAwsRoute53ResolverDnssecConfigRead(d *schema.ResourceData, meta int
...
-	})
-	if isAWSErr(err, route53resolver.ErrCodeResourceNotFoundException, "") {
+	// To delete a Route53 ResolverDnssecConfig, it must be:
+	// (1) updated to a "DISABLED" state
+	// (2) updated again to be permanently removed
+	//
+	// To determine how many Updates are required,
+	// we first find the config by ID and proceed as follows:
+
+	config, err := finder.ResolverDnssecConfigByID(conn, d.Id())
```
Comment (anGie44) [inline aws/resource_aws_route53_resolver_dnssec_config.go:121]: i haven't seen much usage of a `Get` method here in the resource _Delete_, but might be appropriate given the Route53 Resolver API's version of "delete" for this particular resource is a 2-step sequence of "Updates". or in this case is it sufficient to just have the resource achieve the "disabled" state? and handle as needed in our sweepers?

File: aws/resource_aws_route53_resolver_dnssec_config_test.go [hunk 2]
```diff
@@ -178,34 +167,21 @@ func testAccCheckRoute53ResolverDnssecConfigExists(n string, config *route53reso
...
-		})
+		config, err := finder.ResolverDnssecConfigByID(conn, id)
 
 		if err != nil {
 			return err
 		}
 
 		if config == nil {
-			return fmt.Errorf("No Route 53 Resolver Dnssec config found")
+			return fmt.Errorf("Route53 Resolver Dnssec config (%s) not found", id)
```
Comment (bflad) [inline aws/resource_aws_route53_resolver_dnssec_config_test.go:180]: Super nit 😭 : Route 53 does in fact have a space: https://aws.amazon.com/route53/

```suggestion
			return fmt.Errorf("Route 53 Resolver Dnssec config (%s) not found", id)
```

File: aws/resource_aws_route53_resolver_dnssec_config_test.go [hunk 3]
```diff
@@ -178,34 +167,21 @@ func testAccCheckRoute53ResolverDnssecConfigExists(n string, config *route53reso
...
 		}
 
 		if aws.StringValue(config.ValidationStatus) != route53resolver.ResolverDNSSECValidationStatusEnabled {
-			return fmt.Errorf("Route 53 Resolver Dnssec config (%s) is not enabled", aws.StringValue(config.Id))
+			return fmt.Errorf("Route53 Resolver Dnssec config (%s) is not enabled", aws.StringValue(config.Id))
```
Comment (bflad) [inline aws/resource_aws_route53_resolver_dnssec_config_test.go:184]:
```suggestion
			return fmt.Errorf("Route 53 Resolver Dnssec config (%s) is not enabled", aws.StringValue(config.Id))
```

**Review by bflad — APPROVED** [review]
Looks good 🚀 

Output from acceptance testing in AWS Commercial:

```
--- PASS: TestAccAWSRoute53ResolverDnssecConfig_disappear (398.10s)
--- PASS: TestAccAWSRoute53ResolverDnssecConfig_basic (410.76s)
```

Output from sweeper in AWS Commercial:

```
2021/02/10 11:06:36 [DEBUG] Running Sweepers for region (us-west-2):
2021/02/10 11:06:36 [DEBUG] Running Sweeper (aws_route53_resolver_dnssec_config) in region (us-west-2)
2021/02/10 11:06:37 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-235f71ae56873010
2021/02/10 11:06:38 [INFO] Deleting Route53 Resolver Dnssec config: rdsc-e04866f5720a3b76
2021/02/10 11:06:39 Sweeper Tests ran successfully:
	- aws_route53_resolver_dnssec_config
2021/02/10 11:06:39 [DEBUG] Running Sweepers for region (us-east-1):
2021/02/10 11:06:39 [DEBUG] Running Sweeper (aws_route53_resolver_dnssec_config) in region (us-east-1)
2021/02/10 11:06:40 Sweeper Tests ran successfully:
	- aws_route53_resolver_dnssec_config
ok  	github.com/terraform-providers/terraform-provider-aws/aws	5.632s
```

File: aws/resource_aws_route53_resolver_dnssec_config.go (hunk 1 above)
Comment (bflad) [reply aws/resource_aws_route53_resolver_dnssec_config.go:121]: Some other resources rely on existing attribute state during deletion, which is used to validate the planned assumptions, e.g.

- Resource is disabled and that state is saved
- Resource is planned for destroy
- (Outside Terraform) Resource is re-enabled
- Resource destroy occurs

In this case, the resource would skip the disable step (due to the planned state) and properly return the error about needing to disable first.

Another way to avoid read on delete is to react to error messages similar to the `aws_cloudfront_distribution` resource. In that case, it automatically disables the distribution if it receives the error message about needing to be disabled first.

Using the planned attribute state is probably what these resources _should_ do in most cases, but it is hard to enforce across the provider.
