### PR TITLE
resource/aws_lakeformation_permissions: Allow use with IAM Identity Center Groups

### LINKED ISSUE #44574: r/aws_lakeformation_permissions: Inconsistent read behavior with non-IAM principals
### Terraform and AWS Provider Version

```console
terraform -v
Terraform v1.14.0-beta1
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v6.15.0
```

### Affected Resource(s) or Data Source(s)

- `aws_lakeformation_permissions`

### Expected Behavior

Managing permissions for non-IAM principals (e.g. Identity Center users or groups) functions identically to IAM principals.

### Actual Behavior

The read operation fails after successfully creating the permissions. I believe this is a product of inconsistent behavior in the [`ListPermission` API][1] when the principal is an identity center user or group versus an IAM principal.

Here is an example of the ListPermissions API response with no filters, displaying the permissions I’ve configured for both the IDC group and an IAM role.

```
% aws lakeformation list-permissions
{
    "PrincipalResourcePermissions": [
        {
            "Principal": {
                "DataLakePrincipalIdentifier": "arn:aws:iam::<redacted>:role/provider-acc-testing-role"
            },
            "Resource": {
                "Catalog": {
                    "Id": "<redacted>"
                }
            },
            "Permissions": [
                "DESCRIBE"
            ],
            "PermissionsWithGrantOption": [],
            "LastUpdated": "2025-10-06T16:21:44.566000-04:00",
            "LastUpdatedBy": "arn:aws:iam::<redacted>:user/jebaker"
        },
        {
            "Principal": {
                "DataLakePrincipalIdentifier": "arn:aws:identitystore:::group/f48884f8-30e1-7057-0c44-848c0aca4ed2"
            },
            "Resource": {
                "Catalog": {
                    "Id": "<redacted>"
                }
            },
            "Permissions": [
                "DESCRIBE"
            ],
            "PermissionsWithGrantOption": [],
            "LastUpdated": "2025-10-06T16:09:54.675000-04:00",
            "LastUpdatedBy": "arn:aws:iam::<redacted>:user/jebaker"
        }
    ],
    "NextToken": "eyJzaG91bGRRdWVyeUFsbFRhYmxlc1Blcm1pc3Npb25zIjpmYWxzZSwic2hvdWxkUXVlcnlBY2NvdW50UGVybWlzc2lvbnMiOnRydWUsInNob3VsZFF1ZXJ5QWxsSUFNUHJpbmNpcGFsUGVybWlzc2lvbnMiOmZhbHNlLCJzaG91bGRRdWVyeUNyb3NzQWNjb3VudFBlcm1pc3Npb25zRm9yQ2F0YWxvZ1Jlc291cmNlIjpmYWxzZX0="
}
```

When attempting to use the `--principal` and `--resource` flags, the result for the IAM role returns what we’d expect, just a single permission entry for the catalog-based permission.

```
% aws lakeformation list-permissions --principal DataLakePrincipalIdentifier=arn:aws:iam::<redacted>:role/provider-acc-testing-role --resource Catalog={}
{
    "PrincipalResourcePermissions": [
        {
            "Principal": {
                "DataLakePrincipalIdentifier": "arn:aws:iam::<redacted>:role/provider-acc-testing-role"
            },
            "Resource": {
                "Catalog": {
                    "Id": "<redacted>"
                }
            },
            "Permissions": [
                "DESCRIBE"
            ],
            "PermissionsWithGrantOption": []
        }
    ]
}
```

However, using the same flags but swapping the IAM role ARN for the IDC group returns no results.

```
% aws lakeformation list-permissions --principal DataLakePrincipalIdentifier=arn:aws:identitystore:::group/f48884f8-30e1-7057-0c44-848c0aca4ed2 --resource Catalog={}
{
    "PrincipalResourcePermissions": []
}
```

In conjunction with this issue I'll be opening a support case with AWS to clarify the expected behavior of this API. If it is determined to be the correct/expected behavior of the AWS API, the provider will need to implement an alternative approach to reading permissions back for non-IAM principals. 

[1]: https://docs.aws.amazon.com/lake-formation/latest/APIReference/API_ListPermissions.html

### Relevant Error/Panic Output

```
Error: reading Lake Formation permissions: timeout while waiting for state to become  
'AVAILABLE' (timeout: 1m0s)  
```

### Sample Terraform Configuration

<details open>
<summary>Click to expand configuration</summary>

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
  }
}

# Configure the AWS Provider
provider "aws" {}

resource "aws_lakeformation_permissions" "test" {
  principal        = "arn:aws:identitystore:::group/<replace-with-valid-id>"
  permissions      = ["DESCRIBE"]
  catalog_resource = true
}
```
</details>

### Steps to Reproduce

1. Ensure LakeFormation is configured [to operate with Identity Center](https://docs.aws.amazon.com/lake-formation/latest/dg/connect-lf-identity-center.html).
2. Replace the configuration above with a valid, existing identitystore group ID.
3. `terraform apply` and observe read timeout. Permissions have been successfully created when viewed in the console.

### Important Facts and References

Similar behavior has been noted for OU's in this comment: https://github.com/hashicorp/terraform-provider-aws/issues/38982#issuecomment-2766558597

### PR DESCRIPTION
**Pull request by gdavison**
## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the library.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

### Description

When Lake Formation Permissions are configured for an IAM Identity Center Group, creation of the resource times out instead of completing.

The API for reading permissions, `ListPermissions` does not support IAM Identity Center Group ARNs as the principal. Filtering in this case must be done in the provider.

Fixes the error in the resource type `aws_lakeformation_permissions` and the associated data source type.

Also adds basic support for the resource type `aws_lakeformation_identity_center_configuration`. A complete implementation will be added in a future PR, tracked by #44866

### Relations

Closes #44574

### Output from Acceptance Testing

```console
% make testacc PKG=lakeformation TESTS=TestAccLakeFormation_serial/Permissions

--- PASS: TestAccLakeFormation_serial (1050.10s)
    --- PASS: TestAccLakeFormation_serial/PermissionsTable (294.27s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTable/iamAllowed (62.53s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTable/iamPrincipals (14.28s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTable/implicit (30.44s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTable/multipleRoles (22.89s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTable/selectOnly (25.00s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTable/wildcardNoSelect (22.76s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTable/wildcardSelectOnly (23.45s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTable/wildcardSelectPlus (30.65s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTable/basic (22.94s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTable/selectPlus (22.87s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTable/nonIAMPrincipals (16.46s)
    --- PASS: TestAccLakeFormation_serial/PermissionsTableWithColumns (149.62s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTableWithColumns/wildcardSelectOnly (22.68s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTableWithColumns/wildcardSelectPlus (22.80s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTableWithColumns/basic (51.10s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTableWithColumns/implicit (30.26s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTableWithColumns/wildcardExcludedColumns (22.78s)
    --- PASS: TestAccLakeFormation_serial/PermissionsBasic (402.76s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/databaseIAMPrincipals (13.44s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/databaseMultiple (22.39s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/dataCellsFilter (23.00s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/dataLocation (22.12s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/disappears (83.57s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/lfTag (29.44s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/lfTagPolicyMultiple (29.64s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/database (23.63s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/databaseIAMAllowed (90.21s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/lfTagPolicy (21.64s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/nonIAMPrincipals (14.51s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/basic (29.16s)
    --- PASS: TestAccLakeFormation_serial/PermissionsDataSource (203.44s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/dataCellsFilter (23.15s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/database (22.31s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/dataLocation (25.63s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/lfTag (24.47s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/lfTagPolicy (22.07s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/tableWithColumns (23.19s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/basic (22.54s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/table (22.83s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/nonIAMPrincipals (17.25s)
```

### CODE REVIEW

File: internal/service/lakeformation/permissions_test.go [hunk 1]
```diff
@@ -679,6 +752,38 @@ func testAccPermissions_tableWildcardSelectPlus(t *testing.T) {
...
+	ctx := acctest.Context(t)
+	rName := sdkacctest.RandomWithPrefix(acctest.ResourcePrefix)
+	resourceName := "aws_lakeformation_permissions.test"
+	dbName := "aws_glue_catalog_table.test"
+
+	resource.Test(t, resource.TestCase{
+		PreCheck: func() {
+			acctest.PreCheck(ctx, t)
+			acctest.PreCheckPartitionHasService(t, names.LakeFormationEndpointID)
+		},
```
Comment (jar-b) [inline internal/service/lakeformation/permissions_test.go:765]: Do we need a PreCheck for the presence of an SSOAdmin instance in each of the `_nonIAMPrincipals` tests?

File: internal/service/identitystore/group.go [hunk 2]
```diff
@@ -37,6 +37,10 @@ func resourceGroup() *schema.Resource {
 		},
 
 		Schema: map[string]*schema.Schema{
+			names.AttrARN: {
+				Type:     schema.TypeString,
+				Computed: true,
+			},
```
Comment (jar-b) [inline internal/service/identitystore/group.go:43]: Changelog entry for this new attribute?

**Review by YakDriver — APPROVED** [review]
YOLO LGTM 🎉
