### PR TITLE
r/aws_elasticache_replication_group: malformed version error

### LINKED ISSUE #36605: [Bug]: unable to upgrade elastic cache version from terraform
### Terraform Core Version

1.6.4

### AWS Provider Version

5.42.0

### Affected Resource(s)

aws_elasticache_replication_group

### Expected Behavior

should be able to upgrade the version to 7

### Actual Behavior

Failing with following error 

```shell
Error: parsing old engine_version: Malformed version: 7.x
│
│   with module.redis_test.aws_elasticache_replication_group.redis_with_auth[0],
│   on ../../../../modules/aws/data/elastic_cache/main.tf line 41, in resource "aws_elasticache_replication_group" "redis_with_auth":
│   41: resource "aws_elasticache_replication_group" "redis_with_auth" {

```

### Relevant Error/Panic Output Snippet

_No response_

### Terraform Configuration Files

```terraform
module "redis_test" {
  source                         = "../../../../modules/aws/data/elastic_cache"
  env                            = var.env
  name                           = "temp"
  redis_clusters                 = "1"
  redis_failover                 = "false"
  redis_node_type                = "cache.t3.micro"
  subnet_group_name              = local.cache_subnet
  vpc_id                         = local.vpc_id
  redis_maintenance_window       = "sat:04:00-sat:05:00"
  redis_version                  = "7.0"
  redis_snapshot_retention_limit = "1"
  region                         = var.aws_region
  at_rest_encryption_enabled     = true
  transit_encryption_enabled     = true
  auth_enabled                   = true
  apply_immediately              = true
  snapshot_name                  = ""
}
```

It planned and then gave below error

```shell
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with
the following symbols:
-/+ destroy and then create replacement

Terraform planned the following actions, but then encountered a problem:

# module.redis_test.aws_elasticache_parameter_group.redis_parameter_group must be replaced
-/+ resource "aws_elasticache_parameter_group" "redis_parameter_group" {
      ~ arn         = "****************************" -> (known after apply)
      ~ family      = "redis6.x" -> "redis7" # forces replacement
      ~ id          = "temp" -> (known after apply)
        name        = "temp"
       
        # (2 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.

Error: parsing old engine_version: Malformed version: 7.x
│
│   with module.redis_test.aws_elasticache_replication_group.redis_with_auth[0],
│   on ../../../../modules/aws/data/elastic_cache/main.tf line 41, in resource "aws_elasticache_replication_group" "redis_with_auth":
│   41: resource "aws_elasticache_replication_group" "redis_with_auth" {
│
```

replication group resource:

```terraform
resource "aws_elasticache_replication_group" "redis_with_auth" {


  replication_group_id       = format("%.20s", "${var.env}-${var.name}")
  description                = "Terraform-managed ElastiCache replication group for ${var.name}"
  num_cache_clusters         = var.redis_clusters
  node_type                  = var.redis_node_type
  automatic_failover_enabled = var.redis_failover
  multi_az_enabled           = var.redis_failover
  engine_version             = var.redis_version
  port                       = var.redis_port
  parameter_group_name       = aws_elasticache_parameter_group.redis_parameter_group.id
  subnet_group_name          = var.subnet_group_name
  security_group_ids         = [aws_security_group.redis_security_group.id]
  apply_immediately          = var.apply_immediately
  maintenance_window         = var.redis_maintenance_window
  snapshot_window            = var.redis_snapshot_window
  snapshot_retention_limit   = var.redis_snapshot_retention_limit
  snapshot_name              = var.snapshot_name
  at_rest_encryption_enabled = var.at_rest_encryption_enabled
  transit_encryption_enabled = var.transit_encryption_enabled
  auth_token                 = var.auth_token
 
}
```

### Steps to Reproduce

Upgraded elasticcache engine versionfrom 6.2.6 to 7.0 from the AWS console, Now trying to update the engine version in the terraform and getting below error

```shell
Error: parsing old engine_version: Malformed version: 7.x
```

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by johnsonaj**
### Description

The provider can fail to parse a  v7.x `engine_version` upgrade.

```console
% make testacc TESTARGS='-run=TestAccElastiCacheReplicationGroup_OutOfBandUpgrade' PKG=elasticache    

make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.8 test ./internal/service/elasticache/... -v -count 1 -parallel 20  -run=TestAccElastiCacheReplicationGroup_OutOfBandUpgrade -timeout 360m -vet=off
2025/04/23 14:49:25 Initializing Terraform AWS Provider...
=== RUN   TestAccElastiCacheReplicationGroup_OutOfBandUpgrade
=== PAUSE TestAccElastiCacheReplicationGroup_OutOfBandUpgrade
=== CONT  TestAccElastiCacheReplicationGroup_OutOfBandUpgrade
    replication_group_test.go:246: Step 2/2 error running refresh: exit status 1

        Error: parsing old engine_version: Malformed version: 7.x

          with aws_elasticache_replication_group.test,
          on terraform_plugin_test.tf line 12, in resource "aws_elasticache_replication_group" "test":
          12: resource "aws_elasticache_replication_group" "test" {

--- FAIL: TestAccElastiCacheReplicationGroup_OutOfBandUpgrade (1516.98s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/elasticache	1522.577s
FAIL
make: *** [testacc] Error 1
```

### Relations

Closes #36605

### Output from Acceptance Testing

```console
% make testacc TESTARGS='-run=TestAccElastiCacheReplicationGroup_OutOfBandUpgrade\|TestAccElastiCacheReplicationGroup_Redis_basic\|TestAccElastiCacheReplicationGroup_Redis_EngineVersion_v7\|TestAccElastiCacheReplicationGroup_disappears' PKG=elasticache

make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.8 test ./internal/service/elasticache/... -v -count 1 -parallel 20  -run=TestAccElastiCacheReplicationGroup_OutOfBandUpgrade\|TestAccElastiCacheReplicationGroup_Redis_basic\|TestAccElastiCacheReplicationGroup_Redis_EngineVersion_v7\|TestAccElastiCacheReplicationGroup_disappears -timeout 360m -vet=off
2025/04/23 18:17:55 Initializing Terraform AWS Provider...
=== RUN   TestAccElastiCacheReplicationGroup_Redis_basic
=== PAUSE TestAccElastiCacheReplicationGroup_Redis_basic
=== RUN   TestAccElastiCacheReplicationGroup_Redis_basic_v5
=== PAUSE TestAccElastiCacheReplicationGroup_Redis_basic_v5
=== RUN   TestAccElastiCacheReplicationGroup_Redis_EngineVersion_v7
=== PAUSE TestAccElastiCacheReplicationGroup_Redis_EngineVersion_v7
=== RUN   TestAccElastiCacheReplicationGroup_OutOfBandUpgrade
=== PAUSE TestAccElastiCacheReplicationGroup_OutOfBandUpgrade
=== RUN   TestAccElastiCacheReplicationGroup_disappears
=== PAUSE TestAccElastiCacheReplicationGroup_disappears
=== CONT  TestAccElastiCacheReplicationGroup_Redis_basic
=== CONT  TestAccElastiCacheReplicationGroup_OutOfBandUpgrade
=== CONT  TestAccElastiCacheReplicationGroup_disappears
=== CONT  TestAccElastiCacheReplicationGroup_Redis_EngineVersion_v7
=== CONT  TestAccElastiCacheReplicationGroup_Redis_basic_v5
--- PASS: TestAccElastiCacheReplicationGroup_Redis_basic_v5 (730.77s)
--- PASS: TestAccElastiCacheReplicationGroup_Redis_EngineVersion_v7 (731.46s)
--- PASS: TestAccElastiCacheReplicationGroup_Redis_basic (792.95s)
--- PASS: TestAccElastiCacheReplicationGroup_disappears (807.51s)
--- PASS: TestAccElastiCacheReplicationGroup_OutOfBandUpgrade (1608.63s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elasticache	1614.245s
```

### CODE REVIEW

File: internal/service/elasticache/replication_group.go [hunk 1]
```diff
@@ -979,6 +979,11 @@ func resourceReplicationGroupUpdate(ctx context.Context, d *schema.ResourceData,
 		if requestUpdate {
 			updateFuncs = append(updateFuncs, func() error {
 				_, err := conn.ModifyReplicationGroup(ctx, &input)
+				// modifying to match out of band operations may result n this error
```
Comment (ewbankkit) [inline internal/service/elasticache/replication_group.go:982]:
```suggestion
				// modifying to match out of band operations may result in this error
```

File: internal/service/elasticache/replication_group.go [hunk 2]
```diff
@@ -996,6 +1001,11 @@ func resourceReplicationGroupUpdate(ctx context.Context, d *schema.ResourceData,
 
 			updateFuncs = append(updateFuncs, func() error {
 				_, err := conn.ModifyReplicationGroup(ctx, &authInput)
+				// modifying to match out of band operations may result n this error
```
Comment (ewbankkit) [inline internal/service/elasticache/replication_group.go:1004]:
```suggestion
				// modifying to match out of band operations may result in this error
```
