### PR TITLE
resource/aws_instance: fix cpu_options partial update sending only one of CoreCount or ThreadsPerCore

### LINKED ISSUE #46821: aws_instance: When specifying CpuOptions you must specify both CoreCount and ThreadsPerCore.
### Terraform and AWS Provider Version

```console
Terraform v1.14.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v6.35.1
```

### Affected Resource(s) or Data Source(s)

aws_instance

### Expected Behavior

Changing `cpu_options.core_count` or `cpu_options.threads_per_core` should be allowed independently.

### Actual Behavior

Changing either `cpu_options.core_count` or `cpu_options.threads_per_core` alone fails.

### Relevant Error/Panic Output

```console
Error: updating EC2 Instance (<INSTANCE_ID>): modifying CPU options: operation error EC2: ModifyInstanceCpuOptions, https response error StatusCode: 400, RequestID: 73c8ae1b-ec4f-4d77-81a3-1a4a8a9c0f46, api error MissingParameter: When specifying CpuOptions you must specify both CoreCount and ThreadsPerCore.
```

### Sample Terraform Configuration

<details open>
<summary>Click to expand configuration</summary>

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "6.35.1"
    }
  }
}

provider "aws" {
  region = "us-east-1"
}

data "aws_ami" "al2023" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["al2023-ami-2023.*-x86_64"]
  }
}

resource "aws_instance" "example" {
  ami           = data.aws_ami.al2023.id
  instance_type = "c6i.2xlarge"

  cpu_options {
    core_count       = 2
    threads_per_core = 2
  }
}
```
</details>

### Steps to Reproduce

1. Apply configuration
2. Change one of `cpu_options.core_count` or `cpu_options.cpu_options`.
3. Plan, confirming the change of just one of these arguments.
4. Apply configuration

### Debug Logging

<details open>
<summary>Click to expand log output</summary>

```console
2026-03-09T14:43:07.016+0100 [DEBUG] provider.terraform-provider-aws_v6.35.1_x5: HTTP Request Sent: tf_resource_type=aws_instance tf_rpc=ApplyResourceChange http.request.header.authorization="AWS4-HMAC-SHA256 Credential=AKIA************ZMUI/20260309/us-east-1/ec2/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-date, Signature=*****" http.user_agent="APN/1.0 HashiCorp/1.0 Terraform/1.14.6 (+https://www.terraform.io) terraform-provider-aws/6.35.1 (+https://registry.terraform.io/providers/hashicorp/aws) aws-sdk-go-v2/1.41.3 ua/2.1 os/linux lang/go#1.25.7 md/GOOS#linux md/GOARCH#amd64 api/ec2#1.293.1 m/g" net.peer.name=ec2.us-east-1.amazonaws.com tf_aws.signing_region="" tf_req_id=5513e2a6-dff8-4413-21e6-47113a6b1015 @caller=github.com/hashicorp/aws-sdk-go-base/v2@v2.0.0-beta.71/logging/tf_logger.go:45 aws.region=us-east-1 http.request.header.amz_sdk_invocation_id=33a002dd-eea8-46a3-aaf8-b1c1907c52fc http.request_content_length=98 http.url=https://ec2.us-east-1.amazonaws.com/ rpc.system.name=aws-api tf_provider_addr=registry.terraform.io/hashicorp/aws
  http.request.body=
  | Action=ModifyInstanceCpuOptions&InstanceId=<INSTANCE_ID>&ThreadsPerCore=2&Version=2016-11-15
   http.request.header.content_type=application/x-www-form-urlencoded http.request.header.x_amz_date=20260309T134307Z rpc.method=ModifyInstanceCpuOptions tf_aws.sdk=aws-sdk-go-v2 tf_mux_provider="*schema.GRPCProviderServer" @module=aws http.method=POST http.request.header.amz_sdk_request="attempt=1; max=25" timestamp="2026-03-09T14:43:07.016+0100"
2026-03-09T14:43:07.928+0100 [DEBUG] provider.terraform-provider-aws_v6.35.1_x5: HTTP Response Received: http.response.header.date="Mon, 09 Mar 2026 13:43:07 GMT" rpc.method=ModifyInstanceCpuOptions rpc.system.name=aws-api tf_aws.sdk=aws-sdk-go-v2 tf_provider_addr=registry.terraform.io/hashicorp/aws @caller=github.com/hashicorp/aws-sdk-go-base/v2@v2.0.0-beta.71/logging/tf_logger.go:45 aws.region=us-east-1 http.duration=911 http.response.header.vary=accept-encoding tf_aws.signing_region="" tf_mux_provider="*schema.GRPCProviderServer" tf_req_id=5513e2a6-dff8-4413-21e6-47113a6b1015 http.response.header.server=AmazonEC2 http.response.header.strict_transport_security="max-age=31536000; includeSubDomains" tf_rpc=ApplyResourceChange
  http.response.body=
  | <?xml version="1.0" encoding="UTF-8"?>
  | <Response><Errors><Error><Code>MissingParameter</Code><Message>When specifying CpuOptions you must specify both CoreCount and ThreadsPerCore.</Message></Error></Errors><RequestID>7b125bb9-c547-473f-a47b-fb3c5a14baf1</RequestID></Response>
   http.response.header.content_type=text/xml;charset=UTF-8 http.response.header.x_amzn_requestid=7b125bb9-c547-473f-a47b-fb3c5a14baf1 http.status_code=400 tf_resource_type=aws_instance @module=aws http.response.header.cache_control="no-cache, no-store" timestamp="2026-03-09T14:43:07.928+0100"
2026-03-09T14:43:07.929+0100 [DEBUG] provider.terraform-provider-aws_v6.35.1_x5: request failed with unretryable error https response error StatusCode: 400, RequestID: 7b125bb9-c547-473f-a47b-fb3c5a14baf1, api error MissingParameter: When specifying CpuOptions you must specify both CoreCount and ThreadsPerCore.: tf_provider_addr=registry.terraform.io/hashicorp/aws tf_req_id=5513e2a6-dff8-4413-21e6-47113a6b1015 tf_resource_type=aws_instance @caller=github.com/hashicorp/aws-sdk-go-base/v2@v2.0.0-beta.71/logging/tf_logger.go:45 @module=aws rpc.method=ModifyInstanceCpuOptions rpc.system.name=aws-api tf_aws.sdk=aws-sdk-go-v2 tf_rpc=ApplyResourceChange aws.region=us-east-1 tf_mux_provider="*schema.GRPCProviderServer" timestamp="2026-03-09T14:43:07.928+0100"
2026-03-09T14:43:07.930+0100 [ERROR] provider.terraform-provider-aws_v6.35.1_x5: Response contains error diagnostic: @module=sdk.proto diagnostic_summary="updating EC2 Instance (<INSTANCE_ID>): modifying CPU options: operation error EC2: ModifyInstanceCpuOptions, https response error StatusCode: 400, RequestID: 7b125bb9-c547-473f-a47b-fb3c5a14baf1, api error MissingParameter: When specifying CpuOptions you must specify both CoreCount and ThreadsPerCore." tf_proto_version=5.11 tf_resource_type=aws_instance tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/terraform-plugin-go@v0.30.0/tfprotov5/internal/diag/diagnostics.go:58 diagnostic_detail="" diagnostic_severity=ERROR tf_provider_addr=registry.terraform.io/hashicorp/aws tf_req_id=5513e2a6-dff8-4413-21e6-47113a6b1015 timestamp="2026-03-09T14:43:07.930+0100"
```
</details>

### GenAI / LLM Assisted Development

n/a

### Important Facts and References

_No response_

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by sanyer**
## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the library.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

### Description

Fix `aws_instance.cpu_options` update so that changing either `core_count` or `threads_per_core` alone no longer fails with a `MissingParameter` error from the AWS API.

This change:

- sends both `CoreCount` and `ThreadsPerCore` whenever either value changes, using the current state value for the unchanged field
- aligns the update path with the create path (`expandCPUOptions`), which already pairs both fields together
- adds `TestAccEC2Instance_cpuOptionsCoreCountOnly` to verify updating only `core_count` while keeping `threads_per_core` unchanged
- adds `TestAccEC2Instance_cpuOptionsThreadsPerCoreOnly` to verify updating only `threads_per_core` while keeping `core_count` unchanged

### Relations

Closes #46821

### References

<https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-cpu-options-rules.html>
<https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ModifyInstanceCpuOptions.html>

### Output from Acceptance Testing

```console
% make testacc TESTS="TestAccEC2Instance_cpuOptionsCoreCountOnly|TestAccEC2Instance_cpuOptionsThreadsPerCoreOnly|TestAccEC2Instance_cpuOptionsCoreThreads" PKG=ec2
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Building provider...
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 b-aws_instance-cpu_options_partial_update 🌿...
TF_ACC=1 go1.25.8 test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2Instance_cpuOptionsCoreCountOnly|TestAccEC2Instance_cpuOptionsThreadsPerCoreOnly|TestAccEC2Instance_cpuOptionsCoreThreads'  -timeout 360m -vet=off
2026/03/12 00:20:54 Creating Terraform AWS Provider (SDKv2-style)...
2026/03/12 00:20:54 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccEC2Instance_cpuOptionsCoreThreads
=== PAUSE TestAccEC2Instance_cpuOptionsCoreThreads
=== RUN   TestAccEC2Instance_cpuOptionsCoreCountOnly
=== PAUSE TestAccEC2Instance_cpuOptionsCoreCountOnly
=== RUN   TestAccEC2Instance_cpuOptionsThreadsPerCoreOnly
=== PAUSE TestAccEC2Instance_cpuOptionsThreadsPerCoreOnly
=== RUN   TestAccEC2Instance_cpuOptionsCoreThreadsUnspecifiedToSpecified
=== PAUSE TestAccEC2Instance_cpuOptionsCoreThreadsUnspecifiedToSpecified
=== CONT  TestAccEC2Instance_cpuOptionsCoreThreads
=== CONT  TestAccEC2Instance_cpuOptionsThreadsPerCoreOnly
=== CONT  TestAccEC2Instance_cpuOptionsCoreThreadsUnspecifiedToSpecified
=== CONT  TestAccEC2Instance_cpuOptionsCoreCountOnly
--- PASS: TestAccEC2Instance_cpuOptionsCoreThreadsUnspecifiedToSpecified (100.10s)
--- PASS: TestAccEC2Instance_cpuOptionsCoreThreads (136.30s)
--- PASS: TestAccEC2Instance_cpuOptionsThreadsPerCoreOnly (150.18s)
--- PASS: TestAccEC2Instance_cpuOptionsCoreCountOnly (150.41s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	150.666s

...
```

<details> 
  <summary>AI Usage</summary>
  Claude Opus 4.6 was used to help narrow down the issue and generate boilerplate for acceptance tests.

  Prompt:

    While using latest aws terraform provider I've faced the issue:
    Changing either `cpu_options.core_count` or `cpu_options.threads_per_core` alone fails.
    ```console
    Error: updating EC2 Instance (<INSTANCE_ID>): modifying CPU options: operation error EC2: ModifyInstanceCpuOptions, https response error StatusCode: 400, RequestID: 73c8ae1b-ec4f-4d77-81a3-1a4a8a9c0f46, api error MissingParameter: When specifying CpuOptions you must specify both CoreCount and ThreadsPerCore.
    ```
    
    I have pulled provider code and looking into it, it seems like the first files to look into the issue is ec2_instance_migrate.go and ec2_instance.go
    Also, there are tests for these at ec2_instance_test.go and ec2_instance_migrate_test.go
    
    While you research I'll go ahead and run terraform apply with debug tracing on to get more info on issue
</details>

### CODE REVIEW

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccEC2Instance_cpuOptions\|TestAccEC2Instance_basic' PKG=ec2 ACCTEST_PARALLELISM=4
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 HEAD 🌿...
TF_ACC=1 go1.25.8 test ./internal/service/ec2/... -v -count 1 -parallel 4  -run=TestAccEC2Instance_cpuOptions\|TestAccEC2Instance_basic -timeout 360m -vet=off
2026/03/12 09:07:16 Creating Terraform AWS Provider (SDKv2-style)...
2026/03/12 09:07:16 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccEC2Instance_basic
=== PAUSE TestAccEC2Instance_basic
=== RUN   TestAccEC2Instance_cpuOptionsAmdSevSnpUnspecifiedToDisabledToEnabledToUnspecified
=== PAUSE TestAccEC2Instance_cpuOptionsAmdSevSnpUnspecifiedToDisabledToEnabledToUnspecified
=== RUN   TestAccEC2Instance_cpuOptionsAmdSevSnpUnspecifiedToEnabledToDisabledToUnspecified
=== PAUSE TestAccEC2Instance_cpuOptionsAmdSevSnpUnspecifiedToEnabledToDisabledToUnspecified
=== RUN   TestAccEC2Instance_cpuOptionsAmdSevSnpEnabledToDisabled
=== PAUSE TestAccEC2Instance_cpuOptionsAmdSevSnpEnabledToDisabled
=== RUN   TestAccEC2Instance_cpuOptionsAmdSevSnpDisabledToEnabled
=== PAUSE TestAccEC2Instance_cpuOptionsAmdSevSnpDisabledToEnabled
=== RUN   TestAccEC2Instance_cpuOptionsAmdSevSnpCoreThreads
=== PAUSE TestAccEC2Instance_cpuOptionsAmdSevSnpCoreThreads
=== RUN   TestAccEC2Instance_cpuOptionsCoreThreads
=== PAUSE TestAccEC2Instance_cpuOptionsCoreThreads
=== RUN   TestAccEC2Instance_cpuOptionsCoreCountOnly
=== PAUSE TestAccEC2Instance_cpuOptionsCoreCountOnly
=== RUN   TestAccEC2Instance_cpuOptionsThreadsPerCoreOnly
=== PAUSE TestAccEC2Instance_cpuOptionsThreadsPerCoreOnly
=== RUN   TestAccEC2Instance_cpuOptionsCoreThreadsUnspecifiedToSpecified
=== PAUSE TestAccEC2Instance_cpuOptionsCoreThreadsUnspecifiedToSpecified
=== RUN   TestAccEC2Instance_cpuOptionsNestedVirtualizationUnspecifiedToDisabledToEnabledToUnspecified
=== PAUSE TestAccEC2Instance_cpuOptionsNestedVirtualizationUnspecifiedToDisabledToEnabledToUnspecified
=== RUN   TestAccEC2Instance_cpuOptionsNestedVirtualizationUnspecifiedToEnabledToDisabledToUnspecified
=== PAUSE TestAccEC2Instance_cpuOptionsNestedVirtualizationUnspecifiedToEnabledToDisabledToUnspecified
=== RUN   TestAccEC2Instance_cpuOptionsNestedVirtualizationEnabledToDisabled
=== PAUSE TestAccEC2Instance_cpuOptionsNestedVirtualizationEnabledToDisabled
=== RUN   TestAccEC2Instance_cpuOptionsNestedVirtualizationDisabledToEnabled
=== PAUSE TestAccEC2Instance_cpuOptionsNestedVirtualizationDisabledToEnabled
=== RUN   TestAccEC2Instance_basicWithSpot
=== PAUSE TestAccEC2Instance_basicWithSpot
=== CONT  TestAccEC2Instance_basic
=== CONT  TestAccEC2Instance_cpuOptionsThreadsPerCoreOnly
=== CONT  TestAccEC2Instance_cpuOptionsNestedVirtualizationEnabledToDisabled
=== CONT  TestAccEC2Instance_cpuOptionsAmdSevSnpDisabledToEnabled
    ec2_instance_test.go:4772: skipping tests; AWS_DEFAULT_REGION (us-west-2) not supported. Supported: [us-east-2]
--- SKIP: TestAccEC2Instance_cpuOptionsAmdSevSnpDisabledToEnabled (0.36s)
=== CONT  TestAccEC2Instance_basicWithSpot
--- PASS: TestAccEC2Instance_basicWithSpot (105.70s)
=== CONT  TestAccEC2Instance_cpuOptionsNestedVirtualizationDisabledToEnabled
--- PASS: TestAccEC2Instance_basic (126.53s)
=== CONT  TestAccEC2Instance_cpuOptionsNestedVirtualizationUnspecifiedToDisabledToEnabledToUnspecified
--- PASS: TestAccEC2Instance_cpuOptionsThreadsPerCoreOnly (232.75s)
=== CONT  TestAccEC2Instance_cpuOptionsNestedVirtualizationUnspecifiedToEnabledToDisabledToUnspecified
--- PASS: TestAccEC2Instance_cpuOptionsNestedVirtualizationEnabledToDisabled (239.56s)
=== CONT  TestAccEC2Instance_cpuOptionsAmdSevSnpUnspecifiedToEnabledToDisabledToUnspecified
    ec2_instance_test.go:4624: skipping tests; AWS_DEFAULT_REGION (us-west-2) not supported. Supported: [us-east-2]
--- SKIP: TestAccEC2Instance_cpuOptionsAmdSevSnpUnspecifiedToEnabledToDisabledToUnspecified (0.00s)
=== CONT  TestAccEC2Instance_cpuOptionsAmdSevSnpEnabledToDisabled
    ec2_instance_test.go:4713: skipping tests; AWS_DEFAULT_REGION (us-west-2) not supported. Supported: [us-east-2]
--- SKIP: TestAccEC2Instance_cpuOptionsAmdSevSnpEnabledToDisabled (0.00s)
=== CONT  TestAccEC2Instance_cpuOptionsCoreThreads
--- PASS: TestAccEC2Instance_cpuOptionsNestedVirtualizationDisabledToEnabled (232.53s)
=== CONT  TestAccEC2Instance_cpuOptionsCoreCountOnly
--- PASS: TestAccEC2Instance_cpuOptionsNestedVirtualizationUnspecifiedToDisabledToEnabledToUnspecified (312.79s)
=== CONT  TestAccEC2Instance_cpuOptionsAmdSevSnpUnspecifiedToDisabledToEnabledToUnspecified
    ec2_instance_test.go:4540: skipping tests; AWS_DEFAULT_REGION (us-west-2) not supported. Supported: [us-east-2]
--- SKIP: TestAccEC2Instance_cpuOptionsAmdSevSnpUnspecifiedToDisabledToEnabledToUnspecified (0.00s)
=== CONT  TestAccEC2Instance_cpuOptionsCoreThreadsUnspecifiedToSpecified
--- PASS: TestAccEC2Instance_cpuOptionsCoreThreads (236.57s)
=== CONT  TestAccEC2Instance_cpuOptionsAmdSevSnpCoreThreads
    ec2_instance_test.go:4837: skipping tests; AWS_DEFAULT_REGION (us-west-2) not supported. Supported: [us-east-2]
--- SKIP: TestAccEC2Instance_cpuOptionsAmdSevSnpCoreThreads (0.00s)
--- PASS: TestAccEC2Instance_cpuOptionsNestedVirtualizationUnspecifiedToEnabledToDisabledToUnspecified (331.33s)
--- PASS: TestAccEC2Instance_cpuOptionsCoreCountOnly (238.53s)
--- PASS: TestAccEC2Instance_cpuOptionsCoreThreadsUnspecifiedToSpecified (152.71s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	598.198s
```

**Review by YakDriver — APPROVED** [review]
LGTM 🎉

File: internal/service/ec2/ec2_instance.go [hunk 1]
```diff
@@ -1993,18 +1993,19 @@ func resourceInstanceUpdate(ctx context.Context, d *schema.ResourceData, meta an
 				InstanceId: aws.String(d.Id()),
 			}
 
-			if d.HasChange("cpu_options.0.core_count") {
+			// The AWS API requires both CoreCount and ThreadsPerCore to be specified
```
Comment (YakDriver) [inline internal/service/ec2/ec2_instance.go:1996]: We try not to over comment but insight into particularities is a super helpful type of comment! Thanks!

**Comment by ewbankkit** [comment]
@sanyer Thanks for the contribution :tada: :clap:.

**Comment by sanyer** [comment]
> @sanyer Thanks for the contribution 🎉 👏.

thank you for the fast response and good contribution docs @ewbankkit !

File: internal/service/ec2/ec2_instance.go (hunk 1 above)
Comment (sanyer) [reply internal/service/ec2/ec2_instance.go:1996]: Yeah, and this one is not clearly documented by AWS API docs, so adding some details felt useful.
