### PR TITLE
Fix for issue #13538

### LINKED ISSUE #13538: AWS Fargate profiles cannot delete in parallel
_This issue was originally opened by @grobmeier as hashicorp/terraform#25059. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._
    
<hr>
    
### Terraform Version
```
0.12.24
```

### Debug Output

```
Error: error deleting EKS Fargate Profile (xxx-global:fp-kubernetes-dashboard): ResourceInUseException: Cannot Delete Fargate Profile fp-kubernetes-dashboard because cluster xxx-global currently has Fargate profile fp-yellowpages in status DELETING
{
  ClusterName: "xxx-global",
  Message_: "Cannot Delete Fargate Profile fp-kubernetes-dashboard because cluster xxx-global currently has Fargate profile fp-xxxa in status DELETING"
}

```

### Crash Output

After time out, the operation fails and leaves us with a broken state.

### Expected Behavior

Fargate profiles are deleted

### Actual Behavior

Fargate profiles are not deleted (timeout)

### Steps to Reproduce

terraform destroy would cause this.

### Additional Context

We are running an EKS cluster with 5 Fargate profiles.
Apparently AWS does not allow to delete more than one Fargate profile in parallel. The same behavior happens using the AWS browser interface

### PR DESCRIPTION
**Pull request by jhujasonw**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #13538

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```NONE

```

Output from acceptance testing:

```

$ make testacc TESTARGS='-run=TestAccAWSEksFargateProfile_Multi_Profile'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -count 1 -parallel 20 -run=TestAccAWSEksFargateProfile_Multi_Profile -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSEksFargateProfile_Multi_Profile
=== PAUSE TestAccAWSEksFargateProfile_Multi_Profile
=== CONT  TestAccAWSEksFargateProfile_Multi_Profile
--- PASS: TestAccAWSEksFargateProfile_Multi_Profile (1252.89s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       1252.966s
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws/internal/flatmap      0.002s [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws/internal/keyvaluetags 0.013s [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws/internal/naming       0.012s [no tests to run]
?       github.com/terraform-providers/terraform-provider-aws/aws/internal/service/apigatewayv2/waiter  [no test files]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws/internal/service/batch/equivalency    0.006s [no tests to run]
?       github.com/terraform-providers/terraform-provider-aws/aws/internal/service/ec2/waiter   [no test files]
?       github.com/terraform-providers/terraform-provider-aws/aws/internal/service/ecs/waiter   [no test files]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws/internal/service/eks/token    0.006s [no tests to run]
?       github.com/terraform-providers/terraform-provider-aws/aws/internal/service/guardduty/waiter     [no test files]
?       github.com/terraform-providers/terraform-provider-aws/aws/internal/service/iam/waiter   [no test files]
?       github.com/terraform-providers/terraform-provider-aws/aws/internal/service/kinesisanalytics/waiter      [no test files]
?       github.com/terraform-providers/terraform-provider-aws/aws/internal/service/kms/waiter   [no test files]
?       github.com/terraform-providers/terraform-provider-aws/aws/internal/service/neptune/waiter       [no test files]
?       github.com/terraform-providers/terraform-provider-aws/aws/internal/service/rds/waiter   [no test files]
?       github.com/terraform-providers/terraform-provider-aws/aws/internal/service/secretsmanager/waiter        [no test files]
?       github.com/terraform-providers/terraform-provider-aws/aws/internal/service/servicediscovery/waiter      [no test files]
?       github.com/terraform-providers/terraform-provider-aws/aws/internal/service/workspaces/waiter    [no test files]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws/internal/tfawsresource        0.013s [no tests to run]
?       github.com/terraform-providers/terraform-provider-aws/awsproviderlint   [no test files]
?       github.com/terraform-providers/terraform-provider-aws/awsproviderlint/helper/awsprovidertype/keyvaluetags       [no test files]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes    0.012s [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/AWSAT001   0.013s [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/AWSR001    0.003s [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/AWSR002    0.011s [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/fmtsprintfcallexpr 0.003s [no tests to run]


```

### CODE REVIEW

**Comment by jhujasonw** [comment]
Hi @bflad,
I'm relatively new to the provider stuff, so I'm definitely happy to refactor how that is done.  Mutex is definitely the Right Way.   That should be a quick change.  The acceptance test may take me a bit more to sort through the docs and figure out how you all would like that done, so I'll get on it.   Thanks for the pointers.  Let me know if there is anything else you would like me to adjust while I work though it.  This bug is a particular headache for a terraform setup I am working with, so it's in my best interest to work through it quickly.

**Comment by jhujasonw** [comment]
Looking over the acceptance testing doc, would it be a good idea to just add a second profile into the test that already exists?  The destroy checks would pick up on it and if it errors out on creation of the second resource because of serialization issues, the acceptance test configuration apply would fail.  Those are really the only two instances where we care to test serialization and the rest of the test would operate only on the first resource.  I'm not trying to be lazy, but I am trying to simplify the tests for the eks fargate profiles and keep them readable.  If this isn't the right approach, I can come up with a different plan.

**Comment by bflad** [comment]
@jhujasonw in general, we prefer new tests and test configurations to ensure existing configurations work as expected, even if it is more verbose. It also helps future maintainers narrow down issues easier, since the different tests can isolate different behaviors. 👍

**Comment by jhujasonw** [comment]
Changed the serialization method to use mutex locking and gave writing an acceptance test a go.  Output from the acceptance test posted to the original comment.

**Comment by jhujasonw** [comment]
So I have run into another issue with this.   If you are removing multiple profiles that are actually running deployments, they take significantly longer (5 to 15 minutes, each) to destroy and you reach a timeout error on the ones waiting in line to be removed.

This PR fixes the issue of serialization, but perhaps bumping the timeout may still be something that needs to be considered?  Or is there perhaps another way around that that I am not seeing.

**Comment by ivankatliarchuk** [comment]
Can we merge this in? Edge cases can be solved with follow up PR in my opinion. What I can see, EKS Fargate management and lifecycle itself is far from ideal, e.g. idea is great, when implementation is horrible, an I hope the AWS team is going to make it more automation-friendly in the future releases.

**Review by jhujasonw — COMMENTED** [review]
Made the changes in a later commit.

**Comment by jhujasonw** [comment]
Please let me know if you would like me to work on this any further before considering for merge.

File: aws/resource_aws_eks_fargate_profile.go [hunk 1]
```diff
@@ -110,7 +110,13 @@ func resourceAwsEksFargateProfileCreate(d *schema.ResourceData, meta interface{}
...
 	}
 
-	err := resource.Retry(2*time.Minute, func() *resource.RetryError {
+	// mutex lock for creation/deletion serialization
+	mutexKey := fmt.Sprintf("%s-fargate-profiles", d.Get("cluster_name").(string))
+	awsMutexKV.Lock(mutexKey)
+	defer awsMutexKV.Unlock(mutexKey)
+
+	// Creation of profiles must be serialized, and can take a while, increase the timeout to a long time.
+	err := resource.Retry(30*time.Minute, func() *resource.RetryError {
```
Comment (bflad) [inline aws/resource_aws_eks_fargate_profile.go:119]: Since the mutex handles the timing issue -- going to revert this back to the 2 minute IAM propagation timeout.

**Review by bflad — APPROVED** [review]
Sorry for the delay, @jhujasonw, this looks good 🚀 

Output from acceptance testing:

```
--- PASS: TestAccAWSEksFargateProfile_basic (1143.84s)
--- PASS: TestAccAWSEksFargateProfile_disappears (1163.66s)
--- PASS: TestAccAWSEksFargateProfile_Multi_Profile (1456.46s)
--- PASS: TestAccAWSEksFargateProfile_Selector_Labels (1446.71s)
--- PASS: TestAccAWSEksFargateProfile_Tags (1185.36s)
```
