### PR TITLE
r/cognito_resource_server allow name change without ForceNew

### LINKED ISSUE #41347: [Bug]: `aws_cognito_resource_server` `name` attribute unnecessarily has `ForceNew: true`
### Terraform Core Version

any

### AWS Provider Version

main

### Affected Resource(s)

* aws_cognito_resource_server

### Expected Behavior

When updating the value of `name` for a cognito resource server, but leaving the `user_pool_id` and `identifier` attributes unchanged, the provider should update the existing resource server without replacing it.

### Actual Behavior

The provider produces a plan which deletes and recreates the resource server.

### Relevant Error/Panic Output Snippet

```shell

```

### Terraform Configuration Files

```
"aws_cognito_resource_server" "example" {
  identifier = "unchanged"
  name = "changeme"
  user_pool_id = aws_cognito_user_pool.test.id
}
```

### Steps to Reproduce

Apply the above config (with a new or existing user pool). 

Change the `name` attribute.

This can be done with a single aws api call (see references), but the terraform provider will delete and recreate the resource server.

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_UpdateResourceServer.html

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by mbbush**
### Description

Allow updates to the name (which is really just a description) of the cognito resource server without deleting and recreating it.

### Relations

Closes #41347 

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccCognitoIDPResourceServer PKG=cognitoidp
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.5 test ./internal/service/cognitoidp/... -v -count 1 -parallel 20 -run='TestAccCognitoIDPResourceServer'  -timeout 360m -vet=off
2025/03/06 09:32:09 Initializing Terraform AWS Provider...
=== RUN   TestAccCognitoIDPResourceServer_basic
=== PAUSE TestAccCognitoIDPResourceServer_basic
=== RUN   TestAccCognitoIDPResourceServer_disappears
=== PAUSE TestAccCognitoIDPResourceServer_disappears
=== RUN   TestAccCognitoIDPResourceServer_scope
=== PAUSE TestAccCognitoIDPResourceServer_scope
=== RUN   TestAccCognitoIDPResourceServer_nameChange
=== PAUSE TestAccCognitoIDPResourceServer_nameChange
=== CONT  TestAccCognitoIDPResourceServer_basic
=== CONT  TestAccCognitoIDPResourceServer_scope
=== CONT  TestAccCognitoIDPResourceServer_nameChange
=== CONT  TestAccCognitoIDPResourceServer_disappears
--- PASS: TestAccCognitoIDPResourceServer_disappears (15.33s)
--- PASS: TestAccCognitoIDPResourceServer_basic (17.68s)
--- PASS: TestAccCognitoIDPResourceServer_nameChange (22.90s)
--- PASS: TestAccCognitoIDPResourceServer_scope (33.54s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cognitoidp	33.666s

```

### CODE REVIEW

File: internal/service/cognitoidp/resource_server_test.go [hunk 1]
```diff
@@ -123,6 +123,38 @@ func TestAccCognitoIDPResourceServer_scope(t *testing.T) {
...
+					resource.TestCheckResourceAttr(resourceName, "name", rName),
+				),
+			},
+			{
+				Config: testAccResourceServerConfig_nameUpdate(identifier, rName),
+				Check: resource.ComposeAggregateTestCheckFunc(
+					testAccCheckResourceServerExists(ctx, resourceName, &resourceServer),
+					resource.TestCheckResourceAttr(resourceName, "name", fmt.Sprintf(`%s updated`, rName)),
+				),
+			},
```
Comment (mbbush) [inline internal/service/cognitoidp/resource_server_test.go:152]: I was not able to find a good example to follow for asserting that the resource is not deleted and recreated by terraform. 

The examples I did find all used some unique attribute in the AWS api response, like a creation date, to make the assertion, but there is no such attribute available for this resource. The only option I can think of would be to add an assertion on the Plan, but I don't know how to do that, and I'm not sure if it's necessary.

File: internal/service/cognitoidp/resource_server_test.go [hunk 2]
```diff
@@ -123,6 +123,37 @@ func TestAccCognitoIDPResourceServer_scope(t *testing.T) {
...
+			{
+				Config: testAccResourceServerConfig_basic(identifier, rName),
+				Check: resource.ComposeAggregateTestCheckFunc(
+					testAccCheckResourceServerExists(ctx, resourceName, &resourceServer),
+					resource.TestCheckResourceAttr(resourceName, names.AttrName, rName),
+				),
+			},
+			{
+				Config: testAccResourceServerConfig_nameUpdate(identifier, rName),
+				Check: resource.ComposeAggregateTestCheckFunc(
```
Comment (mbbush) [inline internal/service/cognitoidp/resource_server_test.go:148]: I was not able to find a good example to follow for asserting that the resource is not deleted and recreated by terraform.

The examples I did find all used some unique attribute in the AWS api response, like a creation date, to make the assertion, but there is no such attribute available for this resource. The only option I can think of would be to add an assertion on the Plan, but I don't know how to do that, and I'm not sure if it's necessary.
