### PR TITLE
r/config_configuration_aggregator -remove toLower call when setting ID  + disappears test

### LINKED ISSUE #8432: Creating a new aws_config_configuration_aggregator appears to not add to state if name has uppercase letters
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.11.13
+ provider.aws v2.7.0
```

### Affected Resource(s)

* [aws_config_configuration_aggregator](https://www.terraform.io/docs/providers/aws/r/config_configuration_aggregator.html)

### Terraform Configuration Files

```hcl
data "aws_caller_identity" "current" {}

resource "aws_config_configuration_aggregator" "account" {
  name = "MyAccountAggregator"

  account_aggregation_source {
    all_regions = true
    account_ids = ["${data.aws_caller_identity.current.account_id}"]
  }
}
```

### Expected Behavior

* ✅  Aggregator created successfully
* ✅  New resource saved in state, with no changes on a subsequent apply

### Actual Behavior

* ✅  Aggregator created successfully
* ❌  Terraform appears to not be aware of the new resource when running a subsequent apply

### Steps to Reproduce

1. Run `terraform apply`
1. Observe that the new aggregator now exists at https://console.aws.amazon.com/config/home?#/aggregators/view
1. Run `terraform apply` again
1. Observe that Terraform creates the resource again, with no knowledge of the resource previously created
1. Repeat the last two steps as much as you like
1. Run `terraform import aws_config_configuration_aggregator.account MyAccountAggregator`
1. Run `terraform apply` again
1. Observe that the aggregator is now no longer planned for creation

### Important Factoids

I haven't redacted any sensitive tokens from the debug output so I haven't got the entire thing to post, but I did save debug output for each run and did a diff. This stood out:

```
[DEBUG] plugin.terraform-provider-aws_v2.7.0_x4: [WARN] No such configuration aggregator (myaccountaggregator), removing from state
```

...which led to me to try the same exercise again, with the name `my-account-aggregator` instead. This worked fine.

So it appears that:
- aggregators using CamelCase in their names _do not_ get added to state on apply (but they _do_ on import)
- aggregators using kebab-case in their names _do_ get added to state on apply

### LINKED ISSUE #11769: aws_config_configuration_aggregator: Provider produced inconsistent result after apply
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.20
+ provider.aws v2.46.0

### Affected Resource(s)

* aws_config_configuration_aggregator

### Terraform Configuration Files

org_account_ids is passed on commandline via 
```
-var org_account_ids=XXX,YYY,ZZZ
```

```hcl
resource "aws_config_configuration_aggregator" "lz_aggregator" {
  name = "AGGREGATOR"

  account_aggregation_source {
    account_ids = split(",", var.org_account_ids)
    regions     = ["eu-west-1", "eu-central-1"]
  }
}
```

### Debug Output

```
2020-01-27T13:14:01.449+0100 [DEBUG] plugin.terraform-provider-aws_v2.46.0_x4: 2020/01/27 13:14:01 [WARN] No such configuration aggregator (aggregator), removing from state
2020/01/27 13:14:01 [DEBUG] aws_config_configuration_aggregator.lz_aggregator: apply errored, but we're indicating that via the Error pointer rather than returning it: Provider produced inconsistent result after apply: When applying changes to aws_config_configuration_aggregator.lz_aggregator, provider "registry.terraform.io/-/aws" produced an unexpected new value for was present, but now absent.
```

### Panic Output

```
Error: Provider produced inconsistent result after apply

When applying changes to aws_config_configuration_aggregator.lz_aggregator,
provider "registry.terraform.io/-/aws" produced an unexpected new value for
was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```
### Expected Behavior

```
  # aws_config_configuration_aggregator.lz_aggregator will be created
  + resource "aws_config_configuration_aggregator" "lz_aggregator" {
      + arn  = (known after apply)
      + id   = (known after apply)
      + name = "AGGREGATOR"

      + account_aggregation_source {
          + account_ids = [
              + "XXX",
              + "YYY",
              + "ZZZ",
            ]
          + all_regions = false
          + regions     = [
              + "eu-west-1",
              + "eu-central-1",
            ]
        }
    }
```

### Actual Behavior

Bombed out with error

### Steps to Reproduce

HCL listed above

1. `terraform apply`

### Important Factoids

Important fact: the aggregator is specified in full caps in the tf code, but the debug output returns it in lowercase. 

I've manually imported the aggregator in the state file using 
```
terraform import aws_config_configuration_aggregator.lz_aggregator AGGREGATOR
```
and now it deploys without issues (and doesn't try to redeploy it).

This came to light in the terraform 0.11 to 0.12 upgrade.

### References

* #0000

### PR DESCRIPTION
**Pull request by DrFaust92**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #11769
Closes #8432
Related #13826

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource_aws_config_configuration_aggregator: allow name to have uppercase characters
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSConfigConfigurationAggregator_'

--- PASS: TestAccAWSConfigConfigurationAggregator_tags (111.49s)
--- PASS: TestAccAWSConfigConfigurationAggregator_account (43.38s)
--- PASS: TestAccAWSConfigConfigurationAggregator_disappears (36.07s)

    TestAccAWSConfigConfigurationAggregator_organization: provider_test.go:532: skipping tests; this AWS account must not be an existing member of an AWS Organization
--- SKIP: TestAccAWSConfigConfigurationAggregator_organization (3.00s)
Test ignored.
    TestAccAWSConfigConfigurationAggregator_switch: provider_test.go:532: skipping tests; this AWS account must not be an existing member of an AWS Organization
--- SKIP: TestAccAWSConfigConfigurationAggregator_switch (3.59s)
Test ignored.
```

Can't test org features

### CODE REVIEW

**Comment by DrFaust92** [comment]
rebased:

```
--- PASS: TestAccAWSConfigConfigurationAggregator_tags (199.31s)
--- PASS: TestAccAWSConfigConfigurationAggregator_disappears (52.46s)
--- PASS: TestAccAWSConfigConfigurationAggregator_account (102.47s)
```

File: aws/resource_aws_config_configuration_aggregator_test.go [hunk 1]
```diff
@@ -58,8 +60,8 @@ func testSweepConfigConfigurationAggregators(region string) error {
 
 func TestAccAWSConfigConfigurationAggregator_account(t *testing.T) {
 	var ca configservice.ConfigurationAggregator
-	rName := acctest.RandomWithPrefix("tf-acc-test")
-	resourceName := "aws_config_configuration_aggregator.example"
+	rName := acctest.RandomWithPrefix("Tf-acc-test")
```
Comment (ewbankkit) [inline aws/resource_aws_config_configuration_aggregator_test.go:63]: Add a comment that an uppercase character in the resource name is explicitly being tests for so that this isn't inadvertently changed in the future.

Comment (DrFaust92) [reply aws/resource_aws_config_configuration_aggregator_test.go:64]: Thanks, added.

**Review by gdavison — APPROVED** [review]
LGTM 🚀 

--- SKIP: TestAccAWSConfigConfigurationAggregator_switch (1.06s)
--- SKIP: TestAccAWSConfigConfigurationAggregator_organization (1.08s)
--- PASS: TestAccAWSConfigConfigurationAggregator_disappears (16.98s)
--- PASS: TestAccAWSConfigConfigurationAggregator_account (18.94s)
--- PASS: TestAccAWSConfigConfigurationAggregator_tags (41.26s)

**Review by gdavison — APPROVED** [review]
LGTM 🚀 

--- SKIP: TestAccAWSConfigConfigurationAggregator_switch (1.06s)
--- SKIP: TestAccAWSConfigConfigurationAggregator_organization (1.08s)
--- PASS: TestAccAWSConfigConfigurationAggregator_disappears (16.98s)
--- PASS: TestAccAWSConfigConfigurationAggregator_account (18.94s)
--- PASS: TestAccAWSConfigConfigurationAggregator_tags (41.26s)
