### PR TITLE
resource/aws_budgets_budget: Add `metrics` attribute

### LINKED ISSUE #46866: aws_budgets_budget with filter_expression creates malformed budget
### Terraform and AWS Provider Version

```console
Terraform v1.12.2
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v6.33.0


Tested also with latest 6.35.1, same issue.
```

### Affected Resource(s) or Data Source(s)

* `aws_budgets_budget `

### Expected Behavior

Budget is created correctly, same as if `cost_filter` is used.

### Actual Behavior

Budget is created, but it's somehow malformed, `Budget history` window in AWS Console shows error:

```
Unable to load chart. An error has occurred with ce:GetCostAndUsage: ValidationException - Selected metrics cannot be null.
```

Image

### Relevant Error/Panic Output

There are no errors in output, as well as diff on next plan/apply.

### Sample Terraform Configuration

Based on example from [docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/budgets_budget):

<details open>
<summary>Click to expand configuration</summary>

```hcl
resource "aws_budgets_budget" "simple" {
  name         = "budget-ec2-filter"
  budget_type  = "COST"
  limit_amount = "500"
  limit_unit   = "USD"
  time_unit    = "MONTHLY"

  filter_expression {
    dimensions {
      key    = "SERVICE"
      values = ["Amazon Elastic Compute Cloud - Compute"]
    }
  }
}
```
</details>

### Steps to Reproduce

1. Apply example
2. Budget is created, but "Budget history" window doesn't show data, example in "Actual Behavior"
3. Next plan/apply doesn't show changes
4. Fix is possible by manually editing budget in AWS console by switching `Aggregate costs by` to any value and then back to Unblended:
Image

5. After that budget is working properly, but next plan shows diff setting `billing_view_arn` to null.

```terraform
Terraform will perform the following actions:

  # aws_budgets_budget.simple will be updated in-place
  ~ resource "aws_budgets_budget" "simple" {
      - billing_view_arn  = "arn:aws:billing::xxxxxx:billingview/primary" -> null
        id                = "xxxxxx:budget-ec2-filter"
        name              = "budget-ec2-filter"
        tags              = {}
        # (10 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
``` 
6. Which can be fixed by fetching billing_view_arn from datasource like this:
```terraform
data "aws_billing_views" "this" {
  billing_view_types = ["PRIMARY"]
}

resource "aws_budgets_budget" "simple" {
  name                   = "budget-ec2-filter"
  billing_view_arn = data.aws_billing_views.this.billing_view[0].arn
...
```

7. Applying changes with `billing_view_arn -> null` returns budget to broken state with error in "Budget history" view: `Unable to load chart. An error has occurred with ce:GetCostAndUsage: ValidationException - Selected metrics cannot be null.`

P.S. Creating budget with setting `billing_view_arn = data.aws_billing_views.this.billing_view[0].arn` from the beginning doesn't fix "Budget history" view, so it's not the root cause of the issue it seems.

### Debug Logging

Don't think it's applicable.

### GenAI / LLM Assisted Development

Nope

### Important Facts and References

Feature was implemented in this 6.33, PR: https://github.com/hashicorp/terraform-provider-aws/pull/46501

`billing_view_arn` was added in 6.13, PR: https://github.com/hashicorp/terraform-provider-aws/pull/44241

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by Nklya**
## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the library.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

### Description

* Add metrics parameter for budget
* Define "filter_expression", "metrics" fields as interdependent (according to AWS docs)

### Relations

Closes #46866

### References

`filter_expression` was added in #46501

### Output from Acceptance Testing

TODO: Will add after tests

```console
% make testacc TESTS=TestAccXXX PKG=ec2

...
```

### CODE REVIEW

**Comment by Nklya** [comment]
Will add tests, _changelog_ and _docs updates_ after tests somewhere next week.

**UPD**: Tested current version - all works as expected.

**Comment by Nklya** [comment]
UPD: Added changelog and updated docs.

I'm not sure if tests should be updated/added as I haven't added new methods and interdependence of arguments is handled by SDK.

File: internal/service/budgets/budget.go [hunk 1]
```diff
@@ -549,6 +562,10 @@ func resourceBudgetRead(ctx context.Context, d *schema.ResourceData, meta any) d
 		return sdkdiag.AppendErrorf(diags, "setting filter_expression: %s", err)
 	}
 
+	if err := d.Set("metrics", budget.Metrics); err != nil {
```
Comment (Nklya) [inline internal/service/budgets/budget.go:565]: Not 100% sure about this one, did it similar to `filter_expression`.

Tests with locally built provider works as expected, creating properly configured budgets + change of metrics working as well.

**Comment by taruntej-a** [comment]
```console
make testacc PKG=budgets TESTS=TestAccBudgetsBudget_                        
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 fix--aws_budgets_budget-filter_expression-missing-metrics-parameter 🌿...
TF_ACC=1 go1.25.8 test ./internal/service/budgets/... -v -count 1 -parallel 20 -run='TestAccBudgetsBudget_'  -timeout 360m -vet=off
2026/04/14 16:40:10 Creating Terraform AWS Provider (SDKv2-style)...
2026/04/14 16:40:10 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccBudgetsBudget_tags
=== PAUSE TestAccBudgetsBudget_tags
=== RUN   TestAccBudgetsBudget_Tags_null
=== PAUSE TestAccBudgetsBudget_Tags_null
=== RUN   TestAccBudgetsBudget_Tags_emptyMap
=== PAUSE TestAccBudgetsBudget_Tags_emptyMap
=== RUN   TestAccBudgetsBudget_Tags_addOnUpdate
=== PAUSE TestAccBudgetsBudget_Tags_addOnUpdate
=== RUN   TestAccBudgetsBudget_Tags_EmptyTag_onCreate
=== PAUSE TestAccBudgetsBudget_Tags_EmptyTag_onCreate
=== RUN   TestAccBudgetsBudget_Tags_EmptyTag_OnUpdate_add
=== PAUSE TestAccBudgetsBudget_Tags_EmptyTag_OnUpdate_add
=== RUN   TestAccBudgetsBudget_Tags_EmptyTag_OnUpdate_replace
=== PAUSE TestAccBudgetsBudget_Tags_EmptyTag_OnUpdate_replace
=== RUN   TestAccBudgetsBudget_Tags_DefaultTags_providerOnly
=== PAUSE TestAccBudgetsBudget_Tags_DefaultTags_providerOnly
=== RUN   TestAccBudgetsBudget_Tags_DefaultTags_nonOverlapping
=== PAUSE TestAccBudgetsBudget_Tags_DefaultTags_nonOverlapping
=== RUN   TestAccBudgetsBudget_Tags_DefaultTags_overlapping
=== PAUSE TestAccBudgetsBudget_Tags_DefaultTags_overlapping
=== RUN   TestAccBudgetsBudget_Tags_DefaultTags_updateToProviderOnly
=== PAUSE TestAccBudgetsBudget_Tags_DefaultTags_updateToProviderOnly
=== RUN   TestAccBudgetsBudget_Tags_DefaultTags_updateToResourceOnly
=== PAUSE TestAccBudgetsBudget_Tags_DefaultTags_updateToResourceOnly
=== RUN   TestAccBudgetsBudget_Tags_DefaultTags_emptyResourceTag
=== PAUSE TestAccBudgetsBudget_Tags_DefaultTags_emptyResourceTag
=== RUN   TestAccBudgetsBudget_Tags_DefaultTags_emptyProviderOnlyTag
=== PAUSE TestAccBudgetsBudget_Tags_DefaultTags_emptyProviderOnlyTag
=== RUN   TestAccBudgetsBudget_Tags_DefaultTags_nullOverlappingResourceTag
=== PAUSE TestAccBudgetsBudget_Tags_DefaultTags_nullOverlappingResourceTag
=== RUN   TestAccBudgetsBudget_Tags_DefaultTags_nullNonOverlappingResourceTag
=== PAUSE TestAccBudgetsBudget_Tags_DefaultTags_nullNonOverlappingResourceTag
=== RUN   TestAccBudgetsBudget_Tags_ComputedTag_onCreate
=== PAUSE TestAccBudgetsBudget_Tags_ComputedTag_onCreate
=== RUN   TestAccBudgetsBudget_Tags_ComputedTag_OnUpdate_add
=== PAUSE TestAccBudgetsBudget_Tags_ComputedTag_OnUpdate_add
=== RUN   TestAccBudgetsBudget_Tags_ComputedTag_OnUpdate_replace
=== PAUSE TestAccBudgetsBudget_Tags_ComputedTag_OnUpdate_replace
=== RUN   TestAccBudgetsBudget_Tags_IgnoreTags_Overlap_defaultTag
=== PAUSE TestAccBudgetsBudget_Tags_IgnoreTags_Overlap_defaultTag
=== RUN   TestAccBudgetsBudget_Tags_IgnoreTags_Overlap_resourceTag
=== PAUSE TestAccBudgetsBudget_Tags_IgnoreTags_Overlap_resourceTag
=== RUN   TestAccBudgetsBudget_basic
=== PAUSE TestAccBudgetsBudget_basic
=== RUN   TestAccBudgetsBudget_Name_generated
=== PAUSE TestAccBudgetsBudget_Name_generated
=== RUN   TestAccBudgetsBudget_namePrefix
=== PAUSE TestAccBudgetsBudget_namePrefix
=== RUN   TestAccBudgetsBudget_disappears
=== PAUSE TestAccBudgetsBudget_disappears
=== RUN   TestAccBudgetsBudget_autoAdjustDataForecast
=== PAUSE TestAccBudgetsBudget_autoAdjustDataForecast
=== RUN   TestAccBudgetsBudget_autoAdjustDataHistorical
=== PAUSE TestAccBudgetsBudget_autoAdjustDataHistorical
=== RUN   TestAccBudgetsBudget_costTypes
=== PAUSE TestAccBudgetsBudget_costTypes
=== RUN   TestAccBudgetsBudget_notifications
=== PAUSE TestAccBudgetsBudget_notifications
=== RUN   TestAccBudgetsBudget_plannedLimits
=== PAUSE TestAccBudgetsBudget_plannedLimits
=== RUN   TestAccBudgetsBudget_billingViewARN
=== PAUSE TestAccBudgetsBudget_billingViewARN
=== RUN   TestAccBudgetsBudget_filterExpression
=== PAUSE TestAccBudgetsBudget_filterExpression
=== RUN   TestAccBudgetsBudget_metrics
=== PAUSE TestAccBudgetsBudget_metrics
=== CONT  TestAccBudgetsBudget_tags
=== CONT  TestAccBudgetsBudget_Tags_ComputedTag_OnUpdate_add
=== CONT  TestAccBudgetsBudget_Tags_DefaultTags_overlapping
=== CONT  TestAccBudgetsBudget_Tags_EmptyTag_OnUpdate_add
=== CONT  TestAccBudgetsBudget_Tags_addOnUpdate
=== CONT  TestAccBudgetsBudget_Tags_DefaultTags_emptyProviderOnlyTag
=== CONT  TestAccBudgetsBudget_Tags_ComputedTag_onCreate
=== CONT  TestAccBudgetsBudget_Tags_DefaultTags_nullNonOverlappingResourceTag
=== CONT  TestAccBudgetsBudget_Tags_DefaultTags_nullOverlappingResourceTag
=== CONT  TestAccBudgetsBudget_Tags_emptyMap
=== CONT  TestAccBudgetsBudget_Tags_null
=== CONT  TestAccBudgetsBudget_Tags_DefaultTags_updateToResourceOnly
=== CONT  TestAccBudgetsBudget_Tags_DefaultTags_emptyResourceTag
=== CONT  TestAccBudgetsBudget_Tags_EmptyTag_onCreate
=== CONT  TestAccBudgetsBudget_Tags_DefaultTags_updateToProviderOnly
=== CONT  TestAccBudgetsBudget_Tags_DefaultTags_providerOnly
=== CONT  TestAccBudgetsBudget_Tags_DefaultTags_nonOverlapping
=== CONT  TestAccBudgetsBudget_Tags_EmptyTag_OnUpdate_replace
=== CONT  TestAccBudgetsBudget_autoAdjustDataForecast
=== CONT  TestAccBudgetsBudget_metrics
--- PASS: TestAccBudgetsBudget_autoAdjustDataForecast (61.21s)
=== CONT  TestAccBudgetsBudget_filterExpression
--- PASS: TestAccBudgetsBudget_Tags_DefaultTags_nullNonOverlappingResourceTag (70.21s)
=== CONT  TestAccBudgetsBudget_billingViewARN
--- PASS: TestAccBudgetsBudget_Tags_DefaultTags_emptyResourceTag (72.84s)
=== CONT  TestAccBudgetsBudget_plannedLimits
--- PASS: TestAccBudgetsBudget_Tags_ComputedTag_onCreate (73.16s)
=== CONT  TestAccBudgetsBudget_notifications
--- PASS: TestAccBudgetsBudget_Tags_DefaultTags_nullOverlappingResourceTag (73.19s)
=== CONT  TestAccBudgetsBudget_costTypes
--- PASS: TestAccBudgetsBudget_Tags_DefaultTags_emptyProviderOnlyTag (73.19s)
=== CONT  TestAccBudgetsBudget_autoAdjustDataHistorical
--- PASS: TestAccBudgetsBudget_metrics (98.13s)
=== CONT  TestAccBudgetsBudget_basic
--- PASS: TestAccBudgetsBudget_Tags_emptyMap (98.34s)
=== CONT  TestAccBudgetsBudget_disappears
--- PASS: TestAccBudgetsBudget_Tags_null (98.46s)
=== CONT  TestAccBudgetsBudget_namePrefix
--- PASS: TestAccBudgetsBudget_Tags_DefaultTags_updateToResourceOnly (102.25s)
=== CONT  TestAccBudgetsBudget_Name_generated
--- PASS: TestAccBudgetsBudget_Tags_addOnUpdate (109.30s)
=== CONT  TestAccBudgetsBudget_Tags_IgnoreTags_Overlap_defaultTag
--- PASS: TestAccBudgetsBudget_Tags_EmptyTag_OnUpdate_replace (109.36s)
=== CONT  TestAccBudgetsBudget_Tags_ComputedTag_OnUpdate_replace
--- PASS: TestAccBudgetsBudget_Tags_DefaultTags_updateToProviderOnly (112.46s)
=== CONT  TestAccBudgetsBudget_Tags_IgnoreTags_Overlap_resourceTag
--- PASS: TestAccBudgetsBudget_Tags_ComputedTag_OnUpdate_add (114.09s)
--- PASS: TestAccBudgetsBudget_Tags_EmptyTag_onCreate (121.42s)
--- PASS: TestAccBudgetsBudget_billingViewARN (54.89s)
--- PASS: TestAccBudgetsBudget_disappears (43.77s)
--- PASS: TestAccBudgetsBudget_filterExpression (81.24s)
--- PASS: TestAccBudgetsBudget_basic (49.75s)
--- PASS: TestAccBudgetsBudget_namePrefix (49.93s)
--- PASS: TestAccBudgetsBudget_Tags_EmptyTag_OnUpdate_add (150.88s)
--- PASS: TestAccBudgetsBudget_Name_generated (48.75s)
--- PASS: TestAccBudgetsBudget_plannedLimits (79.78s)
--- PASS: TestAccBudgetsBudget_autoAdjustDataHistorical (79.50s)
--- PASS: TestAccBudgetsBudget_costTypes (79.64s)
--- PASS: TestAccBudgetsBudget_Tags_DefaultTags_nonOverlapping (156.87s)
--- PASS: TestAccBudgetsBudget_Tags_DefaultTags_overlapping (157.63s)
--- PASS: TestAccBudgetsBudget_notifications (87.67s)
--- PASS: TestAccBudgetsBudget_tags (180.77s)
--- PASS: TestAccBudgetsBudget_Tags_ComputedTag_OnUpdate_replace (72.14s)
--- PASS: TestAccBudgetsBudget_Tags_DefaultTags_providerOnly (185.76s)
--- PASS: TestAccBudgetsBudget_Tags_IgnoreTags_Overlap_defaultTag (80.97s)
--- PASS: TestAccBudgetsBudget_Tags_IgnoreTags_Overlap_resourceTag (90.39s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/budgets    208.552s
```

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

**Comment by taruntej-a** [comment]
Thanks for the contribution @Nklya! 🚀

**Comment by Nklya** [comment]
Thank you for review, fixes and release 🙂
