### PR TITLE
r/api_gateway_account - fix account import + add some attributes

### LINKED ISSUE #33236: [Bug]: cloudwatch_role_arn is null when importing aws_api_gateway_account
### Terraform Core Version

1.5.6

### AWS Provider Version

5.14.0

### Affected Resource(s)

* aws_api_gateway_account

### Expected Behavior

When `terraform import aws_api_gateway_account.this api-gateway-account` is executed, the cloudwatch_role_arn should import the actual value.

### Actual Behavior

When running `terraform import aws_api_gateway_account.this api-gateway-account` with cloudwatch_role_arn set on AWS, the value is always null.

### Relevant Error/Panic Output Snippet

_No response_

### Terraform Configuration Files

```
import {
  to = aws_api_gateway_account.this
  id = "api-gateway-account"
}
```

### Steps to Reproduce

Executing `terraform plan -generate-config-out=generated.tf` will generate the following resource.

```
resource "aws_api_gateway_account" "sendgrid_event" {
  cloudwatch_role_arn = null
}
```

Normally, the configured Role ARN should be specified.

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

https://registry.terraform.io/providers/-/aws/latest/docs/resources/api_gateway_account#cloudwatch_role_arn

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by DrFaust92**
### Relations

Closes #33236

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccAPIGatewayAccount_basic  PKG=apigateway
--- PASS: TestAccAPIGatewayAccount_basic (157.07s)
```

### CODE REVIEW

File: internal/service/apigateway/account_test.go [hunk 1]
```diff
@@ -61,50 +62,25 @@ resource "aws_api_gateway_account" "test" {}
...
-      "logs:DescribeLogStreams",
-      "logs:PutLogEvents",
-      "logs:GetLogEvents",
-      "logs:FilterLogEvents"
-    ],
-    "Resource": "*"
-  }]
-}
-EOF
+  managed_policy_arns = ["arn:${data.aws_partition.current.partition}:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs"]
```
Comment (DrFaust92) [inline internal/service/apigateway/account_test.go:83]: should docs maybe also be change to this example for simplicty?

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccAPIGatewayAccount_' PKG=apigateway ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/apigateway/... -v -count 1 -parallel 2  -run=TestAccAPIGatewayAccount_ -timeout 180m
=== RUN   TestAccAPIGatewayAccount_basic
=== PAUSE TestAccAPIGatewayAccount_basic
=== CONT  TestAccAPIGatewayAccount_basic
--- PASS: TestAccAPIGatewayAccount_basic (126.53s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/apigateway	132.205s
```

**Comment by ewbankkit** [comment]
@DrFaust92 Thanks for the contribution :tada: :clap:.
