### PR TITLE
r/aws_instance: launch_template Remove unnecessary api calls

### LINKED ISSUE #20287: Skipping the need for AWS creds seems to have broken in 3.51.0
I think prior to [this change](https://github.com/hashicorp/terraform-provider-aws/pull/10807), the `skip_credentials_validation=true` and `skip_requesting_account_id=true` worked as expected. However, in 3.51.0, I'm seeing "error reading Instance Launch Template Id Tag: AuthFailure: AWS was not able to validate the provided access credentials" even when `launch_template` is not used (see following before/after examples). I was under the assumption that the 5 different [`skip_`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#argument-reference) arguments could be used to turn-off the need for AWS creds during testing (we have integration tests in https://github.com/infracost/infracost that started to fail this morning).

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.2 on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.50.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.3.2
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1

### Affected Resource(s)

* aws_instance

#### 3.50.0 behavior
With this example, `terraform plan` worked ok:
```

terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "3.50.0"
    }
  }
}

provider "aws" {
  region                      = "us-east-1"
  skip_credentials_validation = true
  skip_requesting_account_id  = true
  access_key                  = "mock_access_key"
  secret_key                  = "mock_secret_key"
}

resource "aws_instance" "web_app" {
  ami           = "ami-12312312"
  instance_type = "m5.4xlarge"
}
```

#### 3.51.0 behavior, where `terraform plan` fails
```
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "3.51.0"
    }
  }
}

provider "aws" {
  region                      = "us-east-1"
  skip_credentials_validation = true
  skip_requesting_account_id  = true
  access_key                  = "mock_access_key"
  secret_key                  = "mock_secret_key"
}

resource "aws_instance" "web_app" {
  ami           = "ami-12312312"
  instance_type = "m5.4xlarge"
}
```

`terraform plan` produces this error:
```
│ Error: 1 error occurred:
│ 	* error reading Instance Launch Template Id Tag: AuthFailure: AWS was not able to validate the provided access credentials
│ 	status code: 401, request id: 123123-123123-123123-123-123123
│   with aws_instance.web_app,
│   on main.tf line 18, in resource "aws_instance" "web_app":
│   18: resource "aws_instance" "web_app" {
```

### Expected Behavior

`terraform plan` should have worked as it did in 3.50.0

### Actual Behavior

`terraform plan` failed with "error reading Instance Launch Template Id Tag: AuthFailure: AWS was not able to validate the provided access credentials".

### Steps to Reproduce

1. Create a new TF project with `main.tf` and the previously mentioned examples.
2. Run `terraform init` followed by `terraform apply` and notice how it works ok on 3.50.0 but not on 3.51.0

### References

* #10807

### LINKED ISSUE #20331: ec2_instance errors out plan if launch_template has been deleted
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

- aws/3.51.0/linux_amd64/terraform-provider-aws_v3.51.0_x5
- terraform 1.0.3

### Affected Resource(s)

* aws_instance
 
Have an ec2 instance that was imported into TF many months ago.  This running EC2 can not be replaced.  It was started using a launch template X in the aws console.  In recent versions of (aws or tf - not sure) the launch_template has been showing up as a changed resource (although nothing has actually changed in AWS).

That launch template, X, however, no longer exists in AWS, but the tag on the EC2 resource (aws_instance) still exists indicating that launch template X was used to start the instance.

When terraform runs a plan, it tries to load this (nonexistant) launch template X, and the plan fails with:

```
Error: error reading Instance (i-...) Launch Template: error reading Launch Template: InvalidLaunchTemplateId.NotFound: Atleast one of the launch templates specified in the request does not exist.
│ 	status code: 400, request id
```

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

```
Error: error reading Instance (i-...) Launch Template: error reading Launch Template: InvalidLaunchTemplateId.NotFound: Atleast one of the launch templates specified in the request does not exist.
│ 	status code: 400, request id
```

### Expected Behavior

TF should ignore aws_instance resources that have launch_template tags (the launch template of an instance is specified by a private `aws:...` tag on the resource) which no longer exist - or there should be a way to tell TF to ignore them. It is not possible to edit the `aws:` tag in aws that assigns a launch template to an instance, and that tag is not deleted by aws itself when the template has been deleted.  The only other option I can see to move forward is to entirely delete the ec2 instance - this isn't an option for this instance right now.

### Steps to Reproduce

1. create a launch template in aws
2. create an instance in aws console by using that launch template
3. import that instance into terraform as an `aws_instance`
4. delete the launch template from 1.
5. run `terraform plan`

### References

* #0000

### PR DESCRIPTION
**Pull request by gordonbondon**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

My PR #10807 accidentally introduced two regressions related to instance usage when launch template does not yet exist, or was deleted. This PR addresses those two issues.

Closes #20331
Closes #20287

Output from acceptance testing:

```
$ → make testacc TEST=./aws TESTARGS='-run=TestAccAWSInstance_LaunchTemplate'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSInstance_LaunchTemplate -timeout 180m
=== RUN   TestAccAWSInstance_LaunchTemplate_basic
=== PAUSE TestAccAWSInstance_LaunchTemplate_basic
=== RUN   TestAccAWSInstance_LaunchTemplate_OverrideTemplate
=== PAUSE TestAccAWSInstance_LaunchTemplate_OverrideTemplate
=== RUN   TestAccAWSInstance_LaunchTemplate_SetSpecificVersion
=== PAUSE TestAccAWSInstance_LaunchTemplate_SetSpecificVersion
=== RUN   TestAccAWSInstance_LaunchTemplate_ModifyTemplate_DefaultVersion
=== PAUSE TestAccAWSInstance_LaunchTemplate_ModifyTemplate_DefaultVersion
=== RUN   TestAccAWSInstance_LaunchTemplate_UpdateTemplateVersion
=== PAUSE TestAccAWSInstance_LaunchTemplate_UpdateTemplateVersion
=== RUN   TestAccAWSInstance_LaunchTemplate_SwapIDAndName
=== PAUSE TestAccAWSInstance_LaunchTemplate_SwapIDAndName
=== CONT  TestAccAWSInstance_LaunchTemplate_basic
=== CONT  TestAccAWSInstance_LaunchTemplate_SetSpecificVersion
=== CONT  TestAccAWSInstance_LaunchTemplate_OverrideTemplate
=== CONT  TestAccAWSInstance_LaunchTemplate_UpdateTemplateVersion
=== CONT  TestAccAWSInstance_LaunchTemplate_ModifyTemplate_DefaultVersion
=== CONT  TestAccAWSInstance_LaunchTemplate_SwapIDAndName
--- PASS: TestAccAWSInstance_LaunchTemplate_OverrideTemplate (106.95s)
--- PASS: TestAccAWSInstance_LaunchTemplate_basic (142.57s)
--- PASS: TestAccAWSInstance_LaunchTemplate_SwapIDAndName (177.02s)
--- PASS: TestAccAWSInstance_LaunchTemplate_ModifyTemplate_DefaultVersion (182.85s)
--- PASS: TestAccAWSInstance_LaunchTemplate_SetSpecificVersion (206.90s)
--- PASS: TestAccAWSInstance_LaunchTemplate_UpdateTemplateVersion (213.68s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	216.038s
```

### CODE REVIEW

File: aws/resource_aws_instance.go [hunk 1]
```diff
@@ -639,7 +639,9 @@ func resourceAwsInstance() *schema.Resource {
 		CustomizeDiff: customdiff.All(
 			SetTagsDiff,
 			func(_ context.Context, diff *schema.ResourceDiff, meta interface{}) error {
-				if diff.HasChange("launch_template.0.version") {
+				_, ok := diff.GetOk("launch_template")
+
+				if diff.Id() != "" && diff.HasChange("launch_template.0.version") && ok {
```
Comment (gordonbondon) [inline aws/resource_aws_instance.go:644]: Apparently `HasChange` with an empty state will always return true when resource filed has `Default` value, so I've added a check for top-level key.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

##### Commercial

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSInstance_LaunchTemplate'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSInstance_LaunchTemplate -timeout 180m
=== RUN   TestAccAWSInstance_LaunchTemplate_basic
=== PAUSE TestAccAWSInstance_LaunchTemplate_basic
=== RUN   TestAccAWSInstance_LaunchTemplate_OverrideTemplate
=== PAUSE TestAccAWSInstance_LaunchTemplate_OverrideTemplate
=== RUN   TestAccAWSInstance_LaunchTemplate_SetSpecificVersion
=== PAUSE TestAccAWSInstance_LaunchTemplate_SetSpecificVersion
=== RUN   TestAccAWSInstance_LaunchTemplate_ModifyTemplate_DefaultVersion
=== PAUSE TestAccAWSInstance_LaunchTemplate_ModifyTemplate_DefaultVersion
=== RUN   TestAccAWSInstance_LaunchTemplate_UpdateTemplateVersion
=== PAUSE TestAccAWSInstance_LaunchTemplate_UpdateTemplateVersion
=== RUN   TestAccAWSInstance_LaunchTemplate_SwapIDAndName
=== PAUSE TestAccAWSInstance_LaunchTemplate_SwapIDAndName
=== CONT  TestAccAWSInstance_LaunchTemplate_basic
=== CONT  TestAccAWSInstance_LaunchTemplate_UpdateTemplateVersion
=== CONT  TestAccAWSInstance_LaunchTemplate_ModifyTemplate_DefaultVersion
=== CONT  TestAccAWSInstance_LaunchTemplate_SetSpecificVersion
=== CONT  TestAccAWSInstance_LaunchTemplate_OverrideTemplate
=== CONT  TestAccAWSInstance_LaunchTemplate_SwapIDAndName
--- PASS: TestAccAWSInstance_LaunchTemplate_basic (65.29s)
--- PASS: TestAccAWSInstance_LaunchTemplate_OverrideTemplate (108.64s)
--- PASS: TestAccAWSInstance_LaunchTemplate_SwapIDAndName (113.77s)
--- PASS: TestAccAWSInstance_LaunchTemplate_SetSpecificVersion (120.50s)
--- PASS: TestAccAWSInstance_LaunchTemplate_ModifyTemplate_DefaultVersion (123.63s)
--- PASS: TestAccAWSInstance_LaunchTemplate_UpdateTemplateVersion (219.89s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	223.009s
```

##### GovCloud

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSInstance_LaunchTemplate'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSInstance_LaunchTemplate -timeout 180m
=== RUN   TestAccAWSInstance_LaunchTemplate_basic
=== PAUSE TestAccAWSInstance_LaunchTemplate_basic
=== RUN   TestAccAWSInstance_LaunchTemplate_OverrideTemplate
=== PAUSE TestAccAWSInstance_LaunchTemplate_OverrideTemplate
=== RUN   TestAccAWSInstance_LaunchTemplate_SetSpecificVersion
=== PAUSE TestAccAWSInstance_LaunchTemplate_SetSpecificVersion
=== RUN   TestAccAWSInstance_LaunchTemplate_ModifyTemplate_DefaultVersion
=== PAUSE TestAccAWSInstance_LaunchTemplate_ModifyTemplate_DefaultVersion
=== RUN   TestAccAWSInstance_LaunchTemplate_UpdateTemplateVersion
=== PAUSE TestAccAWSInstance_LaunchTemplate_UpdateTemplateVersion
=== RUN   TestAccAWSInstance_LaunchTemplate_SwapIDAndName
=== PAUSE TestAccAWSInstance_LaunchTemplate_SwapIDAndName
=== CONT  TestAccAWSInstance_LaunchTemplate_basic
=== CONT  TestAccAWSInstance_LaunchTemplate_UpdateTemplateVersion
=== CONT  TestAccAWSInstance_LaunchTemplate_ModifyTemplate_DefaultVersion
=== CONT  TestAccAWSInstance_LaunchTemplate_SwapIDAndName
=== CONT  TestAccAWSInstance_LaunchTemplate_SetSpecificVersion
=== CONT  TestAccAWSInstance_LaunchTemplate_OverrideTemplate
--- PASS: TestAccAWSInstance_LaunchTemplate_OverrideTemplate (70.70s)
--- PASS: TestAccAWSInstance_LaunchTemplate_basic (79.14s)
--- PASS: TestAccAWSInstance_LaunchTemplate_SwapIDAndName (125.26s)
--- PASS: TestAccAWSInstance_LaunchTemplate_SetSpecificVersion (134.76s)
--- PASS: TestAccAWSInstance_LaunchTemplate_ModifyTemplate_DefaultVersion (138.20s)
--- PASS: TestAccAWSInstance_LaunchTemplate_UpdateTemplateVersion (190.27s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	193.365s
```

**Comment by ewbankkit** [comment]
@gordonbondon Thanks for the contribution :tada: :clap:.
