### PR TITLE
r/codebuild_report_group -  Allow deleting reports for report group delete

### LINKED ISSUE #17290: `aws_codebuild_report_group` needs time to delete previously generated reports, fails `terraform apply`
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_codebuild_report_group

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
data "aws_kms_alias" "s3" {
  name = "alias/aws/s3"
}

resource "aws_codebuild_report_group" "tests" {
  name  = "myreport-tests"
  type  = "TEST"

  export_config {
    type = "S3"

    s3_destination {
      bucket              = "my-bucket-name"
      encryption_disabled = false
      encryption_key      = data.aws_kms_alias.s3.arn
      packaging           = "NONE"
      path                = "/reports"
    }
  }
}
```

### Debug Output

```
Error: error deleting CodeBuild Report Groups(arn:aws:codebuild:xxx:yyy:report-group/zzz):
InvalidInputException: Report group could only be deleted after its reports are deleted
```

### Panic Output

N/A

### Expected Behavior

Terraform should poll/wait for reports to be deleted and the report group to be deleted before moving forward in the lifecycle.

### Actual Behavior

Terraform fails to delete the report group immediately because existing reports are still being deleted, and then the `terraform apply` fails.. if I wait a minute for AWS to clean up the reports/report-group then re-run the apply, it succeeds.

### Steps to Reproduce

1. `terraform apply`
2. create some reports via codebuild
3. make a change to the report-group.tf, e.g. name change `tests` -> `tests2`
4. `terraform apply`
5. tf will see recreate required, but fail

### Important Factoids

N/A

### References

N/A

### PR DESCRIPTION
**Pull request by DrFaust92**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #17290

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSCodeBuildReportGroup_'
--- PASS: TestAccAWSCodeBuildReportGroup_disappears (27.56s)
--- PASS: TestAccAWSCodeBuildReportGroup_basic (36.17s)
--- PASS: TestAccAWSCodeBuildReportGroup_deleteReports (36.49s)
--- PASS: TestAccAWSCodeBuildReportGroup_tags (84.09s)
--- PASS: TestAccAWSCodeBuildReportGroup_export_s3 (123.29s)
```

### CODE REVIEW

File: aws/internal/service/codebuild/finder/finder.go [hunk 1]
```diff
@@ -0,0 +1,19 @@
+package finder
+
+import (
+	"github.com/aws/aws-sdk-go/aws"
+	"github.com/aws/aws-sdk-go/service/codebuild"
+)
+
+// ReportGroupByArn returns the Report Group corresponding to the specified Arn.
+func ReportGroupByArn(conn *codebuild.CodeBuild, arn string) (*codebuild.BatchGetReportGroupsOutput, error) {
```
Comment (bflad) [inline aws/internal/service/codebuild/finder/finder.go:9]: Nit: Seems like this finder function should be doing all the work of filtering this down to `*codebuild.ReportGroup` (so `waiter.ReportGroupStatus` and other places do not need to do it).

Comment (DrFaust92) [reply aws/internal/service/codebuild/finder/finder.go:9]: Will change 👍

Comment (DrFaust92) [reply aws/internal/service/codebuild/finder/finder.go]: Done, much better now!

File: .changelog/17338.txt [hunk 2]
```diff
@@ -0,0 +1,3 @@
+```release-note:enhancement
+resource/codebuild_report_group: Allow for deleting reports when deleting a report group
```
Comment (bflad) [inline .changelog/17338.txt:2]:
```suggestion
resource/aws_codebuild_report_group: Add `delete_reports` argument
```

File: aws/resource_aws_codebuild_report_group.go [hunk 3]
```diff
@@ -185,11 +182,16 @@ func resourceAwsCodeBuildReportGroupDelete(d *schema.ResourceData, meta interfac
...
+		DeleteReports: aws.Bool(d.Get("delete_reports").(bool)),
 	}
 
 	if _, err := conn.DeleteReportGroup(deleteOpts); err != nil {
-		return fmt.Errorf("error deleting CodeBuild Report Groups(%s): %w", d.Id(), err)
+		return fmt.Errorf("error deleting CodeBuild Report Group (%s): %w", d.Id(), err)
+	}
+
+	if _, err := waiter.ReportGroupDeleted(conn, d.Id()); err != nil {
+		return fmt.Errorf("error while waiting for CodeBuild Report Group (%s) to become deleted: %s", d.Id(), err)
```
Comment (bflad) [inline aws/resource_aws_codebuild_report_group.go:194]:
```suggestion
		return fmt.Errorf("error while waiting for CodeBuild Report Group (%s) to become deleted: %w", d.Id(), err)
```

File: aws/resource_aws_codebuild_report_group_test.go [hunk 4]
```diff
@@ -2,15 +2,72 @@ package aws
...
+		if page == nil {
+			return !isLast
+		}
+
+		for _, arn := range page.ReportGroups {
+			id := aws.StringValue(arn)
+			r := resourceAwsCodeBuildReportGroup()
+			d := r.Data(nil)
+			d.SetId(id)
+			d.Set("delete_reports", true)
```
Comment (bflad) [inline aws/resource_aws_codebuild_report_group_test.go:45]: Nice!

**Review by bflad — COMMENTED** [review]
Looking good, just will run the testing now

File: aws/resource_aws_codebuild_report_group_test.go [hunk 5]
```diff
@@ -179,22 +266,16 @@ func testAccCheckAWSCodeBuildReportGroupDestroy(s *terraform.State) error {
...
+		if resp != nil {
+			return fmt.Errorf("Found Report Group %s", rs.Primary.ID)
 		}
 
-		for _, reportGroup := range resp.ReportGroups {
-			if rs.Primary.ID == aws.StringValue(reportGroup.Arn) {
-				return fmt.Errorf("Found Report Groups %s", rs.Primary.ID)
-			}
-		}
+		return nil
```
Comment (bflad) [inline aws/resource_aws_codebuild_report_group_test.go:278]: Always `continue` in `CheckDestroy` loop in case there are multiple resources in the configuration. 😄  Reference: https://github.com/hashicorp/terraform-provider-aws/issues/15847

```suggestion
```

Comment (DrFaust92) [reply aws/resource_aws_codebuild_report_group_test.go]: 👍

**Review by bflad — APPROVED** [review]
Looks great, thank you, @DrFaust92 🚀 

Output from acceptance testing in AWS Commercial:

```
--- PASS: TestAccAWSCodeBuildReportGroup_disappears (10.64s)
--- PASS: TestAccAWSCodeBuildReportGroup_deleteReports (13.91s)
--- PASS: TestAccAWSCodeBuildReportGroup_basic (14.42s)
--- PASS: TestAccAWSCodeBuildReportGroup_tags (30.94s)
--- PASS: TestAccAWSCodeBuildReportGroup_export_s3 (46.32s)
```

Output from acceptance testing in AWS GovCloud (US):

```
--- PASS: TestAccAWSCodeBuildReportGroup_disappears (14.58s)
--- PASS: TestAccAWSCodeBuildReportGroup_basic (19.24s)
--- PASS: TestAccAWSCodeBuildReportGroup_deleteReports (19.27s)
--- PASS: TestAccAWSCodeBuildReportGroup_tags (44.22s)
--- PASS: TestAccAWSCodeBuildReportGroup_export_s3 (50.66s)
```
