### PR TITLE
Simplify single security group searches and error handling

### LINKED ISSUE #19965: aws_default_security_group cannot be destroyed when vpc is manually deleted
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
$ terraform version
Terraform v0.12.31
+ provider.aws v3.47.0
```

### Affected Resource(s)

* aws_default_security_group

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

- main.tf

```hcl
provider "aws" {
  access_key = var.ACCESS_KEY_ID
  secret_key = var.SECRET_ACCESS_KEY
  region     = "eu-west-1"
}

resource "aws_vpc_dhcp_options" "vpc_dhcp_options" {
  domain_name         = "eu-west-1.compute.internal"
  domain_name_servers = ["AmazonProvidedDNS"]
}

resource "aws_vpc" "vpc" {
  cidr_block           = "10.250.0.0/16"
  enable_dns_support   = true
  enable_dns_hostnames = true
}

resource "aws_vpc_dhcp_options_association" "vpc_dhcp_options_association" {
  vpc_id          = aws_vpc.vpc.id
  dhcp_options_id = aws_vpc_dhcp_options.vpc_dhcp_options.id
}

resource "aws_default_security_group" "default" {
  vpc_id = aws_vpc.vpc.id
}
```

### Debug Output

Not applicable.

### Panic Output

Not applicable.

### Expected Behavior

`terraform destroy` to be able to destroy even when the vpc is manually deleted.

### Actual Behavior

`terraform destroy` fails to destroy when the vpc is manually deleted.

### Steps to Reproduce

1. `terraform apply`

```
$ terraform apply -var-file=creds.tfvars

aws_vpc_dhcp_options.vpc_dhcp_options: Creating...
aws_vpc.vpc: Creating...
aws_vpc_dhcp_options.vpc_dhcp_options: Creation complete after 2s [id=dopt-0777c3b2a92db1234]
aws_vpc.vpc: Still creating... [10s elapsed]
aws_vpc.vpc: Creation complete after 19s [id=vpc-06e6705da603f1234]
aws_vpc_dhcp_options_association.vpc_dhcp_options_association: Creating...
aws_default_security_group.default: Creating...
aws_vpc_dhcp_options_association.vpc_dhcp_options_association: Creation complete after 1s [id=dopt-0777c3b2a92db1234-vpc-06e6705da603f1234]
aws_default_security_group.default: Creation complete after 2s [id=sg-0505854f62efb1234]

Apply complete! Resources: 4 added, 0 changed, 0 destroyed.
```

2. Delete manually the created vpc

```
$ aws ec2 delete-vpc --vpc-id vpc-06e6705da603f1234
```

3. Ensure that `terraform destroy` fails to refresh the aws_default_security_group

```
$ terraform destroy -var-file=creds.tfvars
aws_vpc_dhcp_options.vpc_dhcp_options: Refreshing state... [id=dopt-0777c3b2a92db1234]
aws_vpc.vpc: Refreshing state... [id=vpc-06e6705da603f1234]
aws_vpc_dhcp_options_association.vpc_dhcp_options_association: Refreshing state... [id=dopt-0777c3b2a92db1234-vpc-06e6705da603f1234]
aws_default_security_group.default: Refreshing state... [id=sg-0505854f62efb1234]

Error: InvalidGroup.NotFound: The security group 'sg-0505854f62efb1234' does not exist
	status code: 400, request id: <omitted>

```

### References

* #0000

### PR DESCRIPTION
**Pull request by gdavison**
Updates `finder.SecurityGroup...()` functions to return a `resource.NotFound` error to simplify error handling. Replaces a number of calls to the AWS SDK function with `finder.SecurityGroup..()`.

Closes #19965.

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSDefaultSecurityGroup_\|TestAccAWSEMRCluster_\|TestAccAwsGlobalAcceleratorEndpointGroup_\|TestAccAWSSecurityGroupRule_\|TestAccAWSSecurityGroup_'

--- SKIP: TestAccAWSDefaultSecurityGroup_Classic_empty (0.00s)
--- PASS: TestAccAWSDefaultSecurityGroup_Vpc_basic (294.59s)
--- PASS: TestAccAWSDefaultSecurityGroup_Classic_basic (73.46s)
--- PASS: TestAccAWSDefaultSecurityGroup_Vpc_empty (61.08s)

--- PASS: TestAccAWSSecurityGroupRule_PartialMatching_basic (271.47s)
--- PASS: TestAccAWSSecurityGroupRule_ExpectInvalidCIDR (58.99s)
--- PASS: TestAccAWSSecurityGroupRule_MultipleRuleSearching_AllProtocolCrash (145.49s)
--- PASS: TestAccAWSSecurityGroupRule_EgressDescription (190.14s)
--- PASS: TestAccAWSSecurityGroupRule_PrefixListEgress (213.44s)
--- PASS: TestAccAWSSecurityGroupRule_IngressDescription (186.63s)
--- PASS: TestAccAWSSecurityGroupRule_ExpectInvalidTypeError (43.66s)
--- PASS: TestAccAWSSecurityGroupRule_EgressDescription_updates (297.94s)
--- PASS: TestAccAWSSecurityGroupRule_IngressDescription_updates (295.87s)
--- PASS: TestAccAWSSecurityGroupRule_Description_AllPorts_NonZeroPorts (260.63s)
--- PASS: TestAccAWSSecurityGroupRule_Ingress_Ipv6 (164.42s)
--- PASS: TestAccAWSSecurityGroupRule_Description_AllPorts (262.23s)
--- PASS: TestAccAWSSecurityGroupRule_SelfReference (163.88s)
--- PASS: TestAccAWSSecurityGroupRule_Egress (159.44s)
--- PASS: TestAccAWSSecurityGroupRule_MultiIngress (161.69s)
--- PASS: TestAccAWSSecurityGroupRule_Ingress_Classic (151.80s)
--- PASS: TestAccAWSSecurityGroupRule_SelfSource (98.30s)
--- PASS: TestAccAWSSecurityGroupRule_Issue5310 (88.79s)
--- PASS: TestAccAWSSecurityGroupRule_Ingress_Protocol (110.02s)
--- PASS: TestAccAWSSecurityGroupRule_MultiDescription (434.39s)
--- PASS: TestAccAWSSecurityGroupRule_Ingress_Source_With_Account_Id (95.13s)
--- PASS: TestAccAWSSecurityGroupRule_PartialMatching_Source (89.65s)
--- PASS: TestAccAWSSecurityGroupRule_Race (262.54s)
--- PASS: TestAccAWSSecurityGroupRule_Ingress_VPC (67.93s)

--- PASS: TestAccAwsGlobalAcceleratorEndpointGroup_disappears (321.80s)
--- PASS: TestAccAwsGlobalAcceleratorEndpointGroup_MultiRegion (352.97s)
--- PASS: TestAccAwsGlobalAcceleratorEndpointGroup_TCPHealthCheckProtocol (296.41s)
--- PASS: TestAccAwsGlobalAcceleratorEndpointGroup_basic (253.82s)
--- PASS: TestAccAwsGlobalAcceleratorEndpointGroup_Update (406.31s)
--- PASS: TestAccAwsGlobalAcceleratorEndpointGroup_PortOverrides (419.51s)
--- PASS: TestAccAwsGlobalAcceleratorEndpointGroup_InstanceEndpoint (744.76s)
--- PASS: TestAccAwsGlobalAcceleratorEndpointGroup_ALBEndpoint_ClientIP (888.99s)

--- PASS: TestAccAWSSecurityGroup_failWithDiffMismatch (165.33s)
--- PASS: TestAccAWSSecurityGroup_ingressWithCidrAndSGsClassic (188.08s)
--- PASS: TestAccAWSSecurityGroup_basic (191.57s)
--- PASS: TestAccAWSSecurityGroup_ipv4andipv6Egress (195.10s)
--- PASS: TestAccAWSSecurityGroup_ingressWithCidrAndSGsVPC (198.85s)
--- PASS: TestAccAWSSecurityGroup_CIDRandGroups (201.75s)
--- PASS: TestAccAWSSecurityGroup_multiIngress (207.18s)
--- PASS: TestAccAWSSecurityGroup_egressWithPrefixList (208.52s)
--- PASS: TestAccAWSSecurityGroup_ingressWithPrefixList (209.08s)
--- PASS: TestAccAWSSecurityGroup_ruleGathering (209.63s)
--- FAIL: TestAccAWSSecurityGroup_ruleLimitCidrBlockExceededAppend (243.07s)
--- FAIL: TestAccAWSSecurityGroup_ruleLimitExceededAllNew (264.85s)
--- FAIL: TestAccAWSSecurityGroup_ruleLimitExceededAppend (268.24s)
--- FAIL: TestAccAWSSecurityGroup_ruleLimitExceededPrepend (269.33s)
--- PASS: TestAccAWSSecurityGroup_rulesDropOnError (271.65s)
--- PASS: TestAccAWSSecurityGroup_invalidCIDRBlock (85.36s)
--- PASS: TestAccAWSSecurityGroup_ingressConfigMode (377.62s)
--- PASS: TestAccAWSSecurityGroup_egressConfigMode (382.07s)
--- PASS: TestAccAWSSecurityGroup_drift (185.68s)
--- PASS: TestAccAWSSecurityGroup_driftComplex (201.23s)
--- PASS: TestAccAWSSecurityGroup_defaultEgressClassic (190.29s)
--- PASS: TestAccAWSSecurityGroup_vpcProtoNumIngress (209.21s)
--- PASS: TestAccAWSSecurityGroup_vpcNegOneIngress (220.34s)
--- PASS: TestAccAWSSecurityGroup_vpc (218.13s)
--- PASS: TestAccAWSSecurityGroup_defaultEgressVPC (216.03s)
--- PASS: TestAccAWSSecurityGroup_self (218.63s)
--- PASS: TestAccAWSSecurityGroup_NamePrefix_TerraformPrefix (195.92s)
--- PASS: TestAccAWSSecurityGroup_NamePrefix (201.10s)
--- PASS: TestAccAWSSecurityGroup_Name_TerraformPrefix (203.69s)
--- PASS: TestAccAWSSecurityGroup_Name_Generated (204.16s)
--- PASS: TestAccAWSSecurityGroup_ipv6 (219.60s)
--- PASS: TestAccAWSSecurityGroup_tags (414.33s)
--- PASS: TestAccAWSSecurityGroup_IPRangesWithSameRules (202.56s)
--- PASS: TestAccAWSSecurityGroup_IPRangeAndSecurityGroupWithSameRules (202.48s)
--- PASS: TestAccAWSSecurityGroup_sourceSecurityGroup (193.03s)
--- PASS: TestAccAWSSecurityGroup_change (346.91s)
--- PASS: TestAccAWSSecurityGroup_allowAll (191.44s)
--- PASS: TestAccAWSSecurityGroup_ruleDescription (454.90s)
--- PASS: TestAccAWSSecurityGroup_forceRevokeRulesTrue (1013.00s)
--- PASS: TestAccAWSSecurityGroup_forceRevokeRulesFalse (893.68s)

--- PASS: TestAccAWSEMRCluster_s3Logging (700.73s)
--- PASS: TestAccAWSEMRCluster_instance_fleet_master_only (541.82s)
--- PASS: TestAccAWSEMRCluster_instance_fleet (559.22s)
--- PASS: TestAccAWSEMRCluster_custom_ami_id (569.20s)
--- PASS: TestAccAWSEMRCluster_Kerberos_ClusterDedicatedKdc (506.56s)
--- PASS: TestAccAWSEMRCluster_ebs_config (573.94s)
--- PASS: TestAccAWSEMRCluster_Step_Basic (468.37s)
--- PASS: TestAccAWSEMRCluster_terminationProtected (520.51s)
--- PASS: TestAccAWSEMRCluster_step_concurrency_level (540.32s)
--- PASS: TestAccAWSEMRCluster_Step_Multiple (498.68s)
--- PASS: TestAccAWSEMRCluster_root_volume_size (776.45s)
--- PASS: TestAccAWSEMRCluster_CoreInstanceGroup_AutoscalingPolicy (542.09s)
--- PASS: TestAccAWSEMRCluster_security_config (484.68s)
--- PASS: TestAccAWSEMRCluster_visibleToAllUsers (805.89s)
--- PASS: TestAccAWSEMRCluster_Ec2Attributes_DefaultManagedSecurityGroups (780.92s)
--- PASS: TestAccAWSEMRCluster_configurationsJson (459.96s)
--- PASS: TestAccAWSEMRCluster_additionalInfo (423.57s)
--- PASS: TestAccAWSEMRCluster_keepJob (425.27s)
--- PASS: TestAccAWSEMRCluster_MasterInstanceGroup_InstanceType (809.91s)
--- PASS: TestAccAWSEMRCluster_basic (415.15s)
--- PASS: TestAccAWSEMRCluster_CoreInstanceGroup_InstanceCount (614.14s)
--- PASS: TestAccAWSEMRCluster_disappears (481.99s)
--- PASS: TestAccAWSEMRCluster_tags (1054.55s)
--- PASS: TestAccAWSEMRCluster_Step_ConfigMode (1138.08s)
--- PASS: TestAccAWSEMRCluster_CoreInstanceGroup_InstanceType (924.31s)
--- PASS: TestAccAWSEMRCluster_MasterInstanceGroup_Name (949.85s)
--- PASS: TestAccAWSEMRCluster_CoreInstanceGroup_Name (992.51s)
--- PASS: TestAccAWSEMRCluster_bootstrap_ordering (1419.39s)
--- PASS: TestAccAWSEMRCluster_MasterInstanceGroup_BidPrice (1148.93s)
--- PASS: TestAccAWSEMRCluster_CoreInstanceGroup_BidPrice (985.30s)
--- PASS: TestAccAWSEMRCluster_MasterInstanceGroup_InstanceCount (1190.65s)
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
Will this PR need refactoring once #17613 is merged?

**Comment by gdavison** [comment]
> Will this PR need refactoring once #17613 is merged?

Yes, basically backing out commit 1afb84f

File: aws/data_source_aws_security_group.go [hunk 1]
```diff
@@ -76,19 +79,19 @@ func dataSourceAwsSecurityGroupRead(d *schema.ResourceData, meta interface{}) er
 		req.Filters = nil
 	}
 
-	log.Printf("[DEBUG] Reading Security Group: %s", req)
-	resp, err := conn.DescribeSecurityGroups(req)
+	sg, err := finder.SecurityGroup(conn, req)
```
Comment (ewbankkit) [inline aws/data_source_aws_security_group.go:82]: Ugly but necessary until #17613 is merged.

File: aws/resource_aws_security_group.go [hunk 2]
```diff
@@ -330,10 +328,8 @@ func resourceAwsSecurityGroupCreate(d *schema.ResourceData, meta interface{}) er
 		if err != nil {
 			//If we have a NotFound or InvalidParameterValue, then we are trying to remove the default IPv6 egress of a non-IPv6
 			//enabled SG
-			if ec2err, ok := err.(awserr.Error); ok && ec2err.Code() != "InvalidPermission.NotFound" && !isAWSErr(err, "InvalidParameterValue", "remote-ipv6-range") {
-				return fmt.Errorf(
-					"Error revoking default IPv6 egress rule for Security Group (%s): %s",
-					d.Id(), err)
+			if !tfawserr.ErrCodeEquals(err, "InvalidPermission.NotFound") && !tfawserr.ErrMessageContains(err, "InvalidParameterValue", "remote-ipv6-range") {
```
Comment (ewbankkit) [inline aws/resource_aws_security_group.go:331]: Add/use error code constants in `aws/internal/service/ec2/errors.go`?

File: aws/resource_aws_security_group_rule.go [hunk 3]
```diff
@@ -206,28 +208,23 @@ func resourceAwsSecurityGroupRuleCreate(d *schema.ResourceData, meta interface{}
 		return fmt.Errorf("Security Group Rule must be type 'ingress' or type 'egress'")
 	}
 
-	if autherr != nil {
-		if awsErr, ok := autherr.(awserr.Error); ok {
-			if awsErr.Code() == "InvalidPermission.Duplicate" {
-				return fmt.Errorf(`[WARN] A duplicate Security Group rule was found on (%s). This may be
+	if tfawserr.ErrCodeEquals(autherr, "InvalidPermission.Duplicate") {
```
Comment (ewbankkit) [inline aws/resource_aws_security_group_rule.go:211]: Add/use error code constants in `aws/internal/service/ec2/errors.go`?

File: aws/resource_aws_default_security_group.go [hunk 4]
```diff
@@ -267,14 +268,14 @@ func resourceAwsDefaultSecurityGroupRead(d *schema.ResourceData, meta interface{
 	ignoreTagsConfig := meta.(*AWSClient).IgnoreTagsConfig
 
 	group, err := finder.SecurityGroupByID(conn, d.Id())
-	if err != nil {
-		return err
-	}
-	if group == nil {
+	if tfresource.NotFound(err) {
```
Comment (ewbankkit) [inline aws/resource_aws_default_security_group.go:271]: Add `d.IsNewResource()` check (#16796)?

File: aws/resource_aws_default_security_group.go [hunk 5]
```diff
@@ -267,14 +268,14 @@ func resourceAwsDefaultSecurityGroupRead(d *schema.ResourceData, meta interface{
...
 		log.Printf("[WARN] Security group (%s) not found, removing from state", d.Id())
 		d.SetId("")
 		return nil
 	}
+	if err != nil {
+		return err
```
Comment (ewbankkit) [inline aws/resource_aws_default_security_group.go:277]: Add some error context (`return fmt.Errorf("error reading Security Group (%s): %w", d.Id(), err)`)?

File: aws/resource_aws_default_security_group.go [hunk 6]
```diff
@@ -327,14 +328,14 @@ func resourceAwsDefaultSecurityGroupUpdate(d *schema.ResourceData, meta interfac
 	conn := meta.(*AWSClient).ec2conn
 
 	group, err := finder.SecurityGroupByID(conn, d.Id())
-	if err != nil {
-		return err
-	}
-	if group == nil {
+	if tfresource.NotFound(err) {
```
Comment (ewbankkit) [inline aws/resource_aws_default_security_group.go:331]: Add `d.IsNewResource()` check (#16796)?

File: aws/resource_aws_default_security_group.go [hunk 7]
```diff
@@ -327,14 +328,14 @@ func resourceAwsDefaultSecurityGroupUpdate(d *schema.ResourceData, meta interfac
...
 		log.Printf("[WARN] Security group (%s) not found, removing from state", d.Id())
 		d.SetId("")
 		return nil
 	}
+	if err != nil {
+		return err
```
Comment (ewbankkit) [inline aws/resource_aws_default_security_group.go:337]: Add some error context (`return fmt.Errorf("error reading Security Group (%s): %w", d.Id(), err)`)?

File: aws/resource_aws_globalaccelerator_endpoint_group_test.go [hunk 8]
```diff
@@ -469,27 +471,18 @@ func testAccCheckGlobalAcceleratorEndpointGroupDeleteGlobalAcceleratorSecurityGr
...
-		input := &ec2.DescribeSecurityGroupsInput{
-			Filters: buildEC2AttributeFilterList(
-				map[string]string{
-					"group-name": "GlobalAccelerator",
-					"vpc-id":     aws.StringValue(vpc.VpcId),
-				},
-			),
+		sg, err := ec2finder.SecurityGroupByNameAndVpcID(conn, "GlobalAccelerator", aws.StringValue(vpc.VpcId))
+		var nfe *resource.NotFoundError
+		if errors.As(err, &nfe) {
```
Comment (ewbankkit) [inline aws/resource_aws_globalaccelerator_endpoint_group_test.go:476]: Use `tfresource.NotFound(err)`.

File: aws/resource_aws_security_group.go [hunk 9]
```diff
@@ -347,25 +343,16 @@ func resourceAwsSecurityGroupRead(d *schema.ResourceData, meta interface{}) erro
...
-	}
-
-	if err != nil {
-		return err
-	}
-
-	if sgRaw == nil {
+	sg, err := finder.SecurityGroupByID(conn, d.Id())
+	var nfe *resource.NotFoundError
+	if errors.As(err, &nfe) {
```
Comment (ewbankkit) [inline aws/resource_aws_security_group.go:348]: Use `tfresource.NotFound(err)`.
Add `d.IsNewResource()` check (#16796)?

File: aws/resource_aws_security_group_rule.go [hunk 10]
```diff
@@ -280,17 +277,17 @@ information and instructions for recovery. Error message: %s`, sg_id, awsErr.Mes
 func resourceAwsSecurityGroupRuleRead(d *schema.ResourceData, meta interface{}) error {
 	conn := meta.(*AWSClient).ec2conn
 	sg_id := d.Get("security_group_id").(string)
-	sg, err := findResourceSecurityGroup(conn, sg_id)
-	if _, notFound := err.(securityGroupNotFound); notFound {
-		// The security group containing this rule no longer exists.
+	sg, err := finder.SecurityGroupByID(conn, sg_id)
+	if tfresource.NotFound(err) {
```
Comment (ewbankkit) [inline aws/resource_aws_security_group_rule.go:281]: Add `d.IsNewResource()` check (#16796)?

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% EC2_SECURITY_GROUP_RULES_PER_GROUP_LIMIT=60 make testacc TEST=./aws TESTARGS='-run=TestAccAWSDefaultSecurityGroup_\|TestAccAWSEMRCluster_\|TestAccAwsGlobalAcceleratorEndpointGroup_\|TestAccAWSSecurityGroupRule_\|TestAccAWSSecurityGroup_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSDefaultSecurityGroup_\|TestAccAWSEMRCluster_\|TestAccAwsGlobalAcceleratorEndpointGroup_\|TestAccAWSSecurityGroupRule_\|TestAccAWSSecurityGroup_ -timeout 180m
=== RUN   TestAccAWSDefaultSecurityGroup_Vpc_basic
=== PAUSE TestAccAWSDefaultSecurityGroup_Vpc_basic
=== RUN   TestAccAWSDefaultSecurityGroup_Vpc_empty
=== PAUSE TestAccAWSDefaultSecurityGroup_Vpc_empty
=== RUN   TestAccAWSDefaultSecurityGroup_Classic_basic
=== PAUSE TestAccAWSDefaultSecurityGroup_Classic_basic
=== RUN   TestAccAWSDefaultSecurityGroup_Classic_empty
    provider_test.go:55: This resource does not currently clear tags when adopting the resource
--- SKIP: TestAccAWSDefaultSecurityGroup_Classic_empty (0.00s)
=== RUN   TestAccAWSEMRCluster_basic
=== PAUSE TestAccAWSEMRCluster_basic
=== RUN   TestAccAWSEMRCluster_additionalInfo
=== PAUSE TestAccAWSEMRCluster_additionalInfo
=== RUN   TestAccAWSEMRCluster_disappears
=== PAUSE TestAccAWSEMRCluster_disappears
=== RUN   TestAccAWSEMRCluster_configurationsJson
=== PAUSE TestAccAWSEMRCluster_configurationsJson
=== RUN   TestAccAWSEMRCluster_CoreInstanceGroup_AutoscalingPolicy
=== PAUSE TestAccAWSEMRCluster_CoreInstanceGroup_AutoscalingPolicy
=== RUN   TestAccAWSEMRCluster_CoreInstanceGroup_BidPrice
=== PAUSE TestAccAWSEMRCluster_CoreInstanceGroup_BidPrice
=== RUN   TestAccAWSEMRCluster_CoreInstanceGroup_InstanceCount
=== PAUSE TestAccAWSEMRCluster_CoreInstanceGroup_InstanceCount
=== RUN   TestAccAWSEMRCluster_CoreInstanceGroup_InstanceType
=== PAUSE TestAccAWSEMRCluster_CoreInstanceGroup_InstanceType
=== RUN   TestAccAWSEMRCluster_CoreInstanceGroup_Name
=== PAUSE TestAccAWSEMRCluster_CoreInstanceGroup_Name
=== RUN   TestAccAWSEMRCluster_Ec2Attributes_DefaultManagedSecurityGroups
=== PAUSE TestAccAWSEMRCluster_Ec2Attributes_DefaultManagedSecurityGroups
=== RUN   TestAccAWSEMRCluster_Kerberos_ClusterDedicatedKdc
=== PAUSE TestAccAWSEMRCluster_Kerberos_ClusterDedicatedKdc
=== RUN   TestAccAWSEMRCluster_MasterInstanceGroup_BidPrice
=== PAUSE TestAccAWSEMRCluster_MasterInstanceGroup_BidPrice
=== RUN   TestAccAWSEMRCluster_MasterInstanceGroup_InstanceCount
=== PAUSE TestAccAWSEMRCluster_MasterInstanceGroup_InstanceCount
=== RUN   TestAccAWSEMRCluster_MasterInstanceGroup_InstanceType
=== PAUSE TestAccAWSEMRCluster_MasterInstanceGroup_InstanceType
=== RUN   TestAccAWSEMRCluster_MasterInstanceGroup_Name
=== PAUSE TestAccAWSEMRCluster_MasterInstanceGroup_Name
=== RUN   TestAccAWSEMRCluster_security_config
=== PAUSE TestAccAWSEMRCluster_security_config
=== RUN   TestAccAWSEMRCluster_Step_Basic
=== PAUSE TestAccAWSEMRCluster_Step_Basic
=== RUN   TestAccAWSEMRCluster_Step_ConfigMode
=== PAUSE TestAccAWSEMRCluster_Step_ConfigMode
=== RUN   TestAccAWSEMRCluster_Step_Multiple
=== PAUSE TestAccAWSEMRCluster_Step_Multiple
=== RUN   TestAccAWSEMRCluster_bootstrap_ordering
=== PAUSE TestAccAWSEMRCluster_bootstrap_ordering
=== RUN   TestAccAWSEMRCluster_terminationProtected
=== PAUSE TestAccAWSEMRCluster_terminationProtected
=== RUN   TestAccAWSEMRCluster_keepJob
=== PAUSE TestAccAWSEMRCluster_keepJob
=== RUN   TestAccAWSEMRCluster_visibleToAllUsers
=== PAUSE TestAccAWSEMRCluster_visibleToAllUsers
=== RUN   TestAccAWSEMRCluster_s3Logging
=== PAUSE TestAccAWSEMRCluster_s3Logging
=== RUN   TestAccAWSEMRCluster_tags
=== PAUSE TestAccAWSEMRCluster_tags
=== RUN   TestAccAWSEMRCluster_root_volume_size
=== PAUSE TestAccAWSEMRCluster_root_volume_size
=== RUN   TestAccAWSEMRCluster_step_concurrency_level
=== PAUSE TestAccAWSEMRCluster_step_concurrency_level
=== RUN   TestAccAWSEMRCluster_ebs_config
=== PAUSE TestAccAWSEMRCluster_ebs_config
=== RUN   TestAccAWSEMRCluster_custom_ami_id
=== PAUSE TestAccAWSEMRCluster_custom_ami_id
=== RUN   TestAccAWSEMRCluster_InstanceFleet_basic
=== PAUSE TestAccAWSEMRCluster_InstanceFleet_basic
=== RUN   TestAccAWSEMRCluster_InstanceFleet_master_only
=== PAUSE TestAccAWSEMRCluster_InstanceFleet_master_only
=== RUN   TestAccAwsGlobalAcceleratorEndpointGroup_basic
=== PAUSE TestAccAwsGlobalAcceleratorEndpointGroup_basic
=== RUN   TestAccAwsGlobalAcceleratorEndpointGroup_disappears
=== PAUSE TestAccAwsGlobalAcceleratorEndpointGroup_disappears
=== RUN   TestAccAwsGlobalAcceleratorEndpointGroup_ALBEndpoint_ClientIP
=== PAUSE TestAccAwsGlobalAcceleratorEndpointGroup_ALBEndpoint_ClientIP
=== RUN   TestAccAwsGlobalAcceleratorEndpointGroup_InstanceEndpoint
=== PAUSE TestAccAwsGlobalAcceleratorEndpointGroup_InstanceEndpoint
=== RUN   TestAccAwsGlobalAcceleratorEndpointGroup_MultiRegion
=== PAUSE TestAccAwsGlobalAcceleratorEndpointGroup_MultiRegion
=== RUN   TestAccAwsGlobalAcceleratorEndpointGroup_PortOverrides
=== PAUSE TestAccAwsGlobalAcceleratorEndpointGroup_PortOverrides
=== RUN   TestAccAwsGlobalAcceleratorEndpointGroup_TCPHealthCheckProtocol
=== PAUSE TestAccAwsGlobalAcceleratorEndpointGroup_TCPHealthCheckProtocol
=== RUN   TestAccAwsGlobalAcceleratorEndpointGroup_Update
=== PAUSE TestAccAwsGlobalAcceleratorEndpointGroup_Update
=== RUN   TestAccAWSSecurityGroupRule_Ingress_VPC
=== PAUSE TestAccAWSSecurityGroupRule_Ingress_VPC
=== RUN   TestAccAWSSecurityGroupRule_Ingress_Source_With_Account_Id
=== PAUSE TestAccAWSSecurityGroupRule_Ingress_Source_With_Account_Id
=== RUN   TestAccAWSSecurityGroupRule_Ingress_Protocol
=== PAUSE TestAccAWSSecurityGroupRule_Ingress_Protocol
=== RUN   TestAccAWSSecurityGroupRule_Ingress_Ipv6
=== PAUSE TestAccAWSSecurityGroupRule_Ingress_Ipv6
=== RUN   TestAccAWSSecurityGroupRule_Ingress_Classic
=== PAUSE TestAccAWSSecurityGroupRule_Ingress_Classic
=== RUN   TestAccAWSSecurityGroupRule_MultiIngress
=== PAUSE TestAccAWSSecurityGroupRule_MultiIngress
=== RUN   TestAccAWSSecurityGroupRule_Egress
=== PAUSE TestAccAWSSecurityGroupRule_Egress
=== RUN   TestAccAWSSecurityGroupRule_SelfReference
=== PAUSE TestAccAWSSecurityGroupRule_SelfReference
=== RUN   TestAccAWSSecurityGroupRule_ExpectInvalidTypeError
=== PAUSE TestAccAWSSecurityGroupRule_ExpectInvalidTypeError
=== RUN   TestAccAWSSecurityGroupRule_ExpectInvalidCIDR
=== PAUSE TestAccAWSSecurityGroupRule_ExpectInvalidCIDR
=== RUN   TestAccAWSSecurityGroupRule_PartialMatching_basic
=== PAUSE TestAccAWSSecurityGroupRule_PartialMatching_basic
=== RUN   TestAccAWSSecurityGroupRule_PartialMatching_Source
=== PAUSE TestAccAWSSecurityGroupRule_PartialMatching_Source
=== RUN   TestAccAWSSecurityGroupRule_Issue5310
=== PAUSE TestAccAWSSecurityGroupRule_Issue5310
=== RUN   TestAccAWSSecurityGroupRule_Race
=== PAUSE TestAccAWSSecurityGroupRule_Race
=== RUN   TestAccAWSSecurityGroupRule_SelfSource
=== PAUSE TestAccAWSSecurityGroupRule_SelfSource
=== RUN   TestAccAWSSecurityGroupRule_PrefixListEgress
=== PAUSE TestAccAWSSecurityGroupRule_PrefixListEgress
=== RUN   TestAccAWSSecurityGroupRule_IngressDescription
=== PAUSE TestAccAWSSecurityGroupRule_IngressDescription
=== RUN   TestAccAWSSecurityGroupRule_EgressDescription
=== PAUSE TestAccAWSSecurityGroupRule_EgressDescription
=== RUN   TestAccAWSSecurityGroupRule_IngressDescription_updates
=== PAUSE TestAccAWSSecurityGroupRule_IngressDescription_updates
=== RUN   TestAccAWSSecurityGroupRule_EgressDescription_updates
=== PAUSE TestAccAWSSecurityGroupRule_EgressDescription_updates
=== RUN   TestAccAWSSecurityGroupRule_Description_AllPorts
=== PAUSE TestAccAWSSecurityGroupRule_Description_AllPorts
=== RUN   TestAccAWSSecurityGroupRule_Description_AllPorts_NonZeroPorts
=== PAUSE TestAccAWSSecurityGroupRule_Description_AllPorts_NonZeroPorts
=== RUN   TestAccAWSSecurityGroupRule_MultipleRuleSearching_AllProtocolCrash
=== PAUSE TestAccAWSSecurityGroupRule_MultipleRuleSearching_AllProtocolCrash
=== RUN   TestAccAWSSecurityGroupRule_MultiDescription
=== PAUSE TestAccAWSSecurityGroupRule_MultiDescription
=== RUN   TestAccAWSSecurityGroup_allowAll
=== PAUSE TestAccAWSSecurityGroup_allowAll
=== RUN   TestAccAWSSecurityGroup_sourceSecurityGroup
=== PAUSE TestAccAWSSecurityGroup_sourceSecurityGroup
=== RUN   TestAccAWSSecurityGroup_IPRangeAndSecurityGroupWithSameRules
=== PAUSE TestAccAWSSecurityGroup_IPRangeAndSecurityGroupWithSameRules
=== RUN   TestAccAWSSecurityGroup_IPRangesWithSameRules
=== PAUSE TestAccAWSSecurityGroup_IPRangesWithSameRules
=== RUN   TestAccAWSSecurityGroup_basic
=== PAUSE TestAccAWSSecurityGroup_basic
=== RUN   TestAccAWSSecurityGroup_egressConfigMode
=== PAUSE TestAccAWSSecurityGroup_egressConfigMode
=== RUN   TestAccAWSSecurityGroup_ingressConfigMode
=== PAUSE TestAccAWSSecurityGroup_ingressConfigMode
=== RUN   TestAccAWSSecurityGroup_ruleGathering
=== PAUSE TestAccAWSSecurityGroup_ruleGathering
=== RUN   TestAccAWSSecurityGroup_forceRevokeRulesTrue
=== PAUSE TestAccAWSSecurityGroup_forceRevokeRulesTrue
=== RUN   TestAccAWSSecurityGroup_forceRevokeRulesFalse
=== PAUSE TestAccAWSSecurityGroup_forceRevokeRulesFalse
=== RUN   TestAccAWSSecurityGroup_ipv6
=== PAUSE TestAccAWSSecurityGroup_ipv6
=== RUN   TestAccAWSSecurityGroup_Name_Generated
=== PAUSE TestAccAWSSecurityGroup_Name_Generated
=== RUN   TestAccAWSSecurityGroup_Name_TerraformPrefix
=== PAUSE TestAccAWSSecurityGroup_Name_TerraformPrefix
=== RUN   TestAccAWSSecurityGroup_NamePrefix
=== PAUSE TestAccAWSSecurityGroup_NamePrefix
=== RUN   TestAccAWSSecurityGroup_NamePrefix_TerraformPrefix
=== PAUSE TestAccAWSSecurityGroup_NamePrefix_TerraformPrefix
=== RUN   TestAccAWSSecurityGroup_self
=== PAUSE TestAccAWSSecurityGroup_self
=== RUN   TestAccAWSSecurityGroup_vpc
=== PAUSE TestAccAWSSecurityGroup_vpc
=== RUN   TestAccAWSSecurityGroup_vpcNegOneIngress
=== PAUSE TestAccAWSSecurityGroup_vpcNegOneIngress
=== RUN   TestAccAWSSecurityGroup_vpcProtoNumIngress
=== PAUSE TestAccAWSSecurityGroup_vpcProtoNumIngress
=== RUN   TestAccAWSSecurityGroup_multiIngress
=== PAUSE TestAccAWSSecurityGroup_multiIngress
=== RUN   TestAccAWSSecurityGroup_change
=== PAUSE TestAccAWSSecurityGroup_change
=== RUN   TestAccAWSSecurityGroup_ruleDescription
=== PAUSE TestAccAWSSecurityGroup_ruleDescription
=== RUN   TestAccAWSSecurityGroup_defaultEgressVPC
=== PAUSE TestAccAWSSecurityGroup_defaultEgressVPC
=== RUN   TestAccAWSSecurityGroup_defaultEgressClassic
=== PAUSE TestAccAWSSecurityGroup_defaultEgressClassic
=== RUN   TestAccAWSSecurityGroup_drift
=== PAUSE TestAccAWSSecurityGroup_drift
=== RUN   TestAccAWSSecurityGroup_driftComplex
=== PAUSE TestAccAWSSecurityGroup_driftComplex
=== RUN   TestAccAWSSecurityGroup_invalidCIDRBlock
=== PAUSE TestAccAWSSecurityGroup_invalidCIDRBlock
=== RUN   TestAccAWSSecurityGroup_tags
=== PAUSE TestAccAWSSecurityGroup_tags
=== RUN   TestAccAWSSecurityGroup_CIDRandGroups
=== PAUSE TestAccAWSSecurityGroup_CIDRandGroups
=== RUN   TestAccAWSSecurityGroup_ingressWithCidrAndSGsVPC
=== PAUSE TestAccAWSSecurityGroup_ingressWithCidrAndSGsVPC
=== RUN   TestAccAWSSecurityGroup_ingressWithCidrAndSGsClassic
=== PAUSE TestAccAWSSecurityGroup_ingressWithCidrAndSGsClassic
=== RUN   TestAccAWSSecurityGroup_egressWithPrefixList
=== PAUSE TestAccAWSSecurityGroup_egressWithPrefixList
=== RUN   TestAccAWSSecurityGroup_ingressWithPrefixList
=== PAUSE TestAccAWSSecurityGroup_ingressWithPrefixList
=== RUN   TestAccAWSSecurityGroup_ipv4andipv6Egress
=== PAUSE TestAccAWSSecurityGroup_ipv4andipv6Egress
=== RUN   TestAccAWSSecurityGroup_failWithDiffMismatch
=== PAUSE TestAccAWSSecurityGroup_failWithDiffMismatch
=== RUN   TestAccAWSSecurityGroup_ruleLimitExceededAppend
=== PAUSE TestAccAWSSecurityGroup_ruleLimitExceededAppend
=== RUN   TestAccAWSSecurityGroup_ruleLimitCidrBlockExceededAppend
=== PAUSE TestAccAWSSecurityGroup_ruleLimitCidrBlockExceededAppend
=== RUN   TestAccAWSSecurityGroup_ruleLimitExceededPrepend
=== PAUSE TestAccAWSSecurityGroup_ruleLimitExceededPrepend
=== RUN   TestAccAWSSecurityGroup_ruleLimitExceededAllNew
=== PAUSE TestAccAWSSecurityGroup_ruleLimitExceededAllNew
=== RUN   TestAccAWSSecurityGroup_rulesDropOnError
=== PAUSE TestAccAWSSecurityGroup_rulesDropOnError
=== CONT  TestAccAWSDefaultSecurityGroup_Vpc_basic
=== CONT  TestAccAWSSecurityGroupRule_Issue5310
=== CONT  TestAccAwsGlobalAcceleratorEndpointGroup_Update
=== CONT  TestAccAWSEMRCluster_tags
=== CONT  TestAccAWSSecurityGroupRule_PartialMatching_Source
=== CONT  TestAccAWSSecurityGroupRule_PartialMatching_basic
=== CONT  TestAccAWSSecurityGroupRule_ExpectInvalidCIDR
=== CONT  TestAccAWSSecurityGroupRule_ExpectInvalidTypeError
=== CONT  TestAccAWSSecurityGroupRule_SelfReference
=== CONT  TestAccAWSSecurityGroupRule_Egress
=== CONT  TestAccAWSSecurityGroupRule_MultiIngress
=== CONT  TestAccAWSSecurityGroupRule_Ingress_Classic
=== CONT  TestAccAWSSecurityGroupRule_Ingress_Ipv6
=== CONT  TestAccAWSSecurityGroupRule_Ingress_Protocol
=== CONT  TestAccAWSSecurityGroupRule_Ingress_Source_With_Account_Id
=== CONT  TestAccAWSSecurityGroupRule_Ingress_VPC
=== CONT  TestAccAWSEMRCluster_MasterInstanceGroup_BidPrice
=== CONT  TestAccAWSEMRCluster_s3Logging
=== CONT  TestAccAWSSecurityGroup_rulesDropOnError
=== CONT  TestAccAWSEMRCluster_visibleToAllUsers
--- PASS: TestAccAWSSecurityGroupRule_ExpectInvalidTypeError (4.69s)
=== CONT  TestAccAWSSecurityGroup_ruleLimitExceededAllNew
--- PASS: TestAccAWSSecurityGroupRule_ExpectInvalidCIDR (10.68s)
=== CONT  TestAccAWSSecurityGroup_ruleLimitExceededPrepend
--- PASS: TestAccAWSSecurityGroupRule_Issue5310 (25.54s)
=== CONT  TestAccAWSEMRCluster_keepJob
--- PASS: TestAccAWSSecurityGroupRule_Egress (26.48s)
=== CONT  TestAccAWSSecurityGroup_ruleLimitCidrBlockExceededAppend
--- PASS: TestAccAWSSecurityGroupRule_Ingress_VPC (32.16s)
=== CONT  TestAccAWSSecurityGroup_ruleLimitExceededAppend
--- PASS: TestAccAWSSecurityGroupRule_Ingress_Classic (33.19s)
=== CONT  TestAccAWSEMRCluster_terminationProtected
--- PASS: TestAccAWSSecurityGroupRule_MultiIngress (36.13s)
=== CONT  TestAccAWSSecurityGroup_failWithDiffMismatch
--- PASS: TestAccAWSSecurityGroupRule_SelfReference (39.86s)
=== CONT  TestAccAWSEMRCluster_bootstrap_ordering
--- PASS: TestAccAWSSecurityGroupRule_Ingress_Ipv6 (40.64s)
=== CONT  TestAccAWSEMRCluster_Step_Multiple
--- PASS: TestAccAWSSecurityGroupRule_Ingress_Source_With_Account_Id (46.75s)
=== CONT  TestAccAWSEMRCluster_Step_ConfigMode
--- PASS: TestAccAWSSecurityGroupRule_Ingress_Protocol (47.42s)
=== CONT  TestAccAWSSecurityGroup_ipv4andipv6Egress
--- PASS: TestAccAWSSecurityGroupRule_PartialMatching_Source (50.38s)
=== CONT  TestAccAWSEMRCluster_Step_Basic
=== CONT  TestAccAWSSecurityGroup_rulesDropOnError
--- PASS: TestAccAWSSecurityGroup_rulesDropOnError (53.93s)
--- PASS: TestAccAWSSecurityGroupRule_PartialMatching_basic (54.82s)
=== CONT  TestAccAWSEMRCluster_security_config
--- PASS: TestAccAWSDefaultSecurityGroup_Vpc_basic (55.75s)
=== CONT  TestAccAWSEMRCluster_MasterInstanceGroup_Name111111
=== CONT  TestAccAWSEMRCluster_MasterInstanceGroup_InstanceType
=== CONT  TestAccAWSSecurityGroup_ruleLimitExceededAllNew
=== CONT  TestAccAWSSecurityGroup_ruleLimitExceededPrepend
--- PASS: TestAccAWSSecurityGroup_ruleLimitExceededAllNew (58.18s)
=== CONT  TestAccAWSSecurityGroup_ingressWithPrefixList
--- PASS: TestAccAWSSecurityGroup_ruleLimitExceededPrepend (59.49s)
=== CONT  TestAccAWSEMRCluster_MasterInstanceGroup_InstanceCount
=== CONT  TestAccAWSSecurityGroup_ruleLimitCidrBlockExceededAppend
--- PASS: TestAccAWSSecurityGroup_failWithDiffMismatch (36.68s)
=== CONT  TestAccAWSSecurityGroup_egressWithPrefixList
--- PASS: TestAccAWSSecurityGroup_ipv4andipv6Egress (27.80s)
=== CONT  TestAccAWSSecurityGroup_ingressWithCidrAndSGsClassic
--- PASS: TestAccAWSSecurityGroup_ruleLimitCidrBlockExceededAppend (52.01s)
=== CONT  TestAccAWSEMRCluster_additionalInfo
=== CONT  TestAccAWSSecurityGroup_ruleLimitExceededAppend
--- PASS: TestAccAWSSecurityGroup_ruleLimitExceededAppend (55.35s)
=== CONT  TestAccAWSEMRCluster_configurationsJson
--- PASS: TestAccAWSSecurityGroup_ingressWithCidrAndSGsClassic (11.14s)
=== CONT  TestAccAWSEMRCluster_disappears
--- PASS: TestAccAWSSecurityGroup_ingressWithPrefixList (49.21s)
=== CONT  TestAccAWSEMRCluster_CoreInstanceGroup_Name
--- PASS: TestAccAWSSecurityGroup_egressWithPrefixList (51.08s)
=== CONT  TestAccAWSEMRCluster_Ec2Attributes_DefaultManagedSecurityGroups
--- PASS: TestAccAwsGlobalAcceleratorEndpointGroup_Update (344.87s)
=== CONT  TestAccAWSEMRCluster_Kerberos_ClusterDedicatedKdc
=== CONT  TestAccAWSEMRCluster_keepJob
--- PASS: TestAccAWSEMRCluster_Step_Basic (388.88s)
=== CONT  TestAccAWSSecurityGroup_ingressWithCidrAndSGsVPC
--- PASS: TestAccAWSSecurityGroup_ingressWithCidrAndSGsVPC (29.96s)
=== CONT  TestAccAWSDefaultSecurityGroup_Classic_basic
--- PASS: TestAccAWSDefaultSecurityGroup_Classic_basic (12.46s)
=== CONT  TestAccAWSEMRCluster_basic
--- PASS: TestAccAWSEMRCluster_disappears (416.67s)
=== CONT  TestAccAWSSecurityGroup_forceRevokeRulesTrue
--- PASS: TestAccAWSEMRCluster_terminationProtected (504.94s)
=== CONT  TestAccAWSSecurityGroup_ruleGathering
--- PASS: TestAccAWSEMRCluster_security_config (489.80s)
=== CONT  TestAccAWSDefaultSecurityGroup_Vpc_empty
--- PASS: TestAccAWSEMRCluster_keepJob (416.11s)
=== CONT  TestAccAWSSecurityGroup_ingressConfigMode
--- PASS: TestAccAWSEMRCluster_s3Logging (557.95s)
=== CONT  TestAccAWSSecurityGroup_egressConfigMode
--- PASS: TestAccAWSDefaultSecurityGroup_Vpc_empty (27.07s)
=== CONT  TestAccAWSEMRCluster_CoreInstanceGroup_InstanceCount
=== CONT  TestAccAWSSecurityGroup_egressConfigMode
--- PASS: TestAccAWSSecurityGroup_egressConfigMode (57.40s)
=== CONT  TestAccAWSSecurityGroup_basic
--- PASS: TestAccAWSSecurityGroup_ruleGathering (52.21s)
=== CONT  TestAccAWSEMRCluster_CoreInstanceGroup_InstanceType
--- PASS: TestAccAWSEMRCluster_additionalInfo (523.78s)
=== CONT  TestAccAWSSecurityGroupRule_EgressDescription_updates
--- PASS: TestAccAWSSecurityGroup_basic (34.44s)
=== CONT  TestAccAWSSecurityGroup_forceRevokeRulesFalse
--- PASS: TestAccAWSSecurityGroup_ingressConfigMode (69.87s)
=== CONT  TestAccAwsGlobalAcceleratorEndpointGroup_basic
--- PASS: TestAccAWSSecurityGroupRule_EgressDescription_updates (31.63s)
=== CONT  TestAccAWSSecurityGroup_CIDRandGroups
--- PASS: TestAccAWSSecurityGroup_CIDRandGroups (31.10s)
=== CONT  TestAccAWSSecurityGroup_tags
--- PASS: TestAccAWSEMRCluster_CoreInstanceGroup_Name (591.63s)
=== CONT  TestAccAwsGlobalAcceleratorEndpointGroup_TCPHealthCheckProtocol
--- PASS: TestAccAWSEMRCluster_configurationsJson (627.34s)
=== CONT  TestAccAWSSecurityGroup_invalidCIDRBlock
--- PASS: TestAccAWSEMRCluster_MasterInstanceGroup_InstanceType (654.72s)
=== CONT  TestAccAwsGlobalAcceleratorEndpointGroup_PortOverrides
--- PASS: TestAccAWSSecurityGroup_invalidCIDRBlock (2.27s)
=== CONT  TestAccAWSSecurityGroupRule_IngressDescription_updates
--- PASS: TestAccAWSEMRCluster_Kerberos_ClusterDedicatedKdc (377.59s)
=== CONT  TestAccAwsGlobalAcceleratorEndpointGroup_MultiRegion
--- PASS: TestAccAWSSecurityGroup_tags (60.73s)
=== CONT  TestAccAWSSecurityGroupRule_Description_AllPorts
--- PASS: TestAccAWSEMRCluster_MasterInstanceGroup_BidPrice (737.59s)
=== CONT  TestAccAwsGlobalAcceleratorEndpointGroup_InstanceEndpoint
--- PASS: TestAccAWSEMRCluster_basic (256.34s)
=== CONT  TestAccAWSSecurityGroup_IPRangesWithSameRules
--- PASS: TestAccAWSSecurityGroupRule_IngressDescription_updates (28.72s)
=== CONT  TestAccAWSSecurityGroup_driftComplex
--- PASS: TestAccAWSEMRCluster_visibleToAllUsers (745.66s)
=== CONT  TestAccAwsGlobalAcceleratorEndpointGroup_ALBEndpoint_ClientIP
--- PASS: TestAccAWSSecurityGroupRule_Description_AllPorts (28.91s)
=== CONT  TestAccAWSSecurityGroup_IPRangeAndSecurityGroupWithSameRules
--- PASS: TestAccAWSSecurityGroup_IPRangesWithSameRules (29.92s)
=== CONT  TestAccAWSSecurityGroupRule_EgressDescription
--- PASS: TestAccAWSSecurityGroup_driftComplex (30.39s)
=== CONT  TestAccAwsGlobalAcceleratorEndpointGroup_disappears
--- PASS: TestAccAWSSecurityGroup_IPRangeAndSecurityGroupWithSameRules (32.84s)
=== CONT  TestAccAWSSecurityGroupRule_IngressDescription
--- PASS: TestAccAWSSecurityGroupRule_EgressDescription (17.06s)
=== CONT  TestAccAWSEMRCluster_custom_ami_id
--- PASS: TestAccAwsGlobalAcceleratorEndpointGroup_basic (176.06s)
=== CONT  TestAccAWSSecurityGroupRule_PrefixListEgress
--- PASS: TestAccAWSSecurityGroupRule_IngressDescription (17.71s)
=== CONT  TestAccAWSSecurityGroup_drift
--- PASS: TestAccAWSSecurityGroup_drift (14.60s)
=== CONT  TestAccAWSSecurityGroupRule_SelfSource
--- PASS: TestAccAWSSecurityGroupRule_PrefixListEgress (40.18s)
=== CONT  TestAccAWSSecurityGroup_defaultEgressClassic
--- PASS: TestAccAWSSecurityGroupRule_SelfSource (27.03s)
=== CONT  TestAccAWSSecurityGroupRule_Race
--- PASS: TestAccAWSSecurityGroup_defaultEgressClassic (9.00s)
=== CONT  TestAccAWSSecurityGroup_defaultEgressVPC
--- PASS: TestAccAWSEMRCluster_Step_Multiple (834.66s)
=== CONT  TestAccAWSSecurityGroup_ruleDescription
--- PASS: TestAccAWSSecurityGroup_defaultEgressVPC (29.50s)
=== CONT  TestAccAWSSecurityGroup_change
--- PASS: TestAccAwsGlobalAcceleratorEndpointGroup_MultiRegion (169.27s)
=== CONT  TestAccAWSSecurityGroup_multiIngress
--- PASS: TestAccAWSEMRCluster_Ec2Attributes_DefaultManagedSecurityGroups (769.86s)
=== CONT  TestAccAWSSecurityGroup_vpcProtoNumIngress
--- PASS: TestAccAWSSecurityGroup_vpcProtoNumIngress (31.18s)
=== CONT  TestAccAWSSecurityGroup_sourceSecurityGroup
--- PASS: TestAccAWSSecurityGroup_multiIngress (37.77s)
=== CONT  TestAccAWSSecurityGroup_vpcNegOneIngress
--- PASS: TestAccAWSSecurityGroup_change (59.33s)
=== CONT  TestAccAWSSecurityGroup_allowAll
--- PASS: TestAccAWSSecurityGroup_sourceSecurityGroup (28.18s)
=== CONT  TestAccAWSSecurityGroup_vpc
--- PASS: TestAccAWSSecurityGroup_vpcNegOneIngress (29.79s)
=== CONT  TestAccAWSSecurityGroupRule_MultiDescription
--- PASS: TestAccAWSSecurityGroup_ruleDescription (85.22s)
=== CONT  TestAccAWSSecurityGroup_self
--- PASS: TestAccAWSSecurityGroup_allowAll (29.86s)
=== CONT  TestAccAWSSecurityGroupRule_MultipleRuleSearching_AllProtocolCrash
--- PASS: TestAccAwsGlobalAcceleratorEndpointGroup_TCPHealthCheckProtocol (270.83s)
=== CONT  TestAccAWSEMRCluster_InstanceFleet_master_only
--- PASS: TestAccAWSSecurityGroup_vpc (30.44s)
=== CONT  TestAccAWSSecurityGroup_Name_TerraformPrefix
--- PASS: TestAccAWSSecurityGroupRule_MultipleRuleSearching_AllProtocolCrash (18.55s)
=== CONT  TestAccAWSSecurityGroup_NamePrefix
--- PASS: TestAccAWSSecurityGroup_self (31.43s)
=== CONT  TestAccAWSSecurityGroup_NamePrefix_TerraformPrefix
--- PASS: TestAccAWSSecurityGroup_Name_TerraformPrefix (24.91s)
=== CONT  TestAccAWSSecurityGroup_Name_Generated
--- PASS: TestAccAwsGlobalAcceleratorEndpointGroup_disappears (236.81s)
=== CONT  TestAccAWSSecurityGroup_ipv6
--- PASS: TestAccAwsGlobalAcceleratorEndpointGroup_PortOverrides (298.99s)
=== CONT  TestAccAWSEMRCluster_CoreInstanceGroup_BidPrice
--- PASS: TestAccAWSSecurityGroup_NamePrefix (27.24s)
=== CONT  TestAccAWSEMRCluster_step_concurrency_level
--- PASS: TestAccAWSSecurityGroup_NamePrefix_TerraformPrefix (32.27s)
=== CONT  TestAccAWSEMRCluster_InstanceFleet_basic
--- PASS: TestAccAWSSecurityGroup_Name_Generated (29.48s)
=== CONT  TestAccAWSSecurityGroupRule_Description_AllPorts_NonZeroPorts
--- PASS: TestAccAWSSecurityGroupRule_MultiDescription (94.66s)
=== CONT  TestAccAWSEMRCluster_root_volume_size
--- PASS: TestAccAWSSecurityGroup_ipv6 (47.61s)
=== CONT  TestAccAWSEMRCluster_ebs_config
--- PASS: TestAccAWSEMRCluster_MasterInstanceGroup_Name (1012.56s)
=== CONT  TestAccAWSEMRCluster_CoreInstanceGroup_AutoscalingPolicy
--- PASS: TestAccAWSSecurityGroupRule_Description_AllPorts_NonZeroPorts (30.90s)
--- PASS: TestAccAWSEMRCluster_Step_ConfigMode (1038.69s)
--- PASS: TestAccAWSEMRCluster_bootstrap_ordering (1071.54s)
--- PASS: TestAccAWSSecurityGroupRule_Race (284.68s)
--- PASS: TestAccAWSEMRCluster_CoreInstanceGroup_InstanceCount (606.75s)
--- PASS: TestAccAWSEMRCluster_MasterInstanceGroup_InstanceCount (1143.95s)
--- PASS: TestAccAWSEMRCluster_tags (1289.95s)
--- PASS: TestAccAwsGlobalAcceleratorEndpointGroup_InstanceEndpoint (573.40s)
--- PASS: TestAccAWSEMRCluster_custom_ami_id (565.32s)
--- PASS: TestAccAwsGlobalAcceleratorEndpointGroup_ALBEndpoint_ClientIP (682.54s)
--- PASS: TestAccAWSSecurityGroup_forceRevokeRulesTrue (1021.84s)
--- PASS: TestAccAWSEMRCluster_ebs_config (495.25s)
--- PASS: TestAccAWSSecurityGroup_forceRevokeRulesFalse (968.46s)
--- PASS: TestAccAWSEMRCluster_CoreInstanceGroup_InstanceType (1013.19s)
--- PASS: TestAccAWSEMRCluster_InstanceFleet_master_only (702.07s)
--- PASS: TestAccAWSEMRCluster_CoreInstanceGroup_AutoscalingPolicy (646.69s)
--- PASS: TestAccAWSEMRCluster_root_volume_size (811.30s)
--- PASS: TestAccAWSEMRCluster_CoreInstanceGroup_BidPrice (1063.36s)
--- PASS: TestAccAWSEMRCluster_step_concurrency_level (1086.92s)
--- PASS: TestAccAWSEMRCluster_InstanceFleet_basic (1222.73s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	2250.230s
```
