### PR TITLE
provider: update SetTagsDiff when setting the computed tags_all attribute

### LINKED ISSUE #18366: Provider produced inconsistent final plan - tags_all errors without using default_tags block
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
`Terraform v0.13.3`
`hashicorp/aws 3.33`

`hashicorp/aws 3.32` is working without issues

### Affected Resource(s)

* aws_vpc

### Terraform Configuration Files

We are using [terraform-aws-vpc](github.com/terraform-aws-modules/terraform-aws-vpc?ref=v2.77.0) module in 2.77.0 version for our VPC resources

We are not using "default_tags" block in provider added in 3.33 release

### Expected Behavior

`terraform apply` should work without issues

### Actual Behavior

`terraform apply` produces these kind of errors:

```
Error: Provider produced inconsistent final plan
When expanding the plan for
module.main_vpc.module.vpc.aws_vpc.this[0] to
include new values learned so far during apply, provider
"registry.terraform.io/hashicorp/aws" produced an invalid new value for
.tags_all: new element "Name" has appeared.
This is a bug in the provider, which should be reported in the provider's own
issue tracker.

Error: Provider produced inconsistent final plan
When expanding the plan for
module.main_vpc.module.vpc.aws_vpc.this[0] to
include new values learned so far during apply, provider
"registry.terraform.io/hashicorp/aws" produced an invalid new value for
.tags_all: new element "created_at" has appeared.
This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```
...and more for other elements

### Steps to Reproduce

1. Prepare module using [terraform-aws-vpc](github.com/terraform-aws-modules/terraform-aws-vpc?ref=v2.77.0) module in 2.77.0 version for VPC
2. Set tags in it
2. Do not set "default_tags" block in the provider
2. Run `terraform apply`

### PR DESCRIPTION
**Pull request by anGie44**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #18366 

Output from acceptance testing before code change in `aws/tags.go`:

```
Error: Provider produced inconsistent final plan

        When expanding the plan for aws_subnet.test to include new values learned so
        far during apply, provider "registry.terraform.io/hashicorp/aws" produced an
        invalid new value for .tags_all: new element "key1" has appeared.

        This is a bug in the provider, which should be reported in the provider's own
        issue tracker.


        Error: Provider produced inconsistent final plan

        When expanding the plan for aws_subnet.test to include new values learned so
        far during apply, provider "registry.terraform.io/hashicorp/aws" produced an
        invalid new value for .tags_all: new element "key2" has appeared.

        This is a bug in the provider, which should be reported in the provider's own
        issue tracker.
```

Output from acceptance testing after code change in `aws/tags.go`:

```
--- PASS: TestAccAWSSubnet_updateTagsKnownAtApply (27.48s)
```

### CODE REVIEW

**Review by YakDriver — APPROVED** [review]
Looks good! 🎉 

Output from acceptance tests (`us-west-2`):
```
--- PASS: TestAccAWSSubnet_updateTagsKnownAtApply (52.64s)
```

Output from acceptance tests (`us-east-1`):
```
--- PASS: TestAccAWSSubnet_updateTagsKnownAtApply (26.35s)
```

Output from acceptance tests (GovCloud):
```
--- PASS: TestAccAWSSubnet_updateTagsKnownAtApply (58.31s)
```

File: aws/tags.go [hunk 1]
```diff
@@ -111,8 +111,18 @@ func SetTagsDiff(_ context.Context, diff *schema.ResourceDiff, meta interface{})
...
+	// we explicitly set the attribute diff when values are known,
+	// otherwise mark the attribute only as "Computed"
+	// Reference: https://github.com/hashicorp/terraform-provider-aws/issues/18366
+	if len(allTags) > 0 {
+		if err := diff.SetNew("tags_all", allTags.Map()); err != nil {
+			return fmt.Errorf("error setting new tags_all diff: %w", err)
+		}
+	} else {
+		if err := diff.SetNewComputed("tags_all"); err != nil {
+			return fmt.Errorf("error setting tags_all to computed: %w", err)
```
Comment (anGie44) [inline aws/tags.go:124]: updated the messaging here in-case we'd need to differentiate between the 2 errors
