### PR TITLE
provider: Add custom_ca_bundle

### LINKED ISSUE #23224: Unable to plan/apply with a custom CA bundle defined
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v1.1.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/integrations/github v4.20.0

### Affected Resource(s)

all

### Terraform Configuration Files

Any configs

### Debug Output

https://gist.github.com/repl-mike-roest/ec6247ad53b59c548a8b0875b69c90d0

### Expected Behavior

a plan/apply should work

### Actual Behavior

```
❯ terraform plan
╷
│ Error: error creating AWS SDK v1 session: Error creating AWS session: LoadCustomCABundleError: unable to load custom CA bundle, HTTPClient's transport unsupported type
│ caused by: unsupported transport, http.suppressBadHTTPRedirectTransport
│
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on provider.tf line 1, in provider "aws":
│    1: provider "aws" {
│
╵
❯ terraform apply
╷
│ Error: error creating AWS SDK v1 session: Error creating AWS session: LoadCustomCABundleError: unable to load custom CA bundle, HTTPClient's transport unsupported type
│ caused by: unsupported transport, http.suppressBadHTTPRedirectTransport
│
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on provider.tf line 1, in provider "aws":
│    1: provider "aws" {
│
╵
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

We run a zero trust networking config that requires custom CA bundles to allow for SSL inspection
### References
seems potentially related to  #23182 as with 4.0.0 I get the same error as in that issue.

using 3.74.2 my custom CA bundle works and I'm able to plan/apply

* #0000

### LINKED ISSUE #23229: provider: Add parameter `custom_ca_bundle`
Practitioners can set a custom CA bundle for the provider using either the environment variable `AWS_CA_BUNDLE` ~or the shared configuration file parameter `ca_bundle`~. This is not documented in provider documentation and cannot be set directly in the provider configuration block.

- [ ] Update documentation
- [ ] Add provider parameter

Requires hashicorp/aws-sdk-go-base#119

Relates #23224

Reading from the shared config file requires aws/aws-sdk-go-v2#1589

### PR DESCRIPTION
**Pull request by YakDriver**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #23229
Closes #23224 
Relates hashicorp/aws-sdk-go-base#119
Relates #23212
Relates #23282

Output from acceptance testing: 

```
% make testacc TESTS=TestAccProvider PKG_NAME=./internal/acctest
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ././internal/acctest/... -v -count 1 -parallel 20 -run='TestAccProvider'  -timeout 180m
--- PASS: TestAccProvider_Region_awsGovCloudUs (23.01s)
--- PASS: TestAccProvider_Region_stsRegion (23.13s)
--- PASS: TestAccProvider_Region_awsC2S (23.15s)
--- PASS: TestAccProvider_Region_awsSC2S (23.75s)
--- PASS: TestAccProvider_Region_awsChina (24.11s)
--- PASS: TestAccProvider_Region_awsCommercial (24.78s)
--- PASS: TestAccProvider_IgnoreTagsKeyPrefixes_multiple (28.30s)
--- PASS: TestAccProvider_IgnoreTags_emptyBlock (28.42s)
--- PASS: TestAccProvider_IgnoreTagsKeys_one (29.22s)
--- PASS: TestAccProvider_IgnoreTagsKeys_multiple (29.73s)
--- PASS: TestAccProvider_IgnoreTagsKeyPrefixes_none (30.31s)
--- PASS: TestAccProvider_DefaultTagsTags_one (30.31s)
--- PASS: TestAccProvider_DefaultTagsTags_multiple (30.31s)
--- PASS: TestAccProvider_DefaultTags_emptyBlock (30.31s)
--- PASS: TestAccProvider_IgnoreTagsKeys_none (30.33s)
--- PASS: TestAccProvider_unusualEndpoints (30.35s)
--- PASS: TestAccProvider_IgnoreTagsKeyPrefixes_one (31.28s)
--- PASS: TestAccProvider_endpoints (31.32s)
--- PASS: TestAccProvider_AssumeRole_empty (33.60s)
--- PASS: TestAccProvider_DefaultAndIgnoreTags_emptyBlocks (12.23s)
--- PASS: TestAccProvider_DefaultTagsTags_none (12.35s)
--- PASS: TestAccProvider_fipsEndpoint (39.33s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/acctest	41.489s
```

### CODE REVIEW

File: internal/provider/provider.go [hunk 1]
```diff
@@ -191,6 +191,12 @@ func Provider() *schema.Provider {
 				Set:           schema.HashString,
 			},
 			"assume_role": assumeRoleSchema(),
+			"custom_ca_bundle": {
+				Type:     schema.TypeString,
+				Optional: true,
+				Description: "File containing custom root and intermediate certificates. " +
+					"Can also be configured using the `AWS_CA_BUNDLE` environment variable.",
```
Comment (gdavison) [inline internal/provider/provider.go:198]: This setting also exists in the shared config file (`ca_bundle`), but reading it from the config file isn't currently supported by the AWS SDK (aws/aws-sdk-go-v2#1589). Maybe we should explicitly reference this, since we do support many settings from the file

Comment (YakDriver) [reply internal/provider/provider.go]: Done

**Review by gdavison — APPROVED** [review]
Looks good! 🚀
