### PR TITLE
r/aws_batch_job_definition: handle `INACTIVE` definitions in `List`

### LINKED ISSUE #45689: r/aws_batch_job_defintion: `_List_basic` acceptance test is broken
### Description

The test currently fails with the following on `main`:

```console
% make t K=batch T=TestAccBatchJobDefinition_List
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 main 🌿...
TF_ACC=1 go1.25.5 test ./internal/service/batch/... -v -count 1 -parallel 20 -run='TestAccBatchJobDefinition_List'  -timeout 360m -vet=off
2025/12/22 10:58:15 Creating Terraform AWS Provider (SDKv2-style)...
2025/12/22 10:58:15 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccBatchJobDefinition_List_basic
=== PAUSE TestAccBatchJobDefinition_List_basic
=== CONT  TestAccBatchJobDefinition_List_basic
    job_definition_list_test.go:29: Step 2/2 error running query checks: running terraform query command returned diagnostics: [{baseLogMessage:{Lvl:error Msg:Error: Error Listing Remote Resources Time:2025-12-22 10:58:26.493679 -0500 EST} Diagnostic:{Severity:error Summary:Error Listing Remote Resources Detail:An unexpected error occurred converting identity state. This is always an error in the provider. Please report the following to the provider developer:

        Error: state is nil, call SetId() on ResourceData first Range:0x140080199c0 Snippet:0x14003658b40}}]
--- FAIL: TestAccBatchJobDefinition_List_basic (13.65s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/batch      20.112s
```

### Important Facts and References

Discovered reviewing #45676

### Would you like to implement a relevant change?

No

### PR DESCRIPTION
**Pull request by jar-b**
## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the library.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

### Description

Adds handling to skip results which the `Read` operation will consider `NotFound`. Also moves list handling to it's own source file and adds more explicit checks for the identity returned by `List`.

### Relations

Closes #45689

### Output from Acceptance Testing

```console
% make t K=batch T=TestAccBatchJobDefinition_List
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 b-batch_job_definition-list 🌿...
TF_ACC=1 go1.25.5 test ./internal/service/batch/... -v -count 1 -parallel 20 -run='TestAccBatchJobDefinition_List'  -timeout 360m -vet=off
2025/12/22 14:23:05 Creating Terraform AWS Provider (SDKv2-style)...
2025/12/22 14:23:05 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccBatchJobDefinition_List_basic
=== PAUSE TestAccBatchJobDefinition_List_basic
=== CONT  TestAccBatchJobDefinition_List_basic
--- PASS: TestAccBatchJobDefinition_List_basic (30.60s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/batch      36.959s
```

### CODE REVIEW

File: internal/service/batch/job_definition_list.go [hunk 1]
```diff
@@ -0,0 +1,113 @@
...
+				diags := resourceJobDefinitionRead(ctx, rd, awsClient)
+				if diags.HasError() {
+					result = fwdiag.NewListResultErrorDiagnostic(fmt.Errorf("reading Batch job definition %s", arn))
+					yield(result)
+					return
+				}
+				if rd.Id() == "" {
+					// Resource is logically deleted
+					continue
+				}
```
Comment (jar-b) [inline internal/service/batch/job_definition_list.go:90]: The diff is obscured by moving the `List` bits to a separate file. This is the only addition.
