### PR TITLE
[bugfix] aws_elasticache_serverless_cache, cache usage

### LINKED ISSUE #41777: [Bug]: InvalidParameterCombination error when trying to remove cache_usage_limits in valkey
### Terraform Core Version

v1.5.7

### AWS Provider Version

5.86

### Affected Resource(s)

* aws_elasticache_serverless_cache

### Expected Behavior

When removing `cache_usage_limits` from the `aws_elasticache_serverless_cache` configuration, the generated plan (shown below) that correctly indicates the remove is applied without errors and the cache limits are removed.

Generated plan:
```
  # module.elasticache_valkey_production_location_store.aws_elasticache_serverless_cache.this[0] will be updated in-place
  ~ resource "aws_elasticache_serverless_cache" "this" {
        id                       = "iot-current-location"
        name                     = "iot-current-location"
        tags                     = {}
        # (16 unchanged attributes hidden)

      - cache_usage_limits {
          - data_storage {
              - maximum = 2 -> null
              - unit    = "GB" -> null
            }
          - ecpu_per_second {
              - maximum = 1000 -> null
            }
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Actual Behavior

When applying the plan we get `InvalidParameterCombination: No modifications were requested` error.

### Relevant Error/Panic Output Snippet

```shell
│ Error: updating ElastiCache Serverless Cache (iot-current-location)
│
│   with module.elasticache_valkey_production_location_store.aws_elasticache_serverless_cache.this[0],
│   on .terraform/modules/elasticache_valkey_production_location_store/modules/serverless-cache/main.tf line 1, in resource "aws_elasticache_serverless_cache" "this":
│    1: resource "aws_elasticache_serverless_cache" "this" {
│
│ operation error ElastiCache: ModifyServerlessCache, https response error StatusCode: 400, RequestID: ccb0b306-42b4-4840-8be2-f73ec62d4fca, InvalidParameterCombination: No modifications were requested
```

### Terraform Configuration Files

```terraform
terraform {
  required_version = ">= 1.5.0, < 1.6.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5"
    }
  }
}

provider "aws" {
  region = "us-west-2"
}

module "elasticache_valkey_production_location_store" {
  source = "terraform-aws-modules/elasticache/aws//modules/serverless-cache"

  engine = "valkey"
  // use lower case and dashes for cache name, this is an undocumented requirement
  cache_name = "*************"

  # ORIGINAL TERRAFORM WAS APPLIED WITH THIS CONFIG, THEN IT WAS REMOVED TO PRODUCE THE PLAN IN THE ISSUE
  cache_usage_limits = {
    data_storage = {
      maximum = 2
    }
    ecpu_per_second = {
      maximum = 1000
    }
  }

  daily_snapshot_time  = "22:00"
  description          = "*********"
  kms_key_id           =  **********
  major_engine_version = "7"
  security_group_ids = [******]

  snapshot_retention_limit = 7
  subnet_ids               =  **************

  user_group_id = ************
}
```

### Steps to Reproduce

1. Apply the above snippet
2. Remove `cache_usage_limits`
3. Plan and observe the plan indicate removals
4. Apply and observe InvalidParameterCombination error

### Debug Output

There is no debug log output after the apply.

### Panic Output

_No response_

### Important Factoids

_No response_

### References

https://registry.terraform.io/providers/-/aws/latest/docs/resources/elasticache_serverless_cache#cache_usage_limits-1

### Would you like to implement a fix?

None

### LINKED ISSUE #44746: [Bug]: InvalidParameterCombination error when removing cache_usage_limits in redis
### Terraform and AWS Provider Version

```console
Terraform v1.11.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v6.17.0
```

### Affected Resource(s) or Data Source(s)

`aws_elasticache_serverless_cache`

### Expected Behavior

successfully remove `cache_usage_limits` confugarion from an already existing Redis Serverless resource

### Actual Behavior

an attempt to apply the update returns `InvalidParameterCombination: No modifications were requested` error

### Relevant Error/Panic Output

```console
│ Error: updating ElastiCache Serverless Cache (some-redis-cache)
│ 
│   with aws_elasticache_serverless_cache.example,
│   on redis.tf line 1, in resource "aws_elasticache_serverless_cache" "example":
│    1: resource "aws_elasticache_serverless_cache" "example" {
│ 
│ operation error ElastiCache: ModifyServerlessCache, https response error StatusCode: 400, RequestID: add5a3e1-d40b-420f-89d5-b0860264e062,
│ InvalidParameterCombination: No modifications were requested
```

### Sample Terraform Configuration

<details open>
<summary>Click to expand configuration</summary>

```hcl
  # aws_elasticache_serverless_cache.example will be updated in-place
  ~ resource "aws_elasticache_serverless_cache" "example" {
      ~ full_engine_version      = "7.1" -> (known after apply)
        id                       = "some-redis-cache"
        name                     = "some-redis-cache"
        # (14 unchanged attributes hidden)

      - cache_usage_limits {
          - data_storage {
              - maximum = 10 -> null
              - unit    = "GB" -> null
            }
          - ecpu_per_second {
              - maximum = 50000 -> null
            }
        }
    }
```
</details>

### Steps to Reproduce

1. Create a simple `aws_elasticache_serverless_cache` resource with `cache_usage_limits` specified
2. Apply
3. Remove `cache_usage_limits` block
4. Apply again

### Debug Logging

<details open>
<summary>Click to expand log output</summary>

```console

```
</details>

### GenAI / LLM Assisted Development

n/a

### Important Facts and References

_No response_

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by sukumaar**
## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the library.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

### Description

Fixed, removal of `cache_usage_limits` from `aws_elasticache_serverless_cache` after it had previously been added to the resource. Previously it used to throw `InvalidParameterCombination` error.

Although the original issue is closed due to no response from issue author, the bug persists even in the Terraform AWS provider`6.28.0`. Hence, the fix is provided in this PR.

### Relations

Closes #41777
Closes #44746

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccElastiCacheServerlessCache PKG=elasticache ACCTEST_PARALLELISM=10 ACCTEST_TIMEOUT=3880m
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
xargs: gofmt: No such file or directory
make: Running acceptance tests on branch: 🌿 f-cache-usage-serverless-cache 🌿...
TF_ACC=1 go1.24.10 test ./internal/service/elasticache/... -v -count 1 -parallel 10 -run='TestAccElastiCacheServerlessCache'  -timeout 3880m -vet=off
2026/01/23 16:31:30 Creating Terraform AWS Provider (SDKv2-style)...
2026/01/23 16:31:30 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccElastiCacheServerlessCacheDataSource_Redis_basic
=== PAUSE TestAccElastiCacheServerlessCacheDataSource_Redis_basic
=== RUN   TestAccElastiCacheServerlessCacheDataSource_Valkey_basic
=== PAUSE TestAccElastiCacheServerlessCacheDataSource_Valkey_basic
=== RUN   TestAccElastiCacheServerlessCache_basicRedis
=== PAUSE TestAccElastiCacheServerlessCache_basicRedis
=== RUN   TestAccElastiCacheServerlessCache_basicValkey
=== PAUSE TestAccElastiCacheServerlessCache_basicValkey
=== RUN   TestAccElastiCacheServerlessCache_full
=== PAUSE TestAccElastiCacheServerlessCache_full
=== RUN   TestAccElastiCacheServerlessCache_fullRedis
=== PAUSE TestAccElastiCacheServerlessCache_fullRedis
=== RUN   TestAccElastiCacheServerlessCache_redisUpdateWithUserGroup
=== PAUSE TestAccElastiCacheServerlessCache_redisUpdateWithUserGroup
=== RUN   TestAccElastiCacheServerlessCache_fullValkey
=== PAUSE TestAccElastiCacheServerlessCache_fullValkey
=== RUN   TestAccElastiCacheServerlessCache_description
=== PAUSE TestAccElastiCacheServerlessCache_description
=== RUN   TestAccElastiCacheServerlessCache_cacheUsageLimits
=== PAUSE TestAccElastiCacheServerlessCache_cacheUsageLimits
=== RUN   TestAccElastiCacheServerlessCache_engine
=== PAUSE TestAccElastiCacheServerlessCache_engine
=== RUN   TestAccElastiCacheServerlessCache_disappears
=== PAUSE TestAccElastiCacheServerlessCache_disappears
=== RUN   TestAccElastiCacheServerlessCache_tags
=== PAUSE TestAccElastiCacheServerlessCache_tags
=== RUN   TestAccElastiCacheServerlessCache_cacheUsageLimitsRemovedValkey
=== PAUSE TestAccElastiCacheServerlessCache_cacheUsageLimitsRemovedValkey
=== RUN   TestAccElastiCacheServerlessCache_cacheUsageLimitsRemovedRedis
=== PAUSE TestAccElastiCacheServerlessCache_cacheUsageLimitsRemovedRedis
=== CONT  TestAccElastiCacheServerlessCacheDataSource_Redis_basic
=== CONT  TestAccElastiCacheServerlessCache_description
=== CONT  TestAccElastiCacheServerlessCache_tags
=== CONT  TestAccElastiCacheServerlessCache_cacheUsageLimitsRemovedRedis
=== CONT  TestAccElastiCacheServerlessCache_full
=== CONT  TestAccElastiCacheServerlessCache_engine
=== CONT  TestAccElastiCacheServerlessCache_disappears
=== CONT  TestAccElastiCacheServerlessCache_fullValkey
=== CONT  TestAccElastiCacheServerlessCache_fullRedis
=== CONT  TestAccElastiCacheServerlessCache_redisUpdateWithUserGroup
--- PASS: TestAccElastiCacheServerlessCache_fullValkey (375.96s)
=== CONT  TestAccElastiCacheServerlessCache_cacheUsageLimitsRemovedValkey
--- PASS: TestAccElastiCacheServerlessCacheDataSource_Redis_basic (396.13s)
=== CONT  TestAccElastiCacheServerlessCache_cacheUsageLimits
--- PASS: TestAccElastiCacheServerlessCache_fullRedis (416.23s)
=== CONT  TestAccElastiCacheServerlessCache_basicRedis
--- PASS: TestAccElastiCacheServerlessCache_description (418.39s)
=== CONT  TestAccElastiCacheServerlessCacheDataSource_Valkey_basic
--- PASS: TestAccElastiCacheServerlessCache_tags (422.72s)
=== CONT  TestAccElastiCacheServerlessCache_basicValkey
--- PASS: TestAccElastiCacheServerlessCache_full (436.12s)
--- PASS: TestAccElastiCacheServerlessCache_redisUpdateWithUserGroup (490.45s)
--- PASS: TestAccElastiCacheServerlessCache_disappears (516.70s)
--- PASS: TestAccElastiCacheServerlessCache_cacheUsageLimitsRemovedRedis (517.41s)
--- PASS: TestAccElastiCacheServerlessCache_basicValkey (297.24s)
--- PASS: TestAccElastiCacheServerlessCacheDataSource_Valkey_basic (304.34s)
--- PASS: TestAccElastiCacheServerlessCache_basicRedis (307.87s)
--- PASS: TestAccElastiCacheServerlessCache_cacheUsageLimitsRemovedValkey (519.26s)
--- PASS: TestAccElastiCacheServerlessCache_cacheUsageLimits (588.57s)
--- PASS: TestAccElastiCacheServerlessCache_engine (1282.61s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elasticache	1282.781s

...
```

### CODE REVIEW

File: internal/service/elasticache/serverless_cache_test.go [hunk 1]
```diff
@@ -32,9 +35,7 @@ func TestAccElastiCacheServerlessCache_basicRedis(t *testing.T) {
 		PreCheck:                 func() { acctest.PreCheck(ctx, t) },
 		ErrorCheck:               acctest.ErrorCheck(t, names.ElastiCacheServiceID),
 		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories,
-		CheckDestroy: resource.ComposeAggregateTestCheckFunc(
-			testAccCheckServerlessCacheDestroy(ctx, t),
-		),
+		CheckDestroy:             testAccCheckServerlessCacheDestroy(ctx, t),
```
Comment (gdavison) [inline internal/service/elasticache/serverless_cache_test.go:38]: 👍

File: internal/service/elasticache/serverless_cache_test.go [hunk 2]
```diff
@@ -457,106 +444,115 @@ func TestAccElastiCacheServerlessCache_cacheUsageLimits(t *testing.T) {
...
 		Steps: []resource.TestStep{
 			{
-				Config: testAccServerlessCacheConfig_cacheUsageLimits(rName, descriptionOld, 1, 1000),
```
Comment (gdavison) [inline internal/service/elasticache/serverless_cache_test.go:474]: 👍

File: internal/service/elasticache/serverless_cache_test.go [hunk 3]
```diff
@@ -457,106 +444,115 @@ func TestAccElastiCacheServerlessCache_cacheUsageLimits(t *testing.T) {
...
 					PreApply: []plancheck.PlanCheck{
 						plancheck.ExpectResourceAction(resourceName, plancheck.ResourceActionCreate),
 					},
 				},
 			},
 			{
-				ResourceName:      resourceName,
-				ImportState:       true,
-				ImportStateVerify: true,
-			},
```
Comment (gdavison) [inline internal/service/elasticache/serverless_cache_test.go:499]: Not a blocker, but this could be left in to validate that this configuration imports cleanly. There is overlap, however with a number of other tests that include `cache_usage_limits`, but not in this specific configuration.

File: internal/service/elasticache/serverless_cache_test.go
Comment (gdavison) [inline internal/service/elasticache/serverless_cache_test.go:440]: Not a blocker. Consider splitting this into multiple tests, one for each change, i.e.:

1. modify existing
2. remove
3. add on update

**Review by gdavison — DISMISSED** [review]
Looks good! 🚀 A couple non-blocking comments

--- PASS: TestAccElastiCacheServerlessCache_basicRedis (332.92s)
--- PASS: TestAccElastiCacheServerlessCache_fullValkey (340.88s)
--- PASS: TestAccElastiCacheServerlessCache_basicValkey (341.41s)
--- PASS: TestAccElastiCacheServerlessCache_tags (370.47s)
--- PASS: TestAccElastiCacheServerlessCache_disappears (378.96s)
--- PASS: TestAccElastiCacheServerlessCache_full (387.38s)
--- PASS: TestAccElastiCacheServerlessCache_description (424.76s)
--- PASS: TestAccElastiCacheServerlessCache_fullRedis (431.98s)
--- PASS: TestAccElastiCacheServerlessCache_redisUpdateWithUserGroup (472.86s)
--- PASS: TestAccElastiCacheServerlessCache_cacheUsageLimits (727.21s)
--- PASS: TestAccElastiCacheServerlessCache_valkeyMajorEngineVersion (1218.81s)
--- PASS: TestAccElastiCacheServerlessCache_updateWithUserGroupRemoval (1450.07s)
--- PASS: TestAccElastiCacheServerlessCache_engine (1552.68s)

File: internal/service/elasticache/serverless_cache_test.go (hunk 3 above)
Comment (jar-b) [reply internal/service/elasticache/serverless_cache_test.go:499]: After adding the `import` step back.

```console
% VCR_MODE=RECORD_ONLY VCR_PATH=/Users/jaredbaker/development/_vcr-testdata/  make t K=elasticache T=TestAccElastiCacheServerlessCache_cacheUsageLimits
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 f-cache-usage-serverless-cache 🌿...
TF_ACC=1 go1.25.8 test ./internal/service/elasticache/... -v -count 1 -parallel 20 -run='TestAccElastiCacheServerlessCache_cacheUsageLimits'  -timeout 360m -vet=off
2026/03/31 16:23:32 Creating Terraform AWS Provider (SDKv2-style)...
2026/03/31 16:23:32 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccElastiCacheServerlessCache_cacheUsageLimits
=== PAUSE TestAccElastiCacheServerlessCache_cacheUsageLimits
=== CONT  TestAccElastiCacheServerlessCache_cacheUsageLimits
--- PASS: TestAccElastiCacheServerlessCache_cacheUsageLimits (731.05s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/elasticache        738.132s
```

**Review by gdavison — APPROVED** [review]
Looks good! 🚀

**Comment by jar-b** [comment]
Thanks for your contribution, @sukumaar! 👍

**Comment by sukumaar** [comment]
Thank you so much @jar-b  @gdavison for review.
