### PR TITLE
Fix reading existing organizations accounts

### LINKED ISSUE #24897: aws_organizations_account (v4.15.0): Create Account Status does not validate
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

terraform v1.0.10
terraform-provider-aws v4.15.0 (latest release)

### Affected Resource(s)

* aws_organizations_account

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl

resource "aws_organizations_account" "account" {
  name                       = var.account_name
  email                      = local.account_tags.account_email
  iam_user_access_to_billing = "ALLOW"
  parent_id                  = local.parent_id
  role_name                  = var.organization_role
  tags                       = local.account_tags
  close_on_deletion          = true

  lifecycle {
    ignore_changes = [
      role_name,
      iam_user_access_to_billing
    ]
  }
}

```

### Panic Output

```
2022-05-20T07:43:02.902Z [DEBUG] provider.terraform-provider-aws_v4.15.0_x5: [aws-sdk-go] {"Parents":[{"Id":"X","Type":"ORGANIZATIONAL_UNIT"}]}: timestamp=2022-05-20T07:43:02.902Z
2022-05-20T07:43:02.902Z [DEBUG] provider.terraform-provider-aws_v4.15.0_x5: [aws-sdk-go] DEBUG: Request organizations/DescribeCreateAccountStatus Details:
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: organizations.us-east-1.amazonaws.com
User-Agent: APN/1.0 HashiCorp/1.0 Terraform/1.0.10 (+https://www.terraform.io) terraform-provider-aws/dev (+https://registry.terraform.io/providers/hashicorp/aws) aws-sdk-go/1.44.15 (go1.17.6; linux; amd64) TFE/v202204-2
Content-Length: 41
Authorization: AWS4-HMAC-SHA256 Credential=XXX/20220520/us-east-1/organizations/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date;x-amz-target, Signature=XXX
Content-Type: application/x-amz-json-1.1
X-Amz-Date: 20220520T074302Z
X-Amz-Target: AWSOrganizationsV20161128.DescribeCreateAccountStatus
Accept-Encoding: gzip

-----------------------------------------------------: timestamp=2022-05-20T07:43:02.902Z
2022-05-20T07:43:02.934Z [DEBUG] provider.terraform-provider-aws_v4.15.0_x5: [aws-sdk-go] DEBUG: Response organizations/DescribeCreateAccountStatus Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 400 Bad Request
Connection: close
Content-Length: 162
Content-Type: application/x-amz-json-1.1
Date: Fri, 20 May 2022 07:43:02 GMT
X-Amzn-Requestid: X

-----------------------------------------------------: timestamp=2022-05-20T07:43:02.934Z
2022-05-20T07:43:02.934Z [DEBUG] provider.terraform-provider-aws_v4.15.0_x5: [aws-sdk-go] {"__type":"InvalidInputException","Message":"You provided a value that does not match the required pattern.","Reason":"INVALID_PATTERN:CREATE_ACCOUNT_REQUEST_ID"}: timestamp=2022-05-20T07:43:02.934Z
2022-05-20T07:43:02.934Z [DEBUG] provider.terraform-provider-aws_v4.15.0_x5: [aws-sdk-go] DEBUG: Validate Response organizations/DescribeCreateAccountStatus failed, attempt 0/25, error InvalidInputException: You provided a value that does not match the required pattern.
{
RespMetadata: {
StatusCode: 400,
RequestID: "X"
},
Message_: "You provided a value that does not match the required pattern.",
Reason: "INVALID_PATTERN:CREATE_ACCOUNT_REQUEST_ID"
}: timestamp=2022-05-20T07:43:02.934Z
2022-05-20T07:43:02.936Z [DEBUG] provider.terraform-provider-aws_v4.15.0_x5: [aws-sdk-go] DEBUG: Response organizations/DescribeCreateAccountStatus Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 400 Bad Request
Connection: close
Content-Length: 162
Content-Type: application/x-amz-json-1.1
Date: Fri, 20 May 2022 07:43:02 GMT
X-Amzn-Requestid: X

```

### Expected Behavior

Terraform Plan works for the AWS Organization

### Actual Behavior

Terraform fails with the following error:
```
 Error: finding AWS Organizations Create Account Status (X): InvalidInputException: You provided a value that does not match the required pattern. { RespMetadata: { StatusCode: 400, RequestID: "XXX" }, Message_: "You provided a value that does not match the required pattern.", Reason: "INVALID_PATTERN:CREATE_ACCOUNT_REQUEST_ID" } 
```
### Steps to Reproduce

1. `terraform plan`

### Important Factoids

We have two AWS Organizations. One of them works fine with v4.15.0, the other works fine with v4.14.0 but crashes as described above.

### References

* #0000

### PR DESCRIPTION
**Pull request by linkvt**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #24897

During every account read (also of existing accounts) the create account status is read here
https://github.com/hashicorp/terraform-provider-aws/blob/5b2d3d9aa24ab96f83498f2f0aca44a7b77148c6/internal/service/organizations/account.go#L199
which calls the following SDK function
https://github.com/hashicorp/terraform-provider-aws/blob/5b2d3d9aa24ab96f83498f2f0aca44a7b77148c6/internal/service/organizations/account.go#L390

As per the [AWS docs](https://docs.aws.amazon.com/organizations/latest/APIReference/API_DescribeCreateAccountStatus.html#API_DescribeCreateAccountStatus_RequestSyntax), this `DescribeCreateAccountStatus` function can only be called with the ID of the account creation which looks like this `^car-[a-z0-9]{8,32}$`.
For existing accounts `d.Id()` is the account id (12 digit number) which causes this function to fail with the following error

```
-----------------------------------------------------: timestamp=2022-05-20T11:45:21.246+0200
2022-05-20T11:45:21.246+0200 [DEBUG] provider.terraform-provider-aws_v4.15.0_x5: [aws-sdk-go] {"__type":"InvalidInputException","Message":"You provided a value that does not match the required pattern.","Reason":"INVALID_PATTERN:CREATE_ACCOUNT_REQUEST_ID"}: timestamp=2022-05-20T11:45:21.246+0200
2022-05-20T11:45:21.246+0200 [DEBUG] provider.terraform-provider-aws_v4.15.0_x5: [aws-sdk-go] DEBUG: Validate Response organizations/DescribeCreateAccountStatus failed, attempt 0/25, error InvalidInputException: You provided a value that does not match the required pattern.
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "censored"
  },
  Message_: "You provided a value that does not match the required pattern.",
  Reason: "INVALID_PATTERN:CREATE_ACCOUNT_REQUEST_ID"
}: timestamp=2022-05-20T11:45:21.246+0200
2022-05-20T11:45:21.247+0200 [ERROR] vertex "censored" error: finding AWS Organizations Create Account Status (censored): InvalidInputException: You provided a value that does not match the required pattern.

```

**Sorry I did not understand how to do the testing after reading the docs** and also have no way of testing a govcloud account - Support is appreciated - or just go ahead and reuse this fix in a new PR.

### TODOs

- [x] Changelog
- [ ] Testing

### CODE REVIEW

**Comment by linkvt** [comment]
Hi @YakDriver could you as the last contributor for the govcloud change maybe take a look at the bug this cause, I guess you are already way more into the code than me, Thanks!

**Comment by ewbankkit** [comment]
It looks like this was caused by https://github.com/hashicorp/terraform-provider-aws/pull/24447.

**Comment by ewbankkit** [comment]
@linkvt Thanks for looking at this 👏 .
I don't think the original code was working in the new account creation case either as the ID passed here

```go
s, err := findCreateAccountStatusByID(conn, d.Id()) 
```

is the account ID, not the [`CreateAccountRequestId`](https://docs.aws.amazon.com/organizations/latest/APIReference/API_DescribeCreateAccountStatus.html#API_DescribeCreateAccountStatus_RequestSyntax).
We may need to do something with the [`ListCreateAccountStatus`](https://docs.aws.amazon.com/organizations/latest/APIReference/API_ListCreateAccountStatus.html) API to get that ID in resource Read.

**Comment by ewbankkit** [comment]
@linkvt Thanks for looking at this 👏 .
I don't think the original code was working in the new account creation case either as the ID passed here

```go
s, err := findCreateAccountStatusByID(conn, d.Id()) 
```

is the account ID, not the [`CreateAccountRequestId`](https://docs.aws.amazon.com/organizations/latest/APIReference/API_DescribeCreateAccountStatus.html#API_DescribeCreateAccountStatus_RequestSyntax).
We may need to do something with the [`ListCreateAccountStatus`](https://docs.aws.amazon.com/organizations/latest/APIReference/API_ListCreateAccountStatus.html) API to get that ID in resource Read.

**Comment by linkvt** [comment]
@ewbankkit thanks for the hint, I now understood a bit more of the code and think, that this would rather belong in the `resourceAccountCreate` function, which already contains some code that waits for the account to be created.

I now [read in the docs (~line 1769)](https://github.com/aws/aws-sdk-go/blob/main/service/organizations/api.go), that there are two accounts created for govcloud, one in govcloud and one in the commercial region for billing
```
// When you call the CreateGovCloudAccount action, you create two accounts:
// a standalone account in the Amazon Web Services GovCloud (US) Region and
// an associated account in the commercial Region for billing and support purposes.
// The account in the commercial Region is automatically a member of the organization
// whose credentials made the request. Both accounts are associated with the
// same email address.
```

I don't know how the AWS API behaves; does the `CreateAccountStatus` field contain both account ids or possibly also only one (e.g. if govcloud is created first and commercial takes a few seconds longer).

I have updated my PR to set the govcloud ID in the same location as the account ID was set, but unfortunately can't test it...  I guess this issue needs someone with access to GovCloud to test everything.

**Comment by YakDriver** [comment]
@linkvt Thank you for jumping right on this! I will help by taking a look at what you're working on. The priority now is to get this working for commercial accounts, regardless of the govcloud portion. In other words, we want this to not be a regression and then see if govcloud is behaving. I also cannot test on govcloud.

**Comment by ewbankkit** [comment]
@YakDriver I think I can test with a commercial account I have that is the main account of an organization (not able to test GovCloud though).

File: internal/service/organizations/account.go [hunk 1]
```diff
@@ -140,6 +139,7 @@ func resourceAccountCreate(d *schema.ResourceData, meta interface{}) error {
 	}
 
 	d.SetId(aws.StringValue(output.AccountId))
+	d.Set("govcloud_id", output.GovCloudAccountId)
```
Comment (ewbankkit) [inline internal/service/organizations/account.go:142]: Yes, this works well. The only limitation is that `govcloud_id` will not be available if a an existing account is imported. At the the moment I don't think that is a blocker.

Comment (linkvt) [reply internal/service/organizations/account.go:142]: Yes I can also confirm, creating an commercial account, refreshing the status and deleting it (in terraform with `close_on_deletion = true`, still waiting for the closing of the account on AWS side) works for me.

Comment (linkvt) [reply internal/service/organizations/account.go:142]: Should I maybe add a comment that this line is untested? As no one of us has a govcloud account?

**Comment by ewbankkit** [comment]
```console
% TEST_AWS_ORGANIZATION_ACCOUNT_EMAIL_DOMAIN=xxxxxxxx make testacc TESTS=TestAccOrganizations_serial/Account/GovCloud PKG=organizations
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/organizations/... -v -count 1 -parallel 20 -run='TestAccOrganizations_serial/Account/GovCloud'  -timeout 180m
=== RUN   TestAccOrganizations_serial
=== RUN   TestAccOrganizations_serial/Account
=== RUN   TestAccOrganizations_serial/Account/GovCloud
    acctest.go:1018: skipping test for aws/us-west-2: Error running apply: exit status 1
        
        Error: error creating AWS Organizations Account (tf_acctest_3683535191489411103): ConstraintViolationException: Only master accounts that are enabled for access to GovCloud can create accounts in GovCloud.
        {
          RespMetadata: {
            StatusCode: 400,
            RequestID: "dbeb1d92-5195-49b3-9d35-f94cd047bd04"
          },
          Message_: "Only master accounts that are enabled for access to GovCloud can create accounts in GovCloud.",
          Reason: "MASTER_ACCOUNT_NOT_GOVCLOUD_ENABLED"
        }
        
          with aws_organizations_account.test,
          on terraform_plugin_test.tf line 2, in resource "aws_organizations_account" "test":
           2: resource "aws_organizations_account" "test" {
        
--- PASS: TestAccOrganizations_serial (8.08s)
    --- PASS: TestAccOrganizations_serial/Account (8.08s)
        --- SKIP: TestAccOrganizations_serial/Account/GovCloud (8.08s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/organizations	11.968s
```

**Comment by ewbankkit** [comment]
```console
% make providerlint
==> Checking source code with providerlint...
```

File: internal/service/organizations/account.go (hunk 1 above)
Comment (YakDriver) [reply internal/service/organizations/account.go:142]: I think that is unnecessary since we'll have to take it out after we hear back. New features, especially niche ones, may not be 100%.

Comment (ewbankkit) [reply internal/service/organizations/account.go:142]: But we shouldn't break existing functionality 😺.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% TEST_AWS_ORGANIZATION_ACCOUNT_EMAIL_DOMAIN=xxxxxxxx make testacc TESTS=TestAccOrganizations_serial/Account/CloseOnDeletion PKG=organizations
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/organizations/... -v -count 1 -parallel 20 -run='TestAccOrganizations_serial/Account/CloseOnDeletion'  -timeout 180m
=== RUN   TestAccOrganizations_serial
=== RUN   TestAccOrganizations_serial/Account
=== RUN   TestAccOrganizations_serial/Account/CloseOnDeletion
    testing_new.go:87: Error running post-test destroy, there may be dangling resources: exit status 1
        
        Error: error deleting AWS Organizations Account (123456789012): ConstraintViolationException: You have exceeded close account quota for the past 30 days.
        {
          RespMetadata: {
            StatusCode: 400,
            RequestID: "c59e13ef-e478-4dbe-bb1e-9c2647ff293c"
          },
          Message_: "You have exceeded close account quota for the past 30 days.",
          Reason: "CLOSE_ACCOUNT_QUOTA_EXCEEDED"
        }
        
--- FAIL: TestAccOrganizations_serial (28.65s)
    --- FAIL: TestAccOrganizations_serial/Account (28.65s)
        --- FAIL: TestAccOrganizations_serial/Account/CloseOnDeletion (28.65s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/organizations	32.896s
FAIL
make: *** [testacc] Error 1
```

The failure is unrelated to this change - the account was successfully created and read.

**Review by YakDriver — CHANGES_REQUESTED** [review]

File: internal/service/organizations/account_test.go [hunk 2]
```diff
@@ -173,12 +172,7 @@ func testAccAccount_Tags(t *testing.T) {
 					resource.TestCheckResourceAttr(resourceName, "tags.key1", "value1"),
 				),
 			},
-			{
-				ResourceName:            resourceName,
-				ImportState:             true,
-				ImportStateVerify:       true,
-				ImportStateVerifyIgnore: []string{"close_on_deletion"},
-			},
+			testAccAccountImportStep(resourceName),
```
[the remark this answers is not in the document]
Comment (linkvt) [reply internal/service/organizations/account_test.go:175]: @YakDriver this change was actually done by @ewbankkit :grinning:

[the remark this answers is not in the document]
Comment (ewbankkit) [reply internal/service/organizations/account_test.go:175]: 😄 😢

**Comment by ewbankkit** [comment]
@linkvt Thanks for the contribution :tada: :clap:.

**Comment by ewbankkit** [comment]
We have started the release for this fix now. Should be available in a couple of hours.
