### PR TITLE
aws_storagegateway_smb_file_share: Set `kms_key_arn` when `kms_encrypted` is `true`

### LINKED ISSUE #20766: "KMSEncrypted is set to true, but KMSKey is missing." when updating aws_storagegateway_smb_file_share
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

3.47.0, 3.56.0

### Affected Resource(s)

* aws_storagegateway_smb_file_share

### Debug Output

```
aws_storagegateway_smb_file_share.smb: Modifying... [id=arn:aws:storagegateway:eu-central-1:721109342954:share/share-923A2BEE]
2021/09/02 14:26:23 [DEBUG] EvalApply: ProviderMeta config value set
2021/09/02 14:26:23 [DEBUG] aws_storagegateway_smb_file_share.smb: applying the planned Update change
2021-09-02T14:26:23.914+0200 [INFO]  plugin.terraform-provider-aws_v3.56.0_x5: 2021/09/02 14:26:23 [DEBUG] Updating Storage Gateway SMB File Share: {
  AccessBasedEnumeration: false,
  FileShareARN: "arn:aws:storagegateway:eu-central-1:721109342954:share/share-923A2BEE",
  GuessMIMETypeEnabled: true,
  KMSEncrypted: true,
  ReadOnly: true,
  RequesterPays: false,
  SMBACLEnabled: false
}: timestamp=2021-09-02T14:26:23.913+0200
2021-09-02T14:26:23.914+0200 [INFO]  plugin.terraform-provider-aws_v3.56.0_x5: 2021/09/02 14:26:23 [DEBUG] [aws-sdk-go] DEBUG: Request storagegateway/UpdateSMBFileShare Details:
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: storagegateway.eu-central-1.amazonaws.com
User-Agent: APN/1.0 HashiCorp/1.0 Terraform/0.14.11 (+https://www.terraform.io) terraform-provider-aws/3.56.0 (+https://registry.terraform.io/providers/hashicorp/aws) aws-sdk-go/1.40.29 (go1.16; linux; amd64)
Content-Length: 227
Authorization: AWS4-HMAC-SHA256 Credential={REDACTED}/20210902/eu-central-1/storagegateway/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date;x-amz-security-token;x-amz-target, Signature=c8f067ce750ab11370e342189382442116f0a54b029dbaaa91890bff038f0a75
Content-Type: application/x-amz-json-1.1
X-Amz-Date: 20210902T122623Z
X-Amz-Security-Token: {REDACTED}
X-Amz-Target: StorageGateway_20130630.UpdateSMBFileShare
Accept-Encoding: gzip

{"AccessBasedEnumeration":false,"FileShareARN":"arn:aws:storagegateway:eu-central-1:721109342954:share/share-923A2BEE","GuessMIMETypeEnabled":true,"KMSEncrypted":true,"ReadOnly":true,"RequesterPays":false,"SMBACLEnabled":false}
--------------------: timestamp=2021-09-02T14:26:23.913+0200
2021-09-02T14:26:24.080+0200 [INFO]  plugin.terraform-provider-aws_v3.56.0_x5: 2021/09/02 14:26:24 [DEBUG] [aws-sdk-go] DEBUG: Response storagegateway/UpdateSMBFileShare Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 400 Bad Request
Connection: close
Content-Length: 149
Content-Type: application/x-amz-json-1.1
Date: Thu, 02 Sep 2021 12:26:24 GMT
X-Amzn-Requestid: b127e10d-91bd-4835-8d66-cf75031597cf


-----------------------------------------------------: timestamp=2021-09-02T14:26:24.079+0200
2021-09-02T14:26:24.080+0200 [INFO]  plugin.terraform-provider-aws_v3.56.0_x5: 2021/09/02 14:26:24 [DEBUG] [aws-sdk-go] {"__type":"InvalidGatewayRequestException","error":{"errorCode":"InvalidParameters"},"message":"KMSEncrypted is set to true, but KMSKey is missing."}: timestamp=2021-09-02T14:26:24.079+0200
2021-09-02T14:26:24.080+0200 [INFO]  plugin.terraform-provider-aws_v3.56.0_x5: 2021/09/02 14:26:24 [DEBUG] [aws-sdk-go] DEBUG: Validate Response storagegateway/UpdateSMBFileShare failed, attempt 0/25, error InvalidGatewayRequestException: KMSEncrypted is set to true, but KMSKey is missing.
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "b127e10d-91bd-4835-8d66-cf75031597cf"
  },
  Error_: {
    ErrorCode: "InvalidParameters"
  },
  Message_: "KMSEncrypted is set to true, but KMSKey is missing."
}: timestamp=2021-09-02T14:26:24.079+0200
2021/09/02 14:26:24 [DEBUG] aws_storagegateway_smb_file_share.smb: apply errored, but we're indicating that via the Error pointer rather than returning it: error updating Storage Gateway SMB File Share (arn:aws:storagegateway:eu-central-1:721109342954:share/share-923A2BEE): InvalidGatewayRequestException: KMSEncrypted is set to true, but KMSKey is missing.
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "b127e10d-91bd-4835-8d66-cf75031597cf"
  },
  Error_: {
    ErrorCode: "InvalidParameters"
  },
  Message_: "KMSEncrypted is set to true, but KMSKey is missing."
}

Error: error updating Storage Gateway SMB File Share (arn:aws:storagegateway:eu-central-1:721109342954:share/share-923A2BEE): InvalidGatewayRequestException: KMSEncrypted is set to true, but KMSKey is missing.
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "b127e10d-91bd-4835-8d66-cf75031597cf"
  },
  Error_: {
    ErrorCode: "InvalidParameters"
  },
  Message_: "KMSEncrypted is set to true, but KMSKey is missing."
}

  on main.tf line 303, in resource "aws_storagegateway_smb_file_share" "smb":
 303: resource "aws_storagegateway_smb_file_share" "smb" {


2021-09-02T14:26:27.006+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-09-02T14:26:27.012+0200 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/aws/3.56.0/linux_amd64/terraform-provider-aws_v3.56.0_x5 pid=149241
2021-09-02T14:26:27.013+0200 [DEBUG] plugin: plugin exited
```

### Expected Behavior

The SMB share changes "File access settings > Export as" -> Read-write/Read-only.

### Actual Behavior

The SMB share is not changed.
Terraform shows

```
Error: error updating Storage Gateway SMB File Share (arn:aws:storagegateway:eu-central-1:721109342954:share/share-923A2BEE): InvalidGatewayRequestException: KMSEncrypted is set to true, but KMSKey is missing.
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "b127e10d-91bd-4835-8d66-cf75031597cf"
  },
  Error_: {
    ErrorCode: "InvalidParameters"
  },
  Message_: "KMSEncrypted is set to true, but KMSKey is missing."
}
```

### Steps to Reproduce

1. Create aws_storagegateway_smb_file_share (read_only = false) with `terraform apply`
```
resource "aws_storagegateway_smb_file_share" "smb" {
  file_share_name        = "share"
  default_storage_class  = "S3_STANDARD"
  gateway_arn            = var.gateway.arn
  location_arn           = var.s3_bucket.arn
  role_arn               = var.role.arn
  kms_key_arn            = var.kmskey.arn
  kms_encrypted          = true
  read_only              = false
}
```
2.  Change resource definition to read_only = true and `terraform apply`
```
resource "aws_storagegateway_smb_file_share" "smb" {
  file_share_name        = "share"
  default_storage_class  = "S3_STANDARD"
  gateway_arn            = var.gateway.arn
  location_arn           = var.s3_bucket.arn
  role_arn               = var.role.arn
  kms_key_arn            = var.kmskey.arn
  kms_encrypted          = true
  read_only              = true
}
```

### Important Factoids

The SMB Share can be changed using the AWS webconsole ("File access settings > Export as" ) without entering KMS Key ID.

### References

aws/resource_aws_storagegateway_smb_file_share.go (around lines 410-413)
```
		// This value can only be set when KMSEncrypted is true.
		if d.HasChange("kms_key_arn") && d.Get("kms_encrypted").(bool) {
			input.KMSKey = aws.String(d.Get("kms_key_arn").(string))
		}
```
As the debug output shows there is no reference to the KMS key in request body.
Could the unchanged *kms_key_arn* explain the missing property?

* #0000

### PR DESCRIPTION
**Pull request by johnsonaj**
### Description

Resolve error during an update when `kms_encrypted` is `true` but `kms_key_arn` is not sent in the request.

### Relations

Closes #20766

### Output from Acceptance Testing

```console
$ make testacc TESTARGS='-run=TestAccStorageGatewaySMBFileShare_' PKG=storagegateway

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/storagegateway/... -v -count 1 -parallel 20  -run=TestAccStorageGatewaySMBFileShare_ -timeout 180m
--- PASS: TestAccStorageGatewaySMBFileShare_Authentication_guestAccess (345.92s)
--- PASS: TestAccStorageGatewaySMBFileShare_guessMIMETypeEnabled (394.40s)
--- PASS: TestAccStorageGatewaySMBFileShare_disappears (395.55s)
--- PASS: TestAccStorageGatewaySMBFileShare_encryptedUpdate (410.67s)
--- PASS: TestAccStorageGatewaySMBFileShare_audit (411.60s)
--- PASS: TestAccStorageGatewaySMBFileShare_objectACL (424.00s)
--- PASS: TestAccStorageGatewaySMBFileShare_readOnly (434.67s)
--- PASS: TestAccStorageGatewaySMBFileShare_fileShareName (443.06s)
--- PASS: TestAccStorageGatewaySMBFileShare_defaultStorageClass (443.16s)
--- PASS: TestAccStorageGatewaySMBFileShare_accessBasedEnumeration (449.45s)
--- PASS: TestAccStorageGatewaySMBFileShare_kmsKeyARN (449.87s)
--- PASS: TestAccStorageGatewaySMBFileShare_requesterPays (453.36s)
--- PASS: TestAccStorageGatewaySMBFileShare_cacheAttributes (464.34s)
--- PASS: TestAccStorageGatewaySMBFileShare_caseSensitivity (483.75s)
--- PASS: TestAccStorageGatewaySMBFileShare_notificationPolicy (483.95s)
--- PASS: TestAccStorageGatewaySMBFileShare_kmsEncrypted (319.21s)
--- PASS: TestAccStorageGatewaySMBFileShare_tags (371.39s)
--- PASS: TestAccStorageGatewaySMBFileShare_Authentication_activeDirectory (1071.96s)
--- PASS: TestAccStorageGatewaySMBFileShare_SMB_acl (1137.82s)
--- PASS: TestAccStorageGatewaySMBFileShare_validUserList (1151.34s)
--- PASS: TestAccStorageGatewaySMBFileShare_adminUserList (1153.71s)
--- PASS: TestAccStorageGatewaySMBFileShare_invalidUserList (1397.42s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/storagegateway	1400.765s
```

### CODE REVIEW

File: internal/service/storagegateway/smb_file_share_test.go [hunk 1]
```diff
@@ -1117,6 +1149,26 @@ resource "aws_storagegateway_smb_file_share" "test" {
...
+
+resource "aws_storagegateway_smb_file_share" "test" {
+  # Use GuestAccess to simplify testing
+  authentication = "GuestAccess"
+  gateway_arn    = aws_storagegateway_gateway.test.arn
+  kms_encrypted  = true
+  kms_key_arn    = aws_kms_key.test.arn
+  location_arn   = aws_s3_bucket.test.arn
+  role_arn       = aws_iam_role.test.arn
+  read_only      = %t
```
Comment (YakDriver) [inline internal/service/storagegateway/smb_file_share_test.go:1167]:
```suggestion
  read_only      = %[1]t
```
In multi-line config, best to always use numbers.

File: internal/service/storagegateway/smb_file_share_test.go [hunk 2]
```diff
@@ -1117,6 +1149,26 @@ resource "aws_storagegateway_smb_file_share" "test" {
 `, defaultStorageClass))
 }
 
+func testAccSMBFileShareConfig_encryptedUpdate(rName string, readOnly bool) string {
+	return acctest.ConfigCompose(testAcc_SMBFileShare_GuestAccessBase(rName), fmt.Sprintf(`
+resource "aws_kms_key" "test" {
+ deletion_window_in_days = 7
```
Comment (YakDriver) [inline internal/service/storagegateway/smb_file_share_test.go:1155]:
```suggestion
  deletion_window_in_days = 7
```

**Review by YakDriver — APPROVED** [review]
Otherwise, LGTM 🎉
