### PR TITLE
Fix Terminated Workspace Panic

### LINKED ISSUE #16654: Crashing with: Error: rpc error: code = Unavailable desc = transport is closing
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v0.14.2 + provider registry.terraform.io/hashicorp/aws v3.20.0

### Affected Resource(s)

* aws_workspaces_directory
* aws_workspaces_workspace
* aws_directory_service_directory

### Terraform Configuration Files

```resource "aws_workspaces_directory" "anotherworkspace" {
  directory_id = aws_directory_service_directory.anotherworkspace.id
  subnet_ids   = ["subnet-xxxxxxxx", "subnet-yyyyyyyyyyyy"]
  #subnet_ids   = ["data.terraform_remote_state.network.public_subnets"]
  
  workspace_creation_properties {
    enable_internet_access = true
    enable_maintenance_mode = true
    #user_enabled_as_local_administrator = false
  }
}

data "aws_workspaces_bundle" "w10_terraform_test" {
  bundle_id = "wsb-5rw9k8l9c" # Value with Windows 10 (English)
}
```

### Debug Output

```
Error: rpc error: code = Unavailable desc = transport is closing

```

### Expected Behavior

Should at least run plan without error.

### Actual Behavior

Getting the error below:
`Error: rpc error: code = Unavailable desc = transport is closing
`

### Steps to Reproduce

1. `terraform plan`

### Important Factoids
It happens all the time.
I can't even get to ``terraform apply`` as it happens during ``terraform plan``

### References

* #0000

### PR DESCRIPTION
**Pull request by Tensho**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #16654

Relates to #15945

Follow up to #15705

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
aws_workspaces_workspace: Fix panic when describe workspaces action returns empty output 
```

## Acceptance Test

```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAwsWorkspacesWorkspace_recreate'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsWorkspacesWorkspace_recreate -timeout 120m
=== RUN   TestAccAwsWorkspacesWorkspace_recreate
=== PAUSE TestAccAwsWorkspacesWorkspace_recreate
=== CONT  TestAccAwsWorkspacesWorkspace_recreate
--- PASS: TestAccAwsWorkspacesWorkspace_recreate (1142.43s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	1145.364s
```

### Improvements

- Add tags to all acc test workspace resources

### CODE REVIEW

File: aws/internal/service/workspaces/waiter/status.go [hunk 1]
```diff
@@ -34,7 +34,7 @@ func WorkspaceState(conn *workspaces.WorkSpaces, workspaceID string) resource.St
 		}
 
 		if len(output.Workspaces) == 0 {
-			return nil, "", nil
+			return output, workspaces.WorkspaceStateTerminated, nil
```
Comment (Tensho) [inline aws/internal/service/workspaces/waiter/status.go:37]: We consider an empty list in output as a real workspace termination sign. The `workspaces.WorkspaceStateTerminated` state is checked right after the `DescriobeWorkspaces` call in `Read` func.

**Review by ewbankkit — APPROVED** [review]
LGTM.

File: aws/resource_aws_workspaces_workspace_test.go [hunk 2]
```diff
@@ -401,32 +401,44 @@ func testAccCheckAwsWorkspacesWorkspaceExists(n string, v *workspaces.Workspace)
...
   bundle_id    = data.aws_workspaces_bundle.test.id
   directory_id = aws_workspaces_directory.test.id
 
   # NOTE: WorkSpaces API doesn't allow creating users in the directory.
   # However, "Administrator"" user is always present in a bare directory.
   user_name = "Administrator"
+
+  tags = {
+    Name = "tf-testacc-workspaces-workspace-%[1]s"
+  }
```
Comment (bflad) [inline aws/resource_aws_workspaces_workspace_test.go:433]: The `TestAccAwsWorkspacesWorkspace_basic` acceptance test needs to be updated with this change as well:

```
=== CONT  TestAccAwsWorkspacesWorkspace_basic
TestAccAwsWorkspacesWorkspace_basic: resource_aws_workspaces_workspace_test.go:64: Step 1/2 error: Check failed: 1 error occurred:
  * Check 15/15 error: aws_workspaces_workspace.test: Attribute 'tags.%' expected "0", got "1"
--- FAIL: TestAccAwsWorkspacesWorkspace_basic (1667.19s)
```

**Review by bflad — CHANGES_REQUESTED** [review]

File: aws/resource_aws_workspaces_workspace_test.go (hunk 2 above)
Comment (Tensho) [reply aws/resource_aws_workspaces_workspace_test.go:434]: Sorry for that oversight, fixed 🙇

**Review by bflad — APPROVED** [review]
Looks great, thanks @Tensho 🚀 

Output from acceptance testing:

```
--- PASS: TestFlattenWorkspaceProperties (0.00s)
--- PASS: TestExpandWorkspaceProperties (0.00s)
--- PASS: TestAccAwsWorkspacesWorkspace_validateRootVolumeSize (3.40s)
--- PASS: TestAccAwsWorkspacesWorkspace_validateUserVolumeSize (3.96s)
--- PASS: TestAccAwsWorkspacesWorkspace_workspaceProperties_runningModeAlwaysOn (1775.72s)
--- PASS: TestAccAwsWorkspacesWorkspace_recreate (1836.44s)
--- PASS: TestAccAwsWorkspacesWorkspace_timeout (1848.37s)
--- PASS: TestAccAwsWorkspacesWorkspace_basic (1852.09s)
--- PASS: TestAccAwsWorkspacesWorkspace_tags (1876.63s)
--- PASS: TestAccAwsWorkspacesWorkspace_workspaceProperties (1899.23s)
```
