### PR TITLE
r/aws_rds_cluster: respect `storage_type` when restored from snapshot

### LINKED ISSUE #39935: [Bug]: `storage_type` incorrectly applied when creating Aurora cluster from snapshot
### Terraform Core Version

1.9.2

### AWS Provider Version

5.61.0

### Affected Resource(s)

aws_rds_cluster

### Expected Behavior

New Aurora cluster created matches the plan described by `terraform apply`. Either the cluster should be created with `storage_type = "aurora-iopt1"`, or if that's impossible when restoring from snapshot, then the plan should reflect as much.

### Actual Behavior

`terraform apply` outputs a plan which will create an Aurora cluster with IO Optimized storage:
```
# module.green.module.my_cluster[0].aws_rds_cluster.cluster will be created
+ resource "aws_rds_cluster" "cluster" {
  + allocated_storage                     = (known after apply)
  + allow_major_version_upgrade           = false
  + apply_immediately                     = true
  + arn                                   = (known after apply)
  + availability_zones                    = (known after apply)
  + backtrack_window                      = 0
  + backup_retention_period               = 7
  + ca_certificate_identifier             = (known after apply)
  + ca_certificate_valid_till             = (known after apply)
  + cluster_identifier                    = "redacted-my-cluster"
  + cluster_identifier_prefix             = (known after apply)
  + cluster_members                       = (known after apply)
  + cluster_resource_id                   = (known after apply)
  + copy_tags_to_snapshot                 = true
  + database_name                         = "redacted-my-db"
  + db_cluster_parameter_group_name       = (known after apply)
  + db_instance_parameter_group_name      = "default.aurora-postgresql16"
  + db_subnet_group_name                  = "redacted-my-cluster-group"
  + db_system_id                          = (known after apply)
  + delete_automated_backups              = true
  + deletion_protection                   = false
  + enable_global_write_forwarding        = false
  + enable_http_endpoint                  = false
  + enable_local_write_forwarding         = false
  + enabled_cloudwatch_logs_exports       = [
      + "postgresql",
    ]
  + endpoint                              = (known after apply)
  + engine                                = "aurora-postgresql"
  + engine_lifecycle_support              = (known after apply)
  + engine_mode                           = "provisioned"
  + engine_version                        = "16"
  + engine_version_actual                 = (known after apply)
  + final_snapshot_identifier             = "redacted-my-cluster-final-snapshot"
  + hosted_zone_id                        = (known after apply)
  + iam_database_authentication_enabled   = false
  + iam_roles                             = (known after apply)
  + id                                    = (known after apply)
  + kms_key_id                            = (known after apply)
  + master_password                       = (sensitive value)
  + master_user_secret                    = (known after apply)
  + master_user_secret_kms_key_id         = (known after apply)
  + master_username                       = "us_geo_user"
  + network_type                          = (known after apply)
  + performance_insights_kms_key_id       = (known after apply)
  + performance_insights_retention_period = (known after apply)
  + port                                  = 5432
  + preferred_backup_window               = "06:00-07:00"
  + preferred_maintenance_window          = "sun:07:00-sun:08:00"
  + reader_endpoint                       = (known after apply)
  + skip_final_snapshot                   = true
  + snapshot_identifier                   = "redacted-my-cluster-2024-10-28-06-04"
  + storage_encrypted                     = false
  + storage_type                          = "aurora-iopt1"
  + tags_all                              = {}
  + vpc_security_group_ids                = (known after apply)
}
```
Instead, after applying the plan, the cluster is created with Standard storage:
Screenshot 2024-10-29 at 3 04 36 PM

In terraform state, the relevant resource shows `storage_type = null`. When running `terraform apply` a second time, the storage type is noted as an addition, not a change:
```
# module.main.aws_rds_cluster.cluster will be updated in-place
~ resource "aws_rds_cluster" "cluster" {
    id                                    = "my-cluster"
  + storage_type                          = "aurora-iopt1"
```

### Relevant Error/Panic Output Snippet

_No response_

### Terraform Configuration Files

```
data "aws_db_cluster_snapshot" "example" {
  db_cluster_identifier = "example-original-cluster"
  most_recent           = true
}

resource "aws_rds_cluster" "example" {
  # Because the global cluster is sourced from this cluster, the initial
  # engine and engine_version values are defined here and automatically
  # inherited by the global cluster.
  engine         = "aurora-postgresql"
  engine_version = "16"

  cluster_identifier  = "example"
  snapshot_identifier = data.aws_db_cluster_snapshot.example.id
  storage_type = "aurora-iopt1"
}
```

### Steps to Reproduce

Attempt to create a new aurora cluster from a cluster snapshot, setting `storage_type = "aurora-iopt1"`. 

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

Aurora snapshots always have a storage type of "Aurora Standard", even if the source cluster has storage type of "I/O Optimized"

### References

_No response_

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by jar-b**
### Description

Previously if `storage_type` was configured on an RDS cluster restored from snapshot, the resulting cluster would always have the default value of `aurora` regardless of what was configured. This change properly sets the `storage_type` value, if configured.

Running a test to replicate this scenario against `main`:

```console
% make testacc PKG=rds TESTS=TestAccRDSCluster_SnapshotIdentifier_storageType
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.3 test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccRDSCluster_SnapshotIdentifier_storageType'  -timeout 360m
2024/12/05 14:30:09 Initializing Terraform AWS Provider...

    cluster_test.go:2520: Step 1/1 error: Check failed: Check 4/4 error: aws_rds_cluster.test: Attribute 'storage_type' expected "aurora-iopt1", got ""
--- FAIL: TestAccRDSCluster_SnapshotIdentifier_storageType (268.82s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/rds        274.075s
FAIL
make: *** [testacc] Error 1
```

And against this branch:

```console
% make testacc PKG=rds TESTS=TestAccRDSCluster_SnapshotIdentifier_storageType
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.3 test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccRDSCluster_SnapshotIdentifier_storageType'  -timeout 360m
2024/12/05 11:32:27 Initializing Terraform AWS Provider...

--- PASS: TestAccRDSCluster_SnapshotIdentifier_storageType (283.84s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/rds        289.116s
```

### Relations

Closes #39935

### Output from Acceptance Testing

```console
% make testacc PKG=rds TESTS=TestAccRDSCluster_
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.3 test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccRDSCluster_'  -timeout 360m
2024/12/05 14:46:44 Initializing Terraform AWS Provider...

--- PASS: TestAccRDSCluster_iamAuth (125.49s)
=== CONT  TestAccRDSCluster_GlobalClusterIdentifierEngineMode_provisioned
--- PASS: TestAccRDSCluster_localWriteForwarding (128.52s)
=== CONT  TestAccRDSCluster_GlobalClusterIdentifierEngineModeGlobal_update
--- PASS: TestAccRDSCluster_basic (128.52s)
=== CONT  TestAccRDSCluster_GlobalClusterIdentifierEngineModeGlobal_remove
--- PASS: TestAccRDSCluster_engineLifecycleSupport_disabled (144.48s)
=== CONT  TestAccRDSCluster_scaling
--- PASS: TestAccRDSCluster_GlobalClusterIdentifierEngineModeGlobal_add (147.72s)
=== CONT  TestAccRDSCluster_SnapshotIdentifier_deletionProtection
--- PASS: TestAccRDSCluster_password (165.59s)
=== CONT  TestAccRDSCluster_snapshotIdentifier
--- PASS: TestAccRDSCluster_EnabledCloudWatchLogsExports_mySQL (194.05s)
=== CONT  TestAccRDSCluster_Scaling_defaultMinCapacity
--- PASS: TestAccRDSCluster_enableHTTPEndpointProvisioned (195.43s)
=== CONT  TestAccRDSCluster_serverlessV2ScalingConfiguration
--- PASS: TestAccRDSCluster_copyTagsToSnapshot (204.78s)
=== CONT  TestAccRDSCluster_kmsKey
--- PASS: TestAccRDSCluster_SnapshotIdentifierEngineMode_provisioned (291.40s)
=== CONT  TestAccRDSCluster_encrypted
--- PASS: TestAccRDSCluster_SnapshotIdentifier_encryptedRestore (291.79s)
=== CONT  TestAccRDSCluster_networkType
--- PASS: TestAccRDSCluster_kmsKey (109.48s)
=== CONT  TestAccRDSCluster_ManagedMasterPassword_managedSpecificKMSKey
--- PASS: TestAccRDSCluster_GlobalClusterIdentifierEngineModeGlobal_remove (207.10s)
=== CONT  TestAccRDSCluster_port
--- PASS: TestAccRDSCluster_GlobalClusterIdentifierEngineMode_provisioned (214.07s)
=== CONT  TestAccRDSCluster_ManagedMasterPassword_convertToManaged
--- PASS: TestAccRDSCluster_GlobalClusterIdentifierEngineModeGlobal_update (213.26s)
=== CONT  TestAccRDSCluster_ReplicationSourceIdentifier_promote
--- PASS: TestAccRDSCluster_enableHTTPEndpoint (373.23s)
=== CONT  TestAccRDSCluster_copyTagsToSnapshot_restorePointInTime
--- PASS: TestAccRDSCluster_encrypted (112.92s)
=== CONT  TestAccRDSCluster_minorVersion
--- PASS: TestAccRDSCluster_serverlessV2ScalingConfiguration (218.04s)
=== CONT  TestAccRDSCluster_storageTypeAuroraIopt1UpdateAurora
--- PASS: TestAccRDSCluster_ManagedMasterPassword_managedSpecificKMSKey (113.34s)
=== CONT  TestAccRDSCluster_allocatedStorage
--- PASS: TestAccRDSCluster_snapshotIdentifier (263.15s)
=== CONT  TestAccRDSCluster_storageTypeAuroraUpdateAuroraIopt1
--- PASS: TestAccRDSCluster_NoDeleteAutomatedBackups (433.28s)
=== CONT  TestAccRDSCluster_storageTypeAuroraIopt1
--- PASS: TestAccRDSCluster_Scaling_defaultMinCapacity (266.52s)
=== CONT  TestAccRDSCluster_storageTypeAuroraReturnsBlank
--- PASS: TestAccRDSCluster_SnapshotIdentifier_deletionProtection (313.04s)
=== CONT  TestAccRDSCluster_storageTypeGeneralPurposeToProvisionedIOPS
--- PASS: TestAccRDSCluster_scaling (326.24s)
=== CONT  TestAccRDSCluster_storageTypeIo2
--- PASS: TestAccRDSCluster_port (141.55s)
=== CONT  TestAccRDSCluster_storageTypeIo1
--- PASS: TestAccRDSCluster_ManagedMasterPassword_convertToManaged (145.07s)
=== CONT  TestAccRDSCluster_availabilityZones_caCertificateIdentifier
--- PASS: TestAccRDSCluster_networkType (200.23s)
=== CONT  TestAccRDSCluster_availabilityZones
--- PASS: TestAccRDSCluster_storageTypeAuroraIopt1 (103.88s)
=== CONT  TestAccRDSCluster_allowMajorVersionUpgrade
--- PASS: TestAccRDSCluster_storageTypeAuroraIopt1UpdateAurora (152.83s)
=== CONT  TestAccRDSCluster_onlyMajorVersion
--- PASS: TestAccRDSCluster_storageTypeAuroraReturnsBlank (113.50s)
=== CONT  TestAccRDSCluster_allowMajorVersionUpgradeWithCustomParameters
--- PASS: TestAccRDSCluster_storageTypeAuroraUpdateAuroraIopt1 (154.19s)
=== CONT  TestAccRDSCluster_allowMajorVersionUpgradeWithCustomParametersApplyImm
--- PASS: TestAccRDSCluster_availabilityZones (104.08s)
=== CONT  TestAccRDSCluster_allowMajorVersionUpgradeNoApplyImmediately
--- PASS: TestAccRDSCluster_copyTagsToSnapshot_restorePointInTime (336.72s)
=== CONT  TestAccRDSCluster_identifierPrefix
--- PASS: TestAccRDSCluster_identifierPrefix (116.70s)
=== CONT  TestAccRDSCluster_securityGroupUpdate
--- PASS: TestAccRDSCluster_securityGroupUpdate (202.58s)
=== CONT  TestAccRDSCluster_tags
--- PASS: TestAccRDSCluster_tags (132.66s)
=== CONT  TestAccRDSCluster_identifierGenerated
--- PASS: TestAccRDSCluster_minorVersion (765.39s)
=== CONT  TestAccRDSCluster_updateIAMRoles
--- PASS: TestAccRDSCluster_identifierGenerated (115.61s)
=== CONT  TestAccRDSCluster_ManagedMasterPassword_managed
--- PASS: TestAccRDSCluster_updateIAMRoles (121.63s)
=== CONT  TestAccRDSCluster_backupsUpdate
--- PASS: TestAccRDSCluster_ManagedMasterPassword_managed (116.13s)
=== CONT  TestAccRDSCluster_GlobalClusterIdentifier_secondaryClustersWriteForwarding
--- PASS: TestAccRDSCluster_storageTypeGeneralPurposeToProvisionedIOPS (960.96s)
=== CONT  TestAccRDSCluster_engineVersion
--- PASS: TestAccRDSCluster_backupsUpdate (141.59s)
=== CONT  TestAccRDSCluster_GlobalClusterIdentifierEngineMode_global
--- PASS: TestAccRDSCluster_onlyMajorVersion (868.23s)
=== CONT  TestAccRDSCluster_engineVersionWithPrimaryInstance
--- PASS: TestAccRDSCluster_allowMajorVersionUpgradeNoApplyImmediately (912.21s)
=== CONT  TestAccRDSCluster_SnapshotIdentifierVPCSecurityGroupIDs_tags
--- PASS: TestAccRDSCluster_iops (1550.30s)
=== CONT  TestAccRDSCluster_EnabledCloudWatchLogsExports_postgresql
--- PASS: TestAccRDSCluster_performanceInsightsEnabled (1565.50s)
=== CONT  TestAccRDSCluster_SnapshotIdentifier_vpcSecurityGroupIDs
--- PASS: TestAccRDSCluster_GlobalClusterIdentifierEngineMode_global (197.59s)
=== CONT  TestAccRDSCluster_disappears
--- PASS: TestAccRDSCluster_performanceInsightsKMSKeyID (1631.24s)
=== CONT  TestAccRDSCluster_SnapshotIdentifier_tags
--- PASS: TestAccRDSCluster_performanceInsightsRetentionPeriod (1639.68s)
=== CONT  TestAccRDSCluster_engineMode
--- PASS: TestAccRDSCluster_disappears (113.38s)
=== CONT  TestAccRDSCluster_PointInTimeRestore_enabledCloudWatchLogsExports
--- PASS: TestAccRDSCluster_SnapshotIdentifierVPCSecurityGroupIDs_tags (255.94s)
=== CONT  TestAccRDSCluster_domain
--- PASS: TestAccRDSCluster_engineVersion (412.32s)
=== CONT  TestAccRDSCluster_missingUserNameCausesError
--- PASS: TestAccRDSCluster_missingUserNameCausesError (4.73s)
=== CONT  TestAccRDSCluster_GlobalClusterIdentifierTakeFinalSnapshot
--- PASS: TestAccRDSCluster_SnapshotIdentifier_vpcSecurityGroupIDs (274.54s)
=== CONT  TestAccRDSCluster_takeFinalSnapshot
--- PASS: TestAccRDSCluster_allocatedStorage (1483.04s)
=== CONT  TestAccRDSCluster_dbSubnetGroupName
--- PASS: TestAccRDSCluster_ReplicationSourceIdentifier_kmsKeyID (1931.23s)
=== CONT  TestAccRDSCluster_pointInTimeRestoreViaResourceID
--- PASS: TestAccRDSCluster_SnapshotIdentifier_tags (383.21s)
=== CONT  TestAccRDSCluster_pointInTimeRestore
--- PASS: TestAccRDSCluster_engineMode (376.06s)
=== CONT  TestAccRDSCluster_deletionProtection
=== CONT  TestAccRDSCluster_SnapshotIdentifier_masterPassword
--- PASS: TestAccRDSCluster_PointInTimeRestore_enabledCloudWatchLogsExports (274.65s)
--- PASS: TestAccRDSCluster_dbSubnetGroupName (110.79s)
=== CONT  TestAccRDSCluster_SnapshotIdentifier_preferredMaintenanceWindow
--- PASS: TestAccRDSCluster_takeFinalSnapshot (204.55s)
=== CONT  TestAccRDSCluster_SnapshotIdentifier_preferredBackupWindow
=== CONT  TestAccRDSCluster_SnapshotIdentifier_masterUsername
--- PASS: TestAccRDSCluster_storageTypeIo1 (1574.33s)
--- PASS: TestAccRDSCluster_storageTypeIo2 (1595.67s)
=== CONT  TestAccRDSCluster_backtrackWindow
--- PASS: TestAccRDSCluster_deletionProtection (141.89s)
=== CONT  TestAccRDSCluster_dbClusterInstanceClass
--- PASS: TestAccRDSCluster_GlobalClusterIdentifierTakeFinalSnapshot (348.52s)
=== CONT  TestAccRDSCluster_SnapshotIdentifierEngineVersion_equal
--- PASS: TestAccRDSCluster_pointInTimeRestoreViaResourceID (265.40s)
=== CONT  TestAccRDSCluster_SnapshotIdentifier_kmsKeyID
--- PASS: TestAccRDSCluster_availabilityZones_caCertificateIdentifier (1727.59s)
=== CONT  TestAccRDSCluster_SnapshotIdentifierEngineVersion_different
--- PASS: TestAccRDSCluster_backtrackWindow (151.81s)
=== CONT  TestAccRDSCluster_SnapshotIdentifier_storageType
--- PASS: TestAccRDSCluster_pointInTimeRestore (274.77s)
--- PASS: TestAccRDSCluster_allowMajorVersionUpgrade (1767.38s)
--- PASS: TestAccRDSCluster_SnapshotIdentifier_masterUsername (283.81s)
--- PASS: TestAccRDSCluster_SnapshotIdentifier_masterPassword (353.02s)
--- PASS: TestAccRDSCluster_SnapshotIdentifier_preferredMaintenanceWindow (384.14s)
--- PASS: TestAccRDSCluster_SnapshotIdentifier_preferredBackupWindow (373.99s)
--- PASS: TestAccRDSCluster_SnapshotIdentifierEngineVersion_equal (279.34s)
--- PASS: TestAccRDSCluster_ReplicationSourceIdentifier_promote (2128.84s)
--- PASS: TestAccRDSCluster_SnapshotIdentifier_storageType (272.47s)
--- PASS: TestAccRDSCluster_SnapshotIdentifierEngineVersion_different (298.89s)
--- PASS: TestAccRDSCluster_SnapshotIdentifier_kmsKeyID (343.58s)
--- PASS: TestAccRDSCluster_engineVersionWithPrimaryInstance (1251.83s)
--- PASS: TestAccRDSCluster_allowMajorVersionUpgradeWithCustomParametersApplyImm (2140.55s)
--- PASS: TestAccRDSCluster_allowMajorVersionUpgradeWithCustomParameters (2186.17s)
--- PASS: TestAccRDSCluster_GlobalClusterIdentifier_replicationSourceIdentifier (2903.17s)
--- PASS: TestAccRDSCluster_GlobalClusterIdentifier_primarySecondaryClusters (3058.85s)
--- PASS: TestAccRDSCluster_domain (1663.93s)
--- PASS: TestAccRDSCluster_EnabledCloudWatchLogsExports_postgresql (2209.36s)
--- PASS: TestAccRDSCluster_GlobalClusterIdentifier_secondaryClustersWriteForwarding (3021.23s)
--- PASS: TestAccRDSCluster_dbClusterInstanceClass (3743.24s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/rds        5906.389s
```

### CODE REVIEW

File: internal/service/rds/cluster.go [hunk 1]
```diff
@@ -761,6 +761,10 @@ func resourceClusterCreate(ctx context.Context, d *schema.ResourceData, meta int
 			requiresModifyDbCluster = true
 		}
 
+		if v, ok := d.GetOkExists(names.AttrStorageType); ok {
+			input.StorageType = aws.String(v.(string))
+		}
```
Comment (ewbankkit) [inline internal/service/rds/cluster.go:766]: Why not

```suggestion
		if v, ok := d.GetOk(names.AttrStorageType); ok {
			input.StorageType = aws.String(v.(string))
		}
```

?

Comment (jar-b) [reply internal/service/rds/cluster.go:766]: I copied this from the logic in the final `else` block of the create method (a cluster not restored from anything). I believe `GetOk` is fine in this context though - I'll swap it out everywhere.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccRDSCluster_SnapshotIdentifier_storageType\|TestAccRDSCluster_basic\|TestAccRDSCluster_SnapshotIdentifier_storageType\|TestAccRDSCluster_snapshotIdentifier' PKG=rds
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.3 test ./internal/service/rds/... -v -count 1 -parallel 20  -run=TestAccRDSCluster_SnapshotIdentifier_storageType\|TestAccRDSCluster_basic\|TestAccRDSCluster_SnapshotIdentifier_storageType\|TestAccRDSCluster_snapshotIdentifier -timeout 360m
2024/12/06 09:01:42 Initializing Terraform AWS Provider...
=== RUN   TestAccRDSCluster_basic
=== PAUSE TestAccRDSCluster_basic
=== RUN   TestAccRDSCluster_snapshotIdentifier
=== PAUSE TestAccRDSCluster_snapshotIdentifier
=== RUN   TestAccRDSCluster_SnapshotIdentifier_storageType
=== PAUSE TestAccRDSCluster_SnapshotIdentifier_storageType
=== CONT  TestAccRDSCluster_basic
=== CONT  TestAccRDSCluster_SnapshotIdentifier_storageType
=== CONT  TestAccRDSCluster_snapshotIdentifier
--- PASS: TestAccRDSCluster_basic (109.21s)
--- PASS: TestAccRDSCluster_SnapshotIdentifier_storageType (327.48s)
--- PASS: TestAccRDSCluster_snapshotIdentifier (335.39s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/rds	341.077s
```
