### PR TITLE
r/aws_lexv2models_intent: prompt specification defaults

### LINKED ISSUE #35346: [Bug]: lexv2models/intent: `confirmation_setting` produces diffs for `prompt_attempts_specification`
### Terraform Core Version

1.6.6

### AWS Provider Version

5.32.1

### Affected Resource(s)

* aws_lexv2models_intent

### Expected Behavior

No differences reported.

### Actual Behavior

Differences reported when you use `confirmation_setting` without configuring `confirmation_setting.prompt_specification.prompt_attempts_specification`s for `Initial` and `Retry1`.

### Relevant Error/Panic Output Snippet

_No response_

### Terraform Configuration Files

Reports diffs:

```terraform
resource "aws_lexv2models_intent" "example" {
  bot_id      = aws_lexv2models_bot.test.id
  bot_version = aws_lexv2models_bot_locale.test.bot_version
  name        = "botens_namn"
  locale_id   = aws_lexv2models_bot_locale.test.locale_id

  confirmation_setting {
    active = true

    prompt_specification {
      allow_interrupt            = true
      max_retries                = 1
      message_selection_strategy = "Ordered"
    }
  }
}
```

_Doesn't_ report diffs:

```terraform
resource "aws_lexv2models_intent" "example" {
  bot_id      = aws_lexv2models_bot.test.id
  bot_version = aws_lexv2models_bot_locale.test.bot_version
  name        = "botens_namn"
  locale_id   = aws_lexv2models_bot_locale.test.locale_id

  confirmation_setting {
    active = true

    prompt_specification {
      allow_interrupt            = true
      max_retries                = 1
      message_selection_strategy = "Ordered"

      prompt_attempts_specification {
        allow_interrupt = true
        map_block_key   = "Initial"

        allowed_input_types {
          allow_audio_input = true
          allow_dtmf_input  = true
        }

        audio_and_dtmf_input_specification {
          start_timeout_ms = 4000

          audio_specification {
            end_timeout_ms = 640
            max_length_ms  = 15000
          }

          dtmf_specification {
            deletion_character = "*"
            end_character      = "#"
            end_timeout_ms     = 5000
            max_length         = 513
          }
        }

        text_input_specification {
          start_timeout_ms = 30000
        }
      }

      prompt_attempts_specification {
        allow_interrupt = true
        map_block_key   = "Retry1"

        allowed_input_types {
          allow_audio_input = true
          allow_dtmf_input  = true
        }

        audio_and_dtmf_input_specification {
          start_timeout_ms = 4000

          audio_specification {
            end_timeout_ms = 640
            max_length_ms  = 15000
          }

          dtmf_specification {
            deletion_character = "*"
            end_character      = "#"
            end_timeout_ms     = 5000
            max_length         = 513
          }
        }

        text_input_specification {
          start_timeout_ms = 30000
        }
      }
    }
  }
}
```

### Steps to Reproduce

1. terraform apply

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

* #34891

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by johnsonaj**
## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the library.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

### Description

`confirmation_settings.prompt_specification.prompt_attempt_specifications` can have default values that cause diffs if not present in the configuration.

This change will check for defaults and checks that they are semantically equal.

### Relations

Closes #35346

### References

Relates https://github.com/hashicorp/terraform-plugin-framework/issues/1074

### Output from Acceptance Testing

```console
% make testacc TESTARGS="-run=TestAccLexV2ModelsIntent_confirmationSetting_promptSpecifications_defaults" PKG=lexv2models

make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.24.4 test ./internal/service/lexv2models/... -v -count 1 -parallel 20  -run=TestAccLexV2ModelsIntent_confirmationSetting_promptSpecifications_defaults -timeout 360m -vet=off
2025/06/23 13:15:08 Creating Terraform AWS Provider (SDKv2-style)...
2025/06/23 13:15:08 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccLexV2ModelsIntent_confirmationSetting_promptSpecifications_defaults
=== PAUSE TestAccLexV2ModelsIntent_confirmationSetting_promptSpecifications_defaults
=== CONT  TestAccLexV2ModelsIntent_confirmationSetting_promptSpecifications_defaults
    intent_test.go:1038: Step 1/1 error: After applying this test step, the refresh plan was not empty.
        stdout


        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place

        Terraform will perform the following actions:

          # aws_lexv2models_intent.test will be updated in-place
          ~ resource "aws_lexv2models_intent" "test" {
                id                     = "BZEZCVW43A:BXIEA5F9ML:DRAFT:en_US"
                name                   = "tf-acc-test-7357476630193653006"
                # (7 unchanged attributes hidden)

              ~ confirmation_setting {
                    # (1 unchanged attribute hidden)

                  ~ prompt_specification {
                        # (3 unchanged attributes hidden)

                      - prompt_attempts_specification {
                          - allow_interrupt = true -> null
                          - map_block_key   = "Initial" -> null

                          - allowed_input_types {
                              - allow_audio_input = true -> null
                              - allow_dtmf_input  = true -> null
                            }

                          - audio_and_dtmf_input_specification {
                              - start_timeout_ms = 4000 -> null

                              - audio_specification {
                                  - end_timeout_ms = 640 -> null
                                  - max_length_ms  = 15000 -> null
                                }

                              - dtmf_specification {
                                  - deletion_character = "*" -> null
                                  - end_character      = "#" -> null
                                  - end_timeout_ms     = 5000 -> null
                                  - max_length         = 513 -> null
                                }
                            }

                          - text_input_specification {
                              - start_timeout_ms = 30000 -> null
                            }
                        }
                      - prompt_attempts_specification {
                          - allow_interrupt = true -> null
                          - map_block_key   = "Retry1" -> null

                          - allowed_input_types {
                              - allow_audio_input = true -> null
                              - allow_dtmf_input  = true -> null
                            }

                          - audio_and_dtmf_input_specification {
                              - start_timeout_ms = 4000 -> null

                              - audio_specification {
                                  - end_timeout_ms = 640 -> null
                                  - max_length_ms  = 15000 -> null
                                }

                              - dtmf_specification {
                                  - deletion_character = "*" -> null
                                  - end_character      = "#" -> null
                                  - end_timeout_ms     = 5000 -> null
                                  - max_length         = 513 -> null
                                }
                            }

                          - text_input_specification {
                              - start_timeout_ms = 30000 -> null
                            }
                        }

                        # (1 unchanged block hidden)
                    }
                }
            }

        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccLexV2ModelsIntent_confirmationSetting_promptSpecifications_defaults (42.07s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/lexv2models	47.844s
FAIL
make: *** [testacc] Error 1
```

### after

```console
% make testacc TESTARGS="-run=TestAccLexV2ModelsIntent_" PKG=lexv2models

make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.24.4 test ./internal/service/lexv2models/... -v -count 1 -parallel 20  -run=TestAccLexV2ModelsIntent_ -timeout 360m -vet=off
2025/06/23 13:35:58 Creating Terraform AWS Provider (SDKv2-style)...
2025/06/23 13:35:58 Initializing Terraform AWS Provider (SDKv2-style)...
--- PASS: TestAccLexV2ModelsIntent_disappears (47.76s)
--- PASS: TestAccLexV2ModelsIntent_confirmationSetting_promptSpecifications_defaults (49.72s)
--- PASS: TestAccLexV2ModelsIntent_basic (56.36s)
--- PASS: TestAccLexV2ModelsIntent_updateInputContext (64.76s)
--- PASS: TestAccLexV2ModelsIntent_updateSampleUtterance (64.77s)
--- PASS: TestAccLexV2ModelsIntent_updateClosingSetting (65.68s)
--- PASS: TestAccLexV2ModelsIntent_updateOutputContext (68.15s)
--- PASS: TestAccLexV2ModelsIntent_updateDialogCodeHook (69.70s)
--- PASS: TestAccLexV2ModelsIntent_updateFulfillmentCodeHook (70.40s)
--- PASS: TestAccLexV2ModelsIntent_updateInitialResponseSetting (70.45s)
--- PASS: TestAccLexV2ModelsIntent_updateConfirmationSetting (71.51s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/lexv2models	77.241s
```

### CODE REVIEW

File: internal/service/lexv2models/confirmation_setting_equality.go [hunk 1]
```diff
@@ -0,0 +1,179 @@
...
+			})
+
+			if index != -1 {
+				if !arePromptAttemptValuesEqual(*newPromptAttemptSpecification[index], *value) {
+					return false, diags
+				}
+			} else if _, ok := promptAttemptSpecificationDefaults(ctx, key); ok {
+				hasDefaults = true
+				continue
+			}
```
Comment (jar-b) [inline internal/service/lexv2models/confirmation_setting_equality.go]: This will cause the outer function to return `true` if any of the default map block keys are omitted in the "new" configuration (`hasDefaults` isn't updated again even if  `index` == `-1` and `ok` evaluates to `false` on a subsequent value).

Should this change to verify all "missing" blocks match an expected default? Some unit tests may be helpful here given the complexity of the comparison required.

File: internal/service/lexv2models/confirmation_setting_equality.go [hunk 2]
```diff
@@ -0,0 +1,179 @@
...
+					StartTimeoutMs: fwflex.Int64ValueToFramework(ctx, 30000), //nolint:mnd
+				},
+			}),
+		}
+	}
+
+	defaults := map[string]*PromptAttemptsSpecification{
+		"Initial": objectDefault("Initial"),
+		"Retry1":  objectDefault("Retry1"),
+	}
```
Comment (jar-b) [inline internal/service/lexv2models/confirmation_setting_equality.go]: I vaguely recall the number of returned `RetryN` objects being proportional to the `max_retries` argument. This map may need to be adjusted to return a variable number of keys based on configured retries.

Edit: I was able to confirm this by creating an intent with `v6.0.0` and setting `max_retries` set to `2` with no `prompt_attempt_specifications`. The subsequent plan includes a removal for the `Retry2` map key.

```
              - prompt_attempts_specification {
                  - allow_interrupt = true -> null
                  - map_block_key   = "Retry2" -> null
```

**Comment by johnsonaj** [comment]
```console
% go test -count=1 -v ./internal/service/lexv2models/... -run=TestArePromptAttemptsEqual

2025/06/24 17:20:58 Creating Terraform AWS Provider (SDKv2-style)...
2025/06/24 17:20:58 Initializing Terraform AWS Provider (SDKv2-style)...
--- PASS: TestArePromptAttemptsEqual (0.01s)
    --- PASS: TestArePromptAttemptsEqual/old_values_of_null (0.00s)
    --- PASS: TestArePromptAttemptsEqual/new_value_without_default (0.00s)
    --- PASS: TestArePromptAttemptsEqual/new_value_with_specified_default (0.00s)
    --- PASS: TestArePromptAttemptsEqual/old_values_of_null#01 (0.00s)
    --- PASS: TestArePromptAttemptsEqual/new_values_of_null (0.00s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/lexv2models	5.721s
```

File: internal/service/lexv2models/confirmation_setting_equality.go (hunk 1 above)
Comment (johnsonaj) [reply internal/service/lexv2models/confirmation_setting_equality.go]: @jar-b reworked this to check for all configured arguments and any default attributes that are missing from the configuration.

**Review by jar-b — APPROVED** [review]
LGTM 🎉 

```console
% make testacc PKG=lexv2models TESTS=TestAccLexV2ModelsIntent_
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.24.4 test ./internal/service/lexv2models/... -v -count 1 -parallel 20 -run='TestAccLexV2ModelsIntent_'  -timeout 360m -vet=off
2025/06/26 11:01:11 Creating Terraform AWS Provider (SDKv2-style)...
2025/06/26 11:01:11 Initializing Terraform AWS Provider (SDKv2-style)...

--- PASS: TestAccLexV2ModelsIntent_disappears (47.19s)
--- PASS: TestAccLexV2ModelsIntent_basic (53.79s)
--- PASS: TestAccLexV2ModelsIntent_updateInputContext (61.21s)
--- PASS: TestAccLexV2ModelsIntent_updateClosingSetting (64.70s)
--- PASS: TestAccLexV2ModelsIntent_updateFulfillmentCodeHook (64.73s)
--- PASS: TestAccLexV2ModelsIntent_updateSampleUtterance (66.24s)
--- PASS: TestAccLexV2ModelsIntent_updateConfirmationSetting (67.15s)
--- PASS: TestAccLexV2ModelsIntent_updateDialogCodeHook (69.46s)
--- PASS: TestAccLexV2ModelsIntent_confirmationSetting_promptSpecifications_defaults (70.35s)
--- PASS: TestAccLexV2ModelsIntent_updateOutputContext (70.55s)
--- PASS: TestAccLexV2ModelsIntent_updateInitialResponseSetting (73.95s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/lexv2models        79.811s
```
