### PR TITLE
[aws_workspaces_directory] Fix Empty Custom Security Group ID & Default OU

### LINKED ISSUE #16122: aws_workspaces_directory: Error with workspace_creation_properties
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
```sh
$ terraform -v
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.14.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/time v0.6.0
```

### Affected Resource(s)

* aws_workspaces_directory

### Terraform Configuration Files

```hcl
resource "aws_security_group" "SG-test" {
  name        = "SG-test"
  vpc_id      = aws_vpc.WA-VPC.id

  ingress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name = "SG-test"
  }
}


resource "aws_workspaces_directory" "WORKSPACES-DIRECTORY" {
    directory_id = aws_directory_service_directory.WA-ADCONNECTOR.id
    subnet_ids   = [aws_subnet.WA-SN-PRIV-1A.id, aws_subnet.WA-SN-PRIV-1B.id]

    tags = {
        Name    = "WORKSPACES-DIRECTORY"
    }
    
    depends_on = [aws_directory_service_directory.WA-ADCONNECTOR]

    self_service_permissions {
        change_compute_type  = false
        increase_volume_size = false
        rebuild_workspace    = false
        restart_workspace    = true
        switch_running_mode  = false
    }

    workspace_creation_properties {
        #custom_security_group_id           = aws_security_group.SG-test.id     # Here is the problem
        enable_internet_access              = true
        enable_maintenance_mode             = true
        user_enabled_as_local_administrator = false
    }
}
```

### Debug Output

There are **2 problems**. Both are related to the parameter `custom_security_group_id`.
* The first problem occurs when the parameter is commented: [terraform1.log](https://gist.github.com/fgrebot/c5452f8867ecce7c55b4202eea3d43c4) 
* The second occurs when the parameter is uncommented: [terraform2.log](https://gist.github.com/fgrebot/6ddc1689924922943b045379ab83091d)

### Panic Output
n/a

### Expected Behavior

In both scenarios, the AWS Workspaces Directory should have been registered with the following parameter:
```hlc
workspace_creation_properties {
        enable_internet_access              = true
        enable_maintenance_mode             = true
        user_enabled_as_local_administrator = false
    }
```
According to the [Official API documentation of AWS](https://docs.aws.amazon.com/workspaces/latest/api/API_ModifyWorkspaceCreationProperties.html) and of the [AWS provider](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/workspaces_directory#workspace_creation_properties), all the parameters provided are flagged **optional**.

### Actual Behavior

The AWS Workspaces Directory is registered but all the parameters given are not taken into account. And because of the error, terraform stops to deploy others resources.

### Steps to Reproduce

1. Create a directory in AWS Directory Service
2. Create a `aws_workspaces_directory`, first WITH then WITHOUT a `custom_security_group_id`
3. `terraform apply`

### References

* #14577
* #14332

### PR DESCRIPTION
**Pull request by Tensho**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #16122

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
aws_workspaces_directory: Fix empty custom_security_group_id & default_ou
```

### Unit Tests

```
$ make test TEST=./aws TESTARGS='-run=TestExpandWorkspaceCreationProperties'
==> Checking that code complies with gofmt requirements...
go test ./aws -run=TestExpandWorkspaceCreationProperties -timeout=5m -parallel=4
ok  	github.com/terraform-providers/terraform-provider-aws/aws	2.729s
$ make test TEST=./aws TESTARGS='-run=TestFlattenWorkspaceCreationProperties'
==> Checking that code complies with gofmt requirements...
go test ./aws -run=TestFlattenWorkspaceCreationProperties -timeout=5m -parallel=4
ok  	github.com/terraform-providers/terraform-provider-aws/aws	3.002s
```

### Acceptance Tests

```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAwsWorkspacesDirectory_workspaceCreationProperties'
AWS_REGION=us-east-1 make testacc TEST=./aws TESTARGS='-run=TestAccAwsWorkspacesDirectory_workspaceCreationProperties'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsWorkspacesDirectory_workspaceCreationProperties -timeout 120m
=== RUN   TestAccAwsWorkspacesDirectory_workspaceCreationProperties
=== PAUSE TestAccAwsWorkspacesDirectory_workspaceCreationProperties
=== RUN   TestAccAwsWorkspacesDirectory_workspaceCreationProperties_customSecurityGroupId_defaultOu
=== PAUSE TestAccAwsWorkspacesDirectory_workspaceCreationProperties_customSecurityGroupId_defaultOu
=== CONT  TestAccAwsWorkspacesDirectory_workspaceCreationProperties
=== CONT  TestAccAwsWorkspacesDirectory_workspaceCreationProperties_customSecurityGroupId_defaultOu
--- PASS: TestAccAwsWorkspacesDirectory_workspaceCreationProperties (1070.72s)
--- PASS: TestAccAwsWorkspacesDirectory_workspaceCreationProperties_customSecurityGroupId_defaultOu (1120.56s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	1123.562s
```

### CODE REVIEW

File: aws/resource_aws_workspaces_directory_test.go [hunk 1]
```diff
@@ -658,6 +804,50 @@ resource "aws_workspaces_directory" "main" {
 `, rName))
 }
 
+func testAccWorkspacesDirectoryConfig_workspaceCreationProperties_customSecurityGroupId_defaultOu_Absent(rName string) string {
+	return composeConfig(
+		testAccAwsWorkspacesDirectoryConfig_Prerequisites(rName),
+		fmt.Sprintf(`
+resource "aws_security_group" "test" {
```
Comment (DrFaust92) [inline aws/resource_aws_workspaces_directory_test.go:811]: extraneous as its not used in this config

**Review by DrFaust92 — CHANGES_REQUESTED** [review]
Minor change in test config. otherwise looks good codewise

File: aws/resource_aws_workspaces_directory_test.go (hunk 1 above)
Comment (Tensho) [reply aws/resource_aws_workspaces_directory_test.go:811]: Sharp eyes 🦅  Thank you, I'll drop it.

**Review by DrFaust92 — APPROVED** [review]
LGTM

**Review by ewbankkit — APPROVED** [review]
LGTM.

**Comment by breathingdust** [comment]
LGTM :rocket: Thanks @Tensho 

Verified Acceptance Tests in Commercial (us-west-2)

```console
make testacc TEST=./aws TESTARGS='-run=TestAccAwsWorkspacesDirectory_workspaceCreationProperties'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsWorkspacesDirectory_workspaceCreationProperties -timeout 120m
=== RUN   TestAccAwsWorkspacesDirectory_workspaceCreationProperties
=== PAUSE TestAccAwsWorkspacesDirectory_workspaceCreationProperties
=== CONT  TestAccAwsWorkspacesDirectory_workspaceCreationProperties
--- PASS: TestAccAwsWorkspacesDirectory_workspaceCreationProperties (787.82s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	789.385s
```
