### PR TITLE
iam/role: If inline fails, role fails

### LINKED ISSUE #23124: IAM Role not added to state when inline IAM Policy is invalid
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```shell
Terraform v1.1.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.0.0
```

* aws_iam_role

### Terraform Configuration Files
This config is invalid due to the `inline_policy` missing the `actions`.

```hcl
provider "aws" {
  region = "ap-southeast-2"
}

#####################################
# INVALID POLICY
#####################################

resource "aws_iam_role" "InvalidPolicyIAMRole" {
  name               = "InvalidPolicyIAMRole"
  assume_role_policy = data.aws_iam_policy_document.flow_log_cloudwatch_assume_role.json

  inline_policy {
    name = "my_inline_policy"

    policy = jsonencode({
      Version = "2012-10-17"
      Statement = [
        {
          Effect   = "Allow"
          Resource = "*"
        },
      ]
    })
  }
}

data "aws_iam_policy_document" "flow_log_cloudwatch_assume_role" {
  statement {
    sid = "AWSVPCFlowLogsAssumeRole"

    principals {
      type        = "Service"
      identifiers = ["vpc-flow-logs.amazonaws.com"]
    }

    effect = "Allow"

    actions = ["sts:AssumeRole"]
  }
}

```

### Debug Output
Plan, Apply and Import logs showing the issue.
[Debug Logs](https://gist.github.com/jykingston/ab9952b204c374b6278bc816ce30fd95)

### Panic Output
N/A
### Expected Behavior
The IAM Role should be added to the state, allowing a second `terraform apply` to fix the IAM Policy.
1. `terraform apply` creates the role, ERROR `MalformedPolicyDocument` on the policy
3. `terraform plan` shows **only** the IAM Policy to be updated
4. `terraform apply` updates the IAM Policy and finishes successfully.  

### Actual Behavior
1. `terraform apply` creates the IAM Role. ERROR `MalformedPolicyDocument` on the policy
3. `terraform plan` shows the IAM Policy and the IAM Role to be created
3. `terraform apply` ERROR `EntityAlreadyExists` as the IAM Role was created on the first run, but not added to state. 

### Steps to Reproduce
Just run the config above twice.
1. `terraform apply` - `MalformedPolicyDocument`
2. `terraform apply` - `EntityAlreadyExists`

### PR DESCRIPTION
**Pull request by YakDriver**
### Relations

Closes #23124

### Output from Acceptance Testing

```console
% make t T=TestAccIAMRole_InlinePolicy_malformed K=iam
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.5 test ./internal/service/iam/... -v -count 1 -parallel 20 -run='TestAccIAMRole_InlinePolicy_malformed'  -timeout 360m
=== RUN   TestAccIAMRole_InlinePolicy_malformed
=== PAUSE TestAccIAMRole_InlinePolicy_malformed
=== CONT  TestAccIAMRole_InlinePolicy_malformed
--- PASS: TestAccIAMRole_InlinePolicy_malformed (6.70s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/iam	9.241s
```

### CODE REVIEW

File: internal/service/iam/role_test.go [hunk 1]
```diff
@@ -699,6 +699,24 @@ func TestAccIAMRole_InlinePolicy_empty(t *testing.T) {
...
+
+	resource.ParallelTest(t, resource.TestCase{
+		PreCheck:                 func() { acctest.PreCheck(ctx, t) },
+		ErrorCheck:               acctest.ErrorCheck(t, names.IAMServiceID),
+		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories,
+		CheckDestroy:             testAccCheckRoleDestroy(ctx),
+		Steps: []resource.TestStep{
+			{
+				Config:      testAccRoleConfig_policyInlineMalformed(rName, rName),
+				ExpectError: regexache.MustCompile(`MalformedPolicyDocument`),
```
Comment (YakDriver) [inline internal/service/iam/role_test.go:714]: This is a little tough to test fully because `Check` doesn't run if an error is encountered. I would like to do a `testAccCheckRoleDestroy` to make sure it's gone before the destroy phase, but, I verified by tracing execution that the role is deleted in this case.

**Review by jar-b — APPROVED** [review]
LGTM 🎉 

```console
% make testacc PKG=iam TESTS=TestAccIAMRole_
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.5 test ./internal/service/iam/... -v -count 1 -parallel 20 -run='TestAccIAMRole_'  -timeout 360m

--- PASS: TestAccIAMRole_badJSON (4.58s)
=== CONT  TestAccIAMRole_testNameChange
--- PASS: TestAccIAMRole_InlinePolicy_malformed (13.73s)
=== CONT  TestAccIAMRole_namePrefix
--- PASS: TestAccIAMRole_disappears (25.88s)
=== CONT  TestAccIAMRole_nameGenerated
--- PASS: TestAccIAMRole_InlinePolicy_empty (26.11s)
=== CONT  TestAccIAMRole_ManagedPolicy_outOfBandAdditionIgnored
=== CONT  TestAccIAMRole_tags_DefaultTags_updateToResourceOnly
--- PASS: TestAccIAMRole_namePrefix (33.27s)
--- PASS: TestAccIAMRole_InlinePolicy_outOfBandRemovalAddedBack (51.75s)
=== CONT  TestAccIAMRole_basic
--- PASS: TestAccIAMRole_policiesForceDetach (51.84s)
=== CONT  TestAccIAMRole_tags_ComputedTag_OnUpdate_Replace
--- PASS: TestAccIAMRole_ManagedPolicy_outOfBandRemovalAddedBack (51.98s)
=== CONT  TestAccIAMRole_tags_ComputedTag_OnUpdate_Add
--- PASS: TestAccIAMRole_ManagedPolicy_outOfBandAdditionRemovedEmpty (53.29s)
=== CONT  TestAccIAMRole_tags_ComputedTag_OnCreate
--- PASS: TestAccIAMRole_InlinePolicy_outOfBandAdditionRemovedEmpty (53.52s)
=== CONT  TestAccIAMRole_tags_DefaultTags_nullNonOverlappingResourceTag
--- PASS: TestAccIAMRole_InlinePolicy_outOfBandAdditionRemoved (53.85s)
=== CONT  TestAccIAMRole_tags_DefaultTags_nullOverlappingResourceTag
--- PASS: TestAccIAMRole_ManagedPolicy_outOfBandAdditionRemoved (53.96s)
=== CONT  TestAccIAMRole_tags_DefaultTags_emptyProviderOnlyTag
--- PASS: TestAccIAMRole_testNameChange (51.90s)
=== CONT  TestAccIAMRole_tags_DefaultTags_emptyResourceTag
--- PASS: TestAccIAMRole_nameGenerated (35.28s)
=== CONT  TestAccIAMRole_InlinePolicy_outOfBandAdditionIgnored
--- PASS: TestAccIAMRole_InlinePolicy_ignoreOrder (62.74s)
=== CONT  TestAccIAMRole_tags_EmptyTag_OnUpdate_Replace
--- PASS: TestAccIAMRole_maxSessionDuration (69.36s)
=== CONT  TestAccIAMRole_tags_DefaultTags_updateToProviderOnly
--- PASS: TestAccIAMRole_ManagedPolicy_outOfBandAdditionIgnored (47.76s)
=== CONT  TestAccIAMRole_tags_DefaultTags_overlapping
--- PASS: TestAccIAMRole_ManagedPolicy_basic (75.71s)
=== CONT  TestAccIAMRole_tags_DefaultTags_nonOverlapping
--- PASS: TestAccIAMRole_description (79.39s)
=== CONT  TestAccIAMRole_tags_DefaultTags_providerOnly
--- PASS: TestAccIAMRole_InlinePolicy_basic (79.47s)
=== CONT  TestAccIAMRole_tags_EmptyTag_OnCreate
--- PASS: TestAccIAMRole_basic (39.91s)
=== CONT  TestAccIAMRole_tags_EmptyTag_OnUpdate_Add
--- PASS: TestAccIAMRole_tags_ComputedTag_OnCreate (42.65s)
=== CONT  TestAccIAMRole_tags_AddOnUpdate
--- PASS: TestAccIAMRole_tags_DefaultTags_emptyProviderOnlyTag (42.67s)
=== CONT  TestAccIAMRole_tags_null
--- PASS: TestAccIAMRole_tags_DefaultTags_nullOverlappingResourceTag (43.00s)
--- PASS: TestAccIAMRole_tags_DefaultTags_nullNonOverlappingResourceTag (43.62s)
--- PASS: TestAccIAMRole_tags_DefaultTags_emptyResourceTag (42.21s)
--- PASS: TestAccIAMRole_diffsCondition (111.65s)
--- PASS: TestAccIAMRole_tags_DefaultTags_updateToResourceOnly (65.94s)
--- PASS: TestAccIAMRole_InlinePolicy_outOfBandAdditionIgnored (58.22s)
--- PASS: TestAccIAMRole_tags_ComputedTag_OnUpdate_Add (68.56s)
--- PASS: TestAccIAMRole_tags_ComputedTag_OnUpdate_Replace (69.05s)
--- PASS: TestAccIAMRole_tags_EmptyTag_OnUpdate_Replace (60.54s)
--- PASS: TestAccIAMRole_tags_DefaultTags_updateToProviderOnly (58.37s)
--- PASS: TestAccIAMRole_permissionsBoundary (132.13s)
--- PASS: TestAccIAMRole_tags (132.50s)
--- PASS: TestAccIAMRole_tags_null (37.38s)
--- PASS: TestAccIAMRole_tags_EmptyTag_OnCreate (56.34s)
--- PASS: TestAccIAMRole_tags_AddOnUpdate (42.46s)
--- PASS: TestAccIAMRole_tags_DefaultTags_nonOverlapping (70.72s)
--- PASS: TestAccIAMRole_tags_DefaultTags_overlapping (73.70s)
--- PASS: TestAccIAMRole_tags_EmptyTag_OnUpdate_Add (56.78s)
--- PASS: TestAccIAMRole_tags_DefaultTags_providerOnly (78.09s)
--- PASS: TestAccIAMRole_diffs (202.07s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/iam        207.935s
```
