### PR TITLE
Fix #29866: ignore activities failed because of missing instance profile

### LINKED ISSUE #29866: [Bug]: Invalid IAM Instance Profile ARN when creating ASG using launch template
### Terraform Core Version

v1.2.8

### AWS Provider Version

Discovered on:
v4.57.1

Tested further on:
v4.55.0
v4.10.0

Confirmed NOT affected:
v3.*

### Affected Resource(s)

aws_launch_template
aws_autoscaling_group

### Expected Behavior

The Autoscaling group using launch template should create successfully every time

### Actual Behavior

The Autoscaling group **intermittently** fails to create with error
Error: creating Auto Scaling Group (autoscalinggroupname): ValidationError: You must use a valid fully-formed launch template. Value (instanceprofilearn) for parameter iamInstanceProfile.arn is invalid. Invalid IAM Instance Profile ARN

or the error

Error: waiting for Auto Scaling Group (XXXX) capacity satisfied: 1 error occurred:
│ 	* Scaling activity (f7d61a6f-9968-69b4-17da-7b6f90ee5511): Failed: Value (instanceprofilearn) for parameter iamInstanceProfile.arn is invalid. Invalid IAM Instance Profile ARN. Launching EC2 instance failed.

The DEBUG output I have provided relates to the first error.

### Relevant Error/Panic Output Snippet

```shell
# aws_autoscaling_group.lb will be created
  + resource "aws_autoscaling_group" "lb" {
      + arn                       = (known after apply)
      + availability_zones        = (known after apply)
      + default_cooldown          = (known after apply)
      + desired_capacity          = 1
      + force_delete              = false
      + force_delete_warm_pool    = false
      + health_check_grace_period = 300
      + health_check_type         = (known after apply)
      + id                        = (known after apply)
      + max_size                  = 1
      + metrics_granularity       = "1Minute"
      + min_size                  = 1
      + name                      = "jamieGDS-test"
      + name_prefix               = (known after apply)
      + protect_from_scale_in     = false
      + service_linked_role_arn   = (known after apply)
      + vpc_zone_identifier       = [
          + "subnet-00000000000000",
        ]
      + wait_for_capacity_timeout = "10m"

      + launch_template {
          + id   = (known after apply)
          + name = (known after apply)
        }
    }

  # aws_iam_instance_profile.name will be created
  + resource "aws_iam_instance_profile" "name" {
      + arn         = (known after apply)
      + create_date = (known after apply)
      + id          = (known after apply)
      + name        = "instance-profile.name"
      + path        = "/ecs/instances/name/"
      + role        = "role.name"
      + tags_all    = (known after apply)
      + unique_id   = (known after apply)
    }

  # aws_iam_role.name will be created
  + resource "aws_iam_role" "name" {
      + arn                   = (known after apply)
      + assume_role_policy    = jsonencode(
            {
              + Statement = [
                  + {
                      + Action    = "sts:AssumeRole"
                      + Effect    = "Allow"
                      + Principal = {
                          + Service = [
                              + "ec2.amazonaws.com",
                            ]
                        }
                      + Sid       = ""
                    },
                ]
              + Version   = "2008-10-17"
            }
        )
      + create_date           = (known after apply)
      + force_detach_policies = false
      + id                    = (known after apply)
      + managed_policy_arns   = (known after apply)
      + max_session_duration  = 3600
      + name                  = "role.name"
      + name_prefix           = (known after apply)
      + path                  = "/ecs/instances/name/"
      + tags_all              = (known after apply)
      + unique_id             = (known after apply)

      + inline_policy {
          + name   = (known after apply)
          + policy = (known after apply)
        }
    }

  # aws_launch_template.name will be created
  + resource "aws_launch_template" "name" {
      + arn                    = (known after apply)
      + default_version        = (known after apply)
      + id                     = (known after apply)
      + image_id               = "ami-00000000000"
      + instance_type          = "t3.medium"
      + key_name               = "env-default"
      + latest_version         = (known after apply)
      + name                   = "test"
      + name_prefix            = (known after apply)
      + tags_all               = (known after apply)
      + update_default_version = true

      + block_device_mappings {
          + device_name = "/dev/xvda"

          + ebs {
              + delete_on_termination = "true"
              + iops                  = (known after apply)
              + throughput            = (known after apply)
              + volume_size           = 8
              + volume_type           = "gp3"
            }
        }

      + iam_instance_profile {
          + arn = (known after apply)
        }

      + metadata_options {
          + http_endpoint               = (known after apply)
          + http_protocol_ipv6          = (known after apply)
          + http_put_response_hop_limit = (known after apply)
          + http_tokens                 = (known after apply)
          + instance_metadata_tags      = (known after apply)
        }

      + network_interfaces {
          + associate_public_ip_address = "true"
          + security_groups             = (known after apply)
        }
    }

  # aws_security_group.name will be created
  + resource "aws_security_group" "name" {
      + arn                    = (known after apply)
      + description            = "Managed by Terraform"
      + egress                 = [
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = "Proxy to world (http)"
              + from_port        = 80
              + ipv6_cidr_blocks = [
                  + "::/0",
                ]
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 80
            },
        ]
      + id                     = (known after apply)
      + ingress                = (known after apply)
      + name                   = "jamieGDS-test"
      + name_prefix            = (known after apply)
      + owner_id               = (known after apply)
      + revoke_rules_on_delete = false
      + tags_all               = (known after apply)
      + vpc_id                 = "vpc-000000000000"
    }

Plan: 5 to add, 0 to change, 0 to destroy.

aws_iam_role.name: Creating...
aws_security_group.name: Creating...
aws_iam_role.name: Creation complete after 1s [id=role.name]
aws_iam_instance_profile.name: Creating...
aws_iam_instance_profile.name: Creation complete after 0s [id=instance-profile.name]
aws_security_group.name: Creation complete after 2s [id=sg-03360402bb541956b]
aws_launch_template.name: Creating...
aws_launch_template.name: Creation complete after 0s [id=lt-00fe0a89f42254d47]
aws_autoscaling_group.lb: Creating...

Error: waiting for Auto Scaling Group (jamieGDS-test) capacity satisfied: 1 error occurred:
	* Scaling activity (a0261b07-7c0b-a510-74c9-0b762344ef16): Failed: Value (arn:aws:iam::account-id:instance-profile/ecs/instances/name/instance-profile.name) for parameter iamInstanceProfile.arn is invalid. Invalid IAM Instance Profile ARN. Launching EC2 instance failed.
```

### Terraform Configuration Files

Running this basic test failed approximately 1/10 times for me.

```
resource "aws_iam_role" "name" {
  name = "role.name"
  path = "/ecs/instances/name/"

  assume_role_policy = <<EOF
{
  "Version": "2008-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Service": [
          "ec2.amazonaws.com"
        ]
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
EOF

}

resource "aws_security_group" "name" {
  name   = "jamieGDS-test"
  vpc_id = "vpc-000000000000"

  egress {
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    description = "Proxy to world (http)"

    cidr_blocks      = ["0.0.0.0/0"]
    ipv6_cidr_blocks = ["::/0"]
  }
}

resource "aws_iam_instance_profile" "name" {
  name = "instance-profile.name"
  path = "/ecs/instances/name/"
  role = aws_iam_role.name.name
}



resource "aws_launch_template" "name" {
  name = "test"

  network_interfaces {
    associate_public_ip_address = true
    security_groups = [
      aws_security_group.name.id,
    ]
  }

  image_id               = "ami-0000000000000"
  instance_type          = "t3.medium"
  key_name               = "environment-default"
  update_default_version = true

  block_device_mappings {
    device_name = "/dev/xvda"
    ebs {
      volume_type           = "gp3"
      volume_size           = 8
      delete_on_termination = true
    }
  }

  iam_instance_profile {
    arn = aws_iam_instance_profile.name.arn
  }
}

resource "aws_autoscaling_group" "lb" {
  name                = "jamieGDS-test"
  vpc_zone_identifier = ["subnet_id"]
  min_size            = 1
  desired_capacity    = 1
  max_size            = 1
  launch_template {
    id = aws_launch_template.name.id
  }

  lifecycle {
    ignore_changes        = [desired_capacity]
  }
}
```

### Steps to Reproduce

Replace the ami, subnet and vpc attributes with sensible values for your environment. Run the test code above multiple times.
You can use this script to do so:

```
#!/bin/bash

export TF_LOG_PATH=$(pwd)/output.log
export TF_LOG=debug

for i in $(seq 1 10); do
	echo "Attempting to apply number $i" >> output.log
	terraform-1.2.8 apply -no-color -auto-approve >> output.log
	terraform-1.2.8 apply -destroy -no-color -auto-approve
done
```

### Debug Output

https://gist.github.com/jamiegDS/e44aaf98e03f0ad75a0ccf82c8974b9b

### Panic Output

_No response_

### Important Factoids

Just as stated, this issue seems to happen around 1/10 times. I will continue testing with lower provider versions, but I did see another user with similar error in comment here: https://github.com/hashicorp/terraform-provider-aws/issues/24910

### References

_No response_

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by nicolaferraro**
### Description

This makes the code ignore activities failed because of missing IAM instance profile (often subject to slow propagation), since they'll be retried.

e.g.

```json
{
  "Activities": [
    {
      "ActivityId": "14e61ffe-330b-9033-3631-ef121f4bf815",
      "AutoScalingGroupName": "nicola-test",
      "Description": "Launching a new EC2 instance: i-0f36773391e6f1af8",
      "Cause": "At 2023-05-09T08:07:06Z an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 0 to 1.",
      "StartTime": "2023-05-09T08:07:07.749000+00:00",
      "EndTime": "2023-05-09T08:07:14+00:00",
      "StatusCode": "Successful",
      "Progress": 100,
      "Details": "{\"Subnet ID\":\"subnet-03dcfc9c7fd5bd56d\",\"Availability Zone\":\"eu-west-1c\"}",
      "AutoScalingGroupARN": "arn:aws:autoscaling:eu-west-1:961547496971:autoScalingGroup:f7915229-02e5-4100-a726-6a88239557cb:autoScalingGroupName/nicola-test"
    },
    {
      "ActivityId": "93361ffe-2f35-8033-98f4-fb97ce49988d",
      "AutoScalingGroupName": "nicola-test",
      "Description": "Launching a new EC2 instance.  Status Reason: Value (arn:aws:iam::961547496971:instance-profile/ecs/instances/name/instance-profile.name) for parameter iamInstanceProfile.arn is invalid. Invalid IAM Instance Profile ARN. Launching EC2 instance failed.",
      "Cause": "At 2023-05-09T08:06:02Z a user request created an AutoScalingGroup changing the desired capacity from 0 to 1.  At 2023-05-09T08:06:03Z an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 0 to 1.",
      "StartTime": "2023-05-09T08:06:04.896000+00:00",
      "EndTime": "2023-05-09T08:06:04+00:00",
      "StatusCode": "Failed",
      "StatusMessage": "Value (arn:aws:iam::961547496971:instance-profile/ecs/instances/name/instance-profile.name) for parameter iamInstanceProfile.arn is invalid. Invalid IAM Instance Profile ARN. Launching EC2 instance failed.",
      "Progress": 100,
      "Details": "{\"Subnet ID\":\"subnet-03dcfc9c7fd5bd56d\",\"Availability Zone\":\"eu-west-1c\"}",
      "AutoScalingGroupARN": "arn:aws:autoscaling:eu-west-1:961547496971:autoScalingGroup:f7915229-02e5-4100-a726-6a88239557cb:autoScalingGroupName/nicola-test"
    }
  ]
}
```

### Relations

Closes #29866

### CODE REVIEW

File: internal/service/autoscaling/group.go [hunk 1]
```diff
@@ -2175,6 +2175,10 @@ func statusGroupCapacity(ctx context.Context, conn *autoscaling.AutoScaling, elb
 
 		for _, v := range scalingActivities {
 			if statusCode := aws.StringValue(v.StatusCode); statusCode == autoscaling.ScalingActivityStatusCodeFailed && aws.Int64Value(v.Progress) == 100 {
+				if strings.Contains(aws.StringValue(v.StatusMessage), "Invalid IAM Instance Profile") {
```
Comment (c4milo) [inline internal/service/autoscaling/group.go:2178]: hm, this could match errors on multiple parameters. What do you think about constraining it to the ARN: `Invalid IAM Instance Profile ARN`, so it doesn't retry for invalid instance profile names or other parameters not related to a delay on state propagation.

Comment (nicolaferraro) [reply internal/service/autoscaling/group.go:2178]: Yeah, sounds reasonable

Comment (nicolaferraro) [reply internal/service/autoscaling/group.go:2178]: Probably not... I recall why I didn't add the `ARN` part. It's because the autoscaling group gets the IAM instance profile from the launch template, which supports both `name` and `ARN` as identifiers: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template#instance-profile

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccAutoScalingGroup_' PKG=autoscaling ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/autoscaling/... -v -count 1 -parallel 2  -run=TestAccAutoScalingGroup_ -timeout 180m
=== RUN   TestAccAutoScalingGroup_basic
=== PAUSE TestAccAutoScalingGroup_basic
=== RUN   TestAccAutoScalingGroup_disappears
=== PAUSE TestAccAutoScalingGroup_disappears
=== RUN   TestAccAutoScalingGroup_defaultInstanceWarmup
=== PAUSE TestAccAutoScalingGroup_defaultInstanceWarmup
=== RUN   TestAccAutoScalingGroup_nameGenerated
=== PAUSE TestAccAutoScalingGroup_nameGenerated
=== RUN   TestAccAutoScalingGroup_namePrefix
=== PAUSE TestAccAutoScalingGroup_namePrefix
=== RUN   TestAccAutoScalingGroup_tags
=== PAUSE TestAccAutoScalingGroup_tags
=== RUN   TestAccAutoScalingGroup_simple
=== PAUSE TestAccAutoScalingGroup_simple
=== RUN   TestAccAutoScalingGroup_terminationPolicies
=== PAUSE TestAccAutoScalingGroup_terminationPolicies
=== RUN   TestAccAutoScalingGroup_vpcUpdates
=== PAUSE TestAccAutoScalingGroup_vpcUpdates
=== RUN   TestAccAutoScalingGroup_withLoadBalancer
=== PAUSE TestAccAutoScalingGroup_withLoadBalancer
=== RUN   TestAccAutoScalingGroup_WithLoadBalancer_toTargetGroup
=== PAUSE TestAccAutoScalingGroup_WithLoadBalancer_toTargetGroup
=== RUN   TestAccAutoScalingGroup_withTrafficSourceELB
=== PAUSE TestAccAutoScalingGroup_withTrafficSourceELB
=== RUN   TestAccAutoScalingGroup_withTrafficSourcesELBs
=== PAUSE TestAccAutoScalingGroup_withTrafficSourcesELBs
=== RUN   TestAccAutoScalingGroup_withTrafficSourceELB_toTargetGroup
=== PAUSE TestAccAutoScalingGroup_withTrafficSourceELB_toTargetGroup
=== RUN   TestAccAutoScalingGroup_withTrafficSourceELBV2
=== PAUSE TestAccAutoScalingGroup_withTrafficSourceELBV2
=== RUN   TestAccAutoScalingGroup_withTrafficSourceVPCLatticeTargetGroup
=== PAUSE TestAccAutoScalingGroup_withTrafficSourceVPCLatticeTargetGroup
=== RUN   TestAccAutoScalingGroup_withTrafficSourceVPCLatticeTargetGroups
=== PAUSE TestAccAutoScalingGroup_withTrafficSourceVPCLatticeTargetGroups
=== RUN   TestAccAutoScalingGroup_withPlacementGroup
=== PAUSE TestAccAutoScalingGroup_withPlacementGroup
=== RUN   TestAccAutoScalingGroup_withScalingActivityErrorPlacementGroupNotSupportedOnInstanceType
=== PAUSE TestAccAutoScalingGroup_withScalingActivityErrorPlacementGroupNotSupportedOnInstanceType
=== RUN   TestAccAutoScalingGroup_withScalingActivityErrorIncorrectInstanceArchitecture
=== PAUSE TestAccAutoScalingGroup_withScalingActivityErrorIncorrectInstanceArchitecture
=== RUN   TestAccAutoScalingGroup_withScalingActivityErrorIncorrectInstanceArchitecture_Recovers
=== PAUSE TestAccAutoScalingGroup_withScalingActivityErrorIncorrectInstanceArchitecture_Recovers
=== RUN   TestAccAutoScalingGroup_enablingMetrics
=== PAUSE TestAccAutoScalingGroup_enablingMetrics
=== RUN   TestAccAutoScalingGroup_withMetrics
=== PAUSE TestAccAutoScalingGroup_withMetrics
=== RUN   TestAccAutoScalingGroup_suspendingProcesses
=== PAUSE TestAccAutoScalingGroup_suspendingProcesses
=== RUN   TestAccAutoScalingGroup_serviceLinkedRoleARN
=== PAUSE TestAccAutoScalingGroup_serviceLinkedRoleARN
=== RUN   TestAccAutoScalingGroup_maxInstanceLifetime
=== PAUSE TestAccAutoScalingGroup_maxInstanceLifetime
=== RUN   TestAccAutoScalingGroup_initialLifecycleHook
=== PAUSE TestAccAutoScalingGroup_initialLifecycleHook
=== RUN   TestAccAutoScalingGroup_launchTemplate
=== PAUSE TestAccAutoScalingGroup_launchTemplate
=== RUN   TestAccAutoScalingGroup_LaunchTemplate_update
=== PAUSE TestAccAutoScalingGroup_LaunchTemplate_update
=== RUN   TestAccAutoScalingGroup_largeDesiredCapacity
=== PAUSE TestAccAutoScalingGroup_largeDesiredCapacity
=== RUN   TestAccAutoScalingGroup_InstanceRefresh_basic
=== PAUSE TestAccAutoScalingGroup_InstanceRefresh_basic
=== RUN   TestAccAutoScalingGroup_InstanceRefresh_start
=== PAUSE TestAccAutoScalingGroup_InstanceRefresh_start
=== RUN   TestAccAutoScalingGroup_InstanceRefresh_triggers
=== PAUSE TestAccAutoScalingGroup_InstanceRefresh_triggers
=== RUN   TestAccAutoScalingGroup_InstanceRefresh_autoRollback
=== PAUSE TestAccAutoScalingGroup_InstanceRefresh_autoRollback
=== RUN   TestAccAutoScalingGroup_loadBalancers
=== PAUSE TestAccAutoScalingGroup_loadBalancers
=== RUN   TestAccAutoScalingGroup_targetGroups
=== PAUSE TestAccAutoScalingGroup_targetGroups
=== RUN   TestAccAutoScalingGroup_ALBTargetGroups_elbCapacity
=== PAUSE TestAccAutoScalingGroup_ALBTargetGroups_elbCapacity
=== RUN   TestAccAutoScalingGroup_warmPool
=== PAUSE TestAccAutoScalingGroup_warmPool
=== RUN   TestAccAutoScalingGroup_launchTempPartitionNum
=== PAUSE TestAccAutoScalingGroup_launchTempPartitionNum
=== RUN   TestAccAutoScalingGroup_Destroy_whenProtectedFromScaleIn
=== PAUSE TestAccAutoScalingGroup_Destroy_whenProtectedFromScaleIn
=== RUN   TestAccAutoScalingGroup_mixedInstancesPolicy
=== PAUSE TestAccAutoScalingGroup_mixedInstancesPolicy
=== RUN   TestAccAutoScalingGroup_MixedInstancesPolicy_capacityRebalance
=== PAUSE TestAccAutoScalingGroup_MixedInstancesPolicy_capacityRebalance
=== RUN   TestAccAutoScalingGroup_MixedInstancesPolicyInstancesDistribution_onDemandAllocationStrategy
=== PAUSE TestAccAutoScalingGroup_MixedInstancesPolicyInstancesDistribution_onDemandAllocationStrategy
=== RUN   TestAccAutoScalingGroup_MixedInstancesPolicyInstancesDistribution_onDemandBaseCapacity
=== PAUSE TestAccAutoScalingGroup_MixedInstancesPolicyInstancesDistribution_onDemandBaseCapacity
=== RUN   TestAccAutoScalingGroup_MixedInstancesPolicyInstancesDistribution_updateToZeroOnDemandBaseCapacity
=== PAUSE TestAccAutoScalingGroup_MixedInstancesPolicyInstancesDistribution_updateToZeroOnDemandBaseCapacity
=== RUN   TestAccAutoScalingGroup_MixedInstancesPolicyInstancesDistribution_onDemandPercentageAboveBaseCapacity
=== PAUSE TestAccAutoScalingGroup_MixedInstancesPolicyInstancesDistribution_onDemandPercentageAboveBaseCapacity
=== RUN   TestAccAutoScalingGroup_MixedInstancesPolicyInstancesDistribution_spotAllocationStrategy
=== PAUSE TestAccAutoScalingGroup_MixedInstancesPolicyInstancesDistribution_spotAllocationStrategy
=== RUN   TestAccAutoScalingGroup_MixedInstancesPolicyInstancesDistribution_spotInstancePools
=== PAUSE TestAccAutoScalingGroup_MixedInstancesPolicyInstancesDistribution_spotInstancePools
=== RUN   TestAccAutoScalingGroup_MixedInstancesPolicyInstancesDistribution_spotMaxPrice
=== PAUSE TestAccAutoScalingGroup_MixedInstancesPolicyInstancesDistribution_spotMaxPrice
=== RUN   TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateLaunchTemplateSpecification_launchTemplateName
=== PAUSE TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateLaunchTemplateSpecification_launchTemplateName
=== RUN   TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateLaunchTemplateSpecification_version
=== PAUSE TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateLaunchTemplateSpecification_version
=== RUN   TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceType
=== PAUSE TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceType
=== RUN   TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceTypeWithLaunchTemplateSpecification
=== PAUSE TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceTypeWithLaunchTemplateSpecification
=== RUN   TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_weightedCapacity
=== PAUSE TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_weightedCapacity
=== RUN   TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_weightedCapacity_withELB
=== PAUSE TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_weightedCapacity_withELB
=== RUN   TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_memoryMiBAndVCPUCount
=== PAUSE TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_memoryMiBAndVCPUCount
=== RUN   TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_acceleratorCount
=== PAUSE TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_acceleratorCount
=== RUN   TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_acceleratorManufacturers
=== PAUSE TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_acceleratorManufacturers
=== RUN   TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_acceleratorNames
=== PAUSE TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_acceleratorNames
=== RUN   TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_acceleratorTotalMemoryMiB
=== PAUSE TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_acceleratorTotalMemoryMiB
=== RUN   TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_acceleratorTypes
=== PAUSE TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_acceleratorTypes
=== RUN   TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_allowedInstanceTypes
=== PAUSE TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_allowedInstanceTypes
=== RUN   TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_bareMetal
=== PAUSE TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_bareMetal
=== RUN   TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_baselineEBSBandwidthMbps
=== PAUSE TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_baselineEBSBandwidthMbps
=== RUN   TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_burstablePerformance
=== PAUSE TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_burstablePerformance
=== RUN   TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_cpuManufacturers
=== PAUSE TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_cpuManufacturers
=== RUN   TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_excludedInstanceTypes
=== PAUSE TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_excludedInstanceTypes
=== RUN   TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_instanceGenerations
=== PAUSE TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_instanceGenerations
=== RUN   TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_localStorage
=== PAUSE TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_localStorage
=== RUN   TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_localStorageTypes
=== PAUSE TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_localStorageTypes
=== RUN   TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_memoryGiBPerVCPU
=== PAUSE TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_memoryGiBPerVCPU
=== RUN   TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_networkBandwidthGbps
=== PAUSE TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_networkBandwidthGbps
=== RUN   TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_networkInterfaceCount
=== PAUSE TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_networkInterfaceCount
=== RUN   TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_onDemandMaxPricePercentageOverLowestPrice
=== PAUSE TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_onDemandMaxPricePercentageOverLowestPrice
=== RUN   TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_requireHibernateSupport
=== PAUSE TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_requireHibernateSupport
=== RUN   TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_spotMaxPricePercentageOverLowestPrice
=== PAUSE TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_spotMaxPricePercentageOverLowestPrice
=== RUN   TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_totalLocalStorageGB
=== PAUSE TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_totalLocalStorageGB
=== RUN   TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_desiredCapacityTypeUnits
=== PAUSE TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_desiredCapacityTypeUnits
=== RUN   TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_desiredCapacityTypeVCPU
=== PAUSE TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_desiredCapacityTypeVCPU
=== CONT  TestAccAutoScalingGroup_basic
=== CONT  TestAccAutoScalingGroup_mixedInstancesPolicy
--- PASS: TestAccAutoScalingGroup_mixedInstancesPolicy (66.68s)
=== CONT  TestAccAutoScalingGroup_withScalingActivityErrorIncorrectInstanceArchitecture_Recovers
--- PASS: TestAccAutoScalingGroup_basic (67.19s)
=== CONT  TestAccAutoScalingGroup_Destroy_whenProtectedFromScaleIn
--- PASS: TestAccAutoScalingGroup_Destroy_whenProtectedFromScaleIn (175.24s)
=== CONT  TestAccAutoScalingGroup_launchTempPartitionNum
--- PASS: TestAccAutoScalingGroup_launchTempPartitionNum (47.79s)
=== CONT  TestAccAutoScalingGroup_warmPool
--- PASS: TestAccAutoScalingGroup_withScalingActivityErrorIncorrectInstanceArchitecture_Recovers (299.35s)
=== CONT  TestAccAutoScalingGroup_ALBTargetGroups_elbCapacity
--- PASS: TestAccAutoScalingGroup_ALBTargetGroups_elbCapacity (248.64s)
=== CONT  TestAccAutoScalingGroup_targetGroups
--- PASS: TestAccAutoScalingGroup_warmPool (494.75s)
=== CONT  TestAccAutoScalingGroup_loadBalancers
--- PASS: TestAccAutoScalingGroup_targetGroups (175.18s)
=== CONT  TestAccAutoScalingGroup_InstanceRefresh_autoRollback
--- PASS: TestAccAutoScalingGroup_InstanceRefresh_autoRollback (172.47s)
=== CONT  TestAccAutoScalingGroup_InstanceRefresh_triggers
--- PASS: TestAccAutoScalingGroup_InstanceRefresh_triggers (144.08s)
=== CONT  TestAccAutoScalingGroup_InstanceRefresh_start
--- PASS: TestAccAutoScalingGroup_loadBalancers (344.57s)
=== CONT  TestAccAutoScalingGroup_InstanceRefresh_basic
--- PASS: TestAccAutoScalingGroup_InstanceRefresh_start (182.11s)
=== CONT  TestAccAutoScalingGroup_largeDesiredCapacity
--- PASS: TestAccAutoScalingGroup_InstanceRefresh_basic (243.67s)
=== CONT  TestAccAutoScalingGroup_LaunchTemplate_update
--- PASS: TestAccAutoScalingGroup_largeDesiredCapacity (195.00s)
=== CONT  TestAccAutoScalingGroup_launchTemplate
--- PASS: TestAccAutoScalingGroup_launchTemplate (45.90s)
=== CONT  TestAccAutoScalingGroup_initialLifecycleHook
--- PASS: TestAccAutoScalingGroup_LaunchTemplate_update (170.66s)
=== CONT  TestAccAutoScalingGroup_maxInstanceLifetime
--- PASS: TestAccAutoScalingGroup_maxInstanceLifetime (72.66s)
=== CONT  TestAccAutoScalingGroup_serviceLinkedRoleARN
--- PASS: TestAccAutoScalingGroup_serviceLinkedRoleARN (47.35s)
=== CONT  TestAccAutoScalingGroup_suspendingProcesses
--- PASS: TestAccAutoScalingGroup_initialLifecycleHook (227.78s)
=== CONT  TestAccAutoScalingGroup_withMetrics
--- PASS: TestAccAutoScalingGroup_withMetrics (72.37s)
=== CONT  TestAccAutoScalingGroup_enablingMetrics
--- PASS: TestAccAutoScalingGroup_suspendingProcesses (237.52s)
=== CONT  TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_acceleratorTypes
--- PASS: TestAccAutoScalingGroup_enablingMetrics (86.07s)
=== CONT  TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_desiredCapacityTypeVCPU
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_acceleratorTypes (77.41s)
=== CONT  TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_desiredCapacityTypeUnits
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_desiredCapacityTypeVCPU (149.33s)
=== CONT  TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_totalLocalStorageGB
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_desiredCapacityTypeUnits (157.44s)
=== CONT  TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_spotMaxPricePercentageOverLowestPrice
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_totalLocalStorageGB (116.19s)
=== CONT  TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_requireHibernateSupport
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_spotMaxPricePercentageOverLowestPrice (53.83s)
=== CONT  TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_onDemandMaxPricePercentageOverLowestPrice
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_onDemandMaxPricePercentageOverLowestPrice (54.02s)
=== CONT  TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_networkInterfaceCount
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_requireHibernateSupport (74.44s)
=== CONT  TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_networkBandwidthGbps
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_networkInterfaceCount (107.03s)
=== CONT  TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_memoryGiBPerVCPU
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_networkBandwidthGbps (106.90s)
=== CONT  TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_localStorageTypes
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_localStorageTypes (70.42s)
=== CONT  TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_localStorage
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_memoryGiBPerVCPU (117.39s)
=== CONT  TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_instanceGenerations
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_localStorage (104.56s)
=== CONT  TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_excludedInstanceTypes
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_instanceGenerations (85.37s)
=== CONT  TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_cpuManufacturers
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_excludedInstanceTypes (84.00s)
=== CONT  TestAccAutoScalingGroup_WithLoadBalancer_toTargetGroup
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_cpuManufacturers (82.79s)
=== CONT  TestAccAutoScalingGroup_withScalingActivityErrorIncorrectInstanceArchitecture
--- PASS: TestAccAutoScalingGroup_withScalingActivityErrorIncorrectInstanceArchitecture (30.44s)
=== CONT  TestAccAutoScalingGroup_withScalingActivityErrorPlacementGroupNotSupportedOnInstanceType
--- PASS: TestAccAutoScalingGroup_withScalingActivityErrorPlacementGroupNotSupportedOnInstanceType (30.18s)
=== CONT  TestAccAutoScalingGroup_withPlacementGroup
--- PASS: TestAccAutoScalingGroup_withPlacementGroup (133.68s)
=== CONT  TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_burstablePerformance
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_burstablePerformance (110.25s)
=== CONT  TestAccAutoScalingGroup_withTrafficSourceVPCLatticeTargetGroups
--- PASS: TestAccAutoScalingGroup_WithLoadBalancer_toTargetGroup (351.82s)
=== CONT  TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_baselineEBSBandwidthMbps
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_baselineEBSBandwidthMbps (105.19s)
=== CONT  TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_bareMetal
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_bareMetal (106.89s)
=== CONT  TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_allowedInstanceTypes
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_allowedInstanceTypes (75.78s)
=== CONT  TestAccAutoScalingGroup_withTrafficSourceELB_toTargetGroup
--- PASS: TestAccAutoScalingGroup_withTrafficSourceVPCLatticeTargetGroups (369.51s)
=== CONT  TestAccAutoScalingGroup_withTrafficSourceELBV2
--- PASS: TestAccAutoScalingGroup_withTrafficSourceELBV2 (130.18s)
=== CONT  TestAccAutoScalingGroup_withTrafficSourceVPCLatticeTargetGroup
--- PASS: TestAccAutoScalingGroup_withTrafficSourceELB_toTargetGroup (371.28s)
=== CONT  TestAccAutoScalingGroup_tags
--- PASS: TestAccAutoScalingGroup_withTrafficSourceVPCLatticeTargetGroup (247.36s)
=== CONT  TestAccAutoScalingGroup_withTrafficSourcesELBs
--- PASS: TestAccAutoScalingGroup_tags (99.07s)
=== CONT  TestAccAutoScalingGroup_withLoadBalancer
--- PASS: TestAccAutoScalingGroup_withLoadBalancer (212.39s)
=== CONT  TestAccAutoScalingGroup_withTrafficSourceELB
--- PASS: TestAccAutoScalingGroup_withTrafficSourcesELBs (264.73s)
=== CONT  TestAccAutoScalingGroup_vpcUpdates
--- PASS: TestAccAutoScalingGroup_vpcUpdates (77.73s)
=== CONT  TestAccAutoScalingGroup_simple
--- PASS: TestAccAutoScalingGroup_withTrafficSourceELB (235.03s)
=== CONT  TestAccAutoScalingGroup_terminationPolicies
--- PASS: TestAccAutoScalingGroup_simple (189.89s)
=== CONT  TestAccAutoScalingGroup_defaultInstanceWarmup
--- PASS: TestAccAutoScalingGroup_defaultInstanceWarmup (71.36s)
=== CONT  TestAccAutoScalingGroup_namePrefix
--- PASS: TestAccAutoScalingGroup_terminationPolicies (119.57s)
=== CONT  TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateLaunchTemplateSpecification_version
--- PASS: TestAccAutoScalingGroup_namePrefix (52.14s)
=== CONT  TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_weightedCapacity_withELB
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateLaunchTemplateSpecification_version (73.62s)
=== CONT  TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_weightedCapacity
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_weightedCapacity_withELB (178.98s)
=== CONT  TestAccAutoScalingGroup_nameGenerated
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_weightedCapacity (186.98s)
=== CONT  TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceTypeWithLaunchTemplateSpecification
--- PASS: TestAccAutoScalingGroup_nameGenerated (52.59s)
=== CONT  TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceType
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceTypeWithLaunchTemplateSpecification (55.46s)
=== CONT  TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_acceleratorNames
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceType (91.72s)
=== CONT  TestAccAutoScalingGroup_MixedInstancesPolicyInstancesDistribution_onDemandPercentageAboveBaseCapacity
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_acceleratorNames (124.28s)
=== CONT  TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateLaunchTemplateSpecification_launchTemplateName
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyInstancesDistribution_onDemandPercentageAboveBaseCapacity (101.29s)
=== CONT  TestAccAutoScalingGroup_MixedInstancesPolicyInstancesDistribution_spotMaxPrice
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateLaunchTemplateSpecification_launchTemplateName (54.18s)
=== CONT  TestAccAutoScalingGroup_MixedInstancesPolicyInstancesDistribution_spotInstancePools
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyInstancesDistribution_spotInstancePools (74.80s)
=== CONT  TestAccAutoScalingGroup_MixedInstancesPolicyInstancesDistribution_spotAllocationStrategy
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyInstancesDistribution_spotMaxPrice (112.37s)
=== CONT  TestAccAutoScalingGroup_MixedInstancesPolicyInstancesDistribution_onDemandBaseCapacity
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyInstancesDistribution_spotAllocationStrategy (53.26s)
=== CONT  TestAccAutoScalingGroup_MixedInstancesPolicyInstancesDistribution_updateToZeroOnDemandBaseCapacity
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyInstancesDistribution_onDemandBaseCapacity (108.25s)
=== CONT  TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_acceleratorManufacturers
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyInstancesDistribution_updateToZeroOnDemandBaseCapacity (69.22s)
=== CONT  TestAccAutoScalingGroup_MixedInstancesPolicyInstancesDistribution_onDemandAllocationStrategy
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyInstancesDistribution_onDemandAllocationStrategy (54.11s)
=== CONT  TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_acceleratorCount
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_acceleratorManufacturers (85.15s)
=== CONT  TestAccAutoScalingGroup_MixedInstancesPolicy_capacityRebalance
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicy_capacityRebalance (53.37s)
=== CONT  TestAccAutoScalingGroup_disappears
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_acceleratorCount (105.60s)
=== CONT  TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_memoryMiBAndVCPUCount
--- PASS: TestAccAutoScalingGroup_disappears (36.47s)
=== CONT  TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_acceleratorTotalMemoryMiB
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_memoryMiBAndVCPUCount (77.84s)
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceRequirements_acceleratorTotalMemoryMiB (115.57s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/autoscaling	5285.697s
```
