### PR TITLE
resource/aws_athena_workgroup: Unsets parameters when removing `configuration.result_configuration` from config

### LINKED ISSUE #37917: [Bug]: Error when removing Athena workgroup encryption
### Terraform Core Version

1.7.4

### AWS Provider Version

5.35.0

### Affected Resource(s)

aws_athena_workgroup

### Expected Behavior

Removing the configuration.result_configuration.encryption_configuration block from the resource should call the UpdateWorkgroup API setting ResultConfigurationUpdates={RemoveEncryptionConfiguration=true} 

### Actual Behavior

Terraform seems to try to set the encryption configuration to empty values which is not allowes

### Relevant Error/Panic Output Snippet

```shell
When removing the configuration.result_configuration.encryption_configuration block from the resource, terraform fails on the apply stage with the following error:

Error: updating Athena Workgroup (test): operation error Athena: UpdateWorkGroup, 1 validation error(s) found. - missing required field, UpdateWorkGroupInput.Configuration.ResultConfigurationUpdates.EncryptionConfiguration.EncryptionOption
```

### Terraform Configuration Files

```
resource "aws_athena_workgroup" "test" {
  name = "test"
  force_destroy = true

  configuration {
  bytes_scanned_cutoff_per_query     = 107374182400
  enforce_workgroup_configuration    = true
  publish_cloudwatch_metrics_enabled = true
    result_configuration {
    output_location = "s3://..."
      encryption_configuration {
        encryption_option = "SSE_KMS"
        kms_key_arn          = <KMS key resource reference ARN>
      }
    }
  }
}
```

### Steps to Reproduce

1. create an Athena workgroup with encryption
```
resource "aws_athena_workgroup" "test" {
  name = "test"
  force_destroy = true

  configuration {
  bytes_scanned_cutoff_per_query     = 107374182400
  enforce_workgroup_configuration    = true
  publish_cloudwatch_metrics_enabled = true
    result_configuration {
    output_location = "s3://..."
      encryption_configuration {
        encryption_option = "SSE_KMS"
        kms_key_arn          = <KMS key resource reference ARN>
      }
    }
  }
}
```

2. remove the configuration.result_configuration.encryption_configuration block, then apply the terraform plan

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by gdavison**
## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the library.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

### Description

The update API for Athena Workgroups requires setting various `Remove<parameter>` fields when removing a parameter. Updates handling of removing `configuration.result_configuration` or child values.

### Relations

Closes #37917

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccXXX PKG=ec2

...
```

### CODE REVIEW

File: internal/cty/value_ops_test.go [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+
+	tests := map[string]struct {
+		value    cty.Value
+		expected bool
+	}{
+		"NilVal": {
+			value:    cty.NilVal,
+			expected: false,
+		},
+		"EmptyList": {
```
Comment (jar-b) [inline internal/cty/value_ops_test.go:28]: Add a case for a non-empty list?

**Review by jar-b — APPROVED** [review]
LGTM 🚀 

One non-blocking unit test suggestion.

File: internal/cty/path.go [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+
+	if val.IsNull() {
+		return cty.NilVal, false, nil
+	}
+
+	l := len(p)
+	for i, step := range p {
+		val, err = step.Apply(val)
+		if err != nil {
+			return cty.NilVal, false, fmt.Errorf("at step %d: %s", i, err)
```
Comment (YakDriver) [inline internal/cty/path.go]:
```suggestion
			return cty.NilVal, false, fmt.Errorf("at step %d: %w", i, err)
```
