### PR TITLE
fix: cloudwatch_event_archive retention type on creation bug #16067

### LINKED ISSUE #16067: New resource: aws_cloudwatch_event_archive
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Looks like there's now an API to enable long-term archival of eventbridge events which can later be replayed: 

* https://aws.amazon.com/blogs/aws/new-archive-and-replay-events-with-amazon-eventbridge/
* https://aws.amazon.com/about-aws/whats-new/2020/11/amazon-eventbridge-introduces-support-for-event-replay/

```
client.create_archive(
    ArchiveName='string',
    EventSourceArn='string',
    Description='string',
    EventPattern='string',
    RetentionDays=123
)
```

### New or Affected Resource(s)

* aws_cloudwatch_event_archive

### Potential Terraform Configuration

```hcl
resource "aws_cloudwatch_event_bus" "messenger" {
  name = "chat-messages"
}

resource "aws_cloudwatch_event_archive" "archive" {
  archive_name = "archive"

  event_source_arn = aws_cloudwatch_event_bus.messenger.arn

  description = "Archive of chat message events"

  event_pattern = <<EOF
{
  "detail-type": [
    "customerCreated"
  ]
}
EOF

  retention_days = 0
}
```

### References

* https://docs.aws.amazon.com/cli/latest/reference/events/create-archive.html
* https://awsapichanges.info/archive/changes/034487-events.html#CreateArchive

### PR DESCRIPTION
**Pull request by heitorlessa**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

This is a bugfix for the new `cloudwatch_event_archive` resource that when `retention_days` is set on Creation it panics due to an incorrect type (Schema Behaviour [TypeInt] vs SDK expects [Int64]) - Updating `retention_days` after creation was working as expected, though.

New test has been added to cover `retention_days` set on creation.

Relates #16067

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSCloudWatchArchive'      
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSCloudWatchArchive -timeout 120m
=== RUN   TestAccAWSCloudWatchArchive_basic
=== PAUSE TestAccAWSCloudWatchArchive_basic
=== RUN   TestAccAWSCloudWatchArchive_update
=== PAUSE TestAccAWSCloudWatchArchive_update
=== RUN   TestAccAWSCloudWatchArchive_retentionSetOnCreation
=== PAUSE TestAccAWSCloudWatchArchive_retentionSetOnCreation
=== CONT  TestAccAWSCloudWatchArchive_basic
=== CONT  TestAccAWSCloudWatchArchive_retentionSetOnCreation
=== CONT  TestAccAWSCloudWatchArchive_update
--- PASS: TestAccAWSCloudWatchArchive_basic (31.12s)
--- PASS: TestAccAWSCloudWatchArchive_retentionSetOnCreation (31.16s)
--- PASS: TestAccAWSCloudWatchArchive_update (47.00s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       50.163s


...
```

### CODE REVIEW

File: aws/resource_aws_cloudwatch_event_archive.go [hunk 1]
```diff
@@ -166,7 +166,8 @@ func buildCreateArchiveInputStruct(d *schema.ResourceData) (*events.CreateArchiv
 	}
 
 	if v, ok := d.GetOk("retention_days"); ok {
-		input.RetentionDays = aws.Int64(v.(int64))
+		retentionInDays := int64(v.(int))
+		input.RetentionDays = aws.Int64(retentionInDays)
```
Comment (DrFaust92) [inline aws/resource_aws_cloudwatch_event_archive.go:170]: I think we can simplify this to `input.RetentionDays = aws.Int64(v.(int))`

**Review by DrFaust92 — CHANGES_REQUESTED** [review]

File: aws/resource_aws_cloudwatch_event_archive.go (hunk 1 above)
Comment (heitorlessa) [reply aws/resource_aws_cloudwatch_event_archive.go:170]: That doesn't work: `Cannot use 'v.(int)' (type int) as type int64`. I can however do it one line if that's what you prefer: 

```go
input.RetentionDays = aws.Int64(int64(v.(int)))
```

Comment (gdavison) [reply aws/resource_aws_cloudwatch_event_archive.go:170]: We prefer the inline version

**Review by gdavison — CHANGES_REQUESTED** [review]
This looks good, @heitorlessa. We'll need a fix for the `TestAccAWSCloudWatchEventArchive_disappears` error, and then I can be merged.

**Comment by heitorlessa** [comment]
Odd - it wasn’t failing before. I’ll get those fixes in shortly. Thanks for
the review

**Comment by heitorlessa** [comment]
Done @gdavison - Pushed type conversion change to be inline, and corrected `TestAccAWSCloudWatchEventArchive_disappears` to use `testAccAWSCloudWatchArchiveConfig`

**Testacc output**:

```go
make testacc TESTARGS='-run=TestAccAWSCloudWatchArchive'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSCloudWatchArchive -timeout 120m
=== RUN   TestAccAWSCloudWatchArchive_basic
=== PAUSE TestAccAWSCloudWatchArchive_basic
=== RUN   TestAccAWSCloudWatchArchive_update
=== PAUSE TestAccAWSCloudWatchArchive_update
=== RUN   TestAccAWSCloudWatchArchive_retentionSetOnCreation
=== PAUSE TestAccAWSCloudWatchArchive_retentionSetOnCreation
=== CONT  TestAccAWSCloudWatchArchive_basic
=== CONT  TestAccAWSCloudWatchArchive_retentionSetOnCreation
=== CONT  TestAccAWSCloudWatchArchive_update
--- PASS: TestAccAWSCloudWatchArchive_basic (30.82s)
--- PASS: TestAccAWSCloudWatchArchive_retentionSetOnCreation (31.01s)
--- PASS: TestAccAWSCloudWatchArchive_update (47.99s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       50.762s

```

**Comment by bflad** [comment]
The difference here seems to be `TestAccAWSCloudWatchEventArchive` versus `TestAccAWSCloudWatchArchive` -- maybe something that implementing https://github.com/bflad/tfproviderlint/issues/219 can help with in the future. 👍

**Comment by heitorlessa** [comment]
> The difference here seems to be `TestAccAWSCloudWatchEventArchive` versus `TestAccAWSCloudWatchArchive` -- maybe something that implementing [bflad/tfproviderlint#219](https://github.com/bflad/tfproviderlint/issues/219) can help with in the future. 👍

Thanks @bflad, naming convention was the issue, as I blindly copied the initial structure from Event Bus resource - Fixed all occurrences.

`_disappears` testacc is now fixed too - It was missing an additional check on Read as described in this doc: https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/running-and-writing-acceptance-tests.md#disappears-acceptance-tests

PS: I'll take these learnings and make a PR next month for docs to make it easier for inexperienced contributors like me.

```go
make testacc TESTARGS='-run=TestAccAWSCloudWatchEventArchive'           
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSCloudWatchEventArchive -timeout 120m
=== RUN   TestAccAWSCloudWatchEventArchive_basic
=== PAUSE TestAccAWSCloudWatchEventArchive_basic
=== RUN   TestAccAWSCloudWatchEventArchive_update
=== PAUSE TestAccAWSCloudWatchEventArchive_update
=== RUN   TestAccAWSCloudWatchEventArchive_disappears
=== PAUSE TestAccAWSCloudWatchEventArchive_disappears
=== RUN   TestAccAWSCloudWatchEventArchive_retentionSetOnCreation
=== PAUSE TestAccAWSCloudWatchEventArchive_retentionSetOnCreation
=== CONT  TestAccAWSCloudWatchEventArchive_basic
=== CONT  TestAccAWSCloudWatchEventArchive_retentionSetOnCreation
=== CONT  TestAccAWSCloudWatchEventArchive_disappears
=== CONT  TestAccAWSCloudWatchEventArchive_update
--- PASS: TestAccAWSCloudWatchEventArchive_disappears (26.85s)
--- PASS: TestAccAWSCloudWatchEventArchive_retentionSetOnCreation (30.76s)
--- PASS: TestAccAWSCloudWatchEventArchive_basic (30.89s)
--- PASS: TestAccAWSCloudWatchEventArchive_update (47.39s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       50.052s
```

File: aws/resource_aws_cloudwatch_event_archive.go (hunk 1 above)
Comment (DrFaust92) [reply aws/resource_aws_cloudwatch_event_archive.go]: You are right, i mistyped :D

**Review by gdavison — APPROVED** [review]
Looks good 🚀
Acceptance test results in Commercial partition

--- PASS: TestAccAWSCloudWatchEventArchive_disappears (16.67s)
--- PASS: TestAccAWSCloudWatchEventArchive_basic (17.42s)
--- PASS: TestAccAWSCloudWatchEventArchive_retentionSetOnCreation (18.67s)
--- PASS: TestAccAWSCloudWatchEventArchive_update (27.33s)
