### PR TITLE
fix: normalize returned MLflow version

### LINKED ISSUE #42276: aws_sagemaker_mlflow_tracking_server not recognizing patch-versions
### Terraform and AWS Provider Version

```console
Terraform v1.11.4
hashicorp/aws v5.94.1
```

### Affected Resource(s) or Data Source(s)

* `aws_sagemaker_mlflow_tracking_server`

### Expected Behavior

MLflow tracking server should be deployed successfully.

### Actual Behavior

Error is raised

`Error: creating SageMaker AI Mlflow Tracking Server ml-glo-mlflow-dpa-emea: operation error SageMaker: CreateMlflowTrackingServer, https response error StatusCode: 400, RequestID: 593b60d8-bf4b-4584-87a9-b567c04ba730, api error ValidationException: The provided MLflow version is not supported`

### Relevant Error/Panic Output

Setting `mlflow_version = "2.16"` deploys without error, but then on every new `terraform apply` the mlflow tracking server will be recreated as

```
# sagemaker_domain.aws_sagemaker_mlflow_tracking_server.this must be replaced
-/+ resource "aws_sagemaker_mlflow_tracking_server" "this" {
      ~ arn                             = "arn" -> (known after apply)
      ~ id                              = "**********************" -> (known after apply)
      ~ mlflow_version                  = "2.16.2" -> "2.16" # forces replacement
```

So it seems `mlflow_version = "2.16.2"` is somehow written to the state but not accepted as input.

### Sample Terraform Configuration

<details>
<summary>Click to expand configuration</summary>

```hcl
resource "aws_sagemaker_mlflow_tracking_server" "this" {
  tracking_server_name = "example"
  tracking_server_size = "Small"
  mlflow_version       = "2.16.2"
  role_arn             = aws_iam_role.example.arn
  artifact_store_uri   = "s3://${aws_s3_bucket.example.bucket}/path"
}
```
</details>

### Steps to Reproduce

1. Create MLflow tracking server with `mlflow_version = 2.16.2"`
2. See error
3. Create MLflow tracking server with `mlflow_version = 2.16"`
4. Run `terraform apply` again and see mlflow tracking server being destroyed and recreated

### GenAI / LLM Assisted Development

_No response_

### Important Facts and References

_No response_

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by stefanfreitag**
### Description

For the resource `aws_sagemaker_mlflow_tracking_server` there exists  a difference between the MLflow version requested  and reported by AWS API/ SDK. This leads to a constant drift between Terraform code and Terraform state.

This pull request normalizes the MLflow version used Terraform to only major/minor version. 

#### Example

This Terraform code specifies  `2.16` as input for the MLflow version.

```hcl
resource "aws_sagemaker_mlflow_tracking_server" "this" {
  tracking_server_name = "example"
  tracking_server_size = "Small"
  mlflow_version       = "2.16"
  role_arn             = aws_iam_role.example.arn
  artifact_store_uri   = "s3://sf-poc-tf-state-files"
} 
```

A `terraform apply`  will succeed. But checking created resources and state shows that

* a tracking server with MLflow version 2.16.2 is available
* version 2.16.2 also written into the Terraform state.

The debug logs show

* CreateMlflowTrackingServer with "MlflowVersion":"2.16"
* DescribeMlflowTrackingServer with "MlflowVersion":"2.16.2" (called multiple times during resource creation) 

The relevant part of the logs:

```plain
2025-04-23T19:40:39.027+0200 [INFO]  Starting apply for aws_sagemaker_mlflow_tracking_server.this
2025-04-23T19:40:39.027+0200 [DEBUG] aws_sagemaker_mlflow_tracking_server.this: applying the planned Create change
2025-04-23T19:40:39.027+0200 [DEBUG] provider.terraform-provider-aws_v5.95.0_x5: [DEBUG] setting computed for "tags_all" from ComputedKeys

2025-04-23T19:40:39.028+0200 [DEBUG] provider.terraform-provider-aws_v5.95.0_x5: HTTP Request Sent: http.request.header.x_amz_date=20250423T174039Z tf_aws.sdk=aws-sdk-go-v2 @module=aws rpc.method=CreateMlflowTrackingServer
  http.request.body=
  | {"ArtifactStoreUri":"s3://sf-poc-tf-state-files","AutomaticModelRegistration":false,"MlflowVersion":"2.16","RoleArn":"arn:aws:iam::redacted:role/sagemaker-mlflow-tracking-role","TrackingServerName":"example","TrackingServerSize":"Small"}
   http.request.header.amz_sdk_invocation_id=7d1dcfd0-be43-4f78-9056-0532b64258a7 http.user_agent="APN/1.0 HashiCorp/1.0 Terraform/1.11.2 (+https://www.terraform.io) terraform-provider-aws/5.95.0 (+https://registry.terraform.io/providers/hashicorp/aws) aws-sdk-go-v2/1.36.3 ua/2.1 os/linux lang/go#1.23.8 md/GOOS#linux md/GOARCH#amd64 api/sagemaker#1.187.0 m/g" net.peer.name=api.sagemaker.eu-central-1.amazonaws.com @caller=github.com/hashicorp/aws-sdk-go-base/v2@v2.0.0-beta.64/logging/tf_logger.go:45 tf_mux_provider="*schema.GRPCProviderServer" tf_provider_addr=registry.terraform.io/hashicorp/aws tf_rpc=ApplyResourceChange http.request.header.authorization="AWS4-HMAC-SHA256 Credential=AKIA************RU6X/20250423/eu-central-1/sagemaker/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-date;x-amz-target, Signature=*****" rpc.service=SageMaker tf_aws.signing_region="" aws.region=eu-central-1 http.method=POST http.url=https://api.sagemaker.eu-central-1.amazonaws.com/ rpc.system=aws-api http.request.header.content_type=application/x-amz-json-1.1 tf_resource_type=aws_sagemaker_mlflow_tracking_server http.request.header.amz_sdk_request="attempt=1; max=25" http.request.header.x_amz_target=SageMaker.CreateMlflowTrackingServer http.request_content_length=241 tf_req_id=629189b8-afca-c66f-fe8a-cd31c767ec87 timestamp="2025-04-23T19:40:39.028+0200"

2025-04-23T19:40:39.361+0200 [DEBUG] provider.terraform-provider-aws_v5.95.0_x5: HTTP Response Received: tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/aws-sdk-go-base/v2@v2.0.0-beta.64/logging/tf_logger.go:45
  http.response.body=
  | {"TrackingServerArn":"arn:aws:sagemaker:eu-central-1:redacted:mlflow-tracking-server/example"}
   rpc.system=aws-api tf_aws.signing_region="" tf_req_id=629189b8-afca-c66f-fe8a-cd31c767ec87 tf_aws.sdk=aws-sdk-go-v2 aws.region=eu-central-1 http.response.header.date="Wed, 23 Apr 2025 17:40:39 GMT" http.response.header.x_amzn_requestid=65ef0b52-1ceb-48ad-8b9f-fd4c0a1f0987 http.response_content_length=98 http.status_code=200 rpc.method=CreateMlflowTrackingServer tf_provider_addr=registry.terraform.io/hashicorp/aws @module=aws http.duration=332 http.response.header.content_type=application/x-amz-json-1.1 rpc.service=SageMaker tf_mux_provider="*schema.GRPCProviderServer" tf_resource_type=aws_sagemaker_mlflow_tracking_server timestamp="2025-04-23T19:40:39.361+0200"

2025-04-23T19:40:39.361+0200 [DEBUG] provider.terraform-provider-aws_v5.95.0_x5: [DEBUG] Waiting for state to become: [Created]

2025-04-23T19:40:39.362+0200 [DEBUG] provider.terraform-provider-aws_v5.95.0_x5: HTTP Request Sent: http.request.header.x_amz_date=20250423T174039Z rpc.system=aws-api tf_aws.sdk=aws-sdk-go-v2 tf_mux_provider="*schema.GRPCProviderServer" http.method=POST tf_provider_addr=registry.terraform.io/hashicorp/aws @caller=github.com/hashicorp/aws-sdk-go-base/v2@v2.0.0-beta.64/logging/tf_logger.go:45 @module=aws aws.region=eu-central-1
  http.request.body=
  | {"TrackingServerName":"example"}
   http.request.header.amz_sdk_request="attempt=1; max=25" rpc.service=SageMaker tf_resource_type=aws_sagemaker_mlflow_tracking_server tf_rpc=ApplyResourceChange http.request_content_length=32 http.user_agent="APN/1.0 HashiCorp/1.0 Terraform/1.11.2 (+https://www.terraform.io) terraform-provider-aws/5.95.0 (+https://registry.terraform.io/providers/hashicorp/aws) aws-sdk-go-v2/1.36.3 ua/2.1 os/linux lang/go#1.23.8 md/GOOS#linux md/GOARCH#amd64 api/sagemaker#1.187.0 m/g" http.request.header.content_type=application/x-amz-json-1.1 net.peer.name=api.sagemaker.eu-central-1.amazonaws.com tf_aws.signing_region="" http.url=https://api.sagemaker.eu-central-1.amazonaws.com/ rpc.method=DescribeMlflowTrackingServer tf_req_id=629189b8-afca-c66f-fe8a-cd31c767ec87 http.request.header.amz_sdk_invocation_id=ef12f009-c427-4d83-acf0-d26d5ca1b0bd http.request.header.authorization="AWS4-HMAC-SHA256 Credential=AKIA************RU6X/20250423/eu-central-1/sagemaker/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-date;x-amz-target, Signature=*****" http.request.header.x_amz_target=SageMaker.DescribeMlflowTrackingServer timestamp="2025-04-23T19:40:39.361+0200"

2025-04-23T19:40:39.514+0200 [DEBUG] provider.terraform-provider-aws_v5.95.0_x5: HTTP Response Received: http.response.header.date="Wed, 23 Apr 2025 17:40:39 GMT" tf_aws.signing_region="" tf_req_id=629189b8-afca-c66f-fe8a-cd31c767ec87 tf_provider_addr=registry.terraform.io/hashicorp/aws http.duration=152 http.response_content_length=626 http.status_code=200
  http.response.body=
  | {"ArtifactStoreUri":"s3://sf-poc-tf-state-files","AutomaticModelRegistration":false,"CreatedBy":{},"CreationTime":1.745430039172E9,"IsActive":"Inactive","LastModifiedBy":{},"LastModifiedTime":1.745430039172E9,"MlflowVersion":"2.16.2","RoleArn":"arn:aws:iam::redacted:role/sagemaker-mlflow-tracking-role","TrackingServerArn":"arn:aws:sagemaker:eu-central-1:redacted:mlflow-tracking-server/example","TrackingServerName":"example","TrackingServerSize":"Small","TrackingServerStatus":"Creating","TrackingServerUrl":"https://t-1xexqsukyiag.eu-central-1.experiments.sagemaker.aws","WeeklyMaintenanceWindowStart":"Thu:04:17"}
   rpc.service=SageMaker rpc.system=aws-api tf_aws.sdk=aws-sdk-go-v2 @caller=github.com/hashicorp/aws-sdk-go-base/v2@v2.0.0-beta.64/logging/tf_logger.go:45 @module=aws tf_mux_provider="*schema.GRPCProviderServer" tf_rpc=ApplyResourceChange http.response.header.x_amzn_requestid=6d5f7e55-938c-4a7b-850c-d627448858b0 rpc.method=DescribeMlflowTrackingServer tf_resource_type=aws_sagemaker_mlflow_tracking_server aws.region=eu-central-1 http.response.header.content_type=application/x-amz-json-1.1 timestamp="2025-04-23T19:40:39.514+0200"

2025-04-23T19:40:39.715+0200 [DEBUG] provider.terraform-provider-aws_v5.95.0_x5: HTTP Request Sent: tf_req_id=629189b8-afca-c66f-fe8a-cd31c767ec87 tf_rpc=ApplyResourceChange http.request.header.amz_sdk_invocation_id=2767fe44-e859-449b-b47a-4b1fc3a65afe http.request_content_length=32 rpc.system=aws-api tf_aws.sdk=aws-sdk-go-v2 http.request.header.authorization="AWS4-HMAC-SHA256 Credential=AKIA************RU6X/20250423/eu-central-1/sagemaker/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-date;x-amz-target, Signature=*****" http.request.header.x_amz_date=20250423T174039Z http.url=https://api.sagemaker.eu-central-1.amazonaws.com/ rpc.service=SageMaker http.request.header.amz_sdk_request="attempt=1; max=25" http.user_agent="APN/1.0 HashiCorp/1.0 Terraform/1.11.2 (+https://www.terraform.io) terraform-provider-aws/5.95.0 (+https://registry.terraform.io/providers/hashicorp/aws) aws-sdk-go-v2/1.36.3 ua/2.1 os/linux lang/go#1.23.8 md/GOOS#linux md/GOARCH#amd64 api/sagemaker#1.187.0 m/g" aws.region=eu-central-1
  http.request.body=
  | {"TrackingServerName":"example"}
   @caller=github.com/hashicorp/aws-sdk-go-base/v2@v2.0.0-beta.64/logging/tf_logger.go:45 http.request.header.content_type=application/x-amz-json-1.1 tf_provider_addr=registry.terraform.io/hashicorp/aws @module=aws http.method=POST http.request.header.x_amz_target=SageMaker.DescribeMlflowTrackingServer net.peer.name=api.sagemaker.eu-central-1.amazonaws.com tf_resource_type=aws_sagemaker_mlflow_tracking_server rpc.method=DescribeMlflowTrackingServer tf_aws.signing_region="" tf_mux_provider="*schema.GRPCProviderServer" timestamp="2025-04-23T19:40:39.715+0200"
```
#### Other information

I tried to create the resource with major, minor, patch level using the AWS CLI and this seems not to be supported.

```shell
aws sagemaker create-mlflow-tracking-server --tracking-server-name "test" --mlflow-version 2.16.2 --artifact-store-uri s3://<redacted> --role-arn arn:aws:iam::<redacted>:role/<redacted>
```
shows the error

```shell
An error occurred (ValidationException) when calling the CreateMlflowTrackingServer operation: The provided MLflow version is not supported
```

In the AWS Management Console only options for MLflow versions 2.16 and 2.13 are present. A patch level cannot be specified.

### Relations

Closes #42276 

### References

- [Supported MLflow versions](https://docs.aws.amazon.com/sagemaker/latest/dg/mlflow.html)

### Output from Acceptance Testing

```console
❯ make testacc TESTS=TestAccSageMakerMlflowTrackingServer_mlflowVersion PKG=sagemaker
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.8 test ./internal/service/sagemaker/... -v -count 1 -parallel 20 -run='TestAccSageMakerMlflowTrackingServer_mlflowVersion'  -timeout 360m -vet=off
2025/04/30 20:29:33 Initializing Terraform AWS Provider...
=== RUN   TestAccSageMakerMlflowTrackingServer_mlflowVersion
=== PAUSE TestAccSageMakerMlflowTrackingServer_mlflowVersion
=== CONT  TestAccSageMakerMlflowTrackingServer_mlflowVersion
 
--- PASS: TestAccSageMakerMlflowTrackingServer_mlflowVersion (2614.59s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker  2614.737s
```

### CODE REVIEW

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% ACCTEST_TIMEOUT=720m make testacc TESTARGS='-run=TestAccSageMakerMlflowTrackingServer_' PKG=sagemaker ACCTEST_PARALLELISM=3
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.8 test ./internal/service/sagemaker/... -v -count 1 -parallel 3  -run=TestAccSageMakerMlflowTrackingServer_ -timeout 720m -vet=off
2025/05/12 10:06:39 Initializing Terraform AWS Provider...
=== RUN   TestAccSageMakerMlflowTrackingServer_basic
=== PAUSE TestAccSageMakerMlflowTrackingServer_basic
=== RUN   TestAccSageMakerMlflowTrackingServer_mlflowVersion
=== PAUSE TestAccSageMakerMlflowTrackingServer_mlflowVersion
=== RUN   TestAccSageMakerMlflowTrackingServer_tags
=== PAUSE TestAccSageMakerMlflowTrackingServer_tags
=== RUN   TestAccSageMakerMlflowTrackingServer_disappears
=== PAUSE TestAccSageMakerMlflowTrackingServer_disappears
=== CONT  TestAccSageMakerMlflowTrackingServer_basic
=== CONT  TestAccSageMakerMlflowTrackingServer_tags
=== CONT  TestAccSageMakerMlflowTrackingServer_mlflowVersion
--- PASS: TestAccSageMakerMlflowTrackingServer_mlflowVersion (1862.38s)
=== CONT  TestAccSageMakerMlflowTrackingServer_disappears
--- PASS: TestAccSageMakerMlflowTrackingServer_tags (1865.08s)
--- PASS: TestAccSageMakerMlflowTrackingServer_basic (2147.97s)
--- PASS: TestAccSageMakerMlflowTrackingServer_disappears (2067.10s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker	2071.803s
```
```console
% make testacc TESTARGS='-run=TestAccMQBroker_basic\|TestAccMQBroker_normalizedEngineVersion\|TestAccMQBroker_RabbitMQ_normalizedEngineVersion' PKG=mq
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.8 test ./internal/service/mq/... -v -count 1 -parallel 20  -run=TestAccMQBroker_basic\|TestAccMQBroker_normalizedEngineVersion\|TestAccMQBroker_RabbitMQ_normalizedEngineVersion -timeout 360m -vet=off
2025/05/12 14:16:50 Initializing Terraform AWS Provider...
=== RUN   TestAccMQBroker_basic
=== PAUSE TestAccMQBroker_basic
=== RUN   TestAccMQBroker_normalizedEngineVersion
=== PAUSE TestAccMQBroker_normalizedEngineVersion
=== RUN   TestAccMQBroker_RabbitMQ_normalizedEngineVersion
=== PAUSE TestAccMQBroker_RabbitMQ_normalizedEngineVersion
=== CONT  TestAccMQBroker_basic
=== CONT  TestAccMQBroker_RabbitMQ_normalizedEngineVersion
=== CONT  TestAccMQBroker_normalizedEngineVersion
=== NAME  TestAccMQBroker_RabbitMQ_normalizedEngineVersion
    broker_test.go:1310: Step 1/2 error: After applying this test step, the refresh plan was not empty.
        stdout
        
        
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        
        Terraform will perform the following actions:
        
          # aws_mq_broker.test will be updated in-place
          ~ resource "aws_mq_broker" "test" {
                id                            = "b-b86dfbdd-035d-47ff-b020-49d3d89cb02b"
                tags                          = {}
                # (17 unchanged attributes hidden)
        
                # (4 unchanged blocks hidden)
            }
        
        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccMQBroker_RabbitMQ_normalizedEngineVersion (737.76s)
--- PASS: TestAccMQBroker_normalizedEngineVersion (994.63s)
--- PASS: TestAccMQBroker_basic (1019.24s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/mq	1023.897s
FAIL
make: *** [testacc] Error 1
```

Failures is unrelated to this change and is occurring in CI. See https://github.com/hashicorp/terraform-provider-aws/issues/39317.

**Comment by stefanfreitag** [comment]
@ewbankkit Thank you for the refactoring, much appreciated!

File: internal/service/mq/broker_test.go [hunk 1]
```diff
@@ -1119,6 +1119,7 @@ func TestAccMQBroker_Update_securityGroup(t *testing.T) {
 	})
 }
 
+/*
```
Comment (jar-b) [inline internal/service/mq/broker_test.go:1122]: Can this be removed entirely? Or will it be re-enabled at some point in the future?

**Review by jar-b — APPROVED** [review]
LGTM 🚀

File: internal/service/mq/broker_test.go (hunk 1 above)
Comment (ewbankkit) [reply internal/service/mq/broker_test.go:1122]: I'm going to leave it in as it would be nice to test the functionality if the versions line up in the future.

**Comment by ewbankkit** [comment]
@stefanfreitag Thanks for the contribution :tada: :clap:.
