### PR TITLE
Resolves issue while creating DynamoDB items

### LINKED ISSUE #10385: aws_dynamodb_table_item does not work if one of the field contains a hyphen
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.14
+ provider.aws v2.31.0

### Affected Resource(s)

* aws_dynamodb_table_item

### Terraform Configuration Files

```hcl
resource "aws_dynamodb_table" "dynamodb_table" {
  name            = "test-table"
  hash_key        = "name"

  billing_mode    = "PAY_PER_REQUEST"

  attribute {
    name = "name"
    type = "S"
  }
}

resource "aws_dynamodb_table_item" "item" {
  table_name = "${aws_dynamodb_table.dynamodb_table.name}"
  hash_key   = "${aws_dynamodb_table.dynamodb_table.hash_key}"

  item = <<ITEM
{
  "name":     {"S": "main"},
  "label":    {"S": "Main"}
}
ITEM
}

resource "aws_dynamodb_table_item" "item_2" {
  table_name = "${aws_dynamodb_table.dynamodb_table.name}"
  hash_key   = "${aws_dynamodb_table.dynamodb_table.hash_key}"

  item = <<ITEM
{
  "label-fail":    {"S": "Main"},
  "name":     {"S": "main2"}
}
ITEM
}
```

### Debug Output

https://gist.github.com/thelo-gaultier/d540ff24beebadca969d9db454ca8f4d

### Expected Behavior

the `item_2`should be created successfully

### Actual Behavior

Terraform throw this exception
```
Error: Error applying plan:

1 error occurred:
	* aws_dynamodb_table_item.item_2: 1 error occurred:
	* aws_dynamodb_table_item.item_2: Error retrieving DynamoDB table item: ValidationException: ExpressionAttributeNames contains invalid key: Syntax error; key: "#a_label-fail"
	status code: 400, request id: R9OU92P3E8G8G0GRT7954PSSGJVV4KQNSO5AEMVJF66Q9ASUAAJG
```
### Steps to Reproduce

1. `terraform apply`

### References

Dynamo offers [expression projection](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.ExpressionAttributeNames.html) to solve this problem, however this does not seem to be available in the current terraform provider [documentation](https://www.terraform.io/docs/providers/aws/r/dynamodb_table_item.html)

### PR DESCRIPTION
**Pull request by edwardofclt**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #10385

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
Resolves issue while creating items in DynamoDB table when the keys created aren't alphanumeric
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -count 1 -parallel 20 -run=TestAccXXX -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	2.594s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/flatmap	0.409s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/keyvaluetags	0.792s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/naming	1.619s [no tests to run]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/apigatewayv2/waiter	[no test files]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/batch/equivalency	0.373s [no tests to run]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/ec2/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/ecs/waiter	[no test files]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/eks/token	0.343s [no tests to run]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/guardduty/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/iam/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/kinesisanalytics/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/kms/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/neptune/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/rds/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/secretsmanager/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/servicediscovery/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/sfn/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/workspaces/waiter	[no test files]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/tfawsresource	1.022s [no tests to run]
?   	github.com/terraform-providers/terraform-provider-aws/awsproviderlint	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/helper/awsprovidertype/keyvaluetags	[no test files]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes	2.115s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/AWSAT001	2.212s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/AWSAT002	0.326s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/AWSR001	0.412s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/AWSR002	2.086s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/fmtsprintfcallexpr	0.248s [no tests to run]
```

### CODE REVIEW

**Comment by edwardofclt** [comment]
Bump

**Comment by edwardofclt** [comment]
Bumping again.

**Comment by abased** [comment]
what would it take to get this pushed and versioned! my tables have "." in their keys

**Comment by yermulnik** [comment]
@edwardofclt Thanks for this PR, I'm really looking forward for it to be merged into TF Provider AWS. Could you please take a look into resolving conflicts (so that it's not an obstacle once Provider maintainers get to this PR). Thank you.

File: aws/resource_aws_dynamodb_table_item.go [hunk 1]
```diff
@@ -224,18 +225,30 @@ func resourceAwsDynamoDbTableItemDelete(d *schema.ResourceData, meta interface{}
...
-		names["#a_"+key] = aws.String(key)
+		names["#a_"+cleanDynamoDbKeyName(key)] = aws.String(key)
 	}
 
+	log.Printf("[DEBUG] ExpressionAttributeNames: %+v", names)
 	return names
 }
 
+func cleanDynamoDbKeyName(key string) string {
+	reg, err := regexp.Compile("[^a-zA-Z]+")
```
Comment (yermulnik) [inline aws/resource_aws_dynamodb_table_item.go:238]: I couldn't find what is the exact constraint for the key name. Is it sort of "the key name must start with alpha char only" (rather than "alphanumeric")? If yes, could you please point me in the right direction in the AWS DynamoDB documentation? Thanks.

**Review by YakDriver — APPROVED** [review]
Thank you 🎉 

```console
% make testacc TESTS=TestAccDynamoDBTableItem PKG=dynamodb 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/dynamodb/... -v -count 1 -parallel 20 -run='TestAccDynamoDBTableItem'  -timeout 180m
--- PASS: TestAccDynamoDBTableItem_wonkyItems (25.03s)
--- PASS: TestAccDynamoDBTableItem_withMultipleItems (25.12s)
--- PASS: TestAccDynamoDBTableItem_rangeKey (26.64s)
--- PASS: TestAccDynamoDBTableItem_basic (26.82s)
--- PASS: TestAccDynamoDBTableItem_updateWithRangeKey (36.22s)
--- PASS: TestAccDynamoDBTableItem_update (39.42s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/dynamodb	40.690s
```
