### PR TITLE
r/internet_gateway_attachment - new resource

### LINKED ISSUE #9101: internet gateway was not able to destroy with HELM release aws-alb-ingress-controller
_This issue was originally opened by @SubhakarKotta as hashicorp/terraform#21850. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version
0.12
### Terraform Configuration Files
My application uses the below load balancer creates through HELM Release which was an dependent application
https://github.com/kubernetes-sigs/aws-alb-ingress-controller

So when we deploy the application through helm it internally creates an loadbalancer.

When I destroy the application it was not able to cleanup the newly created loadbalancer and hence the internet gateway was not able to destroy and hence the VPC also was not able to destroy

**_

> Error: Error waiting for internet gateway (igw-0c37628c5687d2d50) to detach: timeout while waiting for state to become 'detached' (last state: 'detaching', timeout: 15m0s)

_**

module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 4m20s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 10s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 4m30s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 20s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 4m40s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 30s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 4m50s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 40s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 5m0s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 50s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 5m10s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 1m0s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 5m20s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 1m10s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 5m30s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 1m20s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 5m40s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 1m30s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 5m50s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 1m40s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 6m0s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 1m50s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 6m10s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 2m0s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 6m20s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 2m10s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 6m30s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 2m20s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 6m40s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 2m30s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 6m50s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 2m40s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 7m0s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 2m50s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 7m10s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 3m0s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 7m20s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 3m10s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 7m30s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 3m20s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 7m40s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 3m30s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 7m50s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 3m40s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 8m0s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 3m50s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 8m10s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 4m0s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 8m20s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 4m10s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 8m30s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 4m20s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 8m40s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 4m30s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 8m50s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 4m40s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 9m0s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 4m50s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 9m10s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 5m0s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 9m20s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 5m10s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 9m30s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 5m20s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 9m40s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 5m30s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 9m50s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 5m40s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 10m0s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 5m50s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 10m10s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 6m0s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 10m20s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 6m10s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 10m30s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 6m20s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 10m40s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 6m30s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 10m50s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 6m40s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 11m0s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 6m50s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 11m10s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 7m0s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 11m20s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 7m10s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 11m30s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 7m20s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 11m40s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 7m30s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 11m50s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 7m40s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 12m0s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 7m50s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 12m10s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 8m0s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 12m20s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 8m10s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 12m30s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 8m20s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 12m40s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 8m30s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 12m50s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 8m40s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 13m0s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 8m50s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 13m10s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 9m0s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 13m20s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 9m10s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 13m30s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 9m20s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 13m40s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 9m30s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 13m50s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 9m40s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 14m0s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 9m50s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 14m10s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 10m0s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 14m20s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 10m10s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 14m30s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 10m20s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 14m40s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 10m30s elapsed]
module.vpc.aws_internet_gateway.this[0]: Still destroying... [id=igw-0c37628c5687d2d50, 14m50s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 10m40s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 10m50s elapsed]
module.cluster.aws_eks_cluster.this: Still destroying... [id=subhakar-demo-cluster, 11m0s elapsed]

### LINKED ISSUE #13742: Create aws_internet_gateway_attachment resource, update aws_internet_gateway
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Internet gateways do not require a vpc ID to create them in the API/SDK however they do in the Terraform AWS provider currently, and they do not behave correctly when the underlying vpc gets recreated (they must be manually detached before the VPC can be destroyed).

I propose we fix this with the following changes:

1. Create a new resource `aws_internet_gateway_attachment` that will appropriately destroy itself when its underlying vpc id changes.
2. Make the vpc_id optional for `aws_internet_gateway` and deprecate the use of vpc_id with that resource.

### New or Affected Resource(s)

* aws_internet_gateway_attachment
* aws_internet_gateway

### Potential Terraform Configuration

```hcl
resource "aws_vpc" "vpc" {
...
}

resource "aws_internet_gateway" "igw" {
  tags = {
    ...
  }
}

resource "aws_internet_gateway_attachment" "igw_attach" {
  vpc_id              = aws_vpc.vpc.id
  internet_gateway_id = aws_internet_gateway.igw.id
}

```

### LINKED ISSUE #16151: If VPC is replaced IGW must be force replaced aswell.
## Terraform CLI and Terraform AWS Provider Version

terraform -v
Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/aws v3.8.0
+ provider registry.terraform.io/hashicorp/local v1.4.0
+ provider registry.terraform.io/hashicorp/tls v2.2.0

Your version of Terraform is out of date! The latest version
is 0.13.5. You can update by downloading from https://www.terraform.io/downloads.html

### Terraform Configuration Files

Module
```hcl
resource "aws_vpc" "vpc" {
  cidr_block           = var.main_vpc_cidr
  enable_dns_hostnames = true
  enable_dns_support   = true
}

resource "aws_vpc_ipv4_cidr_block_association" "secondary_cidr" {
  vpc_id     = aws_vpc.vpc.id
  cidr_block = var.secondary_cidr
}

resource "aws_internet_gateway" "this" {
  vpc_id = aws_vpc.vpc.id
  depends_on = [aws_vpc.vpc]
}

resource "aws_subnet" "this" {
  count                   = length(var.secondary_cidr_subnets)
  vpc_id                  = aws_vpc.vpc.id
  cidr_block              = var.secondary_cidr_subnets[count.index]
  availability_zone       = var.availability_zones[count.index]
  map_public_ip_on_launch = true
}


resource "aws_route_table" "rt" {
  vpc_id = aws_vpc.vpc.id
  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = aws_internet_gateway.this.id
  }
}

resource "aws_route_table_association" "secondary_subnets" {
  count          = length(var.secondary_cidr_subnets)
  subnet_id      = aws_subnet.this[count.index].id
  route_table_id = aws_route_table.rt[count.index].id
}

```

resource:

```hcl
module "vpc" {
  source = "../modules/vpc"
  main_vpc_cidr = "10.0.0.0/24"
  secondary_cidr = "10.0.0.0/24"
  secondary_cidr_subnets = ["10.0.0.0/28", "10.0.0.1/28", "10.0.0.1/28"]
  availability_zones = ["eu-central-1a","eu-central-1b","eu-central-1c"]
  account_name = var.account_name
}

```
### Expected Behavior

- IGW destroyed.
- VPC destroyed
- VPC recreated
- IGW recreated

### Actual Behavior

IGW should be destroyed first then VPC. 
IGW is updated in place hence VPC destroy keep waiting.

Here is the output. As you see the IGW is updated-inplace whereas VPC needs to be replaced. So the VPC will continuously
be in a "still destroying" state. 

IGW needs to be destroyed first.

```
 # module.vpc.aws_internet_gateway.this **will be updated in-place**
  ~ resource "aws_internet_gateway" "this" {
        arn      = "arn:aws:ec2:xxxxxxxxxxxxxxxxf"
        id       = "igw-089d6c28c28ba629f"
        owner_id = "xxxxxxxxxxxxx"
      ~ vpc_id   = "vpc-04ed4302047097b33" -> (known after apply)
    }
 # module.vpc.aws_vpc.centralnet_vpc must be replaced
-/+ resource "aws_vpc" "centralnet_vpc" {
      ~ arn                              = "arn:aws:ec2:xxxxxxxxxxxxxxxxxxxxxxx" -> (known after apply)
        assign_generated_ipv6_cidr_block = false
      ~ cidr_block                       = "10.80.16.0/20" -> "10.0.0.0/24" # forces replacement
      ~ default_network_acl_id           = "acl-06bb7e3a39bc08cb2" -> (known after apply)
      ~ default_route_table_id           = "rtb-045638bffd44824de" -> (known after apply)
      ~ default_security_group_id        = "sg-04c1dbea606ccf0dd" -> (known after apply)
      ~ dhcp_options_id                  = "dopt-93ea2af9" -> (known after apply)
      + enable_classiclink               = (known after apply)
      + enable_classiclink_dns_support   = (known after apply)
        enable_dns_hostnames             = true
        enable_dns_support               = true
      ~ id                               = "vpc-04ed4302047097b33" -> (known after apply)
        instance_tenancy                 = "default"
      + ipv6_association_id              = (known after apply)
      + ipv6_cidr_block                  = (known after apply)
      ~ main_route_table_id              = "rtb-045638bffd44824de" -> (known after apply)
      ~ owner_id                         = "xxxxxxxxxxxxxxxxxxxx" -> (known after apply)
    }

```

### Steps to Reproduce

Use the above resource and module and then:

1. `terraform apply`

### PR DESCRIPTION
**Pull request by DrFaust92**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #16151
Closes #13742
Closes #9101

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

Output from acceptance testing:

```
$ make testacc TESTS=TestAccEC2InternetGatewayAttachment_ PKG=ec2
--- PASS: TestAccEC2InternetGatewayAttachment_disappears (34.04s)
--- PASS: TestAccEC2InternetGatewayAttachment_basic (63.16s)
```

### CODE REVIEW

File: aws/internal/service/ec2/errors.go [hunk 1]
```diff
@@ -20,3 +20,7 @@ const (
 	InvalidVpnGatewayAttachmentNotFound = "InvalidVpnGatewayAttachment.NotFound"
 	InvalidVpnGatewayIDNotFound         = "InvalidVpnGatewayID.NotFound"
 )
+
+const (
+	ErrCodeInternetGatewayIDNotFound = "InvalidInternetGatewayID.NotFound"
```
Comment (ewbankkit) [inline aws/internal/service/ec2/errors.go:25]: I think the guidance is to match the underlying AWS error code.

```suggestion
	ErrCodeInvalidInternetGatewayIDNotFound = "InvalidInternetGatewayID.NotFound"
```

File: aws/internal/service/ec2/finder/finder.go [hunk 2]
```diff
@@ -55,6 +55,19 @@ func ClientVpnRouteByID(conn *ec2.EC2, routeID string) (*ec2.DescribeClientVpnRo
 	return ClientVpnRoute(conn, endpointID, targetSubnetID, destinationCidr)
 }
 
+func InternetGatewayAttachmentByID(conn *ec2.EC2, igwID, vpcID string) (*ec2.DescribeInternetGatewaysOutput, error) {
```
Comment (ewbankkit) [inline aws/internal/service/ec2/finder/finder.go:58]: I would have this return the actual attachment (or `nil`) and deal with all the

```go
if result == nil || len(result.InternetGateways) == 0 || result.InternetGateways[0] == nil {
}
```

logic here rather than in the `Status` function.

```suggestion
func InternetGatewayAttachment(conn *ec2.EC2, igwID, vpcID string) (*ec2.InternetGatewayAttachment, error) {
```

File: aws/internal/service/ec2/waiter/waiter.go [hunk 3]
```diff
@@ -183,6 +183,50 @@ func ClientVpnRouteDeleted(conn *ec2.EC2, routeID string) (*ec2.ClientVpnRoute,
 	return nil, err
 }
 
+const (
+	InternetGatewayAttchmentStatusAvailable       = "available"
+	InternetGatewayAttchmentCreatedTimeout        = 4 * time.Minute
+	InternetGatewayAttchmentDeletedTimeout        = 15 * time.Minute
+	InternetGatewayAttchmentDeletedDelay          = 10 * time.Second
+	InternetGatewayAttchmentDeletedNotFoundChecks = 30
```
Comment (ewbankkit) [inline aws/internal/service/ec2/waiter/waiter.go:191]:
```suggestion
	InternetGatewayAttachmentStatusAvailable       = "available"
	InternetGatewayAttachmentCreatedTimeout        = 4 * time.Minute
	InternetGatewayAttachmentDeletedTimeout        = 15 * time.Minute
	InternetGatewayAttachmentDeletedDelay          = 10 * time.Second
	InternetGatewayAttachmentDeletedNotFoundChecks = 30
```

File: aws/internal/service/ec2/waiter/waiter.go [hunk 4]
```diff
@@ -183,6 +183,50 @@ func ClientVpnRouteDeleted(conn *ec2.EC2, routeID string) (*ec2.ClientVpnRoute,
...
+)
+
+func InternetGatewayAttchmentCreated(conn *ec2.EC2, igwID, vpcID string) (*ec2.InternetGatewayAttachment, error) {
```
Comment (ewbankkit) [inline aws/internal/service/ec2/waiter/waiter.go:194]:
```suggestion
func InternetGatewayAttachmentCreated(conn *ec2.EC2, igwID, vpcID string) (*ec2.InternetGatewayAttachment, error) {
```

File: aws/internal/service/ec2/waiter/waiter.go [hunk 5]
```diff
@@ -183,6 +183,50 @@ func ClientVpnRouteDeleted(conn *ec2.EC2, routeID string) (*ec2.ClientVpnRoute,
...
+	stateConf := &resource.StateChangeConf{
+		Pending: []string{ec2.AttachmentStatusDetached, ec2.AttachmentStatusAttaching},
+		Target:  []string{InternetGatewayAttchmentStatusAvailable},
```
Comment (ewbankkit) [inline aws/internal/service/ec2/waiter/waiter.go:197]:
```suggestion
		Target:  []string{InternetGatewayAttachmentStatusAvailable},
```

File: aws/internal/service/ec2/waiter/waiter.go [hunk 6]
```diff
@@ -183,6 +183,50 @@ func ClientVpnRouteDeleted(conn *ec2.EC2, routeID string) (*ec2.ClientVpnRoute,
...
+		Refresh: InternetGatewayAttachmentStatus(conn, igwID, vpcID),
+		Timeout: InternetGatewayAttchmentCreatedTimeout,
```
Comment (ewbankkit) [inline aws/internal/service/ec2/waiter/waiter.go:199]:
```suggestion
		Timeout: InternetGatewayAttachmentCreatedTimeout,
```

File: aws/internal/service/ec2/waiter/waiter.go [hunk 7]
```diff
@@ -183,6 +183,50 @@ func ClientVpnRouteDeleted(conn *ec2.EC2, routeID string) (*ec2.ClientVpnRoute,
...
+	outputRaw, err := stateConf.WaitForState()
+
+	if output, ok := outputRaw.(*ec2.InternetGatewayAttachment); ok {
+		return output, err
+	}
+
+	return nil, err
+}
+
+func InternetGatewayAttchmentDeleted(conn *ec2.EC2, igwID, vpcID string) (*ec2.InternetGatewayAttachment, error) {
```
Comment (ewbankkit) [inline aws/internal/service/ec2/waiter/waiter.go:211]:
```suggestion
func InternetGatewayAttachmentDeleted(conn *ec2.EC2, igwID, vpcID string) (*ec2.InternetGatewayAttachment, error) {
```

File: aws/internal/service/ec2/waiter/waiter.go [hunk 8]
```diff
@@ -183,6 +183,50 @@ func ClientVpnRouteDeleted(conn *ec2.EC2, routeID string) (*ec2.ClientVpnRoute,
...
+	stateConf := &resource.StateChangeConf{
+		Pending:        []string{ec2.AttachmentStatusDetaching},
+		Target:         []string{},
+		Refresh:        InternetGatewayAttachmentStatus(conn, igwID, vpcID),
+		Timeout:        InternetGatewayAttchmentDeletedTimeout,
+		Delay:          InternetGatewayAttchmentDeletedDelay,
+		NotFoundChecks: InternetGatewayAttchmentDeletedNotFoundChecks,
```
Comment (ewbankkit) [inline aws/internal/service/ec2/waiter/waiter.go:218]:
```suggestion
		Timeout:        InternetGatewayAttachmentDeletedTimeout,
		Delay:          InternetGatewayAttachmentDeletedDelay,
		NotFoundChecks: InternetGatewayAttachmentDeletedNotFoundChecks,
```

File: aws/resource_aws_internet_gateway_attachment.go [hunk 9]
```diff
@@ -0,0 +1,182 @@
...
+	}
+	if err != nil {
+		return fmt.Errorf("Error creating Internet Gateway attachment: %w", err)
+	}
+
+	d.SetId(fmt.Sprintf("%s:%s", vpcID, igwID))
+
+	_, err = waiter.InternetGatewayAttchmentCreated(conn, igwID, vpcID)
+	if err != nil {
+		return fmt.Errorf("error waiting for Internet Gateway attachmen %q to be created: %w", d.Id(), err)
```
Comment (ewbankkit) [inline aws/resource_aws_internet_gateway_attachment.go:77]:
```suggestion
		return fmt.Errorf("error waiting for Internet Gateway attachment %q to be created: %w", d.Id(), err)
```

File: aws/resource_aws_internet_gateway_attachment.go [hunk 10]
```diff
@@ -0,0 +1,182 @@
...
+	if isResourceTimeoutError(err) {
+		_, err = conn.AttachInternetGateway(input)
+	}
+	if err != nil {
+		return fmt.Errorf("Error creating Internet Gateway attachment: %w", err)
+	}
+
+	d.SetId(fmt.Sprintf("%s:%s", vpcID, igwID))
+
+	_, err = waiter.InternetGatewayAttchmentCreated(conn, igwID, vpcID)
```
Comment (ewbankkit) [inline aws/resource_aws_internet_gateway_attachment.go:75]:
```suggestion
	_, err = waiter.InternetGatewayAttachmentCreated(conn, igwID, vpcID)
```

File: aws/resource_aws_internet_gateway_attachment.go [hunk 11]
```diff
@@ -0,0 +1,182 @@
...
+		return resource.NonRetryableError(err)
+	})
+	if isResourceTimeoutError(err) {
+		_, err = conn.AttachInternetGateway(input)
+	}
+	if err != nil {
+		return fmt.Errorf("Error creating Internet Gateway attachment: %w", err)
+	}
+
+	d.SetId(fmt.Sprintf("%s:%s", vpcID, igwID))
```
Comment (ewbankkit) [inline aws/resource_aws_internet_gateway_attachment.go:73]: Add `InternetGatewayCreateID` in https://github.com/hashicorp/terraform-provider-aws/blob/master/aws/internal/service/ec2/id.go.

Comment (DrFaust92) [reply aws/resource_aws_internet_gateway_attachment.go:73]: done

File: aws/resource_aws_internet_gateway_attachment.go [hunk 12]
```diff
@@ -0,0 +1,182 @@
...
+
+func decodeInternetGatewayAttachmentID(id string) (string, string, error) {
+	parts := strings.Split(id, ":")
+
+	if len(parts) != 2 {
+		return "", "", fmt.Errorf("Unexpected format of ID (%q), expected VPC-ID:IGW-ID", id)
+	}
+
+	return parts[0], parts[1], nil
+}
```
[the remark this answers is not in the document]
Comment (DrFaust92) [reply aws/resource_aws_internet_gateway_attachment.go]: done

**Comment by DrFaust92** [comment]
Thanks @ewbankkit, Addressed comments!

**Comment by DrFaust92** [comment]
rebased 

```
--- PASS: TestAccAWSInternetGatewayAttachment_disappears (66.59s)
--- PASS: TestAccAWSInternetGatewayAttachment_basic (101.28s)
```

**Comment by zhelding** [comment]
Pull request #21306 has significantly refactored the AWS Provider codebase. As a result, most PRs opened prior to the refactor now have merge conflicts that must be resolved before proceeding.

Specifically, PR #21306 relocated the code for all AWS resources and data sources from a single `aws` directory to a large number of separate directories in `internal/service`, each corresponding to a particular AWS service. This separation of code has also allowed for us to simplify the names of underlying functions -- while still avoiding namespace collisions.

We recognize that many pull requests have been open for some time without yet being addressed by our maintainers. Therefore, we want to make it clear that resolving these conflicts _in no way affects the prioritization_ of a particular pull request. Once a pull request has been prioritized for review, the necessary changes will be made by a maintainer -- either directly or in collaboration with the pull request author.

For a more complete description of this refactor, including examples of how old filepaths and function names correspond to their new counterparts: please refer to issue #20000.

For a quick guide on how to amend your pull request to resolve the merge conflicts resulting from this refactor and bring it in line with our new code patterns: please refer to our [Service Package Refactor Pull Request Guide](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/service-package-pullrequest-guide.md).

**Comment by ewbankkit** [comment]
@DrFaust92 Thanks for the contribution :tada: :clap:.
I changed the `vpc_id` argument to `ForceNew: true` to match the `aws_vpn_gateway_attachment` resource and other similar resources.
This simplified both the resource implementation (no `Update` required) and acceptance tests.
