### PR TITLE
fix(aws_bedrockagentcore_gateway): config for AWS_IAM authorizer type

### LINKED ISSUE #44825: r/aws_bedrockagentcore_gateway: invalid config possible with authorizer_configuration and authorizer type
### Terraform and AWS Provider Version

```console
❯ terraform --version
Terraform v1.13.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v6.18.0
```

### Affected Resource(s) or Data Source(s)

* `aws_bedrockagentcore_gateway`

### Expected Behavior

Invalid configs are validated and rejected ahead of AWS API requests.

### Actual Behavior

Invalid config results in AWS API request error

### Relevant Error/Panic Output

Error: creating Bedrock AgentCore Gateway

          with aws_bedrockagentcore_gateway.test,
          on terraform_plugin_test.tf line 28, in resource "aws_bedrockagentcore_gateway" "test":
          28: resource "aws_bedrockagentcore_gateway" "test" {

        ID: "tf-acc-test-1398200240711417058"
        Cause: operation error Bedrock AgentCore Control: CreateGateway, ,
        ValidationException: AuthorizerConfiguration is required for CUSTOM_JWT
        authorizer type"

### Sample Terraform Configuration

<details open>
<summary>Click to expand configuration</summary>

```hcl
resource "aws_bedrockagentcore_gateway" "test" {
  name     = "example"
  role_arn = aws_iam_role.test.arn

  authorizer_type = "CUSTOM_JWT"
  protocol_type   = "MCP"
}
```
</details>

### Steps to Reproduce

1. Apply the above configuration
2. See it fail with:

Error: creating Bedrock AgentCore Gateway

          with aws_bedrockagentcore_gateway.test,
          on terraform_plugin_test.tf line 28, in resource "aws_bedrockagentcore_gateway" "test":
          28: resource "aws_bedrockagentcore_gateway" "test" {

        ID: "tf-acc-test-1398200240711417058"
        Cause: operation error Bedrock AgentCore Control: CreateGateway, ,
        ValidationException: AuthorizerConfiguration is required for CUSTOM_JWT
        authorizer type"

### Debug Logging

_No response_

### GenAI / LLM Assisted Development

n/a

### Important Facts and References

_No response_

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by marcinbelczewski**
## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the library.

## Changes to Security Controls

None

### Description

PR allows provisioning AWS_IAM protected AgentCore Gateways.

### Relations

Closes #44825

### References

[CreateGateway API Request](https://docs.aws.amazon.com/bedrock-agentcore-control/latest/APIReference/API_CreateGateway.html#bedrockagentcorecontrol-CreateGateway-request-authorizerConfiguration)

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccBedrockAgentCoreGateway PKG=bedrockagentcore

make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 b-aws-iam-protected-gateway 🌿...
TF_ACC=1 go1.24.8 test ./internal/service/bedrockagentcore/... -v -count 1 -parallel 20 -run='TestAccBedrockAgentCoreGateway_'  -timeout 360m -vet=off
2025/10/27 17:40:57 Creating Terraform AWS Provider (SDKv2-style)...
2025/10/27 17:40:57 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccBedrockAgentCoreGateway_basic
=== PAUSE TestAccBedrockAgentCoreGateway_basic
=== RUN   TestAccBedrockAgentCoreGateway_disappears
=== PAUSE TestAccBedrockAgentCoreGateway_disappears
=== RUN   TestAccBedrockAgentCoreGateway_tags
=== PAUSE TestAccBedrockAgentCoreGateway_tags
=== RUN   TestAccBedrockAgentCoreGateway_description
=== PAUSE TestAccBedrockAgentCoreGateway_description
=== RUN   TestAccBedrockAgentCoreGateway_kmsKey
    gateway_test.go:242: KMS key returns HTTP 500
--- SKIP: TestAccBedrockAgentCoreGateway_kmsKey (0.00s)
=== RUN   TestAccBedrockAgentCoreGateway_protocolConfiguration
=== PAUSE TestAccBedrockAgentCoreGateway_protocolConfiguration
=== RUN   TestAccBedrockAgentCoreGateway_awsIamAuthorizer
=== PAUSE TestAccBedrockAgentCoreGateway_awsIamAuthorizer
=== CONT  TestAccBedrockAgentCoreGateway_basic
=== CONT  TestAccBedrockAgentCoreGateway_description
=== CONT  TestAccBedrockAgentCoreGateway_awsIamAuthorizer
=== CONT  TestAccBedrockAgentCoreGateway_protocolConfiguration
=== CONT  TestAccBedrockAgentCoreGateway_tags
=== CONT  TestAccBedrockAgentCoreGateway_disappears
--- PASS: TestAccBedrockAgentCoreGateway_disappears (23.55s)
--- PASS: TestAccBedrockAgentCoreGateway_awsIamAuthorizer (26.30s)
--- PASS: TestAccBedrockAgentCoreGateway_basic (26.99s)
--- PASS: TestAccBedrockAgentCoreGateway_protocolConfiguration (40.02s)
--- PASS: TestAccBedrockAgentCoreGateway_description (40.67s)
--- PASS: TestAccBedrockAgentCoreGateway_tags (52.21s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/bedrockagentcore	59.690s
```

### CODE REVIEW

File: internal/service/bedrockagentcore/gateway.go [hunk 1]
```diff
@@ -187,6 +185,24 @@ func (r *gatewayResource) Schema(ctx context.Context, request resource.SchemaReq
 	}
 }
 
+func (r *gatewayResource) ValidateConfig(ctx context.Context, req resource.ValidateConfigRequest, resp *resource.ValidateConfigResponse) {
```
Comment (jar-b) [inline internal/service/bedrockagentcore/gateway.go:191]: While #44812 resolves the linked issue, this config validator would still be worth adding if you don't mind rebasing onto `main` and removing the duplicate changelog entry.

Comment (marcinbelczewski) [reply internal/service/bedrockagentcore/gateway.go:191]: Ah indeed! Yes and I just noticed that without config validator there are some invalid scenarios possible. Rebasing now!

**Review by jar-b — APPROVED** [review]
LGTM 🎉 

```console
% make t K=bedrockagentcore T=TestAccBedrockAgentCoreGateway_
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 b-aws-iam-protected-gateway 🌿...
TF_ACC=1 go1.24.8 test ./internal/service/bedrockagentcore/... -v -count 1 -parallel 20 -run='TestAccBedrockAgentCoreGateway_'  -timeout 360m -vet=off
2025/10/27 15:56:33 Creating Terraform AWS Provider (SDKv2-style)...
2025/10/27 15:56:33 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccBedrockAgentCoreGateway_basic
=== PAUSE TestAccBedrockAgentCoreGateway_basic
=== RUN   TestAccBedrockAgentCoreGateway_disappears
=== PAUSE TestAccBedrockAgentCoreGateway_disappears
=== RUN   TestAccBedrockAgentCoreGateway_tags
=== PAUSE TestAccBedrockAgentCoreGateway_tags
=== RUN   TestAccBedrockAgentCoreGateway_description
=== PAUSE TestAccBedrockAgentCoreGateway_description
=== RUN   TestAccBedrockAgentCoreGateway_IAMAuthorizer
=== PAUSE TestAccBedrockAgentCoreGateway_IAMAuthorizer
=== RUN   TestAccBedrockAgentCoreGateway_kmsKey
    gateway_test.go:298: KMS key returns HTTP 500
--- SKIP: TestAccBedrockAgentCoreGateway_kmsKey (0.00s)
=== RUN   TestAccBedrockAgentCoreGateway_protocolConfiguration
=== PAUSE TestAccBedrockAgentCoreGateway_protocolConfiguration
=== CONT  TestAccBedrockAgentCoreGateway_basic
=== CONT  TestAccBedrockAgentCoreGateway_description
=== CONT  TestAccBedrockAgentCoreGateway_tags
=== CONT  TestAccBedrockAgentCoreGateway_IAMAuthorizer
=== CONT  TestAccBedrockAgentCoreGateway_protocolConfiguration
=== CONT  TestAccBedrockAgentCoreGateway_disappears
--- PASS: TestAccBedrockAgentCoreGateway_disappears (20.08s)
--- PASS: TestAccBedrockAgentCoreGateway_basic (23.85s)
--- PASS: TestAccBedrockAgentCoreGateway_description (35.98s)
--- PASS: TestAccBedrockAgentCoreGateway_protocolConfiguration (36.15s)
--- PASS: TestAccBedrockAgentCoreGateway_IAMAuthorizer (37.91s)
--- PASS: TestAccBedrockAgentCoreGateway_tags (46.36s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/bedrockagentcore   54.101s
```

**Comment by jar-b** [comment]
Thank you for the addition, @marcinbelczewski! 👍
