### PR TITLE
aws/resource_aws_emr_cluster.go: Filter completed EMR steps from ListSteps API

### LINKED ISSUE #9888: EMR: many steps with large arguments cause grpc error: received message larger than max
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.12.7

### Affected Resource(s)

* aws_emr_cluster

### Terraform Configuration Files

Not applicable.

### Debug Output

Error: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4760380 vs. 4194304)

### Expected Behavior

Terraform can manage an EMR cluster with many steps where the step argument is large.

### Actual Behavior

Terraform crashes due to grpc receiving a message larger than set max value. This is caused by the list steps api which returns all steps including their argument. If the argument is large, in our case a json string, and the number of totalt steps is also large, the return value is too big for grpc.

### Steps to Reproduce

1. Create an EMR cluster.
2. Add steps(500+) using aws cli or any other api with a large json argument each.
3. Perform a terraform plan

### LINKED ISSUE #14976: Error: rpc error: code = ResourceExhausted desc = grpc: received message larger than max due to elasticmapreduce/ListSteps
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v0.12.28
+ provider.aws v3.1.0
+ provider.external v1.2.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.3.0
+ provider.template v2.1.2

### Affected Resource(s)

* aws_emr_cluster

### Debug Output

full log output (26MB) at https://drive.google.com/file/d/1ShpP3JmtHjg4nShKH2BJMjBJPamq8u94

### Expected Behavior

Plan generated successfully

### Actual Behavior

`Error: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (5209913 vs. 4194304)`

### Steps to Reproduce

Start many steps on the EMR cluster (ours is currently on 23000) and try to generate a terraform plan
On the debug log we noticed a lot of calls to elasticmapreduce/ListSteps (some even had to be retried due to AWS throttling)

### Important Factoids

Our EMR cluster is somewhere long lived and we start a lot of jobs on it during its lifespan

On our configuration we set to ignore changes to step hoping to avoid this type of problem but maybe the plugin doesn't know it doesn't have to query steps before producing configuration differences?
```
  lifecycle {
    ignore_changes = [kerberos_attributes, step, configurations_json]
  }
```

### LINKED ISSUE #17015: RPC ERROR on deleting EMR cluster on TF v0.12.16 provider (aws- 3.18.0)
I see the problem when deleting EMR cluster on TF v0.12.16 provider (hashicorp/aws) 3.18.0, could someone please suggest the fix
```
module.emr_cluster.aws_emr_cluster.emr_cluster: Refreshing state... [id=j-*********]

Error: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4246485 vs. 4194304)
```
I have included the step under ignore_changes section  but could see liststeps on debug logs when Terraform plan is run
```
  lifecycle {
      ignore_changes = [kerberos_attributes, step, configurations_json]
  }
```

Never faced this problem on Terraform 0.11

_Originally posted by @nivreddy14 in https://github.com/hashicorp/terraform-provider-aws/issues/14976#issuecomment-755144130_

### PR DESCRIPTION
**Pull request by dsc133**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

It was found that on long standing EMR clusters, performing a terraform plan can run into a `grpc: Resource Exhaustion` issue when the number of steps or the size of each step reached a large number. This is caused by the default `4 mb` size limit on grpc's. 

This PR filters out completed EMR steps that are returned from the AWS ListSteps API. It maintains returning all steps that have not successfully completed. On long standing EMR clusters this should avoid the issue of steps marked as completed being sent over and using up all the available space in grpc. 

Closes #9888
Closes #14976
Closes #17015

Output from acceptance testing:
Unable to run acceptance testing due to resource constraints.

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### CODE REVIEW

File: aws/resource_aws_emr_cluster.go [hunk 1]
```diff
@@ -1139,8 +1139,21 @@ func resourceAwsEMRClusterRead(d *schema.ResourceData, meta interface{}) error {
...
+		"CANCELLED",
+		"FAILED",
+		"CANCEL_PENDING",
+		"RUNNING",
+		"INTERRUPTED",
+	}
+	var stepStates []*string
+	for _, v := range states {
+		stepStates = append(stepStates, &v)
+	}
```
Comment (kalmykov) [inline aws/resource_aws_emr_cluster.go:1153]: Since `v` will be created only once when loop starts, it will always have the same pointer value. In order to avoid that, use reference to the element of the array via index. More info: https://medium.com/codezillas/uh-ohs-in-go-slice-of-pointers-c0a30669feee

```suggestion
	for i := range states {
		stepStates = append(stepStates, &states[i])
	}
```

**Comment by Thiago-Dantas** [comment]
I wonder if this won't re-submit steps described in terraform configuration?

**Comment by ewbankkit** [comment]
The maximum gRPC buffer size between Terraform CLI and the AWS Provider was increased to 256M in **v4.7.0** via

https://github.com/hashicorp/terraform-plugin-go/pull/139 -> https://github.com/hashicorp/terraform-plugin-sdk/pull/856 -> https://github.com/hashicorp/terraform-provider-aws/pull/23742

but there are still extreme scenarios where this new limit may be exceeded.

**Comment by ewbankkit** [comment]
In order to maintain backwards compatibility here (and prevent the potential drift that @Thiago-Dantas mentions) I think I will add a new optional argument `returns_steps_with_statuses` (name can be fine-tuned) which will be a list of step states (see https://docs.aws.amazon.com/emr/latest/APIReference/API_StepStatus.html) that will be returned when returning steps.
If the list is empty then all steps are returned.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTS=TestAccEMRCluster_Step_ PKG=emr ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/emr/... -v -count 1 -parallel 3 -run='TestAccEMRCluster_Step_'  -timeout 180m
=== RUN   TestAccEMRCluster_Step_basic
=== PAUSE TestAccEMRCluster_Step_basic
=== RUN   TestAccEMRCluster_Step_mode
=== PAUSE TestAccEMRCluster_Step_mode
=== RUN   TestAccEMRCluster_Step_multiple
=== PAUSE TestAccEMRCluster_Step_multiple
=== RUN   TestAccEMRCluster_Step_multiple_listStates
=== PAUSE TestAccEMRCluster_Step_multiple_listStates
=== CONT  TestAccEMRCluster_Step_basic
=== CONT  TestAccEMRCluster_Step_multiple
=== CONT  TestAccEMRCluster_Step_multiple_listStates
--- PASS: TestAccEMRCluster_Step_multiple_listStates (402.72s)
=== CONT  TestAccEMRCluster_Step_mode
--- PASS: TestAccEMRCluster_Step_multiple (396.35s)
--- PASS: TestAccEMRCluster_Step_basic (442.79s)
--- PASS: TestAccEMRCluster_Step_mode (777.90s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/emr	784.537s
```
