### PR TITLE
r/aws_codebuild_fleet: Allow `scaling_configuration`  to be removed on Update

### LINKED ISSUE #40345: [Bug]: Unable to remove scaling_configuration from existing aws_codebuild_fleet resource
### Terraform Core Version

1.9.8

### AWS Provider Version

5.77.0

### Affected Resource(s)

* aws_codebuild_fleet

### Expected Behavior

I should be able to remove the scaling configuration of an existing codebuild fleet.

### Actual Behavior

When I plan the removal of the `scaling_configuration` from an existing `aws_codebuild_fleet` I see the config block gets removed. The apply completes with 'modifications complete', but nothing has actually changed. Running a plan again, again shows the config block planned for removal.

Based on the trace log in 'debug output' below, it seems the 'UpdateFleet' call parameters for removing the configuration should be different than now implemented. The call is made, but nothing is changed as visible in the call response.

### Relevant Error/Panic Output Snippet

_No response_

### Terraform Configuration Files

See code below.

### Steps to Reproduce

Create a fleet with code like this:
```
resource "aws_codebuild_fleet" "linux_small" {
  name              = "linux-general1-small"
  base_capacity     = 1
  environment_type  = "LINUX_EC2"
  compute_type      = "BUILD_GENERAL1_SMALL"
  overflow_behavior = "QUEUE"
  scaling_configuration {
    max_capacity = 5
    scaling_type = "TARGET_TRACKING_SCALING"
    target_tracking_scaling_configs {
      metric_type  = "FLEET_UTILIZATION_RATE"
      target_value = 80
    }
  }
}
```

Once created and stabilised, change the source code to no longer include the scaling block:
```
resource "aws_codebuild_fleet" "linux_small" {
  name              = "linux-general1-small"
  base_capacity     = 1
  environment_type  = "LINUX_EC2"
  compute_type      = "BUILD_GENERAL1_SMALL"
  overflow_behavior = "QUEUE"
}
```

Run 'plan' and see it is planning to remove the scaling configuration.

Run 'apply' and see changes were made.

Run 'plan' again and you'll still see the plan for removing the scaling configuration.

### Debug Output

Relevant portion from 'apply' with `TF_LOG=trace`. It shows the original 'scalingConfiguration' is the response, as if the call to update the fleet to remove the configuration was wrong, or ignored by AWS.

```
2024-11-28T11:08:39.533+0100 [DEBUG] provider.terraform-provider-aws_v5.77.0_x5: HTTP Request Sent: @module=aws http.method=POST http.request.header.x_amz_security_token="*****" rpc.system=aws-api @caller=github.com/hashicorp/aws-sdk-go-base/v2@v2.0.0-beta.59/logging/tf_logger.go:45 http.request.header.amz_sdk_request="attempt=1; max=25" http.request.header.x_amz_target=CodeBuild_20161006.UpdateFleet http.user_agent="APN/1.0 HashiCorp/1.0 Terraform/1.9.8 (+https://www.terraform.io) terraform-provider-aws/5.77.0 (+https://registry.terraform.io/providers/hashicorp/aws) aws-sdk-go-v2/1.32.5 os/macos lang/go#1.23.2 md/GOOS#darwin md/GOARCH#arm64 api/codebuild#1.49.1" tf_aws.signing_region="" net.peer.name=codebuild.eu-west-1.amazonaws.com rpc.service=CodeBuild tf_resource_type=aws_codebuild_fleet tf_req_id=a8ecf3a9-ec42-105c-837f-a25e991d8472 http.request.header.content_type=application/x-amz-json-1.1 http.request.header.x_amz_date=20241128T100839Z tf_rpc=ApplyResourceChange aws.region=eu-west-1 http.request.header.amz_sdk_invocation_id=fb7d870e-a9ad-49fa-99c1-6caaefc43515 http.url=https://codebuild.eu-west-1.amazonaws.com/ rpc.method=UpdateFleet tf_aws.sdk=aws-sdk-go-v2 tf_provider_addr=registry.terraform.io/hashicorp/aws
  http.request.body=
  | {"arn":"arn:aws:codebuild:eu-west-1:1234567890:fleet/linux-general1-small:b6b68ae7-c0bf-40c1-9b7b-7627e573a32a","imageId":"","overflowBehavior":"QUEUE","tags":[...redacted...]}
   http.request.header.authorization="AWS4-HMAC-SHA256 Credential=ASIA************3K4Z/20241128/eu-west-1/codebuild/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-date;x-amz-security-token;x-amz-target, Signature=*****" http.request_content_length=367 tf_mux_provider="*schema.GRPCProviderServer" timestamp="2024-11-28T11:08:39.533+0100"

2024-11-28T11:08:39.849+0100 [DEBUG] provider.terraform-provider-aws_v5.77.0_x5: HTTP Response Received: rpc.service=CodeBuild rpc.system=aws-api tf_aws.signing_region="" tf_req_id=a8ecf3a9-ec42-105c-837f-a25e991d8472 rpc.method=UpdateFleet tf_aws.sdk=aws-sdk-go-v2 tf_rpc=ApplyResourceChange
  http.response.body=
  | {"fleet":{"actualCapacity":3,"arn":"arn:aws:codebuild:eu-west-1:1234567890:fleet/linux-general1-small:b6b68ae7-c0bf-40c1-9b7b-7627e573a32a","availabilityZone":"eu-west-1c","availabilityZoneId":"euw1-az3","baseCapacity":1,"capacity":1,"compute":{"ami":"ami-062313ab11c6221e0","architecture":"AMD64","disk":64,"executionModel":"BARE_METAL","memory":4,"os":"LINUX","vCpu":2},"computeType":"BUILD_GENERAL1_SMALL","created":1.732717070553E9,"desiredCapacity":1,"environmentType":"LINUX_EC2","id":"b6b68ae7-c0bf-40c1-9b7b-7627e573a32a","imageId":"","lastModified":1.732785581029E9,"name":"linux-general1-small","overflowBehavior":"QUEUE","scalingConfiguration":{"desiredCapacity":1,"maxCapacity":5,"scalingType":"TARGET_TRACKING_SCALING","targetTrackingScalingConfigs":[{"metricType":"FLEET_UTILIZATION_RATE","targetValue":80.0}]},"status":{"statusCode":"ACTIVE"},"tags":[...redacted...]}}
   http.response_content_length=1074 http.response.header.x_amzn_requestid=eea8bf6d-3dce-4a09-89a0-974adb679219 http.status_code=200 tf_mux_provider="*schema.GRPCProviderServer" tf_provider_addr=registry.terraform.io/hashicorp/aws tf_resource_type=aws_codebuild_fleet @module=aws http.response.header.content_type=application/x-amz-json-1.1 aws.region=eu-west-1 http.duration=315 http.response.header.date="Thu, 28 Nov 2024 10:08:39 GMT" @caller=github.com/hashicorp/aws-sdk-go-base/v2@v2.0.0-beta.59/logging/tf_logger.go:45 timestamp="2024-11-28T11:08:39.849+0100"
```

### Panic Output

_No response_

### Important Factoids

This is how the fleet looks like under the hood:
```
$ aws codebuild batch-get-fleets --names linux-general1-small
{
    "fleets": [
        {
            "arn": "arn:aws:codebuild:eu-west-1:1234567890:fleet/linux-general1-small:b6b68ae7-c0bf-40c1-9b7b-7627e573a32a",
            "name": "linux-general1-small",
            "id": "b6b68ae7-c0bf-40c1-9b7b-7627e573a32a",
            "created": "2024-11-27T15:17:50.553000+01:00",
            "lastModified": "2024-11-28T10:19:41.029000+01:00",
            "status": {
                "statusCode": "ACTIVE"
            },
            "baseCapacity": 1,
            "environmentType": "LINUX_EC2",
            "computeType": "BUILD_GENERAL1_SMALL",
            "scalingConfiguration": {
                "scalingType": "TARGET_TRACKING_SCALING",
                "targetTrackingScalingConfigs": [
                    {
                        "metricType": "FLEET_UTILIZATION_RATE",
                        "targetValue": 80.0
                    }
                ],
                "maxCapacity": 5,
                "desiredCapacity": 2
            },
            "overflowBehavior": "QUEUE",
            "imageId": "aws/codebuild/ami/amazonlinux-x86_64-base:2023-1.0",
            "tags": [ ... ]
        }
    ],
    "fleetsNotFound": []
}
```

### References

_No response_

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by kamilturek**
### Description
This PR fixes removing the `scaling_configuration` block argument on update. An empty `ScalingConfigurationInput` struct needs to be passed to the `UpdateFleet` action in order to actually remove the scaling configuration.

### Relations
Closes #40345.

### References
https://docs.aws.amazon.com/codebuild/latest/APIReference/API_UpdateFleet.html

### Output from Acceptance Testing
```console
% make testacc PKG=codebuild ACCTEST_PARALLELISM=1 TESTARGS="-run=TestAccCodeBuildFleet_scalingConfiguration"
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.3 test ./internal/service/codebuild/... -v -count 1 -parallel 1  -run=TestAccCodeBuildFleet_scalingConfiguration -timeout 360m
2025/01/04 13:59:36 Initializing Terraform AWS Provider...
=== RUN   TestAccCodeBuildFleet_scalingConfiguration
=== PAUSE TestAccCodeBuildFleet_scalingConfiguration
=== CONT  TestAccCodeBuildFleet_scalingConfiguration
--- PASS: TestAccCodeBuildFleet_scalingConfiguration (103.13s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/codebuild  108.212s
```

### CODE REVIEW

File: internal/service/codebuild/fleet.go [hunk 1]
```diff
@@ -712,7 +710,11 @@ func flattenScalingConfiguration(apiObject *types.ScalingConfigurationOutput) ma
 		tfMap["target_tracking_scaling_configs"] = flattenTargetTrackingScalingConfigs(v)
 	}
 
-	return tfMap
+	if len(tfMap) == 0 {
+		return nil
+	}
+
+	return []interface{}{tfMap}
```
Comment (kamilturek) [inline internal/service/codebuild/fleet.go:717]: The Read operation returns an empty `ScalingConfigurationOutput` object after the scaling configuration is removed and this function flattened it to such state:
```
scaling_configuration {
}
```
Which caused a persistent diff.

I skimmed over other services and resources but I couldn't really find the standard way to deal with such empty nested blocks.

Comment (jar-b) [reply internal/service/codebuild/fleet.go:717]: This seems reasonable to me given the situation. If this is eventually serialized properly to a nil value in the AWS SDK the flattener will still do the "right" thing.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccCodeBuildFleet_' PKG=codebuild ACCTEST_PARALLELISM=3
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.3 test ./internal/service/codebuild/... -v -count 1 -parallel 3  -run=TestAccCodeBuildFleet_ -timeout 360m
2025/01/07 15:47:49 Initializing Terraform AWS Provider...
=== RUN   TestAccCodeBuildFleet_basic
=== PAUSE TestAccCodeBuildFleet_basic
=== RUN   TestAccCodeBuildFleet_disappears
=== PAUSE TestAccCodeBuildFleet_disappears
=== RUN   TestAccCodeBuildFleet_tags
=== PAUSE TestAccCodeBuildFleet_tags
=== RUN   TestAccCodeBuildFleet_baseCapacity
=== PAUSE TestAccCodeBuildFleet_baseCapacity
=== RUN   TestAccCodeBuildFleet_computeConfiguration
=== PAUSE TestAccCodeBuildFleet_computeConfiguration
=== RUN   TestAccCodeBuildFleet_computeType
=== PAUSE TestAccCodeBuildFleet_computeType
=== RUN   TestAccCodeBuildFleet_environmentType
=== PAUSE TestAccCodeBuildFleet_environmentType
=== RUN   TestAccCodeBuildFleet_imageId
=== PAUSE TestAccCodeBuildFleet_imageId
=== RUN   TestAccCodeBuildFleet_scalingConfiguration
=== PAUSE TestAccCodeBuildFleet_scalingConfiguration
=== RUN   TestAccCodeBuildFleet_vpcConfig
=== PAUSE TestAccCodeBuildFleet_vpcConfig
=== CONT  TestAccCodeBuildFleet_basic
=== CONT  TestAccCodeBuildFleet_computeType
=== CONT  TestAccCodeBuildFleet_scalingConfiguration
--- PASS: TestAccCodeBuildFleet_basic (44.08s)
=== CONT  TestAccCodeBuildFleet_vpcConfig
--- PASS: TestAccCodeBuildFleet_computeType (64.88s)
=== CONT  TestAccCodeBuildFleet_baseCapacity
--- PASS: TestAccCodeBuildFleet_scalingConfiguration (90.06s)
=== CONT  TestAccCodeBuildFleet_computeConfiguration
--- PASS: TestAccCodeBuildFleet_vpcConfig (81.96s)
=== CONT  TestAccCodeBuildFleet_tags
--- PASS: TestAccCodeBuildFleet_baseCapacity (63.24s)
=== CONT  TestAccCodeBuildFleet_environmentType
--- PASS: TestAccCodeBuildFleet_computeConfiguration (65.88s)
=== CONT  TestAccCodeBuildFleet_disappears
--- PASS: TestAccCodeBuildFleet_environmentType (63.36s)
=== CONT  TestAccCodeBuildFleet_imageId
--- PASS: TestAccCodeBuildFleet_disappears (56.13s)
--- PASS: TestAccCodeBuildFleet_tags (86.45s)
--- PASS: TestAccCodeBuildFleet_imageId (44.16s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/codebuild	240.975s
```

**Comment by ewbankkit** [comment]
@kamilturek Thanks for the contribution :tada: :clap:.
