### PR TITLE
tests/provider: Fix and enable AT004 lint check

### LINKED ISSUE #8983: Tech Debt: Remove `provider "aws"` blocks from non provider_test.go files
## Description

Provider configurations should be handled outside of individual test configurations. Having the provider configured in individual tests can lead to unexpected behavior when multiple configurations overlap or conflict with each other. This also allows the tests to be AWS Region and Partition agnostic.

## Test Updates

Existing tests should be updated to remove any hardcoded `provider "aws" {...}` blocks from individual test configurations.

## Linting

Going forward, a linter rule such as [AT004](https://github.com/bflad/tfproviderlint/blob/master/passes/AT004/README.md) could be added to prevent these from being added in the future.

## Definition of Done
* In `GNUmakefile`, add -`AT004` to `tfproviderlint` command under `lint` target and have TravisCI testing pass

## Issues:
- [ ] data_source_aws_cur_report_definition_test.go:63:21
- [ ] data_source_aws_eip_test.go:221:57
- [ ] data_source_aws_instance_test.go:779:21
- [ ] provider_test.go:1593:54
- [ ] resource_aws_cur_report_definition_test.go:108:21
- [ ] resource_aws_default_security_group_test.go:169:54
- [ ] resource_aws_eip_association_test.go:410:51
- [ ] resource_aws_eip_test.go:697:41
- [ ] resource_aws_elasticache_security_group_test.go:143:60
- [ ] resource_aws_instance_test.go:3386:21
- [ ] resource_aws_instance_test.go:3810:46
- [ ] resource_aws_lightsail_domain_test.go:131:21
- [ ] resource_aws_opsworks_stack_test.go:226:21
- [ ] resource_aws_opsworks_stack_test.go:312:21
- [ ] resource_aws_opsworks_stack_test.go:721:21
- [ ] resource_aws_opsworks_stack_test.go:988:21

### PR DESCRIPTION
**Pull request by mattburgess**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #8983

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
NONE
```

Output from acceptance testing:

```
$ make awsproviderlint
$ make testacc TEST=./aws TESTARGS='-run=TestAccDataSourceAwsEip_PublicIP_EC2Classic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccDataSourceAwsEip_PublicIP_EC2Classic -timeout 120m
=== RUN   TestAccDataSourceAwsEip_PublicIP_EC2Classic
--- PASS: TestAccDataSourceAwsEip_PublicIP_EC2Classic (20.17s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	20.199s

$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSEIP_tags_Ec2Classic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSEIP_tags_Ec2Classic -timeout 120m
=== RUN   TestAccAWSEIP_tags_Ec2Classic
=== PAUSE TestAccAWSEIP_tags_Ec2Classic
=== CONT  TestAccAWSEIP_tags_Ec2Classic
    TestAccAWSEIP_tags_Ec2Classic: ec2_classic_test.go:54: this test can only run in EC2-Classic, platforms available in us-east-1: ["VPC"]
--- SKIP: TestAccAWSEIP_tags_Ec2Classic (2.71s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	2.743s

$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSLightsailDomain_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSLightsailDomain_basic -timeout 120m
=== RUN   TestAccAWSLightsailDomain_basic
=== PAUSE TestAccAWSLightsailDomain_basic
=== CONT  TestAccAWSLightsailDomain_basic
--- PASS: TestAccAWSLightsailDomain_basic (18.97s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	19.006s

$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSLightsailDomain_disappears'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSLightsailDomain_disappears -timeout 120m
=== RUN   TestAccAWSLightsailDomain_disappears
=== PAUSE TestAccAWSLightsailDomain_disappears
=== CONT  TestAccAWSLightsailDomain_disappears
--- PASS: TestAccAWSLightsailDomain_disappears (18.49s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	18.520s

$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSOpsWorksStack_classicEndpoints'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSOpsWorksStack_classicEndpoints -timeout 120m
=== RUN   TestAccAWSOpsWorksStack_classicEndpoints
=== PAUSE TestAccAWSOpsWorksStack_classicEndpoints
=== CONT  TestAccAWSOpsWorksStack_classicEndpoints
    TestAccAWSOpsWorksStack_classicEndpoints: provider_test.go:694: skipping tests; AWS_DEFAULT_REGION (eu-west-2) does not equal us-west-2
--- SKIP: TestAccAWSOpsWorksStack_classicEndpoints (2.06s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	2.086s
```
It looks like the only remaining instances of provider blocks in the tests are there for valid reasons; i.e. where AWS services are only available in the hard-coded region or for regression testing for when they used to be. This PR therefore simply adds `lintignore` markers to those occurrences.

### CODE REVIEW

File: aws/resource_aws_lightsail_domain_test.go [hunk 1]
```diff
@@ -134,5 +134,5 @@ provider "aws" {
 resource "aws_lightsail_domain" "domain_test" {
   domain_name = "%s"
 }
-`, lightsailDomainName)
+`, lightsailDomainName) //lintignore:AT004
```
Comment (bflad) [inline aws/resource_aws_lightsail_domain_test.go:137]: Per https://github.com/hashicorp/terraform-provider-aws/pull/9080 description and recent similar changes for other region-specific testing (e.g. https://github.com/hashicorp/terraform-provider-aws/pull/16140), will refactor this post-merge and verify in AWS Commercial and AWS GovCloud (US). If you're curious about this esoteric subject (why I'm not requesting you to make these changes 😉 ), please see this very recent [addition in the Contributing Guide](https://github.com/hashicorp/terraform-provider-aws/blob/master/docs/contributing/running-and-writing-acceptance-tests.md#service-specific-region-acceptance-testing).

File: aws/data_source_aws_eip_test.go [hunk 2]
```diff
@@ -219,10 +219,6 @@ data "aws_eip" "test" {
 `
 
 const testAccDataSourceAwsEipConfigPublicIpEc2Classic = `
-provider "aws" {
```
Comment (bflad) [inline aws/data_source_aws_eip_test.go:222]: Since its not a subject that will be dealt with with any future testing, will migrate this to the standardized EC2-Classic handling (https://github.com/hashicorp/terraform-provider-aws/pull/15803) post-merge. It was missed before because it wasn't using `os.Setenv()` like the others.

File: aws/resource_aws_eip_test.go [hunk 3]
```diff
@@ -763,10 +763,6 @@ resource "aws_eip" "test" {
 
 func testAccAWSEIPConfig_tags_Ec2Classic(rName, testName string) string {
 	return fmt.Sprintf(`
-provider "aws" {
```
Comment (bflad) [inline aws/resource_aws_eip_test.go:766]: Since its not a subject that will be dealt with with any future testing, will migrate this to the standardized EC2-Classic handling (https://github.com/hashicorp/terraform-provider-aws/pull/15803) post-merge. It was missed before because it wasn't using `os.Setenv()` like the others.

**Review by bflad — APPROVED** [review]
Given our recent changes to finish up the remaining prerequisites for this linter, this is very apropos, @mattburgess. Thank you! 🚀
