### PR TITLE
odb/aws_odb_cloud_vm_cluster: fixes issue with `data_storage_size_in_tbs`

### LINKED ISSUE #44480: incorrect error:
### Terraform and AWS Provider Version

```console
Terraform v1.11.2
hashicorp/aws 6.14.1
```

### Affected Resource(s) or Data Source(s)

`aws_odb_cloud_vm_cluster`

### Expected Behavior

Either allow null as shown in the documentation:
Image

Or the error msg should be data_storage_size_in_tbs instead of dataStorageSizeInTBs, which  dataStorageSizeInTBs is not a valid parameter in both documentation and IntelliSense . 

### Actual Behavior

Error msg : ValidationException: dataStorageSizeInTBs cannot be null.
Image

dataStorageSizeInTBs is not expected
Image

### Relevant Error/Panic Output

```console
 Error: creating AWS Oracle Database@AWS Cloud Vm Cluster (ofake-vmc-odbdemo): operation error odb: CreateCloudVmCluster, https response error StatusCode: 400, RequestID: xxxxxxx, ValidationException: dataStorageSizeInTBs cannot be null.
│ 
│   with aws_odb_cloud_vm_cluster.this,
│   on odb-exadata-vmc.tf line 2, in resource "aws_odb_cloud_vm_cluster" "this":
│    2: resource "aws_odb_cloud_vm_cluster" "this" {
│ 
│ operation error odb: CreateCloudVmCluster, https response error StatusCode: 400, RequestID: xxxxxx, ValidationException: dataStorageSizeInTBs cannot be null.

```

### Sample Terraform Configuration

<details open>
<summary>Click to expand configuration</summary>

```hcl
resource "aws_odb_cloud_vm_cluster" "this" {
  cloud_exadata_infrastructure_id = aws_odb_cloud_exadata_infrastructure.this.id
  cluster_name                    = local.name.odb_gi_cluster_name
  cpu_core_count                  = 16
  # data_storage_size_in_tbs        = 2
  # dataStorageSizeInTBs            = 2
  db_node_storage_size_in_gbs     = 120
  memory_size_in_gbs              = 60
  db_servers                      = local.db_servers
  display_name                    = local.name.odb_vmc_display_name
  gi_version                      = "23.0.0.0"
  hostname_prefix                 = "vm"
  odb_network_id                  = aws_odb_network.this.id
  ssh_public_keys                 = local.ssh_public_keys
  tags                            = local.tags
  timezone                        = "UTC"
  is_local_backup_enabled         = false
  license_model                   = "BRING_YOUR_OWN_LICENSE"
  is_sparse_diskgroup_enabled     = false
  data_collection_options {
    is_diagnostics_events_enabled = true
    is_health_monitoring_enabled  = true
    is_incident_logs_enabled      = true
  }
}
```
</details>

### Steps to Reproduce

Terraform apply

### Debug Logging

<details open>
<summary>Click to expand log output</summary>

```console

```
</details>

### GenAI / LLM Assisted Development

n/a

### Important Facts and References

_No response_

### Would you like to implement a fix?

No

### LINKED ISSUE #44499: aws_odb_cloud_vm_cluster: gi_version should be a computed value
### Terraform and AWS Provider Version

```console
hashicorp/aws = 6.14.1
```

### Affected Resource(s) or Data Source(s)

`aws_odb_cloud_vm_cluster`

### Expected Behavior

Provision success

### Actual Behavior

Image

### Relevant Error/Panic Output

```console

```

### Sample Terraform Configuration

<details open>
<summary>Click to expand configuration</summary>

```hcl
# Create a VM Cluster in the Exadata Infrastructure
resource "aws_odb_cloud_vm_cluster" "this" {
  depends_on = [aws_odb_cloud_exadata_infrastructure.this, aws_odb_network.this]

  # Required Arguments
  cloud_exadata_infrastructure_id = local.cloud_exadata_infrastructure_id
  cpu_core_count                  = 16
  db_servers                      = local.db_servers
  display_name                    = local.name.odb_vmc_display_name
  gi_version                      = "23.0.0.0"
  hostname_prefix                 = "vm"
  odb_network_id                  = aws_odb_network.this.id
  ssh_public_keys                 = local.ssh_public_keys
  data_collection_options {
    is_diagnostics_events_enabled = true
    is_health_monitoring_enabled  = true
    is_incident_logs_enabled      = true
  }
  
  # Optional Arguments
  cluster_name                    = local.name.odb_gi_cluster_name
  data_storage_size_in_tbs        = 2
  db_node_storage_size_in_gbs     = 120
  is_local_backup_enabled         = false
  is_sparse_diskgroup_enabled     = false
  license_model                   = "BRING_YOUR_OWN_LICENSE"
  memory_size_in_gbs              = 60
  scan_listener_port_tcp          = 1521
  timezone                        = "UTC"
  region                          = local.location.region
  tags                            = local.tags
}


```
</details>

### Steps to Reproduce

terraform apply

### Debug Logging

<details open>
<summary>Click to expand log output</summary>

```console

```
</details>

### GenAI / LLM Assisted Development

n/a

### Important Facts and References

_No response_

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by ab-cs13**
## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the library.

## Changes to Security Controls

No 

### Description
Bug details : https://github.com/hashicorp/terraform-provider-aws/issues/44480

data_storage_size_in_tbs marked as Optional causing the issue. data_storage_size_in_tbs should be required field. This is marked optional in terraform provider because AWS GO SDK marked this field optional where as underlying API treating it as mandatory. This also a bug in AWS SDK.

Please refer: https://github.com/aws/aws-sdk-go-v2/blob/main/service/odb/api_op_CreateCloudVmCluster.go

Bug details : https://github.com/hashicorp/terraform-provider-aws/issues/44499
 
Underlying API confirmed that, they will accept major gi-version and returns exact gi-version.  

### Relations

Closes #44480
Closes #44499
### References

AWS SDK reference : https://github.com/aws/aws-sdk-go-v2/blob/main/service/odb/api_op_CreateCloudVmCluster.go

Bug details : https://github.com/hashicorp/terraform-provider-aws/issues/44480

### Output from Acceptance Testing
To run acceptance test, special multicloud linked (linked between AWS and OCI) account is required. Acceptance tests can't run on normal AWS account. As an oracle employee we have multicloud linked accounts. Therefore we will provide testing evidence by executing acceptance tests in the odb package.

### CODE REVIEW

**Comment by ab-cs13** [comment]
Test Evidences
---------------
Screenshot 2025-10-01 at 13 45 07

Screenshot 2025-10-01 at 11 30 27

File: internal/service/odb/cloud_vm_cluster.go [hunk 1]
```diff
@@ -476,6 +490,16 @@ func (r *resourceCloudVmCluster) Create(ctx context.Context, req resource.Create
 	plan.HostnamePrefixComputed = types.StringValue(*createdVmCluster.Hostname)
 	//scan listener port not returned by API directly
 	plan.ScanListenerPortTcp = types.Int32PointerValue(createdVmCluster.ListenerPort)
+	plan.GiVersionComputed = types.StringPointerValue(createdVmCluster.GiVersion)
```
Comment (johnsonaj) [inline internal/service/odb/cloud_vm_cluster.go]:
```suggestion
	plan.GiVersionComputed = flex.StringToFramework(ctx, createdVmCluster.GiVersion)
```

File: internal/service/odb/cloud_vm_cluster.go [hunk 2]
```diff
@@ -476,6 +490,16 @@ func (r *resourceCloudVmCluster) Create(ctx context.Context, req resource.Create
 	plan.HostnamePrefixComputed = types.StringValue(*createdVmCluster.Hostname)
 	//scan listener port not returned by API directly
 	plan.ScanListenerPortTcp = types.Int32PointerValue(createdVmCluster.ListenerPort)
```
Comment (johnsonaj) [inline internal/service/odb/cloud_vm_cluster.go]:
```suggestion
	plan.ScanListenerPortTcp = flex.Int32ToFramework(ctx, createdVmCluster.ListenerPort)
```

File: internal/service/odb/cloud_vm_cluster.go [hunk 3]
```diff
@@ -476,6 +490,16 @@ func (r *resourceCloudVmCluster) Create(ctx context.Context, req resource.Create
...
+	plan.GiVersionComputed = types.StringPointerValue(createdVmCluster.GiVersion)
+	giVersionMajor, err := getMajorGiVersion(createdVmCluster.GiVersion)
+	if err != nil {
+		resp.Diagnostics.AddError(
+			create.ProblemStandardMessage(names.ODB, create.ErrActionWaitingForCreation, ResNameCloudVmCluster, plan.DisplayName.ValueString(), err),
+			err.Error(),
+		)
+		return
+	}
+	plan.GiVersion = types.StringPointerValue(giVersionMajor)
```
Comment (johnsonaj) [inline internal/service/odb/cloud_vm_cluster.go]: we should use the `flex` functions for value conversions instead of the framework `types

```suggestion
	plan.GiVersion = flex.StringtoFramework(cox, giVersionMajor)
```

File: internal/service/odb/cloud_vm_cluster.go [hunk 4]
```diff
@@ -509,7 +533,16 @@ func (r *resourceCloudVmCluster) Read(ctx context.Context, req resource.ReadRequ
 	state.HostnamePrefixComputed = types.StringValue(*out.Hostname)
 	//scan listener port not returned by API directly
 	state.ScanListenerPortTcp = types.Int32PointerValue(out.ListenerPort)
-
+	state.GiVersionComputed = types.StringPointerValue(out.GiVersion)
```
Comment (johnsonaj) [inline internal/service/odb/cloud_vm_cluster.go]: Same comment as above for using flex functions

File: internal/service/odb/cloud_vm_cluster.go [hunk 5]
```diff
@@ -6,6 +6,7 @@ package odb
 import (
 	"context"
 	"errors"
+	"regexp"
```
Comment (johnsonaj) [inline internal/service/odb/cloud_vm_cluster.go]: we should replace the standard `regex` library with `"github.com/YakDriver/regexache"`. This is used throughout the provider and provides better caching

**Comment by ab-cs13** [comment]
Test evidence
---------------
Screenshot 2025-10-01 at 20 45 21
