### PR TITLE
Initialize start time and end time value avoid null override

### LINKED ISSUE #32616: [Bug]: aws_appautoscaling_scheduled_action start_time and end_time not mantained when updating resources
### Terraform Core Version

1.5.3

### AWS Provider Version

5.8.0

### Affected Resource(s)

aws_appautoscaling_scheduled_action

### Expected Behavior

When updating a aws_appautoscaling_scheduled_action resource, all the previously configured settings are maintained 

### Actual Behavior

When updating a aws_appautoscaling_scheduled_action resource, the previously configured  start_time and end_time are lost

### Relevant Error/Panic Output Snippet

_No response_

### Terraform Configuration Files

```hcl
resource "aws_appautoscaling_target" "ecs_target" {
  max_capacity       = var.MaxCapacity
  min_capacity       = var.MinCapacity
  resource_id        = "service/${var.ecs_cluster.name}/${aws_ecs_service.ecs_service.name}"
  scalable_dimension = "ecs:service:DesiredCount"
  service_namespace  = "ecs"
}

resource "aws_appautoscaling_scheduled_action" "all_days_shift_weekend" {
  name               = "all_days_shift_weekend"
  service_namespace  = aws_appautoscaling_target.ecs_target.service_namespace
  scalable_dimension = aws_appautoscaling_target.ecs_target.scalable_dimension
  resource_id        = aws_appautoscaling_target.ecs_target.resource_id
  schedule           = "cron(00 19 ? * FRI *)"
  timezone           = "Europe/Rome"
  scalable_target_action {
    min_capacity = var.WeekendCapacity
    max_capacity = var.WeekendCapacity
  }
  start_time = "2023-07-19T13:00:00+02:00"
  end_time   = "2023-07-27T13:00:00+02:00"
}
```

### Steps to Reproduce

1. Create an ECS cluster
2. Create an ECS service
3. Plan and apply the Autoscaling Target and Scheduled action as in config files
4. Check via cli `aws application-autoscaling describe-scheduled-actions --service-namespace ecs` and see that start_time and end_time are present
```hcl
{
    "ScheduledActions": [
        {
            "ScheduledActionName": "all_days_shift_weekend",
            "ScheduledActionARN": "arn:aws:autoscaling:eu-west-1:112345123123:scheduledAction:4a1231ff-xxxx-xxxx-xxxx-c989676b6d3e:resource/ecs/service/cluster/service:scheduledActionName/all_days_shift_weekend",
            "ServiceNamespace": "ecs",
            "Schedule": "cron(00 19 ? * FRI *)",
            "Timezone": "Europe/Rome",
            "ResourceId": "service/cluster/service",
            "StartTime": "2023-07-19T13:00:00+02:00",
            "EndTime": "2023-07-27T13:00:00+02:00",
            "ScalableDimension": "ecs:service:DesiredCount",
            "ScalableTargetAction": {
                "MinCapacity": 2,
                "MaxCapacity": 2
            },
            "CreationTime": "2023-07-20T10:58:23.570000+02:00"
        }
    ]
}
```
5. Change the var.WeekendCapacity from 2 to 3 (or anything different from 2) 
6. Plan and apply, you will see 
```hcl
Plan: 0 to add, 1 to change, 0 to destroy.
Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```
8. Check via cli `aws application-autoscaling describe-scheduled-actions --service-namespace ecs` and see that start_time and end_time are not present anymore
```hcl
{
    "ScheduledActions": [
        {
            "ScheduledActionName": "all_days_shift_weekend",
            "ScheduledActionARN": "arn:aws:autoscaling:eu-west-1:112345123123:scheduledAction:4a1231ff-xxxx-xxxx-xxxx-c989676b6d3e:resource/ecs/service/cluster/service:scheduledActionName/all_days_shift_weekend",
            "ServiceNamespace": "ecs",
            "Schedule": "cron(00 19 ? * FRI *)",
            "Timezone": "Europe/Rome",
            "ResourceId": "service/cluster/service",
            "ScalableDimension": "ecs:service:DesiredCount",
            "ScalableTargetAction": {
                "MinCapacity": 3,
                "MaxCapacity": 3
            },
            "CreationTime": "2023-07-20T10:58:23.570000+02:00"
        }
    ]
}
```

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

None

### LINKED ISSUE #33708: [Bug]: Scheduled Action Update State Override Start Time and End Time with Null value
### Terraform Core Version

1.1.X

### AWS Provider Version

5.3.0

### Affected Resource(s)

* aws_scheduledaction

### Expected Behavior

1. Create new scheduled action with `startTime` and `endTime`
2. Resource created and attached to ECS
3. Update `minCapacity` for existing scheduled action that has been created at step 1
4. `schedule` value updated, but retain start time and end time value

### Actual Behavior

1. Create new scheduled action with `startTime` and `endTime`
2. Resource created and attached to ECS
3. Update `minCapacity` for existing scheduled action that has been created at step 1
4. `schedule` value updated, `startTime` and `endTime` value changed to null

### Relevant Error/Panic Output Snippet

```shell
No Error, but it cause my scheduled action keep running without `endTime` and cost us some money to unexpected scale out event for longer than expected.
```

### Terraform Configuration Files

```terraform
resource "aws_appautoscaling_scheduled_action" "scale_morning_promo_start" {
  name               = module.autoscaling_schedule_morning_promo_start_traffic.name
  service_namespace  = local.service_namespace
  resource_id        = module.ecs-app.resource_id
  scalable_dimension = local.scalable_dimension
  timezone           = local.timezone
  schedule           = "cron(45 07 * * ? *)"
  start_time         = "2023-02-24T00:00:00+07:00"
  end_time           = "2023-02-24T23:59:59+07:00"

  scalable_target_action {
    min_capacity = local.ecs_task_count_promo_target_high
  }
  count = local.disable_resource
}
```
This the only config, but as I mentioned above on the behavior section, I update the `minCapacity` value and re-apply it again, then `start_time` and `end_time` is null when I check the schedule action state.

### Steps to Reproduce

1. Create new scheduler with above config:
```terraform
        {
            "ScalableDimension": "ecs:service:DesiredCount", 
            "Schedule": "cron(0 7 * * ? *)", 
            "ResourceId": "service/my-service-cluster/my-app-123abcde", 
            "CreationTime": 1685949955.663, 
            "ScheduledActionARN": "arn:aws:autoscaling:ap-southeast-1:1234567:scheduledAction:c6540143-e917-4d89-8aab-5f61566b4ee2:resource/ecs/service/my-service-cluster/my-app-123abcde:scheduledActionName/my-service-normal-123456", 
            "ScalableTargetAction": {
                "MinCapacity": 1
            }, 
            "ScheduledActionName": "my-service-normal-1234566", 
            "StartTime": 1685293200.0, 
            "Timezone": "Asia/Jakarta", 
            "ServiceNamespace": "ecs", 
            "EndTime": 1685725199.0
        }, 
```
2. Re-apply with updated `minCapacity` value (**Notice that `StartTime` and `EndTime` are missing after update**):
```terraform
        {
            "ScalableDimension": "ecs:service:DesiredCount", 
            "Schedule": "cron(0 7 * * ? *)", 
            "ResourceId": "service/my-service-cluster/my-app-123abcde", 
            "CreationTime": 1685949955.663, 
            "ScheduledActionARN": "arn:aws:autoscaling:ap-southeast-1:1234567:scheduledAction:c6540143-e917-4d89-8aab-5f61566b4ee2:resource/ecs/service/my-service-cluster/my-app-123abcde:scheduledActionName/my-service-normal-123456", 
            "ScalableTargetAction": {
                "MinCapacity": 2
            }, 
            "ScheduledActionName": "my-service-normal-1234566", 
            "Timezone": "Asia/Jakarta", 
            "ServiceNamespace": "ecs"
        }, 
```

### Debug Output

I tried to debug it locally with `main` branch and checkout a new branch base on `main` and try to debug it from I got the unexpected result when run the acc test.
1. When creating new resource, the payload is:
```hcl
{
  "EndTime": "2023-10-07T14:45:21Z",
  "ResourceId": "service/tf-acc-test-12345/tf-acc-test-12345",
  "ScalableDimension": "ecs:service:DesiredCount",
  "ScalableTargetAction": {
    "MaxCapacity": 5,
    "MinCapacity": 1
  },
  "Schedule": "at(2023-09-30T14:45:21)",
  "ScheduledActionName": "tf-acc-test-12345",
  "ServiceNamespace": "ecs",
  "StartTime": "2023-10-01T14:45:21Z",
  "Timezone": "UTC"
}
```
2. When update the existing scheduler the resource payload become (**Notice that `StartTime` and `EndTime` are missing after update**):
```hcl
{
  "EndTime": null,
  "ResourceId": "service/tf-acc-test-12345/tf-acc-test-12345",
  "ScalableDimension": "ecs:service:DesiredCount",
  "ScalableTargetAction": null,
  "Schedule": "at(2023-10-01T14:45:21)",
  "ScheduledActionName": "tf-acc-test-12345",
  "ServiceNamespace": "ecs",
  "StartTime": null,
  "Timezone": null
}
```

### Panic Output

_No response_

### Important Factoids

Since I'm newb so I tried to debug it locally by print the request payload and the state that has been stored, here is my findings:
1. Create new scheduled action input payload:
```hcl
{
  "EndTime": "2023-10-10T10:10:59Z",
  "ResourceId": "service/tf-acc-test-12345/tf-acc-test-12345",
  "ScalableDimension": "ecs:service:DesiredCount",
  "ScalableTargetAction": {
    "MaxCapacity": 5,
    "MinCapacity": 1
  },
  "Schedule": "at(2023-10-03T10:10:59)",
  "ScheduledActionName": "tf-acc-test-12345",
  "ServiceNamespace": "ecs",
  "StartTime": "2023-10-04T10:10:59Z",
  "Timezone": "UTC"
}
```
with the stored state:
```hcl
{
  "CreationTime": "2023-10-02T03:11:15.605Z",
  "EndTime": "2023-10-10T10:10:59Z",
  "ResourceId": "service/tf-acc-test-12345/tf-acc-test-12345",
  "ScalableDimension": "ecs:service:DesiredCount",
  "ScalableTargetAction": {
    "MaxCapacity": 5,
    "MinCapacity": 1
  },
  "Schedule": "at(2023-10-03T10:10:59)",
  "ScheduledActionARN": "arn:aws:autoscaling:ap-southeast-1:12345:scheduledAction:2ca2b6de-ea80-47cc-9131-0f58c3a38ef2:resource/ecs/service/tf-acc-test-12345/tf-acc-test-12345:scheduledActionName/tf-acc-test-12345",
  "ScheduledActionName": "tf-acc-test-12345",
  "ServiceNamespace": "ecs",
  "StartTime": "2023-10-04T10:10:59Z",
  "Timezone": "UTC"
}
```
2. Update `Schedule` value above scheduled action input payload:
```hcl
{
  "EndTime": null,
  "ResourceId": "service/tf-acc-test-12345/tf-acc-test-12345",
  "ScalableDimension": "ecs:service:DesiredCount",
  "ScalableTargetAction": null,
  "Schedule": "at(2023-10-04T10:10:59)",
  "ScheduledActionName": "tf-acc-test-12345",
  "ServiceNamespace": "ecs",
  "StartTime": null,
  "Timezone": null
}
```
stored state after update
```hcl
{
  "CreationTime": "2023-10-02T03:11:15.605Z",
  "EndTime": null,
  "ResourceId": "service/tf-acc-test-12345/tf-acc-test-12345",
  "ScalableDimension": "ecs:service:DesiredCount",
  "ScalableTargetAction": {
    "MaxCapacity": 5,
    "MinCapacity": 1
  },
  "Schedule": "at(2023-10-04T10:10:59)",
  "ScheduledActionARN": "arn:aws:autoscaling:ap-southeast-1:12345:scheduledAction:2ca2b6de-ea80-47cc-9131-0f58c3a38ef2:resource/ecs/service/tf-acc-test-12345/tf-acc-test-7236294745198118092:scheduledActionName/tf-acc-test-12345",
  "ScheduledActionName": "tf-acc-test-12345",
  "ServiceNamespace": "ecs",
  "StartTime": null,
  "Timezone": "UTC"
}
```
Somehow `StartTime` and `EndTime` has been override but other value like `ScalableTargetAction` doesn't get override by `null` value

### References

_No response_

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by yaput**
### Description

Initialize `StartTime` and `EndTime` for aws scheduled action parameter from current existing values.

### Relations

Closes #33708 
Closes #32616

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccAppAutoScalingScheduledAction_UpdateScheduleRetainStartAndEndTime_ecs PKG=appautoscaling
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/appautoscaling/... -v -count 1 -parallel 20 -run='TestAccAppAutoScalingScheduledAction_UpdateScheduleRetainStartAndEndTime_ecs'  -timeout 360m
=== RUN   TestAccAppAutoScalingScheduledAction_UpdateScheduleRetainStartAndEndTime_ecs
=== PAUSE TestAccAppAutoScalingScheduledAction_UpdateScheduleRetainStartAndEndTime_ecs
=== CONT  TestAccAppAutoScalingScheduledAction_UpdateScheduleRetainStartAndEndTime_ecs
--- PASS: TestAccAppAutoScalingScheduledAction_UpdateScheduleRetainStartAndEndTime_ecs (93.85s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/appautoscaling	95.967s
% make testacc TESTS=TestAccAppAutoScalingScheduledAction_UpdateStartAndEndTime_ecs PKG=appautoscaling
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/appautoscaling/... -v -count 1 -parallel 20 -run='TestAccAppAutoScalingScheduledAction_UpdateStartAndEndTime_ecs'  -timeout 360m
=== RUN   TestAccAppAutoScalingScheduledAction_UpdateStartAndEndTime_ecs
=== PAUSE TestAccAppAutoScalingScheduledAction_UpdateStartAndEndTime_ecs
=== CONT  TestAccAppAutoScalingScheduledAction_UpdateStartAndEndTime_ecs
--- PASS: TestAccAppAutoScalingScheduledAction_UpdateStartAndEndTime_ecs (88.49s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/appautoscaling	90.601s
%  make testacc TESTS=TestAccAppAutoScalingScheduledAction_AddStartTimeAndEndTimeAfterResourceCreated_ecs PKG=appautoscaling
TF_ACC=1 go test ./internal/service/appautoscaling/... -v -count 1 -parallel 20 -run='TestAccAppAutoScalingScheduledAction_AddStartTimeAndEndTimeAfterResourceCreated_ecs'  -timeout 360m
=== RUN   TestAccAppAutoScalingScheduledAction_AddStartTimeAndEndTimeAfterResourceCreated_ecs
=== PAUSE TestAccAppAutoScalingScheduledAction_AddStartTimeAndEndTimeAfterResourceCreated_ecs
=== CONT  TestAccAppAutoScalingScheduledAction_AddStartTimeAndEndTimeAfterResourceCreated_ecs
--- PASS: TestAccAppAutoScalingScheduledAction_AddStartTimeAndEndTimeAfterResourceCreated_ecs (73.79s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/appautoscaling	75.917s
```

### CODE REVIEW

File: internal/service/appautoscaling/scheduled_action.go [hunk 1]
```diff
@@ -112,12 +112,16 @@ func ResourceScheduledAction() *schema.Resource {
 func resourceScheduledActionPut(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
 	var diags diag.Diagnostics
 	conn := meta.(*conns.AWSClient).AppAutoScalingConn(ctx)
+	currentStartTime, _ := time.Parse(time.RFC3339, d.Get("start_time").(string))
+	currentEndTime, _ := time.Parse(time.RFC3339, d.Get("end_time").(string))
```
Comment (yaput) [inline internal/service/appautoscaling/scheduled_action.go:116]: To avoid missing `StartTime` and `EndTime` whenever we try to update existing `ScheduledAction` I tried to set existing value, but after this, use might need to explicitly set `StartTime` or `EndTime` to `""` or `null` to remove the value.

File: internal/service/appautoscaling/scheduled_action.go [hunk 2]
```diff
@@ -112,12 +112,16 @@ func ResourceScheduledAction() *schema.Resource {
...
 
 	input := &applicationautoscaling.PutScheduledActionInput{
 		ScheduledActionName: aws.String(d.Get("name").(string)),
 		ServiceNamespace:    aws.String(d.Get("service_namespace").(string)),
 		ResourceId:          aws.String(d.Get("resource_id").(string)),
 		ScalableDimension:   aws.String(d.Get("scalable_dimension").(string)),
+		StartTime:           aws.Time(currentStartTime),
+		EndTime:             aws.Time(currentEndTime),
```
Comment (yaput) [inline internal/service/appautoscaling/scheduled_action.go:124]: To avoid missing `StartTime` and `EndTime` whenever we try to update existing `ScheduledAction` I tried to set existing value, but after this, use might need to explicitly set `StartTime` or `EndTime` to `""` or `null` to remove the value.

File: internal/service/appautoscaling/scheduled_action.go [hunk 3]
```diff
@@ -120,6 +120,15 @@ func resourceScheduledActionPut(ctx context.Context, d *schema.ResourceData, met
...
 	}
 
+	currentStartTime := getTimeIfExist(d, "start_time")
+	if currentStartTime != nil {
+		input.StartTime = aws.Time(currentStartTime.(time.Time))
+	}
+	currentEndTime := getTimeIfExist(d, "end_time")
+	if currentEndTime != nil {
+		input.EndTime = aws.Time(currentEndTime.(time.Time))
+	}
```
Comment (yaput) [inline internal/service/appautoscaling/scheduled_action.go:130]: To avoid unexpected missing StartTime and EndTime whenever we try to update existing ScheduledAction I tried to set existing value if exist, but if it doesn't exist then it will behave like current behavior, but if previously there is a value, then it will carry it.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccAppAutoScalingScheduledAction_ecs' PKG=appautoscaling ACCTEST_PARALLELISM=3      
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.21.8 test ./internal/service/appautoscaling/... -v -count 1 -parallel 3  -run=TestAccAppAutoScalingScheduledAction_ecs -timeout 360m
=== RUN   TestAccAppAutoScalingScheduledAction_ecs
=== PAUSE TestAccAppAutoScalingScheduledAction_ecs
=== RUN   TestAccAppAutoScalingScheduledAction_ecsUpdateScheduleRetainStartAndEndTime
=== PAUSE TestAccAppAutoScalingScheduledAction_ecsUpdateScheduleRetainStartAndEndTime
=== RUN   TestAccAppAutoScalingScheduledAction_ecsUpdateStartAndEndTime
=== PAUSE TestAccAppAutoScalingScheduledAction_ecsUpdateStartAndEndTime
=== RUN   TestAccAppAutoScalingScheduledAction_ecsAddStartTimeAndEndTimeAfterResourceCreated
=== PAUSE TestAccAppAutoScalingScheduledAction_ecsAddStartTimeAndEndTimeAfterResourceCreated
=== CONT  TestAccAppAutoScalingScheduledAction_ecs
=== CONT  TestAccAppAutoScalingScheduledAction_ecsUpdateStartAndEndTime
=== CONT  TestAccAppAutoScalingScheduledAction_ecsAddStartTimeAndEndTimeAfterResourceCreated
--- PASS: TestAccAppAutoScalingScheduledAction_ecs (81.16s)
=== CONT  TestAccAppAutoScalingScheduledAction_ecsUpdateScheduleRetainStartAndEndTime
--- PASS: TestAccAppAutoScalingScheduledAction_ecsAddStartTimeAndEndTimeAfterResourceCreated (85.24s)
--- PASS: TestAccAppAutoScalingScheduledAction_ecsUpdateStartAndEndTime (85.34s)
--- PASS: TestAccAppAutoScalingScheduledAction_ecsUpdateScheduleRetainStartAndEndTime (79.32s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/appautoscaling	166.985s
```

**Comment by ewbankkit** [comment]
@yaput Thanks for the contribution :tada: :clap:.
