### PR TITLE
ec2: Add service-specific ErrorCheck

### LINKED ISSUE #18654: r/instance: GovCloud test failure: VolumeTypeNotAvailableInRegion
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The acceptance test `TestAccAWSInstance_EbsRootDevice_ModifyIOPS_Io2` fails with this error in GovCloud:

```
Error: Error launching source instance: VolumeTypeNotAvailableInRegion: Instance launch can not be fulfilled as 'io2' volumes are not supported in this region.
        	status code: 400, request id: 026626a3-c6da-4a77-ba7e-3bedc0dacc6d
        
          on terraform_plugin_test.tf line 22, in resource "aws_instance" "test":
          22: resource "aws_instance" "test" {
```

### Affected Resource(s)

* aws_instance

### References

* #0000

### PR DESCRIPTION
**Pull request by YakDriver**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #18654

Output from acceptance testing (GovCloud):

```
--- SKIP: TestAccAWSInstance_EbsRootDevice_ModifyIOPS_Io2 (11.13s)
```

Output from acceptance testing (commercial):

```
--- PASS: TestAccAWSInstance_EbsRootDevice_ModifyIOPS_Io2 (150.54s)
```

### CODE REVIEW

File: aws/resource_aws_instance_test.go [hunk 1]
```diff
@@ -32,6 +34,12 @@ func init() {
 	})
 }
 
+func testAccErrorCheckSkipEC2(t *testing.T) resource.ErrorCheckFunc {
+	return testAccErrorCheckSkipMessagesContaining(t,
+		"VolumeTypeNotAvailableInRegion: Instance launch can not be fulfilled",
```
Comment (bflad) [inline aws/resource_aws_instance_test.go:39]: Nit: Seems like the error code portion is descriptive enough in case the messaging changes

```suggestion
		"VolumeTypeNotAvailableInRegion",
```

**Review by bflad — APPROVED** [review]
Looks good to me 🚀
