### PR TITLE
tests/Synthetics: Fix invalid Lambda parameter in acceptance test failures

### LINKED ISSUE #23391: tests/synthetics: InvalidParameterValueException: The role defined for the function cannot be assumed by Lambda.
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Synthetics acceptance test fail intermittently because of the time that it takes IAM to propagate.

### Debug Output

```
=== CONT  TestAccSyntheticsCanary_runTracing
    canary_test.go:355: Step 1/4 error: Error running apply: exit status 1

        Error: error waiting for Synthetics Canary (tf-acc-test-cz8uatva) create: unexpected state 'ERROR', wanted target 'READY'. last error: CREATE_FAILED: The role defined for the function cannot be assumed by Lambda. (Service: AWSLambda; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 2dbbee1b-6d0e-4b7c-b13c-2a555872dc64; Proxy: null)

          with aws_synthetics_canary.test,
          on terraform_plugin_test.tf line 110, in resource "aws_synthetics_canary" "test":
         110: resource "aws_synthetics_canary" "test" {

--- FAIL: TestAccSyntheticsCanary_runTracing (253.05s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/synthetics 254.905s
FAIL
```

### Steps to Reproduce

```make testacc TESTS=TestAccSyntheticsCanary PKG=synthetics```

### References

* #0000

### PR DESCRIPTION
**Pull request by johnsonaj**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #23391 

### Description

* Retries failed canary creation to allow for IAM policy propagation.
 
Output from acceptance testing:

```
% make testacc TESTS=TestAccSyntheticsCanary PKG=synthetics
=== RUN   TestAccSyntheticsCanary_basic
=== PAUSE TestAccSyntheticsCanary_basic
=== RUN   TestAccSyntheticsCanary_artifactEncryption
=== PAUSE TestAccSyntheticsCanary_artifactEncryption
=== RUN   TestAccSyntheticsCanary_runtimeVersion
=== PAUSE TestAccSyntheticsCanary_runtimeVersion
=== RUN   TestAccSyntheticsCanary_startCanary
=== PAUSE TestAccSyntheticsCanary_startCanary
=== RUN   TestAccSyntheticsCanary_StartCanary_codeChanges
=== PAUSE TestAccSyntheticsCanary_StartCanary_codeChanges
=== RUN   TestAccSyntheticsCanary_s3
=== PAUSE TestAccSyntheticsCanary_s3
=== RUN   TestAccSyntheticsCanary_run
=== PAUSE TestAccSyntheticsCanary_run
=== RUN   TestAccSyntheticsCanary_runTracing
=== PAUSE TestAccSyntheticsCanary_runTracing
=== RUN   TestAccSyntheticsCanary_vpc
=== PAUSE TestAccSyntheticsCanary_vpc
=== RUN   TestAccSyntheticsCanary_tags
=== PAUSE TestAccSyntheticsCanary_tags
=== RUN   TestAccSyntheticsCanary_disappears
=== PAUSE TestAccSyntheticsCanary_disappears
=== CONT  TestAccSyntheticsCanary_basic
=== CONT  TestAccSyntheticsCanary_run
=== CONT  TestAccSyntheticsCanary_tags
=== CONT  TestAccSyntheticsCanary_runTracing
=== CONT  TestAccSyntheticsCanary_StartCanary_codeChanges
=== CONT  TestAccSyntheticsCanary_artifactEncryption
=== CONT  TestAccSyntheticsCanary_vpc
=== CONT  TestAccSyntheticsCanary_startCanary
=== CONT  TestAccSyntheticsCanary_s3
=== CONT  TestAccSyntheticsCanary_runtimeVersion
=== CONT  TestAccSyntheticsCanary_disappears
--- PASS: TestAccSyntheticsCanary_disappears (49.04s)
--- PASS: TestAccSyntheticsCanary_artifactEncryption (71.93s)
--- PASS: TestAccSyntheticsCanary_tags (92.03s)
--- PASS: TestAccSyntheticsCanary_s3 (92.79s)
--- PASS: TestAccSyntheticsCanary_startCanary (109.68s)
--- PASS: TestAccSyntheticsCanary_run (111.95s)
--- PASS: TestAccSyntheticsCanary_runtimeVersion (113.63s)
--- PASS: TestAccSyntheticsCanary_runTracing (118.51s)
--- PASS: TestAccSyntheticsCanary_basic (131.31s)
--- PASS: TestAccSyntheticsCanary_StartCanary_codeChanges (290.27s)
--- PASS: TestAccSyntheticsCanary_vpc (2176.74s)
PASS
```

### CODE REVIEW

File: internal/service/synthetics/retry.go [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+		Refresh: statusCanaryState(conn, d.Id()),
+		Timeout: canaryCreatedTimeout,
+	}
+
+	outputRaw, err := stateConf.WaitForState()
+	if output, ok := outputRaw.(*synthetics.Canary); ok {
+		if status := output.Status; aws.StringValue(status.State) == synthetics.CanaryStateError && aws.StringValue(status.StateReasonCode) == canaryCreateFail {
+			// delete canary because it is the only way to reprovision if in an error state
+			err = deleteCanary(conn, d.Id())
+			if err != nil {
```
Comment (ewbankkit) [inline internal/service/synthetics/retry.go:31]: Should we just `return err` if `err != nil`? If the canary couldn't be deleted is it worth trying to create it again?
Same for the other error checks in this block.

**Comment by ewbankkit** [comment]
```console
% make testacc TESTS=TestAccSyntheticsCanary_ PKG=synthetics
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/synthetics/... -v -count 1 -parallel 20 -run='TestAccSyntheticsCanary_'  -timeout 180m
=== RUN   TestAccSyntheticsCanary_basic
=== PAUSE TestAccSyntheticsCanary_basic
=== RUN   TestAccSyntheticsCanary_artifactEncryption
=== PAUSE TestAccSyntheticsCanary_artifactEncryption
=== RUN   TestAccSyntheticsCanary_runtimeVersion
=== PAUSE TestAccSyntheticsCanary_runtimeVersion
=== RUN   TestAccSyntheticsCanary_startCanary
=== PAUSE TestAccSyntheticsCanary_startCanary
=== RUN   TestAccSyntheticsCanary_StartCanary_codeChanges
=== PAUSE TestAccSyntheticsCanary_StartCanary_codeChanges
=== RUN   TestAccSyntheticsCanary_s3
=== PAUSE TestAccSyntheticsCanary_s3
=== RUN   TestAccSyntheticsCanary_run
=== PAUSE TestAccSyntheticsCanary_run
=== RUN   TestAccSyntheticsCanary_runTracing
=== PAUSE TestAccSyntheticsCanary_runTracing
=== RUN   TestAccSyntheticsCanary_vpc
=== PAUSE TestAccSyntheticsCanary_vpc
=== RUN   TestAccSyntheticsCanary_tags
=== PAUSE TestAccSyntheticsCanary_tags
=== RUN   TestAccSyntheticsCanary_disappears
=== PAUSE TestAccSyntheticsCanary_disappears
=== CONT  TestAccSyntheticsCanary_basic
=== CONT  TestAccSyntheticsCanary_run
=== CONT  TestAccSyntheticsCanary_startCanary
=== CONT  TestAccSyntheticsCanary_disappears
=== CONT  TestAccSyntheticsCanary_StartCanary_codeChanges
=== CONT  TestAccSyntheticsCanary_runtimeVersion
=== CONT  TestAccSyntheticsCanary_vpc
=== CONT  TestAccSyntheticsCanary_tags
=== CONT  TestAccSyntheticsCanary_runTracing
=== CONT  TestAccSyntheticsCanary_s3
=== CONT  TestAccSyntheticsCanary_artifactEncryption
--- PASS: TestAccSyntheticsCanary_disappears (61.70s)
--- PASS: TestAccSyntheticsCanary_s3 (65.49s)
=== CONT  TestAccSyntheticsCanary_StartCanary_codeChanges
    canary_test.go:224: Step 3/3 error: Error running apply: exit status 1
        
        Error: error stopping Synthetics Canary (tf-acc-test-jtkguqi7): ConflictException: Canary is in a state that can't be stopped: STOPPED
        
          with aws_synthetics_canary.test,
          on terraform_plugin_test.tf line 110, in resource "aws_synthetics_canary" "test":
         110: resource "aws_synthetics_canary" "test" {
        
=== CONT  TestAccSyntheticsCanary_startCanary
    canary_test.go:176: Step 3/4 error: Error running apply: exit status 1
        
        Error: error stopping Synthetics Canary (tf-acc-test-9nfyoxjh): ConflictException: Canary is in a state that can't be stopped: STOPPED
        
          with aws_synthetics_canary.test,
          on terraform_plugin_test.tf line 110, in resource "aws_synthetics_canary" "test":
         110: resource "aws_synthetics_canary" "test" {
        
=== CONT  TestAccSyntheticsCanary_StartCanary_codeChanges
    testing_new.go:70: Error running post-test destroy, there may be dangling resources: exit status 1
        
        Error: error stopping Synthetics Canary (tf-acc-test-jtkguqi7): ConflictException: Canary is in a state that can't be stopped: STOPPED
        
--- FAIL: TestAccSyntheticsCanary_StartCanary_codeChanges (74.97s)
=== CONT  TestAccSyntheticsCanary_startCanary
    testing_new.go:70: Error running post-test destroy, there may be dangling resources: exit status 1
        
        Error: error stopping Synthetics Canary (tf-acc-test-9nfyoxjh): ConflictException: Canary is in a state that can't be stopped: STOPPED
        
--- FAIL: TestAccSyntheticsCanary_startCanary (75.10s)
--- PASS: TestAccSyntheticsCanary_artifactEncryption (93.06s)
--- PASS: TestAccSyntheticsCanary_basic (107.19s)
--- PASS: TestAccSyntheticsCanary_tags (110.31s)
--- PASS: TestAccSyntheticsCanary_runTracing (111.80s)
--- PASS: TestAccSyntheticsCanary_runtimeVersion (116.66s)
--- PASS: TestAccSyntheticsCanary_run (125.78s)
--- PASS: TestAccSyntheticsCanary_vpc (2151.63s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/synthetics	2156.169s
FAIL
make: *** [testacc] Error 1
```

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.
