### PR TITLE
Initial implementation of self_managed_event_source for aws_lambda_event_source_mapping

### LINKED ISSUE #14042: 5 minutes wait to get an error message for aws_lambda_event_source_mapping
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v0.12.26
+ provider.aws v2.66.0

Your version of Terraform is out of date! The latest version
is 0.12.28. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

* aws_lambda_event_source_mapping
* aws_lambda_function
* aws_sqs_queue

### Terraform Configuration Files

```hcl
# No  "sqs:ReceiveMessage", "sqs:DeleteMessage", "sqs:GetQueueAttributes" permissions configured for the lambda
resource "aws_lambda_event_source_mapping" "this" {
  event_source_arn = aws_sqs_queue.this.arn
  function_name = aws_lambda_function.this.arn
  batch_size = 10
}
```
### Expected Behavior

Terraform should report an error right away.

### Actual Behavior
I needed to wait for 5 minutes until the error message was shown...
<details>
<summary> Output </summary>

```
aws_lambda_event_source_mapping.this: Creating...
aws_lambda_event_source_mapping.this: Still creating... [10s elapsed]
aws_lambda_event_source_mapping.this: Still creating... [20s elapsed]
aws_lambda_event_source_mapping.this: Still creating... [30s elapsed]
aws_lambda_event_source_mapping.this: Still creating... [40s elapsed]
aws_lambda_event_source_mapping.this: Still creating... [50s elapsed]
aws_lambda_event_source_mapping.this: Still creating... [1m0s elapsed]
aws_lambda_event_source_mapping.this: Still creating... [1m10s elapsed]
aws_lambda_event_source_mapping.this: Still creating... [1m20s elapsed]
aws_lambda_event_source_mapping.this: Still creating... [1m30s elapsed]
aws_lambda_event_source_mapping.this: Still creating... [1m40s elapsed]
aws_lambda_event_source_mapping.this: Still creating... [1m50s elapsed]
aws_lambda_event_source_mapping.this: Still creating... [2m0s elapsed]
aws_lambda_event_source_mapping.this: Still creating... [2m10s elapsed]
aws_lambda_event_source_mapping.this: Still creating... [2m20s elapsed]
aws_lambda_event_source_mapping.this: Still creating... [2m30s elapsed]
aws_lambda_event_source_mapping.this: Still creating... [2m40s elapsed]
aws_lambda_event_source_mapping.this: Still creating... [2m50s elapsed]
aws_lambda_event_source_mapping.this: Still creating... [3m0s elapsed]
aws_lambda_event_source_mapping.this: Still creating... [3m10s elapsed]
aws_lambda_event_source_mapping.this: Still creating... [3m20s elapsed]
aws_lambda_event_source_mapping.this: Still creating... [3m30s elapsed]
aws_lambda_event_source_mapping.this: Still creating... [3m40s elapsed]
aws_lambda_event_source_mapping.this: Still creating... [3m50s elapsed]
aws_lambda_event_source_mapping.this: Still creating... [4m0s elapsed]
aws_lambda_event_source_mapping.this: Still creating... [4m10s elapsed]
aws_lambda_event_source_mapping.this: Still creating... [4m20s elapsed]
aws_lambda_event_source_mapping.this: Still creating... [4m30s elapsed]
aws_lambda_event_source_mapping.this: Still creating... [4m40s elapsed]
aws_lambda_event_source_mapping.this: Still creating... [4m50s elapsed]

Error: Error creating Lambda event source mapping: InvalidParameterValueException: The provided execution role does not have permissions to call ReceiveMessage on SQS
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "71bf6150-ee25-4ad5-ac0f-9c51db59dffe"
  },
  Message_: "The provided execution role does not have permissions to call ReceiveMessage on SQS",
  Type: "User"
}
```

</details>

### Steps to Reproduce

1. `terraform apply`

### LINKED ISSUE #16074: AWS Lambda support for Amazon MQ for Apache ActiveMQ as an event source
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> AWS Lambda now supports Amazon MQ for Apache ActiveMQ as an event source

### New or Affected Resource(s)

* [`aws_lambda_event_source_mapping`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_event_source_mapping)

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
resource "aws_lambda_event_source_mapping" "example" {
  event_source_arn  = aws_mq_cluster.example.arn
  function_name     = aws_lambda_function.example.arn
  queues            = ["example"]

  source_access_configuration {
    type = "BASIC_AUTH"
    uri  = aws_secretsmanager_secret.example.arn
  }
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/11/aws-lambda-supports-amazon-mq-apache-activemq-event-source/).
[Blog post](https://aws.amazon.com/blogs/compute/using-amazon-mq-as-an-event-source-for-aws-lambda/).
[Developer Guide](https://docs.aws.amazon.com/lambda/latest/dg/with-mq.html).

Requires [AWS SDK v1.35.22](https://github.com/aws/aws-sdk-go/releases/tag/v1.35.22):

* https://github.com/hashicorp/terraform-provider-aws/pull/16071

Related: https://github.com/hashicorp/terraform-provider-aws/issues/14658.

### LINKED ISSUE #16785: AWS Lambda self-managed Apache Kafka event source
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> AWS Lambda now allows customers to build applications that can be triggered by messages in an Apache Kafka cluster hosted on any infrastructure.

### New or Affected Resource(s)

* [`aws_lambda_event_source_mapping`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_event_source_mapping)

### Potential Terraform Configuration

```hcl
resource "aws_lambda_event_source_mapping" "example" {
  function_name = aws_lambda_function.example.arn

  self_managed_event_source {
    endpoints = {
      KAFKA_BOOTSTRAP_SERVERS = ["abc3.xyz.com:9092,abc2.xyz.com:9092"]
    }
  }

  source_access_configuration {
    type = "VPC_SUBNET"
    uri  = "subnet:${aws_subnet.example.id}"
  }

  topics = ["example"]
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/12/aws-lambda-now-supports-self-managed-apache-kafka-as-an-event-source/).
[Blog post](https://aws.amazon.com/blogs/compute/using-self-hosted-apache-kafka-as-an-event-source-for-aws-lambda/).
[Developer Guide](https://docs.aws.amazon.com/lambda/latest/dg/kafka-smaa.html).

Requires [AWS SDK v1.36.9](https://github.com/aws/aws-sdk-go/releases/tag/v1.36.9):

* #16783

Related:

* #14658
* #14746

### LINKED ISSUE #16786: AWS Lambda streaming analytics calculations
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> Customers can now use AWS Lambda to build analytics workloads for their Amazon Kinesis or Amazon DynamoDB Streams.

### New or Affected Resource(s)

* [`aws_lambda_event_source_mapping`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_event_source_mapping)

### Potential Terraform Configuration

```hcl
resource "aws_lambda_event_source_mapping" "example" {
  function_name = aws_lambda_function.example.arn

  tumbling_window_in_seconds = 30
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/12/aws-lambda-easier-build-analytics-amazon-kinesis-amazon-dynamodb-streams/).
[Blog post](https://aws.amazon.com/blogs/compute/using-aws-lambda-for-streaming-analytics/).
[Developer Guide](https://docs.aws.amazon.com/lambda/latest/dg/with-kinesis.html#services-kinesis-windows).

Requires [AWS SDK v1.36.9](https://github.com/aws/aws-sdk-go/releases/tag/v1.36.9):

* #16783

### LINKED ISSUE #16787: AWS Lambda checkpointing for Amazon Kinesis and Amazon DynamoDB Streams
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> AWS Lambda now allows customers to automatically checkpoint records that have been successfully processed for Amazon Kinesis and Amazon DynamoDB Streams, using a new parameter, FunctionResponseType.

### New or Affected Resource(s)

* [`aws_lambda_event_source_mapping`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_event_source_mapping)

### Potential Terraform Configuration

```hcl
resource "aws_lambda_event_source_mapping" "example" {
  function_name = aws_lambda_function.example.arn

  function_response_types = ["ReportBatchItemFailures"]
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/12/aws-lambda-launches-checkpointing-for-amazon-kinesis-and-amazon-dynamodb-streams/).
[Blog post](https://aws.amazon.com/blogs/compute/optimizing-batch-processing-with-custom-checkpoints-in-aws-lambda/).
[Developer Guide](https://docs.aws.amazon.com/lambda/latest/dg/with-ddb.html#services-ddb-batchfailurereporting).

Requires [AWS SDK v1.36.9](https://github.com/aws/aws-sdk-go/releases/tag/v1.36.9):

* #16783

### LINKED ISSUE #17825: AWS Lambda support for AWS MSK with SASL/SCRAM as an event source
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> Amazon MSK now supports SASL/SCRAM authentication with usernames and passwords secured by AWS Secrets Manager

### New or Affected Resource(s)

* [aws_lambda_event_source_mapping](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_event_source_mapping)

### Potential Terraform Configuration

```hcl
resource "aws_lambda_event_source_mapping" "example" {
  event_source_arn  = aws_msk_cluster.example.arn
  function_name     = aws_lambda_function.example.arn
  topics            = ["Example"]
  starting_position = "LATEST"

  source_access_configuration {
    type = "SASL_SCRAM_512_AUTH"
    uri  = aws_secretsmanager_secret.example.arn
  }
}
```

### References

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2020/09/amazon-msk-now-supports-sasl-scram-authentication-with-usernames-and-passwords-secured-by-aws-secrets-manager/)
* [Blog post](https://aws.amazon.com/blogs/compute/using-amazon-msk-as-an-event-source-for-aws-lambda/)
* [SASL/SCRAM Authentication for event source mapping](https://docs.aws.amazon.com/lambda/latest/dg/msk-permissions.html)
* [Adding MSK cluster as an event source](https://docs.aws.amazon.com/lambda/latest/dg/services-msk-topic-add.html)

### LINKED ISSUE #18099: [SQS and Lambda] Lambda function not properly deployed because queue visibility timeout is less than Function timeout
AWS lambda is not properly deployed because queue visibility timeout is less than Lambda Function timeout

### Terraform CLI and Terraform AWS Provider Version
0.13.6

### Affected Resource(s)

aws_lambda

### Terraform Configuration Files

sqs queue resource configuration:

resource "aws_sqs_queue" "queue" {
  name                       = "sqs-qeue"
  message_retention_seconds  = 1209600
  visibility_timeout_seconds = 400
}

lambda function configuration:

resource "aws_lambda_function" "document_processing_lambda" {
  filename      = "lambda_function_payload.zip"
  function_name = "lambda_function_name"
  role          = aws_iam_role.iam_for_lambda.arn
  handler       = "exports.test"
  source_code_hash = filebase64sha256("lambda_function_payload.zip")

  runtime = "java11"

  memory_size  = "2048"
  timeout = "900"

  environment {
    variables = {
      env= "staging"
    }
  }
}

aws_lambda_event_source_mapping

resource "aws_lambda_event_source_mapping" "lambda_sqs" {
  depends_on       = [aws_sqs_queue.queue]
  event_source_arn = aws_sqs_queue.queue.arn
  function_name    = aws_lambda_function.document_processing_lambda.name
  batch_size       = 10
}

### Expected Behavior

This error should be thrown when deploying:
Error: Error creating Lambda event source mapping: InvalidParameterValueException: Queue visibility timeout: 400 seconds is less than Function timeout: 900 seconds

### Actual Behavior

No error is thrown at the first deployment and the lambda function is deployed with an incoherent state and does not consume messages from the SQS queue, all this happens silently and messages were lost from the queue because no error is thrown.

### Steps to Reproduce

1. `terraform apply`

### PR DESCRIPTION
**Pull request by delbaeth**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #16785.
Closes #17825.
Closes #16786.
Closes #16787.
Closes #14042.
Closes #16074.
Closes #18099.

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

make testacc TESTARGS='-run=TestAccAWSLambdaEventSourceMapping_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSLambdaEventSourceMapping_ -timeout 180m
=== RUN   TestAccAWSLambdaEventSourceMapping_Kinesis_basic
=== PAUSE TestAccAWSLambdaEventSourceMapping_Kinesis_basic
=== RUN   TestAccAWSLambdaEventSourceMapping_SQS_basic
=== PAUSE TestAccAWSLambdaEventSourceMapping_SQS_basic
=== RUN   TestAccAWSLambdaEventSourceMapping_DynamoDB_basic
=== PAUSE TestAccAWSLambdaEventSourceMapping_DynamoDB_basic
=== RUN   TestAccAWSLambdaEventSourceMapping_SQS_BatchWindow
=== PAUSE TestAccAWSLambdaEventSourceMapping_SQS_BatchWindow
=== RUN   TestAccAWSLambdaEventSourceMapping_disappears
=== PAUSE TestAccAWSLambdaEventSourceMapping_disappears
=== RUN   TestAccAWSLambdaEventSourceMapping_SQS_changesInEnabledAreDetected
=== PAUSE TestAccAWSLambdaEventSourceMapping_SQS_changesInEnabledAreDetected
=== RUN   TestAccAWSLambdaEventSourceMapping_Kinesis_StartingPositionTimestamp
=== PAUSE TestAccAWSLambdaEventSourceMapping_Kinesis_StartingPositionTimestamp
=== RUN   TestAccAWSLambdaEventSourceMapping_Kinesis_BatchWindow
=== PAUSE TestAccAWSLambdaEventSourceMapping_Kinesis_BatchWindow
=== RUN   TestAccAWSLambdaEventSourceMapping_Kinesis_ParallelizationFactor
=== PAUSE TestAccAWSLambdaEventSourceMapping_Kinesis_ParallelizationFactor
=== RUN   TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRetryAttempts
=== PAUSE TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRetryAttempts
=== RUN   TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRetryAttemptsZero
=== PAUSE TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRetryAttemptsZero
=== RUN   TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRetryAttemptsNegativeOne
=== PAUSE TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRetryAttemptsNegativeOne
=== RUN   TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRecordAgeInSeconds
=== PAUSE TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRecordAgeInSeconds
=== RUN   TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRecordAgeInSecondsNegativeOne
=== PAUSE TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRecordAgeInSecondsNegativeOne
=== RUN   TestAccAWSLambdaEventSourceMapping_Kinesis_BisectBatch
=== PAUSE TestAccAWSLambdaEventSourceMapping_Kinesis_BisectBatch
=== RUN   TestAccAWSLambdaEventSourceMapping_Kinesis_DestinationConfig
=== PAUSE TestAccAWSLambdaEventSourceMapping_Kinesis_DestinationConfig
=== RUN   TestAccAWSLambdaEventSourceMapping_MSK
=== PAUSE TestAccAWSLambdaEventSourceMapping_MSK
=== RUN   TestAccAWSLambdaEventSourceMapping_SelfManagedKafka
=== PAUSE TestAccAWSLambdaEventSourceMapping_SelfManagedKafka
=== CONT  TestAccAWSLambdaEventSourceMapping_Kinesis_basic
=== CONT  TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRetryAttemptsZero
=== CONT  TestAccAWSLambdaEventSourceMapping_Kinesis_DestinationConfig
=== CONT  TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRetryAttempts
=== CONT  TestAccAWSLambdaEventSourceMapping_Kinesis_ParallelizationFactor
=== CONT  TestAccAWSLambdaEventSourceMapping_Kinesis_BatchWindow
=== CONT  TestAccAWSLambdaEventSourceMapping_Kinesis_StartingPositionTimestamp
=== CONT  TestAccAWSLambdaEventSourceMapping_Kinesis_BisectBatch
=== CONT  TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRecordAgeInSecondsNegativeOne
=== CONT  TestAccAWSLambdaEventSourceMapping_disappears
=== CONT  TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRecordAgeInSeconds
=== CONT  TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRetryAttemptsNegativeOne
=== CONT  TestAccAWSLambdaEventSourceMapping_SQS_basic
=== CONT  TestAccAWSLambdaEventSourceMapping_SelfManagedKafka
=== CONT  TestAccAWSLambdaEventSourceMapping_MSK
=== CONT  TestAccAWSLambdaEventSourceMapping_SQS_changesInEnabledAreDetected
=== CONT  TestAccAWSLambdaEventSourceMapping_SQS_BatchWindow
=== CONT  TestAccAWSLambdaEventSourceMapping_DynamoDB_basic
--- PASS: TestAccAWSLambdaEventSourceMapping_Kinesis_StartingPositionTimestamp (70.50s)
--- PASS: TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRetryAttempts (84.91s)
--- PASS: TestAccAWSLambdaEventSourceMapping_Kinesis_BatchWindow (86.73s)
--- PASS: TestAccAWSLambdaEventSourceMapping_Kinesis_BisectBatch (101.49s)
--- PASS: TestAccAWSLambdaEventSourceMapping_Kinesis_DestinationConfig (109.31s)
--- PASS: TestAccAWSLambdaEventSourceMapping_SQS_changesInEnabledAreDetected (114.31s)
--- PASS: TestAccAWSLambdaEventSourceMapping_DynamoDB_basic (116.90s)
--- PASS: TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRetryAttemptsNegativeOne (118.53s)
--- PASS: TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRecordAgeInSecondsNegativeOne (120.56s)
--- PASS: TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRecordAgeInSeconds (131.24s)
--- PASS: TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRetryAttemptsZero (131.27s)
--- PASS: TestAccAWSLambdaEventSourceMapping_SQS_BatchWindow (133.67s)
--- PASS: TestAccAWSLambdaEventSourceMapping_Kinesis_ParallelizationFactor (148.18s)
--- PASS: TestAccAWSLambdaEventSourceMapping_disappears (157.83s)
--- PASS: TestAccAWSLambdaEventSourceMapping_Kinesis_basic (175.54s)
--- PASS: TestAccAWSLambdaEventSourceMapping_SQS_basic (220.19s)
--- PASS: TestAccAWSLambdaEventSourceMapping_SelfManagedKafka (391.35s)
--- PASS: TestAccAWSLambdaEventSourceMapping_MSK (1083.75s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	1085.614s
```

### CODE REVIEW

File: aws/resource_aws_lambda_event_source_mapping.go [hunk 1]
```diff
@@ -156,6 +163,66 @@ func resourceAwsLambdaEventSourceMapping() *schema.Resource {
 					},
 				},
 			},
+			/*
```
Comment (delbaeth) [inline aws/resource_aws_lambda_event_source_mapping.go:166]: The suggested format for this from @ewbankkit from issue #16785 was:

```
  self_managed_event_source {
    endpoints = {
      KAFKA_BOOTSTRAP_SERVERS = ["abc3.xyz.com:9092", "abc2.xyz.com:9092"]
    }
  }
```

I was unable to make this work.  The parsing of the terraform file would panic as soon as I tried to make
the map value into a list.  I saw some references that TypeMap could only have primitive elements.  If that
isn't the case, I would love to know how to make this work.

File: aws/resource_aws_lambda_event_source_mapping_test.go [hunk 2]
```diff
@@ -48,11 +48,13 @@ func TestAccAWSLambdaEventSourceMapping_Kinesis_basic(t *testing.T) {
 				PlanOnly: true,
 				Config:   testAccAWSLambdaEventSourceMappingConfigKinesisBatchSize(rName, "null"),
 			},
-			{
-				ResourceName:      resourceName,
-				ImportState:       true,
-				ImportStateVerify: true,
-			},
+			/*
```
Comment (delbaeth) [inline aws/resource_aws_lambda_event_source_mapping_test.go:51]: This test will fail if the alphabetical order of the subnets is different than how AWS sorts them.

File: aws/resource_aws_lambda_event_source_mapping.go (hunk 1 above)
Comment (ewbankkit) [reply aws/resource_aws_lambda_event_source_mapping.go:166]: @delbaeth Yes, that is a limitation in the current Terraform Provider type system.
The underlying AWS API type `map[string][]*string` is rarely used and the only place I can find where we are using it currently is in the `aws_budgets_budget` resource's `cost_filters` attribute. There it looks like the list of strings is handled as a comma-separated single string, so the equivalent would be

```hcl
self_managed_event_source {
  endpoints = {
    KAFKA_BOOTSTRAP_SERVERS = "abc3.xyz.com:9092,abc2.xyz.com:9092"
  }
}
```

and the resource handling code will have to do the `strings.Split` and `strings.Join`.
What do you think?

Comment (delbaeth) [reply aws/resource_aws_lambda_event_source_mapping.go:166]: I implemented it that way as well.  Happy to go back to it.  The comma separated list is standard for bootstrap brokers
anyway.

The reason I switched was the API seemed to be intended for generic use
and might at some point be used for something other than kafka.  In that case
the choice of using a comma as the separator might not work as well.
If I needed special handling for the kafka case I figured I might as well
just define it explicitly.

Anyway, none of the implementations seemed great.  I will go back to the comma separated list.

File: aws/resource_aws_lambda_event_source_mapping.go [hunk 3]
```diff
@@ -34,7 +34,7 @@ func resourceAwsLambdaEventSourceMapping() *schema.Resource {
 		Schema: map[string]*schema.Schema{
 			"event_source_arn": {
 				Type:     schema.TypeString,
-				Required: true,
+				Optional: true,
```
Comment (delbaeth) [inline aws/resource_aws_lambda_event_source_mapping.go:37]: I needed to make event_source_arn and self_managed_event_source both optional but one of the two needs to be set.
Is there some place where I should be validating this or should I leave it to the AWS API call failing?

Comment (ewbankkit) [reply aws/resource_aws_lambda_event_source_mapping.go:37]: You'll want to use the `ExactlyOneOf` property.
Make `event_source_arn` and `self_managed_event_source` `Optional: true` and then add `ExactlyOneOf: []string{"event_source_arn", "self_managed_event_source"}` to them both.

**Comment by delbaeth** [comment]
Anything else I should modify before opening this for review?

**Comment by ewbankkit** [comment]
@delbaeth This is looking great.
The only comment I have for now is to move the new _flatten_ and _expand_ functions from `structure.go` into `resource_aws_lambda_event_source_mapping.go` (we want to avoid adding new code to that file).

**Comment by delbaeth** [comment]
Anything on this waiting on me?  I understand if it is just waiting for someone to get time to look at it but I wouldn't want it to be blocked waiting for me.

**Comment by ewbankkit** [comment]
@delbaeth No, everything is great from your side.
I added some additional commits to address some other new features in this resource.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

##### Commercial

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSLambdaEventSourceMapping_'                          
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSLambdaEventSourceMapping_ -timeout 180m
=== RUN   TestAccAWSLambdaEventSourceMapping_Kinesis_basic
=== PAUSE TestAccAWSLambdaEventSourceMapping_Kinesis_basic
=== RUN   TestAccAWSLambdaEventSourceMapping_SQS_basic
=== PAUSE TestAccAWSLambdaEventSourceMapping_SQS_basic
=== RUN   TestAccAWSLambdaEventSourceMapping_DynamoDB_basic
=== PAUSE TestAccAWSLambdaEventSourceMapping_DynamoDB_basic
=== RUN   TestAccAWSLambdaEventSourceMapping_DynamoDB_FunctionResponseTypes
=== PAUSE TestAccAWSLambdaEventSourceMapping_DynamoDB_FunctionResponseTypes
=== RUN   TestAccAWSLambdaEventSourceMapping_SQS_BatchWindow
=== PAUSE TestAccAWSLambdaEventSourceMapping_SQS_BatchWindow
=== RUN   TestAccAWSLambdaEventSourceMapping_disappears
=== PAUSE TestAccAWSLambdaEventSourceMapping_disappears
=== RUN   TestAccAWSLambdaEventSourceMapping_SQS_changesInEnabledAreDetected
=== PAUSE TestAccAWSLambdaEventSourceMapping_SQS_changesInEnabledAreDetected
=== RUN   TestAccAWSLambdaEventSourceMapping_Kinesis_StartingPositionTimestamp
=== PAUSE TestAccAWSLambdaEventSourceMapping_Kinesis_StartingPositionTimestamp
=== RUN   TestAccAWSLambdaEventSourceMapping_Kinesis_BatchWindow
=== PAUSE TestAccAWSLambdaEventSourceMapping_Kinesis_BatchWindow
=== RUN   TestAccAWSLambdaEventSourceMapping_Kinesis_ParallelizationFactor
=== PAUSE TestAccAWSLambdaEventSourceMapping_Kinesis_ParallelizationFactor
=== RUN   TestAccAWSLambdaEventSourceMapping_Kinesis_TumblingWindowInSeconds
=== PAUSE TestAccAWSLambdaEventSourceMapping_Kinesis_TumblingWindowInSeconds
=== RUN   TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRetryAttempts
=== PAUSE TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRetryAttempts
=== RUN   TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRetryAttemptsZero
=== PAUSE TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRetryAttemptsZero
=== RUN   TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRetryAttemptsNegativeOne
=== PAUSE TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRetryAttemptsNegativeOne
=== RUN   TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRecordAgeInSeconds
=== PAUSE TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRecordAgeInSeconds
=== RUN   TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRecordAgeInSecondsNegativeOne
=== PAUSE TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRecordAgeInSecondsNegativeOne
=== RUN   TestAccAWSLambdaEventSourceMapping_Kinesis_BisectBatch
=== PAUSE TestAccAWSLambdaEventSourceMapping_Kinesis_BisectBatch
=== RUN   TestAccAWSLambdaEventSourceMapping_Kinesis_DestinationConfig
=== PAUSE TestAccAWSLambdaEventSourceMapping_Kinesis_DestinationConfig
=== RUN   TestAccAWSLambdaEventSourceMapping_MSK
=== PAUSE TestAccAWSLambdaEventSourceMapping_MSK
=== RUN   TestAccAWSLambdaEventSourceMapping_SelfManagedKafka
=== PAUSE TestAccAWSLambdaEventSourceMapping_SelfManagedKafka
=== RUN   TestAccAWSLambdaEventSourceMapping_ActiveMQ
=== PAUSE TestAccAWSLambdaEventSourceMapping_ActiveMQ
=== CONT  TestAccAWSLambdaEventSourceMapping_Kinesis_basic
=== CONT  TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRetryAttempts
=== CONT  TestAccAWSLambdaEventSourceMapping_Kinesis_TumblingWindowInSeconds
=== CONT  TestAccAWSLambdaEventSourceMapping_DynamoDB_basic
=== CONT  TestAccAWSLambdaEventSourceMapping_SQS_changesInEnabledAreDetected
=== CONT  TestAccAWSLambdaEventSourceMapping_Kinesis_BisectBatch
=== CONT  TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRecordAgeInSecondsNegativeOne
=== CONT  TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRecordAgeInSeconds
=== CONT  TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRetryAttemptsNegativeOne
=== CONT  TestAccAWSLambdaEventSourceMapping_Kinesis_DestinationConfig
=== CONT  TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRetryAttemptsZero
=== CONT  TestAccAWSLambdaEventSourceMapping_ActiveMQ
=== CONT  TestAccAWSLambdaEventSourceMapping_SelfManagedKafka
=== CONT  TestAccAWSLambdaEventSourceMapping_Kinesis_ParallelizationFactor
=== CONT  TestAccAWSLambdaEventSourceMapping_MSK
=== CONT  TestAccAWSLambdaEventSourceMapping_DynamoDB_FunctionResponseTypes
=== CONT  TestAccAWSLambdaEventSourceMapping_Kinesis_BatchWindow
=== CONT  TestAccAWSLambdaEventSourceMapping_Kinesis_StartingPositionTimestamp
=== CONT  TestAccAWSLambdaEventSourceMapping_disappears
=== CONT  TestAccAWSLambdaEventSourceMapping_SQS_basic
--- PASS: TestAccAWSLambdaEventSourceMapping_SQS_changesInEnabledAreDetected (93.20s)
=== CONT  TestAccAWSLambdaEventSourceMapping_SQS_BatchWindow
--- PASS: TestAccAWSLambdaEventSourceMapping_Kinesis_TumblingWindowInSeconds (96.02s)
--- PASS: TestAccAWSLambdaEventSourceMapping_Kinesis_BisectBatch (96.89s)
--- PASS: TestAccAWSLambdaEventSourceMapping_DynamoDB_FunctionResponseTypes (105.36s)
--- PASS: TestAccAWSLambdaEventSourceMapping_Kinesis_BatchWindow (107.82s)
--- PASS: TestAccAWSLambdaEventSourceMapping_disappears (117.07s)
--- PASS: TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRecordAgeInSecondsNegativeOne (120.79s)
--- PASS: TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRetryAttemptsZero (128.37s)
--- PASS: TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRecordAgeInSeconds (128.51s)
--- PASS: TestAccAWSLambdaEventSourceMapping_DynamoDB_basic (133.70s)
--- PASS: TestAccAWSLambdaEventSourceMapping_Kinesis_StartingPositionTimestamp (136.19s)
--- PASS: TestAccAWSLambdaEventSourceMapping_Kinesis_DestinationConfig (137.43s)
--- PASS: TestAccAWSLambdaEventSourceMapping_Kinesis_ParallelizationFactor (156.26s)
--- PASS: TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRetryAttemptsNegativeOne (175.02s)
--- PASS: TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRetryAttempts (183.74s)
--- PASS: TestAccAWSLambdaEventSourceMapping_SelfManagedKafka (185.37s)
--- PASS: TestAccAWSLambdaEventSourceMapping_Kinesis_basic (189.29s)
--- PASS: TestAccAWSLambdaEventSourceMapping_SQS_BatchWindow (111.32s)
--- PASS: TestAccAWSLambdaEventSourceMapping_SQS_basic (229.18s)
--- PASS: TestAccAWSLambdaEventSourceMapping_ActiveMQ (1300.75s)
--- PASS: TestAccAWSLambdaEventSourceMapping_MSK (2011.24s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	2014.715s
```

##### GovCloud

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSLambdaEventSourceMapping_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSLambdaEventSourceMapping_ -timeout 180m
=== RUN   TestAccAWSLambdaEventSourceMapping_Kinesis_basic
=== PAUSE TestAccAWSLambdaEventSourceMapping_Kinesis_basic
=== RUN   TestAccAWSLambdaEventSourceMapping_SQS_basic
=== PAUSE TestAccAWSLambdaEventSourceMapping_SQS_basic
=== RUN   TestAccAWSLambdaEventSourceMapping_DynamoDB_basic
=== PAUSE TestAccAWSLambdaEventSourceMapping_DynamoDB_basic
=== RUN   TestAccAWSLambdaEventSourceMapping_DynamoDB_FunctionResponseTypes
=== PAUSE TestAccAWSLambdaEventSourceMapping_DynamoDB_FunctionResponseTypes
=== RUN   TestAccAWSLambdaEventSourceMapping_SQS_BatchWindow
=== PAUSE TestAccAWSLambdaEventSourceMapping_SQS_BatchWindow
=== RUN   TestAccAWSLambdaEventSourceMapping_disappears
=== PAUSE TestAccAWSLambdaEventSourceMapping_disappears
=== RUN   TestAccAWSLambdaEventSourceMapping_SQS_changesInEnabledAreDetected
=== PAUSE TestAccAWSLambdaEventSourceMapping_SQS_changesInEnabledAreDetected
=== RUN   TestAccAWSLambdaEventSourceMapping_Kinesis_StartingPositionTimestamp
=== PAUSE TestAccAWSLambdaEventSourceMapping_Kinesis_StartingPositionTimestamp
=== RUN   TestAccAWSLambdaEventSourceMapping_Kinesis_BatchWindow
=== PAUSE TestAccAWSLambdaEventSourceMapping_Kinesis_BatchWindow
=== RUN   TestAccAWSLambdaEventSourceMapping_Kinesis_ParallelizationFactor
=== PAUSE TestAccAWSLambdaEventSourceMapping_Kinesis_ParallelizationFactor
=== RUN   TestAccAWSLambdaEventSourceMapping_Kinesis_TumblingWindowInSeconds
=== PAUSE TestAccAWSLambdaEventSourceMapping_Kinesis_TumblingWindowInSeconds
=== RUN   TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRetryAttempts
=== PAUSE TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRetryAttempts
=== RUN   TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRetryAttemptsZero
=== PAUSE TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRetryAttemptsZero
=== RUN   TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRetryAttemptsNegativeOne
=== PAUSE TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRetryAttemptsNegativeOne
=== RUN   TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRecordAgeInSeconds
=== PAUSE TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRecordAgeInSeconds
=== RUN   TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRecordAgeInSecondsNegativeOne
=== PAUSE TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRecordAgeInSecondsNegativeOne
=== RUN   TestAccAWSLambdaEventSourceMapping_Kinesis_BisectBatch
=== PAUSE TestAccAWSLambdaEventSourceMapping_Kinesis_BisectBatch
=== RUN   TestAccAWSLambdaEventSourceMapping_Kinesis_DestinationConfig
=== PAUSE TestAccAWSLambdaEventSourceMapping_Kinesis_DestinationConfig
=== RUN   TestAccAWSLambdaEventSourceMapping_MSK
=== PAUSE TestAccAWSLambdaEventSourceMapping_MSK
=== RUN   TestAccAWSLambdaEventSourceMapping_SelfManagedKafka
=== PAUSE TestAccAWSLambdaEventSourceMapping_SelfManagedKafka
=== RUN   TestAccAWSLambdaEventSourceMapping_ActiveMQ
=== PAUSE TestAccAWSLambdaEventSourceMapping_ActiveMQ
=== CONT  TestAccAWSLambdaEventSourceMapping_Kinesis_basic
=== CONT  TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRetryAttemptsNegativeOne
=== CONT  TestAccAWSLambdaEventSourceMapping_SelfManagedKafka
=== CONT  TestAccAWSLambdaEventSourceMapping_disappears
=== CONT  TestAccAWSLambdaEventSourceMapping_Kinesis_BatchWindow
=== CONT  TestAccAWSLambdaEventSourceMapping_SQS_changesInEnabledAreDetected
=== CONT  TestAccAWSLambdaEventSourceMapping_MSK
=== CONT  TestAccAWSLambdaEventSourceMapping_ActiveMQ
=== CONT  TestAccAWSLambdaEventSourceMapping_Kinesis_DestinationConfig
=== CONT  TestAccAWSLambdaEventSourceMapping_Kinesis_BisectBatch
=== CONT  TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRecordAgeInSecondsNegativeOne
=== CONT  TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRecordAgeInSeconds
=== CONT  TestAccAWSLambdaEventSourceMapping_Kinesis_StartingPositionTimestamp
=== CONT  TestAccAWSLambdaEventSourceMapping_Kinesis_ParallelizationFactor
=== CONT  TestAccAWSLambdaEventSourceMapping_SQS_BatchWindow
=== CONT  TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRetryAttemptsZero
=== CONT  TestAccAWSLambdaEventSourceMapping_Kinesis_TumblingWindowInSeconds
=== CONT  TestAccAWSLambdaEventSourceMapping_DynamoDB_basic
=== CONT  TestAccAWSLambdaEventSourceMapping_DynamoDB_FunctionResponseTypes
=== CONT  TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRetryAttempts
=== CONT  TestAccAWSLambdaEventSourceMapping_ActiveMQ
    provider_test.go:734: skipping tests; partition aws-us-gov does not support mq service
--- SKIP: TestAccAWSLambdaEventSourceMapping_ActiveMQ (1.85s)
=== CONT  TestAccAWSLambdaEventSourceMapping_SQS_basic
--- PASS: TestAccAWSLambdaEventSourceMapping_SQS_BatchWindow (67.60s)
--- PASS: TestAccAWSLambdaEventSourceMapping_SQS_changesInEnabledAreDetected (95.02s)
--- PASS: TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRecordAgeInSecondsNegativeOne (95.93s)
--- PASS: TestAccAWSLambdaEventSourceMapping_Kinesis_StartingPositionTimestamp (97.94s)
=== CONT  TestAccAWSLambdaEventSourceMapping_SelfManagedKafka
    provider_test.go:1103: skipping test for aws-us-gov/us-gov-west-1: Error running apply: exit status 1
        2021/06/01 12:01:42 [DEBUG] Using modified User-Agent: Terraform/0.12.31 HashiCorp-terraform-exec/0.13.3
        
        Error: error creating Lambda Event Source Mapping (Self-Managed Apache Kafka): InvalidParameterValueException: Unsupported source arn : null
        {
          RespMetadata: {
            StatusCode: 400,
            RequestID: "97da7f44-b272-445b-aeea-f80fc9f5a82f"
          },
          Message_: "Unsupported source arn : null",
          Type: "User"
        }
        
          on terraform_plugin_test.tf line 100, in resource "aws_lambda_event_source_mapping" "test":
         100: resource "aws_lambda_event_source_mapping" "test" {
        
        
--- SKIP: TestAccAWSLambdaEventSourceMapping_SelfManagedKafka (114.89s)
--- PASS: TestAccAWSLambdaEventSourceMapping_Kinesis_DestinationConfig (124.12s)
--- PASS: TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRetryAttemptsZero (127.48s)
--- PASS: TestAccAWSLambdaEventSourceMapping_Kinesis_BatchWindow (129.25s)
--- PASS: TestAccAWSLambdaEventSourceMapping_Kinesis_ParallelizationFactor (136.89s)
--- PASS: TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRetryAttempts (150.24s)
--- PASS: TestAccAWSLambdaEventSourceMapping_DynamoDB_basic (152.62s)
--- PASS: TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRecordAgeInSeconds (163.46s)
--- PASS: TestAccAWSLambdaEventSourceMapping_Kinesis_MaximumRetryAttemptsNegativeOne (186.47s)
--- PASS: TestAccAWSLambdaEventSourceMapping_Kinesis_BisectBatch (188.61s)
--- PASS: TestAccAWSLambdaEventSourceMapping_DynamoDB_FunctionResponseTypes (191.33s)
--- PASS: TestAccAWSLambdaEventSourceMapping_Kinesis_basic (195.31s)
--- PASS: TestAccAWSLambdaEventSourceMapping_Kinesis_TumblingWindowInSeconds (200.92s)
--- PASS: TestAccAWSLambdaEventSourceMapping_disappears (204.50s)
--- PASS: TestAccAWSLambdaEventSourceMapping_SQS_basic (207.21s)
=== CONT  TestAccAWSLambdaEventSourceMapping_MSK
    provider_test.go:1103: skipping test for aws-us-gov/us-gov-west-1: Error running apply: exit status 1
        2021/06/01 12:01:44 [DEBUG] Using modified User-Agent: Terraform/0.12.31 HashiCorp-terraform-exec/0.13.3
        
        Error: error creating Lambda Event Source Mapping (arn:aws-us-gov:kafka:us-gov-west-1:357342307427:cluster/tf-acc-test-6080387929156384694/a3bfd034-c62a-445c-b83e-69ccde4b4d12-3): InvalidParameterValueException: Unsupported source arn : arn:aws-us-gov:kafka:us-gov-west-1:357342307427:cluster/tf-acc-test-6080387929156384694/a3bfd034-c62a-445c-b83e-69ccde4b4d12-3
        {
          RespMetadata: {
            StatusCode: 400,
            RequestID: "bad9817d-d774-44e2-ac06-d6a0fa834949"
          },
          Message_: "Unsupported source arn : arn:aws-us-gov:kafka:us-gov-west-1:357342307427:cluster/tf-acc-test-6080387929156384694/a3bfd034-c62a-445c-b83e-69ccde4b4d12-3",
          Type: "User"
        }
        
          on terraform_plugin_test.tf line 113, in resource "aws_lambda_event_source_mapping" "test":
         113: resource "aws_lambda_event_source_mapping" "test" {
        
        
--- SKIP: TestAccAWSLambdaEventSourceMapping_MSK (1398.58s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	1402.177s
```

**Comment by delbaeth** [comment]
@ewbankkit Thanks for all of your help with this.
