### PR TITLE
resource/aws_elasticache_replication_group: Validation fixes

### LINKED ISSUE #27116: resource/aws_elasticache_replication_group: Add plan-time validation for `automatic_failover_enabled` and number of cache clusters
### Description

The resource `aws_elasticache_replication_group` should have a plan-time validation to ensure that there are at least 2 cache clusters when `automatic_failover_enabled` is `true`

### Affected Resource(s) and/or Data Source(s)

* aws_elasticache_replication_group

### Potential Terraform Configuration

_No response_

### References

_No response_

### Would you like to implement a fix?

_No response_

### LINKED ISSUE #38360: resource/aws_elasticache_replication_group: `description` should be required
### Description

When `replication_group_description` was removed in #31008, `description` was not marked as `Required`

### References

_No response_

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by gdavison**
### Description

Fixes the following validations in `aws_elasticache_replication_group`:

* Requires `description` (was missed in #31008)
* When `automatic_failover_enabled` is `true`, `num_cache_clusters` must be greater than or equal to 2 if set
* Prevents setting `replicas_per_node_group` when `num_cache_clusters` is set
* Adds validation for `replicas_per_node_group` and allows setting to `0`.

### Relations

Closes #38360
Closes #27116

### Output from Acceptance Testing

```console
% make testacc PKG=elasticache TESTS=TestAccElastiCacheReplicationGroup_

--- PASS: TestAccElastiCacheReplicationGroup_clusteringAndCacheNodesCausesError (5.53s)
--- PASS: TestAccElastiCacheReplicationGroup_autoFailoverEnabled_validateNumberCacheClusters (6.27s)
--- PASS: TestAccElastiCacheReplicationGroup_dataTiering (735.20s)
--- PASS: TestAccElastiCacheReplicationGroup_multiAzNotInVPC_repeated (822.25s)
--- PASS: TestAccElastiCacheReplicationGroup_cacheClustersConflictsWithReplicasPerNodeGroup (0.96s)
--- PASS: TestAccElastiCacheReplicationGroup_enableSnapshotting (858.28s)
--- PASS: TestAccElastiCacheReplicationGroup_GlobalReplicationGroupIDClusterModeValidation_numNodeGroupsOnSecondary (1124.16s)
--- PASS: TestAccElastiCacheReplicationGroup_basic (1271.39s)
--- PASS: TestAccElastiCacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_ClusterMode_Enabled (1410.62s)
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappears_noChange (1506.26s)
--- PASS: TestAccElastiCacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_ClusterMode_Disabled (1520.49s)
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClusters_basic (1648.18s)
--- PASS: TestAccElastiCacheReplicationGroup_transitEncryptionWithAuthToken (1751.25s)
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappearsRemoveMemberCluster_scaleDown (2370.56s)
--- PASS: TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_basic (2423.89s)
--- PASS: TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroups_scaleUp (2436.61s)
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappearsRemoveMemberCluster_atTargetSize (1720.09s)
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClusters_multiAZEnabled (2536.15s)
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappears_addMemberCluster (1875.23s)
--- PASS: TestAccElastiCacheReplicationGroup_tags (1007.08s)
--- PASS: TestAccElastiCacheReplicationGroup_Validation_noNodeType (4.62s)
--- PASS: TestAccElastiCacheReplicationGroup_ValidationMultiAz_noAutomaticFailover (1.21s)
--- PASS: TestAccElastiCacheReplicationGroup_ipDiscovery (1131.08s)
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClusters_autoFailoverEnabled (2927.24s)
--- PASS: TestAccElastiCacheReplicationGroup_transitEncryption5x (3139.08s)
--- PASS: TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_disappears (3138.80s)
--- PASS: TestAccElastiCacheReplicationGroup_ClusterMode_singleNode (2290.98s)
--- PASS: TestAccElastiCacheReplicationGroup_useCMKKMSKeyID (868.32s)
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClusters_autoFailoverDisabled (3406.56s)
--- PASS: TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroups_scaleDown (1942.47s)
--- PASS: TestAccElastiCacheReplicationGroup_ClusterMode_basic (1057.49s)
--- PASS: TestAccElastiCacheReplicationGroup_ClusterMode_nonClusteredParameterGroup (1253.65s)
--- PASS: TestAccElastiCacheReplicationGroup_Validation_globalReplicationGroupIdAndNodeType (861.66s)
--- PASS: TestAccElastiCacheReplicationGroup_deprecatedAvailabilityZones_multiAzInVPC (1023.74s)
--- PASS: TestAccElastiCacheReplicationGroup_transitEncryption7x (3866.58s)
--- PASS: TestAccElastiCacheReplicationGroup_multiAzNotInVPC (956.40s)
--- PASS: TestAccElastiCacheReplicationGroup_networkType (1570.86s)
--- PASS: TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroupsAndReplicasPerNodeGroup_scaleUp (2600.76s)
--- PASS: TestAccElastiCacheReplicationGroup_updateDescription (1071.46s)
--- PASS: TestAccElastiCacheReplicationGroup_stateUpgrade5270 (899.91s)
--- PASS: TestAccElastiCacheReplicationGroup_vpc (1205.83s)
--- PASS: TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroupsAndReplicasPerNodeGroup_scaleDown (3275.59s)
--- PASS: TestAccElastiCacheReplicationGroup_autoMinorVersionUpgrade (815.62s)
--- PASS: TestAccElastiCacheReplicationGroup_updateUserGroups (1066.82s)
--- PASS: TestAccElastiCacheReplicationGroup_uppercase (744.38s)
--- PASS: TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_full (3760.58s)
--- PASS: TestAccElastiCacheReplicationGroup_EngineVersion_6xToRealVersion (1612.47s)
--- PASS: TestAccElastiCacheReplicationGroup_updateParameterGroup (1492.96s)
--- PASS: TestAccElastiCacheReplicationGroup_ClusterMode_updateReplicasPerNodeGroup (3724.94s)
--- PASS: TestAccElastiCacheReplicationGroup_EngineVersion_v7 (1056.64s)
--- PASS: TestAccElastiCacheReplicationGroup_finalSnapshot (1145.17s)
--- PASS: TestAccElastiCacheReplicationGroup_updateNodeSize (1696.52s)
--- PASS: TestAccElastiCacheReplicationGroup_authToken (2126.85s)
--- PASS: TestAccElastiCacheReplicationGroup_multiAzInVPC (1747.81s)
--- PASS: TestAccElastiCacheReplicationGroup_enableAtRestEncryption (1317.13s)
--- PASS: TestAccElastiCacheReplicationGroup_disappears (2373.47s)
--- PASS: TestAccElastiCacheReplicationGroup_updateMaintenanceWindow (3283.69s)
--- PASS: TestAccElastiCacheReplicationGroup_basic_v5 (1956.02s)
--- PASS: TestAccElastiCacheReplicationGroup_tagWithOtherModification (4229.08s)
--- PASS: TestAccElastiCacheReplicationGroup_EngineVersion_update (8229.94s)
```

### CODE REVIEW

File: internal/service/elasticache/replication_group.go [hunk 1]
```diff
@@ -503,8 +508,23 @@ func resourceReplicationGroupCreate(ctx context.Context, d *schema.ResourceData,
...
+		var v int32
+		err := gocty.FromCtyValue(rawReplicasPerNodeGroup, &v)
+		if err != nil {
+			path := cty.GetAttrPath("replicas_per_node_group")
+			diags = append(diags, errs.NewAttributeErrorDiagnostic(
+				path,
+				"Invalid Value",
+				"An unexpected error occurred while reading configuration values. "+
+					"This is always an error in the provider. "+
+					"Please report the following to the provider developer:\n\n"+
```
Comment (ewbankkit) [inline internal/service/elasticache/replication_group.go:523]: I've seen this string in a number of places -- do we want to extract to a constant?

Comment (gdavison) [reply internal/service/elasticache/replication_group.go:523]: Yes, I plan to do it as part of the ongoing AutoFlex stuff. It would be even better if `terraform-plugin-framework` exported it.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% ACCTEST_TIMEOUT=720m make testacc TESTARGS='-run=TestAccElastiCacheReplicationGroup_cacheClustersConflictsWithReplicasPerNodeGroup\|TestAccElastiCacheReplicationGroup_basic\|TestAccElastiCacheReplicationGroup_autoFailoverEnabled_validateNumberCacheClusters' PKG=elasticache ACCTEST_PARALLELISM=3
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.5 test ./internal/service/elasticache/... -v -count 1 -parallel 3  -run=TestAccElastiCacheReplicationGroup_cacheClustersConflictsWithReplicasPerNodeGroup\|TestAccElastiCacheReplicationGroup_basic\|TestAccElastiCacheReplicationGroup_autoFailoverEnabled_validateNumberCacheClusters -timeout 720m
=== RUN   TestAccElastiCacheReplicationGroup_basic
=== PAUSE TestAccElastiCacheReplicationGroup_basic
=== RUN   TestAccElastiCacheReplicationGroup_basic_v5
=== PAUSE TestAccElastiCacheReplicationGroup_basic_v5
=== RUN   TestAccElastiCacheReplicationGroup_cacheClustersConflictsWithReplicasPerNodeGroup
=== PAUSE TestAccElastiCacheReplicationGroup_cacheClustersConflictsWithReplicasPerNodeGroup
=== RUN   TestAccElastiCacheReplicationGroup_autoFailoverEnabled_validateNumberCacheClusters
=== PAUSE TestAccElastiCacheReplicationGroup_autoFailoverEnabled_validateNumberCacheClusters
=== CONT  TestAccElastiCacheReplicationGroup_basic
=== CONT  TestAccElastiCacheReplicationGroup_cacheClustersConflictsWithReplicasPerNodeGroup
=== CONT  TestAccElastiCacheReplicationGroup_basic_v5
--- PASS: TestAccElastiCacheReplicationGroup_cacheClustersConflictsWithReplicasPerNodeGroup (1.56s)
=== CONT  TestAccElastiCacheReplicationGroup_autoFailoverEnabled_validateNumberCacheClusters
--- PASS: TestAccElastiCacheReplicationGroup_autoFailoverEnabled_validateNumberCacheClusters (1.54s)
--- PASS: TestAccElastiCacheReplicationGroup_basic_v5 (723.32s)
--- PASS: TestAccElastiCacheReplicationGroup_basic (807.40s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elasticache	812.191s
```
