### PR TITLE
aws_workspaces_bundle: Fix empty (private) owner

### LINKED ISSUE #14206: Bundle Owner errors when empty
Owner is optional but errors when omitted.

"owner – (Optional) The owner of the bundles. You have to leave it blank for own bundles. You cannot combine this parameter with bundle_id." -> https://www.terraform.io/docs/providers/aws/d/workspaces_bundle.html

### Terraform CLI and Terraform AWS Provider Version

terraform -v
Terraform v0.12.24
+ provider.aws v2.70.0
### Terraform Configuration Files
```hcl
provider "aws" {
  region     = "us-east-1"
  version = "~> 2.0" # the version of the aws provider is v2.70.0
}

data aws_workspaces_bundle base {
  name  = "Name of my bundle"
}
```

Error: InvalidParameterValuesException: Invalid Owner provided.

  on main.tf line 76, in data "aws_workspaces_bundle" "base":
  76: data aws_workspaces_bundle base {

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by Tensho**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
aws_workspaces_bundle: Fix empty (private) owner
```

Closes #14206.

### Acceptance Tests

For private bundles test I've implemented the kind of the same trick (`AWS_WORKSPACES_BUNDLE_NAME`) as in `aws_workspaces_image` [test](https://github.com/terraform-providers/terraform-provider-aws/pull/11428/files#diff-ec54e665b3caeccdbc381156fade156cR37).

```
$ AWS_WORKSPACES_BUNDLE_NAME=PerformanceLinuxBaseline AWS_DEFAULT_REGION=us-east-1 make testacc TEST=./aws TESTARGS='-run=TestAccDataSourceAwsWorkspaceBundle'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccDataSourceAwsWorkspaceBundle -timeout 120m
=== RUN   TestAccDataSourceAwsWorkspaceBundle_basic
=== PAUSE TestAccDataSourceAwsWorkspaceBundle_basic
=== RUN   TestAccDataSourceAwsWorkspaceBundle_byOwnerName
=== PAUSE TestAccDataSourceAwsWorkspaceBundle_byOwnerName
=== RUN   TestAccDataSourceAwsWorkspaceBundle_bundleIDAndNameConflict
=== PAUSE TestAccDataSourceAwsWorkspaceBundle_bundleIDAndNameConflict
=== RUN   TestAccDataSourceAwsWorkspaceBundle_privateOwner
=== PAUSE TestAccDataSourceAwsWorkspaceBundle_privateOwner
=== CONT  TestAccDataSourceAwsWorkspaceBundle_basic
=== CONT  TestAccDataSourceAwsWorkspaceBundle_privateOwner
=== CONT  TestAccDataSourceAwsWorkspaceBundle_bundleIDAndNameConflict
=== CONT  TestAccDataSourceAwsWorkspaceBundle_byOwnerName
--- PASS: TestAccDataSourceAwsWorkspaceBundle_bundleIDAndNameConflict (2.23s)
--- PASS: TestAccDataSourceAwsWorkspaceBundle_basic (20.44s)
--- PASS: TestAccDataSourceAwsWorkspaceBundle_privateOwner (20.51s)
--- PASS: TestAccDataSourceAwsWorkspaceBundle_byOwnerName (25.91s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	28.444s
```

### CODE REVIEW

**Comment by Tensho** [comment]
@gdavison @ewbankkit Would appreciate for your review 🙇

File: aws/data_source_aws_workspaces_bundle_test.go [hunk 1]
```diff
@@ -73,17 +74,44 @@ func TestAccDataSourceAwsWorkspaceBundle_bundleIDAndNameConflict(t *testing.T) {
...
+func testAccWorkspacesBundlePreCheck(t *testing.T) {
+	if os.Getenv("AWS_WORKSPACES_BUNDLE_NAME") == "" {
+		t.Skip("AWS_WORKSPACES_BUNDLE_NAME env var must be set for AWS WorkSpaces private bundle acceptance test. This is required until AWS provides bundle creation API.")
+	}
+}
+
 func testAccDataSourceAwsWorkspaceBundleConfig(bundleID string) string {
 	return fmt.Sprintf(`
-data "aws_workspaces_bundle" "test" {
+data aws_workspaces_bundle test {
```
Comment (DrFaust92) [inline aws/data_source_aws_workspaces_bundle_test.go:106]: lets revert quotes.

**Review by DrFaust92 — CHANGES_REQUESTED** [review]
small change

**Review by gdavison — APPROVED** [review]
LGTM 🚀 

--- PASS: TestAccDataSourceAwsWorkspaceBundle_bundleIDAndNameConflict (33.06s)
--- PASS: TestAccDataSourceAwsWorkspaceBundle_privateOwner (73.64s)
--- PASS: TestAccDataSourceAwsWorkspaceBundle_basic (74.61s)
--- PASS: TestAccDataSourceAwsWorkspaceBundle_byOwnerName (76.38s)
