### PR TITLE
tests/resource/aws_ssm_resource_data_sync: Implement sweeper

### LINKED ISSUE #18100: tests/resource/aws_ssm_resource_data_sync: Implement sweeper
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The acceptance testing can leave lingering resources on failed runs (e.g. via coding issues during development or panics). These lingering resources can cause quota limits to be reached, extraneous money to be spent, or in some worst cases leave open security risks in the testing account.

Currently testing is failing in the main testing account due to hitting the service limit:

```
=== CONT  TestAccAWSSsmResourceDataSync_update
resource_aws_ssm_resource_data_sync_test.go:40: Step 1/3 error: Error running apply: exit status 1
Error: ResourceDataSyncCountExceededException: You've already reached the maximum of 5 Resource Data Sync Configurations.
on terraform_plugin_test.tf line 47, in resource "aws_ssm_resource_data_sync" "test":
47: resource "aws_ssm_resource_data_sync" "test" {
--- FAIL: TestAccAWSSsmResourceDataSync_update (36.42s)
```

### Affected Resource

* aws_ssm_resource_data_sync

### Definition of Done

- [ ] `go test ./aws -v -timeout=10h -sweep-allow-failures -sweep=us-west-2,us-east-1 -sweep-run=aws_ssm_resource_data_sync` completes successfully without error
- [ ] `aws ssm list-resource-data-sync | jq '.ResourceDataSyncItems | length'` shows no remaining resources

### References

* [Extending Terraform sweeper documentation](https://www.terraform.io/docs/extend/testing/acceptance-tests/sweepers.html)

### PR DESCRIPTION
**Pull request by bflad**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #18100

Output from sweeper in AWS Commercial:

```
$ aws ssm list-resource-data-sync | jq '.ResourceDataSyncItems | length'
4

2021/04/07 13:12:09 [DEBUG] Running Sweepers for region (us-west-2):
2021/04/07 13:12:09 [DEBUG] Running Sweeper (aws_ssm_resource_data_sync) in region (us-west-2)
2021/04/07 13:12:11 Sweeper Tests ran successfully:
        - aws_ssm_resource_data_sync
2021/04/07 13:12:11 [DEBUG] Running Sweepers for region (us-east-1):
2021/04/07 13:12:11 [DEBUG] Running Sweeper (aws_ssm_resource_data_sync) in region (us-east-1)
2021/04/07 13:12:11 Sweeper Tests ran successfully:
        - aws_ssm_resource_data_sync
ok      github.com/terraform-providers/terraform-provider-aws/aws       5.395s

$ aws ssm list-resource-data-sync | jq '.ResourceDataSyncItems | length'
0
```

Output from sweeper in AWS GovCloud (US):

```
2021/04/07 13:13:19 [DEBUG] Running Sweepers for region (us-gov-west-1):
2021/04/07 13:13:19 [DEBUG] Running Sweeper (aws_ssm_resource_data_sync) in region (us-gov-west-1)
2021/04/07 13:13:21 Sweeper Tests ran successfully:
        - aws_ssm_resource_data_sync
ok      github.com/terraform-providers/terraform-provider-aws/aws       5.225s
```

### CODE REVIEW

**Review by YakDriver — APPROVED** [review]
Enastående jobb! 🎉

File: aws/resource_aws_ssm_resource_data_sync_test.go [hunk 1]
```diff
@@ -5,12 +5,70 @@ import (
...
+
+	if err != nil {
+		errs = multierror.Append(errs, fmt.Errorf("error listing SSM Resource Data Sync for %s: %w", region, err))
+	}
+
+	if len(sweepResources) > 0 {
+		if err := testSweepResourceOrchestrator(sweepResources); err != nil {
+			errs = multierror.Append(errs, fmt.Errorf("error sweeping SSM Resource Data Sync for %s: %w", region, err))
+		}
+	}
```
Comment (bflad) [inline aws/resource_aws_ssm_resource_data_sync_test.go:62]:
```suggestion
	if err := testSweepResourceOrchestrator(sweepResources); err != nil {
		errs = multierror.Append(errs, fmt.Errorf("error sweeping SSM Resource Data Sync for %s: %w", region, err))
	}
```
