### PR TITLE
data-source/aws_route53_zone: Perform NS record lookup for private Hosted Zones

### LINKED ISSUE #10391: Empty name_servers in datasource aws_route53_zone
_This issue was originally opened by @masterjg as hashicorp/terraform#23005. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._
    
<hr>
    
### Terraform Version
Terraform v0.12.9

### Terraform Configuration Files
```hcl
variable "subzone_ids" {
  type = list(string)
  default = []
}
data "aws_route53_zone" "subzones" {
  count = length(var.subzone_ids)
  zone_id = var.subzone_ids[count.index]
}
```

### Expected Behavior
```hcl
data.aws_route53_zone.subzones[0].name_servers
```
returns list of nameservers for the first zone.

### Actual Behavior
name_servers empty list returned, even though other properties are returned correctly.

### LINKED ISSUE #16862: Can't get Name Servers with aws_route53_zone data
I can't get Name Servers from data aws_route53_zone

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.22.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/vault v2.17.0
```

### Affected Resource(s)

* data.aws_route53_zone

### Terraform Configuration Files

WORKS
```hcl
resource "aws_route53_zone" "primary" {
  name = "example.com"
}

output "name" {
  value = aws_route53_zone.primary.name_servers
}
```

DOESN'T WORKS
```hcl
data "aws_route53_zone" "devops-cross-domain" {
  name          =  "example.com."
  private_zone  = true
}

output "name2" {
  value = data.aws_route53_zone.devops-cross-domain.name_servers
}
```

### Expected Behavior

Get Name Servers with data

### Actual Behavior

```
  + name  = [
      + "ns-0.awsdns-00.com.",
      + "ns-1024.awsdns-00.org.",
      + "ns-1536.awsdns-00.co.uk.",
      + "ns-512.awsdns-00.net.",
    ]
  + name2 = []
```

Thanks!

### PR DESCRIPTION
**Pull request by bflad**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #10391
Closes #16862

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
NOTES

* data-source/aws_route53_zone: The Route 53 `ListResourceRecordSets` API call has been implemented to support the `name_servers` attribute for private Hosted Zones similar to the resource implementation. Environments using restrictive IAM permissions may require updates.

BUG FIXES

* data-source/aws_route53_zone: Ensure `name_servers` is populated for private Hosted Zones
```

Previously after testing updates:

```
=== CONT  TestAccAWSRoute53ZoneDataSource_vpc
    data_source_aws_route53_zone_test.go:89: Step 1/1 error: Check failed: Check 3/4 error: aws_route53_zone.test: Attribute "name_servers.#" is "4", but "name_servers.#" is not set in data.aws_route53_zone.test
--- FAIL: TestAccAWSRoute53ZoneDataSource_vpc (83.04s)
```

Output from acceptance testing:

```
--- PASS: TestAccAWSRoute53ZoneDataSource_id (46.24s)
--- PASS: TestAccAWSRoute53ZoneDataSource_name (47.24s)
--- PASS: TestAccAWSRoute53ZoneDataSource_tags (94.61s)
--- PASS: TestAccAWSRoute53ZoneDataSource_vpc (94.63s)
--- PASS: TestAccAWSRoute53ZoneDataSource_serviceDiscovery (110.28s)
```

### CODE REVIEW

File: aws/data_source_aws_route53_zone.go [hunk 1]
```diff
@@ -170,46 +170,58 @@ func dataSourceAwsRoute53ZoneRead(d *schema.ResourceData, meta interface{}) erro
 		d.Set("linked_service_description", hostedZoneFound.LinkedService.Description)
 	}
 
-	nameServers, err := hostedZoneNameServers(idHostedZone, conn)
+	nameServers, err := hostedZoneNameServers(conn, idHostedZone, aws.StringValue(hostedZoneFound.Name))
+
 	if err != nil {
-		return fmt.Errorf("Error finding Route 53 Hosted Zone: %v", err)
+		return fmt.Errorf("error getting Route 53 Hosted Zone (%s) name servers: %w", idHostedZone, err)
```
Comment (YakDriver) [inline aws/data_source_aws_route53_zone.go:176]:
```suggestion
		return fmt.Errorf("getting Route 53 Hosted Zone (%s) name servers: %w", idHostedZone, err)
```
Nit: not a fan of `Error: error getting...` that this would produce.

File: aws/data_source_aws_route53_zone.go [hunk 2]
```diff
@@ -170,46 +170,58 @@ func dataSourceAwsRoute53ZoneRead(d *schema.ResourceData, meta interface{}) erro
...
+
 	if err := d.Set("name_servers", nameServers); err != nil {
 		return fmt.Errorf("error setting name_servers: %w", err)
 	}
 
 	tags, err = keyvaluetags.Route53ListTags(conn, idHostedZone, route53.TagResourceTypeHostedzone)
 
 	if err != nil {
-		return fmt.Errorf("Error finding Route 53 Hosted Zone: %v", err)
+		return fmt.Errorf("error listing Route 53 Hosted Zone (%s) tags: %w", idHostedZone, err)
```
Comment (YakDriver) [inline aws/data_source_aws_route53_zone.go:186]:
```suggestion
		return fmt.Errorf("failed listing Route 53 Hosted Zone (%s) tags: %w", idHostedZone, err)
```
Another approach.

File: aws/data_source_aws_route53_zone.go [hunk 3]
```diff
@@ -170,46 +170,58 @@ func dataSourceAwsRoute53ZoneRead(d *schema.ResourceData, meta interface{}) erro
...
 	}
 
 	if err := d.Set("tags", tags.IgnoreAws().IgnoreConfig(ignoreTagsConfig).Map()); err != nil {
-		return fmt.Errorf("error setting tags: %s", err)
+		return fmt.Errorf("error setting tags: %w", err)
```
Comment (YakDriver) [inline aws/data_source_aws_route53_zone.go:190]:
```suggestion
		return fmt.Errorf("setting tags: %w", err)
```

File: aws/data_source_aws_route53_zone.go [hunk 4]
```diff
@@ -170,46 +170,58 @@ func dataSourceAwsRoute53ZoneRead(d *schema.ResourceData, meta interface{}) erro
...
+	input := &route53.GetHostedZoneInput{
+		Id: aws.String(id),
+	}
+
+	output, err := conn.GetHostedZone(input)
 
-	resp, err := conn.GetHostedZone(req)
 	if err != nil {
-		return []string{}, err
+		return nil, fmt.Errorf("error getting Route 53 Hosted Zone (%s): %w", id, err)
```
Comment (YakDriver) [inline aws/data_source_aws_route53_zone.go:205]:
```suggestion
		return nil, fmt.Errorf("getting Route 53 Hosted Zone (%s): %w", id, err)
```

File: aws/data_source_aws_route53_zone.go [hunk 5]
```diff
@@ -170,46 +170,58 @@ func dataSourceAwsRoute53ZoneRead(d *schema.ResourceData, meta interface{}) erro
...
+	}
+
+	if output == nil {
+		return nil, fmt.Errorf("error getting Route 53 Hosted Zone (%s): empty response", id)
```
Comment (YakDriver) [inline aws/data_source_aws_route53_zone.go:209]:
```suggestion
		return nil, fmt.Errorf("getting Route 53 Hosted Zone (%s): empty response", id)
```

File: aws/data_source_aws_route53_zone.go [hunk 6]
```diff
@@ -170,46 +170,58 @@ func dataSourceAwsRoute53ZoneRead(d *schema.ResourceData, meta interface{}) erro
...
 
-	servers := []string{}
-	for _, server := range resp.DelegationSet.NameServers {
-		if server != nil {
-			servers = append(servers, aws.StringValue(server))
+	if output.HostedZone != nil && output.HostedZone.Config != nil && aws.BoolValue(output.HostedZone.Config.PrivateZone) {
+		nameServers, err := getNameServers(id, name, conn)
+
+		if err != nil {
+			return nil, fmt.Errorf("error listing Route 53 Hosted Zone (%s) NS records: %w", id, err)
```
Comment (YakDriver) [inline aws/data_source_aws_route53_zone.go:220]:
```suggestion
			return nil, fmt.Errorf("listing Route 53 Hosted Zone (%s) NS records: %w", id, err)
```

**Review by YakDriver — APPROVED** [review]
Optional nits but LGTM! 🎉 

GovCloud:
```
--- PASS: TestAccAWSRoute53ZoneDataSource_tags (68.32s)
--- PASS: TestAccAWSRoute53ZoneDataSource_vpc (66.51s)
--- SKIP: TestAccAWSRoute53ZoneDataSource_id (6.86s)
--- SKIP: TestAccAWSRoute53ZoneDataSource_name (7.25s)
--- SKIP: TestAccAWSRoute53ZoneDataSource_serviceDiscovery (1.26s)
```

`us-west-2`:
```
--- PASS: TestAccAWSRoute53ZoneDataSource_name (45.95s)
--- PASS: TestAccAWSRoute53ZoneDataSource_id (46.08s)
--- PASS: TestAccAWSRoute53ZoneDataSource_vpc (82.93s)
--- PASS: TestAccAWSRoute53ZoneDataSource_tags (83.90s)
--- PASS: TestAccAWSRoute53ZoneDataSource_serviceDiscovery (118.57s)
```

File: aws/data_source_aws_route53_zone.go (hunk 1 above)
Comment (bflad) [reply aws/data_source_aws_route53_zone.go:176]: Thank you for raising this. Rather than leaving a lengthy comment that could be lost about the history of this, I have created https://github.com/hashicorp/terraform-provider-aws/issues/17314 with all the information. What is important right now is that `fmt.Errorf("error creating/reading/updating/deleting Service Thing (ID): Error")` is the (finally now 😖 ) [documented](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/error-handling.md) practice for consistency that's been the goal last few years, which is showing its age in Terraform 0.12 and later. I would rather continue the existing practice for later find/replace-ability until we can decide as a team on any potential new standards.

Please feel free to check that out issue and contribute!
