### PR TITLE
Fix/create image version get version from call return

### LINKED ISSUE #44959: Race condition in aws_sagemaker_image_version when creating multiple versions concurrently
### Terraform and AWS Provider Version

```console
AWS Provider v6.19.0 
Terraform v1.13.5 (not relevant here)
```

### Affected Resource(s) or Data Source(s)

* aws_sagemaker_image_version                                                                                                                       

### Expected Behavior

When creating multiple image versions concurrently for the same SageMaker image, each resource should get assigned its correct version number (1, 2, etc.).  

### Actual Behavior

When creating multiple image versions concurrently, all resources get assigned the same version number (the latest one created). 

This happens because `waitImageVersionCreated` calls `DescribeImageVersion` without specifying a version parameter, which returns the latest version according to AWS API documentation: "If not specified, the latest version is described."                                                                              

### Relevant Error/Panic Output

```console

```

### Sample Terraform Configuration

<details open>
<summary>Click to expand configuration</summary>

```hcl
hcl                                                                                                                                                 
resource "aws_sagemaker_image" "example" {
 image_name = "example"
 role_arn   = aws_iam_role.example.arn
}

resource "aws_sagemaker_image_version" "version1" {
 image_name = aws_sagemaker_image.example.name
 base_image = "763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-training:1.13.1-gpu-py39-cu117-ubuntu20.04-sagemaker"
}

resource "aws_sagemaker_image_version" "version2" {
 image_name = aws_sagemaker_image.example.name
 base_image = "763104351884.dkr.ecr.us-west-2.amazonaws.com/tensorflow-training:2.11.0-gpu-py39-cu112-ubuntu20.04-sagemaker"
}
```
</details>

### Steps to Reproduce

1. Create multiple `aws_sagemaker_image_version` resources for the same image simultaneously                                                        
2. Apply the configuration with parallelism enabled                                                                                                 
3. Observe that all resources show the same version number in state 

### Debug Logging

<details open>
<summary>Click to expand log output</summary>

```console

```
</details>

### GenAI / LLM Assisted Development

n/a

### Important Facts and References

AWS SageMaker DescribeImageVersion API: https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_DescribeImageVersion.html                     
                                                                                                                                                    
The issue is in the `waitImageVersionCreated` function which uses `findImageVersionByName` that calls `DescribeImageVersion` without the `Version` parameter, causing it to return the latest version instead of the specific version that was just created.                                            
                                                             

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by psantus**
<!---
See what makes a good Pull Request at: https://hashicorp.github.io/terraform-provider-aws/raising-a-pull-request/                                   
--->                                                                                                                                                
                                                                                                                                                    
<!-- heimdall_github_prtemplate:grc-pci_dss-2024-01-05 -->                                                                                          
                                                                                                                                                    
## Rollback Plan                                                                                                                                    
                                                                                                                                                    
If a change needs to be reverted, we will publish an updated version of the library.                                                                
                                                                                                                                                    
## Changes to Security Controls                                                                                                                     
                                                                                                                                                    
Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.                             
                                                                                                                                                    
No changes to security controls.                                                                                                                    
                                                                                                                                                    
### Description                                                                                                                                     
                                                                                                                                                    
Fixes race condition in `aws_sagemaker_image_version` when creating multiple versions concurrently. Previously, `waitImageVersionCreated` called `DescribeImageVersion` without specifying a version parameter, which returns the latest version according to AWS API documentation. This caused all concurrent image version creations to get assigned the same (latest) version number.                                                                   
                                                                                                                                                    
The fix extracts the version number from the `CreateImageVersion` response ARN and uses it in a new version-specific wait function `waitImageVersionCreatedByVersion`, ensuring each resource waits for its specific version to be created.                                                             
                                                                                                                                                    
Also removes unused functions that are no longer needed after the fix.                                                                              
                                                                                                                                                    
### Relations                                                                                                                                       
                                                                                                                                                    
Closes #44959                                                                                                                                        
                                                                                                                                                    
### References                                                                                                                                      
                                                                                                                                                    
- AWS SageMaker DescribeImageVersion API: https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_DescribeImageVersion.html                   
- AWS SageMaker CreateImageVersion API: https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateImageVersion.html                       
                                                                                                                                                    
### Output from Acceptance Testing                                                                                                                  
                                                                                                                                                    
console                                                                                                                                             
% SAGEMAKER_IMAGE_VERSION_BASE_IMAGE="763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-training:1.13.1-gpu-py39-cu117-ubuntu20.04-sagemaker" make testacc PKG=sagemaker TESTARGS='-run=TestAccSageMakerImageVersion_basic' 

make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 fix/create_image_version-get-version-from-call-return 🌿...
TF_ACC=1 go1.24.8 test ./internal/service/sagemaker/... -v -count 1 -parallel 20  -run=TestAccSageMakerImageVersion_basic -timeout 360m -vet=off
2025/11/06 11:16:55 Creating Terraform AWS Provider (SDKv2-style)...
2025/11/06 11:16:55 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccSageMakerImageVersion_basic
=== PAUSE TestAccSageMakerImageVersion_basic
=== CONT  TestAccSageMakerImageVersion_basic
--- PASS: TestAccSageMakerImageVersion_basic (95.39s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker  100.141s

### CODE REVIEW

**Comment by psantus** [comment]
* All SDK v2 has been removed in favor of Terraform Plugin Framework, 
* PR has been rebased
* Tests pass

File: internal/service/sagemaker/image_version.go [hunk 1]
```diff
@@ -415,6 +384,18 @@ func findImageVersionAliasesByTwoPartKey(ctx context.Context, conn *sagemaker.Cl
 	return output.SageMakerImageVersionAliases, nil
 }
 
+// extractVersionFromARN extracts the version number from an ImageVersionArn
+// ARN format: arn:aws:sagemaker:region:account:image-version/image-name/version
+func extractVersionFromARN(arn string) int32 {
```
Comment (jar-b) [inline internal/service/sagemaker/image_version.go]: Add some unit tests for this function?

File: internal/service/sagemaker/status.go [hunk 2]
```diff
@@ -9,14 +9,15 @@ import (
...
+	"github.com/hashicorp/terraform-provider-aws/internal/errs"
 	"github.com/hashicorp/terraform-provider-aws/internal/retry"
 )
 
 func statusNotebookInstance(ctx context.Context, conn *sagemaker.Client, notebookName string) sdkretry.StateRefreshFunc {
 	return func() (any, string, error) {
 		output, err := findNotebookInstanceByName(ctx, conn, notebookName)
 
-		if retry.NotFound(err) {
+		if errs.IsA[*retry.NotFoundError](err) {
```
Comment (jar-b) [inline internal/service/sagemaker/status.go]: All of these changes can be reverted. `retry.NotFound` will work with both variations of the `NotFoundError` error type.

File: internal/service/sagemaker/wait.go [hunk 3]
```diff
@@ -211,11 +213,11 @@ func waitImageDeleted(ctx context.Context, conn *sagemaker.Client, name string)
 	return err
 }
 
-func waitImageVersionCreated(ctx context.Context, conn *sagemaker.Client, name string) (*sagemaker.DescribeImageVersionOutput, error) {
+func waitImageVersionCreatedByVersion(ctx context.Context, conn *sagemaker.Client, name string, version int32) (*sagemaker.DescribeImageVersionOutput, error) {
```
Comment (jar-b) [inline internal/service/sagemaker/wait.go]: This is probably fine to leave as `waitImageVersionCreated`, the function signature itself implies the two part key is required.

File: internal/service/sagemaker/image_version.go [hunk 4]
```diff
@@ -1,21 +1,20 @@
 // Copyright IBM Corp. 2014, 2026
 // SPDX-License-Identifier: MPL-2.0
 
-// DONOTCOPY: Copying old resources spreads bad habits. Use skaff instead.
-
```
Comment (jar-b) [inline internal/service/sagemaker/image_version.go:5]: This should remain in place - we've added this to all resource files to promote the use of skaff rather than copy/pasting from existing work.

Comment (psantus) [reply internal/service/sagemaker/image_version.go:5]: ok

File: internal/service/sagemaker/image_version.go (hunk 1 above)
Comment (psantus) [reply internal/service/sagemaker/image_version.go]: Done

File: internal/service/sagemaker/wait.go (hunk 3 above)
Comment (psantus) [reply internal/service/sagemaker/wait.go]: ok

**Comment by jar-b** [comment]
Thanks for your contribution, @psantus! 👍

**Comment by psantus** [comment]
Thanks for your review @jar-b!
