### PR TITLE
tests/resource/aws_eks_node_group: Fix test failures

### LINKED ISSUE #16146: tests/resource/aws_eks_node_group: Launch Template Version and Release Version Failures
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The following two test failures are present on the main branch:

```
=== CONT  TestAccAWSEksNodeGroup_LaunchTemplate_Version
TestAccAWSEksNodeGroup_LaunchTemplate_Version: resource_aws_eks_node_group_test.go:394: Step 3/3, expected an error but got none
--- FAIL: TestAccAWSEksNodeGroup_LaunchTemplate_Version (2495.73s)

=== CONT  TestAccAWSEksNodeGroup_ReleaseVersion
TestAccAWSEksNodeGroup_ReleaseVersion: resource_aws_eks_node_group_test.go:433: Step 3/3 error: Error running apply: 2020/11/11 10:20:03 [DEBUG] Using modified User-Agent: Terraform/0.12.29 HashiCorp-terraform-exec/0.10.0
Error: error updating EKS Node Group (tf-acc-test-7656789780485850868:tf-acc-test-7656789780485850868) version: InvalidParameterException: Requested Nodegroup release version 1.16.13-20201007 is invalid. Allowed release version is 1.16.15-20201107
{
RespMetadata: {
StatusCode: 400,
RequestID: "17a52d81-285a-4e03-924c-874d3d895e3b"
},
ClusterName: "tf-acc-test-7656789780485850868",
Message_: "Requested Nodegroup release version 1.16.13-20201007 is invalid. Allowed release version is 1.16.15-20201107",
NodegroupName: "tf-acc-test-7656789780485850868"
}
--- FAIL: TestAccAWSEksNodeGroup_ReleaseVersion (4466.46s)
```

In the first case, it appears the service team has fixed the `UpdateNodeGroup` API issue. 🎉  In the second case, it appears SSM parameter and API are out of sync. Created an upstream issue.

### Affected Resource(s)

* aws_eks_node_group

### References

* https://github.com/aws/containers-roadmap/issues/771
* https://github.com/awslabs/amazon-eks-ami/issues/559

### PR DESCRIPTION
**Pull request by bflad**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #16146
Reference: https://github.com/aws/containers-roadmap/issues/771
Reference: https://github.com/awslabs/amazon-eks-ami/issues/559

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
NONE
```

Previously:

```
=== CONT  TestAccAWSEksNodeGroup_LaunchTemplate_Version
TestAccAWSEksNodeGroup_LaunchTemplate_Version: resource_aws_eks_node_group_test.go:394: Step 3/3, expected an error but got none
--- FAIL: TestAccAWSEksNodeGroup_LaunchTemplate_Version (2495.73s)

=== CONT  TestAccAWSEksNodeGroup_ReleaseVersion
TestAccAWSEksNodeGroup_ReleaseVersion: resource_aws_eks_node_group_test.go:433: Step 3/3 error: Error running apply: 2020/11/11 10:20:03 [DEBUG] Using modified User-Agent: Terraform/0.12.29 HashiCorp-terraform-exec/0.10.0
Error: error updating EKS Node Group (tf-acc-test-7656789780485850868:tf-acc-test-7656789780485850868) version: InvalidParameterException: Requested Nodegroup release version 1.16.13-20201007 is invalid. Allowed release version is 1.16.15-20201107
{
RespMetadata: {
StatusCode: 400,
RequestID: "17a52d81-285a-4e03-924c-874d3d895e3b"
},
ClusterName: "tf-acc-test-7656789780485850868",
Message_: "Requested Nodegroup release version 1.16.13-20201007 is invalid. Allowed release version is 1.16.15-20201107",
NodegroupName: "tf-acc-test-7656789780485850868"
}
--- FAIL: TestAccAWSEksNodeGroup_ReleaseVersion (4466.46s)
```

Output from acceptance testing:

```
--- PASS: TestAccAWSEksNodeGroup_LaunchTemplate_Version (2424.12s)
--- PASS: TestAccAWSEksNodeGroup_ReleaseVersion (4059.77s)
```

### CODE REVIEW

File: aws/resource_aws_eks_node_group_test.go [hunk 1]
```diff
@@ -411,14 +411,12 @@ func TestAccAWSEksNodeGroup_LaunchTemplate_Version(t *testing.T) {
...
 				Config: testAccAWSEksNodeGroupConfigLaunchTemplateVersion2(rName),
-				// This API error is incorrect and will need to be rectified by the service team.
-				ExpectError: regexp.MustCompile(`User data was not in the MIME multipart format`),
-				// Check: resource.ComposeTestCheckFunc(
-				// 	testAccCheckAWSEksNodeGroupExists(resourceName, &nodeGroup2),
-				// 	testAccCheckAWSEksNodeGroupNotRecreated(&nodeGroup1, &nodeGroup2),
-				// 	resource.TestCheckResourceAttr(resourceName, "launch_template.#", "1"),
-				// 	resource.TestCheckResourceAttrPair(resourceName, "launch_template.0.version", launchTemplateResourceName, "default_version"),
-				// ),
+				Check: resource.ComposeTestCheckFunc(
```
Comment (anGie44) [inline aws/resource_aws_eks_node_group_test.go:414]: 🙌

**Review by anGie44 — APPROVED** [review]
ahh always tricky with these versions 😞 LGTM tho 🚀
