### PR TITLE
rds/instance: Test correct updating of cert

### LINKED ISSUE #33546: [Bug]: aws_db_instance ca_cert_identifier field applied but not reflected
### Terraform Core Version

1.5.7

### AWS Provider Version

5.14.0

### Affected Resource(s)

aws_db_instance

### Expected Behavior

RDS AWS instance should have rds-ca-rsa2048-g1  CA.

### Actual Behavior

RDS AWS instance remains on rds-ca-2019 .

### Relevant Error/Panic Output Snippet

```shell
There is no error. The changed is detected correctly in plan and apply. According to terraform the change is done, but the value is not changed. 

Rebooting the db does not help. No items are left to install in maintenance.
```

### Terraform Configuration Files

```terraform
resource "aws_db_instance" "db" {
  identifier_prefix                   = "${lower("${var.name}-RDS")}-"
  allocated_storage                   = var.allocated_storage
  max_allocated_storage               = var.max_allocated_storage
  storage_type                        = var.storage_type
  engine                              = var.db_engine
  engine_version                      = var.db_engine_version
  storage_encrypted                   = var.storage_encrypted
  instance_class                      = var.instance_class
  username                            = var.username
  manage_master_user_password         = true
  iam_database_authentication_enabled = true
  db_subnet_group_name                = aws_db_subnet_group.default.name
  multi_az                            = var.multi_az
  copy_tags_to_snapshot               = true
  final_snapshot_identifier           = "${lower("${var.name}-RDS")}-final-snapshot"
  vpc_security_group_ids              = [aws_security_group.rds_sg.id]
  parameter_group_name                = var.parameter_group_name
  backup_retention_period             = "7"
  backup_window                       = "05:00-06:00"
  maintenance_window                  = "Sun:06:00-Sun:07:00"
  auto_minor_version_upgrade          = "true"
  allow_major_version_upgrade         = var.allow_major_version_upgrade
  monitoring_interval                 = var.monitoring_interval
  monitoring_role_arn                 = var.monitoring_role_arn
  deletion_protection                 = var.deletion_protection
  enabled_cloudwatch_logs_exports     = var.enabled_cloudwatch_logs_exports
  ca_cert_identifier                  = "rds-ca-rsa2048-g1"
  port                                = var.db_ingress_port
}
```

### Steps to Reproduce

For a database with current ca_cert_identifier "rds-ca-2019" , update to  "rds-ca-rsa2048-g1".

### Debug Output

build	20-Sep-2023 10:59:14	[0m[0m[1maws_s3_bucket_policy.flow_logs_policy: Modifying... [id=3556xxx-vpc-xxx][0m[0m
build	20-Sep-2023 10:59:14	[0m[1mmodule.rds.aws_db_instance.db: Modifying... [id=db-YMBM3QDXXXX][0m[0m
build	20-Sep-2023 10:59:14	[0m[1maws_s3_bucket_policy.flow_logs_policy: Modifications complete after 0s [id=3556xxx-vpc-0ebb17caaf2062b8c-flow-log-kerr-mg2-dev][0m
build	20-Sep-2023 10:59:24	[0m[1mmodule.rds.aws_db_instance.db: Still modifying... [id=db-YMBM3QDXXXX, 10s elapsed][0m[0m
build	20-Sep-2023 10:59:34	[0m[1mmodule.rds.aws_db_instance.db: Still modifying... [id=db-YMBM3QDXXXX, 20s elapsed][0m[0m
build	20-Sep-2023 10:59:44	[0m[1mmodule.rds.aws_db_instance.db: Still modifying... [id=db-YMBM3QDXXXX, 30s elapsed][0m[0m
build	20-Sep-2023 10:59:54	[0m[1mmodule.rds.aws_db_instance.db: Still modifying... [id=db-YMBM3QDXXXX, 40s elapsed][0m[0m
build	20-Sep-2023 11:00:04	[0m[1mmodule.rds.aws_db_instance.db: Still modifying... [id=db-YMBM3QDXXXX, 50s elapsed][0m[0m
build	20-Sep-2023 11:00:14	[0m[1mmodule.rds.aws_db_instance.db: Still modifying... [id=db-YMBM3QDXXXX, 1m0s elapsed][0m[0m
build	20-Sep-2023 11:00:24	[0m[1mmodule.rds.aws_db_instance.db: Still modifying... [id=db-YMBM3QDXXXX, 1m10s elapsed][0m[0m
build	20-Sep-2023 11:00:34	[0m[1mmodule.rds.aws_db_instance.db: Still modifying... [id=db-YMBM3QDXXXX, 1m20s elapsed][0m[0m
build	20-Sep-2023 11:00:35	[0m[1mmodule.rds.aws_db_instance.db: Modifications complete after 1m21s [id=db-YMBM3QDXXXX][0m

### Panic Output

There is no panic.

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by YakDriver**
### Description

I was not able to find a bug with updating certificates. We're planning to close #33546 with this PR, that makes no changes but adds a test, for these reasons:

1. I'm adding a test that shows the correct updating behavior, when `apply_immediate = "true"`, changing `ca_cert_identifier` from `rds-ca-ecc384-g1` to `rds-ca-rsa2048-g1`.
2. #33546 is stale because the cert discussed, `rds-ca-2019`, is no longer available, and there is no longer urgency to change that cert since people have already done that--the time has passed.
3. Some of the problem seemed to be related to an [AWS issue](https://repost.aws/questions/QU7Qr4sLjXTrqsMRH35WyJ0Q/applying-new-ca-cert-during-maintenance-but-shows-no-changes-pending) that may have been resolved.
4. Additional [complex behavior](https://github.com/hashicorp/terraform-provider-aws/issues/33546#issuecomment-1995399319), such as applying a cert change immediately when `apply_immediate` is `false` is beyond the scope of a bug issue. We welcome a feature request to this effect, however, if it continues to be an issue.

### Relations

Closes #33546

### Output from Acceptance Testing

```console
% make t T=TestAccRDSInstance_CACertificate_update K=rds
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.3 test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccRDSInstance_CACertificate_update'  -timeout 360m
2024/11/22 15:13:35 Initializing Terraform AWS Provider...
=== RUN   TestAccRDSInstance_CACertificate_update
=== PAUSE TestAccRDSInstance_CACertificate_update
=== CONT  TestAccRDSInstance_CACertificate_update
--- PASS: TestAccRDSInstance_CACertificate_update (681.10s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/rds	685.221s
```

### CODE REVIEW

File: internal/service/rds/instance_test.go [hunk 1]
```diff
@@ -10206,7 +10257,7 @@ resource "aws_db_instance" "source" {
   timeouts {
     update = "120m"
   }
-  ca_cert_identifier = "rds-ca-2019"
+  ca_cert_identifier = "rds-ca-rsa2048-g1"
```
Comment (YakDriver) [inline internal/service/rds/instance_test.go:10260]: These test will have been failing since this cert became unavailable.

**Review by jar-b — APPROVED** [review]
