### PR TITLE
f/add slot type attribute

### LINKED ISSUE #35514: [Enhancement]:  lexv2models/slot Needs `sub_slot_setting`
### Terraform Core Version

1.6.6

### AWS Provider Version

5.34.0

### Affected Resource(s)

* aws_lexv2models_slot

### Expected Behavior

Needs `sub_slot_setting` attribute.

### Actual Behavior

Resource does not have `sub_slot_setting` implemented yet. 
https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/lexmodelsv2@v1.38.6/types#SubSlotSetting

### Relevant Error/Panic Output Snippet

_No response_

### Terraform Configuration Files

```
resource "aws_lexv2models_slot" "test" {
  bot_id      = aws_lexv2models_bot.test.id
  bot_version = aws_lexv2models_bot_locale.test.bot_version
  intent_id   = aws_lexv2models_intent.test.intent_id
  name        =  "test"
  locale_id   = aws_lexv2models_bot_locale.test.locale_id

  value_elicitation_setting {
    slot_constraint = "Optional"
    default_value_specification {
      default_value_list {
        default_value = "default"
      }
    }
  }

  sub_slot_setting {
    expression = "string"
    slot_specifications {
      slot_type_id = aws_lexv2models_slottype.id
      value_elicitation_setting {
        prompt_specification {
        }
        default_value_specification {
        }
        sample_utterances {
        }
        wait_and_continue_specification {
        }
      }
    }
  }
}
```

### Steps to Reproduce

1. terraform apply

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

* #34617 

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by nam054**
### Description

Add `sub_slot_type` to `slot` resource

### Relations

Closes #35514

### Output from Acceptance Testing

```console
> make testacc TESTARGS='-run=TestAccLexV2ModelsSlot_' PKG=lexv2models
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.5 test ./internal/service/lexv2models/... -v -count 1 -parallel 20  -run=TestAccLexV2ModelsSlot_ -timeout 360m
=== RUN   TestAccLexV2ModelsSlot_basic
=== PAUSE TestAccLexV2ModelsSlot_basic
=== RUN   TestAccLexV2ModelsSlot_updateMultipleValuesSetting
=== PAUSE TestAccLexV2ModelsSlot_updateMultipleValuesSetting
=== RUN   TestAccLexV2ModelsSlot_obfuscationSetting
=== PAUSE TestAccLexV2ModelsSlot_obfuscationSetting
=== RUN   TestAccLexV2ModelsSlot_subSlotSetting
=== PAUSE TestAccLexV2ModelsSlot_subSlotSetting
=== RUN   TestAccLexV2ModelsSlot_disappears
=== PAUSE TestAccLexV2ModelsSlot_disappears
=== CONT  TestAccLexV2ModelsSlot_basic
=== CONT  TestAccLexV2ModelsSlot_obfuscationSetting
=== CONT  TestAccLexV2ModelsSlot_subSlotSetting
=== CONT  TestAccLexV2ModelsSlot_disappears
=== CONT  TestAccLexV2ModelsSlot_updateMultipleValuesSetting
--- PASS: TestAccLexV2ModelsSlot_obfuscationSetting (40.74s)
--- PASS: TestAccLexV2ModelsSlot_disappears (42.43s)
--- PASS: TestAccLexV2ModelsSlot_basic (44.72s)
--- PASS: TestAccLexV2ModelsSlot_subSlotSetting (47.11s)
--- PASS: TestAccLexV2ModelsSlot_updateMultipleValuesSetting (54.00s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/lexv2models        59.860s

...
```

### CODE REVIEW

File: internal/service/lexv2models/slot_test.go [hunk 1]
```diff
@@ -143,6 +143,41 @@ func TestAccLexV2ModelsSlot_ObfuscationSetting(t *testing.T) {
 	})
 }
 
+func TestAccLexV2ModelsSlot_SubSlotSetting(t *testing.T) {
```
Comment (YakDriver) [inline internal/service/lexv2models/slot_test.go:146]:
```suggestion
func TestAccLexV2ModelsSlot_subSlotSetting(t *testing.T) {
```

Tiny nit. Go naming convention: `Xyz_Abc_jkl` or `Xyz_jkl`. If you have 3 parts, "Xyz" is book title, "Abc" is chapter title, "jkl" is section title. With just 2, book, section. The last one, whether you have 4, 3, or 2, should be lowercase.

File: internal/service/lexv2models/slot.go [hunk 2]
```diff
@@ -448,6 +449,52 @@ func (r *resourceSlot) Schema(ctx context.Context, req resource.SchemaRequest, r
 		},
 	}
 
+	subSlotValueElicitationSettingLNB := schema.ListNestedBlock{
+		CustomType: fwtypes.NewListNestedObjectTypeOf[SubSlotValueElicitationSettingData](ctx),
+		NestedObject: schema.NestedBlockObject{
+			Blocks: map[string]schema.Block{
+				"prompt_specification":            promptSpecificationLNB,
+				"default_value_specification":     defaultValueSpecificationLNB,
```
Comment (YakDriver) [inline internal/service/lexv2models/slot.go:457]:
```suggestion
				"default_value_specification":     defaultValueSpecificationLNB,
				"prompt_specification":            promptSpecificationLNB,
```

Nit: alphabetical

File: internal/service/lexv2models/slot.go [hunk 3]
```diff
@@ -448,6 +449,52 @@ func (r *resourceSlot) Schema(ctx context.Context, req resource.SchemaRequest, r
...
+	subSlotSettingLNB := schema.ListNestedBlock{
+		CustomType: fwtypes.NewListNestedObjectTypeOf[SubSlotSettingData](ctx),
+		NestedObject: schema.NestedBlockObject{
+			Attributes: map[string]schema.Attribute{
+				names.AttrExpression: schema.StringAttribute{
+					Optional: true,
+				},
+			},
+			Blocks: map[string]schema.Block{
+				"slot_specifications": slotSpecificationsLNB,
```
Comment (YakDriver) [inline internal/service/lexv2models/slot.go:493]:
```suggestion
				"slot_specification": slotSpecificationsLNB,
```

In the configuration, these are defined as free-standing blocks. From a practitioner POV, they should be singular.

```terraform
resource "abc" "test" {
  slot_specification {
    ...
  }

  slot_specification {
    ...
  }
}
```

File: internal/service/lexv2models/slot.go [hunk 4]
```diff
@@ -515,13 +562,14 @@ func (r *resourceSlot) Schema(ctx context.Context, req resource.SchemaRequest, r
 			},
 			"slot_type_id": schema.StringAttribute{
 				Optional: true,
+				Computed: true,
 			},
 		},
 		Blocks: map[string]schema.Block{
 			"multiple_values_setting":   multValueSettingsLNB,
 			"obfuscation_setting":       obfuscationSettingLNB,
 			"value_elicitation_setting": valueElicitationSettingLNB,
```
Comment (YakDriver) [inline internal/service/lexv2models/slot.go:571]: These should be alphabetical.

File: internal/service/lexv2models/slot_test.go [hunk 5]
```diff
@@ -359,3 +394,121 @@ resource "aws_lexv2models_slot" "test" {
...
+    }
+  }
+
+  multiple_values_setting {
+    allow_multiple_values = %[2]t
+  }
+
+  sub_slot_setting {
+    expression = "string"
+    slot_specifications {
```
Comment (YakDriver) [inline internal/service/lexv2models/slot_test.go:434]:
```suggestion
    slot_specification {
```

**Review by YakDriver — APPROVED** [review]
LGTM! Just a few nits.

File: internal/service/lexv2models/slot.go (hunk 3 above)
Comment (YakDriver) [reply internal/service/lexv2models/slot.go:493]: Autoflex should be able to match them up despite plural, singular difference.
