### PR TITLE
enhancement(rds): Support default_only, include_all, and filter for aws_rds_engine_version

### LINKED ISSUE #19715: datasource aws_rds_engine_version failed
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_v3.37.0

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
data "aws_rds_engine_version" "test" {
  engine             = "aurora-postgresql"
  version = "10.14"
}
```

### Expected Behavior

add more arguments to select only one specific version entry or give the array back 
### Actual Behavior

```
data.aws_rds_engine_version.test: Refreshing state...

Error: multiple RDS engine versions ([{
  DBEngineDescription: "Aurora (PostgreSQL)",
  DBEngineVersionDescription: "Aurora PostgreSQL (Compatible with PostgreSQL 10.14)",
  DBParameterGroupFamily: "aurora-postgresql10",
 ---
```

one entry for "provisioned" and one entry for "serverless" engine mode

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### References

* #0000

### LINKED ISSUE #26867: [Enhancement]: Add Filter to aws_rds_engine_version
### Description

Within the Console in AWS, when selecting Aurora, there is a section for filters:

Show versions that support the global database feature
Allows a single Amazon Aurora database to span multiple AWS Regions.

Show versions that support the parallel query feature
Improves the performance of analytic queries by pushing processing down to the Aurora storage layer.

Show versions that support Serverless v2
Offers instance scaling for even the most demanding workloads.

The Data resource aws_rds_engine_version should have these same options to return the default version within the filters defined where version and preferred version are not defined.

### Affected Resource(s) and/or Data Source(s)

data aws_rds_engine_version

### Potential Terraform Configuration

```terraform
data "aws_rds_engine_version" "test" {
  engine             = "mysql"
  filter = ["global", "parallel", "serverless v2"]
}
```

### References

_No response_

### Would you like to implement a fix?

_No response_

### PR DESCRIPTION
**Pull request by md5**
This PR adds support for `default_only`, `include_all`, and `filter` to the `aws_rds_engine_version` data source. Adding these flags make it possible to get the default minor version given only a major version for an engine, to distinguish between `provisioned` and `serverless` engine modes, or to allow querying of deprecated versions, among other things.

Closes #19715
Closes #26867

### CODE REVIEW

**Comment by md5** [comment]
Added some tests for the new additions. Here is the output of `make testacc`:

```console
% make testacc AWS_PROFILE=default TESTS=TestAccRDSEngineVersionDataSource PKG=rds
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccRDSEngineVersionDataSource'  -timeout 180m
=== RUN   TestAccRDSEngineVersionDataSource_basic
=== PAUSE TestAccRDSEngineVersionDataSource_basic
=== RUN   TestAccRDSEngineVersionDataSource_upgradeTargets
=== PAUSE TestAccRDSEngineVersionDataSource_upgradeTargets
=== RUN   TestAccRDSEngineVersionDataSource_preferred
=== PAUSE TestAccRDSEngineVersionDataSource_preferred
=== RUN   TestAccRDSEngineVersionDataSource_defaultOnlyImplicit
=== PAUSE TestAccRDSEngineVersionDataSource_defaultOnlyImplicit
=== RUN   TestAccRDSEngineVersionDataSource_defaultOnlyExplicit
=== PAUSE TestAccRDSEngineVersionDataSource_defaultOnlyExplicit
=== RUN   TestAccRDSEngineVersionDataSource_includeAll
=== PAUSE TestAccRDSEngineVersionDataSource_includeAll
=== RUN   TestAccRDSEngineVersionDataSource_filter
=== PAUSE TestAccRDSEngineVersionDataSource_filter
=== CONT  TestAccRDSEngineVersionDataSource_basic
=== CONT  TestAccRDSEngineVersionDataSource_defaultOnlyExplicit
=== CONT  TestAccRDSEngineVersionDataSource_preferred
=== CONT  TestAccRDSEngineVersionDataSource_defaultOnlyImplicit
=== CONT  TestAccRDSEngineVersionDataSource_filter
=== CONT  TestAccRDSEngineVersionDataSource_includeAll
=== CONT  TestAccRDSEngineVersionDataSource_upgradeTargets
--- PASS: TestAccRDSEngineVersionDataSource_upgradeTargets (11.06s)
--- PASS: TestAccRDSEngineVersionDataSource_includeAll (11.07s)
--- PASS: TestAccRDSEngineVersionDataSource_filter (11.27s)
--- PASS: TestAccRDSEngineVersionDataSource_defaultOnlyExplicit (11.27s)
--- PASS: TestAccRDSEngineVersionDataSource_defaultOnlyImplicit (11.27s)
--- PASS: TestAccRDSEngineVersionDataSource_basic (11.35s)
--- PASS: TestAccRDSEngineVersionDataSource_preferred (11.59s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/rds	14.068s
```

File: internal/service/rds/engine_version_data_source.go [hunk 1]
```diff
@@ -136,6 +149,18 @@ func dataSourceEngineVersionRead(d *schema.ResourceData, meta interface{}) error
 		input.Engine = aws.String(v.(string))
 	}
 
+	if v, ok := d.GetOk("default_only"); ok {
+		input.DefaultOnly = aws.Bool(v.(bool))
```
Comment (md5) [inline internal/service/rds/engine_version_data_source.go:153]: While updating the tests, I noticed that `DefaultOnly` is already being set below separately if neither `version` nor `preferred_versions` are set. Let me know if you'd like me to restructure this code to combine the two sections somehow.

I could see checking explicitly first for `default_only`, then having an `else if` with the existing checks to set `DefaultOnly` implicitly when `version` and `preferred_versions` are unset. Or I could see only checking `default_only` if one of `version` or `preferred_versions` are set. Another thing to consider is whether it makes sense to return an error if `default_only = false` is set explicitly without setting `version` or `preferred_versions`.

Comment (md5) [reply internal/service/rds/engine_version_data_source.go:153]:
```diff
diff --git a/internal/service/rds/engine_version_data_source.go b/internal/service/rds/engine_version_data_source.go
index 2a2d6206e1..9c8daba4c7 100644
--- a/internal/service/rds/engine_version_data_source.go
+++ b/internal/service/rds/engine_version_data_source.go
@@ -149,10 +149,6 @@ func dataSourceEngineVersionRead(d *schema.ResourceData, meta interface{}) error
 		input.Engine = aws.String(v.(string))
 	}
 
-	if v, ok := d.GetOk("default_only"); ok {
-		input.DefaultOnly = aws.Bool(v.(bool))
-	}
-
 	if v, ok := d.GetOk("filter"); ok {
 		input.Filters = namevaluesfilters.New(v.(*schema.Set)).RDSFilters()
 	}
@@ -169,7 +165,9 @@ func dataSourceEngineVersionRead(d *schema.ResourceData, meta interface{}) error
 		input.EngineVersion = aws.String(v.(string))
 	}
 
-	if _, ok := d.GetOk("version"); !ok {
+	if v, ok := d.GetOk("default_only"); ok {
+		input.DefaultOnly = aws.Bool(v.(bool))
+	} else if _, ok := d.GetOk("version"); !ok {
 		if _, ok := d.GetOk("preferred_versions"); !ok {
 			input.DefaultOnly = aws.Bool(true)
 		}
```

I feel like this is the right change to make. If a user explicitly sets `default_only`, the flag should not be set to a potentially different value just because `version` and `preferred_versions` are not set. If they set `default_only = false` without setting the other attributes in a way that will guarantee that the lookup only returns a single version, then it should be expected to fail.

Comment (md5) [reply internal/service/rds/engine_version_data_source.go]: I ended up making this change since it makes more sense to me. I can always change it back or to some other approach if that's what the eventual reviewer prefers.

**Comment by md5** [comment]
@justinretzolk do you have a sense for when the next round of PR triage will happen? I'd like to be able to plan for when this change might land in a release of the provider, particularly if I end up needing to address any feedback.

**Comment by md5** [comment]
@breathingdust I know I put `enhancement` in the title, but the original issue is marked as `bug`. Maybe this should be marked as `bug` too?

**Comment by md5** [comment]
Looks like this also closes #26867

**Comment by md5** [comment]
I just rebased this and reran the acceptance tests:

```console
% TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccRDSEngineVersionDataSource'  -timeout 180m
=== RUN   TestAccRDSEngineVersionDataSource_basic
=== PAUSE TestAccRDSEngineVersionDataSource_basic
=== RUN   TestAccRDSEngineVersionDataSource_upgradeTargets
=== PAUSE TestAccRDSEngineVersionDataSource_upgradeTargets
=== RUN   TestAccRDSEngineVersionDataSource_preferred
=== PAUSE TestAccRDSEngineVersionDataSource_preferred
=== RUN   TestAccRDSEngineVersionDataSource_defaultOnlyImplicit
=== PAUSE TestAccRDSEngineVersionDataSource_defaultOnlyImplicit
=== RUN   TestAccRDSEngineVersionDataSource_defaultOnlyExplicit
=== PAUSE TestAccRDSEngineVersionDataSource_defaultOnlyExplicit
=== RUN   TestAccRDSEngineVersionDataSource_includeAll
=== PAUSE TestAccRDSEngineVersionDataSource_includeAll
=== RUN   TestAccRDSEngineVersionDataSource_filter
=== PAUSE TestAccRDSEngineVersionDataSource_filter
=== CONT  TestAccRDSEngineVersionDataSource_basic
=== CONT  TestAccRDSEngineVersionDataSource_filter
=== CONT  TestAccRDSEngineVersionDataSource_defaultOnlyExplicit
=== CONT  TestAccRDSEngineVersionDataSource_includeAll
=== CONT  TestAccRDSEngineVersionDataSource_preferred
=== CONT  TestAccRDSEngineVersionDataSource_defaultOnlyImplicit
=== CONT  TestAccRDSEngineVersionDataSource_upgradeTargets
--- PASS: TestAccRDSEngineVersionDataSource_filter (11.73s)
--- PASS: TestAccRDSEngineVersionDataSource_includeAll (12.00s)
--- PASS: TestAccRDSEngineVersionDataSource_defaultOnlyExplicit (12.34s)
--- PASS: TestAccRDSEngineVersionDataSource_basic (12.34s)
--- PASS: TestAccRDSEngineVersionDataSource_defaultOnlyImplicit (12.34s)
--- PASS: TestAccRDSEngineVersionDataSource_upgradeTargets (12.35s)
--- PASS: TestAccRDSEngineVersionDataSource_preferred (12.42s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/rds	14.939s
```

**Comment by justinretzolk** [comment]
Hey @md5 👋 Thank you for your contribution, and for checking in on this! Unfortunately, I'm not able to provide an estimate on when this will be merged/reviewed due to the potential of shifting priorities (we prioritize work by count of ":+1:" reactions, as well as a few other things). For more information on how we prioritize, check out out [prioritization guide](https://hashicorp.github.io/terraform-provider-aws/prioritization/).

**Comment by md5** [comment]
> Hey @md5 👋 Thank you for your contribution, and for checking in on this! Unfortunately, I'm not able to provide an estimate on when this will be merged/reviewed due to the potential of shifting priorities (we prioritize work by count of "👍" reactions, as well as a few other things). For more information on how we prioritize, check out out [prioritization guide](https://hashicorp.github.io/terraform-provider-aws/prioritization/).

That's all well and good, but I see a bunch of PRs opened since mine was opened that have no 👍 at all that have already been merged. For example, this one was opened and merged within the past 5 hours: https://github.com/hashicorp/terraform-provider-aws/pull/27620. It doesn't even have an open issue that it was addressing.

**Comment by justinretzolk** [comment]
Hey @md5 👋 That's a great callout, and this is something that I'll start to think of how we can be a bit more clear about in the prioritization guide. I realize that you're making a more general statement and aren't pointing to that one PR in particular, but that one was contributed by a user who is in the top five all time contributors to the provider. It's sometimes the case that the team is able to review contributions from folks who contribute regularly a bit more quickly. This is also the true with small documentation fixes -- I'm the Technical Community Manager for the AWS provider, and while doing my daily triage I'll often get those merged in almost immediately.

I saw that you also commented on #27342. I just wanted to mention that both the author and reviewer are community members like yourself, and that it has not been prioritized or reviewed by the AWS provider team at this point. I suspect that PR will be closed in favor of this one since you've added `default_only` and `include_all` as well, but I'd like to leave that to whoever picks this up for review once we're able to prioritize it.

**Comment by md5** [comment]
@justinretzolk thanks for the clarification on #27342. I should have noticed that the reviewer was not a project member. The fact that GitHub uses "Contributor" and "Member" with the same badge styling and prominence has a tendency to confuse me.

**Review by jar-b — COMMENTED** [review]
LGTM 🎉 

```console
$ make testacc PKG=rds TESTS=TestAccRDSEngineVersionDataSource
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccRDSEngineVersionDataSource'  -timeout 180m
=== RUN   TestAccRDSEngineVersionDataSource_basic
=== PAUSE TestAccRDSEngineVersionDataSource_basic
=== RUN   TestAccRDSEngineVersionDataSource_upgradeTargets
=== PAUSE TestAccRDSEngineVersionDataSource_upgradeTargets
=== RUN   TestAccRDSEngineVersionDataSource_preferred
=== PAUSE TestAccRDSEngineVersionDataSource_preferred
=== RUN   TestAccRDSEngineVersionDataSource_defaultOnlyImplicit
=== PAUSE TestAccRDSEngineVersionDataSource_defaultOnlyImplicit
=== RUN   TestAccRDSEngineVersionDataSource_defaultOnlyExplicit
=== PAUSE TestAccRDSEngineVersionDataSource_defaultOnlyExplicit
=== RUN   TestAccRDSEngineVersionDataSource_includeAll
=== PAUSE TestAccRDSEngineVersionDataSource_includeAll
=== RUN   TestAccRDSEngineVersionDataSource_filter
=== PAUSE TestAccRDSEngineVersionDataSource_filter
=== CONT  TestAccRDSEngineVersionDataSource_basic
=== CONT  TestAccRDSEngineVersionDataSource_defaultOnlyExplicit
=== CONT  TestAccRDSEngineVersionDataSource_preferred
=== CONT  TestAccRDSEngineVersionDataSource_defaultOnlyImplicit
=== CONT  TestAccRDSEngineVersionDataSource_filter
=== CONT  TestAccRDSEngineVersionDataSource_includeAll
=== CONT  TestAccRDSEngineVersionDataSource_upgradeTargets
--- PASS: TestAccRDSEngineVersionDataSource_includeAll (15.65s)
--- PASS: TestAccRDSEngineVersionDataSource_upgradeTargets (15.72s)
--- PASS: TestAccRDSEngineVersionDataSource_filter (15.75s)
--- PASS: TestAccRDSEngineVersionDataSource_defaultOnlyExplicit (15.83s)
--- PASS: TestAccRDSEngineVersionDataSource_defaultOnlyImplicit (15.87s)
--- PASS: TestAccRDSEngineVersionDataSource_basic (15.97s)
--- PASS: TestAccRDSEngineVersionDataSource_preferred (16.72s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/rds        19.347s
```

**Review by jar-b — APPROVED** [review]

**Comment by jar-b** [comment]
Thanks for your contribution @md5 👏
