### PR TITLE
[Enhancement] aws_pinpointsmsvoice2_phone_number: Support Amazon Connect as the inbound destination for two-way SMS

### LINKED ISSUE #44321: aws_pinpointsmsvoicev2_phone_number - two_way_channel_arn - Amazon Connect ARN
### Terraform and AWS Provider Version

```console
Terraform v1.11.4 on linux_amd64
provider "registry.terraform.io/hashicorp/aws"  version     = "6.13.0"
```

### Affected Resource(s) or Data Source(s)

```terraform
resource "aws_pinpointsmsvoicev2_phone_number" "smsnumber" {
    for_each = var.awssmsnumber
    iso_country_code = each.value.country_code
    message_type     = each.value.message_type
    number_type      = each.value.number_type
    number_capabilities = each.value.number_capabilities
    two_way_channel_enabled = each.value.two_way
    two_way_channel_arn = each.value.two_way != false ? each.value.two_way_channel_arn : null
    two_way_channel_role = each.value.two_way != false ? aws_iam_role.smsnumber[each.key].arn : null
}
```

### Expected Behavior

The provider should detect that the settings in AWS are of Amazon Connect, then query for the Amazon Connect ARN to use within the provider.

### Actual Behavior

Amazon Connect - The AWS configuration sets the Incoming messages destination to connect.eu-west-2.amazonaws.com, which isn't an ARN.

This results in the following error
Error: Invalid ARN Value

### Relevant Error/Panic Output

```console
  │ Error: Invalid ARN Value
  │
  │   with aws_pinpointsmsvoicev2_phone_number.smsnumber["sms1"],
  │   on main.tf line 11, in resource "aws_pinpointsmsvoicev2_phone_number" "smsnumber":
  │   11:     two_way_channel_arn = each.value.two_way != false ? each.value.two_way_channel_arn : null
  │
  │ The provided value cannot be parsed as an ARN.
  │
  │ Path: two_way_channel_arn
  │ Value: connect.eu-west-2.amazonaws.com

```

### Sample Terraform Configuration

<details open>
<summary>Click to expand configuration</summary>

```terraform
//variable value =  awssmsnumber = { "sms1" = {two_way = true, two_way_channel_arn = "ARN"}}
data "aws_caller_identity" "current" {}

#https://docs.aws.amazon.com/connect/latest/adminguide/setup-sms-messaging.html#get-sms-number
resource "aws_pinpointsmsvoicev2_phone_number" "smsnumber" {
    for_each = var.awssmsnumber
    iso_country_code = each.value.country_code
    message_type     = each.value.message_type
    number_type      = each.value.number_type
    number_capabilities = each.value.number_capabilities
    two_way_channel_enabled = each.value.two_way
    two_way_channel_arn = each.value.two_way != false ? each.value.two_way_channel_arn : null
    two_way_channel_role = each.value.two_way != false ? aws_iam_role.smsnumber[each.key].arn : null
    

}

resource "aws_iam_role" "smsnumber" {
    for_each = var.awssmsnumber
    name = "sms_connect_${each.key}"
    assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = "sts:AssumeRole"
        "Condition": {
        "StringEquals": {
          "aws:SourceAccount": "${data.aws_caller_identity.current.account_id}"
        }}
        Effect = "Allow"
        Sid    = ""
        Principal = {
          Service = "sms-voice.amazonaws.com"
        }
      },
    ]
  })
}


resource "aws_iam_policy" "smsnumber" {
    for_each = var.awssmsnumber
  name        = "sms_connect_${each.key}"
  path        = "/"
  description = "sms_connect_${each.key}"

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = [
          "connect:SendChatIntegrationEvent",
        ]
        Effect   = "Allow"
        Resource = "*"
      },
    ]
  })
}

resource "aws_iam_role_policy_attachment" "smsnumber" {
    for_each = var.awssmsnumber
  
  role       = aws_iam_role.smsnumber[each.key].name
  policy_arn = aws_iam_policy.smsnumber[each.key].arn
}

variable "awssmsnumber" {
    type = map(object({
        country_code = optional(string, "GB")
        message_type = optional(string, "PROMOTIONAL")
        number_type = optional(string, "LONG_CODE")
        number_capabilities = optional(list(string),["SMS"])
        two_way = optional(bool, false)
        two_way_channel_arn = optional(string, null)
    }))
}
```

</details>

### Steps to Reproduce

Create a main.tf with the code attached.
Create an Amazon Connect Instance.
Use the ARN of the Amazon Connect instance in the variable value awssmsnumber = { "sms1" = {two_way = true, two_way_channel_arn = "ARN"}}

The issue will appear when running a plan or apply.

### Debug Logging

<details open>
<summary>Click to expand log output</summary>

```console

```
</details>

### GenAI / LLM Assisted Development

n/a

### Important Facts and References

_No response_

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by tabito-hara**
## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the library.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

### Description

This PR updates the `two_way_channel_arn` argument to support using Amazon Connect as the inbound destination for two-way SMS.  

* The argument type is changed from `ARNType` to `StringType`, removing the strict ARN-only validation.  
* Instead of removing validation entirely, new checks ensure the value either starts with `arn` or matches `connect\.[a-z0-9-]+\.amazonaws.com`.  
* A new acceptance test confirms that `connect.[region].amazonaws.com` is accepted as a valid value for `two_way_channel_arn`.  

### Relations

Closes #44321

### References
https://docs.aws.amazon.com/sms-voice/latest/userguide/two-way-sms-phone-number.html

> To set Amazon Connect as the inbound destination set `TwoWayARN` to `connect.region.amazonaws.com`. Replace region with the AWS Region the Amazon Connect instance is hosted in.

### Output from Acceptance Testing

```console
$ make testacc TESTS='TestAccPinpointSMSVoiceV2PhoneNumber_' PKG=pinpointsmsvoicev2 
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿  f-aws_pinpointsmsvoice2_phone_number-support_amazon_connect_two_way_channel 🌿...
TF_ACC=1 go1.24.6 test ./internal/service/pinpointsmsvoicev2/... -v -count 1 -parallel 20 -run='TestAccPinpointSMSVoiceV2PhoneNumber_'  -timeout 360m -vet=off
2025/09/19 07:47:20 Creating Terraform AWS Provider (SDKv2-style)...
2025/09/19 07:47:20 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccPinpointSMSVoiceV2PhoneNumber_basic
=== PAUSE TestAccPinpointSMSVoiceV2PhoneNumber_basic
=== RUN   TestAccPinpointSMSVoiceV2PhoneNumber_full
=== PAUSE TestAccPinpointSMSVoiceV2PhoneNumber_full
=== RUN   TestAccPinpointSMSVoiceV2PhoneNumber_twoWayChannelRole
=== PAUSE TestAccPinpointSMSVoiceV2PhoneNumber_twoWayChannelRole
=== RUN   TestAccPinpointSMSVoiceV2PhoneNumber_twoWayChannelConnect
=== PAUSE TestAccPinpointSMSVoiceV2PhoneNumber_twoWayChannelConnect
=== RUN   TestAccPinpointSMSVoiceV2PhoneNumber_disappears
=== PAUSE TestAccPinpointSMSVoiceV2PhoneNumber_disappears
=== RUN   TestAccPinpointSMSVoiceV2PhoneNumber_tags
=== PAUSE TestAccPinpointSMSVoiceV2PhoneNumber_tags
=== CONT  TestAccPinpointSMSVoiceV2PhoneNumber_basic
=== CONT  TestAccPinpointSMSVoiceV2PhoneNumber_twoWayChannelConnect
=== CONT  TestAccPinpointSMSVoiceV2PhoneNumber_twoWayChannelRole
=== CONT  TestAccPinpointSMSVoiceV2PhoneNumber_tags
=== CONT  TestAccPinpointSMSVoiceV2PhoneNumber_disappears
=== CONT  TestAccPinpointSMSVoiceV2PhoneNumber_full
--- PASS: TestAccPinpointSMSVoiceV2PhoneNumber_basic (45.90s)
--- PASS: TestAccPinpointSMSVoiceV2PhoneNumber_twoWayChannelConnect (50.37s)
--- PASS: TestAccPinpointSMSVoiceV2PhoneNumber_tags (61.25s)
--- PASS: TestAccPinpointSMSVoiceV2PhoneNumber_twoWayChannelRole (68.25s)
--- PASS: TestAccPinpointSMSVoiceV2PhoneNumber_disappears (70.83s)
--- PASS: TestAccPinpointSMSVoiceV2PhoneNumber_full (73.54s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/pinpointsmsvoicev2 77.692s

```

### CODE REVIEW

File: internal/service/pinpointsmsvoicev2/phone_number.go [hunk 1]
```diff
@@ -128,12 +128,15 @@ func (r *phoneNumberResource) Schema(ctx context.Context, request resource.Schem
...
 			"two_way_channel_arn": schema.StringAttribute{
-				CustomType: fwtypes.ARNType,
-				Optional:   true,
+				Optional: true,
 				Validators: []validator.String{
 					stringvalidator.AlsoRequires(
 						path.MatchRelative().AtParent().AtName("two_way_channel_enabled"),
 					),
+					stringvalidator.Any(
+						stringvalidator.RegexMatches(regexache.MustCompile(`^arn`), "must be a valid ARN"),
```
Comment (ewbankkit) [inline internal/service/pinpointsmsvoicev2/phone_number.go]: Can use validator in `internal/framework/validators/arn.go`.

Comment (tabito-hara) [reply internal/service/pinpointsmsvoicev2/phone_number.go]: @ewbankkit 

Thank you for your comment.
Fixed.

Reran the acceptance test and confirmed ok.
```console
$ make testacc TESTS='TestAccPinpointSMSVoiceV2PhoneNumber_' PKG=pinpointsmsvoicev2 
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 f-aws_pinpointsmsvoice2_phone_number-support_amazon_connect_two_way_channel 🌿...
TF_ACC=1 go1.24.6 test ./internal/service/pinpointsmsvoicev2/... -v -count 1 -parallel 20 -run='TestAccPinpointSMSVoiceV2PhoneNumber_'  -timeout 360m -vet=off
2025/09/25 08:47:55 Creating Terraform AWS Provider (SDKv2-style)...
2025/09/25 08:47:55 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccPinpointSMSVoiceV2PhoneNumber_basic
=== PAUSE TestAccPinpointSMSVoiceV2PhoneNumber_basic
=== RUN   TestAccPinpointSMSVoiceV2PhoneNumber_full
=== PAUSE TestAccPinpointSMSVoiceV2PhoneNumber_full
=== RUN   TestAccPinpointSMSVoiceV2PhoneNumber_twoWayChannelRole
=== PAUSE TestAccPinpointSMSVoiceV2PhoneNumber_twoWayChannelRole
=== RUN   TestAccPinpointSMSVoiceV2PhoneNumber_twoWayChannelConnect
=== PAUSE TestAccPinpointSMSVoiceV2PhoneNumber_twoWayChannelConnect
=== RUN   TestAccPinpointSMSVoiceV2PhoneNumber_disappears
=== PAUSE TestAccPinpointSMSVoiceV2PhoneNumber_disappears
=== RUN   TestAccPinpointSMSVoiceV2PhoneNumber_tags
=== PAUSE TestAccPinpointSMSVoiceV2PhoneNumber_tags
=== CONT  TestAccPinpointSMSVoiceV2PhoneNumber_basic
=== CONT  TestAccPinpointSMSVoiceV2PhoneNumber_twoWayChannelConnect
=== CONT  TestAccPinpointSMSVoiceV2PhoneNumber_tags
=== CONT  TestAccPinpointSMSVoiceV2PhoneNumber_disappears
=== CONT  TestAccPinpointSMSVoiceV2PhoneNumber_twoWayChannelRole
=== CONT  TestAccPinpointSMSVoiceV2PhoneNumber_full
--- PASS: TestAccPinpointSMSVoiceV2PhoneNumber_twoWayChannelConnect (35.94s)
--- PASS: TestAccPinpointSMSVoiceV2PhoneNumber_disappears (39.17s)
--- PASS: TestAccPinpointSMSVoiceV2PhoneNumber_basic (39.85s)
--- PASS: TestAccPinpointSMSVoiceV2PhoneNumber_full (68.24s)
--- PASS: TestAccPinpointSMSVoiceV2PhoneNumber_tags (78.14s)
--- PASS: TestAccPinpointSMSVoiceV2PhoneNumber_twoWayChannelRole (85.66s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/pinpointsmsvoicev2 90.309s


```

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccPinpointSMSVoiceV2PhoneNumber_' PKG=pinpointsmsvoicev2 
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 HEAD 🌿...
TF_ACC=1 go1.24.6 test ./internal/service/pinpointsmsvoicev2/... -v -count 1 -parallel 20  -run=TestAccPinpointSMSVoiceV2PhoneNumber_ -timeout 360m -vet=off
2025/09/25 11:39:21 Creating Terraform AWS Provider (SDKv2-style)...
2025/09/25 11:39:21 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccPinpointSMSVoiceV2PhoneNumber_basic
=== PAUSE TestAccPinpointSMSVoiceV2PhoneNumber_basic
=== RUN   TestAccPinpointSMSVoiceV2PhoneNumber_full
=== PAUSE TestAccPinpointSMSVoiceV2PhoneNumber_full
=== RUN   TestAccPinpointSMSVoiceV2PhoneNumber_twoWayChannelRole
=== PAUSE TestAccPinpointSMSVoiceV2PhoneNumber_twoWayChannelRole
=== RUN   TestAccPinpointSMSVoiceV2PhoneNumber_twoWayChannelConnect
=== PAUSE TestAccPinpointSMSVoiceV2PhoneNumber_twoWayChannelConnect
=== RUN   TestAccPinpointSMSVoiceV2PhoneNumber_disappears
=== PAUSE TestAccPinpointSMSVoiceV2PhoneNumber_disappears
=== RUN   TestAccPinpointSMSVoiceV2PhoneNumber_tags
=== PAUSE TestAccPinpointSMSVoiceV2PhoneNumber_tags
=== CONT  TestAccPinpointSMSVoiceV2PhoneNumber_basic
=== CONT  TestAccPinpointSMSVoiceV2PhoneNumber_twoWayChannelConnect
=== CONT  TestAccPinpointSMSVoiceV2PhoneNumber_tags
=== CONT  TestAccPinpointSMSVoiceV2PhoneNumber_disappears
=== CONT  TestAccPinpointSMSVoiceV2PhoneNumber_twoWayChannelRole
=== CONT  TestAccPinpointSMSVoiceV2PhoneNumber_full
--- PASS: TestAccPinpointSMSVoiceV2PhoneNumber_twoWayChannelConnect (32.90s)
--- PASS: TestAccPinpointSMSVoiceV2PhoneNumber_full (41.18s)
--- PASS: TestAccPinpointSMSVoiceV2PhoneNumber_disappears (45.96s)
--- PASS: TestAccPinpointSMSVoiceV2PhoneNumber_twoWayChannelRole (48.34s)
--- PASS: TestAccPinpointSMSVoiceV2PhoneNumber_tags (55.05s)
--- PASS: TestAccPinpointSMSVoiceV2PhoneNumber_basic (67.21s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/pinpointsmsvoicev2	73.171s
```

**Comment by ewbankkit** [comment]
@tabito-hara Thanks for the contribution :tada: :clap:.

**Comment by vijaykotechnologies** [comment]
@tabito-hara Many thanks for your time and effort in fixing this issue for us.
