### PR TITLE
d/aws_mq_broker: `logs.audit` is TypeString (NullableBool)

### LINKED ISSUE #19494: data.aws_mq_broker results in error  "logs: logs.0.audit: '' expected type 'bool', got unconvertible type 'string'"
I am trying to upgrade terraform 0.14.8 ->0.15.4 and terraform-aws-provider 3.32.0 ->3.42.0.

This has been ok in numerous accounts until I do it on an account that has AmazonMQ (ActiveMQ)

I encountered this error :
```

Error: error setting logs: logs.0.audit: '' expected type 'bool', got unconvertible type 'string'

│   with data.aws_mq_broker.amazon-mq-01,
│   on amazon-mq-02.tf line 12, in data "aws_mq_broker" "amazon-mq-01":
│   12: data "aws_mq_broker" "amazon-mq-01" {
```

The line in question is : 

```
data "aws_mq_broker" "amazon-mq-01" {
  broker_id = "b-f19ff297-ebe4-4593-935f-ee1d3036115a"
}
```

I stayed on terraform 0.15.4 but down-graded back to 3.32.0.  All OK now. 
I upgrade to 3.37.0 and all OK.
I upgrade from 3.37.0 to 3.37.0 and I get the error : 

Error: error setting logs: logs.0.audit: '' expected type 'bool', got unconvertible type 'string'

I'd suspect something to 

```
$ terraform -v
Terraform v0.15.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.38.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
```

This is run from Fedora Linux 33

```
$ uname -a
Linux laptop.foobar.com 5.11.21-200.fc33.x86_64 #1 SMP Sat May 15 20:31:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

There are a few mentions in the release notes for 3.38.0 relating to new RabittMQ support. Maybe this has caused a regression ?
* Merge pull request #19066 from hashicorp/rabbitmq-logs
* Merge pull request #19142 from hashicorp/rabbitmq-logs

### Panic Output
none

### Expected Behavior

The upgrade and terraform apply should complete without error

### Actual Behavior

```
Error : 
Error: error setting logs: logs.0.audit: '' expected type 'bool', got unconvertible type 'string'
│   with data.aws_mq_broker.amazon-mq-01,
│   on amazon-mq-02.tf line 12, in data "aws_mq_broker" "amazon-mq-01":
│   12: data "aws_mq_broker" "amazon-mq-01" {
```

### Steps to Reproduce

In 3.37.0 create an AmazonMQ like this : 
```

resource "aws_mq_broker" "amazon-mq" {
    apply_immediately          = true
    authentication_strategy    = "simple"
    auto_minor_version_upgrade = true
    broker_name                = "amazon-mq-01"
    deployment_mode            = "SINGLE_INSTANCE"
    engine_type                = "ActiveMQ"
    engine_version             = "5.15.15"
    host_instance_type         = "mq.t3.micro"
    publicly_accessible        = false
    security_groups            = [
        "sg-.....",
    ]
    storage_type               = "efs"
    subnet_ids                 = [
        "subnet-.......",
    ]
    tags                       = {
        "Environment"     = "staging"
    }
    configuration {
        id       = aws_mq_configuration.amazon-mq.id
        revision = aws_mq_configuration.amazon-mq.latest_revision
    }
    encryption_options {
        use_aws_owned_key = true
    }
    logs {
        audit   = true
        general = true
    }
    maintenance_window_start_time {
        day_of_week = "SUNDAY"
        time_of_day = "02:00"
        time_zone   = "UTC"
    }
    user {
        console_access = false
        groups         = []
        password       = (sensitive value)
        username       = "MQ_APP"
    }
    user {
        console_access = true
        groups         = [
            "admin",
        ]
        password       = (sensitive value)
        username       = "MQ_ADMIN"
    }
}
resource "aws_mq_configuration" "amazon-mq" {
    authentication_strategy = "simple"
    data                    = <<-EOT
		....
    EOT
    description             = "..."
    engine_type             = "ActiveMQ"
    engine_version          = "5.15.15"
    latest_revision         = 2
    name                    = "amazon-mq-01"
    tags                    = {}
}
data "aws_mq_broker" "amazon-mq-01" {
  broker_id = aws_mq_broker.amazon-mq.id
}
```

Note: above taken from a "terraform show state"  and sensitve info redacted so is not exact replica of my terraform.

Then terraform apply - all should be OK

Then upgrade to 3.38.0 with 

terraform init -upgrade

Then "terraform apply" and should get error : 

`Error: error setting logs: logs.0.audit: '' expected type 'bool', got unconvertible type 'string'`

### Important Factoids

none

### References

Maybe relates to changes in release notes for 3.38.0 : 

https://github.com/hashicorp/terraform-provider-aws/pull/19066
https://github.com/hashicorp/terraform-provider-aws/pull/19142

* #0000

### PR DESCRIPTION
**Pull request by ewbankkit**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #19494.

Output from acceptance testing:

#### Commercial

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccDataSourceAWSMqBroker_'     
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccDataSourceAWSMqBroker_ -timeout 180m
=== RUN   TestAccDataSourceAWSMqBroker_basic
=== PAUSE TestAccDataSourceAWSMqBroker_basic
=== CONT  TestAccDataSourceAWSMqBroker_basic
--- PASS: TestAccDataSourceAWSMqBroker_basic (1180.32s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	1183.527s
```

#### GovCloud

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccDataSourceAWSMqBroker_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccDataSourceAWSMqBroker_ -timeout 180m
=== RUN   TestAccDataSourceAWSMqBroker_basic
=== PAUSE TestAccDataSourceAWSMqBroker_basic
=== CONT  TestAccDataSourceAWSMqBroker_basic
    provider_test.go:734: skipping tests; partition aws-us-gov does not support mq service
--- SKIP: TestAccDataSourceAWSMqBroker_basic (1.36s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	4.399s
```

### CODE REVIEW

File: aws/data_source_aws_mq_broker.go [hunk 1]
```diff
@@ -162,23 +163,15 @@ func dataSourceAwsMqBroker() *schema.Resource {
...
 				Type:     schema.TypeList,
-				Optional: true,
-				MaxItems: 1,
-				// Ignore missing configuration block
-				DiffSuppressFunc: func(k, old, new string, d *schema.ResourceData) bool {
-					if old == "1" && new == "0" {
-						return true
-					}
-					return false
-				},
```
Comment (anGie44) [inline aws/data_source_aws_mq_broker.go:173]: 💯

**Review by anGie44 — APPROVED** [review]
LGTM 👍
