### PR TITLE
aws_sagemaker_app_image_config: have at least one jupyterlab, codeeditor or kernel gateway config block, and push them even if empty fixes #37766 #40493

### LINKED ISSUE #37766: [Bug]: Empty jupyter_lab_image_config block in aws_sagemaker_app_image_config not persisted
### Terraform Core Version

1.8.4

### AWS Provider Version

5.51.1

### Affected Resource(s)

* aws_sagemaker_app_image_config

### Expected Behavior

The empty `jupyter_lab_image_config` block is meaningful and should be persisted.

### Actual Behavior

The empty `jupyter_lab_image_config` block is not persisted. Note that terraform apply succeeds, but an `InternalFailure` error occurs when JupyterLab starts. In addition, a plan diff still remains after apply and never converge.

### Relevant Error/Panic Output Snippet

_No response_

### Terraform Configuration Files

```main.tf
terraform {
  required_version = "1.8.4"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.51.1"
    }
  }
}

provider "aws" {
  region  = "us-east-1"
}

resource "aws_sagemaker_app_image_config" "foo" {
  app_image_config_name = "foo"

  jupyter_lab_image_config {}
}
```

### Steps to Reproduce

1. terraform apply
2. terraform plan

You can see that the plan diff is still there after apply.

```
  # aws_sagemaker_app_image_config.foo will be updated in-place
  ~ resource "aws_sagemaker_app_image_config" "foo" {
        id                    = "foo"
        tags                  = {}
        # (3 unchanged attributes hidden)

      + jupyter_lab_image_config {
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

The resource doesn't contain the `“JupyterLabAppImageConfig”:{}` parameter.

```
$ aws sagemaker list-app-image-configs --name-contains foo
{
    "AppImageConfigs": [
        {
            "AppImageConfigArn": "arn:aws:sagemaker:us-east-1:xxxx:app-image-config/foo",
            "AppImageConfigName": "foo",
            "CreationTime": "2024-05-30T10:47:47.054000+09:00",
            "LastModifiedTime": "2024-05-30T10:47:47.057000+09:00"
        }
    ]
}
```

### Debug Output

I checked the trace log and the API request for UpdateAppImageConfig did not contain the `“JupyterLabAppImageConfig”:{}` parameter.

```
2024-05-30T10:53:12.742+0900 [DEBUG] provider.terraform-provider-aws_v5.51.1_x5: HTTP Request Sent: net.peer.name=api.sagemaker.us-east-1.amazonaws.com aws.region=us-east-1 rpc.method=UpdateAppImageConfig tf_aws.sdk=aws-sdk-go tf_resource_type=aws_sagemaker_app_image_config http.request.header.authorization="AWS4-HMAC-SHA256 Credential=ASIA************R374/20240530/us-east-1/sagemaker/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date;x-amz-security-token;x-amz-target, Signature=*****" http.request.header.x_amz_date=20240530T015312Z tf_provider_addr=registry.terraform.io/hashicorp/aws tf_req_id=4c08a435-a553-ae85-5966-2275c733a30c http.url=https://api.sagemaker.us-east-1.amazonaws.com/ @module=aws tf_mux_provider="*schema.GRPCProviderServer" tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/aws-sdk-go-base/v2/awsv1shim/v2@v2.0.0-beta.54/logger.go:109 http.method=POST rpc.service=SageMaker http.flavor=1.1
  http.request.body=
  | {"AppImageConfigName":"foo"}
   http.request.header.x_amz_security_token="*****" http.user_agent="APN/1.0 HashiCorp/1.0 Terraform/1.8.4 (+https://www.terraform.io/) terraform-provider-aws/5.51.1 (+https://registry.terraform.io/providers/hashicorp/aws) aws-sdk-go/1.53.8 (go1.22.2; darwin; arm64)" http.request.header.content_type=application/x-amz-json-1.1 http.request.header.x_amz_target=SageMaker.UpdateAppImageConfig http.request_content_length=28 rpc.system=aws-api timestamp="2024-05-30T10:53:12.742+0900"
```

### Panic Output

_No response_

### Important Factoids

As already mentioned in https://github.com/hashicorp/terraform-provider-aws/issues/36828#issuecomment-2051395207, it is possible to persist the `jupyter_lab_image_config` by including an empty `container_config` block.

```
resource "aws_sagemaker_app_image_config" "foo" {
  app_image_config_name = "foo"

  jupyter_lab_image_config {
    container_config {}
  }
}
```

However, this doesn't persist the empty container_config and results in a plan diff after apply.

```
  # aws_sagemaker_app_image_config.foo will be updated in-place
  ~ resource "aws_sagemaker_app_image_config" "foo" {
        id                    = "foo"
        tags                  = {}
        # (3 unchanged attributes hidden)

      ~ jupyter_lab_image_config {
          + container_config {}
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

A temporary workaround is to specify `ignore_changes` to `container_config`.

```
resource "aws_sagemaker_app_image_config" "foo" {
  app_image_config_name = "foo"

  jupyter_lab_image_config {
    container_config {}
  }

  lifecycle {
    ignore_changes = [
      jupyter_lab_image_config[0].container_config,
    ]
  }
}
```

### References

https://github.com/hashicorp/terraform-provider-aws/issues/36828

### Would you like to implement a fix?

None

### LINKED ISSUE #40493: [Bug]: Sagemaker Jupyterlab image attached via terraform provider fails booting
### Terraform Core Version

1.6.1

### AWS Provider Version

5.78.0

### Affected Resource(s)

aws_sagemaker_app_image_config
aws_sagemaker_image_version
aws_sagemaker_image
aws_sagemaker_domain

### Expected Behavior

When creating a new image, with its version and image config, and attaching it to the sagemaker domain by specifiying it in the domain configuration default_user_settings.jupyter_lab_app_settings.custom_image, the image should be usable in sagemaker studio. 
```
dynamic "custom_image" {
        for_each = aws_sagemaker_image_version.my_image_version
        content {
          app_image_config_name = custom_image.key
          image_name            = custom_image.value.id
          image_version_number  = custom_image.value.version
        }
      }
 ```

### Actual Behavior

The image seems to be correctly attached to the domain but it is unusable in studio, no error on terraform is produced, When launching the image in sagemaker domain, the error on AWS side is Internal Error and no cloudwatch log is produced. 
Iam Role permissions and anything else have been ruled out by creating an image from the console with the exact same configuration and attaching it via console, then importing into terraform and verifying there were no differences.

### Relevant Error/Panic Output Snippet

_No response_

### Terraform Configuration Files

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.74.0"
    }
  }

  required_version = ">= 1.6.0"
}
```

```
resource "aws_sagemaker_domain" "sagemaker_domain" {
...


  default_user_settings {
    ...
    jupyter_lab_app_settings {
     

      dynamic "custom_image" {
        for_each = aws_sagemaker_image_version.my_image_version
        content {
          app_image_config_name = custom_image.key
          image_name            = custom_image.value.id
          image_version_number  = custom_image.value.version
        }
      }

    }
    
  }
}

resource "aws_sagemaker_image" "my_image" {
  for_each = var.custom_images
  image_name = each.value.name
  display_name = each.value.name
  description = each.value.description
  role_arn   = aws_iam_role.sagemaker_execution_role.arn
}

resource "aws_sagemaker_image_version" "my_image_version" {
  for_each = var.custom_images
  image_name = aws_sagemaker_image.cuebiq_image[each.key].id
  base_image = each.value.image_uri
}

resource "aws_sagemaker_app_image_config" "my_image_config" {
  for_each = var.custom_images
  app_image_config_name = each.key
  tags = {}
  jupyter_lab_image_config {}
}
 ```
 
 ```
 variable "custom_images" {
  type = map(
    object({
      name            = string
      version  = number
      image_uri = string
      description = optional(string)
    })
  )
}
```

### Steps to Reproduce

create with terraform a sagemaker domain, an image, an image version, an image configuration and attach it to the domain.

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by psantus**
### Description

It is currently possible to push an empty `aws_sagemaker_app_image_config`, which is meaningless and leads to spaces not starting properly.

Users trying to add an empty `jupyter_lab_image_config` found it was not pushed to the API, and had to uses a trick/workaround, by embedding a unrequired `container_config` subblock  

This PR fixes both behaviours. 

### Relations
Closes #37766 
Closes #40493

### Output from Acceptance Testing

Nota : tests relying on illegal resources (aws_sagemaker_app_image_config without either `jupyter_lab_image_config`, `code_editor_app_image_config`, or `kernel_gateway_image_config) were removed.

```console
% go test -v ./internal/service/sagemaker -run=TestAccSageMakerAppImageConfig

2025/05/24 00:51:50 Creating Terraform AWS Provider (SDKv2-style)...
2025/05/24 00:51:50 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccSageMakerAppImageConfig_KernelGatewayImage_kernelSpecs
=== PAUSE TestAccSageMakerAppImageConfig_KernelGatewayImage_kernelSpecs
=== RUN   TestAccSageMakerAppImageConfig_KernelGatewayImage_fileSystem
=== PAUSE TestAccSageMakerAppImageConfig_KernelGatewayImage_fileSystem
=== RUN   TestAccSageMakerAppImageConfig_CodeEditor
=== PAUSE TestAccSageMakerAppImageConfig_CodeEditor
=== RUN   TestAccSageMakerAppImageConfig_JupyterLab
=== PAUSE TestAccSageMakerAppImageConfig_JupyterLab
=== RUN   TestAccSageMakerAppImageConfig_tags
--- PASS: TestAccSageMakerAppImageConfig_tags (53.94s)
=== CONT  TestAccSageMakerAppImageConfig_KernelGatewayImage_kernelSpecs
=== CONT  TestAccSageMakerAppImageConfig_CodeEditor
=== CONT  TestAccSageMakerAppImageConfig_JupyterLab
=== CONT  TestAccSageMakerAppImageConfig_KernelGatewayImage_fileSystem
--- PASS: TestAccSageMakerAppImageConfig_KernelGatewayImage_fileSystem (38.86s)
--- PASS: TestAccSageMakerAppImageConfig_KernelGatewayImage_kernelSpecs (38.89s)
--- PASS: TestAccSageMakerAppImageConfig_JupyterLab (41.16s)
--- PASS: TestAccSageMakerAppImageConfig_CodeEditor (41.17s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker  99.182s

...
```

### CODE REVIEW

File: internal/service/sagemaker/app_image_config.go [hunk 1]
```diff
@@ -51,9 +65,10 @@ func resourceAppImageConfig() *schema.Resource {
 				),
 			},
 			"code_editor_app_image_config": {
-				Type:     schema.TypeList,
-				Optional: true,
-				MaxItems: 1,
+				Type:          schema.TypeList,
+				Optional:      true,
+				MaxItems:      1,
+				ConflictsWith: []string{"jupyter_lab_image_config", "kernel_gateway_image_config"},
```
Comment (DrFaust92) [inline internal/service/sagemaker/app_image_config.go:71]: can we try `AtLeastOneOf` instead?

Comment (psantus) [reply internal/service/sagemaker/app_image_config.go:71]: The line you commented would rather be AtMostOneOf.. (ConflictsWith is used this way for example in the Firehose data stream resource)

The AtLeastOneOf part is L41-45... but AFAIK that only applies for blocks argument, not top-level blocks. For those I saw somewhere that done out of the schema, in a validator..

In short, many options, not sure there is a definite best practice here?

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccSageMakerAppImageConfig_' PKG=sagemaker ACCTEST_PARALLELISM=3
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.24.4 test ./internal/service/sagemaker/... -v -count 1 -parallel 3  -run=TestAccSageMakerAppImageConfig_ -timeout 360m -vet=off
2025/06/12 16:50:54 Creating Terraform AWS Provider (SDKv2-style)...
2025/06/12 16:50:54 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccSageMakerAppImageConfig_basic
=== PAUSE TestAccSageMakerAppImageConfig_basic
=== RUN   TestAccSageMakerAppImageConfig_disappears
=== PAUSE TestAccSageMakerAppImageConfig_disappears
=== RUN   TestAccSageMakerAppImageConfig_KernelGatewayImage_kernelSpecs
=== PAUSE TestAccSageMakerAppImageConfig_KernelGatewayImage_kernelSpecs
=== RUN   TestAccSageMakerAppImageConfig_KernelGatewayImage_fileSystem
=== PAUSE TestAccSageMakerAppImageConfig_KernelGatewayImage_fileSystem
=== RUN   TestAccSageMakerAppImageConfig_CodeEditor
=== PAUSE TestAccSageMakerAppImageConfig_CodeEditor
=== RUN   TestAccSageMakerAppImageConfig_JupyterLab
=== PAUSE TestAccSageMakerAppImageConfig_JupyterLab
=== RUN   TestAccSageMakerAppImageConfig_tags
--- PASS: TestAccSageMakerAppImageConfig_tags (30.91s)
=== CONT  TestAccSageMakerAppImageConfig_basic
=== CONT  TestAccSageMakerAppImageConfig_KernelGatewayImage_fileSystem
=== CONT  TestAccSageMakerAppImageConfig_JupyterLab
--- PASS: TestAccSageMakerAppImageConfig_basic (15.21s)
=== CONT  TestAccSageMakerAppImageConfig_CodeEditor
--- PASS: TestAccSageMakerAppImageConfig_JupyterLab (21.72s)
=== CONT  TestAccSageMakerAppImageConfig_KernelGatewayImage_kernelSpecs
--- PASS: TestAccSageMakerAppImageConfig_KernelGatewayImage_fileSystem (24.13s)
=== CONT  TestAccSageMakerAppImageConfig_disappears
--- PASS: TestAccSageMakerAppImageConfig_disappears (10.85s)
--- PASS: TestAccSageMakerAppImageConfig_CodeEditor (21.62s)
--- PASS: TestAccSageMakerAppImageConfig_KernelGatewayImage_kernelSpecs (21.95s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker	79.618s
```

**Review by jar-b — APPROVED** [review]
LGTM 🚀

**Comment by ewbankkit** [comment]
@psantus Thanks for the contribution :tada: :clap:.
