### PR TITLE
fix(opensearchserverless): security_policy policy attribute doesn't normalize json strings

### LINKED ISSUE #38603: [Bug]: aws_opensearchserverless_security_policy.policy fails to normalize json strings
### Terraform Core Version

1.9.2

### AWS Provider Version

5.48.0

### Affected Resource(s)

aws_opensearchserverless_security_policy

### Expected Behavior

If I provide a string value to the `policy` argument I expect the order of the keys in the json policy to not matter.

### Actual Behavior

Running apply results in the following error

```console
aws_opensearchserverless_security_policy.example: Creating...
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to aws_opensearchserverless_security_policy.example, provider "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an unexpected new value: .policy: was
│ cty.StringVal("{\"Rules\":[{\"Resource\":[\"collection/member-search*\"],\"ResourceType\":\"collection\"}],\"AWSOwnedKey\":true}"), but now
│ cty.StringVal("{\"AWSOwnedKey\":true,\"Rules\":[{\"Resource\":[\"collection/member-search*\"],\"ResourceType\":\"collection\"}]}").
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### Relevant Error/Panic Output Snippet

_No response_

### Terraform Configuration Files

```terraform
resource "aws_opensearchserverless_security_policy" "example" {
  name   = "encryption-policy-023672f"
  type   = "encryption"
  policy = "{\"Rules\":[{\"Resource\":[\"collection/member-search*\"],\"ResourceType\":\"collection\"}],\"AWSOwnedKey\":true}"
}
```

### Steps to Reproduce

Run `terraform apply` with the above program

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

It looks like the output of the AWS API call results in normalized json which is stored in state. It looks like the `aws_opensearchserverless_access_policy` has a similar setup, but uses the `jsontypes.Normalized` which should handle this use case.

### References

_No response_

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by corymhall**
The `policy` attribute is a string type, but requires the string to be valid json. The user can input json with the keys in any order, but the value stored in state will have the keys in order causing an error message on apply (see linked issue for details).

This resource is very similar to the `access_policy` resource which uses `jsontypes.Normalize` as the type instead of `types.String`. I have copied most of the implementation from `access_policy` and added tests which test using a string value instead of `jsonencode`.

closes #38603

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccOpenSearchServerlessSecurityPolicy PKG=opensearchserverless
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.5 test ./internal/service/opensearchserverless/... -v -count 1 -parallel 20 -run='TestAccOpenSearchServerlessSecurityPolicy'  -timeout 360m
=== RUN   TestAccOpenSearchServerlessSecurityPolicyDataSource_basic
=== PAUSE TestAccOpenSearchServerlessSecurityPolicyDataSource_basic
=== RUN   TestAccOpenSearchServerlessSecurityPolicy_basic
=== PAUSE TestAccOpenSearchServerlessSecurityPolicy_basic
=== RUN   TestAccOpenSearchServerlessSecurityPolicy_string
=== PAUSE TestAccOpenSearchServerlessSecurityPolicy_string
=== RUN   TestAccOpenSearchServerlessSecurityPolicy_update
=== PAUSE TestAccOpenSearchServerlessSecurityPolicy_update
=== RUN   TestAccOpenSearchServerlessSecurityPolicy_string_update
=== PAUSE TestAccOpenSearchServerlessSecurityPolicy_string_update
=== RUN   TestAccOpenSearchServerlessSecurityPolicy_disappears
=== PAUSE TestAccOpenSearchServerlessSecurityPolicy_disappears
=== CONT  TestAccOpenSearchServerlessSecurityPolicyDataSource_basic
=== CONT  TestAccOpenSearchServerlessSecurityPolicy_update
=== CONT  TestAccOpenSearchServerlessSecurityPolicy_disappears
=== CONT  TestAccOpenSearchServerlessSecurityPolicy_basic
=== CONT  TestAccOpenSearchServerlessSecurityPolicy_string_update
=== CONT  TestAccOpenSearchServerlessSecurityPolicy_string
--- PASS: TestAccOpenSearchServerlessSecurityPolicyDataSource_basic (8.78s)
--- PASS: TestAccOpenSearchServerlessSecurityPolicy_disappears (9.07s)
--- PASS: TestAccOpenSearchServerlessSecurityPolicy_basic (10.38s)
--- PASS: TestAccOpenSearchServerlessSecurityPolicy_string (12.68s)
--- PASS: TestAccOpenSearchServerlessSecurityPolicy_string_update (13.52s)
--- PASS: TestAccOpenSearchServerlessSecurityPolicy_update (13.61s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/opensearchserverless       17.472s
```

### CODE REVIEW

File: internal/service/opensearchserverless/security_policy.go [hunk 1]
```diff
@@ -76,13 +76,17 @@ func (r *resourceSecurityPolicy) Schema(ctx context.Context, req resource.Schema
...
+				CustomType: jsontypes.NormalizedType{},
+				Required:   true,
 				Validators: []validator.String{
 					stringvalidator.LengthBetween(1, 20480),
 				},
 			},
 			"policy_version": schema.StringAttribute{
 				Computed: true,
+				PlanModifiers: []planmodifier.String{
+					stringplanmodifier.UseStateForUnknown(),
```
Comment (t0yv0) [inline internal/service/opensearchserverless/security_policy.go:88]: This was useful or needed?

Comment (corymhall) [reply internal/service/opensearchserverless/security_policy.go:88]: It was needed. Without it the update test failed with `missing required field, UpdateSecurityPolicyInput.PolicyVersion.`

**Review by jar-b — APPROVED** [review]
LGTM 🎉 

```console
% make testacc PKG=opensearchserverless TESTS="TestAccOpenSearchServerlessSecurityPolicy_"
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.5 test ./internal/service/opensearchserverless/... -v -count 1 -parallel 20 -run='TestAccOpenSearchServerlessSecurityPolicy_'  -timeout 360m

--- PASS: TestAccOpenSearchServerlessSecurityPolicy_disappears (12.95s)
--- PASS: TestAccOpenSearchServerlessSecurityPolicy_basic (14.98s)
--- PASS: TestAccOpenSearchServerlessSecurityPolicy_string (18.38s)
--- PASS: TestAccOpenSearchServerlessSecurityPolicy_update (19.96s)
--- PASS: TestAccOpenSearchServerlessSecurityPolicy_stringUpdate (21.87s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/opensearchserverless       27.933s
```

**Comment by jar-b** [comment]
Thanks for your contribution, @corymhall! 👍
