### PR TITLE
[BUG] `aws_batch_job_definition`: add extra nil checks

### LINKED ISSUE #38684: panic: interface conversion: interface {} is nil, not map[string]interface {}           batch.needsJobDefUpdate
### Terraform Core Version

1.8.0

### AWS Provider Version

5.60.0, 5.61.0

### Affected Resource(s)

* aws_batch_job_definition

### Expected Behavior

Plan should succeed

### Actual Behavior

```console
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 761 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/batch.needsJobDefUpdate(0xc003e70800)
```

### Relevant Error/Panic Output Snippet

```console
Stack trace from the terraform-provider-aws_v5.61.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 761 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/batch.needsJobDefUpdate(0xc003e70800)
github.com/hashicorp/terraform-provider-aws/internal/service/batch/job_definition.go:569 +0x1074
github.com/hashicorp/terraform-provider-aws/internal/service/batch.jobDefinitionCustomizeDiff({0x13f75fa0?, 0x208b4340?}, 0xc003e70800, {0xe?, 0xc002598340?})
github.com/hashicorp/terraform-provider-aws/internal/service/batch/job_definition.go:464 +0x3a
github.com/hashicorp/terraform-provider-aws/internal/service/batch.ResourceJobDefinition.Sequence.func23({0x170b2cc8, 0xc003cdf080}, 0xc003e70800, {0x14e571c0, 0xc002598340})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/customdiff/compose.go:69 +0x84
github.com/hashicorp/terraform-provider-aws/internal/provider.New.(*wrappedResource).CustomizeDiff.func5({0x170b2cc8?, 0xc0023c5dd0?}, 0xc003e70800, {0x14e571c0, 0xc002598340})
github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:186 +0x63
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0xc000beb380, {0x170b2cc8, 0xc0023c5dd0}, 0xc001a2f1e0, 0xc0001b51d0, 0xc001078b88, {0x14e571c0, 0xc002598340}, 0x0)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/schema.go:698 +0x4b4
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0x170b30f8?, {0x170b2cc8?, 0xc0023c5dd0?}, 0xc001a2f1e0, 0xc0023c5e00?, {0x14e571c0?, 0xc002598340?})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:990 +0xdb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).PlanResourceChange(0xc003697068, {0x170b2cc8?, 0xc0023c5ce0?}, 0xc000deda90)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/grpc_provider.go:858 +0xbe8
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).PlanResourceChange(0xc0014921c0, {0x170b2cc8?, 0xc0023c5a10?}, 0xc000deda90)
github.com/hashicorp/terraform-plugin-mux@v0.16.0/tf5muxserver/mux_server_PlanResourceChange.go:73 +0x2ad
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).PlanResourceChange(0xc001997cc0, {0x170b2cc8?, 0xc0023c51d0?}, 0xc0006d3d80)
github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/tf5server/server.go:825 +0x3f0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_PlanResourceChange_Handler({0x14c3fb20, 0xc001997cc0}, {0x170b2cc8, 0xc0023c51d0}, 0xc0006d3d00, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:500 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000a60200, {0x170b2cc8, 0xc0023c5140}, {0x17116620, 0xc000002000}, 0xc001f7c6c0, 0xc0025afd40, 0x208231e0, 0x0)
google.golang.org/grpc@v1.63.2/server.go:1369 +0xdf8
google.golang.org/grpc.(*Server).handleStream(0xc000a60200, {0x17116620, 0xc000002000}, 0xc001f7c6c0)
google.golang.org/grpc@v1.63.2/server.go:1780 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 41
google.golang.org/grpc@v1.63.2/server.go:1030 +0x125

Error: The terraform-provider-aws_v5.61.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Terraform Configuration Files

...terraform config...

### Steps to Reproduce

Our apply process occurs in a Terraform Enterprise workspace.

terraform apply

### Debug Output

_No response_

### Panic Output

```console
Stack trace from the terraform-provider-aws_v5.61.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 761 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/batch.needsJobDefUpdate(0xc003e70800)
github.com/hashicorp/terraform-provider-aws/internal/service/batch/job_definition.go:569 +0x1074
github.com/hashicorp/terraform-provider-aws/internal/service/batch.jobDefinitionCustomizeDiff({0x13f75fa0?, 0x208b4340?}, 0xc003e70800, {0xe?, 0xc002598340?})
github.com/hashicorp/terraform-provider-aws/internal/service/batch/job_definition.go:464 +0x3a
github.com/hashicorp/terraform-provider-aws/internal/service/batch.ResourceJobDefinition.Sequence.func23({0x170b2cc8, 0xc003cdf080}, 0xc003e70800, {0x14e571c0, 0xc002598340})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/customdiff/compose.go:69 +0x84
github.com/hashicorp/terraform-provider-aws/internal/provider.New.(*wrappedResource).CustomizeDiff.func5({0x170b2cc8?, 0xc0023c5dd0?}, 0xc003e70800, {0x14e571c0, 0xc002598340})
github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:186 +0x63
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0xc000beb380, {0x170b2cc8, 0xc0023c5dd0}, 0xc001a2f1e0, 0xc0001b51d0, 0xc001078b88, {0x14e571c0, 0xc002598340}, 0x0)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/schema.go:698 +0x4b4
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0x170b30f8?, {0x170b2cc8?, 0xc0023c5dd0?}, 0xc001a2f1e0, 0xc0023c5e00?, {0x14e571c0?, 0xc002598340?})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:990 +0xdb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).PlanResourceChange(0xc003697068, {0x170b2cc8?, 0xc0023c5ce0?}, 0xc000deda90)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/grpc_provider.go:858 +0xbe8
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).PlanResourceChange(0xc0014921c0, {0x170b2cc8?, 0xc0023c5a10?}, 0xc000deda90)
github.com/hashicorp/terraform-plugin-mux@v0.16.0/tf5muxserver/mux_server_PlanResourceChange.go:73 +0x2ad
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).PlanResourceChange(0xc001997cc0, {0x170b2cc8?, 0xc0023c51d0?}, 0xc0006d3d80)
github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/tf5server/server.go:825 +0x3f0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_PlanResourceChange_Handler({0x14c3fb20, 0xc001997cc0}, {0x170b2cc8, 0xc0023c51d0}, 0xc0006d3d00, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:500 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000a60200, {0x170b2cc8, 0xc0023c5140}, {0x17116620, 0xc000002000}, 0xc001f7c6c0, 0xc0025afd40, 0x208231e0, 0x0)
google.golang.org/grpc@v1.63.2/server.go:1369 +0xdf8
google.golang.org/grpc.(*Server).handleStream(0xc000a60200, {0x17116620, 0xc000002000}, 0xc001f7c6c0)
google.golang.org/grpc@v1.63.2/server.go:1780 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 41
google.golang.org/grpc@v1.63.2/server.go:1030 +0x125

Error: The terraform-provider-aws_v5.61.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Important Factoids

apply runs successfully if there is no jobdefinition. Fails when there are existing AWS Batch setup.

### References

_No response_

### Would you like to implement a fix?

None

### LINKED ISSUE #38710: [Bug]: AWS Batch 'panic: interface conversion: interface {} is nil, not map[string]interface {}'
### Terraform Core Version

1.9.3

### AWS Provider Version

5.61.0

### Affected Resource(s)

aws_batch_job_definition

### Expected Behavior

I am using the AWS Batch TF module: https://registry.terraform.io/modules/terraform-aws-modules/batch/aws/latest

But I believe the problem is with the underlying `aws_batch_job_definition` resource.

I expect to be able to create the resources with the batch module.

### Actual Behavior

Creating the resources initially with `terraform apply` works just fine. But even if the code remains completely unchanged, when running `terraform apply` again, the provider crashes.

It looks like it's coming from the `/internal/service/batch.needsJobDefUpdate` function.

Not the same issue, but looks similar: [#22660](https://github.com/hashicorp/terraform-provider-aws/issues/22660), [#17284](https://github.com/hashicorp/terraform-provider-aws/issues/17284)

### Relevant Error/Panic Output Snippet

```shell
Stack trace from the terraform-provider-aws_v5.61.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 3020 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/batch.needsJobDefUpdate(0xc00324e000)
        github.com/hashicorp/terraform-provider-aws/internal/service/batch/job_definition.go:569 +0x1074
github.com/hashicorp/terraform-provider-aws/internal/service/batch.jobDefinitionCustomizeDiff({0x13f75fa0?, 0x208b4340?}, 0xc00324e000, {0xe?, 0xc0026548f0?})
        github.com/hashicorp/terraform-provider-aws/internal/service/batch/job_definition.go:464 +0x3a
github.com/hashicorp/terraform-provider-aws/internal/service/batch.ResourceJobDefinition.Sequence.func23({0x170b2cc8, 0xc003980b10}, 0xc00324e000, {0x14e571c0, 0xc0026548f0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/customdiff/compose.go:69 +0x84
github.com/hashicorp/terraform-provider-aws/internal/provider.New.(*wrappedResource).CustomizeDiff.func5({0x170b2cc8?, 0xc00386a7e0?}, 0xc00324e000, {0x14e571c0, 0xc0026548f0})
        github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:186 +0x63
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0xc000f34060, {0x170b2cc8, 0xc00386a7e0}, 0xc003902c30, 0xc004722280, 0xc00022b9f8, {0x14e571c0, 0xc0026548f0}, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/schema.go:698 +0x4b4
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0x170b30f8?, {0x170b2cc8?, 0xc00386a7e0?}, 0xc003902c30, 0xc00386a810?, {0x14e571c0?, 0xc0026548f0?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:990 +0xdb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).PlanResourceChange(0xc00426f068, {0x170b2cc8?, 0xc00386a6f0?}, 0xc003ca5540)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/grpc_provider.go:858 +0xbe8
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).PlanResourceChange(0xc0013f8f50, {0x170b2cc8?, 0xc00386a420?}, 0xc003ca5540)
        github.com/hashicorp/terraform-plugin-mux@v0.16.0/tf5muxserver/mux_server_PlanResourceChange.go:73 +0x2ad
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).PlanResourceChange(0xc000619c20, {0x170b2cc8?, 0xc00384fb60?}, 0xc004562600)
        github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/tf5server/server.go:825 +0x3f0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_PlanResourceChange_Handler({0x14c3fb20, 0xc000619c20}, {0x170b2cc8, 0xc00384fb60}, 0xc004562580, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:500 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc001296000, {0x170b2cc8, 0xc00384fad0}, {0x17116620, 0xc0002ba300}, 0xc00385eb40, 0xc002700120, 0x208231e0, 0x0)
        google.golang.org/grpc@v1.63.2/server.go:1369 +0xdf8
google.golang.org/grpc.(*Server).handleStream(0xc001296000, {0x17116620, 0xc0002ba300}, 0xc00385eb40)
        google.golang.org/grpc@v1.63.2/server.go:1780 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 65
        google.golang.org/grpc@v1.63.2/server.go:1030 +0x125

Error: The terraform-provider-aws_v5.61.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Terraform Configuration Files

```tf
resource "aws_security_group" "this" {
  name   = "aws_batch_compute_environment_security_group"
  vpc_id = var.vpc_id
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

module "batch" {
  source = "terraform-aws-modules/batch/aws"

  create_instance_iam_role      = true
  instance_iam_role_name        = "batch-role"
  instance_iam_role_path        = "/batch/"
  instance_iam_role_description = "IAM instance role/profile for AWS Batch ECS instance(s)"
  instance_iam_role_additional_policies = [
    "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
  ]

  create_service_iam_role      = true
  service_iam_role_name        = "batch-service-role"
  service_iam_role_path        = "/batch/"
  service_iam_role_description = "IAM service role for AWS Batch"

  compute_environments = {
    ec2_gpu = {
      name_prefix = "ec2_gpu"

      compute_resources = {
        type           = "EC2"
        min_vcpus      = 4
        max_vcpus      = 4
        desired_vcpus  = 4
        instance_types = ["g4dn.xlarge"]

        ec2_configuration = {
          image_type = "ECS_AL2_NVIDIA"
        }

        security_group_ids = [aws_security_group.this.id]
        subnets            = var.private_subnets
      }
    }
  }

  job_queues = {
    batch_queue = {
      name                     = "BatchQueue"
      state                    = "ENABLED"
      priority                 = 1
      create_scheduling_policy = false
    }
  }

  job_definitions = {
    nginx = {
      name = "nginx"
      type = "container"

      container_properties = jsonencode({
        image = "nginx"

        resourceRequirements = [
          { type = "VCPU", value = "4" },
          { type = "MEMORY", value = "15000" },
          { type = "GPU", value = "1" }
        ]
      })
    }
  }
}
```

### Steps to Reproduce

```sh
terraform apply
yes

terraform apply
```

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by aristosvo**
### Description
Extra nil check in the `aws_batch_job_definition` resource

### Relations
Closes #38710
Closes #38684 

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccXXX PKG=batch

...
```

### CODE REVIEW

File: internal/service/batch/job_definition.go [hunk 1]
```diff
@@ -516,14 +516,14 @@ func needsJobDefUpdate(d *schema.ResourceDiff) bool {
 		}
 
 		var oeks, neks *batch.EksPodProperties
-		if len(o.([]interface{})) > 0 {
+		if len(o.([]interface{})) > 0 && 0.([]interface{})[0] != nil {
```
Comment (aristosvo) [inline internal/service/batch/job_definition.go:519]: Oopsie
```suggestion
		if len(o.([]interface{})) > 0 && o.([]interface{})[0] != nil {
```

**Review by jar-b — APPROVED** [review]
LGTM 🎉 

```console
% make testacc PKG=batch TESTS=TestAccBatchJobDefinition_
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.5 test ./internal/service/batch/... -v -count 1 -parallel 20 -run='TestAccBatchJobDefinition_'  -timeout 360m

--- PASS: TestAccBatchJobDefinition_createTypeMultiNodeWithContainerProperties (18.67s)
=== CONT  TestAccBatchJobDefinition_EKSProperties_imagePullSecrets
--- PASS: TestAccBatchJobDefinition_createTypeContainerWithNodeProperties (19.39s)
=== CONT  TestAccBatchJobDefinition_EKSProperties_update
--- PASS: TestAccBatchJobDefinition_ContainerProperties_EmptyField (43.63s)
=== CONT  TestAccBatchJobDefinition_EKSProperties_basic
--- PASS: TestAccBatchJobDefinition_schedulingPriority (43.93s)
=== CONT  TestAccBatchJobDefinition_NodeProperties_advanced
=== CONT  TestAccBatchJobDefinition_NodeProperties_basic
--- PASS: TestAccBatchJobDefinition_basic (44.13s)
--- PASS: TestAccBatchJobDefinition_tags_DefaultTags_nullOverlappingResourceTag (51.75s)
=== CONT  TestAccBatchJobDefinition_PlatformCapabilities_fargate
--- PASS: TestAccBatchJobDefinition_tags_DefaultTags_emptyResourceTag (52.26s)
=== CONT  TestAccBatchJobDefinition_propagateTags
--- PASS: TestAccBatchJobDefinition_tags_DefaultTags_emptyProviderOnlyTag (52.29s)
=== CONT  TestAccBatchJobDefinition_ContainerProperties_minorUpdate
--- PASS: TestAccBatchJobDefinition_EKSProperties_imagePullSecrets (34.98s)
=== CONT  TestAccBatchJobDefinition_ContainerProperties_advanced
--- PASS: TestAccBatchJobDefinition_tags_DefaultTags_updateToResourceOnly (73.71s)
=== CONT  TestAccBatchJobDefinition_tags_ComputedTag_OnCreate
--- PASS: TestAccBatchJobDefinition_EKSProperties_update (56.55s)
=== CONT  TestAccBatchJobDefinition_PlatformCapabilities_ec2
--- PASS: TestAccBatchJobDefinition_tags_EmptyTag_OnUpdate_Replace (76.15s)
=== CONT  TestAccBatchJobDefinition_PlatformCapabilitiesFargate_containerPropertiesDefaults
--- PASS: TestAccBatchJobDefinition_tags_DefaultTags_updateToProviderOnly (76.27s)
=== CONT  TestAccBatchJobDefinition_tags_AddOnUpdate
--- PASS: TestAccBatchJobDefinition_tags_ComputedTag_OnUpdate_Add (76.33s)
=== CONT  TestAccBatchJobDefinition_tags_null
=== CONT  TestAccBatchJobDefinition_disappears
--- PASS: TestAccBatchJobDefinition_tags_DefaultTags_nullNonOverlappingResourceTag (76.47s)
--- PASS: TestAccBatchJobDefinition_EKSProperties_basic (37.90s)
=== CONT  TestAccBatchJobDefinition_attributes
--- PASS: TestAccBatchJobDefinition_tags_ComputedTag_OnUpdate_Replace (83.95s)
--- PASS: TestAccBatchJobDefinition_NodeProperties_basic (39.81s)
--- PASS: TestAccBatchJobDefinition_propagateTags (31.85s)
--- PASS: TestAccBatchJobDefinition_PlatformCapabilities_fargate (40.29s)
--- PASS: TestAccBatchJobDefinition_NodeProperties_advanced (59.49s)
--- PASS: TestAccBatchJobDefinition_disappears (28.35s)
--- PASS: TestAccBatchJobDefinition_tags_EmptyTag_OnCreate (106.39s)
--- PASS: TestAccBatchJobDefinition_tags_EmptyTag_OnUpdate_Add (107.55s)
--- PASS: TestAccBatchJobDefinition_PlatformCapabilities_ec2 (33.05s)
--- PASS: TestAccBatchJobDefinition_PlatformCapabilitiesFargate_containerPropertiesDefaults (34.16s)
--- PASS: TestAccBatchJobDefinition_tags_ComputedTag_OnCreate (38.28s)
--- PASS: TestAccBatchJobDefinition_tags_DefaultTags_nonOverlapping (114.21s)
--- PASS: TestAccBatchJobDefinition_tags_DefaultTags_overlapping (114.28s)
--- PASS: TestAccBatchJobDefinition_tags_null (39.22s)
--- PASS: TestAccBatchJobDefinition_tags_AddOnUpdate (45.63s)
--- PASS: TestAccBatchJobDefinition_tags (125.80s)
--- PASS: TestAccBatchJobDefinition_tags_DefaultTags_providerOnly (134.62s)
--- PASS: TestAccBatchJobDefinition_attributes (55.17s)
--- PASS: TestAccBatchJobDefinition_ContainerProperties_minorUpdate (91.26s)
--- PASS: TestAccBatchJobDefinition_ContainerProperties_advanced (95.85s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/batch      155.527s
```

**Comment by jar-b** [comment]
Thanks for your contribution, @aristosvo! 👍
