### PR TITLE
resource/aws_s3_bucket: Retry on GetBucketTagging 404 Errors

### LINKED ISSUE #13008: aws_s3_bucket create fails with NoSuchBucket error listing resource tags
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
$ terraform -v
Terraform v0.12.20
+ provider.aws v2.59.0
```

### Affected Resource(s)

* aws_s3_bucket

### Terraform Configuration Files

```hcl
resource "aws_s3_bucket" "test" {
  bucket        = "test"
  force_destroy = true

  acl = "private"

  server_side_encryption_configuration {
    rule {
      apply_server_side_encryption_by_default {
        sse_algorithm = "AES256"
      }
    }
  }

  tags = {
    Tag1 = "Tag1Value"
    Tag2 = "Tag2Value"
  }
}
```

### Debug Output

Here are some snippets of the debug log around where the error occurs. The problem appears to occur when AWS returns a 404 Not Found error in response to the `GetBucketTagging` call for a new S3 bucket.

The debug log shows that the S3 bucket itself appears to be created properly:

```
2020-04-23T03:17:18.382Z [DEBUG] plugin.terraform-provider-aws_v2.54.0_x4: 2020/04/23 03:17:18 [DEBUG] [aws-sdk-go] DEBUG: Request s3/CreateBucket Details:
2020-04-23T03:17:18.382Z [DEBUG] plugin.terraform-provider-aws_v2.54.0_x4: ---[ REQUEST POST-SIGN ]-----------------------------
2020-04-23T03:17:18.382Z [DEBUG] plugin.terraform-provider-aws_v2.54.0_x4: PUT / HTTP/1.1
2020-04-23T03:17:18.382Z [DEBUG] plugin.terraform-provider-aws_v2.54.0_x4: Host: xxx.s3.us-west-2.amazonaws.com
2020-04-23T03:17:18.382Z [DEBUG] plugin.terraform-provider-aws_v2.54.0_x4: User-Agent: aws-sdk-go/1.29.24 (go1.13.7; linux; amd64) APN/1.0 HashiCorp/1.0 Terraform/0.12.20 (+https://www.terraform.io)
...
2020-04-23T03:17:18.382Z [DEBUG] plugin.terraform-provider-aws_v2.54.0_x4: 
2020-04-23T03:17:18.382Z [DEBUG] plugin.terraform-provider-aws_v2.54.0_x4: <CreateBucketConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><LocationConstraint>us-west-2</LocationConstraint></CreateBucketConfiguration>
...
2020-04-23T03:17:19.210Z [DEBUG] plugin.terraform-provider-aws_v2.54.0_x4: 2020/04/23 03:17:19 [DEBUG] [aws-sdk-go] DEBUG: Response s3/CreateBucket Details:
2020-04-23T03:17:19.210Z [DEBUG] plugin.terraform-provider-aws_v2.54.0_x4: ---[ RESPONSE ]--------------------------------------
2020-04-23T03:17:19.210Z [DEBUG] plugin.terraform-provider-aws_v2.54.0_x4: HTTP/1.1 200 OK
2020-04-23T03:17:19.210Z [DEBUG] plugin.terraform-provider-aws_v2.54.0_x4: Connection: close
2020-04-23T03:17:19.210Z [DEBUG] plugin.terraform-provider-aws_v2.54.0_x4: Content-Length: 0
2020-04-23T03:17:19.210Z [DEBUG] plugin.terraform-provider-aws_v2.54.0_x4: Date: Thu, 23 Apr 2020 03:17:19 GMT
2020-04-23T03:17:19.210Z [DEBUG] plugin.terraform-provider-aws_v2.54.0_x4: Location: http://xxx.s3.amazonaws.com/
2020-04-23T03:17:19.210Z [DEBUG] plugin.terraform-provider-aws_v2.54.0_x4: Server: AmazonS3
...

```

When the error occurs, the subsequent `GetBucketTagging` request/response looks like this:

```
2020-04-23T03:17:19.210Z [DEBUG] plugin.terraform-provider-aws_v2.54.0_x4: 2020/04/23 03:17:19 [DEBUG] [aws-sdk-go] DEBUG: Request s3/GetBucketTagging Details:
2020-04-23T03:17:19.210Z [DEBUG] plugin.terraform-provider-aws_v2.54.0_x4: ---[ REQUEST POST-SIGN ]-----------------------------
2020-04-23T03:17:19.210Z [DEBUG] plugin.terraform-provider-aws_v2.54.0_x4: GET /?tagging= HTTP/1.1
2020-04-23T03:17:19.210Z [DEBUG] plugin.terraform-provider-aws_v2.54.0_x4: Host: xxx.s3.us-west-2.amazonaws.com
2020-04-23T03:17:19.210Z [DEBUG] plugin.terraform-provider-aws_v2.54.0_x4: User-Agent: aws-sdk-go/1.29.24 (go1.13.7; linux; amd64) APN/1.0 HashiCorp/1.0 Terraform/0.12.20 (+https://www.terraform.io)
...
2020-04-23T03:17:19.431Z [DEBUG] plugin.terraform-provider-aws_v2.54.0_x4: 2020/04/23 03:17:19 [DEBUG] [aws-sdk-go] DEBUG: Response s3/GetBucketTagging Details:
2020-04-23T03:17:19.431Z [DEBUG] plugin.terraform-provider-aws_v2.54.0_x4: ---[ RESPONSE ]--------------------------------------
2020-04-23T03:17:19.431Z [DEBUG] plugin.terraform-provider-aws_v2.54.0_x4: HTTP/1.1 404 Not Found
2020-04-23T03:17:19.431Z [DEBUG] plugin.terraform-provider-aws_v2.54.0_x4: Connection: close
2020-04-23T03:17:19.431Z [DEBUG] plugin.terraform-provider-aws_v2.54.0_x4: Transfer-Encoding: chunked
2020-04-23T03:17:19.431Z [DEBUG] plugin.terraform-provider-aws_v2.54.0_x4: Content-Type: application/xml
2020-04-23T03:17:19.431Z [DEBUG] plugin.terraform-provider-aws_v2.54.0_x4: Date: Thu, 23 Apr 2020 03:17:19 GMT
2020-04-23T03:17:19.431Z [DEBUG] plugin.terraform-provider-aws_v2.54.0_x4: Server: AmazonS3
...
2020-04-23T03:17:19.431Z [DEBUG] plugin.terraform-provider-aws_v2.54.0_x4: -----------------------------------------------------
2020-04-23T03:17:19.431Z [DEBUG] plugin.terraform-provider-aws_v2.54.0_x4: 2020/04/23 03:17:19 [DEBUG] [aws-sdk-go] <?xml version="1.0" encoding="UTF-8"?>
2020-04-23T03:17:19.431Z [DEBUG] plugin.terraform-provider-aws_v2.54.0_x4: <Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>xxx</BucketName><RequestId>xxx</RequestId><HostId>xxx</HostId></Error>
2020-04-23T03:17:19.431Z [DEBUG] plugin.terraform-provider-aws_v2.54.0_x4: 2020/04/23 03:17:19 [DEBUG] [aws-sdk-go] DEBUG: Validate Response s3/GetBucketTagging failed, attempt 0/25, error NoSuchBucket: The specified bucket does not exist
2020-04-23T03:17:19.431Z [DEBUG] plugin.terraform-provider-aws_v2.54.0_x4: 	status code: 404, request id: xxx, host id: xxx
2020/04/23 03:17:19 [DEBUG] module.generic_data_pipeline.module.firehose.module.firehose_s3_bucket.aws_s3_bucket.primary[0]: apply errored, but we're indicating that via the Error pointer rather than returning it: error updating S3 Bucket (xxx) tags: error listing resource tags (xxx): NoSuchBucket: The specified bucket does not exist
	status code: 404, request id: xxx, host id: xxx
```

### Expected Behavior

The S3 bucket is created properly and the `terraform apply` should succeed.

### Actual Behavior

Most of the time, the expected behavior occurs. Intermittently, though, the S3 bucket is created successfully in AWS but the `terraform apply` fails when trying to retrieve tags for the bucket:

```
Error: error updating S3 Bucket (xxx) tags: error listing resource tags (xxx): NoSuchBucket: The specified bucket does not exist
	status code: 404, request id: xxx, host id: xxx

  on modules/common/s3/main.tf line 16, in resource "aws_s3_bucket" "test":
  16: resource "aws_s3_bucket" "test" {
```

If a second `terraform apply` is attempted after the error occurs, the `terraform apply` succeeds.

Given that the problem is intermittent and a later apply succeeds, it seems like the error may be due to an eventual consistency issue.

### Steps to Reproduce

1. `terraform apply`

### References

This appears to be the same as the issue referenced in https://github.com/terraform-providers/terraform-provider-aws/pull/12418, but this problem is still reproducible on the latest provider code (v2.59.0), which includes this fix.

### PR DESCRIPTION
**Pull request by camlow325**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #13008

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
* resource/aws_s3_bucket: Retry on GetBucketTagging 404 errors due to eventual consistency ([#13008](https://github.com/terraform-providers/terraform-provider-aws/issues/13008))
```

The AWS S3 service has eventual consistency considerations. If a
GetBucketTagging call is made to obtain tags just after an S3 bucket is
first created, AWS may return an HTTP 404 (NotFound) error with a
NoSuchBucket error code.

A fix was added for this in #12418. It appears that the NoSuchBucket
errors are not retried with this fix, however. This commit adds some
extra logic which ensures that the code from the awserr.Error instance
is evaluated for retry.

Output for acceptance testing:

```
> make testacc TEST=./aws TESTARGS='-run=TestAccAWSS3Bucket_'
...
--- PASS: TestAccAWSS3Bucket_shouldFailNotFound (22.93s)
--- PASS: TestAccAWSS3Bucket_LifecycleRule_Expiration_EmptyConfigurationBlock (38.71s)
--- PASS: TestAccAWSS3Bucket_forceDestroyWithEmptyPrefixes (40.46s)
--- PASS: TestAccAWSS3Bucket_forceDestroy (40.47s)
--- PASS: TestAccAWSS3Bucket_enableDefaultEncryption_whenAES256IsUsed (45.72s)
--- PASS: TestAccAWSS3Bucket_basic (45.79s)
--- PASS: TestAccAWSS3Bucket_forceDestroyWithObjectLockEnabled (47.59s)
--- PASS: TestAccAWSS3Bucket_ReplicationExpectVersioningValidationError (51.85s)
--- PASS: TestAccAWSS3Bucket_LifecycleBasic (95.95s)
--- PASS: TestAccAWSS3Bucket_LifecycleExpireMarkerOnly (69.16s)
--- PASS: TestAccAWSS3Bucket_enableDefaultEncryption_whenTypical (71.63s)
--- PASS: TestAccAWSS3Bucket_objectLock (74.52s)
--- PASS: TestAccAWSS3Bucket_disableDefaultEncryption_whenDefaultEncryptionIsEnabled (75.75s)
--- PASS: TestAccAWSS3Bucket_region (42.47s)
--- PASS: TestAccAWSS3Bucket_ReplicationWithoutPrefix (96.80s)
--- PASS: TestAccAWSS3Bucket_WebsiteRoutingRules (77.87s)
--- PASS: TestAccAWSS3Bucket_Versioning (106.51s)
--- PASS: TestAccAWSS3Bucket_UpdateGrant (110.50s)
--- PASS: TestAccAWSS3Bucket_GrantToAcl (71.89s)
--- PASS: TestAccAWSS3Bucket_AclToGrant (72.06s)
--- PASS: TestAccAWSS3Bucket_generatedName (47.42s)
--- PASS: TestAccAWSS3Bucket_UpdateAcl (74.86s)
--- PASS: TestAccAWSS3Bucket_namePrefix (44.58s)
--- PASS: TestAccAWSS3Bucket_RequestPayer (75.62s)
--- PASS: TestAccAWSS3Bucket_ReplicationWithoutStorageClass (97.00s)
--- PASS: TestAccAWSS3Bucket_Cors_EmptyOrigin (47.36s)
--- PASS: TestAccAWSS3Bucket_WebsiteRedirect (109.43s)
--- PASS: TestAccAWSS3Bucket_Website_Simple (109.41s)
--- PASS: TestAccAWSS3Bucket_ReplicationConfiguration_Rule_Destination_AddAccessControlTranslation (152.76s)
--- PASS: TestAccAWSS3Bucket_acceleration (81.59s)
--- PASS: TestAccAWSS3Bucket_Cors_Delete (36.58s)
--- PASS: TestAccAWSS3Bucket_Bucket_EmptyString (44.94s)
--- PASS: TestAccAWSS3Bucket_Logging (66.26s)
--- PASS: TestAccAWSS3Bucket_Policy (104.79s)
--- PASS: TestAccAWSS3Bucket_ReplicationConfiguration_Rule_Destination_AccessControlTranslation (176.75s)
--- PASS: TestAccAWSS3Bucket_Cors_Update (71.71s)
--- PASS: TestAccAWSS3Bucket_tagsWithNoSystemTags (135.94s)
--- PASS: TestAccAWSS3Bucket_tagsWithSystemTags (168.39s)
--- PASS: TestAccAWSS3Bucket_Replication (270.65s)
--- PASS: TestAccAWSS3Bucket_ReplicationSchemaV2 (273.25s)
```

### CODE REVIEW

File: aws/resource_aws_s3_bucket.go [hunk 1]
```diff
@@ -734,6 +735,12 @@ func resourceAwsS3BucketUpdate(d *schema.ResourceData, meta interface{}) error {
 		// Retry due to S3 eventual consistency
 		_, err := retryOnAwsCode(s3.ErrCodeNoSuchBucket, func() (interface{}, error) {
 			terr := keyvaluetags.S3BucketUpdateTags(s3conn, d.Id(), o, n)
+			// S3BucketUpdateTags may wrap the underlying awserr.Error. Unwrap
+			// it here so that retryOnAwsCode can evaluate it properly.
+			var awsErr awserr.Error
```
Comment (camlow325) [inline aws/resource_aws_s3_bucket.go:740]: It might be better to go with a more general fix to the `retryOnAwsCode` helper. The problem was also fixed for me when I instead changed the lines [here](https://github.com/terraform-providers/terraform-provider-aws/blob/v2.59.0/aws/awserr.go#L43-L44) to:

```golang
var awsErr awserr.Error
if errors.As(err, &awsErr)&& awsErr.Code() == code {
```

I could modify this to use the more general fix but wasn't sure if this might have unintended effects for other resources that use this helper.

**Comment by ewbankkit** [comment]
@camlow325 Thanks for addressing this.
It may make sense to move that `errors.As` check into `retryOnAwsCode` (and use the `isAWSErr` helper) as I can see this having more general application with other wrapped errors - https://github.com/terraform-providers/terraform-provider-aws/issues/12991.

@bflad What do you think?

**Comment by bflad** [comment]
I would suggest hoisting the `errors.As` unwrapping fix into the `retryOnAwsCode()` function itself. 👍

**Comment by bflad** [comment]
Looks like this may also close #12907

**Comment by ewbankkit** [comment]
@camlow325 Changing

https://github.com/terraform-providers/terraform-provider-aws/blob/33b3d2d55d68cbe558ebcb10df7f85e0a35b6a72/aws/awserr.go#L42-L47

to

```go
		if err != nil {
			var awsErr awserr.Error
			if errors.As(err, &awsErr) && awsErr.Code() == code {
				return resource.RetryableError(err)
			}
			return resource.NonRetryableError(err)
```

should do the trick.

**Comment by ewbankkit** [comment]
I think you can also remove `RetryOnAwsCodes` as it doesn't seem to be called anywhere.

**Comment by camlow325** [comment]
Thanks, @bflad and @ewbankkit. I updated the PR to use the `isAWSErr()` function from `retryOnAwsCode()` in order to have `errors.As()` be used to unwrap any nested `awserr.Error` instances from the `error` object. That seems to work well for having retries be done for `GetBucketTagging` 404 errors and the S3 bucket tests still pass with it as well. I also removed the `RetryOnAwsCodes` function that no longer appears to be used anywhere.

**Comment by ewbankkit** [comment]
Closes #12652.
Closes #12907.

**Comment by bpiper** [comment]
Just curious if there's anything stopping this PR from being approved/merged? Since it's been sitting inactive for several months and may fix a couple of very annoying issues.
</shameless-bump>
