### PR TITLE
r/ecr_repository_policy - Read after update + validate `policy` + disappears test

### LINKED ISSUE #545: AWS ECR Policy - need to run terraform apply twice
_This issue was originally opened by @vikas027 as hashicorp/terraform#12108. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version
```sh
~$ terraform -v
Terraform v0.8.7
```

### Affected Resource(s)
- aws_ecr_repository
- aws_ecr_repository_policy

### Terraform Configuration Files
```hcl
resource "aws_iam_role_policy" "ecr_admin_policy" {
    name = "ecr_admin_policy"
    role = "${aws_iam_role.ecr_admin_role.id}"
    policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "ecr:*"
      ],
      "Effect": "Allow",
      "Resource": "*"
    }
  ]
}
EOF
}

resource "aws_iam_role" "ecr_admin_role" {
  name = "${var.iam_role}"
  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "ecs.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
EOF
}

resource "aws_ecr_repository" "images" {
  depends_on = [ "aws_iam_role_policy.ecr_admin_policy", "aws_iam_role.ecr_admin_role" ]
  count = "${length(var.list_of_images)}",
  name  = "${element(var.list_of_images, count.index)}"
}

resource "aws_ecr_repository_policy" "repo_policy" {
  count = "${length(var.list_of_images)}"
  repository = "${element(aws_ecr_repository.images.*.id, count.index)}"
  policy = <<POLICY
{
    "Version": "2008-10-17",
    "Statement": [
        {
            "Sid": "repo_policy",
            "Effect": "Allow",
            "Principal": {
              "AWS": [
                "arn:aws:iam::11111111111111:root",
                "arn:aws:iam::11111111111111:role/ecr_admin"
              ]
            },
            "Action": [
                "ecr:GetDownloadUrlForLayer",
                "ecr:BatchGetImage",
                "ecr:BatchCheckLayerAvailability",
                "ecr:PutImage",
                "ecr:InitiateLayerUpload",
                "ecr:UploadLayerPart",
                "ecr:CompleteLayerUpload",
                "ecr:DescribeRepositories",
                "ecr:GetRepositoryPolicy",
                "ecr:ListImages",
                "ecr:DeleteRepository",
                "ecr:BatchDeleteImage",
                "ecr:SetRepositoryPolicy",
                "ecr:DeleteRepositoryPolicy"
            ]
        }
    ]
}
POLICY
}
```

### Debug Output
[First Run](https://gist.github.com/vikas027/51e48524e855198546ca3b7594a7f0da) `terraform apply` (fails)
[Second Run](https://gist.github.com/vikas027/5f7614c731218eb369804af9a4f7a7df) `terraform apply` (succeeds)

### Expected Behavior
`terraform apply` should not complain about the policy.

### Actual Behavior
`terraform apply` complains about invalid policy on the first run. And then creates ECR policy in the second run.
I have tried to set resource dependencies using `depends_on` in vain, behavior is same without this parameter.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`  (throws an error)
2. `terraform apply` (run okay this time)

### References
Few other similar issues where terraform does not wait for enough time or AWS reports that the resource creation is complete (a false positive)
- GH-2136
- GH-2349
- GH-5862

### LINKED ISSUE #3924: aws_ecr_repository_policy swallows InvalidParameterException
### Terraform Version
```
Terraform v0.11.5
+ provider.aws v1.10.0
```
### Affected Resource(s)
Please list the resources as a list, for example:
- aws_ecr_repository_policy

### Terraform Configuration Files
The following config results in an invalid policy :flushed: 

```hcl
variable "projects" {
  type = "list"

  default = [
    "alpha",
    "beta",
    "gamma",
    "delta",
  ]
}

variable "account_arns" {
  type = "map"
  # <ids> here are actual AWS account ids.
  # the :* portion is invalid and should be :root
  default = {
    test       = "arn:aws:iam::<id1>:*"
    staging    = "arn:aws:iam::<id2>:*"
    production = "arn:aws:iam::<id3>:*"
  }
}
data aws_iam_policy_document "ecr_policy" {
  statement {
    sid = "ECROrgReadAccess"

    actions = [
      "ecr:BatchCheckLayerAvailability",
      "ecr:GetDownloadUrlForLayer",
      "ecr:GetRepositoryPolicy",
      "ecr:DescribeRepositories",
      "ecr:ListImages",
      "ecr:DescribeImages",
      "ecr:BatchGetImage"
    ]

    principals {
      identifiers = ["${values(var.account_arns)}"]
      type        = "AWS"
    }
  }
}

resource aws_ecr_repository_policy "ecr_policy" {
  count = "${length(var.projects)}"
  repository = "${element(var.projects, count.index)}"
  policy = "${data.aws_iam_policy_document.ecr_policy.json}"
}

```

### Debug Output
```
* aws_ecr_repository_policy.ecr_policy.0: InvalidParameterException: Invalid parameter at 'PolicyText' failed to satisfy constraint: 'Invalid repository policy provided'
```
If needed I can pull the full log - can't include the full debug log at the moment.

### Expected Behavior
Terraform should error with the exception message.

### Actual Behavior
Terraform continually "retries" waiting for the resource to be created.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Nothing special.

### References
None.

### PR DESCRIPTION
**Pull request by DrFaust92**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #13826
Closes #3924
Closes #545

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource_ecr_repository_policy: add plan time validation for `policy`
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSEcrRepositoryPolicy_'
--- PASS: TestAccAWSEcrRepositoryPolicy_basic (63.26s)
--- PASS: TestAccAWSEcrRepositoryPolicy_iam (54.24s)
--- PASS: TestAccAWSEcrRepositoryPolicy_disappears (33.63s)
--- PASS: TestAccAWSEcrRepositoryPolicy_disappears_repository (28.06s)
```

### CODE REVIEW

File: aws/resource_aws_ecr_repository_policy.go [hunk 1]
```diff
@@ -90,52 +88,41 @@ func resourceAwsEcrRepositoryPolicyRead(d *schema.ResourceData, meta interface{}
...
-			switch ecrerr.Code() {
-			case "RepositoryNotFoundException", "RepositoryPolicyNotFoundException":
-				d.SetId("")
-				return nil
-			default:
-				return err
-			}
+		if isAWSErr(err, ecr.ErrCodeRepositoryNotFoundException, "") ||
+			isAWSErr(err, ecr.ErrCodeRepositoryPolicyNotFoundException, "") {
+			log.Printf("[WARN] ECR Repositoy Policy %s not found, removing", d.Id())
```
Comment (chlunde) [inline aws/resource_aws_ecr_repository_policy.go:93]:
```suggestion
			log.Printf("[WARN] ECR Repository Policy %s not found, removing", d.Id())
```

File: aws/resource_aws_ecr_repository_policy.go [hunk 2]
```diff
@@ -49,15 +50,15 @@ func resourceAwsEcrRepositoryPolicyCreate(d *schema.ResourceData, meta interface
 		PolicyText:     aws.String(d.Get("policy").(string)),
 	}
 
-	log.Printf("[DEBUG] Creating ECR resository policy: %s", input)
+	log.Printf("[DEBUG] Creating ECR resository policy: %#v", input)
```
Comment (chlunde) [inline aws/resource_aws_ecr_repository_policy.go:53]:
```suggestion
	log.Printf("[DEBUG] Creating ECR repository policy: %#v", input)
```

File: aws/resource_aws_ecr_repository_policy.go [hunk 3]
```diff
@@ -90,52 +88,41 @@ func resourceAwsEcrRepositoryPolicyRead(d *schema.ResourceData, meta interface{}
...
-
 	input := ecr.SetRepositoryPolicyInput{
-		RepositoryName: aws.String(d.Get("repository").(string)),
+		RepositoryName: aws.String(d.Id()),
 		RegistryId:     aws.String(d.Get("registry_id").(string)),
 		PolicyText:     aws.String(d.Get("policy").(string)),
 	}
 
-	log.Printf("[DEBUG] Updating ECR resository policy: %s", input)
+	log.Printf("[DEBUG] Updating ECR resository policy: %#v", input)
```
Comment (chlunde) [inline aws/resource_aws_ecr_repository_policy.go:118]:
```suggestion
	log.Printf("[DEBUG] Updating ECR repository policy: %#v", input)
```

**Comment by DrFaust92** [comment]
rebased

```
--- PASS: TestAccAWSEcrRepositoryPolicy_disappears_repository (33.65s)
--- PASS: TestAccAWSEcrRepositoryPolicy_disappears (40.01s)
--- PASS: TestAccAWSEcrRepositoryPolicy_iam (52.15s)
--- PASS: TestAccAWSEcrRepositoryPolicy_basic (76.40s)
```

**Review by gdavison — APPROVED** [review]
LGTM 🚀 

--- PASS: TestAccAWSEcrRepositoryPolicy_disappears_repository (12.88s)
--- PASS: TestAccAWSEcrRepositoryPolicy_disappears (14.31s)
--- PASS: TestAccAWSEcrRepositoryPolicy_basic (25.93s)
--- PASS: TestAccAWSEcrRepositoryPolicy_iam (33.38s)
