### PR TITLE
r/aws_ec2_managed_prefix_list: Fix crash with multiple description-only changes

### LINKED ISSUE #19421: resource/aws_ec2_managed_prefix_list: The plugin encountered an error, and failed to respond to the
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

$ terraform -v
Terraform v0.15.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.40.0

### Affected Resource(s)

* aws_ec2_managed_prefix_list

### Terraform Configuration Files

None.

### Debug Output

None.

### Panic Output

https://gist.github.com/tcharewicz/309944f89409bcff10cbeada57db0331

### Expected Behavior

Terraform should modify resouce, add or delete description.

```hcl
  # aws_ec2_managed_prefix_list.this will be updated in-place
  ~ resource "aws_ec2_managed_prefix_list" "this" {
        id             = "pl-0f8022f4f29018d7a"
        name           = "this"
        tags           = {
            "ResourceOwner" = "test"
        }
      ~ version        = 1 -> (known after apply)
        # (5 unchanged attributes hidden)

      + entry {
          + cidr = "1.1.1.0/24"
        }
      - entry {
          - cidr        = "1.1.1.0/24" -> null
          - description = "this" -> null
        }
      + entry {
          + cidr = "1.1.2.0/24"
        }
      - entry {
          - cidr        = "1.1.2.0/24" -> null
          - description = "this" -> null
        }
      + entry {
          + cidr = "1.1.3.0/24"
        }
      - entry {
          - cidr        = "1.1.3.0/24" -> null
          - description = "this" -> null
        }
      + entry {
          + cidr = "1.1.4.0/24"
        }
      - entry {
          - cidr        = "1.1.4.0/24" -> null
          - description = "this" -> null
        }
      + entry {
          + cidr = "1.1.5.0/24"
        }
      - entry {
          - cidr        = "1.1.5.0/24" -> null
          - description = "this" -> null
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Actual Behavior

Terraform crashed.

### Steps to Reproduce

1. Create manged prefix list, with 5 entries. All entries has descriptions.

```hcl
provider "aws" {
  region = "eu-central-1"
}

resource "aws_ec2_managed_prefix_list" "this" {
  name           = "this"
  address_family = "IPv4"
  max_entries    = 5

  entry {
    cidr = "1.1.1.0/24"
    description = "this"
  }

  entry {
    cidr = "1.1.2.0/24"
    description = "this"
  }

  entry {
    cidr = "1.1.3.0/24"
    description = "this"
  }

  entry {
    cidr = "1.1.4.0/24"
    description = "this"
  }

  entry {
    cidr = "1.1.5.0/24"
    description = "this"
  }

  tags = {
      "ResourceOwner"      = "test"
  }
}
```

2. Applay configuration

```
terraform init
terraform apply
```

3. Comment descriptions at entries level.

```hcl
provider "aws" {
  region = "eu-central-1"
}

resource "aws_ec2_managed_prefix_list" "this" {
  name           = "this"
  address_family = "IPv4"
  max_entries    = 5

  entry {
    cidr = "1.1.1.0/24"
    # description = "this"
  }

  entry {
    cidr = "1.1.2.0/24"
    # description = "this"
  }

  entry {
    cidr = "1.1.3.0/24"
    # description = "this"
  }

  entry {
    cidr = "1.1.4.0/24"
    # description = "this"
  }

  entry {
    cidr = "1.1.5.0/24"
    # description = "this"
  }

  tags = {
      "ResourceOwner"      = "test"
  }
}
```

4. Apply

```
terraform apply
```

### Important Factoids

None.

### References

Three weeks ago there were a PR, that changed Behavior of that resource.

https://github.com/hashicorp/terraform-provider-aws/pull/19095

The same behavior you can observe at TF version 0.12.31 and 0.14.11. I do not make a test with TF 0.13.

### PR DESCRIPTION
**Pull request by ewbankkit**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #19421.

Output from acceptance testing:

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAwsEc2ManagedPrefixList_'                 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsEc2ManagedPrefixList_ -timeout 180m
=== RUN   TestAccAwsEc2ManagedPrefixList_basic
=== PAUSE TestAccAwsEc2ManagedPrefixList_basic
=== RUN   TestAccAwsEc2ManagedPrefixList_disappears
=== PAUSE TestAccAwsEc2ManagedPrefixList_disappears
=== RUN   TestAccAwsEc2ManagedPrefixList_AddressFamily_IPv6
=== PAUSE TestAccAwsEc2ManagedPrefixList_AddressFamily_IPv6
=== RUN   TestAccAwsEc2ManagedPrefixList_Entry_Cidr
=== PAUSE TestAccAwsEc2ManagedPrefixList_Entry_Cidr
=== RUN   TestAccAwsEc2ManagedPrefixList_Entry_Description
=== PAUSE TestAccAwsEc2ManagedPrefixList_Entry_Description
=== RUN   TestAccAwsEc2ManagedPrefixList_Name
=== PAUSE TestAccAwsEc2ManagedPrefixList_Name
=== RUN   TestAccAwsEc2ManagedPrefixList_Tags
=== PAUSE TestAccAwsEc2ManagedPrefixList_Tags
=== CONT  TestAccAwsEc2ManagedPrefixList_basic
=== CONT  TestAccAwsEc2ManagedPrefixList_Entry_Description
=== CONT  TestAccAwsEc2ManagedPrefixList_Tags
=== CONT  TestAccAwsEc2ManagedPrefixList_AddressFamily_IPv6
=== CONT  TestAccAwsEc2ManagedPrefixList_Entry_Cidr
=== CONT  TestAccAwsEc2ManagedPrefixList_disappears
=== CONT  TestAccAwsEc2ManagedPrefixList_Name
--- PASS: TestAccAwsEc2ManagedPrefixList_disappears (21.89s)
--- PASS: TestAccAwsEc2ManagedPrefixList_AddressFamily_IPv6 (26.80s)
--- PASS: TestAccAwsEc2ManagedPrefixList_basic (28.43s)
--- PASS: TestAccAwsEc2ManagedPrefixList_Entry_Description (39.82s)
--- PASS: TestAccAwsEc2ManagedPrefixList_Name (40.13s)
--- PASS: TestAccAwsEc2ManagedPrefixList_Entry_Cidr (43.77s)
--- PASS: TestAccAwsEc2ManagedPrefixList_Tags (47.19s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	50.693s
```

### CODE REVIEW

File: aws/resource_aws_ec2_managed_prefix_list.go [hunk 1]
```diff
@@ -242,22 +242,32 @@ func resourceAwsEc2ManagedPrefixListUpdate(d *schema.ResourceData, meta interfac
 		// one with a collection of all description-only removals and the
 		// second one will add them all back.
 		if len(input.AddEntries) > 0 && len(input.RemoveEntries) > 0 {
-			removalInput := &ec2.ModifyManagedPrefixListInput{
-				CurrentVersion: input.CurrentVersion,
-				PrefixListId:   aws.String(d.Id()),
-			}
+			descriptionOnlyRemovals := []*ec2.RemovePrefixListEntry{}
```
Comment (ewbankkit) [inline aws/resource_aws_ec2_managed_prefix_list.go:245]: Name variables for their purpose.

**Review by YakDriver — APPROVED** [review]
Looks great! 🎉 

Output of acceptance tests (`us-west-2`):
```
--- PASS: TestAccAwsEc2ManagedPrefixList_disappears (20.90s)
--- PASS: TestAccAwsEc2ManagedPrefixList_AddressFamily_IPv6 (25.55s)
--- PASS: TestAccAwsEc2ManagedPrefixList_basic (25.73s)
--- PASS: TestAccAwsEc2ManagedPrefixList_Name (35.63s)
--- PASS: TestAccAwsEc2ManagedPrefixList_Entry_Description (38.48s)
--- PASS: TestAccAwsEc2ManagedPrefixList_Entry_Cidr (39.09s)
--- PASS: TestAccAwsEc2ManagedPrefixList_Tags (45.19s)
```

GovCloud:
```
--- SKIP: TestAccAwsEc2ManagedPrefixList_AddressFamily_IPv6 (1.57s)
--- SKIP: TestAccAwsEc2ManagedPrefixList_basic (1.59s)
--- SKIP: TestAccAwsEc2ManagedPrefixList_disappears (1.59s)
--- SKIP: TestAccAwsEc2ManagedPrefixList_Entry_Cidr (1.59s)
--- SKIP: TestAccAwsEc2ManagedPrefixList_Entry_Description (1.58s)
--- SKIP: TestAccAwsEc2ManagedPrefixList_Name (1.58s)
--- SKIP: TestAccAwsEc2ManagedPrefixList_Tags (1.59s)
```
