### PR TITLE
Fix region name validation to be compatible with AWS European Sovereign Cloud regions

### LINKED ISSUE #45894: Region validation in multiple resources fails for eusc-de-east-1 because of the regex pattern being used
### Terraform and AWS Provider Version

```console
Terraform v1.14.0
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v6.28.0
```

### Affected Resource(s) or Data Source(s)

resource/aws_lambda_permission, resource/aws_datazone_environment_profile, resource/aws_emrserverless_application and resource/aws_cloudwatch_event

### Expected Behavior

Resources should be correctly created on eusc-de-east-1

### Actual Behavior

Fails with:
Error: invalid value for function_name (must be valid function name or function ARN)

Destroy fails with the same error and resources have to be destroyed manually

### Relevant Error/Panic Output

```console
Error: invalid value for function_name (must be valid function name or function ARN)
```

### Sample Terraform Configuration

<details open>
<summary>Click to expand configuration</summary>

```hcl

```
</details>

### Steps to Reproduce

Try to create a lambda function triggered by an SNS message using resource/aws_lambda_permission object in eusc-de-east-1

### Debug Logging

<details open>
<summary>Click to expand log output</summary>

```console

```
</details>

### GenAI / LLM Assisted Development

n/a

### Important Facts and References

After investigating the issue found that the regex validation of regions in resource/aws_lambda_permission requires regions to start with "[a-z]{2}-", which does not match the region eusc-de-east-1. Found similar behavior in several other places

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by mateuszsoltys99-spec**
## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the library.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

### Description
New eusc-de-east-1 region was unusable because of regex patterns matching region names requiring regions to start with "[a-z]{2}-". Changed to allow 2-4 letter parts there.

### Relations

Closes #45894

### CODE REVIEW

**Comment by mateuszsoltys99-spec** [comment]
Following should be added to changelog:
* resource/aws_lambda_permission, resource/aws_datazone_environment_profile, resource/aws_emrserverless_application and resource/aws_cloudwatch_event: prevent failing on eusc-de-east-1 due to region validation requiring region names to start with "[a-z]{2}-" ([#45894](https://github.com/hashicorp/terraform-provider-aws/issues/45894))

**Comment by YakDriver** [comment]
Lambda permission tests:

```console
% make t T=TestAccLambdaPermission_ K=lambda P=10                       
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 b-fix-region-name-validation-for-eusc-de-east-1 🌿...
TF_ACC=1 go1.25.5 test ./internal/service/lambda/... -v -count 1 -parallel 10 -run='TestAccLambdaPermission_'  -timeout 360m -vet=off
2026/01/12 17:23:13 Creating Terraform AWS Provider (SDKv2-style)...
2026/01/12 17:23:13 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccLambdaPermission_Identity_Basic
=== PAUSE TestAccLambdaPermission_Identity_Basic
=== RUN   TestAccLambdaPermission_Identity_RegionOverride
=== PAUSE TestAccLambdaPermission_Identity_RegionOverride
=== RUN   TestAccLambdaPermission_Identity_ExistingResource
=== PAUSE TestAccLambdaPermission_Identity_ExistingResource
=== RUN   TestAccLambdaPermission_Identity_ExistingResource_NoRefresh_NoChange
=== PAUSE TestAccLambdaPermission_Identity_ExistingResource_NoRefresh_NoChange
=== RUN   TestAccLambdaPermission_basic
=== PAUSE TestAccLambdaPermission_basic
=== RUN   TestAccLambdaPermission_principalOrgID
=== PAUSE TestAccLambdaPermission_principalOrgID
=== RUN   TestAccLambdaPermission_statementIDDuplicate
=== PAUSE TestAccLambdaPermission_statementIDDuplicate
=== RUN   TestAccLambdaPermission_rawFunctionName
=== PAUSE TestAccLambdaPermission_rawFunctionName
=== RUN   TestAccLambdaPermission_statementIDPrefix
=== PAUSE TestAccLambdaPermission_statementIDPrefix
=== RUN   TestAccLambdaPermission_qualifier
=== PAUSE TestAccLambdaPermission_qualifier
=== RUN   TestAccLambdaPermission_disappears
=== PAUSE TestAccLambdaPermission_disappears
=== RUN   TestAccLambdaPermission_multiplePerms
=== PAUSE TestAccLambdaPermission_multiplePerms
=== RUN   TestAccLambdaPermission_s3
=== PAUSE TestAccLambdaPermission_s3
=== RUN   TestAccLambdaPermission_sns
=== PAUSE TestAccLambdaPermission_sns
=== RUN   TestAccLambdaPermission_iamRole
=== PAUSE TestAccLambdaPermission_iamRole
=== RUN   TestAccLambdaPermission_FunctionURLs_iam
=== PAUSE TestAccLambdaPermission_FunctionURLs_iam
=== RUN   TestAccLambdaPermission_FunctionURLs_none
=== PAUSE TestAccLambdaPermission_FunctionURLs_none
=== RUN   TestAccLambdaPermission_FunctionURLs_invokedViaFunctionURL
=== PAUSE TestAccLambdaPermission_FunctionURLs_invokedViaFunctionURL
=== CONT  TestAccLambdaPermission_Identity_Basic
=== CONT  TestAccLambdaPermission_qualifier
=== CONT  TestAccLambdaPermission_statementIDPrefix
=== CONT  TestAccLambdaPermission_iamRole
=== CONT  TestAccLambdaPermission_Identity_ExistingResource_NoRefresh_NoChange
=== CONT  TestAccLambdaPermission_s3
=== CONT  TestAccLambdaPermission_basic
=== CONT  TestAccLambdaPermission_FunctionURLs_none
=== CONT  TestAccLambdaPermission_principalOrgID
=== CONT  TestAccLambdaPermission_FunctionURLs_invokedViaFunctionURL
--- PASS: TestAccLambdaPermission_qualifier (41.85s)
=== CONT  TestAccLambdaPermission_FunctionURLs_iam
--- PASS: TestAccLambdaPermission_statementIDPrefix (47.21s)
=== CONT  TestAccLambdaPermission_Identity_ExistingResource
--- PASS: TestAccLambdaPermission_FunctionURLs_none (60.84s)
=== CONT  TestAccLambdaPermission_multiplePerms
--- PASS: TestAccLambdaPermission_Identity_Basic (63.28s)
=== CONT  TestAccLambdaPermission_Identity_RegionOverride
--- PASS: TestAccLambdaPermission_Identity_ExistingResource_NoRefresh_NoChange (66.87s)
=== CONT  TestAccLambdaPermission_sns
--- PASS: TestAccLambdaPermission_s3 (69.04s)
=== CONT  TestAccLambdaPermission_rawFunctionName
--- PASS: TestAccLambdaPermission_FunctionURLs_invokedViaFunctionURL (74.71s)
=== CONT  TestAccLambdaPermission_disappears
--- PASS: TestAccLambdaPermission_iamRole (80.89s)
=== CONT  TestAccLambdaPermission_statementIDDuplicate
--- PASS: TestAccLambdaPermission_basic (86.01s)
--- PASS: TestAccLambdaPermission_principalOrgID (93.25s)
--- PASS: TestAccLambdaPermission_FunctionURLs_iam (57.01s)
--- PASS: TestAccLambdaPermission_Identity_ExistingResource (67.12s)
--- PASS: TestAccLambdaPermission_Identity_RegionOverride (54.74s)
--- PASS: TestAccLambdaPermission_sns (52.07s)
--- PASS: TestAccLambdaPermission_multiplePerms (59.05s)
--- PASS: TestAccLambdaPermission_rawFunctionName (55.37s)
--- PASS: TestAccLambdaPermission_disappears (53.66s)
--- PASS: TestAccLambdaPermission_statementIDDuplicate (358.60s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/lambda	445.878s
```

**Comment by YakDriver** [comment]
Datazone tests:

```console
% make t T=TestAccDataZoneEnvironmentProfile_ K=datazone     
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 b-fix-region-name-validation-for-eusc-de-east-1 🌿...
TF_ACC=1 go1.25.5 test ./internal/service/datazone/... -v -count 1 -parallel 20 -run='TestAccDataZoneEnvironmentProfile_'  -timeout 360m -vet=off
2026/01/12 17:36:05 Creating Terraform AWS Provider (SDKv2-style)...
2026/01/12 17:36:05 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccDataZoneEnvironmentProfile_basic
=== PAUSE TestAccDataZoneEnvironmentProfile_basic
=== RUN   TestAccDataZoneEnvironmentProfile_disappears
=== PAUSE TestAccDataZoneEnvironmentProfile_disappears
=== RUN   TestAccDataZoneEnvironmentProfile_update
=== PAUSE TestAccDataZoneEnvironmentProfile_update
=== CONT  TestAccDataZoneEnvironmentProfile_basic
=== CONT  TestAccDataZoneEnvironmentProfile_update
=== CONT  TestAccDataZoneEnvironmentProfile_disappears
--- PASS: TestAccDataZoneEnvironmentProfile_disappears (39.10s)
--- PASS: TestAccDataZoneEnvironmentProfile_basic (42.00s)
--- PASS: TestAccDataZoneEnvironmentProfile_update (56.31s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/datazone	63.016s
```

**Comment by YakDriver** [comment]
EventBridge rule tests:

```console
% make t T=TestAccEventsRule_ P=10 K=events
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 b-fix-region-name-validation-for-eusc-de-east-1 🌿...
TF_ACC=1 go1.25.5 test ./internal/service/events/... -v -count 1 -parallel 10 -run='TestAccEventsRule_'  -timeout 360m -vet=off
2026/01/12 17:39:17 Creating Terraform AWS Provider (SDKv2-style)...
2026/01/12 17:39:17 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccEventsRule_Identity_Basic
=== PAUSE TestAccEventsRule_Identity_Basic
=== RUN   TestAccEventsRule_Identity_RegionOverride
=== PAUSE TestAccEventsRule_Identity_RegionOverride
=== RUN   TestAccEventsRule_Identity_ExistingResource
=== PAUSE TestAccEventsRule_Identity_ExistingResource
=== RUN   TestAccEventsRule_Identity_ExistingResource_NoRefresh_NoChange
=== PAUSE TestAccEventsRule_Identity_ExistingResource_NoRefresh_NoChange
=== RUN   TestAccEventsRule_basic
=== PAUSE TestAccEventsRule_basic
=== RUN   TestAccEventsRule_eventBusName
=== PAUSE TestAccEventsRule_eventBusName
=== RUN   TestAccEventsRule_role
=== PAUSE TestAccEventsRule_role
=== RUN   TestAccEventsRule_description
=== PAUSE TestAccEventsRule_description
=== RUN   TestAccEventsRule_pattern
=== PAUSE TestAccEventsRule_pattern
=== RUN   TestAccEventsRule_patternJSONEncoder
=== PAUSE TestAccEventsRule_patternJSONEncoder
=== RUN   TestAccEventsRule_scheduleAndPattern
=== PAUSE TestAccEventsRule_scheduleAndPattern
=== RUN   TestAccEventsRule_namePrefix
=== PAUSE TestAccEventsRule_namePrefix
=== RUN   TestAccEventsRule_Name_generated
=== PAUSE TestAccEventsRule_Name_generated
=== RUN   TestAccEventsRule_tags
=== PAUSE TestAccEventsRule_tags
=== RUN   TestAccEventsRule_isEnabled
=== PAUSE TestAccEventsRule_isEnabled
=== RUN   TestAccEventsRule_state
=== PAUSE TestAccEventsRule_state
=== RUN   TestAccEventsRule_partnerEventBus
    rule_test.go:707: Environment variable EVENT_BRIDGE_PARTNER_EVENT_BUS_NAME is not set
--- SKIP: TestAccEventsRule_partnerEventBus (0.00s)
=== RUN   TestAccEventsRule_eventBusARN
=== PAUSE TestAccEventsRule_eventBusARN
=== RUN   TestAccEventsRule_migrateV0
=== PAUSE TestAccEventsRule_migrateV0
=== RUN   TestAccEventsRule_migrateV0_Equivalent
=== PAUSE TestAccEventsRule_migrateV0_Equivalent
=== CONT  TestAccEventsRule_Identity_Basic
=== CONT  TestAccEventsRule_scheduleAndPattern
=== CONT  TestAccEventsRule_eventBusName
=== CONT  TestAccEventsRule_pattern
=== CONT  TestAccEventsRule_description
=== CONT  TestAccEventsRule_role
=== CONT  TestAccEventsRule_tags
=== CONT  TestAccEventsRule_patternJSONEncoder
=== CONT  TestAccEventsRule_state
=== CONT  TestAccEventsRule_Identity_ExistingResource_NoRefresh_NoChange
--- PASS: TestAccEventsRule_patternJSONEncoder (15.97s)
=== CONT  TestAccEventsRule_migrateV0_Equivalent
=== RUN   TestAccEventsRule_migrateV0_Equivalent/enabled
=== PAUSE TestAccEventsRule_migrateV0_Equivalent/enabled
=== RUN   TestAccEventsRule_migrateV0_Equivalent/disabled
=== PAUSE TestAccEventsRule_migrateV0_Equivalent/disabled
=== CONT  TestAccEventsRule_migrateV0
=== RUN   TestAccEventsRule_migrateV0/basic
=== PAUSE TestAccEventsRule_migrateV0/basic
=== RUN   TestAccEventsRule_migrateV0/enabled
=== PAUSE TestAccEventsRule_migrateV0/enabled
=== RUN   TestAccEventsRule_migrateV0/disabled
=== PAUSE TestAccEventsRule_migrateV0/disabled
=== CONT  TestAccEventsRule_eventBusARN
--- PASS: TestAccEventsRule_scheduleAndPattern (21.05s)
=== CONT  TestAccEventsRule_Identity_ExistingResource
--- PASS: TestAccEventsRule_Identity_Basic (30.49s)
=== CONT  TestAccEventsRule_isEnabled
--- PASS: TestAccEventsRule_role (31.54s)
=== CONT  TestAccEventsRule_basic
--- PASS: TestAccEventsRule_pattern (32.07s)
=== CONT  TestAccEventsRule_Name_generated
--- PASS: TestAccEventsRule_description (32.83s)
=== CONT  TestAccEventsRule_Identity_RegionOverride
--- PASS: TestAccEventsRule_eventBusARN (18.34s)
=== CONT  TestAccEventsRule_namePrefix
--- PASS: TestAccEventsRule_state (36.26s)
=== CONT  TestAccEventsRule_migrateV0_Equivalent/enabled
--- PASS: TestAccEventsRule_tags (42.78s)
=== CONT  TestAccEventsRule_migrateV0_Equivalent/disabled
--- PASS: TestAccEventsRule_eventBusName (47.52s)
=== CONT  TestAccEventsRule_migrateV0/basic
--- PASS: TestAccEventsRule_Identity_ExistingResource_NoRefresh_NoChange (48.06s)
=== CONT  TestAccEventsRule_migrateV0/disabled
--- PASS: TestAccEventsRule_Name_generated (19.63s)
=== CONT  TestAccEventsRule_migrateV0/enabled
--- PASS: TestAccEventsRule_namePrefix (18.78s)
--- PASS: TestAccEventsRule_Identity_RegionOverride (26.14s)
--- PASS: TestAccEventsRule_Identity_ExistingResource (50.88s)
--- PASS: TestAccEventsRule_basic (43.68s)
--- PASS: TestAccEventsRule_isEnabled (46.77s)
--- PASS: TestAccEventsRule_migrateV0_Equivalent (0.00s)
    --- PASS: TestAccEventsRule_migrateV0_Equivalent/enabled (38.29s)
    --- PASS: TestAccEventsRule_migrateV0_Equivalent/disabled (36.15s)
--- PASS: TestAccEventsRule_migrateV0 (0.00s)
    --- PASS: TestAccEventsRule_migrateV0/basic (36.57s)
    --- PASS: TestAccEventsRule_migrateV0/disabled (37.29s)
    --- PASS: TestAccEventsRule_migrateV0/enabled (39.53s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/events	97.869s
```

**Comment by YakDriver** [comment]
EMR Serverless application tests:

```console
% make t T=TestAccEMRServerlessApplication_ K=emrserverless P=10
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 b-fix-region-name-validation-for-eusc-de-east-1 🌿...
TF_ACC=1 go1.25.5 test ./internal/service/emrserverless/... -v -count 1 -parallel 10 -run='TestAccEMRServerlessApplication_'  -timeout 360m -vet=off
2026/01/12 17:37:54 Creating Terraform AWS Provider (SDKv2-style)...
2026/01/12 17:37:54 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccEMRServerlessApplication_basic
=== PAUSE TestAccEMRServerlessApplication_basic
=== RUN   TestAccEMRServerlessApplication_arch
=== PAUSE TestAccEMRServerlessApplication_arch
=== RUN   TestAccEMRServerlessApplication_releaseLabel
=== PAUSE TestAccEMRServerlessApplication_releaseLabel
=== RUN   TestAccEMRServerlessApplication_initialCapacity
=== PAUSE TestAccEMRServerlessApplication_initialCapacity
=== RUN   TestAccEMRServerlessApplication_imageConfiguration
=== PAUSE TestAccEMRServerlessApplication_imageConfiguration
=== RUN   TestAccEMRServerlessApplication_interactiveConfiguration
=== PAUSE TestAccEMRServerlessApplication_interactiveConfiguration
=== RUN   TestAccEMRServerlessApplication_maxCapacity
=== PAUSE TestAccEMRServerlessApplication_maxCapacity
=== RUN   TestAccEMRServerlessApplication_network
=== PAUSE TestAccEMRServerlessApplication_network
=== RUN   TestAccEMRServerlessApplication_disappears
=== PAUSE TestAccEMRServerlessApplication_disappears
=== RUN   TestAccEMRServerlessApplication_tags
=== PAUSE TestAccEMRServerlessApplication_tags
=== RUN   TestAccEMRServerlessApplication_runtimeConfiguration
=== PAUSE TestAccEMRServerlessApplication_runtimeConfiguration
=== RUN   TestAccEMRServerlessApplication_schedulerConfiguration
=== PAUSE TestAccEMRServerlessApplication_schedulerConfiguration
=== RUN   TestAccEMRServerlessApplication_monitoringConfiguration
=== PAUSE TestAccEMRServerlessApplication_monitoringConfiguration
=== CONT  TestAccEMRServerlessApplication_basic
=== CONT  TestAccEMRServerlessApplication_network
=== CONT  TestAccEMRServerlessApplication_runtimeConfiguration
=== CONT  TestAccEMRServerlessApplication_imageConfiguration
=== CONT  TestAccEMRServerlessApplication_maxCapacity
=== CONT  TestAccEMRServerlessApplication_arch
=== CONT  TestAccEMRServerlessApplication_monitoringConfiguration
=== CONT  TestAccEMRServerlessApplication_releaseLabel
=== CONT  TestAccEMRServerlessApplication_tags
=== CONT  TestAccEMRServerlessApplication_initialCapacity
--- PASS: TestAccEMRServerlessApplication_basic (79.71s)
=== CONT  TestAccEMRServerlessApplication_interactiveConfiguration
--- PASS: TestAccEMRServerlessApplication_arch (89.58s)
=== CONT  TestAccEMRServerlessApplication_schedulerConfiguration
--- PASS: TestAccEMRServerlessApplication_maxCapacity (90.05s)
=== CONT  TestAccEMRServerlessApplication_disappears
--- PASS: TestAccEMRServerlessApplication_runtimeConfiguration (90.07s)
--- PASS: TestAccEMRServerlessApplication_initialCapacity (90.52s)
--- PASS: TestAccEMRServerlessApplication_releaseLabel (90.53s)
--- PASS: TestAccEMRServerlessApplication_network (92.56s)
--- PASS: TestAccEMRServerlessApplication_tags (98.88s)
--- PASS: TestAccEMRServerlessApplication_monitoringConfiguration (100.51s)
--- PASS: TestAccEMRServerlessApplication_interactiveConfiguration (107.79s)
--- PASS: TestAccEMRServerlessApplication_disappears (133.94s)
--- PASS: TestAccEMRServerlessApplication_schedulerConfiguration (140.49s)
--- PASS: TestAccEMRServerlessApplication_imageConfiguration (531.56s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/emrserverless	538.002s
```

**Comment by YakDriver** [comment]
Pipes pipe test:

(Failure unrelated to these changes)
```console
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/emrserverless	538.002s

% make t T=TestAccPipesPipe_ K=pipes P=10        
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 b-fix-region-name-validation-for-eusc-de-east-1 🌿...
TF_ACC=1 go1.25.5 test ./internal/service/pipes/... -v -count 1 -parallel 10 -run='TestAccPipesPipe_'  -timeout 360m -vet=off
2026/01/12 17:45:56 Creating Terraform AWS Provider (SDKv2-style)...
2026/01/12 17:45:56 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccPipesPipe_basicSQS
=== PAUSE TestAccPipesPipe_basicSQS
=== RUN   TestAccPipesPipe_disappears
=== PAUSE TestAccPipesPipe_disappears
=== RUN   TestAccPipesPipe_description
=== PAUSE TestAccPipesPipe_description
=== RUN   TestAccPipesPipe_desiredState
=== PAUSE TestAccPipesPipe_desiredState
=== RUN   TestAccPipesPipe_enrichment
=== PAUSE TestAccPipesPipe_enrichment
=== RUN   TestAccPipesPipe_enrichmentParameters
=== PAUSE TestAccPipesPipe_enrichmentParameters
=== RUN   TestAccPipesPipe_kmsKeyIdentifier
=== PAUSE TestAccPipesPipe_kmsKeyIdentifier
=== RUN   TestAccPipesPipe_logConfiguration_cloudwatchLogsLogDestination
=== PAUSE TestAccPipesPipe_logConfiguration_cloudwatchLogsLogDestination
=== RUN   TestAccPipesPipe_update_logConfiguration_cloudwatchLogsLogDestination
=== PAUSE TestAccPipesPipe_update_logConfiguration_cloudwatchLogsLogDestination
=== RUN   TestAccPipesPipe_logConfiguration_includeExecutionData
=== PAUSE TestAccPipesPipe_logConfiguration_includeExecutionData
=== RUN   TestAccPipesPipe_sourceParameters_filterCriteria
=== PAUSE TestAccPipesPipe_sourceParameters_filterCriteria
=== RUN   TestAccPipesPipe_nameGenerated
=== PAUSE TestAccPipesPipe_nameGenerated
=== RUN   TestAccPipesPipe_namePrefix
=== PAUSE TestAccPipesPipe_namePrefix
=== RUN   TestAccPipesPipe_roleARN
=== PAUSE TestAccPipesPipe_roleARN
=== RUN   TestAccPipesPipe_tags
=== PAUSE TestAccPipesPipe_tags
=== RUN   TestAccPipesPipe_targetUpdate
=== PAUSE TestAccPipesPipe_targetUpdate
=== RUN   TestAccPipesPipe_targetParameters_inputTemplate
=== PAUSE TestAccPipesPipe_targetParameters_inputTemplate
=== RUN   TestAccPipesPipe_targetParameters_inputTemplate_preserveUnchanged
=== PAUSE TestAccPipesPipe_targetParameters_inputTemplate_preserveUnchanged
=== RUN   TestAccPipesPipe_kinesisSourceAndTarget
=== PAUSE TestAccPipesPipe_kinesisSourceAndTarget
=== RUN   TestAccPipesPipe_dynamoDBSourceCloudWatchLogsTarget
=== PAUSE TestAccPipesPipe_dynamoDBSourceCloudWatchLogsTarget
=== RUN   TestAccPipesPipe_activeMQSourceStepFunctionTarget
=== PAUSE TestAccPipesPipe_activeMQSourceStepFunctionTarget
=== RUN   TestAccPipesPipe_rabbitMQSourceEventBusTarget
=== PAUSE TestAccPipesPipe_rabbitMQSourceEventBusTarget
=== RUN   TestAccPipesPipe_mskSourceHTTPTarget
    pipe_test.go:1278: DependencyViolation errors deleting subnets and security group
--- SKIP: TestAccPipesPipe_mskSourceHTTPTarget (0.00s)
=== RUN   TestAccPipesPipe_selfManagedKafkaSourceLambdaFunctionTarget
    pipe_test.go:1354: DependencyViolation errors deleting subnets and security group
--- SKIP: TestAccPipesPipe_selfManagedKafkaSourceLambdaFunctionTarget (0.00s)
=== RUN   TestAccPipesPipe_sqsSourceRedshiftTarget
=== PAUSE TestAccPipesPipe_sqsSourceRedshiftTarget
=== RUN   TestAccPipesPipe_SourceSageMakerTarget
    pipe_test.go:1501: aws_sagemaker_pipeline resource not yet implemented
--- SKIP: TestAccPipesPipe_SourceSageMakerTarget (0.00s)
=== RUN   TestAccPipesPipe_sqsSourceBatchJobTarget
=== PAUSE TestAccPipesPipe_sqsSourceBatchJobTarget
=== RUN   TestAccPipesPipe_sqsSourceECSTaskTarget
    pipe_test.go:1652: ValidationException: [numeric instance is lower than the required minimum (minimum: 1, found: 0)]
--- SKIP: TestAccPipesPipe_sqsSourceECSTaskTarget (0.00s)
=== CONT  TestAccPipesPipe_basicSQS
=== CONT  TestAccPipesPipe_namePrefix
=== CONT  TestAccPipesPipe_desiredState
=== CONT  TestAccPipesPipe_kmsKeyIdentifier
=== CONT  TestAccPipesPipe_logConfiguration_includeExecutionData
=== CONT  TestAccPipesPipe_enrichment
=== CONT  TestAccPipesPipe_description
=== CONT  TestAccPipesPipe_enrichmentParameters
=== CONT  TestAccPipesPipe_nameGenerated
=== CONT  TestAccPipesPipe_sourceParameters_filterCriteria
--- PASS: TestAccPipesPipe_nameGenerated (76.37s)
=== CONT  TestAccPipesPipe_targetUpdate
--- PASS: TestAccPipesPipe_namePrefix (80.05s)
=== CONT  TestAccPipesPipe_targetParameters_inputTemplate_preserveUnchanged
--- PASS: TestAccPipesPipe_basicSQS (80.77s)
=== CONT  TestAccPipesPipe_targetParameters_inputTemplate
--- PASS: TestAccPipesPipe_enrichmentParameters (123.77s)
=== CONT  TestAccPipesPipe_tags
--- PASS: TestAccPipesPipe_logConfiguration_includeExecutionData (149.05s)
=== CONT  TestAccPipesPipe_update_logConfiguration_cloudwatchLogsLogDestination
--- PASS: TestAccPipesPipe_enrichment (150.26s)
=== CONT  TestAccPipesPipe_roleARN
--- PASS: TestAccPipesPipe_kmsKeyIdentifier (153.18s)
=== CONT  TestAccPipesPipe_logConfiguration_cloudwatchLogsLogDestination
--- PASS: TestAccPipesPipe_desiredState (153.56s)
=== NAME  TestAccPipesPipe_rabbitMQSourceEventBusTarget
    pipe_test.go:1227: Step 1/2 error: After applying this test step, the refresh plan was not empty.
        stdout
        
        
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        
        Terraform will perform the following actions:
        
          # aws_mq_broker.source will be updated in-place
          ~ resource "aws_mq_broker" "source" {
                id                            = "b-715291a5-1be1-4694-8b8c-d798dbc35c33"
                tags                          = {}
                # (18 unchanged attributes hidden)
        
                # (4 unchanged blocks hidden)
            }
        
        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccPipesPipe_rabbitMQSourceEventBusTarget (697.04s)
=== CONT  TestAccPipesPipe_disappears
--- PASS: TestAccPipesPipe_description (183.31s)
=== CONT  TestAccPipesPipe_kinesisSourceAndTarget
--- PASS: TestAccPipesPipe_sourceParameters_filterCriteria (210.06s)
=== CONT  TestAccPipesPipe_dynamoDBSourceCloudWatchLogsTarget
--- PASS: TestAccPipesPipe_targetUpdate (136.29s)
=== CONT  TestAccPipesPipe_activeMQSourceStepFunctionTarget
--- PASS: TestAccPipesPipe_targetParameters_inputTemplate (147.33s)
=== CONT  TestAccPipesPipe_sqsSourceBatchJobTarget
--- PASS: TestAccPipesPipe_logConfiguration_cloudwatchLogsLogDestination (77.95s)
=== CONT  TestAccPipesPipe_sqsSourceRedshiftTarget
--- PASS: TestAccPipesPipe_disappears (74.70s)
--- PASS: TestAccPipesPipe_tags (115.79s)
--- PASS: TestAccPipesPipe_activeMQSourceStepFunctionTarget (1096.24s)
--- PASS: TestAccPipesPipe_update_logConfiguration_cloudwatchLogsLogDestination (109.22s)
--- PASS: TestAccPipesPipe_kinesisSourceAndTarget (77.46s)
--- PASS: TestAccPipesPipe_dynamoDBSourceCloudWatchLogsTarget (52.40s)
--- PASS: TestAccPipesPipe_roleARN (139.99s)
--- PASS: TestAccPipesPipe_targetParameters_inputTemplate_preserveUnchanged (212.43s)
--- PASS: TestAccPipesPipe_sqsSourceBatchJobTarget (166.18s)
--- PASS: TestAccPipesPipe_sqsSourceRedshiftTarget (309.44s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/pipes	1102.366s
```

**Comment by YakDriver** [comment]
Lambda Event source mapping tests (failure unrelated to these changes):

```console
% make t T=TestAccLambdaEventSourceMapping_ K=lambda P=10   
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 b-fix-region-name-validation-for-eusc-de-east-1 🌿...
TF_ACC=1 go1.25.5 test ./internal/service/lambda/... -v -count 1 -parallel 10 -run='TestAccLambdaEventSourceMapping_'  -timeout 360m -vet=off
2026/01/12 17:42:45 Creating Terraform AWS Provider (SDKv2-style)...
2026/01/12 17:42:45 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccLambdaEventSourceMapping_Kinesis_basic
=== PAUSE TestAccLambdaEventSourceMapping_Kinesis_basic
=== RUN   TestAccLambdaEventSourceMapping_KMSKeyARN
=== PAUSE TestAccLambdaEventSourceMapping_KMSKeyARN
=== RUN   TestAccLambdaEventSourceMapping_tags
=== PAUSE TestAccLambdaEventSourceMapping_tags
=== RUN   TestAccLambdaEventSourceMapping_SQS_basic
=== PAUSE TestAccLambdaEventSourceMapping_SQS_basic
=== RUN   TestAccLambdaEventSourceMapping_DynamoDB_basic
=== PAUSE TestAccLambdaEventSourceMapping_DynamoDB_basic
=== RUN   TestAccLambdaEventSourceMapping_DynamoDB_functionResponseTypes
=== PAUSE TestAccLambdaEventSourceMapping_DynamoDB_functionResponseTypes
=== RUN   TestAccLambdaEventSourceMapping_DynamoDB_streamAdded
=== PAUSE TestAccLambdaEventSourceMapping_DynamoDB_streamAdded
=== RUN   TestAccLambdaEventSourceMapping_SQS_batchWindow
=== PAUSE TestAccLambdaEventSourceMapping_SQS_batchWindow
=== RUN   TestAccLambdaEventSourceMapping_disappears
=== PAUSE TestAccLambdaEventSourceMapping_disappears
=== RUN   TestAccLambdaEventSourceMapping_SQS_changesInEnabledAreDetected
=== PAUSE TestAccLambdaEventSourceMapping_SQS_changesInEnabledAreDetected
=== RUN   TestAccLambdaEventSourceMapping_Kinesis_startingPositionTimestamp
=== PAUSE TestAccLambdaEventSourceMapping_Kinesis_startingPositionTimestamp
=== RUN   TestAccLambdaEventSourceMapping_Kinesis_batchWindow
=== PAUSE TestAccLambdaEventSourceMapping_Kinesis_batchWindow
=== RUN   TestAccLambdaEventSourceMapping_Kinesis_parallelizationFactor
=== PAUSE TestAccLambdaEventSourceMapping_Kinesis_parallelizationFactor
=== RUN   TestAccLambdaEventSourceMapping_Kinesis_tumblingWindowInSeconds
=== PAUSE TestAccLambdaEventSourceMapping_Kinesis_tumblingWindowInSeconds
=== RUN   TestAccLambdaEventSourceMapping_Kinesis_maximumRetryAttempts
=== PAUSE TestAccLambdaEventSourceMapping_Kinesis_maximumRetryAttempts
=== RUN   TestAccLambdaEventSourceMapping_Kinesis_maximumRetryAttemptsZero
=== PAUSE TestAccLambdaEventSourceMapping_Kinesis_maximumRetryAttemptsZero
=== RUN   TestAccLambdaEventSourceMapping_Kinesis_maximumRetryAttemptsNegativeOne
=== PAUSE TestAccLambdaEventSourceMapping_Kinesis_maximumRetryAttemptsNegativeOne
=== RUN   TestAccLambdaEventSourceMapping_Kinesis_maximumRecordAgeInSeconds
=== PAUSE TestAccLambdaEventSourceMapping_Kinesis_maximumRecordAgeInSeconds
=== RUN   TestAccLambdaEventSourceMapping_Kinesis_maximumRecordAgeInSecondsNegativeOne
=== PAUSE TestAccLambdaEventSourceMapping_Kinesis_maximumRecordAgeInSecondsNegativeOne
=== RUN   TestAccLambdaEventSourceMapping_Kinesis_bisectBatch
=== PAUSE TestAccLambdaEventSourceMapping_Kinesis_bisectBatch
=== RUN   TestAccLambdaEventSourceMapping_Kinesis_destination
=== PAUSE TestAccLambdaEventSourceMapping_Kinesis_destination
=== RUN   TestAccLambdaEventSourceMapping_msk
=== PAUSE TestAccLambdaEventSourceMapping_msk
=== RUN   TestAccLambdaEventSourceMapping_mskWithEventSourceConfig
=== PAUSE TestAccLambdaEventSourceMapping_mskWithEventSourceConfig
=== RUN   TestAccLambdaEventSourceMapping_mskWithEventSourceConfigSchemaRegistry
=== PAUSE TestAccLambdaEventSourceMapping_mskWithEventSourceConfigSchemaRegistry
=== RUN   TestAccLambdaEventSourceMapping_mskWithOnFailureDestination
=== PAUSE TestAccLambdaEventSourceMapping_mskWithOnFailureDestination
=== RUN   TestAccLambdaEventSourceMapping_selfManagedKafka
=== PAUSE TestAccLambdaEventSourceMapping_selfManagedKafka
=== RUN   TestAccLambdaEventSourceMapping_selfManagedKafkaWithEventSourceConfig
=== PAUSE TestAccLambdaEventSourceMapping_selfManagedKafkaWithEventSourceConfig
=== RUN   TestAccLambdaEventSourceMapping_selfManagedKafkaWithEventSourceConfigSchemaRegistry
=== PAUSE TestAccLambdaEventSourceMapping_selfManagedKafkaWithEventSourceConfigSchemaRegistry
=== RUN   TestAccLambdaEventSourceMapping_selfManagedKafkaWithProvisionedPollerConfig
=== PAUSE TestAccLambdaEventSourceMapping_selfManagedKafkaWithProvisionedPollerConfig
=== RUN   TestAccLambdaEventSourceMapping_selfManagedKafkaWithOnFailureDestination
=== PAUSE TestAccLambdaEventSourceMapping_selfManagedKafkaWithOnFailureDestination
=== RUN   TestAccLambdaEventSourceMapping_activeMQ
=== PAUSE TestAccLambdaEventSourceMapping_activeMQ
=== RUN   TestAccLambdaEventSourceMapping_rabbitMQ
=== PAUSE TestAccLambdaEventSourceMapping_rabbitMQ
=== RUN   TestAccLambdaEventSourceMapping_SQS_filterCriteria
=== PAUSE TestAccLambdaEventSourceMapping_SQS_filterCriteria
=== RUN   TestAccLambdaEventSourceMapping_SQS_scalingConfig
=== PAUSE TestAccLambdaEventSourceMapping_SQS_scalingConfig
=== RUN   TestAccLambdaEventSourceMapping_documentDB
=== PAUSE TestAccLambdaEventSourceMapping_documentDB
=== RUN   TestAccLambdaEventSourceMapping_SQS_metricsConfig
=== PAUSE TestAccLambdaEventSourceMapping_SQS_metricsConfig
=== CONT  TestAccLambdaEventSourceMapping_Kinesis_basic
=== CONT  TestAccLambdaEventSourceMapping_Kinesis_maximumRecordAgeInSecondsNegativeOne
=== CONT  TestAccLambdaEventSourceMapping_selfManagedKafkaWithEventSourceConfigSchemaRegistry
=== CONT  TestAccLambdaEventSourceMapping_SQS_metricsConfig
=== CONT  TestAccLambdaEventSourceMapping_rabbitMQ
=== CONT  TestAccLambdaEventSourceMapping_selfManagedKafkaWithEventSourceConfig
=== CONT  TestAccLambdaEventSourceMapping_SQS_changesInEnabledAreDetected
=== CONT  TestAccLambdaEventSourceMapping_selfManagedKafka
=== CONT  TestAccLambdaEventSourceMapping_documentDB
=== CONT  TestAccLambdaEventSourceMapping_selfManagedKafkaWithOnFailureDestination
--- PASS: TestAccLambdaEventSourceMapping_SQS_changesInEnabledAreDetected (67.45s)
=== CONT  TestAccLambdaEventSourceMapping_mskWithOnFailureDestination
--- PASS: TestAccLambdaEventSourceMapping_selfManagedKafkaWithEventSourceConfig (68.32s)
=== CONT  TestAccLambdaEventSourceMapping_mskWithEventSourceConfigSchemaRegistry
--- PASS: TestAccLambdaEventSourceMapping_selfManagedKafkaWithEventSourceConfigSchemaRegistry (75.43s)
=== CONT  TestAccLambdaEventSourceMapping_mskWithEventSourceConfig
--- PASS: TestAccLambdaEventSourceMapping_Kinesis_maximumRecordAgeInSecondsNegativeOne (77.02s)
=== CONT  TestAccLambdaEventSourceMapping_msk
--- PASS: TestAccLambdaEventSourceMapping_selfManagedKafkaWithOnFailureDestination (90.75s)
=== CONT  TestAccLambdaEventSourceMapping_Kinesis_destination
--- PASS: TestAccLambdaEventSourceMapping_SQS_metricsConfig (107.16s)
=== CONT  TestAccLambdaEventSourceMapping_Kinesis_bisectBatch
--- PASS: TestAccLambdaEventSourceMapping_selfManagedKafka (112.03s)
=== CONT  TestAccLambdaEventSourceMapping_SQS_scalingConfig
--- PASS: TestAccLambdaEventSourceMapping_Kinesis_basic (134.99s)
=== CONT  TestAccLambdaEventSourceMapping_SQS_filterCriteria
--- PASS: TestAccLambdaEventSourceMapping_Kinesis_destination (66.91s)
=== CONT  TestAccLambdaEventSourceMapping_Kinesis_maximumRetryAttempts
--- PASS: TestAccLambdaEventSourceMapping_Kinesis_bisectBatch (61.82s)
=== CONT  TestAccLambdaEventSourceMapping_Kinesis_maximumRecordAgeInSeconds
--- PASS: TestAccLambdaEventSourceMapping_Kinesis_maximumRetryAttempts (62.72s)
=== CONT  TestAccLambdaEventSourceMapping_Kinesis_maximumRetryAttemptsNegativeOne
--- PASS: TestAccLambdaEventSourceMapping_Kinesis_maximumRecordAgeInSeconds (61.76s)
=== CONT  TestAccLambdaEventSourceMapping_Kinesis_maximumRetryAttemptsZero
--- PASS: TestAccLambdaEventSourceMapping_SQS_scalingConfig (142.58s)
=== CONT  TestAccLambdaEventSourceMapping_Kinesis_parallelizationFactor
--- PASS: TestAccLambdaEventSourceMapping_SQS_filterCriteria (147.24s)
=== CONT  TestAccLambdaEventSourceMapping_Kinesis_tumblingWindowInSeconds
--- PASS: TestAccLambdaEventSourceMapping_Kinesis_maximumRetryAttemptsNegativeOne (74.63s)
=== CONT  TestAccLambdaEventSourceMapping_activeMQ
--- PASS: TestAccLambdaEventSourceMapping_Kinesis_maximumRetryAttemptsZero (74.79s)
=== CONT  TestAccLambdaEventSourceMapping_Kinesis_batchWindow
--- PASS: TestAccLambdaEventSourceMapping_Kinesis_parallelizationFactor (62.40s)
=== CONT  TestAccLambdaEventSourceMapping_selfManagedKafkaWithProvisionedPollerConfig
--- PASS: TestAccLambdaEventSourceMapping_Kinesis_tumblingWindowInSeconds (62.07s)
=== CONT  TestAccLambdaEventSourceMapping_Kinesis_startingPositionTimestamp
--- PASS: TestAccLambdaEventSourceMapping_Kinesis_batchWindow (61.52s)
=== CONT  TestAccLambdaEventSourceMapping_DynamoDB_functionResponseTypes
--- PASS: TestAccLambdaEventSourceMapping_selfManagedKafkaWithProvisionedPollerConfig (66.60s)
=== CONT  TestAccLambdaEventSourceMapping_disappears
--- PASS: TestAccLambdaEventSourceMapping_Kinesis_startingPositionTimestamp (50.32s)
=== CONT  TestAccLambdaEventSourceMapping_SQS_batchWindow
--- PASS: TestAccLambdaEventSourceMapping_DynamoDB_functionResponseTypes (51.26s)
=== CONT  TestAccLambdaEventSourceMapping_DynamoDB_streamAdded
--- PASS: TestAccLambdaEventSourceMapping_SQS_batchWindow (59.28s)
=== CONT  TestAccLambdaEventSourceMapping_SQS_basic
--- PASS: TestAccLambdaEventSourceMapping_disappears (73.26s)
=== CONT  TestAccLambdaEventSourceMapping_DynamoDB_basic
--- PASS: TestAccLambdaEventSourceMapping_DynamoDB_streamAdded (86.40s)
=== CONT  TestAccLambdaEventSourceMapping_tags
--- PASS: TestAccLambdaEventSourceMapping_DynamoDB_basic (52.90s)
=== CONT  TestAccLambdaEventSourceMapping_KMSKeyARN
--- PASS: TestAccLambdaEventSourceMapping_SQS_basic (111.35s)
--- PASS: TestAccLambdaEventSourceMapping_tags (74.26s)
--- PASS: TestAccLambdaEventSourceMapping_KMSKeyARN (75.89s)
=== NAME  TestAccLambdaEventSourceMapping_rabbitMQ
    event_source_mapping_test.go:1505: Step 1/2 error: After applying this test step, the refresh plan was not empty.
        stdout
        
        
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        
        Terraform will perform the following actions:
        
          # aws_mq_broker.test will be updated in-place
          ~ resource "aws_mq_broker" "test" {
                id                            = "b-e7aaf45b-ad19-4111-8e18-fd387909a9b6"
                tags                          = {}
                # (18 unchanged attributes hidden)
        
                # (4 unchanged blocks hidden)
            }
        
        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccLambdaEventSourceMapping_rabbitMQ (645.40s)
--- PASS: TestAccLambdaEventSourceMapping_activeMQ (1065.04s)
--- PASS: TestAccLambdaEventSourceMapping_mskWithOnFailureDestination (1615.34s)
--- PASS: TestAccLambdaEventSourceMapping_documentDB (1711.23s)
--- PASS: TestAccLambdaEventSourceMapping_mskWithEventSourceConfigSchemaRegistry (1765.83s)
--- PASS: TestAccLambdaEventSourceMapping_msk (2948.20s)
--- PASS: TestAccLambdaEventSourceMapping_mskWithEventSourceConfig (2954.81s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/lambda	3036.969s
```

File: internal/types/aws_region.go [hunk 1]
```diff
@@ -7,7 +7,16 @@ import (
 	"github.com/YakDriver/regexache"
 )
 
+// CanonicalRegionPattern is the canonical regex pattern for validating AWS region names.
+// It supports standard regions (us-east-1), government regions (us-gov-west-1),
+// and sovereign cloud regions (eusc-de-east-1).
+const CanonicalRegionPattern = `^[a-z]{2,4}(-[a-z]+)+-\d{1,2}$`
```
Comment (ewbankkit) [inline internal/types/aws_region.go]: You cold change this to a `var` and use`CanonicalRegionPatternNoAnchors` defined below.

**Review by YakDriver — APPROVED** [review]
LGTM 🎉
