### PR TITLE
aws_load_balancer_listener_policy: add triggers argument

### LINKED ISSUE #13628: ELB SSL cert update resets SSL ciphers causing silent configuration drift
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform & AWS Provider Version

Terraform v0.11.14
provider.aws v2.39.0

### Affected Resource(s)

* aws_lb_ssl_negotiation_policy
* aws_elb

## Initial Configuration
```hcl
resource "aws_acm_certificate" "example-cert-foo" {
    domain_name       = "foo.example.com"
    validation_method = "DNS"
}

resource "aws_acm_certificate" "example-cert-bar" {
    domain_name       = "bar.example.com"
    validation_method = "DNS"
}

resource "aws_elb" "lb" {
  name               = "test-lb"
  availability_zones = ["us-east-1a"]

  listener {
    instance_port      = 8000
    instance_protocol  = "https"
    lb_port            = 443
    lb_protocol        = "https"
    ssl_certificate_id = "${aws_acm_certificate.example-cert-foo.arn}"
  }
}

resource "aws_lb_ssl_negotiation_policy" "baz" {
  name          = "baz-policy"
  load_balancer = "${aws_elb.lb.id}"
  lb_port       = 443

  attribute {
    name  = "Protocol-TLSv1"
    value = "false"
  }

  attribute {
    name  = "Protocol-TLSv1.1"
    value = "false"
  }

  attribute {
    name  = "Protocol-TLSv1.2"
    value = "true"
  }

  attribute {
    name  = "Server-Defined-Cipher-Order"
    value = "true"
  }

  attribute {
    name  = "ECDHE-RSA-AES128-GCM-SHA256"
    value = "true"
  }

  attribute {
    name  = "AES128-GCM-SHA256"
    value = "true"
  }

  attribute {
    name  = "EDH-RSA-DES-CBC3-SHA"
    value = "false"
  }
}
```

## Change: `diff`

```
- ssl_certificate_id = "${aws_acm_certificate.example-cert-foo.arn}"
+ ssl_certificate_id = "${aws_acm_certificate.example-cert-bar.arn}"
```

## Final Configuration

Only the ELB configuration changes:

```hcl
[...]

resource "aws_elb" "lb" {
  name               = "test-lb"
  availability_zones = ["us-east-1a"]

  listener {
    instance_port      = 8000
    instance_protocol  = "https"
    lb_port            = 443
    lb_protocol        = "https"
    ssl_certificate_id = "${aws_acm_certificate.example-cert-bar.arn}"  # Changed
  }
}

[...]
```

### Expected Behavior

After applying the new SSL certificate to the ELB, the custom ciphers policies should persist as declared.

### Actual Behavior

After applying the new SSL certificate to the ELB, the custom ciphers are reset to AWS default cipher policies, clearing out the previous custom ciphers. They do not persist as declared, and Terraform does not recognize a change in custom cipher policy state upon subsequent `terraform plan`s.

### Steps to Reproduce

1. Execute `terraform apply`  (see **Initial Configuration**)
1. Observe that the declared custom SSL cipher policies are correctly associated with the ELB.
1. Modify the ELB by attaching a new SSL certificate (see **Change: `diff`** -> **Final Configuration**)
1. Execute `terraform apply`
1. Observe through the AWS console that the prior custom SSL cipher policies are no longer associated with the ELB, in disagreement with `terraform.tfstate`, drifted from the declared state.
1. Execute `terraform plan`
1. Observe that Terraform _does not_ recognize any difference in state, despite a clear configuration drift.

### Important Factoids

- An alternate way to enumerate the ciphers on the ELB without using the console is to utilize a popular network analysis tool called `nmap`, executing the following command:
  `nmap --script ssl-enum-ciphers -p 443 <foo.example.com>`

I believe the explanation for this issue is quite straightforward; I am more than happy to clarify/assist where able.

* #0000

### PR DESCRIPTION
**Pull request by johnsonaj**
### Relations

Closes #13628

### Output from Acceptance Testing

```console
$ make testacc PKG=elb TESTS="TestAccELBSSLNegotiationPolicy_|TestAccELBListenerPolicy_"

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/elb/... -v -count 1 -parallel 20 -run='TestAccELBSSLNegotiationPolicy_|TestAccELBListenerPolicy_'  -timeout 180m
--- PASS: TestAccELBListenerPolicy_basic (19.67s)
--- PASS: TestAccELBListenerPolicy_disappears (20.03s)
--- PASS: TestAccELBSSLNegotiationPolicy_basic (66.53s)
--- PASS: TestAccELBSSLNegotiationPolicy_update (69.65s)
--- PASS: TestAccELBSSLNegotiationPolicy_disappears (78.85s)
--- PASS: TestAccELBListenerPolicy_update (83.03s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elb	86.537s
...
```

### CODE REVIEW

File: internal/service/elb/listener_policy.go [hunk 1]
```diff
@@ -38,6 +38,11 @@ func ResourceListenerPolicy() *schema.Resource {
 				Optional: true,
 				Elem:     &schema.Schema{Type: schema.TypeString},
 			},
+			"triggers": {
+				Type:     schema.TypeMap,
+				Optional: true,
+				Elem:     &schema.Schema{Type: schema.TypeString},
+			},
```
Comment (jar-b) [inline internal/service/elb/listener_policy.go:45]: Is a `ForceNew` needed here?

Comment (johnsonaj) [reply internal/service/elb/listener_policy.go:45]: not needed here since this resource has and `resourceUpdate` handler. This will just trigger a "update" so the state refreshes

**Review by jar-b — APPROVED** [review]
LGTM 👏 

```console
$ make testacc PKG=elb TESTS="TestAccELBSSLNegotiationPolicy_|TestAccELBListenerPolicy_"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/elb/... -v -count 1 -parallel 20 -run='TestAccELBSSLNegotiationPolicy_|TestAccELBListenerPolicy_'  -timeout 180m
--- PASS: TestAccELBListenerPolicy_basic (20.42s)
--- PASS: TestAccELBSSLNegotiationPolicy_disappears (59.30s)
--- PASS: TestAccELBSSLNegotiationPolicy_basic (68.17s)
--- PASS: TestAccELBListenerPolicy_update (70.69s)
--- PASS: TestAccELBListenerPolicy_disappears (82.16s)
--- PASS: TestAccELBSSLNegotiationPolicy_update (105.42s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/elb        108.901s
```
