### PR TITLE
resource/dms_endpoint: add support for extraConnectionAttributes in create/read ops and handle diffs

### LINKED ISSUE #8000: DMS endpoint s3 target to support extra_connection_attributes
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

DMS has introduced new attributes in s3_settings and api doc will be updated end of this week, it can be passed as either s3_settings or extra_connection_attributes. 

Terraform for s3 target doesn't support extra_connection_attributes, it would be nice to add it so new features on endpoint can be utilized through extra_connection_attributes.

https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_dms_endpoint.go#L283

API which supports new attributes

aws dms create-endpoint --endpoint-identifier s3-target-endpoint --engine-name s3 --endpoint-type target
--s3-settings ‘{“ServiceAccessRoleArn”: “your-service-access-ARN”, “DataFormat”: “parquet”, "parquetVersion":"PARQUET_2_0"}’

aws dms create-endpoint   --extra-connection-attributes "ServiceAccessRoleArn:your-service-access-ARN;bucketName=dms-test-321;bucketFolder=s3test;DataFormat=parquet;parquetVersion=PARQUET_2_0;"

### New or Affected Resource(s)

* aws_dms_endpoint

### Potential Terraform Configuration

```hcl
resource "aws_dms_endpoint" "media_s3_endpoint" {
  endpoint_id  = ""
  endpoint_type = "target"
  extra_connection_attributes = "DataFormat=parquet;parquetVersion=PARQUET_2_0;"
  engine_name = "s3"
  s3_settings = {
    service_access_role_arn = ""
    bucket_name= ""
    bucket_folder = ""
    compression_type= "GZIP"
  }

  tags = ""

}
```

### References

* #0000

### LINKED ISSUE #8009: S3 settings on aws_dms_endpoint conflict with "extra_connection_attributes"
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

v0.11.13

### Affected Resource(s)

* aws_dms_endpoint.s3_settings

### Terraform Configuration Files

```hcl
resource "aws_dms_endpoint" "s3_raw" {
  endpoint_id = "s3-raw"
  engine_name = "s3"
  endpoint_type = "target"
  extra_connection_attributes = "dataFormat=parquet;"
  s3_settings {
    service_access_role_arn = "${aws_iam_role.role.arn}"
    bucket_name = "${var.s3_bucket}"
    bucket_folder = "${var.raw_data_path}/dms"
    compression_type = "GZIP"
  }
}
```
### Expected Behavior

The "extra connection status" in the DMS endpoint should be:

```
bucketFolder=data/raw/dms;bucketName=MY_BUCKET_NAME;compressionType=GZIP;csvDelimiter=,;csvRowDelimiter=\n;dataFormat=parquet;
```

### Actual Behavior

The "extra connection status" in the DMS endpoint is:
```
bucketFolder=data/raw/dms;bucketName=MY_BUCKET_NAME;compressionType=GZIP;csvDelimiter=,;csvRowDelimiter=\n;
```

Notice the lack of `dataFormat=parquet`

### Steps to Reproduce

1. `terraform apply`

### PR DESCRIPTION
**Pull request by anGie44**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #8009 
Closes #8000

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/dms_endpoint: add support for `extra_connection_attributes` on create and read and prevent diffs between the API response and configured value
```

Output from acceptance testing:

```
--- PASS: TestAccAwsDmsEndpoint_Elasticsearch (172.07s)
--- PASS: TestAccAwsDmsEndpoint_Elasticsearch_ErrorRetryDuration (181.10s)
--- PASS: TestAccAwsDmsEndpoint_S3_ExtraConnectionAttributes (192.49s)
--- PASS: TestAccAwsDmsEndpoint_Elasticsearch_ExtraConnectionAttributes (192.98s)
--- PASS: TestAccAwsDmsEndpoint_MongoDb (193.97s)
--- PASS: TestAccAwsDmsEndpoint_Elasticsearch_FullLoadErrorPercentage (202.25s)
--- PASS: TestAccAwsDmsEndpoint_Db2 (222.04s)
--- PASS: TestAccAwsDmsEndpoint_DocDB (233.58s)
--- PASS: TestAccAwsDmsEndpoint_basic (233.69s)
--- PASS: TestAccAwsDmsEndpoint_Kafka_Broker (242.55s)
--- PASS: TestAccAwsDmsEndpoint_DynamoDb (242.66s)
--- PASS: TestAccAwsDmsEndpoint_Kafka_Topic (244.66s)
--- PASS: TestAccAwsDmsEndpoint_S3 (255.30s)
--- PASS: TestAccAwsDmsEndpoint_MongoDb_Update (268.29s)
--- PASS: TestAccAwsDmsEndpoint_Kinesis (276.50s)
```

### CODE REVIEW

File: aws/resource_aws_dms_endpoint.go [hunk 1]
```diff
@@ -396,6 +403,7 @@ func resourceAwsDmsEndpointCreate(d *schema.ResourceData, meta interface{}) erro
 			BucketFolder:            aws.String(d.Get("s3_settings.0.bucket_folder").(string)),
 			BucketName:              aws.String(d.Get("s3_settings.0.bucket_name").(string)),
 			CompressionType:         aws.String(d.Get("s3_settings.0.compression_type").(string)),
+			DatePartitionEnabled:    aws.Bool(d.Get("s3_settings.0.date_partition_enabled").(bool)),
```
Comment (anGie44) [inline aws/resource_aws_dms_endpoint.go:406]: the API returns this value in `extra_connection_attributes` by default so adding it to the schema helps calculating the diff appropriately

**Review by bflad — APPROVED** [review]
Great! 🚀  Could you also check issue #8000 and PRs #5607 / #14620 since they look similar?

Output from acceptance testing in AWS Commercial:

```
--- PASS: TestAccAwsDmsEndpoint_basic (43.30s)
--- PASS: TestAccAwsDmsEndpoint_Db2 (45.39s)
--- PASS: TestAccAwsDmsEndpoint_DocDB (43.68s)
--- PASS: TestAccAwsDmsEndpoint_DynamoDb (53.37s)
--- PASS: TestAccAwsDmsEndpoint_Elasticsearch (41.06s)
--- PASS: TestAccAwsDmsEndpoint_Elasticsearch_ErrorRetryDuration (41.01s)
--- PASS: TestAccAwsDmsEndpoint_Elasticsearch_ExtraConnectionAttributes (47.91s)
--- PASS: TestAccAwsDmsEndpoint_Elasticsearch_FullLoadErrorPercentage (40.98s)
--- PASS: TestAccAwsDmsEndpoint_Kafka_Broker (45.37s)
--- PASS: TestAccAwsDmsEndpoint_Kafka_Topic (44.68s)
--- PASS: TestAccAwsDmsEndpoint_Kinesis (79.14s)
--- PASS: TestAccAwsDmsEndpoint_MongoDb (27.42s)
--- PASS: TestAccAwsDmsEndpoint_MongoDb_Update (51.38s)
--- PASS: TestAccAwsDmsEndpoint_S3 (55.06s)
--- PASS: TestAccAwsDmsEndpoint_S3_ExtraConnectionAttributes (40.85s)
```

Output from acceptance testing in AWS GovCloud (US):

```
--- PASS: TestAccAwsDmsEndpoint_basic (52.91s)
--- PASS: TestAccAwsDmsEndpoint_Db2 (51.46s)
--- PASS: TestAccAwsDmsEndpoint_DocDB (50.24s)
--- PASS: TestAccAwsDmsEndpoint_DynamoDb (58.01s)
--- PASS: TestAccAwsDmsEndpoint_Elasticsearch (46.42s)
--- PASS: TestAccAwsDmsEndpoint_Elasticsearch_ErrorRetryDuration (44.74s)
--- PASS: TestAccAwsDmsEndpoint_Elasticsearch_ExtraConnectionAttributes (47.78s)
--- PASS: TestAccAwsDmsEndpoint_Elasticsearch_FullLoadErrorPercentage (47.42s)
--- PASS: TestAccAwsDmsEndpoint_Kafka_Broker (52.21s)
--- PASS: TestAccAwsDmsEndpoint_Kafka_Topic (51.37s)
--- PASS: TestAccAwsDmsEndpoint_Kinesis (87.21s)
--- PASS: TestAccAwsDmsEndpoint_MongoDb (37.55s)
--- PASS: TestAccAwsDmsEndpoint_MongoDb_Update (55.80s)
--- PASS: TestAccAwsDmsEndpoint_S3 (57.88s)
--- PASS: TestAccAwsDmsEndpoint_S3_ExtraConnectionAttributes (47.20s)
```
