### PR TITLE
r/aws_resourcegroups_resource: fix crash when attempting to parse arn

### LINKED ISSUE #40458: [Bug]: terraform-provider-aws_v5.72.1_x5 plugin crashed for resource group
### Terraform Core Version

v1.7.5

### AWS Provider Version

v5.72.1

### Affected Resource(s)

aws_resource_grp

### Expected Behavior

Applying changes should have tagged lambda function to particular resource groups

### Actual Behavior

╷
│ Error: Plugin did not respond
│ 
│   with module.apps.module.order_transform_carrefour_fr_sqs.aws_resourcegroups_resource.lambda[0],
│   on modules/sfn_lambda/main.tf line 49, in resource "aws_resourcegroups_resource" "lambda":
│   49: resource "aws_resourcegroups_resource" "lambda" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-aws_v5.72.1_x5 plugin:

panic: runtime error: index out of range [1] with length 1

goroutine 95 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/resourcegroups.resourceResourceCreate({0x1af8b688, 0xc0049565d0}, 0xc00495e000, {0x18b88420, 0xc001657a00})
	github.com/hashicorp/terraform-provider-aws/internal/service/resourcegroups/resource.go:66 +0x785
github.com/hashicorp/terraform-provider-aws/internal/provider.New.(*wrappedResource).Create.interceptedHandler[...].func9(0xc00495e000?, {0x18b88420?, 0xc001657a00})
	github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:113 +0x283
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1af8b688?, {0x1af8b688?, 0xc004941a10?}, 0xd?, {0x18b88420?, 0xc001657a00?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:801 +0x7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc002ef1180, {0x1af8b688, 0xc004941a10}, 0xc00465d110, 0xc004641e00, {0x18b88420, 0xc001657a00})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:937 +0xa69
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc001686240, {0x1af8b688?, 0xc004941950?}, 0xc0049038b0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/grpc_provider.go:1153 +0xd5c
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0xc001cbbd50, {0x1af8b688?, 0xc004941680?}, 0xc0049038b0)
	github.com/hashicorp/terraform-plugin-mux@v0.16.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc002309ea0, {0x1af8b688?, 0xc004940ea0?}, 0xc002063ea0)
	github.com/hashicorp/terraform-plugin-go@v0.24.0/tfprotov5/tf5server/server.go:865 +0x3bc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x189cdba0, 0xc002309ea0}, {0x1af8b688, 0xc004940ea0}, 0xc004641b80, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.24.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:545 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0013a0200, {0x1af8b688, 0xc004940e10}, {0x1b005b00, 0xc0018d04e0}, 0xc0049459e0, 0xc001a0cb10, 0x2596f538, 0x0)
	google.golang.org/grpc@v1.66.2/server.go:1394 +0xe2b
google.golang.org/grpc.(*Server).handleStream(0xc0013a0200, {0x1b005b00, 0xc0018d04e0}, 0xc0049459e0)
	google.golang.org/grpc@v1.66.2/server.go:1805 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.66.2/server.go:1029 +0x7f
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 55
	google.golang.org/grpc@v1.66.2/server.go:1040 +0x125

Error: The terraform-provider-aws_v5.72.1_x5 plugin crashed!

### Relevant Error/Panic Output Snippet

_No response_

### Terraform Configuration Files

resource "aws_resourcegroups_resource" "lambda" {
  count     = var.partner_slug != "" ? 1 : 0
  group_arn    = "aws_resourcegroups_group.${var.partner_slug}-${var.env_name}-group.arn"
  resource_arn = module.lambda.lambda_function_arn
}

### Steps to Reproduce

- Add this resource group resource under lambda modules - main.tf
- Make sure to add relevant partner_slug or env_name in variables
- Set variables with proper values in partner specific lambdas functions to

### Debug Output

_No response_

### Panic Output

╷
│ Error: Plugin did not respond
│ 
│   with module.apps.module.order_transform_carrefour_fr_sqs.aws_resourcegroups_resource.lambda[0],
│   on modules/sfn_lambda/main.tf line 49, in resource "aws_resourcegroups_resource" "lambda":
│   49: resource "aws_resourcegroups_resource" "lambda" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-aws_v5.72.1_x5 plugin:

panic: runtime error: index out of range [1] with length 1

goroutine 95 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/resourcegroups.resourceResourceCreate({0x1af8b688, 0xc0049565d0}, 0xc00495e000, {0x18b88420, 0xc001657a00})
	github.com/hashicorp/terraform-provider-aws/internal/service/resourcegroups/resource.go:66 +0x785
github.com/hashicorp/terraform-provider-aws/internal/provider.New.(*wrappedResource).Create.interceptedHandler[...].func9(0xc00495e000?, {0x18b88420?, 0xc001657a00})
	github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:113 +0x283
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1af8b688?, {0x1af8b688?, 0xc004941a10?}, 0xd?, {0x18b88420?, 0xc001657a00?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:801 +0x7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc002ef1180, {0x1af8b688, 0xc004941a10}, 0xc00465d110, 0xc004641e00, {0x18b88420, 0xc001657a00})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:937 +0xa69
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc001686240, {0x1af8b688?, 0xc004941950?}, 0xc0049038b0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/grpc_provider.go:1153 +0xd5c
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0xc001cbbd50, {0x1af8b688?, 0xc004941680?}, 0xc0049038b0)
	github.com/hashicorp/terraform-plugin-mux@v0.16.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc002309ea0, {0x1af8b688?, 0xc004940ea0?}, 0xc002063ea0)
	github.com/hashicorp/terraform-plugin-go@v0.24.0/tfprotov5/tf5server/server.go:865 +0x3bc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x189cdba0, 0xc002309ea0}, {0x1af8b688, 0xc004940ea0}, 0xc004641b80, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.24.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:545 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0013a0200, {0x1af8b688, 0xc004940e10}, {0x1b005b00, 0xc0018d04e0}, 0xc0049459e0, 0xc001a0cb10, 0x2596f538, 0x0)
	google.golang.org/grpc@v1.66.2/server.go:1394 +0xe2b
google.golang.org/grpc.(*Server).handleStream(0xc0013a0200, {0x1b005b00, 0xc0018d04e0}, 0xc0049459e0)
	google.golang.org/grpc@v1.66.2/server.go:1805 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.66.2/server.go:1029 +0x7f
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 55
	google.golang.org/grpc@v1.66.2/server.go:1040 +0x125

Error: The terraform-provider-aws_v5.72.1_x5 plugin crashed!

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

No

### LINKED ISSUE #40504: [Bug]: Unable to add resource group using resource ARN
### Terraform Core Version

1.10.0

### AWS Provider Version

5.80.0

### Affected Resource(s)

aws_resourcegroups_resource

### Expected Behavior

Should add resource to the resource group.

### Actual Behavior

Crash with following error

```
Stack trace from the terraform-provider-aws_v5.80.0_x5 plugin:

panic: runtime error: index out of range [1] with length 1

goroutine 90 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/resourcegroups.resourceResourceCreate({0x1bf4df28, 0xc0043964b0}, 0xc00438c480, {0x19a134a0, 0xc00183a200})
github.com/hashicorp/terraform-provider-aws/internal/service/resourcegroups/resource.go:66 +0x785
github.com/hashicorp/terraform-provider-aws/internal/provider.New.(*wrappedResource).Create.interceptedHandler[...].func9(0xc00438c480?, {0x19a134a0?, 0xc00183a200})
github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:113 +0x283
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1bf4df28?, {0x1bf4df28?, 0xc0043878f0?}, 0xd?, {0x19a134a0?, 0xc00183a200?})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.35.0/helper/schema/resource.go:801 +0x7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc001588a80, {0x1bf4df28, 0xc0043878f0}, 0xc0040cb520, 0xc00438c300, {0x19a134a0, 0xc00183a200})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.35.0/helper/schema/resource.go:937 +0xa69
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc002d3e438, {0x1bf4df28?, 0xc004387830?}, 0xc0040f7180)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.35.0/helper/schema/grpc_provider.go:1155 +0xd5c
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0xc001824b00, {0x1bf4df28?, 0xc004387560?}, 0xc0040f7180)
github.com/hashicorp/terraform-plugin-mux@v0.17.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc001ae6000, {0x1bf4df28?, 0xc004386ba0?}, 0xc000877650)
github.com/hashicorp/terraform-plugin-go@v0.25.0/tfprotov5/tf5server/server.go:865 +0x3bc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x198a2340, 0xc001ae6000}, {0x1bf4df28, 0xc004386ba0}, 0xc00408da80, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.25.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:611 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002c6a00, {0x1bf4df28, 0xc004386b10}, {0x1bfd00a0, 0xc002ebe1a0}, 0xc0043886c0, 0xc002ea2cc0, 0x27050dd8, 0x0)
google.golang.org/grpc@v1.68.0/server.go:1394 +0xe2b
google.golang.org/grpc.(*Server).handleStream(0xc0002c6a00, {0x1bfd00a0, 0xc002ebe1a0}, 0xc0043886c0)
google.golang.org/grpc@v1.68.0/server.go:1805 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
google.golang.org/grpc@v1.68.0/server.go:1029 +0x7f
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 75
google.golang.org/grpc@v1.68.0/server.go:1040 +0x125

Error: The terraform-provider-aws_v5.80.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Relevant Error/Panic Output Snippet

_No response_

### Terraform Configuration Files

resource "aws_resourcegroups_group" "test_1" {
  name = "resources-group-1"

  resource_query {
    query = jsonencode({
      ResourceTypeFilters = [
        "AWS::ApiGatewayV2::Api",
        "AWS::CloudFront::Distribution",
        "AWS::S3::Bucket",
        "AWS::CodeBuild::Project"
      ]
      TagFilters = [
        {
          Key    = "Project"
          Values = "value"
        },
        {
          Key    = "Environment"
          Values = "value"
        }
      ]
    })
  }
}

resource "aws_secretsmanager_secret" "test_1" {
  name = "secret-d"
}

 resource "aws_resourcegroups_resource" "dev_secret" {
   group_arn    = aws_resourcegroups_group.test_1.arn
   resource_arn = aws_secretsmanager_secret.test_1.arn
}

### Steps to Reproduce

Run `terraform apply`

### Debug Output

_No response_

### Panic Output

Stack trace from the terraform-provider-aws_v5.80.0_x5 plugin:

panic: runtime error: index out of range [1] with length 1

goroutine 90 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/resourcegroups.resourceResourceCreate({0x1bf4df28, 0xc0043964b0}, 0xc00438c480, {0x19a134a0, 0xc00183a200})
github.com/hashicorp/terraform-provider-aws/internal/service/resourcegroups/resource.go:66 +0x785
github.com/hashicorp/terraform-provider-aws/internal/provider.New.(*wrappedResource).Create.interceptedHandler[...].func9(0xc00438c480?, {0x19a134a0?, 0xc00183a200})
github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:113 +0x283
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1bf4df28?, {0x1bf4df28?, 0xc0043878f0?}, 0xd?, {0x19a134a0?, 0xc00183a200?})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.35.0/helper/schema/resource.go:801 +0x7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc001588a80, {0x1bf4df28, 0xc0043878f0}, 0xc0040cb520, 0xc00438c300, {0x19a134a0, 0xc00183a200})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.35.0/helper/schema/resource.go:937 +0xa69
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc002d3e438, {0x1bf4df28?, 0xc004387830?}, 0xc0040f7180)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.35.0/helper/schema/grpc_provider.go:1155 +0xd5c
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0xc001824b00, {0x1bf4df28?, 0xc004387560?}, 0xc0040f7180)
github.com/hashicorp/terraform-plugin-mux@v0.17.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc001ae6000, {0x1bf4df28?, 0xc004386ba0?}, 0xc000877650)
github.com/hashicorp/terraform-plugin-go@v0.25.0/tfprotov5/tf5server/server.go:865 +0x3bc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x198a2340, 0xc001ae6000}, {0x1bf4df28, 0xc004386ba0}, 0xc00408da80, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.25.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:611 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002c6a00, {0x1bf4df28, 0xc004386b10}, {0x1bfd00a0, 0xc002ebe1a0}, 0xc0043886c0, 0xc002ea2cc0, 0x27050dd8, 0x0)
google.golang.org/grpc@v1.68.0/server.go:1394 +0xe2b
google.golang.org/grpc.(*Server).handleStream(0xc0002c6a00, {0x1bfd00a0, 0xc002ebe1a0}, 0xc0043886c0)
google.golang.org/grpc@v1.68.0/server.go:1805 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
google.golang.org/grpc@v1.68.0/server.go:1029 +0x7f
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 75
google.golang.org/grpc@v1.68.0/server.go:1040 +0x125

Error: The terraform-provider-aws_v5.80.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by jar-b**
### Description

Previously the `group_arn` and `resource_arn` values were assumed to be ARNs in a format which could always be split by a `/` into at least two parts. The provider did no validation of these inputs prior to attempting to split the value, causing `index out of range` crashes when values were provided that did not match these assumptions.

Instead of attempting to split ARNs of varying formatting to construct the `id` attribute, `id` will now be composed of a comma-delimited string combining `group_arn` and `resource_arn` in their entirety. This removes the logic and assumptions around splitting the ARN and should prevent future crashes regardless of the format provided. The more complete content of the `id` attribute will also enable supporting import for this resource (also added as part of this PR).

### Relations

Closes #40504
Closes #40458

### Output from Acceptance Testing

```console
% make testacc PKG=resourcegroups TESTS=TestAccResourceGroupsResource_
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.3 test ./internal/service/resourcegroups/... -v -count 1 -parallel 20 -run='TestAccResourceGroupsResource_'  -timeout 360m
2024/12/16 11:04:35 Initializing Terraform AWS Provider...

--- PASS: TestAccResourceGroupsResource_basic (21.88s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/resourcegroups     28.172s
```

### CODE REVIEW

File: internal/service/resourcegroups/resource.go [hunk 1]
```diff
@@ -63,7 +71,11 @@ func resourceResourceCreate(ctx context.Context, d *schema.ResourceData, meta in
 
 	groupARN := d.Get("group_arn").(string)
 	resourceARN := d.Get(names.AttrResourceARN).(string)
-	id := strings.Join([]string{strings.Split(strings.ToLower(groupARN), "/")[1], strings.Split(resourceARN, "/")[1]}, "_")
+	id, err := flex.FlattenResourceId([]string{groupARN, resourceARN}, resourceIDPartCount, false)
```
Comment (ewbankkit) [inline internal/service/resourcegroups/resource.go:74]: Will this affect existing Terraform resources?
Should add an acceptance test creating in the previous version and refreshing with the updated code just to make sure.

Comment (jar-b) [reply internal/service/resourcegroups/resource.go:74]: Only if they were consuming the `id` output somewhere else in their configuration. In practice I'm not sure how useful this would have been as this was previously a `_` delimited string of group name and some portion of the resource section of the associated resource ARN.

Comment (ewbankkit) [reply internal/service/resourcegroups/resource.go:74]: I guess add a CHANGELOG entry calling out the `id` format change also?

**Comment by jar-b** [comment]
Acceptance tests after adding a state upgrader and including a new case for upgrading beyond `v5.81.0` (the last with the previous `id` format).

```console
% make testacc PKG=resourcegroups TESTS=TestAccResourceGroupsResource_
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.3 test ./internal/service/resourcegroups/... -v -count 1 -parallel 20 -run='TestAccResourceGroupsResource_'  -timeout 360m
2024/12/17 16:33:36 Initializing Terraform AWS Provider...

--- PASS: TestAccResourceGroupsResource_basic (22.66s)
--- PASS: TestAccResourceGroupsResource_v5_82_0_upgrade (48.45s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/resourcegroups     54.879s
```

File: internal/service/resourcegroups/resource.go (hunk 1 above)
Comment (jar-b) [reply internal/service/resourcegroups/resource.go:83]: Added test case and additional changelog entry.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccResourceGroupsResource_' PKG=resourcegroups
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.3 test ./internal/service/resourcegroups/... -v -count 1 -parallel 20  -run=TestAccResourceGroupsResource_ -timeout 360m
2024/12/18 10:10:41 Initializing Terraform AWS Provider...
=== RUN   TestAccResourceGroupsResource_basic
=== PAUSE TestAccResourceGroupsResource_basic
=== RUN   TestAccResourceGroupsResource_v5_82_0_upgrade
=== PAUSE TestAccResourceGroupsResource_v5_82_0_upgrade
=== CONT  TestAccResourceGroupsResource_basic
=== CONT  TestAccResourceGroupsResource_v5_82_0_upgrade
--- PASS: TestAccResourceGroupsResource_basic (26.51s)
--- PASS: TestAccResourceGroupsResource_v5_82_0_upgrade (54.69s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/resourcegroups	60.585s
```
