### PR TITLE
service/s3: Add d.IsNewResource checks and standardize retry logic

### LINKED ISSUE #10587: Race condition renaming public access blocks
If you rename a `aws_s3_bucket_public_access_block` it will probably get an error on apply. Running the command multiple times will resolve it as presumably would doing a `terraform state mv` first if you remembered.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.12
+ provider.aws v2.33.0
+ provider.external v1.2.0
+ provider.null v2.1.2

### Affected Resource(s)

* aws_s3_bucket_public_access_block

### Terraform Configuration Files

```hcl
resource "aws_s3_bucket_public_access_block" "deployment" {
…
}
```

### Expected Behavior

* The updated configuration would be deployed

### Actual Behavior

 ```
Error: Provider produced inconsistent result after apply

When applying changes to aws_s3_bucket_public_access_block.uploads, provider
"aws" produced an unexpected new value for was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

or

```
Error: error creating public access block policy for S3 bucket (…): OperationAborted: A conflicting conditional operation is currently in progress against this resource. Please try again.
	status code: 409, request id: … host id: …
```

### Steps to Reproduce

1. `terraform apply`

### PR DESCRIPTION
**Pull request by bflad**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #10587
Reference: https://github.com/hashicorp/terraform-provider-aws/issues/16796

Output from acceptance testing:

```
--- PASS: TestAccAWSS3BucketAnalyticsConfiguration_basic (38.97s)
--- PASS: TestAccAWSS3BucketAnalyticsConfiguration_removed (56.16s)
--- PASS: TestAccAWSS3BucketAnalyticsConfiguration_updateBasic (87.68s)
--- PASS: TestAccAWSS3BucketAnalyticsConfiguration_WithFilter_Empty (12.16s)
--- PASS: TestAccAWSS3BucketAnalyticsConfiguration_WithFilter_MultipleTags (60.16s)
--- PASS: TestAccAWSS3BucketAnalyticsConfiguration_WithFilter_Prefix (60.97s)
--- PASS: TestAccAWSS3BucketAnalyticsConfiguration_WithFilter_PrefixAndTags (60.97s)
--- PASS: TestAccAWSS3BucketAnalyticsConfiguration_WithFilter_Remove (61.00s)
--- PASS: TestAccAWSS3BucketAnalyticsConfiguration_WithFilter_SingleTag (60.97s)
--- PASS: TestAccAWSS3BucketAnalyticsConfiguration_WithStorageClassAnalysis_Default (39.98s)
--- PASS: TestAccAWSS3BucketAnalyticsConfiguration_WithStorageClassAnalysis_Empty (12.14s)
--- PASS: TestAccAWSS3BucketAnalyticsConfiguration_WithStorageClassAnalysis_Full (39.60s)

--- PASS: TestAccAWSS3BucketInventory_basic (26.27s)
--- PASS: TestAccAWSS3BucketInventory_encryptWithSSES3 (26.34s)
--- PASS: TestAccAWSS3BucketInventory_encryptWithSSEKMS (26.45s)

--- PASS: TestAccAWSS3BucketMetric_basic (26.21s)
--- PASS: TestAccAWSS3BucketMetric_WithEmptyFilter (2.25s)
--- PASS: TestAccAWSS3BucketMetric_WithFilterMultipleTags (46.71s)
--- PASS: TestAccAWSS3BucketMetric_WithFilterPrefix (45.51s)
--- PASS: TestAccAWSS3BucketMetric_WithFilterPrefixAndMultipleTags (46.55s)
--- PASS: TestAccAWSS3BucketMetric_WithFilterPrefixAndSingleTag (45.88s)
--- PASS: TestAccAWSS3BucketMetric_WithFilterSingleTag (46.49s)

--- PASS: TestAccAWSS3BucketNotification_LambdaFunction (45.26s)
--- PASS: TestAccAWSS3BucketNotification_LambdaFunction_LambdaFunctionArn_Alias (40.24s)
--- PASS: TestAccAWSS3BucketNotification_Queue (27.96s)
--- PASS: TestAccAWSS3BucketNotification_Topic (28.53s)
--- PASS: TestAccAWSS3BucketNotification_Topic_Multiple (29.23s)
--- PASS: TestAccAWSS3BucketNotification_update (49.26s)

--- PASS: TestAccAWSS3BucketPublicAccessBlock_basic (29.52s)
--- PASS: TestAccAWSS3BucketPublicAccessBlock_BlockPublicAcls (68.84s)
--- PASS: TestAccAWSS3BucketPublicAccessBlock_BlockPublicPolicy (68.21s)
--- PASS: TestAccAWSS3BucketPublicAccessBlock_disappears (26.48s)
--- PASS: TestAccAWSS3BucketPublicAccessBlock_disappears_Bucket (18.16s)
--- PASS: TestAccAWSS3BucketPublicAccessBlock_IgnorePublicAcls (68.18s)
--- PASS: TestAccAWSS3BucketPublicAccessBlock_RestrictPublicBuckets (68.83s)
```

### CODE REVIEW

File: aws/resource_aws_s3_bucket_analytics_configuration.go [hunk 1]
```diff
@@ -147,19 +148,23 @@ func resourceAwsS3BucketAnalyticsConfigurationPut(d *schema.ResourceData, meta i
 
 	err := resource.Retry(1*time.Minute, func() *resource.RetryError {
 		_, err := s3conn.PutBucketAnalyticsConfiguration(input)
+
+		if tfawserr.ErrCodeEquals(err, s3.ErrCodeNoSuchBucket) {
```
Comment (anGie44) [inline aws/resource_aws_s3_bucket_analytics_configuration.go:152]: open q: why move this if-logic outside of the `if err != nil` check below? just curious b/c i've caught myself writing these types of checks w/in an `if err != nil` especially in some Delete CRUD ops of resources and i think my rationale at the time was that it didn't seem to make sense to pass the err around if it's `nil` but maybe that goes against our usual patterns...

File: aws/resource_aws_s3_bucket_metric.go [hunk 2]
```diff
@@ -81,21 +84,26 @@ func resourceAwsS3BucketMetricPut(d *schema.ResourceData, meta interface{}) erro
...
 	})
-	if isResourceTimeoutError(err) {
+
+	if tfresource.TimedOut(err) {
 		_, err = conn.PutBucketMetricsConfiguration(input)
 	}
+
 	if err != nil {
-		return fmt.Errorf("Error putting S3 metric configuration: %s", err)
+		return fmt.Errorf("error putting S3 Bucket Metric Configuration: %w", err)
```
Comment (anGie44) [inline aws/resource_aws_s3_bucket_metric.go:106]: Nit: i noticed below `Metrics` is used instead of `Metric` so for consistency maybe use the plural here as well..unless there's an intended diff?

**Review by anGie44 — APPROVED** [review]
Looks great, just left a minor note and open q 👍

File: aws/resource_aws_s3_bucket_analytics_configuration.go (hunk 1 above)
Comment (bflad) [reply aws/resource_aws_s3_bucket_analytics_configuration.go:152]: Great question! It's something I picked up from https://medium.com/@matryer/line-of-sight-in-code-186dd7cdea88

In this case since it is the unhappy path being nested under the `if err != nil`, it is probably _okay_ to be nested if we wanted. Prior to these AWS SDK Go error checking helpers it used to be that this logic _had_ to be nested (or duplicate the `err != nil` check) for the type assertions, but now that this detail is tucked away, it this allows for either style. 👍

File: aws/resource_aws_s3_bucket_metric.go (hunk 2 above)
Comment (bflad) [reply aws/resource_aws_s3_bucket_metric.go:106]: Great catch. I will make them consistent to `Metrics` in a followup commit here. 👍  One day we'll create and use a Go type that will centralize all this information for error reporting, etc. 😍 

```go
&resource{
  FriendlyName: "S3 Bucket Metrics Configuration",
  // ...
}
```

File: aws/resource_aws_s3_bucket_analytics_configuration.go (hunk 1 above)
Comment (anGie44) [reply aws/resource_aws_s3_bucket_analytics_configuration.go:152]: Ohh very cool, thanks! def sounds familiar coming from ruby land (and Sandi Metz's principles)
