### PR TITLE
resource/aws_elasticache_replication_group: Deletes parameter group created when replication group added to global datastore

### LINKED ISSUE #19255: Elasticache global replication destroy does not clean parameter group
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

Terraform Version 0.13.1
Provider Version 3.37.0

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_elasticache_global_replication_group" "global_rep" {
  count = var.secondary_region != "" ? 1 : 0
  global_replication_group_id_suffix = "${var.cluster_name}-${var.product_name}-gr"
  primary_replication_group_id       = aws_elasticache_replication_group.primary.id
}
```

### Debug Output

On Parameter Group Section, in description:
Created by ElastiCache to be used by global cluster \<global-rep\>

### Expected Behavior

When creating primary replication for global data store, 
**parameter_group_name = default.redis5.0.cluster.on**
terraform creates a separate parameter group in the name of **global-datastore-\<replication-id\>_XXXX_**, but when doing destroy of global replication, it does not clean up.
### Actual Behavior

Clean the parameter group created by global replication module.
### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`

### References

* #0000

### PR DESCRIPTION
**Pull request by gdavison**
When a replication group is added to a global datastore, the API creates a custom duplicate parameter group. Delete it when deleting the replication group.

Closes #19255

Output from acceptance testing:

```
$ make testacc PKG=elasticache TESTS='TestAccElastiCacheReplicationGroup|TestAccElastiCacheGlobalReplicationGroup|TestAccElastiCacheParameterGroup'

--- PASS: TestAccElastiCacheReplicationGroupDataSource_nonExistent (31.14s)
--- PASS: TestAccElastiCacheReplicationGroup_Validation_noNodeType (51.85s)
--- PASS: TestAccElastiCacheReplicationGroup_deprecatedAvailabilityZones_multiAzInVPC (901.48s)
--- PASS: TestAccElastiCacheReplicationGroup_finalSnapshot (935.50s)
--- PASS: TestAccElastiCacheGlobalReplicationGroup_basic (989.63s)
--- PASS: TestAccElastiCacheReplicationGroup_tags (1025.51s)
--- PASS: TestAccElastiCacheReplicationGroup_dataTiering (1053.20s)
--- PASS: TestAccElastiCacheReplicationGroup_Validation_globalReplicationGroupIdAndNodeType (1178.33s)
--- PASS: TestAccElastiCacheReplicationGroup_tagWithOtherModification (1213.60s)
--- PASS: TestAccElastiCacheReplicationGroup_multiAzInVPC (1217.32s)
--- PASS: TestAccElastiCacheReplicationGroup_GlobalReplicationGroupIDClusterModeValidation_numNodeGroupsOnSecondary (1407.53s)
--- PASS: TestAccElastiCacheReplicationGroup_updateUserGroups (1434.33s)
--- PASS: TestAccElastiCacheReplicationGroup_autoMinorVersionUpgrade (1496.72s)
--- PASS: TestAccElastiCacheReplicationGroup_updateMaintenanceWindow (1514.15s)
--- PASS: TestAccElastiCacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_ClusterMode_Disabled (1603.63s)
--- PASS: TestAccElastiCacheReplicationGroup_updateDescription (910.08s)
--- PASS: TestAccElastiCacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_ClusterMode_Enabled (1888.37s)
--- PASS: TestAccElastiCacheReplicationGroup_disappears (866.66s)
--- PASS: TestAccElastiCacheReplicationGroup_multiAzNotInVPC (1003.98s)
--- PASS: TestAccElastiCacheReplicationGroup_deprecatedAvailabilityZones_multiAzNotInVPC (2151.06s)
--- PASS: TestAccElastiCacheReplicationGroup_updateNodeSize (2336.83s)
--- PASS: TestAccElastiCacheReplicationGroup_vpc (905.48s)
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappearsRemoveMemberCluster_scaleDown (1560.93s)
--- PASS: TestAccElastiCacheReplicationGroup_uppercase (906.53s)
--- PASS: TestAccElastiCacheParameterGroup_RemoveReservedMemoryParameter_remainingParameters (19.57s)
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappearsRemoveMemberCluster_atTargetSize (1489.85s)
--- PASS: TestAccElastiCacheReplicationGroup_depecatedAvailabilityZones_vpc (1462.19s)
--- PASS: TestAccElastiCacheReplicationGroup_multiAzNotInVPC_repeated (1750.54s)
--- PASS: TestAccElastiCacheReplicationGroup_updateAuthToken (1158.95s)
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappears_noChange (1466.86s)
--- PASS: TestAccElastiCacheReplicationGroup_basic_v5 (1053.45s)
--- PASS: TestAccElastiCacheReplicationGroup_basic (760.84s)
--- PASS: TestAccElastiCacheReplicationGroup_updateParameterGroup (1024.47s)
--- PASS: TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_disappears (3128.98s)
--- PASS: TestAccElastiCacheReplicationGroupDataSource_Engine_Redis_LogDeliveryConfigurations (827.34s)
--- PASS: TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_basic (3182.80s)
--- PASS: TestAccElastiCacheParameterGroup_tags (28.79s)
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappears_addMemberCluster (2046.08s)
--- PASS: TestAccElastiCacheReplicationGroupDataSource_multiAZ (759.13s)
--- PASS: TestAccElastiCacheParameterGroup_description (11.97s)
--- PASS: TestAccElastiCacheReplicationGroup_ValidationMultiAz_noAutomaticFailover (2.01s)
--- PASS: TestAccElastiCacheParameterGroup_uppercaseName (11.91s)
--- PASS: TestAccElastiCacheParameterGroup_updateReservedMemoryParameter (18.52s)
--- PASS: TestAccElastiCacheParameterGroup_switchReservedMemoryParameter (19.83s)
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClusters_multiAZEnabled (1674.92s)
--- PASS: TestAccElastiCacheParameterGroup_removeAllParameters (16.61s)
--- PASS: TestAccElastiCacheParameterGroup_addParameter (20.36s)
--- PASS: TestAccElastiCacheParameterGroup_RemoveReservedMemoryParameter_allParameters (18.75s)
--- PASS: TestAccElastiCacheParameterGroup_basic (10.98s)
--- PASS: TestAccElastiCacheReplicationGroup_enableAtRestEncryption (785.74s)
--- PASS: TestAccElastiCacheReplicationGroupDataSource_clusterMode (999.47s)
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClustersFailover_autoFailoverEnabled (1630.46s)
--- PASS: TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_full (3821.54s)
--- PASS: TestAccElastiCacheReplicationGroup_clusteringAndCacheNodesCausesError (2.03s)
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClustersFailover_autoFailoverDisabled (1513.00s)
--- PASS: TestAccElastiCacheReplicationGroup_enableAuthTokenTransitEncryption (844.52s)
--- PASS: TestAccElastiCacheReplicationGroup_GlobalReplicationGroupIDClusterMode_basic (3975.52s)
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClusters_basic (1693.61s)
--- PASS: TestAccElastiCacheReplicationGroup_ClusterMode_nonClusteredParameterGroup (992.34s)
--- PASS: TestAccElastiCacheReplicationGroup_useCMKKMSKeyID (1498.40s)
--- PASS: TestAccElastiCacheGlobalReplicationGroup_clusterMode (1140.58s)
--- PASS: TestAccElastiCacheReplicationGroupDataSource_basic (1689.05s)
--- PASS: TestAccElastiCacheReplicationGroup_ClusterMode_singleNode (900.63s)
--- PASS: TestAccElastiCacheReplicationGroup_ClusterMode_updateReplicasPerNodeGroup (1906.23s)
--- PASS: TestAccElastiCacheReplicationGroup_enableSnapshotting (1080.11s)
--- PASS: TestAccElastiCacheGlobalReplicationGroup_disappears (1241.88s)
--- PASS: TestAccElastiCacheReplicationGroup_ClusterMode_basic (1813.28s)
--- PASS: TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroupsAndReplicasPerNodeGroup_scaleUp (2593.75s)
--- PASS: TestAccElastiCacheGlobalReplicationGroup_description (1387.54s)
--- PASS: TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroupsAndReplicasPerNodeGroup_scaleDown (2905.88s)
--- PASS: TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroups_scaleDown (2581.84s)
--- PASS: TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroups_scaleUp (2540.88s)
--- PASS: TestAccElastiCacheReplicationGroup_EngineVersion_update (4907.81s)
--- PASS: TestAccElastiCacheGlobalReplicationGroup_multipleSecondaries (3755.36s)
--- PASS: TestAccElastiCacheGlobalReplicationGroup_ReplaceSecondary_differentRegion (3899.34s)
```

### CODE REVIEW

**Comment by gdavison** [comment]
Linting failure is for files out of scope of this PR

File: internal/service/elasticache/find.go [hunk 1]
```diff
@@ -223,3 +223,33 @@ func FindUserGroupByID(conn *elasticache.ElastiCache, groupID string) (*elastica
...
+		return nil, &resource.NotFoundError{
+			LastError:   err,
+			LastRequest: input,
+		}
+	}
+	if err != nil {
+		return nil, err
+	}
+
+	switch len(out.CacheParameterGroups) {
```
Comment (ewbankkit) [inline internal/service/elasticache/find.go:243]:
```suggestion
	switch n := len(out.CacheParameterGroups); n {
```

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccElastiCacheReplicationGroup_basic\|TestAccElastiCacheParameterGroup_basic' PKG=elasticache ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/elasticache/... -v -count 1 -parallel 2  -run=TestAccElastiCacheReplicationGroup_basic\|TestAccElastiCacheParameterGroup_basic -timeout 180m
=== RUN   TestAccElastiCacheParameterGroup_basic
=== PAUSE TestAccElastiCacheParameterGroup_basic
=== RUN   TestAccElastiCacheReplicationGroup_basic
=== PAUSE TestAccElastiCacheReplicationGroup_basic
=== RUN   TestAccElastiCacheReplicationGroup_basic_v5
=== PAUSE TestAccElastiCacheReplicationGroup_basic_v5
=== CONT  TestAccElastiCacheParameterGroup_basic
=== CONT  TestAccElastiCacheReplicationGroup_basic_v5
--- PASS: TestAccElastiCacheParameterGroup_basic (22.70s)
=== CONT  TestAccElastiCacheReplicationGroup_basic
--- PASS: TestAccElastiCacheReplicationGroup_basic_v5 (710.17s)
--- PASS: TestAccElastiCacheReplicationGroup_basic (707.15s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elasticache	735.961s
```
